### ISSUE TITLE
Visual Studio 2015 error

### ISSUE THREAD

**Issue by varghesep** [jspm/jspm-cli#1001]
I ran **jspm init** in an **asp.net** project folder. I get a success message in the command line, but when I turn to **Visual Studio 2015**, I get the following errors in the **output** windows of the Visual Studio.

*TF10122: The path '$/$.array-methods.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.iter-detect.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.species.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.wks.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.for-of.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.uid.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.task.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.def.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.keyof.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.unscope.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.throws.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.collection.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.string-pad.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.for-of.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.set-proto.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.partial.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.enum-keys.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.enum-keys.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$for.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.species.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.iter-define.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.replacer.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.def.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.collection-to-json.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.collection.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.array-methods.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.array-includes.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$for.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.dom-create.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.assign.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.string-repeat.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.redef.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.own-keys.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.unscope.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.assert.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.string-pad.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.same.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.collection-strong.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.iter.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.unscope.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.collection-weak.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.fw.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.invoke.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.array-includes.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.assign.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.replacer.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.own-keys.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.get-names.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.unscope.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.string-at.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.assert.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.fw.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.redef.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.iter-call.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.iter.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.iter-define.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.collection.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.invoke.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.fw.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.partial.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.collection-strong.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.shared.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.keyof.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.mix.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$for.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.redef.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.throws.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.collection-weak.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.same.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.get-names.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.mix.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.fw.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.dom-create.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.def.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.string-repeat.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.cof.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.ctx.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.def.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.iter-call.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.cof.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.ctx.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.task.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.collection-to-json.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.iter-detect.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.string-at.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.shared.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.redef.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.collection.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$for.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.set-proto.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.uid.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.
TF10122: The path '$/$.wks.js' contains a '$' at the beginning of a path component. Remove the '$' and try again.*

**Comment by guybedford** [comment]
Did you manage to resolve your issue here?

**Comment by varghesep** [comment]
This keeps happening. These are generated by the **JavaScript Language Service** in the output folder. I fear this is causing the VS 2015 to respond slow, and sometimes hang.

**Comment by smastous** [comment]
I think you are actually getting smoked by tfs here, hence the tf10122 error.  

[this issue](https://connect.microsoft.com/VisualStudio/feedback/details/763666/tf10122-tfs-not-allowing-files-which-start-with-a-to-be-added) pretty much sums up your problem.

We ran into lots of similarly awful things with tfs and switched as an organization to github enterprise.  This really has nothing to do with jspm and is related to Microsoft using $ in their source control paths.

**Comment by varghesep** [comment]
Thank you. VS 2015 also has performance problem for which I opened a [ticket](https://github.com/aspnet/Mvc/issues/2997).
