### ISSUE TITLE
404 ...foo.js.map not found

### ISSUE THREAD

**Issue by danmartinez101** [jspm/jspm-cli#1003]
Running jspm@beta with an app with two files:
1(main.js) import './test';
2(test.js) console.log('here');

<img width="734" alt="screen shot 2015-08-09 at 11 15 09 am" src="https://cloud.githubusercontent.com/assets/2669819/9155528/951c70da-3e88-11e5-8fbc-4193e0cd402c.png">

I don't notice this in Chrome, and everything else works fine, but it might be confusing for new adopters of jspm.

**Comment by guybedford** [comment]
Which browser are you getting this in?

**Comment by danmartinez101** [comment]
Sorry, that is in safari. 
I think it might be coming from browser.js

**Comment by guybedford** [comment]
Yes, it seems it is due to this line in Babel:

```javascript
var mapFileCommentRx =
  // //# sourceMappingURL=foo.js.map                       
  /(?:\/\/[@#][ \t]+sourceMappingURL=([^\s'"]+?)[ \t]*$)|(?:\/\*[@#][ \t]+sourceMappingURL=([^\*]+?)[ \t]*(?:\*\/){1}[ \t]*$)/mg
```

Which is being detected not as a regex but as a sourceURL comment in Safari.

It's a Babel thing / Safari bug. It may be worth mentioning on Babel's issue queue if they don't already know about it.
