### ISSUE TITLE
Loading CSS from packages.

### ISSUE THREAD

**Issue by richburdon** [jspm/jspm-cli#1004]
It's somewhat cumbersome to load CSS from the package folders -- and prone to breaking when configuration changes:

    <link rel="stylesheet" href="/res/packages/github/twbs/bootstrap@3.3.5/css/bootstrap.css">    

In some cases, one can use the systemjs css plugin, but this loads asynchronously -- so you see the raw HTML for half a second before the CSS loads:

    <script type="application/javascript">
      System.import('bootstrap/css/bootstrap.css!');
    </script>

I guess an alternative would be to write a plugin for frontend servers (e.g., Flask) to parse the config.js file and generate a path on the fly? Is there are better workflow?

**Comment by chenxsan** [comment]
It's convenient to use `System.import` to load CSS when developing. Then at the build time, just bundle a separate css file with [`SeparateCSS` option configured to be true](https://github.com/jspm/jspm-cli/wiki/Plugins#css-builds). With tools like gulp and useref, you can parse the HTML and insert the `<link/>` tag in the head. Check an example [here](https://github.com/geelen/glenmaddern.com/blob/master/snapshot.js#L16).

**Comment by guybedford** [comment]
Yes a `separateCSS` build or a server that uses the CSS trace is the way to go here. CSS tracing servers are pretty easy to setup by using the `require('jspm').Builder` `builder.trace` method and then reading out the CSS.

**Comment by richburdon** [comment]
Thanks -- I think the assumption is that everyone is using node. I'm not.
