### ISSUE TITLE
Unable to install jspm css with TypeScript transpiler

### ISSUE THREAD

**Issue by nicky-lenaers** [jspm/jspm-cli#1005]
I'm trying to run ``jspm install css`` with the recently added TypeScript transpiler initially specified in the jspm config file. I get this error:
![image](https://cloud.githubusercontent.com/assets/2785350/9157176/ee646114-3ef3-11e5-8ef8-66e8a5668f61.png)

Tracing it back to the ``core.js`` file of jspm, I see this statement:

```sh
var tPkgs;
    if (transpilerName === 'traceur')
      tPkgs = ['traceur', 'traceur-runtime'];
    else if (transpilerName === 'babel')
      tPkgs = ['babel', 'babel-runtime', 'core-js'];
    tPkgs.forEach(function(p) {
      if (config.loader.baseMap[p])
        if (!nodeSemver.satisfies(config.loader.baseMap[p].version, tPackages[p].split('@')[1]))
          ui.log('warn', '`' + p + '@' + config.loader.baseMap[p].version + '` is out of date. Use %jspm dl-loader% to update.');
    });
```
There is no branche in the if statement for TypeScript.

Can this be fixed?

Thanks!

**Comment by nicklasb** [comment]
Use the latest beta version, there it is.

**Comment by nicky-lenaers** [comment]
Beta works just fine, thanks!
