### ISSUE TITLE
TypeScript errors being ignored?

### ISSUE THREAD

**Issue by jackfranklin** [jspm/jspm-cli#1009]
Running the latest beta of jspm, I've got a TypeScript plugin going (with Angular 2 as well).

However, it seems that errors that I would expect to see outputted when TypeScript compiles are not.

For example, given a class that looks like this:

```
export default class Friends {
  friends: Array<string>;

  constructor() {
    this.friends = 'bob'; // not Array<string>
  }
}
```

I do not see any errors in my browser console. Do I need to enable some setting? The repo I'm working on is: https://github.com/jackfranklin/ng2-jspm-typescript.

Thanks

**Comment by guybedford** [comment]
This seems like a bug in the TypeScript transpile implementation at https://github.com/ModuleLoader/es6-module-loader/blob/master/src/transpiler.js#L69.

**Comment by jackfranklin** [comment]
:+1: I'm happy to try to give it a fix - if I throw a test into ES6 Module loader that gives it some broken TypeScript and see how I go from there? Does that sound sensible?

**Comment by guybedford** [comment]
Certainly, sounds great!

**Comment by frankwallis** [comment]
The built-in TypeScript transpiler does not perform any type-checking, it just transpiles the code, see https://github.com/systemjs/systemjs/issues/488. If you want type-checking then you can use [plugin-typescript](https://github.com/frankwallis/plugin-typescript), or just run the compiler separately.

**Comment by guybedford** [comment]
Tracking at https://github.com/systemjs/builder/issues/206.
