### ISSUE TITLE
Babel's async methods return undefined from 'await'

### ISSUE THREAD

**Issue by iksose** [jspm/jspm-cli#1017]
https://babeljs.io/repl/#?experimental=false&evaluate=true&loose=true&spec=false&code=const%20promise%20%3D%20()%20%3D%3E%20%7B%0A%20%20return%20new%20Promise((resolve%2C%20reject)%20%3D%3E%20%7B%0A%20%20%20%20setTimeout(()%20%3D%3E%20%7B%0A%20%20%20%20%20%20return%20resolve(%22foo%22)%0A%20%20%20%20%7D%2C%201000)%0A%20%20%7D)%0A%7D%0A%0Aclass%20Foo%7B%0A%20%20constructor()%7B%7D%0A%20%20async%20method()%7B%0A%20%20%20%20const%20res%20%3D%20await%20promise()%3B%0A%20%20%20%20console.log(%22got%22%2C%20res)%0A%20%20%7D%0A%7D%0A%0Avar%20foo%20%3D%20new%20Foo()%3B%0A%0Afoo.method()

````javascript
const res = await promise();
console.log("got", res)
````

Logs undefined in babel 0.16.0-beta.3

**Comment by guybedford** [comment]
`await` is disabled by default in Babel, you need to enable it via the transformer options (http://babeljs.io/docs/advanced/transformers/).

**Comment by iksose** [comment]
I've got the stage option set to 0/1, shouldn't that handle those?

**Comment by guybedford** [comment]
I believe you can only use `await` inside of `async` functions and not at the base-level.
