### ISSUE TITLE
Cannot install typescript@next

### ISSUE THREAD

**Issue by jessegood** [jspm/jspm-cli#1018]
`jspm install typescript=npm:typescript@next` fails with:

> err No version match found for npm:typescript@next

Using jspm 0.16.0-beta.3. Any way to get this to work?

**Comment by guybedford** [comment]
We don't currently support version aliases in jspm, although this may well be supported in future.

You'll need to install the exact version eg `jspm install npm:typescript@1.6.0-dev.20150813`.

**Comment by jessegood** [comment]
I see. Thanks.

**Comment by guybedford** [comment]
You can actually just ignore that message - this would exactly be the way to use the nightly releases.

**Comment by mtrivolli** [comment]
I came to the same situation trying to install typescript@beta. How can I find what version corresponds to an alias?

**Comment by guybedford** [comment]
See http://github.com/frankwallis/plugin-typescript rather.

**Comment by mtrivolli** [comment]
Thanks. The hint was useful!

**Comment by tamird** [comment]
@guybedford is there an issue tracking version alias support?

**Comment by adamburgess** [comment]
@tamird see https://github.com/jspm/npm/issues/61
I've also made a PR for .17 beta: https://github.com/jspm/npm/pull/137
