### ISSUE TITLE
jspm bundle does not follow the baseURL in package

### ISSUE THREAD

**Issue by danfma** [jspm/jspm-cli#1019]
I'm using the new version jspm@beta (0.17 I guess) and it does not respect the baseURL (server path) when bundling some modules... The current release is working good!

**Comment by guybedford** [comment]
@danfma thanks for reporting - can you share a simple test case or some steps to reproduce? Do you mean the baseURL in the package.json file here? Note also that relative imports (`./x`) are not baseURI-relative not baseURL-relative.

**Comment by danfma** [comment]
@guybedford, I used the same configuration on the previous version and it worked. I am trying to create a configuration to use in the ASP.NET 5. So, follow these steps in some new directory:

```markdown
npm install -g jspm@beta
npm install jspm@beta
jspm init

Package.json file does not exist, create it? [yes]:
Would you like jspm to prefix the jspm package.json properties under jspm? [yes]:
Enter server baseURL (public folder path) [./]: **./wwwroot/**
Enter jspm packages folder [wwwroot\jspm_packages]: **wwwroot/libs/jspm**
Enter config file path [wwwroot\config.js]: **wwwroot/libs/jspm-config.js**
Configuration file wwwroot\libs\jspm-config.js doesn't exist, create it? [yes]:
Enter client baseURL (public folder URL) [/]:
Do you wish to use an ES6 transpiler? [yes]: **no**

jspm install core-js
jspm bundle core-js wwwroot/libs/bundle/core-js.bundle.js --inject 
```
I used the core-js as an example, but the same works with any library.
After that, if you go in the config file (`wwwroot/libs/jspm-config.js`) you will see that the bundle is defined as `wwwroot/libs/bundles/core-js.bundle.js` but should be `libs/bundles/core-js.bundle.js`

**Comment by danfma** [comment]
And thanks for the quick response!

**Comment by guybedford** [comment]
Thanks for the detailed info, fixed in https://github.com/jspm/jspm-cli/commit/34fa7b8559acedee648764148e72e6b7c56afeef.

**Comment by theefer** [comment]
Thanks for the fix! I encountered the same bug when upgrading so also waiting for a new JSPM release to switch to >beta.3.

**Comment by guybedford** [comment]
This is released in 0.16 now.

**Comment by danfma** [comment]
Hey @guybedford, I just tested the beta7 and the problem continues... build release error? :)

**Comment by theefer** [comment]
Seems fixed in the stable version \o/
