### ISSUE TITLE
socket.io not working

### ISSUE THREAD

**Issue by zeeshanjan82** [jspm/jspm-cli#1020]
I have experienced a strange issue, when using socket.io client library from the cdb https://cdn.socket.io/socket.io-1.3.6.js I am able to work with socket.io properly but when using socket.io from jspm installed library either through npm install socket.io or using github github:socketio/socket.io-client@1.3.6 I get the socket.io main object undefined. I am really not sure whats causing this issue. For now I just have to include the cdn library url in my index.html file but I would really like  it working through jspm.

**Comment by zeeshanjan82** [comment]
https://github.com/socketio/socket.io-client/issues/873

**Comment by guybedford** [comment]
Support for npm packages in jspm is never perfect, and this is one that needs some overrides to make it work. Issues for overrides are tracked at the jspm registry repo. I've created an issue for you at https://github.com/jspm/registry/issues/525, and tracked the necessary steps to make this work.

**Comment by zeeshanjan82** [comment]
Thanks @guybedford
