### ISSUE TITLE
Ensure that locate has a default timeout setting?

### ISSUE THREAD

**Issue by lookfirst** [jspm/jspm-cli#1021]
I happened to notice some timeouts during some github/circleci weirdness. Looking through the source code of jspm, it looks like `locate` doesn't have any defaults set, but `lookup` does. 

I just wanted to make sure that the `locate` setting isn't forgotten.

Also @guybedford could you please report in the failure message what the current timeout is set as? I'm sure that would be helpful.

```
warn Timed out on locate for github:angular/bower-angular, retrying (1).
     Set the timeout via jspm config registries.github.timeouts.locate <secs>
```

**Comment by guybedford** [comment]
Thanks, locate isn't being left out, it just shares the timeout with lookup. have improved the message in https://github.com/jspm/jspm-cli/commit/94c153169c33c0bfed8abb31b9957a0c2336b962.
