### ISSUE TITLE
JSPM conflates local, relative path with mapped, installed package

### ISSUE THREAD

**Issue by danmartinez101** [jspm/jspm-cli#1022]
I have a source directory that contains all of my source files.
I have configured jspm to put installed packages in source/jspm_packages

I have installed a package: redux-1.0.0rc
I have a folder named redux that contains my redux related code.

When I import './redux/reducers/index' from the root, I get file not found for 'redux-1.0.0-rc/reducers/index'

I would expect that redux-1.0.0rc would only be resolved if the import was for 'redux' but not when the import path is a relative path.

**Comment by guybedford** [comment]
@danmartinez101 try running the jspm beta, I believe it should solve this naming collission issue for you.

**Comment by danmartinez101** [comment]
I believe I'm using the latest beta:     "jspm": "^0.16.0-beta.7",

The boilerplate I started with was https://github.com/danmartinez101/jspm-react-redux-boilerplate/blob/master/package.json but I'll make sure that beta.7 was what actually got installed.

**Comment by guybedford** [comment]
Did you manage to get this to work?

**Comment by danmartinez101** [comment]
Looks like with the latest beta this isn't an issue. I'm guessing I saw the issue before updating. Thanks!
