### ISSUE TITLE
How to properly shim something with no main defined in package.json?

### ISSUE THREAD

**Issue by togakangaroo** [jspm/jspm-cli#1023]
I'm a big fan for the [jquery-form plugin which unfortunately doesn't provide a main key in the `package.json`](https://github.com/malsup/form/blob/master/package.json).

As a result of this, when I `jspm install npm:jquery-form` I don't get the `jspm_packages/npm/jquery-form@3.50.0.js` shim which would typically contain just a line that points to the main:

     module.exports = require("jquery-form@3.50.0/jquery.form");

since the above does not exist I cannot `import foo from 'jquery-form'` because this points to the aforementioned file which does not exist.

Additionally, since the package needs the following configuration to work since it has kind of a half-assed umd on it

```
System.config({
  "meta": {
    "npm:jquery-form@3.50.0": {
      "format": "cjs",
      "exports": "$",
      "deps": ["jquery"]
    }
  }
});
```

## Solution Attempt 1

If I create the aforementioned file, everything works. But that means I have to have a versioned file in a package-manager controlled directory (and I don't commit these). This is convenient but doesn't really fly in a team environment.

## Solution Attempt 2

Create that shim file in a different location eg `shims/jquery-form.js`

     module.exports = require("../jspm_packages/npm/jquery-form@3.50.0/jquery.form");

and set the meta config to this path (or to `npm:/jquery-form@350.0/jquery.form` - I tried both). This fails when loading in the browser I get an error that comes from a 404 attempt to `/process.js`. I don't fully understand this error but clearly `process.js` is being loaded *relative* to the shim script since the previous worked.

## Solution Attempt 2.5

Ok, so how about no shim script at all? I only use this module in one react module that wraps it up into a more usable component - can I just do a regular import?

      import nada from '../jspm_packages/npm/jquery-form@3.50.0/jquery.form'

nope, same 404 loading error.

## Solution Attempt 3

Ok, so in that case we can change the mapping. In my `config.js`, jspm generated 

    "jquery-form": "npm:jquery-form@3.50.0",

...

    "npm:jquery-form@3.50.0": {
      "jquery": "npm:jquery@3.0.0-alpha1",
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
 
What if I put the proper path in there and change all instances of `npm:jquery-form@3.50.0` to `npm:jquery-form@3.50.0/jquery.form`?

**This works!**

**Until I try to jspm install anything** later on down the line - jspm starts blowing up. Debugging into it with node-inspector it seems to be getting confused by the version-number which it parses from the config file to be `3.50.0/jquery.form` rather than just `3.50.0`.

At this point I'm out of ideas and will probably go with option 1, as inferior as it is. But what *is* the right thing to do here? Where are the bugs and what is by-design?

**Comment by Munter** [comment]
You should use a jspm override and submit it to the registry. Try this in package.json:

``` js
{
  "jspm": {
    "overrides": {
      "github:malsup/form@3": {
        "main": "jquery.form.js"
      }
    }
  }
}
```

Then reinstall. If it works, submit a PR to the registry with `{ main: 'jquery.form.js' }` in a file called `form@3.0.0.js` in https://github.com/jspm/registry/tree/master/package-overrides/github/malsup/

**Comment by guybedford** [comment]
Did you resolve this issue?

**Comment by togakangaroo** [comment]
It *did* resolve the issue but unlike what @Munter suggested the correct override was

```
    "overrides": {
      "npm:jquery-form@3.50.0": {
        "main": "jquery.form.js"
      }
    }
```

I'm not sure that pushing it into the registry is the right move since this seems to be tied to a specific version.

**Comment by Munter** [comment]
Is the half-assed UMD and missing main file descriptor only in version `3.50.0`?  or do you mean that the override will only apply to that version? Because the override behavior is actually the version you specified and all subsequent minor and patch releases. So it will apply to all remaining 3.x versions.

You should probably add your System.config meta in the override as well to save future users some trouble

**Comment by guybedford** [comment]
I've added this to the registry in https://github.com/jspm/registry/commit/c174cdb2a30997a213cabbda28a9150de3b1824c.

I'm continually surprised by the reluctance of people to share their configurations with others in the registry, despite the minimal effort.

**Comment by togakangaroo** [comment]
Thanks, again, my concern was that I wasn't sure how to specify it. Does the thing you added mean that its only going to apply to this specific version? I have a PR into jquery-form already to add support for this on their end.

**Comment by guybedford** [comment]
Oh ok nice, yes that is ideal sending a PR back. The override will apply for all versions semver compatible with the override version, if you get it checked in though, we can remove it.
