### ISSUE TITLE
ignore removing incorrect files

### ISSUE THREAD

**Issue by lookfirst** [jspm/jspm-cli#1031]
v16.0

I've specified the main!

```
jspm install angular-input-modified=github:betsol/angular-input-modified -o '{ "main": "dist/angular-input-modified.min", "registry": "jspm", "dependencies": { "angular": "^1.4.0" }, "shim": { "dist/angular-input-modified.min": { "deps": [ "angular" ] } } }'
     Looking up github:betsol/angular-input-modified
     Updating registry cache...
     Downloading github:betsol/angular-input-modified@2.2.5
     Looking up github:angular/bower-angular

warn Main entry point not found for github:betsol/angular-input-modified@2.2.5.
     Adjust this property in the package.json or with an override, setting "main": false if this is the intention.

ok   Installed angular-input-modified as github:betsol/angular-input-modified@^2.2.5 (2.2.5)
ok   Install tree has no forks.

ok   Install complete.
```

**Comment by lookfirst** [comment]
Reverting to b6 makes that work

**Comment by lookfirst** [comment]
probably related to #1026

**Comment by lookfirst** [comment]
@guybedford ? the file is in the registry. I just removed my local override and I still see:

I'm still at b7 due to these issues.

```
warn Main entry point not found for github:betsol/angular-input-modified@2.2.5.
     Adjust this property in the package.json or with an override, setting "main": false if this is the intention.
```

**Comment by lookfirst** [comment]
Oh weird, I had to clear out my config.js map{} to make this work.

**Comment by lookfirst** [comment]
Actually, now that I tried this further, it still isn't installing correctly.

**Comment by lookfirst** [comment]
It works fine with my local override, but doesn't work with the registry override.

```
      "github:betsol/angular-input-modified@2.2.5": {
        "main": "dist/angular-input-modified.min",
        "registry": "jspm",
        "dependencies": {
          "angular": "^1.4.0"
        },
        "ignore": [
          "demos",
          "emblem",
          "tests"
        ],
        "shim": {
          "dist/angular-input-modified.min": {
            "deps": [
              "angular"
            ]
          }
        }
      }
```

If I try locally, with the `.min`, then things fail just like they do with the registry version.

**Comment by lookfirst** [comment]
@guybedford ... this has a way of randomly breaking my builds... any thoughts?

**Comment by guybedford** [comment]
@lookfirst can you clarify what exactly is breaking here? Note that the main difference between your local version and the registry version seems to be that you're locally using the `.min` files while the registry is using the original sources. The shim and everything appears to be working fine though to me.

**Comment by lookfirst** [comment]
From the very first comment, please explain to me why I'd see output saying that I haven't specified a main even though there is clearly one in the override?

**Comment by guybedford** [comment]
It doesn't say you haven't specified a main, it says that the main specified can't be found.

**Comment by lookfirst** [comment]
Ok... so explain that then too. =)

**Comment by guybedford** [comment]
If the main in the override is being set as `dist/angular-input-modified.min` it should probably be `angular-input-modified.min`, as that is the folder structure within the release archive.

**Comment by lookfirst** [comment]
http://take.ms/yvuHq
http://take.ms/PgmzE

This is working today, but sometimes randomly fails in my CI server builds.

**Comment by lookfirst** [comment]
The first shot is the folder in my jspm_packages install

**Comment by guybedford** [comment]
This seems to be an issue with the `ignore` property.

If you run `jspm install angular-input-modified=github:betsol/angular-input-modified -o '{ ignore: null}'` it works ok.

**Comment by lookfirst** [comment]
ignore does seem broken, but I'm not using it in my local override right now and I still randomly see errors every once and while. I think this is a combination of a couple bugs.

**Comment by guybedford** [comment]
Ignore is in the registry override, which always applies - overrides override the registry override, which acts as if it were part of the package by default.

**Comment by lookfirst** [comment]
I guess I'm still confused as to why this is randomly working then. =)

**Comment by guybedford** [comment]
Perhaps that's due to the ignore bug applying randomly due to async fs timings.

**Comment by lookfirst** [comment]
Adding "ignore": null and "ignore": [] to my override and both caused this issue with karma...

```
25 08 2015 02:21:41.727:ERROR [karma]: { [Error: ENOENT, open '/home/ubuntu/hub/target/jspm_packages/github/betsol/angular-input-modified@2.2.5/demos/vendor/angular']
  errno: -2,
  code: 'ENOENT',
  path: '/home/ubuntu/hub/target/jspm_packages/github/betsol/angular-input-modified@2.2.5/demos/vendor/angular' }
Error: ENOENT, open '/home/ubuntu/hub/target/jspm_packages/github/betsol/angular-input-modified@2.2.5/demos/vendor/angular'
    at Error (native)
25 08 2015 02:21:41.735:ERROR [karma]: { [Error: ENOENT, open '/home/ubuntu/hub/target/jspm_packages/github/betsol/angular-input-modified@2.2.5/demos/vendor/angular-ui-tinymce']
  errno: -2,
  code: 'ENOENT',
  path: '/home/ubuntu/hub/target/jspm_packages/github/betsol/angular-input-modified@2.2.5/demos/vendor/angular-ui-tinymce' }
Error: ENOENT, open '/home/ubuntu/hub/target/jspm_packages/github/betsol/angular-input-modified@2.2.5/demos/vendor/angular-ui-tinymce'
    at Error (native)
25 08 2015 02:21:41.737:ERROR [karma]: { [Error: ENOENT, open '/home/ubuntu/hub/target/jspm_packages/github/betsol/angular-input-modified@2.2.5/demos/vendor/tinymce']
  errno: -2,
  code: 'ENOENT',
  path: '/home/ubuntu/hub/target/jspm_packages/github/betsol/angular-input-modified@2.2.5/demos/vendor/tinymce' }
Error: ENOENT, open '/home/ubuntu/hub/target/jspm_packages/github/betsol/angular-input-modified@2.2.5/demos/vendor/tinymce'
    at Error (native)
npm ERR! Test failed.  See above for more details.

```

**Comment by lookfirst** [comment]
@guybedford Just got another random failure in my build. Other than just including the source code in my project directly is there any other solution to this?

**Comment by guybedford** [comment]
@lookfirst the error you posted with `ignore: null` is a Karma error not a jspm one? Are you sure jspm was trying to open that file? As for fixing the issue, yes the ignore code in https://github.com/jspm/jspm-cli/blob/master/lib/build.js#L109 can be fixed.

**Comment by lookfirst** [comment]
@guybedford The error is a result of running Karma after doing a jspm install because the install is horked in some way or another.

**Comment by lookfirst** [comment]
@guybedford These random failures on angular-input-modified are killing me. =(

**Comment by guybedford** [comment]
@lookfirst the bug you are getting setting `ignore: null` is definitely a Karma one not a jspm one - so I'm not sure how you want me to help you with that?

I just spent half an hour debugging the ignore issue to enable the `ignore` property, and it turns out that `demos/vendor/angular-input-modified/angular-input-modified.js` is a symlink to `dist/angular-input-modified.js` we run `fs.unlink` against the symlink, which somehow is causing the original file to be removed as well (which is not what `fs.unlink` should ever do). So that's got me stumped - as I'm really not sure how that could be happening though, but it is clear now at least it has something to do with the symlinking.

**Comment by lookfirst** [comment]
re: the `ignore`... the problem here is that I have no way to disable or override the ignore without breaking karma. 

Since this other bug is the real source of the problem lets just focus on that for now. =)

**Comment by guybedford** [comment]
I'm just not sure I understand how a jspm-only override property can be affecting Karma, as there is no way Karma would be able to even see what override option was passed to jspm? I think it's probably due to the symlink not resolving to anything when Karma globs the files actually, and not jspm-related at all.

**Comment by lookfirst** [comment]
Karma-jspm plugin

**Comment by guybedford** [comment]
@lookfirst I'd suggest posting an issue to Karma-jspm then.

**Comment by guybedford** [comment]
We also incorrectly remove `file.js` on:

```javascript
"files": [
    "/*.js",
    "/License.md",
    "/Readme.md",
    "/module/",
    "/test/"
  ],
```

**Comment by guybedford** [comment]
Fixed in https://github.com/jspm/jspm-cli/commit/d3b70f4fdd195cfd003fdd4b37997b18e3edff92.

**Comment by guybedford** [comment]
Released in 0.16.3.

**Comment by lookfirst** [comment]
THANK YOU! :+1:

**Comment by lookfirst** [comment]
@guybedford Sorry to kick a dead horse, but I just tried installing angular-input-modified and it fails pretty badly. The `dist` folder is empty. It looks like a problem with ignores.

`jspm install angular-input-modified=github:betsol/angular-input-modified`

makes an empty dist folder.

`jspm install angular-input-modified=github:betsol/angular-input-modified -o '{ ignore: null}'`

works better, but that overrides the registry and installs too much...

I'm using jspm 0.16.13.

**Comment by guybedford** [comment]
@lookfirst thanks for the follow up. After the long-winded fix above I actually altered it to just never create symlinks on download at all, but left out a case. Added this in https://github.com/jspm/github/commit/550ecc648ba70bd7c27a3f619f39bc8eaefd4b15.

**Comment by lookfirst** [comment]
@guybedford :+1: :bow:

**Comment by lookfirst** [comment]
Finally got around to confirming this is fixed. ;-)
