### ISSUE TITLE
--inject flag on bundle-sfx causing unexpected behavior

### ISSUE THREAD

**Issue by MattMessmerBlossor** [jspm/jspm-cli#1035]
Hi! I'm new to jspm and just inherited a build process from another dev that's reasonably broken, to say the least. One of the gems in my build process has something to the effect of:

```
jspm bundle-sfx myjsfile my-sfx-bundle.js --inject
```

I can't find anything in the documentation regarding the `--inject` flag when used in combination with `bundle-sfx`, but in reading the documentation provided, it seems like they sort of contradict each other because an sfx bundle should require a single script tag, whereas `--inject` tries to get rid of the need for a script tag. Does that make sense? If so, I'm wondering if it makes sense to throw an error if `--inject` is used with `bundle-sfx`. If not, can you clear up my confusion? :) Thanks much!

Motivation: Until today I didn't really mind what I thought was a contradiction because I still don't fully understand the build process I inherited, but today the bundling suddenly broke and getting rid of `--inject` here magically fixed it, after trying various other fixes for the last 4 hours. Very odd!

**Comment by guybedford** [comment]
Yes the `--inject` flag is not supported for bundle-sfx. A change in our options parsing meant the flag was seen as an argument, which would have broken your code here. I'm not sure I want to change the options parsing to treat it as an invisible flag again though. Closing, but let me know if you have any further questions at all.
