### ISSUE TITLE
Package override not honoring format attribute

### ISSUE THREAD

**Issue by loloolllool** [jspm/jspm-cli#1037]
Testing the following override
`jspm install markdown=github:loloolllool/editor@0.1.2 -o { registry: 'jspm', 'format': 'cjs', main: 'index', 'shim': { 'index': { 'deps': './editor.css!'} } }`

It results with the following error message

    Cannot set property 'exports' of undefined

I figured out that the override writes the following lines to index.js

    /* */ 
    "format global";
    "deps ./editor.css!";

, and tried changing to "format cjs"; instead, and the `cannot set property 'exports' of undefined` went away.

I can't find documentation about why format from my test override would not be honored, therefore i ask here if it is an issue with jspm package overrides or if i am doing something wrong.

P:\atomprojects\demo13>jspm -v
0.16.0
Running against local jspm install.

**Comment by loloolllool** [comment]
P:\atomprojects\demo13>jspm -v
0.16.0
Running against local jspm install.

**Comment by Slumber86** [comment]
Same here, the worst thing is that jqueryUi half modules are globals and half are AMD. the install via CLI all is OK, when you do jspm install  is broken.

**Comment by guybedford** [comment]
Shim implies that the file is a global format module. There isn't currently a way to shim dependencies for other formats. This support will be coming in the next major version.

Rather use SystemJS config directly for this - 

```javascript
System.config({
  meta: {
    'markdown/index.js': { deps: ['./editor.css!'] }
  }
});
```

**Comment by MeoMix** [comment]
:+1 I encountered this issue, as well. At the very least a warning that it's not currently supported would be nice. It was surprising to see it still as "global".

**Comment by guybedford** [comment]
Yes it's confusing - jspm 0.17 will no longer have this restriction.

**Comment by MeoMix** [comment]
:clap: Thank you for all your work and quick responses.
