### ISSUE TITLE
export * from ' ... ' broken

### ISSUE THREAD

**Issue by zcregan** [jspm/jspm-cli#1038]
We recently updated jspm to 0.16.0 in our project but now a certain form of import doesn't seem to be working anymore. The structure looks like this:

module1.js:
```
import module2 from 'module2';
```

module2.js:
```
export * from 'module3';
```

module3.js:
```
export default class { ... }
```

The code following the import statement in module1.js seems to be executing before module2.js has set any of it's exports.

**Comment by guybedford** [comment]
This is actually by design - `export *` by the ES specification does not export the default export.

So you'd need to use:

```javascript
export * from 'module3';
export {defualt} from 'module3';
```

To get a full export * with default.

**Comment by zcregan** [comment]
Oh I see. Did this change recently in SystemJS? Because our code used to work as is.

**Comment by guybedford** [comment]
Yes this changed in Babel and Traceur.

**Comment by zcregan** [comment]
Oh alright. Good to know. Thanks Guy.
