### ISSUE TITLE
Fail to override dependency

### ISSUE THREAD

**Issue by samouss** [jspm/jspm-cli#1039]
Hello,

I have trouble with JSPM for override dependency.

I already have `jQuery` loaded as `global` in my page. 
Then I try to load bootstrap via the registry and it has `jQuery` in his dependency, and I don't want to load this version for avoid conflict.

I already do that by set the map to `@empty` in `config.js` but I don't think that's the right way.

```js
"github:distros/bootstrap-less@3.3.9": {
  "jquery": "@empty"
},
```

So I would like override the package at the installation, I have already check this #924 and I try several ways but none worked:

```js
jspm install bootstrap-less -o "{ map: { jquery: '@empty' } }"
jspm install bootstrap-less -o "{ map: { jquery: '@empty' }, shim: {} }"
```

Any ideas ?

Thanks.

**Comment by guybedford** [comment]
Try using `jspm install bootstrap-less -o "{map: {jquery: 'jquery'}}", where `jquery.js` in the root of your project just contains:

```javascript
module.exports = window.$;
```

**Comment by samouss** [comment]
It doesn't work jQuery is still loaded as global. 
So it overrides my current version already loaded globally.

There are no ways for install a dependency without loads his dependencies ?

**Comment by guybedford** [comment]
@samouss make sure you run `jspm uninstall jquery` so that there is no other match for jQuery at all. This definitely works for me - I did test it.

**Comment by samouss** [comment]
My bad, I update JSPM to `0.16.0`, and it solves my problem.

The `install` command works now with this:

```js
jspm install bootstrap-less -o "{ map: { jquery: '@empty' } }"
```

Thanks for the support !
