### ISSUE TITLE
Cannot integrate converse.js using jspm

### ISSUE THREAD

**Issue by hjbolide** [jspm/jspm-cli#1040]
Hi Guy,

Today I started to port my chat client written in ES5 to using ES6 and came across jspm, when I spinned it up trying to integrate converse.js, system.js kept complaining about "AMD module github:jcbrand/converse.js@0.9.4/main did not define".

My Repo url: https://github.com/hjbolide/xmpp-converse-es6.

I have also tried jspm beta, the error message was different, which was 'require is not a function'.

Do you mind to have a look and see what did I do wrong?

Thanks a bunch.

Charles

**Comment by guybedford** [comment]
If you look at the file, https://github.com/jcbrand/converse.js/blob/master/main.js, it is not an AMD module file, it is actually a JS file that expects RequireJS to be present and then uses the AMD require.

It will likely take some work to construct the necessary override to make converse work through SystemJS. I'd suggest loading the full build directly instead at `converse.js/builds/converse.min.js`.

**Comment by hjbolide** [comment]
Hey Guy,

I've followed your advice to import from converse.min.js and it worked like a charm.
Thank you very much.

Regards,
Charles

**Comment by hjbolide** [comment]
I have tried to delete the meta section in config.js, and put:
    import
