### ISSUE TITLE
jspm github authentication doesn't exit

### ISSUE THREAD

**Issue by Mosho1** [jspm/jspm-cli#1041]
I tried installing jspm on a new machine and received an error about rate limit when installing packages.

I'm using 0.16.0-beta.7
EDIT: happens with 0.15.6 as well

I then tried `jspm registry config github` but when I enter my credentials, the program never exits and the credentials never get configured.

Another issue is that during package installation, I'm asked to add my credentials in a prompt, but when I press enter I get lots of errors from the package installation itself, like it kept running in the background and swallowed errors. After entering my username in the next prompt I press enter and get more errors after which the program exits without asking me for my token/password. I'm not sure this is a real problem, but it kinda looks bad either way.

**UPDATE:** I removed line 169 in `jspm-github/github.js` (`ui.confirm` call) and manually put in my token and it works. I was using the latest git bash (2.4.5) which I recently updated to and that seems to have been the issue. Switching to `cmd` works fine.

**Comment by guybedford** [comment]
Can you clarify what you mean that the program never exists on credential configuration? Have you tried running jspm@0.16 here?

**Comment by Mosho1** [comment]
Sorry, I mean the process stalls. I just installed jspm from npm and tried again, still no go.
 
This is how it looks: (I've entered my password and pressed enter)

![jspm-github-auth](https://cloud.githubusercontent.com/assets/5153007/9437042/906cc8f2-4a5c-11e5-828a-8207f1741784.PNG)

**Comment by guybedford** [comment]
So you mean you're not getting the question `Would you like to test these credentials?` at all? There is no code between those lines in https://github.com/jspm/github/blob/0.13.4/github.js#L169, so the only thing I can think is that `ui.confirm` is not working in your environment! Do other yes/no confirm prompts like in `jspm init -p` work ok?

**Comment by Mosho1** [comment]
Yeah, `jspm init -p` works fine. Note that I've worked around this, so if it's not something you think is important for other potential users you shouldn't bother.

**Comment by guybedford** [comment]
If it's happening for you there's a chance it will happen for other users, so if you're able to work out where the bottleneck is that would help others.

**Comment by Mosho1** [comment]
The issue seems to be around `process.stdin.setRawMode`. If I remove lines 166 and 167 in ui.js it works correctly (other than outputting the password). Calling `process.stdin.isTTY` returns `undefined` (while it returns `true` in cmd), and the `'data'` stream handler in line 169 doesn't get called at all.

**Comment by guybedford** [comment]
@Mosho1 thanks I've added the TTY check in https://github.com/jspm/jspm-cli/commit/ace7c9df999def6152f33a8ee0d6656fac8c3be0 here.

**Comment by guybedford** [comment]
@Mosho1 are you running io.js here by any chance?

**Comment by Mosho1** [comment]
Thanks, and I'm running node 0.12.7
