### ISSUE TITLE
"warn Installation changes not saved." if jspm_packages dir not already created

### ISSUE THREAD

**Issue by artparks** [jspm/jspm-cli#1042]
First time playing around with JSPM, I'm trying to go through the `jspm init` setup and it fails with:

    err  Error: ENOENT, scandir '/Users/me/dev/node/sucket/jspm_packages'

If I manually mkdir the `jspm_packages` directory then run it again it all works fine, but seems weird it's not happy to create the directory itself. Seems odd. Running as sudo makes no difference.

Not a big deal as it's easily fixed but seems worth flagging?

**Comment by guybedford** [comment]
Strange, I've never seen this actually - can you confirm what you do to get this? If I run `jspm init -y` in an empty folder it all works fine for me here on Mac. Could it be a platform issue?

**Comment by guybedford** [comment]
Also check you're definitely running jspm@0.16.

**Comment by artparks** [comment]
weird... if i run it in a totally fresh directory then it works fine. the directory it was failing in had contained a project previously that I deleted, that's the only difference I can see between that and the fresh install that works. no idea what was happening.

may as well close this and if I come across it again i'll do more digging. thanks.

**Comment by douglasros** [comment]
Hi Guy. Also first time installing jspm on Mac. After "jspm install"...enter through defaults...Which ES6 transpiler? I'm getting "Error: ENOENT, scandir '/Users/me/myFolder/jspm_packages'
         at Error (native)"
Workaround: Create a jspm_packages folder under myFolder just like artparks suggested (thanks art!!). "sudo jspm install" doesn't seem to help either.

**Comment by douglasros** [comment]
Also occurring on my Win7 machine (using cmd prompt) and git bash shell.

**Comment by guybedford** [comment]
@douglasros thanks for posting - perhaps it would help to know which version of NodeJS are you using here?

**Comment by artparks** [comment]
for m v0.12.7

**Comment by douglasros** [comment]
node 0.12.3
npm 2.9.1

**Comment by douglasros** [comment]
BTW - thanks for responding! Looks like jspm 0.16.0 is working just fine
for me so I'll just use that for now.

**Comment by nifl** [comment]
Same error on new installation. Initially had node 0.12.0 and jspm 0.16.2. Rolled back to jspm 0.16.0 per previous comment and error persisted. Upgraded node to 0.12.7, error persists.

Steps:

    mkdir newProject
    cd newProject
    npm install -g jspm jspm-server
    jspm install

    err       Error: ENOENT, scandir '/Users/nifl/Code/typeslab/jspm_packages' at Error (native)

**Comment by guybedford** [comment]
@nifl thanks, I'm struggling to recreate this at all following your steps above. Do you get the same if you run `jspm init`? What OS are you running? Any help replicating very welcome.

**Comment by nifl** [comment]
I should have been sleeping last night. I hadn't yet cloned the repository I was trying to run. No more errors. Thanks and sorry for the false flag.

**Comment by madis** [comment]
I'm getting this error too. It doesn't occur when I do ```mkdir jspm_packages``` before ```jspm install```

```bash
$ npm install jspm

$ jspm -v
0.16.12
Running against local jspm install.

$ node -v
v0.12.7

$ jspm install
jspm install -y
Package.json file does not exist, create it?:Yes
Would you like jspm to prefix the jspm package.json properties under jspm?:Yes
Enter server baseURL (public folder path):./
Enter jspm packages folder:./jspm_packages
Enter config file path:./config.js
Configuration file config.js doesn't exist, create it?:Yes
Enter client baseURL (public folder URL):/
Do you wish to use a transpiler?:Yes
Which ES6 transpiler would you like to use, Babel, TypeScript or Traceur?:babel

err  Error: ENOENT, lstat '/Users/madis/temp/jspm-proov/jspm_packages'
         at Error (native)

warn Installation changes not saved.
```

**Comment by guybedford** [comment]
@madis thanks, fixed in https://github.com/jspm/jspm-cli/commit/0004dc8bbae5bff85d50a8fd322ea5f6be6ee9c4
