### ISSUE TITLE
define transpiler in package.json

### ISSUE THREAD

**Issue by brillout** [jspm/jspm-cli#1043]
Is there a way to define the transpiler in the package.json?
I can't find any note on that in the documentation.

Not being able to do so forces me to either include the config.js in the repository or to add a build step `jspm dl-loader babel`.

**Comment by guybedford** [comment]
The `config.js` file is the source of this information, and should be checked in to version control as it forms the version lock for the package.

**Comment by neothemachine** [comment]
To clarify: For applications, config.js should be checked in to version control, but not for libraries. Correct?

**Comment by guybedford** [comment]
@neothemachine :+1: although if you're treating that configuration as a tests configuration, then it can also make sense to treat the tested target versions as locked.
