### ISSUE TITLE
Bundle build fails

### ISSUE THREAD

**Issue by panicbit** [jspm/jspm-cli#1045]
When trying to bundle on `0.16` I get the following error:

```
$ jspm bundle --inject 'index.coffee!coffee'
     Building the bundle tree for index.coffee!coffee...

/usr/lib/node_modules/jspm/node_modules/systemjs/dist/system.src.js:1262
        throw addToError(e.toString(), 'Evaluating ' + load.address);
              ^

err  TypeError: /usr/lib/node_modules/jspm/node_modules/systemjs/dist/system.src.js:2993
            return load.metadata.builderExecute();
                                 ^
     undefined is not a function
	Evaluating file:///<project>/jspm_packages/github/forresto/system-coffee@0.1.2/coffee.js
	Evaluating file:///<project>/jspm_packages/github/forresto/system-coffee@0.1.2.js
	Error loading file:///<project>/jspm_packages/github/forresto/system-coffee@0.1.2.js
```

However bundling on `0.15` works fine.

I'm not sure whether this is a `jspm-cli` or a `system-coffe` issue.

**Comment by guybedford** [comment]
Thanks so much for the detailed report, this helped tracked down an important bug in the latest release due to AMD plugins not building properly. Fixed in https://github.com/systemjs/builder/commit/d2e6c3397821e8d41c9e7d33c756704f1548f69d, with the issue being tracked at https://github.com/systemjs/builder/issues/275.

**Comment by panicbit** [comment]
:+1: 
I think the dependency version needs to be bumped then https://github.com/jspm/jspm-cli/blob/master/package.json#L23

**Comment by guybedford** [comment]
The build should be working now with an update to jspm.

**Comment by panicbit** [comment]
@guybedford Yeah bundling itself works now but the bundle seems to be broken. Issue incoming.
