### ISSUE TITLE
baseURL in Config.js changes when installing a package

### ISSUE THREAD

**Issue by f15gdsy** [jspm/jspm-cli#1046]
Hi,
I'm using jspm with Electron. I put the baseURL field as __dirname + "/" in Config.js. 
However, when installing a package, the __dirname changes to absolute address like "/Users/UserA/Desktop/app/node_modules/jspm/lib/config/".
I'm wondering why it happens and how to fix it?

Thanks!

**Comment by guybedford** [comment]
Yes, dynamic values in the `config.js` file are not supported. Note that `config.js` is the baseURL value in the client. For setting the server-level baseURL, set `directories.baseURL` in the package.json file. Running `jspm init -p` will guide you through the prompts to set these as well.
