### ISSUE TITLE
Support non .js mains

### ISSUE THREAD

**Issue by nicklasb** [jspm/jspm-cli#1048]
While SystemJS [now supports](https://github.com/systemjs/systemjs/issues/721) loading pure typescript packages, jspm so far does not support their installation fully.

Just using a "main"-reference in package.json results no reaction at all, and pointing to an index.ts 
`Main entry point not found for xxx`-error.

In neither case a name@x.y.z.js is created.

**Comment by guybedford** [comment]
Non `.js` extension mains are not currently supported yes... they will only work through package config at the moment.

**Comment by nicklasb** [comment]
In that case, consider this a feature request.  :-)

**Comment by guybedford** [comment]
Sure, it's on the roadmap for 0.17, not sure if I'll be able to prioritise it before then but will see.

**Comment by nicklasb** [comment]
Can't that load like any other SystemJS reference? And be a .css! if
plugins are loaded?

**Comment by nicklasb** [comment]
Also, how do I load it using the package config? 
(some setting that isn't overwritten by updates and so on)

**Comment by nicklasb** [comment]
For example; this doesn't help, it doesn't matter what I put in "main":
```js
  packages: {
    "github:OptimalBPM/mbe-nodes@0.4.10": {
      "defaultExtension": "ts",
      "map": {
        "mbe-nodes": "github:OptimalBPM/mbe-nodes@0.4.10"
      },
      "main": "./dist/nodes.ts"
    }
  }
```

**Comment by nicklasb** [comment]
OMG. I am such a moron. I stared at this for two hours without realizing that I now have updated the package to 0.4.13. Disregard the above statement. It is, however a bit annoying to have to remember to update the package version all the time.

**Comment by nicklasb** [comment]
However, not having to do the package override would make jspm out-of-the-box TypeScript compatible, which I would say is a quite nice feature list item.

**Comment by chrisdostert** [comment]
+1

**Comment by guybedford** [comment]
Supported in jspm 0.17 beta.

**Comment by nicklasb** [comment]
Yay!!
