### ISSUE TITLE
"main" not honouring package.json for npm:form-data

### ISSUE THREAD

**Issue by theefer** [jspm/jspm-cli#1049]
When installing the [form-data](https://github.com/form-data/form-data) NPM package, the "main" property in package.json doesn't seem to be respected. Instead, JSPM seems to be using the value from the "browser" property, which is fine until you try to use form-data from within Node (via JSPM), e.g. when using the NPM `request` package.

```
$ cd /tmp
$ npm install form-data
form-data@1.0.0-rc3 node_modules/form-data
├── async@1.4.2
├── combined-stream@1.0.5 (delayed-stream@1.0.0)
└── mime-types@2.1.5 (mime-db@1.17.0)
$ grep -C 3 main node_modules/form-data/package.json 
    "type": "git",
    "url": "git://github.com/form-data/form-data.git"
  },
  "main": "./lib/form_data",
  "browser": "./lib/browser",
  "scripts": {
    "test": "./test/run.js"
$ jspm install npm:form-data
...
$ grep -C 3 '"main"' jspm_packages/npm/form-data@1.0.0-rc3/package.json 
    "type": "git",
    "url": "git://github.com/form-data/form-data.git"
  },
  "main": "./lib/form_data",
  "browser": "./lib/browser",
  "scripts": {
    "test": "./test/run.js"
$ grep -C 3 '"main"' jspm_packages/npm/form-data@1.0.0-rc3/.jspm.json 
    "type": "git",
    "url": "git://github.com/form-data/form-data.git"
  },
  "main": "./lib/browser",
  "browser": "./lib/browser",
  "scripts": {
    "test": "./test/run.js"
```

Is this expected behaviour? Is there a workaround or solution?

**Comment by guybedford** [comment]
Yes this is a limitation in jspm currently, as described in https://github.com/jspm/jspm-cli/blob/master/docs/nodejs-usage.md. We always use the `browser` property because we needed conditional loading for this. Conditional loading is in SystemJS now though, so this feature should be able to land with jspm 0.17.

**Comment by theefer** [comment]
I see. I was expecting to be able to override the main in that case, but `"browser"` seems to always take the precedence. Overriding browser seems to work:

```
# not working
$ jspm install npm:form-data -o '{"main": "lib/form_data"}'

# working
$ jspm install npm:form-data -o '{"browser": "lib/form_data"}'
```

Obviously will only work within Node but I don't mind in this case..

**Comment by theefer** [comment]
Are `package.json` overrides meant to apply transitively?

`form-data` is being brought in through the transitive dependencies into the [grid-batcher](https://github.com/guardian/grid-batcher) project:

[grid-batcher](https://github.com/guardian/grid-batcher) -> [any-http-request](https://github.com/argo-rest/any-http-request) -> [request](https://github.com/request/request) -> [form-data](https://github.com/form-data/form-data)

I have [tried](https://github.com/argo-rest/any-http-request/blob/master/package.json#L48-L52) to register the form-data config as an override in any-http-request's package.json, which applies to form-data in any-http-request, but not to form-data in grid-batcher. Is the override supposed to apply transitively? Or maybe is any-http-request's [`directories.lib` config](https://github.com/argo-rest/any-http-request/blob/master/package.json#L39) getting in the way?

Adding the override to the grid-batcher `package.json` works, but it'd be nicer to not to have to do that in all `any-http-request` consumers.

(I could add the override to the registry, but that'd mean breaking the package for all browser-based consumers of form-data...)

**Comment by guybedford** [comment]
We don't support transitive overrides no, previous discussion (talking with myself as usual) in https://github.com/jspm/jspm-cli/issues/854.

**Comment by theefer** [comment]
OK fair enough. I will hardcode the override in the top-level package for now.

What are your thoughts on pushing such an override to the registry, knowing it would break the browser behaviour but fix the Node one? Will we need separate overrides for each host environment?

**Comment by guybedford** [comment]
The browser case is the first-class scenario in jspm still. We can only encourage server-side use fully when we solve this issue, which will be possible in 0.17. Working hard to get there!

**Comment by guybedford** [comment]
Closing, as this will happen naturally, thanks for your patience!
