### ISSUE TITLE
"lib":"src" not working for me (or I don't understand it)

### ISSUE THREAD

**Issue by neothemachine** [jspm/jspm-cli#1050]
I thought that when I set "lib": "src" then that means a) all path properties in package.json are relative to it, and b) when I do an import it is relative to src/. But when I run `jspm bundle-sfx src/main bundle.js` it complains because a module imports something relative to src/ (like `sub/foo`) but in fact the error says that it tried to import it from the root path. I wonder if I have to change something in the config.js file, I always thought this is handled by jspm automatically. I haven't used lib before, all I did until now was develop a small application which had used baseURL (without lib) and that had worked.

**Comment by guybedford** [comment]
`directories.lib` is only supported for installed packages. Follow https://github.com/jspm/jspm-cli/issues/855 for support of `directories.lib` in application packages.

**Comment by neothemachine** [comment]
I have a good solution for this problem which I think is similar to what the python community adopted.
For librariess, instead of putting modules into the root or in "src", create a subfolder "mypackagename" under which all modules go. Then in your own code you refer to that prefix which will feel natural since this is how it would be used when installed. `directories.lib` is then set to that subfolder.

**Comment by neothemachine** [comment]
For wider support I will develop a library in npm-style, and, being my first one, I was shocked to find out that npm/node has absolutely no support for *proper* multi-module packages. Support for [directories.lib](http://blog.izs.me/post/44149270867/why-no-directorieslib-in-node-the-less-snarky) was removed long ago. The only sensible way would be to copy everything into the root before publishing to npm (nobody wants `import "mypackage/src/.."` or similar, period), but this is effort and then there's also a slight discrepancy between repo layout and what's installed. Seriously, this sucks. And I'm happy that JSPM supports directories.lib, please never remove that feature. Sorry, had to get that off my chest.
