### ISSUE TITLE
jspm restore bundles

### ISSUE THREAD

**Issue by gig177** [jspm/jspm-cli#1052]
How can i fast restore the bundles, which i was created in config.js by using something like:

``` bash
$ jspm bundle some-module --inject
```

Like a $ jspm unbundle but in reverse mode. Maybe can i use some api?

**Comment by guybedford** [comment]
Good idea - yes existing bundle files can be re-injected. Perhaps a `jspm bundle-inject bundle-name.js` or something like that.
