### ISSUE TITLE
How to install devDependencies?

### ISSUE THREAD

**Issue by ScreenDriver** [jspm/jspm-cli#1053]
I have following `package.json`

```json
{
  "jspm": {
    "directories": {},
    "dependencies": {
      "bluebird": "npm:bluebird@^2.9.34",
      "fetch": "npm:whatwg-fetch@^0.9.0"
    },
    "devDependencies": {
      "babel": "npm:babel-core@^5.8.22",
      "babel-runtime": "npm:babel-runtime@^5.8.20",
      "chai": "npm:chai@^3.2.0",
      "core-js": "npm:core-js@^1.1.0",
      "mocha": "npm:mocha@^2.2.5"
    }
  },
  "devDependencies": {
    "jspm": "^0.16.1"
  }
}
```
For unit testing I added [Mocha](http://mochajs.org) and [Chai](http://chaijs.com) manually by hand (for a full example look [here](https://github.com/curran/jspm-mocha-example)). I did not found anything like `--save-dev` or something like that in the cli.

**Comment by guybedford** [comment]
Because jspm saves all dependencies into the package.json by default, `--save-dev` is just `--dev` in jspm.

**Comment by ScreenDriver** [comment]
Ah ok thank you. This explains #1051 as well :+1: 
You should add `--dev` to `jspm --help` :wink:

**Comment by Yvem** [comment]
@screendriver +1 --dev should be referenced in --help

**Comment by thefabulousdev** [comment]
This option is non-existing on  **0.17.0-beta.12**, yet `jspm init` typescript selection adds a `devDependencies` attribute. 
Any reason for this?

**Comment by guybedford** [comment]
`jspm install x --dev` is supported.

**Comment by dsummersl** [comment]
This still isn't in the help message as of version 0.15.6

**Comment by jlguenego** [comment]
I have a suggestion for next version:

It would be to comply with the npm syntax (doing --save-dev or -D instead of --dev) and adding as well (--save-exact or -E to save the exact version)
