### ISSUE TITLE
jspm uninstall --dev does not delete package.json entry

### ISSUE THREAD

**Issue by ScreenDriver** [jspm/jspm-cli#1054]
I can install devDependencies with `jspm install npm:lodash --dev` but unfortunately `jspm uninstall npm:lodash --dev` does not delete the entry in my `package.json`

**Comment by ScreenDriver** [comment]
For some strange reasons it's working today :confused:

**Comment by tobiasbrenner** [comment]
You have to use the key listed within the dependencies Object (in package.json), not the "npm:" prefixed version of your dependency. 
Example: jspm uninstall lodash --dev
