### ISSUE TITLE
Deploying dependencies remotely and consume them from another porject

### ISSUE THREAD

**Issue by eyalsk** [jspm/jspm-cli#1055]
First I would like to thank you for this project it's brilliantly awesome! :)

I'm building a CMS and I'm thinking to store all my dependencies on a complete different server, meaning, I have a dedicated project that its sole purpose is to host dependencies let it be project A.

Now, in project B I'd have something like the code below in my index.html file.

```html
<script src="http://localhost:5005/jspm_packages/system.js"></script>
<script src="http://localhost:5005/config.js"></script>
```

Then I'd attempt to do something like this.

```html
<script>
System.import('app');
</script>
```

Now, app.ts resides in an app directory in project B and the TypeScript transpiler outputs an app.js to wwwroot using a build file.

Just a note, I don't use JSPM transpiler feature because my workflow is a bit different.

My question is, is this story fully covered from JSPM standpoint? if it does, what do I need to configure in my config.js for it to work?

Fundamentally, the reason for having such a thing is really the same reason I'd want to use a CDN with one difference that it's used only by the CMS.

I hope I've explained it well enough for you or anyone else to understand it. :)

**Comment by guybedford** [comment]
For version resolutions to work out, jspm does expect to be able to have the local `jspm_packages` folder contain the currently installed versions of a project. So it is best to look at it as a single project being used.

Hosting jspm_packages on a separate asset server is certainly encouraged though, and can be configured in SystemJS by setting the baseURL to be the remote server.

**Comment by eyalsk** [comment]
Hmm but how does this work?

So okay, for JSPM nothing changes, all packages are local they are just hosted by project B.

The issue is when I'm trying to consume these packages from project A then I have a quite a problem because my config.js is also stored remotely which is the place it should be because it is the place where all of the packages exist.

When I'm setting my baseURL in the config.js it looks for the application in that base url but the actual application is hosted in a different server.

The config.js I have is quite simple minus the maps I removed to keep it simple.
```js
System.config({
	baseURL: "/",
	defaultJSExtensions: true,
	transpiler: "none",
	paths: {
		"github:*": "jspm_packages/github/*",
		"npm:*": "jspm_packages/npm/*",
	}
});
```
Just for reference and clarity here are the urls to the servers.
project A is hosted at http://localhost:5000
project B is hosted at http://localhost:5005

Here is the error I'm getting.
```text
GET XHR http://localhost:5000/jspm_packages/npm/angular2@2.0.0-alpha.35/angular2.js [HTTP/1.1 404 Not Found 4ms]
no element found [angular2.js:1:1]
Error: XHR error (404 Not Found) loading http://localhost:5000/jspm_packages/npm/angular2@2.0.0-alpha.35/angular2.js
	Error loading http://localhost:5000/jspm_packages/npm/angular2@2.0.0-alpha.35/angular2.js as "angular2/angular2" from http://localhost:5000/app.js [system.js:4:0]
```

**Comment by guybedford** [comment]
Try setting the baseURL to `http://localhost:5005`?

**Comment by eyalsk** [comment]
Done!

Now I'm getting the following error.

```text
GET XHR http://localhost:5005/app.js [HTTP/1.1 404 Not Found 9ms]
no element found []app.js:1:1]
```

**Comment by guybedford** [comment]
Yes you'll need to create a path rule for your local app like `paths: { 'app/*': 'https://localhost:5000/*' }` or you can just do a page-level System.import - `System.import('/app.js')`.

**Comment by eyalsk** [comment]
When I'm adding { 'app/*': 'https://localhost:5000/*' to my paths I'm getting this error.
```text
GET XHR http://localhost:5005/app.js [HTTP/1.1 404 Not Found 0ms]
no element found []app.js:1:1]
Error: XHR error (404 Not Found) loading http://localhost:5005/app.js
	Error loading http://localhost:5005/app.js system.js:4:0
```
When I'm changing System.import('app') to System.import('/app.js') I'm getting the following error.
```text
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:5005/jspm_packages/npm/angular2@2.0.0-alpha.35/angular2.js. (Reason: CORS header 'Access-Control-Allow-Origin' missing). 
Error: XHR error loading http://localhost:5005/jspm_packages/npm/angular2@2.0.0-alpha.35/angular2.js
	Error loading http://localhost:5005/jspm_packages/npm/angular2@2.0.0-alpha.35/angular2.js as "angular2/angular2" from http://localhost:5000/app.js [system.js:4:0]
```

**Comment by guybedford** [comment]
In the first case you have to be loading inside a folder like `app/index.js`. In the second case, this is working, you just need to be setting the header on the remote server `Access-control-allow-origin: *` to indicate this isn't cross-site privilege escalation.

**Comment by eyalsk** [comment]
Okay, I'll try that asap.

Thank you so much for your time.

**Comment by eyalsk** [comment]
It seems to work! but now I get this error.

ReferenceError: System is not defined
