### ISSUE TITLE
Builder version control?

### ISSUE THREAD

**Issue by peteruithoven** [jspm/jspm-cli#1056]
I think I'm experiencing issue https://github.com/jspm/jspm-cli/issues/1032 and I'd like to use that experimental  systemjs/builder build, but I don't understand how I could control which builder version is used when I'm using `jspm bundle-sfx `?

The jspm cli has `dl-loader` methods for controlling the `browser loader files`, but not for the builder feature. I also can't find the builder in the jspm_packages folder.

**Comment by guybedford** [comment]
The fix has been pushed in jspm 0.16. We usually lock the version of the builder to the version of jspm, but you can do manual upgrades by doing an `npm install systemjs-builder@x` within jspm's package folder itself.

**Comment by guybedford** [comment]
Sorry I mean jspm 0.16.1 here.

**Comment by peteruithoven** [comment]
Ah, clear, thanks.

**Comment by peteruithoven** [comment]
For future reference, you can check the builder version using `npm ls`. 
``` bash
npm ls -g --depth 2 # list all globally installed npm packages 2 dependencies deep
npm ls --depth 2 # list all locally installed npm packages 2 dependencies deep
```
`jspm --version` will tell you whether you're using an locally or globally installed version of jspm.
