### ISSUE TITLE
jspm builds much slower since stable 0.16

### ISSUE THREAD

**Issue by jackfranklin** [jspm/jspm-cli#1057]
We just upgraded from 0.16-beta3 to 0.16 stable, and have seen a huge leap in build times.

Everything works fine, however our development build step which was at around ~5secs fresh and ~2 from cache has shot up to ~20 seconds plus from fresh, and not that much less for cached builds too.

Did anything change between the last beta and the first stable that might explain this? Nothing at our end has changed at all. The code we're using is below (edited slightly for readability):

```
var sharedCache = {};

DevBuilder.prototype.build = function() {
  this.builder = new jspm.Builder();

  var buildStart = Date.now();

  this.logInfo('jspm build starting');

  return this.builder.build('app/bootstrap', 'app/bundle.js', {
    minify: false,
    mangle: false,
  }, sharedCache).then(function() {
    var buildEnd = Date.now();
    logInfo('jspm build finished', chalk.red(buildEnd - buildStart));
  }
};
```

**Comment by guybedford** [comment]
@jackfranklin this is really great to know. Any chance you can see if jspm@0.16.0-beta.7 or jspm@0.16 has this regression as well? Ideally knowing the version would help a lot to suggest which changes it might have been.

**Comment by jackfranklin** [comment]
@guybedford sure thing, going to spend sometime today going through each beta to hunt down the cause.

**Comment by jackfranklin** [comment]
@guybedford so some very rudimentary benchmarking:

- 0.16.0-beta3: 6 seconds from fresh, 1.6 from cache
- 0.16.0-beta4: 12 seconds from fresh, 9 from cache
- 0.16.0-beta5: 15 seconds from fresh, 9 from cache

Didn't profile beta6 and 7 yet, looks like the difference is in beta3-beta4. Going to have a look through the diff now.

**Comment by guybedford** [comment]
@jackfranklin perhaps check the versions of SystemJS and SystemJS Builder in the node_modules carefully as well as they are set as ranges in the package.json.

**Comment by jackfranklin** [comment]
@guybedford found something of note. I updated our build script to log out what it has in the cache after finishing a build:

```
var sharedCache = {};

DevBuilder.prototype.build = function() {
  this.builder = new jspm.Builder();

  var buildStart = Date.now();

  this.logInfo('jspm build starting');

  return this.builder.build('app/bootstrap', 'app/bundle.js', {
    minify: false,
    mangle: false,
  }, sharedCache).then(function() {
    console.log('SHARED CACHE', sharedCache);
    var buildEnd = Date.now();
    logInfo('jspm build finished', chalk.red(buildEnd - buildStart));
  }
};
```

On __beta.3__, this outputs an absolutely huge object, as I would expect.

On __beta.4__, this outputs an entirely empty object, which would very much explain the slow down in builds!

**Comment by guybedford** [comment]
@jackfranklin ah that might help yes. Note that the cache API did change, as described in https://github.com/systemjs/builder/issues/232#issuecomment-124061105. Perhaps try using the `builder.setCache` and `builder.getCache` methods and see if that helps?

**Comment by jackfranklin** [comment]
@guybedford just checking SystemJS & builder versions.

__beta.3__:
- systemjs-builder __0.12.2__
- systemjs __0.18.16__

__beta.4__:
- systemjs-builder __0.13.4 __
- systemjs __0.18.9__

That seems like a weird mismatch of newer builder but older systemjs?

**Comment by jackfranklin** [comment]
@guybedford aha, so it seems like the caching API changes between systemjs-builder 0.12 and 0.13 are what's doing it for us.

I updated our build script to look more like:

```
var sharedCache = {};

DevBuilder.prototype.build = function() {
  this.builder = new jspm.Builder();
  this.builder.setCache(sharedCache);

  var buildStart = Date.now();

  this.logInfo('jspm build starting');

  return this.builder.build('app/bootstrap', 'app/bundle.js', {
    minify: false,
    mangle: false,
  }, sharedCache).then(function() {
    sharedCache = this.builder.getCache();
    var buildEnd = Date.now();
    logInfo('jspm build finished', chalk.red(buildEnd - buildStart));
  }
};
```

And this is an improvement; but still slower than the speeds we were getting previously. We're looking now at about __12 seconds__ from fresh and __3 seconds__ from cache.

**Comment by guybedford** [comment]
Ok great, yes it would still be nice to see where the loss comes from as that is very significant. It sounds like this is loss is still from the beta 3 to beta 4? That sounds like it would be the builder update from 0.12 to 0.13. Would be good to know if it is exactly the 0.13.0 builder release or one of the 0.13 patches.

**Comment by jackfranklin** [comment]
Yup, the loss looks like beta3 to beta4.

Is the best way to debug this to install 0.16.0-beta.4, and then start installing various versions of systemjs-builder in `node_modules/jspm` ?

**Comment by guybedford** [comment]
Yes I'd suggest installing builder 0.13.1 and SystemJS 0.18.8 inside the jspm/node_modules and jspm/node_modules/systemjs-builder/node_modules folders respectively. That would determine it was the 0.12 -> 0.13 upgrade exactly on the lowest of the ranges for the upgrade path.

**Comment by jackfranklin** [comment]
@guybedford OK, here's what I did:

```
[ in project root ] npm install jspm@0.16.0-beta.4
[ node_modules/jspm] npm install systemjs-builder@0.13.1 systemjs@0.18.8
[ node_modules/jspm/node_modules/systemjs-builder ] npm install systemjs@0.18.8

> jspm --version
0.16.0-beta.4
Running against local jspm install.
```

And the build times:
- From fresh: 10 sec
- From cache: 2.6-3 sec

So it would like something in that release caused it.

**Comment by jackfranklin** [comment]
@guybedford as an aside, how do we actually turn on trace caching and start working with it? Is that documented at all yet?

**Comment by jackfranklin** [comment]
@guybedford I put some very rough debugging into `systemjs-builder/lib/builder.js` in the `build` method:

```
  var startDate = Date.now();
  return this.trace(expression)
  .then(function(tree) {
    console.log('TRACE DONE', Date.now() - startDate);
    return self.buildTree(tree, outFile, opts);
  });
```

On a fresh build, the trace takes ~4.7 seconds (of ~10). On a cached build, the trace takes ~2.4 of the ~2.8 seconds. This is similar to the behaviour we saw pre SystemJS-Builder 0.13.1; the difference being that everything's just taken a little longer. Previously the tracing would be most of the time when we had a cached build, but it wouldn't take quite so long.

**Comment by guybedford** [comment]
@jackfranklin thanks, I've tried to run on a few hunches in https://github.com/systemjs/builder/commit/4e00229566fccf6b426e68710f3760a4a0c0cf76 to look into any possible duplications. Two main things that may help there are a fetch cache (probably minimal, but worth a shot), and more importantly there might have been some doubling up of the AMD parsing which is resolved.

Do you think you could test out the master branch there and see if there is any improvement at all? Otherwise I can take another shot as well.

**Comment by jackfranklin** [comment]
@guybedford they definitely help. Can't run the build on my work MBP right now to get comparable times, but running on my own MacBook Air (a little less powerful), doing:

```
cd node_modules/jspm && npm install systemjs/builder#master
```

Brings cached builds on this machine to just over 2 seconds, which is a definite improvement.

**Comment by guybedford** [comment]
@jackfranklin thanks for the follow-up - do let me know when you're able to tell if we're still running slower and I can see if there are further improvements to be made.

**Comment by jackfranklin** [comment]
@guybedford on my work MBP that's got fresh builds at about 9.5 seconds, and cached at about 1.9-2 seconds, so it's quicker but we're still down about 0.5 seconds on what we had in beta-3. Is there anything I can do to try and help you debug?

**Comment by guybedford** [comment]
@jackfranklin the most useful thing if you're interested in breaking down these numbers would be to add some perf timing logs to the builder project itself to understand where the time is being spent, and measure improvements. The main functions that are run are `traceExpression` (https://github.com/systemjs/builder/blob/master/lib/arithmetic.js#L112, which in turn calls a cached `getLoadRecord` at https://github.com/systemjs/builder/blob/master/lib/trace.js#L14), `compileOutputs` (https://github.com/systemjs/builder/blob/master/lib/compile.js#L63) and `writeOutputs` (https://github.com/systemjs/builder/blob/master/lib/output.js#L151). These are the running the trace, compiling the individual loads, and concatenation with minification steps respectively.

**Comment by guybedford** [comment]
Closing to track under builder performance issues.
