### ISSUE TITLE
flow support?

### ISSUE THREAD

**Issue by davis** [jspm/jspm-cli#1060]
is there a way to not have facebook's flow print:

```
composite-view.js:5:26,35: backbone
Required module not found

composite-view.js:6:29,40: marionette
Required module not found

composite-view.js:7:19,34: backbone.radio
Required module not found

composite-view.js:8:15,22: jquery
Required module not found

composite-view.js:9:15,22: lodash
Required module not found

composite-view.js:12:22,38: ./template.hbs!
Required module not found

Found 6 errors
```

when running flow?

**Comment by guybedford** [comment]
We could support Flow if Flow were to enable custom resolvers. I'm not sure what the status of that is there though.

**Comment by davis** [comment]
I'll open an issue on their repo, too about the status of cusom resolvers/jspm compatibility. thanks!

**Comment by guybedford** [comment]
Hopefully we can get this going eventually, lets track on the issue there.
