### ISSUE TITLE
Bundle bootstrap css

### ISSUE THREAD

**Issue by ielcoro** [jspm/jspm-cli#1061]
I´m unable to get bootstrap css inside my bundle (like font-awesome does for example).

```
jspm bundle bootstrap test.js
```

only bundles js files. However bootstrap package comes with css files, wich you can import inside index.html with System.import('bootstrap/css/bootstrap.css!'). However this only works in the dev version without bundles.

How can I get bootstrap css bundled with jspm?

**Comment by guybedford** [comment]
Answered at https://github.com/systemjs/builder/issues/292#issuecomment-135341849.
