### ISSUE TITLE
err  Error looking up github:github:systemjs/plugin-css@^0.1.15.

### ISSUE THREAD

**Issue by ncochard** [jspm/jspm-cli#1063]
Hello

I think I've just found an issue in the JSPM client. I don't think it's been reported before. Any help would be appreciated.

You can find detailed steps to recreate this bug at [https://github.com/ncochard/jspm-bug-01](https://github.com/ncochard/jspm-bug-01 "https://github.com/ncochard/jspm-bug-01")

Steps:

* Author you own package using JSPM and add a dependency to a package on GITHUB (e.g. github:systemjs/plugin-css)
* Publish this package to an NPM repository.
* Consume this package from a new project.

I'm getting the following error.

    err  Error looking up github:github:systemjs/plugin-css@^0.1.15.
(Note the duplication of the "github:".)

Any help would be greatly appreciated.

Best regards

**Comment by guybedford** [comment]
See https://github.com/jspm/jspm-cli/wiki/Publishing-Packages#publishing-jspm-style-packages-to-npm for information on how to publish jspm-style packages to npm.

The point is that without using a special property, we have to assume that all packages on npm obey the npm package.json conventions, not the jspm ones.

**Comment by ncochard** [comment]
Thank you for the quick reply.

For other people reading this thread, the solution is to add the following to the following to the package.json.

    {
		"jspm": {
			"jspmNodeConversion": false
		}
    }
