### ISSUE TITLE
problem with order loading modules

### ISSUE THREAD

**Issue by felixpis** [jspm/jspm-cli#1064]
We are using angular.js and elasticsearch.angular.js
When loading these libs with jspm, elasticsearch runs always before angular (and then "angular is not defined"). Is it possible to configure order of modules loading?

**Comment by guybedford** [comment]
Yes, you can configure load order using override configuration. This is the `shim` configuration in https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm#shim. You can see some examples in the jspm registry at https://github.com/jspm/registry/tree/master/package-overrides.

Let me know if you need further help here at all.

**Comment by felixpis** [comment]
Thanks! Now it works for me! :-)
Just had some problems with configuration of shim. Didn't know that it should be in overrides section.

**Comment by guybedford** [comment]
Great, thanks for following up.
