### ISSUE TITLE
Incorrect reference to the bundle.css.map

### ISSUE THREAD

**Issue by ncochard** [jspm/jspm-cli#1065]
Hello

I've illustrated my issue at this URL: [https://github.com/ncochard/jspm-bug-02](https://github.com/ncochard/jspm-bug-02).

If I bundle my css in a folder...

    jspm bundle lib/index dist/bundle.js

... then my bundle.css has an incorrect reference to the bundle.css.map...

Actual:   `/*# sourceMappingURL=dist/bundle.css.map*/`

Expected: `/*# sourceMappingURL=bundle.css.map*/`

This problem is illustrated if you right-click on an element in the browser and click on "Inspect Element".

Thank you for your help.

Best regards

**Comment by guybedford** [comment]
I tested out your example here and it's definitely working fine for me and was able to trace back to the original line of CSS fine. `bundle.css.map` is the correct sourceMappingURL as it is a relative URL. Are you sure you have CSS source maps enabled in the console settings here? Are you using Chrome?

**Comment by ncochard** [comment]
Dear @guybedford

I just realised that my example was not set-up properly.

I've modified my example to inject the bundle into the `config.js`. And I've changed the file `index.html` to only reference `config.js` rather than referencing `dist/bundle.js` directly. This should work better. Hopefully you will be able to recreate the issue if you pull the latest code of my example.

    jspm bundle lib/index dist/bundle.js --inject

- I'm using Chrome.
- The option "Enable CSS source maps" is definitely enabled.
- jspm@0.16.2
- plugin-css@0.1.15

Thanks a lot for your help.

Best regards

**Comment by guybedford** [comment]
@ncochard my dist file definitely contains `/*# sourceMappingURL=bundle.css.map*/` and not `dist/bundle.css.map`.

Check with `jspm -v` that you're definitely running the latest version of jspm here.

**Comment by ncochard** [comment]
I did further investigation...

I can recreate this issue on my **Windows 7** box, but not on my **linux** VM. I can try more operating systems tonight; but I suspect this issue is Windows specific.

    $ jspm -v
    0.16.2
    Running against local jspm install.

**Comment by ncochard** [comment]
I confirm that this is an issue on windows only.
Hopefully, you can recreate this issue consistently on windows machines too.

**Comment by guybedford** [comment]
Thanks I've fixed this up and pushed out a CSS 0.1.16 release.

**Comment by ncochard** [comment]
I confirm: this is fixed.
Thanks a lot for your help.
