### ISSUE TITLE
Uncaught ReferenceError: System is not defined

### ISSUE THREAD

**Issue by jrdmcgr** [jspm/jspm-cli#1066]
I'm trying to get es6 compiled into a bundle, but when I load the site I see this error in the console.

 >Uncaught ReferenceError: System is not defined  (build.js:1)

This is what I did to set this up.

```sh
mkdir jspm-example
cd jspm-example
npm install jspm-cli -g
npm install jspm --save-dev
jspm init  # accept default values
jspm bundle main --inject
```

This is my index.html

```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>JSPM Example</title>
    <script src="build.js"></script>
</head>
<body></body>
</html>
```

And this is main js

```main.js
export class Simple {
	static sayHello () {
		console.log('Hello!');
	}
}
```

Here are my versions.

```sh
$ node --version
v0.12.7
$ jspm --version
0.16.2
Running against local jspm install.
```

Am I missing something?

**Comment by egauci** [comment]
I think you want a bundle-sfx if you are including it with a script tag. See: https://github.com/jspm/jspm-cli/wiki/Production-Workflows

**Comment by jrdmcgr** [comment]
That works. Thanks!
