### ISSUE TITLE
Cannot use "import x from 'my-module'" if my module only exports one default function.

### ISSUE THREAD

**Issue by ncochard** [jspm/jspm-cli#1068]
Hello

I've illustrated this issue at the following URL: [https://github.com/ncochard/jspm-issue-03-application](https://github.com/ncochard/jspm-issue-03-application).

I have created using JSPM [one module](https://github.com/ncochard/jspm-issue-03-module) that exports the following `default` function:

	export default function(){
  		return "Hello world...";
	}
 
From the [application](https://github.com/ncochard/jspm-issue-03-application), I should be able to reference it using the following syntax, but `x` is always undefined.

    import x from 'jspm-issue-03-module';
	(function() {
		console.log(x);//ERROR: x is undefined
	})();

However, if I import the `/index` module directly, it works.

    import y from 'jspm-issue-03-module/index';
	(function() {
		console.log(y);//y is not null
	})();

**Is that a bug in SystemJS?**

Thank you for your help.

Best regards

**Comment by guybedford** [comment]
This was a bug with jspm 0.15, but was fixed in 0.16. Are you running the latest version here?

**Comment by ncochard** [comment]
Hello

I was running jspm version `0.15.7`. I confirm that this is fixed in version `0.16.2`.

Thank you for the quick reply.

Best regards
