### ISSUE TITLE
bundle .ts file issue

### ISSUE THREAD

**Issue by ron-liu** [jspm/jspm-cli#1069]
I am using typescript with jspm, and it report errors when I try to bundle them using:  
```
jspm bundle app 
```
or
```
jspm bundle app typescript
``` 

**The errors are: (I am using iojs, but same error will occur using node 0.12)**
err  TypeError: transpiler.transpileModule is not a function
         at /Users/ronliu/.nvm/versions/io.js/v3.0.0/lib/node_modules/jspm/node_modules/systemjs-builder/compilers/esm.js:107:35
         at process._tickCallback (node.js:356:9)

My config.js file are:
```
System.config({
  baseURL: "/",
  defaultJSExtensions: true,
  transpiler: "typescript",
  babelOptions: {
    "optional": [
      "runtime",
      "optimisation.modules.system"
    ]
  },
  typescriptOptions: {
    "module": "commonjs",
    "emitDecoratorMetadata": true
  },
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*",
    "app": "src"
  },

  packages: {
    "src": {
      "main": "main.ts",
      "defaultExtension": "ts"
    }
  },

  map: {
    "angular2": "npm:angular2@2.0.0-alpha.35",
    ...
 }
```

And the system.js version  is **0.18.9**. 

Anyone can help?

Thanks,
Ron

**Comment by guybedford** [comment]
It sounds like you're using an incompatible version of TypeScript - which version are you running there?

**Comment by guybedford** [comment]
(run `jspm dl-loader --latest` to install the latest TypeScript version).

**Comment by ron-liu** [comment]
Both config.js and "tsc -v" tell me it is Version 1.5.3. I also did "jspm -loader --latest", and I was told it is up to date.

**Comment by guybedford** [comment]
TypeScript 1.5.3 isn't compatible with bundling. Make sure you're running jspm 0.16 (`jspm -v` should show 0.16.2 for the latest version), then try running `jspm dl-loader --latest` again.
