### ISSUE TITLE
jspm update --save

### ISSUE THREAD

**Issue by honzajde** [jspm/jspm-cli#1072]
How to save updates to package.json? Thx

**Comment by guybedford** [comment]
Packages are by default saved into the package.json. Just let me know if you have any more questions on this at all.

**Comment by honzajde** [comment]
So my _package.json_ looks something like this:
<pre> 
  "jspm": {
    "directories": {
      "baseURL": "app",
      "lib": "app/src"
    },
    "dependencies": {
      "angular": "github:angular/bower-angular@^1.4.1",
...
</pre>

When I run `jspm update`, my config.js gets updated:
<pre>
System.config({
  "map": {
    "angular": "github:angular/bower-angular@1.4.5",
...
</pre>
(And jspm_packages too)

However my package.json stays unchanged - I would expect updated versions, and you confirmed that too. So there must be something bad with my configuration.

**Comment by guybedford** [comment]
@honzajde `jspm update` will update the config file only, the package.json represents the ranges, while the config.js represents the exact resolution. Updates don't bump the ranges by default (although this has been discussed, and may still be an option) as you may wish to allow older versions.

**Comment by honzajde** [comment]
Thanks for explanation. This means that if I copy my project to it's deployment location and say `jspm install` or `jspm update` I can get different versions of packages then I have in my development location. This seems entirely wrong to me - how do I preserve consistency between environments. Please, correct me if I am wrong.

**Comment by guybedford** [comment]
The config.js versions represent the version lock, not the package.json version. When you run `jspm install` it will by default ensure the exact same versions in the current config.js file are installed to replicate. See https://github.com/jspm/jspm-cli/wiki/Installing-Packages#reproducible-installs.

**Comment by jimschubert** [comment]
The wiki link doesn't appear to exist any longer.

Here's the update link: https://github.com/jspm/jspm-cli/blob/master/docs/installing-packages.md#reproducible-installs

**Comment by heruan** [comment]
I think it would be useful to have an option to save in `package.json` the latest version in the range: `jspm update --save` seems a logic option.

**Comment by jerryorta-dev** [comment]
+1  
As an option would be nice.

**Comment by chendachao** [comment]
it would be fine if it allows interact with user and can save exact version like `npm-check -Eu` did
