### ISSUE TITLE
"Module {name} not present" when using SFX bundle

### ISSUE THREAD

**Issue by mbreedlove** [jspm/jspm-cli#1073]
I ran a gulp task with the following: 

	jspm.bundleSFX(resolveToApp('app'), dist, {
			mangle: false,
			minify: false,
			sourceMaps: true
		})
	});

When I load the page I get the following error: 

       Uncaught Module 30 not present.

Excerpt from sfx-bundle:

	$__System.registerDynamic("13", ["30"], true, function(require, exports, module) {
	  ;
	  var global = this,
	      __define = global.define;
	  global.define = undefined;
	  module.exports = require("30");
	  global.define = __define;
	  return module.exports;
	});

I confirmed there is no call to `registerDynamic("30", ...)`. 

I wasn't sure if this was a JSPM issue or a SystemJs issue.

**Comment by guybedford** [comment]
Can you confirm which version of jspm you are running here?

**Comment by mbreedlove** [comment]
I was running jspm 0.16.0-beta7 when I first encountered this, I then updated to 0.16.2 and still had the issue.

**Comment by guybedford** [comment]
Sure, any chance you can share a minimal test case for this at all?

**Comment by mbreedlove** [comment]
Unfortunately I can't seem to reproduce it from scratch. 

However I thought to just run `jspm bundle`, since it doesn't seem to mangle module names, so I could compare it to the mangled output of the sfx bundle. Looking at the output side-by-side of both, I believe the `registerDynamic` call in my first post is a mangled version of the following:

	System.registerDynamic("github:necolas/normalize.css@3.0.3", ["github:necolas/normalize.css@3.0.3/normalize.css!github:systemjs/plugin-css@0.1.15"], true, function(require, exports, module) {
	  ;
	  var global = this,
	      __define = global.define;
	  global.define = undefined;
	  module.exports = require("github:necolas/normalize.css@3.0.3/normalize.css!github:systemjs/plugin-css@0.1.15");
	  global.define = __define;
	  return module.exports;
	});

Hopefully that's of some use to you.

**Comment by guybedford** [comment]
@mbreedlove there was an issue with this that was patched in jspm 0.16.2, so I'm wondering if this could still be from that somehow. Was there a `System.registerDynamic(""github:necolas/normalize.css@3.0.3/normalize.css!github:systemjs/plugin-css@0.1.15""...` in the bundle there? If you run `jspm install -f` do you still get the error?

**Comment by guybedford** [comment]
Let me know if you are still having issues here.

**Comment by ludbek** [comment]
I am having similar problem. I created a build excluding `mithril` with the command `jspm bundle-sfx app.js - mithril --globals "{mithril:'m'}"`. When I load the build in browser I get following error. Mithril.js is separately loaded before loading the build.

Uncaught Module 3 not present.

**Comment by guybedford** [comment]
@ludbek I think this could be a duplicate of https://github.com/systemjs/builder/issues/444.

**Comment by Xample** [comment]
Same issue here, did anyone found a solution ?

**Comment by polyclick** [comment]
Me too, build using:

```
gulp.task('buildjs', function () {
  gulp.src('assets/js/app.js')
    .pipe(jspm({
      selfExecutingBundle: true,
      minify: true,
      skipSourceMaps: true
    }))
    .pipe(rename('app.min.js'))
    .pipe(gulp.dest('./assets/js'));
});
```
