### ISSUE TITLE
jspm install forces defaultJSExtensions=true (0.16.2)

### ISSUE THREAD

**Issue by neothemachine** [jspm/jspm-cli#1074]
Whenever I do a `jspm install` it sets `defaultJSExtensions: true` in the config.js. When I manually removed it and tried to create a bundle it failed with an error that it couldn't load babel. Is defaultJSExtensions enabled automatically because I use babel and babel needs this for compatibility? I rewrote all my files to include `.js` in imports. Won't this conflict if defaultJSExtensions is true?

**Comment by neothemachine** [comment]
After reading the 0.16 release notes again, I see that defaultJSExtensions is enabled as part of the SystemJS 0.18 two-step upgrade path and will be disabled with jspm 0.17. Still, I wonder why my imports work with `.js` even though defaultJSExtensions is true.

**Comment by guybedford** [comment]
Yes, `defaultJSExtensions` will only add `.js` extensions when not already present, which is actually breaking against the previous behaviour.

**Comment by zeeshanjan82** [comment]
@guybedford  I have found that setting defaultJSExtensions to true also unnecessarily adds the .js extension to all the html files as well which are imported. Any thoughts?

**Comment by guybedford** [comment]
@zeeshanjan82 use package configuration to opt-out of default extensions, as described in https://github.com/systemjs/systemjs/blob/master/docs/overview.md#basic-use.

**Comment by zeeshanjan82** [comment]
Thanks @guybedford I was able to move ahead, however I am not getting the following error in systemjs
````js
Uncaught TypeError: Unexpected anonymous System.register call.
`````
What could be the cause of this error?
