### ISSUE TITLE
Unable to read global configuration file (invalid JSON in .jspm/config)

### ISSUE THREAD

**Issue by Mosho1** [jspm/jspm-cli#1076]
This is my global `.jspm/config`:

    {
      "defaultTranspiler": "babel",
      "defaultRegistry": "jspm",
      "strictSSL": true,
      "registries": {
        "github": {
          "handler": "jspm-github",
          "remote": "https://github.jspm.io"
        },
        "npm": {
          "handler": "jspm-npm",
          "remote": "https://npm.jspm.io"
        },
        "jspm": {
          "handler": "jspm-registry",
          "remote": "https://registry.jspm.io"
        }
      }
    }     "remote": "https://npm.jspm.io"
        },
        "jspm": {
          "timeouts": {
            "lookup": 60,
            "build": 120
          },
          "handler": "jspm-registry",
          "remote": "https://registry.jspm.io"
        }
      }
    }

Which is invalid. Not sure what I did today that tried to update this. Using 0.16.0

**Comment by guybedford** [comment]
This can happen if you ran two instances of jspm simultaneously, we're not currently set up for write locking the config file.
