### ISSUE TITLE
Control jspm's config.js output

### ISSUE THREAD

**Issue by Mosho1** [jspm/jspm-cli#1077]
I'd like `paths` in config.js to be set by me and not jspm. So either set what is put in the json or omit `paths` entirely. Any built-in way to do that?

**Comment by jdanyow** [comment]
I have a related issue- when I run any jspm command it modifies the paths config.  I'm sure I don't have something configured correctly- here's what happens after running `jspm install`:

![jspm install](http://i.imgur.com/Cz9AClM.png)

The leading `/` is removed, which I have to re-add afterwords to make things work properly.

What do I need to change to either preserve the leading `/` or achieve the same result through some other config point?  I tried a few things with `baseUrl` with no success.

**Comment by guybedford** [comment]
@jdanyow rather set `baseURL: '/`` here (the client baseURL prompt when running `jspm init -p`). The registry paths do need to be managed by jspm though. @Mosho1 you can add extra paths here fine and they will be maintained, but you can't alter the existing ones.

**Comment by jdanyow** [comment]
oh my bad- I was using `baseUrl` instead of `baseURL`!  Thanks for the tip
