### ISSUE TITLE
JSPM with Electron and React

### ISSUE THREAD

**Issue by matthewfowles** [jspm/jspm-cli#1078]
Hi 

I have a project with electron and react. I would like to use JSPM to build this. However I have hit a few road blocks.

1. JSX

I wanted to use JSX which babel should compile out of the box. I have got this working with one small problem. I have to change this line in the config.js ` defaultJSExtensions: false`. This is all fine however when I install anything it changes back. Is there anyway to force it to stay like this?

2. Import

Here is my index.html 

``` html
<!DOCTYPE html>
<html>
  <head>
    <title>Conductor</title>
  </head>
  <body style="padding: 0; margin: 0;">
    <script src="jspm_packages/system.js"></script>
    <script src="config.js"></script>
    <script>
      var React = System._nodeRequire('react');
      var app = System.import('./components/index.jsx');
      React.render(React.createElement(app), document.body);
    </script>
  </body>
</html>

```

I encoutered a problem where I could not `System.import()` installed dependencies so I have to use `System._nodeRequire`. However when I run this there is an issue due to JSPM detected ES6 || ES2015 and not being able to import babel-core. 

<img width="465" alt="screen shot 2015-08-31 at 21 20 22" src="https://cloud.githubusercontent.com/assets/622010/9589435/3edb269e-5026-11e5-8262-bcc3e6ecb99b.png">

I am not sure how to get around this. Is this a project where I should use an alternative to JSPM and may babelify and browserify all the files myself?

Any help would be appreciated want to make sure I am not heading down the wrong road.

Thanks

**Comment by guybedford** [comment]
You need to keep `defaultJSExtensions` set to true in jspm 0.16. This will only be disabled in jspm 0.17. That is the reason your dependencies aren't loading properly. Using `System._nodeRequire` is not advisable.

To be able to load jsx, you need to create a package that sets `defaultExtension: false` that will allow you to skip `defaultJSExtensions` for a folder. See https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#packages for more info.

**Comment by matthewfowles** [comment]
Thanks guy

I am however still having issues with paths etc after creating a package. I think all I really need is babel in the HTML file transforming everything after. I am also planning to use material-ui and I will it problems there. 

But thanks for the advice :)
