### ISSUE TITLE
Timeout on installing package

### ISSUE THREAD

**Issue by nicklasb** [jspm/jspm-cli#1079]
Hi, so I am installing a package and then I am getting into trouble.

The interesting thing is that it has recently started complaining, this is the command.

```bash
$ jspm install npm:angular-schema-form
     Looking up npm:angular-schema-form
     Updating registry cache...
     Downloading npm:angular-schema-form@0.8.8
     Looking up npm:angular
     Looking up npm:tv4
     Looking up npm:angular-sanitize
     Looking up npm:objectpath
     Looking up github:jspm/nodelibs-process
     Looking up npm:process
```

For some reason it always time out on npm:process.
I am not sure if it is actually that one, or eiter lookup that doesn't return. 
I am starting to think that perhaps a verbose mode could be pretty useful.

**Comment by guybedford** [comment]
The `process` dependency here is the one from GitHub, so that you may have been running this while GitHub was experiencing stabillity issues. It can be worth checking http://status.github.com/ as that is usually the cause here.

**Comment by nicklasb** [comment]
I just ran it, and it still stops at the same point.
If I just run `jspm install`, I get this:

```bash
$ jspm install
     Looking up npm:angular-schema-form-dynamic-select
     Looking up npm:objectpath
     Looking up npm:tv4
     Looking up npm:process
     Looking up npm:typescript
     Updating registry cache...
     Looking up github:angular/bower-angular-sanitize
     Looking up github:Textalk/angular-schema-form
     Looking up github:angular/bower-angular-route
     Looking up github:angular/bower-angular-animate
     Looking up github:angular/bower-angular
     Looking up github:mgcrea/angular-strap
     Looking up github:angular/bower-angular-touch
     Looking up github:angular-ui/ui-layout
     Looking up github:angular-ui/ui-select
     Looking up github:angular-ui-tree/angular-ui-tree
     Looking up github:twbs/bootstrap
     Looking up github:systemjs/plugin-css
     Looking up github:nakupanda/bootstrap3-dialog
ok   Up to date - objectpath as npm:objectpath@^1.2.1 (1.2.1)
ok   Up to date - tv4 as npm:tv4@^1.2.3 (1.2.3)
     Looking up npm:angular-schema-form
ok   Up to date - angular-schema-form as github:Textalk/angular-schema-form@0.8.8 (0.8.8)
ok   Up to date - angular as github:angular/bower-angular@^1.4.3 (1.4.4)
ok   Up to date - angular-animate as github:angular/bower-angular-animate@^1.4.3 (1.4.4)
ok   Up to date - angular-route as github:angular/bower-angular-route@^1.4.3 (1.4.4)
ok   Up to date - angular-sanitize as github:angular/bower-angular-sanitize@^1.4.3 (1.4.4)
ok   Up to date - angular-touch as github:angular/bower-angular-touch@^1.4.3 (1.4.4)
ok   Up to date - angular-ui-tree as github:angular-ui-tree/angular-ui-tree@^2.6.0 (2.8.0)
ok   Up to date - angular-ui-select as github:angular-ui/ui-select@^0.12.1 (0.12.1)
ok   Up to date - angular-strap as github:mgcrea/angular-strap@^2.3.1 (2.3.1)
ok   Up to date - angular-ui-layout as github:angular-ui/ui-layout@^1.0.5 (1.1.0)
     Looking up npm:angular-strap
     Looking up npm:bootstrap
     Looking up github:jmcriffey/bower-traceur-runtime
     Looking up github:jmcriffey/bower-traceur
     Looking up npm:ui-select
     Looking up github:components/jquery
ok   Up to date - css as github:systemjs/plugin-css@^0.1.13 (0.1.15)
     Looking up github:jspm/nodelibs-fs
     Looking up github:jspm/nodelibs-os
     Looking up github:jspm/nodelibs-child_process
     Looking up github:jspm/nodelibs-path
     Downloading npm:angular-schema-form@0.8.8
     Looking up github:jspm/nodelibs-process
     Looking up github:jspm/nodelibs-readline
     Looking up github:jspm/nodelibs-buffer
     Looking up npm:angular
     Looking up npm:angular-sanitize
     Looking up github:jspm/nodelibs-assert
ok   Up to date - jmcriffey/bower-traceur as github:jmcriffey/bower-traceur@^0.0.91 (0.0.91)
ok   Up to date - jmcriffey/bower-traceur-runtime as github:jmcriffey/bower-traceur-runtime@0.0.91 (0.0.91)
ok   Up to date - jquery as github:components/jquery@^2.1.4 (2.1.4)
ok   Up to date - bootstrap as github:twbs/bootstrap@^3.3.5 (3.3.5)
ok   Up to date - bootstrap3-dialog as github:nakupanda/bootstrap3-dialog@^1.34.5 (1.34.5)
     Looking up npm:os-browserify
     Looking up npm:path-browserify
     Looking up npm:buffer
     Looking up npm:assert
     Looking up github:systemjs/plugin-json
     Looking up npm:base64-js
     Looking up npm:ieee754
     Looking up npm:is-array
     Looking up npm:util
     Looking up npm:inherits
ok   Up to date - typescript as npm:typescript@^1.5.3 (1.5.3)
     Looking up github:jspm/nodelibs-util
ok   Up to date - process as npm:process@^0.11.1 (0.11.1)

warn It's taking a long time to process the dependencies of npm:angular-schema-form@0.8.8.
     This package may need an ignore property to indicate test or example folders for jspm to skip.

Killed
```

If I run `jspm install angular-schema-form`, i get this:
```bash
$ jspm install angular-schema-form
     Updating registry cache...
     Looking up github:Textalk/angular-schema-form
ok   Up to date - angular-schema-form as github:Textalk/angular-schema-form@^0.8.8 (0.8.8)
     Installed Forks

                                  npm:process 0.10.1 0.11.1
                                      npm:tv4 1.0.18 1.2.3

     To inspect individual package constraints, use jspm inspect registry:name.


warn typescript@1.5.3 is unsupported for this version of jspm. Use jspm dl-loader to update.

ok   Install complete.
```

If I use the npm-package instead,  `jspm install npm:angular-schema-form`, i get this:
```bash
jspm install npm:angular-schema-form
     Looking up npm:angular-schema-form
     Updating registry cache...
     Downloading npm:angular-schema-form@0.8.8
     Looking up npm:angular
     Looking up npm:tv4
     Looking up npm:angular-sanitize
     Looking up npm:objectpath
     Looking up github:jspm/nodelibs-process
     Looking up npm:process

warn It's taking a long time to process the dependencies of npm:angular-schema-form@0.8.8.
     This package may need an ignore property to indicate test or example folders for jspm to skip.

Killed
```

I am not entirely sure how to interpret these results.

**Comment by nicklasb** [comment]
I has been doing this consistently for a week now, so I am thinking that something else than stability issues must be involved.

**Comment by guybedford** [comment]
Ok then this is exactly as the warning says that it is taking a long time to run the node conversion on the package. Note that the version in the jspm registry is the GitHub repo not the npm version at https://github.com/jspm/registry/blob/master/registry.json#L54. The options would be:

1. Find out whatever is dependent on angular-schema-form and use an override to make it use the GitHub version of angular-schema-form instead (likely `npm:angular-schema-form-dynamic-select`)
2. Instead of installing `npm:angular-schema-form-dynamic-select` install the github version with an override.
3. Alter the override for `npm:angular-schema-form` so that it works as expected. There are likely test or library folders that are being converted unnecessarily that can be skipped via ignore rules to make the conversion quicker.

**Comment by nicklasb** [comment]
Ok, thanks!

**Comment by guybedford** [comment]
The other option is of course to increase the npm build timeout and leave it to run through. After that it will be cached so you shouldn't have the issue again until you update, but obviously its not ideal.

**Comment by nicklasb** [comment]
Yes, and as I now realize that this isn't about network timeouts but actual processing time, it would, but the host I am having problems with is running on a micro instance on amazon, so that is probably why it times out. I am not having this problem on my development host.

Either way, something probably has to be changed in the packages, I am leaning towards using github-ones instead, as I understand that needs less conversion.

**Comment by nicklasb** [comment]
Um...how do I set the build timeout? 
I have seen the timeout.build, but I do not know where to put it, in the jspm_config or where?

**Comment by guybedford** [comment]
The warning on the timeout should be including the command to use as of a recent patch, but it is:

`jspm config registries.npm.timesouts.build 600` where the value is in seconds.

**Comment by nicklasb** [comment]
Aha, I should've be a little `--egde`ier. :-)
Thanks!

**Comment by nicklasb** [comment]
Still having same problem, are you sure about the spelling of the setting?
jspm config registries.npm.<b>timesouts</b>.build 600

**Comment by guybedford** [comment]
Yes, the above would be a 10 minute timeout, perhaps increase it further if you're still hitting it?

**Comment by guybedford** [comment]
(yes its a plural is it contains multiple timeouts on the config property)

**Comment by guybedford** [comment]
Did you manage to sort this out?

**Comment by nicklasb** [comment]
No, haven't tried for a while though.
