### ISSUE TITLE
Saving to config removes functions

### ISSUE THREAD

**Issue by Rush** [jspm/jspm-cli#1083]
This is what I had in my `config.js`:
```js
System.config({
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {}
  /* .. other stuff here .. */
  locate: function(file) {
    // custom logic here
    return file.name;
  }
});
````
After running `jspm depcache`, my `locate` key has disappeared.

Essentially with this custom function I had support for running `jspm depcache` (and other function) with multiple baseURL.

**Comment by guybedford** [comment]
Yes any type of computed property is not supported in the machine-generated config file, it's best to use a separate file for these types of configurations.
