### ISSUE TITLE
Allow `jspm install` without clean

### ISSUE THREAD

**Issue by stefanr** [jspm/jspm-cli#1085]
Currently I reuse the `jspm_packages` folder for several local sub packages to share their dependencies as well as SystemJS. In my opinion this shouldn't be a problem since all packages are versioned.

But executing `jspm install` removes "unused" packages which are required by other local packages.

Folder structure:
```
/jspm_packages
/packages
    /foo
        /jspm_packages (symlink)
        ...
    /bar
        /jspm_packages (symlink)
        ...
```

I would suggest an option to skip the cleaning after install, probably even make that the default and require a flag to start the cleaning action.

**Comment by guybedford** [comment]
It can be worth supporting symlinked jspm_packages folders here perhaps even supporting jspm managing the symlink itself to the global cache folder eventually so one always uses that.

How about an exception for now where if jspm_packages is symlinked, the clean function doesn't act on it?

**Comment by stefanr** [comment]
+1 managed symlink support, but this needs options in the `package.json`, e.g.:

```js
"jspm": {
  "directories": {
      "jspmPackages": {
        "path": "jspm-pkgs",  // "jspmPackages": "jspm-pkgs"
        "useGlobalCache": true
        "symlinkDest": "../../jspm_packages",
        "shared": true, // other packages might use this directory (useGlobalCache, symlinkDest -> true)
      }
    }
}
```
