### ISSUE TITLE
"jspm dl-loader --edge" doesn't upgrade to TypeScript 1.6.0-beta

### ISSUE THREAD

**Issue by juergenzimmermann** [jspm/jspm-cli#1089]
I'm using jspm 0.16.2
When I'm doing `jspm dl-loader --edge` then I get `typescript@1.6.0-dev.20150825` although 1.6.0-beta is available since yesterday (2015-09-02) at the NPM registry.

**Comment by guybedford** [comment]
This is actually a limitation of semver - the version `1.6.0-dev.20150825` is actually a greater version according to semver than `1.6.0-beta`. Try using `jspm install typescript@1.6.0-beta` directly here rather.
