### ISSUE TITLE
Persist registry overrides themselves in the package.json

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#1090]
When setting a custom override, we should then store the compound override into the package.json. overrides in the package.json then no longer merge with the registry overrides.

The upgrade path here involves updating the package.json with the compound overrides.

This will then make the derivation clearer, as the package config is then clearly just the package.json combined with the override, instead of having this invisible jspm registry layer that is very difficult to get insight into currently.

It will also allow overrides to be changed in the registry without that being a breaking change for existing installs, giving full control of the environment to the consumer, only using them for the first install, which is a valuable property to have.

In addition, **this will bloat the package.json**, which bear with me - isn't a bad thing. It shows that overrides should not really be used, and encourages users to want to get them merged into the original repos.

We can potentially even enable transitive overrides with such a workflow, by publishing packages with overrides for their dependencies in turn in the package.json, since we now have an explicit detection of the conflict scenario, and can alert users when two overrides clash on the same package.

With all the above we need to provide this along with clear messaging that overrides can be published in the original repo. Later on posting overrides can be handled automatically by a PR bot.

Feedback welcome.

**Comment by lookfirst** [comment]
Having been bitten by this in the past, this sounds great. 

For the bloat, there is always the option of adding support for something like this in package.json:

```
jspm: {
  jspm_config: './jspm.json'
}
```

**Comment by SomethingSexy** [comment]
I think this sounds great! I am coming across this issue now.  What is the suggested work around until this gets added? I am in the process of going a heavy conversion to jspm, so still trying to figure things out.

**Comment by guybedford** [comment]
@SomethingSexy we always ensure that the jspm registry overrides are backwards compatible, and manual overrides via `jspm install x -o "{...}"` will always persist, so there is no work around necessary, this is more of an isolation feature if anything.

**Comment by SomethingSexy** [comment]
@guybedford where does a ```jspm install x -o "{...}"``` persist that?  The project I am working on will need to be run locally by potentially a lot of developers.  I wouldn't want them to have to do anything special when running an generic install if I can avoid it.

**Comment by guybedford** [comment]
Overrides persist into the package.json when used with that syntax, and will continue to be used.

**Comment by SomethingSexy** [comment]
@guybedford thanks! I probably could have just tried that myself so I didn't have to waste anyone's time.

**Comment by guybedford** [comment]
Released in jspm 0.17 beta.
