### ISSUE TITLE
0.16.x breaks Gulp workflows

### ISSUE THREAD

**Issue by gconaty** [jspm/jspm-cli#1093]
The core issue is that in 0.15.? it was possible to have the jspm_packages directory not a subdirectory of the baseURL.  e.g. "warn jspm_packages must be specified in the package.json within the baseURL for paths to resolve correctly."

see this for a related issue. https://github.com/abiee/es6-marionette/issues/4

I'm not sure why this changed but is there a different recommendation to have the libs separate from the app?  Many projects need to pre-process assets first using Gulp or similar (e.g. handlebars, Less) copying them to a (dist/target) directory before gathering the JS dependencies.

**Comment by guybedford** [comment]
Yes, baseURL does need to be the lowest common path.
