### ISSUE TITLE
bundle-sfx throws ENOENT in v0.16.0 but works when downgraded to 0.15.7

### ISSUE THREAD

**Issue by tryggvigy** [jspm/jspm-cli#1094]
Hey,

I noticed the following command breaking on my server but working on my dev machine due to slightly different versions in jspm installed.
~~~sh
jspm bundle-sfx app/scripts/common/common dist/scripts/common.js --minify --skip-source-maps
~~~

Error output:
>err  Error: ENOENT, open '/home/......../app/scripts/common/common'
     Building the single-file sfx bundle for app/scripts/common/common + app/scripts/admin/admin...

Any insights?

**Comment by guybedford** [comment]
I'd need to know the relevant config to look into this - are you able to share an isolated replication at all?

**Comment by tryggvigy** [comment]
I assume you mean the config.js file. I don't want to bloat this comment with miscellaneous
package mappings so here is the slimmed down version.
~~~js
/* jshint ignore: start */
System.config({
  "transpiler": "babel",
  "babelOptions": {
    "optional": [
      "runtime"
    ]
  },
  "paths": {
    "*": "*.js",
    "github:*": "jspm_packages/github/*.js",
    "npm:*": "jspm_packages/npm/*.js"
  }
});

System.config({
  "map": {
    "babel": "npm:babel-core@5.8.20",
    "babel-runtime": "npm:babel-runtime@5.8.20",
    "core-js": "npm:core-js@0.9.18",
    "jquery": "github:components/jquery@2.1.4",
    "marked": "npm:marked@0.3.5",
    "particles-js": "github:VincentGarreau/particles.js@2.0.0",
    "superagent": "npm:superagent@1.2.0",
    "github:jspm/nodelibs-assert@0.1.0": {
      "assert": "npm:assert@1.3.0"
    },
    .
    . 
    .
    "npm:vm-browserify@0.0.4": {
      "indexof": "npm:indexof@0.0.1"
    }
  }
});
/* jshint ignore: end */
~~~
Thanks for taking the time, I'm glad this repo is so well maintained.

**Comment by guybedford** [comment]
Sure, no problem at all. This looks like jspm 0.15 configuration - I'd suggest reading the 0.16 release notes at https://github.com/jspm/jspm-cli/releases/tag/0.16.0 and making sure to follow the points, specifically running `jspm init` first.

**Comment by tryggvigy** [comment]
Argh, should have looked closer at this before opening an issue. Thanks, closing!
