### ISSUE TITLE
Error message documentation

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#1095]
A page at `troubleshooting.md` that covers common errors and common solutions.

In addition jspm errors can link to the relevant section of the errors page.

**Comment by adriatic** [comment]
There is a typo above ``troubleshooting,md`` should be ``troubleshooting.md``

I decided to get engaged a bit deeper, by acting as a proxy between you (Guy) and the whole bunch of Aurelia Developers - see **[this](https://github.com/aurelia-guides/aurelia-jspm-issues/blob/master/README.md)** for the description of the process I proposed to Aurelia folks.

Note that I am not looking for more work - the idea of proxying comes as the consequence of my understanding that it might be easier for you to be presented with the whole bunch if Aurelia - jspm issue, hopefully with the author's explanation how did he resolve it) than to wait for new issues creep in slowly and try to resolve them in order to define the correct "extended issue explanation" to be stored in the ``troubleshooting.md`` file.

By the way - where is that ``troubleshooting.md`` file?

**Comment by guybedford** [comment]
This sounds great. Having a channel for feedback would be useful, and we can use these troubleshooting pages to handle a good portion of that. Let me know if https://github.com/systemjs/systemjs/pull/771 seems like a good initial direction on this.

**Comment by adriatic** [comment]
I left one step of this workflow undefined - what happens with the content of the [issues list](https://github.com/aurelia-guides/aurelia-jspm-issues/issues)?

I would propose that it is better if you take stuff out that list seeing the uncensored discussion about each problem, than me "sending" you some opinionated interpretation of each issue.

Your call, however, as all this is created to help you :-)

**Comment by guybedford** [comment]
@adriatic unfortunately I can't be personally responsible for an Aurelia-focused issue queue. I can work on jspm bugs and support issues and am happy here to expand that to put together some form of common problem troubleshooting guide, but I can only respond to issues that immediately and succinctly fall under these categories, as specific points to include in the troubleshooting guide.

**Comment by adriatic** [comment]
This is a misunderstanding - all the issues that will appear in https://github.com/aurelia-guides/aurelia-jspm-issues/issues are of the same type: 
> jspm bugs and support issues and am happy here to expand that to put together some form of common problem troubleshooting guide, but I can only respond to issues that immediately and succinctly fall under these categories, as specific points to include in the troubleshooting guide

More importantly, I offered help, not more work, so I am quite happy to process the "raw data" accumulated in https://github.com/aurelia-guides/aurelia-jspm-issues/issues -- you only have to tell me where should I save them for you for final processing?

**Comment by guybedford** [comment]
@adriatic perhaps cc me in on issues there that require further action or guidance from a jspm perspective?

**Comment by adriatic** [comment]
Sorry, Guy - not being sure how to "cc" you to let you know about the newly posted issue https://github.com/aurelia-guides/aurelia-jspm-issues/issues/3 that I thought you should see, I sent you the invitation to that repo.

**Comment by guybedford** [comment]
Sure, I'll read this when I can. You can cc me by '@' name and that sends notifications with GitHub.

**Comment by adriatic** [comment]
> You can cc me by '@' name 

where should I place such cc @guybedford ?

**Comment by adriatic** [comment]
Also no need to say "I'll read this when I can" - I am collecting these issues not to press on you with the answer, but to prevent you from searching around for issues to fix :-) (not likely the case).

I will see when you address it and then I will be happy to see how :-) (You are a very polite fellow - I would love to have a chat with your parents, Guy)

**Comment by guybedford** [comment]
Sure, I've responded there, let me know if that works out for you and make sure to run it in the latest version of jspm as I recently fixed a bug where sometimes this config wouldn't apply properly.

Haha, it's always important to be polite and direct with issue queues dealing with people from different backgrounds, don't worry I can be much more abrupt in person :)
