### ISSUE TITLE
jspm installs packages when OS filed is specified in package.json

### ISSUE THREAD

**Issue by CxRes** [jspm/jspm-cli#1097]
jspm is installing strongloop/fsevents, which is OSX specific package on windows. The os is specified in the `os` field of `package.json`.

**Comment by guybedford** [comment]
Is this causing execution errors or install errors for you? Do you mean that you've manually added an os field to your package.json here?

**Comment by CxRes** [comment]
It is causing an execution error because the strongloop/fsextra package is silently installed. 

Actually, I am installing Chokidar (https://github.com/paulmillr/chokidar), which is rather prominent package on npm (because as you must be aware `fs.watch` is painful). fsextra is a dependency in  Chokidar that is meant to cater to Macs. With jspm, it installs on the windows environment as well and then in the code, which uses a try-catch with `require('fsextra')`, the package is found and executed. (My temporary workaround is to delete try-catch line but it not a viable solution for production).

I know that you intend to address conditional loading at a later date, but at least the fsextra package  should not install on windows or linux.

**Comment by guybedford** [comment]
@CxRes if its an execution error then this is exactly an issue with executing code that shouldn't be executed in the environment, which would come under the umbrella of conditional loading.

That said, you can enforce your own environment on install via a custom map override:

```
jspm install npm:chokidar -o "{map: { "fsevents": "@empty" }}"
```

Note that the above will only work if `npm:chokidar` directly requires `require('fsevents')` in one of its files. If it is a dependency of `npm:chokidar` that does this you would need to install that dependency with the override instead, before then installing `npm:chokidar` itself.

Let me know if you need any further help with this at all, but with the right map it should certainly work fine.

**Comment by CxRes** [comment]
Thanks for your answer!!!

My concern (for the long term) is when I use your solution, when some one else installs my app on OSX, fsevents will not install for them either. This is not a problem now though in the absence of conditional loading!!! 

Also, does this mean that jspm cannot detect OS field in the npm manifest for now?

**Comment by guybedford** [comment]
@CxRes overrides can be checked into the jspm registry so that they apply for everyone, but in this case I think we shouldn't check this in as it is environment specific. I'm getting close to releasing an alpha for jspm 0.17, so I'd suggest checking this out on that when it's out, and then we can get a general fix in for that version since it comes with the conditional loading support.

**Comment by CxRes** [comment]
Looking forward to 0.17!

**Comment by guybedford** [comment]
Working on it :)
