### ISSUE TITLE
Loading angular.js And elasticsearch.angular.js takes more then 3 seconds each

### ISSUE THREAD

**Issue by avgalon** [jspm/jspm-cli#1098]
Hi,
First of all, Great work!

Refreshing the browser takes too long.
Attached my app.js imports & debugger loading times.
my jspm config:
System.config({
  "transpiler": "babel",
  "babelOptions": {
    "optional": [
      "runtime",
      "optimisation.modules.system"
    ]
  },
  "paths": {
    "github:*": "jspm_packages/github/*.js",
    "npm:*": "jspm_packages/npm/*.js",
    "*": "*.js"
  },
  "defaultJSExtensions": true
});

System.config({
  "map": {
    "angular": "github:angular/bower-angular@1.4.4",
    "angular-bootstrap": "github:angular-ui/bootstrap-bower@0.13.3",
    "angular-leaflet-directive": "github:tombatossals/angular-leaflet-directive@0.8.7",
    "angular-route": "github:angular/bower-angular-route@1.4.5",
    "angular-sanitize": "github:angular/bower-angular-sanitize@1.4.5",
    "angular-xeditable": "github:vitalets/angular-xeditable@0.1.9",
    "babel": "npm:babel-core@5.8.23",
    "babel-runtime": "npm:babel-runtime@5.8.20",
    "bg-splitter": "github:blackgate/bg-splitter@master",
    "bootstrap": "github:twbs/bootstrap@3.3.5",
    "core-js": "npm:core-js@0.9.18",
    "css": "github:systemjs/plugin-css@0.1.15",
    "d3": "github:mbostock/d3@3.5.6",
    "elastic-js": "github:elastic/bower-elasticsearch-js@6.1.0",
    "jquery": "github:components/jquery@2.1.4",
    "leaflet": "github:Leaflet/Leaflet@0.7.3",
    "leaflet-label": "github:Leaflet/Leaflet.label@0.2.1",
    "ng-table": "github:esvit/ng-table@0.8.3",
    "timeline": "github:yikebocai/timeline@master",
    "github:angular/bower-angular-route@1.4.5": {
      "angular": "github:angular/bower-angular@1.4.4"
    },
    "github:angular/bower-angular-sanitize@1.4.5": {
      "angular": "github:angular/bower-angular@1.4.4"
    },
    "github:jspm/nodelibs-process@0.1.1": {
      "process": "npm:process@0.10.1"
    },
    "github:twbs/bootstrap@3.3.5": {
      "jquery": "github:components/jquery@2.1.4"
    },
    "github:vitalets/angular-xeditable@0.1.9": {
      "angular": "github:angular/bower-angular@1.4.4",
      "css": "github:systemjs/plugin-css@0.1.15"
    },
    "npm:babel-runtime@5.8.20": {
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:core-js@0.9.18": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    }
  }
});

![loading-time](https://cloud.githubusercontent.com/assets/3199491/9703654/1e7bc84c-5493-11e5-98b7-528d6a0b2142.png)
![loading-time2](https://cloud.githubusercontent.com/assets/3199491/9703657/20fb26b2-5493-11e5-9593-fbde2eba478e.png)

Please advise...
P.S: This is very annoying when editing only HTML and have to wait for compilation (Is ther a cache option for that?)

thnx

**Comment by guybedford** [comment]
The following steps can be taken to make refreshes faster:
* Ensure your local server is sending far-future cache headers for jspm_packages (see eg https://github.com/jspm/jspm-cli/issues/993)
* Precompile ES6 to System.register using a custom Gulp task

Ideally we would have a jspm-server and a jspm-gulp to manage these, but I can't personally put the time into them currently. Still waiting for the community to step up!

**Comment by avgalon** [comment]
I understand. Thanks for answering :-)
