### ISSUE TITLE
Support any custom properties under the jspm prefix

### ISSUE THREAD

**Issue by screendriver** [jspm/jspm-cli#1102]
I am publishing packages in our company in [jspm-style to npm](https://github.com/jspm/jspm-cli/blob/master/docs/publishing-packages.md#publishing-jspm-style-packages-to-npm). I know this is not recommended but it's a internal library that is hosted on a self hosted GitLab repository. Because we have no time to write a GitLab registry for jspm we are using this approach. We are setting `"jspmNodeConversion": false` like it is described in the docs. 

Unfortunately every time we make an `jspm install <library>` or an `jspm install <library>` this flag gets deleted from our `package.json`.

**Comment by guybedford** [comment]
I take it you are setting `jspmNodeConversion: false` within the `jspm` property of the package.json here?

Yes we currently don't preserve non-standard properties in this prefix, which jspmNodeConversion sort of is here.

Is there a reason you can't set this property at the base-level?

**Comment by guybedford** [comment]
We should always ensure that custom properties within the `jspm` prefix can work here.

**Comment by screendriver** [comment]
Hmm no, there is no reason. Can I set `jspmNodeConversion: false` directly in the root node of my `package.json` where all the other stuff like `name`, `version` and so on are located?

**Comment by guybedford** [comment]
Yes exactly.

**Comment by screendriver** [comment]
Thank you :+1: Then I will do it that way :sunglasses:

**Comment by guybedford** [comment]
Supported in jspm 0.17 beta.

**Comment by marthinus-engelbrecht** [comment]
This was very helpful. Have exactly the same issues and we will be moving to github soon, hopefully... The [documentation](https://github.com/jspm/jspm-cli/blob/master/docs/publishing-packages.md#publishing-jspm-style-packages-to-npm) does confuse the issue though. It makes it seems  like that's the place to put it. I can do a pull request and make it more clear?

**Comment by guybedford** [comment]
@marthinus-engelbrecht documentation PR's to add clarification are always welcome.

**Comment by marthinus-engelbrecht** [comment]
:+1: done, see #1744
