### ISSUE TITLE
jspm install --link npm:package from local link package doesn't update the main file entry from the package.json

### ISSUE THREAD

**Issue by chauthai** [jspm/jspm-cli#1103]
I've noticed an error, when I changed the main file of a local linked npm package.
The index file in the npm-folder e.g. "package-name".js doesn't update the main file entry from the updated package.json file.
Even uninstalling the package and reinstalling it doesn't change it, if the version number stays the same.
I had to manually edit the main file entry in the "package-name".js file for jspm to register the new main file.

**Comment by guybedford** [comment]
Thanks, yes this is a bug.

**Comment by guybedford** [comment]
Resolved in jspm 0.17 beta.
