### ISSUE TITLE
Source maps from "jspm bundle -m" no longer working

### ISSUE THREAD

**Issue by theefer** [jspm/jspm-cli#1104]
We have found that source maps produced by `jspm bundle -m` (0.16) are no longer applying correctly. Without the minification step the source maps is perfectly fine. It seems mostly an issue around resolving minified tokens.

I initially thought it was related to use of plugins in imports etc, but I have been able to reproduce with a very reduced test case with the following source and the resulting source map still doesn't resolve variable names correctly in Chrome:

``` js
function hello(world) {
    const abcde = 'var';
    const other = abcde + ' ' + world;
    console.log(other);
    return other.length;
}

hello('you');

export default hello;
```

I've tried this [sourcemap-validator tool](https://github.com/ben-ng/sourcemap-validator) and it passes fine with unminified bundles, but fails with the minified bundled source above with:

```
/tmp/node_modules/sourcemap-validator/index.js:140
          throw new Error(errMsg);
                ^
Error: Warning: mismatched names
Expected: System || 'System' || 'System' || "System" || "System"
Got: functi || function || function || function || function
Original Line: function hello(world) {
Mapping: 1:0→1:0 "System" in test.js
    at /tmp/node_modules/sourcemap-validator/index.js:140:17
    at Array.forEach (native)
    at SourceMapConsumer_eachMapping [as eachMapping] (/tmp/node_modules/sourcemap-validator/node_modules/source-map/lib/source-map/source-map-consumer.js:570:10)
    at validate (/tmp/node_modules/sourcemap-validator/index.js:79:12)
    at Object.<anonymous> (/tmp/validate.js:6:1)
    at Module._compile (module.js:456:26)
```

Again likely some issue with the token names.

Was there any change in jspm 0.16 that could explain this? Any pointers as to where I should be looking next?

**Comment by guybedford** [comment]
It sounds like the source map when uglifying is referencing the mappings from the transpiled file (expecting to see `System`) instead of the original ES6 source.

Which transpiler are you using here? Babel?

The way to debug this would be to follow the sourceMap in this test case from putting a `console.log` around https://github.com/systemjs/builder/blob/master/compilers/esm.js#L163 to ensure it's not got a `System` name in it, and then keep checking it down the pipeline to uglify to see where that is coming from.

**Comment by theefer** [comment]
We're using Traceur. The mini reduced example above was with Traceur too (default transpiler right?).

I'll try your suggestion for debugging this as we care a lot about working sourcemaps (we use Sentry).

Thanks!

**Comment by theefer** [comment]
So after testing the bundle phase doesn't reach the line you linked to. It reaches https://github.com/systemjs/builder/blob/master/compilers/esm.js#L109-L112 instead.

At that point of the compilation, the source map doesn't contain any `names`:
``` json
{
    "version": 3,
    "sources": [
        "test.js"
    ],
    "names": [],
    "mappings": "AAAA;;AAAA;AAAA;AACI;AACA;AACA;AACA;EACJ;AAAA;AAJM;AACA;AAKN;AAPA;IAE+B;EAC3B;AAAM;AAOV",
    "file": "file:///home/seb/.../test.js",
    "sourceRoot": "file:///..../",
    "sourcesContent": [
        "function hello(world) {\n    const abcde = 'var';\n    const other = abcde + ' ' + world;\n    console.log(other);\n    return other.length;\n}\n\nhello('you');\n\nexport default hello;\n"
    ]
}
```

whereas the final outputted source map does:
``` json
$ cat build.js.map   # (reformatted)
{
    "version": 3,
    "file": "/home/seb/.../build.js",
    "sources": [
        "test.js"
    ],
    "names": [
        "System",
        "register",
        "$__export",
        "hello",
        "world",
        "abcde",
        "other",
        "console",
        "log",
        "length",
        "setters",
        "execute"
    ],
    "mappings": "AAAA,AAAAA,OAAAC,SAAA,aAAA,SAAAC,eAAA,SAAAC,GAAAC,GACI,GAAAC,GAAA,MACAC,EAAAD,EAAA,IAAAD,CAEA,OADAG,SAAAC,IAAAF,GACAA,EAAAG,OACJ,OAJMC,WACAC,QAAA,WAKNR,EAAA,OAPAD,EAAA,UAAAC;;AAAA;AAAA;AACI;AACA;AACA;AACA;EACJ;AAAA;AAJM;AACA;AAKN;AAPA;IAE+B;EAC3B;AAAM;AAOV"
}
```

I guess that makes sense as the minification has not yet been applied at this stage. I will try and find where the minification occurs as from my experiments, the sourcemap when unminified is correct.

**Comment by theefer** [comment]
Still digging, but it looks like by default (`--minify`) the source map Uglify gets does not contain `sourcesContents` or `names`. That's likely going to make it hard to uglify to correctly extract token names?

**Comment by theefer** [comment]
Reproduced the issue after switching to Babel. Interestingly with Babel `"System","register","$__export"` are no longer in the `names` list, but I still don't get correct name mappings when debugging the bundled code in Chrome.

**Comment by theefer** [comment]
Also interesting to note that when bundling with Babel I don't get any error when running the files through the sourcemap-validator tool. Still not working in Chrome though :-/

**Comment by guybedford** [comment]
@theefer so to summarize, it sounds like this could be some kind of "off-by-one" issue in the source map generation? If so, I can go through some simple test cases, debugging exact offsets in the source maps to see where any gaps might be creeping in.

**Comment by guybedford** [comment]
If the above summary sounds correct, let's track this in https://github.com/systemjs/builder/issues/314.

**Comment by theefer** [comment]
OK moving the discussion there, thanks!
