### ISSUE TITLE
Can't write bundling plugin with ES2015

### ISSUE THREAD

**Issue by screendriver** [jspm/jspm-cli#1105]
Writing plugins in ES2015 for runtime compilation like CoffeeScript, CSS, SASS and so on works fine because at runtime (in the browser) the scripts will be translated to ES5. But if you want to bundle it with `jspm bundle` from the command line I get syntax errors.

It seems that the `jspm` cli does not use babel to transpile everything first. I tried it with `import 'babel/register';` in the first line of my entry script but I get a

```sh
[18:25:23] Error: ENOENT: no such file or directory, open '/home/me/development/plugin-sass/source-map-support.js'
    at Error (native)
	Error loading file:///home/me/development/plugin-sass/source-map-support.js as "source-map-support" from file:///home/me/development/plugin-sass/jspm_packages/npm/babel-core@5.8.23/lib/api/register/node.js
```

**Comment by guybedford** [comment]
I'm not quite sure I follow the exact issue here.

For example:

plugin.js
```javascript
export function fetch() {
  return "console.log('es6 plugin!')";
}
```

`jspm bundle "asdf!plugin" -i` and in the browser `System.import('asdf!plugin')` works absolutely fine for me.

Can you share a case that breaks down here?

**Comment by screendriver** [comment]
Oh ok I have to use ES2015 `export`. All right. My fault. I wrote `exports.fetch` and that did not work.
But another question related to that:

```js
return loader.import('./sass-builder', { name: module.id })
```

Throws me a `ReferenceError: module is not defined`. It seems that the [module Object](https://iojs.org/api/modules.html#modules_the_module_object) is only available if you write in CommonJS. Do you know any workaround for that?

**Comment by guybedford** [comment]
You can use `__moduleName` in ES modules for this.

**Comment by screendriver** [comment]
Awesome! Thank you for your help and for your great work! :+1: 
I think we can close this for now.
