### ISSUE TITLE
tree's are missing metadata property on arithmetic bundle

### ISSUE THREAD

**Issue by redmagic** [jspm/jspm-cli#1106]
I have several files that I create a bundle for using:

`jspm bundle [target/work/javascript/modules/*] modules.js --inject`

These are files using the `export var __useDefault = true;`

modules.js gets properly created containing System.register entries.

I then try to bundle this file with another file, index.js using:

`jspm bundle target/work/javascript/index + modules.js build.js`

Here the error occurs:

`err  TypeError: Cannot read property 'metadata' of null
         at logTree (/Users/arjengeerse/Projects/Schiphol/code/DesignHub/node_modules/jspm/lib/bundle.js:180:19)
         at /Users/arjengeerse/Projects/Schiphol/code/DesignHub/node_modules/jspm/lib/bundle.js:90:5
         at runMicrotasksCallback (node.js:337:7)
         at process._tickCallback (node.js:355:11)
`

**Comment by guybedford** [comment]
Yes you cannot bundle a bundle currently, although this feature may be supported in future.

**Comment by redmagic** [comment]
Ok, thanks for your quick reply. I am still looking to build a single self executing ES5 file for production, bases on code with dynamic imports. Would a regular concatenate do the trick? And before or after transpiling?

Regards,

Arjen

**Comment by guybedford** [comment]
Can you not just do `jspm bundle jspm bundle [target/work/javascript/modules/*] + target/work/javascript/index`?

Otherwise yes, regular concatenation of bundles will work fine too.

**Comment by redmagic** [comment]
Thank you, I overlooked that option.

One last thing, if I bundle everything like that and use bundle-sfx instead of bundle and try to use build.js as the only script file it gives me a `System is not defined error`.

Should bundle-sfx not include a mini loader?

P.S. If I should post this elsewhere, please let me know. And thanks for your time and effort!

**Comment by guybedford** [comment]
Sure happy to provide support but can't always be quick unfortunately. Any code which expects to use `System` will not work in SFX bundles. It no longer inlines the loader, and will use whatever is present in the environment.
