### ISSUE TITLE
Can't use sql.js

### ISSUE THREAD

**Issue by screendriver** [jspm/jspm-cli#1108]
I want to use [sql.js](https://github.com/kripken/sql.js/) and did a `jspm install npm:sql.js`. Installation ran without errors. At runtime my browser error console tells me

```
Error: XHR error (404 Not Found) loading http://localhost:3000/ws.js
	Error loading http://localhost:3000/ws.js as "ws" from http://localhost:3000/jspm_packages/npm/sql.js@0.2.21/js/sql.js
```

Unfortunately I don't know what this `ws.js` is for.

**Comment by chauthai** [comment]
ws a node module not available in the browser.
Take a look at this [issue](https://github.com/kripken/sql.js/issues/112) in the sql.js repo.

**Comment by screendriver** [comment]
Ok thank you. It seems that this is something like issue #1100 that I posted recently where a library (sass.js) reloads dynamically dependencies without requiring / importing it.

**Comment by guybedford** [comment]
You can null out that dependency on install via `jspm install npm:sql.js -o "{map: {ws: '@empty'}}"`. If that works, you can check that into the registry under `package-overrides/npm/sql.js@x.y.z.json` so others get the fix as well, or send a PR to sql.js to include the configuration in the original package.json file.

**Comment by screendriver** [comment]
In the first step the error is gone. But after that I get a

```
uncaught exception: uncaught exception: TypeError: process.platform is undefined
	Evaluating http://localhost:3002/jspm_packages/npm/sql.js@0.2.21/js/sql.js
	Evaluating http://localhost:3002/jspm_packages/npm/sql.js@0.2.21.js
	Error loading http://localhost:3002/index.js
```

I believe this whole thing can only be fixed in sql.js directly like described here https://github.com/kripken/sql.js/issues/112

**Comment by guybedford** [comment]
Sure, please post an issue at the jspm registry if you need further help with these overrides.
