### ISSUE TITLE
Document bundle dependencies functionality

### ISSUE THREAD

**Issue by peteruithoven** [jspm/jspm-cli#1109]
According to the following posts it should be possible to bundle dependencies:
https://github.com/jspm/jspm-cli/issues/482#issuecomment-86668706
https://github.com/jspm/jspm-cli/issues/872#issuecomment-114946729
This is of course totally awesome, but I had to find out trough the issues queues and it seems to use an undocumented syntax. 

Bundling the dependencies should be possible with the command: 

``` bash
jspm bundle app/**/* - [app/**/*]
```
- How does `app/**/*` describe all the dependencies in `jspm_packages` but not one's custom code? 
- `app` should be one's main javascript? So when this is located in a _lib_ folder it should be: `jspm bundle lib/app/**/* - [lib/app/**/*]`?
- What's that `- [app/**/*]` portion? 
- In both cases @guybedford mentions this functionality `--inject` isn't used, is there a reason for that? 

Maybe we could add this info to a _Development workflows_ doc page?

**Comment by peteruithoven** [comment]
I'm using JSPM version `0.16.2`, which seems more recent than the latest beta. 

I've created a new jspm enabled project with `jspm init`, in which I installed `lodash`. I created `app.js` which uses lodash. Then I tried bundling my dependencies, in this case only `lodash` with the following command:
```
jspm bundle app/**/* - [app/**/*] bundle.js 
```
But the created `bundle.js ` file is empty. There is no `bundle.js.map` created. 
Only when I bundle the actual app with `jspm bundle app bundle.js` the bundle.js is filled. 

I've published this example: https://github.com/peteruithoven/jspm-bundle-deps

**Comment by OrKoN** [comment]
Do you use bash? I remember someone had an issue in some other shell because additional escaping was needed. Also simply use gulp to bundle dependencies: 

```
gulp.task('js:bundle', function() {
  var pkg = require('./package.json');
  var deps = pkg.jspm.dependencies;
  var modules = Object.keys(deps);
  var moduleList = modules.join(' + ');
  console.log('\n' + moduleList + '\n');
  return jspm.bundle(moduleList, 'main-bundle.js', { mangle: false, sourceMaps: true, inject: true }).then(function() {
    console.log('Bundled');
  });
});
```

**Comment by peteruithoven** [comment]
Thanks @OrKoN, I tried adding some escaping and I added these to my previous comment. 

The gulp file approach seems to work, but it doesn't really use any of JSPM's dependencies bundle functionality. So that approach adds a lot of boilerplate.

**Comment by guybedford** [comment]
@peteruithoven the syntax is exactly right - which shell are you using here? Perhaps the `*` values are being escaped in the shell somehow?

**Comment by peteruithoven** [comment]
Standard OS X terminal. 
I'm pretty sure it's not a escape issue because jspm responds with:
```
     Building the bundle tree for app/**/* - [app/**/*]...
     
     
ok   Built into bundle.js with source maps, unminified.
```
Which seems to indicate that nothing happened with the `*'`s.

**Comment by guybedford** [comment]
Ok it does sound like it is working fine then. `app` needs to be a folder directly in the baseURL. Perhaps check that the path is correct then.

**Comment by peteruithoven** [comment]
That helps! 
Could you clarify the questions in my first comment of this issue? I didn't know that `app` part needed to be a folder, I was assuming it needed the "starting point" of my app to properly determine the dependencies. 
I've updated my example: https://github.com/peteruithoven/jspm-bundle-deps
The command I'm using is in the Makefile.

**Comment by guybedford** [comment]
Bundle expressions work against module names, the exact same naming space of `System.import` or `import`. `[]` means just that module and none of its dependencies, while globs will expand over the file system.

**Comment by peteruithoven** [comment]
I've made a start of this documentation in the following pull request: https://github.com/jspm/jspm-cli/pull/1136
