### ISSUE TITLE
Runtime error when not using a transpiler

### ISSUE THREAD

**Issue by gregoryagu** [jspm/jspm-cli#1110]
When I set the transpiler option to 'none' in config.js, I get a runtime 404 error because system.js is looking for none.js which of course doesn't exist.  

I would like to not use a transpiler at runtime, but I have not found a way to do this.

I am using version 0.16.2

**Comment by gregoryagu** [comment]
I found the actual issue: there was some ES2015 code in my app and so system.js was trying to download and use the transpiler "none.js".

So the fix was to remove the ES2015 code.  

So the 404 error on none.js really means: You are using ES2015 code without using a transpiler.

The fix is just to set the transpiler to babel.  If the transpiler is not actually needed, it is automatically not loaded.

**Comment by clark-stevenson** [comment]
This one would have ruined me! Thanks for your valuable followup!
