### ISSUE TITLE
Help with importing pre-compiled artifacts from local project

### ISSUE THREAD

**Issue by kburson** [jspm/jspm-cli#1111]
*I apologize for the length of this document, I am trying to be thorough in my pursuit of understanding these tools .*

  *I have summarized my questions at the bottom, and hopefully these questions and any discovered answers can be used in your documentation to help others.*

----

I have a sample repository where I am trying to establish an example workflow using JSPM with ES6 Angular 1.x and LESS.

[NG6-starter](https://github.com/kburson/NG6-starter)   :  **_jspm branch_**

This is a fork of the *Angular-Class/NG6-starter* where I am expanding on the **jspm branch** to add **LESS** transpilation and static asset management (images/fonts).

What I am trying to figure out, and I hope someone here can help me, is:

 **how JSPM integrates with SystemJS/ES6-module-loader, and how to configure them for both dev and production builds**.

----

**JSPM** is a nice package manager that can download the various versions of packages that I need  in my browser application and organizes them cleanly in `./jspm_packages`.
The **JSPM-CLI** also manages the `jspm.config.js`, so as I add/remove packages it updates both the `jspm.config.js` and the `package.json` files.

The `package.json` file has a `jspm` node

```
...
"jspm": {
    "directories": {},
    "configFile": "jspm.config.js",
    "dependencies": {
      "angular": "github:angular/bower-angular@^1.4.5",
      "angular-material": "github:angular/bower-material@^0.11.0",
      "css": "github:systemjs/plugin-css@^0.1.16",
      "font-awesome": "npm:font-awesome@^4.4.0",
      "normalize.css": "github:necolas/normalize.css@^3.0.3",
      "text": "github:systemjs/plugin-text@^0.0.2"
    },
    "devDependencies": {
      "babel": "npm:babel-core@^5.8.22",
      "babel-runtime": "npm:babel-runtime@^5.8.20",
      "core-js": "npm:core-js@^1.1.0",
    }
  },
...
```

that defines the jspm config file: `"configFile": "jspm.config.js"`

The jspm config file contains definitions of paths, maps and proxies to help locate resources:

```
System.config({
  baseURL: "./",
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: { ...  },
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },

  map: {
    "angular": "github:angular/bower-angular@1.4.5",
    "angular-material": "github:angular/bower-material@0.11.0",
    "angular-ui-router": "github:angular-ui/ui-router@0.2.15",
    "babel": "npm:babel-core@5.8.23",
    "babel-runtime": "npm:babel-runtime@5.8.20",
    "core-js": "npm:core-js@1.1.4",
    "css": "github:systemjs/plugin-css@0.1.16",
    "font-awesome": "npm:font-awesome@4.4.0",
    "mocha": "npm:mocha@2.3.2",
    "normalize.css": "github:necolas/normalize.css@3.0.3",
    "text": "github:systemjs/plugin-text@0.0.2",
    "github:angular-ui/ui-router@0.2.15": {
      "angular": "github:angular/bower-angular@1.4.5"
    },
    "github:angular/bower-angular-animate@1.4.5": {
      "angular": "github:angular/bower-angular@1.4.5"
    },
    "github:angular/bower-angular-aria@1.4.5": {
      "angular": "github:angular/bower-angular@1.4.5"
    },
    "github:angular/bower-material@0.11.0": {
      "angular": "github:angular/bower-angular@1.4.5",
      "angular-animate": "github:angular/bower-angular-animate@1.4.5",
      "angular-aria": "github:angular/bower-angular-aria@1.4.5",
      "css": "github:systemjs/plugin-css@0.1.16"
    },
    "npm:font-awesome@4.4.0": {
      "css": "github:systemjs/plugin-css@0.1.16"
    },
    ...
});
```
----

in the config file the `paths` state that any request for a module reference that starts with `github:` can be found in the project folder `./jspm_packages/gihub/`, similarly for `npm:` found in`jspm_packages/npm/`

That is fairly easy to understand.  

the map section defines 'aliases' for specific versions of dependency packages, ie:
`"angular": "github:angular/bower-angular@1.4.5",` 
says that when your code asks to `import angular from 'angular'` to 'map' the module reference `angular`
to the depdency location of `github:angular/bower-angular@1.4.5`.

**File** `./jspm_packages/github/angular/bower-angular@1.4.5.js`
```
module.exports = require("github:angular/bower-angular@1.4.5/angular");
```
simply loads the angular package  `./jspm_packages/github/angular/bower-angular@1.4.5/angular.js`

which has a pre-amble at the top of the file:
```
/* */ 
"format global";
"exports angular";
```

so my `import angular from 'angular';` will load the `angular` definition into my `angular` variable:
`var angular = function angular() { ... };`

Seems the angular team at google want to play nice with SystemJS and have formatted their package accordingly.

----

Let's take `normalize.css`, I have included this in my package dependencies and want to have the css file loaded at runtime, but I do not want to manually insert a `<style>` tag in my index.html.
In my **client/src/app/common.js** file I can import `normalize` as so:

```
import angular from 'angular';
import 'normalize.css';              // <--- load reference from mapped location
import Navbar from './navbar/navbar';
let commonModule = angular.module('app.common', [
	Navbar.name,
]);
export default commonModule;
```

this is 'mapped' in the jspm.config.js file as :

`"normalize.css": "github:necolas/normalize.css@3.0.3",`

**File**: `./jspm_packages/github/necolas/normalize.css@3.0.3.js`
```
module.exports = require("github:necolas/normalize.css@3.0.3/normalize.css!");
```

which in turn loads the css:

`./jspm_packages/github/necolas/normalize.css@3.0/normalize.css` using the css loader plugin (`!css`)

Somehow this gets injected into the window document, but I am not sure how or where. **(@guybedford ?)**

----

Then I want to include angular-material (material design for angular), so I import the following:

`import 'angular-material'`

which maps to:
`"angular-material": "github:angular/bower-material@0.11.0",`

**File**:  `./jspm_packages/github/angular/bower-material@0.11.0.js`
```
module.exports = require("github:angular/bower-material@0.11.0/index");
```
which in turn loads :
**File**: `./jspm_packages/github/angular/bower-material@0.11.0/index.js`
```
// Should already be required, here for clarity
require('angular');

// Load Angular and dependent libs
require('angular-animate');
require('angular-aria');

// Now load Angular Material
require('./angular-material');

// Export namespace
module.exports = 'ngMaterial';
```

which loads all the required dependencies for angular-material, except the css, or so I thought:
as the module definition has a pre-amble:
**angular-material.js**
```
/* */ 
"format global";
"deps ./angular-material.css!";
...
```

I am assuming this `"deps ./angular-material.css!";` which is written like a SystemJS reference will cause the specified dependency to load as well, 
thus injecting the `angular-material.css` contents into the window dom.  is this correct (@guybedford) ?

That's nice, if that is what is happening.  Apparently the angular team is cooperating well with the SystemJS spec.

----

Now, in my project I want to use LESS to transpile to CSS. When using common/global variables and mixins it is required not only to transpile the individual less files, but also to concatenate the results into a single CSS file.
I have a gulp task building the `./.build/app.css` file at the start of my session and whenever a less file is modified.  So, the `./build/app.css` file should always be up to date.

Now, how do I reference this file withough inserting/injecting a `<style>` tag in my `./client/src/index.html` ?

----

My first thought is to add a `path` to the config, ie:

**FILE**: `jspm.config.js`
```
System.config({
...
  paths: {
    "build:*": ".build/*"
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },
...
```

then import the file in my module:

**FILE**: `./client/src/app/common/common.js`
```
import angular from 'angular';

import 'normalize.css';

import 'build/app.css';   // <-- loading compiled css from ./build/app.css

let commonModule = angular.module('app.common', [
...
]);

export default commonModule;
```
----

My alternate plan was to create a map entry for the pre-compiled css file:

**FILE**: .`/jspm.config.js`
```
System.config({
  ...
  paths: {
    ...
  },
  map: {
    "app.css": ".build/app.css",
  }
});

```

then import similar to above:

**FILE**: `./client/src/app/common/common.js`
```
import angular from 'angular';

import 'normalize.css';

import 'app.css';   // <-- loading compiled css from ./build/app.css

let commonModule = angular.module('app.common', [
...
]);

export default commonModule;
```

**concern**
my problem with the previous 2 examples is that the jspm.config.js is managed by the jspm package manager, and whenver I add / remove a package from my dependency list it re-writes the jspm.config.js, so I lose my changes!

----

or I could follow the angular-material pattern and add a pre-amble to my module:

**client/src/app/app.js**
```
/* */ 
"format global";
"deps ./.build/app.css!";    // <--- set the dependency here ??

import angular from 'angular';
import Common from './common/common';

let appModule = angular.module('app', [
...
])
...
```

----

Then my final question, for now, is how to identify that during development I want to import the non-minified resources, and when I bundle for production I want the minified depencencies (both js and css) ?

----

**Summary**:

* How do JSPM, jspm-cli, SystemJS and es6-module-loader inter-relate?

* How much of my discussion content/questions should be targeted to jspm-cli, or to SystemJS?

* How do I identify additional locally compiled dependencies into my dev process so they load properly from their build directory?

* How do I identify that I want non-minified packages (js/css) during development run-time (self-hosting) 
and use minified packages (js/css) to be bundled in the distribution package (this includes transpiling and minifying all my sources too)

---

thanks for your help.  I believe if you can answer these questions this can be used in your documentation to help others understand these processes as well.

**Comment by guybedford** [comment]
Note that the inline meta syntax is injected by jspm as part of the overrides. So it sees the override for Angular at https://github.com/jspm/registry/blob/master/package-overrides/github/angular/bower-angular%401.3.12.json and then knows to inject `"format global" "exports angular"`.

It's not advisable to write this meta in yourself though.

For loading CSS, the best way to do this is via `jspm install css` and then to load `import 'file.css!'`. This workflow is documented at https://github.com/jspm/jspm-cli/blob/master/docs/plugins.md#css.

The jspm config file is entirely a SystemJS config file. Everything to do with how modules are loaded is SystemJS features. The structure of the config file itself is jspm.

It's fine to introduce custom configs that alter paths or maps to use different versions of resources between development and production. If your map configs are getting overwritten then that is a bgu in jspm.

**Comment by kburson** [comment]
Thank you for the reply.

An interesting problem I ran into when trying to import normalize.css.
Because the JSPM package includes a` normalize.css@3.0.3.js` that itself imports the `normalize.css!`, when I want to import the normalize.css I do not use the css loader directly `import 'normalize.css!'` rather I simply import the js file `import 'normalize.css'` and it will import the actual css file using the css loader... tricky, and unfortunately a bit confusing when reading the code because you expect `*.css` to include the training `!`.  

One possible solution for me is to add a map `'normalize-styles': 'normalize.css'` then my js file will simply `import 'normalize-styles'`.

A similar by-product of this is the angular-material library... the angular-material.js has a header 
```
/* */ 
"format global";
"deps ./angular-material.css!";
```
which seems to import the angular.material.css file appropriately.

but this lead me back to the question of a production build.

if my code import angular-material:
`import 'angular-material';`

which maps to 
```map: {
        "angular-material": "github:angular/bower-material@0.11.1",
        ...
   }```

this is the js file mentioned above, but inside the package folder there is a `*.min.js` with a corresponding `*.min.css` file.

How do I tell System that I want the min.js and the min.css files ?

First thought is to modify the `jspm.config:map` to point to the min file inside the package folder, but then I have to manually change this mapping every time angular-material is updated as the version number is part of the path.

The `angular-material.min.js` file has a header:
```
/* */ 
"format cjs";
```
which does not include the `"deps ./angular-material.css!";` of the non-minified version.

so, even if I do change the map for the minified js file, I will not get the included minified css file...

This could simply be a failing of angular team in packaging their minified versions correctly, or I could be confused on how SystemJS will load these minified dependencies...

Wow, it sure would be nice if SystemJS could have a dev and prod mappings to solve this problem in a more universal way...

Any thoughts?

**Comment by guybedford** [comment]
Unminified resources are preferable in development so the maps are correct. The way I currently look at the production operation when using separate files is as being to take the entire jspm_packages folder and minify every resource individually, and instead use that jspm_packages instead, that would be the ideal production scenario (and effectively what the experimental jspm CDN provides).

Usually though, you want to be bundling, which will do the minification for you as part of that process.

**Comment by kburson** [comment]
thanks

**Comment by guybedford** [comment]
Sounds sensible. Do you mean the jspm CDN here? I wouldn't recommend it for production workflows at this point as it is still somewhat experimental (even though the website uses it!).
