### ISSUE TITLE
Correct way to load an minify file?

### ISSUE THREAD

**Issue by nntgwww** [jspm/jspm-cli#1112]
How can I load an an minify files in correct way?
Example bootstrap. When I write 
```javascript
System.import('bootstrap');

```
It will load a bootstrap.js file. But I want to load bootstrap.min.js in package bootstrap@3.3.5 how can i do that without modify bootstrap@3.3.5.js file

```javascript
//module.exports = require("github:twbs/bootstrap@3.3.5/js/bootstrap");
module.exports = require("github:twbs/bootstrap@3.3.5/js/bootstrap.min");
```
If i modify  bootstrap@3.3.5.js file, it will be override by jspm install or update right?

**Comment by guybedford** [comment]
It's best to handle minification as part of bundling when going into production. This is because loading non-minified sources provides the best development experience, as source maps aren't ideal for debugging in development yet.

**Comment by lookfirst** [comment]
sourcemaps work great for me in dev. I wouldn't be able to write code run through systemjs and babel without them.

**Comment by nntgwww** [comment]
I have looked into builder section. Thank you for your guide.
