### ISSUE TITLE
Some typescript feature causes JSPM to require transpiler

### ISSUE THREAD

**Issue by danhalliday** [jspm/jspm-cli#1118]
I have a typescript project compiling to ES5/commonjs, which I then `sfx-bundle` using JSPM. Working fine.

I just added an inheritance to a typescript class, and I'm now getting an error `Error: ENOENT: no such file or directory, open '/......./build/source/javascript/none.js'` from JSPM. The offending typescript code is:

    export class Child extends Model {
      // ...
    }

The compiled Javascript (that JSPM is seeing) is:

    var __extends = (this && this.__extends) || function (d, b) {
        for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
        function __() { this.constructor = d; }
        __.prototype = b.prototype;
        d.prototype = new __();
    };
    var model_1 = require("models/model");
    var Child = (function (_super) {
        __extends(Child, _super);
        function Child(object) {
            _super.call(this, object);
            this.id = "";
            this.name = "";
        }
        return Child;
    })(model_1.Model);
    exports.Child = Child;

I've deduced that JSPM thinks it needs to transpile this code, and that the `none.js` in the error is the result of the `transpiler: "none"` option in my JSPM config, which is as follows:

    System.config({
      defaultJSExtensions: true,
      transpiler: "none",
      paths: {
        "*": "build/source/javascript/*.js",
        "github:*": "jspm_packages/github/*",
        "npm:*": "jspm_packages/npm/*",
        "app/*": "build/source/javascript/*"
      },

      packages: {
        "app": {
          "main": "app",
          "defaultExtension": "js"
        }
      },

      map: {.......}

 When removing the `transpiler: "none"` line from the config, JSPM will bundle without errors. Then, I get a runtime error (all browsers) saying that `exports` in the `Model` module is undefined when SystemJS tries to load it.

Is it possible to use inheritance with typescript and JSPM? Which part of the compiled Javascript is causing problems (the typescript-compiled JS for both `Model` and `Child` looks like plain old JS to me, nothing new from ES6)?

Any pointers much appreciated.

**Comment by danhalliday** [comment]
Wow, fixed it after much painful debugging. The inheritance chain was a red herring — adding the parent class simply included the problematic file. Here's the problem:

    /*

    Model Example:

    export class MyModel extends Model {
      constructor(object: any) {
        super(object);
      }
    }

    */

    export class Model {...}

JSPM chokes on the block comment above the class definition, because of the `export` keyword (even though it's inside a comment).

**Comment by guybedford** [comment]
Glad to hear you sorted it out. Yes the presence of any valid ES module export even in comments will trigger the format detection.

**Comment by icd2k3** [comment]
Thanks for identifying the problem! I spent a long time debugging a similar issue with having the word "import" in a block comment.
