### ISSUE TITLE
`jspm bundle-sfx app/main outfile` produces different output on each run

### ISSUE THREAD

**Issue by quodt** [jspm/jspm-cli#1121]
Each time i bundle my package i'm getting a different output file although the input packages did not change. It doesn't matter if i run `jspm bundle-sfx` or `jspm bundle`. It also does not matter if is use `--minify` or not. The option `--no-mangle` does also not change this behaviour.

Is there a way to get consistent output?

**Comment by guybedford** [comment]
Thanks for posting, this is being tracked in https://github.com/systemjs/builder/issues/284, but has not yet been released.
