### ISSUE TITLE
How to output transpiled files into directory

### ISSUE THREAD

**Issue by bjorm** [jspm/jspm-cli#1122]
We have a Typescript project and would like to have code coverage reports. Due to the current state of the TS ecosystem this will probably roughly consist of the following steps:

1. transpile TS sources using jspm
2. let karma run against transpiled sources with coverage reporter
3. use [remap-instanbul](https://www.npmjs.com/package/remap-istanbul) 

I tried transpiling using "vanilla" tsc but that does not work because it does not know about our SystemJS config.

I tried bundling each test on its own as an SFX using { sfxFormat: 'global', sourceMaps: true, mangle: false, minify: false } as options, but that fails with the rather unhelpful message
`>> TypeError: Global SFX bundle dependency "3" (3) must be configured to an environment global via the sfxGlobals option.`

Thanks for any advice.

**Comment by guybedford** [comment]
Perhaps some lessons can be learned from https://medium.com/@gunnarlium/es6-code-coverage-with-babel-jspm-karma-jasmine-and-istanbul-2c1918c5bb23 here?

**Comment by guybedford** [comment]
Let me know if I can assist further still.

**Comment by bjorm** [comment]
@guybedford Sorry I did not answer any sooner and thanks for the link. Unfortunately ispara is targeted at babel. Anyhow, I briefly tried tsc 1.6 and with the new node-style module resolution and correct .d.ts files in place, I just might be able to transpile each file individually.
