### ISSUE TITLE
jspm doesn't work with TypeScript 1.6.2

### ISSUE THREAD

**Issue by juergenzimmermann** [jspm/jspm-cli#1123]
When I install `jspm install typescript@1.6.0-beta` then my AngularJS app works fine. However, when I install `jspm install typescript=github:Microsoft/TypeScript@1.6.2`, then the app is broken. See attached screenshot.
![typescript-162](https://cloud.githubusercontent.com/assets/734334/9911141/fbaefd28-5ca0-11e5-944c-b68ba6a45e2e.png)

**Comment by guybedford** [comment]
Yes, the GitHub version of TypeScript isn't configured to work in jspm, and it is best to use the npm version (`jspm install typescript@1.6.2` being the same as `jspm install npm:typescript@1.6.2`).
