### ISSUE TITLE
Application version

### ISSUE THREAD

**Issue by nicklasb** [jspm/jspm-cli#1125]
One great thing that I would appreciate would be if there was some way to get the version of the application itself. To get all the dependencies is not a problem, that is kept by SystemJS. 
And I am thinking that perhaps JSPM could do this.

When publishing a new package, the typical thing is to update package.json and/or bower.json. 
Couldn't jspm install/update/something also update jspm_config with the version number of the application? And perhaps licenses and stuff like that too? 

Because that information can be useful in runtime to generate data about the application for information and support purposes. Without adding extra locations where to update that information during builds.

Or perhaps that is a build tools job, just a thought.

**Comment by guybedford** [comment]
We will be refining publishing workflows through jspm in future, and this sort of information would go along with that then. There are certainly some things we could do here, but not rushing into implementations just yet. For now it is probably best to maintain your own manifest and load with say the json plugin.

**Comment by nicklasb** [comment]
Kewl, thanks!
