### ISSUE TITLE
Typescript : "Interfaces only" files failed to transpile.

### ISSUE THREAD

**Issue by hourliert** [jspm/jspm-cli#1127]
Hi,

When I wrote a module (for instance an angular1 module), I like to put my module's interfaces in a separate file. Then my module export some implementation and the public interfaces.

Moreover, I don't want to use `/// <reference />`, I only want to use ES6 import. So I import interface as an exported object of an es6 module.

So for a session module, I have something like that:

module/session-interfaces.ts
```typescript
export interface ISession extends restangular.IElement {
  created?: Date;
  id?: string;
  userId?: number;
  ttl?: number;
}
```

module/session-service.ts
```typescript
import {ISession} from "./session-interface";

export class SessionService {
 // implementation not relevant here that can use the type ISession
}
```

module/session.ts
```typescript
import * as angular from "angular";
import {SessionService} from "./session-service";

let module = angular.module("session-module", [
  "LocalStorageModule"
]);
module.service("SessionService", SessionService);

export * from "./session-service";
export * from "./session-interfaces";
export default module;
```

In this case, `session-interfaces.ts` is fetched by the browser and not transpiled.
So, I got this error message 
```
Uncaught SyntaxError: Unexpected reserved wordD @ system.src.js:4208t.metadata.execute @ system.src.js:4208u @ system.src.js:4208a @ system.src.js:4208Promise.all.then.r.execute @ system.src.js:4208b @ system.src.js:4208x @ system.src.js:4208p @ system.src.js:4208h @ system.src.js:4208(anonymous function) @ system.src.js:4208
Uncaught SyntaxError: Unexpected reserved word
	Evaluating http://localhost:3000/app/common/session/session-interfaces.ts
	Error loading http://localhost:3000/app/main.ts
```

If I had a hacky expression in `session-interfaces.ts` like `
export class Hacky {}` at the end of the file, it works.

I hope I am clear enough.
Any solution ?

**Comment by guybedford** [comment]
`module/session-interfaces.ts` is not being detected as an ES module because it is not standard ES export syntax. You can hint to SystemJS that it is ES via meta configuration:

```javascript
System.config({
  meta: {
    'module/session-interfaces.ts': { format: 'esm' }
  }
});
```

**Comment by hourliert** [comment]
Thanks you very much. It works great.
