### ISSUE TITLE
"Or" peer dependencies get installed

### ISSUE THREAD

**Issue by johngeorgewright** [jspm/jspm-cli#1130]
If I was to install react:

```
jspm install react
```

Then install the react tap event plugin:

```
jspm install npm:react-tap-event-plugin
```

I get 2 version of react "0.13" & "0.12". Looking at the "react-tap-event-plugin"'s package configuration I see this:

```json
  "peerDependencies": {
    "react": "~0.13.x || ~0.12.x"
  }
```

To have just 1 version of react installed, I have to override this in my package.json:

```json
  "jspm": {
    "overrides": {
      "npm:react-tap-event-plugin@0.1.7": {
        "peerDependencies": {
          "react": "~0.13.x"
        }
     }
  }
```

Is this a bug?

**Comment by guybedford** [comment]
Yes this is an issue unfortunately. Try using `jspm resolve --only npm:react@0.13.3` to use one version only.

**Comment by guybedford** [comment]
(This will be resolved when we support peer dependencies properly)
