### ISSUE TITLE
Document new SFX features (0.17)

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#1131]
From the Google group - 

> SFX bundles also support exclusions and output to other module formats like AMD - `jspm bundle-sfx app - jquery --format amd`

> If using the global output, a global map can be provided: `jspm bundle-sfx app - jquery --globals "{jquery:'$'}"` so it looks for the jQuery module from the `$` environment global.

> Also switching disabling the Babel runtime output will use the generic `babelHelpers` global which can then be excluded via `jspm bundle-sfx app --no-runtime` so that you can include `babelHelpers.js` separately to the SFX bundle and not have any helpers inlined.

**Comment by neothemachine** [comment]
Not to forget `--global-name MainName`

**Comment by evanplaice** [comment]
What about using these from the CLI:
- minify
- mangle
- lowResSourceMaps
- sourceMaps

I have come across usage of --minify. It would be cool of the documentation covered the rest (ie if they're supported)

**Comment by milworm** [comment]
and --skip-source-maps
