### ISSUE TITLE
Angular divide

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#1132]
Here's an example fork situation with Angular usage:

```
     Installed versions of github:angular/bower-angular

       angular 1.4.5 (^1.4)

       github:angular-ui/ui-router@0.2.15
         angular 1.4.5 (^1.3.2)

       github:angular/bower-angular-animate@1.4.5
         angular 1.4.5 (^1.3.0)

       github:angular/bower-angular-aria@1.4.5
         angular 1.4.5 (^1.3.0)

       github:angular/bower-angular-mocks@1.4.5
         angular 1.4.5 (^1.3.0)

       github:angular/bower-material@master
         angular 1.4.5 (^1.3.15)


c:\git\pos>jspm inspect npm:angular

     Installed versions of npm:angular

       npm:ng-click-select@0.1.5
         angular 1.4.5 (^1.0.0)

       npm:ng-stats@2.5.1
         angular 1.4.5 (*)
```

We need to ensure that users don't end up forking angular by mistake. This means picking a version to use as the primary one, and making sure it is easy to resolve conflicts into this version. Peer dependencies would also help with this workflow resolution process.

**Comment by guybedford** [comment]
I guess the main point here is specifically - _are all typical Angular projects already on npm or moving to npm?_. Because if the answer is yes, we should probably be using the npm versions of these things!

**Comment by lookfirst** [comment]
I do as much as possible with github and not npm.

**Comment by frankwallis** [comment]
npm is the primary package manager for angular2, but I think most angular1 libraries tend to use bower.

**Comment by guybedford** [comment]
Ok, so is everyone completely happy with the idea of always using GitHub sources for all angular 1 things? That means continuing to grow the shims in this direction. For Angular 2 we should use npm though.

**Comment by lookfirst** [comment]
I can't fork npm projects as easily as github and without cross repo resolution that will always be an issue...

**Comment by guybedford** [comment]
Ok, so to confirm we're sticking with GitHub for Anglar 1. But we will likely use npm for Angular 2.

**Comment by robertbaker** [comment]
@guybedford How can I resolve this.

I'm using `jspm install angular` which uses github.

However those 2 angular directives I'm using reference the npm version. It's creating quirks, so in the meantime I disabled importing those plugins and using them.

Can I do a package override or is there a plan to have jspm correct it in the near future?

I tried the latest release and still same result. However it says npm:angular not found but getting angular loading twice warning.

**Comment by guybedford** [comment]
@robertbaker yes exactly, custom overrides for ng-click-select and ng-stats would be the way to go here, following the examples of the other projects. Also since we're going with the GitHub ecosystem on these, we should probably include the above from github not npm.

**Comment by MacKentoch** [comment]
@robertbaker and @guybedford you saved me time resolving horrible : 
>`WARNING: Tried to load angular more than once`.

My issue was from **angular material** referencing **npm version** of **angular** rather than **github** one.

Now it works after manual fix here 

```json
 "map": {

"github:angular/bower-material@1.0.0-rc3": {
      "angular": "github:angular/bower-angular@1.4.7",
      "angular-animate": "github:angular/bower-angular-animate@1.4.7",
      "angular-aria": "github:angular/bower-angular-aria@1.4.7",
      "css": "github:systemjs/plugin-css@0.1.19"
    }

}
```

**Is there a fix possible? (*if not no problem it is ok to manual fix*)?**

**Comment by robertbaker** [comment]
Run jspm update to angular material master. They put it back to using
github.

**Comment by MacKentoch** [comment]
So simple :smile: 

Thank you for tip :+1:
