### ISSUE TITLE
Support read-only package.json / config.js

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#1133]
When only doing an install that is non-modifying it should be possible to work with read-only config.js and package.json files.

We would throw an error though if we did actually need to persist a change.

**Comment by rolandjitsu** [comment]
This would be nice to have. First of all, jspm should have it's own config file, not added to `package.json` and second of all, it should detect the indent style and keep the same style, because it is really annoying when it changes tabs to spaces in my files.

**Comment by cbelden** [comment]
Hey @guybedford if you want to send an email with some pointers I would like to work on this feature.

Thanks

**Comment by guybedford** [comment]
@cbelden thanks very much for offering, this feature is already implemented in the 0.17 branch though.

**Comment by guybedford** [comment]
Supported in jspm 0.17 beta.

**Comment by rolandjitsu** [comment]
This is great. So now it will only write to the system config as far as I understand from the release notes? Is there also a way of having the jspm manifest in a `jspmconfig.json`/`jspm.json` file instead of a `package.json`?
