### ISSUE TITLE
Including Babel necessary when bundling?

### ISSUE THREAD

**Issue by screendriver** [jspm/jspm-cli#1134]
I want to create a [Bundle](https://github.com/jspm/jspm-cli/blob/master/docs/production-workflows.md) that runs on its own. I know that I can create [self-exuting](https://github.com/jspm/jspm-cli/blob/master/docs/production-workflows.md#creating-a-self-executing-bundle) bundles that are completely independent of SystemJS but then I can't do dynamic imports with `System.import()` because SystemJS is not included anymore.

So I tried to bundle all together in a `bundle.js` and put it together with `system.js` and `config.js` in a `dist` directory. My `index.html` looks like:

```html
<!doctype html>
  <script src="system.js"></script>
  <script src="config.js"></script>
  <script src="bundle.js"></script>
  <script>
    System.import('main');
  </script>
```

At runtime my Browser throws now an error that `jspm_packages/npm/babel-core@5.8.23.js` could not be found. That's true because my `dist` directory only contains the 4 files above.

So is it advisable to include babel within my bundle like `jspm bundle main.js + babel dist/bundle.js`? Or would it be better to copy the whole `jspm_packages` to `dist` which would lead to a very very big directory for production?

**Comment by guybedford** [comment]
You shouldn't need to use Babel in production having built all ES6 into ES5 already. If SystemJS requests babel that means you're attempting to load ES6 somehow.

**Comment by screendriver** [comment]
Hmm ok. I looked at my hello world application and found something. My main script is really simple:

```js
const func = () => {
  alert('Hello world');
};
func();
```
There is no ES2015 `import` and `export`. So I added

```js
meta: {
  "main": {
    "format": "esm"
  }
},
```
to my `config.js`. I looked at my `bundle.js` and can see that the arrow function gets transpiled to a ES5 function. Looks good so far. At runtime I get the error above. Now if I change the `main.js` to

```js
const func = () => {
  alert('Hello world');
};
func();
export default '';
```
the `bundle.js` looks the same, but at runtime SystemJS does not try to download `babel-core`.

Maybe it's a :beetle: ?

**Comment by guybedford** [comment]
Ah, you'd want to remove that meta configuration when running in production. But yes, we shouldn't let format metadata affect loading for bundled modules.

**Comment by guybedford** [comment]
Actually the `format: 'esm'` meta shouldn't be applying for the bundled code. Let me know if removing the meta in production helps though.

**Comment by screendriver** [comment]
If I remove 

```js
meta: {
  "main": {
    "format": "esm"
  }
},
```
from my `config.js` the `bundle.js` contains the ES2015 code. It gets not transpiled to ES5 and my browser tells me a syntax error.

**Comment by guybedford** [comment]
After bundling I mean, in the production code only.

**Comment by screendriver** [comment]
Ah, you mean I should remove it from my production `config.js` in the `dist` directory?

I've tried that now and it's working. So the solution is the include the `meta` property in my `config.js` when bundling, but to remove it from the `config.js` in production?

**Comment by guybedford** [comment]
That's really strange that that works for you as the meta format shouldn't alter the handling when it is in a bundle. Are you sure the browser isn't sending a request to `main.js` at all and it is in the bundle?

**Comment by guybedford** [comment]
Wow, thanks, yes this was a bug! Fixed in https://github.com/systemjs/systemjs/commit/fa2d32c6a0178a76579adbb761d666d041cb4b15.

**Comment by screendriver** [comment]
You're welcome :sunglasses: I'm looking forward to see this in the next release.
