### ISSUE TITLE
bundle-sfx method return to a Promise?

### ISSUE THREAD

**Issue by S-unya** [jspm/jspm-cli#1135]
I've begun using `Systemjs` and `JSPM` and am looking to recommend it as a our base module loading and package managing method; I am really liking it so far but I have come across a potential improvement that could really smooth out a common workflow.
*The problem:* the bundle-sfx method returns immediately, while the output from it happens at some unknown time later. This makes it very hard to fit into an automated build or test framework.

It is entirely possible that I have missed something, I have scoured the docs for an answer, but haven't dipped into the code (which I will do when I have time). *I'm suggesting a promise-like implementation where the promise only returns once the files have been output*. If you need help with this, I'd be happy to help out in between work projects.

**Comment by guybedford** [comment]
@S-unya the `bundleSFX` build method is promise-based in SystemJS Builder (https://github.com/systemjs/builder#self-executing-sfx-bundles). The recommended way to run this in jspm is through the exposed API for this at https://github.com/jspm/jspm-cli/blob/master/docs/api.md#class-builder. Let me know if you need any more help with this at all.

**Comment by S-unya** [comment]
Hi Guy,

I'm really sorry! I thought it was strange that you were using promises
elsewhere and not in this case, but when I tried I couldn't get it to work.
Equally, I totally missed these docs having "scoured" them.


Thanks for your forbearance! Also, thanks for this well considered tool.

Regards,
S'unya

                      o
            o                 o
                O   O   O
      o  o   O S´unya O   o  o

S'unya Dickman
Head of CSD |  Aerian

sunya.dickman@aerian.com   |  www.aerian.com  |  +44 (0) 845 408 6009
