### ISSUE TITLE
Corrupted systemjs when bundle-sfx.

### ISSUE THREAD

**Issue by hourliert** [jspm/jspm-cli#1137]
Hi,

I encounter a very weird bug using JSPM 0.16.2.
In development no problem.
In production (ie. bundle-sfx but not minified), the systemjs code added to the bundle created by jspm seems to be corrupted.

Indeed, around the line 155 of my bundle, there is the systemjs function `linkDeclarativeModule`. Here's its code:
```javascript
function linkDeclarativeModule(entry) {
  // only link if already not already started linking (stops at circular)
  if (entry.module)
    return;

  var module = entry.module = getOrCreateModuleRecord(entry.name);
  var exports = entry.module.exports;

  var declaration = entry.declare.call(global, function(name, value) {
    module.locked = true;
    exports[name] = value;

    for (var i = 0, l = module.importers.length; i < l; i++) {
      var importerModule = module.importers[i];
      if (!importerModule.locked) {
        for (var j = 0; j < importerModule.dependencies.length; ++j) {
          if (importerModule.dependencies[j] === module) {
            importerModule.setters[j](exports);
          }
        }
      }
    }

    module.locked = false;
    return value;
  });

  module.setters = declaration.setters;
  module.execute = declaration.execute;

  // now link all the module dependencies
  for (var i = 0, l = entry.normalizedDeps.length; i < l; i++) {
    var depName = entry.normalizedDeps[i];
    var depEntry = defined[depName];
    var depModule = moduleRecords[depName];

    // work out how to set depExports based on scenarios...
    var depExports;

    if (depModule) {
      depExports = depModule.exports;
    }
    else if (depEntry && !depEntry.declarative) {
      depExports = depEntry.esModule;
    }
    // in the module registry
    else if (!depEntry) {
      depExports = load(depName);
    }
    // we have an entry -> link
    else {
      linkDeclarativeModule(depEntry);
      depModule = depEntry.module;
      depExports = depModule.exports;
    }

    // only declarative modules have dynamic bindings
    if (depModule && depModule.importers) {
      depModule.importers.push(module);
      module.dependencies.push(depModule);
    }
    else
      module.dependencies.push(null);

    // run the setter for this dependency
    if (module.setters[i])
      module.setters[i](depExports);
  }
}
```

If you compare this code to the original one from system.js@0.18.17, you can see that around this line https://github.com/systemjs/systemjs/blob/0.18.17/lib/register.js#L244, the previous code differs.

This create an issue if you have a module that export a module that export something. (ie: two levels of export).

Therefore, if I use `jspm bundle` rather than `jspm bundle-sfx` since I manually load `system.js`, no problem but my app is not standalone anymore.

Thanks in advance.

**Comment by guybedford** [comment]
Yes this is a bug, it's been fixed in the latest release of SystemJS builder 0.13.6. You'll need to run an update through npm to ensure this dependency inside of jspm is bumped though.

**Comment by guybedford** [comment]
I'm actually just pushing out a jspm patch now, which would resolve this too.

**Comment by hourliert** [comment]
Oh, thanks a lot! Perfect!

**Comment by guybedford** [comment]
This should be working in the latest 0.16.3 release now, just let me know if you're still having any issues.

**Comment by hourliert** [comment]
Re, this issue is gone since 0.16.3.
I've got another one (maybe I should create a new issue?).
In my project, I import lodash which depends on https://github.com/jspm/nodelibs-process.
In my bundle, System is known as `$__System`. However, `nodelibs-process` calls directly `System` ([here](https://github.com/jspm/nodelibs-process/blob/master/index.js#L1)) which raise this exception:
`Uncaught ReferenceError: System is not defined`

Here's the generated code by bundleSFX which raise the exception:

```javascript
$__System.registerDynamic("10", ["f"], true, function(require, exports, module) {
  ;
  var global = this,
      __define = global.define;
  global.define = undefined;
  module.exports = System._nodeRequire ? process : require("f");
  global.define = __define;
  return module.exports;
});
```

Thanks in advance.

**Comment by guybedford** [comment]
@hourliert thanks yes this is a bug, I forgot to leave this feature in for backwards compatibility - I've added it back in https://github.com/systemjs/builder/commit/2c6e841e825a49817c7f9a0b99dc624e8cc7550d.

**Comment by hourliert** [comment]
Thanks, everything works! I let you know if I see other bugs ;)

**Comment by jordie23** [comment]
@guybedford Looks like that change was undone in https://github.com/systemjs/builder/commit/a413644407c83328a1c9c306bd8fe226817492f8 ?

I'm getting a self-executing bundle on 0.15.29 with `System._nodeRequire` hardcoded, breaking it.

**Comment by Tim91084** [comment]
@jordie23 I'm having the same issue.

**Comment by guybedford** [comment]
@Tim91084 see https://github.com/jspm/jspm-cli/issues/2046.
