### ISSUE TITLE
Compilation issue with underscore identifiers

### ISSUE THREAD

**Issue by nateabele** [jspm/jspm-cli#1139]
This is probably not _really_ a JSPM issue. I'm mostly looking to be pointed in the right direction for where to report it. Thanks.

I have the following ES6 code:

```javascript
import R from 'ramda/ramda';

const { __, arity, indexOf } = R;
```

Which transpiles to the following (snipped):

```javascript
(function(__moduleName){System.register(['ramda/ramda'], function(exports_1) {
    var ramda_1;
    var __, arity, indexOf;
    return {
        setters:[
            function (ramda_1_1) {
                ramda_1 = ramda_1_1;
            }],
        execute: function() {
            __ = ramda_1.default.___, arity = ramda_1.default.arity, indexOf = ramda_1.default.indexOf;
            // ...
        }
    }
});
```

The relevant bit is `__ = ramda_1.default.___` where the left-hand side of the expression has two underscores, but the right-hand side has 3, consequently the assigned value is undefined. My config is set to use the TypeScript transpiler.

**Comment by guybedford** [comment]
@nateabele it sounds like this is a TypeScript bug. I'd suggest posting there.
