### ISSUE TITLE
System is not defined

### ISSUE THREAD

**Issue by lookfirst** [jspm/jspm-cli#1140]
@guybedford 

It seems that .buildSFX() is deprecated, which is fine. Now I switched to .buildStatic()… but when I load my bundle it chrome now gives me an error that says ‘System is not defined’. 

This was all working just fine before this new version. =( What do I need to fix now?

**Comment by lookfirst** [comment]
The error in Chrome stops on the first line:

```
System.register('github:mgcrea/angular-motion@0.4.2/dist/modules/fade.css!github:systemjs/plugin-css@0.1.16', [], false, function() {});
System.register('github:mgcrea/angular-motion@0.4.2/dist/modules/fade-and-slide.css!github:systemjs/plugin-css@0.1.16', [], false, function() {});
System.register('github:mgcrea/angular-motion@0.4.2/dist/modules/collapse.css!github:systemjs/plugin-css@0.1.16', [], false, function() {});
System.register('github:revolunet/angular-carousel@0.3.13/dist/angular-carousel.css!github:systemjs/plugin-css@0.1.16', [], false, function() {});
```

This code is at the very bottom of my bundle.

**Comment by guybedford** [comment]
@lookfirst you need to update the CSS plugin for SFX compatibility in the latest version. Try running `jspm update css`.

**Comment by lookfirst** [comment]
Ok, thanks. 

Next error:

```
$__System.registerDynamic("11", ["10"], true, function(require, exports, module) {
  ;
  var global = this,
      __define = global.define;
  global.define = undefined;
  module.exports = System._nodeRequire ? process : require("10");
  global.define = __define;
  return module.exports;
});
```

Another reference to System.

**Comment by lookfirst** [comment]
I also still have this in my config.js to get rid of the chrome warnings:

```
  meta: {
    "core-js/modules/$.global": {
      "esmExports": false
    }
  },
```

**Comment by lookfirst** [comment]
Oh, looks like you fixed it... maybe add a comment above it to not remove it again?

**Comment by guybedford** [comment]
I've just posted out the patch. It will be deprecated for 0.17 thankfully.

**Comment by lookfirst** [comment]
Yea... things are working again... thanks for being so fast fixing stuff. =)

**Comment by guybedford** [comment]
Sure!
