### ISSUE TITLE
Isomorphic site with jspm?

### ISSUE THREAD

**Issue by f15gdsy** [jspm/jspm-cli#1141]
Hi, I want to create an isomorphic react site that use jspm.
I'm wondering how should I install the packages?

Normally I use JSPM for front-end.
But in isomorphic site, I want to import front-end packages like "react" into my server code.
Is there a way to do this?

Thanks!

**Comment by majhork** [comment]
Just install them normally. Then import them in your server and start it with "jspm run *server*".

**Comment by guybedford** [comment]
See https://github.com/jspm/jspm-cli/blob/master/docs/nodejs-usage.md and https://github.com/jspm/jspm-cli/blob/master/docs/api.md for jspm use in Node.
