### ISSUE TITLE
With bundle-sfx output, onchange events won't fire when using mdl components with Reactjs

### ISSUE THREAD

**Issue by earlsioson** [jspm/jspm-cli#1142]
When loading modules dynamically via System.import, [mdl](http://www.getmdl.io/) components are working well with [react](https://facebook.github.io/react/). When I create the bundle using..
```jspm bundle-sfx ./src/script/index ./dist/script/bundle.js --inject --inline-source-maps --minify```
the onchange event for a text input no longer fires. If I remove mdl from the equation and re-bundle, the text onchange works again. I suspect that this has to do with the way mdl's componentHandler registers the components. Even though it appears that mdl is the cause of this, I don't understand why this behavior only occurs when bundled to a single file, and not when using System.import.

### Duplication scenario
* In this [app](https://github.com/earlsioson/sample-react-redux-jspm)
* ```gulp start``` will launch the app using System.import with events firing with no issue, when inputting text in the supplied text input.
* ```gulp publish``` will create the bundle which when served from the created dist directory, the onchange event of the text input appears to be no longer firing.

**Comment by guybedford** [comment]
It's difficult to try and debug all of this code without knowing it too well. If the text input isn't binding, can you create a simple example that just installs a text input and shows that the binding doesn't work? If you can somehow reduce it that would help to diagnose it from a package management perspective.

The other thing to bear in mind is timing - when building an SFX bundle, while the same execution order is ensured, the order of execution of modules isn't deterministic (although it will be when we update to the latest spec). Code that may have inadvertently relied on some ordering to access globals or event subscriptions might be affected this way, and should be debugged carefully.

Sorry I can't help more than that.

**Comment by earlsioson** [comment]
Hello Guy,

I created a simple example [here](https://github.com/earlsioson/systemjs-builder-debug). I stripped it down to just React and MDL. This example replicates the scenario using systemjs-builder via buildSFX(). One thing I noticed when putting the example together is that the binding will work fine if I'm using a single React component. To replicate the problem, I created a parent component composed of a child component that fires an onchange event which in turns calls the parents event handler. I'll see if I can narrow it down some more based on your suggestions.

**Comment by earlsioson** [comment]
I built and deployed a live example of the systemjs-builder-debug repo [here](http://74.50.50.62).

**Comment by guybedford** [comment]
@earlsioson it looks like the `onChange` event is not firing at all from the child Header element. I have no idea why that would happen, but can't see any reason why it should be jspm-related.

**Comment by guybedford** [comment]
I tried the following simplified case:

```javascript
import React from 'react';

class Component extends React.Component {
  render() {
    return <input onChange={(e) => console.log(e)} />;
  }
}

class Parent extends React.Component {
  render() {
    return <Component />
  }
}

React.render(React.createElement(Parent, {}), document.body);
```

And it's definitely firing the events fine from what I can tell.

**Comment by earlsioson** [comment]
@guybedford I agree with you that it's probably not a builder.buildSFX/jspm issue. I kept on adding to your example until I could replicate the behavior I was experiencing, and below is the code that exhibits the problem I identified initially. Note that the below example works fine if System.import is being used but is only a problem when using builder.buildSFX. 

Interestingly, I was able to get the code below to work with a builder.buildSFX bundle by removing the mdl-js-layout class from the top div element. I examined the source code on Google's [repo](https://github.com/google/material-design-lite/blob/master/src/layout/layout.js) and see that several EventListeners are being added to this element and it's children. In addition React has it's own thing going on with events so I'm not surprised there are issue's when it's all bundled together. 

I think I'm going to end my experiments with React and MDL for the moment since their integration does not appear to be a supported configuration. 

Than you for your help and all your work on systemjs, builder, es6-module-loader, jspm etc. I appreciate your commitment to compliance with the latest specifications and the quality of your work.

```
import React from 'react';
import ReactDOM from 'react-dom';

class Child extends React.Component{
  componentDidUpdate() {
    componentHandler.upgradeElement(
      ReactDOM.findDOMNode(this.refs.inputContainer, 'MaterialTextfield')
    );
  }

  render() {
    return (
      <div ref='layout' className='mdl-layout mdl-js-layout mdl-layout--fixed-header'>
      <header className='mdl-layout__header'>
      <div className='mdl-layout__header-row'>
        <span className="mdl-layout-title"></span>
        <div className="mdl-layout-spacer"></div>
        <form className='form1'>
          <div className='mdl-textfield mdl-js-textfield mdl-textfield--floating-label'
                ref='inputContainer'>
            <input onChange={e=>this.props.onUserInput(e.target.value)}
                    className='mdl-textfield__input'
                    type='text'
                    id='userInput'
                    ref='userInput'
                    required/>
            <label className="mdl-textfield__label" htmlFor="userInput">Enter Search Term</label>
          </div>
        </form>
      </div>
      </header>
      </div>
    );
  }
}
class Parent extends React.Component{
  handleEvent(e){
    console.log(e);
  }
  componentDidMount() {
  }
  render() {
    return (
        <Child onUserInput={this.handleEvent.bind(this)}/>
    );
  }
}

ReactDOM.render(React.createElement(Parent, {}), document.body);
```

**Comment by guybedford** [comment]
Sure, thanks for the update.
