### ISSUE TITLE
Package not downloaded correctly

### ISSUE THREAD

**Issue by laurentiustamate94** [jspm/jspm-cli#1145]
When i try to install `jspm install npm:crypto-js@3.1.5` it downloads it weird. A file affected by this is `enc-utf16.js` and it start from line 58:

```javascript
function swapEndian(word) {
      return ((word << 8) & 0xff00ff00) | ((word >>> 8) & 0x00ff00ff);
    }
  }());
  return CryptoJS.enc.Utf16;
}));
16Str.charCodeAt(i) << (16 - (i % 2) * 16);
	            }

	            return WordArray.create(words, utf16StrLength * 2);
	        }
	    };
```

I think this is a bug at recreating the file downloaded.

**Comment by guybedford** [comment]
@laurentgoudet we don't currently support multiple jspm installs running at the same time, so this may have been a corruption due to that. I'd suggest trying `jspm install npm:crypto-js@3.1.5 -f` to force clear the caches when installing.

**Comment by laurentgoudet** [comment]
// cc @laurentiustamate94 :)

**Comment by laurentiustamate94** [comment]
I don't run multiple jspm installs. If i just run `jspm install npm:crypto-js@3.1.4` it works like a charm

**Comment by guybedford** [comment]
@laurentiustamate94 did you run with the `-f` flag or run `jspm cc`. The point is that if you had run multiple installs at any point for any reason it would have polluted the cache.

**Comment by laurentiustamate94** [comment]
@guybedford I've run `jspm cc` and nothing happened. I've run `jspm install npm:crypto-js@3.1.5 -f` and it worked. It was a cache problem indeed. Thank you :+1:
