### ISSUE TITLE
devDependencies

### ISSUE THREAD

**Issue by subesokun** [jspm/jspm-cli#115]
Are there any recommendations on tdd with jspm? I want to unit test a package with Karma but I'm not sure yet how I can include jspm / SystemJS into Karma.

Assume following package folder structure:
```
package
  |_ package.json
  |_ src
  |_ test/
       |_ karma-unit.conf.js
       |_ unit/
```

Following issues I see so far are:
 - Defining `devDependencies` in the package.json required for testing (does jspm respects them?)
 - By default a package won't have a config.js (only the app will have it), should the config.js be under test/? This might be troublesome in case of testing apps as there will be then two config.js files.
 - Is it ok to mix in the config.js normal dependencies with devDependencies?
 - How to include the SystemJS into Karma? https://github.com/systemjs/systemjs/issues/177

**Comment by guybedford** [comment]
Supported in https://github.com/jspm/jspm-cli/commit/01b15b07ae6c8e5391bcb1e4402c46109fa4da65.

**Comment by subesokun** [comment]
Awesome, thanks! :)

**Comment by lookfirst** [comment]
I'd like to see devDependencies and karma-jspm somehow work together.

Right now, if I move angular-mocks in my package.json to `jspm: { devDependencies: {} }`, then it doesn't get added to the config.js and karma-jspm can't load it.

**Comment by subesokun** [comment]
I think you've to do a 'jspm install --dev' but I didn't test it so far.

**Comment by lookfirst** [comment]
Ok, I just tested that and it just sets the config.js to have the dev dependencies and nothing else. I'm not really sure of the usefulness of that.

I'm also confused by the special treatment of babel and babel-runtime. They get defined in config.js no matter what. If we are going to special case those two, why not also treat system.js and the es6-module-loader as separate dependencies too? I don't really understand why they are special either.
