### ISSUE TITLE
Can't include socket-io.client in dependency bundle

### ISSUE THREAD

**Issue by akdor1154** [jspm/jspm-cli#1150]
jspm 0.16.9 bundle fails on socket-io.client if I try to use the recommended (where "recommended" => some guy wrote on some github issue; this is not in the docs anywhere for some reason) syntax to make a bundle of project dependencies:

```sh
mkdir test; cd test
jspm init -y
jspm install socket.io-client
echo 'import io from "socket.io-client";' > test.js
jspm bundle build.js # works fine
jspm bundle './**/*' - '[./**/*]' break.js # breaks, with error:
     Building the bundle tree for ./**/* - [./**/*]...

err  Error on fetch for github:socketio/socket.io-client@1.3.7/lib/ at file:///home/jarrad/src/kusema/test/jspm_packages/github/socketio/socket.io-client@1.3.7/lib/.js
        Error: ENOENT, open '/home/jarrad/src/kusema/test/jspm_packages/github/socketio/socket.io-client@1.3.7/lib/.js'
         at Error (native)
```

**Comment by guybedford** [comment]
@akdor1154 try installing `socket.io-client` from npm instead of GitHub to get the npm compatibility for folder requires (amongst other things).

**Comment by akdor1154** [comment]
The npm version pulls in like 5mb of dependencies. How come the github
version works in the full bundle but not deps only?

**Comment by akdor1154** [comment]
I also found a workaround - if I put test.js in '/app/', set directories.baseURL in packages.json and jspm.config.js as 'app/', set directories.packages as '../jspm_packages', and map github and npm packages to '../jspm_packages/[npm|github]/*', then bundl,ing works correctly.
However, I then get a heap of warnings about jspm_packages being outside baseURL, and bundling only works if I do it inside '/app/'.

Should this sort of mucking around be required?

**Comment by guybedford** [comment]
Of course not. I've created https://github.com/jspm/registry/issues/586 to track simplification of the install. All overrides are community contributed - they only get better when people choose to help.
