### ISSUE TITLE
Error after upgrade: somefile.js detected as esm but didn't execute.

### ISSUE THREAD

**Issue by Bodom78** [jspm/jspm-cli#1151]
Upgraded from 0.15.x to the current 0.16.9 and now when I load the project in the browser I get the following type of errors:

`Error: http://site.localhost/client/app/app.controller.js detected as esm but didn't execute.`
`Error loading http://site.localhost/client/app/app.controller.js as "client/app/app.controller" from http://generalsurgeryapplications.localhost/client/bootstrap.js`

The thing is every reload throws the error about a random file, not the same one everytime.

App is using es6 modules. Building a standalone sfx bundle and incluing it works fine.

I'm not too sure how to proceed with this error, any advice on what this error means?

**Comment by guybedford** [comment]
Thanks for posting. Which browser are you using here? Do you get the error in Chrome?

**Comment by Bodom78** [comment]
@guybedford I was using Firefox 40.0.3 Downgrading back to 0.15.x it works again.

Unfortunately I have not been able to use Chrome recently with localhost projects and have yet to sort it out.

**Comment by guybedford** [comment]
If you're able to isolate a smaller subset of your app that shows the behaviour and share that that would be appreciated.

**Comment by Bodom78** [comment]
@guybedford I'll try to replicate the error working up from the bootstrap of the application in the coming days and get back to you.

**Comment by neothemachine** [comment]
I seem to have the same problem currently. Works in Chrome, but not in Firefox: http://reading-escience-centre.github.io/leaflet-coverage/

**Comment by guybedford** [comment]
@neothemachine thanks for sharing. The link you sent loads a map up fine for me in Firefox though?

**Comment by neothemachine** [comment]
Ok I found out what causes it: Firebug. When I have it opened, I get 
this error. When not, it works.

**Comment by guybedford** [comment]
@neothemachine sounds like https://github.com/systemjs/systemjs/issues/814

**Comment by guybedford** [comment]
I think this is very likely that issue. Closing to track there.

Note the fix is to tell SystemJS the module format of the module via meta config in advance so that it uses script injection over evaluation.
