### ISSUE TITLE
jspm install is by default loading up broken 0.19.1 version

### ISSUE THREAD

**Issue by Rush** [jspm/jspm-cli#1154]
My bundled scripts (`builder.bundle()`) don't work at all with 0.19.1, only `jspm dl-loader --latest` fixes it by installing 0.19.2

**Comment by guybedford** [comment]
Thanks, this was an omission. Fixed in https://github.com/jspm/jspm-cli/commit/3788d7c3ca861c5d56ba3323afdcfdb5ac44cbe7.

**Comment by Rush** [comment]
Whew, thanks, took same head scratching on my side ...

**Comment by guybedford** [comment]
Released in 0.16.10.
