### ISSUE TITLE
Expose package path resolver

### ISSUE THREAD

**Issue by tauren** [jspm/jspm-cli#116]
Is there a way to programmatically find the system path to a package? I'd like to specify a package name, such as `foo/foobar`, and get back the path to that package, such as `.\jspm_packages\github\foo\foobar@0.1.0`. This would enable external tools to leverage resources in the packages without having to specify endpoints, version numbers, etc.

In case you need to understand why I'd like this, I'm building a modular application using a component-based architecture. Each UI Component contains its own style files. Components can depend on other components, each of which may includes style files (css, rework, sass, etc.). The application that is being built with these components will have a build process that should be able to intelligently include the styles from all used components so that a final css file can be generated.

To accomplish this, I'd like to be able to include styles from components with something like an `@include` command with a reference to the jspm_package name. For instance:

```
@include "jquery-ui";  // load from jspm_packages/github/components/jquery@2.1.0
@include "foo/foobar";  // load from jspm_package/github/foo/foobar@0.1.0
@include "./app/styles/main"; // load from ./app/styles/main.scss
```

The `package.json` file of a component will have an extra attribute to specify the default style file: `style: "index.css"`.

There are other projects that enable loading CSS from `npm` modules using a node.js `require`-like syntax. I'd like to be able to do the same thing, but from jspm packages. SuitCSS essentially does exactly what I want to do, but from node_modules, not jspm_packages. It uses rework-npm under the covers.

http://suitcss.github.io/
https://github.com/reworkcss/rework-npm

Does jspm-cli or system.js provide anything that would help accomplish this goal?

**Comment by clempat** [comment]
I personally wrote a small plugin allowing me import scss file from systemjs dependancies. https://www.npmjs.com/package/gulp-systemjs-resolver

**Comment by Gu1** [comment]
I also made a module that aim to solve the same problem:
https://www.npmjs.com/package/sass-jspm-importer
Instead of the approach used in gulp-systemjs-resolver, which is to pre-process the scss files if I'm not mistaken, it works through exposing a sass custom function and importer.

**Comment by guybedford** [comment]
@Gu1 nice, I've added this to https://github.com/jspm/jspm-cli/wiki/Third-Party-Resources.
