### ISSUE TITLE
Uncaught SecurityError: Blocked a frame with origin … from accessing a frame with origin

### ISSUE THREAD

**Issue by wei-zhao-83** [jspm/jspm-cli#1161]
Trying to load the app in an iframe, but getting the cross domain error.
It works if load the app directly.
(current jspm version: 0.16.10, works fine in 0.15.7)

`Uncaught (in promise) Error: Failed to read the 'frame' property from 'Window': Blocked a frame with origin "http://example.com" from accessing a cross-origin frame. "http://example.com/build.js"`

**Comment by guybedford** [comment]
What exactly is the value of `window.frame`? Does your iFrame have an id of `frame` here perhaps? If so that would explain it.
