### ISSUE TITLE
System.js requests non-bundled file

### ISSUE THREAD

**Issue by buddhike** [jspm/jspm-cli#1166]
I'm following the production workflows example in 
https://github.com/jspm/jspm-cli/blob/master/docs/production-workflows.md

After including the script tag to reference bundle.js, I can still see a request to app/main.js in network tab. That's not supposed to happen right?

**Comment by jackfranklin** [comment]
@buddhike doesn't sound like that should be happening! Are you able to share a sample repo?

**Comment by buddhike** [comment]
Thanks for getting back to me @jackfranklin. I did a rm -rf on node_modules and jspm_packages to test it before I send it to you, and suddenly the problem is gone. Will keep an eye on it.
