### ISSUE TITLE
Optimizing deployment, delete unneeded files

### ISSUE THREAD

**Issue by reppners** [jspm/jspm-cli#1167]
Since most packages out there are not yet optimized I get a whole lot of files I don't want nor need at runtime. I startet to make overrides for each package that brings an excessive amount of files with them but still there is a whole lot of packages I don't need at runtime.

In numbers:
* 47MB, over 4.3k files unbundled
* 6.4MB, 188 files bundled and minified

So far I'm bundling and minifying the application but it will grow larger and I really would like to take advantage of the HTTP/2 stuff in the future while keeping the deployment size of the whole app low.

So how could we have a step that finds out what my application really needs (imports) and throws away all the rest? Something like "preen" in bower.

**Comment by guybedford** [comment]
There are many ways assets can be loaded, so we can never fully know what belongs to a package and what doesn't. Use overrides to set the `files` or `ignore` properties of packages on install to remove unnecessary files.

**Comment by reppners** [comment]
Thats working good for selecting the exact files needed at runtime (often times the dist/release folder of a package) and I do that where possible. But what about the dependencies like "jspm" itself in the jspm_packages folder. Also there are lots of packages from npm that I just don't need at runtime.

When I create a bundle jspm does "know" (as good as it can) what to put in the bundle. This did a pretty good job at selecting what I need at runtime. It failed only at including some font files from bootstrap that were required through the bootstrap css with relative paths, which of course fails then.

So I'm pretty much asking for the bundling step without the bundling (if that makes sense ^^) to create a clean distribution/release version of my app. If I would write a grunt task, is there any output of jspm/systemjs bundler that I could leverage to achieve this goal?

**Comment by guybedford** [comment]
You can use the builder API to do a trace and then only include that trace, but that is not a sufficient condition to ensure an asset belongs to the package as the module tree is only one way of loading.

**Comment by reppners** [comment]
But thats the same point where bundling can fail, so I end up in the same situation as with bundling but with the files separate for leveraging HTTP/2. Am I right with that?

**Comment by guybedford** [comment]
There's https://github.com/systemjs/plugin-css/issues/61 for the specific bundling issue it sounds like you're having.

**Comment by reppners** [comment]
Yes, its related. Thx for the pointer. Though my goal is not to bundle but to include the minimal file set needed at runtime for production. I will see if I can come up with a solution that works in both scenarios.
