### ISSUE TITLE
How to import full URL?

### ISSUE THREAD

**Issue by neothemachine** [jspm/jspm-cli#1168]
When I do `import 'https://www.google.com/jsapi'` (which is the full URL) while using the jspm CDN systemjs, it tries to load https://www.google.com/jsapi.js and fails. Is this only supported in 0.17? I'm not sure.

**Comment by guybedford** [comment]
To disable adding of js extensions when `System.defaultJSExtensions` is enabled you need to use package config:

```javascript
System.config({
  packages: {
     'https://www.google.com': { defaultExtension: false }
  }
});
```
