### ISSUE TITLE
Error: ENOENT: no such file or directory, open ...\types\mime.types

### ISSUE THREAD

**Issue by mattmazzola** [jspm/jspm-cli#1170]
The error occurs when attempting to run a self-executing bundle created by jspm.  The import which was causing the failure was 'azure-storage' although by the looks of the error it seems unrelated to the package, but something lower level with mime types and the file system module.

Some logs:
```
λ jspm bundle-sfx src/server server.js
     Building the single-file sfx bundle for src/server...
ok   Built into server.js with source maps, unminified.

λ iojs server.js
fs.js:547
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT: no such file or directory, open '<removed>\types\mime.types'
```

Also, if I install this same package using `npm install azure-storage` instead of `jspm install npm:azure-storage` and then use `require('azure-storage')` instead of `import azure from 'azure-storage'`, everything works fine.  This is what made me think the issue might be with how jspm builds the bundles.

**Comment by guybedford** [comment]
This sounds like a limitation due to https://github.com/jspm/jspm-cli/blob/master/docs/nodejs-usage.md. I'd suggest waiting for 0.17.
