### ISSUE TITLE
Install bower package

### ISSUE THREAD

**Issue by varghesep** [jspm/jspm-cli#1171]
[DevExpress DevExtreme](https://github.com/DevExpress/bower-devextreme)  has only bower package. When I install it with **jspm install bower:devextreme** command, I get the error that **Registry bower not found**.

I installed the npm **jspm-bower** and **jspm-bower-endpoint** packages but that did not help.

How can I install bower packages with jspm?

**Comment by varghesep** [comment]
It's not an issue. This [video](https://www.youtube.com/watch?v=sPkyvKtV1CE) helped me. After installing the package **jspm-bower-endpoint**, I had to run the command **jspm registry create bower jspm-bower-endpoint**.

**Comment by guybedford** [comment]
Thanks for sharing. Generally I wouldn't encourage using the bower endpoint as the github endpoint works the same and will also check the `bower.json` for the main entry point when necessary.
