### ISSUE TITLE
Support for <= version ranges on GitHub

### ISSUE THREAD

**Issue by neothemachine** [jspm/jspm-cli#1172]
I'm trying to install "c3" which is in the jspm registry but misses the registry field (should be fixed I guess). Therefore I use:
```
$ jspm install c3 --override "{registry:\"jspm\"}"
     Updating registry cache...
     Looking up github:masayuki0812/c3
     Downloading github:masayuki0812/c3@0.4.10
     Looking up github:mbostock/d3

err  Error: Installing github:masayuki0812/c3@0.4.10, no version match for github:mbostock/d3@<=3.5.0
```
I looked in the github repository, and I would say that https://github.com/mbostock/d3/tree/v3.4.13 satisfies the version constraint. Why doesn't jspm locate that?

**Comment by neothemachine** [comment]
Requesting https://registry.jspm.io/c3.js returns a 404. Is this because the CDN itself cannot install c3 as well like me?

**Comment by guybedford** [comment]
Perhaps `jspm install npm:c3` is the better option here?

**Comment by neothemachine** [comment]
Maybe, but shouldn't it still work? Both c3 and d3 are in the registry and I find it strange that jspm doesn't find the d3 version that c3 needs. I had a quick look at https://github.com/jspm/github and it has code to recognize both v-prefixed and normal x.y.z versions. So it should find d3 `v3.4.13` for `github:mbostock/d3@<=3.5.0`, right?

**Comment by guybedford** [comment]
It's because jspm doesn't support `<=` as a range in versions.

**Comment by neothemachine** [comment]
OK, right, I see this is possibly not as easy to fix right now. I'm fine with using the npm version once the following is fixed: https://github.com/jspm/npm/issues/99 I'll rename the title of this issue.

**Comment by neothemachine** [comment]
Just to solve the registry situation, I think the override should then be `{"registry":"npm"}` since `jspm install c3 --override "{registry:\"npm\"}"` works without problems. But of course then you can just as well point the registry for c3 to npm:c3 and be done with it... I think that makes more sense for the moment. Do you agree? If yes, I can submit a pull request.

**Comment by guybedford** [comment]
Sure, we can update it to `npm:c3` if that is working well for you here.

**Comment by neothemachine** [comment]
What's the resolution of this? I guess that `<=` will not be supported for GitHub for the meantime, right? That's fine with me, but then the error message should be different than just saying that no version matched.

**Comment by guybedford** [comment]
Sure, we can create an issue to track this at https://github.com/jspm/github/issues.
