### ISSUE TITLE
inject option not used in a custom SystemJS Builder instance

### ISSUE THREAD

**Issue by Hypercubed** [jspm/jspm-cli#1173]
The jspm api docs (https://github.com/jspm/jspm-cli/blob/master/docs/api.md#class-builder) indicate that "a custom SystemJS Builder instance" can "inject the bundle config into the configuration file" using the `inject` option.

However, as far as I can tell the inject option is only available through the `jspm.bundle` API.  https://github.com/jspm/jspm-cli/blob/master/lib/bundle.js#L102

**Comment by guybedford** [comment]
Yes you're right. We should be extending the `bundle` method of SystemJS builder to enable this option through jspm.

**Comment by guybedford** [comment]
I've fixed this up in the documentation in https://github.com/jspm/jspm-cli/commit/5f4e8e0cba6d4b16d6ddfb245f1dc776e8fe57a5 rather.

For injection, I think the better focus will be providing an API for modifying the jspm config file.
