### ISSUE TITLE
Loading amd modules and node modules side by side

### ISSUE THREAD

**Issue by alisabzevari** [jspm/jspm-cli#1174]
I am writing an application with electron and aurelia. My problem is loading node modules in my aurelia code. Here is my code (typescript):
```typescript
import fs = require("fs");
export class SettingsProvider {
  movieFolders: { path: string; active: boolean }[];
  private static fileName = "./settings.json";

  constructor() {
    var f = JSON.parse(fs.readFileSync(SettingsProvider.fileName).toString());
    this.movieFolders = f.movieFolders;
  }
}
```
The problem is that systemjs tells it can not find fs.js to load it. I managed to solve the problem but I lost type safety:

```typescript
declare var System: any;
var fs = System._nodeRequire("fs");
...
```
I think it would be good idea to have something to define in config.js to tell jspm to load this module from global namespace.

**Comment by guybedford** [comment]
@alisabzevari did you try `jspm install fs` here?

**Comment by alisabzevari** [comment]
Perfect! Thanks. It worked perfect.
