### ISSUE TITLE
JSPM and Karma (feedback/suggestion)

### ISSUE THREAD

**Issue by eyalsk** [jspm/jspm-cli#1176]
I've been experimenting with JSPM for like over a month now and it's really great, I like it.

Now my problem isn't really with JSPM per-se but when it comes to integration of JSPM with other tools it's not so simple, at least for the inexperienced JSPM user.

I've tried to hook up some tests with Karma and I've spent quite some time on it and unfortunately didn't manage to get it to work because I'm fairly new to JSPM and SystemJS and the two plugins for Karma, [Karma-JSPM](https://github.com/Workiva/karma-jspm) and [Karma-SystemJS](https://github.com/rolaveric/karma-systemjs) have their own configuration and paths that I also had to fix and I kinda got lost in setting up all the paths correctly.

*Just for clarification I've used Karma-JSPM and Karma-SystemJS separately, not together simultaneously.*

There are no documentation that tells you step-by-step how to configure things or a complete, working example that you can inspect and understand how to set it up, I've been using Karma for over two years and yet didn't know how to set everything together, it was a frustrating experience.

I feel like documentation about integration of JSPM/SystemJS with other tools such as Karma is very important especially for newcomers.

Now, the second issue is that Karma-JSPM and Karma-SystemJS  are developed and maintained by different authors, they might not even be compatible with recent versions of JSPM/SystemJS and I really think that isn't ideal, you never know whether things didn't work because of incompatibility in Karma, the Karma plugins or even JSPM/SystemJS itself.

So I thought maybe it's possible to make the CLI do all the plumbing for us? instead of doing things manually the CLI would ask you whether you use Karma or where is the path to the karma configuration file and download this Karma-JSPM and set everything correctly? 

P.S. Maybe even fork Karma-JSPM and add this to the organization.

**Comment by guybedford** [comment]
Yes unfortunately there has to be a strong line between jspm and third-party supporting tools to make the project development manageable. Tool quality is then only as strong as the ecosystem makes it, so the most important thing is for users to realise that things will only get better when they help on these projects and take ownership in these spaces. In future, when jspm is more stable we can certainly expand to document and maintain supporting tools, but the project is just not at that point currently.

**Comment by eyalsk** [comment]
@guybedford I understand, thanks.
