### ISSUE TITLE
JSPM with TypeScript issues. and request for documentation on the matter.

### ISSUE THREAD

**Issue by kosz** [jspm/jspm-cli#1180]
Currently JSPM + TypeScript can get quite confusing. I cannot find any specific documentation on this, and everybody seems to have a different directory structure. Unless we follow the magical directory structures, things can get very confusing. 

I have found some (outdated) examples here for TypeScript 1.5 https://github.com/Microsoft/TypeScriptSamples/blob/master/jspm/config.js but once again, they assume that your basedirectory is the root directory. Many already existing projects don't have that, and once I try to change it, the multitude of settings such as 
```
"*": "src/*",
"src": "src",
```
```
packages: {
    "/src": {
      "defaultExtension": "ts"
    }
  },
```
> Notice how in the microsoft example src is used in 4 places. 

start throwing errors such as:

```
can't find /app/app/app/app.js
```
```
can't find /app/app/app/app.ts
```
```
can't find app.ts
```

etc.

I have actually got it to look for my file in the right place
```
app/app.ts
```
the file is there however I still get: 
```
Error: ENOENT, open '/app/app.ts'
```

My config.js now looks like this 
```
System.config({
  baseURL: "/app",
  defaultJSExtensions: true,
  transpiler: "typescript",
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },

  packages: {
    "/": {
      "defaultExtension": "ts"
    }
  },

  map: {
    "angular": "github:angular/bower-angular@1.4.7",
    "core-js": "npm:core-js@0.9.18",
    "typescript": "npm:typescript@1.6.2",
    "github:jspm/nodelibs-process@0.1.1": {
      "process": "npm:process@0.10.1"
    },
    "npm:core-js@0.9.18": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    }
  }
});
```
And my directory structure: 
```
.
├── app
│   ├── app.ts
│   └── index.html
└── config.js
```
This is not something I can change it's an already existing code base. 

Any help would greatly be appreciated. I would gladly write some docs, if I knew what's going on.

```
jspm -v
0.16.11
```

**Comment by kosz** [comment]
interesting to note that when trying to add this to paths 
```
paths: {
   "*": "app/*",
```
the error becomes
```
{ [Error: ENOENT, open '/app/app/app/app.ts'] errno: -2, code: 'ENOENT', path: '/app/app/app/app.ts' }
```

**Comment by kosz** [comment]
another detail, is that I'm trying to upgrade from jspm 0.16-beta3, the version where typescript was temporarily removed. I was running of an install from a specific commit, right before typescript support was removed in jspm. my previous configuration was : 

```
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*",
    "app": "app"
  },

  packages: {
    "app": {
      "main": "app",
      "defaultExtension": "ts",
      //"meta": { // specific frankwallis/plugin-typescript which i'm trying to remove
      //  "*.ts": {
      //    "loader": "ts"
      //  }
      }
    }
  },
```
However using these settings throws the following error: 
```
{ [Error: ENOENT, open '/app/app/app.ts'] errno: -2, code: 'ENOENT', path: '/app/app/app.ts' }
```

**Comment by kosz** [comment]
The winning combination seems to have been this 
```
System.config({
  defaultJSExtensions: true,
  transpiler: "typescript",
  paths: {
    "github:*": "jspm_packages/github/*",
    "app": "app",
    "npm:*": "jspm_packages/npm/*"
  },

  packages: {
    "app": {
      "main": "app",
      "defaultExtension": "ts"
    }
  },

  map: {
    "angular": "github:angular/bower-angular@1.4.7",
    "core-js": "npm:core-js@0.9.18",
    "typescript": "npm:typescript@1.6.2",
    "github:jspm/nodelibs-process@0.1.1": {
      "process": "npm:process@0.10.1"
    },
    "npm:core-js@0.9.18": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    }
  }
});
```

However, now when trying to run the app I get the following error: 
```
Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
```

I've tracked down the following issue https://github.com/systemjs/systemjs/issues/489, however now I've reached another dead end, since that's closed and people are content that the microsoft example is working ( I too managed to get that to work, and even upgraded it to TS 1.6 with no problems, however I wasn't as lucky in my own codebase so far )

**Comment by kosz** [comment]
ooooh boy ... ok so this may be a very situational bug. 

I have started looking into the output file, and it looks like out of 4500 lines of transpiled code, only one single file doesn't have it's `const` and `let` variables transpiled properly. 

attn @guybedford 

I can probably work around it, however ... why would this ever occur

**Comment by guybedford** [comment]
Is that module definitely running through the TypeScript transpiler? You may find that since it is not using any module syntax it is not being sent through it. Adding `"format esm"` to the top of the source will ensure it is loaded as an es module and the internal transpiler.

Note though that the plugin you were using originally is the recommended way to use TypeScript with jspm.

**Comment by kosz** [comment]
@guybedford thanks for your insights. Indeed adding "format esm" to the top of the file fixes this particular issue. Is this a bug that should be filed for jspm, systemjs or typescript ? The file extension is `.ts`.

As for what is recommended, what are you planning on for the future. Are you planning of having a solid TypeScript transpiler option built in to jspm, or will that plugin always remain the preferred way of doing things ? 


### Note

The actual `root issue` that I'm trying to fix, is that something, somehow, prevents Errors from being printed in the console. 

My first strategy was updating to latest JSPM and TypeScript versions but that hasn't fixed anything yet. It's my main focus at this point, so I'll be sure to let you know if anything JSPM related is causing this. In the meantime if you have any other insights on such an issue, they would greatly be appreciated. Basically the simplest way to explain the erroneous behaviour is that having :

```
throw new Error('any message');
```
fails silently. So obviously any other application errors that may occur, print nothing.

**Comment by guybedford** [comment]
@kosz sure no problem. This is a common catch actually because we only transpile modules that use module syntax in SystemJS. This will be changing when we separate transpilation from the module format happening in jspm 0.17. The TypeScript plugin will then be the way forward for TypeScript integration in jspm and SystemJS.

That's strange errors are not displaying. Did you try adding a catch handler to your import promises - `System.import('x').catch(console.error.bind(console))`? Depending on the global promise implementation these can be suppressed.

**Comment by kosz** [comment]
@guybedford this seems to be some unexpected reaction between Angular (1.3.16) and SystemJS/TypeScript. 

Basically if I have 
```
throw new Error('error');
```
in a : 

- angular service/controller written in non transpiled ES5 ( the error prints ) 
- TypeScript file with error thrown outside of an angular service/controller ( the error prints ) 
- angular service/controller written in TypeScript ( the error `doesn't` print )

Since this is a "hybrid" app, with old legacy Angular 1.0 style code, we import the old source code using standard html `<script src` tags, and we use systemjs-builder as such:
```
builder.loadConfig("./config.js")
		.then(function() {
			return builder.buildStatic('app', paths.dist + '/scripts/app.min.js', { minify: true, mangle: false });
		})
		.then(function() {
			console.log('Build complete');
			cb();
		})
		.catch(function(err) {
			console.log(err);
			cb(err);
		});
});
```
to produce an app.js file which we then manually import into `index.html` . Everything works well except that the errors are not being printed in the case described above.

**Comment by guybedford** [comment]
@kosz thanks for the update. Are you saying the error doesn't show specifically in the SF bundle case? Does it show when loading with `System.import` and separate files?

**Comment by kosz** [comment]
@guybedford I will have to rewire things to test that out. I will do so shortly, I remember when we first did the wiring 2 months ago, we needed to rely on the bundle as Sytem.import wasn't working well with .ts files. 

As for what I'm saying the error does not show specifically in the SF bundle `when` the error is thrown `inside` an angular object. 

So the following code in a *.ts file which has been bundled :
```
  1 throw new Error('error outside of angular code');
  2 angular.module('myModule').factory('factoryName', function() {
  3   throw new Error('error inside angular code');
  4 });
```
will show the error: `'error outside of angular code`
however the following: 
```
  1 //throw new Error('error outside of angular code');
  2 angular.module('myModule').factory('factoryName', function() {
  3   throw new Error('error inside angular code');
  4 });
```
Will fail silently.

**Comment by guybedford** [comment]
@kosz is there any way you can share your built bundle file that is not bubbling the error?

**Comment by kosz** [comment]
@guybedford that's a bit difficult since this file contains some 5000 lines of code which are protected by a NDA. 
I have been hacking around in that file for a while, and I added a console.log to all catch blocks that I could find, however none of them have been printing so far.

**Comment by guybedford** [comment]
Sure, I'll see if I can come up with a test case then. Also if you're able to share an example not covered by an NDA please do too.

**Comment by kosz** [comment]
thanks a lot. I will start working on removing all NDA protected code, and isolating the error with some example code. I should have something ready in a few hours, pending some other meetings coming up.

**Comment by kosz** [comment]
@guybedford here is the app.js with code reproducing the issue 

https://github.com/kosz/silent-errors/blob/master/app.js

I have created a special repo, and I've also added some additional files that can provide additional insight on how things are setup. I have tested and reproduced the issue with this code as well, the Error inside the Angular factory does not print anything

**Comment by kosz** [comment]
@guybedford please hold off on this for now, as I can see there are some problems with my isolated use case, which I cannot address until tonight due to meetings. 

I will update this issue once I have a working isolated use case

**Comment by kosz** [comment]
@guybedford so long story short: 

- https://github.com/kosz/silent-errors/blob/master/app.js this code should be a good isolated example
- earlier I was uncertain if the code can reproduce the error because I noticed in angular .run functions ( `angular.module('modName').run` ) the Errors were printing
- I have now confirmed angular .run functions print the Errors but angular .factories and .controllers at least do not
- still not sure at this point if this is a TypeScript issue, a jspm/systemjs issue or just an angular issue

Next on my list will be ( unless you have other suggestions ) : 

- try without the bundle
- upgrade to a more recent angular version and see if that fixes the issue

**Comment by kosz** [comment]
So an interesting finding ... Building upon the latest discovery that .run functions print errors, but .factory functions don't, I've decided to catch and print the errors with console.log and look for differences. 

The code : 
```
try {
  throw new Error('test');
} catch (e) {
  console.log(e);
}
```
ended up printing slightly different things. 

#### console.log from .factory function ( the silent error )
```
Error: test
    at Object.<anonymous> (http://localhost:3000/app.js:616:31)
    at Object.invoke (http://localhost:3000/bower_components/angular/angular.js:4219:17)
    at Object.enforcedReturnValue [as $get] (http://localhost:3000/bower_components/angular/angular.js:4072:37)
    at Object.invoke (http://localhost:3000/bower_components/angular/angular.js:4219:17)
    at http://localhost:3000/bower_components/angular/angular.js:4037:37
    at getService (http://localhost:3000/bower_components/angular/angular.js:4178:39)
    at invoke (http://localhost:3000/bower_components/angular/angular.js:4210:13)
    at Object.instantiate (http://localhost:3000/bower_components/angular/angular.js:4227:27)
    at Object.<anonymous> (http://localhost:3000/bower_components/angular/angular.js:4088:24)
    at Object.invoke (http://localhost:3000/bower_components/angular/angular.js:4219:17)
```

#### console.log from a .run function ( a normal error which shows up )
```
Error: test non silent
    at http://localhost:3000/app.js:575:15
    at Object.invoke (http://localhost:3000/bower_components/angular/angular.js:4219:17)
    at http://localhost:3000/bower_components/angular/angular.js:4041:71
    at forEach (http://localhost:3000/bower_components/angular/angular.js:326:20)
    at createInjector (http://localhost:3000/bower_components/angular/angular.js:4041:3)
    at doBootstrap (http://localhost:3000/bower_components/angular/angular.js:1455:20)
    at bootstrap (http://localhost:3000/bower_components/angular/angular.js:1476:12)
    at Object.angular.bootstrap (http://localhost:3000/bower_components/oclazyload/dist/ocLazyLoad.min.js:8:12053)
    at HTMLDocument.<anonymous> (http://localhost:3000/app.js:4516:25)
    at jQuery.Callbacks.fire (http://localhost:3000/bower_components/jquery/dist/jquery.js:3099:30)
```

**Comment by kosz** [comment]
Also tested with the latest Angular 1.3. Angular 1.4 seems to have issues with other dependencies within the codebase, so I was unable to test under that. Will work on: 
- testing without a bundle
- stripping the app down of all dependencies and all source code, and have the ability to create a public repo with no NDA protected code which reproduces the problem

**Comment by kosz** [comment]
I guess the difference between angular.run and angular.controller/angular.factory, etc, is that .run does not go through a provider. 

I believe that there could be some sort of conflict between how providers are used and whatever jspm/systemjs/typescript do, in this case. This is the function in Angular 1.3 which triggers the error to be silent under the current configuration : 
```
  function enforceReturnValue(name, factory) {
    return function enforcedReturnValue() {
      var result = instanceInjector.invoke(factory, this);
      if (isUndefined(result)) {
        throw $injectorMinErr('undef', "Provider '{0}' must return a value from $get factory method.", name);
      }
      return result;
    };
  }
```

**Comment by kosz** [comment]
attn @guybedford : 

I was unable to duplicate this behaviour after removing all 47 bower dependencies that this project has. I am suspecting that this situation is caused by one of these dependencies, probably some poorly written code. Having said that, code that doesn't run through the transpiler, still prints errors just fine, even when used inside Angular providers.

**Comment by kosz** [comment]
I have isolated this issue, away from JSPM/SystemJS/TypeScript. 

Having said that, the issue only occurs when using JSPM/SystemJS/TypeScript. However it was caused by code which was monkey patching angular js internals

**Comment by guybedford** [comment]
Sure, no problem.
