### ISSUE TITLE
Add API function to resolve module installation path

### ISSUE THREAD

**Issue by gossel-j** [jspm/jspm-cli#1181]
Hello, I need a functionality on the API, this functionality is to get the installation path of an installed jspm module. Kind of like normalize but return the directory not the dist.js file.

I need this to get some other file in the libraries, like some CSS or assets.

Thanks

**Comment by gossel-j** [comment]
Sorry I just discovered that I can do this by using normalize and appending a trailing slash at the end of the module name.

**Comment by guybedford** [comment]
:+1: yeah it was a useful edge case to cover.
