### ISSUE TITLE
Alt (Flux) store Tests don't run on jspm/jasmine setup

### ISSUE THREAD

**Issue by jabhishek** [jspm/jspm-cli#1182]
I am working on application using Alt and was trying to setup tests based on jdelhman's example [here] (https://github.com/jdlehman/alt-example-tests). I tried to setup the tests in exactly the same way as described there but in jspm/karma/jasmine setup, but wasn't able to make them pass. I have setup a repository with the test on github [here](https://github.com/jabhishek/alt-es6-tests-example).

After spending hours on it, and after discussing with jdlehman, it appears that the tests are not working because of the way jspm handles modules - discussion [here](https://github.com/jdlehman/alt-example-tests/issues/3). Could you advise on this please and suggest any changes that I can make to make these tests work?

Thanks, Abhi.

**Comment by guybedford** [comment]
I guess you need to work out why `MyAlt.js` is executing multiple times here.

The only reason in jspm a module would ever execute multiple times would be if that same module was loaded from many paths like say `http://site.com/MyAlt.js` and `http://site.com/MyAlt.js?asdf` resolving to the same file. Perhaps look at the network tab to see if something like that is happening?

If it is not that, then another thing to do is to log the registry itself via `console.log(Object.keys(System._loader.modules))` to see if there are many entries for `MyAlt.js`.

If it is neither of the above, the only other reason code would run twice is if it is throwing an error and therefore each time you import retrying.

**Comment by jabhishek** [comment]
Hi Guy,

Thanks for looking into this and you were right. It is actually loading the MyAlt.js twice, but it was because the path in my import statement was different in my test js and my source js. In my test it was as follows:-
<code>import alt from 'src/MyAlt';</code>

While in my source js, it was like:-
<code>import alt from 'MyAlt';</code>

I am guessing that although they were both pointing to the same file, as the paths were different, it was trying to load it twice. I was able to fix it though by moving my test (PetStore-spec.js) in the same directory as my source file (PetStore.js), but it feels like a hack as I have to change my folder structure just to make my tests work.

It is quite possible that my karma configuration is wrong, which is causing this, or maybe I need to add some configuration to tell jspm that both the files are the same and it should load it once. I know you are not author of karma or karma-jspm, but could you advise me on this, in case you have any idea on this? I have posted my source code on github [here] (https://github.com/jabhishek/alt-es6-tests-example).

Thanks again for your help on this.

Abhi.

**Comment by guybedford** [comment]
@jabhishek glad to hear you managed to work it out. You can likely use map configuration to ensure that both files get the same version. Details on map configuration can be found in the SystemJS documentation.
