### ISSUE TITLE
Creating bundle with --inject fails

### ISSUE THREAD

**Issue by telekosmos** [jspm/jspm-cli#1183]
Hi
Trying to come up with a patch for [gulp-jspm](https://github.com/brillout/gulp-jspm) to support `--inject` option and get configuration file injected with the bundle tree, I came across with something maybe related to #853. 
Before starting to update the code, I ran a `jspm bundle ...` on the `demo` folder to see the result. I think this is easy to reproduce by getting the `demo` directory from [gulp-jspm](https://github.com/brillout/gulp-jspm) and, from it, just run `jspm bundle main.js build/app.js --inject` (after `npm install`, `jspm install` of course). I get the bundle (`build/app.js`) but the `src/config.js` doesn't get the build tree injected and I get the following error:
```
err  Error: Unable to calculate canonical name to bundle file:///Users/telekosmos/Dev/nodejs/gulp-jspm/demo/build/app.js
         at getCanonicalNamePlain (/Users/telekosmos/Dev/nodejs/gulp-jspm/demo/node_modules/jspm/node_modules/systemjs-builder/lib/utils.js:177:13)
         at getCanonicalName (/Users/telekosmos/Dev/nodejs/gulp-jspm/demo/node_modules/jspm/node_modules/systemjs-builder/lib/utils.js:88:19)
         at /Users/telekosmos/Dev/nodejs/gulp-jspm/demo/node_modules/jspm/lib/bundle.js:104:38
         at process._tickCallback (node.js:349:9)
```
I'm afraid this is related to the bit strange project structure (`config.js` isn't located in the same directory as `package.json` where the `jspm` command is run), but I'm not sure about it.
```
$ jspm -v
0.16.11
Running against local jspm install.
```
`systemjs-builder` version is 0.14.7

Cheers!!

**Comment by guybedford** [comment]
Is `file:///Users/telekosmos/Dev/nodejs/gulp-jspm/demo/build/app.js` your build file here? Or a module in your build?

This message just indicates that the baseURL must always be the lowest common reference point. There is now way to reference a module that is not a path or within the baseURL between both client and server hence this error.

**Comment by telekosmos** [comment]
Ok, thanks!
In addition to update the baseUrl in package.json, I had to add the __`configFile`__ property into the jspm section in order to set the `config.js` location.
