### ISSUE TITLE
SFX with optional dependencies

### ISSUE THREAD

**Issue by neothemachine** [jspm/jspm-cli#1185]
I just had the use case where I wanted to exclude a certain module from the bundle like `jspm bundle-sfx app - c3 --globals "{c3:'c3'}"` and then give the users the choice whether they then want to use the part of the library which requires c3. But it seems this is impossible since when loading the bundle it directly tries to load the c3 module and then fails if it doesn't find it. I had imagined that it would just do something like `modules['c3'] = window['c3']` and let the code fail later if the user actually tries to use that module. I know that all this is absolutely irrelevant when being in ESM land, but for now we have to support the classic way as well. And optional dependencies are quite common there.

**Comment by guybedford** [comment]
We could certainly investigate making this a soft failure.

**Comment by guybedford** [comment]
This would involve altering the `globalDeps.join` in https://github.com/systemjs/builder/blob/master/templates/sfx-global.js#L2 to be accessors on the global object.

**Comment by guybedford** [comment]
Moving to https://github.com/systemjs/builder/issues/360.
