### ISSUE TITLE
Babel runtime breaks Symbol.iterator support

### ISSUE THREAD

**Issue by mzgol** [jspm/jspm-cli#1186]
Consider the following code in file `app.js` (using jQuery 2.1.4):
```js
import $ from 'jquery';

if (!$.fn[Symbol.iterator]) {
    $.fn[Symbol.iterator] = Array.prototype[Symbol.iterator];
}

let counter = 0;
for (const div of $('<div></div><div></div>')) {
    counter++;
}
console.log('counter', 2);
console.assert(counter === 2, 'Iterability doesn\'t work!');
```
Try this in a browser without `Symbol` support; `Symbol` is definitely available in the code as otherwise it'd throw on the `if (!$.fn[Symbol.iterator]) {` check but it only throws later, in the `for..of`:
```
TypeError: [object Object] is not iterable!
```
This is with a default config that has:
```js
System.config({
  /* ... */
  babelOptions: {
    "optional": [
      "runtime"
    ]
  },
  /* ... */
});
```
If I remove the `"runtime"` option and attach the Babel's `browser-polyfill.js` via a script tag before the generated bundle, it works correctly. It's larger then, though, I assume if I use the Babel runtime only the parts that are needed are compiled into the bundle?

In both cases it works correctly in browsers with native `Symbol` support.

jspm 0.16.11, babel-core 5.8.25, core-js 1.2.1, jQuery 2.1.4.

**Comment by guybedford** [comment]
This sounds like an interaction between `core-js` `Symbol` global and the native Symbol? I take it the `Symbol` global in your ES module code is the `core-js` Symbol and not the native one?

**Comment by mzgol** [comment]
There is no global `Symbol` - as I described, if a global `Symbol` exists, it works fine (core-js doesn't replace the global it it's already present), it only breaks if Symbol is not natively available.

**Comment by mzgol** [comment]
It seems as if there were two `Symbol`s - one available to use in my ES6 code that's later compiled by Babel to a polyfill from core-js and another one being used to determine an iterator of an object. In that case, the second one is not found.

If I set up a breakpoint in the place where the transpiled for-of happens (it shows as `app.js!transpiled` because of a sourceURL comment), the last line of this snippet:
```js
if (!$.fn[_Symbol$iterator]) {
    $.fn[_Symbol$iterator] = Array.prototype[_Symbol$iterator];
}

counter = 0;
_iteratorNormalCompletion = true;
_didIteratorError = false;
_iteratorError = undefined;

try {
    for (_iterator = _getIterator($('<div></div><div></div>')); !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true) {
```
it fails in the `_getIterator` function:
```
TypeError: [object Object] is not iterable!
```

Is this a Babel issue? Perhaps the `_getIterator` function uses a polyfill separate from the core-js copy from babel-runtime.

**Comment by guybedford** [comment]
It could be a core-js issue.

**Comment by mzgol** [comment]
I confirmed it's not a jspm-specific issue. The following code:
```js
const o = {0: 'a', 1: 'b', 2: 'c', length: 3};
o[Symbol.iterator] = Array.prototype[Symbol.iterator];

let counter = 0;
for (const div of o) {
	counter++;
}
console.log('counter', 3);
console.assert(counter === 3, 'Iterability doesn\'t work!');
```
is transformed by:
```
babel --optional runtime iterable-test.js > iterable-test-transformed.js
```
to:
```js
'use strict';

var _Symbol$iterator = require('babel-runtime/core-js/symbol/iterator')['default'];

var _getIterator = require('babel-runtime/core-js/get-iterator')['default'];

var o = { 0: 'a', 1: 'b', 2: 'c', length: 3 };
o[_Symbol$iterator] = Array.prototype[_Symbol$iterator];

var counter = 0;
var _iteratorNormalCompletion = true;
var _didIteratorError = false;
var _iteratorError = undefined;

try {
	for (var _iterator = _getIterator(o), _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true) {
		var div = _step.value;

		counter++;
	}
} catch (err) {
	_didIteratorError = true;
	_iteratorError = err;
} finally {
	try {
		if (!_iteratorNormalCompletion && _iterator['return']) {
			_iterator['return']();
		}
	} finally {
		if (_didIteratorError) {
			throw _iteratorError;
		}
	}
}

console.log('counter', 3);
console.assert(counter === 3, 'Iterability doesn\'t work!');
```
After invoking:
```
npm i babel-runtime
```
this transformed script prints `3` correctly in Node 4.1.2 & 0.12.7 but in 0.10.40 it throws:
```
/Users/mgol/_/iterable-test-transformed.js:31
			throw _iteratorError;
			      ^
TypeError: [object Object] is not iterable!
    at TypeError (<anonymous>)
    at module.exports.require.getIterator (/Users/mgol/_/node_modules/core-js/library/modules/core.get-iterator.js:5:40)
    at Object.<anonymous> (/Users/mgol/_/iterable-test-transformed.js:16:23)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
```

I'll report it to core-js. It might be related to https://github.com/zloirock/core-js/issues/51.

**Comment by mzgol** [comment]
Submitted to core-js: https://github.com/zloirock/core-js/issues/118
