### ISSUE TITLE
jspm --link doesn't copy npm link'd dependencies.

### ISSUE THREAD

**Issue by dzearing** [jspm/jspm-cli#1187]
Our team is trying to embrace splitting work out into smaller micro repos that are single purposed. But we're having issues making jspm work in this flow.

Create an npm package repo A.
Create an npm package repo B which depends on A. npm link A inside B, so that A is symlink'd inside of B/node_modules.

Create your site package repo C that uses jspm. 
jspm link B inside C.

Expected: see A inside of jspm_modules/B/node_modules

Resulted: A is missing and the only way to get it to work is to ... avoid symlink scenarios? Xcopy A to B/node_modules before using jspm link? Ugh.

I'm not sure how this really should work. I expected jspm linking to do what npm link does, which is to symlink, but it seems instead to xcopy stuff to jspm's global repository, which is not a great dev experience for splitting work out into multiple smaller repos.

**Comment by guybedford** [comment]
Yes the current linking workflow is not ideal. We're moving to proper symlinking in jspm 0.17 and I'm working on getting an alpha of that out very soon.

Note that the symlinks would effectively be in `jspm_packages/...` as flat symlinks instead of nested.

**Comment by dzearing** [comment]
Thanks for the fast response Guy!

I tried jspm linking package A from within the site as well. But still upon jspm bundling, I get an error while traversing the dep graph that A doesn't exist inside of B/node_modules.

Excited to hear about symlinking in 0.17. Hope to see that drop soon.
