### ISSUE TITLE
`bundle` Command Not Tracing Dependencies when Using `System.amdDefine`

### ISSUE THREAD

**Issue by ryanfitzer** [jspm/jspm-cli#1189]
When I change all of my `define` functions into `System.amdDefine` and run the same `bundle` command, jspm does not trace the dependencies. Is this the expected behavior? I wasn't able to find anywhere that documented this behavior. Is there a config option I need to use?

**Comment by guybedford** [comment]
@ryanfitzer `System.amdDefine` is not a module format. It is designed only to enable global assignment via `window.define = System.amdDefine`.
