### ISSUE TITLE
Unable to bundle modules with defines prefixed with ./

### ISSUE THREAD

**Issue by rich-nguyen** [jspm/jspm-cli#1190]
Hi, I made a repro [here](https://github.com/rich-nguyen/jspm-bundle-issue) to demonstrate the issue.

The bundle command in that test repo fails because there is a [`'./video'` define( )](https://github.com/guardian/videojs-ima/blob/0.2.1/src/videojs.ima.js#L30) in the UMD module definition code, inside the package used by our app. In requirejs, a required module called `./video` still matches the 'video' path in our require config. This is not the case in jspm, which interprets the relative path in the context of the module located in jspm_packages. This looks like well-defined behaviour in system's builder whilst `Building the bundle tree`, which uses `traceModule` https://github.com/systemjs/builder/blob/master/lib/trace.js#L26.

This isn't necessarily an issue, more a question for advice. When I encounter a module such as this, is there an elegant way to deal with these kinds of paths? For our jspm packages in github, I will update the path to 'video'. Would be grateful for any info, @guybedford !

**Comment by guybedford** [comment]
@rich-nguyen you could try using map configuration to alter this resolution via an override or in the package.json with:

```json
{
  "jspm": {
    "map": {
      './src/video': 'path-to-video'
    }
  }
}
```

Just let me know if you have any issues with that.

**Comment by rich-nguyen** [comment]
I was partway through trying the map configuration, which looked to be working, however it's not supported in [curl](https://github.com/cujojs/curl/issues/277), so I didn't get to fully test it. So I ended up making sure module names are consistent throughout, which is probably best anyway. Thanks @guybedford

**Comment by guybedford** [comment]
Sure, no problem sir!
