### ISSUE TITLE
jsroot not found

### ISSUE THREAD

**Issue by awflierman** [jspm/jspm-cli#1192]
Installed jspm globally and local in my project. When I try to run "jspm install -y" I get the error: 

    **err  Registry jsroot not found.**

    **err  Unable to load registry jsroot**

**Comment by guybedford** [comment]
This would happen if you try to install `jspm install jsroot:x`. Have you got something like that in your package.json file dependencies?

**Comment by awflierman** [comment]
Don't know why but in the config.js there was a `jsroot` setting. Removed that one and it worked. Thanks a lot!
