### ISSUE TITLE
Bundling pagedown results in a bad bundle.

### ISSUE THREAD

**Issue by Zoltu** [jspm/jspm-cli#1195]
```
mkdir foo
cd foo
npm install jspm
node_modules/.bin/jspm install npm:pagedown
node_modules/.bin/jspm bundle pagedown
```
Look at the resulting `build.js` line ~`650-656`:
```
    if (typeof exports === "object" && typeof require === "function") {
      output = exports;
      Converter = req('npm:pagedown@1.1.0/Markdown.Converter').Converter;
    } else {
      output = window.Markdown;
      Converter = output.Converter;
    }
```

In particular, note how it is doing a `typeof` check against `require`.  If you drop into a debugger when using this you will see that `require` is undefined.  However, `req` (the function *actually* used in the method) is defined.

The problem appears to be that the bundler is generating code that should be doing a typeof check against `req` instead of `require`.

**Comment by guybedford** [comment]
I've added a fix for this in https://github.com/systemjs/builder/commit/1870422c25b7c10fff46d50b6435ea602595d7e4. If you're able to test against SystemJS Builder master, that would be a great help to ensure there aren't further regressions. Otherwise I will b doing some further testing when I can for a release.

**Comment by Zoltu** [comment]
Using JSPM, what is the easiest way to upgrade SystemJS to master for testing?  Is there a command I can run to temporarily swap it in and is there another command I can run to swap it back to stable?

**Comment by guybedford** [comment]
I guess this is npm usability - something like `cd node_modules/jspm && npm install https://github.com/systemjs/builder#master`?

**Comment by guybedford** [comment]
This should be working now in 0.16.13.
