### ISSUE TITLE
Is it possible to initialize the config file with no baseURL rather than '/'?

### ISSUE THREAD

**Issue by MeoMix** [jspm/jspm-cli#1196]
I'd like to run `jspm init -p` and have it setup the config file with no baseURL. Currently, if I provide " " or just hit enter then it defaults to '/'.

Using '/' as a root directory isn't a viable option for interacting with KarmaJS.

I can manually modify the config file after initialization, but re-initializing the config file results in paths breaking.

**Comment by guybedford** [comment]
Good point - perhaps we can make the prompt - `would you like to configure a baseURL?`.

**Comment by MeoMix** [comment]
Yeah I think that would work!

Do you think it's a reasonable use case for people to not want baseURL defined? It feels weird to fluctuate between "baseURL is so important it needs to be set only once and at the very start" and "actually, don't even worry about setting it ever"

**Comment by guybedford** [comment]
Great, no it makes complete sense - it often needs to be managed outside of the jspm config file.

**Comment by guybedford** [comment]
Supported in jspm 0.17 beta.
