### ISSUE TITLE
jspm bundle ignores baseURL in systemjs config

### ISSUE THREAD

**Issue by pawelgalazka** [jspm/jspm-cli#1197]
Fragment of my config for systemjs:

```javascript
System.config({
  baseURL: "/_cache/"
})
```

After command `jspm bundle react + react-dom _cache/react.bundle.js --inject`:

```javascript
System.config({
  baseURL: "/_cache/",
  bundles: {
    "_cache/react.bundle.js": [
      "npm:react-dom@0.14.0",
      "npm:react-dom@0.14.0/index"
  ]
})
```

Browser console:
```
GET http://localhost:9090/_cache/_cache/react.bundle.js 404 (Not Found)
```

After changing bundle key to `react.bundle.js`, thus:

```javascript
System.config({
  baseURL: "/_cache/",
  bundles: {
    "react.bundle.js": [
      "npm:react-dom@0.14.0",
      "npm:react-dom@0.14.0/index"
  ]
})
```
everything works.

Looks like jspm bundle do not take into consideration baseURL property during supplementing systemjs config.

**Comment by guybedford** [comment]
You need to provide two baseURLs - one reference as a browser URL, and another reference as a server path relative to the package.json file. These need to match up for paths to work correctly between client and server.
