### ISSUE TITLE
Intermittent issues when bundling: unable to load registry

### ISSUE THREAD

**Issue by OliverJAsh** [jspm/jspm-cli#1198]
Very occasionally when we bundle, we get the following error:

```
[16:59:39][Step 2/4] /home/ubuntu/buildAgent/work/4541e69dce9eb322/node_modules/jspm/lib/registry.js:186
[16:59:39][Step 2/4]     throw 'Unable to load registry %' + registry + '%';
[16:59:39][Step 2/4]                                                  ^
[16:59:39][Step 2/4] Unable to load registry %bower%
```

`jspm bundle` seems to mutate the jspm config file to invalid JSON (note the missing comma):

```
{
  "defaultTranspiler": "babel",
  "defaultRegistry": "jspm",
  "strictSSL": true,
  "registries": {
    "github": {
      "handler": "jspm-github",
      "remote": "https://github.jspm.io"
    },
    "npm": {
      "handler": "jspm-npm",
      "remote": "https://npm.jspm.io"
    },
    "jspm": {
      "handler": "jspm-registry",
      "remote": "https://registry.jspm.io"
    }
  }
}"bower": {
      "handler": "jspm-bower-endpoint"
    }
  }
}
```

Reconfiguring the registry corrects the config file.

Any pointers to where jspm bundle is mutating the config? I will take a look :smile:

**Comment by guybedford** [comment]
This usually happens due to multiple instances of jspm running at the same time together. I'm actually looking at better configuration locking for jspm 0.17. If you want to look into a patch that is welcome too.

**Comment by guybedford** [comment]
(I believe it's an actual file system lock that is needed)

**Comment by OliverJAsh** [comment]
@guybedford Can you point me to where the write is happening? I might have a look into this.

**Comment by guybedford** [comment]
@OliverJAsh sure, that would be great! The global config save function is at https://github.com/jspm/jspm-cli/blob/master/lib/global-config.js#L76. This is currently sync but usage could be upgraded to be async. It gets called within that file itself and then at https://github.com/jspm/jspm-cli/blob/master/lib/registry.js#L218.

The global config load does need to be sync though as that enables sync usage of builder class instantation for example.

**Comment by guybedford** [comment]
This should be fixed with the config lock in https://github.com/jspm/jspm-cli/commit/fa03ff55a5793ec9e760bbeab686e5a9c24d3ae5.

**Comment by guybedford** [comment]
(pending release)
