### ISSUE TITLE
Define Globals for all modules

### ISSUE THREAD

**Issue by NicolasSiver** [jspm/jspm-cli#1199]
How to reproduce same approach for globals as in Browserify:

**package.json**

```
 "browserify-shim": {
    "app": "global:app",
    "jquery": "global:$",
    "socket": "global:socket",
    "bootstrap": {
      "exports": "global:bootstrap",
      "depends": [
        "jquery"
      ]
    },
    "bootbox": {
      "exports": "global:bootbox",
      "depends": [
        "jquery",
        "bootstrap"
      ]
    }
  },
```

Then you can `import Bootbox from 'bootbox';` in any module.
Is it possible with _jspm_?

**Comment by guybedford** [comment]
This is possible with shim configuration - https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm#shim-configuration.

Support for all SystemJS package configurations is coming in jspm 0.17.
