### ISSUE TITLE
jspm depcache causes error in asn1

### ISSUE THREAD

**Issue by teohhanhui** [jspm/jspm-cli#1201]
I'm using [npm:object-hash]. Everything runs fine when using only injected vendor bundle, but if I do `jspm depcache` after that it errors out at the `inherits` call below:

npm:asn1.js@2.2.1/lib/asn1/decoders/der
```js
module.exports = DERDecoder;
DERDecoder.prototype.decode = function decode(data, options) {
if (!(data instanceof base.DecoderBuffer))
  data = new base.DecoderBuffer(data, options);
return this.tree._decode(data, options);
};
function DERNode(parent) {
base.Node.call(this, 'der', parent);
}
inherits(DERNode, base.Node);
```

More specifically because `superCtor.prototype` is `undefined` here:

npm:inherits@2.0.1/inherits_browser
```js
if (typeof Object.create === 'function') {
  module.exports = function inherits(ctor, superCtor) {
    ctor.super_ = superCtor;
    ctor.prototype = Object.create(superCtor.prototype, {constructor: {
        value: ctor,
        enumerable: false,
        writable: true,
        configurable: true
      }});
  };
} else {
  ...
}
```

[npm:object-hash]: https://www.npmjs.com/package/object-hash

**Comment by guybedford** [comment]
@teohhanhui thanks for posting. Let's track this at https://github.com/systemjs/systemjs/issues/848.
