### ISSUE TITLE
Improve error message for missing plugins?

### ISSUE THREAD

**Issue by pietschy** [jspm/jspm-cli#1203]
Hi there, 

I just spent a while scratching my head over `Error: ENOENT, open 'path/to/project/ts.js'` before i realised it might be the plugin (it had been working prior to an upgrade of typescript). I was also thrown as I'd had a fair bit of trouble getting the default extensions stuff working in the first place and it looked a bit like that.

Would it be difficult it to emit a more specific message when failing to load a plugin?

Thanks & cheers

**Comment by guybedford** [comment]
Thanks for posting, yes you are completely right. I actually just created an issue on SystemJS recently to track these cases in https://github.com/systemjs/systemjs/issues/849.

**Comment by pietschy** [comment]
Thanks @guybedford.  I was also thinking of raising a similar issue for missing imports (as the error message only displays the missing file but not the file that's trying to import it).  Should I raise this in system js as well?

**Comment by guybedford** [comment]
@pietschy we can track that in the same issue, as this is a load stack specific to plugins - other load errors should always report the parent load already. Although if I'm wrong do post an issue!
