### ISSUE TITLE
Dependency bundle contains html, css and json modules from app

### ISSUE THREAD

**Issue by nestabur** [jspm/jspm-cli#1204]
I have an scenario where we need to split dependencies and application src in two different bundles (as far as I've seen, this is a common approach and supported by jspm). I've achieved it by executing:
<pre>
$ jspm bundle index - '[npm:**/*]' - '[github:**/*]' 
$ jspm bundle app/**/* - [app/**/*]
</pre>
The problem is that when building the dependency bundle modules belonging to the app are also added (not excluded) like:
<pre>
app/application.html!github:systemjs/plugin-text@0.0.2
</pre>
So the module is included in both bundles.
This happens only with no-javascript files (css, html, json).

But first of all, is my approach correct?

**Comment by guybedford** [comment]
@nestabur yes this is the correct approach.

Plugins need to be excluded separately via something like `jspm bundle app/**/* + app/**/*.html!text - [app/**/*]`.

**Comment by teohhanhui** [comment]
@guybedford I've tried the above command but it's not working as expected... Is there a mistake?

**Comment by guybedford** [comment]
@teohhanhui it would depend on knowing the specifics of your build paths and what is not being included / excluded that should be to be able to help here.

**Comment by teohhanhui** [comment]
@guybedford

The bundle commands I normally use:
`jspm bundle 'app/**/* - [app/**/*] - config.json!systemjs-json' 'public/vendor.js' --inject`
`jspm bundle '[app/**/*] + config.json!systemjs-json' 'public/app.js' --inject`

`public/app` is a (relative) symlink to `../src`

What I wish to achieve is to exclude any .css files under `app` directory from the `vendor` bundle, e.g. `app/components/tour-destination/component.css`

**Comment by guybedford** [comment]
Can you confirm adding `- app/**/*.css!` doesn't work here in that case?

**Comment by teohhanhui** [comment]
@guybedford I can confirm that it does not work.

Running

`jspm bundle 'app/**/* - [app/**/*] - app/**/*.css! - config.json!systemjs-json' 'public/vendor.js' --inject`

still gives me these

```
app/app.css
app/components/itinerary-item-hotel/component.css
app/components/itinerary-item/component.css
app/components/tour-destination/component.css
```

**Comment by guybedford** [comment]
@teohhanhui it looks like your CSS files are loaded by configuration not syntax, so you probably want to just do:

```
jspm bundle 'app/**/* - [app/**/*] - config.json!systemjs-json' 'public/vendor.js' --inject
```

The reason the above wouldn't work though is due the `defaultJSExtensions` configuration option in SystemJS effectively turning the above into `'app/**/*.js - [app/**/*.js]'`.

Do you have a defaultExtension set via package configuration? That should be the way to ensure the first command above works here.

**Comment by teohhanhui** [comment]
My package configuration is as above: https://github.com/jspm/jspm-cli/issues/1204#issuecomment-166861392

What do I need to change?

**Comment by guybedford** [comment]
@teohhanhui add `defaultExtension: false`. Then that means having `.js` in all your imports as well. I've created https://github.com/systemjs/builder/issues/447 to track support with `defaultExtension` set.

**Comment by teohhanhui** [comment]
That's not an ideal solution due to the ".js" everywhere, but is that the direction jspm is moving towards too? That kind of module ID seems to be inconsistent with the other loaders (node, babel...)

**Comment by guybedford** [comment]
Specifying the extension explicitly is actually the best-practice yes.

**Comment by teohhanhui** [comment]
Best practice according to who? I can't find any reference to support that... I know the Loader spec was left out of ES2015, but if SystemJS has its own best practices different from node, babel etc. it will kinda defeat the purpose of having a (more or less) standards-based module loader...

**Comment by guybedford** [comment]
@teohhanhui due to that fact that module specifiers are by default relative URLs (`./x.js`), with extensions optional only for direct package namespace includes (`jquery`). This is how the `<script type="module">` is being implemented which in turn determines this best-practice.

**Comment by teohhanhui** [comment]
From https://github.com/whatwg/html/pull/443#issuecomment-167898113

> The idea is that src is always URLs, and never goes through any custom resolution logic. (Neither the simple custom resolution logic in this patch, or any more complicated custom resolution logic if author-customizable loaders are implemented.) That way src gets treated the same as any other URL-containing HTML attribute.

That's not the case at all for SystemJS (nor should it apply to the `import` statement).
