### ISSUE TITLE
Source map "sourcesContent" is empty

### ISSUE THREAD

**Issue by KristianSelnas** [jspm/jspm-cli#1205]
I want to run bundled code during development, in order to develop and test on the same artefacts as being used in production. I've created a small app to test this workflow. It works perfectly, apart from the fact that the generated source map file's `sourcesContent` is empty.

See https://github.com/KristianSelnas/jspm-es6-demo 

The bundle is created with `jspm bundle-sfx src/app dist/app.js --source-map-contents` (see gulpfile.js). The generated source map file has a `sourcesContent`section where all the items are `null`. [The source maps specification](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit) states that
> “null” may be used if some original sources should be retrieved by name.

My source is located under `src/` and the bundled files are placed under `dist/`. The `sources` in the generated source map file have relative paths from `dist/` to their location under `src/`. When I start a web server (gulp-connect with `root: dist/`) the web server will obviously not be able to load the source files as they are located outside the web root.

Is this a bug, or is there some other way of getting the actual source (rather than `null`) included in the `sourcesContent`?

**Comment by johanhar** [comment]
+1

**Comment by guybedford** [comment]
I had a quick look at this and it actually seems to be Babel-specific. The problem happens where we run transpilation at https://github.com/systemjs/builder/blob/master/compilers/esm.js#L147, the source map often comes back empty. My best guess is this may have to do with jspm configuration of Babel for running builds of source maps correctly.

**Comment by guybedford** [comment]
Switching Babel to the `require('babel')` over `System.import('babel')` value makes this work, so unfortunately this is a jspm configuration issue. This involves posting a Babel issue to investigate why the browser build of Babel doesn't generate source maps correctly in Node, but it is already pushing it to assume this use case, so I'm weary to worry Seb with it. This will become resolvable in jspm 0.17 when we can load Node libraries (like Babel) as they expected to be loaded in Node. Apologies there isn't a quick fix for this one.

If you want a work around - add the following to SystemJS Builder  `jspm/node_moules/systemjs-builder/compilers/esm.js` before line 116:

```javascript
transpiler = require('babel')
```

We can't publish this as it breaks the contract that the local project controls the Babel version as this reverts to a `npm install babel` for use.

**Comment by KristianSelnas** [comment]
Thanks for taking the time to investigate this issue. We'll consider whether the workaround can be used in our real life project. If not, I guess we'll have to wait for 0.17. Do you know when we can expect 0.17 to be released?

**Comment by davinkevin** [comment]
+1

**Comment by guybedford** [comment]
One thing that might help here would be to actually run this as a bisection against Babel commits to find out exactly what changed, as this was working.

**Comment by guybedford** [comment]
This should be fixed in https://github.com/systemjs/builder/issues/427 pending release of the SystemJS builder update coming soon.
