### ISSUE TITLE
With depCache unnecessary files load at the end

### ISSUE THREAD

**Issue by neothemachine** [jspm/jspm-cli#1208]
Observable here: http://reading-escience-centre.github.io/leaflet-coverage/

For example, during the bulk depcache loading phase, it loaded "https://npm.jspm.io/iota-array@1.0.0.js". After that phase, it loads "https://npm.jspm.io/iota-array@1.0.js". There are more examples like that, but it doesn't happen for all modules.

**Comment by guybedford** [comment]
Thanks, posted as a CDN bug at https://github.com/jspm/project/issues/31.
