### ISSUE TITLE
SFX bundles breaks class inheritance

### ISSUE THREAD

**Issue by richburdon** [jspm/jspm-cli#1209]
I have a very strange bug that causes the following error when creating sfx bundles (the code works fine without the sfx option):

    Uncaught TypeError: Super expression must either be null or a function, not undefined

The minimal repro requires 3 files:

    [a.js]
    import { B } from 'b';
    new B();

    [b.js]
    import { C } from 'c';
    export class B extends C {}

    [c.js]
    export class C {}

This fails with the Uncaught TypeError.

BUT! If you add "import { C } form 'c';" to [a.js] then it works (even though a does not depend directly on c).

NOTE: this error is usually called when a super() is missing in the derived class' constructor, but this is not necessary in this repro, and adding them makes no difference.

Is something broken with transitive dependencies for class inheritance (i.e., class definitions need to be gathered and declared using the same DAG that they are defined?)

**Comment by guybedford** [comment]
This definitely works fine for me. Are you using TypeScript or something here to have the non-standard `import { C from 'c' }`? `import {C} from 'c'` is the proper form.

**Comment by richburdon** [comment]
I've corrected my original post (the import syntax was a typo in creating the issue, I am using the standard syntax). I'm not using TypeScript -- just regular ES6 modules. Everything works until I use the SFX option (have been using JSPM and this plugin successfully for months, but not trying to compress for production and both sfx and minify fail).

The minimal example above is a repro for me (I stripped down my complex app to get the minimal form that fails). Would it be helpful to create a github repo? Anything else I can try to debug?

[background.min.js] // My app.
  function ensureEvaluated(moduleName, seen) {
    ...
    entry.evaluated = true;
    entry.module.execute.call(global);    <==== TypeError
  }

Uncaught TypeError: Super expression must either be null or a function, not undefinedexports.default @ inherits.js:7(anonymous function) @ chrome.js:12execute @ chrome.js:12ensureEvaluated @ background.min.js:347ensureEvaluated @ background.min.js:339ensureEvaluated @ background.min.js:339load @ background.min.js:371(anonymous function) @ background.min.js:424(anonymous function) @ background.js:12(anonymous function) @ background.min.js:386(anonymous function) @ background.js:12

**Comment by richburdon** [comment]
Guy, in preparing the repro repo, I found the problem. I had a circular import dependency in an internal library that I was importing. Again, there is no error unless I build an SFX module. This is consistent with my "transitive dependencies" guess above. 

Is it possible to test for this in the bundle mechanism and provide a warning (since it's quite difficult to debug)?

Cheers.

**Comment by guybedford** [comment]
@richburdon circular references are difficult to debug unfortunately. There shouldn't be execution differences between build and development though, so it would be good to resolve this. Is there any way you can share a repo that replicates the problem. The only thing that should affect this execution order is if explicitly running say `jspm bundle-sfx a.js + b.js + c.js` for example, which would break them. Otherwise `jspm bundle-sfx a.js` should retain the execution ordering from the entry point.
