### ISSUE TITLE
Support the "depcache" operation on the JSPM API

### ISSUE THREAD

**Issue by ovidiom** [jspm/jspm-cli#1210]
While the JSPM API already supports several operations available from the command line (like install, bundle, ...), it does not support the "depcache" operation. Is there some way to use this functionality through the programmatic API or could this be added to the API? See also #172 .

**Comment by guybedford** [comment]
There is a depCache API example at https://github.com/jspm/jspm-cli/blob/master/docs/api.md#class-builder.

**Comment by ovidiom** [comment]
Thanks for the rapid feedback.

I had seen this API to retrieve the dep cache but I rather meant to provide an API which exposes the same functionality as executing "jspm depcache" on the command line, which not just extracts the dep cache but also writes it back to the SystemJS config file.

E.g. I can use the following code in order to create a bundle which is equivalent to executin "jspm bundle" on the command line:

```
var jspm = require('jspm');
jspm.bundle('my/module', 'bundle.js', { sourceMaps : true, inject : true });
```

However, from what I see, I cannot do the same for the dep cache functionality since the depCache function which actually exists in the bundle.js file is not exposed in the api.js file. I might be able to use the functionality in the bundle.js file directly but I think that it would be nice to expose it through the api.js file.

**Comment by guybedford** [comment]
Yes a configuration API is not currently available. It would be advisable to create a separate config file anyway when using a depCache API though, as you probably don't want to check it into your repo. Such an API may well be available in future, but we will see how the new configuration work goes.
