### ISSUE TITLE
err  URIError: URI malformed

### ISSUE THREAD

**Issue by jesstelford** [jspm/jspm-cli#1211]
Similarly to #932;

I am getting the following error:

```
$ ./node_modules/.bin/jspm install

err  URIError: URI malformed
         at decodeURIComponent (native)
         at Npmrc.getAuth (/Users/jtelford/dev/test/node_modules/jspm-npm/lib/npmrc.js:68:16)
         at Object.NPMLocation (/Users/jtelford/dev/test/node_modules/jspm-npm/lib/npm.js:59:23)
         at Object.exports.load (/Users/jtelford/dev/test/node_modules/jspm/lib/registry.js:72:56)
         at new RegistryPath (/Users/jtelford/dev/test/node_modules/jspm/lib/config/loader.js:261:33)
         at Config.read (/Users/jtelford/dev/test/node_modules/jspm/lib/config/loader.js:126:26)
         at /Users/jtelford/dev/test/node_modules/jspm/lib/config.js:100:26
         at process._tickCallback (node.js:356:9)
         at Function.Module.runMain (module.js:477:11)
         at startup (node.js:117:18)

err  Unable to load registry npm

warn Installation changes not saved.
```

My installed version:

```
$ ./node_modules/.bin/jspm --version
0.16.12
Running against local jspm install.
```

I can `npm install` packages fine, and I have all proxies, etc, disabled.

*Update*: I investigated my npmrc based on the error output, and found some malformed lines:

```
$ npm config list
; cli configs
user-agent = "npm/3.3.6 node/v4.1.0 darwin x64"

; userconfig /Users/jtelford/.npmrc
//https-proxy = "http://proxy.int.f2.com.au:8080/"
//proxy = "http://proxy.int.f2.com.au:8080/"
//registry.npmjs.org/:always-auth = false
//registry.npmjs.org/:email = "jess+npmjs@jes.st"
//registry.npmjs.org/:username = "jesstelford"
init.author.email = "hi@jes.st"
init.author.name = "Jess Telford"
init.author.url = "http://jes.st"
registry = "https://registry.npmjs.org/"

; node bin location = /Users/jtelford/.nvm/versions/node/v4.1.0/bin/node
; cwd = /Users/jtelford/dev/test
; HOME = /Users/jtelford
; "npm config ls -l" to show all defaults.
```

I commented those out, and now things work.

Why is it that npm can happily get past this, but jspm fails?

**Comment by guybedford** [comment]
The failure was actually on reading your password. Did you have a `:_password` entry in your npmrc?

**Comment by jesstelford** [comment]
I do! Good catch:

```
registry.npmjs.org/:_password=<redacted>
```

I'm not sure what the format should be there, but it looks like an alpha-numeric hash of the password?

Is there anything (other than providing the password itself) I can do to help debug?

**Comment by guybedford** [comment]
Sure, yes it would be an amazing help if you could enter the following in the console:

```
decodeURIComponent(new Buffer('<password value>', 'base64').toString());
```

And see if you can isolate tell which characters decodeURIComponent fails on that?

**Comment by guybedford** [comment]
Did you manage to test this further at all?

**Comment by dak0rn** [comment]
I am also affected by this.
The base64'ed password `.npmrc` contained characters like brackets not suitable for URLs.
Thus, `decodeURIComponent()` throws if you apply it with the password.

Changed the password so that it does only consist of URL-safe characters and it works.

**Comment by guybedford** [comment]
@dak0rn can you share a modified example of a password that will throw in the `decodeURIComponent` here?

**Comment by dak0rn** [comment]
I recreated the `.npmrc` file with the the `npm` CLI and it now uses an [auth token](http://blog.npmjs.org/post/118393368555/deploying-with-npm-private-modules) where the issue does not occur.

I wrote it manually and managed to reproduce the issue, here are some examples:

```
LmI2Snd1VntFJXJIbjgqd3socTl2
.b6JwuV{E%rHn8*w{(q9v

JX5+JXt7YmFkcGFzc3dvcmR9fSEh
%~~%{{badpassword}}!!

bG9va2F0bXlzcGVjaWFsY2hhcmFjdGVyOiU=
lookatmyspecialcharacter:%
```

**Comment by guybedford** [comment]
@dak0rn thanks so much for following up here, this should be fixed in https://github.com/jspm/npm/commit/3836b6f0310070cd6093f1a9cd2f630e48bd32e5.

**Comment by dak0rn** [comment]
@guybedford  Glad I could belp!
