### ISSUE TITLE
Controlling the jspm folder names and modulenames

### ISSUE THREAD

**Issue by pusulurm** [jspm/jspm-cli#1212]
I have couple of issues.
1) When i install a package, by default its creating the folder name with version in jspm folder. Is there a way to avaoid the version? I tried with assignment of a name while installation. It just changes the path in config.js.

2) When i generate a bundle, the main module name(main file) generated  has the complete path 
  as module name. npm:<packagename>@3.8.9/host/src/js/main. I just want this name to be host/main.

Please let me know if there is a way to achieve this.

**Comment by guybedford** [comment]
jspm has these conventions built in so there is no way not to use them unfortunately.
