### ISSUE TITLE
Installation fails on lookup

### ISSUE THREAD

**Issue by Mosho1** [jspm/jspm-cli#1215]
I'm getting `error looking up <packageName>` with ECONNRESET on random packages from multiple machines when I try to `jspm install`. The same packages can be installed via npm itself. 

Using v0.16.13.

**Comment by guybedford** [comment]
We still do some github lookups even when installing packages from npm. Perhaps this is github instability?

**Comment by Mosho1** [comment]
This is still happening, very consistently, to the point where I can barely install anything at all. I doubt it's GH instability since it's been happening for weeks now.

**Comment by guybedford** [comment]
Is this specifically for GitHub or npm packages? It's definitely a network issue - the question is how the connection is being reset along the pipe. The command we're running for GitHub is just `git remote-ls https://github.com/repo/name.git`.

**Comment by Mosho1** [comment]
it seems to happen just for npm, though I have relatively few GH dependencies. This might have started happening after updating to node 4.0.0, but I would assume that it's something specific about my network if you haven't heard about this from anyone else.

**Comment by Mosho1** [comment]
So it turns out this is due to something faulty in our router/connection. This has affected other applications as well, so I wouldn't worry about it. npm never stopped working though, so I assume it has a mechanism in place to retry specific packages during an install.

**Comment by guybedford** [comment]
Great, thanks for the follow-up.
