### ISSUE TITLE
Package item not resolved correctly?

### ISSUE THREAD

**Issue by leepowellcouk** [jspm/jspm-cli#1216]
I have defined a package in my config like so:

    baseURL: "/",
    packages: {
        "lib/module-a": {
          "main": "index.js",
          "format": "es6",
          "loader": "babel",
          "map": {
            "foo": "./data.js"
          }
        }
      }

Inside the `module-a` directory are two files: `index.js` and `data.js` (mapped to `foo` for purposes of demo).

Each look like:

**index.js**

    import _ from 'lodash';
    import { people, ages } from 'foo';
    export const data = _.zip(people, ages);

**data.js**

    export const people = ['John', 'Jess', 'Dave', 'Isla'];
    export const ages = [32, 26, 35, 37];

In my main `index.html` file I am simply loading these with:

    System.import('lib/module-a').then(function (module) {
      /** ... */
    });

Now, this all works as expected in development mode with Babel transpiling on the fly etc. However when I try to run a `jspm bundle lib/module-a/index.js build.js` I get the following error:

    Error on fetch for foo.js at file:///Users/leepowell/Sites/jspm/foo.js
    Error: ENOENT: no such file or directory

It's trying to resolve `foo` from the baseURL rather than relatively from the package. What am I missing?

**Comment by guybedford** [comment]
Are you including the same configuration in the built application? Builds don't build in configuration by default.

**Comment by leepowellcouk** [comment]
That's the only configuration file I have - but it never makes it through the bundle build

**Comment by guybedford** [comment]
You will need to include the configuration file with a script tag in the built app, after SystemJS and before the bundle script tag itself for names to work out correctly.

**Comment by leepowellcouk** [comment]
Sorry, maybe I haven't described the problem very well. But the problem is happening when running the following from the command line to build a bundle.

    jspm bundle lib/module-a/index.js build.js

Then I get the error:

    Error on fetch for foo.js at file:///Users/leepowell/Sites/jspm/foo.js
    Error: ENOENT: no such file or directory

**Comment by guybedford** [comment]
There must be something you're not telling me, because if I set up the example exactly as you described in a plain application it seems to work ok for me?

**Comment by guybedford** [comment]
Perhaps make sure you are running the latest version of jspm? (0.16.13)

**Comment by leepowellcouk** [comment]
Just went to create a demo for you, and noticed that baseURL in my package.json was somehow missing. Put it back and it now all works. Sorry for taking up your time!

As a sidenote - I accidentally discovered `jspm build` (typed it instead of bundle) and it started to do something but then threw an error about missing rimraf. Can't find any documentation about that feature though. Is it a deprecated method?

**Comment by guybedford** [comment]
Glad to hear it is resolved. Yes `jspm build` is deprecated!
