### ISSUE TITLE
Packakge override for defaultExtension not working in 0.16.13

### ISSUE THREAD

**Issue by NicholasGW** [jspm/jspm-cli#1218]
Hey, was just trying to setup something like was mentioned at the end of #566 :

     System.config({
      defaultJSExtensions: true, // this is overridden by the package config below
      packages: {
          // where [baseURL]/app is the local code
         'app': {
          defaultExtension: 'jsx'
        }
       }
     });  
  
This doesn't seem to work in 0.16.13; the jsx extension is added even when another is specified in the import, i.e.

    import Test from 'app/test.js'  
  
Will look for app/test.js.jsx. I thought this might be my paths etc, but I had a project using 0.16.0 with a similar setup that worked, and downgrading to 0.16.0 on the new project fixed the issue, so I thought I'd open a new bug.

**Comment by guybedford** [comment]
@NicholasGW are you sure the package config is applying at all? For example if you set `main: 'asdf'` and do `System.import('app')` do you get a request to `app/asdf`?

**Comment by NicholasGW** [comment]
Hey @guybedford, it appears the package config is applying as I tried your above example and the request for the main file was correct, however the error persists. I put together a small case to reproduce in my repo here if that's easier to look at: https://github.com/NicholasGW/jspmExtensionTest/tree/master  
  
Let me know if there's any additional cases etc you'd like me to try!

**Comment by guybedford** [comment]
@NicholasGW ah, yes this was actually a change in SystemJS 0.19 - the reason being to support `import 'some.file'` to support extension adding. The way to allow your case here is to add the configuration:

```javascript
System.config({
  packages: {
    app: {
      defaultExtension: 'jsx',
      modules: {
        'test.js': true // (or an empty object)
      }
    }
  }
});
```

That is, the package meta allows custom extension rules to be made.

**Comment by speigg** [comment]
What does `'test.js': true` do in the module meta? How are custom extension rules specified? 

I'm running into an issue where I am writing an override for a package which uses default js extenions except when loading a `.json` file. Right now, jspm is making requests to that `json` file which end with `json.js`. In the scope of this package, I'd like to keep the default `js` extension for all imports except for imports that end in `.json`. Any help would be appreciated.
