### ISSUE TITLE
Synchronized version for "normalize" for Loader API.

### ISSUE THREAD

**Issue by typhonrt** [jspm/jspm-cli#1219]
Greets,

It would be great to get a synchronized `normalize` method. I currently have an ESDoc plugin (https://esdoc.org/) which makes ESDoc aware of JSPM / SystemJS and makes it possible to build documentation linking across any number of modules / repos, etc loaded that have dependencies between them. There is no way to handle a Promise in the ESDoc plugin execution model.

I have an experimental implementation though that does two step processing performing all Loader normalization as a preprocess step in Gulp which then kicks off ESDoc w/ extra config info to complete the task. If there was a synchronized normalization method I could move that preprocess step into the ESDoc plugin and make things self-contained for a releasable version for others to more easily use.

Here is an issue I posted on the ESDoc repo inquiring if they could handle an asynchronous (callback based or return a Promise IE like Gulp) plugin execution model. Another simpler solution (perhaps?) is a synchronized `normalize` method with the Loader API itself.

Refer to the ESDoc issue as I link to the current experimental implementation and show how cool it is to be able to use ESDoc generically with SystemJS / JSPM:
https://github.com/esdoc/esdoc/issues/135

**Comment by guybedford** [comment]
Did you try `System.normalizeSync`?

**Comment by typhonrt** [comment]
Shit.... ;P

Yeah.. That'll work. Perhaps add that to the docs... :+1: When I quickly traced into the loader API code I didn't see a synchronized version exposed; didn't go deep enough apparently.
