### ISSUE TITLE
Shimming a local module?

### ISSUE THREAD

**Issue by Ryan-Anderson** [jspm/jspm-cli#1222]
I'm moving a package of a larger project to system.js from require.js. If I have a module in another package of my project, `local.js`, how can I shim this module? Assuming that my package cannot be modified.

Previously, I was using requirejs, which looked like:

```
requirejs.config({
  shim: {
    'local.js': [ 'dep' ]
  }
}}
```

Linking doesn't appear to be quite what I want, since I do not plan to publish these modules to a registry.

**Comment by typhonrt** [comment]
I also converted over from RequireJS recently. Try putting your shim in the `meta` part of config.js like

```
meta: {
   'local.js': {
      deps: [ 'dep'],
      exports: 'export`
   }
}
```
