### ISSUE TITLE
how to configure to Install modules from gitlab.corporate.xxxx.com

### ISSUE THREAD

**Issue by manju-reddys** [jspm/jspm-cli#1224]
Hi,

I'm setting up the project to use Systemjs ( + JSPM) + Angularjs 1.4.7. I could able to download all the libraries from github and npm but I couldn't find a way to download the modules in my company repo.

my company repo: https://gitlab.corporate.xxx.com/common-core/dx. I can download it by bower but how can I in `jspm install ??`.

Please guide me.

Thanks,
Manjunath Reddy

**Comment by guybedford** [comment]
A custom company registry can be created via jspm-git. See https://github.com/Orbs/jspm-git.
