### ISSUE TITLE
JSPM update not changing version number in package.json

### ISSUE THREAD

**Issue by pusulurm** [jspm/jspm-cli#1225]
Hi,

I've recently started using jspm for bundling packages. I observed that when i update jspm , the package version number is not updated in package.json file. But its been updated to config.js map section.   

Thank you.

**Comment by dsebastien** [comment]
I've observed the same behavior. It's sometimes annoying when you update your dependencies and you find out that package.json still refers to the old versions.

At some point I thought that the '--save' and/or '--save-dev' options existed like with npm but I think they don't.. Maybe they should? :)

**Comment by OrKoN** [comment]
Can you provide an example of a package.json that does not get updated with jspm update? I wonder how the version ranges are defined in it.

**Comment by guybedford** [comment]
This feature is being tracked in https://github.com/jspm/jspm-cli/issues/706.
