### ISSUE TITLE
Deprecation warnings in chrome 46.0.2490.71 (64-bit)

### ISSUE THREAD

**Issue by mdelbuono** [jspm/jspm-cli#1226]
Hi, after updating chrome to Version 46.0.2490.71 (64-bit) on Ubuntu 14.04, yesterday, I started having the following warnings.

```
'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead. (system.src.js:1028 )

'webkitIndexedDB' is deprecated. Please use 'indexedDB' instead. (system.src.js:1028 )
```

It's just a deprecation warning and it doesn't prevent my program from running, but you may want to fix this.

**Comment by lookfirst** [comment]
Welcome to my hell. =)

Adding this to my config.js fixed it...

```
  meta: {
    "core-js/modules/$.global": {
      "esmExports": false
    }
  },
```

But that doesn't seem to work when I bundle things. =(

**Comment by guybedford** [comment]
Yes that is the correct config. Builder support for this is tracking in https://github.com/systemjs/builder/issues/338.
