### ISSUE TITLE
Child dependencies can't be accessed

### ISSUE THREAD

**Issue by screendriver** [jspm/jspm-cli#1228]
I have written library called `A`. There is also a library called `B` that depends on `A`. In a library called `C` I have a direct dependency to `B` and want to work there with `A` **and** `B`.

```sh
$ ~/Development/c
$ jspm install b
```

If I look in my `jspm_packages` directory I can see that `A` and `B` gets installed and a mapping in my `config.js` is present as well. So far so good. But if I want to access a module from `A` I get following jspm bundling error:

```sh
[13:24:56] Error on fetch for a.js at file:///Users/me/Development/c/src/a.js
	Error: ENOENT: no such file or directory, open '/Users/me/Development/c/src/a.js'
    at Error (native)
```

Now if I install `A` as direct dependency

```sh
$ jspm install a
```

it works. Is there something I am missing? I thought if I install a package that has child dependencies, I can access the child dependencies as well. Or is it good practice to install all needed dependencies a direct dependencies in my project?

**Comment by capaj** [comment]
@screendriver yes, it is needed. If you would rely on package b having as child a, then your app could get broken when b package substitutes it's a dependency with some other.

So this is not a bug, it is a feature.

**Comment by screendriver** [comment]
@capaj thank you for the explanation. So my first thought was right.
