### ISSUE TITLE
Upgrading JSPM to 0.16 has caused quite a few problems

### ISSUE THREAD

**Issue by Quirksmode** [jspm/jspm-cli#1229]
I have been using JSPM really happily for quite some time now, though I have always been using version 0.15. Since a recent Chrome update I started getting the depreciation warnings:

'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.
system.js:1232 'webkitIndexedDB' is deprecated. Please use 'indexedDB' instead.

After seeing these I thought now would be a good time to upgrade everything, but in doing so I seem to have created new problems and frustratingly the warnings have not disappeared. Firstly a few of the Packages I had used stopped working, which I appreciate is a 3rd party issue so I have removed these for now and will solve later. The biggest problem is when I try to now run systemjs builder it gives me the following error:

{ [Error: Error loading "app/src/modules/bootstrap" at file:/Users/quirksmode/_Files/Work-BYND/www/project/frontend/app/src/modules/bootstrap.js
Error loading "npm:babel-core@5.8.29" at file:/Users/quirksmode/_Files/Work-BYND/www/project/frontend/jspm_packages/npm/babel-core@5.8.29
EISDIR, read] errno: -21, code: 'EISDIR' }

I have no idea how I can fix this as it was all working great before, do you have any ideas?

**Comment by Quirksmode** [comment]
To follow on for this, I managed to get the system-builder to work, but to do so I had to change your recommended config.js which greatly worries me. I changed:

`paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },`


to:

`paths: {
    "github:*": "jspm_packages/github/*.js",
    "npm:*": "jspm_packages/npm/*.js"
  },`

Why does this fix it? I have also added the following, but still get the webkit depreciation errors.

`meta: {
    "core-js/modules/$.global.js": {
      "esmExports": false
    }
  },`

And finally, I still get a ton of warnings when I run systemjs builder:

`[BABEL] file:/Users/quirksmode/_Files/Work-BYND/www/project/frontend/app/src/modules/bootstrap.js: Deprecated option metadataUsedHelpers: Not required anymore as this is enabled by default`

By the way I am a massive advocate of JSPM and have been sharing it with everyone plus using it on some high profile projects so really keen to understand and clean up all these problems as it will make it a lot easier for me to share the love (and examples) with other devs. Any help (as always) is massively appreciated.

**Comment by guybedford** [comment]
See https://github.com/jspm/jspm-cli/releases/tag/0.16.0 for information on upgrading to 0.16.

You need to add `defaultJSExtensions: true` to the config file in the upgrade, which should have been added automatically by jspm though.

Yes the `esmExports` is the right thing to do there.

Update babel via `jspm dl-loader --latest` or `jspm update babel` to remove those Babel warnings.

**Comment by Quirksmode** [comment]
Sadly, neither of these have worked for me. This is my config.js

`System.config({
  baseURL: "/",
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "optional": [
      "runtime",
      "optimisation.modules.system"
    ]
  },
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },

  meta: {
    "core-js/modules/$.global.js": {
      "esmExports": false
    }
  },

  map: {
    "Magnific-Popup": "github:dimsemenov/Magnific-Popup@1.0.0",
    "angular": "github:angular/bower-angular@1.4.7",
    "angular-animate": "github:angular/bower-angular-animate@1.4.7",
    "angular-messages": "github:angular/bower-angular-messages@1.4.7",
    "angular-mocks": "github:angular/bower-angular-mocks@1.4.7",
    "babel": "npm:babel-core@5.8.29",
    "babel-runtime": "npm:babel-runtime@5.8.29",
    "clean-css": "npm:clean-css@3.4.6",
    "core-js": "npm:core-js@1.2.3",
    "enquire": "github:WickyNilliams/enquire.js@2.1.2",
    "jquery": "github:components/jquery@2.1.4",
    "moment": "github:moment/moment@2.10.6",
    "ng-file-upload": "github:danialfarid/ng-file-upload-bower@6.2.1",
    "systemjs/plugin-css": "github:systemjs/plugin-css@0.1.19",
    "systemjs/plugin-text": "github:systemjs/plugin-text@0.0.2",
    "text": "github:systemjs/plugin-text@0.0.2",
    "textAngular": "github:fraywing/textAngular@1.4.6",
    "textAngular-sanitize": "github:fraywing/textAngular@1.4.6/dist/textAngular-sanitize",
    "github:angular/bower-angular-animate@1.4.7": {
      "angular": "github:angular/bower-angular@1.4.7"
    },
    "github:angular/bower-angular-mocks@1.4.7": {
      "angular": "github:angular/bower-angular@1.4.7"
    },
    "github:fraywing/textAngular@1.4.6": {
      "angular": "github:angular/bower-angular@1.4.7",
      "css": "github:systemjs/plugin-css@0.1.19",
      "font-awesome": "npm:font-awesome@4.4.0",
      "rangy": "github:timdown/rangy-release@1.3.0"
    },
    "github:jspm/nodelibs-assert@0.1.0": {
      "assert": "npm:assert@1.3.0"
    },
    "github:jspm/nodelibs-buffer@0.1.0": {
      "buffer": "npm:buffer@3.5.1"
    },
    "github:jspm/nodelibs-events@0.1.1": {
      "events": "npm:events@1.0.2"
    },
    "github:jspm/nodelibs-http@1.7.1": {
      "Base64": "npm:Base64@0.2.1",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "url": "github:jspm/nodelibs-url@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "github:jspm/nodelibs-https@0.1.0": {
      "https-browserify": "npm:https-browserify@0.0.0"
    },
    "github:jspm/nodelibs-os@0.1.0": {
      "os-browserify": "npm:os-browserify@0.1.2"
    },
    "github:jspm/nodelibs-path@0.1.0": {
      "path-browserify": "npm:path-browserify@0.0.0"
    },
    "github:jspm/nodelibs-process@0.1.2": {
      "process": "npm:process@0.11.2"
    },
    "github:jspm/nodelibs-stream@0.1.0": {
      "stream-browserify": "npm:stream-browserify@1.0.0"
    },
    "github:jspm/nodelibs-url@0.1.0": {
      "url": "npm:url@0.10.3"
    },
    "github:jspm/nodelibs-util@0.1.0": {
      "util": "npm:util@0.10.3"
    },
    "npm:amdefine@1.0.0": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "module": "github:jspm/nodelibs-module@0.1.0",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:assert@1.3.0": {
      "util": "npm:util@0.10.3"
    },
    "npm:babel-runtime@5.8.29": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:buffer@3.5.1": {
      "base64-js": "npm:base64-js@0.0.8",
      "ieee754": "npm:ieee754@1.1.6",
      "is-array": "npm:is-array@1.0.1"
    },
    "npm:clean-css@3.4.6": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "commander": "npm:commander@2.8.1",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "http": "github:jspm/nodelibs-http@1.7.1",
      "https": "github:jspm/nodelibs-https@0.1.0",
      "os": "github:jspm/nodelibs-os@0.1.0",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "source-map": "npm:source-map@0.4.4",
      "url": "github:jspm/nodelibs-url@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:commander@2.8.1": {
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "graceful-readlink": "npm:graceful-readlink@1.0.1",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:core-js@1.2.3": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:core-util-is@1.0.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:font-awesome@4.4.0": {
      "css": "github:systemjs/plugin-css@0.1.19"
    },
    "npm:graceful-readlink@1.0.1": {
      "fs": "github:jspm/nodelibs-fs@0.1.2"
    },
    "npm:https-browserify@0.0.0": {
      "http": "github:jspm/nodelibs-http@1.7.1"
    },
    "npm:inherits@2.0.1": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:os-browserify@0.1.2": {
      "os": "github:jspm/nodelibs-os@0.1.0"
    },
    "npm:path-browserify@0.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:process@0.11.2": {
      "assert": "github:jspm/nodelibs-assert@0.1.0"
    },
    "npm:punycode@1.3.2": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:readable-stream@1.1.13": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "core-util-is": "npm:core-util-is@1.0.1",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "isarray": "npm:isarray@0.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream-browserify": "npm:stream-browserify@1.0.0",
      "string_decoder": "npm:string_decoder@0.10.31"
    },
    "npm:source-map@0.4.4": {
      "amdefine": "npm:amdefine@1.0.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:stream-browserify@1.0.0": {
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "readable-stream": "npm:readable-stream@1.1.13"
    },
    "npm:string_decoder@0.10.31": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:url@0.10.3": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "punycode": "npm:punycode@1.3.2",
      "querystring": "npm:querystring@0.2.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:util@0.10.3": {
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    }
  }
});
`

My package.json

`{
  "name": "Gulp-SASS-JSPM-AngularJS",
  "version": "0.0.1",
  "author": "David Plunkett",
  "description": "Boilerplate using GULP, SASS, JSPM and AngularJS whilst also utilizing best practices.",
  "keywords": [
    "gulp",
    "sass",
    "boilerplate"
  ],
  "private": true,
  "engines": {
    "node": ">=0.12.0"
  },
  "devDependencies": {
    "babel": "^5.8.29",
    "bluebird": "^2.9.27",
    "browser-sync": "^2.7.6",
    "cheerio": "^0.19.0",
    "clean-css": "^3.3.1",
    "del": "^1.2.0",
    "express": "^4.12.4",
    "filesize": "^3.1.2",
    "gulp": "^3.9.0",
    "gulp-autoprefixer": "^2.3.1",
    "gulp-babel": "^5.1.0",
    "gulp-changed": "^1.2.1",
    "gulp-combine-media-queries": "^0.2.0",
    "gulp-concat": "^2.5.2",
    "gulp-css-globbing": "^0.1.8",
    "gulp-filesize": "0.0.6",
    "gulp-foreach": "^0.1.0",
    "gulp-if": "^1.2.5",
    "gulp-imagemin": "^2.2.1",
    "gulp-inject": "^1.2.0",
    "gulp-jshint": "^1.11.0",
    "gulp-minify-css": "^1.1.5",
    "gulp-ng-annotate": "^1.0.0",
    "gulp-notify": "^2.2.0",
    "gulp-rename": "^1.2.2",
    "gulp-sass": "^2.0.1",
    "gulp-sourcemaps": "^1.5.2",
    "gulp-streamify": "0.0.5",
    "gulp-svgmin": "^1.1.2",
    "gulp-svgstore": "^5.0.2",
    "gulp-uglify": "^1.2.0",
    "gulp-util": "^3.0.5",
    "imagemin-pngcrush": "^4.1.0",
    "jasmine-core": "^2.3.4",
    "jshint-stylish": "^2.0.0",
    "jspm": "^0.16.13",
    "karma": "^0.12.36",
    "karma-babel-preprocessor": "^5.2.1",
    "karma-chrome-launcher": "^0.1.12",
    "karma-coverage": "^0.3.1",
    "karma-firefox-launcher": "^0.1.6",
    "karma-jasmine": "^0.3.5",
    "karma-jspm": "^1.1.5",
    "karma-phantomjs-launcher": "^0.2.0",
    "lodash": "^3.9.3",
    "morgan": "^1.5.3",
    "penthouse": "^0.3.2",
    "phantomjs": "^1.9.17",
    "pretty-hrtime": "^1.0.0",
    "run-sequence": "^1.1.0",
    "spawn-sync": "^1.0.11",
    "systemjs": "^0.19.5",
    "systemjs-builder": "^0.10.6",
    "tiny-lr": "0.1.5",
    "try-thread-sleep": "^1.0.0",
    "uglifyify": "^3.0.1",
    "vinyl-buffer": "^1.0.0",
    "vinyl-source-stream": "^1.1.0"
  },
  "jspm": {
    "directories": {
      "lib": "."
    },
    "dependencies": {
      "Magnific-Popup": "github:dimsemenov/Magnific-Popup@^1.0.0",
      "angular": "github:angular/bower-angular@^1.4.3",
      "angular-animate": "github:angular/bower-angular-animate@^1.4.3",
      "angular-messages": "github:angular/bower-angular-messages@^1.4.3",
      "angular-mocks": "github:angular/bower-angular-mocks@^1.4.3",
      "clean-css": "npm:clean-css@^3.3.7",
      "enquire": "github:WickyNilliams/enquire.js@^2.1.2",
      "jquery": "github:components/jquery@^2.1.4",
      "moment": "github:moment/moment@^2.10.6",
      "ng-file-upload": "github:danialfarid/ng-file-upload-bower@^6.0.3",
      "systemjs/plugin-css": "github:systemjs/plugin-css@^0.1.19",
      "systemjs/plugin-text": "github:systemjs/plugin-text@^0.0.2",
      "text": "github:systemjs/plugin-text@^0.0.2",
      "textAngular": "github:fraywing/textAngular@^1.4.6"
    },
    "devDependencies": {
      "babel": "npm:babel-core@^5.8.24",
      "babel-runtime": "npm:babel-runtime@^5.8.24",
      "core-js": "npm:core-js@^1.1.4"
    }
  },
  "scripts": {
    "jspm": "./node_modules/.bin/jspm",
    "gulp": "./node_modules/.bin/gulp",
    "build:dev": "./node_modules/.bin/gulp",
    "build:production": "./node_modules/.bin/gulp production",
    "ci:all": "./node_modules/.bin/gulp ci-all",
    "ci:lint": "./node_modules/.bin/gulp ci-lint",
    "ci:test": "./node_modules/.bin/gulp ci-test"
  }
}
`

**Comment by guybedford** [comment]
It would be more useful to know what error you are getting here?

There is no way you could be getting exactly this same previous error with `defaultJSExtensions: true` -  `{ [Error: Error loading "app/src/modules/bootstrap" at file:/Users/quirksmode/_Files/Work-BYND/www/project/frontend/app/src/modules/bootstrap.js
Error loading "npm:babel-core@5.8.29" at file:/Users/quirksmode/_Files/Work-BYND/www/project/frontend/jspm_packages/npm/babel-core@5.8.29
EISDIR, read] errno: -21, code: 'EISDIR' }`

**Comment by Quirksmode** [comment]
The error is this: (if I add the .js extensions it fixes it)

[10:18:38] Starting 'systemjs-builder'...
{ [Error: Error loading "app/src/modules/bootstrap" at file:/Users/quirksmode/_Files/Work-BYND/www/project/frontend/app/src/modules/bootstrap.js
Error loading "npm:babel-core@5.8.29" at file:/Users/quirksmode/_Files/Work-BYND/www/project/frontend/jspm_packages/npm/babel-core@5.8.29
EISDIR, read] errno: -21, code: 'EISDIR' }

**Comment by Quirksmode** [comment]
This is my package.json, not sure if that could be an issue, the babel numbers do seem different:

`{
  "name": "Gulp-SASS-JSPM-AngularJS",
  "version": "0.0.1",
  "author": "David Plunkett",
  "description": "Boilerplate using GULP, SASS, JSPM and AngularJS whilst also utilizing best practices.",
  "keywords": [
    "gulp",
    "sass",
    "boilerplate"
  ],
  "private": true,
  "engines": {
    "node": ">=0.12.0"
  },
  "devDependencies": {
    "babel": "^5.8.29",
    "bluebird": "^2.9.27",
    "browser-sync": "^2.7.6",
    "cheerio": "^0.19.0",
    "clean-css": "^3.3.1",
    "del": "^1.2.0",
    "express": "^4.12.4",
    "filesize": "^3.1.2",
    "gulp": "^3.9.0",
    "gulp-autoprefixer": "^2.3.1",
    "gulp-babel": "^5.1.0",
    "gulp-changed": "^1.2.1",
    "gulp-combine-media-queries": "^0.2.0",
    "gulp-concat": "^2.5.2",
    "gulp-css-globbing": "^0.1.8",
    "gulp-filesize": "0.0.6",
    "gulp-foreach": "^0.1.0",
    "gulp-if": "^1.2.5",
    "gulp-imagemin": "^2.2.1",
    "gulp-inject": "^1.2.0",
    "gulp-jshint": "^1.11.0",
    "gulp-minify-css": "^1.1.5",
    "gulp-ng-annotate": "^1.0.0",
    "gulp-notify": "^2.2.0",
    "gulp-rename": "^1.2.2",
    "gulp-sass": "^2.0.1",
    "gulp-sourcemaps": "^1.5.2",
    "gulp-streamify": "0.0.5",
    "gulp-svgmin": "^1.1.2",
    "gulp-svgstore": "^5.0.2",
    "gulp-uglify": "^1.2.0",
    "gulp-util": "^3.0.5",
    "imagemin-pngcrush": "^4.1.0",
    "jasmine-core": "^2.3.4",
    "jshint-stylish": "^2.0.0",
    "jspm": "^0.16.13",
    "karma": "^0.12.36",
    "karma-babel-preprocessor": "^5.2.1",
    "karma-chrome-launcher": "^0.1.12",
    "karma-coverage": "^0.3.1",
    "karma-firefox-launcher": "^0.1.6",
    "karma-jasmine": "^0.3.5",
    "karma-jspm": "^1.1.5",
    "karma-phantomjs-launcher": "^0.2.0",
    "lodash": "^3.9.3",
    "morgan": "^1.5.3",
    "penthouse": "^0.3.2",
    "phantomjs": "^1.9.17",
    "pretty-hrtime": "^1.0.0",
    "run-sequence": "^1.1.0",
    "spawn-sync": "^1.0.11",
    "systemjs": "^0.19.5",
    "systemjs-builder": "^0.10.6",
    "tiny-lr": "0.1.5",
    "try-thread-sleep": "^1.0.0",
    "uglifyify": "^3.0.1",
    "vinyl-buffer": "^1.0.0",
    "vinyl-source-stream": "^1.1.0"
  },
  "jspm": {
    "directories": {
      "lib": "."
    },
    "dependencies": {
      "Magnific-Popup": "github:dimsemenov/Magnific-Popup@^1.0.0",
      "angular": "github:angular/bower-angular@^1.4.3",
      "angular-animate": "github:angular/bower-angular-animate@^1.4.3",
      "angular-messages": "github:angular/bower-angular-messages@^1.4.3",
      "angular-mocks": "github:angular/bower-angular-mocks@^1.4.3",
      "clean-css": "npm:clean-css@^3.3.7",
      "enquire": "github:WickyNilliams/enquire.js@^2.1.2",
      "jquery": "github:components/jquery@^2.1.4",
      "moment": "github:moment/moment@^2.10.6",
      "ng-file-upload": "github:danialfarid/ng-file-upload-bower@^6.0.3",
      "systemjs/plugin-css": "github:systemjs/plugin-css@^0.1.19",
      "systemjs/plugin-text": "github:systemjs/plugin-text@^0.0.2",
      "text": "github:systemjs/plugin-text@^0.0.2",
      "textAngular": "github:fraywing/textAngular@^1.4.6"
    },
    "devDependencies": {
      "babel": "npm:babel-core@^5.8.24",
      "babel-runtime": "npm:babel-runtime@^5.8.24",
      "core-js": "npm:core-js@^1.1.4"
    }
  },
  "scripts": {
    "jspm": "./node_modules/.bin/jspm",
    "gulp": "./node_modules/.bin/gulp",
    "build:dev": "./node_modules/.bin/gulp",
    "build:production": "./node_modules/.bin/gulp production",
    "ci:all": "./node_modules/.bin/gulp ci-all",
    "ci:lint": "./node_modules/.bin/gulp ci-lint",
    "ci:test": "./node_modules/.bin/gulp ci-test"
  }
}`

**Comment by guybedford** [comment]
@Quirksmode how are you running SystemJS Builder here? I think the issue may be that `defaultJSExtensions: true` is not being set for the build somehow. You can check this by logging `builder.loader.defaultJSExtensions`.

**Comment by Quirksmode** [comment]
I recently switched it to use jspm instead of systemjs-builder as per the 0.16 upgrade instructions, this is my gulp task:

`var gulp   = require('gulp');
//var Builder = require('systemjs-builder');
var jspm = require('jspm');
//jspm.setPackagePath('.'); // optional
var config = require('../config');
var path = require('path');

/**
 * Create JS production bundle.
 */
gulp.task('systemjs-builder', function (cb) {
    // load SystemJS config from file
    var builder = new jspm.Builder();
    builder.loadConfig('./config.js')
    .then(function() {
        // Change baseURL to match the file system
        builder.config({ baseURL: path.resolve("./") });

        // Build a self-executing bundle (ie. Has SystemJS built in and auto-imports the 'app' module)
        return builder.buildSFX(
            config.systemjsBuilder.src,
            config.systemjsBuilder.dest,
            {
                minify: true,
                sourceMaps: false
            });
    }).then(function() {
    	cb();
    }).catch(function(err) {
    	console.error(err);
    });
});`

**Comment by Quirksmode** [comment]
apologies for the poor formatting of the code, struggling to get `` to work

**Comment by Quirksmode** [comment]
In fact the previous systemjs-builder setup I just shared was giving me permission errors when running, plus telling me that [TypeError: baseURL should only be configured once and must be configured first.]

The only one that works for me is:

`var gulp   = require('gulp');
var Builder = require('systemjs-builder');
var config = require('../config');
var path = require('path');

/**
 * Create JS production bundle.
 */
gulp.task('systemjs-builder', function (cb) {
    // load SystemJS config from file
    var builder = new Builder();
    builder.loadConfig('./config.js')
    .then(function() {
        // Change baseURL to match the file system
        builder.config({ baseURL: path.resolve("./") });

        // Build a self-executing bundle (ie. Has SystemJS built in and auto-imports the 'app' module)
        return builder.buildSFX(
            config.systemjsBuilder.src,
            config.systemjsBuilder.dest,
            {
                minify: true,
                sourceMaps: false
            });
    }).then(function() {
    	cb();
    }).catch(function(err) {
    	console.error(err);
    });
});`

Thanks again for your time with this, I realise you must be the busiest man on earth!!

**Comment by guybedford** [comment]
@Quirksmode no problem! Yeah I think the issue is getting this build to be configured correctly. It may be easier to use the jspm-configured builder instance as in https://github.com/jspm/jspm-cli/blob/master/docs/api.md#class-builder.

**Comment by Quirksmode** [comment]
I managed to get it to work using the new builder config, though strangely since the upgrade to jspm I keep getting permission errors that seem linked to a hidden jspm folder in my user folder. This is probably unrelated, but any idea why this occurs now? I have to now run sudo to get it working

`/Users/quirksmode/_Files/Work-BYND/www/project/frontend/node_modules/jspm/lib/global-config.js:58
    throw 'Unable to write global configuration file\n' + e.stack;
                                                        ^
Unable to write global configuration file
Error: EACCES, permission denied '/Users/quirksmode/.jspm/config'
    at Error (native)
    at Object.fs.openSync (evalmachine.<anonymous>:502:18)
    at Object.fs.writeFileSync (evalmachine.<anonymous>:1103:15)
    at save (/Users/quirksmode/_Files/Work-BYND/www/project/frontend/node_modules/jspm/lib/global-config.js:55:8)
    at Object.<anonymous> (/Users/quirksmode/_Files/Work-BYND/www/project/frontend/node_modules/jspm/lib/global-config.js:118:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)`

**Comment by guybedford** [comment]
@Quirksmode it sounds like permissions on your jspm files due to running under sudo at one point. I'd suggest running chown against the `~/.jspm/config` file.

**Comment by Quirksmode** [comment]
Massive thanks, this solved the issue. Only thing remaining is I still get the depreciation warnings in the browser, though from reading a few other articles it seems these will disappear in version 0.17 so nothing to worry about?

'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.
system.js:1232 'webkitIndexedDB' is deprecated. Please use 'indexedDB' instead.

**Comment by guybedford** [comment]
Glad to hear that helped. Setting the `esmExports` meta as in the issues about this is the fix, which yes will come by default in 0.17.
