### ISSUE TITLE
Initialize jspm.Builder with a config-path 

### ISSUE THREAD

**Issue by klausbayrhammer** [jspm/jspm-cli#1232]
We have split our system-js config into two different config files (one managing the dependency-map and another one containing the baseUrl, buildCSS attributes etc). The `config-dependency-map.js` is registered as the configFile in the package.json so you can use the jspm cli to install/update dependencies. 

```javascript
//package.json
"jspm": {
    "configFile": "config-dependency-map.js"
}
```
```javascript
//config-dependency-map.js
System.config({
    map: {...}
});
```
```javascript
//config-baseURL.js
System.config({
    baseURL: "/myBaseURL"
});
```

Unfortunately this doesn't work well when it comes to bundling, because the config file defined in the `package.json` (`config-dependency-map.js`) is loaded before all other configs are loaded and the baseURL (defined in `config-baseURL.js`) should be configured first. If we could pass an initial config location to the `jspm.Builder` we could do something like this:

```javascript
const builder = new jspm.Builder('./config-baseURL.js');
builder.loadConfig('./config-dependency-map.js');
```

PS: We were able to work around this issue by splitting the systemjs-configs into three config files (`config-dependency-map.js`, `config-without-baseURL.js`, `config-baseURL.js`) and just loading `config-dependency-map.js` and `config-without-baseURL.js` and 'manually' specifying the baseURL but I think it would be much easier by passing a config-file location to the `jspm.Builder` 
```javascript
const builder = new jspm.Builder({
  baseURL: "/myBaseURL/"
});
//config-dependency-map.js is loaded by the builder because it is specified in package.json
builder.loadConfig('./config-without-baseURL.js');
```

**Comment by guybedford** [comment]
Can you not use the package.json baseURL configuration here at all? Is this because you have custom compilation steps?

**Comment by klausbayrhammer** [comment]
Ultimately we split the config-files because we want to use the same dependency-configs with different baseURLs (depending on the clients context - browser, server side rendering,  ...). It would be great to reuse the config-file which contains the dependency-map and extend them with a config file which configures the baseURL etc. Would the package.json baseURL help us here?

**Comment by guybedford** [comment]
Yes exactly, the package.json baseURL is just the build / Node baseURL.

**Comment by klausbayrhammer** [comment]
Ah that's nice, works out pretty well! Thanks a lot! Is this feature documented somewhere?

**Comment by guybedford** [comment]
Great, glad to hear that works. It's the server baseURL option in `jspm init` and https://github.com/jspm/jspm-cli/blob/master/docs/getting-started.md#2-create-a-project.
