### ISSUE TITLE
jspm bundle with typescript

### ISSUE THREAD

**Issue by vadimpopa** [jspm/jspm-cli#1233]
I'm trying to bundle with typescript but no success so far. 
```javascript
 jspm bundle-sfx js/app dist/app.min.js
```
is not working, keeps saying: Error: ENOENT: no such file or directory, open  ......../client/src/js/app.js'. You can see my configs in the attached file. I've been searching for a working solution, but haven't found anything working. In Dev, the app is loading fine in browser.

<img width="685" alt="screen shot 2015-10-28 at 10 29 17 am" src="https://cloud.githubusercontent.com/assets/3592131/10783302/84e08c0e-7d5f-11e5-8104-dc72a7b9e72a.png">

Btw same error message here: https://github.com/frankwallis/plugin-typescript/issues/51

**Comment by vadimpopa** [comment]
Also I've been looking on https://github.com/frankwallis/plugin-typescript , but wondering if should work by default, without using that plugin.

**Comment by robertbaker** [comment]
@vadimpopa You should use that plugin, it's newer and preferred.

**Comment by vadimpopa** [comment]
ok @robertbaker thanks for your answer, just tried that plugin, and it works.

**Comment by DavidGangel** [comment]
Hi guys,

I'm facing into this issue.
I don't want to use the typescript plugin as it compiles the ts files directly in the browser AFAIK.
How can it be solved?

Thank you.

**Comment by robertbaker** [comment]
You can use a gulp task to precompile the Typescript into a output folder,
that you then would have jspm bundle
