### ISSUE TITLE
clueless typeError: jspm + typescript + angular, using module system

### ISSUE THREAD

**Issue by dizzyone** [jspm/jspm-cli#1234]
I have the weirdest error that for the life of me I can't seem to figure out. 

Whenever I bundle-sfx my app, it seems angular is loaded, but any and all directives that require other controllers will result in a typeError (this also happens to angular own directives like ngForm and ngModel etc.):

```
cannot read property '0' of null
```

This typeError is caused because in Angular's own directives, they define required controllers as ctrls[0], but the ctrls injection seems to return *null*. The odd thing about it is that Angular seems to bootstrap fine without any directives that require controllers, things like angular expressions will work just fine.

My folder structure looks something like the following:

* src
    * app
        * main app
            * main-app.ts (angular is bootstrapped here)
        * util app
            * util-app.ts (separate angular module that has utility services and decorators etc.)

All of this is bundle-sfx'd into /dist/scripts, for instance using: 
```
jspm bundle src/app/mainapp/main-app dist/scripts/main.js
```

Main app currently looks like this: (this is an example, names have been changed for clarity)

```javascript
/// <reference path="../../../typings/tsd.d.ts" />
/// <reference path="../utilapp/util-app.ts" />

import * as angular from "angular";
import {UtilApp} from "../utilapp/util-app";

export const MainApp:ng.IModule = angular.module('MainApp', [
	UtilApp.name
]).controller('demoController',function(){
	var context = this;
	
	context.model = {
		demoField: {
			demoAmount: 5001,
			demoAverage: 10002
		}
	};
});

angular.element(document).ready(() => {
	angular.bootstrap(document, ['MainApp']);
	
	console.log( 'hi from document.ready', angular );
});
```

With the util app being nothing more than:
```
/// <reference path="../../../typings/tsd.d.ts" />

import * as angular from "angular";

export const UtilApp:ng.IModule = angular.module('utilApp', []);
```

I have uploaded the bundled (bundle-sfx) file of this setup here: 
https://gist.github.com/dizzyone/95d32b4210c772e38441

As of yet I am unable to get Angular to work.

**Comment by dizzyone** [comment]
It seemed that the angular included in the bundle was somehow malformed after bundling, not sure about this, but I removed it from the bundle and added it separately in script tags, which fixed the issue but is far from ideal.

Keeping up with my clueless errors. I get a new error with the following code:

```
import {UtilApp} from "../utilapp/util-app";
console.log(UtilApp)
``` 

```
Uncaught ReferenceError: UtilApp is not defined
```

I'm

**Comment by dizzyone** [comment]
Ok so still a bit lost with why the module loading works the way it does. Can't get commonjs to work either, require is not defined at runtime.


so I noticed that it renames the dependencies in the bundled code, but doesn't rename it in the executed code:
```javascript
"format es6";
$__System.register("1", ["2"], function(exports_1) {
    var core_1;
    return {
        setters:[
            function (core_1_1) {
                core_1 = core_1_1;
            }],
        execute: function() {
            console.log(Core); //this is what it transpiles to but Core is undefined
            console.log(core_1) //manually editing it to this works.
```

**Comment by jwcarroll** [comment]
I have literally just run into the **exact same issue**, and have spent the past few hours creating a project that repros the issue.

You can find it here: https://github.com/jwcarroll/jspm-bundling-with-angular-error

**Comment by dizzyone** [comment]
I forgot to mention that I noticed a "invalid left-hand assignment in expression" error somewhere in the bundled angular, but couldn't figure out what was causing it.

**Comment by jwcarroll** [comment]
@dizzyone - Which version of Angular are you using?

**Comment by dizzyone** [comment]
1.4.7

**Comment by dfbaskin** [comment]
This code (from the `angular.js` source file) is not being bundled correctly:

```
          function getControllers(directiveName, require, $element, elementControllers) {
            var value,
                retrievalMethod = 'data',
                optional = false;
            if (isString(require)) {
              while ((value = require.charAt(0)) == '^' || value == '?') {
                require = require.substr(1);
                if (value == '^') {
                  retrievalMethod = 'inheritedData';
                }
                optional = optional || value == '?';
              }
              value = null;
              if (elementControllers && retrievalMethod === 'data') {
                value = elementControllers[require];
              }
              value = value || $element[retrievalMethod]('$' + require + 'Controller');
              if (!value && !optional) {
                throw $compileMinErr('ctreq', "Controller '{0}', required by directive '{1}', can't be found!", require, directiveName);
              }
              return value;
            } else if (isArray(require)) {
              value = [];
              forEach(require, function(require) {
                value.push(getControllers(directiveName, require, $element, elementControllers));
              });
            }
            return value;
          }
```

The bundled version modifies the code to this:

```
            function getControllers(directiveName, require, $element, elementControllers) {
              var value,
                  retrievalMethod = 'data',
                  optional = false;
              if (isString(req)) {
                while ((value = req.charAt(0)) == '^' || value == '?') {
                  req = req.substr(1);
                  if (value == '^') {
                    retrievalMethod = 'inheritedData';
                  }
                  optional = optional || value == '?';
                }
                value = null;
                if (elementControllers && retrievalMethod === 'data') {
                  value = elementControllers[req];
                }
                value = value || $element[retrievalMethod]('$' + req + 'Controller');
                if (!value && !optional) {
                  throw $compileMinErr('ctreq', "Controller '{0}', required by directive '{1}', can't be found!", req, directiveName);
                }
                return value;
              } else if (isArray(req)) {
                value = [];
                forEach(req, function(require) {
                  value.push(getControllers(directiveName, req, $element, elementControllers));
                });
              }
              return value;
            }
```

The `require` variable is being changed to `req`.

**Comment by dfbaskin** [comment]
Related to #1221

**Comment by jwcarroll** [comment]
It looks as though the new code added causing the bug only executes for **commonjs** style modules. And since the version of Angular I needed was being pulled from the **npm** registry, it was being treated as commonjs by default.

The fix for me was to simply add an override in my `package.json` to tell **jspm** that I wanted angular to be treated as a global instead.

```json
    "overrides": {
      "npm:angular@1.2.28": {
        "format": "global",
        "shim": {
          "angular": {
            "exports": "angular"
          }
        }
      }
    }
```

**Comment by dizzyone** [comment]
Thanks, I had to do the overrides in systemJS config, but it seems to have made a difference. (not sure why it doesn't work in package.json).

However I still have the problem with 'require' not being defined in my bundle. 

I'll try using SystemJS builder and downgrading it.

**Comment by dizzyone** [comment]
Alright, ignore my last reply, the require came from jspm_packages using require to get angular. I downgraded to JSPM 0.16.12 which seems to fix the bundling of angular. 

Still having issues with importing with system module though.

**Comment by dfbaskin** [comment]
Looks like the issue has been addressed, just waiting for a release.
[https://github.com/systemjs/builder/issues/367](https://github.com/systemjs/builder/issues/367)

**Comment by dizzyone** [comment]
Thanks, does this also address my problems with es6 module imports?
