### ISSUE TITLE
Problem with resolving and loading external libs that installed by jspm in "chrome-extensions"

### ISSUE THREAD

**Issue by SerkanSipahi** [jspm/jspm-cli#1235]
There is a problem with resolving and loading external libs (npm, github) that installed by jspm in "chrome-extensions". All modules (see below) except Draggabilly and jquery are loaded correctly.

```js
import Googletranslate from './libs/googletranslate';
import Locateword from './libs/locateword';
import Waitfor from './libs/waitfor';
import CssSource from './styles/style.css!';
import htmlSource from './templates/container.html!text';
import Draggabilly from 'draggabilly'; // <- cant load
import $ from 'jquery'; // <- cant load
```

This map setting is loaded correctly. 
```json
map: {
   "draggabilly": "npm:draggabilly@1.2.4",
   "jquery": "npm:jquery@2.1.4"
}
```

The problem occurs after loading `npm:draggabilly@1.2.4`:
```js
module.exports = require("npm:draggabilly@1.2.4/draggabilly/dist/draggabilly.pkgd");
```
Chrome (Network) try to load (see below) but this paths is not reachable:
```js
chrome-extension://acoadokefanhjnnmgcmnoeaakpdckkpa/jspm_packages/npm/draggabilly@1.2.4/draggabilly/dist/draggabilly.pkgd.js
``` 
The right path would be:
```js
chrome-extension://acoadokefanhjnnmgcmnoeaakpdckkpa/jspm_packages/npm/draggabilly@1.2.4/dist/draggabilly.pkgd.js
```

##### Is this a bug (jspm + chrome extension) or am I doing something wrong?

My workaround for this problem is to install external libs by 'npm install' and setting up the paths manually. What i want is that jspm should work "out of the box" :)

Note: the problem only occurs in Chrome-Extensions

**Comment by guybedford** [comment]
Are you saying here that the file reading:

```javascript
module.exports = require("npm:draggabilly@1.2.4/draggabilly/dist/draggabilly.pkgd");
```

is incorrect and should actually be:

```javascript
module.exports = require("npm:draggabilly@1.2.4/dist/draggabilly.pkgd");
```

?

Because that's what it sounds like the issue is from the information given?

**Comment by SerkanSipahi** [comment]
> Because that's what it sounds like the issue is from the information given?

@guybedford Yes exactly (only for Chrome-Extensions) !

**Comment by guybedford** [comment]
This file is generated on install though, and not related to the execution environment at all?

**Comment by SerkanSipahi** [comment]
> This file is generated on install though, and not related to the execution environment at all?

@guybedford : sorry for the late reply. I had no time. Please do not close the Ticket. I will give you later more Information.

**Comment by guybedford** [comment]
If you have any further info here, please feel free to post and I'll reopen.
