### ISSUE TITLE
Export config.newLine and config.tab to the global .jspm/config file

### ISSUE THREAD

**Issue by gig177** [jspm/jspm-cli#1236]
This issue related to [these](/jspm/jspm-cli/blob/0.16.13/lib/config.js#L19,L20) strings. It would be nice if these strings will be looking something like this:
```javascript
exports.newLine = globalConfig.newLine || require('os').EOL;
exports.tab = globalConfig.tab || '  ';
```
The reason is to provide the uniform style indent and EOL coding per project. At Windows OS `$ jspm install` rewrite unix `\n` to  `\r\n`. The WebStorm IDE marks config.js as changed. It's annoying.

**Comment by guybedford** [comment]
jspm 0.17 is coming with auto-detection of these for each config file allowing full flexibility.
