### ISSUE TITLE
Overrides need better documentation

### ISSUE THREAD

**Issue by robertbaker** [jspm/jspm-cli#1237]
I spent a good part of the day trying to override `angular-ui-router` angular dependency to use the npm  source and had no luck.

It was annoying that every time I went to test the override, jspm would remove it.

```
    "overrides": {
      "angular-ui-router": {
        "dependencies": {
          "angular": "npm:angular@^1.4.7"
        }
      }
    }
```

I need to override this because of the angular fork issue. How can I accomplish this?

angular-material is now using npm's angular when it used to use the github angular. ui-router is the only package pulling it from github, causing the 'attempting loading angular more than once` warning.

I find that the documentation for JSPM and SystemJS lacking, and I believe that's a primary reason why more people are choosing webpack. Lack of good documentation hurts.

**Comment by OrKoN** [comment]
Your override is not completely correct. Please see this example for the correct usage: https://github.com/OrKoN/jspm-ember-playground/blob/master/package.json#L49

Overrides are simple `"overrides": { "<fullModuleName>": { whatever is allowed in a package.json } }`. Please not that JSPM removes only unused overrides.

The documentation should be improved, you are right :-)

**Comment by guybedford** [comment]
Thanks @OrKoN for responding here! 

@robertbaker documentation will be prioritised once jspm 0.17 has been released. For now getting that release out is the major priority.
