### ISSUE TITLE
prevent jspm from adding "format cjs"

### ISSUE THREAD

**Issue by ozsay** [jspm/jspm-cli#1240]
Is it possible that upon install I can prevent jspm from adding "format cjs" to the installed package?

This is the repository https://github.com/ozsay/angular-electron of my package and when I install this package `jspm install npm:angular-electron`, "format cjs" is added to angular-electron.js.

The problem with this is that [electron](http://electron.atom.io/) has its own module system which is cjs style. When systemjs tries to load the module, it detects the require statements and adds the dependencies accordingly. Since systemjs doesn't manage the electron modules, it fails to load them.

When I manually remove the line, It's working.

This happens when i wrap the module in [define](https://github.com/ozsay/angular-electron/blob/ecfd20b1f420389d9cebe9b795c07ae3b87a8547/angular-electron.js).

When I [don't](https://github.com/ozsay/angular-electron/blob/master/angular-electron.js), the line isn't added but still systemjs add the electron dependencies.

Any suggestions ? 

Thanks

**Comment by guybedford** [comment]
You can alter the module format by adding shim config or changing the format via `jspm install npm:angular-electron -o "{shim: {...}}"`. See https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm.

**Comment by ozsay** [comment]
I've managed to solve it in a different way.

Thanks anyways

**Comment by linnett** [comment]
@ozsay how did you manage to solve this?

**Comment by ozsay** [comment]
It was a long time ago, but if I remember correctly, I wrapped the module in a function like this:

```js
(function(electronRequire) {'use strict';
// now you can call electronRequire and the loader won't detect it
var electron = electronRequire('electron');
})(window.require);
```

`window.require` is the method that electron provides.

**Comment by linnett** [comment]
@ozsay thanks for that pal.
