### ISSUE TITLE
jspm freeze if cacheDir path contains colon on windows machine

### ISSUE THREAD

**Issue by tbialecki** [jspm/jspm-cli#1242]
I`m trying to use custom endpoint (https://www.npmjs.com/package/jspm-bower-endpoint) which allows to load install packages from bower.
I have noticed that jspm freezes even before atempting to checkout repository.(only on windows machine) 
I have figured out that promise which should prepare cacheDir is guilty.

var cacheDir = path.resolve(config.HOME, '.jspm', 'packages', pkg.registry, pkg.exactPackage);

exactPackage contains url and path is not being normalized which causes mkdirp to freeze. 

Jspm tries to create the following directory: 

C:\Users\tbialeck\AppData\Local\.jspm\packages\bower\https:\github.com\urish\angular-spinner.git@0.8.0

**Comment by guybedford** [comment]
I wouldn't actually advise using jspm-bower since the github endpoint
provides much the same support.

If you really must use this, then I'd suggest posting an issue to
jspm-bower.

**Comment by tbialecki** [comment]
I have to  use my private git repository and bower-endpoint seem to allow to track depencencies defined in bower,json file.

**Comment by guybedford** [comment]
Yes dependencies aren't assumed when installing from github, because jspm would still need shim config or otherwise to make them work, so the idea is that users need to configure packages to work via overrides.

jspm-bower is a third-party project though - any issues with that are to be reported there.

**Comment by tbialecki** [comment]
Yes but the problem occures before this plugin start to download any
package, because code located in package.js file in jspm cannot create temp
directory.
31 paź 2015 12:20 PM "Guy Bedford" <notifications@github.com> napisał(a):

**Comment by guybedford** [comment]
Yes, this is because providing a URL as a package name is not supported in jspm. The name of the package must be file-system-compatible.

**Comment by tbialecki** [comment]
Isin't it confusing that, url as package name ist acceptable on linux based machines and not acceptable on windows machine ?

**Comment by guybedford** [comment]
Yes it is, I would suggest posting an issue to the jspm-bower-endpoint project which has to consider these decisions!
