### ISSUE TITLE
Expose SystemJS Builder In-Memory Builds to API

### ISSUE THREAD

**Issue by tniswong** [jspm/jspm-cli#1244]
This is useful for build tools like Gulp where all operations are in-memory.

From https://github.com/systemjs/builder#in-memory-builds
>### In-Memory Builds
>
>Leave out the `outFile` option to run an in-memory build:
>
>```javascript
>builder.bundle('myModule.js', { minify: true }).then(function(output) {
>  output.source;    // generated bundle source
>  output.sourceMap; // generated bundle source map
>  output.modules;   // array of module names defined in the bundle
>});
>```
>The output object above is provided for all builds, including when `outFile` is set.
>
>`output.modules` can be used to directly populate SystemJS bundles configuration.

**Comment by guybedford** [comment]
Thanks, this is exposed through https://github.com/jspm/jspm-cli/blob/master/docs/api.md#class-builder.

**Comment by tniswong** [comment]
Oh, don't know how I didn't notice that...
