### ISSUE TITLE
Dynamic baseURL

### ISSUE THREAD

**Issue by WorldMaker** [jspm/jspm-cli#1248]
Attempting Electron and Cordova applications with jspm/SystemJS and find myself having to manually update the config.js baseURL in between JSPM operations to handle the somewhat complicated base paths of these platforms. (Also similarly handling cases where I'm copying things to a server where the path is a few levels deeper than others.)

For instance, in Electron I want the baseURL to stay `'file://' + __dirname`. With this example JSPM essentially runs that and records my development path I ran JSPM inside. I haven't quite figured out what I need in Cordova, but it's likely somewhat similar.

At one point I tried setting baseURL to some variable in the ambient/global context, but the command line errors out without the variable set.

Does anyone have an existing work around to handle dynamic baseURLs rather than hand-editing config.js constantly?

I think it would be nice if JSPM just round-tripped whatever was set in baseURL without executing it.

**Comment by guybedford** [comment]
It's best to set the baseURL through a separate config file for these cases.

Is SystemJS not detecting the correct baseURL automatically then in these environments? The code for this is based on the baseURI detection in https://github.com/ModuleLoader/es6-module-loader/blob/master/src/wrapper-start.js#L66. Any help improving this to handle these environments is welcome!

**Comment by dennschu** [comment]
@guybedford i jumped blindly into the same issue like @WorldMaker during jspm update from 0.15.* to 0.16.14. 

### Solution before jspm 0.16.*

Before version 0.16.* in development environment we set the baseUrl in config.js to '/' and override it in html like so:

	<script src="{{ dynammic_path_that_change_with_environment }}jspm_packages/system.js"></script>
	<script src="{{ dynammic_path_that_change_with_environment }}assets/js/config.js"></script>

	<script>
		System.baseURL: '{{ dynammic_path_that_change_with_environment }}';
		System.import( '_assets/js/main' );
	</script>

And for production we created one sfx bundle. That worked excellently so far.

### jspm 0.16.14 Workaround

After fiddling around with jspm 0.16.14 for a whole day, i found a temporary solution where i declare a property at the window object and use that property in config.js. But this breaks on `jspm install` as mentioned by @WorldMaker because config.js gets blindly overwritten.

**Html part of workaround**
```html
	<script src="{{ dynammic_path_that_change_with_environment }}jspm_packages/system.js"></script>
	<script> window.jspm_client_baseUrl = {{ dynammic_path_that_change_with_environment }}; </script>
	<script src="{{ dynammic_path_that_change_with_environment }}assets/js/config.js"></script>

	<script>
		System.import( '_assets/js/main' );
	</script>
```

**config.js part of workaround**

```javascript
var url = '/'; // default for jspm_cli and the absence of window

if ( typeof window != 'undefined' ) {
	url = window.jspm_client_baseUrl;
}

System.config({
	baseURL: url,
	defaultJSExtensions: true,
	...
})
```

### Suggestions for improvements?

@guybedford you mentioned to use a separate file. How can we get the config object during e.g. `jspm install` || `jspm update` in order to write it also into a custom `config.js` or better why is directly written into `System.config( [object_of_interest] )`?

**Comment by dennschu** [comment]
For anybody who is interested a cleaner hack:

```javascript
var SystemJsModifier = {
  _config: null,
  _baseURL: null,

  /**
   * Fake method for hijacking System.config() and
   * receive system js configuration object
   *
   * @param configuration
   * @return {SystemJsModifier}
   */
  config: function ( configuration ) {
    this._config = configuration;
    return this;
  },

  /**
   * Get System.js configuration with modified baseURL
   * @return {null|{}}
   */
  getConfig: function ( baseURL ) {
    this._config[ 'baseURL' ] = baseURL || '/';
    return this._config; 
  }
};

var System = SystemJsModifier;
```

```html
<script src="{{ dynammic_path_that_change_with_environment }}_assets/js/system-js-modifier.js"></script>
<script src="{{ dynammic_path_that_change_with_environment }}assets/js/config.js"></script>
<script src="{{ dynammic_path_that_change_with_environment }}jspm_packages/system.js"></script>

<script>
  System.config( SystemJsModifier.getConfig( '{{ dynammic_path_that_change_with_environment }}' ) );
  System.import( '_assets/js/main' );
</script>

```

**Comment by WorldMaker** [comment]
I guess I had assumed that baseURL was required in config.js. I think this was because of the way jspm asks for a baseURL, but that baseURL is a different colored elephant.

Removing baseURL entirely from the config "just works" on Electron, at least.

**Comment by guybedford** [comment]
I'd suggest just using:

```html
<script>System.config({ baseURL: {{ custom_base_url }} })</script>
<script src="{{ dynammic_path_that_change_with_environment }}assets/js/config.js"></script>
<script src="{{ dynammic_path_that_change_with_environment }}jspm_packages/system.js"></script>
<script>
  System.import( '_assets/js/main' );
</script>
```

As the pattern here.

It's advised to set the baseURL from the default because otherwise subpages will break (eg `sub/page.html` will have baseURL `sub`).
