### ISSUE TITLE
config paths overwritten after install

### ISSUE THREAD

**Issue by brewster1134** [jspm/jspm-cli#1250]
i need to customize the values for endpoint paths in my config, which works fine...

```json
  paths: {
    "*.js": "*.js",
    "github:*": "vendored/github/*",
    "npm:*": "vendored/npm/*"
  },
```

But when I install another jspm package, it rewrite the values back to the defaults...

```json
  paths: {
    "*.js": "*.js",
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },
```

is that expected behavior?  and if so, is there a way to retain custom paths?

**Comment by Mosho1** [comment]
Try putting this: 

    "directories": {
        "packages": "vendored"
    },

Under `jspm` in your `package.json`.

**Comment by brewster1134** [comment]
cool! so that works, but i did find a caveat. when i used the same name `jspm_packages` just with a different path, both `package.json`, and my `config.js` were reverted.

this did NOT work...

```json
    "directories": {
      "packages": "vendored/jspm_components"
    },
```
this DID work...
```json
    "directories": {
      "packages": "vendored/jspm"
    },
```

potential bug?

**Comment by guybedford** [comment]
Yes jspm currently imposes this restriction. jspm 0.17 will be more lenient here.
