### ISSUE TITLE
For TypeScript, load typescriptOptions from tsconfig.json

### ISSUE THREAD

**Issue by rubyboy** [jspm/jspm-cli#1251]
It would be very useful to reuse the tsconfig.json and load its compilerOptions into the typescriptOptions property of config.js
Currently, the configuration options ("experimentalDecorators", for example) need to be defined twice.

**Comment by bali182** [comment]
:+1: This would be pretty cool! Like
```
System.config({
  typescriptOptions: 'tsconfig.json'
});
```

**Comment by GauSim** [comment]
+1

**Comment by xmlking** [comment]
+1

**Comment by Wema** [comment]
+1

**Comment by rubyboy** [comment]
This has been implemented in the typescript plugin: https://github.com/frankwallis/plugin-typescript#tsconfig
Thanks!

**Comment by rubyboy** [comment]
```JavaScript
typescriptOptions: {
    "module": "system",
    "noImplicitAny": true,
    "typeCheck": true,              // also accepts "strict"
    "tsconfig": true                // also accepts a path
  }
```
