### ISSUE TITLE
jspm link workflow issues

### ISSUE THREAD

**Issue by devmondo** [jspm/jspm-cli#1252]
we are developing lots of in house jspm packages, but we are facing issues that are show blockers for us.

- first the link workflow is not automatic, what i mean is that each time we modify the package we have to run `jspm link` this can be solved with a gulp task, we wish it would be like `npm link`

- when we install a linked package it is only added to `config.js` and not `package.json`, i know that we need `jspm install --unlink` but this is really problematic for 2 reasons: 
  - first is that when we give the project to another developer and he runs `jspm install` jspm wont install the packages because they are not listed in `package.json` and we either have to tell each developer the list of linked packages to install or he has to search manually.
 - second is that if you have a linked package that itself references another linked package, the referenced package also wont install because of same reason above. 
 - when you uninstall linked package it only removes it from `config.js` but not from `jspm_packages` folder.

all of above dont happen with `npm` i really wish for this to be addressed, because when you work with huge team and have lots of in house packages, developing and testing them is really pain, not to mention that we have hundreds of sites that we need to automatically upgrade and not follow a manual approach.

thx in advanced.

**Comment by OrKoN** [comment]
> second is that if you have a linked package that itself references another linked package, the referenced package also wont install because of same reason above.

How do you solve this with npm?

**Comment by devmondo** [comment]
@OrKoN 
https://github.com/OrKoN/npm-link-shared
https://github.com/timoxley/linklocal

**Comment by OrKoN** [comment]
@devmondo so not using npm itself. I think `npm-link-shared` can easily adopted for jspm too. The only problem is that linked packages cannot defined in the package.json, can they?

**Comment by devmondo** [comment]
@OrKoN , yeah this is the biggest problem, i expect developer to just run jspm install and it would install all linked packages i did install except for him jspm fetches it from online, of course for this to be fully effective, we need something like `npm-link-shared` as you mentioned so we can get full hierarchy .

thanks for support

**Comment by guybedford** [comment]
Both of the above issues are resolved in jspm 0.17, and currently working on the development branch. The alpha release is set for mid December.

**Comment by devmondo** [comment]
@guybedford 
thanks a lot this is really great, it will solve loads of issues for us as we develop lots of in house packages. 

you said it is working on development branch, maybe i missed something but i dont see development branch here in github?

**Comment by guybedford** [comment]
See https://github.com/jspm/jspm-cli/pull/1099.

**Comment by devmondo** [comment]
thx
