### ISSUE TITLE
Implement max / min ranges, range intersections and range unions

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#1253]
Initially, there was a version resolution extension to SystemJS allowing version resolutions in the browser. To make this code manageable, it only implemented a subset of version range support.

Now that version resolution is not part of SystemJS at all, we need to support all these range options for full npm compatibility.

**Comment by tyrsius** [comment]
As more packages add version range support for React 15, this problem gets worse. Until either every depdendency I have adds support for React 15 or jspm adds this support, I am locked into React 0.14.x and the last version of every package that *hasn't* added a range for React 15.

This is starting to be a real headache.

**Comment by amenadiel** [comment]
Isn't this already managed by semver, by using the `~` prefix? If it doesn't, then using overrides in your `package.json` might help. Do you have an example of a particular module that breaks bc it requires an unsupported React version?
