### ISSUE TITLE
Cannot install webpack 1.12.2: tries to install non-existent version of node-libs-browser

### ISSUE THREAD

**Issue by myitcv** [jspm/jspm-cli#1254]
To reproduce:

```
cd `mktemp -d`
npm init -f
npm install --save-dev jspm@0.16.14
export PATH=$PWD/node_modules/.bin:$PATH
jspm init
```

with options:

```
Would you like jspm to prefix the jspm package.json properties under jspm? [yes]:
Enter server baseURL (public folder path) [./]:
Enter jspm packages folder [./jspm_packages]:
Enter config file path [./config.js]:
Configuration file config.js doesn't exist, create it? [yes]:
Enter client baseURL (public folder URL) [/]:
Do you wish to use a transpiler? [yes]:no
ok   Verified package.json at package.json
     Verified config file at config.js
     Looking up loader files...
       system.js
       system.src.js
       system.js.map
       system-csp-production.js
       system-csp-production.js.map
       system-csp-production.src.js
       system-polyfills.js
       system-polyfills.src.js
       system-polyfills.js.map

     Using loader versions:
       systemjs@0.19.5
ok   Loader files downloaded successfully
```

Then:

```
jspm install npm:webpack@1.12.2
```

Gives:

```
...

err  Installing npm:webpack@1.12.2, no version match for npm:node-libs-browser@0.6.0

warn Installation changes not saved.
```

Here is the relevant line from [`webpack`'s `package.json`](https://github.com/webpack/webpack/blob/v1.12.2/package.json#L14):

```
"node-libs-browser": ">= 0.4.0 <=0.6.0"
```

However you will notice that the latest released version of `node-libs-browser` is `0.5.3`:

https://github.com/webpack/node-libs-browser/releases

Where is the issue here? 

Thanks

**Comment by guybedford** [comment]
This sounds like the same issue as https://github.com/jspm/npm/issues/104.

But you will then hit further issues - installing webpack through jspm is not currently supported. See https://github.com/jspm/jspm-cli/blob/master/docs/nodejs-usage.md for more info.

**Comment by myitcv** [comment]
@guybedford - thanks for the quick response. I'm not actually trying to install it directly, it's a dependency getting picked up somewhere. Thanks for the pointers in any case

**Comment by myitcv** [comment]
This is the package that relies on `webpack`: https://github.com/wangzuo/react-input-color

```
jspm install npm:react-input-color@1.7.0
```

However `webpack` only appears to be a dev dependency (unless I'm missing something)

I have to admit I wouldn't have expected dev dependencies to be installed...?

**Comment by myitcv** [comment]
Just seen https://github.com/jspm/jspm-cli/issues/747 which I guess is related

What's the motivation for installing the devDependencies by default, other than this being the current default for `npm install`? My intuition (so this only loosely reflects reality) would seem to suggest that in most cases people would not need (nor therefore want) devDependencies.

Also I couldn't see an equivalent of the `--production` flag offered by [`npm install`](https://docs.npmjs.com/cli/install)?

So does that mean at the moment there is no way of excluding devDependencies?

**Comment by guybedford** [comment]
jspm doesn't install devDependencies of installed packages, only devDependencies from the package.json of the current project, jspm like npm. There's probably something which has that as a normal dependency somewhere in the tree.

**Comment by myitcv** [comment]
That makes sense. Indeed I've found the dependency.... Confusion here was that `webpack` is a devDependency of the `react-input-color` package.
