### ISSUE TITLE
Prevent installation of global package

### ISSUE THREAD

**Issue by lyptt** [jspm/jspm-cli#1255]
The environment I'm currently loading sfx-bundled scripts into has its own version jQuery it loads before my script runs. I want to be able to use this version of jQuery instead of bundling my own, so I've installed  any packages depending on jQuery with a map to '@empty'. 

This seems to break any CommonJS-enabled jQuery plugins I'm bundling, as now these get an empty object instead of just the global jQuery object.

Is there any way to get jspm installing these packages without installing the jQuery module?

I've found that I can get around the issue by having a basic shim file containing the following:

```javascript
module.exports = window.jQuery;
```

Then set this to be used instead of the actual jQuery script in an override:

```
jspm install angular@1.2 -o "{ 'map': { 'jquery': 'shims/jQuery' } }"
```

This seems to work around the issue for the time being.

**Comment by guybedford** [comment]
Rather than using an empty map, you can build the sfx bundle without jquery, and then tell it to get the jQuery module from the global value via:

```
  jspm bundle-sfx app - jquery --globals "{jquery:'$'}"
```

**Comment by DrDanRyan** [comment]
This should be updated in the documentation section for bundle-sfx. I having been looking for this solution all day; playing with System.config.map and System.config.paths etc

**Comment by DrDanRyan** [comment]
Hi @guybedford, can you tell me what all the command line options are for bundle-sfx, or at least point me to a spot in the code where I could see them? In particular, is there a way to not include the babel runtime in the bundle (the resulting bundle will get processed by Babel later on)?

Also, is there a way to replace the command line options with options in config.js?

**Comment by DrDanRyan** [comment]
Nevermind, found them
```javascript
    case 'bundle':
      options = readOptions(args, ['inject', 'yes', 'skip-source-maps', 'minify',
          'no-mangle', 'hires-source-maps', 'no-runtime', 'inline-source-maps', 'source-map-contents'], ['format', 'global-name', 'globals', 'global-defs']);
```

The first block of options seem self-explanatory, can you shed some light on the difference between global-name, globals, and global-defs?
