### ISSUE TITLE
Publish package as bundle?

### ISSUE THREAD

**Issue by WorldMaker** [jspm/jspm-cli#1258]
I've been working primarily in TypeScript and I prefer not to include the built *.js and *.js.map files in the git repository for aesthetic reasons so I was wondering if maybe it might be a useful feature to support publishing the contents of a repository as a bundle of some sort (say the contents of a library, minus its dependencies) as committing only a single build output *.js file seems a little nicer than all of them.

I'm not sure if this is useful other than for the aesthetic reasons mentioned, so I'm not sure right now if it is worth exploring as a feature, but I thought I might post the idea in case it resonates with anyone else.

**Comment by WorldMaker** [comment]
I did think up more use cases for this. You can do some package-specific configuration using `packageConfigPaths` to load a package-specific config file, but some of what you might need a package-specific file for (complicated `defaultExtension` scenarios within the package, some transpiler needs, et al) might be easier to handle by just normalizing and transpiling into a package bundle ahead of time, instead.

**Comment by guybedford** [comment]
This is definitely on the roadmap to allow publishing workflows that handle pre-optimizations including bundling. The first step would be build workflows via `jspm build` with no arguments that read from config, and output the package ready for publishing.

**Comment by guybedford** [comment]
The main issue with the idea of publishing a bundle is that names are no longer portable. In jspm we provide the ability to do `jspm install x=pkg:y` so that name collissions can always be avoided. This property is lost with bundle publishing.

Better publishing workflows here will definitely be explored though.

**Comment by WorldMaker** [comment]
I'm not sure I understand what you mean here. Supposedly a bundle would just be a variant of a repository, something vaguely like:

`jspm install x=github+bundle:WorldMaker/some-project/bundle.js`

Or perhaps better, in addition to checking for a `main` JS file in `package.json` you might look for a `mainBundle` for a pre-bundled package.

I guess the big issue would be that it would take additional state information in ``System.register`` to deal with the "base path" of a bundle, where `x=` is essentially a "base path". You still have to normalize the names given to `System.register` anyway so it would still presumably be similar to other paths/mapping information... I don't know if that makes it easier or harder, though.

Anyway, this isn't necessarily a critical need right now,
