### ISSUE TITLE
require is not defined

### ISSUE THREAD

**Issue by ggutenberg** [jspm/jspm-cli#1259]
I'm trying to use jspm to build a shared browser/node library, however I'm having some difficulties.  I don't think this is necessarily a problem with jspm, but rather my understanding of how things are supposed to work.

I have 3 files:

* test.js which doesn't do anything right now, but `require`s the native node 'util' lib.  In my actual code, this file is also used in the browser, but with a special `isNode` condition.  There's common code, but then different execution paths based on browser or node.
* importer.js which uses ES6 syntax to import the exported function from test.js.
* node-bootstrap.js which imports importer.js on node only (in the browser this is handled via `System.import( 'importer.js' );`

##### src/test.js
```javascript
export function exportTest() {
    var isNode = ( typeof window == 'undefined' );
    if ( isNode ) {
        var util = require( 'util' );
        // do something
    }
    else {
        // do something else
    }
}
```

##### src/importer.js
```javascript
import {exportTest} from './test.js';
exportTest();
```

##### node-bootstrap.js
```javascript
var jspm = require( 'jspm' );
jspm.setPackagePath( '.' );

jspm.import( './src/importer.js' )
    .then( function( importer ) {
        console.log( importer );
    })
    .catch( function( err ) {
        console.log( err );
    })
;
```

Running `node node-bootstrap.js` outputs:
`[Error: require is not defined]`

I'm pretty sure my issue is the same as https://github.com/jspm/jspm-cli/issues/235, but what I don't know is how to get around it.

Any help would be greatly appreciated.

**Comment by guybedford** [comment]
Mixing CommonJS requires with ES modules is not supported in SystemJS. It's better to do a dynamic `System.import('util')` instead rather as that is the effective equivalent of the dynamic require in this case.
