### ISSUE TITLE
Handling dependencies between registry packages

### ISSUE THREAD

**Issue by Rush** [jspm/jspm-cli#1260]
I'd like for angular from registry to depend on jquery (and load it instead of jqLite), I define in my `config.js` the following:

```js
  meta: {
    "github:angular/bower-angular@1.4.7": {
      "deps": [
        "jquery"
      ]
    }
  },
```

It works ... but the problem is that whenever I am gonna update angular, this entry will not follow with version and my app will be silently broken.

* Is there a way to provide such manual dependencies without canonical paths?
* Why packages such as `angular-messages` don't implement the dependency to angular themselves? I have problem loading them in my application now because `angular-messages.js` is running before `angular.js`. The former one assumes that `window.angular` is set. Before I had manually modified files for AMD.

**Comment by Rush** [comment]
Ok so I fixed my project by providing:

```js
  meta: {
    "github:angular/bower-angular@1.4.7/angular": {
      "deps": [
        "jquery"
      ]
    },
    "github:angular/bower-angular-animate@1.4.7/angular-animate": {
      "deps": [
        "angular"
      ]
    },
    "github:angular/bower-angular-messages@1.4.7/angular-messages": {
      "deps": [
        "angular"
      ]
    },
    "github:angular/bower-angular-sanitize@1.4.7/angular-sanitize": {
      "deps": [
        "angular"
      ]
    },
    "github:angular/bower-angular-cookies@1.4.7/angular-cookies": {
      "deps": [
        "angular"
      ]
    }
  },
```

However I think this is unacceptable to have to provide:
a) manual dependencies
b) provide canonical paths to packages

Can it be fixed somehow?

**Comment by guybedford** [comment]
These can be turned into overrides using:

```
  jspm install github:angular/bower-angular-sanitize@1.4.7 -o "{shim:{ 'angular-sanitize': {deps:['angular']} }}"
```

These overrides can then be added to the jspm registry and shared with others just like https://github.com/jspm/registry/blob/master/package-overrides/github/angular/bower-angular-animate%401.3.0.json.

**Comment by Rush** [comment]
Ok thanks, now my overrides look like this:

```js
    "overrides": {
      "github:angular/bower-angular-sanitize@1.4.7": {
        "shim": {
          "angular-sanitize": {
            "deps": [
              "angular"
            ]
          }
        }
      },
      "github:angular/bower-angular-cookies@1.4.7": {
        "shim": {
          "angular-cookies": {
            "deps": [
              "angular"
            ]
          }
        }
      },
      "github:angular/bower-angular-messages@1.4.7": {
        "shim": {
          "angular-messages": {
            "deps": [
              "angular"
            ]
          }
        }
      },
      "github:angular/bower-angular-animate@1.4.7": {
        "shim": {
          "angular-animate": {
            "deps": [
              "angular"
            ]
          }
        }
      },
      "github:angular/bower-angular@1.4.7": {
        "shim": {
          "angular": {
            "deps": [
              "jquery"
            ]
          }
        }
      }
    }
```

I also had to install both:

* `jspm install angular-sanitize`
* `jspm install github:angular/bower-angular-sanitize@1.4.7 -o "{shim:{ 'angular-sanitize': {deps:['angular']} }}"`

and the same for each dependency.

It still feels kinda cumbersome and I do see some of the overrides in the registry, are they not working then?  I'd like to do a PR to the registry to fix them but I am not sure how.

**Comment by guybedford** [comment]
That is really odd you need the angular-sanitize override as the override is definitely in the registry at https://github.com/jspm/registry/blob/master/package-overrides/github/angular/bower-angular-sanitize%401.3.0.json. Are you really sure you need to manually add this one? And you haven't configured a custom jspm registry at all?

**Comment by Rush** [comment]
@guybedford Hmm, true that I may probably not need it, but having to think and test which one needs it is a pain in the ass so I just added it for everything.

**Comment by guybedford** [comment]
Yeah I know, but unfortunately that is the process here. An automated daemon could handle posting PRs to the registry with deduping, if anyone is interested on working on this sort of stuff it would be awesome. But for now, you have to manually work out what should be in the registry and add PRs for these things yourself.

Just let me know if you have further questions at all.
