### ISSUE TITLE
packageConfigPaths doesn't roundtrip correctly

### ISSUE THREAD

**Issue by WorldMaker** [jspm/jspm-cli#1261]
If I try to set `packageConfigPaths` in config.js to something like so:

```js
{
    packageConfigPaths: ['path/to/config.json']
}
```

The next time I use the jspm CLI and a change is saved to config.js it gets saved back to the file as:

```
{
    packageConfigPaths: {
        "0": "path/to/config.json"
    }
}
```

Because SystemJS is expecting an array, this pseudo-array that JSPM is writing to config.js doesn't work.

For the time being I'm using a workaround of moving this config setting to the HTML (as SystemJS doesn't mind it being configured later than config.js).

**Comment by guybedford** [comment]
Yes this is only supported in jspm 0.17.
