### ISSUE TITLE
support @sha versions

### ISSUE THREAD

**Issue by MadMub** [jspm/jspm-cli#1262]
```
jspm install npm:jsoneditor
```
Errors out as a result of a depedency using a sha as version:
```
jspm install npm:jsoneditor
     Looking up npm:jsoneditor
     Updating registry cache...
     Looking up npm:brace
     Looking up github:jspm/nodelibs-process
     Downloading npm:brace@0.4.1
     Looking up npm:w3c-blob
     Looking up github:josdejong/jsonlint
     Looking up npm:process

err  Installing npm:jsoneditor@4.2.1, no version match for github:josdejong/jsonlint@85a19d7
```
Tested doing a standard npm install jsoneditor to make sure it wasn't the package itself having a broken reference

**Comment by MadMub** [comment]
Noticed the following documentation:
https://github.com/jspm/jspm-cli/blob/master/docs/installing-packages.md#versioning

anyone know a way to overwrite the dependencies on install to ditch the versions and try installing latest (just for the sake of having a clean install)

**Comment by guybedford** [comment]
You can use a dependencies override for the package that installs jsonlint to handle this.

Something like:

```
  jspm install thing-that-installs-jsonlint@x.y.z -o "{dependencies:{all: 'dependencies', 'jsonlint': 'git://github.com/josedejong/jsonlint#x.y.z'}}"
```

Before then installing `npm:jsoneditor`. If it's jsoneditor that has that dependency then you just need the single install and override.

There aren't any plans to support sha versions for github at the moment.
