### ISSUE TITLE
Best practice to share code between server and client?

### ISSUE THREAD

**Issue by peterjuras** [jspm/jspm-cli#1263]
Hi!

I want to use a file on both the server side and in the client. My current (simplified) setup looks like this:

```
my-app/
├── package.json
├── server.js                            # Main node entry point
└── public
    └── main.js                          # jspm entry point
    └── index.html                       # Main browser entry point
    └── jspm_packages
    └── config.js                        # jspm config file 
    └── sharedModule.js                  # module that should be shared 
```

JSPM configurations:
```
package.json:
"directories": {
      "baseURL": "public",
      "lib": "public/javascripts"
    }
```
```
config.js:
baseUrl: "/",
{ ... }
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },
```

I can reference the sharedModule from both node and inside my main.js file on the client side and it works fine. However, this will stop working when I sfx bundle my main.js file and clean up the public folder to only include index.html and main.bundle.js, since node will no longer find the sharedModule.js

I would really like to not expose sharedModule.js in the public folder. What would you recommend? If I move sharedModule outside of the public folder jspm is no longer able to find it.

Thanks for your help, I really appreciate your hard work on this library!

**Comment by peterjuras** [comment]
I have one possible solution, or rather a workaround:

When I do a production build, I copy everything to a target folder (e.g. 'build') and only put the main.bundle.js and index.html into the public folder. The sharedModule.js will be copied into a new shared folder that sits outside the public folder.

In node I can now dynamically build a path to the sharedModule file by reacting to NODE_ENV or another setting to find the module.

I'd still like to know if there would be a better way to implement this.

**Comment by guybedford** [comment]
If you want code that is only available to the server, you can set up a custom paths configuration:

```javascript
System.config({
  paths: {
    'server-only/*': './path/only/on/server/*'
  }
});
```

The above config can also be added dynamically.

**Comment by calbertts** [comment]
I'm trying to bundle my app by doing that, but it fails because it seems only the directory specified in "baseURL" in the package.json is read, it's looking for the file in the client folder.

Does not baseURL receive an Array?
