### ISSUE TITLE
Current state of NodeJS support

### ISSUE THREAD

**Issue by subesokun** [jspm/jspm-cli#1266]
Hi, I just wanted to know what the current state of the NodeJS support for server applications is. The [Wiki](https://github.com/jspm/jspm-cli/blob/master/docs/nodejs-usage.md) mentions that it's not yet recommended to use JSPM for arbitrary server applications. But in case I'm writing an own server application that depends on a few third-party npm packages will it then be also hard to prevent the issues mentioned in the Wiki?

**Comment by guybedford** [comment]
This is coming in jspm 0.17, alpha release will be mid December.

**Comment by subesokun** [comment]
Great, looking forward to it :)
