### ISSUE TITLE
Troublesome workflow with Django

### ISSUE THREAD

**Issue by sergei-maertens** [jspm/jspm-cli#1267]
I'm trying to properly integrate an enjoyable development workflow + robust production deployment process with JSPM and Django, but running into limitations of `directories.baseURL`.

**Let me start with an introduction on how Django handles static files**
A Django project is basically composed of a collection of apps, and this is my project structure:

    ├── node_modules
    ├── package.json
    ├── README.rst
    ├── src
    │   ├── brouwers
    │   │   └── albums
    │   │       ├── __init__.py
    │   │       └── static
    │   │           └── albums
    │   │               └── js
    │   │                   └── photo-detail.js
    │   ├── conf
    │   ├── locale
    │   ├── manage.py
    │   ├── static
    │   └── templates
    └── static
        ├── admin
        ├── admin_tools
        ├── albums
        │   └── js
        │       ├── photo-detail.19ef401ae194.js
        │       └── photo-detail.js -> /project/src/brouwers/albums/static/albums/js/photo-detail.js
        ├── config.1b9981094867.js
        ├── config.462c530b069d.js
        ├── config.4da6ff7e785f.js
        ├── config.js -> /project/src/static/config.js
        └── ... more of the same

Here __albums__ is an app, with it's own static file photo-detail that uses SystemJS/JSPM. Eventually, I need this file to be bundled.

Now, it's important to note that the contents of the root `/static` folder are generated by a Django command - these files are not kept in version control. Django discovers all static files placed in the `static` folder of an app and copies/symlinks them to the `static root` folder (__collectstatic__). Another thing to note - and this is the source of my problems - is that these files in the static root have bits of md5 hashes appended to them. An optional Django storage calculates these hashes, and it's an excellent way to send far-future headers while busting the cache if the file is changed. Say for instance, JSPM is updated in this project and a new version of SystemJS is shipped. `static/jspm_packages/system.js` would be served from the browsers cache, but `static/jspm_packages/system.abcdef123456.js` would not.

**So, getting to the JSPM bit...**

In my `package.json`, I had set-up `/static/` as my `baseURL`, and `/static/jspm_packages/` as my packages folder. This was great, except that Django is not nice here - it has no notion the jspm_packages directory, as it is the target directory for __collectstatic__. So, in my case, I cannot use Django's nice templatetag, because I need the storage that appends hashes. This could be worked around, except that on every update of SystemJS I will probably have a bunch of users that will complain that something doesn't work and I will have to tell them to hard refresh, effectively ruining all the efforts to be able to work with far future headers.

Bundling works in this case, because collectstatic collected all the 'deeply nested' JS files into the known directory for JSPM.

**Fixing the hash-problem breaks bundling**
So, I thought I was going to be clever and it would be a no brainer and I decided to move the `jspm_packages` directory to some place where __collectstatic__ will pick it up. Easily done, file is properly cached, but now bundling is broken. For this, I had to change the `directories.packages` setting in `package.json` to `src/static/jspm_packages` (picked up by __collectstatic__). Which in turn leads to `jspm` warning me that this is not a subfolder of `baseURL` (which was still set to `static/`). This also broke development mode where no bundling takes place, because in `config.js` the path mapping is now changed to `src/static/jspm_packages/<whatever>` instead of the `jspm_packages/<whatever>` it used to be. Obviously that warning is there for a reason, so I changed the `baseURL` to `src/static/, but then bundling is broken because it tries to locate `photo-detail.js` in `/project/src/static/albums/js/photo-detail.js` instead of `/project/static/albums/js/photo-detail.js`.

**Solution**
None... so far. I'm mainly putting this out here in hope that someone else can also give it a thought, maybe I even run into a Django dev who's having the same issue or I can be of any use to someone running into this problem in the future...

But it would be nice if there could be some feedback/discussion w/r to possible options to solve this in a nice way without having to concede too much.

**Comment by guybedford** [comment]
It sounds like the underlying issue here is the constraint imposed by jspm that the jspm_packages folder in the browser and the server must both be the same folder relative to the baseURL. Is it not possible to maintain this invariant with the separate hashing folder by altering the baseURL instead of the packages folder?

jspm_packages is effectively only versioned to the major version of jspm itself, so ideally that major version number would be the only URL hash necessary. SystemJS can change more regularly, but doesn't have to be served from jspm_packages. You could equally well download it directly and allow it to be hashed separately.

**Comment by sergei-maertens** [comment]
Finally got some time to get back to this.

For a while I thought that was indeed the underlying constraint - if the 'prefix' (jspm_packages) could be specified manually instead of derived from `directories.packages`, the development stuff would work.

In that case, you could end up with (relevant bit in package.json):

    directories: {
        "basePath": "static",  // this is where bundling will look for the files, relative to package.json
        "baseURL": "/static/jspm_packages",  // this is what SystemJS should prefix for async loading in the browser
        "packages": "src/static/jspm_packages", // relative to package.json
    }

Ofcourse, this would have big implications for jspm/systemjs I'm afraid.

The flow with that situation would be that Django handles any '/static/...' request, and maps it to any 'static' subfolder. So, SystemJS doesn't have to do any path translation. Before bundling, `collectstatic` is run, which makes all static files end up in the root `/static/` folder (`basePath` in the example config bit). So, JSPM would then install in `directories.packages`, which is NOT a subfolder of `directories.packages` (this is problematic for JSPM/SystemJS), and the files would be gathered into the correct location by Django.

"Is it not possible to maintain this invariant with the separate hashing folder by altering the baseURL instead of the packages folder?"
I'm not a hundres percent sure I get what you mean. Do you mean changing the root `/static/`folder to a name with a hash in it?

"jspm_packages is effectively only versioned to the major version of jspm itself, so ideally that major version number would be the only URL hash necessary."

If, when you run `jspm install`, the resulting

**Comment by guybedford** [comment]
It would help a lot if you could explain again here, with reference to your first attempt at this workflow - could you not set baseURL to the generated /static folder and then have bundling run against the generated jspm_packages and everything else in there?

**Comment by sergei-maertens** [comment]
@guybedford yes, that works, bundling works and local development works, except that jspm_packages in that case is not generated by Django, but by JSPM. This in turn has the result that Django has no notion whatsoever of the jspm_packages folder.

Hashing the files is an optional step - but one that is done in production, and there exists the problem: Django only hashes the files it knows of, so any file inside of jspm_packages doesn't get a copy with the hash. This is only a problem for the places where SystemJS itself is referenced, for example in https://github.com/modelbrouwers/modelbrouwers/blob/master/src/templates/sniplates/js.html#L4

Hope I've made myself clear, if not, I'll be happy to try again!

**Comment by guybedford** [comment]
@sergei-maertens ahh, so ideally you would want the **installed** jspm_packages to be `src/static/jspm_packages`, but the **served** jspm_packages to be `static/jspm_packages`?

**Comment by sergei-maertens** [comment]
yes, that would be the best scenario I think

**Comment by guybedford** [comment]
Ok thanks - the feedback really helps to hear. I will see what we can do in jspm 0.17 around this, but there's nothing that can be done for the current version unfortunately.

**Comment by sergei-maertens** [comment]
Cool, for the time being I'm properly dealing with it in
https://github.com/sergei-maertens/django-systemjs, so no haste. Thanks for
thinking along!

**Comment by guybedford** [comment]
I've included this flexibility in jspm 0.17, do try it out when it finally gets released!

**Comment by sergei-maertens** [comment]
Great news, I'll keep an eye on the upcoming release!

**Comment by davis** [comment]
how can i accomplish this in jspm 0.17? :o

**Comment by guybedford** [comment]
@davis jspm init with custom prompts should guide you through it?
