### ISSUE TITLE
Installing JSPM on Mac OS X El Capitan -bash: jspm: command not found

### ISSUE THREAD

**Issue by iyerushalmi** [jspm/jspm-cli#1268]
I try installing jspm on my Mac OS X but when I run the jspm command "jspm registry config github" I get the error "-bash: jspm: command not found".

Here is how I installed JSPM. I appreciate any advice:

sudo npm install jspm -g
Password:
/usr/local/Cellar/node/4.1.1/libexec/npm/bin/jspm -> /usr/local/Cellar/node/4.1.1/libexec/npm/lib/node_modules/jspm/jspm.js
jspm@0.16.14 /usr/local/Cellar/node/4.1.1/libexec/npm/lib/node_modules/jspm
├── rimraf@2.4.3
├── graceful-fs@3.0.8
├── semver@5.0.3
├── ncp@2.0.0
├── jspm-registry@0.4.0 (semver@4.3.6)
├── rsvp@3.1.0
├── chalk@1.1.1 (escape-string-regexp@1.0.3, ansi-styles@2.1.0, supports-color@2.0.0, has-ansi@2.0.0, strip-ansi@3.0.0)
├── glob@5.0.15 (path-is-absolute@1.0.0, inherits@2.0.1, once@1.3.2, inflight@1.0.4)
├── minimatch@2.0.10 (brace-expansion@1.1.1)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── liftoff@2.2.0 (findup-sync@0.3.0, extend@2.0.1, rechoir@0.6.2, flagged-respawn@0.3.1, resolve@1.1.6)
├── jspm-github@0.13.8 (netrc@0.1.4, expand-tilde@1.2.0, yauzl@2.3.1, which@1.2.0, rimraf@2.3.4, tar@2.2.1, request@2.53.0)
├── uglify-js@2.4.24 (async@0.2.10, uglify-to-browserify@1.0.2, yargs@3.5.4, source-map@0.1.34)
├── traceur@0.0.92 (commander@2.6.0, semver@2.3.2, glob@4.3.5, source-map-support@0.2.10)
├── core-js@0.9.18
├── jspm-npm@0.25.3 (which@1.2.0, resolve@1.1.6, tar@1.0.3, rmdir@1.1.0, request@2.58.0)
├── request@2.65.0 (aws-sign2@0.6.0, forever-agent@0.6.1, tunnel-agent@0.4.1, oauth-sign@0.8.0, caseless@0.11.0, stringstream@0.0.5, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, tough-cookie@2.2.0, node-uuid@1.4.3, qs@5.2.0, form-data@1.0.0-rc3, combined-stream@1.0.5, mime-types@2.1.7, http-signature@0.11.0, hawk@3.1.1, bl@1.0.0, har-validator@2.0.2)
├── systemjs@0.19.5 (when@3.7.4, es6-module-loader@0.17.8)
└── systemjs-builder@0.14.10 (source-map@0.4.4, es6-template-strings@2.0.0)

**Comment by guybedford** [comment]
I guess you need to make sure `/usr/local/Cellar/node/4.1.1/libexec/npm/bin/jspm` is in your PATH? This is more of an npm install support issue than a jspm one.
