### ISSUE TITLE
npm react-forms does not install correctly

### ISSUE THREAD

**Issue by 5an1ty** [jspm/jspm-cli#1270]
I'm writing an application in react and everything is working fine except installing react-forms.
It seems like jspm/systemjs/babel is not transpiling the jsx in that package... I have no clue why.

example:

    jspm install npm:react-forms

then in your js:

    import reactForms from 'react-forms'

**Comment by johnsoftek** [comment]
@5an1ty System.js assumes cjs format for npm packages. react-forms/lib/index.js has no import or export statements, so the transpiler is not invoked.

> https://github.com/jspm/jspm-cli/blob/master/docs/getting-started.md
> Note modules are only detected as ES6 when module syntax is present.

**Comment by 5an1ty** [comment]
Thanks a lot, that explains it.

**Comment by guybedford** [comment]
If you need help with the override here further just let me know.
