### ISSUE TITLE
jspm uninstall github:anything/anything fails after jspm install github:anything/anything

### ISSUE THREAD

**Issue by capaj** [jspm/jspm-cli#1271]
This occurs to me when I install a wrong package and I need to unsinstall it. Naturally, I expect that after installing package with

```
jspm install github:anything/anything
```

Then it would work to uninstall it with 

```
jspm uninstall github:anything/anything
```

But no. Could we have it like that?

**Comment by guybedford** [comment]
Yes, we should!

**Comment by jackfranklin** [comment]
@guybedford what would this involve? Happy to take a stab. I guess it's figuring out the files that would have been created on install and just removing them?

**Comment by capaj** [comment]
@jackfranklin 
```
jspm uninstall anything/anything
```
works for uninstalling, so basically to resolve this issue, it should be enough to alias the current behaviour to work with the 'github' in the front. Should be solvable somewhere here:
https://github.com/jspm/jspm-cli/blob/master/cli.js#L311

**Comment by guybedford** [comment]
@jackfranklin thanks, that would be amazing. It involves doing a reverse lookup of the full package name provided against the dependency lists in `config.pjson.dependencies` and `config.pjson.devDependencies` around https://github.com/jspm/jspm-cli/blob/master/lib/install.js#L1025 to check custom aliases. It could also be designed to allow the version part to be optional as well when doing this reverse lookup. The dependencies objects are maps of install aliases to PackageName instances.
