### ISSUE TITLE
Installing from private endpoint using bower fails

### ISSUE THREAD

**Issue by charlespockert** [jspm/jspm-cli#1273]
Trying to install using `jspm-bower-endpoint` plugin to pull from a private repo (Telerik's KendoUI pro) and I get 

```
Downloading bower:https://bower.telerik.com/bower-kendo-ui.git@2015.2.813
```

This sits there forever, killing my CPU - inspection in ProcMon (this is on a Win8.1 system) reveals:

![image](https://cloud.githubusercontent.com/assets/9073518/11033355/3b1f0558-86da-11e5-9a78-aa3aa1557c23.png)

(this repeats forever...)

So it looks like the package name is including the URL protocol and trying to create a directory for the same. I tried a quick tweak in `package.js` and `config\package.js` to strip off the `https://` which seemed to work, but at the end of the install I got this:

```
ok   Installed kendo as bower:https://bower.telerik.com/bower-kendo-ui.git@^2015.2.813 (2015.2.813)
     Removing package files for bower:bower-kendo-ui.git@2015.2.813
```

The package was created OK in the cache, but was removed after install from the install directory, not sure what JSPM checks for to see if a package is required.

Is this the correct way to install from private repos? The bower endpoint docs suggest so: https://www.npmjs.com/package/jspm-bower-endpoint

Does this work on Linux systems because of the relaxed available path characters?

FYI: Setup was...

```
npm install jspm-bower-endpoint
jspm registry create bower jspm-bower-endpoint
jspm install bower:https://bower.telerik.com/bower-kendo-ui.git
```

**Comment by guybedford** [comment]
The bower endpoint is not supported or advised. Any issues should be reported there.

**Comment by charlespockert** [comment]
@guybedford I understand that the bower endpoint is not supported and since you say "not advised", is there a supported way for installing from a private git repo/bower (e.g. not github)?

Apologies if this has already been asked/there are some docs somewhere, I've yet to locate them despite a fair bit of trawling the issues/google. I also appreciate all the work you've been doing on jspm :)

**Comment by guybedford** [comment]
@charlespockert there is jspm-git which is recommended for these cases - https://github.com/Orbs/jspm-git.

**Comment by charlespockert** [comment]
Thanks Guy will take a look!
