### ISSUE TITLE
Handle casing - ensure all package names are lowercased

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#1274]
By default we should just lowercase all package name inputs.

**Comment by jackfranklin** [comment]
@guybedford would that be a case of lowercasing the inputs to https://github.com/jspm/jspm-cli/blob/master/lib/install.js#L168 ? I'm happy to work on the PR, but a pointer in the right direction would be appreciated to avoid wasted effort :)

**Comment by guybedford** [comment]
@jackfranklin yes exactly, that should cover it all actually. Would be awesome to have a contribution here.

**Comment by jackfranklin** [comment]
@guybedford perfect, PR incoming.

Am I right in saying that `name` is always a string, but `target` might be? 

EG, need to handle all these cases:

```
jspm.install('jquery', 'github:components/jquery@^2.0.0') => downcase both
jspm.install('jquery', {...}) => downcase just name
jspm.install('jquery', 'github:components/jquery@^2.0.0', {...}) => downcase first two
```

**Comment by jackfranklin** [comment]
@guybedford this is now done as of #1275 being merged :tada:

**Comment by guybedford** [comment]
I'm only just starting to think properly through the edge case upgrade path breaks on this now...

1. Registry entries at https://github.com/jspm/registry/tree/master/package-overrides/github would all need to be lower cased. Existing installs in jspm that are case sensitive would then break, so we probably want to duplicate the above entries into their lower case equivalents
2. If projects have previously installed a cased package, they would need to run `jspm install` to "downcase" their configuration file. Any System.import statements to the full name like `github:Project/name@x.y.z/...` would then need to be rewritten.

(1) is completely resolvable and just involves upgrading the registry.

(2) is a little bit more worrying though, and makes me think we may have to bump this change to jspm 0.17 as a breaking change unfortunately.
