### ISSUE TITLE
[idea] Compile JavaScript in a worker(s).

### ISSUE THREAD

**Issue by trusktr** [jspm/jspm-cli#1278]
That would speed up the in-browser process. [matthiasak/Arbiter](https://github.com/matthiasak/Arbiter) is using this technique to compile code in-browser with Babel. The difference with JSPM would be that JSPM sends it back to the UI thread. It's possible that each module (or groups of modules) can be compiled in separate workers, then the final bundle gluing can happen in a final worker.

The question is, would the benefits of compiling in a worker outweigh the amount of overhead in creating the workers and send code to/from the workers?

**Comment by guybedford** [comment]
It's really interesting to explore these areas, and projects can be made that build on top of SystemJS or jspm to handle this. jspm and SystemJS are designed to enable these kinds of secondary projects.

The current direction jspm is taking wrt to this type of performance is through server workflows that can persist and cache on the server. Projects like https://github.com/capaj/jspm-hot-reloader and https://github.com/jackfranklin/jspm-dev-builder being the currently recommended directions.
