### ISSUE TITLE
dagre-d3 dependency d3 is not getting loaded

### ISSUE THREAD

**Issue by myitcv** [jspm/jspm-cli#1280]
_Recreated here from https://github.com/systemjs/systemjs/issues/897_

I notice https://github.com/systemjs/systemjs/issues/741 which might be related.

```
    "jspm": "0.16.14",
    "systemjs": "0.19.5",
```

As a simple repro, `jspm install npm:dagre-d3`. You will notice from `config.js` that `d3` is listed as a dependency:

```
    "dagre-d3": "npm:dagre-d3@0.4.10",
...
    "npm:dagre-d3@0.4.10": {
      "d3": "npm:d3@3.5.6",
      "dagre": "npm:dagre@0.7.4",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "graphlib": "npm:graphlib@1.0.7",
      "lodash": "npm:lodash@3.10.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
```

Using this simple TypeScript example:

```typescript
import "dagre-d3";

export function Run(): void {
	console.log("Running browser");
}
```

which gets transpiled to [this](https://gist.github.com/myitcv/abde649d718bd30685f6), then setting a breakpoint in Chrome on the `console.log` line. 

What I observe is that `d3` has not been loaded at this breakpoint, at least these facts lead me to believe so:

* the network tab in Chrome debugger does not show that the file has been loaded
* the `d3.js` source file (within `npm/d3@3.5.6`) is not present in the 'Sources' tab
* `window.d3` is `undefined`

This obviously breaks `dagre-d3` because it is relying on `d3` having been loaded (and available via `window.d3`)... But given the dependency tree above it would seem to suggest it _should_ have been loaded. 

Of the dependencies above, I can see the following have been loaded:

```
"process": "github:jspm/nodelibs-process@0.1.2"
"lodash": "npm:lodash@3.10.1"
"graphlib": "npm:graphlib@1.0.7"
"dagre": "npm:dagre@0.7.4"
```

whereas two, including `d3`, have not:

```
"fs": "github:jspm/nodelibs-fs@0.1.2"
"d3": "npm:d3@3.5.6"
```

Am I missing something?

Any help much appreciated!

**Comment by myitcv** [comment]
@guybedford in response to [your comment](https://github.com/systemjs/systemjs/issues/897#issuecomment-154422583) in the previous 'version' of this issue, I've created a small repro of the problem as I see it:

https://github.com/myitcv/jspm_dependency_repro

Do you see `undefined` in this repro (as mentioned in the `README.md`)?

**Comment by jackfranklin** [comment]
@myitcv I wouldn't expect `window.d3` to be defined necessarily. Running your repo locally, I see this in the server logs:

```
GET /jspm_packages/npm/dagre-d3@0.4.10/lib/d3.js
```

The contents of that file are:

```
module.exports = window.d3;
```

Which is weird to me and is probably the cause of the issue, this should be requiring d3 instead of expecting it to exist globally. I'm not sure how we can fix this though, and I don't know enough about the internals about jspm to be able to suggest anything.

# Workaround

```
jspm install d3
```

```js
    System.import('d3').then(function(d3) {
      window.d3 = d3;
      return System.import('dagre-d3').then(function(dagre) {
        console.log('got here');
      });
    }).catch(function(err) {
      console.log('Error', err);
    });
```

Does seem to get things going, far from ideal though.

**Comment by jackfranklin** [comment]
So for whatever reason the creator of dagre-d3 explicitly made it so you need to load in D3 ahead of loading in dagre-d3:

https://github.com/cpettitt/dagre-d3/commit/b240dbda623ce84723bfffa9420f98271f15282f

So I don't think this is a jspm bug - d3 is listed as a dependency of dagre-d3 but you still need to do some manual shifting to get it into the global object for dagre to work.

**Comment by myitcv** [comment]
Thanks @jackfranklin :smile: 

> Running your repo locally, I see this in the server logs:

> ```
GET /jspm_packages/npm/dagre-d3@0.4.10/lib/d3.js
```

As do I (it's presumably some wrapper that this library is using to avoid having to reference `window.d3` everywhere), but critically you don't see a line like this:

```
GET /jspm_packages/npm/d3@3.5.7/d3.js
```

i.e. the actual `d3` library. 

Hence, as far as I can tell, why `window.d3` is not defined in my repro.

> ## Workaround
> ```
jspm install d3
```

Indeed, that's what I also see: if I install `d3` separately and load it per your example, `window.d3` is available. So that confirms for me that if `d3` does get loaded, `window.d3` is defined as a side effect.

So, to my basic understanding the summary is as follows:

* `dagre-d3` expects `window.d3` to be defined, hence why `d3` is listed as a dependency. We see that `jspm` understands this dependency because it is present in [`config.js`](https://github.com/myitcv/jspm_dependency_repro/blob/master/config.js#L25)
* Installing and importing `d3` separately confirms that in so doing `window.d3` does get defined
* Installing `dagre-d3` via `jspm` and importing it does not however load `d3`, even though it is listed (in `config.js`) as a dependency, hence `window.d3` is not available to `dagre-d3`

**Comment by jackfranklin** [comment]
I think the key thing you're missing though is that I don't think there's anywhere in the dagre-d3 source where it explicitly does do `require('d3')`. So whilst it is a dependency and jspm rightly lists it as one, dagre-d3 never requires it and hence it never loads (jspm doesn't just blindly load all deps onto `window`, that would go wrong quickly!). Does that make sense?

**Comment by myitcv** [comment]
Ah, I see what you're saying. Yes, my assumption had been that SystemJS would front load all dependencies, regardless of when/where they are used. 

I guess another solution here would be to shim the `lib/d3` file?

**Comment by jackfranklin** [comment]
Yes, I'd be tempted to fork dagre-d3 and swap lib/d3 for one that does: `module.exports = require('d3')`. I would expect jspm to play nicely with that.

**Comment by myitcv** [comment]
Actually the shim approach is almost working (agreed, fixing `dagre-d3` is the proper fix):

```
{
	"shim": {
		"lib/d3": {
			"format": "cjs",
			"deps": ["d3"]
		}
	}
}
```

You will notice I've tried to set the `format` of the shim. Nonetheless, `jspm_packages/npm/dagre-d3@0.4.10/lib/d3.js` still looks like this:

```javascript
/* */
"format global";
"deps d3";
// Stub to get D3 either via NPM or from the global object
module.exports = window.d3;
```

Changing this manually to:

```javascript
/* */
"format cjs";
"deps d3";
// Stub to get D3 either via NPM or from the global object
module.exports = window.d3;
```

then everything works.

From [here](https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm#shim-configuration):

> Shims aren't limited to globals and can be used to define the dependencies for any file in a project.

So again, I'm probably missing something obvious...any thoughts?

**Comment by myitcv** [comment]
@jackfranklin thanks again for setting me straight on this. I've [raised an issue on `dagre-d3`](https://github.com/cpettitt/dagre-d3/issues/198).

Only outstanding question here (and maybe @guybedford can help on this one) is how to set the `"format"` for a shim to something other than `"global"`?

**Comment by guybedford** [comment]
@myitcv shimming dependencies always forces modules to be treated as globals unfortunately. I've removed that line from the documentation.

The ability to set dependencies for non-globals is supported in the coming jspm 0.17 though.

**Comment by myitcv** [comment]
@guybedford thanks for confirming. I'll use my fork of `dagre-d3` for now and work on getting the correct 'fix' committed back.

Thanks again to you and @jackfranklin - I'll close this for now.
