### ISSUE TITLE
Clarify a sentence in production-workflows.md

### ISSUE THREAD

**Issue by luisfmsouza** [jspm/jspm-cli#1281]
From this:

`This command will make main-bundle.js file with app/main and app/core module excluded.`

To something like this:

`This command will make main-bundle.js file with app/main, excluding app/core module.`

Sorry if I had doubts because of my poor english.

**Comment by guybedford** [comment]
Sure, thanks for the suggestion - added https://github.com/jspm/jspm-cli/commit/4d06355a73708b81d567f196ac759174b27b3021.
