### ISSUE TITLE
Not discovering global registry handler

### ISSUE THREAD

**Issue by unional** [jspm/jspm-cli#1284]
I've created [jspm-p4](https://github.com/unional/jspm-p4) and intend to use it for multple modules in my company, so I install and create the registory globally:

````
npm -g i jspm-p4
jspm registry create comp jspm-p4
...
````

When I use it without a local copy of jspm, it works correctly. But as suggest, we should run a local jspm:
````
npm i jspm
````
But once I do that, installing modules fails:
````
jspm i comp:mymodule
> Cannot find module 'jspm-p4' ...
> Unable to load registry comp
````

Seems like the local jspm need to check with the global jspm for the available registry?

The same will happen if I try to create the registry with local jspm installed:

````
npm i jspm
npm -g i jspm-p4
jspm registry create comp jspm-p4
> Registry handler jspm-p4 not installed
````

**Comment by guybedford** [comment]
All that jspm does is a `require(endpointName)`, so as long as the global npm install folder is in your node_modules paths, it should be found. If you run a simple test app via `test.js` with `require('jspm-p4')` are you able to require the global module from a local project?

**Comment by unional** [comment]
You are right, it's npm can't resolve the module.  I couldn't find out what's wrong. The `package.json` seems to be ok and it is installed at the right path.

This is likely the last issue to resolve before it can be useful for everyone.
I'm not expert in npm so maybe I'm missing something obvious?

Would anyone can give me a little help to get it solved?

Thanks,
Unional

https://github.com/unional/jspm-p4

**Comment by guybedford** [comment]
See https://nodejs.org/api/modules.html#modules_loading_from_the_global_folders for where NodeJS will search for modules. It's about ensuring that the npm global install folder is within this lookup path.

**Comment by unional** [comment]
From discussion on https://github.com/nodejs/node/issues/3865, seems like node is not expecting to reference global module through `require(...)` to begin with.
In that case, `jspm` may need to think of another workflow to support local/private registry?

Custom module such as `jspm-p4` should make sense to be configure once and use on multiple projects.

**Comment by unional** [comment]
Figured it out. Closing this issue.

`jspm` does work correctly with local `jspm-p4` and `jspm registry create comp jspm-p4`. The `comp` registry is recognized in other projects even it is ran against local copy of `jspm` and `jspm-p4` on each project.

Excellent work. :+1:

**Comment by unional** [comment]
Adding comment to make it more elaborate if someone has the same issue:

````
npm -g i jspm  // Install jspm globally
npm i jspm jspm-p4 // Install them locally
jspm registry create comp jspm-p4 // Create 'comp' using local jspm an jspm-p4
jspm i comp:myModule // install myModule from comp registry.
mkdir ../anotherProject && cd ../anotherProject // go to another project
npm i jspm jspm-p4 // install them locally at anotherProject
jspm i comp:myModule // Also works here, no need to do 'jspm registry create comp jspm-p4' again.
````

**Comment by smartmouse** [comment]
@guybedford  is correct, the module loading mechanism -Loading from the global  folders  -should have located the globally installed node module.  I think the search locations will be correct if $PREFIX/lib/node is  replaced by $PREFIX/lib/node_modules  ,  On windows, it will be different as it will be $PREFIX/node_modules .    Note that NODE_PATH should be optional thing.

**Comment by unional** [comment]
Well, as said in the link: **You are highly encouraged to place your dependencies locally in node_modules folders**. I agree to that statement and the direction node is heading in that regards, as I run into IT problems and begging them to install/update module with `-g`.  It is best if we can keep things local to each project.

Since `jspm` does exactly what I want when running `jspm` and customer registry (`jspm-p4`) locally, I'm a happy camper.
