### ISSUE TITLE
Almost ts module

### ISSUE THREAD

**Issue by unional** [jspm/jspm-cli#1287]
I followed https://github.com/jspm/jspm-cli/blob/master/docs/publishing-packages.md to expose typescript only module and **almost** get it to work.

The modules I created are:

* https://github.com/unional/jspm-ts-named  // do named export
* https://github.com/unional/jspm-ts-test  // do default export
* https://github.com/unional/jspm-ts-consume // consume the above modules.

The named export works but the default export does not.  The simplest way to fix it is to edit the generated js file to export `default` (or change it to es6 import/export would also work).

Can then endpoint hook able to change the generated js file automatically?

Or there can be another way to make it work?

Another reason that I post this as it might be helpful to 0.17 release.

Cheers,

**Comment by guybedford** [comment]
Perhaps the suggestion in https://github.com/Microsoft/TypeScript/issues/5285#issuecomment-153207020 is relevant here?

**Comment by unional** [comment]
It is jspm thing.  The generated js I mean is the `jspm-ts-test@0.1.5.js` file under `jspm_packages/github/unional/`.

Anyway the https://github.com/jspm/jspm-cli/pull/1291 would be a good enough workaround for now, I think.

Closing this for now until need it again. :)
