### ISSUE TITLE
The right way to bundle with sourcemap?

### ISSUE THREAD

**Issue by unional** [jspm/jspm-cli#1288]
I try to bundle ts files and the sourcemap generated is basically empty: `{"version":3,"sources":[],"names":[],"mappings":"","file":"undefined"}`.

This happens when I remove external dependencies: `jspm bundle src/index.ts - lodash`

What is the right way to generate the sourcemap needed?

**Comment by guybedford** [comment]
The TypeScript transpiler internally does have its limitations like this.

The suggested way of using TypeScript is actually via the plugin at https://github.com/frankwallis/plugin-typescript, perhaps try using that here instead.

**Comment by guybedford** [comment]
If you get any source maps issues with the plugin approach please let me know, but the internal transpilation layer is being deprecated.

**Comment by unional** [comment]
Sure. Thanks.
Will first try to resolve the issue with Frank first.
