### ISSUE TITLE
Can you expose modules to the global space?

### ISSUE THREAD

**Issue by Kennethtruyers** [jspm/jspm-cli#1289]
Is it possible to declare a module in such a way that it will be exposed to the global namespace?

My use case:

I'm using ReactJS.NET to render react components on the server. To do this, you need to pass it a list of components on app start up (on the server). ReactJS.NET doesn't do modules though, so you need to pass it a bundle in which all components are public in scope.
The preferred way of doing this is by creating a separate local bundle that you can pass it.

In the documentation for ReactJS.NET (http://reactjs.net/guides/webpack.html) they give an example of doing this with webpack, specifically with the expose-loader plugin (https://github.com/webpack/expose-loader).

Is there a similar plugin for JSPM?

**Comment by guybedford** [comment]
There isn't something like this available for jspm, but when building SFX bundles, it will turn the module you bundle into a global itself which can be named by the `jspm bundle-sfx asdf --global-name globalName` command.
