### ISSUE TITLE
defaultJSExtension and React jsx files in isomorphic setting

### ISSUE THREAD

**Issue by perrin4869** [jspm/jspm-cli#1292]
I'm currently working on an isomorphic React application with a node backend. Problem is, on the backend babel doesn't support using the `import App from 'app.jsx!'` bang setup, and on the frontend, jspm doesn't support `defaultJSExtension` option, failing with `GET http://therapyfun.dotcore.co.il/client/jspm_packages/npm/babel-core@5.8.33/ 404 (Not Found)`... and so I'm at a state where I can't use the modules on both the client and the server... is there any solution to this? Will this be fixed for jspm 0.17?

**Comment by guybedford** [comment]
For running code in NodeJS you can use the jspm API here - `require('jspm').import('module')`. That will then support the plugin syntax and everything fine in Node for server workflows.

On the frontend, note that the option is `defaultJSExtensions` not `defaultJSExtension`.

**Comment by perrin4869** [comment]
hm... my setup is slightly different.
I have a component, `app.jsx` which depends on some other `jsx` modules, which it imports using ES6 syntax. Now, this `app.jsx` file is used both by node an by the client. The problem is, that when importing `app.jsx` from within node, you cannot use a `!` when including the rest of the jsx components, but from inside the client, with:
1) `defaultJSExtensions = true`: you need to include the `bang`, otherwise SystemJS will try to import `component.jsx.js`
2) `defaultJSExtensions = false`: fails because then it fails to find other modules, and also, `config.js` gets overwritten each time

**Comment by guybedford** [comment]
If you're able to use `jspm.import` on the server that will get you full universal JS working between both environments as you'll be using the same loader. It is completely understandable though if you need to use alternative Node workflows here.

`defaultJSExtensions: true` is necessary in jspm 0.16 yes. You can disable it for select packages using package config `defaultExtension: false` (https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#packages):

```javascript
System.config({
  packages: {
    app: { defaultExtension: false }
  }
});
```

Note that that does require putting all app code into its own folder that can be used to define the package.

**Comment by perrin4869** [comment]
Awesome, this worked like charm! Thanks!
Hope to be seeing jspm 0.17 soon :)
