### ISSUE TITLE
Detect and use the existing EOL sequence in package.json and config.js

### ISSUE THREAD

**Issue by glen-84** [jspm/jspm-cli#1293]
See: https://github.com/jspm/jspm-cli/issues/518#issuecomment-157309164

My package.json file uses LF (on Windows), and every time that I run a JSPM command, it overwrites the file using CRLF.

Can you please change this to instead detect the existing EOL sequence in the file, and use this when updating it?

Also, when config.js is initially created, it would be nice if it used the EOL sequence detected in package.json.

**Comment by guybedford** [comment]
Thanks, this support is coming in jspm 0.17.

**Comment by glen-84** [comment]
Great, thanks. =)
