### ISSUE TITLE
SFX bundle order issue since > 0.16.2

### ISSUE THREAD

**Issue by cAhmad** [jspm/jspm-cli#1294]
Hi, I want to say a big **THANKS** for your work here, it's amazing :muscle:!

I guess this issue is related to issues #1290 and #1285 
When I try to SFX bundle my app with a `> 0.16.2` which use Builder `0.14.x` and SystemJS `0.19.x` I got ordering issue.

I also add in my `config.js` some `deps` like you said in #1285 
```
System.config({
  meta: {
    'plugin/src/pluginFile2': { deps: ['plugin'] }
  }
});
```

I suppose the problem appear since Builder try to `Deterministic build order`in `0.14.0`

If you need more details or investigation, I'm here.

**Comment by chapati23** [comment]
+1

**Comment by guybedford** [comment]
Resolved in https://github.com/jspm/jspm-cli/issues/1294, release pending.
