### ISSUE TITLE
jspm bundle hangs with scss import

### ISSUE THREAD

**Issue by tzejohn** [jspm/jspm-cli#1295]
I am using the "github:mobilexag/plugin-sass@^0.0.10" plugin to import sass files in via the import statement.  But, when I include the line
```
import './styles/main.scss!';
```
in my module, the bundle command just hangs.  If I remove the import statement, it works fine.  I am just executing:
```
jspm bundle index
```
Is there anything that needs to be added to the plugin to support bundling, or to configure certain module paths to be skipped?

**Comment by ebpa** [comment]
See my PR: mobilexag/plugin-sass#18

You can pull from my repo (ebpa/sass@windows-local-path-fix) or edit it by hand (a very minor change) until they merge it.

**Comment by guybedford** [comment]
It sounds like this was a plugin issue that has been fixed.

**Comment by ebpa** [comment]
@guybedford  Correct.
