### ISSUE TITLE
Ignoring Module or File

### ISSUE THREAD

**Issue by xealot** [jspm/jspm-cli#1298]
We have a particular package that switches implementations based on the Javascript runtime (node or browser). SystemJS and jspm traverses the file blindly and includes a lot of node packages that will never be used in the browser.

Is it possible to exclude a particular file within a module from being analyzed?

I know you can do `bundle X - Y` for the bundler, which I've tried successfully. However, I was hoping this could be done at the dependency itself as to avoid needing every upstream user to exclude the file.

Or maybe, a totally different suggestion?

Thanks

**Comment by guybedford** [comment]
One way that can be shared is to use the empty map for this, which can be included in the package.json:

```
{
  "map": {
    "some-dep": "@empty"
  }
}
```

or by an override config:

```
  jspm install x -o "{map:{'some-dep':'@empty'}}"
```

Where `require('some-dep')` in code will then just return an empty object.

**Comment by xealot** [comment]
Does the `map` need to be in the `jspm` key of the package.json or can it be on its own?

Should I place that map directive in the project that is depending on the module or should I place it in the module's package.json? From your statement, it seems like the latter but the command line version makes me think maybe not.

This should work with any file right? Not just the top level module.

**Comment by guybedford** [comment]
It can be in either, but must be in the original project package.json that does the require, or it can be via an override of it. See https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm#testing-configuration for more info.

**Comment by xealot** [comment]
I'm really sorry, I must be missing something. I'm trying to mimic what's going on here https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm#map-configuration but it isn't working for me.

```javascript
  "jspm": {
    "map": {
      "./connector/node": "@empty",
      "connector/node": "@empty",
      "@usr/http/connector/node": "@empty",
      "@usr/http/js/connector/node": "@empty"
    }
  },
```

I'm trying quite a few permutation of this, the actual require call looks like this:
```javascript
require("./connector/node")
```

When I update the package and the run `jspm update` in my other project it still includes all of the node polyfills from the node portion of the dependency.

What am I missing?

**Comment by guybedford** [comment]
Which Node polyfills is it including? Perhaps you want to be mapping the node polyfills themselves to `@empty`?

**Comment by xealot** [comment]
Blacklisting the node modules that my file imports seems to work much better. So the config works, it just doesn't work on any require it seems like. Does this only work for modules outside of your current project?

**Comment by guybedford** [comment]
Yes almost. So the way that we support Node modules is by parsing all the sources of a package from the `npm` registry on install, and all `require()` statements that require Node core modules add those Node core modules as dependencies. So it's not tree-based but covering all files in the package. To exclude files for this check, add them to the `ignore` list rather - eg `jspm install npm:x -o "{ignore:['folder-not-to-include']}"`. Otherwise explicitly mapping the Node core modules to empty is the exact way to go as you have done.

**Comment by xealot** [comment]
Ok, thanks for the information!
