### ISSUE TITLE
Exclude core-js promise polyfill

### ISSUE THREAD

**Issue by OliverJAsh** [jspm/jspm-cli#1302]
I noticed that when I use `Promise` in my JS, jspm will bundle all of the following:

```
       npm:core-js@1.2.6/library/fn/promise
       npm:core-js@1.2.6/library/modules/$
       npm:core-js@1.2.6/library/modules/$.a-function
       npm:core-js@1.2.6/library/modules/$.add-to-unscopables
       npm:core-js@1.2.6/library/modules/$.an-object
       npm:core-js@1.2.6/library/modules/$.classof
       npm:core-js@1.2.6/library/modules/$.cof
       npm:core-js@1.2.6/library/modules/$.core
       npm:core-js@1.2.6/library/modules/$.ctx
       npm:core-js@1.2.6/library/modules/$.defined
       npm:core-js@1.2.6/library/modules/$.descriptors
       npm:core-js@1.2.6/library/modules/$.dom-create
       npm:core-js@1.2.6/library/modules/$.export
       npm:core-js@1.2.6/library/modules/$.fails
       npm:core-js@1.2.6/library/modules/$.for-of
       npm:core-js@1.2.6/library/modules/$.global
       npm:core-js@1.2.6/library/modules/$.has
       npm:core-js@1.2.6/library/modules/$.hide
       npm:core-js@1.2.6/library/modules/$.html
       npm:core-js@1.2.6/library/modules/$.invoke
       npm:core-js@1.2.6/library/modules/$.iobject
       npm:core-js@1.2.6/library/modules/$.is-array-iter
       npm:core-js@1.2.6/library/modules/$.is-object
       npm:core-js@1.2.6/library/modules/$.iter-call
       npm:core-js@1.2.6/library/modules/$.iter-create
       npm:core-js@1.2.6/library/modules/$.iter-define
       npm:core-js@1.2.6/library/modules/$.iter-detect
       npm:core-js@1.2.6/library/modules/$.iter-step
       npm:core-js@1.2.6/library/modules/$.iterators
       npm:core-js@1.2.6/library/modules/$.library
       npm:core-js@1.2.6/library/modules/$.microtask
       npm:core-js@1.2.6/library/modules/$.property-desc
       npm:core-js@1.2.6/library/modules/$.redefine
       npm:core-js@1.2.6/library/modules/$.redefine-all
       npm:core-js@1.2.6/library/modules/$.same-value
       npm:core-js@1.2.6/library/modules/$.set-proto
       npm:core-js@1.2.6/library/modules/$.set-species
       npm:core-js@1.2.6/library/modules/$.set-to-string-tag
       npm:core-js@1.2.6/library/modules/$.shared
       npm:core-js@1.2.6/library/modules/$.species-constructor
       npm:core-js@1.2.6/library/modules/$.strict-new
       npm:core-js@1.2.6/library/modules/$.string-at
       npm:core-js@1.2.6/library/modules/$.task
       npm:core-js@1.2.6/library/modules/$.to-integer
       npm:core-js@1.2.6/library/modules/$.to-iobject
       npm:core-js@1.2.6/library/modules/$.to-length
       npm:core-js@1.2.6/library/modules/$.uid
       npm:core-js@1.2.6/library/modules/$.wks
       npm:core-js@1.2.6/library/modules/core.get-iterator-method
       npm:core-js@1.2.6/library/modules/es6.array.iterator
       npm:core-js@1.2.6/library/modules/es6.object.to-string
       npm:core-js@1.2.6/library/modules/es6.promise
       npm:core-js@1.2.6/library/modules/es6.string.iterator
       npm:core-js@1.2.6/library/modules/web.dom.iterable
```

Can you clarify whether this is just what is needed for `Promise`, or whether the whole of core-js is being added to the bundle, perhaps unnecessarily? I'm just trying to avoid any code redundancy.

Secondly, is there a way to disable this, so I can provide my own lightweight polyfill for Promise? I also noticed that if I provide my own `Promise`, i.e. `var Promise = {};`, jspm still seems to bundle the one from `core-js`.

Could this behaviour be documented? It surprised me!

Thanks again for your awesome work :smile:

**Comment by guybedford** [comment]
SystemJS comes with its own Promise polyfill so this is unnecessary.

This is being added by Babel when detecting the `Promise` global, so the right blacklist item should be able to remove it. That said it would be nice if this was automatic.

**Comment by OliverJAsh** [comment]
It would of course still be needed for bundle SFX, but it would be nice if
you could provide your own polyfill also

**Comment by jackfranklin** [comment]
core-js is added as a dependency by jspm: https://github.com/jspm/jspm-cli/blob/master/lib/core.js#L184

I guess the issue, as you say Guy, is Babel detecting we need to bundle core-js? I can't really find any docs from Babel on how we can turn that behaviour off, or where that stuff is happening.

**Comment by guybedford** [comment]
This is more of a sort of Babel issue I think. Will definitely bear this in mind though while working on the Babel 6 plugin.

**Comment by neothemachine** [comment]
@guybedford You said "the right blacklist item should be able to remove it" -> How can this be set in jspm's config.js or package.json section?

**Comment by guybedford** [comment]
@neothemachine I'd suggest posting a Babel issue asking how to use the runtime transformer without automatically injecting the core-js specific Promise polyfill if that is the specific issue you are asking about. jspm simply runs Babel with the runtime transformer enabled, so it's not something we have control over.
