### ISSUE TITLE
Issue when opting not to use a transpiler

### ISSUE THREAD

**Issue by glen-84** [jspm/jspm-cli#1303]
If I answer `no` to `Do you wish to use a transpiler?`, it puts `transpiler: "none"` in the config.js file – is this not supposed to be set to `false`?

[These checks](https://github.com/systemjs/systemjs/commit/78ec7f29b2526cc82f236b23a3b3f0063d135a6a#diff-41d0147f345a3c4223cb35393ff4385fR45) look for `false` and not `none`.

I've also seen it trying to load `none.js` when encountering ES6 code.

Might be related to https://github.com/aurelia/framework/issues/241.

**Comment by guybedford** [comment]
Yes it should be set to false.

**Comment by glen-84** [comment]
Related: If I change it to false, and then run `jspm install`, it switches the transpiler to babel and installs it.

Also, [this](https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#transpiler) documentation probably needs to be updated.

Thanks for all your hard work. =)

**Comment by speigg** [comment]
I'm seeing the same issue, where running `jspm install` or `jspm update` changes the `transpiler: false` option to `babel` and installs it anyways.

**Comment by guybedford** [comment]
Thanks, I believe this was fixed in https://github.com/jspm/jspm-cli/commit/51d593454fca369033ec58f8240c0cf2b55cae78 which will be released very soon.
