### ISSUE TITLE
Throw errors instead of strings

### ISSUE THREAD

**Issue by tyscorp** [jspm/jspm-cli#1304]
There are ~40 instances of throwing string literals which [destroys the stack](http://www.devthought.com/2011/12/22/a-string-is-not-an-error/) and makes debugging difficult.

I'd be happy to help with replacing them.

**Comment by guybedford** [comment]
Strings are thrown internally to distinguish between errors where stacks matter or where it is an actual `err Some error message` log without a stack. When using with the API though, it could be better to rather throw a full error, but set `err.showStack = false` to indicate that the stack should be left out as part of the logging phase.
