### ISSUE TITLE
Optional dependencies from npm

### ISSUE THREAD

**Issue by jack4it** [jspm/jspm-cli#1307]
Is it possible to pass ```--no-optional``` through ```jspm install```? The amount of dependencies (mostly optional) pulled in via ```jspm install npm:less``` is a little crazy... :(

**Comment by guybedford** [comment]
What do you mean by optional dependencies? How would we distinguish these?

**Comment by jack4it** [comment]
I mean ```optionalDependencies``` https://docs.npmjs.com/files/package.json#optionaldependencies.

And you can see there are quite a few in the less package.json (https://github.com/less/less.js/blob/master/package.json). Is it possible to teach jspm install not to install these optional ones?

```javascript
  "optionalDependencies": {
    "errno": "^0.1.1",
    "graceful-fs": "^3.0.5",
    "image-size": "~0.3.5",
    "mime": "^1.2.11",
    "mkdirp": "^0.5.0",
    "promise": "^6.0.1",
    "request": "^2.51.0",
    "source-map": "^0.4.2"
  }
```

**Comment by guybedford** [comment]
@jack4it we do not install any of the `optionalDependencies` from npm.

**Comment by jack4it** [comment]
But it's weird when ```jspm install npm:less```, jspm brings down all the "optional" dependencies... Will you be able to try it out real quick? Maybe I'm missing something here

**Comment by guybedford** [comment]
@jack4it interesting, it seems that this is done by npm itself where it includes the optionalDependencies as dependencies in the package configuration data provided from http://registry.npmjs.org/less. I'm not sure how to get around this, but we do just aim to copy what npm does.

**Comment by guybedford** [comment]
I guess we could remove `optionalDependencies` from the `dependencies` list to handle this.

**Comment by guybedford** [comment]
It would be worth investigating though first if npm always merges optionalDependencies into dependencies, or of this is an exception.

**Comment by jack4it** [comment]
npm install has this argument ```--no-optional``` to override the default behavior. Is it easy enough to have this override pass to npm?

**Comment by guybedford** [comment]
I actually went ahead and implemented this on the 0.17 branch. We can certainly do a backport.

**Comment by guybedford** [comment]
See https://github.com/jspm/npm/blob/0.17/lib/npm.js#L254

**Comment by jack4it** [comment]
Awesome! Please do back port it. Let me know if I can help

**Comment by jack4it** [comment]
Sorry I was a little confused. Is 0.17 branch the next major release branch? Do you have a planned release date for it?

**Comment by guybedford** [comment]
It turned out that there are too many cases where optional dependencies are expected to always ignore them. Rather a decent story for optionalDependencies is being worked on at https://github.com/jspm/jspm-cli/issues/1441.
