### ISSUE TITLE
"registry:package": "version" case to warn or error

### ISSUE THREAD

**Issue by aubm** [jspm/jspm-cli#1309]
Hello,

I am facing an issue when configuring overrides for a package fetched from a custom registry.

Here is the configuration for the custom registry :

```
jspm config registries.corp.baseurl http://git.corp.com
jspm config registries.corp.auth xxxxxxxxxxxxxxxxxxx
jspm config registries.corp.handler jspm-git
```

Here is a sample of package.json :

``` json
"jspm": {
    ...
    "dependencies": {
      "my-package": "corp:corp/my-package@^1.0.0",
      "angular": "npm:angular@1.4.7",
      "angular-sanitize": "npm:angular-sanitize@1.4.7",
      "openlayers/ol3": "github:openlayers/ol3@3.11.2"
    },
    "overrides": {
      "corp:corp/my-package@1.0.0": {
        "main": "dist/index.js",
        "dependencies": {
          "npm:angular": "^1.4.0",
          "npm:angular-sanitize": "^1.4.0",
          "github:openlayers/ol3": "3.11.2"
        },
        "shim": {
          "dist/index": {
            "deps": [
              "angular",
              "angular-sanitize",
              "openlayers/ol3"
            ]
          }
        }
      },
      "github:openlayers/ol3@3.11.2": {
        "main": "ol",
        "dependencies": {
          "css": "jspm:css@*"
        },
        "shim": {
          "ol": {
            "deps": [
              "./ol.css!"
            ]
          }
        }
      }
    }
  }
  ...
```

What happens when JSPM resolves dependencies for `corp:corp:my-package@1.0.0` is that it tries to fetch the following dependencies : `corp:npm:angular`, `corp:npm:angular-sanitize` and `corp:github:openlayers/ol3`.

Here is a sample of the output of the `jspm install` command :

```
warn Error on lookup for corp:npm:angular, retrying (1).
     Error: fatal: unable to access '/': The requested URL returned error: 500


warn Error on lookup for corp:npm:angular-sanitize, retrying (1).
     Error: fatal: unable to access '/': The requested URL returned error: 500

ok   Installed github:jspm/nodelibs-fs@^0.1.0 (0.1.2)

warn Error on lookup for corp:github:openlayers/ol3, retrying (1).
     Error: fatal: unable to access '/': The requested URL returned error: 500


warn Error on lookup for corp:npm:angular, retrying (2).
     Error: fatal: unable to access '/': The requested URL returned error: 500

     Looking up npm:base64-js
     Looking up npm:ieee754
     Looking up npm:is-array
     Looking up npm:os-browserify
ok   Installed npm:buffer@^3.0.1 (3.5.1)
ok   Installed github:jspm/nodelibs-os@^0.1.0 (0.1.0)
ok   Installed npm:inherits@2.0.1 (2.0.1)
     Looking up npm:process
ok   Installed github:jspm/nodelibs-process@^0.1.0 (0.1.2)

warn Error on lookup for corp:npm:angular-sanitize, retrying (2).
     Error: fatal: unable to access '/': The requested URL returned error: 500


warn Error on lookup for corp:github:openlayers/ol3, retrying (2).
     Error: fatal: unable to access '/': The requested URL returned error: 500

ok   Installed npm:is-array@^1.0.1 (1.0.1)
ok   Installed npm:os-browserify@^0.1.2 (0.1.2)
ok   Installed npm:base64-js@0.0.8 (0.0.8)
ok   Installed npm:ieee754@^1.1.4 (1.1.6)
ok   Installed npm:process@^0.11.0 (0.11.2)

warn Error on lookup for corp:npm:angular, retrying (3).
     Error: fatal: unable to access '/': The requested URL returned error: 500


warn Error on lookup for corp:npm:angular-sanitize, retrying (3).
     Error: fatal: unable to access '/': The requested URL returned error: 500

     Looking up npm:url
ok   Installed github:jspm/nodelibs-url@^0.1.0 (0.1.0)
     Looking up npm:Base64
ok   Installed github:jspm/nodelibs-http@^1.7.0 (1.7.1)

warn Error on lookup for corp:npm:angular
     Error: fatal: unable to access '/': The requested URL returned error: 500


err  Error looking up corp:npm:angular.

warn Installation changes not saved.
```

This issue seems to occur when dependencies need to be fetched from not only one registry. Is there a way to make it work as expected ?

Thanks in advance.

**Comment by guybedford** [comment]
The dependencies object in the override should be an object like - 

```
          "angular": "npm:angular@^1.4.0",
          "angular-sanitize": "npm:angular-sanitize@^1.4.0",
          "ol3": "github:openlayers/ol3@3.11.2"
```

I'm wondering if we should allow your example as a shorthand form or just throw a better error here though - keeping this issue open to consider that.

**Comment by aubm** [comment]
It worked, thanks for helping me fixing that one :)

Maybe the dependencies object should stay as it is for a better consistency. However, considering that all dependencies should be declared directly in `jspm.dependencies`, dependencies declared under the overrides key could be expressed as a simple array containing only aliases.

Content of `package.json` would look like :

```
"jspm": {
    ...
    "dependencies": {
      "my-package": "corp:corp/my-package@^1.0.0",
      "angular": "npm:angular@1.4.7",
      "angular-sanitize": "npm:angular-sanitize@1.4.7",
      "openlayers/ol3": "github:openlayers/ol3@3.11.2"
    },
    "overrides": {
      "my-package": {
        "main": "dist/index.js",
        "dependencies": ["angular", "angular-sanitize", "openlayers/ol3"],
        ...
```

What do you think ?

**Comment by guybedford** [comment]
It may be best to go slowly on these kinds of additions. I'm trying to be very careful with override rules to make the logic as transparent as possible by maintaining a 1 - 1 relationship between the override and the package.json file. These kinds of suggestions, while convenient, may make that learning curve more difficult. For the other case I think perhaps we need to make `"registry:package": "version"` an error case rather than allowing it to work out?

**Comment by ca0v** [comment]
How would I install openlayers with jspm?  After running this:

    jspm install npm:openlayers

It downloads a lot of files I have no interest in and then ends with a warning after failing to install jsdoc:

    ok   Installed npm:es5-ext@~0.10.6 (0.10.11)
    err  Error processing package config for npm:jsdoc.
    warn Installation changes not saved.

So I tried to guess how to configure

    map: {
      "openlayers": "npm:openlayers@3.12.1"
    }

But get various errors depending on what I try.  With the config above it is this:

    Uncaught (in promise) Error: XHR error (404 Not Found) loading http://localhost:93/code/ol3-lab/process.js(…)

**Comment by guybedford** [comment]
@ca0v configuration help questions should be posted as jspm registry issues - https://github.com/jspm/registry/issues.

**Comment by aindlq** [comment]
I'm experiencing the same issue with openlayers. Here is corresponding issue in registry project - https://github.com/jspm/registry/issues/885
