### ISSUE TITLE
Getting Started wiki page has no content

### ISSUE THREAD

**Issue by kmoe** [jspm/jspm-cli#1310]
I got to this page by googling:

https://github.com/jspm/jspm-cli/wiki/Getting-Started

It seems to have no content, but is still linked to from the wiki index pages.

**Comment by jackfranklin** [comment]
The wiki should definitely be updated, but the best place to start is https://github.com/jspm/jspm-cli/blob/master/docs/getting-started.md :)

**Comment by jackfranklin** [comment]
And I've updated the wiki to point to that file.

**Comment by guybedford** [comment]
Yes all documentation was moved into the repo for versioning. Thanks Jack for adding the links.
