### ISSUE TITLE
Transpiling ES6 modules server-side via middleware

### ISSUE THREAD

**Issue by Rush** [jspm/jspm-cli#1311]
To reduce load time of ES6 code and avoid client-side compilation, I would like to transpile those files server side. Will it work correctly in regards to how JSPM handles ES6 modules? Furthermore, how does JSPM/SystemJS figure out whether the module is ES5 or ES6? Does it look for import/export statements?

**Comment by jackfranklin** [comment]
The regex that SystemJS uses to determine if a module is ES6 or not is here: https://github.com/systemjs/systemjs/blob/master/lib/esm.js#L6, so yes, you're effectively right in saying it looks for import and export statements.

If jspm gets a file and doesn't detect that it's ES6 it will just not try to run it through your transpiler, so you should be fine to serve up ES5 from your server, I would expect SystemJS to just deal with it.

**Comment by guybedford** [comment]
Exactly, if the module file starts with `System.register(...` SystemJS will detect that first as well automatically as the ES module compile target. Let me know how you get on with setting this up.
