### ISSUE TITLE
It should be possible to use ES2015 code without transpiling.

### ISSUE THREAD

**Issue by matthewleon** [jspm/jspm-cli#1312]
Given that several modern browsers support various aspects of ES2015 syntax, there should be a documented way of using ES2015 code in a project without causing automatic transpilation. I want to use JSPM for its module loading and bundling features, and that's it.

**Comment by matthewleon** [comment]
More specifically, I don't want to get this error:

`Error: Unable to dynamically transpile ES module as System.transpiler set to false.`

**Comment by jackfranklin** [comment]
But don't you need a transpiler to transpile the ES6 modules part?

With the release of Babel 6 and the fact that it uses plugins for all its transpilation, this should be possible in the future. However moving from Babel 5 to Babel 6 is no mean feat.

You can track the state of that at https://github.com/systemjs/systemjs/issues/914.

**Comment by matthewleon** [comment]
@jackfranklin I guess I made a kind of dumb mental distinction between "bundling" and "transpiling." The approach I favor would be to use a fast, minimal tool like Rollup as the transpiler: https://github.com/rollup/rollup
