### ISSUE TITLE
How (or should I) get `pjson.name` as the import module name?

### ISSUE THREAD

**Issue by unional** [jspm/jspm-cli#1313]
I wrote `jspm-p4` for internal modules live in p4. When I save them in p4, I incline to save them under project folder just describing what it is, (e.g. `ajax` for an internal ajax library). But when I use them, I would like to differentiate them from public libraries.

So I attempt to put that name in `pjson.name` (e.g `comp-ajax`). Is there a way to instruct `jspm` to use `pjson.name` as the alias from registry (`jspm-p4`)?

For example, folder:
````
+-- repo-root
    +-- ajax
         +-- package.json
         +-- ...other files
````

`package.json`:
````
{
  name: 'comp-ajax',
  ...
}
````

````
jspm i mycomp:ajax
````

produces `config.js`:
````
...
map: {
  "comp-ajax": "mycomp:ajax@0.1.1" // instead of "ajax": "mycomp:ajax@0.1.1"
}
````

produces `package.json`:
````
...
"jspm": {
  "dependencies": {
    "comp-ajax": "mycomp:ajax@0.1.1", // instead of "ajax": "mycomp:ajax@0.1.1"
  }
}
````

**Comment by unional** [comment]
I know I can do: `jspm i comp-ajax=mycomp:ajax`, but want to see if I can make it bake in the `package.json`

**Comment by guybedford** [comment]
@unional the default name to install into when running `jspm install registry:package-name` is `package-name`. The package.json `name` property is something that is only checked at publish time by npm, and in jspm will have the same behaviour when we introduce publishing workflows.

It might be possible to alter the default above to read the `package.json` name, but I'm not sure if that would be a good idea, as the name in the package.json is supposed to correspond to the name in the registry anyway.
