### ISSUE TITLE
Module X not declared as a dependency at runtime

### ISSUE THREAD

**Issue by yoavniran** [jspm/jspm-cli#1314]
Hi, 
Im getting the Module not declared as a dependency error when Im running my __SFX__ bundled code in the browser.

The error comes from a module of mine that loads other modules dynamically based on configuration thats created at build time.

this is the requiring code: 

``` js
function _createIntegrator(name, intConfig) {
       var integrator = require("jtvw.integrations/" + name + "/" + intConfig.integrator);
        return Promise.resolve(integrator.create(intConfig.config));
}
```

the supporting configuration in config.js:

``` js
System.config({
   //...
     meta: {
          "jtvw.integrations/integrationsProvider":{
			"format": "cjs",
			"deps": ["jtvw.integrations/facebook/fbIntegrator",
				"jtvw.integrations/twitter/twitterIntegrator"]
		},
    },
     map: {
          //...
       "jtvw.integrations": "src/integrations",
         //...
      }
});
```

At dev time with the files open everything works. However with the bundled code, the require call fails as it doesnt recognize the dynamically constructed required module name:

![20151125_102734-screenshot](https://cloud.githubusercontent.com/assets/1102278/11392658/d23622c4-9363-11e5-93e8-e7336091fab1.png)

and the dependency list:

![20151125_102747-screenshot](https://cloud.githubusercontent.com/assets/1102278/11392670/e2ad46f0-9363-11e5-9313-487213d45ce3.png)

Notice that "81" is the module thats supposed to be loaded and it is available in the bundle. 

Is there a way to  make this kind of set up work?
or is there a better way?

The modules need to be dynamically loaded as the list of modules will be different depending on the build.

thanks.

**Comment by yoavniran** [comment]
I was using _System.import()_ instead of _require()_ but in the SFX bundle _System_ isn't available... 

require() works in dev but the SFX bundling converts all dependency names (including those specified in the meta config) into hex values so the code doing the "dynamic" requiring cant predict the name at runtime... :disappointed: 

@guybedford some guidance on this would be greatly appreciated.

**Comment by jackfranklin** [comment]
@yoavniran I'm pretty sure these aren't supported in SFX bundles. You'd need to stick to a regular bundle and include your config + SystemJS in the page too.

**Comment by yoavniran** [comment]
hi @jackfranklin 
If this is completely unsupported that would be bad for me as the project im working on goes on to customers' pages so it must be a SFX bundle and not touch the global object in any way...

The "packages" configuration might help me here, If I build the package at build time but I really wanted to avoid building any kind of code dynamically so was hoping for a more supported solution. 
Something a  long the lines of specifying in the meta config that these are dynamically loaded so keep their full module name in the bundle instead of converting to the hex value.

**Comment by jackfranklin** [comment]
I'm fairly confident that you can't have any dynamic behaviour like this in an SFX build - @guybedford is the authority on this though and the reasons why! You'll need to either generate the code for this based on your config and give jspm a generated file, or import all of the files in src/integrations and then make the `_createIntegrator` function return the one you need.

**Comment by yoavniran** [comment]
thanks @jackfranklin 
thats disappointing. I really was hoping I could get by building the right config at build time and that runtime could cope.
I think its a valid scenario as well (though probably not very common) so wonder whether someone faced it before...?

**Comment by OrKoN** [comment]
@yoavniran why don't use want to use normal bundles?

**Comment by yoavniran** [comment]
hi @OrKoN im not sure I follow. can you elaborate?

**Comment by yoavniran** [comment]
very happy to say I found a solution for this. 
(out of desperation) I dug into the builder code to see whether the module name encoding can be disabled. And what do you know, it can be! using the "_encodeNames_" compile option. (set it to false)
This leaves the original module names in the bundled code (not as short but ok) and all is well again. :smile: 
Turns out there are quite a lot of options there if you look under the hood... 
which begs the question, __is this documented anywhere?__ @jackfranklin @guybedford  ???

thanks.

**Comment by jackfranklin** [comment]
That's a new option that I didn't know existed - a lot of this stuff isn't documented because it's not necessarily set in stone and might change. That said, it sounds like that problem could also solve the jspm-dev-builder issues we've been having around caching and SFX bundles - @guybedford it might be worth documenting?

@yoavniran can you share some code as to how you changed that option?

Thanks!

**Comment by yoavniran** [comment]
hi @jackfranklin 

My build process includes the [grunt-systemjs-builder](https://www.npmjs.com/package/grunt-systemjs-builder) task I wrote.
It allows passing builder init options and compile options.
The gist is that you need to pass to buildStatic() the "encodeNames" prop set to false in the opts parameter. ex:
```js
var builder = new Builder();
builder.bundle("src/app", "app.min.js", {encodeNames: false});
``` 

I really think these options should be documented (adding the "Experimental" disclaimer is perfectly fine) but at least people will know they're there and might be spared the hair pulling one might experience... :cry: 

btw, i updated my previous reply regarding the normalize flag which you might also be relevant for you...

**Comment by yoavniran** [comment]
@jackfranklin turns out the situation is far from ideal... when setting encodeNames to false, the module names are left with ".js" so now my requires dont work (i guess i can add the ".js" to the end of the names so perhaps its not too bad, just annoying.

however, setting normalize to false seems to cause havoc on the bundled code. there is a complete mess with the require() name, for example with minify set to true, the entire code is left with calls to require() while the actual method named is uglified to a one letter name... so I immediately get a "require is not defined" error.

Ill keep playing with it but unfortunately there doesnt seem to be a quick win here for me...

**Comment by guybedford** [comment]
Closing to track in systemjs/builder#417.

**Comment by yoavniran** [comment]
@guybedford please consider this as a documentation enhancement request for the builder (magic) options. Id be happy to open on the systemjs/builder repo if you prefer.

**Comment by guybedford** [comment]
Sure, I've added a note at https://github.com/systemjs/builder/issues/250#issuecomment-152299085.
