### ISSUE TITLE
setting github credentials won't allow me to enter a password or token

### ISSUE THREAD

**Issue by wiredprogrammer** [jspm/jspm-cli#1315]
When using "jspm registry config github" it won't allow me to enter anything when I'm prompted for the token or password.

**Comment by guybedford** [comment]
Thanks for posting. What OS / version of Node are you using here?

**Comment by guybedford** [comment]
Also note that the password field is designed not to show any characters.

**Comment by wiredprogrammer** [comment]
I'm not getting any indication I've typed anything.
I'm on Windows 7 running v0.10.31 of node.
Thanks for the quick response!!

**Comment by wiredprogrammer** [comment]
That node version is probably it.  I thought I updated.

**Comment by wiredprogrammer** [comment]
That fixed it.  Would be nice to have some sort of way of knowing you've typed something in if possible.  Thanks again and sorry for the bother.  I just had to set up a new box and thought I'd already updated the node install.
