### ISSUE TITLE
Allow package overwrites in the jspm API

### ISSUE THREAD

**Issue by sandroboehme** [jspm/jspm-cli#1316]
As fixed in https://github.com/jspm/registry/issues/673 lightbox2@2.8.1 has not officially configured it's artifacts correctly.
When calling
```
./jspm install lightbox2 -o '{  "format": "global", "registry": "jspm","main": "dist/js/lightbox.js",  "dependencies": {    "jquery": "*","css":"*"  }, "shim": {    "dist/js/lightbox": {      "deps": [        "jquery",        "../css/lightbox.css!"],      "exports": "$"    }}}'
```
at the command line it installs correctly.
But it's not clear to me how to pass this overwrite to the server side install call for installing the lightbox2 package. I assume this is currently not possible.

What worked for me is, adding this overwrite
```
"overrides": {
      "github:lokesh/lightbox2@2.8.1": {
        "format": "global",
        "registry": "jspm",
        "main": "dist/js/lightbox.js",
        "dependencies": {
          "jquery": "*",
          "css": "*"
        },
        "shim": {
          "dist/js/lightbox": {
            "deps": [
              "jquery",
              "../css/lightbox.css!"
            ],
            "exports": "$"
          }
        }
      }
    }
  }
```

to the `jspm` property of the `package.json` and calling `jspm.install(true).then(installSuccessful, installUnsuccessful);` at the server to reproduce the install.

Did I overlook something or would you enhance the API?

Thanks for your feedback!

Sandro

**Comment by guybedford** [comment]
With https://github.com/jspm/registry/pull/673, this should no longer be necessary to do custom config at all, so I'm not sure I understand the question?

**Comment by sandroboehme** [comment]
Ok, I understand.

The background is, that I'am working on a sitebuilder that allows one to drop components of other component developers at a page. If these components have dependencies I would like to use the jspm api to install them to the server.

To allow component developers to use packages that have not yet setup for jspm yet it would be great to give them the possibility to define overwrites that I can use in the jspm api to install their package.

This means that the lightbox2 package is really just an example to me and the solution would be for me to be able to pass overwrites as options for the jspm install api for example.

**Comment by guybedford** [comment]
Just including the override in the `package.json` `overrides` hash is enough to ensure that the override is applied for subsequent install runs, which would enable an automated workflow here. Let me know if that helps?

**Comment by guybedford** [comment]
Additionally the jspm API itself allows `jspm.install('jquery', { override: ... })`.

**Comment by sandroboehme** [comment]
It worked like a charm according to your last comment. Thanks a lot @guybedford!
