### ISSUE TITLE
package.json is modified w/ `jspm install`

### ISSUE THREAD

**Issue by typhonrt** [jspm/jspm-cli#1318]
I noticed today that `jspm install` is removing in the `package.json->jspm hash` :
"main": false,
and any 
"files": [] entry. 

In the case that "main" is a string it doesn't remove it only when it is set to boolean->false, but "files" is always being removed presently. It's late here, but reproduction is reliable on latest JSPM release.

Perhaps related or not: #1317

**Comment by guybedford** [comment]
Yes grouping this together with that under the https://github.com/jspm/jspm-cli/issues/428 umbrella issue. These issues are resolved in jspm 0.17.
