### ISSUE TITLE
Consider dependencies in override to imply jspm registry if none set

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#132]

**Comment by trusktr** [comment]
I think there should be a prioritzed fallback mechanism for all cases. For example, if a github package is installed and it has a missing dependency not found on github, then check npm, then bower. If an npm package is installed and a dependency can't be found on npm then check github, then bower. etc.

**Comment by guybedford** [comment]
The only case here we can possible consider is installing npm packages from GitHub, which has been discussed at https://github.com/jspm/github/issues/14. npm packages with GitHub dependencies is not really a thing.

**Comment by trusktr** [comment]
Yeah, I agree, but sometimes package versions from npmjs get unpublished, for whatever add reason, so maybe github would still have it?
