### ISSUE TITLE
Add path mapping to a folder

### ISSUE THREAD

**Issue by JeroenVinke** [jspm/jspm-cli#1322]
As far as I know, Kendo-PRO can be installed in 2 ways:

- using the bower repository (via jspm-git)
- download a ZIP file from the telerik website containing the same files as in the bower repository, and add a path mapping in `config.js` to `kendo.all.min.js`.

This question is about the second option: downloading a ZIP from telerik, and adding this as a path mapping to `config.js`.

I would like to know if it's possible to add a path mapping to a whole folder so that I won't have to add a path mapping to [every file](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/blob/master/sample/config.js#L17-L19)

In the end I would like to be able to `import 'kendo-ui/src/js/kendo.button';` where `kendo-ui` is a folder outside of jspm_packages containing all files of kendo.

I tried to add a path mapping of `"kendo:*": "vendors/kendo/*"`, but I got errors during `jspm install` telling me it is expecting `kendo` to be a registered endpoint, which it is not.

**Comment by JeroenVinke** [comment]
```
"kendo-ui:*": "vendors/*" <-- jspm sees kendo-ui as an endpoint
"kendo-ui/*": "vendors/*" <-- jspm sees kendo-ui as folder mapping
```
using `kendo-ui/*` instead of `kendo-ui:*` fixes my issue :smile:

**Comment by adriatic** [comment]
This is of course logical - but not necessarily easy to deduce :-)
Great thinking

**Comment by guybedford** [comment]
`map` config does folder / package mappings so that the advised way to do this is just via:

```javascript
System.config({
  map: {
    'kendo-ui': 'vendors'
  }
});
```

To allow `import "kendo-ui/moduleA"` etc.

**Comment by guybedford** [comment]
(the examples show map config in this way to encourage such workflows)
