### ISSUE TITLE
.dependencies.json doesn't get updated when dependencies in updated package changes

### ISSUE THREAD

**Issue by chauthai** [jspm/jspm-cli#1324]
A dependency in a package I've installed got removed and as I updated the package via
`jspm install npm:mypackage` the removed dependency kept getting installed.
I removed it manually from the `config.js` and it still kept coming back. 

So I checked out the `.dependencies.json` in the jspm_packages folder and had to remove it there too.

**Comment by guybedford** [comment]
Can you clarify how the dependency was removed? Say it was `npm:mypackage@1.2.3`, was the dependency removed for version `npm:mypackage@1.2.3` or the next version `npm:mypackage@1.2.4`?

**Comment by chauthai** [comment]
The dependency was removed for the same version of the package `npm:mypackage@1.2.3`. We are in early development and are trying out a lot of things and didn't start incrementing our package versions, when dependencies change.

**Comment by guybedford** [comment]
Sure, thanks that makes sense. While npm usually restricts this case jspm is designed to support these sorts of changes so that is a bug.

**Comment by DanielSWolf** [comment]
:+1:
