### ISSUE TITLE
Seemingly correct config file causes the command `jspm -v` to fail

### ISSUE THREAD

**Issue by adriatic** [jspm/jspm-cli#1326]
Running `jspm -v` after editing my `C:\Users\Nikolaj\AppData\Local\.jspm\config` results with
```
λ jspm -v                                                                                    
                                                                                             
err  Unable to read global configuration file.
     Ensure you have read and write access to C:\Users\Nikolaj\AppData\Local\.jspm\config.
```
here is the config file
```
{
  "registry": "jspm",
  "endpoints": {
    "github": {
      "timeouts": {
        "lookups": 60
      },
      "remote": "https://github.jspm.io",
      "auth": "YWRyaWF0aWM6QW5uQXJib3IyMDEz",
      "maxRepoSize": 0,
      "handler": "jspm-github"
    },
    "npm": {
      "timeouts": {
        "lookups": 60
      },
      "handler": "jspm-npm",
      "remote": "https://npm.jspm.io"
    },
    "jspm": {
      "timeouts": {
        "lookups": 60
      },
      "handler": "jspm-registry",
      "remote": "https://registry.jspm.io"
    }
  },
  "defaultRegistry": "jspm",
  "registries": {
    "github": {
      "timeouts": {
        "lookup": 60,
        "build": 120,
        "lookups": 60
      },
      "remote": "https://github.jspm.io",
      "auth": "YWRyaWF0aWM6QmVsbGluZ2hhbTIwMTU=",
      "maxRepoSize": 0,
      "handler": "jspm-github"
    },
    "npm": {
      "timeouts": {
        "lookup": 60,
        "build": 120,
        "lookups": 60
      },
      "handler": "jspm-npm",
      "remote": "https://npm.jspm.io"
    },
    "jspm": {
      "timeouts": {
        "lookup": 60,
        "build": 120,
        "lookups": 60
      },
      "handler": "jspm-registry",
      "remote": "https://registry.jspm.io"
    },
  }
  "defaultTranspiler": "babel",
  "strictSSL": true
}

```

**Comment by jackfranklin** [comment]
It loosk like jspm is unable to read the file, rather than the file being badly formatted. What are the permissions on the file?

**Comment by adriatic** [comment]
I thought of that immediately so I made this screenshot:

![image](https://cloud.githubusercontent.com/assets/2712405/11452900/3d57aaa6-95c5-11e5-9746-45b124483b02.png)

Note: I finally deleted this file (after saving it's content and the above screenshot) realizing that there is not much I could do to address this situation differently. At that time I also un-installed and installed jspm, resulting with a normal situation.

My guess is that by editing this file with Atom editor something happened that confused jspm. 

Most likely none of this is helpful - unless you are aware of similar incidents with other users.

**Comment by guybedford** [comment]
I think the error message is sufficient here to catch this case, but if there is anything else we can do please let me know.

**Comment by adriatic** [comment]
The error message was 
```
err  Unable to read global configuration file.
     Ensure you have read and write access to C:\Users\Nikolaj\AppData\Local\.jspm\config.
```
This is an **incorrect** message since that file had read and write access for any account and the process that failed had administrative rights.

I cannot reproduce it, so the issue have to be put to rest, I just did not want to leave the impression that my error report was bogus :-)

**Comment by TheoMer** [comment]
I am having a similar issue, when running

`jspm install -y 

or

jspm -v
`

Doing so, I get the following error message

`
C:\Users\Theo\Documents\Visual Studio 2015\Projects\skeleton-typescript\node_modules\jspm\lib\global-config.js:58
    throw 'Unable to write global configuration file\n' + e.stack;
    ^
 Unable to write global configuration file
Error: EPERM: operation not permitted, open 'C:\Users\Theo\AppData\Local\.jspm\config'
    at Error (native)
    at Object.fs.openSync (evalmachine.<anonymous>:584:18)
    at Object.fs.writeFileSync (evalmachine.<anonymous>:1224:33)
    at save (C:\Users\Theo\Documents\Visual Studio 2015\Projects\skeleton-typescript\node_modules\jspm\lib\global-config.js:55:8)
    at Object.<anonymous> (C:\Users\Theo\Documents\Visual Studio 2015\Projects\skeleton-typescript\node_modules\jspm\lib\global-config.js:118:1)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
`

How does one resolve this?

**Comment by adriatic** [comment]
I had to do the "drastic" measure in order to fix this - delete all content of `C:\Users\username\AppData\Local\.jspm` folder. Only later I found that the `config` file in this folder (referred to as jspm global configuration file) was ___corrupted___, when I understood the error message telling me that it is write protected.

This was few months ago, so I do not recall all details of how did I rebuild the content of `C:\Users\username\AppData\Local\.jspm` folder - most likely it is regenerated by repetitive use of jspm.

In your situation you may just move the config file somewhere safe and use jspm again

**Comment by guybedford** [comment]
@adriatic a proper file lock was introduced in jspm 0.16.16 to avoid this issue.

**Comment by adriatic** [comment]
Guy, when in God's name do you find the time to respond to such low priority issues  :-)

**Comment by TheoMer** [comment]
@adriatic Are you referring to the config.js file, in root of my project? As there is no config.js file located in C:\Users\Username\AppData\Local\.jspm folder

@guybedford 'a proper file lock was introduced in jspm 0.16.16 to avoid this issue' - In which case, and as I installed jspm around the time when I wrote my initial message here this morning, something is amiss.

**Comment by adriatic** [comment]
@TheoMer I am referring to the file highlighted below:

![image](https://cloud.githubusercontent.com/assets/2712405/12821374/2ba0efa6-cb31-11e5-84d2-eaf2df74de32.png)

**Comment by TheoMer** [comment]
@adriatic @guybedford Yes, that file doesn't exist in my folder.

![jspm](https://cloud.githubusercontent.com/assets/15969262/12821630/15b74a70-cb5c-11e5-9196-c635d2188612.jpg)

**Comment by adriatic** [comment]
Than that is your problem - you need to run `jspm init` to create that file

**Comment by TheoMer** [comment]
@adriatic jspm <any command> throws the above mentioned error.

**Comment by TheoMer** [comment]
@adriatic @guybedford Ok, so jspm@0.16.16 appears to have cut me some slack, on the initial generated errors. But then I'm back to the dreaded github errors, which I've never been able to resolve.

![jspm github error](https://cloud.githubusercontent.com/assets/15969262/12824164/d1a67340-cb67-11e5-87ab-ce5b40f6358c.jpg)


Many thanks for your help, chaps. Think I'm going to leave jspm/aurelia alone, and head back to angular2. Cheers

**Comment by adriatic** [comment]
@TheoMer I am responding to your message
> Many thanks for your help, chaps. Think I'm going to leave jspm/aurelia alone, and head back to angular2. Cheers

I am ex-angular fan, so while I understand your frustration, I do not believe that you should reach the level where Angular is more appealing than Aurelia, as I would not go back there even under the gun.

Your problem has nothing to do with Aurelia and everything to do with your preference for Visual Studio combined with some recent jspm issues caused by transition to next release. Allow me to invite you to one of Aurelia chatrooms - https://gitter.im/adriatic/Aurelia-KendoUI and I am sure that we could solve your problem in no time

**Comment by TheoMer** [comment]
@adriatic Many thanks for your comment. I will take you up on the offer.

Many thanks.

P.S. I was initially using VS a few months back, but have since transitioned to WebStorm 11
