### ISSUE TITLE
"jspm install bootstrap" not working correctly

### ISSUE THREAD

**Issue by cpritchard** [jspm/jspm-cli#1327]
jspm install bootstrap is failing to download all necessary files. My first suspicion was bootstrap itself but maybe there is a change within jspm that could also be causing the trouble.

Please see: https://github.com/twbs/bootstrap/issues/18360
for the issue started specifically on the Bootstrap repo.

**Comment by guybedford** [comment]
Thanks for letting me know. I was working on the jspm 0.17 Bootstrap override today, and inadvertently caused this to break. It should be working again now that I've added https://github.com/jspm/registry/commit/b5076b364f16bebc3fb3c06c22d6dbc9a771978f. Please let me know if that is ok now?

Note that this fragility is resolved in jspm 0.17 by having all overrides checked in locally on install.

**Comment by cpritchard** [comment]
It appears to be working again locally. I'll get it to run on the build server shortly as well.

**Comment by cpritchard** [comment]
Confirmed working on both machines

**Comment by cvrebert** [comment]
@guybedford Would you mind explaining the fix? I'm a tad confused, since there's no `/css` directory in Bootstrap, only `/dist/css`, and `dist` was already in `files` prior to your fix.

**Comment by cvrebert** [comment]
Likewise, I'm unclear on how a fix for `bootstrap@3.3.4.json` supposedly also fixed Bootstrap v3.3.5

**Comment by guybedford** [comment]
@cvrebert for legacy reasons, jspm downloads Bootstrap from the github releases archive file, which doesn't have a dist folder. This behaviour is being removed in jspm 0.17 to just use the direct repo on download, and we'll use the npm version of Bootstrap as the main source instead. Let me know if anything is still unclear at all.

**Comment by cvrebert** [comment]
Okay, just making sure there's nothing that should be changed upstream in Bootstrap.

**Comment by guybedford** [comment]
@cvrebert thanks for checking. In jspm 0.17 some changes will be necessary when we switch to the npm version as the main source. I will likely send a PR along these lines when jspm 0.17 is released in the next month or so if that is ok with you.

**Comment by cvrebert** [comment]
Sounds wonderful. It's great to know that jspm is actively maintained :-)
