### ISSUE TITLE
Bundling should fail when build fails

### ISSUE THREAD

**Issue by peterjuras** [jspm/jspm-cli#1329]
Hi!

I am counting on CI tests to know whether I have messed up my code somehow. This works most of the time, however bundling ignores build failures and just continues without erroring out. This makes travis think that the build was ok, when in fact some errors occured.

I created a [small example](https://github.com/peterjuras/jspm-bundle-issue) where this issue can be reproduced. After an **npm install** the bundling can be kicked of with **npm start**. 

The [TypeScript plugin](https://github.com/frankwallis/plugin-typescript) for jspm allows for a typeCheck: strict setting, which will make the build fail when something is not right. 
While bundling, the plugin manages to print out the errors to the console but the bundling will still continue.

Is this a bug or a feature? @frankwallis any ideas how to solve this?

**Comment by guybedford** [comment]
I'd tried running `jspm bundle src/index.tsx` and got the following error messages in the console as the first output (before the bundle completed successfully):

```
TypeScript file:///Users/guybedford/projects/test/jspm-bundle-issue/src/index.tsx:4:7
TypeScript 'const' declarations must be initialized (TS1155)
TypeScript file:///Users/guybedford/projects/test/jspm-bundle-issue/src/index.tsx:6:11
TypeScript Cannot find name 'a'. (TS2304)
TypeScript file:///Users/guybedford/projects/test/jspm-bundle-issue/src/index.tsx:8:18
TypeScript Cannot find name 'UnknownComponent'. (TS2304)
```

Perhaps @frankwallis can share if these should be build failing errors or not.

**Comment by frankwallis** [comment]
This is an issue with the way plugin-typescript works - the type-checking is asynchronous so as not to hold up the systemjs loader pipeline. When it encounters an error it throws but it is inside an untrapped promise so it does not fail the build.

To fix it I need to hook into an event at the end of the build process and trigger an error there. @guybedford - I think I can do this by hooking into the ```bundle``` method, but when I tried that before I couldn't work out how implement ```bundle``` in the successful situation?

**Comment by guybedford** [comment]
@frankwallis the `bundle` hook should certainly work here for this use case, note that it expects to get an array return value though, so you may need to just return an empty array.

**Comment by frankwallis** [comment]
As of plugin-typescript@2.3.2, type-checking errors in strict mode will now fail the build.

**Comment by guybedford** [comment]
:+1:
