### ISSUE TITLE
Problem with installation on MacOSX El Capitan

### ISSUE THREAD

**Issue by fedojo** [jspm/jspm-cli#1331]
hi,

I have a following problem when Im trying to install JSPM with command: sudo  npm install jspm -g

npm WARN install:ansi-regex ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/jspm/node_modules/ansi-regex' -> '/usr/local/lib/node_modules/jspm/node_modules/ansi-regex'
npm WARN install:ansi-styles ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/jspm/node_modules/ansi-styles' -> '/usr/local/lib/node_modules/jspm/node_modules/ansi-styles'
npm WARN install:camelcase ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/jspm/node_modules/camelcase' -> '/usr/local/lib/node_modules/jspm/node_modules/camelcase'
npm WARN install:dashdash ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/jspm/node_modules/dashdash' -> '/usr/local/lib/node_modules/jspm/node_modules/dashdash'
npm WARN install:combined-stream ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/jspm/node_modules/combined-stream' -> '/usr/local/lib/node_modules/jspm/node_modules/combined-stream'
npm WARN install:escape-string-regexp ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/jspm/node_modules/escape-string-regexp' -> '/usr/local/lib/node_modules/jspm/node_modules/escape-string-regexp'
npm WARN install:es6-template-strings ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/jspm/node_modules/es6-template-strings' -> '/usr/local/lib/node_modules/jspm/node_modules/es6-template-strings'
npm WARN install:extend ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/jspm/node_modules/extend' -> '/usr/local/lib/node_modules/jspm/node_modules/extend'
npm WARN install:flagged-respawn ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/jspm/node_modules/flagged-respawn' -> '/usr/local/lib/node_modules/jspm/node_modules/flagged-respawn'
npm WARN install:graceful-fs ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/jspm/node_modules/fstream/node_modules/graceful-fs' -> '/usr/local/lib/node_modules/jspm/node_modules/fstream/node_modules/graceful-fs'
npm WARN install:commander ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/jspm/node_modules/commander' -> '/usr/local/lib/node_modules/jspm/node_modules/commander'
npm WARN install:boom ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/jspm/node_modules/boom' -> '/usr/local/lib/node_modules/jspm/node_modules/boom'
npm WARN install:http-signature ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/jspm/node_modules/http-signature' -> '/usr/local/lib/node_modules/jspm/node_modules/http-signature'
npm WARN install:inherits ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/jspm/node_modules/inherits' -> '/usr/local/lib/node_modules/jspm/node_modules/inherits'
npm WARN install:generate-object-property ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/jspm/node_modules/generate-object-property' -> '/usr/local/lib/node_modules/jspm/node_modules/generate-object-property'
npm WARN install:is-absolute ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/jspm/node_modules/is-absolute' -> '/usr/local/lib/node_modules/jspm/node_modules/is-absolute'
npm WARN install:jodid25519 ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/jspm/node_modules/jodid25519' -> '/usr/local/lib/node_modules/jspm/node_modules/jodid25519'
npm WARN install:ecc-jsbn ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/jspm/node_modules/ecc-jsbn' -> '/usr/local/lib/node_modules/jspm/node_modules/ecc-jsbn'
npm WARN install:combined-stream ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/jspm/node_modules/jspm-npm/node_modules/combined-stream' -> '/usr/local/lib/node_modules/jspm/node_modules/jspm-npm/node_modules/combined-stream'
npm WARN install:http-signature ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/jspm/node_modules/jspm-npm/node_modules/http-signature' -> '/usr/local/lib/node_modules/jspm/node_modules/jspm-npm/node_modules/http-signature'
npm WARN install:mime-types ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/jspm/node_modules/jspm-npm/node_modules/form-data/node_modules/mime-types' -> '/usr/local/lib/node_modules/jspm/node_modules/jspm-npm/node_modules/form-data/node_modules/mime-types'
npm WARN install:semver ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/jspm/node_modules/jspm-registry/node_modules/semver' -> '/usr/local/lib/node_modules/jspm/node_modules/jspm-registry/node_modules/semver'
npm WARN install:mime-types ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/jspm/node_modules/mime-types' -> '/usr/local/lib/node_modules/jspm/node_modules/mime-types'
npm WARN install:node.extend ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/jspm/node_modules/node.extend' -> '/usr/local/lib/node_modules/jspm/node_modules/node.extend'
npm WARN install:path-is-absolute ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/jspm/node_modules/path-is-absolute' -> '/usr/local/lib/node_modules/jspm/node_modules/path-is-absolute'
npm WARN install:fd-slicer ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/jspm/node_modules/fd-slicer' -> '/usr/local/lib/node_modules/jspm/node_modules/fd-slicer'
npm WARN install:pinkie ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/jspm/node_modules/pinkie' -> '/usr/local/lib/node_modules/jspm/node_modules/pinkie'
npm WARN install:combined-stream ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/jspm/node_modules/request/node_modules/combined-stream' -> '/usr/local/lib/node_modules/jspm/node_modules/request/node_modules/combined-stream'
npm WARN install:mime-types ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/jspm/node_modules/request/node_modules/mime-types' -> '/usr/local/lib/node_modules/jspm/node_modules/request/node_modules/mime-types'
npm WARN install:resolve ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/jspm/node_modules/resolve' -> '/usr/local/lib/node_modules/jspm/node_modules/resolve'
npm WARN install:sntp ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/jspm/node_modules/sntp' -> '/usr/local/lib/node_modules/jspm/node_modules/sntp'
npm WARN install:source-map ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/jspm/node_modules/source-map' -> '/usr/local/lib/node_modules/jspm/node_modules/source-map'
npm WARN install:source-map ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/jspm/node_modules/source-map-support/node_modules/source-map' -> '/usr/local/lib/node_modules/jspm/node_modules/source-map-support/node_modules/source-map'
npm WARN install:supports-color ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/jspm/node_modules/supports-color' -> '/usr/local/lib/node_modules/jspm/node_modules/supports-color'
npm WARN install:source-map ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/jspm/node_modules/uglify-js/node_modules/source-map' -> '/usr/local/lib/node_modules/jspm/node_modules/uglify-js/node_modules/source-map'
npm WARN install:verror ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/jspm/node_modules/verror' -> '/usr/local/lib/node_modules/jspm/node_modules/verror'
npm WARN install:es6-module-loader ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/jspm/node_modules/es6-module-loader' -> '/usr/local/lib/node_modules/jspm/node_modules/es6-module-loader'
npm WARN install:wrappy ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/jspm/node_modules/wrappy' -> '/usr/local/lib/node_modules/jspm/node_modules/wrappy'
npm WARN install:xtend ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/jspm/node_modules/xtend' -> '/usr/local/lib/node_modules/jspm/node_modules/xtend'
ansi-regex@2.0.0 node_modules/jspm/node_modules/ansi-regex -> node_modules/jspm/node_modules/ansi-regex
ansi-styles@2.1.0 node_modules/jspm/node_modules/ansi-styles -> node_modules/jspm/node_modules/ansi-styles
camelcase@1.2.1 node_modules/jspm/node_modules/camelcase -> node_modules/jspm/node_modules/camelcase
dashdash@1.10.1 node_modules/jspm/node_modules/dashdash -> node_modules/jspm/node_modules/dashdash
combined-stream@0.0.7 node_modules/jspm/node_modules/combined-stream -> node_modules/jspm/node_modules/combined-stream
escape-string-regexp@1.0.3 node_modules/jspm/node_modules/escape-string-regexp -> node_modules/jspm/node_modules/escape-string-regexp
es6-template-strings@2.0.0 node_modules/jspm/node_modules/es6-template-strings -> node_modules/jspm/node_modules/es6-template-strings
extend@2.0.1 node_modules/jspm/node_modules/extend -> node_modules/jspm/node_modules/extend
flagged-respawn@0.3.1 node_modules/jspm/node_modules/flagged-respawn -> node_modules/jspm/node_modules/flagged-respawn
graceful-fs@4.1.2 node_modules/jspm/node_modules/fstream/node_modules/graceful-fs -> node_modules/jspm/node_modules/fstream/node_modules/graceful-fs
commander@2.9.0 node_modules/jspm/node_modules/commander -> node_modules/jspm/node_modules/commander
has-ansi@2.0.0 node_modules/jspm/node_modules/has-ansi -> node_modules/jspm/node_modules/has-ansi
boom@2.10.1 node_modules/jspm/node_modules/boom -> node_modules/jspm/node_modules/boom
cryptiles@2.0.5 node_modules/jspm/node_modules/cryptiles -> node_modules/jspm/node_modules/cryptiles
http-signature@0.10.1 node_modules/jspm/node_modules/http-signature -> node_modules/jspm/node_modules/http-signature
inherits@2.0.1 node_modules/jspm/node_modules/inherits -> node_modules/jspm/node_modules/inherits
generate-object-property@1.2.0 node_modules/jspm/node_modules/generate-object-property -> node_modules/jspm/node_modules/generate-object-property
is-absolute@0.1.7 node_modules/jspm/node_modules/is-absolute -> node_modules/jspm/node_modules/is-absolute
jodid25519@1.0.2 node_modules/jspm/node_modules/jodid25519 -> node_modules/jspm/node_modules/jodid25519
ecc-jsbn@0.1.1 node_modules/jspm/node_modules/ecc-jsbn -> node_modules/jspm/node_modules/ecc-jsbn
async@1.5.0 node_modules/jspm/node_modules/request/node_modules/async -> node_modules/jspm/node_modules/jspm-npm/node_modules/async
combined-stream@1.0.5 node_modules/jspm/node_modules/jspm-npm/node_modules/combined-stream -> node_modules/jspm/node_modules/jspm-npm/node_modules/combined-stream
http-signature@0.11.0 node_modules/jspm/node_modules/jspm-npm/node_modules/http-signature -> node_modules/jspm/node_modules/jspm-npm/node_modules/http-signature
mime-types@2.1.7 node_modules/jspm/node_modules/jspm-npm/node_modules/form-data/node_modules/mime-types -> node_modules/jspm/node_modules/jspm-npm/node_modules/form-data/node_modules/mime-types
form-data@1.0.0-rc3 node_modules/jspm/node_modules/jspm-npm/node_modules/form-data -> node_modules/jspm/node_modules/jspm-npm/node_modules/form-data
semver@4.3.6 node_modules/jspm/node_modules/jspm-registry/node_modules/semver -> node_modules/jspm/node_modules/jspm-registry/node_modules/semver
mime-types@2.0.14 node_modules/jspm/node_modules/mime-types -> node_modules/jspm/node_modules/mime-types
form-data@0.2.0 node_modules/jspm/node_modules/form-data -> node_modules/jspm/node_modules/form-data
node.extend@1.0.8 node_modules/jspm/node_modules/node.extend -> node_modules/jspm/node_modules/node.extend
node.flow@1.2.3 node_modules/jspm/node_modules/node.flow -> node_modules/jspm/node_modules/node.flow
path-is-absolute@1.0.0 node_modules/jspm/node_modules/path-is-absolute -> node_modules/jspm/node_modules/path-is-absolute
fd-slicer@1.0.1 node_modules/jspm/node_modules/fd-slicer -> node_modules/jspm/node_modules/fd-slicer
pinkie@2.0.1 node_modules/jspm/node_modules/pinkie -> node_modules/jspm/node_modules/pinkie
pinkie-promise@2.0.0 node_modules/jspm/node_modules/pinkie-promise -> node_modules/jspm/node_modules/pinkie-promise
combined-stream@1.0.5 node_modules/jspm/node_modules/request/node_modules/combined-stream -> node_modules/jspm/node_modules/request/node_modules/combined-stream
mime-types@2.1.7 node_modules/jspm/node_modules/request/node_modules/mime-types -> node_modules/jspm/node_modules/request/node_modules/mime-types
form-data@1.0.0-rc3 node_modules/jspm/node_modules/request/node_modules/form-data -> node_modules/jspm/node_modules/request/node_modules/form-data
resolve@1.1.6 node_modules/jspm/node_modules/resolve -> node_modules/jspm/node_modules/resolve
rechoir@0.6.2 node_modules/jspm/node_modules/rechoir -> node_modules/jspm/node_modules/rechoir
rmdir@1.1.0 node_modules/jspm/node_modules/rmdir -> node_modules/jspm/node_modules/rmdir
sntp@1.0.9 node_modules/jspm/node_modules/sntp -> node_modules/jspm/node_modules/sntp
hawk@3.1.2 node_modules/jspm/node_modules/request/node_modules/hawk -> node_modules/jspm/node_modules/request/node_modules/hawk
hawk@2.3.1 node_modules/jspm/node_modules/hawk -> node_modules/jspm/node_modules/hawk
source-map@0.4.4 node_modules/jspm/node_modules/source-map -> node_modules/jspm/node_modules/source-map
source-map@0.1.32 node_modules/jspm/node_modules/source-map-support/node_modules/source-map -> node_modules/jspm/node_modules/source-map-support/node_modules/source-map
source-map-support@0.2.10 node_modules/jspm/node_modules/source-map-support -> node_modules/jspm/node_modules/source-map-support
bl@0.9.4 node_modules/jspm/node_modules/bl -> node_modules/jspm/node_modules/bl
strip-ansi@3.0.0 node_modules/jspm/node_modules/strip-ansi -> node_modules/jspm/node_modules/strip-ansi
supports-color@2.0.0 node_modules/jspm/node_modules/supports-color -> node_modules/jspm/node_modules/supports-color
chalk@1.1.1 node_modules/jspm/node_modules/chalk -> node_modules/jspm/node_modules/chalk
request@2.53.0 node_modules/jspm/node_modules/jspm-github/node_modules/request -> node_modules/jspm/node_modules/jspm-github/node_modules/request
sshpk@1.7.0 node_modules/jspm/node_modules/sshpk -> node_modules/jspm/node_modules/sshpk
source-map@0.1.34 node_modules/jspm/node_modules/uglify-js/node_modules/source-map -> node_modules/jspm/node_modules/uglify-js/node_modules/source-map
bl@1.0.0 node_modules/jspm/node_modules/request/node_modules/bl -> node_modules/jspm/node_modules/request/node_modules/bl
verror@1.3.6 node_modules/jspm/node_modules/verror -> node_modules/jspm/node_modules/verror
jsprim@1.2.2 node_modules/jspm/node_modules/jsprim -> node_modules/jspm/node_modules/jsprim
http-signature@1.1.0 node_modules/jspm/node_modules/request/node_modules/http-signature -> node_modules/jspm/node_modules/request/node_modules/http-signature
es6-module-loader@0.17.8 node_modules/jspm/node_modules/es6-module-loader -> node_modules/jspm/node_modules/es6-module-loader
systemjs@0.19.6 node_modules/jspm/node_modules/systemjs -> node_modules/jspm/node_modules/systemjs
which@1.2.0 node_modules/jspm/node_modules/which -> node_modules/jspm/node_modules/which
wrappy@1.0.1 node_modules/jspm/node_modules/wrappy -> node_modules/jspm/node_modules/wrappy
once@1.3.3 node_modules/jspm/node_modules/once -> node_modules/jspm/node_modules/once
inflight@1.0.4 node_modules/jspm/node_modules/inflight -> node_modules/jspm/node_modules/inflight
glob@4.3.5 node_modules/jspm/node_modules/traceur/node_modules/glob -> node_modules/jspm/node_modules/traceur/node_modules/glob
traceur@0.0.92 node_modules/jspm/node_modules/traceur -> node_modules/jspm/node_modules/traceur
glob@4.5.3 node_modules/jspm/node_modules/jspm-github/node_modules/glob -> node_modules/jspm/node_modules/jspm-github/node_modules/glob
rimraf@2.3.4 node_modules/jspm/node_modules/jspm-github/node_modules/rimraf -> node_modules/jspm/node_modules/jspm-github/node_modules/rimraf
rimraf@2.4.4 node_modules/jspm/node_modules/rimraf -> node_modules/jspm/node_modules/rimraf
jspm-registry@0.4.0 node_modules/jspm/node_modules/jspm-registry -> node_modules/jspm/node_modules/jspm-registry
fstream@1.0.8 node_modules/jspm/node_modules/fstream -> node_modules/jspm/node_modules/fstream
tar@2.2.1 node_modules/jspm/node_modules/tar -> node_modules/jspm/node_modules/tar
tar@1.0.3 node_modules/jspm/node_modules/jspm-npm/node_modules/tar -> node_modules/jspm/node_modules/jspm-npm/node_modules/tar
xtend@4.0.1 node_modules/jspm/node_modules/xtend -> node_modules/jspm/node_modules/xtend
is-my-json-valid@2.12.3 node_modules/jspm/node_modules/is-my-json-valid -> node_modules/jspm/node_modules/is-my-json-valid
har-validator@2.0.3 node_modules/jspm/node_modules/request/node_modules/har-validator -> node_modules/jspm/node_modules/request/node_modules/har-validator
request@2.67.0 node_modules/jspm/node_modules/request -> node_modules/jspm/node_modules/request
har-validator@1.8.0 node_modules/jspm/node_modules/har-validator -> node_modules/jspm/node_modules/har-validator
request@2.58.0 node_modules/jspm/node_modules/jspm-npm/node_modules/request -> node_modules/jspm/node_modules/jspm-npm/node_modules/request
yauzl@2.3.1 node_modules/jspm/node_modules/yauzl -> node_modules/jspm/node_modules/yauzl
jspm-github@0.13.9 node_modules/jspm/node_modules/jspm-github -> node_modules/jspm/node_modules/jspm-github
/usr/local/lib
└── (empty)

npm WARN ENOENT ENOENT: no such file or directory, open '/usr/local/lib/node_modules/jspm/package.json'
npm WARN ENOENT ENOENT: no such file or directory, open '/usr/local/lib/node_modules/jspm/node_modules/jspm-npm/package.json'
npm ERR! code 1

I will be thankful for any tip how to do it.
Kind regards

**Comment by guybedford** [comment]
This sounds like an issue with your Node / npm setup not jspm. Have you tried reinstalling NodeJS?

**Comment by fedojo** [comment]
works ! :) thanks @guybedford
