### ISSUE TITLE
Bundle-sfx css ordering

### ISSUE THREAD

**Issue by areel** [jspm/jspm-cli#1337]
Hi,

When not bundling I get the following css links injected
```
<script src="jspm_packages/system.js"></script>
<script src="jspm.config.js"></script>
<link type="text/css" rel="stylesheet" href="http://localhost:3000/styles/app.css">
<link type="text/css" rel="stylesheet" href="http://localhost:3000/components/sbGraph/sbGraph.css">
<link type="text/css" rel="stylesheet" href="http://localhost:3000/components/sbEditor/sbEditor.css">
<link type="text/css" rel="stylesheet" href="http://localhost:3000/jspm_packages/npm/codemirror@5.8.0/lib/codemirror.css">
<link type="text/css" rel="stylesheet" href="http://localhost:3000/jspm_packages/npm/codemirror@5.8.0/theme/dracula.css">
<link type="text/css" rel="stylesheet" href="http://localhost:3000/jspm_packages/npm/jspanel@2.5.5/vendor/jquery-ui-1.11.4.complete/jquery-ui.css">
<link type="text/css" rel="stylesheet" href="http://localhost:3000/jspm_packages/npm/jspanel@2.5.5/source/jquery.jspanel.css"></head>
```
which renders correctly.
When I move onto bunding using 
`jspm bundle-sfx  app.js app.bundle.sfx.js` with same code/folder structure/config settings etc

the rendering is incorrect. Looking in the bundled js code I see
```
$__System.register('styles/app.css!github:systemjs/plugin-css@0.1.19', [], false, function() {});
$__System.register('components/sbEditor/sbEditor.css!github:systemjs/plugin-css@0.1.19', [], false, function() {});
$__System.register('npm:codemirror@5.8.0/theme/dracula.css!github:systemjs/plugin-css@0.1.19', [], false, function() {});
$__System.register('npm:codemirror@5.8.0/lib/codemirror.css!github:systemjs/plugin-css@0.1.19', [], false, function() {});
$__System.register('npm:jspanel@2.5.5/source/jquery.jspanel.css!github:systemjs/plugin-css@0.1.19', [], false, function() {});
$__System.register('npm:jspanel@2.5.5/vendor/jquery-ui-1.11.4.complete/jquery-ui.css!github:systemjs/plugin-css@0.1.19', [], false, function() {});
$__System.register('components/sbGraph/sbGraph.css!github:systemjs/plugin-css@0.1.19', [], false, function() {});
```
Note that the different ordering for codemirror and jspanel. When I beautify the css I can see that this is the ordering within the css, and if I manually modify it to be in the order given in the non bundled version, the rendering is back to being correct.

While browsing this issue I have seen comments like "we dont provide guarantees for CSS loading order" over at  https://github.com/systemjs/plugin-css/issues/57 and "yes we should aim to ensure the order is maintained in bundling at https://github.com/systemjs/plugin-css/issues/18. 

I am hoping the latter and that I am missing something obvious, any pointers would be appreciated.

Aidan

**Comment by guybedford** [comment]
What you've read is correct - the order is not currently guaranteed, but will be guaranteed in future.

It is usually best to rely on CSS specificity over CSS ordering.

**Comment by areel** [comment]
Thanks for the clarification.

CSS specificity does get you part of the way, but other situations still require ordering such as 
* customisations of a CSS framework, the customisation needs to be loaded after the said framework.
* 3rd party styling, sometimes you dont have the control you need

Do you have any suggestions for other tooling around CSS bundling that I could use in conjunction with jspm bundle/bundle-sfx in the meantime? 

Closing as issue known and will be addressed in future release.

**Comment by MrAndMrsK** [comment]
Shouldn't this issue be kept open as the manifestation of the known issue until the issue is resolved?  Maybe it gets a milestone tag or something if it's on the roadmap for a future release to keep it organized?

**Comment by dalgard** [comment]
+1

**Comment by damonjentree** [comment]
Has anyone had any luck dictating loading order? Just as @areel mentioned, when using 3rd party frameworks it is ideal to load custom styles last to override global things. 

> customisations of a CSS framework, the customisation needs to be loaded after the said framework.
> 3rd party styling, sometimes you dont have the control you need

Setting css specificity works well when you are at the element/package level but it would be ideal to be able to globally set things like the font.
