### ISSUE TITLE
jspm --version always prints 'Running against local jspm install.'

### ISSUE THREAD

**Issue by amitport** [jspm/jspm-cli#1338]
even when the current library is completely empty, using `v0.6.15`

**Comment by guybedford** [comment]
If you had a `node_modules` folder in your local user folder with jspm installed, that would trigger as a local jspm install. So check that your parent folders don't contain node_modules. Running `jspm init` may help see which folder is the parent too.

**Comment by amitport** [comment]
tried from root folder (no node_modules)- still jspm prints "local". 

`jspm init` does not print anything about the version

**Comment by guybedford** [comment]
Try running a local Node repl with:

```
console.log(require.resolve('jspm'));
```

You can then see where the local jspm is installed.

**Comment by amitport** [comment]
`C:\Users\<my-user-name>\AppData\Roaming\npm\node_modules\jspm\api.js`
(does not look local...)

**Comment by guybedford** [comment]
@amitport is that the same path as the `jspm` bin path? If not then that would be the reason it thinks that this is a local install. I think `where jspm` might work in windows?

**Comment by amitport** [comment]
`where jspm` returns
`C:\Users\<my-user-name>\AppData\Roaming\npm\jspm`

/:

**Comment by OrKoN** [comment]
@amitport @guybedford I see the same behavior: I have installed jspm with `npm i jspm -g` but my global node_modules go to `~/.npm-packages/`:

```
alex@alex:/tmp$ which jspm
/home/alex/.npm-packages/bin/jspm
alex@alex:/tmp$ ls
arangod_kDKZ6F  config-err-FDHr3E  hsperfdata_alex  jna-2996766  npm-10638-8e525d2e  orbit-alex  sni-qt_keepassx_3898-ptGunh  SublimeLinter3-alex  unity_support_test.0
alex@alex:/tmp$ jspm --version
0.16.15
Running against local jspm install.
```

**Comment by guybedford** [comment]
@amitport if your `require.resolve('jspm')` is returning the global jspm install, then you ARE running the global version of jspm. Are you sure you have jspm installed in `node_modules/jspm` of the local project?

@OrKoN that sounds like a separate issue, but thanks for posting.

**Comment by guybedford** [comment]
@OrKoN actually in your case you also don't seem to have a `node_modules/jspm` in the `/tmp` folder.

**Comment by OrKoN** [comment]
I added log messages here:

```
  process.env.jspmConfigPath = env.configPath || '';
  process.env.globalJspm = !env.modulePath;
  console.log(process.env.globalJspm, '-', env.modulePath)
```

outputs `false - /home/alex/.npm-packages/lib/node_modules/jspm/api.js`

**Comment by guybedford** [comment]
Argh, sorry I missed reading the full history on this one, apologies for the confusion I got this the wrong way around.

I've posted https://github.com/js-cli/js-liftoff/issues/60.

**Comment by guybedford** [comment]
@OrKoN in principle `~/.npm-packages` isn't actually in the global lookup path though? Where is that global path configured, in npmrc itself?

**Comment by guybedford** [comment]
(`~/.node_modules` is the one listed in https://nodejs.org/api/modules.html#modules_loading_from_the_global_folders)

**Comment by guybedford** [comment]
@OrKoN I just tested this out again myself here and wasn't able to replicate your case @OrKoN. Are you running jspm 0.16.15? Thanks for the feedback.

**Comment by OrKoN** [comment]
@guybedford I am running jspm 0.16.15. I have the following ~/.npmrc:

```
prefix=/home/alex/.npm-packages
```

and my versions are:

```
npm --version
3.3.5
node --version
v5.1.1
```

This setup is recommended by this guide: https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md

**Comment by OrKoN** [comment]
`NODE_PATH` says for me `/home/alex/.npm-packages/lib/node_modules:/usr/lib/nodejs:/usr/lib/node_modules:/usr/share/javascript`

Accordingly, I have the following in `.bashrc`:

```
NPM_PACKAGES="${HOME}/.npm-packages"
NODE_PATH="$NPM_PACKAGES/lib/node_modules:$NODE_PATH"

PATH="$NPM_PACKAGES/bin:$PATH"
# Unset manpath so we can inherit from /etc/manpath via the `manpath`
# command
unset MANPATH # delete if you already modified MANPATH elsewhere in your config
MANPATH="$NPM_PACKAGES/share/man:$(manpath)"
```

**Comment by guybedford** [comment]
@OrKoN thanks, I tried following those instructions and the guide as well, but `~/.npm-packages/bin/jspm -v` still informs me it is the global install. Perhaps check that your verison of jspm is using the latest version of node-liftoff? I'm sorry I don't have the time right now to spend more than half an hour trying to replicate this.

**Comment by OrKoN** [comment]
@amitport What do you have in NODE_PATH? `echo $NODE_PATH`

**Comment by OrKoN** [comment]
@guybedford I think it's not so important issue to be spending any significant amount of time on it. I think the problem is related to the NODE_PATH - i.e. if a dir is in the NODE_PATH it's considered to be local by https://github.com/substack/node-resolve.

**Comment by amitport** [comment]
I'll check the NODE_PATH on Sunday (I won't have access to the comp with that issue until then)

**Comment by guybedford** [comment]
Let me know if you still need help here at all.

**Comment by amitport** [comment]
not critical, but the issue persist:
NODE_PATH is C:\Users\<username>\AppData\Roaming\npm\node_modules

**Comment by jonschlinkert** [comment]
@amitport just want to clarify that there was no slash between `Users` and `<username>` in `C:\Users<username>\`

is that the actual output, or was it a typo here on the issue?

**Comment by amitport** [comment]
I think it's just a typo (sorry, can't actually check right now since the issue occurred in a computer I won't have access to in the near future)

**Comment by jonschlinkert** [comment]
no worries! just wanted to make sure, since that would have been an obvious clue to something that shouldn't be happening to the path...

**Comment by nlwillia** [comment]
There is a slash.  `C:\Users\<username>\AppData\Roaming\npm\node_modules`  This just bit me as well, and clearing NODE_PATH fixed it.  No idea how that got set...I've had a range of Node versions installed and it could be an artifact or some past cluelessness about how to configure it.
