### ISSUE TITLE
Can't load modules from folder in filesystem above project

### ISSUE THREAD

**Issue by dj-hedgehog** [jspm/jspm-cli#1339]
I'm developing an application which depends on a few other packages I develop myself.
Up until now I published them to the npm registry every time something changed.
I'm streamlining my development workflow and therefore try to link to the packages locally.
So I replaced: `"my-package-es6": "npm:my-package-es6@1.1.2"` with `"my-package-es6": "../my-package/dist/my-package-es6"` in the config.js-file.

In my code I try to import a module from the repository like this `import models from 'my-package/models/Models.js';`. When accessing the page I get a 404

```
import models from 'my-package-es6/models/Models.js';
```
> GET http://localhost:3000/my-package/dist/my-package-es6/models/Models.js 404 (Not Found)

It worked correctly when loaded from the npm-registry. My local webserver is koa just serving everything in `my-app`.

**How can I fix this path problem or what did I do wrong?**

Here's the simplified folder structure:
```
.
├── my-app
│   ├── config.js
│   └── jspm_packages
│       └── npm
└── my-package
    └── dist
        └── my-package-es6
```

**Comment by guybedford** [comment]
The path `../my-package/dist/my-package-es6` is being used from what you say, and the resolution of that should be relative to the current page (since top-level relative requires are page-relative). If the page is already at the top-level then `resolve(baseURI, '../my-package/...')` will return `my-package/...` as it is doing.

But that seems to be the right folder structure anyway from what I can tell? Perhaps it would help to understand what you'd like the correct request to be?

**Comment by dj-hedgehog** [comment]
Sorry, I messed up the folder structure. It actually is:

```
.
├── my-app
│   ├── config.js
│   └── jspm_packages
│       └── npm
└── my-package
    └── dist
        └── my-package-es6
```

I figured there is no correct request I can send like this.
The web server will never be able to resolve it as it is currently because it serve's all static files in `my-app`. `my-package` however is located at the same level.

I either have to serve all package-folders as well or symlink them into jspm_packages. At least that's what I think.

Which workflow would you suggest?

**Comment by guybedford** [comment]
I guess I would include `my-package` in the `my-app` folder above if that is the public folder.

**Comment by guybedford** [comment]
Just let me know if you need further help here.
