### ISSUE TITLE
Installing Materialize results in empty directory

### ISSUE THREAD

**Issue by 32graham** [jspm/jspm-cli#1343]
When I run

```
jspm install github:Dogfalo/materialize
```

I just get an empty folder at `jspm_packages/github/Dogfalo/materialize@0.97.3/`

**Comment by jackfranklin** [comment]
Do you get any warnings or output from jspm? Pasting the output from the console here would be really useful to assist with debugging.

**Comment by 32graham** [comment]
You are right. Looks like it can't find the main entry point. Would that result in an empty folder?

```
Joshs-MacBook-Pro:Cusi.Web.Core josh$ jspm install github:Dogfalo/materialize
     Looking up github:Dogfalo/materialize
     Updating registry cache...
     Downloading github:Dogfalo/materialize@0.97.3
     Looking up github:components/jquery
     Looking up github:systemjs/plugin-css
     Downloading github:systemjs/plugin-css@0.1.20
     Downloading github:components/jquery@2.1.4

warn Main entry point not found for github:Dogfalo/materialize@0.97.3.
     Adjust this property in the package.json or with an override, setting "main": false if this is the intention.

ok   Installed github:systemjs/plugin-css (0.1.20)
ok   Installed github:components/jquery (2.1.4)
ok   Installed Dogfalo/materialize as github:Dogfalo/materialize@^0.97.3 (0.97.3)
     Clearing configuration for github:systemjs/plugin-css@0.1.19
     Clearing configuration for github:components/jquery@2.1.3
     Removing package files for github:components/jquery@2.1.3
     Removing package files for github:systemjs/plugin-css@0.1.19
     Removing package files for github:webix-hub/tracker@3.1.0

     The following existing package versions were altered by install deduping:

       systemjs/plugin-css 0.1.19 -> 0.1.20
       components/jquery 2.1.3 -> 2.1.4

     To keep existing dependencies locked during install, use the --lock option.
ok   Install tree has no forks.

ok   Install complete.
Joshs-MacBook-Pro:Cusi.Web.Core josh$ ls jspm_packages/github/Dogfalo/materialize\@0.97.3/
Joshs-MacBook-Pro:Cusi.Web.Core josh$ 
```

**Comment by jackfranklin** [comment]
Interesting, the package.json of that lib does indeed have a `main` property set. I'll debug further - what version of jspm are you on?

**Comment by jackfranklin** [comment]
If you install in lower case (`github:dogfalo/materialize`) the warning about not being able to find a `main` goes away, but still the installed folder is empty :/

**Comment by guybedford** [comment]
This could be the 0.97.0 override at https://github.com/jspm/registry/blob/master/package-overrides/github/Dogfalo/materialize%400.97.0.json interfering with the 0.97.3 version.

The release archive file at https://github.com/Dogfalo/materialize/releases must have changed structure. I've removed the files override in https://github.com/jspm/registry/commit/08db7a54c71f1f097cc504b2cc2c3530b924ec86 which should resolve the empty folder issue, but unfortunately since the paths don't match the override probably just needs to be recreated with a 0.97.3 version.

**Comment by guybedford** [comment]
I've created the registry issue https://github.com/jspm/registry/issues/680 to track the 0.97.3 override update.

**Comment by guybedford** [comment]
The fix was merged into the registry.
