### ISSUE TITLE
Mix of Babel transpiled and non-transpiled code breaks instanceof Map

### ISSUE THREAD

**Issue by neothemachine** [jspm/jspm-cli#1348]
I have two libraries, one written in ES5 and doesn't need any transpiling, the other is ES6 and gets transpiled. In the ES6 one I have a line `obj instanceof Map` which works fine in ES6 land, but when I get such a Map object from the ES5 library the check breaks. And this is because babel uses a polyfill in the ES6 one. I'm not sure if this is strictly a Babel bug so I thought I start the bug chain here. What I find really strange is that the core-js polyfill is actually used even though the browser has a Map implementation (which the ES5 lib uses). Doesn't make sense to me. Any ideas?

**Comment by guybedford** [comment]
Interesting. Yes I'd also have thought core-js should expose the native `Map` implementation though by default instead of exporting its own implementation. Did you try searching the core-js issues on this one?

I guess the alternative is to turn off the Map polyfill from Babel and assume native support.

**Comment by guybedford** [comment]
Did you manage to make any process here?

**Comment by neothemachine** [comment]
I couldn't find anything in the core-js issues on that, but I filed one just now: https://github.com/zloirock/core-js/issues/147

One more thing: Since jspm uses Babel more or less automatically, who decides which core-js polyfills are applied by Babel? Are there default settings in Babel that manage that? Or does jspm/systemjs set a hardcoded list?

**Comment by guybedford** [comment]
I've actually disabled the polyfilling entirely in the new Babel plugin.

**Comment by neothemachine** [comment]
Good choice, I think this makes most sense.
