### ISSUE TITLE
Installing angular-material from npm switches to github

### ISSUE THREAD

**Issue by xealot** [jspm/jspm-cli#1352]
I have tried to trace why this happens but I cannot.

All of our modules use NPM. When we try to install `npm:angular-material` the dependencies switch to using `github:*`. This sort of breaks angular as the rest of our modules use `npm:angular` and SystemJS ends up including both in the page.

```
$ jspm install npm:angular-material
     Looking up npm:angular-material
     Updating registry cache...
     Looking up github:angular/bower-angular-aria
     Looking up github:angular/bower-angular
     Looking up github:systemjs/plugin-css
     Looking up github:angular/bower-angular-animate
ok   Installed github:systemjs/plugin-css@^0.1.9 (0.1.20)
ok   Installed github:angular/bower-angular-aria@^1.3.15 (1.4.8)
ok   Installed github:angular/bower-angular@^1.3.15 (1.4.8)
ok   Installed github:angular/bower-angular-animate@^1.3.15 (1.4.8)
ok   Installed angular-material as npm:angular-material@^0.11.4 (0.11.4)
ok   Install tree has no forks.

ok   Install complete.
```

Looking at https://github.com/angular/material/blob/master/package.json it doesn't even have any dependencies listed so I'm not even sure where the rest of the installs are coming from.

**Comment by xealot** [comment]
This seems related
https://github.com/jspm/registry/issues/558

However having an override like this is very confusing.
```json
"overrides": {
  "npm:@pkg@0.3.16": {
    "map": {
      "angular": "angular"
   }
}
```

**Comment by guybedford** [comment]
We currently use `github` as the preferred registry for the entire Angular 1 ecosystem due to the fact that Angular 1 used Bower for dependency management traditionally which made this the best match for that.

If installing an Angular 1 project from `npm` yes this gives conflicts due to this not working with the natural ecosystem of dependencies on github.

I would suggest installing from `github` if you can here. If `npm` really is a necessity due to company reasons, then it does mean a harder road of manually updating every override yourselves.

Just let me know if you have any further questions here at all.

**Comment by xealot** [comment]
We can try this, hopefully the rest of the angular stuff we use is ok with it. 

Is the override as specified above the only way to handle this? We tried for quite a while to get `overrides.<package>.dependencies` to work first.

**Comment by guybedford** [comment]
A `dependencies` override should work fine. Note that https://github.com/angular/material doesn't declare any dependencies in its package.json though.

**Comment by xealot** [comment]
We actually thought that at too first, but I think the "compiled" version of that source does have some. Our conclusion was that the repo there is for building the project.

**Comment by guybedford** [comment]
Ah right I see. Note that when overriding dependencies, all the original dependencies have to be manually listed as the override does not merge with the existing dependencies.

**Comment by xealot** [comment]
Gotcha. Thanks for the information. It's appreciated.

**Comment by xealot** [comment]
Quick followup:

We're trying to switch the angular references to use github. However we only use `npm` is almost all of our modules since they either are strictly libraries designed for import or server-side only.

Do we need to run `jspm` for all of these and maintain another set of files?

**Comment by guybedford** [comment]
Do you mean the duplication of `node_modules` and `jspm_packages`? If so then yes it is a necessary duplication for the time being.

**Comment by xealot** [comment]
I meant more the specification in package.json, I don't care about the duplicated files. I'll just throw them in .gitigore anyway.

We have to keep the npm versions because typescript's module system uses "node_modules" style lookups to resolve dependencies. But the `jspm` key in package.json will essentially be nearly duplicated.

**Comment by guybedford** [comment]
Ah right, yes unfortunately dependencies do need to be duplicated to cater to the minor differences between the two. We don't do any merging of overrides for conceptual simplicity.

**Comment by xealot** [comment]
It's all good. Just trying to understand the limits here. I got this mostly working by adding `jspm` to some of our lower level module's `package.json` file, so :+1: there. 

```javascript
  "jspm": {
    "jspmNodeConversion": false,
    "dependencies": {
      "angular": "github:angular/bower-angular@^1.4.8",
      "jquery": "github:components/jquery@^2.1.4"
    }
  }
```

However, I also needed to add `"jspmNodeConversion": false,` which I don't completely understand. But, hey... Progress!

**Comment by guybedford** [comment]
Glad to hear that.

Btw we're renaming that to `"jspmPackage": true` in the next version which hopefully makes it a little more obvious.
