### ISSUE TITLE
Performance of jspm install

### ISSUE THREAD

**Issue by CxRes** [jspm/jspm-cli#1356]
Recently I was trying to install google/material-design-icons and I found that the download consistently failed.  This is a fairly large repo ~60MB and I have a slow connection 1Mbps. 

My hack around this was to git clone and then remove the git folder. It was so effective the first time (despite the repo being larger due to the `.git` folder) that I tried it a few more times under different circumstance (such as running a youtube video or running a cpu intensive operation) but everytime this would succeed. 

Maybe there is something to learn from this?

**Comment by guybedford** [comment]
The github registry used to use cloning (https://github.com/jspm/github/commit/f4009062cf13082522b0a2d6262a2805e31e2d00), but these were too big. It might be possible to do shallow clones, but ideally we can move to not needing to call out to the `git` process at all. We'd certainly need very strong reasons to alter transport at this point.
