### ISSUE TITLE
better default config name

### ISSUE THREAD

**Issue by tcurdt** [jspm/jspm-cli#1358]
`config.js` is awfully generic.

...and I am not seeing how I could just rename it so that `jspm` still finds it.

It would be great if the config name could be specified in the `package.json`.

**Comment by kfix** [comment]
There is a key in packages.json[jspm] that redefines the config's location, but there's no reconfig subcommand for it under `jspm` if you didn't specify a place when you did `jspm init` in the first place..

**Comment by tcurdt** [comment]
Perfect! Exactly what I was looking for:

    {
      "jspm": {
        "configFile": "jspm.config.js",
        "devDependencies": {
          "babel": "npm:babel-core@^5.8.24",
          "babel-runtime": "npm:babel-runtime@^5.8.24",
          "core-js": "npm:core-js@^1.1.4"
        }
      }
    }

I still think the default name should be changed - but I am fine for now :)

Is this documented somewhere and I just missed it?

**Comment by guybedford** [comment]
This is the _config file path_ option listed under https://github.com/jspm/jspm-cli/blob/master/docs/getting-started.md#2-create-a-project.
