### ISSUE TITLE
conditional imports

### ISSUE THREAD

**Issue by tcurdt** [jspm/jspm-cli#1359]
IIUC a setup like this is not supported with `jspm`?

    import { ENV } from '../env'

    if (ENV === 'development') {
      module.exports = require('./root.dev')
    } else {
      module.exports = require('./root.prod')
    }

because that gives `Error: module is not defined`

I found "Extension Conditions"

    import './root.#{ENV|environment}';

are those the only way to go about this with `jspm`?

**Comment by guybedford** [comment]
Yes exactly as requires are statically traced, and this type of conditional structure doesn't work with ES modules, so the conditional interpolation is the way we are handling these sorts of branchings of the dependency tree, allowing build support as well.

**Comment by tcurdt** [comment]
Thanks for the clarification, @guybedford.

Using `require` was [suggested as](https://github.com/gaearon/redux-devtools) a work around.
