### ISSUE TITLE
Migration coffescript + requirejs project to jspm

### ISSUE THREAD

**Issue by Bnaya** [jspm/jspm-cli#1361]
I have project written in coffee with build step and requirejs on top of that.
(the coffee compile is made by grunt task and not requirejs plugin)

The project is also using several requirejs plugins.

I would evaluate if i could plug this code to work with jspm without any/minimal changes .

start with the coffee:
is there a way i can tell systemjs that specific paths needs to be complied as coffee without any plugin annotation?

is there a way to make systemjs respect requirejs pkugins annotation?

hbs!pathtohbs/file/tempalte
tpl!pathtohbs/file/tempalte

Thanks!

**Comment by larryhe** [comment]
I had similar issue of requirejs handlebar plugin. After replacing requirejs plugin with corresponding systemJS plugin (https://github.com/davis/plugin-hbs) and importing template with 'pathtohbs/file/tempalte.hbs!' fixes the issue.

**Comment by guybedford** [comment]
SystemJS can use RequireJS style plugin syntax by setting `pluginFirst: true` in the SystemJS configuration. This is not recommended though as it may break other things so code rewriting is usually preferable.

Plugins can be specified via configuration as described at https://github.com/systemjs/systemjs/blob/master/docs/overview.md#basic-use.

**Comment by Bnaya** [comment]
Thanks for the info!
