### ISSUE TITLE
Tag release ZIP downloaded from Github doesn't contain expected source tree

### ISSUE THREAD

**Issue by theefer** [jspm/jspm-cli#1364]
I've been helping @adamnfish get to the bottom of an error with the github:Dogfalo/materialize package, specifically at version 0.97.0. We saw that @guybedford updated the override recently for 0.97.3, but we can't get either version to work.

Digging further, it seems to be caused by the files JSPM downloads for the package (both 0.97.0 and 0.97.3). When jspm installing that package using the github endpoint, the materialize directory in the jspm_packages only gets 3 directories: js, fonts and sass (plus LICENSE and README.md). These are *not* the files in the tagged git tree. The only release archive that seems to contain exactly the same files are the materialize-src-v0.97.x.zip ZIPs in the Github releases.

Since we know the package used to work and stopped working without us changing anything, we suspect the contents of that ZIP got updated recently, hence broking the JSPM overrides.

Where is JSPM supposed to get the sources from? How does it pick the ZIP to download? Should it pick the "Source code (zip)" that cannot be tampered with? Or let you override which ZIP gets downloaded?

So many questions! :-)

Thanks!

**Comment by guybedford** [comment]
@theefer thanks for asking about this - there is an issue tracking this waiting for someone to pick it up at https://github.com/jspm/registry/issues/680.

Yes exactly the folder structure changed. The reason for this is that we use the GitHub release archive when it is available (although this is being deprecated in jspm 0.17). The release archive published changed structure between the 0.97.2 and 0.97.3 releases resulting in this issue.

Simply adjusting the 0.97.3 override to the new paths references is all that is needed and exactly what is tracking in the registry issue for this.

**Comment by guybedford** [comment]
Note the use of GitHub release archives is deprecated in jspm 0.17 beta.
