### ISSUE TITLE
jspm registry config github authentication fail

### ISSUE THREAD

**Issue by TheoMer** [jspm/jspm-cli#1365]
OS: Windows 10 Pro
jspm: ver. 0.16.15
npm: ver 3.5.2

Running 'jspm registry config github' in a command window, as administrator, generates the following error message:

'Provided GitHub credentials are not authorized'

Is this a known issue, and is there a fix?

**Comment by guybedford** [comment]
There aren't any known bugs in this workflow. I'd suggest checking your credentials.

**Comment by TheoMer** [comment]
@guybedford The credentials I am using work perfectly when entered into github.com, but fail when entered into 'jspm registry config github'. 

I am happy to message you my credentials to test, if you wish?

**Comment by TheoMer** [comment]
![jspm error](https://cloud.githubusercontent.com/assets/15969262/11840451/f10384c2-a3ed-11e5-8fe4-f667e62dc517.jpg)

The attached image shows the error message

**Comment by guybedford** [comment]
The only thing that might affect this is character encoding. Perhaps share the non-standard characters you are using and I can look into this.

The workaround is just to use a token.

**Comment by TheoMer** [comment]
@guybedford Login also fails when using a token.

Can you clarify what you mean by 'non-standard characters'?

**Comment by guybedford** [comment]
If it also fails with a token then it won't be due to character encoding either.

Are you behind some form of proxy there?

**Comment by TheoMer** [comment]
@guybedford No I'm not behind a proxy. Does jspm generate any logs one can view, so as to potentially narrow down what could be happening?

**Comment by apiv** [comment]
If you have two-factor authentication enabled on your github account, your username/password will return unauthorized. Do you have 2FA enabled?

**Comment by TheoMer** [comment]
@apiv Two-factor was on. I switched it off, and my credentials were still not authorised.

**Comment by TheoMer** [comment]
I momentarily received the following error message, as per the attached image, before the messages returned back to 'credentials not authorised'. This message was received after I switched off 2FA, and regenerated a new token.

![jspm error 2](https://cloud.githubusercontent.com/assets/15969262/11850635/7fa89342-a426-11e5-8794-5421a4f00db8.jpg)

**Comment by TheoMer** [comment]
As a further update, I looked at the Security log of my Github account and the folowing error message has been logged against attempted logins from 'jspm registry config github'

user.failed_login

**Comment by guybedford** [comment]
The issue with `getaddrinfo` means your local DNS is not finding `api.github.com`. So it would mean eg `dig api.github.com` would probably also be failing. That is a sign of network issues there.

If you see "invalid response code 403" that means you've tried too many times, and GitHub is blocking further authorization requests.

With two factor disabled, a token or password should definitely work.

If you want to dig deeper to confirm, try reading `~/.jspm/config` and check that the `registries.github.auth` value is coming out when set as Base64 encoding of `user:pass`, or try setting it directly as such.

There's not really much more I can do to help from here since it is purely between the data entry and your local network behaviour.

**Comment by naeemsarfraz** [comment]
@TheoMer did you resolve this issue? I'm seeing the exact same problem. Both approaches (password, personal access token) fail when trying to configure my github login.

**Comment by TheoMer** [comment]
@naeemsarfraz I had many months, after I posted this issue, of back and forth until it was resolved. so much so, that I made notes, which are comprised of the conversations I had which finally resolved the issue for me. Hope it helps:

> Hi - thanks for not giving up on me, I do plan to get you going, despite my slow reaction today. You have Node 5.4.0 (I was worried that you might have too old version which does not seem to be the case.

The mere fact that at some point you did not have that config file where jspm keeps all of its persistent information (this is something that should not be possible) makes me believe that something bad happened and the best way to resolve this is to uninstall node (which will also remove everything related to npm (see http://blog.teamtreehouse.com/install-node-js-npm-windows and scroll down until you see "How to Uninstall Node and NPM".

npm and jspm are tightly interconnected - which is why I am asking you to remove node, which will take down npm - and in theory also jspm. However, once you are done with "How to Uninstall Node and NPM", please check your folder C:\Users\Nikolaj\AppData\Roaming (replace your user name of course) and delete both npm and npm-cachefolders.

When both these folders (npm and npm-cache) are gone, install NodeJS again, which will also bring the npm, start with Aurelia herehttp://aurelia.io/docs.html#/aurelia/framework/1.0.0-beta.1.1.1/doc/article/a-production-setup


In relation to my last jspm install -y error message, that I left on gitter (adriatic/Aurelia-KendoUI)

This looks like a glitch in GitHub - or you have not established your ssh access to Github (https://help.github.com/articles/generating-an-ssh-key/)


Note: So all is working now. Running, jspm registry config github, from C:\Users\Theo, using Cmder, for the first time, worked properly. So jspm is now correctly configured.
