### ISSUE TITLE
node-sass is not installed properly

### ISSUE THREAD

**Issue by poeschko** [jspm/jspm-cli#1367]
I'd like to preprocess SASS using node-sass (which is faster than sass.js) when creating bundles on node (while still using sass.js in the browser). I tried

    jspm install npm:node-sass

but then

    import sass from 'node-sass';

fails:

```
err  Error: The libsass binding was not found in [...]/jspm_packages/npm/node-sass@3.4.2/vendor/darwin-x64-46/binding.node
     This usually happens because your node version has changed.
     Run npm rebuild node-sass to build the binding for your current node version.
```

I've also tried manually copying over the vendor directory from a pure npm install of node-sass, but keep running into other issues.

I guess something goes wrong with that non-JS dependency of node-sass.

Could I import node-sass from its regular npm installation (in node_modules, where it works just fine)?

**Comment by guybedford** [comment]
This is a limitation in jspm, see https://github.com/jspm/jspm-cli/blob/master/docs/nodejs-usage.md. Although this will likely work in jspm 0.17.

**Comment by guybedford** [comment]
This is really about Node binary support in jspm. The place to start tracking this is at https://github.com/systemjs/systemjs/issues/1052.
