### ISSUE TITLE
Cannot override baseURL.

### ISSUE THREAD

**Issue by wawyed** [jspm/jspm-cli#1369]
I'm trying to configure jspm.builder to accept a different baseURL than the one defined in package.json but I get an error from systemjs: "baseURL should only be configured once and must be configured first.". This is caused because the constructor for jspm.builder calls systemjs.config twice on this line:

https://github.com/jspm/jspm-cli/blob/master/lib/bundle.js#L41

I managed to fix the issue by modifying the bundle.js file to merge both configuration objects. Would that be a viable solution?

**Comment by guybedford** [comment]
When using the jspm builder API, you can pass a baseURL as a constructor argument:

```javascript
var Builder = require('jspm').Builder;
var builder = new Builder(customBaseURL);
// ...
```

The above should work in the latest jspm, but let me know if you have any further issues.

**Comment by wawyed** [comment]
This is your constructor:

```
function Builder(_config) {
  config.loadSync();
  SystemJSBuilder.call(this, toFileURL(config.pjson.baseURL));

  var cfg = config.loader.getConfig();

  if (cfg.depCache)
    delete cfg.depCache;
  if (cfg.bundles)
    delete cfg.bundles;
  if (cfg.baseURL)
    delete cfg.baseURL;

  this.config(cfg, true); //First call

  if (typeof _config == 'object')
    this.config(_config, true); //Second call
}
```

As far as I can see, if you pass anything but an object the constructor will ignore the parameter. And if I pass an object ({baseURL: myUrlPath}). SystemJS will error since this.config is called twice and It only allows to configure baseURL on the first call.

My suggestion would be to merge both objects and only do one call to this.config so I can override the baseURL.

Am I missing something?

**Comment by guybedford** [comment]
Ah right sorry, it's been upgraded on the 0.17 branch only - https://github.com/jspm/jspm-cli/blob/0.17/lib/bundle.js#L31.

**Comment by wawyed** [comment]
When will 0.17 be released?

**Comment by guybedford** [comment]
Hopefully before the end of the year.

**Comment by wawyed** [comment]
Thanks, I'll go with my fix for now then, since I can't npm 0.17 yet.

**Comment by chrismagri** [comment]
@guybedford when will 0.17 be released please?

**Comment by guybedford** [comment]
@chrismagri the beta should be released soon.
