### ISSUE TITLE
Can't system.import bundled file

### ISSUE THREAD

**Issue by dj-hedgehog** [jspm/jspm-cli#1370]
I'm doing this in my application

```
System.import('lib/bootstrap.js').then(m => {
   this.socket = m.io("http://localhost:3000");
})
```

This is `bootstrap.js`
```
import io from 'socket.io-client';
export { io };
``` 

I created a bundle via `jspm bundle lib/bootstrap.js outfile.js`.

When I try to `System.import('outfile.js')` the resolved Promise `m` is only an empty Object.
What am I doing wrong here? 

```
System.import('outfile.js').then(m => {
   this.socket = m.io("http://localhost:3000");
})
```

**Comment by guybedford** [comment]
You would need to do effectively:

```javascript
System.import('outfile.js').then(function() {
  System.import('lib/bootstrap.js').then(function(m) {
    this.socket = m.io('http://localhost:3000');
  });
});
```

That is the bundle defines the modules, but isn't the module itself. Alternatively include the bundle file with a script tag in the head of the page after System.js.

See http://jspm.io/docs/production-workflows.html for more info.

**Comment by dj-hedgehog** [comment]
I think I didn't understand you entirely.
Can I get rid of my extra `lib/bootstrap.js` file at all?

**Comment by guybedford** [comment]
The second import will not load the file, it will read the module from the bundle, but the module still needs to be explicitly loaded otherwise it just sits in the module cache, and won't be executed.

**Comment by dj-hedgehog** [comment]
Thanks a lot for the explanation. I am now able to do everything I wanted.
