### ISSUE TITLE
should I use jspm to automatically install and update my third party libraries?

### ISSUE THREAD

**Issue by larryhe** [jspm/jspm-cli#1371]
This is not an issue of jspm. Please let me know if it should not be asked here. 
Recently we are trying to migrate our code base of requireJS and AMD to SystemJS and ES6. My question is should I use JSPM to manage third party libraries. Our code base is huge and we had dozens of third party libraries in use. But I have some concerns/questions about JSPM outlined below. 
1.  from JSPM documentation, Seems that it can only support installing package from github and npm. what if i have some old library that is not hosted in github or npm?
2.  when i do 'jspm install jquery', not only jquery (jquery@2.1.4.js) got installed under jspm_packages/github/components, but also a jquery@2.1.4 folder with below files (<code>README.md             component.json        jquery-migrate.js     jquery.js             jquery.min.map
bower.json            composer.json         jquery-migrate.min.js jquery.min.js         package.json</code>) , why JSPM install those additional files for me? basically we don't need those files and thus do not want put then in version control given that we have so many third party libraries and each one have an additional folder. that will be a lot unneeded files in version control. Is there any way to disable installing unneeded files? 
3.  from JSPM documentation, Seems that you suggest version control config.js. should i also put jspm_packages folder in version control if I want to put all the third party library here? from my prospective, I definitely want to version control all our external libraries.
based on above questions, should I use jspm to automatically install and update external library or I just manually download and update external libary and put them in a different place other than jspm_packages folder. if yes, what's is the best practice you would suggest. Looking forward to your reply. Thanks for your time.

**Comment by Rush** [comment]
> should i also put jspm_packages folder in version control if I want to put all the third party library here?

Since all jspm packages come from either npm or github, they are already versioned  controlled for you. How to link those packages is defined in `package.json` and `config.js` which you do want to keep.

**Comment by larryhe** [comment]
Hi Rush, 
Thanks for your comment. I mean version controlled in our version control system. you do not want to download external libraries on each build. also some of the libraries were touched by our engineers. 

thanks,
-Larry

**Comment by Rush** [comment]
We do download them all on each build. Works well.
