### ISSUE TITLE
cannot open .git/FETCH_HEAD: Permission denied error after running jspm install -y

### ISSUE THREAD

**Issue by TheoMer** [jspm/jspm-cli#1372]
OS: Windows 10 Pro
JSPM: 0.16.19
Git: 2.6.4.windows.1
NPM: 3.5.2

Running jspm install -y

 causes the following error message:

cannot open .git/FETCH_HEAD: Permission denied

as shown in the following image. How do I rectify this issue?

**Comment by TheoMer** [comment]
![jspm error](https://cloud.githubusercontent.com/assets/15969262/11871945/a900602c-a4ca-11e5-9647-45c65e929e97.jpg)

**Comment by guybedford** [comment]
@TheoMer sorry to hear this stuff isn't working easily for you. If you previously ran jspm as an admin when it created the temporary file git repo clones, then run it no longer as admin that would explain the permission issue. Try resetting the permissions of `C:\Users\[username]\AppData\Roaming\.jspm` (it's something like that) or even removing the folder entirely and starting over, or running jspm itself as admin.

**Comment by TheoMer** [comment]
@guybedford Suffice to say, this is the part of learning/setting up new technology that I have no love for.

I uninstalled jspm, both global and local, and reinstalled them both (non admin). I appear to be making headway though, although my issue appears to be an issue of non authentication of github credentials.
I switched firewall off, used tokens, and nothings working. The attached image shows the error message I'm currently receiving. Any ideas?

![current error](https://cloud.githubusercontent.com/assets/15969262/11884135/8b8fd79e-a50f-11e5-9e7f-4b594b0ca1f2.jpg)

**Comment by TheoMer** [comment]
@guybedford Just to add, jspm registry config github just issues an unathorised credentials error message.

**Comment by guybedford** [comment]
Are you running behind a proxy at all?

**Comment by amenadiel** [comment]
I had a problem somewhat like this one (but I'm using Ubuntu 15.10). It turns out I had  the `unsafe-perm` set to true, so when I sudoed  `npm install` the postinstall hook (which runs `jspm install`) was implicitly sudoed.

In the end I had to `chown ubuntu:ubuntu ~/.jspm -R` to become, again, the owner of jspm cached modules.
