### ISSUE TITLE
Persisting configuration through to System

### ISSUE THREAD

**Issue by sberney** [jspm/jspm-cli#1374]
The default `jspm.config.js` file has this format:

```javascript
System.config({
  ...
})
```

Instead of overriding System.config to keep a copy of the configuration (at say `System.originalConfiguration`), it might be nice to be able to modify the configuration file along the lines of (the clearly less beautiful):

```javascript
originalConfiguration = {
  ...
};
System.config(originalConfiguration);
```

However, jspm will delete this every time it is run. I need my configuration again later! It's true, I can reconstruct components of it from System, but it would be nice to be allowed to keep a complete copy somewhere.

**Comment by pocesar** [comment]
maybe it could merge a custom JSON from a file, like in package.json jspm section, `{ merge: ["myconfig.json","myotherconfig.json"] }`

**Comment by guybedford** [comment]
I always liked the idea of `System.config(oldSystem)` being able to work for this kind of thing as a SystemJS feature. Would that be useful here?

**Comment by sberney** [comment]
Yes, and that is nicely elegant. Although it is nice to have an explicit originalConfiguration which allows you to see the intermediary state for debugging purposes, I do not need it right now.

**Comment by guybedford** [comment]
On second thoughts I think a configuration namespace might be better here even. I've created https://github.com/systemjs/systemjs/issues/999 to track this further.
