### ISSUE TITLE
JSX not compiling with Babel

### ISSUE THREAD

**Issue by Zacqary** [jspm/jspm-cli#1375]
I can't get my JSPM project to process my JSX correctly with Babel. It throws `Unexpected token <` errors.

I took all the suggestions I was able to find. My `config.js` has:
```
defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "optional": [
      "runtime",
      "optimisation.modules.system"
    ],
    "blacklist": []
  },
```
and
```
 packages: {
    "app": {
      "defaultExtension": false
    }
  },
```

And as per the Babel docs, I created a `.babelrc` file, which looks like:
```
{
  "presets": ["react"]
}
```

And I ran `jspm install npm:babel-preset-react`.

But it's still not working. Any ideas what's going on?

**Comment by Zacqary** [comment]
So this is confusing: I got it to work by doing `jspm bundle-sfx [canonical source path] [canonical output path]` instead of `jspm bundle-sfx [relative source path] [relative output path]`.

**Comment by guybedford** [comment]
Are you definitely using Babel 5?

**Comment by guybedford** [comment]
(As in the package.json `devDependencies` for jspm?)

**Comment by guybedford** [comment]
Let me know if you still need help here.

**Comment by bhavinkamani** [comment]
I am running into the same issue. I have `Babel 5` installed under devDependencies. 
I am getting following error
```
Uncaught (in promise) Uncaught SyntaxError: Unexpected token <
	Evaluating http://localhost:5000/lib/main.jsx
	Error loading http://localhost:5000/lib/main.jsx
```

My package.json has:
```
 "jspm": {
    "directories": {
      "baseURL": "src"
    },
    "dependencies": {
      "jspm-hot-reloader": "github:capaj/systemjs-hot-reloader@^0.5.1",
      "react": "npm:react@^0.14.6",
      "react-dom": "npm:react-dom@^0.14.6"
    },
    "devDependencies": {
      "babel": "npm:babel-core@^5.8.24",
      "babel-runtime": "npm:babel-runtime@^5.8.24",
      "core-js": "npm:core-js@^1.1.4"
    }
 }
```
My config.js has 
```
System.config({
  baseURL: "/",
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "optional": [
      "runtime",
      "optimisation.modules.system"
    ],
    blacklist: []
  },
  packages: {
    "lib": {
      "defaultExtension": "jsx",
      "meta": {
        "/**/*.js*": {
          "format": "register"
        }
      }
    }
  },
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },

  map: {
    "babel": "npm:babel-core@5.8.34",
    "babel-runtime": "npm:babel-runtime@5.8.34",
    "core-js": "npm:core-js@1.2.6",
    "jspm-hot-reloader": "github:capaj/systemjs-hot-reloader@0.5.1",
    "react": "npm:react@0.14.6",
    "react-dom": "npm:react-dom@0.14.6",
    ........
}
```
I am using typescript which is getting auto compiled into jsx by my editor. My `main.tsx` file has 
```
/// <reference path="../typings/tsd.d.ts" />
import * as React from 'react';
import * as ReactDOM from 'react-dom';

const Site = () => {
  return (
      <div>fsjfdjs</div>
  );
};

ReactDOM.render(<Site/>, document.getElementById('root'));
```
my generated `main.jsx` file that goes to the browser has
```
System.register(['react', 'react-dom'], function(exports_1, __moduleName) {
    "use strict";
    var React, ReactDOM;
    var Site;
    return {
        setters:[
            function (React_1) {
                React = React_1;
            },
            function (ReactDOM_1) {
                ReactDOM = ReactDOM_1;
            }],
        execute: function() {
            Site = function () {
                return (<div>fsjfdjs</div>);
            };
            ReactDOM.render(<Site />, document.getElementById('root'));
        }
    }
});
//# sourceMappingURL=main.jsx.map
```

**Comment by guybedford** [comment]
SystemJS only applies module transpilation to ES module files. Perhaps see if there is a TypeScript file to output as ES6 modules and then run that through Babel/SystemJS rather.

**Comment by bhavinkamani** [comment]
I recompiled my `tsx` file with `es6` as target. My `tsconfig.json` is
```
{
  "compilerOptions": {
    "module": "system",
    "target": "es6",
    "noImplicitAny": true,
    "removeComments": true,
    "preserveConstEnums": true,
    "sourceMap": true,
    "jsx": "preserve",
    "noLib": true
  },
  "exclude": [
    "node_modules",
    "jspm_packages"
  ]
}
```
With this generated `jsx` file is
```
System.register(['react', 'react-dom'], function(exports_1, __moduleName) {
    "use strict";
    var React, ReactDOM;
    var Site;
    return {
        setters:[
            function (React_1) {
                React = React_1;
            },
            function (ReactDOM_1) {
                ReactDOM = ReactDOM_1;
            }],
        execute: function() {
            Site = () => {
                return (<div>fsjfdjs</div>);
            };
            ReactDOM.render(<Site />, document.getElementById('root'));
        }
    }
});
//# sourceMappingURL=main.jsx.map
```
It still gives me the same error. 

Am I missing something here? I am calling my jsx using `System.import('lib/main');` call.

**Comment by frankwallis** [comment]
I think you need to use ```module: 'es6'``` or ```module: 'commonjs'``` in your tsconfig.json file. babel won't accept code out put in system.register format.

**Comment by bhavinkamani** [comment]
Thank you so much. That was the missing piece. Its working fine now. 

`es6` is not documented as an alternative for `module` flag in the typescript [documentation](https://github.com/Microsoft/TypeScript/wiki/Compiler-Options). That sort of misled me. I will raise that issue in the typescript forum.

**Comment by frankwallis** [comment]
yes ```module: 'es6'``` was a new addition in 1.7 I think

**Comment by bhavinkamani** [comment]
You are right. Its mentioned in their [release note](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#support-for---target-es6-with---module). Though the example is a bit contrived.

**Comment by calbertts** [comment]
I'm having the same problem that @Zacqary, I just started a project with JSPM and React, but I'm not able to use JSX, I've been reading a lot of ways to fix it, but everything looks like hacks or workarounds, I would like to find a "right way" to accomplish this.

I have the same configuration that @Zacqary and also, I followed the same steps, additionally I've installed babel-plugin-syntax-jsx and added to the .babelrc file as a plugin but is not still working.

Would be great if this problem is solved and a standard solution is provided, I'm seeing that I'm not the only with this issue, this can be a blocker for the newcomers to JSPM world and want to work with React.

**Comment by mmuriel** [comment]
@calbertts Did you find a solution for this topic?

**Comment by calbertts** [comment]
@mmuriel It was one year ago, I can't remember how I did it, if what you want is to get started with ReactJS, I would recommend NextJS which is very simple and server-side rendered.

**Comment by guybedford** [comment]
@mmuriel try using the Babel plugin along with the react setting - https://github.com/systemjs/plugin-babel#react-jsx.
