### ISSUE TITLE
jspm install of Angular 2 beta error

### ISSUE THREAD

**Issue by robhicks** [jspm/jspm-cli#1376]
I have several projects which use jspm with angular 2 alpha 46.

Now that angular 2 is out in beta, I have tried to update them to the beta release. While angular2 appears to install without problems, attempting to use the installed code results in errors. 

In trying to track down the reason, I have found that the code generated when installing angular 2 using npm is different from the code generated using jspm. For example, I have noticed that the angular2-polyfills.js file is remarkably different.

For example, angular2-polyfills.js, a file which contains all of the polyfills needed by angular 2, is converted to a "cjs" format, and when loaded in the browser results in a "Uncaught ReferenceError: require is not defined" error. According to everything I have read about jspm, this is an error.

**Comment by guybedford** [comment]
You can alter the module format of SystemJS through metadata - 

```javascript
System.config({
  meta: {
    'angular2-polyfills.js': { format: 'global' }
  }
});
```

Something like that should help. But rather than try to get this configured on your own it may be better to use an Angular SystemJS template or ask for pointers there?

**Comment by playground** [comment]
I'm also using JSPM with ng2 alpha 53.  I'm having the same issue when updating to ng2 beta.0.  
It was complaining something Zone is not defined.

When Loading zone.js via script tag before system.js

Uncaught RangeError: Maximum call stack size exceededobj.addEventListener @ zone.js:1005Zone.addEventListener @ core.js:89obj.addEventListener @ zone.js:1014Zone.addEventListener @ core.js:89obj.addEventListener @

**Comment by guybedford** [comment]
Did you make any progress here? It's usually best to stick to a boilerplate on the angular workflows.

**Comment by playground** [comment]
Yes, I did.  One of the component still has an import zone.js.  I guess the script tag zone.js and import were  competing .

**Comment by danielmorlock** [comment]
why is this closed? I still cannot install angular2@beta with jspm

**Comment by playground** [comment]
You will need to load zone.js before angular.  Hopefully this won't be necessary in future release.

**Comment by rubyboy** [comment]
Run this:
```sh
curl "angular2-jspm.surge.sh" | node
```
Then, run "jspm install" and you've got a starter project with Angular 2, JSPM and TypeScript

In the project setup you'll see that zone.js is being imported in main.ts
