### ISSUE TITLE
Support for node-gyp binary builds on npm

### ISSUE THREAD

**Issue by typhonrt** [jspm/jspm-cli#1377]
Hi Guy et al... 

I'm just posting a potential use case that may become possible with `0.17.x`. In particular in my library authoring I'm now attempting to support Node / server usage along with browsers when creating library bundles or direct source inclusion through mapped paths that follow a convention across modules / Github repos imported. I've come across the "browser" package.json issue as mentioned here and am awaiting `0.17.x` for possible better solutions:
https://github.com/jspm/jspm-cli/issues/1049

I have tested with overrides to get around the browser default path. The next issue that I'm having with loading NPM modules for Node usage is that some of them like [websocket](https://www.npmjs.com/package/websocket) in particular require node-gyp to compile native extensions when installing the module. My assumption is that JSPM currently due to the browser focus seemingly ignores this installation step and thus even with the override to load the node / server path things fail due to the native extensions not being compiled / installed. 

So, this is just something I'd like to discuss / make sure it's somewhere on the radar. Maybe there is something I'm missing, but I haven't found any discussion relating to this matter. It's definitely something I'd like to see in the future if possible for library authoring with JSPM / SystemJS.

Thanks!

**Comment by guybedford** [comment]
Yes in 0.17 we support the server / browser use cases fully but node-gyp support will not be included.

The underlying argument in jspm is that installing dependencies should not be a code-executing process from a security perspective, as I should be able to install an insecure browser library without any worry of my system being compromised.

That argument does fall down as soon as you run a build though I know, but I'd like to continue with the idea that running install is not an insecure operation as much as possible.

So for node-gyp, I think Node and npm are also still working out the best workflows for this stuff too and I don't think we should hardcode something into jspm until the Node approach fully settles down. That's just from my brief reading on the topic, so if I'm wrong or anyone knows what the Node plans are here in more detail, please do share.

In an ideal world, surely binaries would be cloud-created on install, and all available on install inside jspm_packages with a different folder for each compliation target? Or is that kind of enumeration too large to expect to precompute? (probably just showing my lack of C and processor knowledge here now!).

**Comment by typhonrt** [comment]
Since I only need to one npm module, websocket, that uses node-gyp I've been trying to map and load the node_modules version directly. I've had success except for the last step which is where the native code is loaded which ends in `.node` instead of `.js`. I've tried various SystemJS paths config parameters and couldn't get just those files to load. 

First here are my map configuration for [node_modules/websocket](https://github.com/typhonjs/typhonjs-core-logging-socket/blob/master/config/config-paths-node.js#L26-L40). This solves loading all of the JS referenced from node_modules/websocket. 

In particular the two points where websocket attempts to load the native files are here:

node_modules/websocket/lib/Validation.js
```
try {
    module.exports = require('../build/Release/validation');
} catch (e) { try {
    module.exports = require('../build/default/validation');
} catch (e) { try {
    module.exports = require('./Validation.fallback');
} catch (e) {
    console.error('validation.node seems not to have been built. Run npm install.');
    throw e;
}}}
```

and node_modules/websocket/lib/BufferUtil.js
```
try {
  module.exports = require('../build/Release/bufferutil');
} catch (e) { try {
  module.exports = require('../build/default/bufferutil');
} catch (e) { try {
  module.exports = require('./BufferUtil.fallback');
} catch (e) {
  console.error('bufferutil.node seems to not have been built. Run npm install.');
  throw e;
}}}
```

There are two issues here. The first is that both require statements for `../build/Release/validation` and `../build/Release/bufferutil` are resolving to `.js` extensions when they are actually `.node`. It's unclear if any SystemJS paths configuration works in the node_modules directory. If so the files are:
node_modules/websocket/build/Release/validation.node
node_modules/websocket/build/Release/bufferutil.node

The second issue is that the require function is assumed to be a SystemJS shimmed version? If a file is not found when it is relative path loading operation then SystemJS errors out and the try / catch block isn't executed. An example of the error:
```
Error: ENOENT: no such file or directory, open '/Volumes/Data/program/web/projects/TyphonJS/repos/typhonjs/typhonjs-core-logging-socket/node_modules/websocket/build/Release/validation.js'
```
Instead of falling through the try/catch block to load other options things fail instead. It should be noted that if one swaps a non-relative path include for testing say `foobar` for the first require which fails then the try / catch block continues to the next require attempt. This won't be a problem of course if the /build/Release file can be loaded.

I've tried many permutations of SystemJS config paths to load the `.node` file in `node_modules/websocket/build/Release/` perhaps I'm missing something. Can you suggest a possible solution as this is the final step to getting websocket to work in the Node environment.

If I comment out the loading of the native files and only attempt to load the fallback versions then everything works when linking my JSPM managed socket / logging and Meteor related repos when working in a Node environment. 

Thanks for any help when you get a chance.

**Comment by guybedford** [comment]
Certainly this should be possible. I've created https://github.com/systemjs/systemjs/issues/1052 to track. Once that is supported the Node conversion layer can handle ensuring these are processed correctly.

That would then just leave the binary generation itself.

In the mean time I would suggest using a wrapper module approach:

websocket-binary-wrapper.js:
```javascript
module.exports = System._nodeRequire(__dirname + 'path/to/binary.node');
```

**Comment by typhonrt** [comment]
Excellent suggestion. I wasn't aware of `_nodeRequire`. The only rub is that `_nodeRequire` doesn't seem to work with relative paths. IE the necessity of having to have `__dirname + <path>`. The only other problem is that indeed Validation.js and BufferUtils.js as described above are internal websocket npm module files and one can't easily replace those files or remap them as they are relatively accessed. For example here is how Validation.js is loaded in WebSocketConnection.js:
`var Validation = require('./Validation').Validation;`

I did however have success using `System._nodeRequire` to load the compiled node resource and successfully get websocket to work using the native resources. But this requires rewriting `Validation.js` and `BufferUtils.js`. 

Very close.. And very exciting. I'll keep tabs on systemjs/systemjs#1052 and test as soon as possible solution is in place.

**Comment by guybedford** [comment]
You can remap local requires with package map config using relative syntax so it is possible to replace the internal requires to the wrapper.

**Comment by typhonrt** [comment]
Thanks for the heads up... I've got a test working and now trying to see if I can get this worked out transparently. For folks that happen on this issue here is the package remapping for the test:
```
   // Remap the internal websocket files to shims which use `System._nodeRequire`.
   packages:
   {
      'node_modules/websocket/lib':
      {
         format: 'cjs',
         map:
         {
            './Validation': '../../../src/websocketValidation.js',
            './BufferUtil': '../../../src/websocketBufferUtil.js'
         }
      }
   }
```

**Comment by guybedford** [comment]
@typhonrt generally it is advisable to always make the package config the base-level of the package:

```javascript
   // Remap the internal websocket files to shims which use `System._nodeRequire`.
   packages:
   {
      'node_modules/websocket':
      {
         format: 'cjs',
         map:
         {
            './lib/Validation': '../../src/websocketValidation.js',
            './lib/BufferUtil': '../../src/websocketBufferUtil.js'
         }
      }
   }
```

Also if your `src` folder is baseURL-relative the above maps can just be `src/websocketValidation.js` etc as package map still runs through the global map.

**Comment by typhonrt** [comment]
Indeed things are baseURL-relative and work without the extra `../../` Well.. I can close this issue as systemjs/systemjs#1052 should track the associated feature for `0.17`. I'm definitely interested in testing things once an RC / release candidate is available.  

Thanks again!
