### ISSUE TITLE
Use case: support test code coverage w/ Istanbul & Mocha & JSPM

### ISSUE THREAD

**Issue by typhonrt** [jspm/jspm-cli#1378]
Greets @guybedford  & @gotwarlost

While this isn't necessarily a direct issue with JSPM / SystemJS presently [Istanbul](https://github.com/gotwarlost/istanbul) doesn't have a hook for supporting code coverage with JSPM tests. This issue is just to provide an opportunity as necessary for Guy & Krishnan to coordinate to make this happen. 

Please see [Istanbul Issue #498](https://github.com/gotwarlost/istanbul/issues/498) tracking this problem.

I have posted a minimal example of an Istanbul, Mocha, JSPM test w/ a vanilla ES6 example here:
https://github.com/typhonjs/istanbul-jspm-coverage-test

Once Istanbul supports code coverage w/ JSPM I'll update the test repo above to show clear examples of how to setup Istanbul, Mocha & JSPM tests including upload to Codecov via Travis CI. Perhaps even put together some PhantomJS or other web test examples to be added to JSPM wiki / how to resources.

Thanks!

**Comment by guybedford** [comment]
I think it may be better to consider a generic SystemJS support over jspm support here. Posted https://github.com/systemjs/systemjs/issues/992.
