### ISSUE TITLE
jspm update fails on linked packages

### ISSUE THREAD

**Issue by sandys** [jspm/jspm-cli#1379]
I installed https://github.com/handsontable/handsontable as a linked package. steps followed were:
1. git checkout handsontable (from github)
2. jspm link jspm:handsontable
3. jspm install --link handsontable (at this point, config.js was updated). JSPM also showed a message "ok   Linked handsontable as jspm:handsontable (0.0.1)"
4. jspm update - this fails saying unable to locate jspm:handsontable.

**Comment by guybedford** [comment]
Thanks, this sounds like a bug.

**Comment by guybedford** [comment]
Resolved in jspm 0.17 beta.
