### ISSUE TITLE
ES6-Promise polyfill

### ISSUE THREAD

**Issue by peteringram0** [jspm/jspm-cli#1380]
How do you use the ES6-Promise polyfill without using require?

Is there a way to load and run this with JSPM ?

https://github.com/jakearchibald/es6-promise

**Comment by guybedford** [comment]
Promise polyfills can't be loaded by SystemJS because it relies on promises itself already.

There is a `system-polyfills.js` file containing a promise and URL polyfill which should be loaded before SystemJS for older browser support.

**Comment by guybedford** [comment]
(Of course you can load a promise polyfill, but it would be rather pointless though)

**Comment by wprater** [comment]
@guybedford I was having a similar issue on IE11, but found that when using `buildStatic` and had an ES6 package that used the `Promise`, it was somehow dependency injected.  However, I have another package `fetch` where this is no the case.  

Are you loading a Promise Polyfill during the build?  And how can I enforce this as a dependency for another package, such as `fetch`?

**Comment by guybedford** [comment]
core-js comes with a Promise polyfill which does get pulled in unnecessarily so that might explain it.

**Comment by aaronmars** [comment]
So, would this core-js polyfill be messing with the one provided by System.js?
According to the comment at the top of system-polyfills.js, I should expect Promise to work in IE8, but when run in a bundle, I'm getting errors in core-js stuff (looks like $.iter-create.js, perhaps?)

**Comment by guybedford** [comment]
@aaronmars yes it can be worth removing the runtime transformer from the `config.js` to avoid these pitfalls. Note that ES module transpilation doesn't support IE8 as the transpilers don't tend to support IE8, although it can be possible to find feature subsets that do.

**Comment by guybedford** [comment]
Just let me know if you have any further questions here.
