### ISSUE TITLE
Error loading sub-module

### ISSUE THREAD

**Issue by omerts** [jspm/jspm-cli#1381]
Hello,

I have a module with  material-ui, as a dependency. Installing the module, also installs material-ui, just fine. The problem is while trying to run, I get the following error:
```
err  Error: ENOENT, open 'some_path\react-gen-wizard\example\jspm_packages\npm\material-ui@0.12.5.js'
         at Error (native)
        Error loading file:///'some_path/react-gen-wizard/example/jspm_packages/npm/material-ui@0.12.5.js as "material-ui" from file:///'some_path/react-gen-wizard/example/jspm_packages/npm/react-gen-wizard@0.0.2/lib/Wizard.react.js
```

It looks like it is trying to load material-ui@0.12.5.js, while this is not the entry point.
I am using version 0.16.9.
As a side note, I have being using material-ui directly, and not as a sub-dependency, with jspm and it worked well.

**Comment by guybedford** [comment]
Does `material-ui` even have a single main entry point? This would be picked up from the package.json file by jspm to know what to load, and if it does not exist, it means that jspm did not find the main entry point file.

**Comment by omerts** [comment]
Using material-ui in JSPM usually works fine. But when it is a dependency of a package I install it fails with the above message.

**Comment by guybedford** [comment]
So when you do `import 'material-ui'` it works fine in your own code?

**Comment by omerts** [comment]
yes, but when using a module which uses material-ui, it gives the above error

**Comment by guybedford** [comment]
How do you load material-ui in your own code?

**Comment by omerts** [comment]
```javascript 
import {Menu, FontIcon} from 'material-ui';
```

**Comment by guybedford** [comment]
And the above doesn't load the file `some_path\react-gen-wizard\example\jspm_packages\npm\material-ui@0.12.5.js` at all? How does it know where the main file is then?

**Comment by omerts** [comment]
The above loads perfect, using a sub-module that uses it the same way doesn't work.

**Comment by guybedford** [comment]
So the file at `some_path\react-gen-wizard\example\jspm_packages\npm\material-ui@0.12.5.js` does exist?

**Comment by omerts** [comment]
Sorry I misunderstood the above question, so you can ignore my previous last answer. Checking now.

**Comment by omerts** [comment]
@guybedford It looks like I was doing something totally wrong, to the point I can't reproduce it now. Sorry for wasting your time, and I greatly appreciate your support.
