### ISSUE TITLE
Can't show a Leaflet Map with jspm

### ISSUE THREAD

**Issue by p4535992** [jspm/jspm-cli#1382]
Hi,I just started using jspm,so then the my issue may be due to my unexperience with jspm, most that has a problem with jspm himself. I just simply try to load and show a leaflet map , i'm using jspm and i succesfully loaded  all the dependency , but the map not show on the browser , my example with the code is here: ![jspm-leaflet-test1](https://github.com/p4535992/repositoryForTest/tree/master/jspm-leaflet-test1).

ty in advance for any help.

**Comment by guybedford** [comment]
Did you try `import leaflet from 'leaflet'; console.log(leaflet)`? Does that define `leaflet` correctly?

**Comment by p4535992** [comment]
Sorry for the delay, the leaflet module seems loaded correctly.
Here i show you the output console i get:
```
1  
2
L:[object Object]
leaflet:[object Object]
is this thing on?
done all
2.5 
```
Here my **main.js**:
```
import leaflet from 'leaflet';
console.log('L:'+L);
console.log('leaflet:'+leaflet);
//import '../jspm_packages/npm/leaflet@0.7.7/dist/leaflet.css!';
import './filelayer/leaflet.filelayer.js';

console.log('is this thing on?');
var osm = L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
    attribution: 'Map data &copy; 2013 OpenStreetMap contributors'
});
//var map = L.map('map').fitWorld().addLayer(osm);
var map = new L.Map("map", {center: [35.78, -78.68], zoom: 13});
map.addLayer(osm);

console.log('done all');
```
Here my **index.html**
```
<body>
<script src="jspm_packages/system.js"></script>
<script src="config.js"></script>
    <script>
        console.log(1);
        try {
            System.import('./lib/main.js').then(function(){
                console.log(2.5);
            }).catch(function(err) {
                console.log('Error: ', err.stack);
            });
        }catch(e){
            console.error(e.message);
        }
        console.log(2);
    </script>
    <div id="map"></div>
</body>
```
Note i load the CSS of leaflet with a static resource:
```
  <link rel="stylesheet" href="jspm_packages/npm/leaflet@0.7.7/dist/leaflet.css">
```
but i get always the blank page on chrome.

**Comment by guybedford** [comment]
Sure, if leaflet is importing ok, but not behaving correctly, I'd suggest trying to whittle this down to the simplest possible example of how Leaflet is not working. Since I don't work with leaflet it is difficult to debug that code otherwise.

**Comment by p4535992** [comment]
K, i solved, but i'm not really sure about the cause of the problem. For some reason the map of leaflet is printed with a ```height = 0;```
So to solved this little issue i just set the css, with this little piece of code: 
```javascript
   #map {
            height: 100vh;
        }
```
I will try to found out if the problem is on the jspm or leaflet side.
I close this ticket because my problem is in effect solved.
