### ISSUE TITLE
bundle-sfx wont exclude vendor package

### ISSUE THREAD

**Issue by ludbek** [jspm/jspm-cli#1383]
I have following files
```javascript
// app/main.js

import m from 'mithril';

console.log('loaded mithril');
```

I wish to bundle `app/main.js` and exclude `mithril`. So I tried following command -

`jspm bundle-sfx app/main.js - mithril app.js`

But `jspm` does not create app.js. It silently exists.

**Comment by peteruithoven** [comment]
Have you tried:
```
jspm bundle-sfx 'app/main.js - mithril' app.js
```
?
(Not that it's good that it silently fails)

**Comment by guybedford** [comment]
Yes any silent exit can be considered a bug. Any chance of sharing a test repo to look into this further?

**Comment by radius** [comment]
I'm having this same issue. Is there a fix or workaround? Thx

**Comment by guybedford** [comment]
@radius perhaps try setting `rollup: false` in your build options and see if that helps?

**Comment by silver2k** [comment]
I didn't think this was supported - I'm also struggling to create a SFX bundle that excludes jquery & angular and just shims in the globals. Maybe I should just be creating regular bundles but I can't work out how to group them (vendor vs our stuff) without editing the build script to + & - things.

**Comment by guybedford** [comment]
@silver2k `+` and `-` is exactly the way to do it.

**Comment by silver2k** [comment]
Sorry - I was going by this https://github.com/jspm/jspm-cli/issues/144 which implied that shims were the way to go, and - wasn't in for bundleSFX. But that issue is kinda old. In which case I'm getting the same silent fail. I gave `rollup:false` a go, but nothing changed - although I'm not 100% sure I set it in the right place

**Comment by radius** [comment]
yeah, not sure about the rollup thing either. Searching for it on both jspm-cli and systemjs repos yielded no fruit.

@silver2k my solution to this (I have angular and other libs loaded in another bundle earlier in my page) was to create a file shims/angular.js with the following inside it:
```
module.exports = window.angular;
```

and then in my jspm config:
```
map: {
"angular": "shims/angular.js",
"angular-animate": "shims/noop.js",
...
}
```

The noop.js file simply looks like this:
```
module.exports = {};
```

I'm sure there's a better way, and I'd love to know what that way is.
