### ISSUE TITLE
What does `Use jspm dl-loader --latest` mean/do?

### ISSUE THREAD

**Issue by MrAndMrsK** [jspm/jspm-cli#1384]
I'm trying to force update of `core-js` from `1.2.6` to `2.0.0` (in this example) but jspm seems to refuse to do it.

If I `jspm uninstall core-js` and then `jspm install core-js`:

```text
...
ok   Installed core-js as npm:core-js@^2.0.0 (2.0.0)
     Installed Forks

                                  npm:core-js 1.2.6 2.0.0

     To inspect individual package constraints, use jspm inspect registry:name.


warn core-js@2.0.0 is unsupported for this version of jspm. Use jspm dl-loader --latest to update.
```

I don't know what that means but OK, so I run `jspm dl-loader --latest` but it does bad:

```text
...
     Using loader versions:
       systemjs@0.19.9
     Looking up npm:babel-core
     Looking up npm:babel-runtime
     Looking up npm:core-js
     Updating registry cache...
ok   Up to date - babel as npm:babel-core@^5.8.24 (5.8.34)
     Looking up github:jspm/nodelibs-fs
     Looking up github:systemjs/plugin-json
     Looking up github:jspm/nodelibs-path
     Looking up github:jspm/nodelibs-process
     Looking up npm:path-browserify
     Looking up npm:process
     Looking up github:jspm/nodelibs-assert
     Looking up npm:assert
     Looking up npm:util
     Looking up npm:inherits
     Looking up github:jspm/nodelibs-util
ok   Up to date - core-js as npm:core-js@^1.1.4 (1.2.6)
ok   Up to date - babel-runtime as npm:babel-runtime@^5.8.24 (5.8.34)
     Clearing configuration for npm:core-js@2.0.0
     Removing package files for npm:core-js@2.0.0
ok   Loader files downloaded successfully
```

I even tried upgrading jspm itself with `npm update jspm` (don't even know if that's right) but anyway I have `jspm@0.16.19` installed which seems to be the latest.

Clearly I'm missing something, so I'm wishing that jspm had a better explanation for this.  `jspm dl-loader --latest` does the wrong thing and even if it didn't I the suggestions seems to imply that jspm will be updated to a version that supports the library (but why doesn't it already?) but command output doesn't seem to do any permanent compatibility correction that I expected.  

And in the meantime, if someone could explain it to me I'd appreciate it.

**Comment by guybedford** [comment]
Sure, to explain:

* `jspm dl-loader` - download the loader files, if already downloaded don't upgrade them
* `jspm dl-loader --latest` - download the loader files to the latest semver range supported by this version of jspm
* `jspm dl-loader --edge` - download SystemJS to the current master unstable version. CoreJS etc will still be on their stable range paths though.

The message `warn core-js@2.0.0 is unsupported for this version of jspm. Use jspm dl-loader --latest to update.` indicates exactly that core-js 2 is not supported for this version of jspm.

To install core-js 2, simply ignore that warning, and change your config.js and package.json versions of core-js to the 2.0.0 version you want.

**Comment by guybedford** [comment]
This has been added to the cli command notes in 0.17.
