### ISSUE TITLE
installs are hanging on the look up

### ISSUE THREAD

**Issue by mgenev** [jspm/jspm-cli#1385]
I copied this project:
https://github.com/lalitkapoor/systemjs-es6-react-boilerplate

and when I do the jspm install it hangs at places like this:
```
jspm install

     Updating registry cache...
     Looking up npm:react

```

```
Looking up npm:react-tools
```

When I change to Node 0.12 it goes through fine...

**Comment by guybedford** [comment]
Which version of Node specifically is it hanging on then here? Would be good to look into this if it is specifically that causing the issue.
