### ISSUE TITLE
jspm 0.16.15 last known good version to work with angular

### ISSUE THREAD

**Issue by ssljivic** [jspm/jspm-cli#1386]
JSPM 0.16.15 worked fine with my angular application.

However, when I try any later version up to 0.15.19, Angular application is not working when **self executing bundle** is created.

The error I am getting in browser is **Uncaught ReferenceError: angular is not defined**.

**Comment by ssljivic** [comment]
JSPM relevant config:

```
System.config({
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "optional": [
      "runtime",
      "optimisation.modules.system"
    ]
  },
  paths: {
    "github:*": "lib/github/*",
    "npm:*": "lib/npm/*"
  },

  map: {
    "angular": "github:angular/bower-angular@1.4.8",
...
```

And Babel is version 5.8.34.

Btw, no error is reported during the build process.

**Comment by ssljivic** [comment]
This is related to angular-nicescroll angular directive. It is missing dependencies definition. Pull request created for registry project: https://github.com/jspm/registry/pull/698

**Comment by guybedford** [comment]
Nicely done for tracking this down!
