### ISSUE TITLE
Import fails for npm package - file not found

### ISSUE THREAD

**Issue by johnsoftek** [jspm/jspm-cli#1387]
> This issue was originally raised against the jade plugin: johnsoftek/plugin-jade#11

Recently, after installing plugin-jade with no error messages, an attempt to load a .jade file results in a 404 error, file not found, for url http://localhost:8080/jspm_packages/npm/jade@1.11.0.js.

In the past, `jspm install jade` would create a directory, jade@1.11.0, and a file, jade@1.11.0.js, in directory jspm_packages/npm. The file is no longer created during installation.

The error may be related to commit 7089f781de7b14781a85daf19528d6bfdc9b2536 for issue #1291.
When these two lines are removed from lib/package.js, the former behaviour is restored:
 ```javascript
# lines 790, 791
if (exists)
   return exists;
```

The error seems to occur when the ```main``` entry in ```package.json``` is a directory, not a file.

**Comment by guybedford** [comment]
Thanks, fixed in https://github.com/jspm/jspm-cli/commit/df48f49dfb4dff76a0eed4cf27536900fc26b622.

**Comment by guybedford** [comment]
Released in 0.16.20.
