### ISSUE TITLE
Global JQuery object

### ISSUE THREAD

**Issue by arfmann** [jspm/jspm-cli#1388]
I have a project where I'm having to use a custom framework which puts JQuery on the global object (`window.jQuery`, `window.$`). The project also uses a number of additional JQuery plugins, which JSPM installs as having dependencies on JQuery. 

Oddly, some of these seem to work, and some don't. When they don't, I get '$.xxx is not a function' errors which suggests to me that some plugins are being added to the wrong JQuery object. Is there any way I can configure JSPM/SystemJS such that whenever any module asks for 'jquery', it is given the global object rather than trying to re-import JQuery?

I hope this makes sense!

**Comment by evanplaice** [comment]
This sounds similar to #431

**Comment by jamiewinder** [comment]
@evanplaice no, I don't think so...?

**Comment by guybedford** [comment]
The first check to do here would be to ensure you are only running one version of jQuery. When running `jspm inspect -f` does it show any forks of jquery?

**Comment by arfmann** [comment]
No, no forks. The version in the framework is 2.1.4, as is the one pulled from NPM. I think the problem is just that I'm adding JQuery into the global context in the standard way, using a `<script>` tag, and most other libraries are doing the equivalent of `require('jquery')` which will presumably load another instance of JQuery?

**Comment by arfmann** [comment]
My current workaround for this, which might help clarify what I'm trying to do, is to change the jquery@2.1.4.js created by JSPM to:
```javascript
define([], function() {
  return window.jQuery;
});
```
It does the trick, but it's difficult to manage (jspm_packages isn't under source control) and seems hacky. Presumably there is a better way to do this?

**Comment by guybedford** [comment]
@arfmann the ideal way to do this is to replace the maps of `jquery` in the config.js file to `./local/jquery.js` with your wrapper. But I believe there is a bug with doing these custom maps in the current version, which will be going away in jspm 0.17, so perhaps try this when the alpha is out.

**Comment by sujesharukil** [comment]
Just found out that this is the issue with handsontable being setup as a jQuery plugin. This issue was reported here https://github.com/jspm/registry/issues/697 .. this was closed, but it is still a problem.

**Comment by arfmann** [comment]
@guybedford - Thanks Guy, that seems to have worked. So I have:
```
map: {
    "github:CodeSeven/toastr@2.1.2": {
      "jquery": "local/jquery"
    },
    etc.
}
```
Where local/jquery exists relative to the baseURL. 

I still have the remaining problem that I can't add these as package overrides in my package.json file. If I try to do:
```
"overrides": {
  "github:CodeSeven/toastr@2.1.2": {
    "dependencies": {
      "jquery": "local/jquery"
    }
  }
}
```
and then `jspm install` again 

Then I get errors during the 'Downloading' phase:
```
warn TypeError: Path must be a string. Received undefined
         at assertPath (path.js:8:11)
         at Object.win32.resolve (path.js:130:5)
         at Package.getPath (C:\Projects\Atlas\Atlas\node_modules\jspm\lib\config\package-name.js:82:15)
         at Object.exports.download (C:\Projects\Atlas\Atlas\node_modules\jspm\lib\package.js:430:25)
         at C:\Projects\Atlas\Atlas\node_modules\jspm\lib\install.js:321:18
         at lib$rsvp$$internal$$tryCatch (C:\Projects\Atlas\Atlas\node_modules\rsvp\dist\rsvp.js:493:16)
         at lib$rsvp$$internal$$invokeCallback (C:\Projects\Atlas\Atlas\node_modules\rsvp\dist\rsvp.js:505:17)
         at C:\Projects\Atlas\Atlas\node_modules\rsvp\dist\rsvp.js:1001:13
         at lib$rsvp$asap$$flush (C:\Projects\Atlas\Atlas\node_modules\rsvp\dist\rsvp.js:1198:9)
         at nextTickCallbackWith0Args (node.js:456:9)
         at process._tickCallback (node.js:385:13)
```
Is this the bug you were referring to?

**Comment by guybedford** [comment]
@arfmann yes exactly. I believe this works a little better in the upcoming 0.17.
