### ISSUE TITLE
Loading wrong transpiler

### ISSUE THREAD

**Issue by j3ddesign** [jspm/jspm-cli#1389]
I was just doing a quick test script to check out jspm. However when I got to importing a module within app/main.js jspm tried loading Traceur instead of Babel (which I set during init).

I have confirmed in config.js that babel is the selected transpiler.
``` 
  transpiler: "babel",
  babelOptions: {
    "optional": [
      "runtime",
      "optimisation.modules.system"
    ]
  },
```

The errors I get are
```
GET http://localhost/traceur 404 (Not Found)
Uncaught (in promise) Error: XHR error (404 Not Found) loading http://localhost/traceur (...)
```

This is the contents of my app/main.js
```
import 'fetch';
console.log("Hello World");
```
(fetch is in relation to `jspm install fetch=npm:whatwg-fetch`)

Any help would be magnificent, thanks!

EDIT: 
Jspm version: `"^0.16.19"`

**Comment by guybedford** [comment]
Did you definitely include the `config.js` file with a script tag in the page after including `system.js`?

**Comment by j3ddesign** [comment]
Well now I feel stupid. 
Nope, I failed gloriously.

thanks! :)

**Comment by guybedford** [comment]
Sure, always happy when my job is easier!
