### ISSUE TITLE
Documentation: What conditions cause buildStatic to include System in bundles?

### ISSUE THREAD

**Issue by MeoMix** [jspm/jspm-cli#1391]
Hey,

I'm still playing around heavily with https://github.com/geelen/jspm-loader-css. One snag I've encountered is that previously I was able to call `buildStatic` with `runtime: false`, but, with the introduction of geelen's css plugin, I now have a dependency on it at runtime in production.

I'm working on understanding exactly why this is happening, but it'd be awesome if there was a list of common reasons why this happens rather than having to play whack-a-mole with code.

**Comment by MeoMix** [comment]
Figured out that it's because `fetch` is returning `export default ${JSON.stringify(exportTokens)}` which is causing System to be needed. Unsure how to resolve this just yet.

**Comment by guybedford** [comment]
Do you mean the transpiler runtime is being pulled in here which you don't want? You are using Babel I assume?

**Comment by guybedford** [comment]
(And yes it does turn into a whack-a-mole, but that is the nature of transpilation unfortunately, working on some more predictable workflows in the 0.17 branch, but it's hard to coerce babel).

**Comment by MeoMix** [comment]
Ended up resolving it by replacing the above code with `module.exports =` instead of `exports default` which makes sense. Just use ES5 instead and no System is needed, but was still a pita to track down from having no clue. All good for now.
