### ISSUE TITLE
JSPM Offline package cache workflow

### ISSUE THREAD

**Issue by ErikGrijzen** [jspm/jspm-cli#1393]
I searched already similar issues here in the repository, but i'm not really satisfied with the answers, so that's why I created a new issue.

Is it possible to do some sort of offline build straight from the **jspm_packages** cache? I expected this to work exactly as NPM to be honest, but it doesn't.

How I ideally want it to work is:

---
**jspm install** (without a jspm_packages cache folder)
* Does an install of all packages with downloads, updates and lookups (requires an internet connection).

**jspm install** (with a jspm_packages cache folder)
* Does an install of all packages directly from the cache (requires **no** internet connection).

---
OR

---
**jspm install** or **jspm install --offline** (without a jspm_packages cache folder)
* Does an install of all packages with downloads, updates and lookups (requires an internet connection).

**jspm install --offline** (with a jspm_packages cache folder)
* Does an install of all packages directly from the cache (requires **no** internet connection).

---

This also solves directly the problem with the Github rate limit for CI systems.

Is this something that's already possible? Did I miss something? 

Thanks in advance!

**Comment by guybedford** [comment]
Sure, I've just reopened https://github.com/jspm/jspm-cli/issues/126.

Note that in jspm 0.17 the CI limiting issues go away as well.
