### ISSUE TITLE
jspm bundle does not expose __moduleName

### ISSUE THREAD

**Issue by zbyte64** [jspm/jspm-cli#1395]
I am using `__moduleName` to dynamically import certain modules. This works up until I run bundled code produced with `jspm bundle`

In my code:

```
export default function(appConfig) {
  return Promise.all(_.map(appConfig, (modulePath, baseUrl) => {
    return System.import(modulePath, __moduleName).then(mod => mod.default(baseUrl));
  }))
}
```

When the browser goes to load the bundle it fails saying: `Uncaught (in promise) Error: __moduleName is not defined`

**Comment by guybedford** [comment]
Yes this is currently being settled in the transpiler implementations currently. Which transpiler are you using here?

**Comment by zbyte64** [comment]
babel 5.8.34

**Comment by guybedford** [comment]
Sure, this support is tracking at PR https://github.com/babel/babel/pull/3166.

**Comment by guybedford** [comment]
I believe this is working now.
