### ISSUE TITLE
Forcing package folder

### ISSUE THREAD

**Issue by amenadiel** [jspm/jspm-cli#1396]
I'm moving from RequireJS to JSPM/SystemJS, and I've had relative success moving one module at a time, for which the only duplicated effort has been to replicate any changes to `requirejs.config` to the corresponding setting in `SystemJS.config` and vice-versa.

With regards to this, I wish it was possible to force `lodash` (for example) to install to  `jspm_packages/npm/lodash/` instead of `jspm_packages/npm/lodash@3.10.1` so I won't need to update the folder suffix in `requirejs.config`.

Do you think that an approach like

```js
"overrides": {
      "lodash": {
        "install_folder": "lodash"
      }
    }
```

could be possible?

**Comment by guybedford** [comment]
No this is not possible in jspm. You could always use SystemJS natively with npm if you want that sort of structure.

**Comment by amenadiel** [comment]
I guess I could deploy a named branch like

```sh
jspm install package@branch
```

Something like capistrano's `current` which was a symlink to the newest tag.

**Comment by guybedford** [comment]
That could work, although this issue may apply then - https://github.com/jspm/jspm-cli/issues/1394, which is effectively a bug.

**Comment by amenadiel** [comment]
Oh, I haven't considered that one. And yes, it makes perfect sense that if you already jspm-installed "master" it will keep it as unchanged, and install from caché during deploy tasks. 

Then my second best plan would be to run a task after jspm install, that parsed `package.json` jspm's dependencies to create RequireJS friendly symlinks to their real folders.

...or I could man up and just port my whole project to jspm.

**Comment by guybedford** [comment]
Sure, closing this to track at the other issue, but let me know know if you have any questions further.
