### ISSUE TITLE
"Pin" systemjs version number

### ISSUE THREAD

**Issue by NervosaX** [jspm/jspm-cli#1397]
Currently building an application feels a little wild west, due to errors sometimes cropping up in a jspm dl-loader call. There's been many more than one time where our build has suddenly stopped working, and it was because of an update to system JS. I feel that it should be possible to set what version of systemjs you're expecting in the config file so that updating to a new version of systemjs is a deliberate action. 

It would be nice if `jspm install` checked what version of systemjs is being expected, and upgrading or even downgrading to match it.

Essentially it's just very very hard to keep an automated build and a dev build at the right system js version. Any ideas on how to combat this?

**Comment by guybedford** [comment]
Are you running the latest jspm? jspm does pin the SystemJS version exactly, and should still be pinning to 0.19.9. `jspm dl-loader --latest` removes the pin.

**Comment by NervosaX** [comment]
Okay, so specific reason is because of a break on 0.19.10 that is failing our application. We need to step it back to a version that works again - but I only have --edge and --latest to work with. How can that be done?

**Comment by guybedford** [comment]
`jspm dl-loader` will download 0.19.9.

**Comment by NervosaX** [comment]
Okay, I see. So dl-loader always gets the version before the latest? I'm not sure if I'm just being a little thick or of it's not terribly obvious. :)

**Comment by guybedford** [comment]
`jspm dl-loader` gets the version locked to the jspm version for stability.

**Comment by NervosaX** [comment]
Perhaps it's worth noting that in the cli help as:

jspm dl-loader --stable

But thank you for making that clear. I will close the issue.
