### ISSUE TITLE
Jquery dependency isn't being respected

### ISSUE THREAD

**Issue by lookfirst** [jspm/jspm-cli#1398]
jspm v0.16.19

I'm installing selectize. In my package.json, I have this:

```
      "selectize": "github:brianreavis/selectize.js@^0.12.1",
      "jquery": "github:components/jquery@^2.1.4",
```

I just had a case where my config.js map got automatically changed from using the github version to the npm version for selectize:

```
    "github:brianreavis/selectize.js@0.12.1": {
      "css": "github:systemjs/plugin-css@0.1.20",
      "jquery": "npm:jquery@2.1.4",
      "microplugin": "npm:microplugin@0.0.3",
      "sifter": "github:brianreavis/sifter.js@0.4.5"
    },
```

I'd think that if I declare jquery as a dependency that that would get used first instead of the npm version being used. Not sure why this changed. =(

Nothing else in my project depends on jquery.

**Comment by guybedford** [comment]
Yes `jquery` was switched over to the npm version in the jspm registry via https://github.com/jspm/registry/commit/94432f091b0cc76dd961cea3f6916e5dac359721.

Anywhere where `jspm:jquery` is used in dependencies then updates to this version automatically.

The jquery update should only have happened though if the selectivize version was updated, as version lock principles still apply.

**Comment by lookfirst** [comment]
Sure, but I don't think you're understanding the problem here. I've already declared jquery as a dependency in my project. Let's say that I've forked jquery and I want all my dependencies to use that forked version. Now I don't have a way to do that without creating an override for selectize (and every other project that uses jquery).

**Comment by guybedford** [comment]
I've created https://github.com/jspm/jspm-cli/issues/1401 to track such a resolution feature.
