### ISSUE TITLE
Docs: CLI link in README.md is broken or missing file

### ISSUE THREAD

**Issue by siulung4073** [jspm/jspm-cli#1399]

**Comment by guybedford** [comment]
Can you clarify which link you are referring to?

**Comment by siulung4073** [comment]
In the https://github.com/jspm/jspm-cli/tree/master/docs page which shows you the README.md file, it has a CLI link (https://github.com/jspm/jspm-cli/blob/master/docs/cli.md) that respons 404 because the cli.md file doesn't exist.

**Comment by guybedford** [comment]
Sure, thanks I'll look into that.
