### ISSUE TITLE
jspm resolve by alias

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#1401]
`jquery` is a good example of something that will always be aliased by the same name.

It could be useful to have a resolve command that acts on the alias to ensure it always resolves to the correct registry location.

Something like `jspm resolve --alias jquery github:components/jquery`.

**Comment by lookfirst** [comment]
I don't think we need a special command for this. The simple solution is to look at the locally defined dependencies for things of the same name before looking upstream in the registry.

**Comment by Nehon** [comment]
Hello.
This would solve an issue I have with angular-material.
Please have look at : https://github.com/angular/material/issues/5489

In short, angular-material's package.json has jspm dependencies on angular and angular-animate pointing to the github registry.
In my project I already have npm:angular and npm:angular-animate installed.
When you `jspm install npm:angular-materal` it installs angular and angular-animate from github that resolves to the same aliases as the npm dependencies.

With @lookfirst solution, jspm would pick the already installed dependencies and skip the install from github.

**Comment by guybedford** [comment]
Let's handle this with peerDependencies rather via https://github.com/jspm/jspm-cli/issues/1479.
