### ISSUE TITLE
Promise replacement (bluebird) and async/await

### ISSUE THREAD

**Issue by mpfau** [jspm/jspm-cli#1402]
Hi there,
I am migrating from webpack to jspm and having some problems with using bluebirds error handling together with async/await.

When I `import Promise from 'bluebird'`, bluebird is used from transpiled ES6. If an error occurs in a Promise, bluebirds default error handling is triggered and I can handle unhandled rejections in `Promise.onPossiblyUnhandledRejection`. However, if I use the promise in a async/await scenario the default error handling of the core-js polyfill (jspm_packages/npm/core-js@1.2.6/library/modules/es6.promise.js) is triggered and `Promise.onPossiblyUnhandledRejection` is never invoked.

I tried to override the Promise polyfill in a bootstrap script that is loaded with `System.import` (based on babel doc):
```
delete window.Promise
require('babel-runtime/core-js/promise').default = require('bluebird');
window.Promise = require('bluebird')
```
Unfortunately, this does not work. How do I override the polyfill for all cases (including async/await)?

**Comment by guybedford** [comment]
@mpfau Promises is the one and only case in jspm that I would suggest loading the implementation with a script tag before SystemJS. The reason for this is that then SystemJS itself will use that promise implementation in its pipeline. And it then also avoids all the issues of working with core-js promises as well.

core-js including the Promise implementation is not ideal. To avoid this I would suggest removing the runtime transform from your code.

**Comment by mpfau** [comment]
@guybedford Ah, I got it, thanks for your input!

I just added bluebird as a script import to my html file and removed all `import Promise from 'bluebird'` statements. I also temporarily removed the await/async which requires a runtime transform (besides I really want to make use of it).

Unfortunately babel still pulls in the Promise implementation from core-js. Is there a way to tell babel not to polyfill `Promise` and to tell jspm that the module is already there (bluebird)?

**Comment by guybedford** [comment]
@mpfau sure, no problem. Yes you can remove the `runtime` transformer from the config.js file.

**Comment by mpfau** [comment]
@guybedford great! I had to replace the `runtime` transformer with `bluebirdCoroutines` to make it work as expected.

I think it would be good if we would add this to the docs. Is https://github.com/jspm/jspm-cli/blob/master/docs/installing-packages.md the right place? Would create a PR for it, then...

**Comment by guybedford** [comment]
@mpfau thanks for offering, I've created https://github.com/systemjs/plugin-babel/issues/4 to track this feature in the new Babel plugin coming in jspm 0.17. I'd rather not document it now as this release is just a couple of weeks from stable at this point, but hopefully we can get this story figured out nicely with the new loader.

**Comment by mpfau** [comment]
@guybedford great, that is even better!

**Comment by amenadiel** [comment]
@guybedford this should be added to the docs (althought I came here after googling for something I swear I've read in the docs somewhere). However, I have two doubts:

- To load bluebird from a script tag means knowing deterministically its location, for which we can't use JSPM since the folder changes according to the version. This introduces the need to keep a separate place for other dependencies which is less than optimal if bluebird is the one and only use case.
- Where should I disable the `runtime` transformer and replace it with `bluebirdCoroutines`? This is a project that's still using JSPM 0.16.x.
