### ISSUE TITLE
jspm config weirdness

### ISSUE THREAD

**Issue by u9520107** [jspm/jspm-cli#1405]
ok.. there comes a need for me to run jspm config registries.github.password to temperarily set password into the system, but ran into this issue:

my password starts with number.. the cli seems to then assume it's a number and so the .jspm/config show the password field as a number.... which means the alphabet parts are truncated and result in a password error.

**Comment by guybedford** [comment]
Thanks, I've added a fix in https://github.com/jspm/jspm-cli/commit/6af4c97c4aa2f5de62a04b95c2724c73f1700cb7.

**Comment by guybedford** [comment]
Released in 0.16.20.
