### ISSUE TITLE
JSPM does not respect minimum dependency version

### ISSUE THREAD

**Issue by neothemachine** [jspm/jspm-cli#1406]
```
ok   Up to date - covjson-reader as npm:covjson-reader@^0.3.2 (0.3.1)
```
Here it should try to install a newer version since 0.3.1 is too old.

**Comment by guybedford** [comment]
When dependencies are out-of-range, jspm considers them pinned by the user and manually managed.

Better communicating this in these messages is certainly an issue though. For example this should probably rather read something along the lines of

```
ok   Manually pinned - covjson-reader as npm:covjson-reader@^0.3.2 (0.3.1)
```

**Comment by neothemachine** [comment]
I see, makes sense. When I deleted the config.js it updated the version as expected. I guess this is another of those cases where `jspm update` or `jspm update packagename` would be useful.

**Comment by guybedford** [comment]
Yes exactly this would be solved by `jspm upgrade`.
