### ISSUE TITLE
Issue with new link workflow (0.17-beta)

### ISSUE THREAD

**Issue by frederikschubert** [jspm/jspm-cli#1408]
After using the new link workflow it is not possible to unlink and install the linked package. Here is what I did:

### Install the package from npm
```
jspm install npm:im2m-navigation
     Updating registry cache...
     Downloading npm:im2m-navigation@0.0.4
ok   Installed im2m-navigation to npm:im2m-navigation@^0.0.4 (0.0.4)
     Installed Forks
     
       npm:isarray 0.0.1 1.0.0
     
     To inspect individual package constraints, use jspm inspect registry:name.
     

ok   Install complete.
```
### Link the package to my local development copy of the project
```
jspm link ../../components/im2m-navigation im2m-navigation
     Processing linked package local:im2m-navigation@0.0.4
ok   Symlinked im2m-navigation as local:im2m-navigation@0.0.4 (0.0.4)
     Removing package files for npm:im2m-navigation@0.0.4
     Installed Forks
     
       npm:isarray 0.0.1 1.0.0
     
     To inspect individual package constraints, use jspm inspect registry:name.
     
     
     Run this link command again or jspm install local:im2m-navigation@0.0.4 to relink changes in the package.json file.
     Run jspm install --unlink to unlink and install all original packages. Linked packages can also be uninstalled normally.
```
### Try to unlink and install the package from npm
```
jspm install --unlink

err  Package local:im2m-navigation can only be linked and not installed.

err  Error looking up local:im2m-navigation.

warn Installation changes not saved.
```
Am I using the link command wrong or can this be considered a bug? I thought that the `jspm install --unlink` command would be a shortcut for `jspm uninstall <linked package> && jspm install <package>`. Additionally I think that the note about how to unlink a package should be included in the cli's `--help` output.

**Comment by guybedford** [comment]
When linking you should link it into its exact name:

`jspm link ../../components/im2m-navigation npm:im2m-navigation`

That will then link it into the right name, so that when you unlink it it will know where to install it from when unsymlinking.

**Comment by frederikschubert** [comment]
Ok I understand. Then its working as intended and I will close this issue. Thank you for your help!

**Comment by guybedford** [comment]
Sure, no problem.
