### ISSUE TITLE
Import of css error when bundling after upgrading to v0.16.20

### ISSUE THREAD

**Issue by canhamd** [jspm/jspm-cli#1411]
After upgrading to v0.16.20 the bundling process is throwing the following error when trying to process css imports:

	E:\jspm-test>jspm bundle modules/startup --inject
		 Building the bundle tree for modules/startup...

		   components/about-page/about.html!github:systemjs/plugin-text@0.0.4
		   components/home-page/home.html!github:systemjs/plugin-text@0.0.4
		   components/home-page/home.js
		   components/nav-bar/nav-bar.html!github:systemjs/plugin-text@0.0.4
		   components/nav-bar/nav-bar.js
		   components/search-page/search-page.html!github:systemjs/plugin-text@0.0.4
		   components/search-page/search-page.js
		   github:components/jquery@2.2.0
		   github:components/jquery@2.2.0/jquery
		   github:knockout/knockout@3.4.0
		   github:knockout/knockout@3.4.0/dist/knockout.debug
		   github:twbs/bootstrap@3.3.6
		   github:twbs/bootstrap@3.3.6/css/bootstrap.css!github:systemjs/plugin-css@0.1.20
		   github:twbs/bootstrap@3.3.6/js/bootstrap
		   modules/router.js
		   modules/startup.js
		   npm:babel-runtime@5.8.34/core-js/object/define-property
		   npm:babel-runtime@5.8.34/helpers/class-call-check
		   npm:babel-runtime@5.8.34/helpers/create-class
		   npm:core-js@1.2.6/library/fn/object/define-property
		   npm:core-js@1.2.6/library/modules/$
		   npm:crossroads@0.12.2
		   npm:crossroads@0.12.2/dist/crossroads
		   npm:hasher@1.2.0
		   npm:hasher@1.2.0/dist/js/hasher
		   npm:jquery@2.2.0
		   npm:jquery@2.2.0/dist/jquery
		   npm:signals@1.0.0
		   npm:signals@1.0.0/dist/signals
		   stylesheets/styles.css!github:systemjs/plugin-css@0.1.20
		   typescript-modules/hello-world.ts

	err  Error: CSS Plugin:
		 Broken @import declaration of "..\jspm_packages\github\twbs\bootstrap@3.3.6\css\bootstrap.css"
		 Broken @import declaration of "..\stylesheets\styles.css"
			 at file:///E:/jspm-test/wwwroot/jspm_packages/github/systemjs/plugin-css@0.1.20/css-builder.js:76:13

PS. the css is being successfully imported when unbundled.

**Comment by neothemachine** [comment]
I have the same. Just tested against 0.16.19 and there it still works.

**Comment by ciriarte** [comment]
Same here. 0.16.20 broke our build.

**Comment by guybedford** [comment]
I've just been looking into this and am unable to replicate at all when doing the same style import with an SFX build. Help replicating with the right combination of baseURL / paths configs (which it sounds like might be the issue), would be very helpful.

**Comment by neothemachine** [comment]
1. Clone https://github.com/Reading-eScience-Centre/leaflet-coverage-demo
2. Change package.json -> `"jspm": "0.16.20"`
3. Run `npm install`
4. Run `npm run build`

**Comment by guybedford** [comment]
Thanks, I've managed to track it down. Will post out a patch shortly.

**Comment by guybedford** [comment]
Fixed in 0.16.21.

**Comment by neothemachine** [comment]
Great, thanks! Confirmed it works.

**Comment by dougludlow** [comment]
I've been beating my head against the keyboard for a few hours over this. Thanks!

**Comment by born2net** [comment]
I am seeing same error now with 0.17 beta

**Comment by nithril** [comment]
Same issue using the 0.17.0-beta.22

**Comment by HongJheLi** [comment]
The same problem when I import onsenui css using jspm 0.16.45.

```
import 'onsenui/css/onsenui.css!'
import 'onsenui/css/onsen-css-components.css!'
```
