### ISSUE TITLE
Throws error "Main entry point not found" when "main" is declared as array

### ISSUE THREAD

**Issue by swernerx** [jspm/jspm-cli#1413]
There is a package I'd like to use called vue-i18n https://github.com/Haixing-Hu/vue-i18n. In their package.json the main entry point is defined as an array. I am not sure whether this is an error, but interestingly the error message from jspm is also not very helpful:

```
$ jspm install npm:vue-i18n-plugin
```

    Main entry point not found for npm:vue-i18n-plugin@0.2.0.
    Adjust this property in the package.json or with an override, setting "main": false if this is the intention.

The file which is referenced is available though:

```
"main": [
  "src/vue-i18n.js"
],
```

I am not sure if jspm should tolerate this declaration of whether this is a problem in the package itself. It just seems like npm itself is not having any issues which this.

**Comment by swernerx** [comment]
See also: 
https://github.com/Haixing-Hu/vue-i18n/issues/4

**Comment by guybedford** [comment]
Array mains are not supported in Node (giving an error message when loaded), so we ignore array mains in jspm as well.

**Comment by swernerx** [comment]
Maybe we can improve the error message a little...

**Comment by guybedford** [comment]
Sure - https://github.com/jspm/npm/commit/c05fb41a57d0ed1b898fef610c2898d010025128.
