### ISSUE TITLE
jspm@beta: incomplete jspm.browser.js file created

### ISSUE THREAD

**Issue by yoctopuce** [jspm/jspm-cli#1414]
The jspm.browser.js file created by 'jspm init' is missing critical information:
- transpiler is not specified, so it defaults to traceur instead of babel by default
- map section does not include links to plugin-babel, etc.

**Comment by guybedford** [comment]
I'll post the detailed release notes tomorrow explaining this. The `jspm.js` config file needs to be included as well.
