### ISSUE TITLE
travis-ci jspm credentials issue

### ISSUE THREAD

**Issue by erfangc** [jspm/jspm-cli#1416]
Trying to build and test a project with `jspm` in `travis`

I followed the procedure outlined here (i.e. encrypting  `registries.github.auth`)
[https://gist.github.com/topheman/25241e48a1b4f91ec6d4](https://gist.github.com/topheman/25241e48a1b4f91ec6d4)

```bash
Use jspm registry config github to reconfigure the credentials, or update them in your ~/.netrc file.
```

Am I using outdated instructions?

Build Log:
https://travis-ci.org/erfangc/GigaGrid/jobs/101678781

I tried the Wiki posted [Here](https://github.com/jspm/jspm-cli/blob/master/docs/registries.md)
(i.e. setting the JSPM_GITHUB_AUTH_TOKEN in the `travis-ci.org` `Settings` page) that did not help either.

I am able to pull/push to `github` using my access token locally
Local usage of  `jspm` also works without any issue

If it is any help ... I also tried NOT encrypting the auth token at all and simply added

`jspm config registries.github.auth <Base64 Tnencrypted Token>` in my `.travis.yml` without any luck.

**Comment by erfangc** [comment]
I am using 

```
$ jspm --version
0.16.20
```

**Comment by guybedford** [comment]
The comments at the end of that gist provide some insights... did you try any of those suggestions? There isn't anything magic going on here, just wiring.

**Comment by erfangc** [comment]
I finally got it to work ... the scary thing is that I am not sure how ... 

I *think* either I made a mistake copying the token (i.e. not copying the jspm generated `username:password` Base64 string) Or the `travis encrypt` didn't work ... 

Either way, it looks like the most straight forward way is to use a Env variable and not manually encrypt thats @guybedford 

This is my first project with `jspm`, so far it is amazing, with some oddities along the way that typically comes with new technologies, cheers!

**Comment by guybedford** [comment]
Sure, no problem. Glad to hear that - yes contributions are always welcome, however small, to help smooth the edges.
