### ISSUE TITLE
jspm@beta: error loading systemjs-plugin-babel@0.0.2

### ISSUE THREAD

**Issue by yoctopuce** [jspm/jspm-cli#1419]
My html file now properly loads 
- jspm_packages/system.js
- jspm.js
- jspm.browser.js
SystemJS seems to start fine, but then fails to load babel because it request the systemhs-plugin-babel@0.0.2 _directory_ instead of a json or js file. Apache responds with a redirect (301) to the directory name with a slash appended, and but this cause an error on load since it actually is an html page describing the directory contents.

See attached screenshot
![screen shot 2016-01-11 at 22 24 07](https://cloud.githubusercontent.com/assets/1703194/12247160/036fd1e0-b8b3-11e5-85d9-48265d43d1fd.png)

**Comment by guybedford** [comment]
Again, I will post the real docs soon, but it is critical to include the browser.js file before the jspm.js file.

**Comment by yoctopuce** [comment]
Yipee, that solves it ! Sorry for being that impatient...
