### ISSUE TITLE
Uncaught ReferenceError: module is not defined

### ISSUE THREAD

**Issue by lookfirst** [jspm/jspm-cli#1421]
jspm 0.6.21

Ok... after builder.buildStatic() i'm left with a file that I then load in the browser. In the browser console, I'm seeing `Uncaught ReferenceError: module is not defined`

The very end of the file has: `(function(a){module.exports=a()});` in it (which isn't added by me) and that is underlined in red as the error. The top of the file has `"format cjs";`.

This was working fine in 0.6.19. =)

**Comment by guybedford** [comment]
@lookfirst by default static bundles output as CommonJS in SystemJS Builder 0.15. I've updated the release notes in https://github.com/systemjs/builder/releases/tag/0.15.0, and included the backwards compat API layer in https://github.com/jspm/jspm-cli/commit/6ae541e0a3bc16a2ff385f11aa2ed5bc4297b0dd.

**Comment by guybedford** [comment]
(Run your build with `builder.buildStatic('main', { format: 'global' })` to work around)

**Comment by davinkevin** [comment]
I've got the same problem, I try your solution. Thanks

**Comment by lookfirst** [comment]
@guybedford Interesting. What is the reason for that default change? Is there something on my end that I should do in order to make my build work with cjs instead?

**Comment by guybedford** [comment]
@lookfirst the output format is cjs. That is you would need to System.import your bundle. (`module` and `exports` are not defined in the browser usually).

**Comment by lookfirst** [comment]
@guybedford But I thought the idea behind buildStatic is to build a 'self-executing' bundle. If I need to then System.import() it, that would mean a dependency on having System(JS) available first. It seems odd to change the default for buildStatic to CJS then.

**Comment by guybedford** [comment]
@lookfirst this will be properly documented in due course. But no, rather than a self-executing bundle, it is now just an optimized module.

**Comment by guybedford** [comment]
(that is, a module can be in any module format)

**Comment by guybedford** [comment]
Released in 0.16.22.
