### ISSUE TITLE
format is ignored in override

### ISSUE THREAD

**Issue by lookfirst** [jspm/jspm-cli#1422]
jspm 0.6.19 (not 21 cause of my other issue)

I have an override in my `package.json` where I'm trying to set it as `format cjs` and the angular-clipboard.js file keeps getting `format global` stuck at the top.

```
      "github:lookfirst/angular-clipboard@master": {
        "dependencies": {
          "angular": "^1.4.0"
        },
        "main": "angular-clipboard",
        "registry": "jspm",
        "format": "cjs",
        "shim": {
          "angular-clipboard": {
            "deps": [
              "angular"
            ]
          }
        }
      },
```

I see this expected warning in the `jspm install` output:

```
warn Using local override for github:lookfirst/angular-clipboard@master
```

**Comment by lookfirst** [comment]
The followup question to this is:

What is the best way to export a default module from a package that is installed via github:?

**Comment by guybedford** [comment]
The behaviours are all correct here. Shim always means global format for that specific file, regardless of the package format.

**Comment by lookfirst** [comment]
Ah, removing that 'fixed' things. =) Interesting, I still don't get a 'format cjs' at the top of the file, but it all seems to load as cjs anyway in the browser with a transform.
