### ISSUE TITLE
Alphabetize the bundles section

### ISSUE THREAD

**Issue by arfmann** [jspm/jspm-cli#1424]
Just a minor niggle, which seems to be related to #215 

The last step of my build process is to bundle JSPM packages, and this of course updates the config.js file's bundles section. However, the order of the entries in each array seems to change each time this runs. The effect is that a pending change starts to show up in Git every time I rebuild even though nothing of significance has changed. 

If the entries in this array were alphabetized (or somehow consistent), this wouldn't be a problem. I don't think it'd effect anything else?

**Comment by guybedford** [comment]
@arfmann which version of jspm are you using here? The array of modules is supposed to be deterministic based on the build tree.

**Comment by arfmann** [comment]
0.16.19 according to JSPM. I've updated to 0.16.22 now, and I still see the same. Looking into further, it seems to be a more specific issue. Here's a screenshot of a before-and-after diff of my config.js:

![image](https://cloud.githubusercontent.com/assets/16491341/12297837/f7be8dc8-ba06-11e5-80c8-6f5c8434f1f1.png)

It actually seems to be some inner files within a package that are changing order (in this case, RXJS). The expression I'm using to build just has ' + rx +' in there.

**Comment by fMads** [comment]
I also have this problem
JSPM 0.16.15

I does that on all my packages - external libraries or internal modules.
![image](https://cloud.githubusercontent.com/assets/832842/12350528/da8b0a66-bb77-11e5-9151-e82eecdc6292.png)

**Comment by fMads** [comment]
@guybedford Was this fixed? :)

**Comment by guybedford** [comment]
Yes, it should be resolved in the latest jspm versions.
