### ISSUE TITLE
Column size too small in TravisCI

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#1425]
For some reason the beta logging column size is too small (https://travis-ci.org/jspm/jspm-cli/jobs/101803937), while this works fine on a local machine. We read `process.stdout.columns` perhaps there is some issue with this in https://github.com/jspm/jspm-cli/blob/0.17/lib/ui.js#L212.

**Comment by amalahussein** [comment]
the column logging looks fine to me here, is there still a valid bug?

**Comment by guybedford** [comment]
Thanks @amalahussein you're right this seems to have magically fixed itself!
