### ISSUE TITLE
Injected bundle tries to load Traceur Runtime

### ISSUE THREAD

**Issue by subesokun** [jspm/jspm-cli#1426]
Hi, to avoid modifying the `index.html` when building the production version of my app I was trying inject the bundle automatically via

```bash
# my baseURL is web/src
jspm bundle main web/src/main.js --inject 
```

So far so good but when I try to load now my application I get the following error

```
GET http://localhost:3002/traceur-runtime.js 404 (Not Found)    system.src.js:4840
```

Any idea? Btw. my transpiler is set to Babel so I'm wondering why it tries to load Traceur... :(

**Comment by mgamsjager** [comment]
show us your config.js

**Comment by guybedford** [comment]
@subesokun it would help if you can share the bundle file here actually.

**Comment by subesokun** [comment]
Hi, thanks for the feedback! As I'm using private modules it's actually a bit difficult to post here the bundle or the config file :/ I'll try to make a sample application which (hopefully not :p?) shows the same error.

**Comment by guybedford** [comment]
Sure that would help. There must be a reference to `$traceurRuntime` somewhere in your bundle, which would be good to understand how that happened.

**Comment by subesokun** [comment]
Not sure if this error is related but I was using now the latest jspm beta.5 to create a sample application for tracking down my issue with the traceur runtime but I do get now the following error when simply trying to import Angular.

```
GET http://localhost:3000/traceur 404 (Not Found)
Uncaught (in promise) Error: XHR error (404 Not Found) loading http://localhost:3000/traceur(…)
```

Note: I was not using the jspm:angular, but the npm:angular version with some custom overwrite rules stored in the `package.json`.

I've uploaded my sample app as Gist https://gist.github.com/subesokun/e8689c4ffbf3d78b617d

```bash
npm install
jspm install
serve .
```

**Comment by guybedford** [comment]
@subesokun I just copied your example exactly and I'm definitely not getting this. Are you running the latest SystemJS?

**Comment by subesokun** [comment]
Ah I've fixed already the issue mentioned in my last comment by including the `jspm.config.js` in my `index.html` in my Gist. Without that configuration there is a fallback to the traceur compiler it seems which I don't have installed locally.

But still working on getting a demo ready which shows the traceur runtime error when trying to bundle the application.
