### ISSUE TITLE
A unknow error when run npm install jspm --save-dev on windows 10

### ISSUE THREAD

**Issue by p4535992** [jspm/jspm-cli#1428]
Not sure about this in windows 8 work all fine , but with windows 10 i get this strange error, after i put the following commands:
<code>
C:\Users\4535992\Desktop\ee>node -v

v5.0.0
</code>
<code>
C:\Users\4535992\Desktop\ee>npm -v

3.3.6
</code>
<code> npm install jspm -g</code>
all is fine so when i choose a folder and run the command
 <code>cd my-project</code>
 <code>npm install jspm --save-dev</code>
here my output console:
<code>
C:\Users\4535992\Desktop\ee> npm install jspm --save-dev
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "jspm" "--save-dev"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6

npm ERR! Cannot read property 'localeCompare' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\4535992\Desktop\ee\npm-debug.log
</code>
here my npm-debug.log: [link to npm-debug.log](https://onedrive.live.com/redir?resid=DDE1406B855226E5!5819&authkey=!AEwQPWv7Wg6Cvhk&ithint=file%2clog) 

Any idea why is doing that?

**Comment by guybedford** [comment]
This seems more like an npm bug than a jspm one?

**Comment by p4535992** [comment]
Now you point me to that, i found similiar issues on the npm project, but i wonder why in other projects where i not using jspm npm seem still work. I closed the ticket because is more a npm problem than a jspm.
Ty for the fast response.

**Comment by p4535992** [comment]
Confirmed, using old version of npm work, there is some problem with the last release of npm.
