### ISSUE TITLE
overrides in package.json get deleted

### ISSUE THREAD

**Issue by jansensan** [jspm/jspm-cli#1429]
With our project we need to use the `overrides` section to add some overrides and dependencies. However, if I run `jspm update`, I would expect the package manager to get the additions set there (for example: a lib missing a dependency on `moment`), but instead running that task deletes the whoe `overrides` section.

This makes any manual additions lost, and it's scary that this happens without a warning. I am wondering if this is as designed, however if so, I do not understand why.

**Comment by jansensan** [comment]
So I discovered this thread: [Save install overrides to config.js or package.json](https://github.com/jspm/jspm-cli/issues/164)

@guybedford I detailed my question in a [StackOverflow question](http://stackoverflow.com/questions/34774702/how-to-make-jspm-install-bower-dependencies), but I think  that your final conclusion in the thread/issue 164 is that the `overrides` to happen in the source library or in the public registry repo.

It's an architectural choice you made, however it really defeats the purpose of an override section. It should be left to the project consuming JSPM to choose whether or not to override this or that, and this was the strength of Bower.

A bit disappointed with that choice.

**Comment by corneliutusnea** [comment]
Totally agree. The central repository is great but should not be the only option. I should have an easy option to have my own overrides that are respected. Maybe for our own libraries or private repos.

**Comment by eesdil** [comment]
I think it is getting deleted because you have wrong config, you have to configure it in packages.json in jspm section, note that the override need specific version and not range (it took some time to find the way though...):

```
"jspm": {
    "overrides": {
      "npm:moment-timezone@0.4.1": {
        "registry": "jspm",
        "dependencies": {
          "moment": "npm:moment@^2.10.6"
        },
        "shim": {
          "moment-timezone": {
            "deps": [
              "moment"
            ]
          }
        }
      }
    }
}
```

**Comment by marchel2** [comment]
I have a slightly different use case in that I need to provide shims for local files(3rd party libraries not on github/npm). 

Currently, in the module's package.json , I have(without the "overrides" section)
```json
"jspm": {
    "dependencies": {"jquery": "npm:jquery@^2.2.0" },
    "devDependencies": {"core-js": "npm:core-js@^1.2.6"},
    "shim": {
      "vendor/jaydata@1.4/jaydata": {
        "deps": ["./../datajs@1.0.3-patched/datajs.js"],
        "exports": "$data.Acorn"
      },
      "vendor/datajs@1.0.3-patched/datajs": ["jquery"]
    }
  }
```
Everything works great when I jspm install this package in another project as a dependency.

However, if I jspm install any other dependency into my module, the shims get wiped out, as this post has described. 

What I would like to do, is add the "overrides" section into the module's package.json, but I don't see how to declare the over-rides for the module itself.  Is this supported?
```
"overrides": {
      "this-package?": {
        "shim":{//shims for local vendor files...}
      }
    }

**Comment by guybedford** [comment]
@jansensan overrides in the package.json are supposed to track updates, ensure the version is specified exactly as in https://github.com/jspm/jspm-cli/issues/1429#issuecomment-172302702.

@marchel2 try moving the `shim` property out of the jspm prefix. Supporting non-local properties in the jspm prefix is provided in jspm 0.17.

**Comment by raptor9g** [comment]
I'm having the same issue.  I'm trying to use the "babel-polyfill" module.  Which contains a "browser.js" file.  That's what I want my "main" file to be and no dependancies.  Get's wiped out every time. I run `jsmp install`

```
"jspm": {
    "configFile": "_config/jspm.config.js",
    "overrides":{
        "npm:babel-polyfill@^6.6.1":{
            "formatt":"global",
            "main": "browser",
            "dependencies": {},
        }
    },
    "dependencies": {
      "babel-polyfill": "npm:babel-polyfill@^6.6.1"
    },
    "devDependencies": {}
  }
```

```
ok   Up to date - babel-polyfill as npm:babel-polyfill@^6.6.1 (6.6.1)
     Removing unused package.json override npm:babel-polyfill@^6.6.1
ok   Install tree has no forks.
```
