### ISSUE TITLE
Default configFile name (jspm.js) should not conflict with common user commands (0.17.0-beta.2)

### ISSUE THREAD

**Issue by ebpa** [jspm/jspm-cli#1438]
Windows unfortunately has lazy extension behavior which effectively limits options for naming the default SystemJS/JSPM config file (other merits of naming are discussed in #715).   

Most people are familiar with typing `somecommand` into the command line on Windows and having `somecommand.exe` or `somecommand.bat` execute automatically.  Windows accommodates this lazy interpretation of commands using a list of extensions in the `PATHEXT` environment variable (`.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC`).   In all versions of Windows since XP `.JS` is included in this list by default, so Windows attempts to execute any matching js files using wscript.exe (Windows Script Host).  Currently the default configFile used by init in 0.17.0-beta.2 is `jspm.js` which- owing to its descriptiveness- happens to conflict with the jspm-cli command name `jspm`.  Executing jspm.js / config.js naturally doesn't work.

Users encountering this problem will be presented by a Microsoft JScript runtime error window indicating `JScript error code 800A1391` `'SystemJS' is undefined`.

This collision would take place for any project that doesn't have a configPath specified manually in package.json.

Windows is lazy with respect to file extensions and the presence of jspm.js basically breaks jspm.
jspm commands are issued in the root folder of a project, so

**Comment by unional** [comment]
This would be a major blocker on windows environment. :rose:

**Comment by guybedford** [comment]
This was fixed in the latest beta, thanks @ebpa for the early catch here.

**Comment by ebpa** [comment]
:+1:

**Comment by ArmorDarks** [comment]
This is too late, but just for the information. We've used in our projects all time `.jspm.js` and never had any issues. Leading dot does the trick and keep it consistent with linux-styled config files naming.
