### ISSUE TITLE
implement optionalDependencies

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#1441]
A good story for optionalDependencies is really necessary to allow flexible packaging scenarios.

The way this would work, is that optional dependencies would basically be peerDependencies that are not installed.

That is, the package gets to specify the range and name of the thing as a peerDependency (eg `promise: 'npm:when@^1'`), and then when installing something that is an optional dependency of any of our dependencies, it notifies accordingly. Eg in the case above `jspm install promise` will automatically become a peer install if it is an optional dependency of something already installed. We then prompt with the exact same prompts peerDependencies use for conflicts, but against the optionalDependencies ranges, for as many may match that dependency.

**Comment by gertsonderby** [comment]
I've run into an actual breaking optional dependency (`nearley@2.7.7` attempts to install `railroad-diagrams` from a commit hash, which makes JSPM angry).

As well, it seems that attempting to override this (i.e. `jspm install npm:nearley@2.7.7 -o "{optionalDependencies:{}}"`) has no effect - the breaking dep still gets attempted pulled, and installation shuts down in flames. Halp?

**Comment by guybedford** [comment]
@gertsonderby if you look at the package you'll see that it has optionalDependencies and dependencies both with a `railroad-diagrams` entry. So the actual override needed would be something like `jspm install npm:nearley@2.7.7 -o "{optionalDependencies:{},dependencies:{\"cli-color\": \"^1.0.0\",\"nomnom\": \"~1.6.2\",\"randexp\": \"^0.4.2\"}}"`.

**Comment by patrickmichalina** [comment]
In the case of something like this project

https://github.com/PrismJS/prism/blob/gh-pages/package.json

How would one best ignore the optional deps? It [fails](https://github.com/PrismJS/prism/issues/1071) when installing version 1.6 because of the dep on "clipboard".

**Comment by guybedford** [comment]
@patrickmichalina you could use an override like `-o "{optionalDependencies:null}"`.

**Comment by GongT** [comment]
```
[root workspace]# jspm -v
0.17.0-beta.42
Running against local jspm install.
[root workspace]# jspm install npm:prismjs -o "{optionalDependencies:null}"
     Updating registry cache...

err  Repo jspm:clipboard not found. Perhaps try jspm install npm:clipboard.

warn Installation changes not saved.
```

hmmm....
