### ISSUE TITLE
Use case: Mocha Programmatic API

### ISSUE THREAD

**Issue by yanneves** [jspm/jspm-cli#1443]
Had some struggle solving a way to use Mocha in-browser and bundling using JSPM, to avoid any risk of differences between transpiling source through JSPM and Mocha's Babel plug-in.

Referred to #843 and systemjs/systemjs#725, but required the ability to run this directly through JSPM, one identical transpilation step.

The key here was in understanding `mocha.setup()` (bindings!) in the programmatic API, and I arrived at a working solution that runs in-browser with a single point of entry, defining Mocha / Chai once. You can see a lean demonstration of this in this gist https://gist.github.com/yanneves/93a41bd38923e4bc247d.

Setup just requires:
```
jspm install mocha chai --dev
```

Building on from here should be familiar, in this case using Mocha + Chai, which could be extended to include Sinon, etc. I'd be interested to know how this sits with other use-cases, and it may warrant a place in documentation.

**Comment by guybedford** [comment]
@yanneves this sort of information is really great to share with other users. If you feel like writing it up and sharing it with the world please do. The jspm docs are aiming to cover just the bare minimum, that's why we rely on the ecosystem around the project to share solutions like this.
