### ISSUE TITLE
Separate jspm.dev.js config file

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#1444]
This way the dev tree can be isolated from the production tree.

The complexity here is joining and then separating the dev and production trees in order to perform install operations that handle resolutions correctly. It should be relatively straightforward in principle, but requires some careful handling.

**Comment by yanneves** [comment]
Does this mean all jspm dependencies are currently injected in a self-executing production build, or just those that are imported somewhere?

**Comment by guybedford** [comment]
Builds only build the import trees.

**Comment by guybedford** [comment]
Released in jspm 0.17.0-beta.15.
