### ISSUE TITLE
Support parallel installs comprehensively

### ISSUE THREAD

**Issue by laurentgoudet** [jspm/jspm-cli#1445]
I have `jspm` running in a CI environment (Jenkins), and it seems that it's not playing nice with `git` locking mechanism:

```
00:06:05.030 warn Error on getOverride for jspm:npm
00:06:05.030      Error: Command failed: /bin/sh -c git fetch --all && git reset --hard origin/master
00:06:05.030      fatal: Unable to create '/home/jenkins-slave/.jspm/jspm-cache/.git/index.lock': File exists.
00:06:05.030 
00:06:05.030      If no other git process is currently running, this probably means a
00:06:05.030      git process crashed in this repository earlier. Make sure no other git
00:06:05.030      process is running and remove the file manually to continue.
00:06:05.030 
00:06:05.030          at ChildProcess.exithandler (child_process.js:751:12)
00:06:05.030          at ChildProcess.emit (events.js:110:17)
00:06:05.030          at maybeClose (child_process.js:1015:16)
00:06:05.030          at Socket.<anonymous> (child_process.js:1183:11)
00:06:05.030          at Socket.emit (events.js:107:17)
00:06:05.033          at Pipe.close (net.js:485:12)
```

**Comment by guybedford** [comment]
@laurentgoudet are you running multiple jspm installs at the same time?

**Comment by laurentgoudet** [comment]
Yes, our CI setup is running multiple builds in parallel, with sometimes the jspm installs happening at the same time.

**Comment by guybedford** [comment]
Parallel executions of jspm are not currently designed to be comprehensively supported. Marking as a feature.

**Comment by mikz** [comment]
@laurentgoudet AFAIK jenkins will run parallel jobs in different folder. At least ours does.

That being said, most of the tooling (npm shrinkwrap, ruby bundler) reads its configuration, then tries do to resolving and writes the lock atomically (or seems so). However, not sure what would happen if two processes would try to write the same packages on the file system.

I'm pretty sure that parallel install is not very useful, as it is almost indescribable, what should happen in the edge cases. For parallel jobs on jenkins, just use jenkins native concurrency setting and it will spawn the jobs in different folders.

**Comment by jtamary** [comment]
We encountered a related issue with JSPM and Jenkins.

Since JSPM caches the packages and the registry per user we have a problem with our CI runs which runs on different machines with the same user in parallel.

**Comment by mikz** [comment]
Ok. That makes total sense. Had no idea that it stores cache the home folder. 

Would it be cool to have an option to store it in current workdir. I know it would be less effective, but also more predictable.

**Comment by guybedford** [comment]
Moving to #1609.
