### ISSUE TITLE
jspm.normalize only works with direct dependencies

### ISSUE THREAD

**Issue by frederikschubert** [jspm/jspm-cli#1446]
## My use case

I use the [jspm-sass-importer](https://github.com/idcware/node-sass-jspm-importer) to import SASS files from my JSPM dependencies (e.g. font-awesome) into my project. 
The importer [uses](https://github.com/idcware/node-sass-jspm-importer/blob/master/src/importer.js#L16) JSPM's `normalize` function to resolve the dependency.

## The problem

I now have a project where I import the SASS files via the importer and it works just fine. But when I try to use this project in another project and declare it as a dependency, the SASS import breaks. This is because the `normalize` function can only resolve the file path to the dependency if it is a direct dependency of the project.

One workaround would be that I declare the SASS dependencies as peer dependencies but I would like to avoid this.

**Comment by gcnm-pgeil** [comment]
I'd file your issue in the https://github.com/idcware/node-sass-jspm-importer repository, since it's primarily their duty to keep up with developments of jspm (they don't lock a specific jspm version in their package.json btw.) and offer support. And since the use-case you outlined seems pretty common to me, I believe the solution to this issue lies in the domain of jspm-sass-importer.

**Comment by frederikschubert** [comment]
Ok I will open an issue at their repo. I opened this issue here because I thought it would be a bug in the `normalize` function of jspm. I expected it to also normalize (resolve) dependencies of dependencies.

**Comment by typhonrt** [comment]
Just a FYI as I happened to be browsing JSPM issues and came across this one. I have a NPM module which can resolve dependencies of dependencies: [typhonjs-config-jspm-parse](https://www.npmjs.com/package/typhonjs-config-jspm-parse). Check out `getPackageResolver` and `getDirectDependency`.
