### ISSUE TITLE
Unable to install npm: local packages

### ISSUE THREAD

**Issue by voodooattack** [jspm/jspm-cli#1447]
I recently switched out npm in favour of jspm in my project.

NPM allows you to supply a local path as package version:

``` npm install ../example-package/ ```

It looks like jspm does not accept such a method, it throws this when I make the api call:

``` Repo `npm:/home/voodooattack/dev/nodepress/nodepress-core-plugin-locale` not found! ```

I tried linking my local packages instead (``` jspm link npm: ```) and then installing them like so:

``` jspm.install({ "nodepress-core-plugin-locale": "npm:nodepress-core-plugin-locale" }, { link: true }) ```

Which does not produce the error above; but it causes this error to appear when it tries to install a dependency (also linked in both npm and jspm):

``` Repo `npm:nodepress-interfaces` not found! Error: Repo `npm:nodepress-interfaces` not found! ```

I tried everything short of writing my own registry module. (which I might have to do at some point for this project anyway)

Any idea what I might be doing wrong here?

**Comment by gcnm-pgeil** [comment]
I was faced by the same issue. Currently (read: in latest jspm-cli release) the module api (exports of `require('jspm/api')`) of JSPM doesn't allow for linking local package sources. This is only possible through the cli interface (run `jspm link /path/to/pkg/src/dir npm:my-module-name-without-slashes@1.2.3` in console). I issued a pull request which addresses exactly this issue yesterday: https://github.com/jspm/jspm-cli/pull/1452 -- when @guybedford accepts it this might land in the next jspm minor release.

**Comment by guybedford** [comment]
jspm 0.17 supports linking local folders via `jspm link ../path/to/folder`.

**Comment by voodooattack** [comment]
Awesome, thanks.

Already solved the issue by running my own private npm registry, it's tedious but it'll work for now.
