### ISSUE TITLE
bug: 0.16.23, Inconsistent loading using `import`

### ISSUE THREAD

**Issue by unional** [jspm/jspm-cli#1448]
I have a ts package importing `domready`:
`import * as domready from 'domready';`

It works fine inside the package. `domready` is resolved to the function.

When I reference this package, it fails. `domready` is resolved to `{ default: Function }`.

Tried to trace the issue, seems like one is called by `linkDynamicModule()` L3109 (working)
and the other is called by `link()` L2838 (not working).

**Comment by frankwallis** [comment]
It looks correct to me that ```import * as domready from 'domready';``` should return ```{ default: Function }```. You should use ```import domready from 'domready';``` to get the default export. If TypeScript is not picking up on this then you may have an incorrect 'domready' declaration?

**Comment by unional** [comment]
I originally was doing `import domready from 'domready'`, but then in the latest build it failed as it returned undefined. In either case, the behavior should be consistent.

However, after I tried to roll back to 0.16.20 and test things out, it starts to work again.

Will continue to monitor a bit. Will close this issue now and reopen it if needed.

**Comment by unional** [comment]
Oh, by the way `domready` was not doing `export default`, so it may be `__ESModule` related?

**Comment by frankwallis** [comment]
Yes I do agree there is an issue, but it is hard to pinpoint. It seems that though files are not reliably being detected as commonjs/esm.

This issue is also similar: https://github.com/capaj/systemjs-hot-reloader/issues/42

**Comment by unional** [comment]
I am able to reproduce the issue.

It turns out to be related to the `module` flag.
In `config.js`:
```js
System.config({
  ...
  typescriptOptions: {
    module: "system"
    ...
  }
  ...
```

module | import domready from `domready' | import * as dr from 'domready'
----------| ------ | ------
system | yes | no
commonjs | no | yes
amd | no | yes
umd | no | yes

**Comment by frederikschubert** [comment]
I see the same behavior with momentjs. The typings suggest to import it as a module with `import * as moment from "moment";` but this only worked with commonjs module format. 
After switching it to system format as the new version of plugin-typescript suggested I have to import moment as the default export `import moment from "moment"`.

**Comment by frankwallis** [comment]
I think this may be related to [this](https://github.com/Microsoft/TypeScript/issues/5285) issue. There is a new compiler option in 1.8.0 ```--allowSyntheticDefaultImports``` which could solve it, see [here](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#support-for-default-import-interop-with-systemjs).

**Comment by unional** [comment]
@frankwallis I think it could be different. This is more about the discrepancy between different module output. That is more about exposing `default` on definitions.

And supposedly, according to the link: `Module loaders like SystemJS wrap CommonJS modules and expose then as a default ES6 import.`

Which means `import dr from 'domready'` should work for `module: "commonjs"`

**Comment by unional** [comment]
Oh, take it back. Didn't notice that link IS for 1.8.

In that case then the issue is the flip-side: `module: "system"` + `import * as dr from 'domready'` is the other issue need to tackle.

**Comment by unional** [comment]
Adding more detail: It also has to do with the format of the importing module.

I am importing `bluebird` and `domready`. `bluebird` is `"format global"` and `domready` is `"format cjs"`.

module | import dr from `domready' | import * as dr from 'domready' | import B from 'bluebird' | import * as B from 'bluebird'
----------| ------ | ------ | ----- | ----
system | works | fails | works | works
commonjs/amd/umd | fails | works | fails | works

**Comment by unional** [comment]
To clarify, `import B from 'bluebird'` and `import * as B from 'bluebird'` is doing two different things.

`import * as B from 'bluebird'` returns the module export while `import B from 'bluebird'` returns the default export.

In simplest way, `import B from 'bluebird'` returns a `Promise` that you can call with `new B(...)`, while `import * as B from 'bluebird'` returns a module object and you need `new B.default()` to access the promise function.

**Comment by unional** [comment]
Adding references
https://github.com/Microsoft/TypeScript/issues/2839
https://github.com/Microsoft/TypeScript/issues/4668

**Comment by unional** [comment]
Close as it is a duplicate of https://github.com/Microsoft/TypeScript/issues/5285
