### ISSUE TITLE
Changes major version on update

### ISSUE THREAD

**Issue by dalgard** [jspm/jspm-cli#1454]
I did a `jspm update` in my project and `lodash` was updated from `3.10.1` to `4.0.0`. This bump in major version broke compatibility, which caused the code of another library to fail.

Shouldn't `jspm update` only upgrade to compatible versions according to SemVer?

This may be related to #705.

**Comment by guybedford** [comment]
What was the range in your package.json when you ran jspm update?

**Comment by dalgard** [comment]
I'm not sure what you mean by 'range', but `lodash` isn't in my `package.json` file, since it is only a dependency of the `restangular` package. That is, it only appears under `map`.

**Comment by teohhanhui** [comment]
@dalgard If you're using `lodash` directly in your code, it should be in your `dependencies`. Otherwise you're at the behest of another package (`restangular` in your case). They might even decide to drop the dependency on `lodash` altogether!

**Comment by teohhanhui** [comment]
Okay, I get what you mean now. It's the problem with another library not properly specifying via semver what they can work with...

**Comment by dalgard** [comment]
I guess, yeah.

Restangular depends on `lodash` being present as `_` in the global scope, and to that end, I've specified `"lodash": "github:lodash/lodash@3.10.1"` as a dependency in `map`, overwriting the `npm:` version.

When running `jspm update`, I don't think it should look at `@3.10.1` and think "Hmm, I think I might just upgrade that to `@4.0.0`, there you go".

**Comment by teohhanhui** [comment]
From `restangular`'s package.json:

```json
  "dependencies": {
    "lodash": ">=1.3.0"
  },
```

They're not using semver correctly, that's why.

**Comment by dalgard** [comment]
I'm creating an issue with them. Thanks for the help!
