### ISSUE TITLE
[bug] Conflict when looking up package versions strings with special chars

### ISSUE THREAD

**Issue by gcnm-pgeil** [jspm/jspm-cli#1461]
### Problem

I wanted to use jspm-github for resolving package names hosted on github and using branch/tag names as (non-semver compliant) version strings which may contain slashes (`/`). Some background: we use a slashed naming scheme for our branch and tag names (`MyAspect/master`, `MyAspect/feature/SomeFeature`asf.) and slahes are obviously considered special chars in the pkg name/version space. However, JSPM can't deal with them and yields an error.

### Solution

When using `lib/package.lookup(pkg, edge)` for looking up packages in the github registry, we first request a map with all found versions in the according repository. But the original version strings are not escaped and instead are used as they are (which may also include slashes). Then we match the originally requested package version string against all found versions by first **decoding** it. Then, after we had a match, we return a new PackageName with parameter `escape = true` object as lookup result. When we finally try to download that package (with the **url encoded* version string) we can't find the original release/branch and receive an error.

We correct this conflicting algorithm by passed `escape = false` to the PackageName constructor. 

https://github.com/jspm/jspm-cli/blob/b49f8ec196decd3b92311c75bc589e33a8875d64/lib/package.js#L145-L160

**Comment by guybedford** [comment]
Yes a comprehensive handling of this case is definitely needed.

**Comment by guybedford** [comment]
This has been reworked in jspm 0.17 now.
