### ISSUE TITLE
JSPM unable to load packages

### ISSUE THREAD

**Issue by voodooattack** [jspm/jspm-cli#1467]
I've made a small test case here: [jspm-bugs.zip](https://github.com/jspm/jspm-cli/files/103263/jspm-bugs.zip)

When trying to load `sequelize` I get the following:
```
[voodooattack ~/dev/jspm-bugs] node test.js 
[Error: ENOENT: no such file or directory, open '/home/voodooattack/dev/jspm-bugs/pg-hstore.js']
[voodooattack ~/dev/jspm-bugs] 
```
or
```
[Error: ENOENT: no such file or directory, open '/home/voodooattack/dev/jspm-bugs/mysql.js']
```

Apparently `sequelize` is trying to load the `mysql` and `pg-hrestore` packages but fails to do so, even when they are manually installed and are available in `jspm_packages/`.

**Comment by voodooattack** [comment]
I upgraded to 0.17-beta.5, and after some tinkering, now I get this error:
```
Unhandled rejection Error: Installing `npm:sshpk@1.7.3`, no version match for `npm:ecc-jsbn@>=0.0.1 <1.0.0`
```

**Comment by guybedford** [comment]
@voodooattack nice work getting that far! For your last issue, cross-package json resolutions don't resolve properly in jspm 0.16. I'd suggest trying the jspm 0.17 beta if you can here as it comes with improved npm install support which definitely covers that specific bug.
