### ISSUE TITLE
BundleSFX doesn't have literal at header in Global mode

### ISSUE THREAD

**Issue by davinkevin** [jspm/jspm-cli#1470]
Hi, 

I facing a problem to use a library I build with JSPM in other JSPM project (I can made modification in both project).

In the version 0.16.23, when I use the following build task : 
```
gulp.task('build:jspm', (cb) => {
let options = {
        sourceMaps: true,
        globalDeps: { angular : 'angular', oidc : 'OidcTokenManager'},
        format : 'global'
    };

    new jspm.Builder()
        .buildStatic(`${paths.app.entryPoint} - angular - oidc`, `${paths.releaseDir}/${paths.app.name}.js`, options)
        .then(() => cb())
        .catch((ex) => cb(new Error(ex)));
});
```

I have in the file some headers linked to the globalDeps :  
```
"format global";
"globals.angular angular";
"globals.OidcTokenManager oidc";

...
```

But since the version 0.16.24 (and 25 also), those headers aren't written, so when I import my library in other JSPM project, the system don't know it has to load the global dependencies first... leading to `XXXX is not defined`.

Do I misunderstand something or is it a bug ? If you have an idea of better implementation, I'll be glad to hear it.

For now, I stay in 0.16.23.

Thanks 

/cc @aubm

**Comment by guybedford** [comment]
Try outputting to UMD instead of a global via `--format umd`. It's a better way to declare dependencies. If you want the headers back, you can run a custom build via https://github.com/jspm/jspm-cli/blob/master/docs/api.md#class-builder and set `formatHint: true` in the build options.

**Comment by davinkevin** [comment]
Thanks for your answer, but I want to know if this solution (the UMD packaging) allow people using my lib with bower (for example) to import it and using it ?

**Comment by guybedford** [comment]
@davinkevin if you set `--global-name myGlobal` as well it will output a global object, so it will work with any module format.

**Comment by davinkevin** [comment]
Thanks, but after searching, I don't find the syntax in the JSPM Builder API for the "--global-name myGlobal".

I build only with https://github.com/jspm/jspm-cli/blob/master/docs/api.md#class-builder because I have all in gulp tasks.

I'll try to do a PR on this page when I'll found all the solution for my case : https://github.com/jspm/jspm-cli/blob/master/docs/publishing-packages.md

**Comment by guybedford** [comment]
In the builder API it is just `globalName`. The options can be seen in https://github.com/systemjs/builder/blob/master/lib/builder.js#L411.

**Comment by guybedford** [comment]
Ah as you found... the current doc structure doesn't really scale, but happy to consider a PR if it can fit into the existing flow in a way that makes sense.
