### ISSUE TITLE
Rate limit reached – Teamcity build

### ISSUE THREAD

**Issue by ashleynolan** [jspm/jspm-cli#1472]
This one is more of a question we are having when integrating JSPM into our Teamcity build process, rather than an issue directly with JSPM.

When we have been testing out switching to using JSPM as part of our build, we’ve started seeing the 'Github Rate limit' message appear do to too many requests from our build server.  I’ve seen a previous issue relating to this #20 , and subsequently how to configure authorisation for [Travis builds](https://gist.github.com/topheman/25241e48a1b4f91ec6d4).

I was wondering how this might apply for a build server such as Teamcity and if anyone has any idea how to configure the auth to ensure this doesn’t happen.  Has anyone had any experience of this, or know if this is possible?

**Comment by m4r71n** [comment]
@ashleynolan I've executed jspm on the TeamCity buildagent as the same user the agent runs and set up git credentials.
Alternatively you can try jspm [0.17.0-beta.5](https://github.com/jspm/jspm-cli/releases)

> The GitHub registry will always download the git tree tag or branch directly instead of checking for uploaded release archive assets. As a result GitHub API credentials are no longer necessary.

**Comment by ashleynolan** [comment]
Will try upgrading to 0.17 – thanks for the advice
