### ISSUE TITLE
Applying babelOptions to jspm-loader-css package in 0.17 beta

### ISSUE THREAD

**Issue by bhavinkamani** [jspm/jspm-cli#1473]
I upgraded jspm from `0.16` to the latest `0.17.0.beta-5`. All went fine except this - It throws following error

```
systemjs-babel-browser.js:8 [BABEL] Note: The code generator has deoptimised the styling of "http://localhost:5000/jspm_packages/npm/jspm-loader-css@1.0.1-beta1/autoprefixer.js" as it exceeds the max of "100KB"
```
I am using `jspm-loader-css` to leverage css-modules with react. `autoprefixer.js` which is part of that modules, indeed is more than 100kb and does not required to be passed to `babel`. So I added `ignore` babelOptions within `jspm.config.js`. However, it is still giving the same error. 

Here what my `jspm.config.js` looks like

```
packages: {
   ......
    "npm:jspm-loader-css@1.0.1-beta1": {
      "map": {
        "css-modules-loader-core": "npm:css-modules-loader-core@1.0.0",
        "debounce": "npm:debounce@1.0.0",
        "path": "npm:path@0.12.7",
        "toposort": "npm:toposort@0.2.12"
      },
      "meta": {
        "*.js": {
          babelOptions: {
            "ignore": ["**/autoprefixer.js"]
          }
        }
      }
    },
   ......
}
```

**Comment by guybedford** [comment]
@bhavinkamani if after installing you look at the file `jspm_packages/npm/jspm-loader-css@1.0.1-beta1.json` you will see that it has `format: 'es6'` set. This means that all modules inside the package are treated as es6 modules.

You can alter this package configuration file to read:

```javascript
{
  "main": "index",
  "format": "es6",
  "meta": {
    "autoprefixer.js": {
      "format": "global"
    }
  }
}
```

Which is how to ensure a module does not run through babel in SystemJS as it only runs es6 modules through babel.

The above configuration will work in an override, although it would be good to send a PR back to the jspm-loader-css project so that it can have jspm 0.17 support.

**Comment by bhavinkamani** [comment]
@guybedford Thanks a lot. I was able to override the settings. However, now its throwing following error.

```system.js:4 Uncaught (in promise) Error: __moduleName is not defined(…)```.

This one appears to be due to incompatibility between `0.17` and `jspm-loader-css` project. Is there any brief guidelines on what is required to make this project compatible with `0.17`, as I am new to this codebase.

**Comment by bhavinkamani** [comment]
@guybedford I went through [systemjs/builder#416](https://github.com/systemjs/builder/issues/416). This seems to be a babel transpilation issue and I guess it requires changes within each of the supported transpilers.

Would you suggest me to wait for it to be fixed in babel before checking `jspm-loader-css` plugin?

**Comment by guybedford** [comment]
@bhavinkamani yes proper build support for __moduleName is only provided in Babel 6, but you shouldn't need the jspm loader project to work bundled since it is only needed during builds and in the browser development?

**Comment by bhavinkamani** [comment]
@guybedford Thats true. I require it only during browser development and during builds. Since `jspm-loader-css` ships in `esm` format, the latest `systemjs-plugin-babel` is unable to transpile it on browser during dev flow. Hence I can't use `0.17` for my development flow. Am I missing something?

**Comment by guybedford** [comment]
@bhavinkamani right, this will work pending the Babel upgrade in https://github.com/systemjs/plugin-babel/issues/12.
