### ISSUE TITLE
Bundling and Paths

### ISSUE THREAD

**Issue by keitwb** [jspm/jspm-cli#1474]
I'm trying to bundle a project's third-party library modules into a single file but I keep running into an apparent conflict between the `paths` config and the `bundles` config.  It seems that the `paths` config is somehow overridding the bundles config so that the loader is trying to load modules individually from their installed location instead of the library bundle that I created.

The relevant parts of `config.js` look like this:

```
...
  paths: {
    "github:*": "vendor/github/*",
    "npm:*": "vendor/npm/*"
  },
  bundles: {
    "libs.js": [
      "npm:redux-actions@0.9.1",
      "npm:redux-actions@0.9.1/lib/index",
      "npm:redux-actions@0.9.1/lib/createAction",
      "npm:redux-actions@0.9.1/lib/handleAction",
      "npm:redux-actions@0.9.1/lib/handleActions",
      "npm:flux-standard-action@0.6.0",
      "npm:redux-actions@0.9.1/lib/ownKeys",
      "npm:reduce-reducers@0.1.1",
....
```

Where `vendor` is the place where I've configured `jspm install` to put all of the downloaded packages.

When I run the following in the browser:
```
    <script src="https://static.dev/js/vendor/system-csp-production.src.js"></script>
    <script src="https://static.dev/js/config.js"></script>
    <script>
      System.baseURL = 'https://static.dev/js';
      System.import('cm/index.js');
    </script>
```
it completely skips loading the `libs.js` bundle and proceeds to try and load each individual module, which fails because I'm using the CSP build that can't handle CommonJS modules.

If I manually delete the `paths` config from `config.js`, then everything loads correctly from `libs.js`.

My current workflow is to run `jspm install` and then `jspm bundle --inject 'cm/*/** - [cm/*/**]' libs.js`, (where 'cm' is the application code itself) which gives me both the `paths` and `bundles` config.  Am I using the tool wrong, or is there some workaround to this without having to manually (or even programmatically apart from jspm) delete `paths` from the config file?

Thank you.

```
$ jspm -v
0.16.24
```

**Comment by guybedford** [comment]
Everything looks fine. I think the issue is that you must set the baseURL before including the configuration file.

**Comment by guybedford** [comment]
(also it is advisable to always do `System.config({ baseURL: '...' })`, as that will then warn about this case as well)

**Comment by keitwb** [comment]
Thank you, setting `baseURL` before the config loads did the trick.  I'm setting `baseURL` outside of the config.js primarily so I don't have to templatize the config file with the static URL which might change between environments, it just helps keep the workflow a bit simpler.  I never could find a way to set `baseURL` in the config.js file in such a way that it can be populated from an envvar and survive injections from jspm (setting `baseURL` in `.jspm/config` didn't seem to have any effect), but if you know how to do that I would greatly like to know!

Thanks.
