### ISSUE TITLE
0.17.0-beta.5 "Transpiler: None" is handled incorrectly in jspm init

### ISSUE THREAD

**Issue by ryohpops** [jspm/jspm-cli#1477]
At `System.config transpiler` item in `jspm init`, "None" seems to be handled as one of transpiler names, resulting in an error `jspm:plugin-none` not found. I've confirmed this on every Init Mode.

Here is the log for Quick mode:
```
>jspm init

warn Running jspm globally, it is advisable to locally install jspm via npm
     install jspm --save-dev.

Package.json file does not exist, create it? [Yes]: Yes
Init Mode (Quick, Standard, Custom) [Quick]: Quick
Local package name (recommended, optional): app
package.json directories.lib [src]: src
System.config browser baseURL (optional): /
System.config transpiler (Babel, Traceur, TypeScript, None) [babel]: none
     Updating registry cache...

err  Repo jspm:plugin-none not found. Perhaps try jspm install npm:plugin-none.
```

**Comment by guybedford** [comment]
Thanks, fixed in https://github.com/jspm/jspm-cli/commit/8c542cf866b6d28dae3f711495c0a0d3438cbdcf.

**Comment by eestein** [comment]
@guybedford the same thing is happening on linux for typescript:

`err  Repo jspm:plugin-typescript not found. Perhaps try jspm install npm:plugin-typescript.`

This happens when I try to jspm init using TypeScript as transpiler. FYI, it works on my Mac.

Thanks.
