### ISSUE TITLE
bundle-sfx removes comments

### ISSUE THREAD

**Issue by andrenarchy** [jspm/jspm-cli#1478]
`bundle-sfx` currently removes all comments (jspm 0.16.25). There should be a flag for keeping comments. This is particularly useful for including license comments in the resulting code.

My bundling chain is:
```
jspm (with typescript transpiler; generates es6) -> babel (generates es5) -> uglifyjs
```
Since uglifyjs removes all comments except license comments it'd be enough to keep all comments in the jspm bundling step.

**Comment by guybedford** [comment]
Sure, let's track this in https://github.com/systemjs/builder/issues/489.

**Comment by guybedford** [comment]
Actually there is already an issue for this at https://github.com/systemjs/builder/issues/329 as well.

**Comment by andrenarchy** [comment]
Hmm, the linked issue only addresses license comments. Perhaps there's an easier solution for keeping *all* comments?

**Comment by micaelmbagira** [comment]
Any update about this one, to allow comments in general, not only license comments ?

**Comment by guybedford** [comment]
@micaelmbagira this should be supported in the next best release.
