### ISSUE TITLE
peerDependencies to prompt for normal dependencies to behave as peerDependencies

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#1479]
If I have a peerDependency in my app called `angular`, then whenever a normal dependency of another dependency is called `angular`, we should provide the peerDependency conflict resolution prompts.

There can be an option in this specific conflict resolution case, to allow the dependency to remain encapsulated, or to revert to the peerDependency option.

That would solve the multi-registry fork resolution problem quite nicely through this "viral" property of peerDependencies.

**Comment by Nehon** [comment]
It would be nice indeed and would solve https://github.com/jspm/jspm-cli/issues/1401#issuecomment-177430153

However, let's say I have a continuous integration plan that pulls the sources and install all dependencies (I actually do, heh). If a prompt pops out during this process there will be no one to answer and it will stall the plan.

It's would be nice to be able to provide hints in the config file, so that jspm knows how to auto resolve those conflicts.
For example ; favor npm registry or favor github registry.
Easier said than done, I guess...

**Comment by guybedford** [comment]
@Nehon CI installs should always be using `jspm install` with no arguments that means running the config version lock which would never prompt for resolution questions as it has all the resolutions.

**Comment by Nehon** [comment]
oh uh... duh, I had not realized that. But that makes sense.
I'm all for it then ;)

**Comment by Shrulik** [comment]
What is the correct workaround for now ? 

Adding the following to package.json : 
```javascript
    "jspm": {
        "overrides": {
            "npm:angular-material@1.0.7": {
                "map": {
                    "angular": "npm:angular@^1.5.3",
                    "angular-animate": "npm:angular-animate@^1.5.3",
                    "angular-aria": "npm:angular-aria@^1.5.3",
                    "angular-messages": "npm:angular-messages@^1.5.3",
                    "css": "github:systemjs/plugin-css@0.1.20"
                }
            }
        }
    }
```

Isn't enough. After doing this, jspm install would ignore the override and use angular from github for npm:angular-material. I had to remove the github:angular and npm:angular-material packages manually  jspm.config.js and add the similar (Hard coded versions are a must, can't use ^  in packages): 

```javascript
packages: {
        "npm:angular-material@1.0.7": {
            "map": {
                "angular": "npm:angular@1.5.3",
                "angular-animate": "npm:angular-animate@1.5.3",
                "angular-aria": "npm:angular-aria@1.5.3",
                "angular-messages": "npm:angular-messages@1.5.3",
                "css": "github:systemjs/plugin-css@0.1.20"
            }
        }
}
```
