### ISSUE TITLE
after bundleSfx Uncaught ReferenceError: angular is not defined for angular-bootstrap

### ISSUE THREAD

**Issue by rdehuyss** [jspm/jspm-cli#1481]
Hi,

## Short story:
I can't get angular-bootstrap (`jspm install angular-bootstrap`) working after building the app using the jspm plugin (bundleSFX) in gulp. After building and navigating to page with bundled javascript, I get `Uncaught ReferenceError: angular is not defined`

### First of all: the versions I'm using:
`jspm --version` => 0.16.25
`SystemJS (downloaded in jspm_packages)` => SystemJS v0.19.17

### To reproduce
```
git clone https://github.com/AngularClass/NG6-starter.git
cd NG6-starter
git checkout jspm
```

Then, open the `package.json` and `jspm.config.json` to change all version references from `plugin-css` to version @0.1.20 (otherwise when running the builded version, one will have problems with `Uncaught ReferenceError: System is not defined`). See AngularClass/NG6-starter#55 for more info.

If on windows, change line 19 in Gulpfile.js with `return path.relative(root, path.resolve(path.join(root, resolvePath, glob)));`. See AngularClass/NG6-starter#57 for more info.

continue with
```
jspm install angular-bootstrap
npm i
gulp build => fails
jspm install npm:clean-css --dev
gulp build => succeeds
cd dist
ws (assuming you have local-web-server)
```
Open a browser and go to [http://127.0.0.1:8000/](http://127.0.0.1:8000/)
All is still well! Yeey!

Now, in app.js change the top of the file to the following to include angular-bootstrap: 
```
import angular from 'angular';
import 'angular-ui-router';
import 'angular-bootstrap';
import Common from './common/common';
import Components from './components/components';
import AppComponent from './app.component';
import 'normalize.css';

let appModule = angular.module('app', [
	'ui.router',
	'ui.bootstrap',
	Common.name,
	Components.name
])
.directive('app', AppComponent);
```

In a command prompt:
```
gulp build
cd dist
ws (assuming you have local-web-server)
```
Open a browser and go to [http://127.0.0.1:8000/](http://127.0.0.1:8000/)
White page => console shows `Uncaught ReferenceError: angular is not defined`

What did I try to solve this issue:

1. Add the following in the jspm.config.js as the issue does not exist for `angular-ui-router` (Hey, it works there so why wouldn't it work here ;-) )
In the map part of jspm.config.js: add the following (it was not there):
   ```
      "github:angular-ui/bootstrap-bower@1.1.1": {
         "angular": "github:angular/bower-angular@1.4.9"
       },
   ```

   No success, same issue.

2. RTFM  and some [googleing](https://github.com/jspm/registry/issues/40)
3. I doublechecked if there is a shim for angular-bootstrap in the jspm [package-overrides](https://github.com/jspm/registry/blob/master/package-overrides/github/angular-ui/bootstrap-bower%400.12.0.json). Possible issue as the version of angular there is `~1.2.0` while the version we have is `1.4.9`. However, if I understand [jspm issue 40](https://github.com/jspm/registry/issues/40) correctly, I think that the fix I did in nr.1 should do it...
4. Some more [googling](https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#meta) and [reading](https://github.com/systemjs/systemjs/issues/518)
5. In the same jspm.config.js added the following at the bottom:
   ```
   meta: {
       "angular-bootstrap": {
         "deps": [
           "angular"
         ]
       }
     }
   ```
   No success, same issue.

6. Creating this issue... 

Any idea what I'm doing wrong? I really like jspm (especially the dependency management part!) but I'm blocked on this one... I am a noobie on all this, but I did my best on trying to find a fix for this.

**Comment by rdehuyss** [comment]
Perhaps related:

when running 
`jspm install angular2-now=github:pbastowski/angular2-now -o "{shim: {'angular2-now': ['angular']}}"`

and then changing `app.js` to

```
 import {State, SetModule, Inject, View, Component, bootstrap} from "angular2-now";

SetModule('app', []);

@Component({
    selector: 'app',
    template: '<h1>angular2-now Application</h1>',
    services: ['$http']
})
//@Inject('$http')
class App {
    constructor($http) {
        console.log('@ app: $http: ', $http);
    }
}

bootstrap(App);
```

I also get `Error: angular is not defined`.

Also changing jspm.config.js to add a dependency from angular2-now to angular does not work. Any idea's?

**Comment by rdehuyss** [comment]
@guybedford if a github project to reproduce this helps, just give a shout!

**Comment by guybedford** [comment]
This is just about ensuring that the shim is configured correctly such that angular is loaded before executing the given file. Dependency shims need to be configured for the specific file.

It sounds like you are using jspm 0.17 beta. In that case, you can simply edit `jspm_packages/github/path/to/angular-bootstrap@x.y.z.json` and ensure that the `meta` configuration is correctly setting `deps` on angular for the file that is giving the error that angular is not defined.

Alternatively you can do the override approach as well here.

**Comment by rdehuyss** [comment]
I'm not following completely:
- I'm using jspm version 0.16.25 (see above)
- the dependency I'm installing (angular-bootstrap) is known in the JSPM registry
- in the `jspm_packages/github/angular-ui/bootstrap-bower@1.1.1` is a `package.json` as below which looks correct:
    ```
       {
      "name": "angular-ui-bootstrap",
      "version": "1.1.1",
      "description": "Bootstrap widgets for Angular",
      "main": "index.js",
      "repository": {
        "type": "git",
        "url": "https://github.com/angular-ui/bootstrap.git"
      },
      "peerDependencies": {
        "angular": ">= 1.4.0-beta.0 || >= 1.5.0-beta.0"
      },
    }
    ```
   
- If I do the override (which adds the following to `package.json`), the issue is still there...
   ```
   "overrides": {
         "github:angular-ui/bootstrap-bower@1.1.1": {
           "main": "index.js",
           "dependencies": {
             "angular": "jspm:angular@1.4.0"
           }
         }
       }
   ```

Do note that this is only after a **jspm bundle-sfx**.

**Comment by rdehuyss** [comment]
I forked the repo, fixed all the issues, included the result of the build and now you can see the error here thanks to git html preview: [https://htmlpreview.github.io/?https://github.com/rdehuyss/NG6-starter/blob/jspm/dist/index.html](https://htmlpreview.github.io/?https://github.com/rdehuyss/NG6-starter/blob/jspm/dist/index.html)

P.s.:thx for the support, we really appreciate it!!

**Comment by rdehuyss** [comment]
@guybedford: I just pinpointed it: it is related due to jspm.bundleSFX(). If I use jspm.bundle(), all is well. This [blogpost](http://code.rawlinson.us/2015/11/jspm-bundling-options.html) gave me the hint I needed.

What do you want to do with this issue? I am still quite sure it is an issue when creating a single self-executing bundle... (But hey, I have a workaround :-) )

Thx again for an excellent library!

**Comment by guybedford** [comment]
@rdehuyss the issue will likely still come up at some point. It has to do with the main js file not explicitly depending on angular. Basically the shim needs to be configured correctly.

**Comment by bverbist** [comment]
@rdehuyss Had the same issue and was able to fix it with this override:

jspm install angular-bootstrap=github:angular-ui/bootstrap-bower@~1.2.4 -o "{ registry: 'jspm', main: 'ui-bootstrap-tpls', 'format': 'cjs', dependencies: { angular: '1.5.0' }, shim: { 'ui-bootstrap-tpls': { deps: ['angular'] } } }"

Afterwards running the sfx bundled js file worked without erros. Depending on the js file and version you use from angular-bootstrap, you'll have to tweak the above override.
