### ISSUE TITLE
Cannot run jspm.init() programmatically

### ISSUE THREAD

**Issue by MTyson** [jspm/jspm-cli#1482]
I've followed a couple threads on running JSPM programmatically, but I don't see any steps on running init.  I want to take an empty directory and by passing in parameters, get the results of running jspm init at the commandline and responding to the UI prompts.

If I try to run jspm.install("foo") on an empty dir, I get ui prompts, probably because it detects that the project is not initialized yet.

So, given an empty project dir, is there a way to run jspm.init() with some config arguments and get the results of running jspm init from the cl?

**Comment by guybedford** [comment]
Yes there is no init exposed through the API, that's mainly because the API doesn't currently provide a good way to handle these prompts. You can use `jspm.useDefaults()` to ensure that the prompts are all skipped. Contributions always welcome to extend the API.

**Comment by MTyson** [comment]
OK.  I may have opportunity to work on this as part of another project.  To be clear, something like this would be the API:

jspm.init({ 
  "prefix-package": true,
  "package.json": "/my-dir",
  "use-transpiler": true,
  "transpiler": "babel"
});

And so on for the other options, maybe using defaults for any unspecified options.
  "use-

**Comment by guybedford** [comment]
It's worth putting some thought to this API. It's nice to have some sort of 1 - 1 correspondence between the CLI and API that is all. I'm not sure between considering adding these options to `jspm init` for a non-prompting version of init, or alternatively to treat the API for this handling the prompts as events.

**Comment by m-a-r-c-e-l-i-n-o** [comment]
@MTyson You could technically skip creating this `init` method and instead write options directly to a `package.json` file, and then call `jspm.install(true)` on it. Had similar requirement and been sucessfully resolving it that way.
@guybedford However, there seems to be an issue with the programmatic `jspm.install(true)`, it doesn't install the system files that reside in the top level of the `jspm_packages` (i.e. `system.src.js`, `system-polyfills.src.js`) folder. I've been using a workaround, but deff not ideal. Also checked the source to see if I could pass in some parameter to make that work, but saw nothing of that sort.

**Comment by guybedford** [comment]
@m-a-r-c-e-l-i-n-o there's a `jspm.dlLoader` method in the API.
