### ISSUE TITLE
Document typescript + babel configuration

### ISSUE THREAD

**Issue by andrenarchy** [jspm/jspm-cli#1483]
It would be great if the documentation includes a brief working example for typescript *and* babel. Since typescript cannot compile directly to es5 if certain es6 features (e.g., generators) are used, the idea is to use typescript for compiling to es6 code and then babel for compiling to es5. It's probably possible but I'm not able to make it work. Simply selecting "typescript" as the transpiler obviously is not enough. :smiley:

**Comment by guybedford** [comment]
You can do this with the following configuration in the config file of jspm 0.17 beta (not 0.16):

```javascript
System.config({
  transpiler: 'babel',
  typescriptOptions: {
    modules: 'es6'
  },
  packages: {
    'app': {
      meta: {
        '*.ts': {
          loader: 'ts'
        }
      }
    }
  }
});
```

**Comment by guybedford** [comment]
(if anything this is a documentation issue for the typescript plugin)

**Comment by andrenarchy** [comment]
Alright, I tried this but it doesn't work at all. Do you know if there's an example that actually works with client-side loading (for dev) and bundling (for production)?

One of the major problems I have with jspm is that it's hard to guess which repo/plugin is actually responsible for accomplishing a task. For example there's the option `transpiler: "typescript"` (which is set by `jspm init`) but there's also `loader: "ts"` (which you recommend here). It would be great to have  a list of currently supported plugins (and a list of deprecated ones).

**Comment by guybedford** [comment]
@andrenarchy `ts` is exactly the typescript loader above. The configuration was not meant to be a copy-and-paste job but a conceptual demonstration of the principles.

**Comment by andrenarchy** [comment]
@guybedford Thanks for your answer, I managed to compile to es5! :+1: 

If anyone's interested in the config: [here](https://github.com/andrenarchy/jspm-typescript-es6-boilerplate/tree/3f90cd5a8c1161999fe5d6000cd7dbd620da7fb7) it is. FYI: there are still 2 issues which are tracked in https://github.com/frankwallis/plugin-typescript/issues/98 and https://github.com/frankwallis/plugin-typescript/issues/99

**Comment by guybedford** [comment]
@andrenarchy thanks so much for posting the issues there, it is exactly by appreciating that all of this is a work in progress and actively reporting issues for broken workflows that things get better.

**Comment by andrenarchy** [comment]
Sure! You do the awesome work here, keep it up! :smiley:

**Comment by ajhyndman** [comment]
Thanks for posting this, @andrenarchy, your boilerplate example is very helpful.
