### ISSUE TITLE
UMD modules are recognized as global modules

### ISSUE THREAD

**Issue by PhilippMi** [jspm/jspm-cli#1484]
HI,

we have a problem when it comes to loading UMD modules with jspm/SystemJS. JSPM recognizes UMD modules as global modules which leads to the issue that the CSP-compatible version of SystemJS is unable to load the module.

To demonstrate the issue, I created a little test repository: https://github.com/PhilippMi/jspm-umd-recognition

I know that this could be solved using overrides but AFAIK overrides should only be used for testing and do not work on transitive dependencies.

**Comment by guybedford** [comment]
If you look at the file that is shown in the error message it is actually `moment@2.11.2.js`, the main entry point alias module. That is written as CommonJS as SystemJS detected moment as CommonJS during the install.

If you alter the moment map, skipping the entry point, to `moment/moment.js` it should work fine. The way to fix via a local app override is exactly `jspm install npm:moment -o "{format:'global'}"`.

**Comment by PhilippMi** [comment]
Thanks for your help. Your solutions fixed the problem but were not exactly what we were looking for because they do not seem like a long-term solution.

What bothers me is why jspm detects UMD modules as CommonJS modules. Is there any possibility (except for overrides) to detect them as UMD modules and creating a UMD entrypoint?

**Comment by guybedford** [comment]
Detection order in SystemJS is well-defined according to https://github.com/systemjs/systemjs/blob/master/docs/module-formats.md#module-format-detection. If you don't want detection, override the format. This is the way jspm is designed to work. Usually CJS interpretation is preferred as it enables CJS circular references to work out, which does not happen with globals.

If you want this package to run as a global for all users, we can always update the override.

Closing for now, happy to answer any further questions you have.
