### ISSUE TITLE
About installing packages

### ISSUE THREAD

**Issue by telekosmos** [jspm/jspm-cli#1485]
Hi
I've noticed a couple of things installing packages. Given a `package.json` with jspm dependencies as
```
// ...
"jspm": {
    "dependencies": {
        "capaj/systemjs-hot-reloader": "github:capaj/systemjs-hot-reloader@^0.5.0",
        "css": "github:systemjs/plugin-css@^0.1.20"
  }
}
```
- system-hot-reloader does not install 0.5.5 (currently the last one). Given the semver [caret ranges](https://docs.npmjs.com/misc/semver#caret-ranges-1-2-3-0-2-5-0-0-4), if I'm not wrong, 0.5.5 should be installed (as it is a **patch update**). (Note this is "fixed" by explicitely `jspm install github:capaj/system-hot-reloader`)
- regarding to css, install two versions of plugin-css, 0.1.12 and 0.1.20.

To reproduce, clone the [NG6-starter jspm branch](https://github.com/angularclass/NG6-starter/tree/jspm). I updated by editing the jspm.config.js and changing the plugin-css version from 0.1.11 to 0.1.20 and got the second install issue

**Comment by ryanlutgen** [comment]
What happens when you run a jspm update?

To my knowledge, since there is an established config file in the repo, a JSPM install installs the versions specified in the config, while update will update the packages AND the config.

**Comment by rdehuyss** [comment]
`jspm update` indeed solves that...

**Comment by telekosmos** [comment]
Indeed; I thought the latest possible version of every package where installed

Cheers
