### ISSUE TITLE
Recommended dev server

### ISSUE THREAD

**Issue by MTyson** [jspm/jspm-cli#1486]
I'm looking for a basic dev server that supports serving JSPM static content and proxying certain requests to a backend API server.  What are folks using for this kind of thing?

**Comment by mikz** [comment]
Shameless plug, I did [jspm-dev-server](https://github.com/mikz/jspm-dev-server) few weeks ago. 
Used it for: hot reload, serving static content, proxying to other web app and http/2.

**Comment by veggiemonk** [comment]
@mikz thanks :smile: 
Nice project!
