### ISSUE TITLE
Warn and correct overrides starting with ^ or ~ in package.json

### ISSUE THREAD

**Issue by nschloe** [jspm/jspm-cli#1488]
I'm trying to install [the Angular leaftlet directive](https://github.com/tombatossals/angular-leaflet-directive) via JSPM (0.17-beta) and needs to specify that the directive depends on [leaflet](http://leafletjs.com/). To this end, I've added

``` js
jspm: {
  // ...
  overrides: {
    "github:tombatossals/angular-leaflet-directive@^0.10.0": {
      "meta": {
        "angular-leaflet-directive.js": {
          "deps": ["leaflet"]
        }
      }
    }
  }
}
```

to the `package.json` as advised on http://jspm.io/0.17-beta-guide/overrides.html.

However, when doing a

```
jspm install
```

the override is simple _removed_ by the cli.

What to make of this?

**Comment by guybedford** [comment]
The override version should not include a version range - `github:tombatossals/angular-leaflet-directive@0.10.0`.

This has come up way to many times before though, so changing the title to possible fix.

**Comment by nschloe** [comment]
I'm rather confused as to why jspm messes around with my config files – the contents of which I have so carefully devised ;) – by default. What I'm used to by npm and bower ist that the files are edited when I do `--save`/`--save-dev` alright, but not by _default_.

**Comment by andrenarchy** [comment]
If jspm is not able to parse `package.json`, it's probably best practice to stop execution and show a meaningful error message to the user.

I think we should open another issue for discussing the way jspm treats config files. After `jspm init` has been called, it's not clear which files (or which sections of `package.json` and `jspm.config.js`) are auto-generated by jspm and which ones are actually user-provided config.

**Comment by guybedford** [comment]
@nschloe yes there have been many complaints about this before. jspm 0.17 has a full diffing configuration system that only saves when making actual config changes.
