### ISSUE TITLE
Allow requiring the React "dev" (unminified) version when bundling

### ISSUE THREAD

**Issue by cdeveas** [jspm/jspm-cli#1489]
Our build process requires bundling/building the code for local development (the wrong way, I know, but it's necessary for the time-being). Before version 0.16.24, we could develop locally this way and were shown valid React error messages. After version 0.16.24, it appears that the bundle step uses the "production" version of React, which hides error messages. This appears to happen under the hood, and is not dependent on which version of React we specify in package.json or config.js; it is only dependent on the version of jspm (and version of SystemJS, I suppose).

**Comment by guybedford** [comment]
In jspm 0.17, this is provided by `jspm bundle react --dev`. See http://jspm.io/0.17-beta-guide/conditional-loading.html for more info.

**Comment by cdeveas** [comment]
Awesome. Thanks!
