### ISSUE TITLE
Persist local overrides

### ISSUE THREAD

**Issue by theefer** [jspm/jspm-cli#149]
When jspm installing packages, there seem to be two different kind of definitions that can take place.

The first one, "aliasing" (e.g. `jspm install jcrop=github:tapmodo/Jcrop@0.9.12`), makes the given package available under an alias by adding a config mapping line to the `config.js` file.

The second, overrides (e.g. `jspm install github:tapmodo/Jcrop@0.9.12 -o '{"main": "js/jquery.Jcrop", "shim": {"js/jquery.Jcrop": ["jquery"]}}'`), configures overrides for the original package by altering the `package.json` file in the `jspm_packages/github/tapmodo/...` local cache.

My general stance is that dependencies should _not_ be committed to the source tree of a projet (e.g. `bower_components`, `node_modules` or `jspm_packages`), only the dependency definition file should be. In the case of jspm, I assume the good practice would be to commit the `package.json`, as well as the `config.js` file to would guarantee locking of versions of transitive dependencies?

So that means the aliasing is also persisted, however the overrides would not be as they are not written to `package.json` or `config.js`. Am I missing some way to persist overrides to a source tree?

If not, should the overrides be written to `config.js` instead? Or else, where?

Currently, I've been adding them to another file that isn't managed by jspm, but that means jspm (and jspm bundle etc) are missing the information.

**Comment by trusktr** [comment]
> Ideally we wouldn't need overrides at all and everything would be in the original package.json files

Ideally, but not realistically due to the fact that not all devs will do it, as simple as it even is. F.e. I asked famous to do it, but they didn't want to add "bloat" to their package.json, unfortunately, so even awareness of jspm doesn't mean they'll do it.

+1 for jspm.overrides in package.json.
