### ISSUE TITLE
jspm adds "buffer" dependency to npm:is-buffer for no reason

### ISSUE THREAD

**Issue by neothemachine** [jspm/jspm-cli#1490]
The [index.js](https://github.com/feross/is-buffer/blob/master/index.js) file of the is-buffer package is really quite simple:
```js
module.exports = function (obj) {
  return !!(obj != null &&
    (obj._isBuffer || // For Safari 5-7 (missing Object.prototype.constructor)
      (obj.constructor &&
      typeof obj.constructor.isBuffer === 'function' &&
      obj.constructor.isBuffer(obj))
    ))
}
```

This is what jspm converts it to:
```js
/* */ 
(function(Buffer) {
  module.exports = function(obj) {
    return !!(obj != null && (obj._isBuffer || (obj.constructor && typeof obj.constructor.isBuffer === 'function' && obj.constructor.isBuffer(obj))));
  };
})(require('buffer').Buffer);
```

Suddenly there's a dependency to 'buffer' and I have no idea why. Am I missing something here?

**Comment by guybedford** [comment]
This is fixed in jspm 0.17 and is a bug yes - we detect in jspm 0.16 npm conversion if a module uses Buffer, simply by the existence of `Buffer` in the source.
