### ISSUE TITLE
Import not working for systemjs-hot-reloader during 0.17 tutorial

### ISSUE THREAD

**Issue by josephrocca** [jspm/jspm-cli#1494]
Following the [guide for 0.17](http://jspm.io/0.17-beta-guide/hot-reloading.html), I put this code in my main.js:

```js
import 'systemjs-hot-reloader/default-listener.js';
export function __reload(m) {
  if (m.component.state)
    component.setState(m.component.state);
}
```

And when I refresh chrome, I get this:

`GET http://172.20.10.8:8080/systemjs-hot-reloader/default-listener.js 404 (Not Found)  system.src.js:4882`

Shouldn't jspm be automatically resolving "systemjs-hot-reloader/default-listener.js" into "jspm_packages/github/capaj/systemjs-hot-reloader@0.5.5.js" or whatever?

Thanks

**Edit:** I've attached my config files which I hope will help with diagnosis.
[jspm.config.txt](https://github.com/jspm/jspm-cli/files/115272/jspm.config.txt)
[package.txt](https://github.com/jspm/jspm-cli/files/115273/package.txt)
[jspm.browser.txt](https://github.com/jspm/jspm-cli/files/115274/jspm.browser.txt)
[config.txt](https://github.com/jspm/jspm-cli/files/115271/config.txt)

**Comment by josephrocca** [comment]
Also, unrelatedly, "defaultJSExtensions" shouldn't be in my config, should it? I didn't add it, but it may have been carried over from 0.16, since I uninstalled that when I realised that 0.17 was available. Either that, or it's being erroneously added by default in 0.17?

**Comment by guybedford** [comment]
From your config file it doesn't look like you have installed systemjs-hot-reloader? There would be a map entry for it otherwise.

**Comment by josephrocca** [comment]
Thanks for your reply! In the map object of `config.js` there is an entry `"systemjs-hot-reloader": "github:capaj/systemjs-hot-reloader@0.5.5",` - the sixth line down. Or am I looking at the wrong thing?

**Comment by guybedford** [comment]
It wasn't in the file you provided?

**Comment by josephrocca** [comment]
Are you sure? When I download config.txt, from the original post, and look inside, this is what I see:

```
System.config({
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "optional": [
      "runtime",
      "optimisation.modules.system"
    ]
  },
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },

  map: {
    "babel": "npm:babel-core@5.8.35",
    "babel-runtime": "npm:babel-runtime@5.8.35",
    "core-js": "npm:core-js@1.2.6",
    "jquery": "npm:jquery@2.2.0",
    "plugin-babel": "npm:systemjs-plugin-babel@0.0.2",
    "systemjs-hot-reloader": "github:capaj/systemjs-hot-reloader@0.5.5",
    "github:capaj/systemjs-hot-reloader@0.5.5": {
      "debug": "npm:debug@2.2.0",
      "socket.io-client": "github:socketio/socket.io-client@1.4.5",
      "weakee": "npm:weakee@1.0.0"
    },
    "github:jspm/nodelibs-assert@0.1.0": {
      "assert": "npm:assert@1.3.0"
    },
...
...
...
(etc.)
```

**Comment by guybedford** [comment]
Ok, `jspm.config.js` is the file used in jspm 0.17, while `config.js` is the file used in jspm 0.16. Perhaps you're mixing up the versions?

**Comment by josephrocca** [comment]
Oh goodness.
```
> jspm -v
0.16.26
```
I don't know how this happened, but I'll remove everything and start fresh. Sorry for the trouble, thanks for your help!
