### ISSUE TITLE
Overrides of "directories.lib" not working for codemirror component

### ISSUE THREAD

**Issue by kwesterfeld** [jspm/jspm-cli#1495]
I am trying to jspm import codemirror. This is what I am using:

```
jspm install codemirror=github:codemirror/codemirror@5.11.0
```

And no matter what I do, I cannot get the whole package to come in. The codemirror distro has all sorts of plugins, addons, themes, etc., and I want to selectively pull those in that I need. I would think jspm would eat this use-case alive!

The package.json for codemirror specifies:

```
 "directories": {"lib": "./lib"},
```

And so it seems that jspm is forcing the use of that, and will not allow override.

The only thing that gets pulled in is codemirror.js and codemirror.css. I tried doing:

```
      "github:codemirror/codemirror@5.11.0": {
        "main": "lib/codemirror",
        "format": "global",
        "dependencies": {
          "css": "github:systemjs/plugin-css"
        },
        "files": [
          "*"
        ],
```

as an override, and various variations on “files”, no dice

I also tried:

```
      "github:codemirror/codemirror@5.11.0": {
        "main": "dist/codemirror",
        "format": "global",
        "directories": {
          "dist": "./lib",
          "addons": "./addons"
        },
        "dependencies": {
          "css": "github:systemjs/plugin-css"
        },
        "shim": {
          "dist/codemirror": {
            "exports": "CodeMirror",
            "deps": [
              "./codemirror.css!"
            ]
          }
        }
      }
```

Also no dice.  

Ideally I would pull the whole package and filter it.

**Comment by guybedford** [comment]
It sounds like you sorted this out by adding a `directories.lib` override via `jspm install github:codemirror/codemirror -o "{directories:{lib:'.'}}"` for https://github.com/codemirror/CodeMirror/blob/master/package.json#L7.

If you think this would make sense for all users, we can potentially provide this in the jspm registry, although it would be interesting to know why this directories.lib was set in the first place if it doesn't include everything you would want.

Also it may also be worth trying `npm:codemirror`. Perhaps the addons are published as separate packages on npm?

**Comment by kwesterfeld** [comment]
When you look at the codemirror distribution, it is true that basic codemirror is handled by it's own declaration of "lib".  That being said, addons, modes, themes, keymaps, etc., are all opt-in.  I was able to "customize" my use of code mirror this way, once I removed the directories.lib handling:
```
import CodeMirror from 'codemirror';
import 'codemirror/theme/elegant.css!';
import 'codemirror/addon/edit/closetag';
import 'codemirror/addon/edit/continuelist';
import 'codemirror/addon/edit/matchbrackets';
import 'codemirror/addon/fold/foldcode';
import 'codemirror/addon/fold/brace-fold';
import 'codemirror/addon/fold/xml-fold';
import 'codemirror/mode/javascript/javascript';
import 'codemirror/mode/xml/xml';
import 'codemirror/mode/css/css';
import 'codemirror/mode/htmlmixed/htmlmixed';
import 'codemirror/mode/markdown/markdown';
import 'codemirror/mode/diff/diff';
import 'codemirror/mode/properties/properties';
import 'codemirror/mode/clike/clike';
import 'codemirror/mode/yaml/yaml';
import 'codemirror/mode/sql/sql';
```

To answer your question, I would believe a jspm registry that preserves the behavior of the default codemirror "lib" inclusion (1 .js, 1 .css), would be great if it also allowed this type of customization.

**Comment by guybedford** [comment]
Ok, it could still be worth considering `npm:codemirror` over the github version, but your approach seems exactly right. Closing, and if you want to check the override into the registry feel free to send a PR.

**Comment by kwesterfeld** [comment]
I realize you closed this, but you are right (of course), installing npm:codemirror brings the whole shebang.  I need to shim the module, however, and I was under the impression I didn't have that flexibility if I pulled the npm: version.

**Comment by guybedford** [comment]
Shimming is supported on npm. The main issue with using npm versions is unnecessary dependencies getting pulled in.
