### ISSUE TITLE
err installing, no version match, installation changes not saved - when installing riot.js

### ISSUE THREAD

**Issue by josephrocca** [jspm/jspm-cli#1496]
Does anyone know what's going on here? Just want to add riot.js to my fresh jspm 0.17 project.
```
> jspm install riot
     Updating registry cache...
ok   Installed npm:riot-route@^2.3.15 (2.3.15)
ok   Installed npm:simple-html-tokenizer@^0.2.1 (0.2.1)
...
...
...
ok   Installed peer https to github:jspm/nodelibs-https@^0.2.0-alpha (0.2.0-alpha)
ok   Installed peer cluster to github:jspm/nodelibs-cluster@^0.2.0-alpha (0.2.0-alpha)

err  Installing npm:sshpk@1.7.3, no version match for npm:tweetnacl@>=0.13.0 <1.0.0

warn Installation changes not saved.
```
Thanks!

**Edit:** Also, I tried `jspm install npm:riot`, and got the same result.

**Comment by guybedford** [comment]
Thanks, that's a bug parsing optional dependencies. Fixed in https://github.com/jspm/npm/commit/49a151628caf335a9776c4579aac26c4042b2c5f pending release.

**Comment by josephrocca** [comment]
No worries. Roughly how long til it'll be working? Hours / days? Really looking forward to finally getting something up and running with jspm.

**Comment by josephrocca** [comment]
All good now (y)
