### ISSUE TITLE
Trying to switch from Webpack and getting ... Error: Unable to calculate canonical name to bundle file:

### ISSUE THREAD

**Issue by born2net** [jspm/jspm-cli#1498]
I am trying to bundle my app which works great by the way when I run it in the browser.
so I am assuming that all is setup properly with System.js and jspm since again, no issues in the browser.

I am using Typescript, but when I bundle I just want to use the already transpiled js files, so Typescript really should not be part of the mix for the bundle.

But I get the error of:

```
root|src>pwd
/cygdrive/c/msweb/studioEnterprise/src
root|src>jspm bundle-sfx ./App.js a.out
     Building the single-file sfx bundle for ./App.js...

err  Error: Unable to calculate canonical name to bundle file:///C:/msweb/studioEnterprise/src/App.js. Ensure that this module sits within the baseURL or a wildcard path config.
         at getCanonicalNamePlain (C:\msweb\studioEnterprise\node_modules\jspm\node_modules\systemjs-builder\lib\utils.js:203:13)
         at getCanonicalName (C:\msweb\studioEnterprise\node_modules\jspm\node_modules\systemjs-builder\lib\utils.js:130:19)
         at C:\msweb\studioEnterprise\node_modules\jspm\node_modules\systemjs-builder\lib\arithmetic.js:96:38
root|src>
```

I tried a bunch of path configs and always the same error :(
this is my config.js https://github.com/born2net/studioEnterprise/blob/master/src/public/config.js

any help is appreciated,

regards

Sean

**Comment by born2net** [comment]
had some progress

**Comment by calbertts** [comment]
What was the solution?
