### ISSUE TITLE
0.17 beta purpose of jspm.config.js & jspm.browser.js

### ISSUE THREAD

**Issue by mmoss** [jspm/jspm-cli#1499]
Understandably, I don't see much documentation for the latest source. Though, as a long-time user, I'm quite curious about the coming changes.

For my development workflow, I'm used to just loading `jspm.config.js`, and bundling things for my deployment workflow. I've attempted to load just `jspm.browser.js`, in place of how I'd normally use `jspm.config.js` (my original thinking being that one supplanted the other for development builds)...

Right now it appears things are working as long as I include the configs like so:

```
  <script src="jspm_packages/system.js"></script>
  <script src="jspm.browser.js"></script>
  <script src="jspm.config.js"></script>
  <script>
    System.import('app/main.js').then(function (main) { main(); });
  </script>
```

I've yet to try out bundling just yet...

**Comment by guybedford** [comment]
Sure, yes documentation will be coming. Separating the browser config allows browser-specific configuration to be separate from the general-purpose configuration. For example `baseURL` has always been effectively a browser configuration set in a config file that was intended for all environments. Separating it into its own config makes a lot more sense and allows easier custom configuration of the browser environment as well.

**Comment by mmoss** [comment]
Got it! Thanks a ton for the clarification. Love the work you guys are doing.

**Comment by leepowellcouk** [comment]
Is this still the preferred method for separating concerns? I've just started using jspm 0.17 beta and see it writes to the main config file with browserConfig and nodeConfig properties.

**Comment by guybedford** [comment]
This was made an optional separation which can be chosen at any time when running `jspm init`.

**Comment by leepowellcouk** [comment]
Thanks. So if I split them, is it possible to pass multiple config files to the cli interface? Or is the browser/node version automatically picked up?

**Comment by guybedford** [comment]
The selection is automatically made. You can use a `--config` flag to pass a custom configuration when using the jspm cli though.

**Comment by leepowellcouk** [comment]
Sorry, that's what I meant - if I was passing a config to jspm cli, would I have to pass through the main config and the browser config files?

**Comment by guybedford** [comment]
@leepowellcouk `jspm build` and `jspm bundle` both support a `--config` flag which can be inline configuration or a config file reference to use for the build or bundle operation.
