### ISSUE TITLE
Bump Registry API version to 2.0

### ISSUE THREAD

**Issue by subesokun** [jspm/jspm-cli#1500]
Hi, I was trying to get jspm-git ready for the new Registry API and I've noticed that jspm@0.17 still reports the API version 1.6 instead of 2.0

https://github.com/jspm/jspm-cli/blob/0.17/lib/registry.js#L67

**Comment by guybedford** [comment]
Thanks, I've included this in https://github.com/jspm/jspm-cli/commit/0f348f6fbad5bf420bc7c4769b6916bff855f406 for the next beta patch.

**Comment by guybedford** [comment]
Fixed in jspm 0.17.0-beta.7.

**Comment by subesokun** [comment]
Thanks :)
