### ISSUE TITLE
map config should override dependencies

### ISSUE THREAD

**Issue by MeoMix** [jspm/jspm-cli#1503]
Hey,

I'm running the following:

`jspm install backbone -o { map: { underscore: 'lodash' } }`

The command completes successfully and `package.json` has the following:

```
      "npm:backbone@1.2.3": {
        "map": {
          "underscore": "lodash"
        }
      }
```

Looking at the installed file, I see:

```
//     Backbone.js 1.2.3

//     (c) 2010-2015 Jeremy Ashkenas, DocumentCloud and Investigative Reporters & Editors
//     Backbone may be freely distributed under the MIT license.
//     For all details and documentation:
//     http://backbonejs.org

(function(factory) {

  // Establish the root object, `window` (`self`) in the browser, or `global` on the server.
  // We use `self` instead of `window` for `WebWorker` support.
  var root = (typeof self == 'object' && self.self == self && self) ||
            (typeof global == 'object' && global.global == global && global);

  // Set up Backbone appropriately for the environment. Start with AMD.
  if (typeof define === 'function' && define.amd) {
    define(['underscore', 'jquery', 'exports'], function(_, $, exports) {
      // Export global even in AMD case in case this script is loaded with
      // others that may still expect a global Backbone.
      root.Backbone = factory(root, exports, _, $);
    });

  // Next for Node.js or CommonJS. jQuery may not be needed as a module.
  } else if (typeof exports !== 'undefined') {
    var _ = require('underscore'), $;
    try { $ = require('jquery'); } catch(e) {}
    factory(root, exports, _, $);

  // Finally, as a browser global.
  } else {
    root.Backbone = factory(root, {}, root._, (root.jQuery || root.Zepto || root.ender || root.$));
  }

}(function(root, Backbone, _, $) {
  console.log('_ is: ', _);
```

Underscore has been installed and is being loaded by Backbone.

Additionally, adding:

```
map: {
  underscore: "lodash"
}
```

to the root level of `jspm.config.js` does not result in all requests for underscore being redirected to lodash.

**Comment by guybedford** [comment]
The issue here is that the config is working, but is being overridden by the config in `jspm.config.js` which also contains this same map value so takes priority.

You can workaround by manually editing the `jspm.config.js` map for underscore to lodash, but we should detect this intent automatically for map overrides like this. It's a little bit complex though because it digs into the heart of the dependency install process, so will take some thought to implement properly.

**Comment by MeoMix** [comment]
You've labeled this as a feature, but it seems like it's a bug to me.

Loading lodash instead of underscore for Backbone libraries is **very** common and, in general, overriding the dependencies of packages seems like common workflow.

Is there a more standard approach to doing this which works?
