### ISSUE TITLE
First tx... + an issue... lazy loading...EXCEPTION: TypeError: AMD module 

### ISSUE THREAD

**Issue by born2net** [jspm/jspm-cli#1504]
First let me say thank you... I am LOVING jspm. I moved to this from Webpack and will soon release my popular project on: http://ng2.javascriptninja.io/  to jspm, well as soon as I resolve this one issue...

I am trying to load a bundle dynamically.
I have my main bundle, and for the lazy loaded bundle I do:

```jspm bundle-sfx src/comps/app1/App1.js out.js --skip-source-maps```
and in the angular2 code I run
```
if (condition){
   return System.import('/dist/public/out.js').then(c => c[name]);
}
```

the problem is that I am getting an error of:

```EXCEPTION: TypeError: AMD module http://localhost:8003/dist/public/out.js did not define```

Is there something special I need to do to be able to load App1 dynamically (lazy load)?

(if I don't bundle lazy loading is working great by the way)...

my config.js is:

```
    ...
    packages: {
        "src": {
            "main": "App",
            "defaultExtension": "ts",
            "meta": {
                "*.js": {
                    "loader": "ts"
                },
                "*.ts": {
                    "loader": "ts"
                },
                "*.css": {
                    "loader": "css"
                }
            }
       ...
```

so as you can see I didn't put any special package entry for App1 (don't think I need to?!?!?!)

tx again for an AMAZING project,
I will make sure I push lots of new devs to jspm and plan on making a video tutorial on jspm workflow which kicks ass... I love working close to the metal which is what jspm allows + TS complication in the broswer, + versioning... WOW!!!! Webpack bye bye...!

regards

Sean.

**Comment by born2net** [comment]
if I run:
```jspm bundle src/comps/app1/App1.js ./dist/public/out.js --skip-source-maps```
I don't get the amd error, when loading out.js, but I can't seem to import the App1.js from inside the out.js

any help is appreciated

**Comment by born2net** [comment]
any help will be appreciated, is this not supported?

http://stackoverflow.com/questions/35278273/how-to-lazy-load-jspm-module-with-angular-2

**Comment by born2net** [comment]
anyone?

**Comment by guybedford** [comment]
Can you share your contents of `/dist/public/out.js` here that wasn't working?

**Comment by born2net** [comment]
Hi Guy,
let me update, once I ran 
```
jspm bundle-sfx src/comps/app1/App1.js out.js --skip-source-maps --inject
```

I no longer got the AMD error, which is good!
but, when I try and load App2 (which embedded inside out.js) I simply don't get any object back (just an empty object literal)

I am using Angular2 so my lazy load is:

```
 return System.import('/dist/public/out.js')
           .catch(function (e) {
               alert('prob loading out.js ' + e);
          }).then(function (e) {
               alert(e);
               alert(e[name]);
               alert(JSON.stringify(e));
               return System.import('App1').then(c => c[name]);
           });
```
but on the alert I just get {}

I think the issue is that maybe the 2nd statement of:
```
return System.import('App1').then(c => c[name]);
```
as it just returns an empty object...
I am sure there is a way to get it working, prob just my syntax,

by the way I moved my project to jspm and love it... it kicks ass compare to Webpack.

and if you want to see the code I use to load, it's here (commented out now :(  )

loadComponent async:
https://github.com/born2net/ng2Boilerplate/blob/master/src/Lib.ts

which is being called from AsyncRoute:
https://github.com/born2net/ng2Boilerplate/blob/master/src/App.ts

tx again

Sean

**Comment by born2net** [comment]
let me know if any ideas...
FYI posted this on ng2 cli project: https://github.com/angular/angular-cli/issues/187

good stuff...

**Comment by guybedford** [comment]
@born2net note that is the correct behaviour - bundle files are empty modules, which define other modules into the registry. You need to load the bundle itself and then load the module you wanted from the bundle.

**Comment by born2net** [comment]
I understand, I wish it actaully loaded my module :)
if you ever find time and can get it to work with ng2 it would be amazing.
I have no doubt that ng2 is going to be THE framework that consolidates the JS world and I can see already that jspm will be the blunder of choice (I love jspm).

if we could just get ng2 to lazy load separate bundles we would be golden!!!

tx again

Sean.

**Comment by guybedford** [comment]
@born2net did you try using the `bundles` config or inject option in jspm? That is designed exactly for this.

**Comment by born2net** [comment]
I do use the 
```
jspm bundle-sfx src/comps/app1/App1.js out.js --skip-source-maps --inject
```
which helped as I don't get the amd error anymore.

however I am still not able to get an instance of my module.

**Comment by born2net** [comment]
I must be getting close, the issue I am having is that after creating the bundle config I get an error of:
```
http://localhost:8003/dist/public/App1 404 (Not Found)
```

basically System.js is trying to load the module from the drive instead of from the bundle

I added bundle config as:

```
  bundles: {
    "main-bundle": [
      "app/App1.ts",
      "app/App1.js",
      "app/App1.ts",
      "App1.ts",
      "App1.js",
      "src/comps/app1/App1",
      "src/comps/app1/App1.ts",
      "/dist/comps/app1/App1",
      "/dist/comps/app1/App1",
      "/dist/comps/app1/App1.ts",
      "/dist/comps/app1/App1.js",
      "comps/app1/App1.js",
      "app1/App1.js",
      "App1",
      "comps/app1/App1.ts",
      "app1/App1.ts",
      "App1",
      "/dist/comps/app1/App1",
      "src/comps/app1/App1.js",
      "src/comps/app1/app1",
      "src/comps/app1/App1"
    ],
```

**Comment by born2net** [comment]
and here is my import in ng2:

```
 return System.import('main-bundle')
            .catch(function (e) {
                alert('prob loading out.js ' + e);
            }).then(function (e) {
                alert(e);
                alert(e[name]);
                alert(JSON.stringify(e));
                return System.import('../../main-bundle/App1').then(c => c[name]);
            });
```

any tips?

**Comment by guybedford** [comment]
Make sure you are including your configuration file after including SystemJS in production and before loading the bundle.

**Comment by born2net** [comment]
well my config.js is injected into my bundles... :/

**Comment by guybedford** [comment]
@born2net does it come at the top, before any of the System.register statements? The point is that the config needs to be already called, before running System.register or System.import.

**Comment by born2net** [comment]
maybe I am wrong, but all I include in my index.html file is: 

<script src="index.min.js"></script>

which is the bundle created by 

```
jspm bundle-sfx src/App.js " + paths.dist + "/" + paths.targetJS + ' --skip-source-maps
```

and so since I am using -sfx the config and System.js will already be inside no?
I assume I am right since everything is working (thus a config exists internally) but just the lazy load doesn't work

Sean.

**Comment by guybedford** [comment]
SFX bundles do not include SystemJS or the configuration. It's a completely different loaderless workflow to bundles.

**Comment by born2net** [comment]
I know that SystemJS, the config and all your modules can be bundled into a single self executing file, which means replacing the setup within your HTML file with a script tag loading the compiled file.
jspm bundle-sfx main, so that's how I load it... (I know it works that way cause it works LOL... putting lazy loading aside) ...

**Comment by born2net** [comment]
I tried to load the config.js inside the html file and still get same old:
```
GET http://localhost:8003/App1.js 404 (Not Found)
```

**Comment by guybedford** [comment]
Well it has the extension now at least! The point is to get the name imported to line up with the name defined by the bundle. If you need to double-check what that should be you can also look at `System.defined` to see the names the bundle has registered, and how they differ from http://localhost:8003/App1.js.

if you've done a bundle inject like that then `System.import('src/comps/app1/App1.js')` is what you're after. Names need to be consistent between client and server. But you really shouldn't be loading a bundle on top of an SFX bundle as that is code duplication. Ideally you want a bundle on top of a bundle. I'd suggest following some existing workflows carefully.
