### ISSUE TITLE
Nodelibs-* licenses

### ISSUE THREAD

**Issue by brycecr** [jspm/jspm-cli#1505]
I was curious what best practice is for using the nodelibs-* bits of code is, in terms of licensing. I noticed a few repos (e.g. nodelibs-http), contain their own Licenses. There, I assume best practice is to include the license in the redistributed software. However, what about for the repos that don't contain licenses? May we consider the jspm Apache license to cover these or should we be doing something else?

Thank you!

**Comment by guybedford** [comment]
The nodelibs libraries are all clones of the libraries at https://github.com/substack/node-browserify#compatibility, so I'd advise checking the originals there for the licenses.

**Comment by brycecr** [comment]
Thanks, guy! 

It appears they are MIT licensed (along with some licenses of their dependencies).
