### ISSUE TITLE
JS warnings in Firefox

### ISSUE THREAD

**Issue by bronzehedwick** [jspm/jspm-cli#1508]
I started a new jspm project with a simple hello world script, and found the following javascript warnings in the Firefox console:

`unreachable code after return statement`

and

`mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create`

Both warnings point to my index.html file.

I didn't see the warnings in any other browser. Should I be worried about these? Or better yet, why are they happening?

Thanks.

**Comment by guybedford** [comment]
Yes Firefox will check all code being used for warnings. This often results in third-party code providing irrelevant warnings which aren't desired.

**Comment by bronzehedwick** [comment]
Got it, thanks!
