### ISSUE TITLE
Typescript doesn't resolve JSPM definitions properly

### ISSUE THREAD

**Issue by playground** [jspm/jspm-cli#1510]
I'm trying to get karma unit tests to work with typescript and jspm. Wherever my spec files are referencing angular2, rxjs or other dependencies, It's throwing errors like these

error TS1148: Cannot compile modules unless the '--module' flag is provided.
error TS2307: Cannot find module 'angular2/testing'.
error TS2307: Cannot find module 'angular2/http'.
error TS2307: Cannot find module 'rxjs/Observable'
error TS2304: Cannot find name 'WeakMap'

The components are loading up fine on the page. It's only when running karma test.

If I manually supply the .dt.ts files such as
in the gulp task, just added those d.ts files. Got further along but getting other errors.

var tsconfig = require('./tsconfig.json');
gulp.task(tasks.typeScript, function () {
var tsProject = ts.createProject(tsconfig);
console.log('compile ts files.', tsconfig);
return gulp.src(['typings//*.ts',
"jspm_packages/npm/angular2@2.0.0-beta.2/src/facade/lang.d.ts",
"jspm_packages/npm/angular2@2.0.0-beta.2/di.d.ts",
"jspm_packages/npm/angular2@2.0.0-beta.2/core.d.ts",
"jspm_packages/npm/angular2@2.0.0-beta.2/http.d.ts",
"jspm_packages/npm/angular2@2.0.0-beta.2/testing.d.ts",
"jspm_packages/npm/rxjs@5.0.0-beta.0/Rx.d.ts",
'src//*.ts'])
.pipe(sourcemaps.init())
.pipe(ts(tsProject))
.pipe(sourcemaps.write('./', { includeContent: false, sourceRoot: '/'+wuSrc }))
.pipe(gulp.dest('./dist/src'));
});

jspm_packages/npm/angular2@2.0.0-beta.2/core.d.ts(11,32): error TS2307: Cannot find module 'angular2/src/facade/lang'.
/Users/jefflu/git_repo/sandbox/wu/angular2-unit-testing/jspm_packages/npm/angular2@2.0.0-beta.2/src/core/application_common_providers.d.ts(1,22): error TS2307: Cannot find module 'angular2/src/facade/lang'.
/Users/jefflu/git_repo/sandbox/wu/angular2-unit-testing/jspm_packages/npm/angular2@2.0.0-beta.2/src/core/application_common_providers.d.ts(2,26): error TS2307: Cannot find module 'angular2/src/core/di'.

**Comment by rolandjitsu** [comment]
I am not sure what @playground is getting there, hard to read. But there are currently some issues with using JSPM and TS. But with the latest release, TS has implemented a way to tell it where the typings are located by using `baseUrl` and `paths` in the `tsconfig.json` file. You can read more [here](https://github.com/Microsoft/TypeScript/issues/6012) about this feature.

But there already is an ongoing discussion on this matter on the TS side, [#6012](https://github.com/Microsoft/TypeScript/issues/6012), and I think this is related to TS and not JSPM.

**Comment by guybedford** [comment]
There is a typings resolution discussion happening at https://github.com/frankwallis/plugin-typescript/issues/102, and the directions there sound promising.

**Comment by born2net** [comment]
+1

**Comment by darkmortem** [comment]
The solution move the file tsconfig to wwwroot/

Thanks to the valuable feedback provided, here are a few more edits required to ensure app runs successfully.

Add the following line to the  wwwroot/tsconfig.json  so that systemjs won’t try to load sourcemaps:

{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": false
  },
  "exclude": [
    "jspm_packages"
  ]
}
