### ISSUE TITLE
bundle deps with 0.17

### ISSUE THREAD

**Issue by rolandjitsu** [jspm/jspm-cli#1511]
I found some info on how to bundle deps ([872](https://github.com/jspm/jspm-cli/issues/872)), but it looks like I only get an empty file when I run:
```shell
  jspm bundle app/**/* - [app/**/*] dependency-bundle.js
```
My `jspm.browser.js` is pretty simple:
```js
SystemJS.config({
	trace: false,
	production: false,
	paths: {
		'github:*': '/jspm_packages/github/*',
		'npm:*': '/jspm_packages/npm/*'
	},
	packages: {
		app: {
			defaultExtension: 'js',
			format: 'cjs',
			map: {
				'./env': {
					'~production': './env.dev'
				}
			}
		}
	}
});
```
And the `jspm.config.js` has only the info added by JSPM upon package install:
```js
SystemJS.config({
	transpiler: false,
	globalEvaluationScope: false,
	packageConfigPaths: [
		'github:*/*.json',
		'npm:@*/*.json',
		'npm:*.json'
	],

	map: {
		'angular': 'github:angular/bower-angular@1.5.0',
		'angular-animate': 'github:angular/bower-angular-animate@1.5.0',
		'angular-aria': 'github:angular/bower-angular-aria@1.5.0',
		'angular-material': 'github:angular/bower-material@1.0.5',
		'angular-material-data-table': 'github:daniel-nagy/md-data-table@0.9.11',
		'angular-messages': 'github:angular/bower-angular-messages@1.5.0',
		'angular-sanitize': 'github:angular/bower-angular-sanitize@1.5.0',
		'angular-touch': 'github:angular/bower-angular-touch@1.5.0',
		'angular-translate': 'github:angular-translate/bower-angular-translate@2.9.0',
		'angular-translate-loader-partial': 'github:angular-translate/bower-angular-translate-loader-partial@2.9.0',
		'angular-ui-router': 'github:angular-ui/ui-router@0.2.18',
		'css': 'github:systemjs/plugin-css@0.1.20',
		'firebase': 'github:firebase/firebase-bower@2.4.0',
		'process': 'github:jspm/nodelibs-process@0.2.0-alpha',
		'rxjs': 'npm:rxjs@5.0.0-beta.1'
	},

	packages: {
		'github:angular-translate/bower-angular-translate-loader-partial@2.9.0': {
			'map': {
				'angular': 'github:angular/bower-angular@1.5.0',
				'angular-translate': 'github:angular-translate/bower-angular-translate@2.9.0'
			}
		},
		'github:angular-translate/bower-angular-translate@2.9.0': {
			'map': {
				'angular': 'github:angular/bower-angular@1.5.0'
			}
		},
		'github:angular-ui/ui-router@0.2.18': {
			'map': {
				'angular': 'github:angular/bower-angular@1.5.0'
			}
		},
		'github:angular/bower-angular-animate@1.5.0': {
			'map': {
				'angular': 'github:angular/bower-angular@1.5.0'
			}
		},
		'github:angular/bower-angular-aria@1.5.0': {
			'map': {
				'angular': 'github:angular/bower-angular@1.5.0'
			}
		},
		'github:angular/bower-angular-sanitize@1.5.0': {
			'map': {
				'angular': 'github:angular/bower-angular@1.5.0'
			}
		},
		'github:angular/bower-angular-touch@1.5.0': {
			'map': {
				'angular': 'github:angular/bower-angular@1.5.0'
			}
		},
		'github:angular/bower-material@1.0.5': {
			'map': {
				'angular': 'github:angular/bower-angular@1.5.0',
				'angular-animate': 'github:angular/bower-angular-animate@1.5.0',
				'angular-aria': 'github:angular/bower-angular-aria@1.5.0',
				'css': 'github:systemjs/plugin-css@0.1.20'
			}
		}
	}
});
```

I am transpiling TS files offline using the TS compiler, so I only need to package the deps installed by JSPM.

Does someone have any indication towards why is the bundled file empty? I haven't been using JSPM that much until the latest release, so I might have misunderstood how to bundle deps.

**Comment by guybedford** [comment]
When running through the command line be sure to quote the expression so it doesn't run through the command-lines own wildcard parsing - `jspm bundle 'app/**/* - [app/**/*]' dependency-bundle.js`.

**Comment by rolandjitsu** [comment]
I actually still get an empty file though. Could it be something about my config?

**Comment by guybedford** [comment]
Can you bundle an individual module correctly via `jspm bundle app/x.js out.js`?

**Comment by rolandjitsu** [comment]
But I do not have any `.js` files. I have TS files that I compile with `tsc` offline. So JSPM does not handle the transpilation.

**Comment by guybedford** [comment]
Then `jspm bundle app/x.ts out.js` then? Note that this won't work if you're using `defaultJSExtensions`.

**Comment by rolandjitsu** [comment]
Ok, so it seems like I had to add the fill path when using the `jspm` command. So instead of `jspm bundle 'app/*.ts'` I had to `jspm bundle src/app/*.ts`. That seems to work, even though it throws:
```shell
err  MultipleErrors: src/app/bootstrap.ts:1:1: Unexpected reserved word import
src/app/bootstrap.ts:1:13: Semi-colon expected
src/app/bootstrap.ts:1:21: Semi-colon expected
src/app/bootstrap.ts:1:26: Semi-colon expected
src/app/bootstrap.ts:3:1: Unexpected reserved word import
src/app/bootstrap.ts:3:8: Semi-colon expected
src/app/bootstrap.ts:3:13: Semi-colon expected
src/app/bootstrap.ts:3:18: Semi-colon expected
```
Which is probably because I do not use JSPM/SystemJS for transpilation. Let me give it a try with the deps.

**Comment by rolandjitsu** [comment]
Nope, `jspm bundle 'src/app/**/* - [src/app/**/*]' dependency-bundle.js` gives me an empty file.

**Comment by guybedford** [comment]
@rolandjitsu did you manage to do `jspm bundle src/app/x.ts`, without any wildcard? The best way to discuss issues here is to isolate specific cases and tackle those.

**Comment by rolandjitsu** [comment]
If I try that it throws those errors above. But is it not required to setup the transpiler if I want to bundle `.ts` files?

**Comment by rolandjitsu** [comment]
And `jspm bundle src/app/x.ts` throws:
```shell
err  Error on fetch for src/app/x.ts at file:///Users/rolandjitsu/Projects/bolijo/src/app/x.ts
  Error: ENOENT: no such file or directory, open '/Users/rolandjitsu/Projects/bolijo/src/app/x.ts'
    at Error (native)
```
Because there is no such file `x`. If I try something that exists, I get the mentioned errors.

**Comment by guybedford** [comment]
@rolandjitsu I was using `x` as an example to find out if you could bundle a single file without using the wildcard syntax.

**Comment by rolandjitsu** [comment]
@guybedford obviously I knew that :) And that is why I completed the comment with `If I try something that exists, I get the mentioned errors.`. So trying to bundle an existing file will throw:
```shell
err  MultipleErrors: src/app/bootstrap.ts:1:1: Unexpected reserved word import
src/app/bootstrap.ts:1:13: Semi-colon expected
src/app/bootstrap.ts:1:21: Semi-colon expected
src/app/bootstrap.ts:1:26: Semi-colon expected
src/app/bootstrap.ts:3:1: Unexpected reserved word import
src/app/bootstrap.ts:3:8: Semi-colon expected
src/app/bootstrap.ts:3:13: Semi-colon expected
src/app/bootstrap.ts:3:18: Semi-colon expected
```
Because I do not use any runtime compiler with SystemJS, I compile my source files offline with `tsc` and I use the option `transpiler: "none"`. So it would be impossible to try to bundle anything that is a `.ts` file. That is why I want to bundle only the deps which do not need any compilation.

I do hope I made this clearer now.

**Comment by guybedford** [comment]
I'm still not sure what the underlying problem is. Here's what I've got so far:

* You get an empty bundle when you run `jspm bundle app/**/*`
* Your package configuration sets the default extension as `.js`
* You have TypeScript files in the `app` folder but don't want to bundle them?

Are you compiling the TypeScript files into JS files in the `app` folder so you just want to bundle all the js files there but not the ts files? Or are you compiling into files that retain the .ts extension?

**Comment by rolandjitsu** [comment]
Yes, so:
- Running `jspm bundle 'app/**/* - [app/**/*]' dependency-bundle.js` gives me an empty bundle
- I do set the default extension as `.js`
- I have `.ts` files in my app folder, and I do not want to compile and bundle them because `tsc` can do that with `tsc -outFile=bundle.js` command

I am compiling everything into a `dist` folder. So the only responsibility that JSPM/SystemJS has, is to load the files in the browser. And what I want is to bundle all the dependencies (angular, firebase, etc.) into one file, because there's too many requests and the page load time is decreased considerably (above 1s).

So again, the compilation of TS is not done by SystemJS/JSPM, it is handled offline by the TS compiler. I do not run TS compilation runtime, because that makes the page load time event worst.

**Comment by guybedford** [comment]
So the js files you want jspm to bundle as `app` are located in a `dist` folder then? If so you would need to use paths configuration to tell SystemJS to load the contents of `app` from `dist`.

**Comment by rolandjitsu** [comment]
Yeah, the transpiled files, by the TS compiler, are all into a `dist` folder. Ok, so in order to bundle depes, it still needs the app files? Even though the deps have nothing to do with the app files? I just want to know if I got that right.

That means that running `jspm bundle 'dist/app/**/* - [dist/app/**/*]' dependency-bundle.js` should work, without having to configure SystemJS, as that would mess with the way the app is running in the browser.

**Comment by rolandjitsu** [comment]
So trying what I asked gives me:
```js
    Building the bundle tree for dist/app/**/* - [dist/app/**/*]...

err  Error on fetch for dist/app/main at file:///Users/rolandjitsu/Projects/bolijo/dist/app/main
  Loading dist/app/bootstrap.js
  Error: ENOENT: no such file or directory, open '/Users/rolandjitsu/Projects/bolijo/dist/app/main'
    at Error (native)
```
I suppose that is because my config for the app is:
```js
packages: {
        app: {
            defaultExtension: 'js',
            format: 'cjs',
            map: {
                './env': {
                    '~production': './env.dev'
                }
            }
        }
   }
```
So it does not point to `dist/app`.

**Comment by guybedford** [comment]
@rolandjitsu in order to bundle the files, it needs the files. So if the files are in a dist folder, SystemJS needs to know where to find them.

Something like:

```javascript
builder.config({
  paths: {
    'app/*': 'dist/*'
  }
});
```

When using the builder API - https://github.com/jspm/jspm-cli/blob/master/docs/api.md#class-builder.

I hope you can understand if I'm not able to respond immediately again on support further here very soon, it's a big time commitment responding to all these messages.

**Comment by rolandjitsu** [comment]
No worries. I understand.

But you may consider letting the user create dependency bundles without needing the app files. And if I'd change the path config, it would break the loading in the brower, as the server is running from `dist`, not at root.

**Comment by guybedford** [comment]
The paths configuration as I provided above allows setting a custom build path while still supporting the package config and without affecting the structure of the names output in the bundle.

**Comment by rolandjitsu** [comment]
I see, so I should do this programatically using the builder. I'll give it a try.
