### ISSUE TITLE
Package config for Foundation Sites, help required

### ISSUE THREAD

**Issue by glen-84** [jspm/jspm-cli#1514]
I'm trying to write package config/overrides for [Foundation Sites](http://foundation.zurb.com/sites/docs/), and I have a number of questions.

1. Is JSPM at a stage yet where this can/should be submitted as a PR to the package repo, or should the registry still be used?
2. Is this default config (http://pastie.org/private/rmludep0bgtt399n51phug) documented somewhere? The main will be from package.json, the format because it's an NPM package? What about the globals process thing and the *.json format thing?
3. I want to get the dropdown menu component working as a standalone module, but with the configuration below I'm getting `Error: Foundation is not defined`. Am I doing something wrong, or is it choking on the circular dependency?
4. Am I supposed to be using `.js` extensions in this file or not?

```json
{
  "main": "dist/foundation.js",
  "format": "global",
  "meta": {
    "dist/foundation.js": {
      "deps": "jquery",
      "exports": "Foundation"
    },
    "js/foundation.core.js": {
      "deps": [
        "jquery",
        "./foundation.util.mediaQuery.js"
      ],
      "exports": "Foundation"
    },
    "js/foundation.dropdownMenu.js": {
      "deps": [
        "jquery",
        "./foundation.core.js",
        "./foundation.util.keyboard.js",
        "./foundation.util.box.js",
        "./foundation.util.nest.js"
      ]
    },
    "js/foundation.util.mediaQuery.js": {
      "deps": [
        "jquery",
        "./foundation.core.js"
      ]
    },
    "*": {
      "globals": {
        "process": "process"
      }
    },
    "*.json": {
      "format": "json"
    }
  }
}
```

Foundation installed using `jspm i npm:foundation-sites`.

Load with `require("foundation-sites/js/foundation.dropdownMenu");`

**Comment by guybedford** [comment]
> Is JSPM at a stage yet where this can/should be submitted as a PR to the package repo, or should the registry still be used?

I assume you mean jspm 0.17 configuration? If so then yes, jspm 0.17 configuration is stable and can be checked into packages directly.

> Is this default config (http://pastie.org/private/rmludep0bgtt399n51phug) documented somewhere? The main will be from package.json, the format because it's an NPM package? What about the globals process thing and the *.json format thing?

This is the standard Node support configuration for jspm packages. Not documented anywhere yet apart from just mentioning that the Node compatibility configuration is automatically generated.

> I want to get the dropdown menu component working as a standalone module, but with the configuration below I'm getting Error: Foundation is not defined. Am I doing something wrong, or is it choking on the circular dependency?

Try using the `globals` option to set the `Foundation` global to the core foundation. Running as CommonJS may be affecting this too, so if Foundation is only designed to be run as a global you could potentially alter the format to global.

> Am I supposed to be using .js extensions in this file or not?

Yes js extensions should always be explicit everywhere, that is the best practice.

**Comment by glen-84** [comment]
1. Yep, 0.17.
2. I guess this will be merged in if you don't include it in the package.json?
3. Where & how do I set that? I have set the format to global (it's in the config above). I think perhaps I bit off more than I can chew, and I should just include the whole thing. :disappointed:

**Comment by guybedford** [comment]
`globals` is a SystemJS meta property (https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#meta).

Perhaps something like - 

```json
{
  "main": "dist/foundation.js",
  "format": "global",
  "meta": {
    "dist/foundation.js": {
      "deps": "jquery",
      "exports": "Foundation"
    },
    "js/foundation.*.js": {
      "globals": {
         "Foundation": "./dist/foundation.js"
      }
    },
    "js/foundation.core.js": {
      "deps": [
        "jquery",
        "./foundation.util.mediaQuery.js"
      ],
      "exports": "Foundation"
    },
    "js/foundation.dropdownMenu.js": {
      "deps": [
        "jquery",
        "./foundation.core.js",
        "./foundation.util.keyboard.js",
        "./foundation.util.box.js",
        "./foundation.util.nest.js"
      ]
    },
    "js/foundation.util.mediaQuery.js": {
      "deps": [
        "jquery",
        "./foundation.core.js"
      ]
    },
    "*": {
      "globals": {
        "process": "process"
      }
    },
    "*.json": {
      "format": "json"
    }
  }
}
```

**Comment by glen-84** [comment]
I couldn't get this to work. There's some weird cyclic dependency where `foundation.core` requires `foundation.util.mediaQuery`, and `foundation.util.mediaQuery` requires `foundation.core`.

It would have been nice to selectively include components, but I don't understand things enough, so I'll just have to import the whole thing.
