### ISSUE TITLE
Ensure jspm properly warns when git is not installed

### ISSUE THREAD

**Issue by evanweible-wf** [jspm/jspm-cli#1515]
In trying out the latest jspm 0.17 beta, the init step is failing for me:

```
› jspm init
Init Mode (Quick, Standard, Custom) [Quick]: Quick
Local package name (recommended, optional): 
package.json directories.lib [src]: src
System.config browser baseURL (optional): /
System.config transpiler (Babel, Traceur, TypeScript, None) [babel]: babel
     Updating registry cache...

err  Repo jspm:plugin-babel not found. Perhaps try jspm install npm:plugin-babel.
```

Node version: 4.3.0
Npm version: 2.14.12

> I am using nvm for this project, if that matters. Globally I have node v0.10.28 and npm v1.4.9.

**Comment by Vanuan** [comment]
Why is that closed? Have you found the problem?

**Comment by Vanuan** [comment]
Ok, after installing git it works. Apparently, jspm 0.17 in contrast to 0.16 doesn't tell you that you're missing git.
