### ISSUE TITLE
Importing custom JS files that aren't part of any package (e.g. Github, npm, custom endpoint)

### ISSUE THREAD

**Issue by miguelcaires** [jspm/jspm-cli#1518]
Hi.

Thanks so much for all your hard work on this!
It's pretty amazing and alleviates a lot of problems, as you're well aware! :+1: 

However, as expected, some difficulties do show up occasionally, to which we need your expertise. 

I'm trying to import a custom JS file into JSPM (more specifically JWPlayer), but I can't seem to figure out the right way to do it.
I'm trying something like this:
`import jwplayer from '../../../../assets/js/lib/jwplayer/jwplayer';`

I can see the actual file being pulled in the Network tab on chrome, but I can't access the global **jwplayer** namespace.

Additionally, is there a way I can reference the file once within the jspm.config.js, and that way not having to use the relative path to the file?
For example: 
`import jwplayer from 'jwplayer'`

Hope you can help.

Thanks a lot!

**Comment by Quirksmode** [comment]
Also having a similar problem, when I am unable to install a package through JSPM and need to reference a local script/library I am unsure on how best to approach this using JSPM. jwplayer is a perfect example, how can I reference it once in the config.js and then be able to use it within all my ES6 modules. I basically need to achieve something similar to the issue outlined here http://stackoverflow.com/questions/15713887/loading-jwplayer-js-using-require-js

This is the solution for requirejs, but how can we solve it using JSPM?

````require.config({
    shim: {
        'jwplayer/jwplayer': {
            exports: 'jwplayer'
        }
    }
});````


So that whenever I need to access the plugin from within a moduel I can simply use 

````import jwplayer from 'jwplayer'````

**Comment by guybedford** [comment]
I'd suggest something like the following here:

```javascript
System.config({
  paths: {
    'jwplayer': '/path/to/jwplayer.js'
  },
  meta: {
    'jwplayer': {
      exports: 'jwplayer'
    }
  }
});
```

with `import jwplayer from 'jwplayer'` in the code. Let me know if you have any luck along those lines. Also it may help to have a look at the SystemJS configuration documentation as well - https://github.com/systemjs/systemjs/blob/master/docs/config-api.md.

**Comment by Quirksmode** [comment]
Many thanks for getting back to me so quickly, I tried adding the script to 'paths' and when I run without building it works great. However, when I try to run systemJS now to do a bundle/build it does not seem to be able to find that file, it kicks out this error:

[Error: ENOENT, open '/path/to/jwplayer']

The path it says it can't open is actually correct so I am not sure why it is unable to open it? My systemjs gulp file is this:

```gulp.task('systemjs-builder', function (cb) {
    // load SystemJS config from file
    jspm.setPackagePath('.'); // optional
    var builder = new jspm.Builder();

    // Build a self-executing bundle (ie. Has SystemJS built in and auto-imports the 'app' module)
    builder.buildStatic(
        config.systemjsBuilder.src,
        config.systemjsBuilder.dest,
        {
            minify: false,
            sourceMaps: false
        }
    ).then(function() {
        cb();
    }).catch(function(err) {
        console.error(err);
    });

});
```

**Comment by guybedford** [comment]
The path should exclude the leading `/` as during builds there is no meaning for "absolute URL" and it gets treated as an absolute file system path.

**Comment by Quirksmode** [comment]
Sadly I already tried removing this and it did not work. As a test I setup a new file called test.js. I placed it at the root (to be 100% certain) and referenced it like so:

```paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
    "test": "test.js"
  },```

When I add ```import test from test``` and run jspm.builder it still gives me the error. Should I be setting any additional paths anywhere else for this to work?

[Error: ENOENT, open '/path/to/test']

**Comment by guybedford** [comment]
This is just standard baseURL configuration. See what the `/path/to` part in the error is and how it differs from what it should be. Then adjust the builder baseURL accordingly. The default baseURL is the same folder the package.json is in, so the test.js file would need to be in that folder in the default case.

**Comment by Quirksmode** [comment]
This is the issue I am having, that path is exactly correct, it actually works when I run it without building. It's the build process that breaks.
```

paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*",
    "test": "test.js"
  },
```

This is where the file is:

`/Users/dave/Files/www/website/frontend/test.js`

This is what the error says:

`[Error: ENOENT, open '/Users/dave/Files/www/website/frontend/test']`

**Comment by guybedford** [comment]
@Quirksmode which versions of SystemJS and SystemJS Builder are you using?

**Comment by Quirksmode** [comment]
I am using JSPM version 0.16.27 which I am assuming has the latest version of SystemJS and SystemJS Builder included?

**Comment by guybedford** [comment]
Ah, that would be a bug. defaultJSExtensions is a hack, so there are so many edge cases. Things get a lot simpler in jspm 0.17. I've added a fix in https://github.com/systemjs/systemjs/commit/60b3fc003140e1097f829e51b1f9d5555d4dd551 and https://github.com/systemjs/builder/commit/299711664d52459eaa49526dca7d4cc08e555c19.

**Comment by Quirksmode** [comment]
Ah great news it's something that can be fixed, thanks for responding so quickly, when do you think this fix will make it into a JSPM version? Just out of interest when will 0.17 be launching, really looking forward to using it.

**Comment by guybedford** [comment]
The 0.17 beta is already out, I'd advise upgrading already if you can. Will post out this update when I can.

**Comment by guybedford** [comment]
These fixes are released now in both branches.

**Comment by miguelcaires** [comment]
Hi guys.

Thank you so much for following up on this.
Piggybacking on the conversation above, I've upgraded to 0.16.29 and the problem still persists, even with a test file in the root folder.

```
paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*",
    "jwplayer": "jwplayer"
  },

  meta: {
    "jwplayer": {
      "format": "global",
      "exports": "jwplayer"
    }
  },
```

File lives in `/Users/miguelcaires/project/frontend/jwplayer`.

Getting the following error:
```
 errno: -2,
 code: 'ENOENT',
 path: '/Users/miguelcaires/project/frontend/jwplayer'
```

Any ideas?

Thanks! :+1:

**Comment by miguelcaires** [comment]
This was just a matter of adding the js extension in the paths for jwplayer.

Thank you.
