### ISSUE TITLE
Koa-style config pipeline? Or jspm.config.d/

### ISSUE THREAD

**Issue by krisdages** [jspm/jspm-cli#1520]
Very happy for the browser vs node duality in 0.17 but still feel a bit trapped by my own ignorance about how things work and the frustration of having hard-won experimental gains lost to pair coding with a bleeding edge compiler :) 

The flexibility of SystemJS is amazing, as is the convenience of the JSPM cli. I would love to use both for their strengths as seems to be the recommended strategy, but there is still the need to retain ownership (and memory) of personalized, persistent customizations that I make to the loader while letting the package manager handle the daily semver shuffle in its own files.  

Another use case with the same perceived solution is maintaining multiple build configurations within the same project. The conditional interpolated properties are a great step toward covering all bases and call attention to the fact that from one configuration to another it is frequently only a few configuration options that vary, which would lend itself to a concise "diff" or programmatic transform that could be versioned or shared as an automation building block instead of getting lost as part of a monolithic copy. just like the many gulp scripts and familiar middleware modules already. A modular pipeline with exports and imports could also permit programmatic adjustments of parameters before or instead of automatically applying the configuration. 

I think the transparency and familiarity of a compile process would also be helpful in overcoming the often opaque and laboriously documented esoterica that hinder many upgrades

**Comment by guybedford** [comment]
What sort of customizations to the loader were you making that didn't survive the upgrade path? The 0.17 is in beta to be able to track upgrade bugs and fix them to make this process smoother so help diagnosing that would be very welcome. Ideally the upgrade path can be smooth if we know these points.

There was a bug with jspm stripping overrides unnecessarily from the package config on upgrade, would this have been related at all.

In jspm 0.17, configurations are modular and properly per-package. In addition we've opened up the ability to have custom configuration files that can be used as extra configuration inputs for operations.

When constructing a manual SystemJS builder instance via `require('jspm').Builder`, the builder options there do provide most compilation hooks as well. Improving documentation for these in-depth mechanisms in SystemJS and SystemJS Builder is a priority currently, which I expect will shed some much-needed light here too.

**Comment by guybedford** [comment]
Happy to continue this discussion anytime.

**Comment by krisdages** [comment]
Things have been a little chaotic here the last couple months. Sorry for the lack of followup ... there are a handful of half-finshed replies probably stuck in localStorage somewhere, but reading over the latest docs I couldn't be more thrilled with the disambiguation and especially the additional breakout of customized config files, which is really what I was going for here. I will try and get a moment today to try it out and see if the use cases I had are covered, but the big worries about losing manual changes and confusion about where and which SystemJS properties were legal in package.json look to have been wiped out.  Thanks!
