### ISSUE TITLE
Bundle Error Unable to import "typescript"

### ISSUE THREAD

**Issue by rmuchall** [jspm/jspm-cli#1523]
jspm version: 0.16.19
typescript version: 1.7.5

I'm receiving the following error when attempting to use the jspm bundle command:
jspm bundle app/main.ts out.js

`Unhandled rejection Error: Unable to import "typescript".
The incorrect instance of System is being used to System.import during builds.
When writing plugins, always use this.import in plugin hooks for the correct loader instance to import utility code.`

This issue is only occurring during bundling. jspm/Typescript is working correctly when using my web browser (Chrome Version 48.0.2564.109 m). The application I'm attempting to bundle just consists of 2 files (main.ts/app.component.ts).

A friend of mine also ran into this problem and informs me that he resolved it by dropping back to jspm version: 0.16.6

JSPM is awesome, many thanks :)

Update:
I've come across a closed issue that is related:
https://github.com/jspm/jspm-cli/issues/1453

Workaround:
I've found that a work-around is to install and use the jspm typescript plugin located here:
https://github.com/frankwallis/plugin-typescript

**Comment by nlwillia** [comment]
I'm running into this as well.  I wanted to start with a barebones example and build on my understanding from there, but part of the reason why I'd be using jspm is to have a consistent solution for managing dependencies in the browser for development and static builds for production, so bundling not working is a roadblock.

What's the difference between choosing `typescript` as the transpiler during `jspm init` and using `plugin-typescript` instead?  Why is transpiler a top-level option to begin with?  Is that just a convenient shorthand for loader configuration under packages or is there something else that's special about it?

**Comment by guybedford** [comment]
Thanks for the clear report, yes this is a bug, I've added a fix in https://github.com/systemjs/builder/commit/cfb05fb9830c53edfe34ecceca669d6353e78714.

The TypeScript plugin is the recommended TypeScript workflow as this entire layer is being deprecated. In jspm 0.17 beta, selecting typescript just installs that plugin directly so everything happens transparently through plugin configuration with nothing special going on.

**Comment by guybedford** [comment]
This fix is released in the latest branches now.
