### ISSUE TITLE
"Failed to parse SourceMap" error with 0.17-beta.6

### ISSUE THREAD

**Issue by bhavinkamani** [jspm/jspm-cli#1526]
I am getting a bunch of "Failed to parse SourceMap:" errors on `Chrome Canary` while running jspm. This also causes source maps to stop functioning on my dev environment. 

This appears to be happening during in-browser transpilation. If I bundle my app code, I don't see these errors and source map is working fine. My config files are [here](https://gist.github.com/bhavinkamani/9f176dcec03576c37244)

**Comment by guybedford** [comment]
@bhavinkamani I take it that is a browser warning? Yes source maps are not currently working for the Babel plugin. I'm aiming to release an update very soon with this.

**Comment by bhavinkamani** [comment]
Thanks @guybedford of the update. These messages are shown in the browser as errors
