### ISSUE TITLE
Angular Messages is currently not shimmed globally

### ISSUE THREAD

**Issue by Quirksmode** [jspm/jspm-cli#1528]
Hi, I keep having to apply a shim override... 

```jspm install angular-messages=github:angular/bower-angular-messages -o "{shim:{'angular-messages':{ deps: ['angular'] }}}"```

...to get Angular Messages working as it does not correctly declare its dependancy to Angular. How can we get this updated so when we run...

```jspm install angular-messages```

...it installs correctly?

**Comment by guybedford** [comment]
The override will save in the package.json file when used like that so subsequent calls to `jspm install angular-messages` will continue to use the same override. Make sure you're running the latest jspm 0.16 version.
