### ISSUE TITLE
Has anyone has any luck getting this to work with Karma JSPM?

### ISSUE THREAD

**Issue by rafi-cengage** [jspm/jspm-cli#1529]
Which config file are we supposed to include? I assume the JSPM config file and not the browser one. Also I keep getting error that Require is not defined. Otherwise this new beta is working well so far in my project... I haven't tested the bundling and packaging and I hope it's as easy as the regular set up I have had to do so far.

**Comment by amenadiel** [comment]
Uh... Why would you keep two configs in parallel?

**Comment by rafi-cengage** [comment]
Sorry I didn't mean to call the jspm.browser.js file a config file. I was talking about that one when I mentioned the second one. Karma-JSPM wants a config file, but when I supply it the jspm.config.js file, it won't work. It says require is not found when I use import/require to bring a package in a test.

**Comment by guybedford** [comment]
This is a third-party project - post an issue there or to the Karma SystemJS project. Test workflows are important definitely, but they fall outside the line of jspm core's immediate responsibilities.
