### ISSUE TITLE
"packages / {package_name} / defaultExtension" config not work in version 0.16.28

### ISSUE THREAD

**Issue by Tiscs** [jspm/jspm-cli#1531]
Execute command ```jspm bundle-sfx src/Main.tsx dist/bundle.min.js --minify``` when package ```jspm``` version is ```0.16.28``` throw exception ```Error on fetch for src/Main.tsx at file:///c:/TeamProjects/jspm-tsdemo/src/Main.tsx.js```, but works fine in version ```0.16.27```.

**Comment by guybedford** [comment]
Can you share your config file here?

**Comment by Tiscs** [comment]
My config file is here.
https://github.com/Tiscs/jspm-react-tsx/blob/9caf8b91ca08ac7b8e59cb743ff85167762fae0e/config.js
And this is the project link.
https://github.com/Tiscs/jspm-react-tsx

**Comment by guybedford** [comment]
Thanks, yes this is a bug, will post out a patch shortly.

**Comment by guybedford** [comment]
Thanks, fixed in 0.16.29.
