### ISSUE TITLE
Making a build after upgrading to 0.17.0-beta.7

### ISSUE THREAD

**Issue by miguelcaires** [jspm/jspm-cli#1532]
Hi. 

I upgraded JSPM to 0.17.0-beta.7. 
In my setup, I'm using Gulp to run a SystemJS build task (which has been working fine till the upgrade), using the code below:

```
gulp.task('builder', function (cb) {
    jspm.setPackagePath('.'); // optional
    var builder = new jspm.Builder();

    builder.buildStatic(
        'app/src/modules/bootstrap',
        'app/dest/js/app.js',
        {
            minify: false,
            sourceMaps: false
        }
    ).then(function() {
        cb();
    }).catch(function(err) {
        console.error(err);
    });

});
```
However, I now keep getting the following error: 

`{ [Error: Error on fetch for app/src/modules/bootstrap at file:///Users/miguelcaires/project/frontend/app/src/modules/bootstrap
	ENOENT, open '/Users/miguelcaires/project/frontend/app/src/modules/bootstrap']
  errno: -2,
  code: 'ENOENT',
  path: '/Users/miguelcaires/project/frontend/app/src/modules/bootstrap' }`

Can you please point out what am I doing wrong?

Thanks a lot!

**Comment by guybedford** [comment]
I assume this is jspm 0.16? Have you got `defaultJSExtensions` set in your config.js file?

**Comment by guybedford** [comment]
Oh right sorry this is jspm 0.17 - in jspm 0.17 extensions need to be included unless using defaultExtension package configuration.

**Comment by miguelcaires** [comment]
Thanks for getting back.

Adding the .js extension fixed the issue for that file. 

Does this mean that I know have to go through **all** of my modules and manually add the .js extension to them?

For instance:
```
import APIService from './api.service';
import PageDataService from './page-data.service';
import TopicDataService from './topic-data.service';
```

to 

```
import APIService from './api.service.js';
import PageDataService from './page-data.service.js';
import TopicDataService from './topic-data.service.js';
```

**Comment by guybedford** [comment]
Package configuration is the way to set extensions in jspm 0.17. Make a package for your app and by default extensions are added.

**Comment by guybedford** [comment]
(https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#packages) and also see the jspm beta guide which explains package config too - http://jspm.io/0.17-beta-guide/package-configuration.html

**Comment by conor909** [comment]
for jspm 0.17 where do you set `defaultExtensions` ?  And do you need to include the full path to every mapped package?

**Comment by supermoos** [comment]
@conor909 did you figure this out?

**Comment by conor909** [comment]
@supermoos I cant remember, I gave up on upgrading to jspm 0.17 because at that time there were too many issues with it.

**Comment by supermoos** [comment]
@conor909 alright :-) @guybedford anyway to configure this defaultJSExtension on the command line with something like: `jspm build build/js/src/Main.js release/js/Main.min.js --minify --skip-source-maps --defaultJSExtensions` or how do you do this with JSPM 0.17?

**Comment by dinoboff** [comment]
In `jspm.config.js`, locate:
```
[...]
  packages: {
    "my-package-name": {
      "main": "my-package-name.js",
      "meta": {
        "*.js": {
          "loader": "plugin-babel"
        }
      }
    }
  }
[...]
```
Add `defaultExtension: 'js'`:
```
[...]
  packages: {
    "my-package-name": {
      "main": "my-package-name.js",
      "defaultExtension": "js",
      "meta": {
        "*.js": {
          "loader": "plugin-babel"
        }
      }
    }
  }
[...]
```

**Comment by supermoos** [comment]
Is there a way to do it without having to define your project as a package?
