### ISSUE TITLE
__dirname is undefined?

### ISSUE THREAD

**Issue by davis** [jspm/jspm-cli#1537]
Not sure how to report this issue, or if it even is an issue, but when I create a server.js
(was following the jspm 0.17 guide)
```
import express from 'express';
import path from 'path';

let app = express();
app.get('/', (req, res) => res.sendFile(path.join(__dirname, 'index.html')));
app.listen(3000);
```

and I do jspm run server.js, when I hit the endpoint i get __dirname is undefined.

Probably not running in a node context?

**Comment by guybedford** [comment]
`__dirname` is not defined in ES modules, only in CommonJS modules. Use `__moduleName` in ES6 modules.
