### ISSUE TITLE
bundling babel-runtime in 0.17

### ISSUE THREAD

**Issue by bhavinkamani** [jspm/jspm-cli#1539]
In my development setup, I am trying to speed up the page load time. Currently, 250+ requests are sent for the first page to load up a simple react based app which ends up taking close to 8 seconds. This is after bundling all of my vendor libraries. Though I am using [systemjs-hot-reloader](https://github.com/capaj/systemjs-hot-reloader), I do need to occasionally refresh my entire page. 

Most of the request are coming from `babel-runtime`. How do I use non-modular babel-runtime or bundle up `babel-runtime`? I saw this [thread](https://groups.google.com/forum/#!topic/jspm-io/Ub2FNS4LQPs). However, I don't see `transform-runtime` as part of the default babelOptions in `jspm.config.js`. I am using `0.17-beta-7`

**Comment by guybedford** [comment]
Certainly bundle everything for the quickest page load. What modules in Babel-runtime are being loaded?

**Comment by bhavinkamani** [comment]
I was able to reduce no of request to 40+ by bundling `babel-plugin-transform-react-jsx`. Most of the request are for the app code This knocked off 2 seconds from my load time.

`transfrom-react-jsx` plugin is still using `babel ^5.0.0`. So It ends up loading the `5.x` version. Even with bundling two versions of `babel runtime` is being loaded. I guess this is out of the realm of jspm unless there is any workaround!!

**Comment by guybedford** [comment]
But you're only using `babel-plugin-transform-react-jsx` right and not `transform-react-jsx` then? Would certainly be faster not to have to load two versions of Babel.

**Comment by bhavinkamani** [comment]
yes I am only using `babel-plugin-transform-react-jsx`. The other version that I was referring to is `systemjs-babel-browser.js` that gets loaded from `systemjs-plugin-babel` by default.

**Comment by guybedford** [comment]
Ok I was just unclear because neither of the above load the Babel 5 version.

**Comment by bhavinkamani** [comment]
Actually `babel-plugin-transform-react-jsx` does load `babel-runtime` [^5.0.0](https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-react-jsx/package.json). 

I am installing `babel-plugin-transform-react-jsx` with which whole lot of other libraries gets installed These I believe are already bundled with `systemjs-babel-browser.js`. 

Is it possible to rebundle `systemjs-babel-browser.js` with additional plugins?

**Comment by guybedford** [comment]
Ah right, yes no it isn't possible because this repo hosts an SFX bundle here only, which doesn't expose the registry for dependency sharing.

**Comment by bhavinkamani** [comment]
Would it make sense to have a babel `loader` that is extendable? Else, for any additional plugins or presets, two babel runtime will get loaded on the browser. 

I am not worried about the load time since mostly this will be used during development from localhost. However, not sure if it will lead to any potential version conflict?

**Comment by guybedford** [comment]
It was a necessary tradeoff of the approach here, and a decision that has been made. Create an sfx bundle for your jsx plugin if you want a faster load, the duplication isn't a big cost.

**Comment by bhavinkamani** [comment]
got it... Thanks
