### ISSUE TITLE
0.17beta-7 build issues

### ISSUE THREAD

**Issue by davis** [jspm/jspm-cli#1541]
running into
```
err  TypeError: Cannot read property 'react' of undefined
    at /Users/davis/workspace/project/node_modules/jspm/node_modules/systemjs-builder/lib/rollup.js:298:37
```
when running
```
jspm build src/step1.js src/step2.js --minify --skip-source-maps --skip-rollup
```

could i provide any more info to help debug?

**Comment by davis** [comment]
```
jspm bundle src/step1.js src/step2.js
``` seems to work fine

**Comment by davis** [comment]
also, for some reason, `jspm install react` doesn't add react to the dependencies in my package.json... could that have anything to do with it?

**Comment by davis** [comment]
I just tried running through 0.17beta walkthrough and can't build that project either
I made an even simpler case

1. install jspm@0.17-beta.7
2. install react-dom
3. create a js file containing only import React from 'react'
4. try building
repro:
```
mkdir test-0.17
cd test-0.17
npm install jspm@beta
alias jspm="./node_modules/jspm/jspm.js"
jspm install react-dom
echo "import React from 'react';" > test.js
jspm build test.js bundle.js
```

**Comment by guybedford** [comment]
Thanks! I think this was fixed in https://github.com/systemjs/builder/pull/503.

**Comment by davis** [comment]
thanks. a somewhat related question -- why do I still run into rollup errors when running `jspm build` with `--skip-rollup?`

**Comment by mikz** [comment]
For anyone who is affected by this. 
You can force the master revision by:

```shell
npm install https://github.com/systemjs/builder/tarball/master --save
``
