### ISSUE TITLE
0.17-beta node and strict-mode

### ISSUE THREAD

**Issue by salfield** [jspm/jspm-cli#1542]
I'm testing out using 0.17 beta with Node. In general working fine as per:

http://jspm.io/0.17-beta-guide/universal-js-with-server-rendering.html

However, I tried to impoty a module which uses es6 features supported by Node under strict-mode, such as "let" and "const" (https://nodejs.org/en/docs/es6/). I'm using Node v5.6.0. This is the module:

https://github.com/koajs/generic-session

When I do:

> jspm run

I get:

`err SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode`

The files in the "generic session" module have "use strict" at the top, so I would expect that they would be executed in strict-mode - and when importing the same module in Node with commonjs imports, everything works.

Is this an issue with jspm/systemjs and Node?

**Comment by guybedford** [comment]
Thanks, I've created a SystemJS issue to track this in https://github.com/systemjs/systemjs/issues/1109.
