### ISSUE TITLE
Split Out Static Settings in Config.js

### ISSUE THREAD

**Issue by casesandberg** [jspm/jspm-cli#1544]
I know that you can call `System.config` twice, once passing in the static settings and the other with the dynamic map stuff. But I would like to split out the files such that the static one doesn't change. Maybe modifying `configFile` such that it can take an array of files? I'm not sure the best way to handle this.

**Comment by guybedford** [comment]
@casesandberg have you tried jspm 0.17? It separates into two config files and allows custom config files as an argument to the CLI commands.

**Comment by casesandberg** [comment]
Ah, thanks. We are using in production and need to wait for `0.17` to be stable.
