### ISSUE TITLE
Workflow for transpiled typescript module with local reference

### ISSUE THREAD

**Issue by unional** [jspm/jspm-cli#1545]
I write my packages in TypeScript.

Since `defaultJSExtension` will be deprecated, I have been referencing local file with extensions, such as `import moduleA from './moduleA.ts';`

When I expose the code directly as TypeScript, things were fine.

Now I try to expose them as `.js` and `.d.ts`.  The problem is that the reference name is not updated by `tsc -d` so I get 404 at runtime. The transpiled code remains in the form of `__export(require('./moduleA.ts'));`.

What is the right workflow for authoring packages in TypeScript?

**Comment by guybedford** [comment]
This is a question without an easy answer. This is certainly a good use case where not including the extensions to allow portability of code between transpiled and untranspiled forms can make sense.

defaultJSExtensions as a feature is being deprecated, but defaulExtension as a per-package option is remaining, so you can certainly continue to use code written without extensions by using this feature.

It's really up to the specific workflow of the project what makes the most sense. Perhaps leaving the `.ts` extension in through the bundling process makes sense, perhaps it doesn't. What gets written into the bundle either way though is a name with the extension. The configuration only acts at the top-level import normalization level as a helper.

**Comment by unional** [comment]
Would it be possible that the `defaultExtension` can be set in the package instead of in the consumer's `jspm.config.json`?

It is quite a hassle for the consumer to know whether each package need special `defaultExtension` handling.

It should just work for the consumer.

**Comment by guybedford** [comment]
Yes `defaultExtension` is designed to go in the package.json file, which is supported in jspm 0.17.

**Comment by unional** [comment]
Oh nice. I was putting in consumer `jspm.config.ks`

**Comment by guybedford** [comment]
All SystemJS package config is supported in the package.json in jspm. Closing, but happy to continue this discuss anytime.
