### ISSUE TITLE
Safe to place jspm.config.js & jspm.browser.js in gitignore?

### ISSUE THREAD

**Issue by speigg** [jspm/jspm-cli#1546]
Is the intention with jspm v0.17 that `jspm.config.js` & `jspm.browser.js` can be accurately recreated from `package.json` after running `jspm install` (and thus can be safely gitignored)? If so, I don't believe this is working yet (`jspm.meta` configuration in `package.json` is not copied to `jspm.config.js`).

**Comment by guybedford** [comment]
jspm.config.js is the version lock and jspm.browser.js is custom config. Both must be checked in.
