### ISSUE TITLE
Loading fonts with JSPM bundle

### ISSUE THREAD

**Issue by fknop** [jspm/jspm-cli#1553]
Hi,

I'm using font-awesome with JSPM, everything works fine without bundle but when I'm trying to bundle my app, I'm getting a 404 : 
`GET 
http://localhost:51314/jspm_packages/npm/font-awesome@4.5.0/fonts/fontawesome-webfont.woff2` with the wrong path (the base path is missing).

I can't find a solution about that !

Thanks.

**Comment by frederikschubert** [comment]
You have to set the font path variable in order to tell font-awesome where the fonts are. Like this:
```sass
$fa-font-path: "./path/to/your/fonts";
```

**Comment by fknop** [comment]
So if I understand correctly, I need to change the sass variable and recompile the all thing ?

**Comment by frederikschubert** [comment]
Yes you have to set the variable and then import the font-awesome scss file.
The fonts are loaded via `url(...)` blocks in the css and those are not loaded by systemjs but with normal xhr requests.

**Comment by fknop** [comment]
Hi,

So I tried what you said. I created a new scss file with only these two lines: 

```scss
@import '../jspm_packages/npm/font-awesome@4.5.0/scss/font-awesome';

$fa-font-path: '../jspm_packages/npm/font-awesome@4.5.0/fonts';
```

I installed the sass plugin with an alias like this: `jspm install scss=sass` and I'm importing my file:

```javascript
import './fa.scss!';
```

When I bundle my app, it works fine, but without bundle, I'm having a 404 on my fa.scss file.

Any idea ?

**Comment by guybedford** [comment]
This is very much a plugin-specific thing. You're loading the font file through a scss plugin right? It would be worth seeing if that plugin has an option for setting the base path, for example, pluginCSS handles this via a `rootURL` option - https://github.com/systemjs/plugin-css#builder-support.

**Comment by Pleasurazy** [comment]
Hi,

I use bootstrap, and I have same problem with jspm v0.16.30 (everything works fine without bundle):

```
import 'bootstrap'
import 'bootstrap/css/bootstrap.css!'
```

If I run sh$ `jspm bundle app/entry public/assets/all.js --inject`

then I get:

![image](https://cloud.githubusercontent.com/assets/1500206/13595604/b83f30d2-e547-11e5-8c9d-58b2ac525b15.png)

expect to GET 200
`http://127.0.0.1:3000/assets/jspm_packages/...`

if I unset `rootURL` will GET 404
`http://127.0.0.1:3000/jspm_packages/...`

if I set `rootURL: "assets"` will GET 404
`http://127.0.0.1:3000/public/assets/jspm_packages/...`

if I set `rootURL: "foo/bar"` will GET 404
`http://127.0.0.1:3000/public/assets/jspm_packages/...`

if I set `rootURL: "/assets"` will GET 404
`http://127.0.0.1:3000/Users/pleasurazy/git/projects/my-cms/public/assets/jspm_packages/...`

if I set `rootURL: "../assets"` will GET 404
`http://127.0.0.1:3000/my-cms/public/assets/jspm_packages/...`

I have no idea, how to solve this problem gracefully.

```
$ jspm init -p

Would you like jspm to prefix the jspm package.json properties under jspm? [yes]:
Enter server baseURL (public folder path) [public/assets]:
Enter jspm packages folder [public/assets/jspm_packages]:
Enter config file path [public/assets/jspm_config_default.js]:
Enter client baseURL (public folder URL) [/assets]:
Do you wish to use a transpiler? [yes]:
Which ES6 transpiler would you like to use, Babel, TypeScript or Traceur? [babel]:
ok   Verified package.json at package.json
     Verified config file at app/assets/jspm_config_default.js

$ node -v
v4.2.6

$ npm -v
3.8.1
```

```
package.json

  "jspm": {
    "directories": {
      "baseURL": "public/assets",
      "packags": "public/assets/jspm_packages"
    },
    "configFile": "public/assets/jspm_config_default.js",
    "dependencies": {
      "angular": "github:angular/bower-angular@^1.5.0",
      "angular-ui-router": "github:angular-ui/ui-router@0.2",
      "bootstrap": "github:twbs/bootstrap@^3.3.6",
      "clean-css": "npm:clean-css@^3.4.10",
      "css": "github:systemjs/plugin-css@^0.1.20"
    },
    "devDependencies": {
      "babel": "npm:babel-core@^5.8.24",
      "babel-runtime": "npm:babel-runtime@^5.8.24",
      "core-js": "npm:core-js@^1.1.4"
    }
  },
```

structure:
![image](https://cloud.githubusercontent.com/assets/1500206/13596168/a506940c-e54b-11e5-86e3-447bcb829779.png)

**Comment by fknop** [comment]
What I did is :

* download bootstrap-less
* create a new less file in my project
* change the font path, include the less bootstrap file
* include my less file with less loader (not the official one tho)
* create a different bundle with static assets so I can develop using the less files

**Comment by fknop** [comment]
Check this issue for the less loader. 
https://github.com/jspm/jspm-cli/issues/1560

**Comment by guybedford** [comment]
@fknop did you try a value of `rootURL: 'public/assets'`?

**Comment by fknop** [comment]
I think you mean @Pleasurazy ! It's working for me ! :)

**Comment by Pleasurazy** [comment]
Hi, @guybedford 

if I set `rootURL: "public/assets",` will GET 404
`http://127.0.0.1:3000/jspm_packages/...`

I have workaround for now, using rails `routes.rb`:

```
  get '/public/*all.:ext', to: redirect(status: 301) {
    |params| "/#{params[:all]}.#{params[:ext]}"
  }
```

**Comment by guybedford** [comment]
@Pleasurazy did you try `rootURL: 'public'`? I think that's the right option here.

**Comment by Pleasurazy** [comment]
Ok, look works now...

Thank you very much for your patience!!!

I can't believe I just never consider about that!
