### ISSUE TITLE
Using linking with directories option in 0.17

### ISSUE THREAD

**Issue by domagojk** [jspm/jspm-cli#1558]
I like the new linking concept in 0.17 version but I cannot use it if I have directories property in my package.json
I version 0.16 i am using directores.lib for my linked repositores
usually defined as: 
`{directories: "lib": "src"}`

in new version I got message saying "dist" should be used insted

> Linked package.json specifies directories.lib, which is deprecated in jspm 0.17. If this is the intended folder to link from the package, set it as  directories.dist instead.

But after changing linked repository package.json to
`{directories: "dist": "src"}`
its dependencies are not mapped

I managed to reproduce this in JSPM 0.17 demo project as well (jspm-react-component-demo) by adding directores.dist and installing "jquey" as its dependecy
After this repository is linked, jquey was not mapped in "main" repo

**Comment by guybedford** [comment]
Thanks, I can confirm this is a bug. The package.json is ignored once we link the subfolder.

**Comment by guybedford** [comment]
Released in 0.17.0-beta.8.

**Comment by domagojk** [comment]
@guybedford 
Thanks, it works for me now, but there is now another issue on beta-8 and that is when there is no "directories" propery and you try to create a link it throws an error:
![screen shot 2016-02-25 at 18 18 52](https://cloud.githubusercontent.com/assets/1868852/13327987/92a2110a-dbec-11e5-9bd3-9576c097661d.png)

when I define
`  "directories": {
    "dist": "src"
  },`
then it works fine
