### ISSUE TITLE
Circular dependencies broken with System.import() - 0.17 beta

### ISSUE THREAD

**Issue by architruc** [jspm/jspm-cli#1559]
The circular dependencies seems broken in the 0.17 beta version and typescript module format _system_ (it works well with 0.16+system or any version+commonjs). Here is an example:

**main.ts / bootstrap.ts:**

``` typescript
// Import A -> B -> A: KO
System.import('src/services/loadme').then(file => {
    console.log("Loaded:", new file.Loadme().myval);
}, err => {
    console.error(err);
});
```

**src/services/loadme.ts:**

``` typescript
export class Loadme {
    myval = "I am loaded!";
}
export {LoadmeChild} from './loadmeChild';
```

**src/services/loadmeChild.ts:**

``` typescript
import { Loadme } from './loadme'; // <<------ Does not work ---------

console.log("I extend Loadme:", Loadme); // Loadme is undefined

// Throws an error: TypeError: Cannot read property 'prototype' of undefined
export class LoadmeChild extends Loadme {
    myval = "I am a child loaded!";
}
```

**index.html:**

``` html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
Check the console for logs

<script src="jspm_packages/system.js"></script>
<script src="jspm.browser.js"></script>
<script src="jspm.config.js"></script>

<script>System.import("src");</script>

</body>
</html>
```

While debugging with JS compiled version, I found that the module _Loadme_ is found but its object of exports is empty.

I don't know if it is a SystemJS issue instead of JSPM.

Thanks for the hard work on these great tools by the way!

**Comment by AdamBurgess** [comment]
>it works well with 0.16+system or any version+commonjs
I tested it with 0.16 and it still didn't work ... I was under the impression that if you want to do cyclic dependencies you need to expose a function/interface to get it, e.g.
```js
import { Loadme } from './loadme.ts!';
console.log("I extend Loadme:", Loadme); // at this point, Loadme is undefined.
export function getClass() {
    console.log("I extend Loadme defined:", Loadme); // now it will be defined
    return class LoadmeChild extends Loadme {
        myval = "I am a child loaded!";
    }
}
```

**Comment by guybedford** [comment]
Yes classes are undefined due to the temporal dead zone (TDZ) that allows classes to extend expressions (`class P extends ...` syntax). Functions will give this behaviour though.

**Comment by architruc** [comment]
@guybedford @AdamBurgess  It actually works with commonjs module. [See plunker here](http://plnkr.co/edit/ueBkUmW8dBzI5xNSbNDX?p=preview). Update tsconfig.json and replace _commonjs_ by _system_ and it fails.

My bad, it was not related to the version but the module format (I thought I was testing 0.16 with system, but it was commonjs). I edited the title to reflect it.

Is it normal? I thought it was a typical usecase of circular dependencies, like node.js where we can have cross imports as long as we export early enough.

**Comment by guybedford** [comment]
Yes, while not ideal, this is exactly how circular references are specified to work in ES6.

**Comment by architruc** [comment]
@guybedford Thanks. So is it supposed to work here with _module: system_ format, the same way as _commonjs_, or the difference is normal?
