### ISSUE TITLE
postinstall script not getting trigger while installing npm package on jspm 0.17 

### ISSUE THREAD

**Issue by bhavinkamani** [jspm/jspm-cli#1561]
As an example [caniuse-api](https://github.com/nyalab/caniuse-api) can be tried. I used `jspm install caniuse-api`. `postinstall` trigger works well when installing via `npm`

**Comment by guybedford** [comment]
Yes jspm does not run install hooks at all. For previous discussion see https://github.com/jspm/npm/issues/36.
