### ISSUE TITLE
problems with koa and 0.17

### ISSUE THREAD

**Issue by paulwalker** [jspm/jspm-cli#1563]
after `jspm install npm:koa` and then simply trying to `import koa from 'koa'` in server.js i get (after `jspm run server.js`):

```
warn Running jspm globally, it is advisable to locally install jspm via npm install jspm --save-dev.

err  Error: ENOENT: no such file or directory, open '/Users/paul/Projects/jspm-test/bluebird'
  Error loading file:///Users/paul/Projects/jspm-test/bluebird as "bluebird" from file:///Users/paul/Projects/jspm-test/jspm_packages/npm/native-or-bluebird@1.2.0/promise.js
    at Error (native)
```

**Comment by guybedford** [comment]
So the issue is that `npm/native-or-bluebird@1.2.0/promise.js` is trying to load bluebird, but it doesn't seem to be installed. You can probably just do `jspm install npm:bluebird`. Alternatively updating your version of Node may trigger that package to know to use native promises instead.

**Comment by paulwalker** [comment]
My version of node is 5.7.0 btw, installing bluebird as you suggested resolved this.

**Comment by AdamBurgess** [comment]
Couldn't this be a bug, though?
in node you can try-catch require() errors, maybe that functionality should be emulated for cjs modules?

**Comment by guybedford** [comment]
@AdamBurgess it would be nice to be able to support try-catch require errors in SystemJS for cjs modules, but the difficulty is that we in SystemJS we separate the loading phase (network async fetch of the whole tree through static analysis) from the execution phase. Execution errors can thus be caught by a try-catch around the cjs require, but network errors throw earlier in the pipeline so immediately reject the top-level import promise. There is likely an override or adjustment that can be made to `native-or-bluebird` to make it behave as desired in jspm though (perhaps taking advantage of conditional package loading to determine if the environment needs promise polyfilling).

**Comment by guybedford** [comment]
If anyone wants to work on a configuration for `native-or-bluebird` just post a registry issue and I'm happy to help there.
