### ISSUE TITLE
Object.assign is not polyfilled

### ISSUE THREAD

**Issue by capaj** [jspm/jspm-cli#1565]
I have an app that I need to run in safari on iphone S6 and when I make a build with JSPM 0.16.29 I would expect it to polyfill `Object.assign()` as this polyfill is included in babel

Problem is it doesn't and my app breaks on any `Object.assign()` call.

**Comment by guybedford** [comment]
We don't automatically include polyfills anymore as part of the Babel plugin for the reason that it is left to the user to handle their target environment. Simply installing core-js and requiring the needed polyfills is the suggested workflow here.

**Comment by guybedford** [comment]
Let me know if you agree with the decision not to include Babel polyfills or not here? Always happy to discuss further at the Babel plugin repo too.
