### ISSUE TITLE
bundle-sfx: Broken bundle with angular/http

### ISSUE THREAD

**Issue by DamonGant** [jspm/jspm-cli#1568]
If a module is bundled as self-extracting and includes angular2/http, the bundle will throw in http.js, missing "System".

Reference Project: https://github.com/DamonGant/jspm-sfx-ng2-http

To reproduce: clone, `npm i`, `jspm i`, `jspm bundle-sfx app/main.ts build.js`, `lite-server`, navigate to index.min.html.

**Comment by AdamBurgess** [comment]
Possibly your source maps are messing up - if you disable them you'll see that it actually throws here: https://github.com/DamonGant/jspm-sfx-ng2-http/blob/master/app/main.ts#L5
```js
System.import("bootstrap/css/bootstrap.css!");
```
in an SFX build you cannot import things dynamically.
Even in a non-sfx build, you should probably only be using the dynamic `System.import` if it's, well, dynamic
Try `import "bootstrap/css/bootstrap.css!"` instead, which will tell systemjs that main.ts needs that css as an actual dependency

**Comment by DamonGant** [comment]
Ah, now that I look at it, it makes a lot of sense. It's my first app with ng2/jspm so a lot of things are a bit cobbled together, my apologies.
