### ISSUE TITLE
URL encoding of version string in package-name.js

### ISSUE THREAD

**Issue by salfield** [jspm/jspm-cli#1571]
jspm install github:rase-/node-XMLHttpRequest@add/ssl-support -o "{registry:'npm'}"
Gives me the following error:

err TypeError: Cannot read property 'hash' of undefined

This appears to be due to the url encoding of "/" in the version string in "package-name.js", while the package version information returned from registry.load appears not to be not url-encoded. Removing the url encoding of slash allows the package to install - but I assume you url encode these elements for a reason? In any case there appears to be bug here.

This commit is my temporary fix: 
https://github.com/salfield/jspm-cli/commit/35bdd0028a936cfc941ef8ff667432a90881b70d#diff-f0edec5eee04e9c14b0ddd0730b368a8

**Comment by guybedford** [comment]
Again, this is working fine for me on master. Let me know if you still get issues though.

**Comment by salfield** [comment]
By master I'm assuming you mean the HEAD of branch "0.17"? I've just tested with that and get the same issue.

**Comment by salfield** [comment]
Let me know if you'd like me to do any further investigation, but from placing some console.log's it looks clear that (for me) the url-encoding is stopping the versions from matching.

**Comment by guybedford** [comment]
Released in 0.17.0-beta.10.
