### ISSUE TITLE
Scoped npm packages drops scope from module ID

### ISSUE THREAD

**Issue by jryans** [jspm/jspm-cli#1573]
(This issue was reproduced using jspm 0.17.0-beta.7.)

If you install a scoped npm package via npm itself:

```
npm install @cycle/core --save
```

it is recorded in package.json as `@cycle/core`, and that is how you require it as well.

With jspm if you install it:

```
jspm install npm:@cycle/core
```

it is recorded as just `core` in package.json and mapped to `core` in `jspm.config.js` as well. You can force jspm to act like npm by using:

```
jspm install @cycle/core=npm:@cycle/core
```

Would it better to include the scope in module ID by default to match npm behavior?

**Comment by guybedford** [comment]
Typically the organization is not part of the name. For example the organization is like a github organization - the company or user name. So we make the default alias the version without the `/`.

Compatibility with npm is included though when it is used as a dependency it should be treated as this alias for the package using it, just not in jspm projects by default.
