### ISSUE TITLE
Use Other Projects `jspm_modules` When Importing

### ISSUE THREAD

**Issue by casesandberg** [jspm/jspm-cli#1574]
I am requiring a file in another projects repo and would like its imports to look in that projects `jspm_modules` instead of looking for them in the current projects. How can I achieve this?

**Comment by guybedford** [comment]
This is not possible, rather the dependencies field of the package.json is for this.

**Comment by casesandberg** [comment]
I am working on an app that sits in an electron shell and loads in other projects you are working on. So in order for the app to render components from other projects I would need to be appending that projects dependencies to the package.json file? Or is there any other way to do this?

**Comment by guybedford** [comment]
Your package.json just references the dependencies you use. The dependencies of your dependencies are in turn referenced in their package.json files, and will be installed along with the installed package itself. It's the same way npm works.

**Comment by casesandberg** [comment]
But if I require in a component from a different repo, it is not going to be using that packages dependencies, it is going to be looking for it in the first repo.

**Comment by guybedford** [comment]
Yes projects never share exact version solutions (the jspm config file
being the source of truth for this not jspm_packages itself unlike node),
projects share depdendency ranges so each project can work out its own best
version solution. This is the package.json dependencies field as mentioned.
