### ISSUE TITLE
Error on fetch when running bundle excluding angular2

### ISSUE THREAD

**Issue by oherman1** [jspm/jspm-cli#1575]
Hi,

I'm trying to use angular2 from a CDN, using jspm 0.17.0-beta.9
When running the following command line: 
```
jspm bundle app/boot.ts - angular2  bundle.js 
```
The following error is displayed:

```
err  Error on fetch for npm:angular2@2.0.0-beta.7/index.js at file:///home/myuser/work/app/jspm_packages/npm/angular2@2.0.0-beta.7/index.js
  Error: ENOENT: no such file or directory, open '/home/myuser/work/app/jspm_packages/npm/angular2@2.0.0-beta.7/index.js'
    at Error (native)
```

if angular2 is included all is working well.

Anything I should do?

**Comment by guybedford** [comment]
Try using a build: false metadata as described in https://github.com/systemjs/builder#ignore-resources.

**Comment by oherman1** [comment]
When doing so there is no error but angular2 is still included in the bundle

**Comment by guybedford** [comment]
`build: false` will never be included in the bundle. Note that in jspm 0.16 it may need to reference the main directly - `meta: { 'angular2/index.js': { build: false } }`.

**Comment by oherman1** [comment]
Thanks @guybedford 
It worked when all angular2 files were excluded using `meta: { 'angular2/*.js': { build: false } }`
