### ISSUE TITLE
Avoid using AppData on Windows

### ISSUE THREAD

**Issue by mfidemraizer** [jspm/jspm-cli#1582]
I've been experiencing an issue with JSPM command-line interface. 

Even when JSPM is installed locally, it later caches things in `AppData\local\.jspm`. 

If I'm not mistaken, the main advantage or goal of installing JSPM locally is locking the JSPM version per project, and also isolate its configurations and settings to avoid that a change could break other projects in the same machine.

IMHO, it seems that the whole cache should be moved to the local project directory (like `.git` directory) to avoid collisions also with caches.

In the other hand, for me, this has been a problem because some error in my `config.js` turned into JSPM caching some package in a folder "[package-name].js" and, until I completely dropped the `AppData\local\.jspm`, `jspm install` was trying to locate the cached package in the folder "dot js"...

Thanks in advance ;)

**Comment by guybedford** [comment]
If you can share how the cache got corrupted here clearly that would help a lot here to ensure this doesn't happen. `jspm cc` can be used to clear the cache in these cases, but a global cache is important because it means you share the cache between projects.

**Comment by mfidemraizer** [comment]
If I'm not mistaken, it happened following these steps:

1. Create any project and perform the first `jspm install` using a local installation of JSPM.
2. Edit `config.js` manually. You need to be sure that it's still using `defaultJSExtension`. Go to `babel-core` map and add the whole `.js` extension. (for example `"babel": "npm:babel-core@5.8.35.js")
3. Manually remove `jspm_packages`.
4. Trigger a fresh `jspm install`.

It might happen that this time it will install everything fine. If this happens, remove `jspm_packages` again, and trigger a new and fresh `jspm install`. This time it should show the so-called error.

I understand that `jspm cc` is equivalent to `jspm cache-clear`, isn't it? It was not enough in my case, I had to go to `AppData` and remove the `.jspm` directory.

**Comment by guybedford** [comment]
Thanks, I gave this a go, but after getting the error and changing back to `npm:babel-core@5.8.35` without the extension, the install worked again fine. That is there was no actual cache corruption going on. If you do have a replication case for cache corruption that would be very useful to know though.

**Comment by mfidemraizer** [comment]
@guybedford I'll try to reproduce it and I'll give you more info...

**Comment by mfidemraizer** [comment]
@guybedford It's very strange, but you can be sure that I had the issue and I had to manually remove the whole directory from `AppData`. 

BTW, I've tried to reproduce the issue again and it's not happening anymore. The worst thing is it happened in my dev machine and also in a CI/development server...

For now we can close it, if I the problem arises again, I'll re-open the same issue and we can investigate further what's causing this possible (who knows) issue...

Thank you for your effort

**Comment by mfidemraizer** [comment]
Hey, @guybedford 

It seems that the issue happened again. I believe that I know what you need to reproduce it.

Perform the whole steps but once you've added the `.js` extension to `babel-core`, completely remove your `jspm_packages` directory from your project, and then `jspm install`. 

In my case, it has happened when I did that and now I need to remove the `.jspm` directory from `AppData` to solve the issue.

**Comment by guybedford** [comment]
Thanks for your persistence I finally managed to track this down in https://github.com/jspm/jspm-cli/commit/4c28bd389a8abd7d086f26ddb19d904b58cbb5a1.

**Comment by mfidemraizer** [comment]
@guybedford Nice! Thank you for your effort :+1:

**Comment by guybedford** [comment]
Fixed in jspm 0.17.0-beta.12.
