### ISSUE TITLE
What's different between jspm install npm:package and npm install package?

### ISSUE THREAD

**Issue by xmichaelx** [jspm/jspm-cli#1583]
# Issue

I'm installing package rxjs. When installed with `npm install package` all paths in import are fine, but when I use `jspm install npm:rxjs` they get changed to something like this:

```js
var Observable_1 = require('.js');
```

original code being:

```js
import {Observable} from '../Observable';
```

this results in 404 in the browser because it can't find the corrupted paths.

# Sample code and steps for reproducing

[TypescriptSystemRxTemplate.zip](https://github.com/jspm/jspm-cli/files/156602/TypescriptSystemRxTemplate.zip)

1. npm install
2. jspm install -y
3. typings install
4. gulp watch

I've already mentioned the issue on the [rxjs github](https://github.com/ReactiveX/RxJS/issues/1416) but I was routed here :)

**Comment by OrKoN** [comment]
When you do "jspm install package" you install the package using the `jspm` registry which contains important configs that make everything run smoothly. The registry is here https://github.com/jspm/registry and there are some overrides for rxjs already: https://github.com/jspm/registry/blob/master/package-overrides/npm/%40reactivex/rxjs%405.0.0-alpha.2.json

When you define the registry explicitly, for example, "jspm install npm:rxjs" you get the raw package installed without applying any additional configuration.

**Comment by guybedford** [comment]
@xmichaelx installing ES6 modules through npm is only supported when setting `jspmNodeConversion: false` (). You may want to try using jspm 0.17 which is more flexible in this case.

**Comment by dmarginian** [comment]
One of the developers on my team is seeing the same error with JSPM 0.16.39, the odd thing is that it is working for the rest of the team (same package.json, etc.).  We have tried clearing jspm and npm caches with no luck.  Guy, I am a bit confused by your comment as according to the rxjs docs to pull in the library as commonjs you should use npm install rxjs and rxjs-es if you want ES6.  I tried setting jsomNodeConversion to false in the non-working environment and I got past the rxjs error but got other errors.

**Comment by guybedford** [comment]
@dmarginian it may be worth trying jspm 0.17 here, it has better support for npm conversion.

**Comment by dmarginian** [comment]
Thanks Guy.  I have issues with 0.17 because we have a large node modules directory and it is constantly running out of memory unless we clear it.  This particular problem ended up being an issue with the version of Node/NPM the developer had installed.  We updated to the latest and greatest and everything started working again.
