### ISSUE TITLE
Configuring credentials on Appveyor

### ISSUE THREAD

**Issue by awflierman** [jspm/jspm-cli#1585]
I wrote [this question ](http://stackoverflow.com/questions/35083523/unauthorized-response-from-github-api-on-appveyor) on Stackoverflow, I'm kind of stuck right now on configuring the proper authentication settings for GitHub. 

Does anyone else have this issue on Appveyor? 

We use jspm 0.16.15

**Comment by guybedford** [comment]
Perhaps check that you're definitely getting the manual local authentication to work. Does the configuration test work ok when you run that? Perhaps try generating an auth token otherwise? If using an auth token make sure that it has all the repo permissions granted.

**Comment by awflierman** [comment]
It seems that the node version is my problem: need to install stable version of Node which is v5.6.0 at this point.
