### ISSUE TITLE
font-awesome doesn't loaded

### ISSUE THREAD

**Issue by gig177** [jspm/jspm-cli#1588]
```bash
$ jspm -v
0.17.0-beta.9
```
Overrides from jspm registry:
```json
    "overrides": {
      "npm:font-awesome@4.5.0": {
        "main": "css/font-awesome.css!",
        "jspmNodeConversion": false,
        "registry": "jspm",
        "dependencies": {
          "css": "0.1"
        }
      }
    }
```
Related strings from jspm.config.js:
```javascript
  // ...
  map: {
    "font-awesome": "npm:font-awesome@4.5.0"
  },
  packages: {
    "npm:font-awesome@4.5.0": {
      "map": {
        "css": "github:systemjs/plugin-css@0.1.20"
      }
    }
  }
```
But stil throws: `Error loading http://localhost:8080/static/pagerank_graph/jspm_packages/npm/font-awesome@4.5.0/css/font-awesome.css!.js ` (404 Err). Looks like mapping doesn't work.

**Comment by guybedford** [comment]
Yes, this is a breaking change - plugin syntax mains are no longer supported in jspm 0.17. Rather the main should just be `font-awesome.css` with a meta configuration setting the CSS load, something like:

```json
{
  "main": "font-awesome.css",
  "meta": {
    "*.css": { "loader": "css" }
  }
}
```

**Comment by gig177** [comment]
Thanks for your reply. It works.
