### ISSUE TITLE
NPM devDepencies copied to jspm devDepencies

### ISSUE THREAD

**Issue by chips5k** [jspm/jspm-cli#1589]
Not sure if this is meant to be a feature or not, but i have noticed that
if you have a package.json like follows:

```
{
  .....
  "devDependencies": {
    "aurelia-tools": "^0.1.18",
    "conventional-changelog": "0.0.11",
    "del": "^1.1.0",
    .....
  },
  "jspm": {
    "registry": "npm",
    "jspmPackage": true,
    "main": "index",
    "format": "amd",
    "directories": {
      "dist": "dist/amd"
    },
    "peerDependencies": {}
  }
}
```

All of the base "devDependencies" get added into the jspm.devDepencies

To work around this i had to provide an empty  object e.g:

```
"jspm": {
    "devDependencies": {}
} 
```

I apologize in advance if this is in fact an intended feature and i simply misunderstood how jspm works.

**Comment by guybedford** [comment]
`peerDependencies` are not recognized in jspm 0.16. If running in jspm 0.17 the above should work though without the `devDependencies` being added or needing an empty object to avoid that.

**Comment by chips5k** [comment]
ok no worries, thanks!
