### ISSUE TITLE
Transpiler not upgrading in beta upgrade path

### ISSUE THREAD

**Issue by perrin4869** [jspm/jspm-cli#1591]
Prepared a repo demonstrating the attempt here: https://github.com/perrin4869/jspm_superagent

The README.md has the explanation. Deleting all JSPM configuration and initializing from zero works without problems. I got a few more test cases I'll post later :)

**Comment by guybedford** [comment]
Thanks! I'll check this out when I can.

**Comment by guybedford** [comment]
Thanks I tracked this down to the transpiler not upgrading properly. Will create a fix when I can.

**Comment by guybedford** [comment]
Released in 0.17.0-beta.10.
