### ISSUE TITLE
Initializing jspm@0.17beta9 at a subdir produces incompatible settings

### ISSUE THREAD

**Issue by perrin4869** [jspm/jspm-cli#1592]
Second test case I stumbled into: https://github.com/perrin4869/jspm0.17_subdir

Left instructions in README.md again. Basically, the settings produced by the configurator must be fixed manually for jspm to work.

**Comment by guybedford** [comment]
Thanks, there was actually one bug here and that was that the baseURL is not being prompted for the custom case. Fixed in https://github.com/jspm/jspm-cli/commit/887941b21822759812d128999ee8fc1bc3358691.
