### ISSUE TITLE
System is not defined with bundle-sfx (0.16.30)

### ISSUE THREAD

**Issue by fknop** [jspm/jspm-cli#1594]
Hello,

I tried to bundle my app using a sfx bundle.

I ran the command: `jspm bundle-sfx app/app.js Scripts/dist/app.bundle.sfx.js --minify`
I include this bundle file in the index.html (only this file).

I have the following error: `ReferenceError: System is not defined` but I don't use the System variable anywhere in my code.

Any ideas ?

Thanks

**Comment by guybedford** [comment]
Can you see where in the bundle code the `System` reference is? If you can share the output file with minification disabled then that would help to suggest something here.

**Comment by fknop** [comment]
https://gist.github.com/fknop/fb712ea5e584405edad9

I see this:

```
var x={},y="undefined"!=typeof System&&System._nodeRequire
```

**Comment by guybedford** [comment]
It looks like it is the systemjs-less-plugin causing this then. I've posted https://github.com/InstaGIS/systemjs-less-plugin/issues/1.

**Comment by fknop** [comment]
Great, thank you.
