### ISSUE TITLE
system.js etc. in head or body?

### ISSUE THREAD

**Issue by glen-84** [jspm/jspm-cli#1595]
In the past I put `system.js` and `config.js` in the body, which is what is currently used in the Aurelia [documentation](http://aurelia.io/docs.html#/aurelia/framework/1.0.0-beta.1.1.4/doc/article/getting-started). The [Beta Guide](http://jspm.io/0.17-beta-guide/creating-a-project.html) for 0.17 shows these files in the head section. Where do you recommend that these files be placed (in 0.17)?

Thanks.

**Comment by guybedford** [comment]
At the end of the body is usually the best practice.

**Comment by glen-84** [comment]
Okay, thanks.
