### ISSUE TITLE
Structure/partition big app with multiple modules/apps as single app

### ISSUE THREAD

**Issue by luboid** [jspm/jspm-cli#1596]
Is this structure is posible to be created, I using 0.17 version
When I anser to "package.json directories.packages" with ../jspm_packages it want directory to be under app1/src

```html
site
  |
  + - node_modules (dirrectory to share modules)
  + - jspm_packages (dirrectory to share modules)
  +--- app1
  |      |
  |      + - node_modules (sym link to upper directory)
  |      + - src (code directory???)
  |      + - app.js
  |      + - index.html
  |      + - package.json
  |
  +--- app2
  |      |
  |      + - node_modules (sym link to upper directory)
  |      + - src (code directory???)
  |      + - app.js
  |      + - index.html
  |      + - package.json
  |
  + - index.html (links to app1/index.html,app1/index.html) or this can be app3 which to load app1 or app2
      may I share code between diffrent apps
```

We achive this with require.js but I cant success in this with jspm.

**Comment by guybedford** [comment]
Your jspm package.json file should be in the `site/package.json` location in this case to manage the project-level configuration. Let me know if that can work out for you here.

**Comment by qlayer** [comment]
We have made a simple application:
https://github.com/qlayer/jspm-beta-test
What is your opinion ?

**Comment by guybedford** [comment]
Looks good. If you wanted to be fancy you could have a package.json with the individual package configs in it in app1 and app2 folders with the package config and add to jspm.config.js:

```javascript
SystemJS.config({
  packageConfigPaths: [
    "app1/package.json",
    "app2/package.json",
    "github:*/*.json",
    "npm:@*/*.json",
    "npm:*.json"
  ],
});
```

**Comment by guybedford** [comment]
(although there is no need for fanciness... just duplicating config is fine too, since normally production and dev configs are different anyway, but that would give the full encapsulation experience).

**Comment by qlayer** [comment]
Thanks for the help.
