### ISSUE TITLE
Symlinked package.json not visible for JSPM

### ISSUE THREAD

**Issue by TomiS** [jspm/jspm-cli#1597]
I have symlinked a package.json file to the project root from a subfolder of the project.

When I run `jspm install` in project root, I get:
`Configuration file path/to/my/subfolder/config.js doesn't exist, create it? [yes]`

Wouldn't it be more logical if JSPM would handle symlinks as if they were real files or is there a reasoning behind current behaviour? Now it seems it does not recognize their existence at all and searches subfolders for existing `package.json`. This happens even after I initialized `config.js` with . (dot) to get it stay in the root.

Tested with version 0.16.29

**Comment by guybedford** [comment]
This would actually be a liftoff issue that it doesn't detected a symlinked package.json. Perhaps it's best just to create two package.json files?

**Comment by guybedford** [comment]
(The liftoff issue queue is at https://github.com/js-cli/js-liftoff/issues)

**Comment by TomiS** [comment]
Yep, two package.json files is my workaround, but it causes maintenance overhead. Anywhoo, thanks for answering. Closing.
