### ISSUE TITLE
0.17.0-Beta.9 - Error when trying to load Optional Dependencies

### ISSUE THREAD

**Issue by davinkevin** [jspm/jspm-cli#1598]
Hi, 

I try to migrate my lib project (https://github.com/davinkevin/AngularStompDK) to JSPM 0.17, but when I try to install all like if it is a new project (not using the migration path), when I try to do the first `jspm install github:jmesnil/stomp-websocket` JSPM tries to install the optional Dependencies to github:websocket.

```
     Updating registry cache...

err  Error on locate for github:websocket
GitHub packages must be of the form owner/repo.

err  Error locating github:websocket.

warn Installation changes not saved.
```

Could you help, all was working on the 0.16.X version.

Thanks

**Comment by guybedford** [comment]
Thanks for letting me know about this. Fixed in https://github.com/jspm/github/commit/2606226de94738e64cea7e2f9c931172688fad77, and this is released in jspm-github so should come through with an update to the beta.
