### ISSUE TITLE
0.17-beta.10: skip the init mode selection

### ISSUE THREAD

**Issue by micaelmbagira** [jspm/jspm-cli#1600]
Is there a way to disable jspm init mode selection ?  
At install it keeps asking to select the correct options though I **already** have the following in `jspm.config.js`: 
````javascript
SystemJS.config({
  defaultExtension: 'js',
  packages: {
    'src': {
      'main': 'index.js'
    }
  },
  transpiler: 'plugin-babel',
  babelOptions: {
    'presets': [
      'babel-preset-react'
    ]
  }
});
````

**Comment by guybedford** [comment]
It sounds like it may not be finding your package.json file then? That is necessary for jspm to not prompt.

**Comment by micaelmbagira** [comment]
This must be in package.json ?
````javascript
'src': {
    'main': 'index.js'
}
````

**Comment by micaelmbagira** [comment]
Maybe before returning `initPrompts()` here https://github.com/jspm/jspm-cli/blob/0.17/lib/config/index.js#L270, jspm should make this check:
````js
if (!config.pjson.jspmAware && !allowNoConfig || prompts)
      return initPrompts();
````
just like you did here : https://github.com/jspm/jspm-cli/blob/0.17/lib/config/index.js#L124-L125

**Comment by guybedford** [comment]
That line specifically is for the beta upgrade path. The usual guard is at https://github.com/jspm/jspm-cli/blob/0.17/lib/config/index.js#L128.

**Comment by micaelmbagira** [comment]
Alright, then should we add the usual gard before `return initPrompts()` ?

**Comment by guybedford** [comment]
I would first focus on sharing a replication if you can. If I copy your exact package.json file, I get the beta upgrade path prompts with no configuration present, then once that config is generated it no longer prompts.

**Comment by micaelmbagira** [comment]
So you don't have the `Select an init mode for jspm project configuration.` prompt when using my exact package.json ?

**Comment by guybedford** [comment]
No.

**Comment by guybedford** [comment]
It might be worth checking what OS / Node version you are using here.

**Comment by micaelmbagira** [comment]
I'm using Mac OS X/Node v4.2.6

**Comment by micaelmbagira** [comment]
Sorry, closed by mistake. So here is a replication project where you should be able to replicate the issue : https://github.com/micaelmbagira/jspm-example
If you run `jspm install` ,

**Comment by guybedford** [comment]
If you run through the upgrade process though anyway, once complete your jspm.config.js file will have `packageConfigPaths: []` set and then be valid though and not trigger the upgrade path any more.

I can see how this can be confusing though, so have added a change in https://github.com/jspm/jspm-cli/commit/5a7c7d92dc005c7a84753190cfca0935ddda4d46 to avoid this case.
