### ISSUE TITLE
declaration of invalid dependency (jspm-npm)

### ISSUE THREAD

**Issue by mirco312312** [jspm/jspm-cli#1602]
Hi,

I think the commit [1e75d3afff3ee8278ab364dc021848741bf347ce](https://github.com/jspm/jspm-cli/commit/1e75d3afff3ee8278ab364dc021848741bf347ce) broke the [JSPM version available on npmjs.com](https://www.npmjs.com/package/jspm). This commit specifies 'jspm-npm' version '^0.26.6', which doesn't match any version available on npmjs.com.

```
npm ERR! notarget No compatible version found: jspm-npm@'>=0.26.6 <0.27.0' 
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.0.1","0.0.2","0.0.3","0.1.0","0.1.1","0.2.0","0.2.1","0.2.2","0.2.3","0.2.4","0.2.5","0.2.6","0.2.7","0.3.0","0.3.1","0.3.2","0.4.0","0.5.0","0.5.1","0.6.0","0.6.1","0.7.0","0.8.0","0.8.1","0.8.2","0.8.3","0.8.4","0.8.5","0.8.6","0.9.0","0.10.0","0.11.0","0.12.0","0.13.0","0.13.1","0.14.0","0.14.1","0.14.2","0.13.2","0.13.3","0.13.4","0.15.0","0.15.1","0.15.2","0.16.0","0.17.0","0.18.0","0.18.1","0.18.2","0.18.3","0.18.4","0.19.0","0.20.0","0.20.1","0.20.2","0.20.3","0.20.4","0.21.0","0.21.1","0.21.2","0.21.3","0.21.4","0.22.0","0.22.1","0.23.0","0.23.1","0.23.2","0.23.3","0.23.4","0.24.0","0.24.1","0.25.0","0.25.1","0.25.2","0.25.3","0.26.0","0.27.0","0.26.1","0.27.1","0.27.2","0.26.2","0.27.3","0.26.3","0.28.0","0.26.4","0.28.1","0.26.5","0.28.2"]
```

It looks like you [published a version 0.28.x of 'jspm-npm'](https://github.com/jspm/npm/releases), should 'jspm' reference that version?

**Comment by AdamBurgess** [comment]
Probably a caching error on npm's side, `npm view jspm-npm` shows `0.26.6` in the list of versions for me, and jspm 0.16 installs successfully

**Comment by guybedford** [comment]
Thanks, there's definitely a 0.26.6 version of jspm-npm published though. Perhaps your local mirror hasn't updated yet?

**Comment by mirco312312** [comment]
Thanks guys! Most probably a caching error, sorry! Now `npm view jspm-npm`shows `'0.26.6': '2016-03-09T14:21:08.750Z'`.
