### ISSUE TITLE
Out of memory when using jspm install

### ISSUE THREAD

**Issue by delasteve** [jspm/jspm-cli#1604]
In a new folder, I ran `jspm init` and used all the defaults under `Quick` setup. It was successful in downloading `SystemJS`. When trying to install `angular2@2.0.0-beta9` I received the following.

```
$ jspm install angular2
     Updating registry cache...
     Downloading npm:angular2@2.0.0-beta.9
ok   Installed peer es6-promise to npm:es6-promise@^3.0.2 (3.1.2)
ok   Installed peer es6-shim to npm:es6-shim@^0.33.3 (0.33.13)
ok   Installed peer reflect-metadata to npm:reflect-metadata@0.1.2 (0.1.2)
ok   Installed peer zone.js to npm:zone.js@0.5.15 (0.5.15)
ok   Installed peer rxjs to npm:rxjs@5.0.0-beta.2 (5.0.0-beta.2)
ok   Installed peer process to github:jspm/nodelibs-process@^0.2.0-alpha (0.2.0-alpha)
[1]    31382 killed     jspm install angular2
```

Attempting again, I got:

```
$ jspm install angular2
     Updating registry cache...
     Downloading npm:angular2@2.0.0-beta.9
[1]    32268 killed     jspm install angular2
```

```
$ uname -a
Linux delasteve 4.2.0-27-generic #32-Ubuntu SMP Fri Jan 22 04:49:08 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
$ node -v
v5.8.0
$ npm -v
3.8.1
$ jspm -v
0.17.0-beta.11
Running against local jspm install.
```

Running `dmesg`:

```
[2997873.822147] [ pid ]   uid  tgid total_vm      rss nr_ptes nr_pmds swapents oom_score_adj name
...
[2997873.822221] [32268]  1000 32268   397933   109266     413     298        0             0 jspm
[2997873.822224] Out of memory: Kill process 32268 (jspm) score 878 or sacrifice child
[2997873.828083] Killed process 32268 (jspm) total-vm:1591732kB, anon-rss:436360kB, file-rss:704kB
```

This is on a fresh $5/mo (512MB RAM, 1 Core) box from DigitalOcean. 

Any help would be appreciated. Thanks!

**Comment by OrKoN** [comment]
Hey, this happens with npm/other node programs too. Simply not enough memory :( For example, https://www.digitalocean.com/community/questions/npm-gets-killed-no-matter-what

The possible solutions are:

 - increase the droplet size (temporarily) to run installations
 - don't run install commands on the box and copy jspm_packages/node_modules from your dev machine instead
 - try to decrease the default node memory limit which I believe is 1.5 Gb https://github.com/nodejs/node/issues/2738 and http://stackoverflow.com/questions/12779724/limiting-node-jss-memory-usage

**Comment by guybedford** [comment]
Unfortunately jspm does use quite a lot of memory. Reducing this footprint in future will be an ongoing task, and something best worked around in the mean time.
