### ISSUE TITLE
Allow uncompressed packed code above / below source code in bundles

### ISSUE THREAD

**Issue by juliandoucette** [jspm/jspm-cli#1607]
Some (including myself), would make the argument that it is unethical to include compressed code as part of a web page / application; especially without sourcemaps.

1. Since you do not compress source code by default when creating a bundle, can you not compress the packed code above / below source code by default too?

2. Can you add an API option and command line option to compress or not compress the code packed above / below source code?

**Comment by guybedford** [comment]
Are you referring to https://raw.githubusercontent.com/systemjs/builder/master/templates/sfx-core.min.js here?

If so, this is following the pattern established by browserify and webpack. If we don't compress this, users complain that bundle output doesn't look nice, and contains unnecessary code.

This source can always be looked up in https://raw.githubusercontent.com/systemjs/builder/master/templates/sfx-core.js.

**Comment by juliandoucette** [comment]
> Are you referring to https://raw.githubusercontent.com/systemjs/builder/master/templates/sfx-core.min.js here?

Yes. And others. EG:

```
!function(e){function r(e,r){for(var n=e.split(".");n.length;)r=r[n.shift()];return r}function n(n){if("string"==typeof n)return r(n,e);if(!(n instanceof Array))throw new Error("\
Global exports must be a string or array.");for(var t={},o=!0,f=0;f<n.length;f++){var i=r(n[f],e);o&&(t["default"]=i,o=!1),t[n[f].split(".").pop()]=i}return t}function t(r){if(Ob\
ject.keys)Object.keys(e).forEach(r);else for(var n in e)a.call(e,n)&&r(n)}function o(r){t(function(n){if(-1==l.call(s,n)){try{var t=e[n]}catch(o){s.push(n)}r(n,t)}})}var f,i=$__S\
ystem,a=Object.prototype.hasOwnProperty,l=Array.prototype.indexOf||function(e){for(var r=0,n=this.length;n>r;r++)if(this[r]===e)return r;return-1},s=["_g","sessionStorage","local\
Storage","clipboardData","frames","frameElement","external","mozAnimationStartTime","webkitStorageInfo","webkitIndexedDB","mozInnerScreenY","mozInnerScreenX"];i.set("@@global-hel\
pers",i.newModule({prepareGlobal:function(r,t,i){var a=e.define;e.define=void 0;var l;if(i){l={};for(var s in i)l[s]=e[s],e[s]=i[s]}return t||(f={},o(function(e,r){f[e]=r})),func\
tion(){var r;if(t)r=n(t);else{r={};var i,s;o(function(e,n){f[e]!==n&&"undefined"!=typeof n&&(r[e]=n,"undefined"!=typeof i?s||i===n||(s=!0):i=n)}),r=s?r:i}if(l)for(var u in l)e[u]\
=l[u];return e.define=a,r}}}))}("undefined"!=typeof self?self:global);
```

> If so, this is following the pattern established by browserify and webpack. 

I have opened the same bug at browserify https://github.com/substack/node-browserify/issues/1520

> If we don't compress this, users complain that bundle output doesn't look nice, and contains unnecessary code.

This is a matter of taste.

- Which is ok, if all of the source code that is bundled by default is free software compliant and referenced in a way that makes it easy to find online or via source maps

However, shouldn't there be an option to include it uncompressed so that one does not have to include source maps and external links to distribute source code that respects the essential 4 freedoms of free software?

**Comment by guybedford** [comment]
Ideology should always be rooted. In this case, the minified code is a small registry implementation. It can be thought of like a "marker" for what tool was used to build the code. Over all JS built, there are probably less than 20 of these markers that someone would need to know to fully understand what is going on. No freedoms are being lost.
