### ISSUE TITLE
remote mode in 0.17?

### ISSUE THREAD

**Issue by edrex** [jspm/jspm-cli#1608]
Hi, I really like the remote CDN mode in master, for making quick demos and such. I noticed that it was removed from the 0.17 branch (the last bit in f52bdf5842c13e91c980976165). Is it going away? 

I totally understand not wanting to spread limited resources too thin, and maybe I am the only one who was using it.

**Comment by edrex** [comment]
I discovered that by just including System.js from the CDN, everything else is loaded from it by default, see https://github.com/edrex/prosemirror-playground. This is basically what I wanted, minimal local overhead for demos.

**Comment by guybedford** [comment]
This isn't actually fully supported as it requires a redevelopment of the CDN work, which is exactly delayed as it is hard to find the time to include as part of the 0.17 release cycle as well, but it's definitely on the list.

**Comment by guybedford** [comment]
Closing as this is on the roadmap.
