### ISSUE TITLE
Issue with multiple jspm processes running concurrently 

### ISSUE THREAD

**Issue by subesokun** [jspm/jspm-cli#1609]
Hi :) While debugging https://github.com/Orbs/jspm-git/issues/23 I've noticed that jspm has some issues when running concurrently. In fact there are several issues I've experienced so far:

When trying to update concurrently the jspm registry with an empty jspm cache following error gets thrown

```
     Creating registry cache...

err  Error creating registry file
Error: Command failed: /bin/sh -c git clone --depth=1 https://github.com/jspm/registry.git .
Cloning into '.'...
fatal: Unable to read current working directory: No such file or directory
fatal: The remote end hung up unexpectedly

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:821:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

err  Repo jspm:plugin-babel not found. Perhaps try jspm install npm:plugin-babel.
```

Also later on when running jspm install various error are getting thrown.

```
err  Error on download for github:jquery/jquery
Error: ENOENT: no such file or directory, utime '/home/subesokun/.jspm/packages/github/jquery/jquery@2.2.1/test/unit/ajax.js'
    at Error (native)

warn Installation changes not saved.


err  Error: ENOTEMPTY: directory not empty, rmdir '/home/subesokun/.jspm/packages/github/jquery/jquery@2.2.1/test'
    at Error (native)

warn Installation changes not saved.
```

The bash script I was using for testing can be found here https://gist.github.com/subesokun/00a6c89a48fc012d1c0f

**Comment by guybedford** [comment]
Yes, jspm doesn't actually support simultaneous execution yet. See https://github.com/jspm/jspm-cli/issues/1445.

**Comment by guybedford** [comment]
Actually this is a really good summary, so lets make this the main issue :)

**Comment by subesokun** [comment]
Ok, thanks for clarification :) So I'll also move the https://github.com/Orbs/jspm-git/issues/23 to here.

**Comment by jtamary** [comment]
As @mikz pointed out on #1445 I think that a first step forward is to add a working directory (or a name) that will be under .jspm directory (for permissions).
so we can configure in the config file:
`cacheName: <cacheName> `

so the cache dir would be
`.jspm/<cacheName>`

I won't eliminate all of the concurrency problems, but certainly help CI users which can configure such parameters on their own.

I would happily try and add this feature.
@guybedford what do you think?

**Comment by guybedford** [comment]
@jtamary thanks for your interest here. The cache is something that can actually be shared globally because it is properly hashed and relatively universal. So the task here is actually just to ensure a cross-process locking of the cache folders using lock files.

**Comment by joshuaspence** [comment]
Is there any workaround for this issue?

**Comment by mikz** [comment]
@joshuaspence you could use [`flock`](http://linux.die.net/man/1/flock) around jspm to make it run just one copy at the time. Like `flock ~/.jspm/lock -c jspm install`.

**Comment by nillis** [comment]
+1

**Comment by nillis** [comment]
Are there any solutions (/hacks) to turn around this problem until a fix is released?

**Comment by mikz** [comment]
Looks like the new `JSPM_GLOBAL_PATH` (https://github.com/jspm/jspm-cli/issues/1831) in beta 16 could be the way to go?

**Comment by mikz** [comment]
@nillis you can try to use JSPM_GLOBAL_PATH to create new folder per parallel build or just use flock as described in https://github.com/jspm/jspm-cli/issues/1609#issuecomment-219957367

**Comment by thorseye** [comment]
The property seems to be called `LOCALAPPDATA` (not `JSPM_GLOBAL_PATH`): 
https://github.com/jspm/jspm-cli/blob/master/lib/config.js#L16

If you set this environment variable, JSPM will create a `${LOCALAPPDATA}/.jspm` directory, which will be used for cache (and other things). 

But the feature to make concurrent jspm executions is highly requested. 
@guybedford Any updates on this?

**Comment by guybedford** [comment]
jspm 2.0 now supports a fully locking cache with multiple processes running concurrently.
