### ISSUE TITLE
require from ./ fails to load ./index

### ISSUE THREAD

**Issue by rolandjitsu** [jspm/jspm-cli#1610]
While trying to do an import from [plotly.js](https://github.com/plotly/plotly.js):
```js
import Plotly from 'plotly.js/lib/core';
```
I noticed that it fails with a 404 when it reaches [L15](https://github.com/plotly/plotly.js/blob/master/src/components/modebar/manage.js#L15) `var createModeBar = require('./');`.

I would have expected that this would automatically resolve to `./index.js`, but it does not. I've also tested locally the same behaviour just to make sure it's not something within the plotly framework causes that and I can confirm that this is because either SystemJS or JSPM does not resolve `./` to `./index.js`.

Let me know if you need further examples or more info.

**Comment by guybedford** [comment]
Try `jspm install npm:plotly.js` as the npm conversion layer handles compatiblity of features like this which aren't native to SystemJS loading.

**Comment by DavidStrada** [comment]
Hi, I'm having somehow the same problem using the same library, installed using `jspm install npm:plotly.js` I'm using `"jspm": "0.17.0-beta.6"'

here are the following scenarios :

``` javascript 

// file components/graphics.js
import plotly from 'plotly.js';
console.log( plotly );
```
I get the following errors on the console.

``` console
GET http://localhost:3000/jspm_packages/npm/plotly.js@1.6.3/lib/heatmap.js net::ERR_BLOCKED_BY_CLIENTN @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935
system.js:4 

Uncaught (in promise) Error: Error: XHR error loading http://localhost:3000/jspm_packages/npm/plotly.js@1.6.3/lib/heatmap.js(…)t @ system.src.js:4935g @ system.src.js:4935(anonymous function) @ system.src.js:4935
system.src.js:4935 

GET http://localhost:3000/jspm_packages/npm/plotly.js@1.6.3/src/components/modebar/ 404 (Not Found)N @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935
system.src.js:4935 

GET http://localhost:3000/jspm_packages/npm/readable-stream@1.0.33/index.js 404 (Not Found)N @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935

```

if i do 

``` javascript

import plotly from 'plotly.js/lib/core';
console.log( plotly );
```

``` console

GET http://localhost:3000/jspm_packages/npm/plotly.js@1.6.3/src/components/modebar/ 404 (Not Found)N @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935
system.js:4 

Uncaught (in promise) Error: Error: XHR error (404 Not Found) loading http://localhost:3000/jspm_packages/npm/plotly.js@1.6.3/src/components/modebar/(…)t @ system.src.js:4935g @ system.src.js:4935(anonymous function) @ system.src.js:4935
system.src.js:4935 

GET http://localhost:3000/jspm_packages/npm/plotly.js@1.6.3/src/components/modebar/ 404 (Not Found)

```

do you have any thoughts ? what i think is going on it's that by plotly not being explicit about what file to load `e.g. ../core/index `and just putting `../core/` `jspm or systemjs` doesn't know what to load.

**Comment by rolandjitsu** [comment]
@guybedford I will try it out tomorrow and let you know if it works, thanks.

**Comment by rolandjitsu** [comment]
@guybedford I still get that. And I did use that syntax for installing before you suggested it. I get the following exception:
```js
system.js:4 Uncaught (in promise) Error: SyntaxError: Unexpected token <
	    at Object.eval (https://local.dev/jspm_packages/npm/plotly.js@1.6.3/src/components/modebar/manage.js:15:21)
	    at eval (https://local.dev/jspm_packages/npm/plotly.js@1.6.3/src/components/modebar/manage.js:227:4)
	Evaluating https://local.dev/jspm_packages/npm/plotly.js@1.6.3/src/components/modebar/
	Evaluating https://local.dev/jspm_packages/npm/plotly.js@1.6.3/src/components/modebar/manage.js
	Evaluating https://local.dev/jspm_packages/npm/plotly.js@1.6.3/src/plot_api/plot_api.js
	Evaluating https://local.dev/jspm_packages/npm/plotly.js@1.6.3/src/plotly.js
	Evaluating https://local.dev/jspm_packages/npm/plotly.js@1.6.3/src/core.js
	Evaluating https://local.dev/jspm_packages/npm/plotly.js@1.6.3/lib/core.js
	Evaluating https://local.dev/app/app.js
	Evaluating https://local.dev/app/bootstrap.js
	Error loading https://local.dev/app/bootstrap.jst @ system.src.js:4935g @ system.src.js:4935(anonymous function) @ system.src.js:4935y @ system.src.js:4935w @ system.src.js:4935p @ system.src.js:4935h @ system.src.js:4935(anonymous function) @ system.src.js:4935
```
If you look closely you can spot `Evaluating https://local.dev/jspm_packages/npm/plotly.js@1.6.3/src/components/modebar/`, that is where the problem occurs. Instead of loading `https://local.dev/jspm_packages/npm/plotly.js@1.6.3/src/components/modebar/index.js` it loads the folder. And since I have a static http server that is configured to always respond with `index.html` whenever a file that does not exist is requested, it loads that html file and thinks it's a js file, thus the `Unexpected token <`.

So I think the problem is that system (or jspm) cannot recognize the path `./` as `./index.js`. Before switching to `0.17` I used the plotly lib successfully, so I think this is a bug, unless it's on purpose.

Also, as far as I know, you are allowed, in node, to `require('./')`, because that usually resolves to `./index.js`, so I expected the same behaviour.

**Comment by guybedford** [comment]
Right so the issue here is exactly that `require('./')` is resolving to the directory instead of the directory with a js extension in SystemJS. I've created a SystemJS issue to track this in https://github.com/systemjs/systemjs/issues/1164.

Unfortunately I can't suggest a workaround here without manually editing the require.

**Comment by guybedford** [comment]
So yes, this is something more fundamental, and appreciated for bringing it up. Let's continue to track at the SystemJS repo.

I'm sure we can resolve the SystemJS issue in the coming weeks.

**Comment by rolandjitsu** [comment]
@guybedford no problem. I will wait for the feature to be implemented.

**Comment by DavidStrada** [comment]
@rolandjitsu, @guybedford Really needed this worked out, so i ended up "hacking" my way around for now, here's what I did, given that plotly provides a CDN. 

``` javascript
//jspm.browser.js
SystemJS.config({
  baseURL: "/",
  paths: {
    "dashboard/": "app/",
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*",
    "npm:plotly.js@1.6.3": "https://cdn.plot.ly/plotly-1.5.0.min.js",
  }
});
```

Just for now i can include it and work with it, ( In case you are curious ).

` import Plotly from 'plotly.js'; `
