### ISSUE TITLE
Still having trouble with "@empty" mapping in browser field of package.json

### ISSUE THREAD

**Issue by MeoMix** [jspm/jspm-cli#1611]
Hey,

We talked a bit about this on Gitter and you pushed this fix: https://github.com/jspm/npm/commit/59938712bc1e5df811e66738bf92eec6cb983222

I'm still unsuccessful in getting this code to work as hoped.

I'm on beta-11. In `jspm-loader-css` I have the following:

```
  "jspm": {
    "browser": {
      "cssnano": "@empty"
    }
  }
```

The full package.json can be seen [here](https://github.com/MeoMix/jspm-loader-css/blob/master/package.json#L39).

When I load `jspm-loader-css` in the browser I still see `cssnano` being loaded. Code errors out on cssnano dependencies failing to load.

Inside of my `jspm.config.js` I see:

```
    "github:MeoMix/jspm-loader-css@master": {
      "map": {
        "css-modules-loader-core": "npm:css-modules-loader-core@1.0.0",
        "cssnano": "npm:cssnano@3.5.2",
        "node-cssnano": "npm:cssnano@3.5.2"
      }
    }
```

It looks like the `node-*` dependency was added, but the original dependency was not set to `@empty`. If I manually edit the mapping to make it `@empty` then things work as expected, but I'm unsure if that's the correct solution or if something else is going awry.

**Comment by guybedford** [comment]
@MeoMix since this is your package, I think you just want to use:

```
"jspm": {
  "dependencies": {
    "css-modules-loader-core": "npm:css-modules-loader-core@1.0.0",
    "node-cssnano": "npm:cssnano@3.5.2"
  },
  "map": {
    "cssnano": {
      "node": "node-cssnano",
      "default": "@empty"
    }
  }
}
```

The `browser` property is actually a legacy property we support for browserify when the `registry: 'npm'` is set for a package. For custom jspm packages setting `jspmNodeConversion: false` can be advised to avoid this handling.

**Comment by guybedford** [comment]
It should work like that though, and is a bug with jspm-npm.

**Comment by MeoMix** [comment]
Cool. Thanks for the response. Would you like me to raise an issue on jspm-npm regarding the bug?

Additionally, was there any way for me to have come up with your solution via documentation? If not, perhaps we could start an issue for what existing JSPM functionality isn't documented currently? I think working on documentation (while costly in up-front time) would have a compounding effect of saving you time answering questions in the long run. :) I can appreciate the hesitancy to document a rapidly-changing environment, though, too.

**Comment by guybedford** [comment]
Sure a jspm-npm issue to track would be good as it's not a fix I can get to just right now.

Yes it's a documentation issue - it's actually a jspm 0.17 only feature, so falls under that (the principles are mentioned in the beta guide though). jspm 0.17 documentation is exactly the top priority currently for the jspm 0.17 release to go out.
