### ISSUE TITLE
improve github token test

### ISSUE THREAD

**Issue by eroux** [jspm/jspm-cli#1612]
the test part of `jspm registry config github` seems to test only if the token is valid, but not if it has the right to access public repositories, so it reports the token to be ok while it's not. I've spent quite some time debugging before realizing the token I gave it didn't have the proper access, so would it be possible to check the token properly in the config command?

**Comment by guybedford** [comment]
Certainly that might be a better experience, as a lot of users seem to fall into these catches.

This problem goes away in jspm 0.17 though, so I think it would be better to upgrade to that if you can, and for efforts here to be focused on that release.
