### ISSUE TITLE
0.17.0-beta.11: `strictSSL` option is ignored

### ISSUE THREAD

**Issue by apiv** [jspm/jspm-cli#1613]
Putting `"strictSSL": false` in `~/.jspm/config` no longer turns off strict SSL validation.

**Comment by guybedford** [comment]
I just tested this and it's certainly being set correctly for GitHub installs. Can you share the exact error message to show what sort of request it is failing on here? Also what version of jspm is this with?

**Comment by fastner** [comment]
This is fixed in pull request https://github.com/jspm/github/pull/88
