### ISSUE TITLE
Loading library with global

### ISSUE THREAD

**Issue by chriseyhorn** [jspm/jspm-cli#1616]
I am trying to load the cesium library that is built with almond loader that does a global export like this:

```
/*global require*/
// require in the complete Cesium object and reassign it globally.
// This is meant for use with the Almond loader.
require([
        'Cesium'
    ], function(
        Cesium) {
    'use strict';
    /*global self*/
    var scope = typeof window !== 'undefined' ? window : typeof self !== 'undefined' ? self : {};

    scope.Cesium = Cesium;
}, undefined, true);
```

What is the proper way to get this to load through jspm?

Best Regards,
Chris

**Comment by guybedford** [comment]
You may find that due to the presence of AMD syntax, this module is being detected by SystemJS as AMD and then not loading properly.

Try installing as a global in jspm - `jspm install x -o "{format:'global'}"`.

**Comment by chriseyhorn** [comment]
Hey @guybedford, it seems to load ok but then I'm getting an error trying to call any functions in the library.  When I debug in Chrome I can see the object defined but I'm getting an error like this on any calls into the library.

> TypeError: cesium_1.default.Viewer is not a function

The call in the code is to Cesium.Viewer, this error happens on any call to Cesium.

Thanks for the help.

**Comment by chriseyhorn** [comment]
Going to close this issue as I got it working, turned out that

`import Cesium from 'cesium'`

was causing an error because it wanted Cesium.Cesium.foo wth that import statement.

The fix was to just `import 'cesium'`
