### ISSUE TITLE
sharing code between modules during development

### ISSUE THREAD

**Issue by slanted** [jspm/jspm-cli#1619]
Hello,

My team is trying to find an answer to this but we can't seem to figure it out.

We have a package named 'shop' that has a dependency on a package named 'util'. So we install both shop and util into our jsp registry. However right now we are stuck in a dumb development workflow:

1. We make a change in 'util'. After that we check/push the change into our private git repo. 
2. We go to the 'shop' directory and do a 'jspm install' to pull down the change from util.

We want the 'util'  package to be installable through jspm for a different development group, but our group develops both the 'util' and the 'shop' modules (our app uses 'shop', theirs just uses 'util'), and this process is pretty dumb. 

Can we develop by just editing code in the 'util' package without having to do this 2 step dance I described above? Sorry I know this is probably a noob question.

Ideally, we just edit code in 'util' and somehow our local 'shop' module sees the changes instantly without having to pull them down from the registry.

**Comment by guybedford** [comment]
See the linking workflows here. In jspm 0.17 the linking workflows are much easier, so I would suggest using that if you can. There's a section on linking in both the 0.16 docs and the jspm 0.17 beta guide on the website.
