### ISSUE TITLE
jspm run to allow environment flags

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#1621]
Just like the ones we have for jspm build and jspm bundle - eg `jspm bundle x --production`.

**Comment by HongJheLi** [comment]
Thank you for your contribution to this project.

**Comment by guybedford** [comment]
Implemented in https://github.com/jspm/jspm-cli/commit/b12583a4cd12cb2dea7ccbeafeab9c9db86a1ae8. //cc @AdamBurgess

**Comment by guybedford** [comment]
Fixed in jspm 0.17.0-beta.12.
