### ISSUE TITLE
bundleSFX does not respect source map contents when minify is true

### ISSUE THREAD

**Issue by JeremyRH** [jspm/jspm-cli#1622]
JSPM version 0.16.31

Reproducible example: https://github.com/JeremyRH/systemjs-builder-sourceMapContents-min-failing

It seems that adding minify to options is causing source map contents to not be inlined in the source map.

```javascript
jspm.bundleSFX('./src/app.js', './dist/app.js', {
  'minify': true,
  'sourceMaps': true,
  'sourceMapContents': true  // <--- not respected when minify is true
});
```

**Comment by JeremyRH** [comment]
also seems this documentation is incorrect (minify does not default to true):
https://github.com/jspm/jspm-cli/blob/master/docs/api.md#bundle-options

**Comment by guybedford** [comment]
Thanks, fixed in https://github.com/jspm/jspm-cli/commit/f6c9c87d30c0cf8f346e046ace160f9b18c4e720 and https://github.com/systemjs/builder/commit/13ff32d4493505816fd420f389489b279550d86f.

**Comment by guybedford** [comment]
I spoke too soon on this one - UglifyJS doesn't actually provide the feature quite that simply outside of the CLI. Let's track this in https://github.com/systemjs/builder/issues/527.
