### ISSUE TITLE
Mapping issue at building time

### ISSUE THREAD

**Issue by gig177** [jspm/jspm-cli#1623]
I was created [repo](https://github.com/gig177/jspm-issues/tree/master/static) with some code example. 
```bash
$ jspm -v
0.17.0-beta.11
$ jspm build app --skip-rollup -m dist/app.js

err  Error on fetch for app/main.js at file:///home/evgeniy/tmp/_jspm_test/static/src/main.js
  Error: ENOENT: no such file or directory, open '/home/evgeniy/tmp/_jspm_test/static/src/main.js'
    at Error (native)
```
At jspm 0.16.x this works fine, but at jspm 0.17.x it doesn't. I've got confused why this happen. For a long time of debugging I was found some related lines at `lib/config/package.js` (lines [100](https://github.com/jspm/jspm-cli/blob/0.17.0-beta.11/lib/config/package.js#L100) and [143](https://github.com/jspm/jspm-cli/blob/0.17.0-beta.11/lib/config/package.js#L143)).
Where can I read about relationship between `pjson.name` and `pjson.directories.lib` options in more details? I won't  have additional `src` dir at `app` folder.

**Comment by guybedford** [comment]
`jspm init -p` will go through these prompts in the jspm beta. The default is for the application package to be in a `src` folder within the baseURL, and it must be some subfolder of the baseURL. If you don't want to use a package rather just use `jspm build custom.js` or whatever file you want to build, and leave out the local package config.

**Comment by gig177** [comment]
Yep. I understand jspm prompt. But usage `src` dir is strictly required. I wanna flat structure without `src` dir.
```jbash
static
|---app
|     |---main.js
|     `---some_other.js
|---jspm_packages/
|---jspm.config.js
|---jspm.browser.js
|---dist/

$ jspm build app dist/app.js
```
How to accomplish this structure? Follow my [repo](https://github.com/gig177/jspm-issues/tree/master/static) example please.

**Comment by guybedford** [comment]
As mentioned, if you want your js at the root level don't use a package, just directly reference modules in the baseURL as in the example.

**Comment by gig177** [comment]
This sounds like a hack.
