### ISSUE TITLE
.jspm.errors file generated when there are ES6 src folder in npm package

### ISSUE THREAD

**Issue by dfahlander** [jspm/jspm-cli#1624]
First of all, thanks for a great module loader! I love the idea but haven't still started using it, but certainly will.

I'm a frontent library developer need to make sure that my npm lib works well in jspm. But I have some issues.

It is suggested by [rollup](https://github.com/rollup/rollup) to [npm-publish ES6 source together with the transpiled ES5 output](https://github.com/rollup/rollup#can-i-distribute-my-package-as-an-es6-module). But JSPM will inspect each JS file in the entire npm package and complain about ES6 module syntax unless you set format to "esm" - which is not what I desire because I also have a cjs module in dist that my users would prefer to get over jspm.

I can get rid of the error file by either say "I'm an ES6 module - here is my main for JSPM", or say "ignore all my ES6 source files":

```js
   jspm: {
       ignore: [ <all my ES6 tools and src files>]
   }
```
But it's not possible to use wildcards in the ignore list, which makes me having to list all my ES6 files there.

I cannot either use the "files" attribute. It makes the package only contain those files, but the warnings remains for non-included files!

Would it be possible to either accept wildcard patterns in the ignore, or just not inspect files that are not going to be used from the main entry?

Kind regards,
David ([Dexie.js](https://github.com/dfahlander/Dexie.js))

**Comment by guybedford** [comment]
If you're new to jspm and looking into it, I'd highly suggest using the jspm 0.17 beta, as this will better allow cases like the one you've mentioned.
