### ISSUE TITLE
how to configure the proxy?

### ISSUE THREAD

**Issue by obingo** [jspm/jspm-cli#1625]
when i try to jspm init, i got a error like this:

```
$ jspm init

warn Running jspm globally, it is advisable to locally install jspm via npm inst                                                                                                                                                                                               all jspm --save-dev.
ok   Verified package.json at package.json
     Verified config file at config.js
     Looking up loader files...

warn Error on download for github:systemjs/systemjs
     Error: connect ETIMEDOUT 192.30.252.126:443
         at Object.exports._errnoException (util.js:870:11)
         at exports._exceptionWithHostPort (util.js:893:20)
         at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1062:14)

err

err  Error downloading loader files.

err
```

then i try to set a proxy through: `jspm config proxy http://dev-proxy.oa.com:8080`

but, not work for me, so, how to configure the proxy?

**Comment by guybedford** [comment]
These proxy environment variables are supported here - https://github.com/request/request#controlling-proxy-behaviour-using-environment-variables.

**Comment by obingo** [comment]
why does't support config proxy in ```.jspm/config```?

**Comment by obingo** [comment]
@guybedford why does't support config proxy in ```.jspm/config```?

**Comment by guybedford** [comment]
@obingo that would be ideal certainly. It's purely a matter of time to put together the simple piping.

**Comment by guybedford** [comment]
(as in, I don't have the time!)

**Comment by obingo** [comment]
haha, anyway, thank you so much.
