### ISSUE TITLE
import default not working after bundle

### ISSUE THREAD

**Issue by robersonccgomes** [jspm/jspm-cli#1626]
I have a module that uses bower:angular imported using:
`import angular from 'angular'`

It's working fine, but after the scripts are bundled it stops working. The error is:

> Uncaught (in promise) Error: TypeError: angular.module is not a function
> at execute (http://localhost:8080/import_default/bundle.js:11614:34)
> Error loading http://localhost:8080/import_default/import_default/login.js

If I add another import or if imported as `import {angular} from 'angular'`, it works again.

It can be reproduced in this sample: https://github.com/robersonccgomes/jspm-bundle-bug
(just run `npm install && npm start` and you're good to go)

**Comment by guybedford** [comment]
Make sure every angular plugin that expects the angular global is properly shimmed on angular.
