### ISSUE TITLE
Way to override nodelibs core module

### ISSUE THREAD

**Issue by KenRmk** [jspm/jspm-cli#1629]
Is there a way i could force JSPM to not use `nodelibs-net` when `net` is required, but rather my module of choice like `chrome-net` or `winrt-net` ? I couldn't find a way to do this other than keep renaming my module in jspm.config map.
from
```
"chrome-net": "npm:chrome-net@3.1.2",
"net": "github:jspm/nodelibs-net@0.2.0-alpha",
```
to
```
"chrome-net": "npm:chrome-net@3.1.2",
"net": "npm:chrome-net@3.1.2",
```
But this gets overwritten by `nodelibs-net` everytime new module using `net` is installed.

**Comment by amenadiel** [comment]
You could try looking for every package in your current config that has `nodelibs-net` as a dependency, and install them with a local override like:

```sh
jspm install github:my/package -o '{ "map" : { "net" : "chrome-net" } }'
```

**Comment by KenRmk** [comment]
That seems like a pain to type it into terminal everytime trying a new module.
It'd be much nicer to have it in the config file just like defining paths

**Comment by guybedford** [comment]
This is fine to do in jspm 0.17 and then each new version would prompt to override through the peer dependency conflict process. Is this conflict prompt what you don't want?
