### ISSUE TITLE
Static exclusion of unused exports (tree shaking)

### ISSUE THREAD

**Issue by nlwillia** [jspm/jspm-cli#1631]
I'm interested in using the [lodash-es](https://github.com/lodash/lodash/issues/1473) build of `lodash` which is structured so that you can selectively pluck out just the functions that you need.  This is important for a library like lodash since it has gotten fairly large and some of what it does is now redundant with built-in capabilities in JavaScript arrays and objects.

I tried this under jspm 0.16 and 0.17, and neither seem to be currently doing anything to remove what's never used.  (In all fairness, [webpack](https://github.com/webpack/webpack/issues/1750) isn't there yet either.)
```
jspm install npm:lodash-es
```
```
import { chunk } from 'lodash-es';
console.log(chunk);
```
In development, there were still hundreds of eagerly dispatched requests for every exported fragment of lodash.  In `jspm build` the resulting file did not change whether I imported by function name or the whole thing except for how the import binding was compiled for my module.

Am I missing something?  Is this something rollup should have detected?  If so, and there is a build solution, then is there (equally important) a development solution as well?  Is there a road map for this sort of optimized modularity?  If the answer is "we're not there yet" that's ok; I'd just like to know what to expect.

**Comment by AdamBurgess** [comment]
>In development, there were still hundreds of eagerly dispatched requests for every exported fragment of lodash.

Removing unnecessary code requires knowing the code beforehand, so you'd still have to load all the files to do any kind of optimisations/tree-shaking.

>In jspm build the resulting file did not change whether I imported by function name or the whole thing except for how the import binding was compiled for my module.

`import chunk from 'lodash-es/chunk.js'` is significantly smaller (7kb build) than `import { chunk } from 'lodash-es'` (499kb).

>Am I missing something? Is this something rollup should have detected?

Rollup can only eliminate code that it thinks won't change the result of the build...the difference in bundle size is due to how lodash is written - rollup thinks that there are many side-effects, so it inlines most of the code leading to a large build.
In lodash-es's main `lodash.js`, try removing the last import/export: `export { default as default } from './lodash.default.js'`. This single change alone reduces that 499kb build down to 232kb.
So, I don't think this is a problem with rollup, rather it's a 'flaw' in the way lodash was written.

**Comment by nlwillia** [comment]
Take a look at the [es version of lodash](https://github.com/lodash/lodash/blob/es/lodash.js).  It's nothing but re-exports.  I'm not saying it's a trivial problem, but it should be possible to statically identify what's needed without loading the whole dependency graph.  It changes the load process from an eager "fetch everything as soon as possible" to a lazy "wait until the imports are known, then fetch what's used".  This might be an expensive policy to institute globally, particularly if it interferes with future improvements involving server push, but for modules known to follow this pattern, having a registry option to enable it could be a benefit.  Some of the runtime overhead could be avoided by doing analysis of ES6 modules at install and caching metadata about the static dependencies.

Importing a specific file works, but that's a less expressive subset of ES6 syntax.  There may not be a better option right now though.

It looks like [rollup isn't there yet](https://github.com/rollup/rollup/issues/501) either, but maybe it will [get there](https://medium.com/@Rich_Harris/tree-shaking-versus-dead-code-elimination-d3765df85c80).

**Comment by AdamBurgess** [comment]
>it should be possible to statically identify what's needed without loading the whole dependency graph. 

the fact of the matter is that js is not static. if any of the imports in lodash.js do something that rollup thinks could influence another module, it opts to include it.

>"wait until the imports are known, then fetch what's used"

rollup is already doing this, and it determines that all the files **are** actually used.

>Importing a specific file works, but that's a less expressive subset of ES6 syntax

I disagree. Importing the exact module you want isn't some premature optimisation, it's what you should be doing. Inporting one named export from a module should run the entire module, exporting and importing all unnecessary code. That's what the ES6 module definition is. Rollup, to me, is a nice hack, but it's not something you should be depending on. In any case, importing the exact module will *always* be faster than importing it from the main file, as rollup doesn't need to analyse any of the other dependencies.

**Comment by guybedford** [comment]
I think you'll find this has been discussed extensively on the Rollup issue queue. Perhaps try searching there for the details on these specific cases?

**Comment by jdalton** [comment]
@AdamBurgess 
> This single change alone reduces that 499kb build down to 232kb.
So, although rollup's optimisations aren't perfect, most of the problem lies with how lodash was written.

Disagree.

**Comment by nlwillia** [comment]
It sounds like the answer to my original question is that although there's clearly interest elsewhere, this is not something you can currently expect under a strict ES6 interpretation (where you don't actually know whether an otherwise unused module is still doing something with side-effects just by being loaded).  And since rollup currently has to load files before it can optimize them, there's probably not a case for it being part of browser-based loading at this time.  But that could (hypothetically) change if loaders or standards develop a way to describe whether a module has non-exported side-effects.  (It seems kind of a waste in my mind to have statically analyzable import/export semantics and still have to load every imported file just to be able to rule out whether it's used.  Maybe that's not what the language authors had in mind, but it's certainly relevant to the browser environment.)

In the case of `lodash-es`, there's no current way to avoid loading everything (which ends up being fairly disastrous in the browser) except importing each specific modularlized file separately.  This is entirely workable, but depending on the environment, the multiple specific smaller files might not end up loading faster than the regular monolithic lodash in browser.  This is not anything wrong with lodash, but it is something that people looking to optimize their workflows and builds will need to be aware of.

**Comment by philer** [comment]
Does the production bundle use tree shaking? All the posts in the thread seem to refer to the case where modules are loaded via individual requests, which is obviously not the way you'd want things to work in production. The whole point of rollup's tree-shaking is to create a minimal single-file bundle by analysing static import/export. This should be possible for JSPM's `--inject` or `bundle-sfx`.

**Comment by OrKoN** [comment]
@philer have you seen this page? http://jspm.io/0.17-beta-guide/static-builds-with-rollup-optimization.html

**Comment by philer** [comment]
@OrKoN I have not, because I'm dumb and only looked at the 0.16 docs. Thanks for the hint. :)
