### ISSUE TITLE
Builder API Bundle with configuration Injection

### ISSUE THREAD

**Issue by mikereinhold** [jspm/jspm-cli#1633]
I'm not sure if this is a bug or a design change, however after upgrading to 0.17 beta 11 and switching to the Builder API in my Gulp script (since the bundle function is both deprecated and removed), I find that my jspm.browser.js config file is not updated with the bundle mapping as previous with the jspm.bundle function when using the inject option. I've confirmed that running the bundle manually from the command line properly injects the bundle configuration however the Builder API does not. Again, maybe this is by design as there is no documentation about performing a config injection with the Builder API. Not having the capability to inject complicates integrating JSPM in a Gulp script. 

Should the builder API perform config injection? If not, what is the recommended approach to getting the bundle config pushed back to jspm.browser.js when using the API?

**Comment by mikereinhold** [comment]
I'm currently working around the issue by calling the JSPM via it's CLI interface instead of the API. It works, but it has reduced flexibility as the command line does not provide all of the options that the Builder API has available...

**Comment by guybedford** [comment]
Yes we don't currently have an API for configuration injection. We could certainly wrap the builder class to make this an option as a jspm-specific extension of `builder.bundle({  injectConfig: true })` or similar.

**Comment by guybedford** [comment]
This has now been implemented via the `injectConfig` option as described, pending release.

**Comment by guybedford** [comment]
Fixed in jspm 0.17.0-beta.12.

**Comment by mikereinhold** [comment]
Thanks @guybedford - looks good!
