### ISSUE TITLE
Understanding jspm bundle-sfx

### ISSUE THREAD

**Issue by mfidemraizer** [jspm/jspm-cli#1634]
Hey,

Reading the docs I'm not sure if I'm understanding what `jspm bundle-sfx` produces at all.

AFAIK, it should produce a file that can work alone without SystemJS and its bundled as a module un *global* format.

In my case, the bundled file doesn't make an exported class in my *main* available to the global scope:

`export class Whatever { .. }`

In the bundled file I was expecting `window.Whatever` if I just include the script using a script element:

`<script src="bundle.js"></script>`

Am I in the right track or I've completely misunderstood `jspm bundle-sfx` switch?

**Comment by mfidemraizer** [comment]
Ok, I've found that you can give the global module name using `--global-name` argument. 

BTW, what happens if you don't want this but the *global module* to be my `Whatever` class? 

I want to avoid something like this:

`var boo = new Whatever.default();`
`var foo = new Whatever.Whatever();`

**Comment by AdamBurgess** [comment]
Export a single default export, and it won't be named 'default':
```js
export default class Whatever {
  constructor() {
    console.log('hi!');
  }
}
```

gets transpiled into:
```js
var Whatever = (function () {
  'use strict';

  var _classCallCheck = (function (instance, Constructor) {
    if (!(instance instanceof Constructor)) {
      throw new TypeError("Cannot call a class as a function");
    }
  })

  var Whatever = function Whatever() {
    _classCallCheck(this, Whatever);

    console.log('hi!');
  };

  return Whatever;

}());
```

**Comment by mfidemraizer** [comment]
@AdamBurgess  I'll give this a try, thanks!

**Comment by guybedford** [comment]
Thanks @AdamBurgess.
