### ISSUE TITLE
get systemjs config from jspm.config.js as JSON object with JSPM API

### ISSUE THREAD

**Issue by rolandjitsu** [jspm/jspm-cli#1636]
I am trying to get the contents of `jspm.config.js` as a JSON object so I can replace some of the options when I build for production.

Currently I am using:

``` js
import jspmConfig from 'jspm/lib/config';
jspmConfig.loadSync();
const config = jspmConfig.loader.getConfig();
```

That gives me exactly what I need. But I was wondering if there was a better way, as this seems unstable and probably subject to change.

_P.S: I am using jspm@beta._

**Comment by guybedford** [comment]
There is currently not configuration API yes, and that is because it's still not been clear what the best form for this API might be - whether we should allow loading, modifying then saving config, or just starting with a load config API.

Perhaps a load config API like you have is the best way forward, but it would need to cater to both jspm.config.js and jspm.browser.js in jspm 0.17. So something like `require('jspm').getConfig('browser')` may be the route forward here, with a default `require('jspm').getConfig()` to return the main config file.

In terms of format this is also where it gets complicated since config is a structured JSON object, but perhaps returning all of it would be useful. I'm just weary of pushing something out that will not just lead to backwards compatibility woes.

**Comment by rolandjitsu** [comment]
Ok. I figured that there wasn't an official API for doing this.

I think having a `.getConfig()` or `.config()` exported from jspm would be a great idea. As you suggested, using `.config('browser')` would return the config for `jspm.browser.js`.

Even better, the `.config()` should be passed a file or file path instead of a string, just to make things more friendly as a simple string like `'browser'` might confuse people and it's not very intuitive. Whereas using `.getConfig(<config file>)` just seems better. That would also mean that the user can have whatever names he/she desires for the config file with no impact on how the `.getConfig()` implementation works.

The reason I suggested a name like `.config()` is because this fn could also behave as a setter. So calling `.config()` would return the configuration for a `jspm.config.js` and calling `.config({production: true})` would merge the object into the existing config file `jspm.config.js`. Mostly because most of the time, the only reason you would load the config would be so that you change some of it then save it again to some file (which also means that I would have to add `SystemJS.config()` as well).

And to use it with custom config file names, the `.config()` could have a second param that would take the file/file path as I described two paragraphs above.

How does that sound?

**Comment by guybedford** [comment]
This is exactly why I've had implementation reservations! The save config problem isn't trivial.

Could you perhaps share in more detail what configuration changes you're making? It would help a lot to understand the use cases around this.

**Comment by rolandjitsu** [comment]
For instance I need to change the `production` value in the `System.config({"production": false})` to `true`. Or I need to override the `transpiler` value from `"ts"` to `"none"`. Both of these is because I have different setups for dev and prod.

So maybe there the simples solution would be to have a `jspm.config.dev.js`? There are many ways to solve this I guess.

**Comment by rolandjitsu** [comment]
@guybedford is there a way with the new changes you made lately to change these configs?

**Comment by guybedford** [comment]
@rolandjitsu in the latest beta we now support `productionConfig: {...}` and `devConfig: {...}` in the main configuration file. The dev configuration can also be split off into a separate file by following the prompts in `jspm init`.

**Comment by rolandjitsu** [comment]
Ok so assuming that I use the following config in `jspm.config.js`:
```js
SystemJS.config({
	browserConfig: {
		"paths": {
			"github:": "/jspm_packages/github/",
			"npm:": "/jspm_packages/npm/",
			"app/": "/app/"
		}
	},
	nodeConfig: {
		"paths": {
			"github:": "jspm_packages/github/",
			"npm:": "jspm_packages/npm/",
			"app/": "app/"
		}
	},
	productionConfig: {
		packages: {
			"app": {
				"defaultExtension": "js"
			}
		}
	},
	devConfig: {
		map: {
			"plugin-babel": "npm:systemjs-plugin-babel@0.0.12",
			"plugin-typescript": "github:frankwallis/plugin-typescript@4.0.16"
		},
		packages: {
			"github:frankwallis/plugin-typescript@4.0.16": {
				"map": {
					"typescript": "npm:typescript@1.8.10"
				}
			},
			"app": {
				"defaultExtension": "ts"
			}
		},
		transpiler: "plugin-typescript",
		typescriptOptions: {
			"module": "system",
			"typeCheck": true,
			"tsconfig": true
		}
	},
	packages: {
		"app": {
			"map": {
				"./env": {
					"~production": "./env.dev"
				}
			}
		}
	}
});

SystemJS.config({
	packageConfigPaths: [
		"github:*/*.json",
		"npm:@*/*.json",
		"npm:*.json"
	],
	map: {
		"@angular/common": "npm:@angular/common@2.0.0-rc.2",
		"@angular/compiler": "npm:@angular/compiler@2.0.0-rc.2",
		"@angular/core": "npm:@angular/core@2.0.0-rc.2",
		"@angular/http": "npm:@angular/http@2.0.0-rc.2",
		"@angular/platform-browser": "npm:@angular/platform-browser@2.0.0-rc.2",
		"@angular/platform-browser-dynamic": "npm:@angular/platform-browser-dynamic@2.0.0-rc.2",
		"@angular/router": "npm:@angular/router@3.0.0-alpha.7",
		"core-js": "npm:core-js@2.4.0",
		"fs": "github:jspm/nodelibs-fs@0.2.0-alpha",
		"os": "github:jspm/nodelibs-os@0.2.0-alpha",
		"path": "github:jspm/nodelibs-path@0.2.0-alpha",
		"process": "github:jspm/nodelibs-process@0.2.0-alpha",
		"reflect-metadata": "npm:reflect-metadata@0.1.3",
		"rxjs": "npm:rxjs@5.0.0-beta.6",
		"zone.js": "npm:zone.js@0.6.12"
	},
	packages: {
		"github:jspm/nodelibs-os@0.2.0-alpha": {
			"map": {
				"os-browserify": "npm:os-browserify@0.2.1"
			}
		}
	}
});
```

How would this work? Since in my `index.html` file I load `jspm.config.js`, how do I tell jspm that I am currently in dev or prod mode?

**Comment by guybedford** [comment]
System.config({ production: true }) in a script tag after loading systemjs.
In future we may well have a production build of systemjs.

**Comment by rolandjitsu** [comment]
Ok, so that has not changed, we still configure that the same way. Thanks

**Comment by rolandjitsu** [comment]
It would be nice if changing the prod setting would be more trivial, because right now I use a setup as such to do it when I build the app:
```js
gulp.task('jspm:config', function () {
	jspmConfig.loadSync();
	return gulp
		.src('jspm.config.js')
		.pipe(changed(PATHS.dist))
		.pipe(transform(jspmConfig.loader.getConfig()))
		.pipe(size(GULP_SIZE_DEFAULT_CONFIG))
		.pipe(gulp.dest(PATHS.dist));
});

function transform(config) {
	config.production = true;
	return through.obj((chunk, enc, callback) => {
		chunk.contents = new Buffer(`SystemJS.config(${JSON.stringify(config)})`, 'utf8');
		callback(null, chunk);
	});
}
```

**Comment by abhishiv** [comment]
@rolandjitsu Why do you need to read the config.js file? The .dependencies and package.json have exactly the same data as config.js as far as I can see.

**Comment by rolandjitsu** [comment]
@abhishiv how else would you tell JSPM that you are in prod/dev mode? You get the config, you change the production prop to true/false and you save the config, right?

But if there is another way, please let me know.

And nope, the config file and the package file are different. Maybe in your case looks the same, but that might be just a coincidence.

**Comment by AMorgaut** [comment]
@rolandjitsu I found a page about conditionnal imports which shows a use case loading different config files depending on a production property

Here a simplified example

> env.conditions.js

```js
export var mock = false;
export var environment = 'prod';
```
> SystemJS Config

```js
System.config({
  map: {
    "ENV": "src/app/core/config/env.conditions.js"
  }
}); 
```

> app.js

```js
import './config.#{ENV|environment}.js'; // will load config.prod.js
import './mock.js#?ENV|mock'; // will not load mock data
// ...
```

Hope this helps!

see: http://martinmicunda.com/2015/10/26/conditional-module-loading-with-systemjs/
