### ISSUE TITLE
transpiler: "plugin-babel", builds are made using traceur

### ISSUE THREAD

**Issue by ineentho** [jspm/jspm-cli#1637]
I'm using .17 beta11.

In my jspm.config.js I have

```
SystemJS.config({
    transpiler: "plugin-babel"
});
```

It loads using babel in the browser, but builds are made using traceur for some reason. I noticed because traceur was unable to transpile some of my code.

```
Cannot read property 'reportError' of null
    at reportDuplicateVar (node_modules\jspm\node_modules\systemjs-builder\node_modules\traceur\bin\traceur.js:17691:13)
```

Or am I wrong here, maybe you always use some part of Traceur for builds since you have it as a systemjs-builder dependency?

```
const jspm = require('jspm')
jspm.setPackagePath('.')
const builder = new jspm.Builder(BASE_DIR);
builder.bundle('file', 'out', {
    minify: true,
    sourceMaps: true
};
```

**Comment by rjharmon** [comment]
I got the same result with an existing project originally created around beta.4.  I updated to beta.11 and got this symptom when building.  Recreating the project from scratch using the beta setup sequence and npm 3 worked without trouble.  FYI

**Comment by guybedford** [comment]
Traceur is used for handling the SystemJS module format transformers in all cases. There is an issue tracking converting these to use Babel in https://github.com/systemjs/builder/issues/489. I've also created a bug to track the swallowed error stack here in https://github.com/systemjs/builder/issues/534.

**Comment by guybedford** [comment]
Note also Traceur bugs are being fixed all the time and upgrades to Traceur happen with each release.
