### ISSUE TITLE
babel-core@5.8.24.js file is using different file pointing to node.js on few Windows 7 machines

### ISSUE THREAD

**Issue by NJBUIC1** [jspm/jspm-cli#1638]
---------------------------------------------------------------------------------------------------------------------------------
What is the issue: Windows 7 and "jspm install of babel-core@5.8.24" - details below:
---------------------------------------------------------------------------------------------------------------------------------
1. On few windows 7 boxes ONLY we are seeing below issue:
2. User is doing "jspm install" on project we provided
3. For whatever reason "jspm_packages/npm/babel-core@5.8.24.js"  has below content:
    module.exports = require("npm:babel-core@5.8.24/index");
4. Problem with this is: This points to index.js that points to "node.js"
    /* */ module.exports = require('./lib/api/node');

After this all goes bad for browser trying to render the application:

---------------------------------------------------------------------------------------------------------------------------------
Manual workaround: How we fixed this:
---------------------------------------------------------------------------------------------------------------------------------
1. On almost all machines "jspm_packages/npm/babel-core@5.8.24.js" file contents are as below: 
        module.exports = require("npm:babel-core@5.8.24/browser.js");
2. So we provided "babel-core@5.8.24.js" generated from different machine to get over.

---------------------------------------------------------------------------------------------------------------------------------
Why "babel-core@5.8.24.js" contents are different only when "jspm istall" runs on few Windows 7 machines?
---------------------------------------------------------------------------------------------------------------------------------
1. We noticed that package.json of babel-core package as below line:
"browser": {
    "./lib/api/register/node.js": "./lib/api/register/browser.js"
  },

2. We are suspecting that somehow on these specific Windows 7 boxes, something is not triggering to create "babel-core@5.8.24.js" file with "browser.js" - and instead going with "index.js" that is pointing to node.js. Don't know if above "browser" property is doing anything or someother issue?

3. We could not find much documentation on use of "browser" property in package.json. So we can't guess what the issue is.

------------------------
Question:
------------------------
1. What is triggering "jspm install" of babel-core to create same "babel-core@5.8.24.js" in "jspm_packages/npm" folder -with different contents - based on what machine we run?

2. How can we get around this, instead of manually providing correct file from different machine?

**Comment by guybedford** [comment]
Thanks for the careful report here. By the consistency it may sound like this is a windows compatibility issue. I will look into this case when I can and report back further.

**Comment by NJBUIC1** [comment]
Thank you very much. 
I am very happy that the issue is in good hands. 
Appreciate your input on this once you find out more.

**Comment by guybedford** [comment]
I just tested out the install of `jspm install npm:babel-core@5.8.24` on windows 7 and it's definitely giving the right contents of `jspm_packages/npm/babel-core@5.8.24.js` as `module.exports = require("npm:babel-core@5.8.24/browser.js")`.

Perhaps check that there are no local overrides present in the package.json file. Another thing worth trying is a `jspm install npm:babel-core@5.8.24 -f` to do a force install ignoring the existing cache in case the cache contains incorrect contents.

Otherwise if you have any other suggestions for replication just let me know.

**Comment by NJBUIC1** [comment]
Thanks for getting back. 
Same package.json works fine on some Windows 7 boxes [so your observation is right]
On 2 machines that it is not working, we tried deleting JSPM cache, NPM cache clear and trying fresh.
We are going try -f option and let you know.

Meanwhile, just quick question: Can you please shed some light on if there is anyway to expose verbosity in this area to know more on what is going on [So we can compare logs and also look for any specific step errors] 

Also If you know specific step that creates this file, it helps if you can share few details on that too.

Thanks again for your time.

**Comment by guybedford** [comment]
Yes do try with the `-f` option and also double check that the `jspm -v` is giving the right version.

jspm by default runs at its greatest verbosity, there is only the ability to reduce it via logging options.

**Comment by divvu224** [comment]
Thank you for both your help. We resolved this by using the jspm overrides section in package.json for babel.
