### ISSUE TITLE
Save install overrides to config.js or package.json 

### ISSUE THREAD

**Issue by tauren** [jspm/jspm-cli#164]
Why does install override information not get saved anywhere? For instance:

```
jspm install github:JimLiu/angular-ui-tree -o "{ main: 'dist/angular-ui-tree.min' }"
```

This installs into `jspm_packages` correctly, pointing at the new main file. However, no record of the overrides used is saved anywhere outside of `jspm_packages`. This means that when other users check out the project and run `jspm install`, the packages won't get installed properly. I do not want to have to check in my `jspm_packages` folder to source control.

I know there is JSPM registry to help with this, but we have various concerns with it. For instance, we cannot be dependent on someone outside of our organization to accept pull requests in a timely manner. Nor can we be dependent on a relatively unknown third party server to be online (obviously we are reliant on github, but that's easier to sell to the boss). Lastly, we may have private packages that require overrides that cannot be referenced on a public server.

Is there a place this information is stored and I'm just missing it? Is this something that is planned?

**Comment by trusktr** [comment]
> The configuration itself, should always be in the package.json of the original repo. That is the place it belongs

We wish this was true for all repos. Even if an override exists in the jspm registry, some people might want to override the override.

+1 for jspm.overrides.

**Comment by brianfeister** [comment]
Any movement on this?  I have a common use case, which is a library on github which is wrapped for AMD but I need to do `-o { format: 'global' }` for my app to use the library.  I need to build this project for continuous integration and the override should be in `package.json` - it seems silly to need a bash script to pass the flag and correctly install this for continuous integration.

**Comment by trusktr** [comment]
@guybedford Is there a way to apply overrides without having to reinstall everything after `jspm install`? I mean, I suppose I can just *not* track jspm.json in my repo, then store all my dependencies in a script full of `jspm install this` and `jspm install that`.

Currently I'm tracking jspm.json, doing `jspm install`, then `jspm install something -o {...}` for all the overrides, which means that things gets installed twice and it takes longer than it should.
