### ISSUE TITLE
uglify excludes

### ISSUE THREAD

**Issue by amitport** [jspm/jspm-cli#1640]
I have a library that use es6 features, but I do not have a build phase since those are supported by node+chrome+firefox (classes, arrow functions, block scoping)

when bundling a jspm project that depend on such lib I get errors from uglify that apparently still doesn't support es6 very well.

Is there a way for me to use `--minify` but disable uglify for just one dependency without having to create a few bundles?

**Comment by guybedford** [comment]
Unfortunately we are still waiting for good minification support for modern ES6 syntax. Check that it is definitely using the latest version of the uglify dependency perhaps? If you hear of any options here certainly let me know.
