### ISSUE TITLE
How to improve Transpiling speeds with jspm and TS module

### ISSUE THREAD

**Issue by born2net** [jspm/jspm-cli#1641]
In an effort to understand better how JSPM works, as I am trying to improve my development re-launch cycles speeds which right now take about 5-8 seconds each time I reload the browser.

So I am using Angular 2 with Typescript plugin ( https://github.com/frankwallis/plugin-typescript ) , and I am trying to improve the transpiling time of TS in the browser (although to be honest, when looking at the load times via network tab in google dev tool, I do see a lot of the time is being spent just fetching files... but I guess nothing we can do about that).

So my question is, if I convert my project into many smaller npm type libs, which are developerd in TS but when provided through the npm already come with the transpiled JS equivalents, will this improve load times as the TS module will not need to re-transpile them? or will that not be the case?

regards

Sean.

**Comment by lookfirst** [comment]
Actually using the browser cache to not fetch the files improves the speed a lot.

**Comment by born2net** [comment]
any special flag / option to enable this?
regards

**Comment by lookfirst** [comment]
https://github.com/jspm/jspm-cli/issues/872

**Comment by born2net** [comment]
wow that's a long discussion and I see some people report no improvements... some do...
is there a single solution that is recommended?
maybe a quick reference in the readme would be helpful as from #872 I am really not sure what is the approach to adopt... best practice?

regards

**Comment by lookfirst** [comment]
I think everything is still being decided. You're a JS Ninja, help us figure it out. =)

**Comment by born2net** [comment]
:) word!
from the looks of it, the future (tx to Guy) has been decided: http://jspm.io/0.17-beta-guide/hot-reloading.html

**Comment by born2net** [comment]
tx for the feedback
