### ISSUE TITLE
Automatically trace and include dependencies in separate bundles?

### ISSUE THREAD

**Issue by deitch** [jspm/jspm-cli#1645]
How do I include all dependencies in 2 separate packages?

I know I can do:

````json
    "dist/app-build": {
      "includes": [
        "[*.js]",
        "*.html!text",
        "*.css!text"
      ],
      "options": {
        "inject": true,
        "minify": true,
        "depCache": true,
        "rev": false
      }
    }
````

which will include all of my js files except those included elsewhere, and then:

````json
    "dist/vendor-build": {
      "includes": [
        "a",
        "b",
        ....
        "c"
      ],
      "options": {
        "inject": true,
        "minify": true,
        "depCache": true,
        "rev": false
      }
    }
````

which will include a, b, c, etc. 

But what I really want is:

* Include all my app's source files (probably from `src/`) in `app-build.js`
* automatically include every other dependency from `jspm_packages/` in `vendor-build.js`

Right now, I only have a few options:

1. List everything in `dist/vendor-build` key. Now I am listing everything in `package.json` and my config for bundling. Duplication and messy.
2. Include everything in a single file.

Is there any way to include everything recursively from `src/` in one and every dependency it finds while parsing those in another?

**Comment by deitch** [comment]
One of the earlier bundlers had something like this. I don't remember if it was requirejs or browserify or something, but maybe I am remembering it incorrectly?

**Comment by guybedford** [comment]
This can be done with the build syntax `jspm bundle '*.js + *.html!text + *.css!text' - [*.js] - [*.html!text] - [*.css!text] vendor-bundle.js` and then `jspm bundle '*.js + *.html!text + *.css!text - vendor-bundle.js' app-bundle.js` to make the app bundle. Making this case much easier in jspm in future is also being tracked through a possible flag to sugar this case.

**Comment by deitch** [comment]
Hey @guybedford . Thanks for the response. 2 questions:

1. I didn't get that. How does that syntax cause all of my libs not in `src/` to go into the `vendor-bundle.js`?
2. Can you show me how to do that in config file syntax?

**Comment by guybedford** [comment]
I'm not sure what builder system you are using here, but the jspm API works through arithmetic syntax, see https://github.com/systemjs/builder#bundle-arithmetic for more info.

This can be accessed directly through the jspm builder API wrapper - https://github.com/jspm/jspm-cli/blob/master/docs/api.md#class-builder.

**Comment by deitch** [comment]
For q2, I was trying to understand how you would structure if with `config.js`, e.g. what is given in prod workflows http://jspm.io/docs/production-workflows.html

As for 1, I still don't fully get it.

````
jspm bundle '*.js + *.html!text + *.css!text' - [*.js] - [*.html!text] - [*.css!text] vendor-bundle.js
jspm bundle '*.js + *.html!text + *.css!text - vendor-bundle.js' app-bundle.js
````

I see how the second line will exclude everything already in the first line, using `- vendor-bundle.js`. Makes sense. But how does the arithmetic syntax in the first line cause it to include everything in `jspm_packages/` but exclude everything in my own app source?  Obviously the difference is in the ` - [*.js] - [*.html!text] - [*.css!text]` exclusion, but I clearly didn't understand what that does?

**Comment by guybedford** [comment]
`jspm bundle x` means bundle x and all its dependencies. `jspm bundle [x]` means bundle just x, and none of its dependencies. So `jspm bundle x - [x]` means bundle just the dependencies of x.

**Comment by deitch** [comment]
Thanks @guybedford that works.
