### ISSUE TITLE
JSPM Karma installation

### ISSUE THREAD

**Issue by m-a-r-c-e-l-i-n-o** [jspm/jspm-cli#1646]
I'm trying to integrate the Karma test runner into my jspm workflow and according to this closed issue https://github.com/jspm/jspm-cli/issues/863 it doesn't seem like Karma should be installed through jspm and live in the "jspm_packages" folder. Is this still true as of jspm 0.17 Beta? If so, any plans to address this in the future, or should I just get used to the idea of having certain things be installed directly with NPM into a "node_packages" folder?

Thank you for the work, it's been a pleasure so far.

**Comment by guybedford** [comment]
Sure, yes Karma is something that needs to always be installed with npm. Node support for jspm is improving, but it doesn't yet support all the features needed to run Karma.
