### ISSUE TITLE
Multiple calls to jspm install is slow

### ISSUE THREAD

**Issue by RomkeVdMeulen** [jspm/jspm-cli#1647]
I've added `jspm install` to the build script for my project. That this takes some time on a clean build is to be expected. But if the build is run again, it takes 6-7 seconds for `jspm install` to complete, even if nothing needs to be updated.

Is there anything I can do to speed this up?

**Comment by guybedford** [comment]
You can use `jspm install -q` to speed it up, which will just check the dependencies are present, without verifying the deep tree version resolutions.

**Comment by RomkeVdMeulen** [comment]
Thanks! That's exactly what I needed.

This option doesn't show up when I run `jspm --help` on 0.16.31. Is that intentional?

**Comment by guybedford** [comment]
Sure, it's only shown in the CLI help in jspm 0.17 as it was still somewhat experimental in jspm 0.16.

**Comment by RomkeVdMeulen** [comment]
Ah, I see. Thanks for clarifying that.
