### ISSUE TITLE
JSPM beta - memory leak

### ISSUE THREAD

**Issue by ggrimbert** [jspm/jspm-cli#1648]
Hi,

I am experiencing a problem while using jspm beta.

The jspm process takes more and more RAM until it has to swap, and then it kills itself with the following error.
```
<--- Last few GCs --->

   79820 ms: Scavenge 1396.7 (1456.7) -> 1396.7 (1456.7) MB, 2.1 / 0 ms (+ 2.8 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
   80933 ms: Mark-sweep 1396.7 (1456.7) -> 1396.7 (1456.7) MB, 1112.8 / 0 ms (+ 12.5 ms in 76 steps since start of marking, biggest step 2.8 ms) [last resort gc].
   82034 ms: Mark-sweep 1396.7 (1456.7) -> 1396.7 (1456.7) MB, 1101.3 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x243b37844a49 <JS Object>
    1: toString [/home/ggrimbert/edevelo/local/Aurelia/testUpdateAurelia/node_modules/traceur/bin/traceur.js:~15988] [pc=0xc34512f4492] (this=0xf89efef8531 <a SourcePosition with map 0x2823cbc75f39>)
    2: DefaultNumber [native runtime.js:~514] [pc=0xc34515fb92b] (this=0x243b378c22b9 <JS Global Object>,h=0xf89efef8531 <a SourcePosition with map 0x2823cbc75f39>)
    3: $toPrimitive(aka ToPrimit...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
Abandon (core dumped)
```

This happens while calling **jspm install**.

My project works fine in jspm 1.16.15. When I launch the command, my available RAM is about 3.5Go.

**Comment by guybedford** [comment]
jspm does use a lot of memory unfortunately, likely due to some leaks. Your RAM limit here looks like 1.5G, perhaps see if any specific installs are adding larger memory use here if you try installing dependencies one-by-one or removing dependencies from the tree? The other thing to note is that jspm runs a npm build step when installing npm dependencies. These may possible consume some bigger chunks of memory as well, and it it's a specific dependency that may be fixable with an override.

**Comment by ggrimbert** [comment]
Hi,

I tried what you've said and I found the problem, it's effectively one dependency that causes the problem, I will post on their issue tracker.

I had those logs while trying to install this dependency : 
```
warn It's taking a long time to process the dependencies of npm:pnotify@3.0.0.
     This package may need an ignore property to indicate test or example folders for jspm to skip.
```
and then the stack like previously. Is there a way to increase the RAM for jspm to see if it changes anything ?

**Comment by guybedford** [comment]
You can do this ignore via an override with for example:

```
jspm install npm:pnotify@3.0.0 -o "{ignore:['libtests','build-tools','includes']}"
```

**Comment by ronzeidman** [comment]
trying to install npm:ag-grid@4.1.0 and later will result in an out-of-memory exception (the same one), letting node get to 10GB RAM will not resolve it. when installing npm:ag-grid@4.0.5 and earlier there is no issue.
npm works with all versions with no issues.

**Comment by ronzeidman** [comment]
adding `-o "{ignore:['.idea','spec','src','dist']}"` which are all folders doesn't solve the issue

**Comment by ronzeidman** [comment]
was able to workaround by downloading manually, compiling locally and linking to the local folder.

**Comment by guybedford** [comment]
The ignores are definitely working fine here in jspm 0.17. Note that jspm 0.16 doesn't do the ignores before the build though so will have this issue. This is not so much a memory leak specifically in this scenario as just high memory.
