### ISSUE TITLE
peerDependency version matching bug?

### ISSUE THREAD

**Issue by mkampik** [jspm/jspm-cli#1649]
Hi,

I am running jspm version ```0.17.0-beta.11``` and have ```react-dom@^0.14.7``` installed.

When trying to ```jspm install npm:react-keydown```, I get the following error message although my version of react-dom should match just fine:

> err  Installing npm:react-keydown@1.4.8, no version match for npm:react-dom@>= ^0.14.0

Any ideas? [This guy](https://github.com/gaearon/react-dnd/issues/162) seemed to have a similar issue with a package requiring react.

Thanks in advance,

Max

**Comment by guybedford** [comment]
jspm doesn't support arbitrary operators in version ranges beyond `^` and `~` in an attempt to naturally enforce semver. It can be a compatibility catch though and given enough user pressure it could change.

**Comment by guybedford** [comment]
When installing npm:react-keydown, jspm is supposed to convert the range `>=^0.14.0` into the range `^0.14.0` within the npm conversion process. If that is being converted into `^0.15.0` then that may be a bug here.

**Comment by guybedford** [comment]
It turns out that `>=^0.14.0` is not actually a valid version range according to https://github.com/npm/node-semver. I'd suggest posting an issue to the react-keydown project.

**Comment by mkampik** [comment]
Will do! I wasn't aware of this - thanks for looking into it @guybedford!
