### ISSUE TITLE
Question on package override for Angular2

### ISSUE THREAD

**Issue by jcmoore0** [jspm/jspm-cli#1651]
Hi Guy - Thanks for all of your fantastic work on JSPM.

When I first converted to v17, the angular2@2.0.0-beta.12.json contained may meta properties:
  "main": "index",  "format": "cjs", "meta": {
    "*": {
      "globals": {
        "process": "process"
      }
    },
    "*.json": {
      "format": "json"
    },
    "animate.d.ts": {
      "format": "esm"
    },    (1244 lines)

If I remove and reinstall angular2,  the angular2@2.0.0-beta.12.json contains:
{
  "meta": {
    "src/core/util/decorators.js": {
      "deps": [
        "reflect-metadata"
      ]
    }
  }
} 

I notice this caused system to load additional packages (crypto..) and some error "no directive annotation found on NgClass".   If I copy the original json back the problem disappears.

Do you have any suggestions for installing angular2 beta?

Thanks and best regards,
John

**Comment by guybedford** [comment]
Thanks so much @jcmoore0 for posting here. Yes there was an attempt to check in an Angular 2 in https://github.com/jspm/registry/pull/797, but this was something that did not have enough feedback as I am not an Angular 2 user myself.

Can you perhaps share a test project that demonstrates the issue? I'd be really grateful for any help in working out how to fix the override here.

**Comment by guybedford** [comment]
Ok i've added a possible correction override at https://github.com/jspm/registry/pull/846. If you could try that out (updating the overrides section of the package.json accordingly then running `jspm install` would work) that would be a great help, but no pressure at all.

**Comment by guybedford** [comment]
The correction override is now live and can be refreshed via `jspm update angular2 -o`. Please let me know if you notice any more issues here.
