### ISSUE TITLE
JSPM Error on Fetch for file that exists

### ISSUE THREAD

**Issue by Wavewash** [jspm/jspm-cli#1652]
I am trying to bundle the dependencies for a project:
![image](https://cloud.githubusercontent.com/assets/315474/14068130/9cb41076-f447-11e5-8304-89f5e07d966a.png)
The command I'm running is to just bundle the dependencies:
`jspm bundle app/**/* - [app/**/*] build/dependency-bundle.js`
And I'm receiving an error for a file that exists (liquidbackground.js):
![image](https://cloud.githubusercontent.com/assets/315474/14069393/16cdcaae-f467-11e5-8772-b77a02295b20.png)

This seems like a configuration issue but I'm lost as to what
jspm.browser.js:
SystemJS.config({
  baseURL: "/",
  trace: true,
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*",
    "assets/": "assets/",
    "app/": "app/"
  }
});

package.json:
"jspm": {
    "directories": {
      "lib": ".",
      "baseURL": "."
    }, ...

I apologize if this is trivial - I've done some searching and there seems to be a lot of mistakes of this sort that arise from the baseURL not being set appropriately. I'm not sure where I've made my mistake and any help would be appreciated.

Thank you!

**Comment by guybedford** [comment]
To avoid the OS from expanding the `*` characters you need to wrap the expression in quotes:

```
jspm bundle 'app/**/* - [app/**/*]' build/dependency-bundle.js
```

**Comment by Wavewash** [comment]
That solved the build issue, but I'm running into another:
![image](https://cloud.githubusercontent.com/assets/315474/14087101/64f66e36-f4f6-11e5-9a25-436fcd93fc75.png)

which seems very much like this issue:
[https://github.com/jspm/jspm-cli/issues/1404](url)

Your quoted answer was:

> This isn't at all advisable as it effectively attempts to trace every single file, it could even be a valid stack limit, and not due to anything circular!

>I've reopened systemjs/builder#188 which previously traced optimization of this case to avoid touching the file system, I think that would be what you're after here (unless you'd expect jspm bundle jspm_packages/**/* to work!).

I'm probably being foolish but that's exactly what I did expect. In attempting to create a self executing bundle I figured it would have to build all the required dependency libraries too. What's the best practice for bundling an app up for deployment?

Thank you!
