### ISSUE TITLE
[Question] React build environment

### ISSUE THREAD

**Issue by perrin4869** [jspm/jspm-cli#1657]
This is something that I've been wondering for a while. With JSPM, if I load react without bundling all my javascript, I will get the debug messages, however, after bundling, by default, the messages are gone. What is the mechanism that makes that happen? I am asking because I'm working on a React component, and I would like to add similar functionality to it. Thanks!

Edit: is there an example where https://www.npmjs.com/package/debug is integrated?

**Comment by guybedford** [comment]
In jspm 0.17, this is handled through the `--production` and `--dev` conditional build flags, with production being the default.

These conditionals can be used through SystemJS conditionals - http://jspm.io/0.17-beta-guide/conditional-loading.html.

**Comment by perrin4869** [comment]
Interesting. I think I'll go with this route.

In the react documentation they mention setting the `NODE_ENV` environment variable to production when building. When using the `--production` and the `--dev` flags, does that variable get set? Is it set as a global?

**Comment by HongJheLi** [comment]
Author replied how to use before.
[Production builds plugins don't get NODE_ENV=production from process #526 ](https://github.com/systemjs/builder/issues/526)

**Comment by perrin4869** [comment]
I see. Still trying to wrap my head around it but it's not very critical I guess. Conditional loading solves the problem I had so I'll go ahead and close this
