### ISSUE TITLE
jspm build fails if ")" or "(" or both are in the directory path

### ISSUE THREAD

**Issue by philwade** [jspm/jspm-cli#1659]
Ran into this one because jenkins drops our stuff into a folder called repo-name (branch-name).

This is on 0.17.0-beta.11

With one paren:

    studio Studios-MBP app $ jspm build scripts/app.js dist/main.js
         Creating the single-file build for scripts/app.js...

     err  SyntaxError: Invalid regular expression: /^(file:///Users/studio/code/repo-dev)/public_html/app/jspm_packages/npm/@[^\/]+/[^\/]+)(\/|$)/: Unmatched ')'
    at new RegExp (native)
    at createPkgConfigPathObj (/Users/studio/code/repo-dev)/public_html/app/node_modules/jspm/node_modules/systemjs/dist/system.src.js:2415:14)
    at getPackageConfigMatch (/Users/studio/code/repo-dev)/public_html/app/node_modules/jspm/node_modules/systemjs/dist/system.src.js:2425:97)
    at /Users/studio/code/repo-dev)/public_html/app/node_modules/jspm/node_modules/systemjs/dist/system.src.js:2384:30

With two:

    studio Studios-MBP app $ jspm build scripts/app.js dist/main.js
     Creating the single-file build for scripts/app.js...

    err  Error on translate for scripts/app.js at  file:///Users/studio/code/repo(dev)/public_html/app/scripts/app.js
      Error: EISDIR: illegal operation on a directory, read
      at Error (native)
      Error loading /Users/studio/code/repo(dev)/public_html/app/jspm_packages/npm/systemjs-plugin-babel@0.0.8

**Comment by guybedford** [comment]
Thanks, this is a SystemJS issue, tracking in https://github.com/systemjs/systemjs/issues/1188.

**Comment by philwade** [comment]
Thanks for the quick response! Any chance for the SystemJS dependency to get bumped to 0.19.25 for the 0.17 branch?
