### ISSUE TITLE
bundleSFX() / builder.buildStatic() with glob does not produce correct js.

### ISSUE THREAD

**Issue by unional** [jspm/jspm-cli#1660]
using `0.16.31`

When I run:
```js
jspm.bundleSFX('spec/A.spec.ts', 'out1.js', {});
```
the bundle file is correct and works.
When I run:
```js
jspm.bundleSFX('spec/*.spec.ts', 'out2.js', {}); // which resolve to only `A.spec.ts`
```
the bundle file is incorrect. When load the file on html, the the error is: `Uncaught Module 1 not present.`

When comparing the `out1.js` and `out2.js`, the only difference is the module index:
![image](https://cloud.githubusercontent.com/assets/3254987/14131435/fee5b0fc-f5ef-11e5-9b2e-12a917e7e34d.png)

**Comment by unional** [comment]
Error is the same if the glob resolves to 2 files.

**Comment by unional** [comment]
If this is resolved, then I have a nice example of using `jspm` with `tape`:

```js
const jspm = require('jspm');
const run = require('tape-run');
const tapSpec = require('tap-spec');
const streams = require('stream');

new jspm.Builder().buildStatic('spec/**/*.spec.ts')
.then((output) => {
  const reader = new streams.Readable();
  reader._read = function () {};
  reader.push(output.source);
  reader.push(null);

  reader
  .pipe(run())
  .pipe(tapSpec())
  .pipe(process.stdout);
});
```

**Comment by guybedford** [comment]
Fixed pending release.

**Comment by unional** [comment]
Thank!

Do you have a markdown section about how to run tests with jspm?
I spend quite some time to get it working with tape. I think other people maybe able to benefit from it. :rose:
