### ISSUE TITLE
in beta 0.12 I am getting an error, can't find CSS dir...

### ISSUE THREAD

**Issue by born2net** [jspm/jspm-cli#1661]
in beta 0.12 I am getting an error
```
jspm bundle src/App.js ./dist/index.js --skip-source-maps
     Building the bundle tree for src/App.js...

err  Error: ENOENT: no such file or directory, open 'C:\msweb\studioDashboard\css'
      at Error (native)
  Error loading C:/msweb/studioDashboard/css
I don't have or use a directory named C:/msweb/studioDashboard/css so I am not sure why the bundler is looking for that dir...
```

the project and structure can be viewed here:
https://github.com/born2net/studioDashboard

it's angular2 + typescript project

FYI in 0.16 build I run:
```
jspm bundle-sfx src/App.js ./dist/index.js --skip-source-maps
```
which works perfectly,

regards

Sean.

**Comment by born2net** [comment]
any ideas?

**Comment by guybedford** [comment]
It sounds like this is a 0.16 -> 0.17 upgrade issue then? Did you check if there is a map config for `css` present? Did you run the upgrade process?

**Comment by born2net** [comment]
sorry I am unaware of the process... can you please provide a link to the docs on what's needed to move to 0.17?

FYI I am a BIG advocate of jspm, I have been spreading the word on ng2 forms, reddit and blogs ;)

Sean

**Comment by born2net** [comment]
as for source map, I didn't need one in 0.16, do I need something special for 0.17?

**Comment by born2net** [comment]
looked at: http://jspm.io/0.17-beta-guide/package-configuration.html
but didn't see any mention of upg process...
basically in ng2 I just include css files via templateUrl which works flawlessly with 0.16

**Comment by guybedford** [comment]
CSS as a plugin is loaded because it is installed. So did you try even just `jspm install css`? That's what I mean by checking the map, because there should be an entry for `System.config({ map: { css: '...' } })`.
