### ISSUE TITLE
 _os.platform is not a function

### ISSUE THREAD

**Issue by nschloe** [jspm/jspm-cli#1662]
For a few hours now, I'm getting
```
> jspm build app/index.ts build-tmp/index.js --skip-rollup --skip-source-maps
     Creating the single-file build for app/index.ts...

err  TypeError: _os.platform is not a function
      at getNodeSystem (/paperhive-frontend/jspm_packages/npm/typescript@1.8.9/lib/typescript.js:2051:32)
      at eval (/paperhive-frontend/jspm_packages/npm/typescript@1.8.9/lib/typescript.js:2241:20)
      at ts (/paperhive-frontend/jspm_packages/npm/typescript@1.8.9/lib/typescript.js:2249:7)
      at Object.eval (/paperhive-frontend/jspm_packages/npm/typescript@1.8.9/lib/typescript.js:2250:3)
      at eval (/paperhive-frontend/jspm_packages/npm/typescript@1.8.9/lib/typescript.js:54798:4)
      at eval (native)
  Evaluating /paperhive-frontend/jspm_packages/npm/typescript@1.8.9/lib/typescript.js
  Error loading /paperhive-frontend/jspm_packages/github/frankwallis/plugin-typescript@4.0.5/plugin.js

ERROR: can't read file: build-tmp/index.js
```
on one build machine now. (Output updated following andrenarchy's comment.) Might or might not be related to bug #1092 or the 0.17.0-beta.12 release. (I couldn't reproduce this locally for now.) Perhaps related to @frankwallis's [typescript plugin](https://github.com/frankwallis/plugin-typescript).

**Comment by andrenarchy** [comment]
Unfortunately, the error is 100% reproducible on our build machines. Since we currently don't have any workaround we're not able to build/deploy anything. And it's definitely strange that we cannot reproduce this locally.

In @nschloe's output a few lines are missing; here's a bit more context:
```
$ jspm build app/index.ts build-tmp/index.js --skip-rollup --skip-source-maps
     Creating the single-file build for app/index.ts...

err  TypeError: _os.platform is not a function
      at getNodeSystem (/paperhive-frontend/jspm_packages/npm/typescript@1.8.9/lib/typescript.js:2051:32)
      at eval (/paperhive-frontend/jspm_packages/npm/typescript@1.8.9/lib/typescript.js:2241:20)
      at ts (/paperhive-frontend/jspm_packages/npm/typescript@1.8.9/lib/typescript.js:2249:7)
      at Object.eval (/paperhive-frontend/jspm_packages/npm/typescript@1.8.9/lib/typescript.js:2250:3)
      at eval (/paperhive-frontend/jspm_packages/npm/typescript@1.8.9/lib/typescript.js:54798:4)
      at eval (/paperhive-frontend/jspm_packages/npm/typescript@1.8.9/lib/typescript.js:54799:3)
      at eval (native)
  Evaluating /paperhive-frontend/jspm_packages/npm/typescript@1.8.9/lib/typescript.js
  Error loading /paperhive-frontend/jspm_packages/github/frankwallis/plugin-typescript@4.0.2/plugin.js
```
Looks like an issue in the typescript plugin, right? Do you have any idea what we could try to solve this?

**Comment by frankwallis** [comment]
This indicates that the jspm typescript override is not being applied for some reason

https://github.com/jspm/registry/blob/master/package-overrides/npm/typescript%401.6.2.json

**Comment by frankwallis** [comment]
perhaps try adding the override manually?

**Comment by JonathanDaSilva** [comment]
The override is applied and that's the problem, _os is an empty object and it try to call platform on it.

The temporary solution is to remove the override "os": "@empty" in the package.json.

Hope that will help.

**Comment by frankwallis** [comment]
Also see https://github.com/jspm/jspm-cli/issues/1092

**Comment by nschloe** [comment]
@JonathanDaSilva Thanks for the hint! Indeed, removing [the line `"os": "@empty"` ](https://github.com/paperhive/paperhive-frontend/blob/master/package.json#L235) from the package.json does the trick.

**Comment by guybedford** [comment]
@frankwallis @nschloe should we be removing the `os: "@empty"` map from the override then?

**Comment by frankwallis** [comment]
we could do, although it would be nice to know what has changed to make this start happening. This is the relevant code in typescript.js (https://github.com/Microsoft/TypeScript/blob/master/src/compiler/sys.ts):

```
        if (typeof WScript !== "undefined" && typeof ActiveXObject === "function") {
            return getWScriptSystem();
        }
        else if (typeof process !== "undefined" && process.nextTick && !process.browser && typeof require !== "undefined") {
            // process and process.nextTick checks if current environment is node-like
            // process.browser check excludes webpack and browserify
            return getNodeSystem();
        }
        else if (typeof ChakraHost !== "undefined") {
            return getChakraSystem();
        }
        else {
            return undefined; // Unsupported host
        }
```

Now I think it used to return undefined, because ```process.browser``` was true becuase ```browser``` is set in the overrides, does that make sense? It sounds like it is now going into getNodeSystem() which is why it throws this error.

**Comment by guybedford** [comment]
@frankwallis yes all those checks would pass when running jspm 0.17 in Node, so it would run the `getNodeSystem` path. So then it does seem to make sense that we run the Node version of OS here.

**Comment by frankwallis** [comment]
agreed, I'll send a PR

**Comment by guybedford** [comment]
Thanks! Just let me know if there are further issues here.

**Comment by nicky-lenaers** [comment]
I'm still experiencing this error with ``jspm@0.17.0-beta.12``, even when I remove ``os: "@empty"``. Both locally (Windows) and on my Docker builds. Is that correct?

**Comment by guybedford** [comment]
Try running `jspm install npm:typescript -o` to ensure you're getting the updated override from the registry (local overrides will persist otherwise).

**Comment by nicky-lenaers** [comment]
Cool, got it working again :) 

For those visiting this issue somewhere in the future: I have to mention I also needed to update ``plugin-typescript`` (it was still using some 1.9.0-dev version of TypeScript), so after running ``jspm install npm:typescript -o`` (as @guybedford said) **and** ``jspm install ts -o`` I was ready to go again.
