### ISSUE TITLE
Import module from another bundle

### ISSUE THREAD

**Issue by joakimstrandell** [jspm/jspm-cli#1663]
Hi,

I can't figure out how this should be solved. I have two different bundles, they are called `core.js` and `secondary.js`. In `secondary.js` I import some of the modules that also are imported in `core.js`. But when I bundle each file, the imported modules ends up in each bundle.

What is the correct approach to make the `secondary.js` bundle import a module from the `core.js` bundle?

Best regards
Joakim Strandell

**Comment by guybedford** [comment]
I hope you managed to work this out ok. If core.js is loaded with a script tag in the page, and secondary.js is bundled with injection, then you should get the sort of workflow you're after here.
