### ISSUE TITLE
jspm install --lock by default

### ISSUE THREAD

**Issue by mikz** [jspm/jspm-cli#1665]
0.17 would be good chance to switch to locking dependencies on install by default

i was bitten so many times by this, that our ci server started installing different dependencies than locally

we shrinkwrap all npm dependencies, so we are covered there

at least would be good to have a flag in the jspm config to lock dependencies by default and never upgrade on install

would that be possible?

**Comment by guybedford** [comment]
jspm is locked by default if you run `jspm install` with no arguments and include the configuration file in version control. I can't think of any reason to be running fresh installs on a CI server?

**Comment by mikz** [comment]
We run our builds in docker. All the lock files were commited in the version control, but still when new jquery version was released, our ci server installed that instead. 

So what is the difference between `jspm install` and `jspm install --lock` after fresh checkout?

When we added `--lock` to all `jspm install` commands, the issue disappeared for good.

**Comment by guybedford** [comment]
Ah ok. With no other arguments, jspm install is exactly the same as jspm
install --lock. If not that is a bug.

**Comment by mikz** [comment]
Ok. Will update to the latest beta, remove the `--lock` and see if i can reproduce it. Closing in the meantime. Thanks!
