### ISSUE TITLE
Merge jquery.cookie with jquery?

### ISSUE THREAD

**Issue by slanted** [jspm/jspm-cli#1669]
Is it possible to merge jquery.cookie into jquery so that in my app.js I could write something like this?
```
import $ from 'jquery';
console.log("jquery.cookie is:"+$.cookie); 
```
Here $.cookie is undefined as expected, but it would be cool if I could have it have $.cookie defined by doing some jspm install magic.

The way this works is to do:
```
import $ from 'jquery';
import 'jquery.cookie';
console.log("jquery cookie is:"+$.cookie);
```

Here $.cookie is properly defined, but I'm a little irked having to do 2 imports. I know, picky, but I'm curious if the system can accomodate for this. I'm using .17 of jspm-cli.

And as many people I'm confused about how I could accomplish this with a package override command such as:
>jspm install jquery.cookie;
>jspm install jquery -o "{dep:'jquery.cookie')"

Any help would be appreciated.

**Comment by guybedford** [comment]
I'm not sure if it would be that encouraged. Usually the pattern encouraged is to make jQuery plugins themselves export jQuery:

```
shim: {
  'jquery.cookie': {
    deps: ['jquery'],
    exports: '$'
  }
}
```

So you can do:

```javascript
import $ from 'jquery.cookie';
```

Otherwise to do what you're after could be achieved by setting jquery.cookie as a dependency of jquery itself.

**Comment by amenadiel** [comment]
@slanted I've done something like you describe, althought I used AMD instead of es6:

https://github.com/HuasoFoundries/jquery_helper

We use it as a drop-in replacement of jQuery
