### ISSUE TITLE
Order of modules in bundle should be deterministic

### ISSUE THREAD

**Issue by philer** [jspm/jspm-cli#1672]
When I run `jspm bundle src/app.js dist/bundle.js --inject` multiple times in a row I get a different output every time. Looking at my `jspm.browser.js` tells me that apparently the order of my modules changes. It's not completely random but slightly different every time.

I figure that the order in which modules are defined doesn't really matter to SystemJS, however this is very annoying when working with git (or probably any other vcs) since it causes changes where there shouldn't be any. It also means it becomes harder to track the effects of changes I might make to the import/export statements in my code.

Curiously enough I do believe that the order *should* be deterministic since the code is read from top to bottom and all dependencies should be resolved in a given order. I assume this has to do with whatever magic JSPM uses to resolve cycles and keep the dependency graph flat.

I don't really care to much in which order the modules are, as long as it's fixed. You might as well just sort them alphabetically.

PS: If this happens because I did something wrong please let me know. I'm on version 0.17.0-beta.12

**Comment by Munter** [comment]
I thought we added post order traversal of dependencies for bundling

**Comment by guybedford** [comment]
Thanks, this is because we're not exposing the same ordering. Fixed in https://github.com/systemjs/builder/commit/641637177f818af2ce270ae94af161760ea1cc8e.

**Comment by philer** [comment]
Cool, thanks :+1:

**Comment by guybedford** [comment]
Released in 0.17.0-beta.13.
