### ISSUE TITLE
Possibly a bug with jspm link?

### ISSUE THREAD

**Issue by slanted** [jspm/jspm-cli#1673]
First of all thanks so much for all of the prompt responses on here!

For .17: Either I'm doing this wrong or there is a bug with the override linking in the client.

I have 2 jspm projects:
1. The dependency project named 'dep'
2. A project named 'client' that has a dependency on 'dep'

In 'dep' I have installed 'jquery', and also 'jquery.cookie' with an override like this:
`>jspm install jquery.cookie -o "{format:'global'}"`

This seems to update the package.json correctly - AND it updates the jspm_packages/github/carhartl/jquery-cookie@1.4.1.json file correctly to look like this:
```
{
  "main": "jquery.cookie",
  "format": "global"
}
```

I then export my 'patched' jquery so my client can import it like this in my main in 'dep':
```
import $ from 'jquery';
import 'jquery.cookie';
console.log("$.cookie",$.cookie); // this is defined here, all is well
var patchedJquery = $;
export var patchedJquery;
```

In my 'client' app I import the patched jquery like this:
`import {patchedJquery as $} from 'dep';`

So then I go to my 'client' project and do a
`>jspm link ../dep`

'dep' is one directory up from 'client', so this works.

And it installs the jquery.cookie plugin into the jspm_packages directory of 'client', however, when I look at my jspm_packages/github/carhartl/jquery-cookie@1.4.1.json in 'client', I only see
```
{
  "main": "jquery.cookie"
}
```

Is this by design or should the "format":"global" come over? Hope this makes sense. In this case $.cookie is not defined in either 'dep' or 'client', because the network load loads 'jquery' and 'jquery.cookie' from the jspm_packages/npm/jquery and jspm_packages/github/carhartl directory in 'client', since the link command copies over the dependencies from 'dep'.

If I add the "format":"global" to the jquery-cookie@1.4.1.json in the 'client' jspm_packages directory for jquery.cookie everything works as I expect.

I hope I'm not asking for something that would cause a problem in another use case, but I thought that the link command was supposed to pickup any changes in the package.json of the dependency modules - in this case the override as well.

**Comment by guybedford** [comment]
Overrides do not get read from installed packages. While this is trivial to add as a feature, this reason this hasn't been implemented is because it leads to an ecosystem where every package inlines its own overrides, and override conflicts then become the rule.

The jspm registry is designed to be the place where shared overrides live. If you want the override to apply when your dependency is linked or installed, check it into the jspm registry.
