### ISSUE TITLE
Object.assing not getting transformed by babel

### ISSUE THREAD

**Issue by philer** [jspm/jspm-cli#1674]
I'm using jspm 0.17.0-beta.12. My code uses `Object.assign` which needs to be polyfilled. My goal is to generate a single output file (`$ jspm build …`) that contains all necessary helpers and runtime and whatever else babel uses to do its magic. According to [babel's documentation](https://babeljs.io/docs/plugins/transform-runtime/) it is able to do that.

Now there are two old issues here (#535 and #615) that make it sound like jspm was at some point able to do that. I can't get it to work though. I created a minimal project to test it (`src/app.js`):
```JS
export default class Foo {
  constructor(a) {
    this.a = a;
    let foo = {a};
    Object.assign(foo, {b:2});
    console.log(a, foo);
  }
}
```
In the resulting output the `_classCallCheck` exists (so babel's helpers are getting inlined) but the `Object.assign` call remains untouched.

So, I tried adding the transform myself:
`$ jspm i --dev npm:babel-plugin-transform-runtime npm:babel-runtime`
Added the plugin to babelOptions in `jspm.config.js`:
```JS
// ...
      "meta": {
        "*.js": {
          "loader": "plugin-babel",
          // added this to use the plugin
          "babelOptions": { "plugins": ["babel-plugin-transform-runtime"] }
        }
      }
```
This works! The output file for my example above now has 762 lines (most of it from `core-js`, but not *all* of `core-js`, which is what I was hoping for). The `Object.assign` call was replaced with **`_Object$assign`**. So it worked.

However.

In my actual project I'm importing from a package I installed via JSPM. This package contains ES6 modules which I'm using via `import` (I made sure the `main` key in the remote package's `package.json` actually points to the ES6 code's entry point). They are getting transpiled by babel, however they also contain a `Object.assign` call which is **not** getting transformed. So it appears that the imported package is getting transpiled with different settings than my local code. What now?

Summary: JSPM doesn't use babel's transform-runtime by itself and if I add it manually it only applies it to my own code.

**Comment by guybedford** [comment]
It sounds like you need a global polyfill here, that will actually set `Object.assign`. Core-js doesn't do this I assume because it doesn't want to cause any other repercussions so you are using a scoped function that represents Object.assign.

One way might simply be to write in your own code - `Object.assign = require('core-js/object/assign') // or whatever this is`.

CoreJS may also provide a module that does the above for you too.

**Comment by philer** [comment]
I know I can just include core-js or a part of it directly in my code. However since babel is able to do this transformation I'd prefer to use that. That way I don't need the entire polyfill and I also don't need any special imports.

After reading the issues I mentioned above I was under the impression that jspm should be using [babel's runtime transformation](https://babeljs.algolia.com/docs/usage/runtime/) natively ([from this comment](https://github.com/jspm/jspm-cli/issues/535#issuecomment-82317933)):
> This is fixed in the upcoming release, which uses the runtime transformation.

**Comment by guybedford** [comment]
The babelOptions you set should be applying to the imported package. Perhaps try setting `System.config({ babelOptions: {...} })` and see if that works over the meta wildcard? The meta wildcard is supposed to be catching your jspm_packages though, so thats why I'm tempted to say it sounds like the issue is in code that is not actually transpiled by Babel (and hence the global polyfill suggestion).

**Comment by philer** [comment]
The imported package also uses ES6 code and is transpiled by babel (it's actually an extracted part of my own code). I guess I'll try experimenting some more with the settings. It's a little difficult to figure out what settings work at all since there isn't exactly an abundance of documentation.

**Comment by guybedford** [comment]
Help improving the documentation is always welcome. The project is only as strong as its contributors.
