### ISSUE TITLE
0.17-beta-guide Bundling Command does not produce expected output

### ISSUE THREAD

**Issue by Wavewash** [jspm/jspm-cli#1677]
I've been struggling with getting bundling working for JSPM on my project so thought I'd try to build from the guide again http://jspm.io/0.17-beta-guide/development-bundling.html

The following line does not bundle correctly:
`jspm bundle test.js -wid`
(which bundles to -w)

I think you want this to be:
`jspm bundle test.js build.js -id`

But I couldn't get the last watch flag 'w' to work - I checked the help by `jspm --help` but the the help also does not mention --watch or --development for bundling either:
````
jspm bundle app.js + b [outfile] Create a named bundle to pre-populate the loader
  --minify --no-mangle --skip-source-maps --source-map-contents
  bundle x --config build.json   Use a custom config file for the build.

jspm bundle ./app.js --inject    Automatically load the named bundle when needed
````

**Comment by guybedford** [comment]
@Wavewash the `-w` flag was released in the 0.17.0-beta.12, so you'd need to update jspm to get that to work.
