### ISSUE TITLE
can't bundle with format = iife

### ISSUE THREAD

**Issue by davis** [jspm/jspm-cli#1678]
running into a strange thing when using the iife format (0.17.0-beta.12)

```
err  Error: ENOENT: no such file or directory, open '/Users/davis/workspace/project/node_modules/systemjs-builder/templates/sfx-iife.js'
```

when i go into the systemjs-builder directory, there is indeed no sfx-iife.js

**Comment by guybedford** [comment]
Sure, we have no `iife` format in SystemJS builder. Only `umd` or `global`.
