### ISSUE TITLE
jspm check - command to verify all modules are installed

### ISSUE THREAD

**Issue by mikz** [jspm/jspm-cli#1680]
Would be nice to have a command same as [`bundle check`](http://bundler.io/v1.1/bundle_check.html).

It would verify local modules against the lockfile, without connecting to the internet.
The benefit is that it would be much faster and it would not require internet connection. Also could help in cases when something is broken (like #1679).

The use then is like: `jspm check || jspm install` to install only, when something is missing locally.

**Comment by gertsonderby** [comment]
I would give a body part for this at this point. I'm stuck on Windows, with Visual Studio, and `jspm install` freezes up my computer for several minutes when running it as part of a VS project build. I've tried everything. But it seems like jspm is just very, very slow in this case.

Running it outside VS (i.e. in command line) doesn't help much, either.

**Comment by mikz** [comment]
I was trying `jspm install --quick` but that wasn't installing new dependencies at some point. Maybe it could work for you.

**Comment by gertsonderby** [comment]
@mikz You're a prophet and a hero, as far as I'm concerned. I was unaware of that switch, and it's solved my headache neatly.
