### ISSUE TITLE
Paths * builder config feature not working for 0.17beta

### ISSUE THREAD

**Issue by Rush** [jspm/jspm-cli#1683]
It seems this commit is the culprit https://github.com/jspm/jspm-cli/commit/1e75d3afff3ee8278ab364dc021848741bf347ce

I am using the following piece of code in my build process that you advised me once @guybedford 

``` js
    builder.config({
      paths: {
        '*': path.join(tmpBuildDir, '*')
      }
    });
```

This is because I am using separate directory for vendor scripts (jspm_packages, 3rd party scripts) and my application files.
`myapp/javascripts/` <- app files
`myapp/vendor/javascripts` <- vendor javascripts
`myapp/vendor/javascripts/jspm_packages` <- jspm packages

JSPM baseURL is set to:

```
  "jspm": {
    "directories": {
      "baseURL": "vendor/javascripts"
    },
```

Any ideas why would this fail in recent versions?

This is the error I am getting:

```
[11:54:43] Starting 'systemjs:application'...
Unhandled rejection Error on fetch for application.js at file:///code/virtkick/webapp/frontend/vendor/javascripts/.gulp-build/application.js
        Error: ENOENT: no such file or directory, open '/code/virtkick/webapp/frontend/vendor/javascripts/.gulp-build/application.js'
    at Error (native)
```

This is my setup:

``` js
var builder = new jspm.Builder();
    builder.config({
      paths: {
        '*': path.join(tmpBuildDir, '*')
      }
    });
    builder.buildStatic(moduleName,  builtJs, {
      runtime: true,
      sourceMaps: true, // change to true after #316 is fixed
      minify: !options.debug
    })
     .then(function() {
       return fs.writeFileAsync(loadJs, '');
     })
     .then(function() {
       return gulp.src([systemCspJs, builtJs, loadJs])
        .pipe(sourceMaps.init({loadMaps: true}))
        .pipe(concat(moduleName + '.js'))
        .pipe(rev())
        .pipe(sourceMaps.write('./'))
        .pipe(gulp.dest(destinationDir))
        .pipe(rev.manifest({
          base: destinationDir,
          path: destinationDir + '/' + 'rev-manifest.json',
          merge: true
        }))
        .pipe(gulp.dest(destinationDir))
        .on('end', callback);
     });
```

**Comment by Rush** [comment]
I am trying to track it down to either systemjs or systemjs-builder. So far it looks like it's not systemjs-builder's fault.

**Comment by Rush** [comment]
I have confirmed that this commit is the culprit https://github.com/systemjs/systemjs/commit/bb588cee15403be37edb807b765fc69168014f36

**Comment by Rush** [comment]
@guybedford any ideas? I can try to fix it myself and post a PR but need some guidance.

**Comment by guybedford** [comment]
What is the import that is failing here? It would help to understand the expected configuration a little more clearly, as I don't recall the exact details of the previous conversation.

In terms of tracking down the commit, note that the SystemJS builds are done for releases, so if running git bisect, a `make` operation needs to be run on SystemJS for that to catch properly, which requires `es6-module-loader` to be available in a parallel directory to SystemJS to work.

If you're able to share any more info at all that would help. Even just pointing to the previous discussion as well if you can find it.

**Comment by Rush** [comment]
This is the original discussion: Restore ability to have custom/temporary
baseURL on build time (#1152)

What is failing is any import from the * path.

**Comment by guybedford** [comment]
I'm not sure I follow the issue though, `import 'application.js'` is expected to resolve to `path.join(tmpBuildDir, '*')` right? But isn't that exactly file:///code/virtkick/webapp/frontend/vendor/javascripts/.gulp-build/application.js then? How is the path incorrect?

**Comment by Rush** [comment]
The correct path is: `file:///code/virtkick/webapp/frontend/.gulp-build` - also just found out that providing an absolute path via `{ paths: { '*': '/home/rush/code/virtkick/webapp/frontend/.gulp-build/*' } }` does indeed fix it (shamefully I have to admit that I thought I checked it before pasting this issue but I must have done it badly ...)

Also, where this `.gulp-build` comes from is transpiling/post-processing project's js/jade sources whereas `vendor` is smth that's taken as it is without touching it. For example in vendor there may be also non-jspm 3rd party js files.

Doens't this https://github.com/systemjs/systemjs/commit/bb588cee15403be37edb807b765fc69168014f36#diff-6ca98ddd5ecd1e80fe9d555133609912R1882 change the way the path is resolved?

**Comment by guybedford** [comment]
Paths are resolved relative to the baseURL themselves. So if it was a name like `frontend/.gulp-build` then that would have had the baseURL applied. The solution is to use an absolute URL or a relative URL (`./.gulp-build` say), exactly as you have done.

That line specifically is only for package configuration. So it sounds like this may have been some sort of bug fix that broke this assumption, but the behaviour sounds correct.

**Comment by Rush** [comment]
@guybedford Thanks so much for leading me to a fix. Indeed it must have worked accidentally, Have a great Sunday.

**Comment by guybedford** [comment]
Sure no problem at all, it is always good to check these cases.

**Comment by Rush** [comment]
Hi @guybedford - this seems to be not working for 0.17.beta. Can you advise what needs to be adjusted?

**Comment by Rush** [comment]
Ok it seems the problem is that requiring the files without extension fails. Any ideas?

**Comment by Rush** [comment]
I think I was missing `"main"` and `"name"`.  Now I have a problem with bluebird:

```
Message:
    Cannot read property 'map' of undefined
Stack:
TypeError: Cannot read property 'map' of undefined
    at /home/rush/code/virtkick/webapp/frontend/node_modules/systemjs-builder/lib/trace.js:238:39
```

After adding `console.log(pkg, subPath, normalizedPkgName);;` below that line, I get:
```
undefined './js/release/bluebird.js' 'file:///home/rush/code/project/frontend/.gulp-build/jspm_packages/npm/bluebird@3.4.6'
```

@guybedford how else can I help? Should installing bluebird with `jspm install bluebird` just work with this beta?

**Comment by guybedford** [comment]
@Rush `jspm install bluebird -f && jspm bundle bluebird` seems to work fine for me in jspm 0.17. What would be the simplest steps to replicate?
