### ISSUE TITLE
Global require conflict in 0.16.32

### ISSUE THREAD

**Issue by JordanBelford** [jspm/jspm-cli#1684]
The app I am working on expects require to be on the global scope, but 0.16.32 undefines require, from https://github.com/systemjs/systemjs/issues/1161

The dependency that needs require is dojo in the esri mapping API. (https://developers.arcgis.com/javascript/) We link to it with a script tage from their CDN.

What is the recommended solution or workaround?

**Comment by guybedford** [comment]
This is being tracked in https://github.com/systemjs/systemjs/issues/1199.
