### ISSUE TITLE
Bundling with gulp and arithmetics in 0.17

### ISSUE THREAD

**Issue by smajl** [jspm/jspm-cli#1688]
Hi, please, would love to get a little hint for my migration attempt to 0.17. I used this gulp task to build my app:
```javascript
gulp.task('bundle', gulp.series(gulp.parallel('less', 'templates'), bundleFn));
function bundleFn (cb) {
  var Builder = require('jspm').Builder,
      builder = new Builder();

  builder.loadConfig('jspm.conf.js').then(function() {
    builder.config({
      separateCSS: true
    });

    Promise.all([
      builder.trace('src/main.js'),
      builder.trace('src/vendor.js')
    ]).then(function (trees) {
      return Promise.all([
        builder.bundle(builder.subtractTrees(trees[0], trees[1]), PATHS.tmp.basePath + 'main-bundle.js'),
        builder.bundle(trees[1], PATHS.tmp.basePath + 'vendor-bundle.js')
      ]);
    }).then(function () {
      return cb();
    }).catch(function (e) {
      cb(new Error(e));
    });
  });
}
```
Those `main-bundle.js` and `vendor-bundle.js` files are then injected into `index.html` file. It worked in 0.16.x, but in 0.17 I get this in console while loading the page:
```
Error: Error: XHR error (404 Not Found) loading http://localhost:8001/jspm_packages/github/angular/bower-angular@1.5.3.json
	Error loading http://localhost:8001/jspm_packages/github/angular/bower-angular@1.5.3.json
	Error loading http://localhost:8001/src/main.js
```
It seems like ignoring those bundles and still trying to reach for separate files (which are not available in dist location of course). What should I do differently in 0.17?

EDIT: I tried switching from `Builder = require('jspm').Builder` to `Builder = require('systemjs-builder')` (version 0.15.14) but then I get this error when building:
```
Error: Error: Error on instantiate for src/main.js at file:///c:/xxx/front-end/src/main.js
	Error: Unable to fetch "github:angular/bower-angular@1.5.3.json". Only file URLs of the form  allowed running in Node.
	Error loading github:angular/bower-angular@1.5.3.json
```

**Comment by guybedford** [comment]
You should definitely use `require('jspm').Builder`. Also note you shouldn't need to load the `jspm.conf.js` file although that wouldn't break anything. Can you share any replication here at all perhaps?

There's a patch release coming out soon, which may be worth checking as well here.

**Comment by ahmedshuhel** [comment]
@guybedford What is/are the differences between

````javascript
var Builder = require('systemjs-builder'),
      builder = new Builder();

  builder.loadConfigSync('browswer.conf.js'); 
  builder.loadConfigSync('jspm.conf.js');
```
vs

```javascript
var Builder = require('jspm').Builder,
      builder = new Builder();
```

What is the recommended way to go if someone does not want to use `jspm api` and use `systemjs-builder` instead?

**Comment by smajl** [comment]
Btw, I have postponed migrating to 0.17. Will check this issue when the next major update to 0.17beta or final release is out.
