### ISSUE TITLE
Failed build when importing `crypto`

### ISSUE THREAD

**Issue by Demurgos** [jspm/jspm-cli#1689]
Hi,
I am facing an error when trying to create a bundle. My module relies on `reflect-metadata` which itself relies on Node's `crypto`.
Here is the error I get:

````bash
D:\projects\test\jspm-crypto>jspm bundle-sfx index dist/index
     Building the single-file sfx bundle for index...

err  Error on fetch for crypto.js at file:///D:/projects/test/jspm-crypto/crypto.js
        Loading npm:reflect-metadata@0.1.3/Reflect.js
        Loading npm:reflect-metadata@0.1.3.js
        Loading index.js
        Error: ENOENT: no such file or directory, open 'D:\projects\test\jspm-crypto\crypto.js'
         at Error (native)
````

It seems that the `crypto` module is not recognized as a native module (it should use [nodelibs-crypto](https://github.com/jspm/nodelibs-crypto)).

Here is [a minimal repository demonstrating the bug](https://github.com/Demurgos/jspm-crypto).

This is a regression, it worked ~2 weeks ago. (I am using `jspm@0.16.32`)

**Comment by guybedford** [comment]
The `@crypto` dependency of reflect-metadata was removed in https://github.com/jspm/registry/blob/master/package-overrides/npm/reflect-metadata%400.1.3.json, since this is a dependency of Angular2 which loads these unnecessary parts.

This will work in jspm 0.17 though due to this being set up as a conditional dependency.

Alternatively you can locally use an override to fix this - 

```
jspm install npm:reflect-metadata -o "{map:{},jspmNodeConversion:true}"
```

**Comment by Demurgos** [comment]
I also get the error without `reflect-metadata`:

index.js:
````js
var crypto = require("crypto");
console.log(crypto);
````
Bundle:
````bash
D:\projects\test\jspm-crypto>jspm bundle-sfx index dist/index
     Building the single-file sfx bundle for index...

err  Error on fetch for crypto.js at file:///D:/projects/test/jspm-crypto/crypto.js
        Loading index.js
        Error: ENOENT: no such file or directory, open 'D:\projects\test\jspm-crypto\crypto.js'
         at Error (native)
````
Shouldn't jspm automatically resolve node libs ?
I fixed it by listing crypto as one of my dependencies but I wasn't satisfied with this. I'll try your solution.

**Comment by guybedford** [comment]
You'd need to trace which parent is importing it. Crypto is also removed for AngularJS 2 itself, so it may be that.

**Comment by Demurgos** [comment]
I get this error even **without any third-party dependency**.
I updated [the demonstration repository](https://github.com/Demurgos/jspm-crypto) to make it clearer. (I mentioned `reflect-metadata` because it is how my coworker discovered the error, but it fails even when I import `crypto` directly).

[package.json](https://github.com/Demurgos/jspm-crypto/blob/master/package.json)
````json
{
  "name": "jspm-crypto",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "jspm bundle-sfx index dist/index"
  },
  "author": "",
  "license": "ISC",
  "jspm": {
    "dependencies": {},
    "devDependencies": {}
  },
  "dependencies": {},
  "devDependencies": {
    "jspm": "0.16.32"
  }
}
````
[index.js](https://github.com/Demurgos/jspm-crypto/blob/master/index.js)
````js
var crypto = require("crypto");
console.log(crypto );
````

This minimal set-up really demonstrates the error. The error happens even without `angular2` or `reflect-metadata`. I am still writing under the assumption that JSPM detects automatically imported modules such as `events`, `utils`, `path` or `crypto` (like browserify does) so maybe it's just a misconception on my side but I would like to understand.

Here is how to quickly reproduce my error:
````bash
git clone https://github.com/Demurgos/jspm-crypto.git
cd jspm-crypto
npm install && jspm install
jspm bundle-sfx index dist/index
````

**Comment by guybedford** [comment]
jspm doesn't automatically set up crypto for you, it only automatically detects when a npm package requires crypto via static analysis at install time.

There is supposed to be an empty mapping for crypto in the Angular override - that is it shouldn't even be detected as a dependency when building. If you can track what is loading it, you can null it out. Alternatively you can also `jspm install crypto` if it really is needed to be built.

**Comment by Demurgos** [comment]
> jspm doesn't automatically set up crypto for you, it only automatically detects when a npm package requires crypto via static analysis at install time.
Thank you for clarifying it: this was the reason of my problem.

I was able to build with `jspm install npm:reflect-metadata -o "{map:{},jspmNodeConversion:true}"`.
