### ISSUE TITLE
Install of superagent defaulting to node implementation

### ISSUE THREAD

**Issue by cengage-stan** [jspm/jspm-cli#1690]
I'm not sure if this is the right place for this so hopefully someone can help point me in the right direction:

At some point in the past when I did a jspm install of superagent the wrapping module (jspm_packages/npm/superagent@1.3.0.js ) contained this:
require("npm:superagent@1.3.0/lib/client");

Now it appears that it's defaulting to the node impl (jspm_packages/npm/superagent@1.6.1.js):
module.exports = require("npm:superagent@1.6.1/lib/node/index.js");

I looked through the history of superagent's package.json, but package.main and package.browser do not appear to have changed between 1.3.0 and 1.6.1:

"main": "./lib/node/index.js",
"browser": {
    "./lib/node/index.js": "./lib/client.js",
    "emitter": "component-emitter",
    "reduce": "reduce-component",
    "./test/support/server.js": "./test/support/blank.js"
  },

Attempting to reinstall 1.3.0 now yields the same results (pointing to node). 

I'm making an assumption on how jspm creates that wrapping module though, so I may be off base, but was hoping someone here could help shed some light.  Thanks!

**Comment by bennullgraham** [comment]
So, this is total hax, but it unbroke our application.
```
cd jspm_packages
sed --in-place 's#lib/node/index.js#lib/client.js#g' **/*.js
```

**Comment by NervosaX** [comment]
https://github.com/jspm/registry/commit/26c127a44b86414f236b00c3c5eda0ad39f02be7 related?

**Comment by cengage-stan** [comment]
Could also be related to this: https://github.com/jspm/jspm-cli/issues/1062

**Comment by guybedford** [comment]
I've reverted the Superagent override removal in https://github.com/jspm/registry/commit/1efc81df23621e8810f48220241f4befbd922083, so this should be working again.

@cengage-stan you're exactly right, the override shouldn't be needed, but is needed until https://github.com/jspm/npm/issues/115 is fixed.

**Comment by guybedford** [comment]
(note that in jspm 0.17 overrides check into the package.json once installed, so that future registry changes don't break packages, exactly to avoid this sort of thing that is possible in jspm 0.16). Upgrading is very much recommended.

**Comment by cengage-stan** [comment]
Was just about to put in a workaround to manually override the map in our system config file!  Looks like the registry revert is working now.  Much appreciated!

module.exports = require("npm:superagent@1.6.1/lib/client");

**Comment by cengage-stan** [comment]
Thanks @guybedford, will definitely look into upgrading to 0.17.

**Comment by NervosaX** [comment]
That's all well and good, but .17 isn't even the default yet. Is it safe to upgrade?

**Comment by guybedford** [comment]
Yes it is safe to upgrade, the beta is mostly pending documentation at this point.

**Comment by NervosaX** [comment]
Thank you for that. Sorry for my last comment, it reads a little rude. It's just a big deal changing a whole lot of our apps to new version.
