### ISSUE TITLE
It seems css loader can't handle @empty

### ISSUE THREAD

**Issue by hadalin** [jspm/jspm-cli#1692]
I want to map _angular-material.css_ to _empty_.

```
packages: {
    "angular-material": {
      "map": {
        "./angular-material.css": "@empty"
      }
    }
  },
```

And when I try to create a self-executing bundle, I get

`Unhandled rejection TypeError: Global SFX bundle dependency "@empty!css" must be configured to an environment global via the globalDeps option.`

In some other instance I get

```
[09:52:08] Error: CSS Plugin:
Broken @import declaration of "null"
    at someproject/jspm_packages/github/systemjs/plugin-css@0.1.20/css-builder.js:76:13
```

**Comment by kostko** [comment]
Note that it works if you map it to some other CSS file, like `empty.css`. It just doesn't seem to properly handle `@empty`.

**Comment by guybedford** [comment]
Can you clarify if this is jspm 0.16 or jspm 0.17? I just tested in jspm 0.17 and this seems to work as far as I can tell?

**Comment by kostko** [comment]
This is in 0.16.

**Comment by hadalin** [comment]
Will test if it works in 0.17.

**Comment by guybedford** [comment]
Any update here?

**Comment by hadalin** [comment]
The update messes the config and I'm not able to run the app. It seems the migration process to 0.17 uses fresh settings. Is there any migration documentation available?

**Comment by guybedford** [comment]
@hadalin is there anyway you can share your app that is breaking on the update path? Help knowing how to make the path smoother would be really great - ideally we can handle these cases.

**Comment by hadalin** [comment]
By sharing the app do you mean sharing `package.json` and `jspm.conf.js`? I'm afraid that's all I can share.

This migration process should be discussed elsewhere, but it the command line tool smart enough to reuse old config, i.e. can I just use suggested values? I could toy around a bit and try to set it up myself.

**Comment by guybedford** [comment]
The upgrade path is supposed to do a configuration conversion. There is one known bug currently which hasn't been released yet which is that if you had `paths: { '*': 'x/*' }` that will break as it removes the wildcard. Other than that all configuration should be respected.

The issue is really just being able to test project upgrades, and I don't have the variety of cases to test here without users sharing cases that break.

Are you able to fix the upgrade yourself manually or is that a problem?

**Comment by hadalin** [comment]
If the upgrade does a config conversion then that helps a lot. I will try to fix the upgrade myself (don't know when exactly). There are some wildcards used, thanks for mentioning it.

**Comment by hadalin** [comment]
Went though the upgrade, hit enter on every option and now getting 404s for js files. Can't deal with this now, but can try again when new versions come out.

**Comment by guybedford** [comment]
@hadalin is there any chance you can share any part of your project here to test the upgrade path?

**Comment by guybedford** [comment]
This may just be that you need to manually still ensure `paths: { '*': 'x/*' }` is retained in the configuration until the above release is made though.
