### ISSUE TITLE
"jspm run" missing __dirname symbol

### ISSUE THREAD

**Issue by yoctopuce** [jspm/jspm-cli#1693]
Running jspm 0.17 beta 12.
I have a simple EcmaScript source file for node.js that uses Node global __dirname
- When I use "jspm build src/demo.hs index.js" followed by "node index.js", everything works well.
- When I try to run it directly using "jspm run src/demo.js", the global __dirname is undefined.

**Comment by guybedford** [comment]
We only add the `__dirname` global for CommonJS modules. ES modules will likely have their own types of metadata. Currently we support only `__moduleName` which is a file URL representing the path to the module.

**Comment by yoctopuce** [comment]
Is there a workaround similar to the System._nodeRequire trick ? Like System._nodeModuleName ?

**Comment by yoctopuce** [comment]
I just tried __moduleName and got a ReferenceError as well. Is there any prerequisite to get it defined ?

**Comment by guybedford** [comment]
`__moduleName` is only available in ES modules. AMD modules have another mechanism here - `define(['module'], function(module) { console.log(module.uri) })` and globals don't provide this information at all.

**Comment by yoctopuce** [comment]
My source file is using ES import syntax, so I guess it is  handled as an ES module. I have tried to add in my app package.json under "jspm" section a key like "format":"esm" or "format":"cjs" but I am still unable to access __dirName or __moduleName when my app is started using "jspm run"...

**Comment by guybedford** [comment]
The following definitely works - 

```javascript
export var p = 6;
console.log(__moduleName);
```

with `jspm run test.js`. What transpiler are you using here?

**Comment by yoctopuce** [comment]
I am using babel, with stage-3 extensions.
With babel, even your simple two-line examples fails with jspm run.
If I remove the directive to use babel, your example works. But I need babel...

**Comment by guybedford** [comment]
Are you running jspm 0.16 with Babel 5? That might be the issue then?

**Comment by guybedford** [comment]
Alternatively if using Babel 6 make sure you're compiling modules with the register extension or the SystemJS Babel plugin.

**Comment by yoctopuce** [comment]
No, I am using jspm 0.17 beta 12 (see first message)

**Comment by guybedford** [comment]
The default jspm 0.17 install will install plugin babel which will support this feature, so at this point it's just about working out what configuration might have been added to alter this from the default setup. Perhaps try creating a blank project with jspm and comparing the configs?

**Comment by yoctopuce** [comment]
I have tried a brand new project and I can replicate the problem. I created two files:
- package.json
- src/demo.js
(you can find them in attachment)
Then I run "npm install" to install jspm, and "jspm init" to setup jspm config files.
I edited jspm.config to add by babel options (see attached files as well) and run "jspm install".
Then I run "jspm run src/demo.js" and got the error:
    ReferenceError: __moduleName is not defined    

[Archive.zip](https://github.com/jspm/jspm-cli/files/208536/Archive.zip)

**Comment by guybedford** [comment]
You need to upgrade the version of plugin-babel being used. It's currently on version 0.0.2, if you run `jspm install plugin-babel` it should work correctly.
