### ISSUE TITLE
Beta: `files` / `jspm/files` have no effect

### ISSUE THREAD

**Issue by unional** [jspm/jspm-cli#1699]
Linked issue:
https://github.com/Orbs/jspm-git/issues/33

Using:
- jspm@0.17.0-beta.12
- jspm-git@0.5.0-beta.3

I have a package that has the following:

``` js
// package.json
{
  "files": [
    "dist/",
    "typings.json"
  ],
  "jspm": {
    "files": [
      "dist/",
      "typings.json"
    ]
  }
}
```

When I install it, neither have effect and I still get the whole repo under `jspm_package/bit/<mypackage>/`.
(bit is the registry created with `jspm-git`)

**Comment by guybedford** [comment]
Thanks for letting me know. In jspm 0.17, the registry API was updated where we don't assume that the `package.json` file is the package configuration, but rather rely on the registry itself to load the package.json and return its contents from the `download` or `getPackageConfig` hook.

We could consider adding back the auto-fallback of loading the package.json file if no config is returned by the registry implementation. This change was part of simplifying the logic of the registry API, cutting back on assumptions like this, but perhaps this is a common-sense one to keep.

**Comment by unional** [comment]
> but rather rely on the registry itself to load the package.json and return its contents from the download or getPackageConfig hook.

This this mean the registry (created by endpoint `jspm-git` in this case) should read the `package.json` and return only the filtered contents?

**Comment by guybedford** [comment]
@unional no the registry should just do:

```javascript
download: function() {
  // ...
  return JSON.parse(fs.readFileSync(path.resolve(package, 'package.json')));
}
```

**Comment by guybedford** [comment]
Sorry my explanation is completely wrong here... we do do this automatically. I'll look into it further and report back.
