### ISSUE TITLE
Add jspm/systemjs equivalent of babel-register?

### ISSUE THREAD

**Issue by rpkilby** [jspm/jspm-cli#1701]
Currently, we can write tests in es6 with the use of babel-register. With mocha, I can run the specs through babel with:
```sh
$ mocha --compilers js:babel-register [files]
```

However, babel's module loader only support loading packages installed in `node_modules`. In order to load modules installed with jspm, we have to use a small but semi-annoying amount of boilerplate. This isn't too bad for one module, but it gets increasingly unwieldy for an increasing number of modules.

```js
import {assert, default as chai} from 'chai';
import promises from 'chai-as-promised';
import System from 'jspm';
import './jspm.browser';
import './jspm.config';

chai.use(promises);

// jspm imports
let Primary
let ClassA;
let ClassB;
let ClassC;

describe('Primary', () => {
    before(() => {
        return Promise.all([
            System.import('./primary'),
            System.import('./moduleA'),
            System.import('./moduleB'),
            System.import('./moduleC'),
        ])
        .then(([primary, a, b, c]) => {
            Primary = primary.Primary;
            ClassA = a.ClassA;
            ClassB = b.ClassB;
            ClassC = c.ClassC;
        });
    ...
    });
```

This could potentially be simplified with a jspm-register or systemjs-register.
```js
import {assert, default as chai} from 'chai';
import promises from 'chai-as-promised';

import Primary from './primary';
import ClassA from 'moduleA';
import ClassB from 'moduleB';
import ClassC from 'moduleC';

chai.use(promises);

describe('Primary', () => {
    ...
});
```

A couple of considerations:
- It probably wouldn't make sense to install chai, mocha, etc... as jspm modules. Maybe jspm-register could automatically include node_modules (but override if present in jspm)?. This could also be a configuration option.
- In a browser environment, we have to include the `system.js`, `jspm.browser.js`, and `jspm.config.js` scripts. For testing purposes, a config file might be necessary to specify which scripts to load before jspm-register itself is ran. Some setups may have a different number of scripts or alternate paths, so jspm-register probably can't make config path assumptions.

**Comment by bjanderson** [comment]
+1

I've been 'npm install'ing my jspm dependencies in order to get around this same issue. I don't like doing it, but I think it's better than adding the above mentioned boilerplate to every test.

**Comment by guybedford** [comment]
Using `jspm run` to execute a jspm test module is the suggested workflow here.
