### ISSUE TITLE
Use --watch option from API

### ISSUE THREAD

**Issue by samouss** [jspm/jspm-cli#1702]
Hi,

I try to integrate JSPM workflow with Gulp.

In the latest beta release `0.17.0-beta.12` you add an option for quickly rebuild bundle, this option works perfectly with the CLI.

But I would like to use it via Gulp in order to enable browser live reload and run only one command for build the dev environment.

I check the code and the `watch` option is only handle in `bundle` and `build` and not in the exported builder `require('jspm').Builder` which I use from Gulp.

Is there a way for use this option from Gulp ?

Thanks.

**Comment by frederikschubert** [comment]
I would also really like to use this feature through the API.

**Comment by guybedford** [comment]
We currently implement the watch specifically in jspm, and not in SystemJS Builder.

We could potentially add the `watch` as an option just to the `require('jspm').Builder` extension of SystemJS builder, or we could add it into SystemJS Builder core itself.

My worry here is trying to do too much with SystemJS Builder, when it is designed to be composed into other build tools.

**Comment by samouss** [comment]
Thanks for the answer, it would be great if the SystemJS Builder can implement it. 

Like you said SystemJS is great tool, restrict the `watch` option to only JSPM is a bit sad.

This options in the Builder allow us to have workflow more performant and more customizable.

**Comment by guybedford** [comment]
It may be possible, but I wouldn't want to guarantee anything.

In the mean time you can use https://github.com/jackfranklin/jspm-dev-builder.

**Comment by jonricaurte** [comment]
@guybedford This feature would be great because for people who do not want to use the hot reloading, it would be nice to use systemjs builder and browsersync together so when the build is done watching, we can just call browsersync.reload. Right now we have to go back and forth between windows and reload manually which is more tedious.

**Comment by jonricaurte** [comment]
@samouss A way I worked around this issue is I have jspm running in one terminal window, then I have a gulp task running in another terminal window. I have the bundle build to the public folder, and then I have my gulp task watch to see if the bundle.js file has changed and if it has, use browsersync to refresh the window.

**Comment by samouss** [comment]
Thanks for your recommendation, and I'm doing that in my project too!

**Comment by thefabulousdev** [comment]
I want to use this option from the command line, I have another task which watches for changes on the bundle and re-runs tests, as `bundle module dest -w` always generates a bundle before watching, tests are run twice.

**Comment by artdias90** [comment]
+1

**Comment by jonricaurte** [comment]
@samouss @guybedford one way to integrate it into a gulp flow is the following:

```
'use strict';

var gulp       = require('gulp');
var spawn      = require('child_process').spawn;
var argv       = require('yargs').argv;

function jsTask(done) {
  if (argv.env === 'production' || argv.env === 'staging' || argv.build === 'sfx') {
    var command = spawn('./node_modules/.bin/jspm', ['build', 'h2', 'public/h2_assets/build.js', '--skip-source-maps', '--skip-rollup'], { stdio: 'inherit' });
    command.on('close', function(code) {
      done();
    });
  } else {
    spawn('./node_modules/.bin/jspm', ['bundle', 'h2', 'public/h2_assets/build.js', '--skip-source-maps', '-wd'], { stdio: 'inherit' });
    done();
  }
}

gulp.task('js', jsTask);

module.exports = jsTask;
```

And then in a combined js task you can have this:

```
'use strict';

var gulp       = require('gulp');
var uglify     = require('gulp-uglify');
var concat     = require('gulp-concat');
var gulpif     = require('gulp-if');
var insert     = require('gulp-insert');
var ngAnnotate = require('gulp-ng-annotate');
var argv       = require('yargs').argv;

function isSfxBuild() {
  return argv.env === 'production' || argv.env === 'staging' || argv.build === 'sfx';
}

function initializeApplication() {
  var angularBootstrap = 'angular.bootstrap(document, ["h2App"]);';
  if (isSfxBuild()) {
    return angularBootstrap;
  }
  return 'SystemJS.import("h2").then(function() {' +
           angularBootstrap +
         '});';
}

function combinedJsJade() {
  return gulp.src(['vendor/javascripts/browser-polyfill.js',
                   'jspm_packages/system-polyfills.js',
                   'jspm_packages/system.js',
                   'jspm.browser.js',
                   'jspm.config.js',
                   'public/h2_assets/build.js'])
    .pipe(concat('h2_app.js'))
    .pipe(insert.append(initializeApplication()))
    .pipe(gulpif(isSfxBuild(), ngAnnotate()))
    .pipe(gulpif(isSfxBuild(), uglify()))
    .pipe(gulp.dest('public/h2_assets'));
}

gulp.task('combined-js-jade', combinedJsJade);

module.exports = combinedJsJade;

```

@guybedford I think we can close this ticket and someone can make a new one in systemjs if they really want it.

**Comment by jonricaurte** [comment]
@samouss ok for @guybedford to close this issue?
