### ISSUE TITLE
Why is the "Production workflows" wiki "sad"?

### ISSUE THREAD

**Issue by kdex** [jspm/jspm-cli#1705]
In the GitHub wiki, [this](https://github.com/jspm/jspm-cli/wiki/Production-Workflows) page shows "sad" since September 2015.

At first, this seemed like vandalism, but @guybedford seemed to have made that change according to [its history](https://github.com/jspm/jspm-cli/wiki/Production-Workflows/_history) (see "Destroyed Production Workflows").

If this is due to outsourcing all of this information to [here](https://github.com/jspm/jspm-cli/tree/master/docs), could the Wiki please be deleted? (If not, what is this all about?)

**Comment by guybedford** [comment]
Wow, thanks for letting me know. I've removed these pages now.
