### ISSUE TITLE
Lock on jspm install -q

### ISSUE THREAD

**Issue by nillis** [jspm/jspm-cli#1708]
@guybedford why are dependencies locked on a quick install? This causes changes to the config.js not to be installed when executing a jspm install -q again.

![image](https://cloud.githubusercontent.com/assets/2675228/14430830/5f49d654-0003-11e6-9b16-34a37ce77282.png)

**Comment by guybedford** [comment]
I'm not quite sure I follow what you mean here. A lock means exactly that the version in the config.js file will be used. This definitely works in jspm 0.17. If it's not working in jspm 0.16 I'd advise upgrading.
