### ISSUE TITLE
`main` -o override ignored in some cases

### ISSUE THREAD

**Issue by brianfeister** [jspm/jspm-cli#1711]
If you check out [`bower-material`](https://github.com/angular/bower-material) you'll find an unusual scenario, in that their [`bower.json`](https://github.com/angular/bower-material/blob/master/bower.json) file does 
```
  "main": [
    "angular-material.js",
    "angular-material.css"
  ]
```
while their [`package.json`](https://github.com/angular/bower-material/blob/master/package.json) has 
```
  "main": "index",
```
which is pointing to this [`index.js`](https://github.com/angular/bower-material/blob/master/index.js) file, in which the dependencies are set up like:
```
// Should already be required, here for clarity
require('angular');

// Load Angular and dependent libs
require('angular-animate');
require('angular-aria');

// Now load Angular Material
require('./angular-material');

// Export namespace
module.exports = 'ngMaterial';
```

My main goal here is to bypass this `index.js` file above, in order to require only the minimized dependencies, but for some reason my 
```
jspm install angular-material=github:angular/bower-material@1.0.7 -o "{ 'main': ['./angular-material.min.js','./angular-material.min.css'] }"
```
is successfully writing the overrides object to my local `package.json` and `system.config.js` but the install somehow fails, because the generated index `bower-material@1.0.7.js` has the following:
```
module.exports = require("github:angular/bower-material@1.0.7/index");
```

I've no idea why `/index` would be in that file since I've explicitly used an `-o` override to prevent that.

Am I missing something?

**Comment by brianfeister** [comment]
Seems that declaring `main` as an array with `overrides` option is not permitted in JSPM. I'll leave a project owner to comment as to why and if that's up for possible change.

**Comment by guybedford** [comment]
We can certainly look at adding a nice warning for this.

The point is the package spec needs to be quite strict so I don't want to start supporting cases like this, that don't make sense.

**Comment by guybedford** [comment]
(Note that NodeJS does not support array mains at all)

**Comment by brianfeister** [comment]
Fair enough. A warning would definitely love to see an error message for it.  I get that it's not the norm, but it is a bit of a headache to deal with packages that have array `main`s (seems like in my workflow I've encountered an increasing number of them)

**Comment by guybedford** [comment]
Also note though that array mains are supported from bower.json when installing through the github registry - https://github.com/jspm/github/blob/master/github.js#L789.

It's specifically the `jspm install npm:x` that doesn't support it as npm doesn't support it (and also cryptically fails).
