### ISSUE TITLE
Cache is returning .json imports when using jspm 0.16 after using 0.17

### ISSUE THREAD

**Issue by NervosaX** [jspm/jspm-cli#1712]
I'm attempting to upgrade to jspm 0.17 from 0.16 - which is proving to be a lot of work. I then needed to go back to work on code from 0.16... and after clearing out the jspm_packages folder and re-installing, was getting errors where it was trying to load .json files (which the new spec seems to run on). After pulling my hair out, I got the idea to try a full cache clear... and bingo, it works.

Obviously the cache is storing files incompatible with 0.16.

---

A specific example was the require in here being replaced with `.json!systemjs-json`
https://github.com/unshiftio/url-parse/blob/master/lolcation.js#L30

**Comment by guybedford** [comment]
The entire cache is supposed to be versioned, so if it is not clearing that is certainly a bug. What OS are you running on here?

**Comment by NervosaX** [comment]
This is Linux, Ubuntu 16.04. I noticed jspm install -f doesn't seem to get around it either, only a full cache clear
