### ISSUE TITLE
0.17 question: plugin inside of bundle used to load a dependency of that bundle

### ISSUE THREAD

**Issue by joeldenning** [jspm/jspm-cli#1713]
First off, I appreciate the good work done here -- I just migrated from jspm bundle to jspm build and am loving the noticeable boost in performance.

My question is if it is possible for a plugin that is inside of a bundle that was created with `jspm build` to be used when loading the dependencies of the bundle itself.

My use case is that that the external dependencies of my `jspm build` bundle rely on the [sofe](https://github.com/CanopyTax/sofe) systemjs plugin. In a `jspm bundle` workflow, this is not problem, since the bundle executes fully, calling System.registerDynamic all throughout, and then a `System.import('main')` is done afterwards. But the same cannot be done (as far as I know) with a `jspm build` workflow, since the built file doesn't do the `System.registerDynamic`s until *all* dependencies (including plugins) are loaded.

My workaround for now is to create two bundles -- one that is loaded first and is `jspm bundl`ed with the `sofe` plugin. The second bundle is a `jspm build` bundle that declares the dependencies on things that use the sofe plugin. Is there a better way for me to do this (without two script tags??).

**Comment by joeldenning** [comment]
To give some code examples of what I mean, here's what I'm doing but am hoping to consolidate into one bundle:

```bash
# build process
jspm bundle sofe dist/plugins.js
jspm build src/main.js - external-dep\!sofe dist/bundle.js
```

```html
<!-- The html page -->
<html>
  <!-- assume I've already loaded all the system.js files and the config files and the polyfill, etc. -->
  
  <!-- script tag the plugins bundle, since it is not self executing -->
  <script src="/dist/plugins.js"></script>

  <!-- then System.import the self executing bundle -->
  <script>
    System.import('dist/bundle.js');
  </script>
</html>
```

**Comment by guybedford** [comment]
You're doing this exactly correctly - builds don't share their internals or handle dynamic loading. A bundle is just a multiplexing of many modules into one file, retaining dynamic linking, while a build is a static optimization of many modules into a single module.

**Comment by joeldenning** [comment]
Sounds good -- as I think about it more and more it now makes sense why there *must* be the two bundles.
