### ISSUE TITLE
Global mappings conf?

### ISSUE THREAD

**Issue by amenadiel** [jspm/jspm-cli#1720]
There's a chance this doesn't go here, or that is already supported, but I haven't found any other way  that isn't manually overriding everything.

I've noticed that most packages installed from the NPM registry have nodelibs-* dependencies. Some of them depend only on those libs: fs, path, stream, buffer, process, etc.

In turn, some of those nodelibs have their own dependencies, tied to specific versions that might cause several forks to coexist unnecesarily. Today I spent several hours cleaning a large project that had 3 versions of npm:isarray, 2 of chalk, 3 of stream concat, and so on.

 It turns out that, if I explicitly install path, fs, stream, process, etc and manually declare map overrides for the 12 devdependencies like

```sh
jspm install --dev somepackage -o '{"map": {"fs":"fs", "path":" path", "process":" process" }}'
```

Most forks go away, and the config file goes from 700 to 200 lines. 

I really wish there was a way to set **my current project** to assume a mapping override for every nodelib dependency and store that setting in package.json so it would be reproducible.

**Comment by guybedford** [comment]
If you use jspm 0.17, it installs these core libs as peer dependencies, and there is some more restriction over the external deps. I'd suggest trying to upgrade if you can, although let me know if you hit any issues.
