### ISSUE TITLE
Add support for transpiling via Bublé

### ISSUE THREAD

**Issue by swernerx** [jspm/jspm-cli#1721]
There is a new high-performant ES6 -> ES5 transpiler called Bublé. It would be amazing if we could use them as an alternative to Babel/TypeScript.

"Bublé limits itself to ES2015 that can be transpiled to compact, performant ES5"
https://gitlab.com/Rich-Harris/buble

**Comment by guybedford** [comment]
This would only be possible to support in jspm itself if Buble supported compiling module syntax into a compatible form, otherwise it would be fine to include in the registry as a plugin loader.
