### ISSUE TITLE
Help message doesn't display on Cygwin

### ISSUE THREAD

**Issue by nguillaumin** [jspm/jspm-cli#1724]
Hi,

I'm using v0.16.32 and the help message doesn't display nicely on Cygwin. Running `jspm` only shows "JSPM" on a white background then a bunch of empty lines. Selecting these empty lines shows that there seem to be some text present but it's black on black background:

![jspm-cli-cygwin](https://cloud.githubusercontent.com/assets/762512/14547514/e5889d86-02f1-11e6-939f-ef1516d35229.png)

Commenting the fancy escape codes in `cli.js` : `showHeader()` fixes the problem, so it seems to be related to them...

It works fine on the Windows default command prompt.

Nico

**Comment by nguillaumin** [comment]
When running a command (e.g. `jpsm install`) the text is correctly displayed (presumably because the header is not output so there are no escape codes to mess up the display).

**Comment by guybedford** [comment]
Thanks, I fixed this in jspm 0.17 in https://github.com/jspm/jspm-cli/commit/044bbff9669f35c24124de5db6d9eb67c4f3cdb7.
