### ISSUE TITLE
source-maps works not correct( not the dynamic created )

### ISSUE THREAD

**Issue by SerkanSipahi** [jspm/jspm-cli#1725]
@guybedford does source maps works correctly( not the dynamic created ) here by anyone? our sourcemaps are not working corretcly ( im trying to place a breakpoint in a script and it will jump several lines down/up rather than where I'm trying to set it ) since we have changed from jspm@0.16.x to jspm@0.17.0-beta.13. We use as precompiler for creating es6 to es5 + sourcemaps babel-cli and as loader systemjs which is included in jspm. Whats going wrong?

**Comment by SerkanSipahi** [comment]
@guybedford update: source-maps works with Chrome-Canary (Version 52.0.2705.0 canary (64-bit)) but not with Chrome-Stable(Version 50.0.2661.75 (64-bit))

**Comment by SerkanSipahi** [comment]
@guybedford finding problem/issue ( test it with many files ): if i remove the comments ( //, /* ...*/ ) sourcemaps works are correct in all major stable browsers. Also it possible to set breakpoints correctly.
How we can resolve that? Do you have any workaround for that?

**Comment by SerkanSipahi** [comment]
@guybedford update: i implemented following in my development build => before compiling from es6 to es5 i remove all comments and everything works well without any issues. I guess the comments breaks the sourcemaps.

**Comment by guybedford** [comment]
@SerkanSipahi that's really interesting, is there anyway you can share a test case that demonstrates how removing comments makes the source maps work?

**Comment by SerkanSipahi** [comment]
@guybedford sure, here is a testcase:
```
git clone https://github.com/SerkanSipahi/app-decorators.git
cd app-decorators
make install
make compile
make test
```

before you begin with the above tasks please remove this lines for broken sourcemap:
https://github.com/SerkanSipahi/app-decorators/blob/master/gulpfile.babel.js#L12
https://github.com/SerkanSipahi/app-decorators/blob/master/gulpfile.babel.js#L23

... now you can try to set breakpoints e.g. in src/libs/customelement.js , it not possible !
But if you add this lines again:
https://github.com/SerkanSipahi/app-decorators/blob/master/gulpfile.babel.js#L12
https://github.com/SerkanSipahi/app-decorators/blob/master/gulpfile.babel.js#L23

and starting make compile and make test again it is possible to setting breakpoints.

**Comment by oligot** [comment]
There is definitely something wrong with the source maps in jspm 0.17.0-beta.13.
We encounter a similar problem where setting a breakpoint on a given line set it on a totally different one.
This typically occurs with `jspm bundle` which means we can't use the new watch mode :cry:

This can be reproduced with [this demo project](https://github.com/guybedford/jspm-react-component-demo):
> git clone git@github.com:guybedford/jspm-react-component-demo
cd jspm-react-component-demo
npm install -g jspm@beta
jspm install
jspm bundle test.js bundle.js --inject

Then in Chrome (50.0.2661.75), trying to set a breakpoint in `test.js`, line 12 put it on line 1.

![jspm source maps bug](https://cloud.githubusercontent.com/assets/1004034/14673371/ec854c6e-06fd-11e6-8411-d34fca2485cc.png)

**Comment by guybedford** [comment]
Let's track this in https://github.com/systemjs/builder/issues/542.
