### ISSUE TITLE
Error: Install Clean CSS via jspm install npm:clean-css --dev for CSS build support. Set System.buildCSS = false to skip CSS builds

### ISSUE THREAD

**Issue by SerkanSipahi** [jspm/jspm-cli#1726]
Since we changed from jspm@0.16.x to jspm@0.17.0-beta.13 we get follwoing error if we run: `jspm bundle app/ApplicationBootstrap.js + pages/*.js cu.js --minify --skip-source-maps`

if we set System.buildCSS = false everything is fine but that is not what we want.

```
err  Error: Install Clean CSS via jspm install npm:clean-css --dev for CSS build support. Set System.buildCSS = false to skip CSS builds.
    at eval (eval at <anonymous> (/srv/cu-client/node_modules/jspm/node_modules/systemjs/dist/system.src.js:1482:16), <anonymous>:95:13)
    at tryCatchReject (/srv/cu-client/node_modules/jspm/node_modules/systemjs/node_modules/when/es6-shim/Promise.js:1183:30)
    at runContinuation1 (/srv/cu-client/node_modules/jspm/node_modules/systemjs/node_modules/when/es6-shim/Promise.js:1142:4)
    at Rejected.when (/srv/cu-client/node_modules/jspm/node_modules/systemjs/node_modules/when/es6-shim/Promise.js:963:4)
    at Pending.run (/srv/cu-client/node_modules/jspm/node_modules/systemjs/node_modules/when/es6-shim/Promise.js:821:13)
    at Scheduler._drain (/srv/cu-client/node_modules/jspm/node_modules/systemjs/node_modules/when/es6-shim/Promise.js:97:19)
    at Scheduler.drain (/srv/cu-client/node_modules/jspm/node_modules/systemjs/node_modules/when/es6-shim/Promise.js:62:9)
    at process._tickCallback (node.js:415:13)
```
Although we install clean-css with jspm we get the same error.

**Comment by SerkanSipahi** [comment]
Update: usually if we install something with jspm, its update jspm.config.js ( meta properties ) but not in this case with `jspm install npm:clean-cass` !

**Comment by guybedford** [comment]
Perhaps try clearing the cache or uninstalling first? `jspm install npm:clean-css -f`.

**Comment by SerkanSipahi** [comment]
@guybedford : tried following, same effect:

jspm install npm:clean-css -f // has no effect, same issue

then tried (see below), same effect:

1.) removed jspm_packages folder
2.) jspm cache-clear
3.) jspm install

Error while jspm is installing:
```
warn Error on locate for github:systemjs/plugin-css, retrying (1).
     Error: getaddrinfo ENOTFOUND github.com github.com:443
         at errnoException (dns.js:26:10)
         at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
```
whats going wrong? is that an bug?

**Comment by amenadiel** [comment]
I submitted a PR on system' plugin-css repo that might help you as a workaround, For the time beign: https://github.com/systemjs/plugin-css/pull/80

It basically allows to use clean-css instaled as a node module, and skip jspm installing said module.

**Comment by SerkanSipahi** [comment]
@amenadiel @guybedford  thanks it works with your patch but it can only resolve urls like these `import "./component.css!"` but not `import "../css/brandbook.css"` (parent paths)

getting error:
```
err  Error: CSS Plugin:
Broken @import declaration of "../jspm_packages/github/systemjs/plugin-css@0.1.20/brandbook.css"
```

**Comment by guybedford** [comment]
@SerkanSipahi if you have a folder called `css`, that can mess with the mappings when you do `import "css/brandbook.css"` as css is the plugin itself. But importing `import "./css/brandbook.css!"` and `import "../css/brandbook.css!"` shouldn't cause this problem, and if they do I'd be very interested to hear more. Basically I would suggest ensuring you have no `import "css/x.css!"` statements here, replacing them with `import "./css/x.css!"`.

**Comment by SerkanSipahi** [comment]
@guybedford sorry, i meant xxx `css/brandbook.css!` . I've mistyped here. I use the plugin. This caused not a problem `import "./css/brandbook.css!"` but if want to import from parent path `import "../css/brandbook.css"` getting "Broken @import declaration" although the parent path exists.

**Comment by guybedford** [comment]
@SerkanSipahi this is actually a normalization bug in SystemJS, I've created https://github.com/systemjs/systemjs/issues/1230 to track.

Unfortunately because it is a breaking bug, it's best to just assume that this case won't work, and rather either install the css plugin itself as another name - `jspm install plugin-css=css` say. Or to call the `css` folder something else - `styles` for example, or to put it inside a subfolder of the baseURL.

**Comment by SerkanSipahi** [comment]
@guybedford thank you renaming the folder css to styles worked like a charm :) 
`jspm install plugin-css=css` would be to much of a hassle ( touching to many files)
