### ISSUE TITLE
bundle --watch not updating bundle file

### ISSUE THREAD

**Issue by b-kelly** [jspm/jspm-cli#1727]
`jspm 0.17.0-beta.13 on Windows 10
`
I'm having some trouble with the bundle watching functionality. I looked through the issue list (open/closed both) and didn't see any similar issue to mine.

When running the bundle command (with watch) straight from the cli, the bundle builds correctly and the watcher starts. When I then save a file, the watcher confirms that the file was saved and re-runs the build. It appears that the build file has been written, but any changes to the file are _not_ included.

I built a standalone, trivial app to see if I could reproduce in a clean environment (I can).

Reproduction:

Run in a new folder:
```
npm i jspm@beta
jspm init . # continuously hit <enter> for all the defaults
```

Create two new files (app.js, test.js) in the directory:

app.js
```
import Test from 'test.js'
console.log(Test);
```

test.js
`export default 43;`

Run:
`jspm bundle app.js --watch`

Check build.js bundle file (optionally copy for diff later)

Update either app.js or test.js (any change is fine, notice change happens in console)

Check build.js bundle file again, note _changes not included_.

I've attached my repro directory to this issue. Please let me know if you need any other info or if you need me to debug anything locally.

More info:
```
>node -v
v5.10.1
```
```
>jspm -v
0.17.0-beta.13
Running against local jspm install.
```
```
>wmic os get BuildNumber
BuildNumber
10586
```

[jspm-test.zip](https://github.com/jspm/jspm-cli/files/222016/jspm-test.zip)

**Comment by guybedford** [comment]
Try installing watchman here, it offers better OS support, and will then be automatically picked up when running the watch flag.

**Comment by b-kelly** [comment]
I just installed Watchman, then tested with the same repro and problem is still persisting.

The issue isn't the initial bundling or the file watching, but the _re_-bundling after a watched file has been (correctly) found to have been changed and the rebundling happens.

I have confirmed (via manually adding log statements to the source) that the rebundling does run, the correct file is picked up as changed, and a file _is_ written (with updated date stamp), but the file that is written is the exact same as the file that was already on disk (no changes from the dependent files are included).

**Comment by guybedford** [comment]
This sounds like a windows-specific bug actually, I'll look into it.

**Comment by guybedford** [comment]
Fixed in https://github.com/jspm/jspm-cli/commit/cd2764a6d24a04c8d6e343f4c3849d90cefdf90e.

**Comment by b-kelly** [comment]
Wow, that was fast! Pulled latest and I can confirm that it IS working on my machine, both with and without Watchman.

Thanks for your work on this!
