### ISSUE TITLE
Server Side Tools not recommended installing with JSPM ?

### ISSUE THREAD

**Issue by binarysqueeze** [jspm/jspm-cli#1728]
Hi,

I noticed a comment in one of the issues stating that server side tools should only be installed with NPM and not JSPM.

I initially installed typescript via JSPM as I followed a getting started guide :-)

I then tried to install TSLINT via NPM but NPM complained that typescript wasn't installed. It was sort of right, Typescript is available in JSPM under npm but not in NPM itself.

I didn't want to install typescript under NPM as well as JSPM so I tried installing TSLINT vis JSPM i.e.

`jspm install npm:tslint --dev`

Everything seems to be working although a little confused if I have done it correctly, should I be forcing an uninstall on typescript and tslint under jspm and reinstall these under npm ?

If I install anything else in the future that requires typescript then I would need to install it via JSPM or install typescript with NPM otherwise the dependencies wouldn't be found.

The comment I saw was going back more than a year I think so I wondered if things have changed or what the recommended way of doing what I have described above.

Thanks in advance

**Comment by guybedford** [comment]
npm package support in jspm is always improving, but it is still advisable to install many tools through npm. tslint is probably advisable to install via npm. This can be done in jspm by having `jspm.dependencies` in the package.json for jspm, and root dependencies for Node. I know it can be tricky maintaining both, so it's worth finding the workflow that works best for you here.

**Comment by binarysqueeze** [comment]
Ok, no probs. I will do that. Thanks for your help. So to clarify, i would need to install typescript in both npm and via jspm. Tslint has a dependency on typescript so i would be forced to install this in NPM too - right ?

**Comment by guybedford** [comment]
Yes exactly.

**Comment by binarysqueeze** [comment]
Thanks @guybedford, all done. Again, thanks for your help.
