### ISSUE TITLE
Is jspm meant to handle TypeScript compilation?

### ISSUE THREAD

**Issue by buu700** [jspm/jspm-cli#1730]
The documentation for bundle doesn't address this at all, but I'm not sure what the transpiler configuration option would mean otherwise.

My attempts at bundling:

1. `jspm bundle-sfx cyph.im/main cyph.im/main.js`, nothing special added to config.js. Returns an error about not being able to fetch cyph.im/main.js.

2. Added a basic record for package "cyph.im" with main "main" and defaultExtension "ts". Returns an error about not being able to find one of my imports from elsewhere in my code, with ".js" instead of ".ts" added to the path.

3. Set defaultJSExtensions to false. Returns `Error: EISDIR: illegal operation on a directory, read at Error (native) Error loading /Users/buu700/cyph/angular2/shared/lib/js/npm/typescript@1.8.10`.

4. Added "meta" property with loader "ts" set for "*.ts". Returns `Error: ENOENT: no such file or directory, open '/Users/buu700/cyph/angular2/shared/js/ts'`.

5. Changed the loader from "ts" to "typescript". Returns the same thing as #3.

If jspm is meant to handle this, I'm really not sure what I'm doing wrong here and the documentation has nothing relevant to help me out. Am I just supposed to use tsc directly in my build process before running jspm bundle? If that's the case, what does the transpiler config option do, and how am I supposed to handle tsc failing to find any systemjs modules I want to bring in via import statements?

jspm version is 0.16.33 if that helps.

Thanks!
Ryan

**Comment by OrKoN** [comment]
Perhaps this would help: https://github.com/frankwallis/plugin-typescript

**Comment by aluanhaddad** [comment]
@buu700 is the meta object scoped within the package? This works fine for me.

```javascript
System.config({
  defaultJsExtensions: true,
  packages: {
    app: {
      main: "index",
      defaultExtension: "ts",
      meta: {
        "*.ts": { 
          loader: "ts" 
        }
      },
  map: {
    ts: ......
  }
})

```

**Comment by guybedford** [comment]
Yes, please use the TypeScript plugin here.
