### ISSUE TITLE
Question: Why is defaultJSExtensions stripped and how to work around this?

### ISSUE THREAD

**Issue by nicky-lenaers** [jspm/jspm-cli#1732]
``jspm 0.17.0-beta.12``:

I'm using ``karma-jspm`` for testing. On every ``jspm install``, the property in my config file called ``defaultJSExtensions`` gets removed. However, ``karma-jspm`` is not working properly without this property. There is no way for me "add it in" on the ``karma-jspm`` side.

**Example:**

I compile some TypeScript file called ``myfile.ts`` into ``myfile.js``. When running my testrunner wihout ``defaultJSExtensions`` I get errors saying it can't find the file called ``myfile``. Which is correct, since it's missing the extension. With ``defaultJSExtensions`` enabled, it does find ``myfile.js`` and everything works.

I tried other settings on the ``karma-jspm`` end, like setting ``stripExtension: false``, but that didn't help.

So this left me wondering two things: 

1. Why is it being removed? 
2. How do I work around this issue?

@guybedford Please let me know if I'm invalidly posting this issue to this repo if you think this should be resolved by ppl from ``karma-jspm``.

Thanks in advance.

**Comment by guybedford** [comment]
See the package configuration `defaultExtension` property which replaces `defaultJSExtensions`. See eg https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#packages. By default any folder defined as a package will get default js extensions.

**Comment by gingerik** [comment]
I've just strarted migrating to jspm 0.17 beta.
Am I correct to state that if a have tests in `test/` (and source in `src/`) I just need to add
```
  packages: {
    ...
    'test': {
      'format': 'esm'
    },
    ...
  }
```
to my `jsom.config.js`?
