### ISSUE TITLE
jspm 0.17 beta.13 not resolving dependency for chartjs/color-string

### ISSUE THREAD

**Issue by jithin1987** [jspm/jspm-cli#1735]
This is package.json for color-string https://github.com/chartjs/color-string/blob/master/package.json which has a single dependency color-name
```
  "dependencies": {
    "color-name": "^1.0.0"
  },

```
`color-name` does exist as an npm package https://www.npmjs.com/package/color-name  But jspm is not able to resolve it

```
newsupply-lm:simple jithine$ jspm bundle src/main.js -wid
     Building the bundle tree for src/main.js...

err  Error on fetch for color-name at file:///Users/jithine/dev/simple/color-name
  Loading github:chartjs/color-string@0.3.0/color-string.js
  Loading npm:chartjs-color@1.0.21/src/color.js
  Loading npm:chart.js@2.0.2/src/core/core.helpers.js
  Loading npm:chart.js@2.0.2/src/chart.js
  Loading npm:react-chartjs@0.7.3/lib/core.js
  Loading npm:react-chartjs@0.7.3/index.js

  Loading simple/main.js
  Error: ENOENT: no such file or directory, open '/Users/jithine/dev/simple/color-name'
    at Error (native)

```

Is it because `color-string` came from a `github` registry which has a dependency from `npm` registry ?

These are mappings from `jspm.config.js`

```
    "npm:chart.js@2.0.2": {
      "map": {
        "chartjs-color": "npm:chartjs-color@1.0.21",
        "moment": "npm:moment@2.13.0"
      }
    },
    "npm:chartjs-color@1.0.21": {
      "map": {
        "color-convert": "npm:color-convert@0.5.3",
        "color-string": "github:chartjs/color-string@0.3.0"
      }
    },
```

It does not resolve anything for `color-string`

**Comment by jithin1987** [comment]
I was able to workaround this by putting config on package.json -> jspm.overrides

```
"jspm" {
 ---
"overrides: {
 ----
      "github:chartjs/color-string@0.3.0": {
        "dependencies": {
          "color-name": "npm:color-name@~1.1.1"
        }
      }
---
```

**Comment by guybedford** [comment]
GitHub packages do not install dependencies without a registry property. There is a warning about this in the install prompts, including how to fix - `jspm instal github:charjs/color-string -o "{registry:'npm'}"` or just to install from npm in the first place.
