### ISSUE TITLE
jspm 0.17 beta.13 - Error loading babel/external-helpers with development bundling

### ISSUE THREAD

**Issue by jithin1987** [jspm/jspm-cli#1736]
I get this error only when using development bundling. I see this on browser console
```
system.js:4 Uncaught (in promise) Error: SyntaxError: Unexpected token <
	Evaluating http://localhost:3000/babel/external-helpers
	Error loading http://localhost:3000/babel/external-helpers
	Error loading http://localhost:3000/build.js
	Error loading http://localhost:3000/src/main.jst @ system.src.js:5031g @ system.src.js:5031(anonymous function) @ system.src.js:5031
```

Without development bundle I don't get this error

**Comment by guybedford** [comment]
As mentioned on Gitter, are you using the `modularRuntime: false` option here?

**Comment by jithin1987** [comment]
@guybedford I am not using `modularRuntime` setting.

**Comment by guybedford** [comment]
Can you share a replication?

**Comment by jithin1987** [comment]
I am able to replicate the issue here https://github.com/jithin1987/jspm-react-component-demo/tree/react-intl

This happens when `react-intl` is used. Should I be adding babel external helpers as a dependency ?

**Comment by JustinWilabyPrecor** [comment]
I noticed `babel-helpers` isn't requested when adding including the package in a script tag:
```js
<script src="jspm_packages/system.src.js"></script>
<script src="jspm.browser.js"></script>
<script src="jspm.config.js"></script>
<script src="build.js"></script>
<script>
    System.import('main');
</script>
```

If I remove `build.js`, `babel-helpers` is 404'd.  I hope this helps.

**Comment by jithin1987** [comment]
@JustinWilabyPrecor you are right, I don't get the error if I include `build.js`

@guybedford should that be the case? http://jspm.io/0.17-beta-guide/development-bundling.html needs update them.

**Comment by guybedford** [comment]
@jithin1987 react-intl is doing its own inclusion of the babel helpers. So to support it you may want to check if it supports an option to either disable that, or otherwise just ensure that `babel/external-helpers` exists as a map in the SystemJS configuration, set to `map: { 'babel/external-helpers': 'plugin-babel/babel-helpers' }` say.

**Comment by jithin1987** [comment]
@guybedford I added a map, but it's error outing on `babel-herlpers'

```
system.src.js:121 Uncaught (in promise) Error: SyntaxError: Unexpected token <
	Evaluating http://localhost3000/plugin-babel/babel-helpers
	Error loading http://localhost:3000/plugin-babel/babel-helpers
	Error loading http://localhost:3000/build.js
	Error loading http://localhost:3000/src/main.js
```

I do have babel-helpers

```
ithine$ ls jspm_packages/npm/systemjs-plugin-babel\@0.0.9/babel-helpers*
jspm_packages/npm/systemjs-plugin-babel@0.0.9/babel-helpers.js

jspm_packages/npm/systemjs-plugin-babel@0.0.9/babel-helpers:
asyncToGenerator.js            defaults.js                    extends.js                     instanceof.js                  jsx.js                         objectWithoutProperties.js     set.js                         taggedTemplateLiteral.js       temporalUndefined.js           typeof.js
classCallCheck.js              defineEnumerableProperties.js  get.js                         interopRequireDefault.js       newArrowCheck.js               possibleConstructorReturn.js   slicedToArray.js               taggedTemplateLiteralLoose.js  toArray.js
createClass.js                 defineProperty.js
```

**Comment by guybedford** [comment]
@jithin1987 try changing the map to `npm:systemjs-babel-plugin@0.0.9/babel-helpers.js`.

**Comment by jithin1987** [comment]
@guybedford after explicitly specifying version I no longer get that error, but app does not work. I see no console errors, but an empty page.

https://github.com/jithin1987/jspm-react-component-demo/tree/react-intl

However @JustinWilabyPrecor  suggested if I include `build.js` as a script everything works.

**Comment by jithin1987** [comment]
@guybedford could you please give your thoughts on why `build.js` script tag is required when using `react-intl` ? As I have mentioned in my previous comment without it page does not load (also no errors)
