### ISSUE TITLE
Unclear how to use babel plugins

### ISSUE THREAD

**Issue by wesleycoder** [jspm/jspm-cli#1738]
I'm trying to use [import-css-to-jss](https://github.com/websecurify/babel-plugin-import-css-to-jss) with jspm, but couldn't find how to get it working with 0.16.33.
Is this possible yet? Any other version on what it can work?
Couldn't find any doc or example on it...
Can any sample be put about this?

**Comment by guybedford** [comment]
To use custom babel plugins, it is advisable to use jspm 0.17 along with https://github.com/systemjs/plugin-babel. This is also described in the beta guide where jsx is setup - http://jspm.io/0.17-beta-guide/installing-the-jsx-babel-plugin.html.
