### ISSUE TITLE
Problem JPSM 0.17 bundling with exclusions (using CDN versions)

### ISSUE THREAD

**Issue by misscs** [jspm/jspm-cli#1739]
In `jspm.browser.js`, I have mapped waypoints to external CDN 

```
"npm:waypoints@4.0.0": "https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.0/noframework.waypoints.min.js"
```

When I try to bundle `jspm bundle .tmp/views/welcome/CredibilityPage.js - [waypoints] .tmp/assets/app-bundle.js` I get an error that it cannot find waypoint file as it keeps looking for the library version. 

How do I properly create the bundle using the CDN version of the file?

**Comment by guybedford** [comment]
Instead of using map configuration, try setting this with a paths configuration:

```javascript
System.config({
  paths: {
    'npm:waypoints@4.0.0': 'https://cdnjs.cloudflare.com/...'
  }
});
```

Note that this config will also be needed for the loader in the browser, as it won't build in this URL to the bundle file.
