### ISSUE TITLE
Jade plugin - error loading referenced text plugin

### ISSUE THREAD

**Issue by johnsoftek** [jspm/jspm-cli#1740]
The jade plugin uses the text plugin to read included jade files.

The loader does not find the text plugin even though it is referenced in jspm.config.js:
```
  packages: {
    "github:johnsoftek/plugin-jade@0.6.0": {
      "map": {
        "jade-compiler": "npm:jade@1.11.0",
        "text": "github:systemjs/plugin-text@0.0.4"
      }
    },
```

Adding the text plugin to the map section of jspm.config.js fixes the problem:
```
  map: {
   ...
     "text": "github:systemjs/plugin-text@0.0.4",
```

**Comment by SerkanSipahi** [comment]
How do you use the jade plugin?

e.g. 1.) `import foo from 'templates/foo!jade'` or 2.)`import foo from 'templates/foo!jade-compiler'`

I believe if you map it to "jade-compiler" to have to use the 2nd example (see above)

**Comment by johnsoftek** [comment]
@SerkanSipahi I am the author of the jade plugin. I am pointing out a problem that the plugin encounters when run with jspm beta 17.

**Comment by guybedford** [comment]
In https://github.com/johnsoftek/plugin-jade/blob/master/jade.js#L58 try using a contextual System.import statement:

```javascript
System.import(parent_dir + include.file_path + '!text', __moduleName)
```

The second argument scopes the import to the parent of the current module, then picking up the package-specific maps etc.

There may also be two alternatives to relying on the text plugin:

1. Use System.fetch directly  - `System.fetch(path, { metadata: {} })` I think works here.
2. Return the plugins themselves as transpiled modules that use import statements to load their dependencies, this way the dependencies are loaded through the module system without having to manually recurse the import tree.

**Comment by johnsoftek** [comment]
@guybedford Thanks for the tips. System.fetch seems ideal. I will try it out.

**Comment by johnsoftek** [comment]
@guybedford Both suggestions worked. I went with System.fetch. The syntax was actually:
```
System.fetch({ name: include.file_path, address: parent_dir + include.file_path, metadata: {} })
```

Thanks!
