### ISSUE TITLE
bootstrap 4 dependency upgrade breaks bootstrap 4 popovers

### ISSUE THREAD

**Issue by Sahasrara** [jspm/jspm-cli#1743]
My last "jspm install" yielded the following changes to my config.js.

      "jquery": "github:components/jquery@2.2.1",
      "tether": "github:HubSpot/tether@1.2.0"
to
      "jquery": "npm:jquery@2.2.3",
      "tether": "github:HubSpot/tether@1.3.1"

this breaks popovers for bootstrap 4.  Apologies if this is the wrong forum for this problems, but I don't know where else this bug should be reported.

**Comment by guybedford** [comment]
Yes, we updated the override here recently in https://github.com/jspm/registry/commit/52fcf0f0056f08592bb42babf0c81988ff180fe1.

The reasoning here is that `jspm install jquery` will install jquery from npm, so we wanted to move over the other versions of jquery in the registry to use this same reference to avoid duplicate versions of jquery.

For existing installs, this would be a problem yes, as you then need to resolve this duplication of jquery versions again.

The options here are:
1. Install bootstrap with a custom override that reverts to the previous jquery version
2. Update all other references to jquery to use the `npm:jquery` version over the `github:` version

I know it's certainly annoying and unacceptable to have a change here break your package, but this is something that was specifically designed not to happen in jspm 0.17 as overrides are always checked into the package.json. And for the existing overrides we do need to make changes from time to time. If you're worried about this in future, it may be worth running the jspm 0.17 upgrade path.

Just let me know if I can help further here at all.

**Comment by Sahasrara** [comment]
Alright, I appreciate your help.  I guess I'll wait for 0.17 to come out of beta, and for now I'll modify make custom accommodations for the bootstrap version.
