### ISSUE TITLE
jspm 0.16 throwing  “Mixed dependency cycle detected” execption

### ISSUE THREAD

**Issue by tejas-patel34** [jspm/jspm-cli#1745]
**I have JSPM based application which is throwing “Mixed dependency cycle detected” as below.**

> Uncaught (in promise) Error: Mixed dependency cycle detected  system.src.js:41                               	
> Error loading http://localhost/MixedDependencyIssue/app.js
> 

Below is app.js code snippet
```
import angular from 'angular';
import 'package1';
import 'package2';
import 'package3';
import 'package4';
import 'package5';
import 'package6’;

angular.element(document).ready(function () {
    var demoApp = angular.module('demoApp', ['ng',
        'module1',
        'module2']);

    angular.bootstrap(document.querySelector('#demo-div-id'), ['demoApp']);
});

```
**All my imported packages and JSPM application traspiled into ES5 system module using typescript transpiler using below options**.
```

declarationFiles: false,
noExternalResolve: true,
target: "es5",
module: "system",
emitDecoratorMetadata: true,
experimentalDecorators: true
```

**Comment by guybedford** [comment]
This error is thrown when you have an ES module loading a non-ES module, which in turn is loading the first ES module. That is circular references of the form A imports B imports A, where A is an ES module and B is say CommonJS.

**Comment by tejas-patel34** [comment]
Thanks for reply but all my packages which I importing in application are ES modules. Packages has inter dependency like package1 import package4 and package4 import package7 etc. but none of packages are non-ES module.

**Comment by tejas-patel34** [comment]
I verified my packages and dependencies but I am not able to find any circular references. Could you please suggest some tool or way to find circular reference (like some way to debug system.js or log information to find circular reference) which mentioned previously.

**Comment by dharmax** [comment]
same problem. 
In my case, it simply started happening on a living project, without me doing any relevant [to my understanding] change. Still investigating.

**Comment by dharmax** [comment]
Found the problem. The Typescript compiler was messing stuff. i deleted the JS and let it compile the suspicious file again and the problem is gone.

**Comment by aluanhaddad** [comment]
@dharmax interesting. That could happen if the you were compiling via 
```bash
$ tsc --watch --project tsconfig.json
```
and the `tsconfig.compilerOptions.module` property were edited or invalidated, perhaps during a checkout or an autosave. By default `tsc` emits cjs modules.

**Comment by dharmax** [comment]
Could be. i don't remember if it was with the IDE (webstorm) or not, so i can't be sure. Thanks!
