### ISSUE TITLE
Issue with double slashes causing double load of module

### ISSUE THREAD

**Issue by grofit** [jspm/jspm-cli#1746]
I have a scenario where I am using a package with mappings in my config.js to allow local files to be used as a `plugin` inside aurelia without having to host it or link it (this way it can be viewed in github with the repo).

The symptom shows itself in aurelia when I setup DI in the package, and when its consumed in the other files, the type being used as a DI key does not match. So to simplify the problem:

`import {a} from "./some-file/in-my-plugin"`

does not yield the same type as:

`import {a} from "my-plugin" // which is mapped via the package with mappings`

Which means that in scenarios like Aurelia where it will be using the type as the key for the DI, it will just fail as the types don't match, even though they are both pointing to the same thing.

There is a long winded outstanding issue on the aurelia DI which has FAR more information and working examples on C9 as well as a downloadable example to test:

https://github.com/aurelia/dependency-injection/issues/83

The Aurelia team are unsure and point towards it being a jspm/systemjs issue which would make more sense but I have already spent days of my life trying to find out what the problem was and why it was occurring, so I come to you guys in my hour of need to help me regain some sanity which I used to have before I engaged in writing aurelia plugins.

**Comment by guybedford** [comment]
Am I right in thinking that the issue is that the two values for `a` are not the same reference? Did you manually check this, by for example writing `window.a1 = a` and `window.a2 = a` in both files, and then checking the equality? Or alternatively adding a log statement in `my-plugin.js` itself on execution, and seeing if that runs twice?

If it's duplication or something else, that would at least help to narrow down further.

My knowledge of Aurelia is limited, so sorry you're having to deal with an issue on the boundary between the projects. I guess it's best to see it as a learning experience, and attempt to grasp exactly where in the Aurelia plugin process this is not doing what it is supposed to be doing.

**Comment by grofit** [comment]
If you check the link there is a c9 project which has a runnable version of the problem which has console logs, one of the other chaps did a quick test to output the log in both sections and also get an instance from both sections and compare them and the 2 didnt match.

> I just ran it in the debugger and stopped in index.js and saved an reference to the BaseClass function. Then I stopped in the plugin.js and compared them
> ```
> DEBUG [aurelia] Loading plugin aurelia-injection-issue.
> window.INDEXBASECLASS = BaseClass
> BaseClass() {
>                 _classCallCheck(this, BaseClass);
> 
>                 this.message = "base";
>             }
> VM428 index.js!transpiled:13 instance before injection ExtendedClass {message: "extended"}
> VM372 aurelia-logging-console.js:56 DEBUG [aurelia] Configured plugin aurelia-injection-issue.
> INDEXBASECLASS === BaseClass
> false
>```
> So when injecting the BaseClass in plugin.js it will find the autoRegistered when loading the file which points to a different one than in index.js
> 
> No idea why that's happening.. just wanted to share my findings..

If I had not already spent days of my life trying to track down the source of the issue and reproduce and debug etc I would be more than happy to see this as a learning experience, unfortunately I have already allocated my "learning experience" quota, hopefully in a week or so I will have some more motivation to come back and do some more on this if I can assist in any way.

As mentioned there are fully working examples which can be easily ran and the console.logs show the main bits, you can add more if needed, or there is a zipped version of the example which just need unzipping and npm/jspm install then a gulp and off you go.

**Comment by guybedford** [comment]
If there really are two executions happening, then one way of checking for duplications is to inspect the registry itself, and see if there are multiple versions of the same file in it. This can be done via - 

```javascript
Object.keys(System._loader.modules)
```

Every execution that SystemJS does corresponds to a unique module in this registry. If a module is executing twice, then it would have to appear twice in this registry (somehow, I'm not sure I know how that could even happen!).

**Comment by grofit** [comment]
Hey, so I have done as you say above and there is a huge output but the listed file is in there twice:

First instance at index 91 and then 121.

```
0: "@empty"
1:"@system-env"
2:"@@global-helpers"
3:"@@cjs-helpers"
4:"<url>/<jspm>/npm/aurelia-bootstrapper@1.0.0-beta.1.2.0.js"
5:"<url>/<jspm>/npm/aurelia-bootstrapper@1.0.0-beta.1.2.0/aurelia-bootstrapper.js"
6:"<url>/<jspm>/npm/aurelia-pal@1.0.0-beta.1.2.0.js"
7:"<url>/<jspm>/npm/aurelia-pal-browser@1.0.0-beta.1.2.0.js"
8:"<url>/<jspm>/npm/aurelia-polyfills@1.0.0-beta.1.1.1.js"
9:"<url>/<jspm>/npm/aurelia-pal@1.0.0-beta.1.2.0/aurelia-pal.js"
10:"<url>/<jspm>/npm/aurelia-pal-browser@1.0.0-beta.1.2.0/aurelia-pal-browser.js"
11:"<url>/<jspm>/npm/aurelia-polyfills@1.0.0-beta.1.1.1/aurelia-polyfills.js"
12:"text"
13:"<url>/<jspm>/npm/aurelia-loader-default@1.0.0-beta.1.2.0.js"
14:"<url>/<jspm>/npm/aurelia-loader-default@1.0.0-beta.1.2.0/aurelia-loader-default.js"
15:"<url>/<jspm>/npm/aurelia-loader@1.0.0-beta.1.2.0.js"
16:"<url>/<jspm>/npm/aurelia-metadata@1.0.0-beta.1.2.0.js"
17:"<url>/<jspm>/npm/aurelia-loader@1.0.0-beta.1.2.0/aurelia-loader.js"
18:"<url>/<jspm>/npm/aurelia-metadata@1.0.0-beta.1.2.0/aurelia-metadata.js"
19:"<url>/<jspm>/npm/aurelia-path@1.0.0-beta.1.2.0.js"
20:"<url>/<jspm>/npm/aurelia-path@1.0.0-beta.1.2.0/aurelia-path.js"
21:"template-registry-entry"
22:"<url>/<jspm>/npm/aurelia-framework@1.0.0-beta.1.2.1.js"
23:"<url>/<jspm>/npm/aurelia-framework@1.0.0-beta.1.2.1/aurelia-framework.js"
24:"<url>/<jspm>/npm/aurelia-logging@1.0.0-beta.1.2.0.js"
25:"<url>/<jspm>/npm/aurelia-dependency-injection@1.0.0-beta.1.2.0.js"
26:"<url>/<jspm>/npm/aurelia-binding@1.0.0-beta.1.3.1.js"
27:"<url>/<jspm>/npm/aurelia-templating@1.0.0-beta.1.2.1.js"
28:"<url>/<jspm>/npm/aurelia-task-queue@1.0.0-beta.1.2.0.js"
29:"<url>/<jspm>/npm/aurelia-logging@1.0.0-beta.1.2.0/aurelia-logging.js"
30:"<url>/<jspm>/npm/aurelia-dependency-injection@1.0.0-beta.1.2.0/aurelia-dependency-injection.js"
31:"<url>/<jspm>/npm/aurelia-binding@1.0.0-beta.1.3.1/aurelia-binding.js"
32:"<url>/<jspm>/npm/aurelia-templating@1.0.0-beta.1.2.1/aurelia-templating.js"
33:"<url>/<jspm>/npm/aurelia-task-queue@1.0.0-beta.1.2.0/aurelia-task-queue.js"
34:"<url>/<jspm>/npm/babel-core@5.8.38.js"
35:"<url>/<jspm>/npm/babel-core@5.8.38/browser.js"
36:"<url>/src/main.js"
37:"<url>/<jspm>/npm/aurelia-logging-console@1.0.0-beta.1.2.0.js"
38:"<url>/<jspm>/npm/aurelia-logging-console@1.0.0-beta.1.2.0/aurelia-logging-console.js"
39:"<url>/<jspm>/npm/aurelia-templating-binding@1.0.0-beta.1.2.1.js"
40:"<url>/<jspm>/npm/aurelia-templating-binding@1.0.0-beta.1.2.1/aurelia-templating-binding.js"
41:"<url>/<jspm>/npm/aurelia-templating-resources@1.0.0-beta.1.2.1.js"
42:"<url>/<jspm>/npm/aurelia-templating-resources@1.0.0-beta.1.2.1/aurelia-templating-resources.js"
43:"<url>/<jspm>/npm/aurelia-templating-resources@1.0.0-beta.1.2.1/compose.js"
44:"<url>/<jspm>/npm/aurelia-templating-resources@1.0.0-beta.1.2.1/if.js"
45:"<url>/<jspm>/npm/aurelia-templating-resources@1.0.0-beta.1.2.1/with.js"
46:"<url>/<jspm>/npm/aurelia-templating-resources@1.0.0-beta.1.2.1/repeat.js"
47:"<url>/<jspm>/npm/aurelia-templating-resources@1.0.0-beta.1.2.1/show.js"
48:"<url>/<jspm>/npm/aurelia-templating-resources@1.0.0-beta.1.2.1/hide.js"
49:"<url>/<jspm>/npm/aurelia-templating-resources@1.0.0-beta.1.2.1/sanitize-html.js"
50:"<url>/<jspm>/npm/aurelia-templating-resources@1.0.0-beta.1.2.1/replaceable.js"
51:"<url>/<jspm>/npm/aurelia-templating-resources@1.0.0-beta.1.2.1/focus.js"
52:"<url>/<jspm>/npm/aurelia-templating-resources@1.0.0-beta.1.2.1/compile-spy.js"
53:"<url>/<jspm>/npm/aurelia-templating-resources@1.0.0-beta.1.2.1/view-spy.js"
54:"<url>/<jspm>/npm/aurelia-templating-resources@1.0.0-beta.1.2.1/css-resource.js"
55:"<url>/<jspm>/npm/aurelia-templating-resources@1.0.0-beta.1.2.1/html-sanitizer.js"
56:"<url>/<jspm>/npm/aurelia-templating-resources@1.0.0-beta.1.2.1/binding-mode-behaviors.js"
57:"<url>/<jspm>/npm/aurelia-templating-resources@1.0.0-beta.1.2.1/throttle-binding-behavior.js"
58:"<url>/<jspm>/npm/aurelia-templating-resources@1.0.0-beta.1.2.1/debounce-binding-behavior.js"
59:"<url>/<jspm>/npm/aurelia-templating-resources@1.0.0-beta.1.2.1/signal-binding-behavior.js"
60:"<url>/<jspm>/npm/aurelia-templating-resources@1.0.0-beta.1.2.1/binding-signaler.js"
61:"<url>/<jspm>/npm/aurelia-templating-resources@1.0.0-beta.1.2.1/update-trigger-binding-behavior.js"
62:"<url>/<jspm>/npm/aurelia-templating-resources@1.0.0-beta.1.2.1/abstract-repeater.js"
63:"<url>/<jspm>/npm/aurelia-templating-resources@1.0.0-beta.1.2.1/repeat-strategy-locator.js"
64:"<url>/<jspm>/npm/aurelia-templating-resources@1.0.0-beta.1.2.1/html-resource-plugin.js"
65:"<url>/<jspm>/npm/aurelia-templating-resources@1.0.0-beta.1.2.1/repeat-utilities.js"
66:"<url>/<jspm>/npm/aurelia-templating-resources@1.0.0-beta.1.2.1/analyze-view-factory.js"
67:"<url>/<jspm>/npm/aurelia-templating-resources@1.0.0-beta.1.2.1/null-repeat-strategy.js"
68:"<url>/<jspm>/npm/aurelia-templating-resources@1.0.0-beta.1.2.1/array-repeat-strategy.js"
69:"<url>/<jspm>/npm/aurelia-templating-resources@1.0.0-beta.1.2.1/map-repeat-strategy.js"
70:"<url>/<jspm>/npm/aurelia-templating-resources@1.0.0-beta.1.2.1/set-repeat-strategy.js"
71:"<url>/<jspm>/npm/aurelia-templating-resources@1.0.0-beta.1.2.1/number-repeat-strategy.js"
72:"<url>/<jspm>/npm/aurelia-templating-resources@1.0.0-beta.1.2.1/dynamic-element.js"
73:"html-resource-plugin"
74:"css-resource-plugin"
75:"<url>/<jspm>/npm/aurelia-history-browser@1.0.0-beta.1.2.0.js"
76:"<url>/<jspm>/npm/aurelia-history-browser@1.0.0-beta.1.2.0/aurelia-history-browser.js"
77:"<url>/<jspm>/npm/aurelia-history@1.0.0-beta.1.2.0.js"
78:"<url>/<jspm>/npm/aurelia-history@1.0.0-beta.1.2.0/aurelia-history.js"
79:"<url>/<jspm>/npm/aurelia-templating-router@1.0.0-beta.1.2.0.js"
80:"<url>/<jspm>/npm/aurelia-templating-router@1.0.0-beta.1.2.0/aurelia-templating-router.js"
81:"<url>/<jspm>/npm/aurelia-templating-router@1.0.0-beta.1.2.0/route-loader.js"
82:"<url>/<jspm>/npm/aurelia-templating-router@1.0.0-beta.1.2.0/router-view.js"
83:"<url>/<jspm>/npm/aurelia-templating-router@1.0.0-beta.1.2.0/route-href.js"
84:"<url>/<jspm>/npm/aurelia-router@1.0.0-beta.1.2.0.js"
85:"<url>/<jspm>/npm/aurelia-router@1.0.0-beta.1.2.0/aurelia-router.js"
86:"<url>/<jspm>/npm/aurelia-route-recognizer@1.0.0-beta.1.2.0.js"
87:"<url>/<jspm>/npm/aurelia-event-aggregator@1.0.0-beta.1.2.0.js"
88:"<url>/<jspm>/npm/aurelia-event-aggregator@1.0.0-beta.1.2.0/aurelia-event-aggregator.js"
89:"<url>/<jspm>/npm/aurelia-route-recognizer@1.0.0-beta.1.2.0/aurelia-route-recognizer.js"
90:"<url>/plugin/index.js"
> HERE IS ONE 91:"<url>/plugin/classes/base-class.js"
92:"<url>/plugin/classes/extended-class.js"
93:"<url>/<jspm>/npm/babel-runtime@5.8.38/helpers/class-call-check.js"
94:"<url>/<jspm>/npm/babel-runtime@5.8.38/helpers/get.js"
95:"<url>/<jspm>/npm/babel-runtime@5.8.38/helpers/inherits.js"
96:"<url>/<jspm>/npm/babel-runtime@5.8.38/core-js/object/get-own-property-descriptor.js"
97:"<url>/<jspm>/npm/babel-runtime@5.8.38/core-js/object/create.js"
98:"<url>/<jspm>/npm/babel-runtime@5.8.38/core-js/object/set-prototype-of.js"
99:"<url>/<jspm>/npm/core-js@1.2.6/library/fn/object/get-own-property-descriptor.js"
100:"<url>/<jspm>/npm/core-js@1.2.6/library/fn/object/create.js"
101:"<url>/<jspm>/npm/core-js@1.2.6/library/fn/object/set-prototype-of.js"
102:"<url>/<jspm>/npm/core-js@1.2.6/library/modules/$.js"
103:"<url>/<jspm>/npm/core-js@1.2.6/library/modules/es6.object.get-own-property-descriptor.js"
104:"<url>/<jspm>/npm/core-js@1.2.6/library/modules/es6.object.set-prototype-of.js"
105:"<url>/<jspm>/npm/core-js@1.2.6/library/modules/$.core.js"
106:"<url>/<jspm>/npm/core-js@1.2.6/library/modules/$.to-iobject.js"
107:"<url>/<jspm>/npm/core-js@1.2.6/library/modules/$.object-sap.js"
108:"<url>/<jspm>/npm/core-js@1.2.6/library/modules/$.export.js"
109:"<url>/<jspm>/npm/core-js@1.2.6/library/modules/$.set-proto.js"
110:"<url>/<jspm>/npm/core-js@1.2.6/library/modules/$.iobject.js"
111:"<url>/<jspm>/npm/core-js@1.2.6/library/modules/$.defined.js"
112:"<url>/<jspm>/npm/core-js@1.2.6/library/modules/$.fails.js"
113:"<url>/<jspm>/npm/core-js@1.2.6/library/modules/$.global.js"
114:"<url>/<jspm>/npm/core-js@1.2.6/library/modules/$.ctx.js"
115:"<url>/<jspm>/npm/core-js@1.2.6/library/modules/$.is-object.js"
116:"<url>/<jspm>/npm/core-js@1.2.6/library/modules/$.an-object.js"
117:"<url>/<jspm>/npm/core-js@1.2.6/library/modules/$.cof.js"
118:"<url>/<jspm>/npm/core-js@1.2.6/library/modules/$.a-function.js"
119:"<url>/plugin//elements/plugin.js"
120:"<url>/<jspm>/npm/babel-runtime@5.8.38/core-js/object/keys.js"
> HERE IS ANOTHER 121:"<url>/plugin//classes/base-class.js"
122:"<url>/<jspm>/npm/core-js@1.2.6/library/fn/object/keys.js"
123:"<url>/<jspm>/npm/core-js@1.2.6/library/modules/es6.object.keys.js"
124:"<url>/<jspm>/npm/core-js@1.2.6/library/modules/$.to-object.js"
125:"<url>/plugin//elements/plugin.html!text"
126:"<url>/plugin//elements/plugin.html!template-registry-entry"
127:"<url>/src/app.js"
128:"<url>/src/app.html!text"
129:"<url>/src/app.html!template-registry-entry"
```

**Comment by guybedford** [comment]
@grofit right that is exactly the issue then that an extra `/` is appearing in `<url>/plugin//classes/base-class.js"` causing the duplicate execution.

To debug this further I would suggest adding something like the following to SystemJS, immediately after the SystemJS script tag is loaded:

```javascript
var systemNormalize = System.normalize;
System.normalize = function(name, parentName) {
  return systemNormalize.apply(this, arguments)
  .then(function(normalized) {
    if (normalized.endsWith('//classes/base-class.js')
      throw new Error('Duplicate plugin normalization caused by normalizing ' + name + ' to ' + parentName + ');
    return normalized;
  });
};
```

That should then show the stack that is causing the invalid normalization, pointing to where in your own code or Aurelia it is originating from.

**Comment by grofit** [comment]
Just to raise the question then, should system js do anything to normalize paths with double/mixed slashes? I only ask as I know sometimes when doing string concats you may not know if the config has a trailing slash or not, and some people on windows will use `\` slashes instead of `/`. In most cases these urls when put into a browser are automatically normalized and handled so it has never really been much of a worry.

I dont know if it currently does anything to deal with casing (i.e it automatically lower cases everything etc), but anyway should this be raised up as a possible bug to fix or is it just seen as a developer problem?

**Comment by guybedford** [comment]
@grofit we use the rules of `new URL('./a', 'https://site.com/parent/url.js')` for normalization, which doesn't do double slash removal. I think being consistent with the URL spec makes sense, but really it depends on how exactly this arises in the first place (what the arguments are to the URL function above, as provided by the debugging hint in my previous comment), and then in future, how module loaders deal with these cases... SystemJS isn't in a position to make assumptions here really.

**Comment by grofit** [comment]
thats fine, well I will leave it to you if you want to close it or not, as my config which causes this is:

```js
paths: {
    ...
    "your-plugin-name": "./your-plugin-folder/"
  },
  packages: {
    "your-plugin-name": {
      "main": "index.js",
      "map": {
        "*": "**/*"
      }
    }
  },
```

I have tried removing the trailing slash from the package but then it wont resolve the files within the plugin directory.

**Comment by guybedford** [comment]
Try using map rather -

```javascript
map: {
  'your-plugin-name' : './your-plugin-folder'
}
```

Note also `*: '**/*'` is not a valid map value in packages.

**Comment by grofit** [comment]
oh right thats good to know, I needed that bit to tell all child calls from the plugin that they needed to be relative to that route (without that bit it wouldnt resolve something like `./elements/custom-element` from the `index` in the `plugins` folder).

**Comment by grofit** [comment]
Just to confirm, are you implying I should be using the paths and packages as above but the `map` part of it should be as you say? or are you indicating that I should not be using `packages` or `path` entries as shown and should replace all of it with an entry in the `map` like you show above?

As if its the latter it doesn't work, it just says:

```
GET http://localhost:63342/<project-name>/dist/commonjs.js 404 Not Found
```

When the map looks like:

```
map: {
   // ... other mappings
   "project-name": "../dist/commonjs",
}
```

With trailing slashes yields same result, just it has a slash before the empty `.js` its trying to include.

**Comment by guybedford** [comment]
@grofit I mean using map instead of the paths config like:

```javascript
map: {
    "your-plugin-name": "./your-plugin-folder"
  },
  packages: {
    "your-plugin-name": {
      "main": "index.js",
    }
  },
```

**Comment by grofit** [comment]
Thank you so much, this appears to work and loads the correct DI instances (so it resolves to the same file). I have spent WEEKS trying to find a nice way to host local files which have dependencies and no one was able to provide an answer (in JSPM gitter or aurelia discussions). So I know you are a very busy man, but you have made my development with aurelia and JSPM far more productive with your quick solution. Thanks again!

**Comment by guybedford** [comment]
Sure great to hear that. Will definitely note this for documentation improvements then.
