### ISSUE TITLE
json files are loaded although it was bundled

### ISSUE THREAD

**Issue by SerkanSipahi** [jspm/jspm-cli#1747]
@guybedford the configuration file is included before the bundle file. All of the configured dependencies are not loaded via XHR but the json files will still be loaded even though they are configured as well e.g.
bundle file:

```
SystemJS.config({
  packageConfigPaths: [
    "npm:@*/*.json",
    "npm:*.json",
    "github:*/*.json"
  ],
  map: {
    ...
    "document-register-element": "npm:document-register-element@0.3.0",
  },
...
}

"bundle";System.registerDynamic("npm:document-register-element@0.3.0.json",[],!1,function(){return{main:"build/document-register-element.js",format:"cjs",meta:{"*.json":{format:"json"}}}}),System.registerDynamic("npm:document-register-element@0.3.0/build/document-register-element.js",[],!0,function(a,b, ....
````

For clarification: The json file has been bundled but is beeing loaded at runtime even though a mapping has been provided.

both code snippets are included in one file, see our gulp concat order:

```
    bundle: [
        'jspm_packages/system-polyfills.src.js',
        'jspm_packages/system.src.js',
        'jspm.browser.js',
        'jspm.config.js',
        'bundle.js'
    ],
```

we have a reproducible example:

```
git clone https://github.com/SerkanSipahi/testcase-jspm-bundle.git
cd testcase-jspm-bundle
npm install
node_modules/.bin/jspm bundle src

```

if you serve index.html in the browser you will see the loaded json files in the networkpanel

Whats going wrong? Is this a bug?

**Comment by guybedford** [comment]
@SerkanSipahi the reason for this is that `defaultJSExtensions` is not supported in jspm 0.17 at all, as it is being deprecated. Rather use the package configuration defaultExtension property.

**Comment by SerkanSipahi** [comment]
@guybedford after removing "defaultJSExtensions" and "setting package configuration" it is work as expected (json files are no longer loaded) :)
