### ISSUE TITLE
After bundle JQuery doesn't load before angular 

### ISSUE THREAD

**Issue by marthinus-engelbrecht** [jspm/jspm-cli#1748]
Hi, 

In my `config.js` i have the meta tag set like below: 

```JSON
  "angular": {
      "deps": [
        "jquery"
      ]
    },
```

I installed jquery using `jspm install jquery -o "{format: 'global'}" `

Everything works great, but when I run `jspm bundle app.js build.js` then jquery loads after angular. JQuery does eventually load though because it's available in the console. 

I'm using jspm '0.16.33'

**Comment by guybedford** [comment]
The way to check if the meta configuration has worked is to read `Object.keys(System.meta)` and check that the `angular` meta value has been correctly normalized into the full path to Angular.

**Comment by marthinus-engelbrecht** [comment]
Thanks. When I run `Object.keys(System.meta)` against the bundled code it gives me nothing. When I run it against the code before it's bundled it gives a bunch of paths for the meta tags. Any ideas why it would not cary it over into the bundle?

**Comment by marthinus-engelbrecht** [comment]
I literally just run `jspm bundle app.js build.js`

**Comment by guybedford** [comment]
I mean check it in the unbundled version to check if the meta relation is setup correctly there.

**Comment by marthinus-engelbrecht** [comment]
Ok, yeah `angular` is there in the unbundled and it's pointing pointing to the correct location. `http://127.0.0.1:9091/jspm_packages/npm/angular@1.5.5.js`

**Comment by guybedford** [comment]
Try altering the meta to `angular/lib/angular.js`, or whatever the main entry point is for angular.

**Comment by marthinus-engelbrecht** [comment]
Thanks. That did the trick. But I'm curious to why?

**Comment by guybedford** [comment]
The main entry point pointer module is a different module, which can be short-circuited by a direct dependency on angular's direct main. This problem goes away in jspm 0.17 as we've deprecated main entry point pointer modules for being replaced with a package configuration request.

**Comment by marthinus-engelbrecht** [comment]
Cool. Thanks for the help. Looking forward to 0.17 release and rollup.
