### ISSUE TITLE
Injecting bundles don't work if site root is subfolder

### ISSUE THREAD

**Issue by lukechilds** [jspm/jspm-cli#1749]
Running `jspm bundle src/main bundle.js --inject` successfully creates a bundle and injects it into my `config.js` file. This all works fine locally but when I push live it breaks because my live site is served from a subfolder and `bundle.js` get's loaded from the root and 404s.

Manually changing `config.js` from something like this:

```js
bundles: {
  "bundle.js": [
    "foo",
    "bar"
  ]
}
```
to this:

```js
bundles: {
  "./bundle.js": [
    "foo",
    "bar"
  ]
}
```

Fixes the issue.

**Comment by guybedford** [comment]
The way to handle this case is to set the baseURL in config.js. The bundle name is worked out relative to the baseURL by jspm, and if it is another folder, set it in the package.json directories.baseURL to ensure it is worked out correctly.

**Comment by lukechilds** [comment]
But then won't it be wrong locally?

Is there a way you can specify the directory relative to the `system.js` location so it would work in both environments?

**Comment by guybedford** [comment]
The baseURL is designed to be this shared reference path between client and server that can form an absolute reference point.

**Comment by lukechilds** [comment]
Sorry, I'm not sure I understand, my baseUrl is `"/"` and `system.js` correctly finds my jspm packages both locally and on GitHub Pages. Why doesn't it check the same root for the bundle?

What's the correct way to make this work?

**Comment by lukechilds** [comment]
For anyone else who stumbles across this issue, the solution was to remove `baseURL: "/"` from `config.js`. It appears that baseURL then defaults to the `config.js` directory if it's not explicitly set, meaning the bundle will be loaded correctly weather the app is served from the root or a subfolder.
