### ISSUE TITLE
Error: Multiple anonymous defines.

### ISSUE THREAD

**Issue by yyaari** [jspm/jspm-cli#1751]
Hi,
I'm trying to import a 3rd party file to use in my app. when bundling i get (partial error stack):
`Error: Multiple anonymous defines.
    at ParseTreeTransformer.AMDDependenciesTransformer.transformCallExpression (c:\yy_ws\b2b\DX-cloud\main\subsystem\b2b-gw\frontend\ui\app\node_modules\jspm\node_modules\systemjs-builder\compilers\amd.js:98:13)
    at CallExpression.args.transform (c:\yy_ws\b2b\DX-cloud\main\subsystem\b2b-gw\frontend\ui\app\node_modules\jspm\node_modules\systemjs-builder\node_modules\traceur\bin\traceur.js:6649:28)`

I'm using babel to transpile, however the file i'm importing is not written in es6.
any ideas what is the cause for this?

Thanks!

**Comment by guybedford** [comment]
This will happen for a file that contains two statements of the form `define([], function() {})`.

**Comment by yyaari** [comment]
Thanks for your quick reply.
does this means that i cannot import it using jspm and must add it as a script tag?

Thanks again

**Comment by guybedford** [comment]
If the file really does contain two statements like that, then it wouldn't load as a script tag either. Perhaps check if it uses a umd pattern and can be set to load through another format.

**Comment by guybedford** [comment]
If you need more help here just let me know.

**Comment by yyaari** [comment]
Thanks. 
Actually i dont have much (if any)  knowledge about this subject.  The file is loaded fine with a script tag and i wouldn't know where or what to start looking. 
Your help is much appreciated!
