### ISSUE TITLE
When installing module B within module A it results in a GET with a non-flat path to B's dependencies.

### ISSUE THREAD

**Issue by marthinus-engelbrecht** [jspm/jspm-cli#1752]
Hi @guybedford, 

I'm not sure whether this should be posted here or on [plugin-scss](https://github.com/mobilexag/plugin-sass). I will post it there as well.

I have two modules **A** and **B**, **B** has a dependency on material-design-lite's scss, among other scss files and **A** has a dependency on **B**. I import it in my `index.js` via a `style.scss` file. See below. 

*index.js*
```javascript 
import './style.scss!';
```

*style.scss*
```scss
@import "../jspm_packages/npm/material-design-lite@1.1.3/src/material-design-lite.scss";
@import "../jspm_packages/othermodule@1.1.1/file.scss";
```

When I install **B**  in **A** and try to run **A** I get the following: 

```
system.js:4 Uncaught (in promise) Error: Error: Invalid CSS after "<": expected 1 selector or at-rule, was "<!DOCTYPE html>"
	        on line 1 of jspm_packages/npm/B@0.0.2/jspm_packages/npm/material-design-lite@1.1.3/src/material-design-lite.scss
	>> <!DOCTYPE html>
	   ^
	
	Error loading http://127.0.0.1:9091/jspm_packages/npm/Bt@0.0.2/source/style.…!http://127.0.0.1:9091/jspm_packages/github/mobilexag/plugin-sass@0.4.2.js as "./style.scss!" from http://127.0.0.1:9091/jspm_packages/npm/sbg-email-input@0.0.2/source/index.js
```

See how the `jspm_packages` folder is nested in the path twice. That's not how it's on my machine and as far as my understanding of jspm goes it should never look like that. 

I'm not doing any bundling. 

**P.S**: Don't let the `Invalid CSS` part confuse you. I'm using html5 routing, so I'm always serving the `index.html` when a file can't be found (...should most probable make that more fine grained :unamused:).

**Comment by guybedford** [comment]
This sounds like an issue with that plugin. I'd suggest seeking support there.

**Comment by marthinus-engelbrecht** [comment]
Cool. Once again. Thanks for taking the time to give feedback. Know you must be busy. I already raised it with them. When I get a chance I will see if I can maybe fix it myself.

**Comment by guybedford** [comment]
Sure, appreciated for understanding! Yes it is important to draw lines of responsibility at some point to retain some sanity :)

**Comment by marthinus-engelbrecht** [comment]
This ended up being my issue. I thought that I couldn't use the `jspm:` syntax with npm dependencies but it turns out you can. So the import should be: 
```scss
@import "jspm:material-design-lite/src/material-design-lite.scss";
```
