### ISSUE TITLE
Transpile without bundling

### ISSUE THREAD

**Issue by JayantaP** [jspm/jspm-cli#1753]
Hi @guybedford,

I'm doing an application in typescript. I want to transpile the code but without any bundling. The use case is to provide a dev build, which can be run on a dev server, still having separate js files for debugging. Is there a way to do it using jspm/systemjs builder?

Regards,
Jay

**Comment by bgoscinski** [comment]
I don't think there is currently such functionality available but maybe you could do something like
```js
var builder = new (require('jspm').Builder);
builder
  .trace('src/app')
  .then((tree) => {
    return Promise.all(Object.keys(tree).map((key) => {
      var path = tree[key].path;
      return path
        ? builder.buildStatic(`[${path}]`, `dist/${path}`, {format: 'cjs'})
        : null
    }))
  })
```

**Comment by JayantaP** [comment]
Thank you very much for the response.
I'm getting a "module is undefined" error when I try this. I
included system-csp-production.js and System.import() but with no luck.

Regards,
Jay

**Comment by bgoscinski** [comment]
I deleted my response because I realised that it's not going to work like that. Sorry for confusion :(

**Comment by guybedford** [comment]
You can use the `builder.compile` method here, which supports single module compilation to a precompiled output that can then be loaded by SystemJS directly with the `scriptLoad: true` metadata set.

**Comment by JayantaP** [comment]
@guybedford this works if I don't have a plugin.
I'm using a text plugin and the plugin files are not compiled/copied to the destination.

**Comment by giusepperj** [comment]
@guybedford I'm experiencing the same issue when incorporating the text plugin into my `jspm bundle myproject/src/app.js -wid` the bundle works but any import reference paths `import template from "./template.html!text"` do not get compiled on the dev bundle. Is this a separate open issue?

**Comment by guybedford** [comment]
@JayantaP do you mean you're doing `builder.compile('file.html!text')` for example? Are you getting an incorrect output?

@giusepperj this definitely works fine for me. Perhaps if you're using TypeScript that would explain the incompatibility of the syntax. Note also that plugins by loader metadata (`meta: { '*.html': { loader: 'text' } })`) is advised over syntax these days.

**Comment by giusepperj** [comment]
@guybedford adding the metadata to jspm.config.js is what worked for me thank you.
