### ISSUE TITLE
Cross-origin error using bundled jade-plugin

### ISSUE THREAD

**Issue by johnsoftek** [jspm/jspm-cli#1756]
The Jade plugin loads the jade runtime like so:
```javascript
      let fn = 'var jade = require' + '("' + runtime_loc + '");\n\n' +
        'module.exports = ' + Jade.compileCient(text)
      return fn
```
and runtime_loc is set by:
``` javascript
System.normalize('jade-compiler/lib/runtime.js', __moduleName)
```
giving `file:///.../jspm_packages/npm/jade@1.11.0/lib/runtime.js`

With jspm@0.16.33, the build file references the Jade runtime using a logical path:
``` javascript
System.registerDynamic("d1/test.jade!jade.js", ["npm:jade@1.11.0/lib/runtime"], true, function($__require, exports, module) {
```

With jspm@0.17.x, although the runtime is bundled:
```javascript
System.registerDynamic("npm:jade@1.11.0/lib/runtime.js",
```
the build file references the Jade runtime using a file system path:
```javascript
System.registerDynamic("d1/test.jade", ["file:///.../jspm_packages/npm/jade@1.11.0/lib/runtime.js"], true, function($__require, exports, module) {
```
resulting in a browser error:
>system.src.js:5031 XMLHttpRequest cannot load file:///.../jspm_packages/npm/jade@1.11.0/lib/runtime.js. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.

**Comment by guybedford** [comment]
This is an important difference in jspm 0.17 - bundles are unlinked, so we don't do any canonicalization automatically.

Try adding the following:

```javascript
if (this.builder)
  runtime_loc = this.getCanonicalName(runtime_loc);
```

**Comment by johnsoftek** [comment]
@guybedford Genius, as usual. Thanks.
