### ISSUE TITLE
How to use 'paths' section from within 'packages' section of config.js

### ISSUE THREAD

**Issue by press-on-regardless** [jspm/jspm-cli#1757]
Hi,

My app is trying to load a JSPM package "pkg1" from a remote URL. From app's config.js::

map {
  "pkg1": "http://some-url/pkg1"
}, 
packages: {
  "http://some-url/pkg1": {
    "main": "dist/index",
    "map": {
      "bootstrap": "http://some-url//jspm_packages/github/twbs/bootstrap@3.3.6"
    }
}, 
paths: {
  "github:*": "jspm_packages/github/*",
  "npm:*": "jspm_packages/npm/*"
}

System.import('pkg1') fails because it doesn't find bootstrap.

bootstrap@3.3.6.js has one line, module.exports = require("github:twbs/bootstrap@3.3.6/js/bootstrap")

I was expecting github: to resolve to http://some-url//jspm_packages/github, but it doesn't, and looks for bootstrap in app's jspm_packages. 

I also tried specifying a paths property inside packages to point to the remote location, but that didn't work either.
packages: {
  paths: {
    "github:*": "http://some-url/jspm_packages/github/*",
    "npm:*": "http://some-url/jspm_packages/npm/*"
  }
}

Any help will be appreciated..

**Comment by guybedford** [comment]
I assume this is jspm 0.16 you are running?

Note to be careful with things like `http://some-url//jspm_packages/github/twbs/bootstrap@3.3.6` as the double slash (`-some-url//`) will alter the naming. That shouldn't be the issue here though.

If `defaultJSExtensions` is set in the config file, then `System.normalize('bootstrap', 'http://some-url/pkg1/dist/index.js').then(console.log.bind(console))` should certainly return `jspm_packages/github/twbs/bootstrap@3.3.6.js`. Or did you say the issue is that it tries to load `github:twbs/bootstrap@3.3.6/js/bootstrap` incorrectly?

**Comment by press-on-regardless** [comment]
Hi Guy,

Thanks for replying. Yes, I am using jspm 0.16 and the issue is that bootstrap is not loading correctly.

Bootstrap is present only in http://some-url website. I expected that since I am pointing packages paths property to http://some-url, require("github:twbs/bootstrap@3.3.6/js/bootstrap") should resolve to  require("http://some-url/jspm_packages/githubtwbs/bootstrap@3.3.6/js/bootstrap") rather than  require("http://localhost/jspm_packages/githubtwbs/bootstrap@3.3.6/js/bootstrap").

**Comment by guybedford** [comment]
I see, it sounds like changing the paths is exactly the right thing to do here. Perhaps that change is just not applying properly somehow? To test this try inspecting `System.paths` or running `System.normalizeSync('github:asdf')` to ensure that it is going to the right place.

**Comment by press-on-regardless** [comment]
Hi Guy,

This is my flow:
1. App has a config.js. This config.js doesn't have pkg1 (There was no jspm install pkg1 done at the app)
2. App has a button
3. User clicks button, handler calls System.config API to update packages and map (first post in this thread) so that System.import('pk1') works.

The only way I could get it to work was:
oldPaths = System.paths;
System.config(...)
System.paths = <update github: and npm: in paths to point to http://some-url>
System.import(pkg1)
System.paths = oldPaths

This is not ideal because I need to dynamically load multiple of these remote packages in the app. 

While packages gives a nice way of managing dependencies of remote components, I was hoping I could specify a packages specific paths so that github: and npm: of remote dependencies resolve to whatever I specify in individual packages.

**Comment by guybedford** [comment]
@press-on-regardless changing paths locations between packages is not supported.

**Comment by press-on-regardless** [comment]
Hi Guy, 

Would you have any recommendation on how I can solve for the above scenario?

**Comment by guybedford** [comment]
I'd suggest using package map configuration to set say `github-a:bootstrap` for the one server and `github-b:bootstrap` for the other server.

**Comment by press-on-regardless** [comment]
Hi Guy, 

How do I do that? I am already using the package map configuration - 

Config.js in server-1 has a packages section which looks like this:

```
packages: {

    "http://server-2/pkg1/": {

      "main": "dist/index", 

      "map": {
        "bootstrap": "http://server-3/jspm_packages/github/twbs/bootstrap@3.3.6"
      }

}
```
and map: 
```

map: {
  "pkg1": "http://server-2/pkg1/"
}

```

System.import("pkg1") in server-1 downloads pkg1 from server-2, but is not able to resolve 'github:' in server-3's bootstrap

**Comment by guybedford** [comment]
@press-on-regardless something like:

```javascript
paths: {
  'server-a:': 'http://server-a.com/',
  'server-b:': 'http://server-b.com/'
},
packages: {
    "server-a:pkg1": {

      "main": "dist/index", 

      "map": {
        "bootstrap": "server-b:bootstrap"
      }

}
```

let me know if that makes sense.

**Comment by press-on-regardless** [comment]
Hi Guy, I tried it, but it doesn't work. Same issue as before, which is, "github" in server-b/bootstrap's  require("github:twbs/bootstrap@3.3.6/js/bootstrap") is not resolving correctly. Systemjs is looking for http://APP_URL/jspm_packages/github/twbs/bootstrap@3.3.6/js/bootstrap.js instead of http://server-b/jspm_packages/github/twbs/bootstrap@3.3.6/js/bootstrap.js

**Comment by guybedford** [comment]
@press-on-regardless if you have an explicit require to `require('github:twbs/bootstrap')` then you would need to map that name itself - `packages: { 'pkgname': { map: { 'github:twbs/bootstrap@3.3.6': 'custom/bootstrap/path' } } }`.

**Comment by press-on-regardless** [comment]
Ok, that worked! But I had to put the entry in System.map, not System.packages.pkgname.map. Is that a problem?
