### ISSUE TITLE
Move the injected "bundles" property outside of jspm.browser.js

### ISSUE THREAD

**Issue by Palid** [jspm/jspm-cli#1758]
Please move the injected properties outside of the `jspm.browser.js`. Our team is overriding the file all the time in such a way that automerging is really hard due to usage of `jspm bundle -wid`. We have recently switched to injecting from builder, but that doesn't change a thing to the huge array. 
IMHO The simplest fix would be to provide a flag for both builder and CI that would allow to give destination/path to the object with only `bundles` property. This would allow to just have the file in .gitignore and forget about stupid merges.

**Comment by ineentho** [comment]
I've not used the inject option just because of this. Temporary development configuration shouldn't be source controlled, but the jspm configs has to be. The same things is true of the dependency tree injection if used in development.

**Comment by guybedford** [comment]
It's a tricky thing, because we will quickly end up with 5 different config files if we're not careful.

If you don't like having injection into `jspm.browser.js`, then perhaps do a custom build with `require('jspm').Builder` and then do your own custom injection. Most production apps should really be running the builder manually for the best integration.

**Comment by guybedford** [comment]
This is how injection is done through the builder API - https://github.com/jspm/jspm-cli/blob/master/lib/bundle.js#L80.

**Comment by Palid** [comment]
@guybedford Overriding method 'Bundle' doesn't sound like a reasonable fix. Monkey patching a library to make it not annoying in development environment is not really a good idea, especially if we would like to use bleeding-edge release (as right now we're using beta). 
The other thing is about having 'five different configs' - why should we even care, if that's a file that could be safely gitignored? 
I don't even understand why do we have jspm.browser.js and jspm.config.js separately now, as there aren't a lot of additional data in jspm browser config. Moving two few things back to jspm.config.js and having jspm.temporary.js would resolve this issue. That's just one way of fixing this problem. ;)

**Comment by oligot** [comment]
Another alternative that we use quite often is to skip the injection part (no `--inject`option in the command line) by doing
 > jspm bundle app.js dev-bundle.js --watch --development

and then include the `dev-bundle.js` file in your `index.html` just after `jspm.config.js`

```
<!docype html>
<meta charset="utf-8">
<script src="jspm_packages/system.js"></script>
<script src="jspm.browser.js"></script>
<script src="jspm.config.js"></script>
<script src="dev-bundle.js"></script>
<body>
  <div id="container"></div>
  <script>
    SystemJS.import('test.js');
  </script>
```

This does the same thing as the `--inject` option, except it doesn't change the `jspm.browser.js` file

**Comment by Palid** [comment]
@oligot This does sound like the only reasonable resolution for the moment. But I'm not sure how will it work with the chokidar-socket-emitter and livereloading.

**Comment by guybedford** [comment]
@Palid I'm not suggesting overriding any hooks, but simply writing a custom build script looking like:

```javascript
var Builder = require('jspm').Builder;
var builder = new Builder();

builder.build('app/main.js').then(function(output) {
  var customProductionConfig = { bundles: {} };
  customProductionConfig.bundles['my-custom-bundle'] = output.modules;
  injectIntoProduction(customProductionConfig);
});
```

**Comment by guybedford** [comment]
I certainly agree that this isn't a great experience right now, but I don't think this is something we can solve right now.
