### ISSUE TITLE
Consider supporting `deps` for all module formats

### ISSUE THREAD

**Issue by trusktr** [jspm/jspm-cli#176]
As we discovered with Famo.us, libraries that have files that are not global (i.e. AMD or CJS modules) might also need meta info.

For the time being, I'm just running the following after installing Famo.us with jspm, to add the `"deps ...";` strings, and to fix the famous-polyfills `require()` lines:

``` javascript
#!/usr/bin/env node

var walker = require('at-at');
var fs = require('fs');

process.chdir('./party/jspm/github/');
walker.walk('./', function(files) {
    // files is an array of filenames (including the paths).
    files.forEach(function(fileName, index, array) {

        // match the folder name for famous
        if (fileName.match(/famous@.*/)) {

            // match any javascript file except the entrypoint file of the same name as the folder.
            if (!fileName.match(/famous@[\.0-9a-zA-Z]*\.js/) && fileName.match(/\.js$/) ) {

                var fileContent = fs.readFileSync(fileName).toString();

                if ( fileContent.indexOf('"deps') === -1 ) {
                    console.log('Adding meta info for', fileName);
                    fileContent = fileContent.split("\n");
                    var filePosition = 0;
                    fileContent.splice(filePosition++, 0, '"deps ../core/famous.css!";');
                    fileContent.splice(filePosition++, 0, '"deps famous-polyfills";');
                    fs.writeFileSync(fileName, fileContent.join("\n"));
                }
            }
        }
    });
});
```

**Comment by trusktr** [comment]
@guybedford What was the conclusion for this issue? Were you tracking it somewhere else? Or did you just decide it's not needed? This is what has been keeping me from finishing my the jspm workflow. +1 for [postinstall scripts](https://github.com/jspm/jspm-cli/pull/372).

**Comment by trusktr** [comment]
This is my famous fork's package.json (the important parts):

```js
{
  "name": "famous",
  "jspm": {
    "registry":"jspm",
    "directories": {
      "lib": "src"
    },
    "dependencies": {
      "css": "^0.1.0"
    },
    "shim": {
      "./*/*": {
        "deps": ["../core/famous.css!"]
      }
    }
  }
}
```

**Comment by guybedford** [comment]
@trusktr yes this is supported in SystemJS. So `shim` is what causes `"deps ../core/famous.css!"` to be written into the source files. As mentioned before, I think this is not happening because double-wildcard shim isn't supported I don't believe.

**Comment by trusktr** [comment]
As per #382, this still isn't working without wildcards. Can we re-open this issue?

**Comment by trusktr** [comment]
My goodness! I found the solution so that I can finally post the jspm workflow.

```js
"registry":"jspm"
```

in my project's package.json, and now I can load the famous.css file at least in my project, but not automatically using famous' override, but at least now things work. 

It doesn't seems practical that it is automatically set for npm endpoint packages, but not for other endpoints. This has been such a headache, going in circles trying to get things working.

I put a note in the registry wiki suggesting to just always put the registry property in package.json.

My project isn't meant to be installed by anyone. I don't see a reason why (other than if I don't it doesn't work) I should need to put that property in my project. It should just work. It's not intuitive IMHO.

Can you provide a good example where you actually don't want the registry property?

**Comment by guybedford** [comment]
Nice, glad you found it! There's an open issue to enable this at https://github.com/jspm/jspm-cli/issues/360. I'm aiming to get into the code again today with some luck.

**Comment by trusktr** [comment]
OK, so apparently that wasn't the problem. I removed the `registry` property, reinstalled everything, and now it just works. I've no idea why it works, when before it didn't. :(

**Comment by trusktr** [comment]
@guybedford shims are currently supported for non-globals right?

**Comment by trusktr** [comment]
They seem to work, just not with any wildcards (maybe I'm just doing it wrong). Not even a simple `*` works.

**Comment by guybedford** [comment]
@trusktr I'm more than happy to look into things like this. If you would like to see features like this improved, it would help a lot if you can report issues:

* With a new issue for a specific actionable item.
* Include enough detail (say an example) to understand exactly.
* Don't include any more detail than necessary.

It is really great to have feedback, and with a little care in terms of issue management it can be put to a lot of use.

**Comment by trusktr** [comment]
I'll keep that in mind for next time. I'm about to pass out.
