### ISSUE TITLE
Allow use of selfExecutingBundle excluding libraries from bundle with arithmetic

### ISSUE THREAD

**Issue by kmturley** [jspm/jspm-cli#1761]
If I run the gulp-jspm arithmetic demo:
https://github.com/brillout/gulp-jspm/blob/master/demo/gulpfile.js#L43

It runs fine using the code:

    gulp_jspm({arithmetic:'- message'})

But it fails if I use the params:

    gulp_jspm({arithmetic:'- message',selfExecutingBundle: true})

The error is:

    SFX Bundle input error

To start with, it's not really clear what the error is. However the bigger issue is, how can you create a self executing bundle, but exclude a library or js module?

In my case I'm wanting to use system js for my dev environment importing one js file:

    <script>
        System.import('{% static "web/components/all" %}');
    </script>

Then within all.js import angular and my other modules

    import angular from 'angular';
    import Comments from './comments/comments';

Then when creating the production build, exclude angular so I can use the CDN version

**Comment by guybedford** [comment]
This has been supported for sfx bundles for some time. See for example http://jspm.io/0.17-beta-guide/static-builds-with-rollup-optimization.html in jspm 0.17. Perhaps take this up with gulp-jspm rather.

**Comment by kmturley** [comment]
Great thanks, I have opened an issue with the gulp-jspm author!

**Comment by brillout** [comment]
@kmturley you have to specify a module loader, i.e. AMD or CommonJS or global. That makes sense since JSPM has to know how to load the module you are excluding.

@guybedford why handle `ui.log('err', ` as an event and not an exception? It would be more convenient for a JSPM API consumer to treat errors as exceptions and not as events. I can make a PR

**Comment by guybedford** [comment]
@brillout thanks the logging action itself is just logging, but in all places used, `ui.log('err')` should also throw. Anywhere where it doesn't a PR is welcome to ensure consistency.
