### ISSUE TITLE
jspm.Builder memory leaking as hell (0.17.0-beta.13)

### ISSUE THREAD

**Issue by Palid** [jspm/jspm-cli#1762]
Hey, 
I'm using `const builder = jspm.Builder(); builder.bundle()` with chokidar-socket-emitter due to it being only way to catch errors and show system notifications. Unfortunately, when you run `builder.bundle` a few times the memory spikes unbelievably high. I didn't notice this behavior with command `jspm bundle src/app.js build/app.js -wid`, it does however exist with plain Builder. Tried to trace the memory leak with Node Inspector, but that didn't give me any serious data.

If needed, I can attach the code I'm using. I even tried doing build() in timeouts just to be sure - it does exist even then.

PS. Neither one instance of builder nor creating additional instance on each build does fix the problem.

**Comment by guybedford** [comment]
Moved to https://github.com/systemjs/builder/issues/571.
