### ISSUE TITLE
Bundle tries to transpile `.html` files.

### ISSUE THREAD

**Issue by Zoltu** [jspm/jspm-cli#1767]
```js
SystemJS.config({
  transpiler: "plugin-typescript",
  format: "esm",
  packages: {
    "source": {
      defaultExtension: "ts",
      meta: {
        "*.ts": {
          loader: "plugin-typescript"
        }
      }
    }
  }
  baseURL: "/",
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  }
});
```

Folder structure:
```
source/
	app.html
	app.ts
```

Bundle command:
```
jspm bundle source/**/*
```

Result:
```
$ jspm bundle source/**/*
     Building the bundle tree for source/**/*...

err  MultipleErrors: Error compiling global module "source/app.html" at source\app.html
  source/app.html:1:1: Unexpected token <
source/app.html:1:2: Semi-colon expected
source/app.html:2:2: Unexpected token <
source/app.html:2:3: Semi-colon expected
source/app.html:2:7: Semi-colon expected
source/app.html:2:16: Unexpected token <
source/app.html:3:1: Unexpected token <
source/app.html:4:1: Unexpected end of input
```

**Comment by Zoltu** [comment]
The `meta` section only lists `*.ts` files to use the TypeScript loader yet it appears that the `TypeScript` loader is being used for all file types.

**Comment by jonricaurte** [comment]
@Zoltu you need to:

jspm bundle source/app.ts

**Comment by Zoltu** [comment]
`app.html` is not a dependency of `app.ts`.  Aurelia (SPA framework) links them together but JSPM isn't smart enough (unsurprisingly, its complicated) to figure that out.

**Comment by guybedford** [comment]
In order to bundle html files, jspm needs to know how to load them. By default all files are loaded as modules. In order to load html, some plugin would need to be used like a template plugin loader or text plugin loader, although I'm not sure what plugin or method Aurelia uses to load html template files.

**Comment by StrahilKazlachev** [comment]
It uses the text plugin for html and css.

**Comment by guybedford** [comment]
Right, then it sounds like this should be `jspm bundle source/**/*.ts + source/**/*.html!text`. It may be worth just using Aurelia bundler though which as far as I'm aware was designed to cater to these kinds of bundling problems.

**Comment by Zoltu** [comment]
Sadly, the Aurelia bundler doesn't work with JSPM 0.17.  :/

I didn't know I could add `!text` to a bundle glob.  I'll give that a try.  Thanks!

**Comment by Zoltu** [comment]
`jspm bundle source/**/*.ts + source/**/*.html!text` resolved my issue and allowed me to bundle HTML files in a way that Aurelia can leverage.  Thanks!
