### ISSUE TITLE
jspm 0.17 beta invalid JSON file for sfx/build

### ISSUE THREAD

**Issue by jonricaurte** [jspm/jspm-cli#1770]
When using bundle, I do not get an error:

jspm bundle h2 public/h2_assets/build.js --skip-source-maps

When building an sfx bundle using the following command:

jspm build h2 public/h2_assets/build.js --skip-source-maps

I get the following error:

h2_app.js:4 Potentially unhandled rejection [4] Error: Invalid JSON file https://www.somedomain.dev/jspm_packages/npm/systemjs-plugin-babel@0.0.9.json
Error loading https://www.somedomain.dev/jspm_packages/npm/systemjs-plugin-babel@0.0.9.json

**Comment by guybedford** [comment]
@jonricaurte that wouldn't be possible as a jspm build doesn't have any loader to give a message like that. That error would only happen when using System.import which is a completely separate loading process to jspm build.

**Comment by jonricaurte** [comment]
@guybedford thanks for the response. So the jspm.config.js is how sfx builds know where to start loading from initially so we do not need a System.import to import the first file? Thanks.

**Comment by guybedford** [comment]
SFX builds will just execute immediately when the script tag is included in the page.

**Comment by jonricaurte** [comment]
@guybedford thanks. Is there a way to detect if the current bundle on the page is an sfx or normal bundle? In my Node.js server jade template I have:

```
script(type='text/javascript').
      SystemJS.import('h2').then(function() {
        angular.bootstrap(document, ['h2App']);
      });
```
It would be nice to have something like this:

```
script(type='text/javascript').
      if (SystemJS.isSfxBundle) {
        SystemJS.import('h2').then(function() {
          angular.bootstrap(document, ['h2App']);
        });
    } else {
        angular.bootstrap(document, ['h2App']);
    }
```
So then I don't have to have a gulp task modify the server jade files.

Thanks.

**Comment by guybedford** [comment]
An SFX bundle is just a module like any other module, so there's no detection process.

**Comment by jonricaurte** [comment]
Running the jspm should be able to set a flag on window so the client knows. Right now you would have to use gulp to strip out the System.import. Is it possible for JSPM to set a flag like the one above when its building?

**Comment by jonricaurte** [comment]
@guybedford is it possible to reopen? Maybe also include something in the README here saying you have to remove SystemJS.import:

https://github.com/jspm/jspm-cli/blob/master/docs/production-workflows.md#user-content-creating-a-self-executing-bundle

**Comment by guybedford** [comment]
@jonricaurte in jspm 0.17 this will be clarified as we call it simply `jspm build x` over `jspm bundle`. The documentation update will be coming with the 0.17 release hopefully fairly soon now. A build is not a bundle, and you can have many of them in the same page. It is just an optimized compaction of many modules into one, treating the combined module as a single global build, just like jQuery.js itself is a single build.

**Comment by jonricaurte** [comment]
@guybedford thanks for the clarification. I think I can get around this by having the below code added in the build process and not on the index page:

```
SystemJS.import('h2').then(function() {
        angular.bootstrap(document, ['h2App']);
      });
```

This way during production deploys I just won't include the SystemJS.import.
