### ISSUE TITLE
Comment and code conflicts

### ISSUE THREAD

**Issue by ahmedshuhel** [jspm/jspm-cli#1771]
This line is conflicting with the above comment: https://github.com/jspm/jspm-cli/blob/0.17/lib/config/index.js#L60

**Comment by guybedford** [comment]
Is this related to a specific issue. I was thinking that bundles may make some sense in Node as fs access is much faster for a single file over many, so it would be a Node optimization that could be useful.

**Comment by ahmedshuhel** [comment]
No, not related to a specific issue. the comment says `// no depCache or bundles` but only `delete cfg.bundles` is commented out. 

It's deleting bundle injection from the config object, right? I thought reason for `deleting` is that it would create duplicate(it not gets deleted as it is now) bundles in the `config` file when the config gets saved after a `jspm bundle -i` command. Is there `fs` involved [here?](https://github.com/jspm/jspm-cli/blob/0.17/lib/config/index.js#L60)

**Comment by guybedford** [comment]
This is just the configuration that gets used when running in NodeJS itself. This doesn't change the configuration file itself, which is handled through the config file classes.

**Comment by ahmedshuhel** [comment]
Closing this. Let me know if you want me to do a PR fixing the comment. Thanks.
