### ISSUE TITLE
Update packages to latest

### ISSUE THREAD

**Issue by aTable** [jspm/jspm-cli#1773]
I've looked around for an answer but I couldn't find a (lazy) blind get latest option like `jspm update --force-latest` 

As [defined in the docs](https://github.com/jspm/jspm-cli/blob/master/docs/installing-packages.md#versioning) there are some handy versioning rules which jspm will adhere to when updating packages. However, it would be handy during dev to have this brute force option to ignore versioning constraints as installing packages like so `jspm install npm:react` results in `"react": "npm:react@15.0.2"` a hardcoded version. Which is fine until you find yourself having 20+ packages. 

Has jspm already solved this or could this be just a bad idea?

**Comment by adamburgess** [comment]
I think #471 is tracking this, some people have made packages that seem to follow the same path as [npm-check-updates](https://www.npmjs.com/package/npm-check-updates)

**Comment by guybedford** [comment]
This would be `jspm upgrade` over `jspm update`, which is tracking at https://github.com/jspm/jspm-cli/issues/706.
