### ISSUE TITLE
Module ./definitions/init not declared as a dependency of jspm_packages/npm/babel-types@6.8.1/lib/index.js

### ISSUE THREAD

**Issue by micaelmbagira** [jspm/jspm-cli#1774]
Since last update of babel (or babel-types), I get this error when running a React app with jspm:
> Error: Error: Module ./definitions/init not declared as a dependency of http://localhost:3002/jspm_packages/npm/babel-types@6.8.1/lib/index.js
	    at Object.eval (http://localhost:3002/jspm_packages/npm/babel-types@6.8.1/lib/index.js:329:25)
	    at eval (http://localhost:3002/jspm_packages/npm/babel-types@6.8.1/lib/index.js:864:4)
	    at eval (http://localhost:3002/jspm_packages/npm/babel-types@6.8.1/lib/index.js:865:3)
	Evaluating http://localhost:3002/jspm_packages/npm/babel-types@6.8.1/lib/index.js
	Evaluating http://localhost:3002/jspm_packages/npm/babel-helper-builder-react-jsx@6.8.0/lib/index.js
	Error loading http://localhost:3002/jspm_packages/npm/babel-preset-react@6.5.0/index.js
	Error loading http://localhost:3002/src/index.js

**Comment by Vanuan** [comment]
Same here

**Comment by benbender** [comment]
Version 6.7.7 of babel-types is the last-working version. But it's a bit stressful to get it work.

**Comment by micaelmbagira** [comment]
And I don't even know how to make it work with 6.7.7 because other Babel plugins have babel-types 6.8.0 as peer dependency.

**Comment by benbender** [comment]
Here is what I did as a workaround to make it work:
1. jspm install npm:babel-types@6.7.7
2. you will have package-definitions for babel-types@6.8.1 and babel-types@6.7.7 in jspm.config.js -> remove the one for babel-types@6.8.1
3. replace every occurance of babel-types@6.8.1 with babel-types@6.7.7

**Comment by guybedford** [comment]
Which version of jspm is this happening with, and for what top-level install and run?

**Comment by Vanuan** [comment]
npm install -g jspm@beta
and

     jspm install --dev npm:babel-plugin-transform-react-jsx core-js

**Comment by micaelmbagira** [comment]
This is happening with last beta version.
Here is a replication project https://github.com/FountainJS/jspm-replication-1774

**Comment by mtiitson** [comment]
It seems that SystemJS fails to recognise the dependencies whose require call is immediately preceded by a comment as is the case in babel-types. 
`/*istanbul ignore next*/require("./definitions/init");`

**Comment by micaelmbagira** [comment]
Removing it or moving it after `require` didn't work.

**Comment by guybedford** [comment]
Ok this was a require extraction bug in SystemJS, fixed in https://github.com/systemjs/systemjs/commit/6fb3344b638ad4e7e92adfff5ef45fbda70408cc.

Until the next SystemJS release, the workaround would be the override:

override.json
{
  "meta": {
    "lib/index.js": {
      "deps": ["./definitions/init.js"],
      "cjsDeferDepsExecute": true
    },
    "lib/definitions/init.js": {
      "deps": ["./index", "./core", "./es2015", "./flow", "./jsx", "./misc", "./experimental"],
      "cjsDeferDepsExecute": true
    }
  }
}
```

```
jspm install npm:babel-types@6.8.1 -o override.json
```

after installing `npm:babel-plugin-transform-react-jsx`.

**Comment by micaelmbagira** [comment]
After applying the workaround, I have one other similar error
> Module core-js/shim not declared as a dependency of http://localhost:3002/jspm_packages/npm/babel-polyfill@6.8.0/lib/index.js
	    at Object.eval (http://localhost:3002/jspm_packages/npm/babel-polyfill@6.8.0/lib/index.js:3:25)
	    at eval (http://localhost:3002/jspm_packages/npm/babel-polyfill@6.8.0/lib/index.js:33:4)
	    at eval (http://localhost:3002/jspm_packages/npm/babel-polyfill@6.8.0/lib/index.js:34:3)

Is it related ?

**Comment by micaelmbagira** [comment]
@guybedford any update about this one or ETA about the release because this is a blocking issue ?Cannot rollback babel version because of peer deps and as said above, the workaround is not working.

**Comment by cengage-stan** [comment]
@guybedford, do we have an ETA on the release of systemjs that will fix this issue?

**Comment by guybedford** [comment]
The next SystemJS update release should be this week hopefully.

**Comment by alexisvincent** [comment]
@guybedford I still that the same issue after following your fix. Any advice?

**Comment by guybedford** [comment]
@alexisvincent this should definitely work with the latest SystemJS version.

**Comment by alexisvincent** [comment]
Should this work without the fix above or with it?

**Comment by guybedford** [comment]
Yes without the fix being necessary.

**Comment by alexisvincent** [comment]
Thanks. Working now, issue was incorrect wildcard mapping. Interesting that it resulted in the same error as above.
