### ISSUE TITLE
Question: how to install an esm version of lib from npm to get use of Rollup?

### ISSUE THREAD

**Issue by RomanGotsiy** [jspm/jspm-cli#1777]
I've installed `@angular/core` lib via jspm:
```jspm install npm:@angular/core```

It has `jsnext:main` in it's [`package.json`](https://github.com/angular/angular/blob/master/modules/%40angular/core/package.json#L6).

Then I'm building static bundle using [systemjs/builder](https://github.com/systemjs/builder). But resulting bundle uses `cjs` version of the lib so it doesn't get use of rollup tree-shaking.

Is there any way to install a module from `npm` but use `esm` version in the builder?

I'm using `jspm@0.16.34` and `systemjs-builder@0.15.16`

**Comment by amenadiel** [comment]
You can do a format override such as

```sh
jspm install npm:angular/core -o '{"format":"esm"}'
```

Anyway, tree shaking doesn't always work. For example, I've failed tree shaking lodash, and while jQuery is tree-shakeable, some parts are broken if you override it to be ESM.

**Comment by RomanGotsiy** [comment]
@amenadiel, format override doesn't work; when I override format systemjs-builder treats angular `cjs` code as `esm` and I get `Uncaught ReferenceError: require is not defined`
I need to take advantage of [`jsnext:main`](https://github.com/rollup/rollup#can-i-distribute-my-package-as-an-es6-module) key in package json.
Maybe jspm doesn't support it.

**Comment by sod** [comment]
This worked for me:

```
jspm install npm:@angular/core -o '{"main":"esm/index.js"}';
jspm install npm:@angular/common -o '{"main":"esm/index.js"}';
jspm install npm:@angular/compiler -o '{"main":"esm/index.js"}';
jspm install npm:@angular/http -o '{"main":"esm/index.js"}';
jspm install npm:@angular/platform-browser -o '{"main":"esm/index.js"}';
jspm install npm:@angular/platform-browser-dynamic -o '{"main":"esm/index.js"}';
jspm install npm:@angular/router -o '{"main":"esm/index.js"}';
```

There also is a esm version of rxjs under npm:rxjs-es. But rxjs already doesn't throw a hole lot of unimported context at you so it is efficient out of the box without the need to rollup.

**Comment by RomanGotsiy** [comment]
@sod thanks. Yes, that worked for me (it used es6 sources but unfortunately not reached code seems not to be removed by Rollup, ut that's the separate story).

The one thing I had also to override `format` to `esm`.

But from my point of view this it is kind of hack. It would be useful if jspm or system-js (i'm not sure on which level it should be done) builder supported `jsnext:main` property.

**Comment by sod** [comment]
There happens a lot in these `*-builds` repositories like https://github.com/angular/core-builds - There are now rollupped bundles and `jsnext:main` is present in the package.json. So maybe just be patient until rc.2 or rc.3 :)
