### ISSUE TITLE
Ability to configure the .jspm directory location (other than ~/.jspm)

### ISSUE THREAD

**Issue by ilbmiller** [jspm/jspm-cli#1783]
Hi,
  Within my company, we run automated builds using the user 'build' account, and the build user directory (~build) is nfs mounted (shared) across all machines.   

   This can lead to ~/.jspm/** file lock collisions between independent builds, as .jspm is stored under the nfs-mounted ~build directory.  We are getting errors of the ilk:
```
   warn Error on getOverride for jspm:github
     Error: Command failed: /bin/sh -c git fetch --all && git reset --hard origin/master
     fatal: Unable to create '/u/build/.jspm/jspm-cache/.git/index.lock': File exists.
```
Note that while the collision is currently between builds running on different machines but sharing the same (nfs) user directory (~build/.jspm), I believe the problem could also arise from multiple parallel builds on the same machine (even without nfs mounted directories) as they would also collide on ~/.jspm.

Is there a way to specify the location of the .jspm directory to be anything other than ~/.jspm?  I'd like to be able to configure a specific .jspm location per build to avoid collisions.  Failing that, is there a way to customize the jspm-cache location?

I searched stackoverflow and the jspm doc, but didn't find anything.

Thanks,
Brad

**Comment by guybedford** [comment]
Yes unfortunately while it would be good to share the same cache across machines in theory, as it allows reduced network load, we don't currently properly handle shared use of this folder in full.

This folder is set as `process.env.LOCALAPPDATA || process.env.HOME || process.env.HOMEPATH`. So you could try running jspm with the `LOCALAPPDATA` environment variable set to a custom folder here.

Perhaps we could add a better name for the override here if this environment variable approach makes the most sense.

**Comment by guybedford** [comment]
Moving to https://github.com/jspm/jspm-cli/issues/1831.
