### ISSUE TITLE
Transpiler sourcemaps

### ISSUE THREAD

**Issue by babakness** [jspm/jspm-cli#1785]
The Babel transpiler is working out of the box, which is great. Yet I'm not sure how to see the original file when I follow the error stack. I see files with "!transpiled" tacked on the end. Do we need to explicitly turn on source-maps? If so, how is this done, I couldn't find instructions in the docs. Thanks.

**Comment by guybedford** [comment]
Is this in jspm 0.16 or jspm 0.17? You should be getting full source maps back to the original sources in Chrome at least.
