### ISSUE TITLE
Hot loading and exceptions not re-loading after update.

### ISSUE THREAD

**Issue by babakness** [jspm/jspm-cli#1786]
I've taken a peak at the up-coming version of jspm in beta and see that hot code loading is on its way. I followed instructions to set this up for the current version. 

One thing I've noticed is that when one of the files has an error, I get an error like

```... reimport failed because this error was thrown: ...```

Yet the exception continues even after the fix. Perhaps the transpiled version stays cached somewhere and doesn't get re-transpiled before being re-imported? Any suggestions would be great.

**Comment by guybedford** [comment]
I'd advise posting issues to the hot reloader itself for hot reloading problems.
