### ISSUE TITLE
Error trying to install bpmn-js

### ISSUE THREAD

**Issue by calbertts** [jspm/jspm-cli#1787]
Hi guys,

I've been trying to install the library bpmn-js with JSPM but I'm getting this error:

`err  Error locating github:Nikku/Snap.svg/archive/v0.3.0-browserify.tar.gz.`

But it works if I use `npm install bpmn-js`

How can I deal with this?

Thanks

**Comment by guybedford** [comment]
Yes this does seem to be a jspm 0.16 bug, although it works fine for me in jspm 0.17. Perhaps try upgrading if you can?

**Comment by calbertts** [comment]
It worked with 0.17.0-beta.14 although I'll need to fix some parts of my project because this new version has a different structure, is there a good documentation to migrate?

**Comment by guybedford** [comment]
Let me know if you still need any upgrade help here.

**Comment by Casturan** [comment]
We had this issue as well, and upgrading to jspm 0.17 isn't an option (yet). We have tested it with 0.17 though, which works.

We came up with a dirty 'hack' to get it working with jspm 0.16, as we only need it temporarily: simply install all depencencies of bpmn-js and diagram-js manually, and override the dependencies of bpmn-js and diagram-js:

    jspm install snapsvg=github:nikku/Snap.svg@0.3.0-browserify
    jspm install didi=npm:didi@0.1.0
    jspm install eve=npm:eve@0.4.2
    jspm install hammerjs=npm:hammerjs@2.0.1
    jspm install inherits=npm:inherits@2.0.1
    jspm install lodash=npm:lodash@3.0.1
    jspm install min-dom=npm:min-dom@0.2.0
    jspm install object-refs=npm:object-refs@0.1.1
    jspm install npm:diagram-js@0.17.0 -o '{"dependencies":{}}'
    jspm install bpmn-moddle=npm:bpmn-moddle@0.12.2
    jspm install diagram-js-direct-editing=npm:diagram-js-direct-editing@0.17.0
    jspm install diagram-js-origin=npm:diagram-js-origin@0.14.1
    jspm install ids=npm:ids@0.2.0
    jspm install npm:bpmn-js -o '{dependencies: {}}'

Please note, that this list of dependencies is for version 0.17.1 of bpmn-js and version 0.17.0 of diagram-js.
