### ISSUE TITLE
Plugin that uses a bundle

### ISSUE THREAD

**Issue by krasimir** [jspm/jspm-cli#1788]
Hello,

I'm trying to integrate [cssx](https://github.com/krasimir/cssx) with jspm and I created the following plugin:

```js
var cssxTranspiler = require('cssx-transpiler');

exports.translate = function (load) {
  return cssxTranspiler(load.source);
};
```
I do resolve properly `cssx-transpiler` with

```js
"npm:cssx-transpiler@5.0.0": {
  "buffer": "github:jspm/nodelibs-buffer@0.1.0",
  "process": "github:jspm/nodelibs-process@0.1.2"
}
```
The problem is that `cssx-transpiler` is distributed as a bundle produced by browserify. Here is the file that is run by jspm https://raw.githubusercontent.com/krasimir/cssx/master/packages/cssx-transpiler/lib/cssx-transpiler.js

And I have bunch of `requires` inside that bundle which make sense in the context of the bundle :) because it's browserify specific requires. What I have to do to make the `cssx-transpiler` working.

**Comment by amenadiel** [comment]
What error are you getting?

**Comment by krasimir** [comment]
![image](https://cloud.githubusercontent.com/assets/528677/15077139/bdcdbfae-13b5-11e6-9831-a2cc091d6a76.png)

It's because I have `require('../../tokenizer/types')` in my bundle. The module `types.js` is inside but it is resolved by using browserify.

**Comment by amenadiel** [comment]
Looking at your bundle, it seems that `tokenizer/types`is required as `./tokenizer/types`, ../tokenizer/types` and ../../tokenizer/types`.It's also declared as  `./tokenizer/type.jss`, ../tokenizer/types.js` and ../../tokenizer/types.js`.

One way around it it's to define a mapping: 

```js
packages: {
  cssx:
    {
    "../../tokenizer": "./tokenizer",
    "../tokenizer": "./tokenizer"
    }
}
```

But your mileage might vary. The core problem is that "require" is reserved-ish in node, but it can be redeclared/shadowed. SystemJS does that, and when it does, it will look for module paths and mappings in its register.

**Comment by krasimir** [comment]
I see. Is there any way to exclude specific file from SystemJS require resolving?

**Comment by krasimir** [comment]
I [ended](https://github.com/krasimir/cssx/tree/master/playground/jspm) up by adding `cssx-transpiler.js` bundle in the project and don't use it as a dependency. That skips the SystemJS `require` resolving.

**Comment by amenadiel** [comment]
I'm doing the same on my less.js plugin and a couple of weeks ago they merged a similar modification I did for plugin-css. In the end, adding the transpiler to version control in the form of a single file is a more sane practice.
