### ISSUE TITLE
jspm Broken @import declaration of

### ISSUE THREAD

**Issue by born2net** [jspm/jspm-cli#1791]
upd from 0.16 to 0.17 and not getting the following error:

![err](https://cloud.githubusercontent.com/assets/5090936/15080451/0f43074c-1373-11e6-816c-05757e885eb7.PNG)

using
"clean-css": "npm:clean-css@3.4.12",

and

```
"src": {
      "main": "App",
      "defaultExtension": "ts",
      "meta": {
        "*.js": {
          "loader": "ts"
        },
        "*.ts": {
          "loader": "ts"
        },
        "*.css": {
          "loader": "css"
        }
      }
```

and my imports are:

```
import 'twbs/bootstrap/dist/css/bootstrap.css';
or
import 'twbs/bootstrap/dist/css/bootstrap.css!';
```

any help is appreciated

regards

Sean

**Comment by born2net** [comment]
closing

**Comment by amenadiel** [comment]
please tell us how did you solved it. Did you update to a newer plugin-css version?

**Comment by born2net** [comment]
I ended up just reinstalling the entire jspm directory and it fixed it,  odd I know.
