### ISSUE TITLE
0.17 - `jspm build` with dependency subtraction causes "Module exports cannot be changed externally."

### ISSUE THREAD

**Issue by joeldenning** [jspm/jspm-cli#1793]
I don't understand the intricacies of this problem fully, but here's my best shot at explaining it. If you have a project called foo that is built with something like `jspm build foo - bar foo.bundle.js`, and bar is another project that is built with `jspm build bar bar.bundle.js`, there is a race condition at runtime. That race condition sometimes causes the `foo` project's `bar` dependency to be injected while it is a `Module` object, and sometimes not. If bar is injected as a `Module`, then the error "Module exports cannot be changed externally" [will be thrown](https://github.com/ModuleLoader/es6-module-loader/blob/6c324164db8cdbaf1713c26b43bf867044a48ac1/src/loader.js#L764). The cause seems to be related to the `Module` object for `bar` having a `default` property on it, but when it comes in not as a Module object it does not have a `default` property. The reason why the `default` property is problematic is that the [getESModule function inside of systemjs/builder](https://github.com/systemjs/builder/blob/master/templates/sfx-core.js#L290-L311) will first [set the "default" property with the same setter that throws the exception](https://github.com/systemjs/builder/blob/master/templates/sfx-core.js#L321-L322), but then will [try to set `default` again afterwards](https://github.com/systemjs/builder/blob/master/templates/sfx-core.js#L306) (which triggers the setter which throws the error).

Hopefully that makes sense. A couple more things that hopefully clarify the situation I'm running into:
1) I call it a race condition because it seems that the order/timing of the various ajax requests might be part of it. However, I'm not totally sure if that's true or not -- I will try to continue to figuring this to try to confirm this.
2) [`this._loader.modules`](https://github.com/systemjs/systemjs/blob/master/dist/system.src.js#L857) seems to contain `Module` objects for a while, but at some point during the lifecycle of the module it seems to be removed from `this._loader.modules`?? And that seems to determine whether the module is injected as a `Module` or not. This is the part where I don't understand really what's going on, and would appreciate an explanation.

I'm willing to help out in fixing the issue, but need a bit of help understanding everything in order to do so.

**Comment by guybedford** [comment]
The switching between a Module and a non-Module is very strange.

What I also don't understand here is why there is any assignment to `bar` when it is a dependency. Dependency objects are not mutated anywhere.

What loader are you using to load `foo` and `bar`? Is this error entirely constricted to the sfx-core implementation of `foo` itself? Can you share a replication or `foo.js` and `bar.js` that give this error?

Any help tracking this down further would be great.

**Comment by joeldenning** [comment]
1) I'm using SystemJS as the loader for all of this, and systemjs/builder's static builds for all of this.

2) You're right that dependency objects aren't mutated, but the esModule object [*is* mutated](https://github.com/systemjs/builder/blob/693390b72f0a1189b1e227d22b0ba63a01f7625b/templates/sfx-core.js#L307) and it inherits all the getters/setters from the original object (since the sfx-core template [copies the entire property descriptor](https://github.com/systemjs/builder/blob/693390b72f0a1189b1e227d22b0ba63a01f7625b/templates/sfx-core.js#L317-318) over to the `esModule` object). It is the [setter on Module objects](https://github.com/ModuleLoader/es6-module-loader/blob/6c324164db8cdbaf1713c26b43bf867044a48ac1/src/loader.js#L764) that throws an error whenever you try to change it, and that setter is getting put onto the `default` property of the `Module` object that is being injected as a dependency.

3) You asked for an example -- here are the two files that cause the problem. The first is [contact-menu](https://cdn2.canopytax.com/sofe/contact-menu/commence-sofe-49-g52268da/contact-menu.js), which was made with a static build done by jspm@0.17. The second is [toast-service](https://cdn.canopytax.com/sofe/toast-service/v0.7.3-33-g4385ed4/toast-service.js) which was made by an sfx build done by jspm@0.16. Contact-menu depends on toast-service, and contact-menu is the one that throws the error because it tries to do `esModule['default'] = exports` even though `esModule` already has a `default` property on it (whose setter will throw the error when you try to change it).

4) I still don't know enough to know where the problem really is and which code should be responsible for fixing it. I know that adding the `__esModule` property to `Module`s fixes it because then static builds don't think that `Module`s are commonjs modules. But as we discussed in the es6-module-loader pr, that's not the place to fix it. Do you think that it's the responsibility of `getESModule` to be smart enough to handle `Module` objects? Or do you think that the [`__esModule` check](https://github.com/systemjs/builder/blob/master/templates/sfx-core.js#L283-L286) should be enhanced to detect `Module` objects and not call `getESModule` on something that is already a `Module`?

I appreciate your help with this.

**Comment by guybedford** [comment]
@joeldenning ahhh thanks so much for clarifying. Can you test if the following change helps:

Replacing https://github.com/systemjs/builder/blob/693390b72f0a1189b1e227d22b0ba63a01f7625b/templates/sfx-core.js#L307:

```javascript
esModule['default'] = exports;
```

with:

```javascript
defineProperty(esModule, 'default', { value: exports, enumerable: true });
```
?

**Comment by guybedford** [comment]
Or actually just even adding `if (p == 'default') continue` to the loops at https://github.com/systemjs/builder/blob/693390b72f0a1189b1e227d22b0ba63a01f7625b/templates/sfx-core.js#L295 and https://github.com/systemjs/builder/blob/693390b72f0a1189b1e227d22b0ba63a01f7625b/templates/sfx-core.js#L301.

**Comment by joeldenning** [comment]
The first solution you suggested didn't work because the `default` property was not configurable, but the second solution worked great. I created systemjs/builder#595 to fix it, thanks for your help with this!
