### ISSUE TITLE
Roadmap request

### ISSUE THREAD

**Issue by frederikschubert** [jspm/jspm-cli#1794]
Hi, first of all thank you for all the work you do with jspm @guybedford ! :)
I wondered if you have a roadmap for jspm, especially regarding a release of the 0.17 version?

**Comment by Vanuan** [comment]
https://github.com/jspm/project/blob/master/ROADMAP.md

**Comment by frederikschubert** [comment]
Ah I did not see that. :) Thanks!

**Comment by guybedford** [comment]
@frederikschubert the next beta release of jspm 0.17 can be considered the release candidate... the official release is purely pending documentation updates.

**Comment by frederikschubert** [comment]
Great! Looking forward to it! :)
