### ISSUE TITLE
Empty source maps for linked packages in JSPM 0.17.0-beta.14

### ISSUE THREAD

**Issue by domagojk** [jspm/jspm-cli#1795]
As of version 0.17.0-beta.14, when executing `jspm build src dest --skip-rollup` my source maps for linked packages are not mapped.
It seems that configuration for local repositories (npm path is mapped correctly) from jspm.browser.js is not applied correctly

```
SystemJS.config({
  baseURL: "/",
  paths: {
    "github:*": "jspm_packages/github/*",
    "local:*": "jspm_packages/local/*",
    "npm:*": "jspm_packages/npm/*",
  }
});
```
If I change local:_PATH_ with "jspm_packages/local..." inside my .map file it works fine.

**Comment by guybedford** [comment]
Can you share more details about how exactly the `local` path is not working here, or a replication? You shouldn't be getting `local:...` showing up in your source map at all, so knowing how that is being generated would help.

**Comment by domagojk** [comment]
@guybedford 
I had created sample application for replicating it

```
git clone https://github.com/domagojk/jspm-test2.git
cd jspm-test2
npm install
jspm link plugin-codemirror-beautify=codemirror-beautify
jspm install
jspm build test.js builded.js --skip-rollup
```

then, in builded.js there should be "local:" line

**Comment by guybedford** [comment]
@domagojk thanks, I just tested it and funnily enough this is already fixed on SystemJS builder master for the coming release!

**Comment by domagojk** [comment]
Great then! :)

**Comment by guybedford** [comment]
Released in jspm 0.17.0-beta.15.

**Comment by domagojk** [comment]
@guybedford 
I had now tested this with new release, but now I get different bug with source maps

You can reproduce it in the same way as in original post, and you should see "index.js" in the project root as empty file but the real path is in "local/codemirror-beautify/web/index.js"

![screen shot 2016-05-25 at 19 48 25](https://cloud.githubusercontent.com/assets/1868852/15550424/ab63aad0-22b1-11e6-8261-4bfd95d4ccc8.png)

**Comment by guybedford** [comment]
Thanks, that seems like a Babel bug actually - fixed in https://github.com/systemjs/builder/commit/e6bd7c51c3ad45eacedf11e514334796f65b452f.
