### ISSUE TITLE
error information in browser

### ISSUE THREAD

**Issue by jonex2** [jspm/jspm-cli#1798]
jspm version .16 and .17 beta
It's hard to debug my app because i don't get a useful error infomation in the browser console (thrown by system.js)

**Comment by guybedford** [comment]
Make sure you click the `...` in the error message in Chrome. See the screenshots
![screen shot 2016-05-16 at 01 36 31](https://cloud.githubusercontent.com/assets/598730/15277498/b3eacd1c-1b06-11e6-9a7c-806e738dda48.png)
![screen shot 2016-05-16 at 01 36 38](https://cloud.githubusercontent.com/assets/598730/15277499/b4a602e4-1b06-11e6-8f4a-99b72a24f33a.png)

 as an example.

**Comment by jonex2** [comment]
Thank you! That was it!

In this context:
Doing your getting-started project and causing an error in bootrap.js, the error points me to the transpiled file, like
Error: bootstrap@http://localhost:8000/lib/bootstrap.js!transpiled:10:5

Is there a way to point to the original, untranspiled file?
