### ISSUE TITLE
Is "setmode remote" supported anymore ?

### ISSUE THREAD

**Issue by minhcao** [jspm/jspm-cli#1800]
I have been using JSPM **version 0.16.34** and everything seems to be well-functional.

The other day I noticed when doing "jspm --help"  that JSPM has a command "jspm setmode remote" and I really like the idea to put assets to cloud servers for production. Nonetheless, i have 2 confusions: 

- Command "jspm setmode local" works well for me. However, when i changed to "remote" mode then I noticed the order of dependencies getting loaded in browser is messed up. For example: JQuery is loaded after Angular and some other Jquery-dependent packages get missing JQuery.... I used **meta** tag to define **deps** for each module and it worked fine in "local" mode. 

```
  meta: {
    "angular": {
      "deps": [
        "jquery"
      ]
    }
  }
```

- Another thing i notice is that everything in cloud seems to be minified and is formatted ( added format: "cjs" or something ) which i'm not sure if it'll be unreadable for browser.

JSPM docs now doesn't mention this "setmode" command but it was included in version 0.8.0 and some previous versions, hence i'm not sure if this is deprecated or not. If it is then please tell me how to make **setmode remote** works just like **setmode local**.

**Comment by guybedford** [comment]
This was an early feature of the project to have a seamless remote switch for installed packages, but hasn't been prioritised recently and so does have bugs since it hasn't been kept up-to-date with all the latest changes. The goal is to update this to work to parity against jspm 0.17, but that will take a few months unfortunately.

**Comment by guybedford** [comment]
This will be updated in due course.
