### ISSUE TITLE
"Uncaught ReferenceError: System is not defined" with static builds

### ISSUE THREAD

**Issue by jithin1987** [jspm/jspm-cli#1802]
I am on JSPM v0.17 latest beta. I have a line `System.register` in the static build which is causing the error

From the minified file via `jspm build src/main public/js/build-min.js --minify;`
```
    a.register("14a", [], function() {
        return {
            setters: [],
            execute: function() {}
        }
    }),
    System.register("1", ["3", "51", "52", "61", "62", "63", "64", "65", "66", "67", "68", "69", "89", "97", "98", "148", "149", "9f", "3e", "6a", "6b", "8a", "6c", "9e", "a4", "a0", "a1", "a2", "a3", "a5", "a6", "14a"], function(a, b) {
        function c(a, b) {

````

If I manually replace `System.register` with `a.register` then the static build works. I am not able to create a test repo for this because of https://github.com/jspm/jspm-cli/issues/1774

However on following stack trace I believe it's caused by `react-chartjs`. So I tried removing `react-chartjs`, but got same error on `react-select`. Could be that these packages use commonjs modules.

This seems to be similar to an old issue https://github.com/jspm/jspm-cli/issues/1032

**Comment by guybedford** [comment]
Is there anyway you can provide a reduced test case? Or at least share the process of how module "1" was transpiled?

**Comment by jithin1987** [comment]
Module 1 is the `main` module (starting point of my app) in this command `jspm build src/main public/js/build.js;`

**Comment by guybedford** [comment]
What I mean is what transpiler and configuration are you using for it? Is that module written in ES6?

**Comment by jithin1987** [comment]
Yes, it is es6, and I am using babel. 
```
SystemJS.config({
  transpiler: "plugin-babel",
  packages: {
    "iaas-dashboard": {
      "format": "esm",
      "main": "main.js",
      "meta": {
        "*.js": {
          "loader": "babel",
          "babelOptions": {
            "plugins": [
              "babel-plugin-transform-react-jsx",
              "babel-plugin-transform-class-properties"
            ]
          }
        }
      }
    }
  }
});
```

But I believe there could be some downstream modules which are not es6. One module I suspect is `react-chartjs` while it itself is es6 its dependency could be commonjs.

**Comment by jithin1987** [comment]
@guybedford I was able to narrow my codebase to a point that this error was not happening. What I did was stripped off modules from my code base to a point that I don't see this issue. 

And when this issue happens I always get this warning while doing bundle.

`[BABEL] Note: The code generator has deoptimised the styling of "unknown" as it exceeds the max of "100KB".`

I noticed that when I start stripping off modules from my code base, at one point this error disappeared  and the bundle which jspm produced did not have the stray `System.register`

**Comment by jithin1987** [comment]
@guybedford After nuking `node_modules` and reinstalling things are working. I no longer get the incorrect `System.register` line. Before nuking `node_modules` I tried a build with rollup skipped. That also did not have the issue. So I guess it was caused by one of dependencies.

**Comment by guybedford** [comment]
Ok, if you do come across this again, please report back.
