### ISSUE TITLE
React.js component got broken after using `jspm bundle-sfx`

### ISSUE THREAD

**Issue by jeud** [jspm/jspm-cli#1803]
I have done some googling so I think my problem might be related to `system.js`

I have a very simple React.js Component *app/index.js*

    import React, { Component } from 'react';
    import ReactDOM from 'react-dom';
    
    class ReactApp extends Component {
    
    	handleClick(event) {
    		console.log('Clicked ...');
    	}
    
    	render() {
    		return (
    			<div>
    				<h3>Hello World</h3>
    				<button className="btn btn-success" onClick={ this.handleClick.bind(this) }>Click</button>
    			</div>
    		);
    	}
    }
    
    ReactDOM.render(<ReactApp />, document.getElementById('reactApp'));

This component works fine using jspm (development mode) with `<script>` tag in the *index.html* as below

    <script type="text/javascript" src="jspm_packages/system.js"></script>
    <script type="text/javascript" src="config.js"></script>
    <script type="text/javascript">
    	System.import('app/index');
    </script>

After using `jspm bundle-sfx app/index dist/app.min.js` and editing *index.html* to

    <script type="text/javascript" src="dist/app.min.js"></script>

I then have got this error

[![enter image description here][1]][1]

    'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.
    
    'webkitIndexedDB' is deprecated. Please use 'indexedDB' instead.

I believe, I have done this using `jspm bundle-sfx` 2 months ago, it was working just fine, I have tried to google for some solution but no luck, please guide

Thanks

  [1]: http://i.stack.imgur.com/YwfRF.png

**Comment by guybedford** [comment]
Response from SystemJS duplicate issue - 

> These are not critical warnings here. The issue would be something else. I'm surprised there isn't any error though.

> Perhaps try step debugging to see where in the code it is stopping? If you can share the dist/app.js (unminified) file I may be able to take a look.

**Comment by jeud** [comment]
@guybedford Thanks for your reply

This is my [dist/app.js](https://gist.github.com/anonymous/87a90b1a91bc99ee71a878ac3dff3806)

Right now I'm only able to use `jspm bundle`

*Terminal*
````
jspm bundle app/index dist/app.bundle.js
````
*index.html*
````
<script type="text/javascript" src="jspm_packages/system.js"></script>
<script type="text/javascript" src="config.js"></script>
<script type="text/javascript" src="dist/app.bundle.js"></script>
<script type="text/javascript">
	System.import('app/index');
</script>
````
> My jspm version: 0.16.34

**Comment by guybedford** [comment]
@jeud if I use your build file in a new page I get the message:

```
app.js:11980 Uncaught Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
```

Are you not getting that at all?

To do a development build you'd need to use manual builder API instead of the CLI (https://github.com/jspm/jspm-cli/blob/master/docs/api.md#class-builder) and then add the build option: `production: false`.

In jspm 0.17 this can be done with `jspm build --dev` so is a bit easier there.

**Comment by guybedford** [comment]
Let me know if you still need help here.

**Comment by jeud** [comment]
@guybedford yes please.

I'm not really getting that if I would like a production build (to deploy `react.js` app), can I use `jspm build-sfx` or not, or I only have to use the *builder API*, I quite sure that a few months ago (not sure which `jspm`'s version was) I can using `jspm build-sfx` successfully without this kind of errors

So please give some more advice, thanks.

**Comment by guybedford** [comment]
@jeud perhaps try using jspm 0.17 beta here with `jspm build` which replaces the sfx build.

**Comment by jeud** [comment]
Thanks @guybedford
