### ISSUE TITLE
jspm install changes SystemJS paths

### ISSUE THREAD

**Issue by code-chris** [jspm/jspm-cli#1807]
Hi,
if I execute ```jspm install``` jspm will reset the generic path mappings (github:* and npm:*) to the values in the following code snippet. My config.js looks like this:

```
System.config({
  baseURL: "/test/aurelia",
  defaultJSExtensions: true,
  transpiler: false,
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*",
    "knockout": "../../jspm_packages/npm/knockout@3.4.0"
  },
```

My baseUrl is not set to "/" so the path directly to the jspm_packages folder would not work. So I have to revert this change every time I executed "jspm install".

Is it possible to change this behavior, that this mapping will respect the baseUrl?

**Comment by guybedford** [comment]
jspm 0.17 is much more careful not to override custom user configurations like this, but altering the pathing behaviours in jspm 0.16 is not a priority currently.

**Comment by code-chris** [comment]
Ok, then I think it is not necessary to fix that now.
