### ISSUE TITLE
builder#bundle does not re-bundle

### ISSUE THREAD

**Issue by thefabulousdev** [jspm/jspm-cli#1808]
**Version : 0.17.0-beta.12**

### Given
We require the jspm `Builder` constructor and create and we create an instance
```js
var JspmBuilder = require('jspm').Builder;
var jspmBuilder = new JspmBuilder();
```
We create a function to bundle
```js
function bundlePackage(){
    return jspmBuilder.bundle('my-package-name', projectBundleFilePath);
}
```
We initialize its configuration and perform an initial bundle 
```js
jspmBuilder.loadConfig(jspmConfigFile).then(function () {
    return bundlePackage();
});
```
### Then
After some time, on this example on a source file change we call the `bundlePackage` function again 
```js
onSourceFileChange(bundlePackage);
```
### Finally
The first call to the `bundlePackage` function did bundle the package and created its respective files, the second call although the promise gets resolved, the bundle files are created but without the changes done to the source files which in this case were the ones that triggered the rebuild.

If I re run the process the bundle gets generated once with the source files changes and same non-rebundling behavior occurs on further changes.

### Notes 

- I saw that on the old `bundle` there was a `watch` option, however that option seems to be missing on the `builder.bundle()`, the previous example is a quick attempt to get a similar behavior

**Comment by guybedford** [comment]
Try calling `builder.reset()` between builds to invalidate the cache. This is a documentation issue though.
