### ISSUE TITLE
Subtracted dependencies from builds still have to be installed

### ISSUE THREAD

**Issue by joeldenning** [jspm/jspm-cli#1812]
There might be a very good reason for this, but if you run `jspm build my-project - lodash my-project.build.js`, you *must* have lodash installed even though it's going to get subtracted out.

What's the reason for that? Would it be possible/easy for the build to succeed even when lodash isn't installed locally?

**Comment by guybedford** [comment]
Subtractions are bundle tree subtractions, so for example if lodash depends on x and my-project depends on x and lodash, all instances of `x` will be subtracted.

Try using `--externals` rather - `jspm build my-project --externals lodash`.

**Comment by guybedford** [comment]
(Just experimenting with the "support" label here)

**Comment by joeldenning** [comment]
Awesome, I didn't know about `--externals`. If I want to do multiple externals I would just do something like `--externals lodash --externals jQuery`? If so then that's perfect.

**Comment by guybedford** [comment]
The externals are actually just space separated currently. It seemed a valid tradeoff in the externals case specificially (even though other operators carefully allow spaces in module names).

**Comment by joeldenning** [comment]
Oh so you probably do the --externals after specifying the out file, instead of before (which is how I've done things with bundle tree subtraction)?

Sounds good, thanks for the quick responses

**Comment by lookfirst** [comment]
Cheesy and lack of class to ask for tips like this. Just imho. Plus if I see this for all the support emails I'm  going to stop watching tickets. It is total inbox spam.

**Comment by guybedford** [comment]
@lookfirst just experimenting with it here (after 3 hours of issue queues on a Sunday evening), but point taken and I appreciate hearing your reaction as opposed to not!

**Comment by joeldenning** [comment]
I, for one, don't mind it -- what would be worse in my opinion is if money was the reason that Guy Bedford stopped building/supporting/improving jspm/systemjs. We use systemjs extensively in production at work and I also use it a lot for personal projects, so I have a stake in its future.

**Comment by lookfirst** [comment]
If @guybedford needs money to support his time on this project, then there are better ways to go about getting it. Namely, create a business around jspm and provide professional level support contracts. It is the way that many OSS projects have been doing things for so many years now and is a proven business model. I for one, would happily be an early subscriber as I also depend heavily on jspm and in the last year have built a very successful business. Thanks @guybedford.

**Comment by dckesler** [comment]
@guybedford I think it's fine that you ask for tips. It's your project that you actively support, and you should be able to do what you want.

**Comment by leggyman** [comment]
I donated $1 just because I disagree with @lookfirst. Keep up the good work, @guybedford!

**Comment by dckesler** [comment]
I did $2. That's twice as much as @leggyman.

**Comment by lookfirst** [comment]
Sweet, I'll give him $1000 when he adds a real support system. $1, $2... that isn't even enough to buy a cup of coffee. Rude.

**Comment by blittle** [comment]
If every developer who stared JSPM gave $2, that would be a fair chunk of change!

**Comment by leggyman** [comment]
@lookfirst your future self is so freaking generous! Give yourself a pat on the back (in the future).

**Comment by lookfirst** [comment]
@leggyman Your current self is cheap and rude. =)

**Comment by guybedford** [comment]
I appreciate all the sentiments... it's really good to get feedback on this stuff. Getting small recurring payments to add up is the current goal.

@lookfirst I've send you an email with a previous support offering I took to a few companies, it would be great to get your feedback as I wasn't able to get any companies to bite on that specific proposal, and actually felt much worse about trying to "sell" that than I do about asking for tips.

**Comment by alairock** [comment]
I'm going to donate a couple bucks as well. Why? Because I _too_ want to ruffle some feathers.

**Comment by joeldenning** [comment]
I donated $3

**Comment by lbntly** [comment]
Donated 5 bucks. Thanks @guybedford :)

**Comment by lookfirst** [comment]
@alairock Why does donating ruffle feathers? I **ABSOLUTELY** want @guybedford to get donations. I just don't think that doing it as an automated fashion on support tickets is a good way to do it. I also think donating $1 or $3 is rude. That's less than a cup of coffee.

I just donated $100 out of my own pocket.

As soon as Guy and I can work out a proper support contract system, I'll get my company to buy one.

Up your game people. Guy works harder than you.

**Comment by leggyman** [comment]
@lookfirst We would like to thank you for your generosity and for showing us all such a good time today. You are truly inspiring 😄

**Comment by alairock** [comment]
@lookfirst Pic of receipt or it didn't happen.

**Comment by lookfirst** [comment]
@alairock where is your screenshot? http://take.ms/HNaKI

**Comment by perrin4869** [comment]
@lookfirst I actually think the automated reminder, while not perfect, is a pretty good compromise for a project as big as JSPM, which so many people depend on. It's easy to miss the support badge on the README, and sometimes people need a reminder to go ahead and make a donation.

**Comment by lookfirst** [comment]
@perrin4869 Then add it to 'jspm install' output. ;-)

**Comment by perrin4869** [comment]
@lookfirst lol heck no :P
In any case I think it's disgraceful that a project as this cannot raise a measly 500usd per month...

**Comment by dckesler** [comment]
I know a company that sells coffee for less than $2. High five me.

**Comment by alairock** [comment]
@lookfirst Beat that! ![all mail - latchkey 40gmail com - gmail 2016-05-16 17-16-46](https://cloud.githubusercontent.com/assets/1480236/15308383/e1d33ad2-1b99-11e6-8787-e8592515eaec.png)
