### ISSUE TITLE
JSX-Loader No Longer Required?

### ISSUE THREAD

**Issue by ajhyndman** [jspm/jspm-cli#1819]
Apologies if I'm missing something obvious here.

JSX-Loader no longer seems to be required, as long as you somehow tell SystemJS to run the file through Babel.

I've experienced some weird behaviour with this though.  Currently, by including `!babel` after the filename of a JSX import, I can force babel transpiling.  Adding just `!` works, if I add another line to config.js as follows:

```
  map: {
    "jsx": "npm:babel-core@5.8.38", ...
```

This is great for development, but now bundling is failing the first time it hits JSX code.  It looks to me like the code is not being processed by any JSX transpilation.

```
[01:46] λ jspm bundle-sfx app/main.jsx!babel app.js --skip-source-maps
     Building the single-file sfx bundle for app/main.jsx!babel...

err  SyntaxError: unknown: Unexpected token (26:12)
  24 |
       25 |         return (
> 26 |             <div
     |             ^
```

This issue seems related, but I'm not sure I grasp what's going on.
https://github.com/jspm/registry/issues/481

This repository exhibits the issue.  I'm using JSPM 0.16.34 on a windows development machine with node version 5.0.0

Any suggestions would be appreciated.

**Comment by guybedford** [comment]
Babel version 5 does include jsx automatically. But in jspm 0.17 with the upgrade to Babel 6 you need to install jsx support again! (see http://jspm.io/0.17-beta-guide/installing-the-jsx-babel-plugin.html if you are interested)

To understand the error there would need understanding what `babel` is mapped to as that would be the plugin in use (not what `jsx` is mapped to). The error message you're getting is definitely a Babel error message though.

**Comment by ajhyndman** [comment]
Thanks for the response!  I'm pretty sure I'm running babel pre-6.  I'm still using the version of jspm that's published on npm.

If I try actually including presets, I very clearly get a babel-5.8.38 error.

```
[21:13] λ node_modules\.bin\jspm bundle-sfx .\app\main.jsx!
     Building the single-file sfx bundle for .\app\main.jsx!...

err  Error on translate for ./app/main.jsx!npm:babel-core@5.8.38.js at file:///E:/Projects/jspm-react/app/main.jsx!file:///E:/Projects/jspm-react/jspm_packages/npm/babel-core@5.8.38.js
        ReferenceError: [BABEL] file:///E:/Projects/jspm-react/app/main.jsx: Unknown option: direct.presets
```

**Comment by guybedford** [comment]
I guess the error is `Unknown option: direct.presets`, which sounds like it is related to an invalid input option (presets is not an option in Babel 5).

**Comment by ajhyndman** [comment]
Sorry, I guess I'm not explaining myself very well.

I am using babel 5.8.38, with jspm 0.16.34.  I can get systemjs to load an app with transpilation in the browser **without** installing jspm's jsx plugin (i.e. `jspm install jsx`).  This lets me use Babel's sourcemap feature, which works great!

However, with the same settings, running `jspm bundle-sfx app/main.jsx!babel` triggers a syntax error, and I'm not sure why.

```
[01:46] λ jspm bundle-sfx app/main.jsx!babel app.js --skip-source-maps
     Building the single-file sfx bundle for app/main.jsx!babel...

err  SyntaxError: unknown: Unexpected token (26:12)
  24 |
       25 |         return (
> 26 |             <div
     |             ^
```

**Comment by ajhyndman** [comment]
I'll try experimenting with jspm 0.17.  If that upgrades babel to version 6, then I shouldn't have any of the same problems.  :)

**Comment by ajhyndman** [comment]
I'm really enjoying the changes in 0.17!  I can achieve everything I was after this way, thanks.
