### ISSUE TITLE
External dependencies gets overwritten in the bundle by local imports

### ISSUE THREAD

**Issue by GlurG** [jspm/jspm-cli#1821]
I'm running the following command to bundle my application: `jspm bundle js/boot.js client/js/app.min.js`

```
// boot.js
import $ from "jquery";
```
```
// Relevant parts of my index.html:
<script src="https://cdnjs.cloudflare.com/ajax/libs/systemjs/0.19.27/system.js"></script>
<script src="jspm.browser.js"></script>
<script src="jspm.config.js"></script>
<script src="js/app.min.js"></script>
<script>System.import("js/boot.js");</script>
```
```
// jspm.browser.js:
SystemJS.config({
  paths: {
    "github:*": "/jspm_packages/github/*",
    "npm:*": "/jspm_packages/npm/*"
  }
});
```
```
// Relevant parts of jspm.config.js:
"js/boot.js": {
  "deps": [
    "bootstrap",
    "stylesheets/main.css"
  ]
},
...
map: {
  "bootstrap": "https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/js/bootstrap.min.js",
  "jquery": "https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.3/jquery.min.js"
}
```
The problem is that bootstrap never gets loaded when I `System.import("boot.js")` and upon inspecting the bundle, it doesn't contain the dependency to bootstrap even though I have specified it as a dependency (in jspm.config.js).
```
// app.min.js
System.register("js/boot.js", ["jquery"], function (_export, _context) { ...
```
If I remove `import "jquery"` line in `boot.js`, then it gets correctly included.
```
// app.min.js
System.registerDynamic("js/boot.js", ["bootstrap", "stylesheets/main.css"], false, function($__require, $__exports, $__module) { ...
```
My workaround is to import all dependencies in boot.js instead of specifying them in jspm.config.js
Is this intended?

**Comment by guybedford** [comment]
`metadata.deps` is not currently supported for ES Modules, which is tracking in https://github.com/systemjs/systemjs/issues/1248. Closing to follow there. The reason for the resistance to this feature is that it hasn't been clear if `metadata.deps` would be possible in the loader spec for ES modules in browsers in future.
