### ISSUE TITLE
jspm clean to remove stale map configurations

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#1822]
So to effectively automatically uninstall anything unreferenced.

**Comment by adriatic** [comment]
Do you want to do this - or should I try to contribute with a PR? I admit that I never looked at the jspm code, so while I need this badly it can take me a couple of centuries to do it alone :-)

**Comment by guybedford** [comment]
I'll see if I can squeeze it in for the next jspm 0.17 release. Backporting it to jspm 0.16 is something I may need some help with as it's harder to justify that time.

**Comment by adriatic** [comment]
Note also that the we have to use a section of config.js to communicate some data to systemjs that does not exist in package.json - as shown [here](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/master/config.js#L11-L16)

**Comment by adriatic** [comment]
> Backporting it to jspm 0.16 is something I may need some help with as

Given the "model" you will write for 0.17, I will gladly backport it to 0.16 :-)

**Comment by guybedford** [comment]
Well that was easy... https://github.com/jspm/jspm-cli/commit/b9dfb53e2e200d3e6f0421c6c7ba3b00fe4f1917

**Comment by adriatic** [comment]
I did not even finish my dinner - and you created the solution for what bugged me for months ...

Thanks Guy !

**Comment by adriatic** [comment]
One more comment that makes sense in my logic applied to natural language semantics: `clean` should be renamed to `prune` - as then the sequence

```
jspm install
jspm prune
``` 

would make complete sense: after processing the `package.json` and making relevant updates to `config.js`, I want to ensure that `config.js` has no stale entries.

**Comment by guybedford** [comment]
You're completely right about the term `prune`, but I must admit I can't help not much liking the word. `jspm clean` still seems to get the point across I think, especially if we document it as a "pruning" operation?

**Comment by adriatic** [comment]
You certainly have earned the right to call things your way - as a croatia born and raised, all english words are just symbols, now mapped to croatian idioms, so I am not sensitive to prune as you are.

**Comment by guybedford** [comment]
Released in jspm 0.17.0-beta.15.

**Comment by piotrwitek** [comment]
@guybedford I don't want to be rude and to push too hard, but maybe it would be good idea to provide `prune` as an alias to `clean` especially for a new audience starting to use JSPM, most of JS dev are already familiar with this operation from NPM so it would be a natural transition

**Comment by guybedford** [comment]
@piotrwitek sure we can do that, I've included this.

**Comment by amcdnl** [comment]
`jspm clean` basically removed almost everything... :( See: http://www.screencast.com/t/LO6iIG99RGNI

**Comment by guybedford** [comment]
@amcdnl it removes everything not listed as a package.json dependency or sub-dependency of a package.json dependency.

**Comment by tyrsius** [comment]
Is there a "dry-run" option available for `prune/clean`?
