### ISSUE TITLE
When there is an error using jspm bundle, new save doesn't rebuild

### ISSUE THREAD

**Issue by jonricaurte** [jspm/jspm-cli#1825]
When I am running:

jspm bundle h2 public/h2_assets/build.js --skip-source-maps -wd

And there is an error in one of my files, the build stops and gives an error. When I go and fix that file and press save, the build does not try to restart. I have to Ctrl + C and kill the process and then use the above command again. It would be nice if when you fixed an error, it would rebuild again automatically.

**Comment by guybedford** [comment]
Let's track this in https://github.com/jspm/jspm-cli/issues/1789.

**Comment by jonricaurte** [comment]
@guybedford sounds good
