### ISSUE TITLE
Unauthorized response for GitHub API

### ISSUE THREAD

**Issue by linnett** [jspm/jspm-cli#1827]
We are currently using jpsm and when running it on the server to do builds, we are getting the following error (in this example, specifically jqueryui):

```
warn Error on getPackageConfig for github:components/jqueryui
     Unauthorized response for GitHub API.
     Use jspm registry config github to reconfigure the credentials, or update them in your ~/.netrc file.
```

We have tried fixing this with the following: 
```
JSPM_GITHUB_AUTH_TOKEN=$(echo TOKENTOKENTOKEN | base64)
JSPM_GITHUB_AUTH_TOKEN=$(echo username:TOKENTOKENTOKEN | base64)
JSPM_GITHUB_AUTH_TOKEN='TOKENTOKENTOKEN'
```

We have also created a `~/.netrc` file here that looks like this:
`machine github.com login USERUSERUSER password TOKENTOKENTOKEN`

However, these solutions do not work. What exactly do we need to do to get around this error? 

@guybedford your help with this would be greatly appreciated.

Please note versions below:
```
+ /bin/bash -l -c 'node -v'
v0.12.7
+ /bin/bash -l -c 'npm -v'
2.11.3
+ /bin/bash -l -c 'jspm -v'
0.16.34
```

**Comment by leventyalcin** [comment]
We've also tried to create ~/.netrc file with following content and didn't help too 

```
machine github.com login USERUSERUSER password TOKENTOKENTOKEN```
```

**Comment by leventyalcin** [comment]
On the other hand, jspm doesn't have any sort of verbosity/debug option and it makes jspm impossible to debug. I can't know what credentials of stuff jspm is using. 

For instance, this is output of `composer`
```
/usr/local/bin/composer -vvv --no-interaction install
Reading ./composer.json
Loading config file /var/lib/jenkins/.composer/config.json
Loading config file /var/lib/jenkins/.composer/auth.json
Loading auth config from COMPOSER_AUTH
Loading config file ./composer.json
Checked CA file /etc/pki/tls/certs/ca-bundle.crt: valid
```

You see `COMPOSER_AUTH` over there because of the environment variable exist and it has valid format etc.

This is the nature and expected behaviour of cli.

**Comment by guybedford** [comment]
The encoding we use is `new Buffer(encodeURIComponent(username) + ':' + encodeURIComponent(password)).toString('base64');`.

**Comment by leventyalcin** [comment]
Thanks for the prompt respond @guybedford. 

I've tried `JSPM_GITHUB_AUTH_TOKEN=USERNAME:BASE64TOKEN` but the result is the same one.

**Comment by markosamuli** [comment]
@linnett Try "echo -n" instead of "echo" http://stackoverflow.com/questions/20499578/n-option-with-echo-command-in-linux

**Comment by guybedford** [comment]
It's a very specific encoding as provided above. The other way to get the right value is to configure locally and then use `jspm registry export github` to extract the jspm-generated token.

**Comment by leventyalcin** [comment]
@markosamuli Thanks for heads up I've tried assign actual values directly instead echo but didn't help too.

**Comment by leventyalcin** [comment]
@guybedford 
`jspm registry export github` tells me 
```
jspm config registries.github.handler jspm-github
jspm config registries.github.remote https://github.jspm.io
```

shall I set `jspm config registries.github.remote JSPM_GITHUB_AUTH_TOKEN` or shall I give the token  `jspm config registries.github.remote TOKENTOKENTOKEN`?

**Comment by leventyalcin** [comment]
Is there any way to make sure `jspm` uses the credentials?

I've tried with 
```
export JSPM_GITHUB_AUTH_TOKEN=USERNAME:BASE64TOKEN
jspm config registries.github.auth JSPM_GITHUB_AUTH_TOKEN
jspm install
```

and 

```
jspm config registries.github.auth USERNAME:BASE64TOKEN
jspm install 
```

and didn't help

**Comment by markosamuli** [comment]
@leventyalcin Have you tried `jspm registry config github` and then copying working token from the `~/.jspm/config` file? 

The base64 encoded auth token includes the username and the access token. Your example looks like it would not be encoding the username.

```
  export GITHUB_USERNAME=username
  export GITHUB_TOKEN=token
  export JSPM_GITHUB_AUTH_TOKEN=$(echo -n $GITHUB_USERNAME:$GITHUB_TOKEN | base64)
```

**Comment by linnett** [comment]
@markosamuli you're the man! `-n` was the winner - thanks dude. Thanks as well for the input @guybedford

**Comment by leventyalcin** [comment]
thanks a lot @markosamuli! 
the confusing thing to me was base64. 
> new Buffer(encodeURIComponent(username) + ':' + encodeURIComponent(password)).toString('base64');
regarding this I was sending user:base64token and new line at the end. 

It seems ok now. 

Thanks guys!
