### ISSUE TITLE
jspm bundle produces no output

### ISSUE THREAD

**Issue by crystalbyte** [jspm/jspm-cli#1829]
I am using the 0.17-beta.14 version of jspm and am trying to create the dependency bundle on Windows Server 2012 RC2. It did work with recent versions, I am however unsure whether it is due to an invalid config file or the version update.

Unfortunately this is all the output I get in the console.
`PS D:\AWK\ITS Portal Full\Main\Source\Kpmg.ItsPortal\Source\Kpmg.ItsPortalWeb\Client\app> jspm bundle .\app.js --minify
     Building the bundle tree for .\app.js...

PS D:\AWK\ITS Portal Full\Main\Source\Kpmg.ItsPortal\Source\Kpmg.ItsPortalWeb\Client\app>`
There is no error message or any output whatsoever.
I attached the main script and the config file, any help would be greatly appreciated.

[app.js.txt](https://github.com/jspm/jspm-cli/files/275016/app.js.txt)
[jspm.config.js.txt](https://github.com/jspm/jspm-cli/files/275017/jspm.config.js.txt)

**Comment by guybedford** [comment]
Are you using the TypeScript plugin here then? If you can help by tracking down what change may have caused this that would be a big help. Is it eg jspm@0.17.0-beta.13 -> jspm @0.17.0-beta.14? Or perhaps a version change in the TypeScript plugin itself?

**Comment by crystalbyte** [comment]
While the source for the JS file is written in typescript, I bundle against the plain ES5 output without jspm plugins. I will try the previous version and get back to you.

**Comment by crystalbyte** [comment]
I just rolled back to beta.4 where it definitely worked and I get the same result, so it's not a version thing. I stripped my JS file to a single line `require("webl10n/l10n");` and an output file was successfully generated. Is there perhaps a size limitation or a verbose mode to activate?
