### ISSUE TITLE
jspm config file path

### ISSUE THREAD

**Issue by kanivenk** [jspm/jspm-cli#1831]
We have requirement not use users folder for jspm configuration file and cache packages. do we have any way to direct jspm tool to use config file from any custom folder. I understand there is a way to refer local config path from project folder but we want to maintain this config file machine level.

**Comment by guybedford** [comment]
jspm will use the environment variables in this order - `LOCALAPPDATA`, `HOME`, `HOMEPATH`. So you could try setting `LOCALAPPDATA`. Also we could certainly add a custom environment variable here like `JSPM_GLOBAL_CONFIG`. Let me know your thoughts.

**Comment by kanivenk** [comment]
Thanks for the information. we tried with LOCALAPPDATA ,HOME and HOMEPATH but they didn't work. jspm install still checking for config in the %USERPROFILE%\AppData\Local\.jspm folder and creating default config file there.

may be its good idea to add  JSPM_GLOBAL_CONFIG but wondering why those above environment variables didn't work.
may be we are doing something not correct in setting up these environment variables.

**Comment by guybedford** [comment]
@kanivenk those environment variables definitely should have worked. Perhaps in windows those environment variables aren't writable. Did you want to try adding a JSPM_GLOBAL_CONFIG environment variable check at https://github.com/jspm/jspm-cli/blob/master/lib/config.js#L16 and see if that works?

**Comment by kanivenk** [comment]
adding JSPM_GLOBAL_CONFIG to environment variable worked as expected. the below is the line changed in config js file
exports.HOME = process.env.JSPM_GLOBAL_CONFIG || process.env.LOCALAPPDATA || process.env.HOME || process.env.HOMEPATH;

Thanks for quick help on this.

**Comment by guybedford** [comment]
I've added support for a `JSPMPATH` environment variable in https://github.com/jspm/jspm-cli/commit/d6feb3c2a2769fa48d9ecbcefd536d998e40bf83.

**Comment by guybedford** [comment]
Ok changed to `JSPM_GLOBAL_PATH`.

**Comment by guybedford** [comment]
Released in 0.17.0-beta.16.

**Comment by JoshMcCullough** [comment]
@guybedford Is the `LOCALAPPDATA` / `HOME` / `HOMEPATH` env. variable used to tell JSPM where to look for config, or where to cache packages, or both?

I've set them all to a specific directory where I'd like JSPM's cache to go. But JSPM never creates the `.jspm` folder in that location. This leads me to believe that these variables are not considered when determining where JSPM's cache should go.

Related comment here: https://github.com/jspm/jspm-cli/issues/995#issuecomment-338247074

**Comment by guybedford** [comment]
@JoshMcCullough see above comment - https://github.com/jspm/jspm-cli/issues/1831#issuecomment-221741486 the environment variable is JSPM_GLOBAL_PATH.

**Comment by JoshMcCullough** [comment]
@guybedford but we're not on .17 so we can't use that new variable.

**Comment by guybedford** [comment]
@JoshMcCullough right, the line is here - https://github.com/jspm/jspm-cli/blob/master/lib/config.js#L16. If you wanted to PR JSPM_GLOBAL_PATH support for 0.16 that is welcome too.

**Comment by JoshMcCullough** [comment]
@guybedford  Thanks for your response. The `LOCALAPPDATA` environment variable is indeed working, I just had something else screwed up when I was testing this. All set for now!
