### ISSUE TITLE
 Globals are not being respected in sfx builds

### ISSUE THREAD

**Issue by jonricaurte** [jspm/jspm-cli#1833]
In my javascript I have the following being imported:

```
import 'jquery';
import 'angular';
import 'angular-animate';
import 'angular-mocks';
import 'angular-resource';
import 'angular-messages';
import 'angular-cookies';
import 'angular-sanitize';
import 'angular-local-storage';
import 'angular-ui-bootstrap';
import 'angular-ui-router';
import 'angular-cookie';
import 'angular-inview';
import 'angular-loading-bar';
```

These all show in the bundle.js file in the order listed above. The moment I add one of the following:
import 'slick-carousel';
import 'angular-oauth2';
import 'videogular';

Then all the sudden the order is wrong and angular-animate is listed above angular in the bundle.js file. When i run jspm build, what happens is since it loads angular-animate before angular, I get an error saying angular is undefined.

**Comment by aluanhaddad** [comment]
Is angular mapped as a dependency of angular-animate?

**Comment by jonricaurte** [comment]
@aluanhaddad  it is not, but I do have angular as a global like so:

```

  meta: {
    "*.jade": {
      "loader": "jade"
    },
    "npm:jquery@2.1.3/dist/jquery.js": {
      "format": "global"
    },
    "npm:angular@1.5.3/angular.js": {
      "format": "global"
    },
    "npm:underscore@1.8.3/underscore.js": {
      "format": "global"
    }
  },
```

By making it be global, shouldn't it be available each in module? This is in regards to sfx builds though. When I run jspm bundle, angular is within each module and it does not matter which order they are loaded in, but running an sfx build angular animate does not find angular so maybe that is the issue instead.

**Comment by jonricaurte** [comment]
Maybe the issue is globals are not loading correctly in sfx builds @guybedford @aluanhaddad

**Comment by jonricaurte** [comment]
@guybedford It looks like globals aren't being respected in sfx builds because then the order would not matter.

**Comment by guybedford** [comment]
@jonricaurte execution order is not deterministic. The only way to guarantee execution order of globals is to have all global modules which assume the `angular` global to have an explicit `meta: { deps: ['angular'] }` metadata on them.

**Comment by aluanhaddad** [comment]
@jonricaurte to expand a little further on what @guybedford said as it pertains to this specific example, you are loading jQuery as a global an angular as a global but you have not declared a dependency for angular on jQuery. Because the execution order is not deterministic, angular may use its own internal jqlite or the full version of jQuery depending on the order in which they are loaded and this may differ between different runs of your application. This is extremely problematic.

**Comment by jonricaurte** [comment]
@guybedford thanks. It looks like I have to do this on all the following dependencies:

```
 meta: {
    '*.jade': {
      'loader': 'jade'
    },
    'npm:jquery@2.1.3/dist/jquery.js': {
      'format': 'global',
      'exports': 'jQuery'
    },
    'npm:angular@1.5.3/angular.js': {
      'format': 'global',
      'exports': 'angular',
      'deps': [
        'jquery'
      ]
    },
    'npm:underscore@1.8.3/underscore.js': {
      'format': 'global',
      'exports': '_'
    },
    'npm:angular-animate@1.5.3/angular-animate.js': {
      'deps': [
        'angular'
      ]
    },
```
If that is correct, we can close this ticket. Thanks!

**Comment by jonricaurte** [comment]
@aluanhaddad @guybedford  thanks for the clarification. Closing.

**Comment by guybedford** [comment]
@jonricaurte another alternative to the above deps is globals config:

```javascript
 meta: {
    '*.jade': {
      'loader': 'jade'
    },
    'npm:jquery@2.1.3/dist/jquery.js': {
      'format': 'global',
      'exports': 'jQuery'
    },
    'npm:angular@1.5.3/angular.js': {
      'format': 'global',
      'exports': 'angular',
      'globals': {
        '$': 'jquery'
      }
    },
    'npm:underscore@1.8.3/underscore.js': {
      'format': 'global',
      'exports': '_'
    },
    'npm:angular-animate@1.5.3/angular-animate.js': {
      globals: {
        'angular': 'angular'
      }
    },
```

**Comment by jonricaurte** [comment]
@guybedford thanks for the alternative
