### ISSUE TITLE
Typescript + jspm - browser giving useless error messages

### ISSUE THREAD

**Issue by JustASquid** [jspm/jspm-cli#1834]
[Sorry if this is the wrong place for this type of question, I'm a web dev beginner]

I'm working on a Typescript client-side browser app in Webstorm. I'm using jspm for package management, and it all works wonderfully. Typescript transpiles directly to es5 so I don't need to use jspm's transpiler.

The only problem I've noticed is a frustrating one. Whenever my program has a runtime error (e.g. array out of bounds), instead of generating something useful, the Chrome debugger instead generates an error like this:

`system.js:4 Uncaught (in promise) Error: TypeError: ((e.stack || e.message) || e).split is not a function
	Error linking http://localhost:63342/[ProjectName]/app/source/main.js @ system.js:4g @ system.js:4p @ system.js:4h @ system.js:4(anonymous function) @ system.js:4`

'main.js' is just the entry point and is not where the runtime error is ocurring. The actual error `((e.stack || e.message) || e).split is not a function` is also not an error that my program is making, I assume this is something internal to System.js.

How can I get proper error message from the Chrome console?

**Comment by guybedford** [comment]
Yes this is a bug that the error message isn't coming through properly. I've added https://github.com/ModuleLoader/es6-module-loader/commit/de862f7161d084f07322c5f5c4e6afc4efe9fd04 for the next release.
