### ISSUE TITLE
Incorrect nodeConfig paths generated

### ISSUE THREAD

**Issue by bmayen** [jspm/jspm-cli#1835]
Using `0.17` branch, when I run `jspm i` in a project with no preexisting jspm.config.js, it creates the following config:

```
nodeConfig: {
    "paths": {
      "npm:": "jspm_packagesnpm/",
      "github:": "jspm_packagesgithub/"
    }
  }
```

Note the missing path delineator between `jspm_packages` and the repo type.

**Comment by guybedford** [comment]
Thanks, yes I'm aware of this.
