### ISSUE TITLE
JSPM link doesn't install nested linked dependencies (0.17.14 Beta)

### ISSUE THREAD

**Issue by fusionstrings** [jspm/jspm-cli#1836]
Hi,
Ability to link with local folders is a very useful feature. I am using it for couple of modules and it's working fine unless one of the linked package also uses another local folder as linked dependency.

##Example
- Package *A* depends on local linked package *B* (**This works**)
- Created another package *C*, add it as dependency on package "B". (**Package B works**)
- Trying to relink *B* in *A* using documented method/s results in following error.

```sh
    jspm link ./../module-b local:module-b@0.0.1
        Updating registry cache...
        Processing linked package local:module-b@0.0.1

    err  Package local:module-c can only be linked and not installed.

    err  Error looking up local:module-c.
```
 Using `jspm link ./../module-b`also results in same error.

**Comment by guybedford** [comment]
You'd need to first link package C into package A so that it knows about `local:module-c`. The analogy is that `local:module-c` might be linked as `npm:c@x.y.z`, so it will aim to install c as another dependency directly from remote source by default.

**Comment by fusionstrings** [comment]
Alright, but how is it different than making C direct dependency in A? 
Not complaining but just trying to understand, doesn't it defeat the purpose of encapsulated dependencies?

One needs to know full dependency tree to achieve it.

**Comment by fusionstrings** [comment]
Either way since problem is resolved closing the issue. Long live JSPM. 💯

**Comment by guybedford** [comment]
Linking is treated as a project-local state, not a global state. We could consider transitive linking like this I guess, but it also isn't clear-cut how such a process might work - do we check every installed dependency against the jspm_packages of every linked package to see if it is linked in those? What about third-level linking? It sounds like a lot of statting.

**Comment by fusionstrings** [comment]
Yup, it does sound like complex, but I had in my mind such a scenario where using local module is kind of seamless. As it's required (now) to relink local dependencies, if `package.json` is changed, if it's combined with effort to directly linking nested dependencies (each time), it does not bring lot of good DX.

Regardless, JSPM has already made my life hell lot better and I admire how it is shaping up.
Thanks for your kind support.
