### ISSUE TITLE
Support Electron directly 

### ISSUE THREAD

**Issue by MeirionHughes** [jspm/jspm-cli#1837]
I recently wanted to support es6 import of electron; See: http://stackoverflow.com/questions/37346275/aurelia-using-es6-import-for-electron-typescript/37346276

my work around was to create a module that would wrap the require call and pass all exports onto System.js. 

Is there a way this could be added to jspm like with nodelibs? such that we can do: `jspm install electron`?

**Comment by guybedford** [comment]
If you upgrade to the latest SystemJS (coming in the next jspm release very soon) it supports `import electron from '@node/electon'` as of the latest 0.17 beta.

**Comment by MeirionHughes** [comment]
hmm. Not sure if that will help with regard to typescript though. For example, in my ts I have 

`import {remote} from 'electron';`

that definition is provided by [typings](https://github.com/typings/typings) during development and typescript compilation, and works really well..  

Presumably if you stay with  `import {remote from '@node/electron'` that would mean having to change typing imports; which is something I'd rather not do because as of typings@1.0 the definitions can be automatically restored, rather than committed to the project git. 

Is it something that can be mapped in system.js config? i.e. 

"electron" : "@node/electron"

**Comment by guybedford** [comment]
Yes you could set up a custom map like that certainly.

**Comment by MeirionHughes** [comment]
okay, that would be ideal then.
