### ISSUE TITLE
Put --source-map-contents into the .map file, instead of requiring --inline-source-maps

### ISSUE THREAD

**Issue by joeldenning** [jspm/jspm-cli#1838]
`jspm build my-project my-project.build.js --source-map-contents --inline-source-maps` is wonderful and would be perfect for me...except it's not ideal for production workflows since it makes built files a lot bigger. What I would love is if there was a way to have `my-project.build.js` just point to `./my-project.build.js.map` AND have `./my-project.build.js.map` contain the source map contents. As far as I am aware, that is not possible since `--source-map-contents` does not do anything [unless you also `--inline-source-maps`](https://github.com/jspm/jspm-cli/issues/1723#issuecomment-210897750).

Let me know if there is a way to already do this, or if not how hard it would be. Would be happy to try to contribute.

**Comment by joeldenning** [comment]
This is a bit embarrassing but looks like doing just `--source-map-contents` (without also doing `--inline-source-maps`) actually is working. I just had something unrelated misconfigured that got me confused into thinking that there was an issue here. Closing this issue.

**Comment by guybedford** [comment]
No problem!
