### ISSUE TITLE
0.17 -- package name messes up source map URLs

### ISSUE THREAD

**Issue by joeldenning** [jspm/jspm-cli#1839]
This issue is basically a continuation of #1723. In that issue, we talked about whether the jspm name for the package should be in the url, and I don't think I was able to full communicate what I meant.

![screen shot 2016-05-23 at 2 21 26 pm](https://cloud.githubusercontent.com/assets/5524384/15483385/aa5f2694-20f1-11e6-9a1b-2b147181e6db.png)

![screen shot 2016-05-23 at 2 20 00 pm](https://cloud.githubusercontent.com/assets/5524384/15483350/765fca24-20f1-11e6-8015-b7ff594cfcd7.png)

Here's my concern / where I think there is an issue. If I run `jspm build my-project dist/my-project.build.js`, the actual source files for `my-project` are not in a directory called `my-project`. But jspm puts `my-project` in as a directory when creating the source mapping urls. The reason why there is not a directory called `my-project` is because my `jspm.browser.js` file looks something like this:

```js
SystemJS.config({
  baseURL: "/",
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*",
    "my-project/": "src/"
  }
});
```
*What the source map url actually is*: `../my-project/main.js`
*What I want the source map url to be*: `../src/main.js`

So really my source files are in a directory called `src`, and `my-project` is more of an abstract concept/name that doesn't equate to a directory served up by my webserver. Is this the expected behavior and I am just doing it wrong? Or maybe a bug in jspm?

**Comment by joeldenning** [comment]
A potential enhancement that could be done while fixing the bug:

Make the package name be the prefix before the `://` in the source map url. So make the sourcemap url be `my-package:///src/main.js` Webpack does something similar by prefixing all their source map urls with `webpack:///`, but if each package had its own prefix then that would be even better.

**Comment by guybedford** [comment]
I believe this is already fixed in the 0.17 branch.

**Comment by joeldenning** [comment]
Is it released in 0.17.0-beta.14, or is it still unreleased? I replicated this issue yesterday on 0.17.0-beta.14

**Comment by guybedford** [comment]
The 0.17 branch should be working correctly now, and I did test this a couple of times and the source maps seemed to be the correct names as far as I can tell.

**Comment by joeldenning** [comment]
Just upgraded to beta.15 and it is now working for me.

**Comment by guybedford** [comment]
👍
