### ISSUE TITLE
Using jspm with http2 possible today? trying to speed up dev process..

### ISSUE THREAD

**Issue by born2net** [jspm/jspm-cli#1840]
So I keep reading how webpack people are enjoing fast dev cycles and it is really the only thing that I am still struggling with jspm / systemjs
I am still unable to use hot-reload (my project wont work with system so using commonjs) and so I am hoping anyone can share idea to maybe use http2 for dev process in hopes to get concurrent loading and faster dev cycle... 

having to wait 10-20 seconds on evey debug cycle (and TypeScript compilation in the browser) is sooo annoying... )
tx

Sean

**Comment by oligot** [comment]
There is a long issue [here](#872) discussing the various ways to speed up development time.

The next version of jspm (0.17) which is currently in beta supports a new flag (--watch) that can be used to rebuild the app every time a source file changes.
You can follow this tutorial to see how it works: http://jspm.io/0.17-beta-guide/development-bundling.html

There is also a section dedicated to hot-reloading in the 0.17 beta guide: http://jspm.io/0.17-beta-guide/hot-reloading.html

**Comment by born2net** [comment]
tx for that!
