### ISSUE TITLE
Using an exports file and importing a sibling export returns undefined

### ISSUE THREAD

**Issue by jonricaurte** [jspm/jspm-cli#1841]
I have the following in a common/components.js file:

```
export { default as cart } from './components/cart/cart.module';
export { default as chatWithUs } from './components/chat_with_us/chat_with_us.module';
export { default as footer } from './components/footer/footer.module';
export { default as navigation } from './components/navigation/navigation.module';
export { default as productSearch } from './components/product_search/product_search.module';
export { default as registrationModal } from './components/registration_modal/registration_modal.module';
```

In my navigation.module file, I have it depend on another common component:

```
import { registrationModal } from 'h2/common/components';

console.log(registrationModal);
```

In my registration_modal.module file I have:

```
var moduleName = 'components.registration_modal';
export default moduleName;
```

The above console.log gives an undefined. If I move the export { default as navigation } from './components/navigation/navigation.module'; to the bottom of the file like so:

```
export { default as cart } from './components/cart/cart.module';
export { default as chatWithUs } from './components/chat_with_us/chat_with_us.module';
export { default as footer } from './components/footer/footer.module';
export { default as productSearch } from './components/product_search/product_search.module';
export { default as registrationModal } from './components/registration_modal/registration_modal.module';
export { default as navigation } from './components/navigation/navigation.module';
```

The console.log gives: components.registration_modal

**Comment by jonricaurte** [comment]
It turns out this only started happening when I added meta tags for everything to have dependencies. Will investigate further.

**Comment by jonricaurte** [comment]
@guybedford this actually happens with no meta tag changes, so it definitely is a bug.

**Comment by jonricaurte** [comment]
This however prints correctly when making an sfx build, but does not print correctly using jspm bundle.

**Comment by guybedford** [comment]
If you `System.import('navigation.module')` directly, is the export value still undefined?

**Comment by jonricaurte** [comment]
@guybedford yes it is still undefined. In my app.js I had:

```
import { navigation } from 'h2/common/components';
```

Then I switched it to:

```
import navigation from '../common/components/navigation/navigation.module';
```

And the console.log still gives undefined.

**Comment by guybedford** [comment]
@jonricaurte to explicitly confirm - if you run `System.import("h2/common/components').then(function(c) { console.log(c); })` then it definitely has an undefined `default` or `navigation` export value?

**Comment by jonricaurte** [comment]
When I run the above, I get actual values and not undefined:

```
n {}
cart
:
"components.cart"
get cart
:
()
set cart
:
()
chatWithUs
:
"components.chatWithUs"
get chatWithUs
:
()
set chatWithUs
:
()
footer
:
"components.footer"
get footer
:
()
set footer
:
()
navigation
:
"components.navigation"
get navigation
:
()
set navigation
:
()
productSearch
:
"components.productSearch"
get productSearch
:
()
set productSearch
:
()
registrationModal
:
"components.registration_modal"
get registrationModal
:
()
set registrationModal
:
()
```

**Comment by guybedford** [comment]
Then it's circular references.

**Comment by jonricaurte** [comment]
@guybedford ok. Is this not supposed to work, or is this an issue with jspm/systemjs? Also, sfx builds work fine; it was just bundling that was not working.

**Comment by guybedford** [comment]
@jonricaurte you'd need to check your execution order and see if there's a circular reference somewhere. Module execution happens in order, so circular references have undefined exports.

**Comment by jonricaurte** [comment]
@guybedford I only have 2 things now in h2/common/component:

```
export { default as registrationModal } from './components/registration_modal/registration_modal.module';
export { default as footer } from './components/footer/footer.module';
```

In my app.js I have:
```
import { registrationModal } from 'h2/common/components';
```

Then in my registration_modal.module.js I have:
```
import { footer } from 'h2/common/components';
console.log(footer)

var moduleName = 'components.registration_modal';

export default moduleName;
```

The console log returns undefined. If I change app.js to the following:
```
import registrationModal from '../common/components/registration_modal/registration_modal.module';
```

I get from the console.log: components.footer
If I change app.js back to:
```
import { registrationModal } from 'h2/common/components';
```

And then change registration_modal.module to be:
```
import footer from '../footer/footer.module';
console.log(footer)

var moduleName = 'components.registration_modal';

export default moduleName;
```

Then I also get from the console.log: components.footer

This makes me think jspm goes through all exports in the file until it gets to the correct one, which is why if I move registration_modal to below the footer with the original set up everything works. There is no circular dependency, but I think since jspm is parsing every export before it gets to the correct one, it thinks there is.

**Comment by jonricaurte** [comment]
I noticed with only two things in the exports file it still gave undefined when I switched them:

```
export { default as footer } from './components/footer/footer.module';
export { default as registrationModal } from './components/registration_modal/registration_modal.module';
```

**Comment by jonricaurte** [comment]
So it looks like the circular dependency is happening because I am referencing the same exports file as shown above even though I am referencing different exports within that file.

**Comment by guybedford** [comment]
That sounds like it then... import order determines execution order, which determines when bindings are defined or not.

**Comment by jonricaurte** [comment]
@guybedford is this a bug or working as intended? Thanks!

**Comment by guybedford** [comment]
This is the way circular references work.

**Comment by jonricaurte** [comment]
@guybedford Thanks, so this ticket can be closed then since it is working as intended. So suggestions for working around this is to only have the exports file be used as a library api for other parties to consume your api, but not to be used by the library to also consume cause then you will get circular references.
