### ISSUE TITLE
Bug in 0.17 edge -- no such file or directory plugin-babel

### ISSUE THREAD

**Issue by joeldenning** [jspm/jspm-cli#1842]
I tried upgrading to the tip of the 0.17 branch since there is a bug fix I need that happened after 0.17.0-beta.14. However, when I upgraded to the latest code on the 0.17 branch, I get the following error:

```
     Creating the single-file build for src/engagements-menu.js - lodash - rx - single-spa - canopy-urls!sofe -
     sentry-error-logging!sofe - toast-service!sofe - fetcher!sofe...

err  Error: ENOENT: no such file or directory, open '/Users/joel/workplace/engagements-menu/plugin-babel'
      at Error (native)
  Error loading /Users/joel/workplace/engagements-menu/plugin-babel
```

Reverting back to 0.17.0-beta.14 corrects the error for me. I then tried this on another project and saw the exact same error occur when trying to use the edge of the 0.17 branch. I am indeed using plugin-babel as my transpiler, and it definitely is installed into the jspm_packages directory but apparently is just not being mapped correctly in the jspm.config or package.json or something.

**Comment by joeldenning** [comment]
Now that 0.17.0-beta.15 is out, I upgraded to that instead of just the edge of the 0.17 branch. I no longer see this problem, so am closing the issue. Not sure if it was related to me trying to use an unpublished version of jspm?? That seems like that would be a weird thing if that was the case.

**Comment by guybedford** [comment]
That bug was there for a short while on the 0.17 branch.
