### ISSUE TITLE
Hot reload with angular 2 and router expception: Route config should contain exactly one "as" or "name" property

### ISSUE THREAD

**Issue by born2net** [jspm/jspm-cli#1844]
I am trying to use hot reload with ng2 and jspm 0.17
the app loads ok, but when I make a change to a file that is under the ng2 router, I receieve an error of:
```
ORIGINAL EXCEPTION: Route config should contain exactly one "as" or "name" property.
```

here:
![capture](https://cloud.githubusercontent.com/assets/5090936/15505480/941d3b6e-2178-11e6-8a49-c14f5ecdccb8.PNG)

has anyone seen this? is there a fix?
and this works fine if I don't use hot-reload.
regards

Sean

**Comment by guybedford** [comment]
I'd suggest posting an issue to the hot reloader project here. Also there is another hot reloader project you can also try at https://github.com/npbenjohnson/systemjs-reloader.

**Comment by born2net** [comment]
ok tx.
