### ISSUE TITLE
Anyone knows how to load highmaps when using system (works fine with cjs)

### ISSUE THREAD

**Issue by born2net** [jspm/jspm-cli#1847]
so this snippet works great when I use commonjs on my config.js
```
import * as Ng2Highcharts from 'highcharts/modules/map';
Ng2Highcharts(Highcharts);
```
but as soon as I switch to system with the following import:
```
import * as Ng2Highcharts from 'highcharts/modules/map';
Ng2Highcharts.default(Highcharts)
```

I get an error of :
```
ORIGINAL EXCEPTION: TypeError: x[(intermediate value)(intermediate value)(intermediate value)] is not a constructor
  ORIGINAL STACKTRACE:
```

any help is appreciated,

Sean

**Comment by born2net** [comment]
anyone :( ?

**Comment by guybedford** [comment]
I just tried `jspm install highcharts` then I created `test.js`:

```javascript
import highchartsMap from 'highcharts/lib/modules/map';
console.log(highchartsMap);
```

Then `System.import('test.js')` seemed to give the correct value for Highcharts as far as I can tell.

**Comment by born2net** [comment]
ok I ended up moving to google maps, as I could not get that to work... better anyways ;)
so closing, but tx for looking!!!!

**Comment by born2net** [comment]
by the way, been playing with ng2 and hot-reload... OMG... so awesome.. 
I am going to make some kick ass video tutorials soon on ng2, jspm, ts and related GitHub projects to make it super easy for people to start with all this amazing tech!
