### ISSUE TITLE
bluebird@3.4.0.json returning "undefined" for browser map

### ISSUE THREAD

**Issue by NervosaX** [jspm/jspm-cli#1849]
On jspm 0.17.0-beta.15. Installing npm:bluebird returns bluebird@3.4.0, which in ~/.jspm/packages/npm/bluebird@3.4.0.json and in my project I'm getting the following:

```
{
  "main": "js/release/bluebird.js",
  "meta": {
    "js/browser/bluebird.js": {
      "format": "global"
    },
    "js/browser/bluebird.min.js": {
      "format": "global"
    }
  },
  "format": "cjs",
  "map": {
    "./js/release/bluebird.js": {
      "browser": "./undefined"
    }
  }
}
```

(note the undefined value)

Seems that it should be:
https://github.com/petkaantonov/bluebird/blob/master/package.json#L70
```
"browser": "./js/browser/bluebird.js",
```

**Comment by NervosaX** [comment]
If anyone has the same problem you can override with the following:

```
jspm install npm:bluebird -o '{ "map": { "./js/release/bluebird.js": { "browser": "./js/browser/bluebird.js" } } }'
```

**Comment by guybedford** [comment]
Thanks for letting me know about this. Fix added in https://github.com/jspm/npm/commit/d001fad30e070cba90e0149e3a23dcfa3ef58b1c pending release.

**Comment by guybedford** [comment]
This has been released.
