### ISSUE TITLE
support github @sha versions

### ISSUE THREAD

**Issue by amitport** [jspm/jspm-cli#1851]
I noticed https://github.com/jspm/jspm-cli/issues/1262 and https://github.com/jspm/jspm-cli/issues/52, but I have a different use case, which I think deserves a separate discussion.

I want to use [this repository](https://github.com/mikaelnousiainen/rangeslider-videojs), but the mainterner did not publish any relevant tag or branch. I do not think referring to the 'master' branch is an acceptable behavior as it may cause an inadvertent, possibly breaking, change later.

**Comment by guybedford** [comment]
This is not something that is currently possible unfortunately, due to the fact that the version resolver is based on looking up all versions rather than individual version requests. This may well become possible in future, but it would need to be part of a larger architectural shift.
