### ISSUE TITLE
[0.17] Consider a wrapper for serving + hot reloading

### ISSUE THREAD

**Issue by jackfranklin** [jspm/jspm-cli#1852]
When I build a project with jspm 0.17 I also have to install some form of local server (I tend to go for [serve](https://github.com/tj/serve)) and as of 0.17 I also have to install the chokidar-socket-emitter.

If I think about getting a new person up and running with jspm then the above is a bit hard to explain - particularly the need for this (what appears) random package chokidar-socket-emitter.

Would you consider a command like `jspm serve` which would spin up a local server and fire up the chokidar socket emitter too? Then the dev experience would be a little smoother. 

I'll probably roll these up into a tiny CLI script for myself but I'd happily contrib it back if it was of interest.

**Comment by aluanhaddad** [comment]
I think it's a great idea to help people get started.

**Comment by guybedford** [comment]
This is definitely a great project to work on. @geelen was working on jspm-server at some point which looked very promising. Something like that may well be able to pave the way for a `jspm serve` feature in future. It's worth keeping features in core to a minimum though, and let them be proved via popularity with third party projects first. If you make any process on a `jspm-serve` CLI please do share further!

**Comment by jackfranklin** [comment]
@guybedford :+1: I'll start work and have it as a separate project and go from there :)
