### ISSUE TITLE
[0.17-beta.14] TypeError on systemjs-hot-reloader when running `jspm build`

### ISSUE THREAD

**Issue by jackfranklin** [jspm/jspm-cli#1854]
I'm running

```
jspm build index.js --skip-source-maps --format iife
```

To build my React application and I'm getting the following error:

```
err  TypeError: No resolution found at all for condition github:capaj/systemjs-hot-reloader@0.5.8/#:./default-listener.js.
    at /Users/jackfranklin/git/talks/client-side-jspm/node_modules/jspm/node_modules/systemjs-builder/lib/trace.js:668:15
    at Array.forEach (native)
    at /Users/jackfranklin/git/talks/client-side-jspm/node_modules/jspm/node_modules/systemjs-builder/lib/trace.js:662:6
    at tryCatcher (/Users/jackfranklin/git/talks/client-side-jspm/node_modules/jspm/node_modules/systemjs-builder/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/jackfranklin/git/talks/client-side-jspm/node_modules/jspm/node_modules/systemjs-builder/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/Users/jackfranklin/git/talks/client-side-jspm/node_modules/jspm/node_modules/systemjs-builder/node_modules/bluebird/js/release/promise.js:559:18)
```

I have updated jspm's systemjs-builder dependency to 0.15.17 but no luck with that.

**Comment by guybedford** [comment]
Hmm, I can't replicate this at all here - `jspm build systemjs-hot-reloader` always works fine for me...

Also you may want to use `--format umd` or `--format global` as we don't actually support `--format iife`.

**Comment by jackfranklin** [comment]
Is it because `index.js`, which I'm trying to build, imports systemjs-hot-reloader?

**Comment by jackfranklin** [comment]
If it's any use, the repo is here: https://github.com/jackfranklin/jspm-017

**Comment by jackfranklin** [comment]
The docs say that for _bundling_, this happens:

> In addition, the hot reloader is by default configured to be excluded when bundling and React has been configured with a jspm override to use conditional loading to exclude its development dependencies as well. CommonJS files will have process.env.NODE_ENV inlined to the value of production, which is then removed by minification giving us the minimal download footprint for React.

Is there problem here that I'm trying to build instead of bundle, and the above isn't configured? Should I even be building here?

**Comment by guybedford** [comment]
Ah thanks, I tracked this down. You can workaround the issue with `jspm build test.js --production`, fix added in https://github.com/systemjs/builder/commit/bbf0e11c01df3750e6ece15539515bf7b1519546.

**Comment by jackfranklin** [comment]
Awesome, thank you!

**Comment by guybedford** [comment]
This should be working in the last release.
