### ISSUE TITLE
How to bundle with dev packages?

### ISSUE THREAD

**Issue by unional** [jspm/jspm-cli#1856]
I'm using `blue-tape` to write by test the the `tape-run` to run the test using the code below:

```js
const streams = require('stream');
const jspm = require('jspm');
const run = require('tape-run');
const reporter = require('tap-spec');

const testFileGlobs = process.argv[2] || "spec/**/*.ts";

new jspm.Builder()
  .buildStatic(testFileGlobs, { sourceMaps: 'inline' })
  .then((output) => {
    const reader = new streams.Readable();
    reader._read = function () { };
    reader.push(output.source);
    reader.push(null);
    reader
      .pipe(run())
      .pipe(reporter())
      .pipe(process.stdout)
      .on('results', (results) => {
        if (!results.ok) {
          process.exit(1);
        }
      });
  });
```

It is working in `beta.14` but in `beta.16` it fails with:
```sh
TypeScript transpiling to CommonJS, consider setting module: "system" in typescriptOptions to transpile directly to System.register format
Unhandled rejection Error on fetch for blue-tape at file:///E:/hwong/bitbucket/pandash/blue-tape
        Loading spec/array/composeMap.spec.ts
        Error: ENOENT: no such file or directory, open 'E:\hwong\bitbucket\pandash\blue-tape'
    at Error (native)
```

If I install `blue-tape` as dependencies (`jspm i npm:blue-tape`), then it works.

What should I put in the `buildStatic(..., option)` to tell it to bundle with dev packages?

The best solution is to not relying on bundle and load the files directly, much as in the `karma` workflow. But I couldn't find a way to do that with `tape`

**Comment by unional** [comment]
It is related to work from #1444

**Comment by guybedford** [comment]
What would be importing `blue-tape` here? Does `spec/array/composeMap.spec.ts` directly depend on `blue-tape`?

The builder runs more strictly without dev installs availabile with the dev configuration separation, so you can't have dev dependencies as dependencies of the build tree. You can only have dev dependencies used as build plugins rather.

If `blue-tape` is required by something you're building, then perhaps it isn't a dev dependency? Let me know if that makes sense, or what I'm missing here.

**Comment by unional** [comment]
This build step is to build the test code as a bundle to be feed into `tape-run`. 
Yes, the test code `.spec.ts` uses `blue-tape`.

**Comment by guybedford** [comment]
So effectively, this is a "development bundle"?

**Comment by guybedford** [comment]
Maybe what we can do is enable development configuration into the build when the `--dev` flag is set for bundling.

**Comment by unional** [comment]
Yes that would be great. 

It is the same tooling as in browerisfy. I would like to utilize jspm to its fullest in dev env, but the tool chain limits it. :(

**Comment by guybedford** [comment]
Sure, we can definitely do this. The hard part is just managing the configuration state because development configuration still needs to be isolated to not spill into production builds, so it requires the builder to maintain parallel environment-specific configurations, and using the right one depending on the trace options.

**Comment by guybedford** [comment]
Development configuration is now used in the builder environment by default.
