### ISSUE TITLE
Difference between jspm bundle, budlesfx and jspm build

### ISSUE THREAD

**Issue by tomeraz** [jspm/jspm-cli#1861]
I'm confused.
What's the difference and use cases for each:
1. jspm bundle
2. jspm bundle -sfx
3. jspm build

It would be great to write this on http://jspm.io/0.17-beta-guide/
Thanks!

**Comment by m-a-r-c-e-l-i-n-o** [comment]
@tomeraz I believe that `jspm build` is a shortcut for `jspm bundle-sfx`. They are both used to create a [self executing bundle](https://github.com/jspm/jspm-cli/blob/master/docs/production-workflows.md#creating-a-self-executing-bundle). The `jspm bundle` still requires you to load the config and system js files separately, which I find great for debugging. I would recommend using `jspm build` for client side production and node. While `jspm bundle` for client side development.

**Comment by abhipanda** [comment]
Can you close this ?

**Comment by tomeraz** [comment]
I'm sorry, it's still not clear.


Why do each of these options exist?

How can I decide when to use each?


Was the config created for debugging, aiming production to use without the config?

Should the config be avoided on production?

Then why use bundle sfx if you can use jspm build?




From: Abhi

Sent: Tuesday, May 31, 21:55

Subject: Re: [jspm/jspm-cli] Difference between jspm bundle, budlesfx and jspm build (#1861)

To: jspm/jspm-cli

Cc: tomeraz, Mention



Can you close this ?

**Comment by tomeraz** [comment]
@m-a-r-c-e-l-i-n-o, thanks for your help so far.
I managed to work with "jspm build", for a single huge build file.
Can you help me understand how to work with 2 builds?
I need to have 2 builds: app.js and vendor.js.
vendor.js should contain react, material-ui etc.
app.js contains my app code.
Inside app.js, modules should be able to write:
```
import React from 'react'
```
So I understand one build should be:
```
jspm build react + material-ui public/vendor.js -i
```
And second build should be:
```
jspm build client.js - react - material-ui public/app.js -i
```
When I load vendor.js and app.js in the browser, modules inside app.js do not import react and throw errors.
I couldn't figure out which System.Config({}) setting to use inside jspm.config.js in order for this to work.
Can you help?
Thanks!
