### ISSUE TITLE
d.ts dependencies in same folder are not recognized and parsed

### ISSUE THREAD

**Issue by PeterAronZentai** [jspm/jspm-cli#1862]
react-router's d.ts - (screenshot below) translates to invalid d.ts screenshot pasted
The dependency history.d.ts is not picked up from the same folder despite having a ///reference to it

![image](https://cloud.githubusercontent.com/assets/1798835/15628771/fdcf9066-2501-11e6-88e0-ccc8887ea8dc.png)

![image](https://cloud.githubusercontent.com/assets/1798835/15628780/244deb16-2502-11e6-856f-7276dae8b14f.png)

**Comment by aluanhaddad** [comment]
@PeterAronZentai you may want to raise this on definitelytyped or typings. I do not believe that jspm looks at .d.ts files to infer dependencies in any way. 

Furthermore those are not external module dependencies, they are Global references, and typings explicitly ignores them.

**Comment by PeterAronZentai** [comment]
@aluanhaddad thanks. thats what I need to do.

**Comment by aluanhaddad** [comment]
@PeterAronZentai glad I could help.
