### ISSUE TITLE
npm compatibility bug -- htmlparser2

### ISSUE THREAD

**Issue by joeldenning** [jspm/jspm-cli#1864]
The [`htmlparser2`](https://github.com/fb55/htmlparser2) npm library doesn't work when jspm installed because it `require`s directories, assuming that the directory path will turn into `directory/index.js` when `require`d. Seems like jspm/npm#40 is sort of related to this, except that in this case we're not talking about the main file in the package.json, but just dynamic requires happening inside of the source.

Also, it seems like once that problem is resolved that there might be another problem that prevents `htmlparser2` from being used in jspm: the `files` and `directories` configuration inside of htmlparser2's package.json is such that another error occurred for me. I don't have a stacktrace for that one because it happened a while ago, but let me know if that would be useful.

I have reproduced the problem on jspm@0.17.0-beta.16. Also, for reference, [here is my fork of htmlparser2](https://github.com/joeldenning/htmlparser2/commits/master) which has three commits that eventually get htmlparser2 to a point where jspm installing it actually works.

**Comment by joeldenning** [comment]
Also for reference, here are the places where htmlparser2 requires directories, assuming that the index.js file in that directory will be used:

https://github.com/fb55/htmlparser2/blob/master/lib/CollectingHandler.js#L8
https://github.com/fb55/htmlparser2/blob/master/lib/ProxyHandler.js#L7
https://github.com/fb55/htmlparser2/blob/master/lib/Stream.js#L17

**Comment by guybedford** [comment]
The issue here is actually https://github.com/systemjs/systemjs/issues/1164.

**Comment by joeldenning** [comment]
Awesome, I'll close in favor of that bug.
