### ISSUE TITLE
What's the best plan to map Paths with the new "Path" support from TypeScript 2.0

### ISSUE THREAD

**Issue by born2net** [jspm/jspm-cli#1867]
so the awesome TS 2.0 support Path mapping so we can get rid of node_modules.
I am wondering what's the best way to map all paths as I find myself needing to add an entry for each library now in tsconfig (all of a sudden tsconfig becomes the source of truths which seems wrong):

```
{
  "compilerOptions": {
    "target": "ES5",
    "inlineSources": true,
    "module": "system",
    "moduleResolution": "node",
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "noEmitHelpers": false,
    "sourceMap": true,
    "noResolve": false,
    "baseUrl": "./jspm_packages",
    "paths": {
      "angular2-redux-util": [
        "npm/angular2-redux-util@0.8.64"
      ],
      "angular2-google-maps/core": [
        "npm/angular2-google-maps@0.10.0/core"
      ],
      "@angular/*": [
        "npm/@angular/*@2.0.0-rc.1"
      ],
      "@angular/platform-browser/src/browser/browser_adapter": [
        "npm/@angular/platform-browser@2.0.0-rc.1/src/browser/browser_adapter"
      ],
      "rxjs/*": [
        "npm/rxjs@5.0.0-beta.6/*"
      ]
    }
  },
...
```

so as you can see for each lib, angular2-redux-util, rxjs etc I now need to map in tsconfig
so essentially you are replacing one evil (node_modules) with another evil (tsconfig) thus still needing to maintain 2 seperate configs for each lib.... rrrrr
is that best approach?

regards

Sean

**Comment by jakeNiemiec** [comment]
+1 Relevant: https://github.com/Microsoft/TypeScript/issues/6012

**Comment by guybedford** [comment]
//cc @frankwallis

**Comment by guybedford** [comment]
Yeah, it's a war of resolvers!
