### ISSUE TITLE
Is there a way to install packages without the version in the path?

### ISSUE THREAD

**Issue by canamo06** [jspm/jspm-cli#1868]
Right now I'm trying to migrate my code from requirejs to jspm/systemjs and I need to install packages but without the version in the path:

### Example:

    jspm install myrepo=github:org/myrepo -o "{ 'directories':{'lib': 'src'}, 'format' : 'amd' }"

It generates this folder tree :

    jspm_packages/github/org/myrepo@1.1.0

But I want **myrepo** instead of **myrepo@1.1.0**

    jspm_packages/github/org/myrepo/

### Why?

We are adding the version with hashes in the file name like: "src/unicorn.273c2cin.js", the hash is based on its contents. (using https://github.com/smysnk/gulp-rev-all). So we don't want the version in the package path, because if we updated or created a new version, systemjs will load all the package files again, the path version will change.

Example:

if we have:

	jspm_packages/github/org/myrepo@1.1.0/src/unicorn.273c2cin.js

And we release new version , but we didn't change that file.

	jspm_packages/github/org/myrepo@1.1.1/src/unicorn.273c2cin.js

The browser will load the file again, even if it is the same. 

We are preparing to use http2 without bundles... that's why we need the hashes at file level.

thanks!

**Comment by guybedford** [comment]
For file-level hashing, I think in future this kind of optimization may be possible at the transport level with eg service workers as opposed to using URLs.

jspm using versioned folders is a fixed assumption of the project though, which provides a solid caching base for use today.
