### ISSUE TITLE
b17 upgrade bundle issues

### ISSUE THREAD

**Issue by lookfirst** [jspm/jspm-cli#1873]
Upgraded from 0.17  b14 to b17 and now I'm getting this error during bundling. I don't really understand why things are looking in node_modules now...

```
Error tracing babel-runtime/helpers/createClass at file:///Users/beaker//hub/node_modules/babel-runtime/helpers/createClass.js
	Loading js/util/AuthService.js
	Loading js/sell/app.js
	Error: Unable to calculate canonical name to bundle file:///Users/beaker//hub/node_modules/babel-runtime/core-js/object/define-property. Ensure that this module sits within the baseURL or a wildcard path config.
  at getCanonicalNamePlain (/Users/beaker//hub/node_modules/jspm/node_modules/systemjs-builder/lib/utils.js:222:13)
  at getCanonicalName (/Users/beaker//hub/node_modules/jspm/node_modules/systemjs-builder/lib/utils.js:145:19)
  at /Users/beaker//hub/node_modules/jspm/node_modules/systemjs-builder/lib/trace.js:509:36
  at run (/Users/beaker//hub/node_modules/karma/node_modules/core-js/modules/es6.promise.js:89:22)
  at /Users/beaker//hub/node_modules/karma/node_modules/core-js/modules/es6.promise.js:102:28
  at flush (/Users/beaker//hub/node_modules/karma/node_modules/core-js/modules/_microtask.js:18:9)
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by guybedford** [comment]
When using Babel for transpilation, where `babel` is not otherwise configured by the build, SystemJS has a default to get `babel` from `path.resolve('babel')` in Node for convenience, which will then look in node_modules.

In the Babel plugin, we do a mapping of these automatically to use local helpers instead of `babel-runtime` to avoid this issue.

So I guess the question is how are you running Babel compilation here, through a custom build step of your own, or via the Babel plugin or legacy Babel layer of SystemJS?

**Comment by lookfirst** [comment]
My code is already babel compiled by the time that the buildStatic is processing it.

I use these options to first compile with babel (via my https://github.com/lookfirst/gulp-helpers project):

```
	plugins: ['transform-es2015-modules-systemjs', ['transform-runtime', { 'polyfill': false, 'regenerator': false }]]
```

Here is my buildStatic function call...

```
let bundler = (bundle) => {
	let builder = new Builder();
	return builder.buildStatic(`js/${bundle.name}/app`, `${path.war}/js/${bundle.name}/${bundle.name}-bundle.js`,
		{minify: bundle.minify, sourceMaps: false, uglify: {beautify: {ascii_only: true}}, runtime: false});
};
```

jspm.browser.js:

```
SystemJS.config({
  baseURL: "/",
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*",
    "js/": "js/"
  }
});
```

jspm.config.js: screenshot was easier: http://take.ms/s1Is5

**Comment by guybedford** [comment]
Your custom transform includes `transform-runtime` so would be creating the dependencies on `babel-runtime/helpers/createClass` etc here I think.

So it's just about ensuring the loader can find those. Perhaps it will be as simple as `jspm install babel-runtime`?

**Comment by lookfirst** [comment]
it is already in there as jspm devDependency within the package.json.

**Comment by guybedford** [comment]
Try `jspm install babel-runtime` as a non-dev dependency?

**Comment by lookfirst** [comment]
Ok, that solved the problem and things seem to be building again. =)

One question, why does my dependency on angular keep getting moved into the jspm peerDependencies (from the dependencies) section?

```
    "peerDependencies": {
      "angular": "github:angular/bower-angular@^1.5.6",
      "buffer": "github:jspm/nodelibs-buffer@^0.2.0-alpha",
      "fs": "github:jspm/nodelibs-fs@^0.2.0-alpha",
      "moment": "npm:moment@^2.13.0",
      "path": "github:jspm/nodelibs-path@^0.2.0-alpha",
      "process": "github:jspm/nodelibs-process@^0.2.0-alpha"
    },
```

I do have a single override that looks like this:

```
      "github:angular-slider/angularjs-slider@2.14.0": {
        "registry": "jspm",
        "dependencies": {
          "angular": "*"
        },
        "peerDependencies": {
          "angular": "*"
        },
        "main": "dist/rzslider",
        "meta": {
          "dist/rzslider.js": {
            "deps": [
              "angular"
            ],
            "format": "global"
          }
        }
      },
```

I have to have that or else I get this error:

```
err  Installing github:angular-slider/angularjs-slider@2.14.0, no version match for github:angular/bower-angular@^1.2.x
```

**Comment by guybedford** [comment]
peerDependencies override dependencies exactly because of that.

If you don't want that perhaps try just `peerDependencies: {}` or `peerDependencies: null` in the override.

**Comment by lookfirst** [comment]
It just seems weird that it gets moved by `jspm install` to be a peerDep when I specify it as a dep. I'd rather it just live as a dep and not be pushed around. I shouldn't have to make those changes in overrides just to get angular to live in the right place in the file.

**Comment by guybedford** [comment]
@lookfirst a peer dependency of an installed dependency becomes a top-level peer dependency in jspm. So the alternative would be for it to be both a peer dependency and a normal dependency.

**Comment by guybedford** [comment]
Let me know if you still need further assistance here at all.
