### ISSUE TITLE
announcement: angular 2 with jspm hot-reload project available

### ISSUE THREAD

**Issue by born2net** [jspm/jspm-cli#1874]
announcement: angular 2 with jspm hot-reload project available

just a quick announcement, if you love jspm and angular 2 be sure to checkout the awesomeness of hot-reload: https://github.com/born2net/ng2Boilerplate?v=3

**Comment by jakeNiemiec** [comment]
+1 - Works out of the box, extremely quick. Glad you could get it working. Do you use automatic file saving in Webstorm?

**Comment by born2net** [comment]
yes auto save , so cool!

**Comment by born2net** [comment]
FYI that's my next challenge: http://stackoverflow.com/questions/37578117/angular-2-trying-to-load-a-component-dynamically-getting-typeerror-cannot-re
