### ISSUE TITLE
jspm shim for globals does not work, works in config.js

### ISSUE THREAD

**Issue by maximnaidenov** [jspm/jspm-cli#1876]
Hi,
According https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm I want to define a shim that defines a global for my module. The global is the export of a cjs module. 
In my package.json I have: 
```
"overrides": {
      "github:robertbaker/angular-numbro@1.5.2": {
        "main": "src/angular-numbro.js",
        "format": "global",
        "shim": {
          "src/angular-numbro.js": {
              "deps": [
                "angular",
                "numbro"
              ],
              "globals": {
                  "numbro": "numbro"
              }
           }
        }
    }
}
```
But this way 'numbro' global is not available in angular-numbro. But if I have similar configuration in config.js the global is defined fine:
```
meta: {
    "github:robertbaker/angular-numbro@1.5.2/src/angular-numbro.js": {
        "globals": {
            "numbro": "numbro"
        }
    }
}
```
I use:
└─┬ jspm@0.16.2
  └── systemjs@0.18.17 

I prefer to have all overrides defined in package.json and have config.js fully generated.

**Comment by guybedford** [comment]
`globals` like the above is only supported in jspm 0.17-beta and for `meta` overrides (basically `meta` instead of `shim` in your example).
