### ISSUE TITLE
path.resolve is not a function when running mocha from jspm run

### ISSUE THREAD

**Issue by xiankai** [jspm/jspm-cli#1878]
I'm trying to setup a test suite with mocha and jspm, and ran into the following error:

1) `jspm install mocha`
2) edit `test.js`
```
var Mocha = require('mocha');
var mocha = new Mocha();
mocha.addFile('test.js');
mocha.run();
```
3) `jspm run ./test.js`
Then I get:
```
err  TypeError: path.resolve is not a function
      at /Users/kj/jspm-test/jspm_packages/npm/mocha@2.5.3/mocha.js:1358:17
      at Array.forEach (native)
      at Mocha.loadFiles (/Users/kj/jspm-test/jspm_packages/npm/mocha@2.5.3/mocha.js:1357:14)
      at Mocha.run (/Users/kj/jspm-test/jspm_packages/npm/mocha@2.5.3/mocha.js:1609:10)
      at Object.<anonymous> (/Users/kj/jspm-test/mocha.js:4:7)
      at /Users/kj/jspm-test/mocha.js:6:4
      at /Users/kj/jspm-test/mocha.js:7:3
      at Object.exports.runInThisContext (vm.js:54:17)
  Evaluating /Users/kj/jspm-test/mocha.js
  Error loading /Users/kj/jspm-test/mocha.js
```

Upon further inspection, `require('path')` produces a blank object inside `mocha.js`. However, it works inside `test.js` (after doing `jspm install path --edge`). For some reason mocha does not have access to the `path` node module?

**Comment by guybedford** [comment]
I was working on the Mocha override yesterday and it seems to be working pretty well now in 0.17. Make sure to do `jspm install mocha -o` to refresh the override from the jspm registry.

Unfortunately the `addFile` API in mocha isn't compatible with jspm as it will attempt to do a `require('test.js')` synchronous require which isn't supported in SystemJS giving this error:

```
Error: Module /Users/guybedford/Projects/jspm-cli/sandbox/test.js not declared as a dependency of /Users/guybedford/Projects/jspm-cli/sandbox/jspm_packages/npm/mocha@2.5.3/lib/mocha.js
      at /Users/guybedford/Projects/jspm-cli/sandbox/jspm_packages/npm/mocha@2.5.3/lib/mocha.js:220:27
```

The way I would suggest using Mocha is via eg:

```javascript
import Mocha from 'mocha';

SystemJS.import('./tests.js')
.then(function(tests) {
  var runner = new Mocha({
    ui: 'exports',
    reporter: typeof window != 'undefined' ? 'html' : 'spec'
  });

  runner.suite.emit('require', tests);

  runner.run();
})
.catch(console.error.bind(console));
```
