### ISSUE TITLE
JSPM is pulling the minified version of React even when NODE_ENV=development

### ISSUE THREAD

**Issue by conor909** [jspm/jspm-cli#1879]
I'm trying to work `draft-js` library with `react`, but jspm is pulling the minified versions of libraries instead of unminified so I'm getting the following error: 
`invariant.js`:`13`
`Uncaught Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.` 

I'v tried setting my `NODE_ENV` to `development` but it doesn't help.  Im on `"jspm": "^0.16.11"`

**Comment by guybedford** [comment]
Perhaps try jspm 0.17 here as it has better support for React?

**Comment by conor909** [comment]
I'm trying to upgrade, but I'm getting the following warning and error: 
`warning.js:45Warning: require('react/addons') is deprecated. Access using require('react-addons-{addon}') instead.`

`system.js:4 Uncaught (in promise) Error: TypeError: Cannot read property 'mark' of undefined(…)`

**Comment by HeinrichFilter** [comment]
@conor909 are you using [Enzyme](https://github.com/airbnb/enzyme) or any other lib that supports React 0.13?

I had this problem with Enzyme and added the following override in my package.json
```
"jspm": {
  "overrides": {
      "npm:enzyme@2.2.0": {
        "map": {
          "react/addons": "@empty",
          "react/lib/ReactContext": "@empty",
          "react/lib/ExecutionEnvironment": "@empty"
        }
      }
    }
}
```
To understand why, you can have a look at this Enzyme code as an example:
https://github.com/airbnb/enzyme/blob/master/src/react-compat.js#L17-23

JSPM doesn't understand the `if (REACT013)` conditional when parsing the files for dependencies. Therefore, JSPM tries to import `'react/addons'` even though that code will never be reached at runtime. 

Adding the `@empty` override solves that problem.

**Comment by conor909** [comment]
Thanks for the reply @HeinrichFilter, I'm not using Enzyme and I'm not sure how to find out which dependency is using older react versions.  How did you know that Enzyme was the one giving you trouble?

**Comment by HeinrichFilter** [comment]
@conor909 Unfortunately, I can't remember exactly how I found the problem (it's been a while since I had this problem).

But for now, the easiest would probably be to do a text search for `react/addons` in your `jspm_packages` directory and see which libraries come up.

**Comment by guybedford** [comment]
It may help to share the expanded loads list from `system.js:4 Uncaught (in promise) Error: TypeError: Cannot read property 'mark' of undefined(…)` after clicing the `...` part.

**Comment by conor909** [comment]
I'v had to change my `baseUrl` paths and the path in my index `System.import`, but I'v got 1 remaining dependency which wont load:

`system.src.js`:`5112` 
`GET http://localhost/jspm_packages/npm/babel-runtime@6.9.2.json 404 (Not Found)`

```javascript
package.json
src/
├── jspm_packages
├── jspm.browser.js
├── jspm.config.js
├── index.html
```

**Comment by guybedford** [comment]
Uhh, that is a different error now though? Which error am I helping with?

**Comment by conor909** [comment]
I'm loosing track of the errors too.  From my experience in the last 3 working days I wouldn't advise anyone to upgrade to `jspm 0.17`.  It's just one error after another.  Possibly all of my problems are fixed since [#1889](https://github.com/jspm/jspm-cli/issues/1889) just got fixed, but I'v given up.  I still think my original issue (the title of this issue) is still a problem on the current stable.  I'm using `jspm 0.16.36`.

**Comment by guybedford** [comment]
@conor909 happy to help further, but I do need to have a specific issue and replication to work with.

**Comment by jackfranklin** [comment]
@conor909 can you get the repo with jspm 0.17 online? I'd happily try to take a look if you'd like a second pair of eyes.

>  From my experience in the last 3 working days I wouldn't advise anyone to upgrade to jspm 0.17. It's just one error after another.

In my experience I've found jspm 0.17 to be pretty smooth; I'm sure it's a matter of fixing a small piece of config that jspm might have got wrong when it first installed.

You could also try removing the `jspm_packages` folder and `jspm install` again, along with `jspm dl-loader` to get the latest SystemJS.

**Comment by conor909** [comment]
I believe the issue was because I was unlucky enough to be trying to install while #1889 was an issue but I had to move on since then

**Comment by stonebraker** [comment]
I've faced this issue a few times and have determined it to occur when including a bundle and using System.import() instead of System.load().

So this:
```
<script src="jspm_packages/system.js"></script>
<script src="config.js"></script>
<script src="dist/bundle.js"></script>
<script>
	System.import('src/app.js');
</script>

```
Produces this error:
```
system.js:4 Uncaught (in promise) Error: (SystemJS) Invariant Violation: Minified React error #37; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=37 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

While the following works as expected:
```
<script src="jspm_packages/system.js"></script>
<script src="config.js"></script>
<script src="dist/bundle.js"></script>
<script>
	System.load('src/app.js');
</script>
```

I looked for an explanation of the difference between `load()` and `import()` in in the docs, but saw no mention of `load()`, so I can't offer an explanation of why this is.

Point of note: the above bundles were created using `jspm bundle` and not `jspm bundle-sfx`. Using bundle-sfx results in this error as well, but I'll raise that as a different issue.

**Comment by guybedford** [comment]
Load is non executing, so it won't actually run the code.
