### ISSUE TITLE
 Specifiy html files as bundle dependencies

### ISSUE THREAD

**Issue by djflex68** [jspm/jspm-cli#1881]
The structure of my app is : 
- app
  - config.js
  - main.js
  - views (html)
  - viewmodels (.js)
  - ...

The underlying SPA framework I use (Durandal) is using a rooter that dynamically loads views and viewmodels when they're navigated to.
On production, I'm trying to bundle all files inclusive html files (using text loader plugin). To do that I type :
`jspm bundle app/main + app/viewmodels/**/*.js + app/views/**/*.html out.js`

As result, viewmodels (.js) files are correctly integrated into my build, but html files aren't. 
In config.js, I tried to define into meta variable :
`"*.html": { "loader": "text" },`

But this doesn't help. What am I missing ? 
The only solution I see, would be to create a "fake" js file, that requires all html views, but I think it's not the best solution...

Thanks for your help

**Comment by guybedford** [comment]
Are you loading the HTML files using plugin syntax (`import 'x.html!'`) or plugins via configuration (`import 'x.html'`)?

If using plugin syntax, the bundle command should be `jspm bundle app/main + app/vewmodels/**/*.js + app/views/**/*.html! out.js`.

**Comment by djflex68** [comment]
Tried this but I get :
`err  Error: ENOENT: no such file or directory, open 'D:\(...)\www\dist\html.js'`

I'm not requiring directly html files from code using `import 'x.html!'`, html files are required dynamically by Durandal's composition mechanism with something like `System.import(moduleName+ 'html!';`

**Comment by guybedford** [comment]
The html fetch failure sounds like it is due to the html plugin not being available by name. You want the `!html` part to be `!path/to/html/plugin.js`.

It may also be worth using aurelias bundling mechanisms otherwise if this is too much hard work as well.

**Comment by djflex68** [comment]
> The html fetch failure sounds like it is due to the html plugin not being available by name. You want the !html part to be !path/to/html/plugin.js.

I'm not sure about this. What should I try ? Is there a specific config to try in config.js ?

**Comment by guybedford** [comment]
There is an html plugin installed at some location, you should see `'html': '...'` somewhere in the jspm configuration file. So you want to copy that `...` into the bundle command - `jspm bundle app/main + app/viewmodels/**/*.js + app/views/**/*.html!<...> out.js`, where `<...>` is substituted here. Again, using standard bundling workflows for Aurelia will probably be a better bet though.

**Comment by djflex68** [comment]
I already tried this solution before, which gave the following result :
```
jspm bundle index.html!jspm_packages/github/systemjs/plugin-text@0.0.8/text.js out.js

Building the bundle tree for index.html!jspm_packages/github/systemjs/plugin-text@0.0.8/text.js...

err  Error on translate for index.html!github:systemjs/plugin-text@0.0.8/text.js at file:///(...)/www/dist/index.html!file:///(...)/www/dist/jspm_packages/github/systemjs/plugin-text@0.0.8/text.js
        Error: ENOENT: no such file or directory, open 'D:\(...)\www\dist\none.js'
            at Error (native)
        Error loading D:(..)/www/dist/none.js
```

I just don't get where the "none.js" file comes from

**Comment by guybedford** [comment]
Very odd, I have no idea where `none.js` is coming from either.

**Comment by djflex68** [comment]
Okay I will keep investigating, thanks for support anyway ;-)

**Comment by MaximBalaganskiy** [comment]
@djflex68 Did you figure out where `none.js` comes from? I'm having the same issue when bundling aurelia app directly with `jspm bundle`

**Comment by aluanhaddad** [comment]
Didn't `"none"` use to mean no transpiler in old configs? I remember getting this error long time ago because transpiler was set to `"none"` instead of `false`.
Have you tried loading your templates with meta config? It would be interesting to see if that makes a difference.
