### ISSUE TITLE
[Feature proposal] jspm doctor

### ISSUE THREAD

**Issue by jakeNiemiec** [jspm/jspm-cli#1883]
The purpose would be to detect potential issues and gotchas with users system or project that could prevent the 'SystemJS ecosystem' (jspm / SystemJS / es6-module-loader) from working correctly. There [already seems to be some of this](https://github.com/jspm/jspm-cli/blob/0.17/lib/config/loader.js#L280) when `jspm install` is run. Inspired by something like [yoman doctor](https://github.com/yeoman/doctor), this could also provide useful output for diagnosing problems that cannot be solved programmatically. Jsm

Granted, easier said than done; this has the potential to cut down on gitter/github questions by provide customized solutions to common problems, and provide a standardized output that other users can use to diagnose a problem.

**Comment by guybedford** [comment]
This is definitely a great concept. Is this something you were interested in working on? Let me know if you want to discuss ideas at all further.

**Comment by jakeNiemiec** [comment]
I would love to contribute work at some point. Right now, I am still acclimating myself to jspm /systemjs as a whole. I will be making note of things I run into that can be solved in this way; the problem that prompted this issue was having incompatible versions of jspm & systemjs (I'm not entirely sure how I managed that).

**Comment by DavidStrada** [comment]
I would like to help you on this task, also still wrapping my head around jspm/systemjs as a whole.

**Comment by guybedford** [comment]
I think the best way to approach this would be as a third-party project. If there is anything in the jspm API itself that can be opened up to provide better integration with such a tool I'll gladly discuss work on API extensions.

**Comment by jakeNiemiec** [comment]
Thanks, feel free to close this.
