### ISSUE TITLE
Specifying a different path for bundle

### ISSUE THREAD

**Issue by siulung4073** [jspm/jspm-cli#1885]
Hi there, I'm having an issue  with the way I have my project configured, and I dont know how to fix it and if its possible.

app folder: `./src/client/app`
tmp folder: `./tmp/client/app`
Jspm folder is on root: `./jspm_packages`
config on root: `./config.js`
server public folder: `./dist/server/public/app`

For dev I have a gulp task that compiles everything to `.tmp` and then to `dist`.

For prod I compile to `.tmp` and then bundle from there. Which it works but every path gets the prefix `./tmp/client/app/...`, instead of `app/...`

For what I read, this is because of the `baseUrl` on `package.json`, which I dont use, since `jspm_packages` is on root.

I know I can fix this with a custom path in the config like this: `".tmp/client/app/*": "app/*"`

But everything since kinda weird.

Is there a better way to override the relative path used in the `System.registerDynamic` ?

thanks!

**Comment by siulung4073** [comment]
I wanted to comment something, adding the path config, doesn't work, since it tries to look for files in `./app`

All I want is to change `System.registerDynamic(".tmp/client/app/..."`, to `System.registerDynamic("app/..."`

**Comment by guybedford** [comment]
This is exactly handled via paths configuration at build time:

```javascript
paths: {
  'app/': '.tmp/client/app/'
}
```

**Comment by siulung4073** [comment]
That works as expected. I feel kinda dump because I thought I tried that and didn't work.

Thanks again for the time

**Comment by guybedford** [comment]
👍 it's a common catch, because this is badly documented... working on it!

**Comment by siulung4073** [comment]
I just have another question, what about if I want a different paht config
for dev?
because the one I config is for prod.
thanks

**Comment by guybedford** [comment]
Yes paths configurations are environment-specific, usually you'll want to set paths per-environment using custom code or eg using `System.config({ devConfig: { paths: {...} } })`.
