### ISSUE TITLE
can jspm fix npm's bad behavior

### ISSUE THREAD

**Issue by adriatic** [jspm/jspm-cli#1886]
Many times each day I am seeing warning's like
```
λ npm install && jspm install                                                                
npm WARN deprecated conventional-changelog@0.0.11: Please update conventional-changelog to >1
.0.0. If you are running the cli, use conventional-changelog-cli                             
npm WARN deprecated babel-core@5.8.3: Babel 5 is no longer being maintained. Upgrade to Babel
 6.                                                                                          
npm WARN deprecated line-numbers@0.2.0: Copy its ~20 LOC directly into your code instead.    
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releas
es >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs'
 to find it in the tree.                                                                     
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4
.0.0.                                                                                        
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releas
es >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs'
 to find it in the tree.                                                                     
npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3
.0.0.                                                                                        
```

Admittedly, this is npm's problem and there should be a way to address all these WARNs without finding the owner of each module that references too old versions of other modules. So, I am asking Guy how realistic is tool that would scan the whole tree and create an usable "report" that human would use to report all these issues to all affected modules?

**Comment by guybedford** [comment]
This is happening in the npm tree not the jspm one, so it's part of npm tooling certainly.

Usually the `npm ls graceful-fs` approach works pretty well though.

Closing as it's not a jspm issue, but happy to discuss further.

**Comment by adriatic** [comment]
> Closing as it's not a jspm issue, but happy to discuss further.

I knew that from the getgo :-) but I believe that there are some chances to make life for folks that use npm via jspm a bit easier. This would of course require that jspm is able to apply some additional intelligence when invoking npm. Assuming that this is a possibility, I would like to talk some more, thanks for offering that :-)
