### ISSUE TITLE
Lodash toString not found

### ISSUE THREAD

**Issue by Ignavia** [jspm/jspm-cli#1887]
After installing Lodash Version 4.13.1 with JSPM 0.17.0-beta.17 and opening the page in the browser I get the following error:

`GET http://localhost:8080/jspm_packages/npm/lodash@4.13.1/toString 404 (Not Found)`

Apparently the path is missing the .js extension. This is the content of the lodash@4.13.1.json file in jspm_packages:

```
{
  "main": "lodash.js",
  "format": "cjs",
  "meta": {
    "*.json": {
      "format": "json"
    },
    "core.js": {
      "format": "amd"
    },
    "core.min.js": {
      "format": "amd"
    },
    "isBuffer.js": {
      "globals": {
        "Buffer": "buffer/global"
      }
    },
    "lodash.js": {
      "format": "amd"
    },
    "lodash.min.js": {
      "format": "amd"
    },
    "toString": true,
    "valueOf": true
  }
}
```

It works fine after manually removing the toString and valueOf properties.

**Comment by guybedford** [comment]
You need to make sure you're running the latest version of jspm-npm here. It should be at least 0.28.13 when using `npm ls jspm-npm`. If that is correct try `jspm install lodash -f` to clear the package cache.

**Comment by Ignavia** [comment]
Clearing the cache fixed it. Thank you.
