### ISSUE TITLE
nested imports?

### ISSUE THREAD

**Issue by trusktr** [jspm/jspm-cli#1888]
@benjamin has enabled the following feature in Meteor:

https://www.reddit.com/r/javascript/comments/4m5f03/meteor_133_introduces_nested_import_statements_if/

The Meteor user-base is wide, which presents a nice opportunity for the feature to be widely tested. What are your thoughts on SystemJS/JSPM supporting nested imports so that more people can try out nested imports?

(I myself love the idea, so far. I always dislike the thought of having to switch from `import` syntax to some functional syntax (CommonJS, SystemJS), and feel that staying within the ES6 `import` language makes everything feel super nice.)

**Comment by aluanhaddad** [comment]
Since modules are loaded asynchronously, wouldn't this require some sort of implicit `await` style transformation? I suppose another alternative would be to hoist the imports to the top of the module, but that would seem to defeat the purpose of the idea is presented by the linked article.

**Comment by guybedford** [comment]
@trusktr thanks for sharing. This feature will be supported and is planned to be supported... we're just waiting on the specification for it.
