### ISSUE TITLE
Loading jQuery using sfx-bundles in one module overwrites the main version in the page. 

### ISSUE THREAD

**Issue by tcorral** [jspm/jspm-cli#1890]
In my project to create our widget bundles we are using:

jspm - jspm-cli
As they are widgets we want our code as isolated as possible, so we use jspm sfx bundles that you can create using:

jspm bundle-sfx scripts/main dist/main.js
The problem is that if this packages doesn't add a define or require to the global and when jQuery wants to export itself it decides that needs to be on the global.

Overwriting the jQuery we have in the page we have a lot of issues.

I have created a ticket also in jQuery to solve this problem: https://github.com/jquery/jquery/issues/3145

Link to test case

https://jsfiddle.net/aptm7qxy/1/

If we use Webpack Dev Server it doesn't happens:

https://jsfiddle.net/2xua7b98/

**Comment by guybedford** [comment]
If you'd rather not have jQuery overwrite the global jQuery version, try running jQuery as an AMD module:

```javascript
System.config({
    meta: {
    'npm:jquery@2.2.4/dist/jquery.js': {
      format: 'cjs'
    }
  }
});
```

**Comment by tcorral** [comment]
Should I modify the config.js file to do that?

I have checked that and it only happens with jQuery's version 2.x.

It doesn't happens with version 1.x or 3.x

**Comment by tcorral** [comment]
Ok. That's solves the problem. Thanks.
