### ISSUE TITLE
jspm install keep config paths

### ISSUE THREAD

**Issue by xhallix** [jspm/jspm-cli#1891]
Hi,

I found several issues and threads but none is helping me here.
Is there an ***easy*** way to do `jspm install` without having the `paths` node in `config.js` overwritten?

Thanks

**Comment by guybedford** [comment]
I'd suggest using jspm 0.17, as it contains a much more fine-grained configuration system.

**Comment by xhallix** [comment]
ahh cool, will definitly taken a look at this :) 

:+1:
