### ISSUE TITLE
Bootstrap V4 + Dependencies, How to ? ( example repo created ).

### ISSUE THREAD

**Issue by DavidStrada** [jspm/jspm-cli#1892]
Hi, How can i declare or overwrite a jspm install to do the following : 

1. Install Boostrap 4 + it's dependencies 
  - jQuery 
  - Tether 

Tether has been the mayor pain point on this combination see [example](https://github.com/DavidStrada/boostrap4_jspm_cli_v0.17.0-beta.17).

When `import bootstrap from "bootstrap";` it complains about tether not being available or present.

``` javascript
import $ from "jquery";
import tether from "tether";
import bootstrap from "bootstrap";


console.log( bootstrap, $, tether);
```

If you need extra clarifications do let me know,
Thanks.

**Comment by jakeNiemiec** [comment]
[Does this work?](https://github.com/DavidStrada/boostrap4_jspm_cli_v0.17.0-beta.17/pull/1/files)

**Comment by DavidStrada** [comment]
Yes it does.!

Thanks,
David

**Comment by DavidStrada** [comment]
After hours of work finally works --> If anyone interested here's the [repo](https://github.com/DavidStrada/boostrap4_jspm_cli_v0.17.0-beta.17)

**Comment by jakeNiemiec** [comment]
@DavidStrada Btw, your title is 2spooky4me.
![image](https://cloud.githubusercontent.com/assets/16782063/15934451/4150cf28-2e29-11e6-98c2-c4438426f7c6.png)

**Comment by DavidStrada** [comment]
@jakeNiemiec haha It was a long name :) fixed the typo tho.

**Comment by guybedford** [comment]
Do we need to update the Bootstrap override here in the registry?

**Comment by jakeNiemiec** [comment]
@guybedford I think that [bootstrap4's repo](https://github.com/twbs/bootstrap/tree/v4-dev) just might be [**configured wrong**](https://github.com/twbs/bootstrap/blob/v4-dev/package.json#L88).

Compare what npm gives you from `npm install bootstrap@4.0.0-alpha.2` (via [their install instructions](http://v4-alpha.getbootstrap.com/getting-started/download/#package-managers))

![image](https://cloud.githubusercontent.com/assets/16782063/15952249/e52f64f0-2e84-11e6-804d-4c8ef66d4694.png)
(the scss folder is full)

What jspm gives you from `jspm install npm:bootstrap@4.0.0-alpha.2`
![image](https://cloud.githubusercontent.com/assets/16782063/15952329/53064048-2e85-11e6-8e12-0c92e299d36e.png)
As you can see, jspm is working how it was intended.

**Comment by DavidStrada** [comment]
@guybedford Yes we need to do overwrite the registry, the problem raises when you want to work or modify css, you don't want the compiled version ".css" you want `sass` directory in, so you can use it either by symlinking the scss or manually importing the bootstrap.scss onto your own directory.

So in other words Include the all package just like we ( @jakeNiemiec  ) did, and if someone wants the compile version they can easily access it by referencing "dist" folder/directory.

**Comment by frederikschubert** [comment]
My [PR](https://github.com/jspm/registry/pull/903) would fix that problem but would be a breaking change.

**Comment by DavidStrada** [comment]
I wouldn't be to worry about breaking change, given the following reason : 

- Right now it's pretty messed up, you need to do a lot config in order for it to work properly.
- We are in beta so breaking changes are expected.
- If not now when ?

**Comment by frederikschubert** [comment]
I would also like the change to be merged, but I guess its up to @guybedford to decide.

**Comment by DavidStrada** [comment]
If he hasn't experienced these pain points is because he is not using it, so i guess doing it wouldn't be a problem. That's my perspective tho.

**Comment by jakeNiemiec** [comment]
@frederikschubert wouldn't your PR break (as things are now), because the directories.lib is set in the package.json for the bootstrap4 repo?

**Comment by frederikschubert** [comment]
I am not sure what you mean. Do you think the override should look different than my PR?

**Comment by jakeNiemiec** [comment]
I believe so. The directories.lib is set here https://github.com/twbs/bootstrap/blob/v4-dev/package.json#L88

If you remove it in the override, I think that it will set directories.lib according to package.json. According to what David has said, we need so thing like `"lib": "."`, but I feel that we could reach a nuanced approach that could match npm's behavior (what bootstrap expects the end user to work with).

**Comment by frederikschubert** [comment]
Ah ok. Yes that makes sense! Will update the PR to include `"lib": "."` till we find something better.

**Comment by guybedford** [comment]
Yeah we really need to sort this out. Overrides are owned by the community, it just needs someone to champion this stuff.

Breaking an override is a big issue for jspm 0.16. In 0.17 overrides can break as they are checked in. Override changes can be backwards compatible though, it is only the directories.lib change that is a breaking override change.

It does sound like we do need to alter directories.lib for bootstrap here though.

The alternative is setting up a `npm:bootstrap` override for the beta release branch. That can then be breaking as it is a different package in jspm, and we can switch `jspm install bootstrap` to alias `npm:bootstrap` as registry location changes are allowed like this.

So it's just about setting up that override and merging it. If anyone is able to work on this, I'm more than happy to discuss further and give feedback.

**Comment by guybedford** [comment]
PR at https://github.com/jspm/registry/pull/912 thanks to @frederikschubert. Help reviewing this override is very welcome here too.
