### ISSUE TITLE
bundle without some ES6 transformations

### ISSUE THREAD

**Issue by arackaf** [jspm/jspm-cli#1893]
Apologies if this isn't the right place to post; I'm not sure if this belongs here, or in the systemjs-builder repo.

Is it possible to bundle ES6 modules, but without some transformations?  For example, if all of your target environments support ES6 `class` and destructuring, is it possible to let those ES6 features through, un-transpiled when making bundles?  

I'm guessing there's probably a place to list out the babel transformations you *want* / *don't* want?

**Comment by guybedford** [comment]
This would be options for the Babel plugin, which are grouped by stage (https://github.com/systemjs/plugin-babel/blob/master/plugin-babel.js#L40).

For example, to turn off all ES2015 compilation, leaving just the stage proposals, you can do:

```javascript
System.config({
  babelOptions: {
    es2015: false
  }
});
```

Because environment support is changing, these are quite course options, so batching by ES year seems like it might work going forward. For finer-grained support, Babel plugins can always be applied individually (eg turning everything off, then installing just the plugins you want). Let me know what you think might work for you here.

**Comment by arackaf** [comment]
Thank you so much for the reply.

With all major desktop browsers being fully ES6 compatible, and mobile ones getting there, I think we're close to being able to ship native (and much smaller, and potentially more performant) ES6 code, with transpiled fallback versions for IE and such.  The biggest bottleneck at the moment seems to be UglifyJS2, whose harmony branch is still in work.

To answer your question, yes, the ability to manually add in individual transforms would be incredibly useful.  So I could switch off ES2015, but add in ES6 modules, object spread, etc.

So from your answer above, am I correct in assuming that I can pass that same `babelOptions` object to your builder like so?

```
let builder = new Builder('../' + baseDirectory);
builder.config(configToUse); //where configToUse has babelOptions
```

How would I do that with jspm?  How would I go about making more than 1 pass on the same set of bundles, with different transpilation settings?  I imagine some other things may need to be changed with jspm for that to be possible, since I believe the jspm bundle call modifies the config files in place, adding the bundles paths.  I imagine the ad hoc managing of those paths I do (with just SystemJS-builder and some manual code), putting them together at runtime, from the right source directory based on the user's browser isn't really feasible at the moment.

**Comment by guybedford** [comment]
Yes that would all be fine. Custom plugins can be passed already via `babelOptions: { plugins: ['jspm-module-name-for-plugin'] }`. babelOptions can be at the base-level like `builder.config({ babelOptions: {...} })` or they can also be metadata:

```javascript
builder.config({
  meta: {
    'app/es/*.js': {
      babelOptions: { presets: ['preset-just-for-this-folder'] }
    }
  }
});
```

In jspm we provide `var Builder = require('jspm').Builder` for its builder API here.

**Comment by arackaf** [comment]
Wow - it looks like this is all covered. Thank you so much for the info!

**Comment by arackaf** [comment]
The one last transpilation I've been curious about for awhile now - these SystemJS transpilation settings - do they / can they affect the client-side download of all the babel "stuff."  The delay is pretty noticeable on each refresh.

**Comment by guybedford** [comment]
We use a single build of Babel with its plugins. We could potentially separate this out into two builds, but the issue here is that there are a lot of shared dependencies between the plugins and Babel itself. The logical conclusion down this road is just to go back to a `jspm install babel --dev`, which was way slower. So I guess not.

**Comment by arackaf** [comment]
I can see any number of problems with providing for a lot of customization in that file.  I just wonder if a small, but useful subset would be possible.  Would it be feasible to let users opt into a babel file that *only* does ES6 modules; and maybe one other option that only does ES6 modules, JSX, and object spread?  

ie let users opt into a minimal build to dev against with Chrome: one for React devs, and one for everyone else.

**Comment by arackaf** [comment]
By the way, I'd be happy to code up a PR for you if you think this is a worthwhile objective, though I'd need some instruction on what needs to change and where.

**Comment by guybedford** [comment]
Good point - in the case where all transforms are disabled it would be possible to use a pure Babel build.

You could probably do this yourself via:

minimal-babel-wrapper.js
```javascript
import babel from 'babel-core';
export {babel};
```

```
jspm install babel-core --dev
jspm build minimal-babel-wrapper.js systemjs-build-minimal.js
```

And then update the config file at `jspm_packages/npm/plugin-babel@0.0.12.json` so that the `map` entry for the Babel build points to the local file `systemjs-build-minimal.js`.

If that works out ok, we could do a PR into the main project where the build itself is dynamically loaded with a `System.import` inside the translate hook, and then when all options are set to false it loads a different build file instead.

**Comment by arackaf** [comment]
I will investigate soon and get back to you!

**Comment by arackaf** [comment]
One preliminary question: are es6 modules baked into babel-core, or would I need to add them to the minimal-babel-wrapper above?

**Comment by guybedford** [comment]
It is separate, so yes I think you're right that would need to be included. It's here in the wrapper we use for building the plugin Babel version - https://github.com/systemjs/plugin-babel/blob/master/build-babel/systemjs-babel.js#L4

**Comment by arackaf** [comment]
Sorry to be so helpless - I'm afraid I didn't get too terribly far.  I tried making the build references above - I called it modern-babel-package since it would be used to dev against modern js engines, like Chrome.

The repo is here, https://github.com/arackaf/jspm-configuration-sandbox.git and I added you as a collaborator.  Even with just a bare 

```
import babel from 'babel-core';
export {babel};
```

I'm getting the error above.  I tried also adding the ES6 module transform, which generates the same error. 

> Creating the single-file build for modern-babel-package.js...
err  Error: Synchronous conditional normalization not supported sync normalizing ./process.js in file:///c:/GIT/jspm-configuration-sandbox/jspm_packages/github/jspm/nodelibs-process@0.2.0-alpha
    at doMapSync (C:\Program Files\nodejs\node_modules\jspm\node_modules\systemjs\dist\system.src.js:2296:13)
    at applyPackageConfigSync (C:\Program Files\nodejs\node_modules\jspm\node_modules\systemjs\dist\system.src.js:2267:22)
    at SystemJSNodeLoader.<anonymous> (C:\Program Files\nodejs\node_modules\jspm\node_modules\systemjs\dist\system.src.js:2497:14)
    at SystemJSNodeLoader.normalizeSync (C:\Program Files\nodejs\node_modules\jspm\node_modules\systemjs\dist\system.src.js:4423:30)
    at SystemJSNodeLoader.loader.normalizeSync (C:\Program Files\nodejs\node_modules\jspm\node_modules\systemjs-builder\lib\builder.js:223:42)
    at C:\Program Files\nodejs\node_modules\jspm\node_modules\systemjs-builder\lib\utils.js:86:50
    at Array.forEach (native)
    at getAlias (C:\Program Files\nodejs\node_modules\jspm\node_modules\systemjs-builder\lib\utils.js:81:27)
    at C:\Program Files\nodejs\node_modules\jspm\node_modules\systemjs-builder\lib\rollup.js:221:19
    at Array.map (native)
    at C:\Program Files\nodejs\node_modules\jspm\node_modules\systemjs-builder\lib\rollup.js:220:38
    at Array.map (native)
    at exports.rollupTree (C:\Program Files\nodejs\node_modules\jspm\node_modules\systemjs-builder\lib\rollup.js:210:62)
    at C:\Program Files\nodejs\node_modules\jspm\node_modules\systemjs-builder\lib\builder.js:702:14
    at tryCatcher (C:\Program Files\nodejs\node_modules\jspm\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\jspm\node_modules\bluebird\js\release\promise.js:502:31)

**Comment by arackaf** [comment]
Also, possibly related, I'm not seeing any plugin-babel@0.0.12.json.

![image](https://cloud.githubusercontent.com/assets/11261266/15988489/7257b460-3018-11e6-8b16-315980629349.png)

**Comment by guybedford** [comment]
If you compare to the original wrapper I made a typo - it's import * as
babel from 'babel' not the default import as Babel uses __esModule flag on
its cjs output. I think that may be the issue?

**Comment by guybedford** [comment]
And systemjs-plugin-babel I guess?

**Comment by guybedford** [comment]
Argh, this could also be a regression in the latest beta actually...

**Comment by guybedford** [comment]
@arackaf this was exactly a regression on the latest... I've published a new release and thanks for catching it!!

**Comment by arackaf** [comment]
I'm thinking this idea won't work.  As you said, transforms depend on other things, and that appears to be the problem.  My file is this:

```
import * as babel from 'babel';
import modulesRegisterPlugin from 'babel-plugin-transform-es2015-modules-systemjs';

export let modulesRegister = {
    plugins: [modulesRegisterPlugin]
};

export { babel };
```

Which builds out to a whopping 790KB - somehow *larger* than the existing `systemjs-babel-browser.js file`.

Removing the references to `babel-plugin-transform-es2015-modules-systemjs` drops the file down to like 7KB.

It's checked into the branch `custom-babel-build-ES6Modules-only` in the repo above, which you have access to if you want to take a look.

That said, it appears React is the real delay, so I'll take a closer look there—maybe pre-bundling React, and I know you have some info on that very topic in the jspm docs.

**Comment by arackaf** [comment]
Of course, the other option might be to provide Buble as an option.  Not sure how hard that is to run from the browser, though it does appear jsx support is minimal at the moment - maybe in a few months some more robust options will exist :)

**Comment by arackaf** [comment]
@guybedford thank you for your help here.  It looks like pre-bundling all the React items only works if you include `babel-plugin-transform-react-jsx` along with react and react-dom, which brings the bundle to about 1,200KB.  Like I said, hopefully there'll be some bubble-like tools here in the future which would match this use case well.

I'm hoping you can help me understand one thing, though.  Making individual bundles of `react` and `react-dom`, ie

`jspm bundle react-dom react-dom-only-bundle.js` and `jspm bundle react react-only-bundle.js`

Results in bundles 95KB for react, and 471 for react-dom, unminified, of course.  The dist files those packages ship with from npm are 654KB and 2KB, respectively (unminified).  Can you help me understand why the jspm bundles are so radically off (either way bigger, or way smaller)?

**Comment by guybedford** [comment]
@arackaf with React it is worth noting that there are development and production builds of the tree, which will account to size difference. By default jspm will build for the production environment, unless explicitly building or bundling with the `--dev` flag.

It could be possible to build `babel-plugin-trasnform-react-jsx` via `jspm build` along with the Babel file, instead of `jspm bundle`, by making React and React-DOM externals, so that only React is bundled. Similarly a static build of React like you would get from CDN may be quicker too.

**Comment by tamird** [comment]
@guybedford in https://github.com/jspm/jspm-cli/issues/918 it was suggested that the env would get inlined as "production" only on minified builds, but I am observing that behaviour in all builds. Is that intended?

Is there any way to get the non-production behaviour before 0.17?

**Comment by guybedford** [comment]
@tamird these are two separate things - (1) the CommonJS-only `process.env.NODE_ENV == production` optimization for CommonJS modules that only applies for minfication (2) the ability for conditional loads in the tree to apply removal of non-production conditional nodes.

That all said we probably need to add the exclusions for React actually like we did for React 0.14 in https://github.com/jspm/registry/blob/master/package-overrides/npm/react%400.14.6.json, which allows these production environment to remove the development modules.

**Comment by arackaf** [comment]
@guybedford re-visiting this - any idea why react-dom would be building so huge?  Do you suppose other things are getting included by accident?

**Comment by guybedford** [comment]
@arackaf React and ReactDOM do not seem to be configured for bundling production-only dependencies in jspm I think? As they were for 0.14 in https://github.com/jspm/registry/blob/master/package-overrides/npm/react%400.14.6.json. I think it's just about going through and fixing up the override here.

**Comment by arackaf** [comment]
Thanks for the reply.  Honestly I'm just trying to understand what's going on here.  React-dom's dist is only 2KB - jspm just walks the path from index.js (or main in package.json) and just scoops everything up, right?  Isn't that what many people have Webpack do when making dist builds?  I'm just trying to understand what jspm is picking up (and there's a lot of it) that doesn't belong there.  

Are there a ton of helpers that are also contained in React that the react-dom's build step is just manually configured to exclude?

**Comment by guybedford** [comment]
@arackaf ReactDOM is doing - `module.exports = require('react/lib/ReactDOM');` so it's pulling in all of React. In React's build it changes this to `require('react').__SECRET_DOM_DO_NOT_USE_OR_YOU_WILL_BE_FIRED`.

So it's the difference between the two approaches I think - basically how the internals are shared as there are a lot of cross-loads within the trees.

Basically it's probably advisable to always build React and ReactDOM together... or use Facebooks existing dist builds. Let me know if that makes sense / answers your questions here?

**Comment by arackaf** [comment]
It does, and I appreciate you taking the time.
