### ISSUE TITLE
peerDependencies to dependencies

### ISSUE THREAD

**Issue by unional** [jspm/jspm-cli#1895]
I was using `aurellia-dependency-injection` which uses `aurelia-metadata`, so the `package.json` look like this:

```js
{
  "jspm": {
    "dependencies": {
      "aurelia-dependency-injection": "..."
      ...
    },
    "peerDependencies": {
      "aurelia-metadata": "..."
    }
  }
}
```

Now I also use `aurelia-metadata` directly, so I run `jspm i npm:aurelia-metadata`:

However jspm detect it is a peer dependency and install it as is:
```sh
> jspm i npm:aurelia-metadata
     Updating registry cache...
ok   Peer aurelia-metadata to npm:aurelia-metadata@^1.0.0-beta.1.2.1 (1.0.0-beta.1.2.1)
     Install tree has no forks.

ok   Install complete.
```

and the `package.json` does not change.

How to tell jspm to change `aurelia-metadata` from `peerDependencies` to `dependencies` beside manually editing `package.json`?

Using `jspm@0.17.0-beta.17`

**Comment by unional** [comment]
UPDATE:
Manually changing `package.json` doesn't work, after `jspm i`, jspm moves it back to `peerDependencies`.

I had problem installing that package once, the error is something like:
```sh
...not a file or directory: .../jspm_packages/npm/aurelia-metadata@.../.jspm-hash ...
```

I don't have the exact error because I run it in VSCode's terminal and close it accidentally.
When I run it again it seems to be fine.

So if the above situation is "as designed", please close this issue. 🌷

**Comment by guybedford** [comment]
This has to do with install order. Running `jspm install -f` may well return the peerDependencies value.

Typically when something is a peerDependency already, installing it will not create a "duplicate" `dependencies` entry, as the peerDependency property dominates.

The alternative would be to allow a dependency to be both a peerDependency and a dependency if that makes more intuitive sense.

**Comment by unional** [comment]
> This has to do with install order.

That would lead to transitive or non-deterministric outcome, IMO

> Typically when something is a peerDependency already, installing it will not create a "duplicate" dependencies entry

If I recall correctly, if a `devDepencencies` is installed (as normal dependency), it will move from `devDepenencies` to `dependencies`  (or at least this is what `typings` would do. :smile:)
Would jspm consider the same mechanism (and or `peerDependencies`)?

> The alternative would be to allow a dependency to be both a peerDependency and a dependency

How to do that?

**Comment by guybedford** [comment]
Moving from devDependencies to dependencies is moving to the more dominant install form, without loss. Moving from peerDependencies to dependencies would be the reverse unfortunately. There is no big difference between peerDependencies and dependencies to the project itself, only for packages installing the package with these properties.
