### ISSUE TITLE
0.17.0-beta.17: TypeScript with AMD and globals

### ISSUE THREAD

**Issue by OliverJAsh** [jspm/jspm-cli#1898]
I want to use jspm to write a TypeScript application which consists of ES6, AMD, and globals.

When loading from the bundle, SystemJS throws an error:

``` ts
import es6 from './es6.ts';
import amd from './amd.ts';
import global from './global.ts';

console.log(es6, amd, global);
```

```
Uncaught (in promise) Error: ReferenceError: define is not defined(…)
```

Here is my project: https://gist.github.com/OliverJAsh/a1d5e9feb6b0d8ccaae51ac77ab290f4

It appears that the bundle process is not detecting the AMD module in `amd.ts`:

``` js
System.register("module-test/amd.ts", [], function(exports_1, context_1) {
  "use strict";
  var __moduleName = context_1 && context_1.id;
  return {
    setters: [],
    execute: function() {
      define(function() {
        return 'amd';
      });
    }
  };
});
```

If I take away the AMD module and try to import a global, I get `undefined` back from the import.

**Comment by guybedford** [comment]
Created https://github.com/frankwallis/plugin-typescript/issues/138. Also caught https://github.com/jspm/jspm-cli/commit/229359325cc4d83a3e83841d2c1e4f9adfae0e95 in the process so thanks for that. Let's track at the TypeScript plugin issue.

**Comment by OliverJAsh** [comment]
I'm not sure how https://github.com/frankwallis/plugin-typescript/issues/138 relates to this issue. When that is fixed, will my issue above also be fixed?

**Comment by guybedford** [comment]
@OliverJAsh loading a TypeScript-written AMD module instead of only ES6 is exactly something that the plugin-typescript project needs to support itself, so I've just tried to repost this there. Perhaps clarifying the issue there if I've missed anything would help.

**Comment by frankwallis** [comment]
@OliverJAsh is the amd module actually typescript or just javascript?

**Comment by OliverJAsh** [comment]
TypeScript but could be either!

**Comment by frankwallis** [comment]
I think this is probably happening because the plugin tells SystemJS what the output format is (based on the ```module``` tsconfig option. See https://github.com/frankwallis/plugin-typescript/blob/master/src/plugin.ts#L47:

```
         if (host.options.module === ts.ModuleKind.System)
            load.metadata.format = 'register';
         else if (host.options.module === ts.ModuleKind.ES6)
            load.metadata.format = 'esm';
         else if (host.options.module === ts.ModuleKind.CommonJS)
            load.metadata.format = 'cjs';
```

I think the solution would be to remove that code and let SystemJS automatically detect the output. Could you try commenting out that code in the plugin and see if that resolves it?
