### ISSUE TITLE
Install hooks

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#1899]
An idea for supporting hooks:

``` json
{
  "jspm": {
    "hooks": {
      "preinstall": "./hooks/preinstall.js"
    }
  }
}
```

Where we load the module `./hooks/preinstall.js` and run the default export function with some arguments to run the hook.

Hooks would only be supported in the package doing the install - hooks in installed packages would not run for security reasons.

The set of hooks and arguments should be determined here.

**Comment by guybedford** [comment]
Note that above effectively allows an ecosystem of hooks via:

```
jspm install custom-jspm-hook --dev
```

```json
{
  "jspm": {
    "hooks": {
      "preinstall": "custom-jspm-hook"
    }
  }
}
```

**Comment by frederikschubert** [comment]
This proposal would fit our use case quiet well!

**Comment by aluanhaddad** [comment]
Is this still being considered? I have a node cli tool which attempts to install specifically versioned TypeScript declaration files based on the state of `jspm.config.js` after an install and I would like to make it part of my build process.

**Comment by WorldMaker** [comment]
I have similar but subtly different use case as well: some of the packages I install were built with Typescript themselves and their npm packages and/or github projects include a `tsconfig.json` file. Visual Studio tries to recurse the project folder for all `tsconfig.json` files and build them, resulting in build errors from the `jspm_packages` directly even if I trying to tell VS to ignore that directory. It would be nice if jspm didn't install those files at all (some sort of install file ignore) or I could hook a cleanup process post-install.

**Comment by aluanhaddad** [comment]
@WorldMaker There should be a way to exclude these files in your root tsconfig.json. If not I would file an issue at [Microsoft/TypeScript](//github.com/Microsoft/TypeScript/). The information in these tsconfig.json files is often helpful and I would hate to see them ignored by default.

**Comment by WorldMaker** [comment]
@aluanhaddad They are definitely excluded in the top level tsconfig and Typescript has no issue with it; it just seems to be VS trying to be more helpful than is actually helpful.

**Comment by aluanhaddad** [comment]
What version of VS and what version of TypeScript Tools are you using?

**Comment by WorldMaker** [comment]
@aluanhaddad VS2015 and every version of TS Tools I've come across so far as I can tell, including the just released one that coincides with TS 2.0. I have an exclude for the jspm_packages directory in all of my top level tsconfig.json files and if JSPM installs a tsconfig.json with a package: VS tries to build it, creates errors listed under "TypeScript Virtual Projects", and fails builds. It's become habit at this point that if build errors show up under jspm_packages to `rm -recurse tsconfig.json`.

**Comment by aluanhaddad** [comment]
Yeah, this behavior is annoying. It is one of the reasons I don't use Visual Studio for TypeScript these days. It should be better in the next version of VS which will use the TypeScript language service directly.

**Comment by frederikschubert** [comment]
@guybedford I would like to implement this.
I will start with the `preinstall` and `postinstall` hooks as those are the most common ones.
