### ISSUE TITLE
Local configuration support

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#190]
It should be possible to have a `.jspmconfig` or similar file in the current project directory, which overrides the global jspm configuration.

This is useful for project-specific credentials / settings.

When running `jspm config`, it would be useful to set the level of setting with `jspm config --local` for setting local config.

**Contribution Steps:**
1. Alter the global config loading code at https://github.com/jspm/jspm-cli/blob/master/lib/global-config.js#L41 to also check for a local `.jspmconfig` file in the current folder (taken to be `process.env.jspmConfigPath || process.cwd()`).
2. Have this local config override the local config
3. Add an option to `jspm config` and `jspm endpoint` (https://github.com/jspm/jspm-cli/blob/master/cli.js#L470, https://github.com/jspm/jspm-cli/blob/master/cli.js#L410) for a `--local` flag to indicate that the [global config save function](https://github.com/jspm/jspm-cli/blob/master/lib/global-config.js#L35) should save the new changes to this local file. Some type of tracking code would be needed to ensure we save just those properties which have been changed.

**Testing:**
- I should be able to do `jspm endpoint create custom jspm-github --local` and create a custom GitHub endpoint that I can see in my local `.jspmconfig` file only and not in `~/.jspm/config`
- I should be able to do `jspm config custom.property value --local` and see my `.jspmconfig` file have this property added, but not `.jspmconfig`.

**Comment by djindjic** [comment]
is there some workaround (for travisci)? something like:

jspm endpoint config github --username=MY_USERNAME --token=MY_TOKEN

**Comment by guybedford** [comment]
@djindjic yes, look at your local `~/.jspm/config` file and you'll see your github auth string.

Then write:

```
  jspm config endpoints.github.auth AUTH_STRING
```

**Comment by djindjic** [comment]
thanks!

**Comment by andreasgrimm** [comment]
(sorry if too obvious) for public repos use the travis cli tool and `travis encrypt 'GH_TOKEN=g5489ugh9...` your github auth token and include it like this in your .travis.yml file:
```yml
env:
  global:
  - secure: "HJJH9889JK......"

before_install:
- npm install -g jspm ...
- jspm config endpoints.github.auth $GH_TOKEN
```

**Comment by djindjic** [comment]
thanks @andreasgrimm, and thanks for sharing your [jspm ng-next-example](https://github.com/ng-next/ng-next-example) sample.
if you are interested you can also take a look to my js lib [yeaman generator](https://github.com/djindjic/generator-jspm-lib) with [jspm-sample.tk](https://github.com/djindjic/jspm-sample.tk) examples focused to travis-sauce testing and npm/divshot deploying with jspm projects.

**Comment by guybedford** [comment]
Thanks @andreasgrimm I've included this note in the wiki - https://github.com/jspm/jspm-cli/wiki/Endpoints#travis-ci.

**Comment by andreasgrimm** [comment]
awesome, thanks @djindjic for mentioning.
I'll have a deeper look into these during the next couple of days I guess.

**Comment by Zoltu** [comment]
The link provided with details appears to be dead.  :/

**Comment by guybedford** [comment]
We should also look at supporting an algorithm like https://github.com/jspm/jspm-cli/issues/729 for the lookup here.

**Comment by shannonmoeller** [comment]
Thanks, @guybedford ! I'm excited to see some traction on the `.config/` idea.

**Comment by glen-84** [comment]
Will JSPM get its own configuration file, instead of using package.json? (like jspm.json)[1]

If you wanted to "include" values from package.json, bower.json, or any other JSON file, you could do something like:

```json
{
    "include": [
        "../package.json",
        "bower.json"
    ],
    "name": "MyPackage"
}
```

The name `MyPackage` would override the name in the two included files.

The JSPM configuration itself (timeouts, etc.) could be placed in the same file, under a `config` key.

Also, +1 for the idea by @shannonmoeller. I wish that the NPM devs were more open to change ([1](https://github.com/npm/npm/issues/8159), [2](https://github.com/npm/npm/issues/8222)).

***

[1] Sadly, it's not likely that we'll get away from using JSON for configuration files any time soon.

**Comment by hmps** [comment]
@guybedford, I've been working on a PR for this. Given that this thread is rather old I would just like to check in with you to see if there are any cli commands that has been added that need to support local config. Except for `endpoint` becoming `registry` that is. :)

**Comment by shukriadams** [comment]
/bump

Has there been any movement on this implementation? It would still be extremely useful to have.
