### ISSUE TITLE
jspm install fails on circle ci

### ISSUE THREAD

**Issue by tamird** [jspm/jspm-cli#1902]
This appears to be the same issue as https://github.com/meteor/meteor/issues/4566

The relevant comment from that issue is https://github.com/meteor/meteor/issues/4566#issuecomment-156453715, which explains that this is due to node-tar not supporting GNU tar's `--no-same-owner`. That feature request is tracked in https://github.com/npm/node-tar/issues/39.

**Comment by guybedford** [comment]
Thanks for reporting and tracking it down, I'll leave this up here then.

**Comment by JohnnyEstilles** [comment]
Any update on this issue? npm/node-tar#39 seems to be fixed now.

**Comment by guybedford** [comment]
@JohnnyEstilles thanks for the update. A PR would be welcome to add this option to https://github.com/jspm/npm/blob/master/lib/npm.js#L405 for 0.16 or 0.17 if you're able to test it out?

**Comment by JohnnyEstilles** [comment]
Definitely! I'll submit a PR soon.
