### ISSUE TITLE
Duplicate SystemJS.config() in config.jspm.js

### ISSUE THREAD

**Issue by mrhyde** [jspm/jspm-cli#1908]
I'm trying to dive into jspm@0.17 and it's just keep hitting me with questionable code and solutions...
For example in 0.16 in config file we had one `System.config()` call, but in 0.17 there is now two of them after `jspm init`

```js
SystemJS.config({        ## <--------- FIRST
  browserConfig: {
    'baseURL': '/',
    'paths': {
      'npm:': 'assets/scripts/jspm_packages/npm/',
      'playground/': 'assets/scripts/'
    }
  },
  nodeConfig: {
    'paths': {
      'npm:': 'temp/jspm_packages/npm/',
      'playground/': 'source/scripts/'
    }
  },
  devConfig: {
    'map': {
      'plugin-babel': 'npm:systemjs-plugin-babel@0.0.12'
    }
  },
  transpiler: 'plugin-babel',
  packages: {            ## <------------ LOCAL PACKAGES
    'playground': {
      'main': 'main.js',
      'format': 'esm',
      'meta': {
        '*.js': {
          'loader': 'plugin-babel'
        }
      }
    }
  }
})

SystemJS.config({        ## <------------ SECOND
  packageConfigPaths: [
    'npm:@*/*.json',
    'npm:*.json'
  ],
  map: {},
  packages: {}           ## <----------- REMOTE PACKAGES (npm, github)
})
```

**Comment by guybedford** [comment]
This was to make it easier to distinguish what is user-config and automatically managed dependency configuration, but I'm also not 100% sure about it yet either.

**Comment by frederikschubert** [comment]
I like this behavior. But I guess it would be good to insert a comment for the generated config part that states that this part is automatically generated.

**Comment by ArmorDarks** [comment]
@guybedford Maybe it would be better to keep issue open then for now?
