### ISSUE TITLE
Differences between jspm.Builer and systemjs-builder

### ISSUE THREAD

**Issue by micaelmbagira** [jspm/jspm-cli#1909]
I am confused by some issues that happen or not depending the use of `require('jspm').Builder` or `require('systemjs-builder`). All the steps below only happen when using **Babel** (not if I use ES5 or Typescript).
With Angular 1, if I use `const Builder = require('systemjs-builder');` it works but if I use `const Builder = require('jspm').Builder;` I have
> TypeError: null: Cannot read property 'replace' of null
    at module.exports (webapp3/node_modules/slash/index.js:10:12)
    at Object.shouldIgnore (webapp3/node_modules/babel-core/lib/util.js:174:34)
    at File.shouldIgnore (webapp3/node_modules/babel-core/lib/transformation/file/index.js:609:17)
    at File.wrap (webapp3/node_modules/babel-core/lib/transformation/file/index.js:560:16)
    at Pipeline.transform (webapp3/node_modules/babel-core/lib/transformation/pipeline.js:47:17)
    at Object.exports.compile (webapp3/node_modules/systemjs-builder/compilers/esm.js:114:22)
    at webapp3/node_modules/systemjs-builder/lib/compile.js:117:43

Also, I can make it work if I pass `{rollup: false}` to `builder.buildStatic(...)`.

With Angular2, if I use `const Builder = require('jspm').Builder;` I have no problem but if I use `const Builder = require('systemjs-builder')`, I have 
> Error on translate for src/index.js at webapp2/src/index.js
	(SystemJS) Error: ENOENT: no such file or directory, open '/Users/micael/Documents/zenika/sandbox/webapp2/babel-generator'
	    at Error (native)
	Error loading webapp2/babel-generator as "babel-generator" from webapp2/jspm_packages/npm/babel-plugin-angular2-annotations@5.1.0/lib/index.js

and my config is 

```js
  const builder = new Builder('./', 'jspm.config.js');
  builder.config({
    paths: {
      "github:*": "jspm_packages/github/*",
      "npm:*": "jspm_packages/npm/*"
    },
    packageConfigPaths: [
      'npm:@*/*.json',
      'npm:*.json',
      'github:*/*.json'
    ]
  });
  builder.buildStatic(
    src/index.js,
    tmp/index.js
  ).then(() => done(), done);
```

**Comment by guybedford** [comment]
It's generally advisable to use `require('jspm').Builder` as it will do all the correct jspm configuration for you. Options changes will lead to build differences.
