### ISSUE TITLE
0.16.39 / 0.17.0-beta.22 - __moduleName/module.id not usable with bundle-sfx / build

### ISSUE THREAD

**Issue by frederikschubert** [jspm/jspm-cli#1913]
When creating a self-executing bundle, the module names are no longer the path to the files (for example `npm:angular2@2.0.0-beta.15/core.js`), but some random identifier like `32f`.
Because the `__moduleName` (system format) and the `module.id` (commonjs format) variables depend on that name, they cannot be used anymore in a sfx-bundle.
Here is the code that breaks:
```typescript
var __moduleName = context_1 && context_1.id;
```
When using plain bundling, the module names stay the same.

I haven't tried the 0.17 behavior, but will try to do that soon.

**Comment by guybedford** [comment]
Building with `--skip-encode-names` can make it work out. This is an area that needs some more work though.

**Comment by frederikschubert** [comment]
Ah I didn't know that option. :)
Though I would rather have this as the default behavior because the functioning of the code is more important than saving those few bytes.
I think an option to enable the encoding would be better. Also this way jspm could issue a warning that this option prevents the usage of `module.id` and `__moduleName`?

**Comment by frederikschubert** [comment]
I tried using the option you suggested and it does indeed prevent the encoding. However `__moduleName` is still undefined because `context_1` is now a string that contains the name of the module.

**Comment by guybedford** [comment]
@frederikschubert make sure you are running the latest version of the transpiler in use (babel plugin / typescript plugin etc).

**Comment by frederikschubert** [comment]
Sorry for the late reply.
I have now also tested it with `jspm@0.17.0-beta.22` and `plugin-typescript@5.0.8`.
It's the same behavior. When using the command
```
jspm build --skip-rollup www/bootstrap.ts www/app.js
```
the module name is assigned to `context_1` as a string and thus `__moduleName = context_1 && context_1.id` is undefined.

**Comment by guybedford** [comment]
Sure, thanks, fixed in https://github.com/systemjs/builder/commit/cb94933ecf504f9069f9437d53d3c0c7193c5148.

**Comment by frederikschubert** [comment]
Great! 👍  I look forward to the next beta release!
