### ISSUE TITLE
[0.17-beta.21] Bundling doesn't pick up new modules

### ISSUE THREAD

**Issue by jackfranklin** [jspm/jspm-cli#1914]
If you're running `jspm bundle foo -wid` and install a new package you have to restart the bundle for it to pick up the package. It would be great if this could be avoided, although I realise this could be a little bit tricky.

**Comment by guybedford** [comment]
Thanks, this can actually be implemented relatively simply by just ensuring the configuration file is being watched. This is item 2 in https://github.com/jspm/jspm-cli/issues/1789.

**Comment by jackfranklin** [comment]
@guybedford sounds like it might be one I could take a  stab at...

**Comment by guybedford** [comment]
Sure, that would be welcome! It's the path at config.package.configFile to
add to the watch list, including checking if configFileBrowser etc also
exist.

**Comment by jackfranklin** [comment]
@guybedford I started doing this but then the issue is that I think `jspm bundle` touches `jspm.config.js` everytime, and hence it just infinitely rebuilds constantly. I'm thinking I need to do a check in the code when the file changed is a config file, and actually `require` it and see if any of the bits we care about have changed (aka, anything other than the `browserConfig.bundles` mapping) ?

**Comment by jackfranklin** [comment]
Except we can't require the config and check what changed because they aren't JSON / exporting a config. How can I get around this?

**Comment by guybedford** [comment]
Ahh ok. I'd stick with the original method but perhaps a flag can be used
to ignore configuration change file events during the reinjection process
itself?

**Comment by jackfranklin** [comment]
@guybedford I opened #1916 which has my attempts so far.
