### ISSUE TITLE
Private JSPM Registry and Repository

### ISSUE THREAD

**Issue by kanivenk** [jspm/jspm-cli#1917]
We wanted to host JSPM Registry and Repository on one of our web servers ( preferably IIS ) and then change jspm config to point to this registry and repository.

We didn't find any samples , approaches on this.

Any help on this is greatly appreciated.

**Comment by guybedford** [comment]
If you're referring to the jspm registry naming service, that is explained in https://github.com/jspm/jspm-cli/blob/master/docs/registries.md#creating-a-private-jspm-registry.

If you want to use a private registry endpoint, there are various options here. If you're looking for `jspm install company:package` style management, that could be implemented through the registry API. It would definitely be nice though if there was a simple registry handler that could make these out of say standard git URL construction or something similar.

**Comment by kanivenk** [comment]
Sorry for not giving the details in my previous request.. This is what exactly we are looking for .. we want to use our privately hosted registries for github and jspm. we want to host these registries in CDN style web server instead of using GitHub Enterprise.
The below is the sample config that we wanted to make it work.
  "registries": {
    "github": {
      "handler": "jspm-github",
      "remote": "https://github.jspm.io",
      **"storageLocation" :  "https://<<`hosting server`>>/jspmrepo/"**
    },
    "npm": {
      "handler": "jspm-npm",
      "remote": "https://npm.jspm.io"
    },
    "jspm": {
      "handler": "jspm-registry",
      "remote": "https://registry.jspm.io",
      **"repo": "https://<<`hosting server`>>/jspmregistry/.git"**
    }

**Comment by guybedford** [comment]
The registry can be set in that way, following the private registry configuration instructions above.

The jspm-github and jspm-npm repos can be set to download from remotes via perhaps using something like jspm-git (https://github.com/Orbs/jspm-git).

Let me know if you need further help with either of those.

**Comment by guybedford** [comment]
The repo for jspm-registry must be a git repo containing a registry.json - `http://server/jspm/registry/registry.git` or just `http://server/jspm/registry` I think?

**Comment by kanivenk** [comment]
We did "git init" and then added files and committed to git repo and now git clone is working fine. but once we do jspm install the loader files are not generated in jspm_packages\github\systemjs\ folder. 
the are files are in  jspm_packages\github\jspm but not in jspm_packages\github\systemjs.

**Comment by guybedford** [comment]
Are you referring to jspm_packages/system.src.js?

**Comment by kanivenk** [comment]
I am referring to the files that will be created in these folders when we do jspm install. we see files in \jspm_packages\github\jspm and in \jspm_packages\github\components folder but these files are not in \jspm_packages\github\systemjs folder 

\jspm_packages\github\systemjs
plugin-json@0.1.0.js
plugin-text@0.0.4.js
plugin-css@0.1.20.js

\jspm_packages\github\jspm
nodelibs-path@0.1.0.js
nodelibs-module@0.1.0.js
nodelibs-fs@0.1.2.js

\jspm_packages\github\components
jquery@1.11.3.js

**Comment by guybedford** [comment]
Those files are created when the main entry point configuration is set. So it sounds like perhaps your custom registry isn't providing the package configuration data with the main back to jspm?

**Comment by kanivenk** [comment]
I see its giving some warning on this package..
warn Main entry point not found for github:systemjs/plugin-json@0.1.0.
     Adjust this property in the package.json or with an override, setting "main
": false if this is the intention.

do we have to specifically set this property? or its because our custom github handler unable to download some files from our custom github repository?

**Comment by guybedford** [comment]
The handler is responsible for returning the package configuration in `getPackageConfig` or `download`. If there is no `getPackageConfig` and the download method returns `undefined` then it should automatically use the package.json in jspm 0.16 though.

**Comment by kanivenk** [comment]
ok. but these package configuration files are generated dynamically or it just downloads the static files from repository? I am just trying to see if we missed any files in our custom repository.

**Comment by guybedford** [comment]
It's just the package.json file.

**Comment by kanivenk** [comment]
Thanks for the hint.. this helped us to fix the problem that's not downloading some of the files. now we see package.json is getting downloaded from repo but still the .js files are not created in systemjs folder..

\jspm_packages\github\systemjs
plugin-css@0.1.20
plugin-json@0.1.0
plugin-text@0.0.4

\jspm_packages\github\components
**jquery@1.11.3.js**
jquery@1.11.3

\jspm_packages\github\jspm
nodelibs-buffer@0.1.0
**nodelibs-buffer@0.1.0.js**
nodelibs-http@1.7.1
**nodelibs-http@1.7.1.js**

Are we missing any other configuration?

**Comment by guybedford** [comment]
@kanivenk do you have a getPackageConfig method in your API, and is your download method returning anything? Both of those will act as the source of truth for package.json if provided.

**Comment by guybedford** [comment]
(That is either ensure they are undefined, or that you are returning the package.json contents manually)

**Comment by kanivenk** [comment]
we don't have getPackageConfig in our API but we do have download method and I see the Package.Json file in \.jspm\packages\github\systemjs\plugin-css@0.1.20 folder with the below content..

{
  "main": "css",
  "registry": "jspm"
}

but we don't see .js files in .jspm\packages\github\systemjs folder.

**Comment by guybedford** [comment]
What does the download method return? Make sure it returns undefined.

**Comment by kanivenk** [comment]
This is how the download function looks like..

download: function (repo, version, hash, meta, outDir) {
        return new Promise(function (resolve, reject) {
            getPackageFiles(repo, version, function (resp) {
                if (!resp) {
                    reject();
                }
                var data = JSON.parse(resp);
                var pjson = "";
                
                for (var i in data.files) {
                        var options = {
                        };
                        var packageName = ""
                        var fileName = ""
                        
                        fsextra.outputFileSyncfileName , '');
                        //download                                     
                        var stream = request(options);
                        var writeStream = fs.createWriteStream(fileName );
			//write file
                        stream.pipe(writeStream);
                        
                        if (data.files[i].indexOf("package.json") > -1) {
                            pjson = data.files[i];
                        }
                    };
                resolve(readPackageJSON(pjson));

            });

        });
    },

**Comment by guybedford** [comment]
If you've verified that the resolved value is the correct package.json JSON
object then it should be using that configuration correctly. Perhaps verify
it has the 'main' set (npm defaults to index which needs to be implemented
too for a custom registry like this)

**Comment by kanivenk** [comment]
my confusion here is its creating those .js files successfully for \jspm_packages\github\components and \jspm_packages\github\jspm but not creating for \jspm_packages\github\systemjs.

**Comment by guybedford** [comment]
Does the systemjs folder have a main in the package json?

**Comment by kanivenk** [comment]
I only see the following folders and files in **.jspm\packages\github\systemjs** folder..

plugin-css@0.1.20.deps.json   - this file just has "{}"    
plugin-json@0.1.0.deps.json  - this file just has "{}"    
plugin-text@0.0.4.deps.json  - this file just has "{}"    
plugin-css@0.1.20
plugin-json@0.1.0
plugin-text@0.0.4

**Comment by guybedford** [comment]
I'd really just suggest simple debugging here - stick a console.log at the end of your download hook. Log the name of the package, and the main value of the package json configuration you are returning. Make sure to use the `-f` flag with jspm install to ensure you're not using the cached version.

If you can 100% confirm the above is returning a main for eg plugin-css but not using it, then we can proceed further and debugging this as a jspm bug.

**Comment by kanivenk** [comment]
getting the following warning when we do jspm install but I see **{  "main": "css",   "registry": "jspm" }** in plugin-css package json file which is downloaded from server.

warn Main entry point not found for github:systemjs/plugin-css@0.1.20.
     Adjust this property in the package.json or with an override, setting "main
": false if this is the intention.

**Comment by guybedford** [comment]
Does changing the main to `css.js` help?

**Comment by kanivenk** [comment]
We are stuck with "err  Error: EPERM: operation not permitted, lstat" error when doing jspm install. we still have to make the  `css.js`  change in main and test. trying to resolve the "err  Error: EPERM: operation not permitted, lstat" error for now.
