### ISSUE TITLE
Caret dependency not being respected by jspm-cli

### ISSUE THREAD

**Issue by davismj** [jspm/jspm-cli#1918]
When installing Semantic-UI, jQuery@3.0.0 is installed even though [the dependency is specified as @^2.1.4](https://github.com/Semantic-Org/Semantic-UI/blob/master/package.json#L80). 

I originally opened this as an issue on the Semantic-UI repo ([here](https://github.com/Semantic-Org/Semantic-UI/issues/4126)) until I reviewed their `package.json` and found that they had correctly specified their dependency.

**Comment by guybedford** [comment]
I think we have a jspm override applying here in https://github.com/jspm/registry/blob/master/package-overrides/github/Semantic-Org/Semantic-UI%402.0.4.json. Happy to take a PR to change that back to the `2` version.
