### ISSUE TITLE
How to not use babel-preset-es2015?

### ISSUE THREAD

**Issue by jackfranklin** [jspm/jspm-cli#1920]
This is probably a documentation one (that I'm happy to provide), but is it possible to configure Babel to not do the ES2015 transpilation by default? If I'm working in just Chrome for example I'm in a fortunate position where I don't need to bother with any transpilation.

**Comment by jackfranklin** [comment]
And of course the moment I open this issue I realise I looked in the wrong place...

https://github.com/systemjs/plugin-babel#es-features.

Sorry!

**Comment by guybedford** [comment]
Glad you found it!
