### ISSUE TITLE
TypeScript + rollup => es5 bundle?

### ISSUE THREAD

**Issue by sod** [jspm/jspm-cli#1921]
Version: jspm 0.17.0-beta.22

I did a typescript rollup build test. For rollup to work with typescript I have to set https://github.com/sod/jspm-rollup/blob/master/jspm.config.js#L3

```
  typescriptOptions: {
    "target": "es2015"
  },
```

That works, but I end up with a bundle that only runs in es2015 compatible browsers. Is there a switch to convert the bundle to es5? Or should I just postprocess the bundle via babel myself?

**Comment by sod** [comment]
Nevermind, found https://github.com/Microsoft/TypeScript/issues/6319 and related tickets that you are on it 👍

**Comment by sod** [comment]
Aaaaand typescript just merged support for output "everything es5 + es6 modules" 🎉 

https://github.com/Microsoft/TypeScript/pull/9042

**Comment by guybedford** [comment]
Thanks for the update! Automatic support is tracking in https://github.com/frankwallis/plugin-typescript/issues/97.
