### ISSUE TITLE
jspm bundle doesn't use root package's map config

### ISSUE THREAD

**Issue by mwhite** [jspm/jspm-cli#1922]
This is an issue with map config for vendorized dependencies:

```json
// package.json
{  
  "jspm": {
    "map": {
      "foo": "vendor/foo"
    }
  }
}
```

```
$ jspm bundle 'foo' output.js
     Building the bundle tree for foo...

err  Error on fetch for foo.js at file:///path/to/package/foo.js
	Error: ENOENT, open '/path/to/package/foo.js'

```

**Comment by mwhite** [comment]
Probably an error on my part.  Will re-open if not. Sorry.

**Comment by guybedford** [comment]
Map config goes in the js configuration file not the package.json. It can be tricky to know what is used where certainly I know though. Better docs are needed too.

**Comment by mwhite** [comment]
Sorry about that.  I was assuming it would be copied from package.json to config.js, before I had looked in config.js when introducing SystemJS to a new project after not having needed map config before.
