### ISSUE TITLE
jspm dl-loader --latest changed ts to babel

### ISSUE THREAD

**Issue by Mosho1** [jspm/jspm-cli#1924]
I got the following change using 0.16.33:

![image](https://cloud.githubusercontent.com/assets/5153007/16168601/af7f1d40-3515-11e6-81b6-f06ed9fbaf8a.png)

A similar change to package.json as well.

**Comment by guybedford** [comment]
Thanks, added support for the ts alias in https://github.com/jspm/jspm-cli/commit/272f61b5392234c70a3db2ec2d23ae655e4f1600.

**Comment by guybedford** [comment]
Released in 0.16.40.
