### ISSUE TITLE
Proposal: JSPM Resolve Interaction

### ISSUE THREAD

**Issue by WorldMaker** [jspm/jspm-cli#1926]
It would nice to have a `jspm resolve --interactive` (`jspm resolve -i`) to inspect forks one at a time and determine a resolution.

For each fork in the project (ie, the output of `jspm inspect --forks`) it could present a numerical chooser between forked versions (with such a choice acting as `jspm resolve --only`), inspect the fork for further details, or skip to the next fork.

A tool like this would be useful for situations with lots of forks. (My current example coming from updates to a bunch of Aurelia packages resulted in a lot of forks.)

**Comment by guybedford** [comment]
A third-party tool could easily be made to support this sort of thing. If anyone is interested please let me know. Also if there are features we can add to the jspm API to make this easier I'd be happy to talk that through as well.
