### ISSUE TITLE
Error: SFX Bundle input error

### ISSUE THREAD

**Issue by m-j** [jspm/jspm-cli#1928]
When trying to use bundle arithmetic, doing simple:

```
jspm.bundleSFX(`app/app - angular`, dist, { runtime: false })
```

I get `Error: SFX Bundle input error`

I'm using 0.16.39 on Windows 8.1.

**Comment by guybedford** [comment]
You need to add a globalDeps option for exclusions output as a global. See the SystemJS Builder readme - https://github.com/systemjs/builder#self-executing-sfx-bundles.

**Comment by guybedford** [comment]
(alternatively set `format: 'amd'` or similar.

**Comment by m-j** [comment]
@guybedford Thx. You were right I was using it wrong (missed globalDeps).
