### ISSUE TITLE
jspm link before vs after jspm install?

### ISSUE THREAD

**Issue by wkw** [jspm/jspm-cli#1929]
**using jspm: 0.16.39**

My first time working with jspm links to npm packages. My current workflow (still being tested) is to:

`(cd package && npm link)`

then go into project and `jspm link npm:package`

this is all __before__ running `jspm install` on the main project.

Is this the correct way? or should I have run `jspm install` before linking in the global npm link?

My underlying need for this is multiple npm-published packages I need have invalid peerDependencies, and it's stopping jspm from resolving/installing them.

**Comment by marthinus-engelbrecht** [comment]
`jspm link npm:package@version` in the package that needs to be linked
`jspm install --link npm:package@version` in main repo consuming the linked package
in that order.

**Comment by wkw** [comment]
thanks.

**Comment by marthinus-engelbrecht** [comment]
Pleasure
