### ISSUE TITLE
unable to find github dependency of npm-style package

### ISSUE THREAD

**Issue by davismj** [jspm/jspm-cli#1930]
I am trying to install `module` into `application` via `jspm install my-reg:module`. `module` is npm-style, but has github dependencies as per the spec [here](https://docs.npmjs.com/files/package.json#github-urls). When installing, jspm fails with a 400 error on the github dependencies:

> warn Error on lookup for github:systemjs/plugin-css@^0.1.21
     Error: fatal: unable to access 'systemjs/plugin-css@0.1.21.git/': The requested URL returned error: 400

Here is the `jspm` section of my `package.json`:

**module/package.json**
```json
"jspm": {
  "registry": "npm",
  "main": "dist/index",
  "format": "amd",
  "directories": {
    "lib": "dist"
  },
  "dependencies": {
    "css": "systemjs/plugin-css@^0.1.21"
  }
}
```

**Comment by guybedford** [comment]
This does sound like a bug. Which version of jspm is this with. And specifically which version of jspm-npm? It's worth ensuring you're running the latest.

**Comment by davismj** [comment]
Version 0.16.39.

The source of the bug seems to be less buggy than expected. npm-style packages don't allow semver on git urls (see https://github.com/npm/npm/issues/3328). Nevertheless, it would be backward compatible to support it, and it seems to be a forthcoming feature.

**Comment by guybedford** [comment]
Perhaps confirm you are using a # not a @ for npm versions here as well?

**Comment by davismj** [comment]
I'm using `@` everywhere.

**Comment by guybedford** [comment]
Because this is a package.json on npm, it needs to follow the npm conventions (`#` for version) and not the jspm conventions. To use the jspm conventions specifically (and stop the package working in npm and Node) you need to add `jspmNodeConversion: false`.
