### ISSUE TITLE
Linking strategy for indirect dependencies

### ISSUE THREAD

**Issue by DanielSWolf** [jspm/jspm-cli#1932]
Package linking is easy when the application package directly references the package I want to change. I'm not sure how to proceed when the dependency graph is deeper, like this:

![packages](https://cloud.githubusercontent.com/assets/5963162/16264659/15f73fe0-387b-11e6-83a4-7286721b597f.png)

Here, A is the package that contains the application and can be run. A depends on B and C, C depends on D, and both B and D depend on E. For simplicity's sake, let's assume that B and D depend on the same version of E.

Now I make some changes to E. **How do I use linking to get the new version of E into A?**

I see two possible approaches. First, I could emulate the way I would later release the packages: link E into B, link B into A, link E into D, link D into C, link C into A. Alternatively, I could link E directly into A, skipping the steps inbetween.

Which approach is the recommended one?

Also, what if I want B to use the new version of E, but D should still use the old version of E? Naively, I'd link E into B and B into A, hoping that within A, B will now receive the linked version of E, while D will still receive the old, published version of E. But given that both versions of E share the same version number, is JSPM able to differentiate between the two?

**Comment by guybedford** [comment]
Because jspm uses a flat structure, you would probably want to do link in the tree from the bottom up:

1. Link E into A
2. Link D into A (D dependency on E will now use the linked version)
3. Link C into A
4. Link B into A

Now all changes are reflected in the top-level project.

If you're testing packages individually, then you may also want to follow the same approach again for each individual package.

It's a lot of linking, and tooling could certainly make this simpler too.

**Comment by DanielSWolf** [comment]
Thanks for your answer! Unfortunately, this approach doesn't seem to work for me.

I actually created and published five dummy packages (A..E) and followed your link steps in the order you gave. As a result, B and D still get the unchanged E package when called from A.

I took a look at `A\jspm.config.js`. This is the relevant part:

```js
SystemJS.config({
  packageConfigPaths: [
    "npm:@*/*.json",
    "npm:*.json",
    "github:*/*.json",
    "local:*.json"
  ],
  map: {
    "B": "local:B@2.0.0",
    "C": "local:C@2.0.0",
    "D": "local:D@2.0.0",
    "E": "local:E@2.0.0"
  },
  packages: {
    "github:donald-50/D@2.0.0": {
      "map": {
        "E": "github:donald-50/E@2.0.0"
      }
    },
    "local:D@2.0.0": {
      "map": {
        "E": "github:donald-50/E@2.0.0"
      }
    },
    "local:C@2.0.0": {
      "map": {
        "D": "github:donald-50/D@2.0.0"
      }
    },
    "local:B@2.0.0": {
      "map": {
        "E": "github:donald-50/E@2.0.0"
      }
    }
  }
});
```

As you see, B, C, D, and E correctly point to the linked versions. However, the indirect dependency maps still point to the released versions.

**Comment by guybedford** [comment]
In order for the dependencies to be shared properly you need to make sure that the linked names correspond to the remote names.

Try using `jspm link ../path/to/e github:donald-50/E@2.0.0`

etc for each package so they are linked into the names that they correspond to in the packaging namespaces.

**Comment by DanielSWolf** [comment]
Thanks, that works! Actually, now that you told me how to *keep the original remote names*, it seems there are multiple ways of going about.

*Notes:*

* The following assumes JSPM 0.17.
* A black arrow indicates a dependency on the pointed-to package.
* A green arrow indicates a link; links are numbered in order of creation.

### 1. Link everything into A

![1](https://cloud.githubusercontent.com/assets/5963162/16451863/cf4ba5d2-3e05-11e6-8da0-a7e10e817d66.png)

That's the approach @guybedford suggested. This changes `A/package.json` and `A/jspm.config.js` by adding new dependencies on D and E. It doesn't make any other changes to these files. The magic happens because `A/jspm_packages/github/donald-50/B@2.0.0` etc. now are symlinks pointing to the local package directories.

### 2. Follow the dependencies

![2](https://cloud.githubusercontent.com/assets/5963162/16452001/845d101e-3e06-11e6-986c-05568102a170.png)

That's the approach I originally suggested. Every dependency on the paths from E to A is replaced with an equivalent link. This works, too. It also has the advantage that not a single checked-in file is changed; all it does is establish symlinks to directories containing symlinks to directories. Then again, there's rather a lot of linking involved.

### 3. Just link E into A

![3](https://cloud.githubusercontent.com/assets/5963162/16452123/29f067a6-3e07-11e6-9550-aafabe772de3.png)

This works, too. It has the clear advantage of requiring only a single link step. In fact, if all I want to do is link a *single* indirect dependency, I guess that's the way I would choose.

### 4. Link everything into A, but disregard order

![4](https://cloud.githubusercontent.com/assets/5963162/16452382/664287ba-3e08-11e6-8ecc-8dc44626e67e.png)

At this point, I had a feeling that the new, symlink-based linking mechanism in JSPM 0.17 doesn't rely on linking order the way JSPM 0.16 did. So I tried @guybedford's approach, but reversed linking order. Yup -- works, too.

So as long as you're using JSPM 0.17 and you want to test *a single indirect dependency*, there are several approaches to linking that all work.

**Comment by DanielSWolf** [comment]
Now that I've got the simple case covered, I'd like to learn about the more complex scenarios I'm facing:

1. What's the best linking approach if you change *multiple* packages, some of which depend on others? My guess is: link all modified packages directly into A, ignore the rest.
2. Is it possible to link a package so that only *some* dependent packages get the new version? For instance, is it possible to modify E and link it so that within A, D gets the modified version, but B gets the old, released one?

By the way, I might find the time to write an automated tool for these scenarios if it seems to make sense.

**Comment by guybedford** [comment]
1. Yes.
2. One approach for linking is to link the version as a new version so say you have `npm:pkg@1.2.3` then you can link it as `npm:pkg@1.2.4-beta` for example. That way you can support the linked version as another multiversion, and modify your own resolutions through the jspm config to choose which packages resolve to which version, while still respecting the overraching semver constraints.

**Comment by DanielSWolf** [comment]
Thanks for all your feedback. The new symlink-based linking mechanism in JSPM 0.17 makes linking much more straight-forward and convenient!

We currently hesitate to migrate to a beta version, though. Do you have a date in mind for the final 0.17 release?

**Comment by guybedford** [comment]
The final 0.17 is pending docs updates only. This will still take a couple of months to land, but the release is safe to use.

**Comment by DanielSWolf** [comment]
Thanks for your insights!
