### ISSUE TITLE
Unable to build a static single-file after upgrading to 0.17.0-beta.22

### ISSUE THREAD

**Issue by fayway** [jspm/jspm-cli#1933]
Unable to build when customizing jspm's **"directories": { "baseURL": "..." }** in **package.json**

Get the following error:

     $ jspm build main.js

     Creating the single-file build for main.js...

     err  Error: Unable to calculate canonical name to bundle file:///C:/jspm_0.17.0-beta.22/main.js. Ensure that this module sits within the baseURL or a wildcard path config.
         at getCanonicalNamePlain (C:\jspm_0.17.0-beta.22\node_modules\systemjs-builder\lib\utils.js:222:13)
         at getCanonicalName (C:\jspm_0.17.0-beta.22\node_modules\systemjs-builder\lib\utils.js:145:19)
         at C:\jspm_0.17.0-beta.22\node_modules\systemjs-builder\lib\rollup.js:283:25
         at Array.map (native)
         at C:\jspm_0.17.0-beta.22\node_modules\systemjs-builder\lib\rollup.js:282:49

Versions: node v6.2.2, npm 3.3.12, jspm 0.17.0-beta.22

Issue repo: https://github.com/fayway/jspm0.17.0-beta.22-build-issue

**package.json**

     {
       "name": "beta.22.test",
       "devDependencies": {
         "jspm": "^0.17.0-beta.22"
       },
       "jspm": {
         "name": "app",
         "main": "main.js",
         "directories": {
           "baseURL": "web"
         },
         "dependencies": {
           "jquery": "npm:jquery@^3.0.0"
         },
         "devDependencies": {
           "plugin-babel": "npm:systemjs-plugin-babel@^0.0.12"
         }
       }
     }

**Comment by sod** [comment]
moving the `main.js` to `web/src` and doing `jspm build app` works.

**Comment by fayway** [comment]
Thanks sod, that fixed it.
