### ISSUE TITLE
Mappings that are internal to a jspm package are not preserved/resolved when installed into an app.  

### ISSUE THREAD

**Issue by marthinus-engelbrecht** [jspm/jspm-cli#1934]
Hi, 

I have a bunch feature module that have mappings internal to the module to make using `import`  inside the feature easier. I also have external npm modules install. See example below 

```js
"map" : {
     "component1" : "source/component1"
     "component2" : "source/component2" 
     "angular" : "npm:angular@1.5.6" 
}
```

This allows me to just say `import "component1"` or `import "angular"`. The problem is when I install this feature module inside an app the "component1" and "component2" mappings are not preserved, thus the app doesn't know where "component1" or "component2" is. I'm suspecting that this is not something that is supported? I can't find anything on it.

**Comment by guybedford** [comment]
`map` in the package.json is only supported in jspm 0.17.

**Comment by marthinus-engelbrecht** [comment]
Thanks
