### ISSUE TITLE
jspm install is not creating loader-files folder in .jspm folder

### ISSUE THREAD

**Issue by timurtu** [jspm/jspm-cli#1935]
```
err  Error: ENOENT: no such file or directory, open 
'%USERPROFILE%\AppData\Lo
cal\.jspm\loader-files\systemjs'
         
at Error (native)
```

Hello,

We are trying to create a custom CDN handler for jspm installing GitHub packages. When we jspm install a package using the custom handler, jspm looks for specific loader-files. The jspm-cli is not creating the loader-files folder on jspm install. Are we missing anything here?

**Comment by guybedford** [comment]
If the configuration folder is corrupted, perhaps try running `jspm cc`?

**Comment by poonam212** [comment]
![jspm](https://user-images.githubusercontent.com/37362386/40357503-fd60f314-5dd9-11e8-9c51-a8818eea74ac.PNG)
