### ISSUE TITLE
--minify does not remove dead dependencies

### ISSUE THREAD

**Issue by julienvincent** [jspm/jspm-cli#1937]
I have a required npm package that has dependency requirements in an `if-else` that looks something like this:
```javascript
if (!"production") {
   f = require('faker')
   c = require('chance')
} else {
   f = someImitatorFunction
   c = someImitatorFunction
}
```
The code resolves to f and c containing `someImitatorFunction` and the `if` code portion is removed as dead code, however the `faker` and `chance` dependencies are still loaded into the bundle resulting in large production bundles.

**Comment by guybedford** [comment]
Yes, dependencies are statically analysed and we don't handle any conditional cases currently (although may well in future).

The level at which to handle this is through configuration:

```
map: {
  faker: '@empty'
}
```

That can be done via custom System.config call, or an override as well.

**Comment by julienvincent** [comment]
Ok thanks 👍  Closing.

**Comment by julienvincent** [comment]
Re-opening as:

```javascript
builder.config({
    map: {
        faker: '@empty',
        chance: '@empty'
    }
})
```

Did nothing.

**Comment by julienvincent** [comment]
Any updates on this?

**Comment by guybedford** [comment]
@julienvincent if it's a dependency of a dependency then the empty configuration would need to be provided through the package map of the parent dependency - 

```javascript
builder.config({
  packages: {
    'parent:package@x.y.z': {
      map: { faker: '@empty' }
    }
  }
});
```

etc. Let me know if that helps.

**Comment by julienvincent** [comment]
@guybedford I'm afraid this still did not work.

**Comment by guybedford** [comment]
@julienvincent I'm sorry to hear that.

**Comment by guybedford** [comment]
@julienvincent the way to test normalization configurations in the builder is via:

```javascript
builder.loader.normalize('faker', builder.loader.normalizeSync('parent:package@x.y.z'))
.then(function(normalized) {
  console.log(normalized);
});
```

The example config I provided should make the normalization above return `@empty`, but if it doesn't then that would be about ensuring the correct values for the pathing there. If it does return `@empty` then that would also be surprising as things should work from there.

So I'd suggest debugging the inputs and outputs of the above suggestion carefully.

Just let me know if you need any further help with this at all.

**Comment by ArmorDarks** [comment]
@guybedford Looking for `@empty`, I wonder, is it possible to map some modules to `@empty` in production environment without creating additional `jspm.config.js`?

Like

```js
builder.config({
    map: {
        production: { faker: '@empty' }
    }
})
```

**Comment by aluanhaddad** [comment]
@ArmorDarks 
You would need not _duplicate_ any configuration, as you could just load the additional configuration for production as of the bundling process. jspm@0.17-beta also has features such as conditional substitution and options to modularize into browser, node, and dev sections among others.

This might look like
 **tasks/builder.config.prod.js**
```js
export default {
  map: {
    faker: '@empty'
 }
};
```
**tasks/build.js**
```js
import jspm from 'jspm';
import prodConfig from './builder.config.prod';
const builder = new jspm.Builder(); // autoconfigured
builder.config(prodConfig); // add prod-config.
builder.bundle({format: 'esm', minify: false});

export default async function build(packageName, ...sharedPackageNames) {
  const bundleExpression = `${packageName} - ${sharedPackageNames.join('-')}`;
  try {
    await builder.bundle({format: 'esm', minify: false});
  } catch (e) {
    console.error(e);
  }
};
```
This may address your concern.

**Comment by ArmorDarks** [comment]
@aluanhaddad 

Thanks! I've re-read documentation about JSPM beta before few times and saw conditional substitution part, but still I'm unable to figure out how it can help in our situation.

From you code snippets I still see that you're loading specific config for production, `tasks/builder.config.prod.js`. This means that somewhere also stored main config, with all, not only production, mappings.

This is exactly what we're trying to avoid, since we're using JSPM as CLI tool, and messing with configs harder, and we don't want to store few config files with partially duplicated mappings.

Or did I miss something from your example?
