### ISSUE TITLE
jspm cannot find indirectly installed dependencies

### ISSUE THREAD

**Issue by julienvincent** [jspm/jspm-cli#1938]
Module `a` has dependencies on module `b`, which is defined in its `package.json`. Module `b` has dependencies on modules `c` and `d`, which are defined in its `package.json`.

Module `a` now attempts to `require` modules `c` and `d`, which aren't directly defined in its `package.json` but are installed under `jspm_packages` however jspm throws a `cannot find module c, d`. This pattern does work with npm.

This results in jspm not being directly compatible with CommonJS packages.

**Comment by julienvincent** [comment]
`jspm i npm:a` and then manually running `jspm i npm:c npm:d` allows jspm to find the dependencies.

**Comment by amalahussein** [comment]
I'm having the same issue...is there an issue with the registry?

**Comment by adamburgess** [comment]
In my opinion I don't think this is a bug
This practice is just hoping that `c` and `d` are in a neighbouring folder to `a`, which probably isn't the best thing to rely on, and could break if npm changes it's folder structure, for example.
If package `a` depends on `c`, then `c` should be a dependency of `a`! Tell the maintainer of `a` to fix their deps, or for now, locally override the deps on `a` to add `c` and `d`.

**Comment by julienvincent** [comment]
I agree that it isn't a bug, and I as the owner of `a` have already added the indirect modules as dependencies as I agree its not a stable pattern to rely on. However, my point is that this means that npm packages are not entirely compatible with jspm (albeit only in this rare case) and if other packages do this, they will break.

**Comment by guybedford** [comment]
The only way to allow loading packages that are not declared as direct dependencies, is by having those dependencies (c and d in your example) as top-level dependencies. The problem is top-level dependencies can only be installed to one version name. peerDependencies expresses this feature and limitation in jspm 0.17.

**Comment by julienvincent** [comment]
I had not considered peerDeps - that would resolve this. Thanks
