### ISSUE TITLE
jspm installs additional dependencies like nodelibs-buffer

### ISSUE THREAD

**Issue by martinstein** [jspm/jspm-cli#1940]
When I do a normal:
```
jspm install lodash
```
then jspm installs a number of other dependencies:
- nodelibs-buffer
- nodelibs-process
- process
- buffer
- base64-js (seems to be a dependency of buffer)
- ... (17 dependencies in total)

So I have 2 questions I can't figure out:

1. Where are these dependencies for `lodash` coming from/declared? lodash itself doesn't show them and I can't find any overrides in the jspm registry.
2. What are they needed for/do I really need these packages when I just want to use lodash in a web app?
3. How do I avoid these dependencies (in case they are not required)?

Not sure if a Github issue is the right place to ask, hope that's okay. Thanks for any help with this, I feel like I've hit a wall in this.

**Comment by adamburgess** [comment]
my install has these deps:

* npm:lodash
* (peer) nodelibs-buffer
  *  npm:buffer@4.7.0
    * npm:ieee754
    * npm:base64-js
    * npm:isarray
* (peer) nodelibs-process

as for your questions:

>Where are these dependencies for lodash coming from/declared? lodash itself doesn't show them and I can't find any overrides in the jspm registry.

jspm detects lodash's modules using `process`, a node global, so it installs a polyfill for the browser. It does this with `Buffer` too.

>Do I really need these packages when I just want to use lodash in a web app?

to use lodash unmodified? no. Take this example:
```js
import _ from 'lodash'
console.log(_.reverse([1,2,3]));
```
if you `jspm build app.js`, you'll see it'll **only**[1] includes `lodash.js`. The resulting file is still large though, ~190kb (as it includes the entirety of lodash, consider using `lodash/core.js` or more ideally the individual modules)

If you imported a file using Buffer, such as `isBuffer.js`:
```js
import isBuffer from 'lodash/isBuffer.js'
console.log(isBuffer(new Buffer()));
```

you'll see it includes everything else,
```
     Creating the single-file build for test.js...
       github:jspm/nodelibs-buffer@0.2.0-alpha/global.js
       github:jspm/nodelibs-process@0.2.0-alpha/process.js
       npm:base64-js@1.1.2/lib/b64.js
       npm:buffer@4.7.0/index.js
       npm:ieee754@1.1.6/index.js
       npm:isarray@1.0.0/index.js
       npm:lodash@4.13.1/_checkGlobal.js
       npm:lodash@4.13.1/_root.js
       npm:lodash@4.13.1/isBuffer.js
       npm:lodash@4.13.1/stubFalse.js
       app.js
```

> How do I avoid these dependencies (in case they are not required)?

If you use something like isBuffer in a web app, you need them. JSPM would (well, should, see footnote) import Buffer for you. If using them in node, then passing the `--node` flag to build makes jspm aware that Buffer is already available.

[1]
I believe this is actually a bug, as jspm detects the main lodash.js file as AMD, and thus does not try to polyfill Buffer..If you manually tell jspm that lodash.js is CJS, then it includes buffer and process and their deps.

**Comment by guybedford** [comment]
@adamburgess thanks for the clear explanation here. If it is worth excluding these since we use the main AMD lodash by default, that can be done via adding empty map overrides for process and Buffer or even by disabling the Node conversion (but that would stop the individual file mode from working).

**Comment by martinstein** [comment]
Hi @adamburgess and @guybedford, thanks for your replies. Adam, your explanation was very helpful. Before that I wasn't aware that jspm did a deeper analysis of imported packages. Just out of curiousity: When I jspm-install a package, jspm does a full analysis of the package source and if it detects a Node-global somewhere, it installs that polyfill? How does it detect the process usage for lodash though? In the lodash source, process isn't even referred directly but through a helper variable `freeGlobal` (https://github.com/lodash/lodash/blob/master/lodash.js#L385)

I'm thinking that the empty map overrides for process and buffer might make sense. I don't think lodash expects Buffer or process to be present or work in a browser environment, so automatically adding them during install definitely surprised me a lot.

As a somewhat new user to jspm, I'm not completely clear on the overrides yet. Are those empty proces and Buffer overrides something that I can do myself during install or does that need to be in the global jspm registry? The only docs mention that I found for v0.16 was here: http://jspm.io/docs/installing-packages.html, but that section doesn't go into too much detail.

**Comment by guybedford** [comment]
@markstickley the process and Buffer globals are added automatically when checked to replicate the NodeJS environment to ensure correct behaviours.

The override docs are at https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm. It's somewhat dated but still covers roughly the right ideas. (`jspm install lodash -o "{map:{process:'@empty',buffer:'@empty'}}"` should be the right approach to test I think)

**Comment by martinstein** [comment]
Okay, I've just tried the `jspm install lodash -o "{map:{process:'@empty',buffer:'@empty'}}"` and it works flawlessly (i.e. no further dependencies installed beyond lodash). Thanks for your help!

**Comment by guybedford** [comment]
Ok great, I've added this as an override in https://github.com/jspm/registry/commit/3fb4f65918ce477364ab060504a05faab980de1d. To use the override on projects where lodash is already installed you can do `jspm install lodash -o` which will refresh from the remote override (usually installs lock the override to what was present at install time).

**Comment by MaximBalaganskiy** [comment]
I've got a similar issue when sfx bundling with numeral `buildStatic` errors
`Error: Unable to build dependency npm:jspm-nodelibs-process@0.2.1/#:./process.js. normalize must be disabled for bundles containing conditionals.`

Installing numeral with the following command helps
`jspm install numeral -o "{map:{process:'@empty'}}"`
