### ISSUE TITLE
Semver not being respected 

### ISSUE THREAD

**Issue by marthinus-engelbrecht** [jspm/jspm-cli#1941]
Hi,

I'm using jspm 0.16.39. 

I have dependency `"mediator": "npm:mediator@^1.0.4"` , in my package.json. When I run `jspm install` it install mediator@1.0.4 but there is a mediator@1.0.7 in my repository. The way I understand semver it should have installed mediator@1.0.7. If I run `jspm install npm:mediator` it changes my package.json to `"mediator": "npm:mediator@^1.0.7" ` and installs mediator@1.0.7

**Comment by OrKoN** [comment]
`jspm install` uses the exact version stored in the JSPM's config.js. You should use `jspm update` to update your config.js according to the semver defined in your package.json.

**Comment by marthinus-engelbrecht** [comment]
Thanks, this works as you mentioned.
