### ISSUE TITLE
Angular2 lazy loading not working with latest lazy loading support from google...

### ISSUE THREAD

**Issue by born2net** [jspm/jspm-cli#1944]
So I tried to get this working with jspm (now supprted by the ng2 team):
https://plnkr.co/edit/7W8g8GxWREXQPlwsqdcx?p=preview

and I keep getting an error from zone.js that Promise could not be resolved.

```
EXCEPTION: Error: Uncaught (in promise): Cannot resolve component using 'lazy#LazyComponent'.
  STACKTRACE:
  Error: Uncaught (in promise): Cannot resolve component using 'lazy#LazyComponent'.
    at resolvePromise (http://localhost:9089/jspm_packages/npm/zone.js@0.6.12/dist/zone.js:538:32)
    at eval (http://localhost:9089/jspm_packages/npm/zone.js@0.6.12/dist/zone.js:515:14)
    at ZoneDelegate.invoke (http://localhost:9089/jspm_packages/npm/zone.js@0.6.12/dist/zone.js:323:29)
```
Is this supposed to work or does jspm need some features added to support this?

regards

Sean

**Comment by guybedford** [comment]
It sounds like you just need to ensure that `System.import('lazy')` will be able to resolve properly on its own, as I think Angular just calls that.

**Comment by born2net** [comment]
actually I believe it's a bit more involved, the angular2 team redeveloped the entire router from scratcjh and released last week just to support lazy loading via routes, so the component does not bundle in and the framework is not aware of the component UNTIL the route is established... AFIK, it may require special support from jspm... am I correct?

**Comment by guybedford** [comment]
The lazy loading itself still boils down to a call to `System.import('lazy')` in that example, which it reads from the router. I inspected the example you provided and that's definitely what it's doing.

**Comment by born2net** [comment]
Ok I will try and resolve System.import('lazy') on it's own and see if it resolves.
However I did try dozens of combinations, even just putting lazy.ts in the root of the server and just mapping it in jspm.config, with no success...
regards
