### ISSUE TITLE
Small typo in jspm init

### ISSUE THREAD

**Issue by MeoMix** [jspm/jspm-cli#1945]
Hey,

When I run `jspm init`

I see the following:

> If ommitted, paths locations must be individually configured

There's only one m in omitted. Also, there's a weird plural usage with paths + locations. Suggest it should be:

> If omitted, path locations must be individually configured

I haven't looked closely at the rest of the messages. Suggest the entire thing is ran through a quick spellcheck + grammar check.

**Comment by guybedford** [comment]
Thanks, I've included https://github.com/jspm/jspm-cli/commit/5fda902b835d60c07e8e143d3e862e7bf9540c46.
