### ISSUE TITLE
JSPM package naming for NPM scoped packages with specified version

### ISSUE THREAD

**Issue by asteinfeld** [jspm/jspm-cli#1948]
When installing an npm scoped package to a specific version, I'm seeing inconsistent package naming when compared to a non-scoped package. For example,
`jspm install npm:@angular/core@2.0.0-rc.3`
successfully installs with the message (note the version on the installed name):
`Installed @angular/core@2.0.0-rc.3 as npm:@angular/core@2.0.0-rc.3 (2.0.0-rc.3)`

On the other hand, a normal non-scoped package behaves as expected:
`jspm install npm:jquery@3.0.0`
succeeds with the message (no version on installed name):
`Installed jquery as npm:jquery@3.0.0 (3.0.0)`

Both the config.js file and package.json produced also reflect this inconsistency.

I would expected scoped packages to behave in the same way as non-scoped - in this case, to install with the name `@angular/core`.

Seeing this behavior both on stable (0.16.39) and beta (0.17.0-beta.22), while raw npm (3.8.9) installs of the same packages seem to follow my expected behavior.

I can work around this with aliases, but are my expectations correct here?

**Comment by guybedford** [comment]
You're completely right and thanks for posting. I've added a fix for the next release.

**Comment by guybedford** [comment]
Released in 0.17.0-beta.23.
