### ISSUE TITLE
How to use npm dev dependecies in jspm?

### ISSUE THREAD

**Issue by gokul11** [jspm/jspm-cli#1949]
My project (Node JS) have three private packages itself.

1. common - gulp task to run process and control
2. process - base process functions
3. control - control functions

The control package is dependent to process and common packages, so when I install I got the above three packages in jspm_packages folder.

`jspm install bitbucket:account/control`

All npm dev dependencies are configured inside the package.json of common package.

```
"devDependencies": {   
    "gulp": "^3.9.0",
    "gulp-autoprefixer": "^3.1.0",
    "gulp-codecov": "^2.0.1",
    "gulp-jasmine": "^2.0.1",
    "gulp-jshint": "^1.11.2",
    "gulp-open": "^2.0.0",
    "gulp-sass": "^2.3.1",
    "gulp-sass-lint": "^1.1.1",
    "gulp-tslint": "^4.1",
    "gulp-typedoc": "^2.0.0",
    "gulp-typescript": "^2.13.0",
    ........
    ........
  },
```

 Is it necessary to run `npm install` to get the node modules inside common package? or any other options available in jspm itself?

**Comment by guybedford** [comment]
Yes npm is required for npm installs. jspm may well provide bin features itself for running its own server-side code in future, but currently a separate npm install is still recommended.

**Comment by gokul11** [comment]
Thanks for the info @guybedford. I have one more doubt. Is it possible to merge 3 packages as a single package while installing jspm? because I have to run the gulp tasks to other packages (process and control) and need to refer some dependencies from one package to other. If I can get a single package after installing jspm, it is easy to run gulp task at single package.
