### ISSUE TITLE
Error parsing package.json

### ISSUE THREAD

**Issue by ggrimbert** [jspm/jspm-cli#1950]
Hi,

I am having this strange error message while trying to do `jspm install` with jspm 0.17 : 

```
err  Error parsing package.json file /home/ggrimbert/edevelo/local/Aurelia/jspm-webapp/jspm_packages/npm/url@0.11.0.json
```

the package url@0.11.0 exists in my jspm_packages folder and has a package.json file, but at the path url@0.11.0/package.json. 
I don't know if the file trace is false or if JSPM really wants to load url@0.11.0.json.

The 'url ' package comes from dependencies of another module, that was imported in my app since the beginning and I never had this kind of problem.

By the way, I have a question and don't really want to open a new issue for this:
Have you planned to integrate natively local git providers ? I know that jspm-git exists but I believe that it should work better if you do it yourself, and the current version of this package has a big bug with JSPM beta.

**Comment by guybedford** [comment]
This sounds like an install corruption case. Perhaps try `jspm install -f`?

jspm-git is the way to go about it. I'd be interested to hear what bug jspm-git has on the beta?

**Comment by ggrimbert** [comment]
JSPM install -f gives the same result, I will try to reinstall jspm.

The bug with jspm-cli is the following : https://github.com/Orbs/jspm-git/issues/30.

**Comment by ggrimbert** [comment]
The reinstall of JSPM resolved the issue.

Now I am having the same error I had few months ago, https://github.com/jspm/jspm-cli/issues/1648.

I ran : jspm install -o "{ignore:['libtests','build-tools','includes']}" without success. Am I supposed to do this for each dependency that fail ?

**Comment by guybedford** [comment]
For that bug it sounds like you need to run the beta version of jspm-git then (0.5.0-beta.3 through npm)?

It sounds like your problems are related - crashing installs causing corrupted jspm_packages. It sounds like there's just one large package causing your problems here though that you need to deal with through ignores (unless you're installing 1000 dependencies, in which case that could also be it!).

**Comment by ggrimbert** [comment]
It's still the same problem that I reported, pnotify. I made it work:
- remove it from the package.json
- jspm install
- jspm install npm:pnotify@3.0.0 -o  "{ignore:['libtests','build-tools','includes']}"


Quick questions before you close this post, I use gulp to build my app. 

So I understand that the config.js has disappeared for jspm.config.js, but you talk about a jspm.browser.js in your doc (http://jspm.io/0.17-beta-guide/creating-a-project.html), this file has not been created. Am I supposed to create it by hand ?

Now with the new jspm.config.js, when I run my app, the requires are taken 'as it ' (understand as the require -> without .js), so the file loading is like that : ```http://localhost:1337/dist/konnect/services/core/ws/connection-service ```
What should I do for it to search files with .js ?
I've tried this in the jspm.config.js : 
```
packages: {
    "kimweb-home": {
      "main": "kimweb-home.js",
      "defaultExtension" : ".js"
    }
  },
```
but without success.

However, thanks for your quick and clear answers :)

**Comment by guybedford** [comment]
Yes `jspm.browser.js` is no longer created by default, I've updated the beta guide.

If `kimweb-home` is the parent folder of `dist/konnect/services/core/ws/...` then the above is the right approach. For example if you had the paths configuration:

```javascript
paths: {
   'kimweb-home/': 'dist/'
}
```

Then the above should work.

**Comment by ggrimbert** [comment]
Awesome ! I found a workaround but what you said is really better. 

I will try to set the jspm.browser.js

Thanks for your help.

Feel free to close this discuss.
