### ISSUE TITLE
Multiple packages defined, always loads last one

### ISSUE THREAD

**Issue by perrin4869** [jspm/jspm-cli#1951]
I'm trying to setup two different entry points for the app, one for admins and one for regular users:

```js
// after loading jspm.config.js
System.import('app') // loads normal users
System.import('admin') // loads admin scripts
```

In `jspm.config.js` I setup:

```js
SystemJS.config({
  paths: {
    "npm:": "jspm_packages/npm/",
    "github:": "jspm_packages/github/",
    "admin/": "js/",
    "app/": "js/"
  },
  browserConfig: {
    "baseURL": "/client"
  },
  devConfig: {
  // ...
  },
  transpiler: "plugin-babel",
  packages: {
    "admin": {
      "main": "admin.js",
      "format": "esm"
    },
    "app": {
      "main": "main.jsx",
      "format": "esm",
      "map": {
        "./config.js": {
          "~production": "./config.dev.js"
        }
      },
      "meta": {
        "*.jsx": {
          "babelOptions": {
            "plugins": [
              "babel-plugin-transform-react-jsx",
              "babel-plugin-transform-class-properties"
            ]
          }
        }
      }
    }
  }
});

// additional jspm managed configs...
```

Unfortunately, both `System.import('app')` and `System.import('admin')` load `app`. If I change the order `app` and `admin` are defined in `jspm.config.js`, then `admin` will be the one that is always loaded.

**Comment by guybedford** [comment]
Make sure the apps have unique names in pathed space - `js-admin` and `js-app` for example.

**Comment by perrin4869** [comment]
sorry for the potentially stupid question - what is pathed space?

**Comment by guybedford** [comment]
The URL space in which all modules are referenced in the registry. The module loader stores all modules under a unique URL, which corresponds to the normalized name in SystemJS. All names and configurations in SystemJS are normalized into this space. If this URL matches, then the modules are assumed to match. Use `System.normalizeSync('x')` to see what this is.

**Comment by perrin4869** [comment]
hm... both `System.normalizeSync('admin')` and `System.normalizeSync('app')` point to the same url - `"http://localhost:3000/client/js/main.jsx"`. Renaming them to `js-app` and `js-admin` still pointed to the same url though

**Comment by perrin4869** [comment]
@guybedford is this a confirmed bug then? I can try to reproduce if it'll help to fix this

**Comment by guybedford** [comment]
No, this is how normalization works - `admin` and `app` are both being configured to the same URL with this configuration - normalization is allowed to be many-to-one.

**Comment by perrin4869** [comment]
hm... how do you configure them to point to different URLs then? Is that not possible?

**Comment by guybedford** [comment]
Two entry points = two normalized URLs.

So you want to have eg `import 'app'` normalize into `app-admin.js` for the one case and `app-not-admin.js` for the other case.

That can be done by including different map configurations between the environments.

**Comment by perrin4869** [comment]
hm... that's not quite what I'm trying to achieve though. Rather than 2 different environments, I want 2 separate, independent applications basically.
So from http://localhost/ I would do `System.import('app')`, and from http://localhost/admin I would do `System.import('admin')`, and they do completely different things. Is that possible?

Does this mean that configuring the `main` property of multiple packages is not allowed?

Sorry, I'm still trying to wrap  my head around this ><;;

**Comment by perrin4869** [comment]
Hm... from the documentation on [packages](https://github.com/systemjs/systemjs/blob/0.19.16/docs/config-api.md#packages) it would seem you can assign different `main` properties to different `packages` entries, right?

**Comment by guybedford** [comment]
It does sound like you have two packages in this case - 

```javascript
System.config({
  map: {
    'admin/': 'path/to/admin/',
    'app/': 'path/to/app/'
  },
  packages: {
    admin: {
      // ...
    },
    app: {
      // ...
    }
  }
});
```

**Comment by perrin4869** [comment]
I see, yeah, using different maps does work. Shouldn't it be possible to setup different `main` properties for each case though?

**Comment by guybedford** [comment]
Yes packages can have their own mains in the above. Just let me know if you have any further questions here at all.
