### ISSUE TITLE
Unable to apply typescript override

### ISSUE THREAD

**Issue by speigg** [jspm/jspm-cli#1952]
Using `jspm@0.17.0-beta.22`. I have been trying to apply this override in my package.json
```
      "npm:typescript@1.9.0-dev.20160627-1.0": {
        "browser": {},
        "jspmPackage": true
      }
```

But jspm seems to ignore it and adds the override from the registry to my package.json, which doesn't even match the version of typescript I have installed. 

I also applied this override, if it matters:
```
 "github:frankwallis/plugin-typescript@2.6.0": {
        "dependencies": {
          "typescript": "npm:typescript@1.9.0-dev.20160627-1.0"
        }
 }
```

**Comment by guybedford** [comment]
It may be using the other override is exactly because the versions aren't matching. Make sure your install is resolving to the right version by either using `jspm install x=npm:x@x.y.z` style exact version install or just running a `jspm install` with no arguments?

**Comment by speigg** [comment]
Hmm, I'm not sure what the problem was, but I upgraded the ts plugin and it seems to behave as expected now.
