### ISSUE TITLE
Proposal [ Initial Angular 2 Boilerplate ] 

### ISSUE THREAD

**Issue by DavidStrada** [jspm/jspm-cli#1960]
Hi Guy, I've created a barebones Angular 2 Started kit, after seeing a lot of either Issues here and on gitter, I decided to act upon it. 

[This is the Repo](https://github.com/DavidStrada/jspm_ng2)

I'm adding it to see what do you/community thinks, would this be useful for other people, improve upon it ? hopefully you/others will find this useful. 

If you would like to have a pull request to integrate this in the docs/resources do let me know.

Thanks,
David.

**Comment by OrKoN** [comment]
Hey @DavidStrada, you may want to add the project to the list of 3rd-party resources: https://github.com/jspm/jspm-cli/wiki/Third-Party-Resources

**Comment by jakeNiemiec** [comment]
+1 I think would be very helpful.

**Comment by guybedford** [comment]
Great to see this. Please do include it in the wiki and elsewhere if you like.
