### ISSUE TITLE
0.17@beta jspm install semantic-ui throw an error jspm:better-console not found

### ISSUE THREAD

**Issue by kresli** [jspm/jspm-cli#1962]
Same for `jspm install semantic-ui=github:Semantic-Org/Semantic-UI`. Both works on 0.16 so not sure whats wrong. Also one of my issues are to locate JSPM's plugins. Where I can find the list of all plugins? Am I miss that list somewhere in the docs? I can imagine some cli command for this list `jspm --plugins`.
`node -v 5.10.1`
```
$ jspm install semantic-ui     
     Updating registry cache...
     Downloading github:Semantic-Org/Semantic-UI@2.2.1
     Downloading npm:jquery@2.2.4
ok   Installed npm:jquery@^2.1.4 (2.2.4)
     Downloading github:systemjs/plugin-css@0.1.23
ok   Installed peer extend to github:gamtiq/extend (0.1.1)
ok   Installed github:systemjs/plugin-css (0.1.23)

err  Repo jspm:better-console not found. Perhaps try jspm install npm:better-console.
```
Thanks.

**Comment by kresli** [comment]
I tried to `jspm install github:Semantic-Org/Semantic-UI` I've got an error.
When I fork it and install it by `jspm install github:kresli/Semantic-UI` it works.
Finally when Im trying to install it from my fork with the options I've got same error.
`jspm install semantic-ui=github:kresli/Semantic-UI -o "{ 'directories': { 'lib': 'dist' }, main: 'semantic', 'shim': { 'semantic': { 'deps': [ 'jquery', 'semantic-ui/semantic.css!' ] } }, 'dependencies': { 'jquery': 'github:components/jquery', 'css': 'github:systemjs/plugin-css' } }"` From the error I can see the jspm trying to install the `better-console` by `jspm:better-console`. This should be with npm prefix, though. Hope that helps a bit.

**Comment by guybedford** [comment]
I just tried this on the current 0.17 and it seems to work ok for me?

**Comment by andrewkon** [comment]
Same problem here, trying to upgrade from 16 to 17, but cannot because of this.

**Comment by glen-84** [comment]
I don't know if it's related, but I'm also seeing errors like `err  Repo npm:isomorphic-fetch not found!`.

I'm using a private npm registry though.

```
$ node -v
v6.3.0

$ npm -v
3.10.5

$ jspm -v
0.17.0-beta.22
Running against local jspm install.
```

**Comment by dinoboff** [comment]
confirming:
```
Running against local jspm install.
mkdir jspm-semantic-ui
cd jspm-semantic-ui
npm init -y
npm i --save-dev jspm@beta
./node_modules/.bin/jspm init -y
/node_modules/.bin/jspm install semantic-ui
```

Gets:

         Updating registry cache...
         Downloading npm:jquery@2.2.4

    err  Repo jspm:better-console not found. Perhaps try jspm install npm:better-console.

    warn Installation changes not saved.

Details:

    $ node -v
    v4.4.5
    $ npm -v
    3.9.2
    $ ./node_modules/.bin/jspm -v
    0.17.0-beta.22
    Running against local jspm install.

**Comment by dinoboff** [comment]
It fails since version 2.1.8. `jspm install semantic-ui@2.1.7` works. Could it be related to [that commit with peerDependencies](https://github.com/Semantic-Org/Semantic-UI/commit/04a3c48a0dd3bd9b440b59036004409239a6db16#diff-b9cfc7f2cdf78a7f4b91a753d10865a2)?

**Comment by dinoboff** [comment]
The only relevant difference between 2.0.3 and 2.0.4 is the [jspm registry](https://github.com/jspm/registry/tree/master/package-overrides/github/Semantic-Org) setting the module type to "jspm".

The difference between 2.1.7 and 2.1.8 are those peer dependencies.

**Comment by dinoboff** [comment]
It works if you override peerDependencies:
```
jspm install semantic-ui -o '{"directories":{"lib":"dist"},"main":"semantic","shim":{"semantic":{"deps":["jquery","./semantic.css!"],"exports":"$"}},"registry":"jspm","dependencies":{"jquery":"^2.1.4","css":"*"},"peerDependencies":{}}'
```

@guybedford is it bug? Or does the registry needs to be updated?

**Comment by guybedford** [comment]
@dinoboff yes we can add the override to remove peerDependencies, or to switch the registry to npm. But if switching the registry to npm we may as well set this up as `npm:semantic-ui`??

Did you try `jspm install npm:semantic-ui` as well perhaps?

**Comment by dinoboff** [comment]
I tried with `"registry":"npm"`, but it installs lots of npm modules.

**Comment by guybedford** [comment]
If you're happy with the empty peerDependencies approach, a PR to the jspm registry would be really welcome.

**Comment by JulianIsrael** [comment]
importing semantic-ui-react is giving an error in latests jspm beta versions.
