### ISSUE TITLE
How do I get bootstrap 4 flexbox working?

### ISSUE THREAD

**Issue by norgeous** [jspm/jspm-cli#1963]
Hello,

Not really a bug, but didn't know where else to ask. I'm trying to get bootstrap v4 flexbox edition working...

First I ran:
```jspm install bootstrap@4.0.0-alpha.2```

Now I would like to enable the flexbox properties using [this method](http://v4-alpha.getbootstrap.com/getting-started/flexbox/#how-it-works), but `_variables.scss` was not included in the download that jspm did.

Is there a way to get `jspm` to download the `scss` files also?
Or perhaps there is there some other magic to getting bs 4 flexbox working?

Thanks!

**Comment by DavidStrada** [comment]
here's a working copy of bootstrap including `scss` directory --> [check the repo](https://github.com/DavidStrada/bootstrap4_jspm_cli_v0.17.0-beta.17), @jakeNiemiec I thought we solve this ?

**Comment by norgeous** [comment]
Thanks @DavidStrada ! Yes, that helps... I am new to all this and I believe your comment has pushed me in the right direction.

There is a difference between these two commands:
```sh
jspm install bootstrap@4.0.0-alpha.2
```
It creates the folder `/jspm_packages/github/twbs/bootstrap@4.0.0-alpha.2`, but no scss files =[.

When I try:
```sh
npm install bootstrap@4.0.0-alpha.2
```
It provides the scss files I need at `/node_modules/bootstrap/scss`.

I thought `jspm` was a kind of replacement for `npm`, but I suppose this is not really true? Sorry for asking you, but what is the difference in this case? Running `jspm install` on the repo you supplied does not get the scss files.

**Comment by norgeous** [comment]
ok I have discovered the command that I need is:
```
jspm install github:twbs/bootstrap@4.0.0-alpha.2
```

**Comment by norgeous** [comment]
This command works perfect:
```
npm install jspm@beta --save-dev
jspm install bootstrap=github:twbs/bootstrap@4.0.0-alpha.2 -o "{'directories':{'lib':'.'}}"
```
thanks!

please close.

**Comment by jakeNiemiec** [comment]
@norgeous @DavidStrada It depends on this here: https://github.com/jspm/registry/pull/916
