### ISSUE TITLE
How to create 'singleton' packages?

### ISSUE THREAD

**Issue by DanielSWolf** [jspm/jspm-cli#1965]
Sometimes, we need to make sure that there's only a single version of a given package running at once. In other words, we don't want two different versions of that package to occur within the same dependency tree.

Here are some examples:
- A package representing a global event manager. Other packages register for named events or publish them. If by accident some packages reference one version of the event manager, others a different one, there will be two event manager instances at the same time. One package may publish an event, but another package won't receive it, since it registered with the other event manager.
- A logging framework that logs to files. If there are multiple instances at once, they'll both try to write to the same file, which may result in corruption for structured file formats.
- In general, any package that models a global singleton.

Is there any way to automatically enforce this constraint? Ideally, `jspm install` and `jspm update` should exit with an error if the resulting dependency graph would contain such a conflict.

**Comment by guybedford** [comment]
This is what peerDependencies are for in jspm 0.17. Then you can use `jspm install x --peer`. I'd suggest running that version if you can.

**Comment by DanielSWolf** [comment]
I read about peer dependencies a while ago. The problem I see is that the person installing the package has to *know* they need to install it as a peer dependency. Which is a chance for human error.

Logically, I think the one entity that knows for certain how a package needs to be installed is *that package itself*. When you write a package, you may decide that multiple versions of that package may co-exist. Or you may decide that there may only be a single instance. In any case, it's a decision that logically lies with the package author.

Would it be possible to move the knowledge that a given package is single-instance *into the package itself*? For instance, something like this?

**package.json**
```xml
...
<jspm>
  <peerDependency>true<peerDependency>
  ...
</jspm>
...
```

That way, you could simply `jspm install` a peer dependency like any other package. JSPM itself would take care of recognizing the package as a peer dependency and installing it accordingly.

**Comment by guybedford** [comment]
In jspm 0.17, if I install for example `jspm install npm:material-ui` that will automatically install React and ReactDOM as top-level dependencies. That is peerDependencies of dependencies automatically become top-level dependencies in jspm, exactly for this user experience argument.

**Comment by DanielSWolf** [comment]
Hi @guybedford, I think I didn't properly explain my point. I'm not concerned about *indirect* peer dependencies.

Let's say I write a package that wraps access to a local database. Any read or write access to that database goes through my package, and for performance reasons it caches some of these values. Clearly, this package expects that there is only ever a single running instance of it. If multiple instances were active, caching errors and data corruption would ensue.

My point is: This limitation is absolutely obvious to the person who has written this package. *But it may not be obvious to a person __using__ the package*. The person *using* the package may just `jsmp install` it, without thinking to add the `--peer` argument.

This is why I believe that installation time is not the best time to decide whether a package should be installed as a peer dependency or not. We could prevent a lot of human error if there was a way for the *author* of a package to specify that this package must always be installed as a peer dependency. Thus my proposal for something like this:

**package.json**
```xml
...
<jspm>
  <peerDependency>true<peerDependency>
  ...
</jspm>
...
```

This would mean that whenever *this package* is installed into another package, the `--peer` argument is added implicitly. This prevents a package that requires peer installation to be installed non-peer.

Of course, the other direction would still be possible: You can always take a package that was conceived non-peer and install it as a peer dependency by explicitly specifying `--peer`.

**Comment by guybedford** [comment]
@DanielSWolf I see what you mean - for packages themselves to indicate that they are always to be installed as peer dependencies via a package.json flag. That would definitely be useful.

Another way of doing this today would be to have the main database driver in a dependency package that is a peer dependency of the main installed library package.

**Comment by DanielSWolf** [comment]
@guybedford That could indeed be a workaround. Then again, we have a whole bunch of single-instance packages like this. So we'd have to split them all in two...

What are the chances of seeing a package.json flag implemented?

**Comment by guybedford** [comment]
@DanielSWolf I'd be happy to include a `peerDependency: true/false` flag in the package.json actually. Would you be interested in working on this?
