### ISSUE TITLE
Invalidation does not work correctly for files which use a loader plugin (jspm 0.17.0-beta.22).

### ISSUE THREAD

**Issue by swernerx** [jspm/jspm-cli#1966]
I am using the jspm.Builder inside gulp to re-build whenever changes happen to the file system. The combination of calling `invalidate(path)` (in gulp.watch) with `bundle()` works fine so far for all JS files. What I stumbled upon know is probably some edge case not handled correctly yet. When doing the invalidation for non-JS files e.g. JSON files which are loaded by a specific plugin. It seems like in `traceCache` there is also the information of the loader plugin attached to the filename. As this data is not available to the outside it would be IMHO better to accept plain file names for non-JS files, too.

This is the section identified in the code (systemjs-builder):

```js
  // invalidate the given path in the trace cache
  var traceCache = this.cache.trace;
  Object.keys(traceCache).forEach(function(canonical) {
    var moduleName = loader.decanonicalize(canonical);
    if (matchesInvalidation(moduleName)) {
      if (traceCache[canonical])
        invalidated.push(moduleName);
      traceCache[canonical] = undefined;
    }
  });
```

The `moduleName` in these cases is always something like "file://xxx!yyyplugin.js" which does not allow any matching.

My workaround at the moment is to attach a "*" to every invalidation of non-JS files.

```js
  gulp.watch([
    "src/app/**/*.js",
    "src/app/**/*.css.json"
  ], [ "js:main" ]).
    on("change", (info) => {
      var path = info.path

      // SystemJS uses loader plugins for non-js files which
      // lead to issues when trying to invalidate non-JS files.
      if (!path.endsWith(".js")) {
        path += "*"
      }

      jspmBuilder.invalidate(path)
    })
```

**Comment by adamburgess** [comment]
I believe this is the expected behaviour. Files can be loaded by more than one plugin, so invalidating a file shouldn't mean to invalidate all separate modules loaded.

Your workaround is the correct approach - JSPM's inbuilt `watch` command also does this, see https://github.com/jspm/jspm-cli/commit/e25d7beca3e359daf377be3fa324d91d413d82df

**Comment by swernerx** [comment]
Thanks for clarification. So it's not `invalidate(file)` but more like `invalidate(identifier)`. It would be nice to add an API for file invalidation e.g. for simplify connecting it to watchdog/gulp.watch.

**Comment by swernerx** [comment]
BTW: Doing possibly thousands of regexp checks might be a performance issue for such a simple use care where we just want to report a single file invalidation (which could be with an alternative implementation O(1)).

**Comment by guybedford** [comment]
invalidate('*') is the full proof option always... and still pretty fast as it actually still maintains the cache, but just stats the file system to check freshness.
