### ISSUE TITLE
Error parsing package.json only in Windows

### ISSUE THREAD

**Issue by williamliangwl** [jspm/jspm-cli#1970]
I got the following error when i run jspm install:

Error parsing package.json file [some strings]\AppData\Local\.jspm\packages\npm\timed-out@2.0.0.deps.json

I used npm install first and run jspm init -y and jspm install as the postinstall script, but unfortunately i always get the error above.

I am using Windows 10, node v6.2.2, npm v.3.9.5, jspm v.0.16.39

I am new to both npm and jspm, can somebody help me?

**Comment by guybedford** [comment]
This may be due to permissions or a local corruption - try running jspm cc or even just removing that `AppData/Local/.jspm` folder entirely.

**Comment by williamliangwl** [comment]
removing the .jspm folder works for me, thanks :+1:
