### ISSUE TITLE
JSPM resolves symlink to package.json directory instead of using the CWD

### ISSUE THREAD

**Issue by moloch--** [jspm/jspm-cli#1971]
I use a docker base image to install dependancies to avoid needing to rebuild the image often. To achive this I have a symlinked `package.json` file file:

#### `src/`
```
drwxr-xr-x   15 moloch  staff   510B Jul  6 10:31 jspm_packages
drwxr-xr-x  219 moloch  staff   7.3K Jul  6 10:30 node_modules
lrwxr-xr-x    1 moloch  staff    42B Jul  6 10:35 package.json -> ../../setup/docker-base/nginx/package.json
```

If I want to run a bundle from the `src/` directory and put it into `./public` for example JSPM instead attempts to put it into the symlinked directory:

```
➜  ✗ jspm bundle-sfx --minify public/bundle.min.js
     Building the single-file sfx bundle for public/bundle.min.js...

err  Error on fetch for public/bundle.min.js at file:///Users/moloch/git/app/setup/docker-base/nginx/public/bundle.min.js
	Error: ENOENT: no such file or directory, open '/Users/moloch/git/app/setup/docker-base/nginx/public/bundle.min.js'
         at Error (native)
```

I had a similar issue with the `config.js` but fixed that by moving the file into the `../../setup/docker-base/nginx/` directory.

**Comment by guybedford** [comment]
I can confirm this is definitely working in jspm 0.17. Perhaps this would be a good reason to upgrade.
