### ISSUE TITLE
question - documentation for how to test jspm projects

### ISSUE THREAD

**Issue by joeldenning** [jspm/jspm-cli#1975]
I've seen several issues related to testing jspm projects -- would docs for testing be something you'd be interested in adding? If so, where do you think the best place for them would be? [0.17 guide](http://jspm.io/0.17-beta-guide/index.html)? [JSPM docs](https://github.com/jspm/jspm-cli/tree/master/docs)? [SystemJS docs](https://github.com/systemjs/systemjs/tree/master/docs)?

If this is something you'd like, I'd be happy to put together a pull request. What I have in mind is pretty simple. It would explain how you can use `new jspm.loader()`, `jspm.setPackagePath()`, etc. And also I was thinking it would link to the projects out there that facilitate testing jspm projects, such as [karma-jspm](https://github.com/Workiva/karma-jspm), [jspm-mocha-example](https://github.com/curran/jspm-mocha-example), [jspm-testem](https://github.com/OrKoN/jspm-testem), and [node-jspm-jasmine](https://github.com/CanopyTax/node-jspm-jasmine). I am, admittedly, biased towards node-jspm-jasmine since I started the project and actively maintain it, but I think that the jspm community would benefit as a whole if there was a place for testing-related resources to be explained and listed.

Your thoughts?

**Comment by joeldenning** [comment]
Also, I think that your recent [blog post](http://guybedford.com/systemjs-mocha-istanbul) would be a good thing to list as a resource.

**Comment by guybedford** [comment]
@joeldenning sorry for the delay, you are completely right here, this is something that is very much needed. I'd like to keep the core docs to a simple tutorial and API information, with better links to suitable external docs. If you write up a blog post here, please let me know and we must link to it. I think it could be worth creating a "Third-Party Documentation" section in the readme that can include things like this as curated links, covering the various topics of the project.
