### ISSUE TITLE
Unable to link scoped packages

### ISSUE THREAD

**Issue by circlingthesun** [jspm/jspm-cli#1976]
When attempting to link a local directory containing a package.json with a scoped package name (@somescope/somepackagename), the following error is thrown:

`The local registry doesn't support package names of this form`. (https://github.com/jspm/jspm-cli/blob/0.17/lib/link.js#L87)

It appears that the local registry's package name format defaults to `*` which, when converted to a regular expression, doesn't match package names containing slashes.

This is problematic for packages like: https://www.npmjs.com/package/@angular/common

**Comment by guybedford** [comment]
@circlingthesun I'd suggest linking into an `npm` name in this case - `jspm link ../folder npm:@scoped/package`.

**Comment by circlingthesun** [comment]
@guybedford thanks for the tip. I've only gotten back to trying this again today. Works like a charm :)

**Comment by guybedford** [comment]
Sure thanks for the update!
