### ISSUE TITLE
install latest version of dependency as an exact dependency

### ISSUE THREAD

**Issue by joeldenning** [jspm/jspm-cli#1977]
http://jspm.io/docs/installing-packages.html indicates that you can install the exact version of a dependency by doing `jspm install npm:react@15.2.1`, but I don't see a way to install exact the latest version of a dependency without specifying the version you want.

With npm, I do this with `npm install react@latest --save --save-exact` or just `npm install react --save --save-exact` or just `npm i react -S -E` and it automatically puts the latest version as an exact dependency. Would perhaps a `--save-exact` or a `--exact` flag be the right thing for jspm?

**Comment by guybedford** [comment]
The way to handle this use case currently is that it does just mean making it a top-level dependency.

**Comment by joeldenning** [comment]
How does making it a top-level dependency solve this? Doing `jspm install npm:react` will put `"react": "npm:react@^15.3.0"` into my package.json, and I'm looking for a way to make it put in `npm:react@15.3.0` (pinned without the `^`). Am I missing something?

**Comment by guybedford** [comment]
I'm just stating the obvious - that you need to install the sub-dependency first to an exact range in order to handle this use case today.

**Comment by guybedford** [comment]
Released in 0.17.0-beta.32.
