### ISSUE TITLE
.dependencies.json is not stable across machines

### ISSUE THREAD

**Issue by mikz** [jspm/jspm-cli#1978]
we have quite small package.json (just karma + jspm + some test tools)
and quite small jspm.config.js, but when we run jspm install on different machines, .dependencies.json changes 

we tried to clear the cache on all machines, upgrading node, upgrading npm, but it still happens
(node 6.2.0, npm 3.10.5, jspm 0.17.0-beta.22)

can't publish the whole app, but at least the config files in the gist: https://gist.github.com/mikz/4c925565644a4645b0d8bb0b5ef43f23

btw

**Comment by guybedford** [comment]
How is this causing issues? The `.dependencies` is just a small cache of the dependnecy ranges of the installed packages. So it will depend on what the package.json ranges are when installed, although usually that should be stable with the check-in of the configuration file.

Can you share a diff perhaps?

**Comment by mikz** [comment]
Maybe it is my misunderstanding, that `.dependencies.json` should be checked into version control?

If so, then it is annoying to commit it back on unrelated change. My understanding is that it behaves like shrinkwrap effectively locking every dependency and without it they can't be resolved the same on different machines. 

The diff would be comparing https://gist.github.com/mikz/4c925565644a4645b0d8bb0b5ef43f23#file-old-dependencies-json and https://gist.github.com/mikz/4c925565644a4645b0d8bb0b5ef43f23#file-new-dependencies-json . Made it a diff in a gist: https://gist.github.com/mikz/4c925565644a4645b0d8bb0b5ef43f23#file-dependencies-json-diff

**Comment by mikz** [comment]
Or maybe I'm mistaken and the whole can be ignored in version control ?

I can't really find any documentation on this.

**Comment by guybedford** [comment]
@mikz yes exactly this is not supposed to be under version control, like jspm_packages itself. It's just a local cache.

**Comment by mikz** [comment]
@guybedford I could write documentation for this. Do you know if there is some already or I should create some category/subcategory ?

Describing what the individual files do and if they are supposed to be in git or not.

**Comment by guybedford** [comment]
Sure, something along these lines when describing the project setup / getting started could be great!

**Comment by mikz** [comment]
Awesome. Only question I have is what to do with the `system.js` and `system.src.js`. They can be also excluded from the repo? JSPM locks them internally, right?

**Comment by guybedford** [comment]
Yes exactly.
