### ISSUE TITLE
Any paid support options?

### ISSUE THREAD

**Issue by glen-84** [jspm/jspm-cli#1980]
Are there any paid support options? I have some critical issues with 0.17 that result in me not being able to install or even link my own package.

I don't have a lot of money, but I don't mind paying at least something to expedite the process of fixing these issues, as they are preventing me from doing my work, and I am falling behind badly.

I appreciate the work that you do.

**Comment by guybedford** [comment]
What are the critical issues you are dealing with? Contributions are always welcome.

**Comment by guybedford** [comment]
Sorry I mean code contributions in the above.

**Comment by glen-84** [comment]
The critical issue is/was https://github.com/jspm/npm/issues/98, but some help with https://github.com/systemjs/systemjs/issues/1343 would be really useful within the next couple of weeks (it's now somewhat less urgent, as I decided to do an initial release without the "lazy" [dynamic] loading).

**Comment by guybedford** [comment]
@glen-84 let's continue to track in the individual issues then. Does the support directions we've taken on those work for you here?

**Comment by glen-84** [comment]
Sometimes in a business environment you just need something to work, and when it doesn't, it causes delays, and the delays can lead to financial loss, etc. In these cases the company would rather pay for these changes, as opposed to waiting weeks, months, or even years in the case of some open-source projects.

It's a bit tricky using open-source because of this, as there can be no expectations for something that is provided free of charge. In this particular instance, I was able to fix the issue (with some direction from yourself), but that won't always be possible (time constraints, insufficient understanding of the code, etc.).

Perhaps something like [Bountysource](https://www.bountysource.com/) might be useful in future. If it can speed up issue resolution while rewarding the developer, then it seems like a win-win situation to me.

Anyway, I've made another small (personal) donation as a symbol of my appreciation for your assistance in these matters and the work that you do. Thanks again.

**Comment by guybedford** [comment]
@glen-84 thanks for being open to getting involved to work on this stuff yourself. I've been taking a short break recently so really haven't had the bandwidth to assist with this kind of thing, this is certainly always the risk with open source, and why having a strong community matters.
