### ISSUE TITLE
0.17-beta.22 and commit resolution

### ISSUE THREAD

**Issue by pocesar** [jspm/jspm-cli#1983]
I'm trying to install npm:angular-google-maps, but it's giving me this error:

```
err Installing npm:angular-google-maps@2.3.3, no version match for github:MikaFima/js-rich-marker@0383f4bbdad4ddf154772fedbdd27e464600e943
```

If you go to `https://github.com/angular-ui/angular-google-maps/blob/e7631d28f642d54f06f14b50901b53c7c3d6d0ca/package.json#L82` you can see it's defined as `git://github.com/MikaFima/js-rich-marker.git#0383f4bbdad4ddf154772fedbdd27e464600e943`, and the commit do exist https://github.com/MikaFima/js-rich-marker/commit/0383f4bbdad4ddf154772fedbdd27e464600e943

how can I do a work around for this problem?

**Comment by dinoboff** [comment]
npm package info:

    $ npm view angular-google-maps versions

    [ '2.0.12',
      '2.0.13',
      '2.0.14',
      '2.0.16',
      '2.0.17',
      '2.0.18',
      '2.0.19',
      '2.0.20',
      '2.1.0',
      '2.1.1',
      '2.1.3',
      '2.1.4',
      '2.1.5',
      '2.1.6',
      '2.2.0',
      '2.2.1',
      '2.3.0',
      '2.3.1',
      '2.3.2',
      '2.3.3' ]

**Comment by OrKoN** [comment]
@pocesar afaik, the commit installs are not supported by the GitHub registry. I would try to contact the owner of js-rich-marker and ask them to create a GitHub release for this version. Or you could fork this project, create a release or a tag and write an override that will use that version instead of the original one.

**Comment by pocesar** [comment]
@OrKoN but then I'd need to fork both? angular maps and js-rich-marker?

**Comment by OrKoN** [comment]
just install angular-google-maps with -o "override" where it tells jspm to use your fork of js-rich-marker https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm#map-configuration

**Comment by pocesar** [comment]
worked thanks!

```
jspm install npm:angular-google-maps -o "{'dependencies': { 'js-rich-marker': 'github:pocesar/js-rich-marker' }}"
```
