### ISSUE TITLE
snabbdom-to-html fails to find index.js file

### ISSUE THREAD

**Issue by perrin4869** [jspm/jspm-cli#1984]
Trying to run `cycle.js` with `JSPM` I ran into the following issue, where `snabbdom-to-html`, which is a dependency, failed to load. I think this is because of an unhandled case where a `browser` main file is specified.

I put up a repo reproducing the problem [here](github.com/perrin4869/jspm_snabbdom.git)
To run, do `npm install && jspm install && http-server -c-1`.
Or I am currently hosting that demo [here](https://julian.dotcore.co.il/) too for convenience.
Thanks!

**Comment by guybedford** [comment]
Thanks I'll look into this when I can.

**Comment by guybedford** [comment]
You can fix this with `jspm install npm:snabbdom-to-html -o main=lib/index.js`.

The reason is that the browser main is not properly resolved in the install conversion process. I've created an issue for this at https://github.com/jspm/npm/issues/144.

**Comment by perrin4869** [comment]
got it, thanks!
