### ISSUE TITLE
How? jspm with uglifyjs-harmony branch

### ISSUE THREAD

**Issue by mkastner** [jspm/jspm-cli#1985]
Please correct me, if I am wrong here.

If understand the dependencies properly then the uglifyjs version, which comes with the jspm installation is _not_ the harmony branch but the master branch of UglifyJS2.

But generator functions currently can only minified by the harmony branch of UglifyJS2.

Thus my question:

How do I setup jspm in such a manner that it uses the uglifyjs-harmony branch as a dependency instead of the master branch?

**Comment by guybedford** [comment]
Is the uglifyjs harmony branch stable enough to use do you think? We can certainly upgrade to that in the builder if it's good to go now.

**Comment by mkastner** [comment]
No, I don't think so. At least from what I understand from that project. However, having said (resp. written) that – a jspm version, which allows opting for the harmony branch of uglify js would be helpful in moving towards a es6 workflow.

It might not be production ready yet, but once it will be, it will smoothen the transition.

**Comment by oligot** [comment]
I just discovered that there is an ES6+ aware minifier based on the Babel toolchain (still in beta):
https://github.com/babel/babili

As it comes with a preset, this could be used with [plugin-babel](https://github.com/systemjs/plugin-babel/). (I haven't tested it yet, so it's just theoretical for now)

**Comment by oligot** [comment]
And here is the blog post introducing babili:
https://babeljs.io/blog/2016/08/30/babili
