### ISSUE TITLE
Stop JSPM from rewriting paths

### ISSUE THREAD

**Issue by Bolza** [jspm/jspm-cli#1986]
I have this kind of structure:

```
app/
├── public/
│   ├── jspm_packages
│   ├── config.js
```

And i need config.js to look like this

```
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
    [...]
  },
```

So i set `package.json` in this way

```
    "directories": {
      "packages": "public/jspm_packages"
    },
    "configFile": "public/config.js",
```

After `jspm init` i get `config.js` re-written i this way

```
  baseURL: "public",
  paths: {
    "github:*": "public/jspm_packages/github/*",
    "npm:*": "public/jspm_packages/npm/*"
    [...]
  },
```

Which is absolutely wrong as `public` is my served folder and the file path must not start with it.
I find the fact that setting `directories.packages` in package.json rewrites `paths` in config.js confusing and limitating. We should cut down on all this "magic" and just rely on the user to setup his own configuration.

**Comment by dinoboff** [comment]
I think you need to set package.json with:
```
"directories": {
  "baseURL": "public/"
}
```

**Comment by amenadiel** [comment]
jspm init should walk you through every setting suggesting the default. For your case, the packages directory is relative to baseurl, so you either not set it or set it to "jspm_packages".

**Comment by guybedford** [comment]
jspm 0.17 goes through more effort not to alter user-set paths.

**Comment by charles-smith** [comment]
@guybedford, I think I'm running into a similar (possibly the same issue) with 0.17 beta. I'm trying to run a project that will use the same config for both a desktop (via electron) and website front ends, so I'm modifying the config like so:

    var __dirname = __dirname || '.'
    
    System.config({
      // ...
      paths: {
        '*': `${__dirname}/src/*.js`,
        'github': `${__dirname}/jspm_packages/github/*`,
        'npm:*': `${__dirname}/jspm_packages/npm/*`
      },
      //...
    })

However whenever I update packages it completely removes __dirname from the paths (replacing them with a `'.'`).

Is this what got fixed? If so, is it working on master?

**Comment by guybedford** [comment]
@charles-smith jspm doesn't support non-string identifiers for values as it needs to be able to perform re-serialization of the configuration to make changes.

Supporting arbitrary configuration parse trees is certainly something we can look at in future, but the only reason configuration is a JS file and not a JSON file in the first place is to support including it with a script tag, not to allow users to make it based on arbitrary computation. Unintended consequences I guess...
