### ISSUE TITLE
Angular module loading out of order. Module is not declared issue according to angular.

### ISSUE THREAD

**Issue by jvelezc** [jspm/jspm-cli#1988]
So these tree should load in this specific order... 

So slate.component is loaded first
Then slate.component should load openedClaims.component finally my main bootstrapper should do the rest. This is not working. What concept am I missing?

<pre>
import "./slate.component";
var app: ng.IModule = angular.module(names.Modules.slate,
        [
            "components"
     
        ]);
export default app;

angular.element(document).ready(() => {
    angular.bootstrap(document, ["app"]);
});
</pre>

This is slate.component
<pre>
import "./openedClaims.component";
angular
    .module("components", []);
</pre>

this is: openedClaims.component

<pre>
angular
    .module("components")
      .component("openedClaimsPanel", {
        template: "hello world"
    });
</pre>
`

What I am trying but has failed... below shows the real path of my app.Full source is here:
https://github.com/jvelezc/GridStackDemo
<pre>
System.config({
  baseURL: "/",
  defaultJSExtensions: true,
  transpiler: "typescript",
  meta: {
      "app/modules/slate.component": {
          format:"global",
          deps: ["app/components/openclaims/openedClaims.component"]
      }
  },...
</pre>

**Comment by guybedford** [comment]
What error are you getting here? Modules will execute from the bottom to the top of the dependency tree in ES modules.

**Comment by jvelezc** [comment]
I am getting module has not been declared by angular.

**Comment by jvelezc** [comment]
So i got it to work! The reason is that jspm is lazy loading the module. So for whatever reason it could not detect it. 


Here an example that works! 

Notice the fact that i have

So first I have a main module which purpose is to load other types of modules. Third party, my own , etc.
These modules are for organizational purposes such as directive modules, thirdparty directive, components etc. 


/// <reference path="../../typings/index.d.ts" />
```

import * as angular from "angular";
import {names} from "./angular.global";
import "./modules/slate.controller.module";
import "./modules/slate.directive.module";
import "./modules/slate.service.module";
import "./modules/third.party.module";
import "./modules/slate.component";
var app: ng.IModule = angular.module(names.Modules.slate,
        [
            names.Modules.slateServices,
            names.Modules.slateDirectives,
            names.Modules.slateControllers,
            names.Modules.thirdPartyModules,
            names.Modules.components
     
        ]);

export default app;


angular.element(document).ready(() => {
    angular.bootstrap(document, ["slate"]);
});

```


My slate component module
/// <reference path="../../../typings/index.d.ts" />
```

import {names} from '../angular.global';

angular
    .module(names.Modules.components, []);
//Since i must first declare the module and only then load the sub module I have to put 
//the import statement below the declaration of it.
import * as fixingThisQuirkLazyLoading from '../components/openclaims/openedClaims.component';
var quirkhere = fixingThisQuirkLazyLoading;// only when i use it for something it loads it.

```


finally my implementation of the module

```

/// <reference path="../../../../typings/index.d.ts" />
import {names} from '../../angular.global';
angular
    .module(names.Modules.components)
    //<opened-Claims-Panel></open-Claims-Panel>
    .component(names.Components.openClaimsPanel, {

        template: "hello world"
    });

console.log("works fine"); 
```



So based on this i would suggest the following for your framework. An import eargerly command
importEargerly * from '../components/openclaims/openedClaims.component';

**Comment by dinoboff** [comment]
You could also avoid to use `angular.module` to retrieve an angular module. 

Instead, have the es6 module defining the angular module export it:
```
// src/ng-module.js
import angular from 'angular';

const module = angular.module('myApp', []);

export default module;
```

Then to register a component:
```
// src/components/my-component/index.js
import module from 'my-app/ng-module.js';

module.component({...});
```

Or you can put all angular pluming into one file. The component es6 modules would just have to export the component definitions; they don't register them with angular directly.
```
// src/components/my-component/index.js
export const component = {...};
```

Angular pluming:
```
// src/index.js
import angular from 'angular';
import * as myComponent from 'my-app/components/my-component/index.js'

export const module = angular.module('myApp', []);

module.component('my-component', myComponent.component);

export default module;
```

With this setup all browser and angular specific code can be left out of every modules except one. You components or services can be unit tested with any node test runner like mocha. No need to setup karma.

**Comment by jvelezc** [comment]
Wow i am glad i asked this here. I will try out your answer it looks very good.
