### ISSUE TITLE
Self executing bundle throwing React error: Invariant Violation 

### ISSUE THREAD

**Issue by stonebraker** [jspm/jspm-cli#1989]
Here is a link to the test project:
https://github.com/stonebraker/jspm-systemjs-react-starter

When React components are in play, the app fails to load the self executing bundle created by `jspm bundle-sfx`.

The error that is thrown is:
```
bundle-sfx.js:6 Uncaught Invariant Violation: Minified React error #37; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=37 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

The application (with React components) runs as expected when it is transpiled at runtime as well as when a regular bundle is created using `jspm bundle`. 

The only time the self executing bundle loads successfully is when no React components are utilized.

Is there something I ought to be doing in order to successfully load and run a self executing bundle that includes React components?

Thanks! Any assistance is appreciated.

**Comment by guybedford** [comment]
@stonebraker I'd suggest trying jspm 0.17 here, it deals much better with the different build scenarios due to the conditional loading system added.
