### ISSUE TITLE
jspm should try to resolve ./path/index when doing ./path imports

### ISSUE THREAD

**Issue by rolandjitsu** [jspm/jspm-cli#1990]
I just noticed that when I try to:
```js
import {MyClass} from './shared';
```

SystemJS fails to load the `./shared/index.js` file, but tries to load `./shared.js` instead. Is there any way this can be avoided?

It would make it very easy to export many things from `index.js` and import from one path instead of having to do imports explicitly.

But maybe it's just my own config that breaks that.

**Comment by dinoboff** [comment]
I don't think according to #1580

Maybe you can create package entry like
```js
System.config({
  packages: {
    // meaning [baseURL]/local/package when no other rules are present
    // path is normalized using map and paths configuration
    'src/**': {
      main: 'index.js',
    }
  }
});
```

**Comment by rolandjitsu** [comment]
@dinoboff that does not work when the import is from a subfolder from a package. Say:
```js
packages: {
	'app': {}
}
```

And the `import {MyClass} from './shared';` is from a subfolder of `app` (`app/shared`). It looks like there are some issues when trying to do that.

**Comment by guybedford** [comment]
This is not a feature of the SystemJS resolver.

**Comment by ArmorDarks** [comment]
@guybedford Any chances to make it possible through configuration in future?

**Comment by guybedford** [comment]
@ArmorDarks normalization is configurable through normalization hooks, but this isn't encouraged.

**Comment by matthew-dean** [comment]
I don't get why this is closed. JSPM is supposed to be compatible with Node modules, no? Node.js path resolution will try to look for `shared.js` and then `shared/index.js`. Without this behavior, certain modules aren't compatible. Is there no way to do this?

**Comment by ArmorDarks** [comment]
I guess this is because `System.import` official specs do not support predictive importing, like Node does. Despite I don't like it either, can't fight with specs :(

**Comment by Centaur** [comment]
Specs should be improved.
