### ISSUE TITLE
Cannot install npm:openlayers

### ISSUE THREAD

**Issue by frederikschubert** [jspm/jspm-cli#1992]
When running
```
jspm install npm:openlayers
```
this error pops up:
```
err  Error parsing package.json file /Users/frederik/Development/project/jspm_packages/github/jspm/nodelibs-process@0.2.0-alpha.json
```

**JSPM Version**
0.17.0-beta.22

**Comment by mikz** [comment]
I think this is related to https://github.com/jspm/jspm-cli/issues/1994

Just delete jspm packages and try to reinstall.

**Comment by frederikschubert** [comment]
I tried that but I got the same error when trying again to install npm:openlayers.
I guess it fails because openlayers has a tarball dependency which is not yet supported by jspm. With `jspm@0.16.39` I could install github:openlayers/ol3 but that doesn't work with the 0.17.0.

**Comment by mikz** [comment]
Hm. Makes sense. And then it actually writes empty `jspm_packages/github/jspm/nodelibs-process@0.2.0-alpha.json` and breaks the jspm install.
This is great way to reproduce #1994.

**Comment by frederikschubert** [comment]
@guybedford Do you have any idea how I could get openlayers to install? I tried it with a dependency override but was not successful.

**Comment by guybedford** [comment]
A dependency override sounds like the right approach to me.

**Comment by frederikschubert** [comment]
I tried the [one](https://github.com/jspm/registry/blob/master/package-overrides/github/openlayers/ol3%403.11.2.json) in the registry but it doesn't work.

**Comment by guybedford** [comment]
Configuration issues like this are tracked in the jspm registry (https://github.com/jspm/registry). Please share the details of the bugs you're getting there, with a clear report, and I can try and help you out further.

**Comment by frederikschubert** [comment]
Created https://github.com/jspm/registry/pull/951.
