### ISSUE TITLE
Dependency load order angular-ui/ui-codemirror

### ISSUE THREAD

**Issue by MattLishman** [jspm/jspm-cli#1993]
Hi,

`angular-ui/ui-codemirror` requires `codemirror/codemirror` to run.

I have downloaded both via jspm:
```
jspm install github:codemirror/codemirror
jspm install github:angular-ui/ui-codemirror
```

Then I set the meta for `angular-ui/ui-codemirror` giving it a dependency like so:

```
meta: {
        "angular-ui/ui-codemirror": {
            deps: [
                'codemirror/codemirror'
            ],
            "format": "global"
        }
    }
```

I would then expect to be able to `import 'angular-ui/ui-codemirror'` and have it **first** load `codemirror`.

However, I see `codemirror/codemirror` load afterwards when looking at the chrome network tab.

What am I misunderstanding here?
Or is this a bug?

![image](https://cloud.githubusercontent.com/assets/14980374/17053139/7cf3cdc8-4ff8-11e6-8da4-7c34cff8f02d.png)

**Comment by MattLishman** [comment]
Created a repo with a basic example https://github.com/MattLishman/jspm-dependency-example

**Comment by guybedford** [comment]
Meta doesn't automatically include the main.

So you need to write 

```javascript
meta: {
        "angular-ui/ui-codemirror/path/to/main.js": {
            deps: [
                'codemirror/codemirror'
            ],
            "format": "global"
        }
    }
```

There is a ticket to support this in https://github.com/systemjs/systemjs/issues/1331, I just need to verify the normalization consistency of the approach.

**Comment by MattLishman** [comment]
Unless I misunderstand, I did that and I still see the same thing.

```meta: {
      "angular-ui/ui-codemirror/ui-codemirror.js": {
          "deps": [
              "codemirror/codemirror"
           ],
      }
  },```

Does `angular-ui/ui-codemirror/path/to/main.js` need to point to the wrapper/barrel file (I don't know what to call it, the one jspm produces) or the main file the plugin uses?

I do still see it load `codemirror`, but only **afterwards**

**Comment by guybedford** [comment]
@MattLishman if you're using jspm 0.16 I'd advise the approach of `jspm install angular-ui/ui-codemirror -o "{shim:{ui-codemirror:{deps:['codemirror/codemirror']}}}"`.

**Comment by MattLishman** [comment]
So, I used this command 
```
jspm install github:angular-ui/ui-codemirror -o "{shim:{'ui-codemirror':{deps:['github:codemirror/codemirror@5.17.0']}}}"
```

System still looks like it is loading this file *after* `angular-ui/ui-codemirror` one. 

I also had to include the version in the dependency argument for it to work.

**Comment by guybedford** [comment]
When I try that I get an angular is not defined message.

Perhaps try:

```
jspm install github:angular-ui/ui-codemirror -o "{shim:{'ui-codemirror':{deps:['github:codemirror/codemirror@5.17.0', 'angular']}}}"
```

**Comment by MattLishman** [comment]
I tried that command and I still see the same thing.
I haven't seen that angular is not defined yet though.

When trying all these approaches I still see that `codemirror` is loaded **after** `ui-codemirrior`, *despite* `codemirror` being a dependency of `ui-codemirror`.

I want to essentially say "Whenever loading `ui-codemirror`, load `codemirror` **first**"

**Comment by guybedford** [comment]
@MattLishman on a fresh jspm project in both 0.16 and 0.17, the following doesn't display that to me at all:

```
jspm install angular github:codemirror/codemirror 
jspm install github:angular-ui/ui-codemirror -o "{shim:{'ui-codemirror':{deps:['github:codemirror/codemirror@5.17.0', 'angular']}}}"
```

When running in the browser it seems to complete execution as far as I can see.

Perhaps try adding the `-f` flag to clear any cache, and also removing any overrides in the package.json that may be interfering with the base install.

**Comment by MattLishman** [comment]
The execution completes, but I still see them load in the wrong order.

Perhaps I am not explaining this well.

When I create a fresh project and follow these steps, I still see the issue.

```
npm install jspm
jspm install angular github:codemirror/codemirror
```
_Follow all promts and select defaults to all except using babel_

```
jspm install github:angular-ui/ui-codemirror -o "{shim:{'ui-codemirror':{deps:['github:codemirror/codemirror@5.17.0', 'angular']}}}"
```
Create an `index.html` containing
```
<html>
    <head></head>
    <body>

    <div ng-app="app">
        <div ui-codemirror>

        </div>
    </div>

    <script src="jspm_packages/system.js"></script>
    <script src="config.js"></script>
    <script>
        System.import('./index.js');
    </script>
    </body>
</html>

``` 

and an `index.js` containing
```
"use strict";
var angular = require('angular');
require('angular-ui/ui-codemirror');
angular.module('app', [
    'ui.codemirror'
]);

```

(Apologies for the angular bits, no way to test properly without it though)

From here I see chrome load an execute both files, but not in the order I would expect.
(Unless I am misunderstanding Chrome's network tab)

I see this:
![image](https://cloud.githubusercontent.com/assets/14980374/17175170/daa5b5fe-53fd-11e6-96c2-cfa455c4208c.png)

Which makes me think the order is `ui-codemirror barrel file` -> `ui-codemirror main file` -> `codemirror barrel file` -> `codemirror barrel file`.

This means `codemirror` is loaded last.

I thought the dependencies would mean it was loaded **before** `ui-codemirror`

More like this 
`ui-codemirror barrel file` -> `codemirror barrel file` -> `codemirror barrel file` -> `ui-codemirror main file`.

And I would expect the network tab to look like this: (Sorry for horrible photoshop skills)
<img width="1280" alt="how it should look" src="https://cloud.githubusercontent.com/assets/14980374/17175349/fe56afa2-53fe-11e6-9dbd-087fc1738e14.png">

Does that make sense?

**Comment by guybedford** [comment]
The network order does not mean anything - the execution order is what
matters.

Dependency discovery happens down the tree, not up the tree.

**Comment by MattLishman** [comment]
I see, that's interesting to know. 
I guess I wrongly assumed the code was executed as soon as it was received.

I think this gives me enough information to debug why this isn't working. It's starting to sound like it might not be jspm related.

(I'm not even using codemirror anymore, i'm only doing this to try resolve this github issue)

I think we can probably close this issue, as it seems everything is working as intended for now.
I will reopen if I find anything else.
Unless you think there is anything left to resolve here?

Might as well add a bit of a summary though:

- Meta doesn't automatically include the main. You need to specify this.
- You can shim dependencies using `-o{ shim: "dependency"}`
- The order in which the files are loaded is not important, only the order they are executed.

Thank you for your help with this!
