### ISSUE TITLE
Question: Overwrite "map" setting in config.js of a dependencies dependency via package.json

### ISSUE THREAD

**Issue by schorfES** [jspm/jspm-cli#1995]
Sorry for that complicated title of this issue. I've looked around a lot of documentations and issues, but didn't found the correct way. Let me explain my problem a bit more detailed:

I have two dependencies defined in my `package.json`:

```json
{
   "jspm": {
    "dependencies": {
      "backbone": "npm:backbone@^1.3.3",
      "backbone.geppetto": "npm:backbone.geppetto@^0.7.1"
    }
 }
}
```

I fact that backbone.geppetto is currently a bit rarely maintained and depends on [backbone@~1.1.0](https://github.com/GeppettoJS/backbone.geppetto/blob/master/package.json#L56), both versions of backbone will be installed (@1.3.3 and @1.1.2 via backbone.geppetto) and loaded by systemjs. I don't wan't to load and bundle both versions, so I can edit the `config.js`

```javascript
System.config({
  "map": {
    "npm:backbone.geppetto@0.7.1": {
      "backbone": "npm:backbone@1.3.3" // previously from install "backbone": "npm:backbone@1.1.2"
    }
  }
});
```

The problem is that the `config.js` is git ignored (or will be in the near future), so I need a way to configure this via the `package.json`. I've tried some approaches using the `"map"` setting but didn't get it to work. Is this possible?

Thanks in Advance!

**Comment by guybedford** [comment]
config.js should be checked in - it represents the version lock, while the package.json represents the install range intent.

**Comment by schorfES** [comment]
Okay, but I want install that project as dependency into an other(s). So I don't want to reconfigure the config.js everytime I install it through jspm. I also don't really want to document such steps in a readme. Any suggestions?

**Comment by guybedford** [comment]
Apologies for missing what you were after here... I'd suggest adding an override for backbone.geppetto that allows the backbone dependency to work against a higher version. That override can be checked into the jspm registry to make it apply universally.
