### ISSUE TITLE
build only the changed module and not all 

### ISSUE THREAD

**Issue by Berg-it** [jspm/jspm-cli#1996]
Hi, I use (gulp, jspm, systemjs and babel) with ES6 in project Angularjs. the problem that when I change a file I have to gulp task to launch command js`pm bundle-sfx app/bootstrap app/bootstrap.bundle.js` to create each time the bundle where take few seconde. There's any solution to resolve this kind of problem?

**Comment by guybedford** [comment]
In jspm 0.17, there is the `jspm build --watch` feature for this, which works just like bundle-sfx.
