### ISSUE TITLE
Relative path not resolving from System.import

### ISSUE THREAD

**Issue by forceuser** [jspm/jspm-cli#1997]
i have project structure

```
project
│  jspm_packages
│  node_modules
│  index.html    
│  index.js
│  jspm.config.js
│  package.json
└───app
    │  index.js
    │  module1.js
    │  module2.js
```

**index.js**

```js
import module1 from './module1';
console.log("module1", module1);

System.import('./module2.js').then(module2 => {
    console.log("module2", module2.default);
});
```

**module1** loading from ```/app/module1.js``` but **module2** trying to load from ```/module2.js```

**jspm.config.js**

```js
SystemJS.config({
    paths: {
        "npm:": "jspm_packages/npm/"
    },
    baseURL: "/",
    devConfig: {
        "map": {
            "plugin-babel": "npm:systemjs-plugin-babel@0.0.12"
        }
    },
    transpiler: "plugin-babel",
    packages: {
        "app": {
            "main": "index.js",
            "meta": {
                "*.js": {
                    "loader": "plugin-babel"
                }
            }
        }
    }
});

SystemJS.config({
    packageConfigPaths: [
        "npm:@*/*.json",
        "npm:*.json"
    ],
    map: {},
    packages: {}
});
```

source code https://github.com/forceuser/jspm-issue

_jspm 0.17.0-beta.22_

**Comment by adamburgess** [comment]
>System.import('./module2.js')

try `System.import('./module2.js', __moduleName)` instead.
the module syntax (import x) is resolved easily, but the dynamic import needs to know what the current location is, which is what `__moduleName` provides.

this is documented here: https://github.com/systemjs/systemjs/blob/master/docs/module-formats.md#es6

**Comment by forceuser** [comment]
Oh thanks! missed that part

Anyway is there any reason why not create System (System.loader) instance for every module to store its context like nodejs require does? just for conveniece

**Comment by guybedford** [comment]
We will likely have a scoped contextual loader in future, just waiting for
the specification for it.
