### ISSUE TITLE
System is not defined in an sfx build

### ISSUE THREAD

**Issue by atrauzzi** [jspm/jspm-cli#1998]
I have a project I'm building into an SFX.  Part of what my code is doing is it does reach out to `System.import` at "run time" to grab modules.
The only reason I do this is to dynamically obtain references to them.  I don't actually have a requirement to late-load them.

Anyway, I've got 2 sets of questions based on all this:

 - Is there any way to just obtain already-loaded modules at runtime by some kind of name reference?  Doing this would obviate my current use of `System.import`.

And then:

 - The SFX build is likely trying to use SystemJS to do the runtime load.  Would it be possible to enable runtime loading on a super minified portable profile if I ever wanted that?
 - Is there a way to pre-bundle the full list of modules I know can be runtime-loaded and then really all it's doing is just obtaining references to content that shipped as part of the SFX bundle?

Thanks!

**Comment by guybedford** [comment]
@atrauzzi see the conditional loading system in http://jspm.io/0.17-beta-guide/conditional-loading.html for some ways of doing dynamic resolution.

SFX does not come with System runtime loading, use SystemJS rather for runtime loading, which can itself load SFX bundles.

Prebundling everything is a good bundling approach, but would need to run against the full SystemJS not SFX.

**Comment by atrauzzi** [comment]
I'll investigate and if I end up with any questions, I'm sure I'll bother you or someone else on gitter.

Thanks for the info! :)
