### ISSUE TITLE
Building with core node libs

### ISSUE THREAD

**Issue by tkuminecz** [jspm/jspm-cli#2000]
Hi,

I'm trying to build a module for use in node that imports some core node libraries, `crypto` for example. I run `jspm build app build/app.js --node` and it seems to succeed, but when I run `node build/app.js`, `crypto` is undefined. Digging into the built file a bit, it looks like it's referencing `@node/crypto` but I'm kind of lost after that. How can I get core node libs to resolve?

**Comment by guybedford** [comment]
Thanks, yes that is a bug. Fixed in https://github.com/systemjs/builder/commit/3cdb29c7b5507fae3aecfe52a7d48e81045df43f.

**Comment by guybedford** [comment]
This has been released.
