### ISSUE TITLE
TypeError: Cannot read property 'file:///X' of undefined

### ISSUE THREAD

**Issue by wegorich** [jspm/jspm-cli#2002]
It's seems one of the dependencies modules are updates with bugs. Can you please help clarify witch one is it. 

Please read the error more detail, with the discussion
[TypeError: Cannot read property 'file:///X' of undefined](https://github.com/aurelia/bundler/issues/136)

**Comment by guybedford** [comment]
This should be fixed in the latest SystemJS builder release, jspm release will be made shortly.
