### ISSUE TITLE
Auto optimizations for Bundles

### ISSUE THREAD

**Issue by believer-ufa** [jspm/jspm-cli#2003]
Hello all )

Today i finded a problem with bundles in my application.

Lets imagine i have 3 bundles.

First bundle its a bootstrapper for my app. It contains all main deps like `jquery`, `react` and other.
Second bundle - its a big part of my application which depends from jquery.
Third bundle - other big part of my application which depends from react.

Of course, we can exclude jquery and react through bundle arithmetic. But if project scales in future, it may be difficult.

So what about create some algorithms for automatic optimization all bundles of application? Like in [Webpack](https://github.com/webpack/docs/wiki/code-splitting#chunk-optimization)?

**Comment by guybedford** [comment]
Yes this is certainly a direction SystemJS builder can move in to be more webpack-like. This sort of stuff is tracking in https://github.com/systemjs/builder/issues/511.
