### ISSUE TITLE
jspm build: Cross origin requests / XHR error problems

### ISSUE THREAD

**Issue by cpmech** [jspm/jspm-cli#2005]
Hi,

I'm using jspm@beta (0.17) to build a self-contained bundle; but am getting problems when trying to load the resulting library.

I've followed the tutorial to build my library using:
```bash
jspm build src/main.js dist/mylib.js --skip-source-maps --format umd --global-name mylib
```

And am using as follows:
```javascript
<script src="js/system.js"></script>
<script>
SystemJS.config({
    baseURL: 'dist'
});
SystemJS.import('mylib.js');

var myVar = new mylib.MyClass();

</script>
```

Any help is much appreciated.

**Comment by guybedford** [comment]
What is the exact issue you are getting here? Perhaps try using the CSP build of SystemJS?

**Comment by cpmech** [comment]
Thanks for your response.

I'm trying to bundle an existent project into a static file (mylib.js) and then later load mylib.js into another project (a simple webpage). Ideally I woud load mylib.js as anyother webpage (browser) script; e.g. `<script src="mylib.js></script>`. Unfortunately I don't know how to do this.

I've quickly tried `system-csp-production.js` as well; but am getting an error: _Unexpected anonymous AMD define_...

**Comment by guybedford** [comment]
@cpmech since you're using UMD output you can just include a script tag like that.

If you want to System.import the UMD then you'd need to use:

```javascript
SystemJS.import('dist/mylib.js').then(function(myLib) {
  new myLib.class();
});
```

Note that when System importing, you will not get the global defined as it runs a different branch for the UMD format.

**Comment by cpmech** [comment]
Thank you for your help. And thanks for *jspm* and *systemjs*; both are awesome. Cheers.
