### ISSUE TITLE
jspm bundle arithmetic problem with npm scopes (beginning with @ sign, eg @angular/*)

### ISSUE THREAD

**Issue by Dutchboy** [jspm/jspm-cli#2006]
Hi!!!

I'm trying to exclude all external packages

jspm 0.16 - gulpfile - didn't do fine:
`builder.bundle('main - github:* - npm:* - npm:@* - shared', 'dist/main.js');`

jspm 0.16 - gulpfile - did fine - (I referred to the literal scope angular, which is a bit ugly)
`builder.bundle('main - github:* - npm:* - npm:@angular/* - shared', 'dist/main.js');`

jspm 0.17 - gulpfile - does not work any more
`builder.bundle('main - github:* - npm:* - npm:@angular/* - shared', 'dist/main.js');`

Also.... a difference between 0.16 and 0.17 is the _meaning_ of the` minus sign`... Wihch, I think will show some unwanted results......... 
In 0.16, it meant "exclude the (group of) package(s)"
In 0.17, it means "exclude the (group of) package(s) _AND_ all of the packages that one depends on"
.... In the above codes lines, this resulted in far less (hopefully temporary!) `minus signs `(only `@angular/forms` etc), because by using the `minus sign` for `shared`, for instance `@angular/core` was already excluded.
.... But this will result in unwanted situations - what if I'd do some safety excludes, eg. `main/**/*.spec.ts`, and these `spec.ts` depend upon (test) life code modules, these will be excluded too?...

Any clue?

Also, apart from the above, the produced bundle has:
`System.register("0.src/app/app.routes.ts", ["@angular/router", "./+about/index", "./+home/index"], function(exports_1, context_1) {`
Which exposes/shows the original development paths in the module names.

Is there a way to change them?
(so that the end users do see my logics)
(or back to the module names I originally gave/referred to eg. main/app.routes)
.... EDIT - in my own implementation with **jspm 0.16** I could shorten the "0.src/app/app.routes.ts" to "app.main/app.routes.ts" by adding "app.main/*": "0.src/app/*" to the path... Just tested it, it still works! Sorry :-)

A lot of thanks in advance for answering!

**And I really appreciate the whole system you've built, it is wonderfully coded, even though it has been tiresome to go through it, I do realize it is difficult to document / instruct people to use it...**

**Comment by guybedford** [comment]
I really wouldn't suggest globbing jspm_packages. Perhaps try the external
exclude suggestion in the read me of the systemjs builder documentation.
