### ISSUE TITLE
jspm_packages certain package file referencing to Gruntfile.js

### ISSUE THREAD

**Issue by ekoren82** [jspm/jspm-cli#2008]
Hi.
I have a problem regarding a reference of a certain jspm_packages package file to Gruntfile.js:
I have jspm installed a package named "angular-switcher", and in the directory jspm_packages/npm I have it's reference file (**angular-switcher@0.2.7.js**) that contains the following content:
module.exports = require("**npm:angular-switcher@0.2.7/Gruntfile.js**");

In order to use the angular-switcher package I have to manually update the content to  reference a correct js file:
module.exports = require("npm:angular-switcher@0.2.7/dist/angular-switcher.js");

Is there a way to fix this reference not manually, for example by config.js file?

Thanks,
Eran

**Comment by guybedford** [comment]
Because this is a jspm reference you are making in Node, you could try using:

```javascript
var jspm = require('jspm');
exports.getPath = jspm.normalize('angular-switcher').then(function(normalized) {
  return normalized + '/dist/angular-switcher.js';
});
```

See also `jspm.setPackagePath` for referring to the project.
