### ISSUE TITLE
Requiring css file located in jspm_packages 

### ISSUE THREAD

**Issue by ekoren82** [jspm/jspm-cli#2009]
Hi.
How can I require a css file located in **jspm_packages** (in a ceratin pacakge I have jspm installed) ?
For the meanwhile I see suggestions to copy the css files from jspm_packages to the application assets directory during build (by gulp for example).
**Is there a better way not including copying the css files?**

Thanks,
Eran

**Comment by guybedford** [comment]
You can use:

```
jspm install css
```

and then `import 'x/file.css!'`.

**Comment by ekoren82** [comment]
I already have the css plugin installed and I am using it,but I am not sure how should I get the **css files from jspm_packages** using it.

If for example I have the css file I need location in:
app/jspm_packages/npm/angular-switcher@0.2.7/dist/angular-switcher.css

and in config.js I have the following entry of angular-switcher:
"angular-switcher": "npm:angular-switcher@0.2.7"

What import statement should I approximately write?

Thanks

**Comment by guybedford** [comment]
Try `angular-switcher/dist/angular-switcher.css!`.
