### ISSUE TITLE
JSPM API Inject Documentation Error

### ISSUE THREAD

**Issue by cjkoski** [jspm/jspm-cli#2010]
HI,

Docs here:

https://github.com/jspm/jspm-cli/blob/master/docs/api.md

Say 

_Set the inject option to inject the bundle tree into the configuration file._

But should be:

_Set the i**njectConfig** option to inject the bundle tree into the configuration file._

**Comment by guybedford** [comment]
Thanks, I've included this in https://github.com/jspm/jspm-cli.
