### ISSUE TITLE
Best approach for publishing as JSPM for my scenario

### ISSUE THREAD

**Issue by atrauzzi** [jspm/jspm-cli#2013]
I have a project that's structured roughly as follows:

 - package.json
 - public/
   - jspm.config.js
   - src/
     - SomeReactComponent.tsx
     - legacyshimmed.js

I'd like to be able to require this project from another and make use of the component I've defined.  I'm a bit uncertain however as to what I should be setting in my `package.json` to ensure that the JSPM project consuming this library gets everything "right".

Of specific note:

 - My `jspm.config.js` has a `meta` section defining some global `deps` for `legacyshimmed.js`.
 - I am using typescript
 - I am using TSX/JSX

**Comment by guybedford** [comment]
Perhaps something like - 

```json
{
  "main": "public/src/SomeReactcomponent.tsx",
  "meta": {
    "*.tsx": {
      "loader": "typescript"
    }
  },
  "dependencies": {
    "typescript": "github:frankwallis/plugin-typescript@1.2.3"
  }
}
```

Usually it is advisable to publish compiled sources though, so these workflows haven't been explored that thoroughly.

**Comment by guybedford** [comment]
(the above assumes jspm 0.17 of course)
