### ISSUE TITLE
json3: no such file or directory (Mocha 3)

### ISSUE THREAD

**Issue by screendriver** [jspm/jspm-cli#2014]
I followed the instructions at [Testing and coverage with SystemJS, Mocha + Istanbul](http://guybedford.com/systemjs-mocha-istanbul) and use the latest jspm version `0.17.0-beta.25` but it seems not working on my machine.

I set up a completely new project with `jspm init`. After that I did a `jspm install mocha unexpected --dev` and wrote a `runner.js`

##### runner.js

```js
import Mocha from 'mocha';

SystemJS.import('./tests.js')
.then(function(tests) {
  var runner = new Mocha({
    ui: 'exports',
    reporter: typeof window != 'undefined' ? 'html' : 'spec'
  });
  runner.suite.emit('require', tests);
  return new Promise((resolve, reject) => {
    runner.run((failures) => {
      if (failures)
        reject(failures);
      else
        resolve();
    });
  });
})
.catch(console.error.bind(console));
```

Now when I do a `jspm run runner.js` it fails on the very first line where Mocha gets imported.

```sh
err  (SystemJS) ENOENT: no such file or directory, open '/Users/me/Development/foo/json3'
  Error: ENOENT: no such file or directory, open '/Users/me/Development/foo/json3'
      at Error (native)
  Error loading /Users/me/Development/foo/json3 as "json3" from /Users/me/Development/foo/jspm_packages/npm/mocha@3.0.1/lib/context.js
```

**Comment by guybedford** [comment]
Are you using Mocha 3 here? I haven't tested the workflow against that version yet.

**Comment by screendriver** [comment]
Ups, I didn't tested it with Mocha `2`. I replaced Mocha `3` with `2` and the error disappears.

I will update the issue title for that.

**Comment by guybedford** [comment]
I believe I fixed up the override now so it should work with `jspm install mocha -fo` if you have an existing install.

**Comment by screendriver** [comment]
Thank you. It's working now 👍
