### ISSUE TITLE
JSPM+TypeScript package doesn't configure extensions in consuming project

### ISSUE THREAD

**Issue by atrauzzi** [jspm/jspm-cli#2015]
I'm trying to use a JSPM package that uses TypeScript from within another JSPM project - so this is a pure JSPM scenario.
Unfortunately, whenever I go to include a `.ts` or `.tsx` file inside my consuming project, JSPM tries to load using the extension `.ts.js` or `.tsx.js`.

When I am in the package and just running it using it's own JSPM configuration and loading, everything imports fine.

It seems like when I consume my package from another JSPM project, it doesn't think the package is using typescript anymore.

I'm currently working around this by placing `"defaultExtension": "tsx",` inside of my `jspm.config.js` for the package, but I suspect this should be getting wired up automatically by JSPM based on what the package itself defines for default extension behaviour?

**Comment by guybedford** [comment]
Try adding `defaultExtension: 'tsx'` into the package.json of the project you're loading the typescript from?
