### ISSUE TITLE
Canonical Name Issue on folder with " - "

### ISSUE THREAD

**Issue by eheaton** [jspm/jspm-cli#2016]
I have a project that's in a folder with a name structure like `/Projects/ClientName - ProjectName` and I get this error when I try to build:

```
[Error: Unable to calculate canonical name to bundle file:///Users/username/Projects/ClientName.js. 
Ensure that this module sits within the baseURL or a wildcard path config.]
```

If I remove the ` - ` and just have a space, the build process works.

**Comment by guybedford** [comment]
Tracking in https://github.com/systemjs/builder/issues/668.
