### ISSUE TITLE
babelOptions ignored in Cordova Apps

### ISSUE THREAD

**Issue by screendriver** [jspm/jspm-cli#2018]
jspm `0.17.0-beta.25`: I tried to write React components that should run in my Cordova app. On my Desktop Browser everything works fine but in my Cordova app I get a

```
Error: (SystemJS) file:///android_asset/www/index.js: Unexpected token (6:11)
      4 | class Button extends React.Component {
      5 |   render() {
    > 6 |     return <input type="button" value="Hello"></input>;
        |            ^
      7 |   }
      8 | }
```

My `jspm.config.js` looks like this:

``` js
packages: {
    "loginer": {
      "main": "index.js",
      "format": "esm",
      "meta": {
        "*.js": {
          "loader": "plugin-babel",
          "babelOptions": {
            "plugins": ["babel-plugin-transform-react-jsx"]
          }
        }
      }
    }
  }
```

I can provide a sample app where you can reproduce it if you want.

Ah and by the way: `"format": "esm",` will also be ignored. I tried to write following in my `index.js`

``` js
document.addEventListener('deviceready', () => {
  console.log('hello');
}, false);
```

and it complains about a syntax error at the arrow function. If I import something it works. So I guess both errors belong together.

**Comment by guybedford** [comment]
The arrow function error, does it look the same as the error you provided:

```
Error: (SystemJS) file:///android_asset/www/index.js: Unexpected token (6:11)
      4 | class Button extends React.Component {
      5 |   render() {
    > 6 |     return <input type="button" value="Hello"></input>;
        |            ^
      7 |   }
      8 | }
```

Or is it a different type of error?

The above error there on the jsx is a Babel error which means that Babel is working but the Babel JSX plugin isn't being applied for some reason.

**Comment by screendriver** [comment]
It's a different type of error. I **can** use arrow functions but only if I import something, like React. After that I use JSX syntax and getting the error above.

So yes: babel is working (after I import something) but `babel-plugin-transform-react-jsx` does not get applied to my code.

Should I open a new issue for the `"format": "esm"` issue? Do you want a sample project where you can reproduce it?

**Comment by guybedford** [comment]
These are two separate errors. It sounds like it's an issue with your meta not applying actually.

Remember that `*.js` meta only applies to the baseURL path... you may want to try some exact meta variations from that.

**Comment by screendriver** [comment]
> you may want to try some exact meta variations from that.

What do you mean with that?

I've created a [sample project](https://github.com/screendriver/ignored-babeloptions) for you. Notice that I changed the `baseURL` to `.` because Cordova requests all files with the `file://` protocol instead of `http://`. If you leave the `baseURL` to `/` it can't load any files.

**Comment by guybedford** [comment]
I mean that it is worth carefully verifying that the meta is even applying in the first place. Are the modules you are loading definitely contained within the baseURL?

**Comment by guybedford** [comment]
An exact meta can be set like:

```javascript
System.config({
  meta: {
    'file:///path/to/file.js': { deps: ['does-not-exist'] } // simple test to see if we get 'does-not-exist' not found
  }
});
```

**Comment by screendriver** [comment]
I triey that with `file:///android_asset/www/index.js` and `file:///www/index.js` and `file:///index.js` and didn't saw any error console statements about `does-not-exist`. It seems that meta was completely ignored.

**Comment by guybedford** [comment]
Are you sure the above are the right file URLs to be using? Usually these
are file paths on the local file system?

**Comment by screendriver** [comment]
Yes, these file parths are on the local file system. In an [Apache Cordova](https://cordova.apache.org) app the whole application is wrapped in a [WebView](https://developer.android.com/reference/android/webkit/WebView.html) that serves all files from the local file system (`file:///`) instead of a web server. So all local requests has to use the `file:///` protocol.

**Comment by guybedford** [comment]
@screendriver what I'm saying here is that `/android_asset/www/index.js` doesn't seem like a file path in your local file system?

**Comment by screendriver** [comment]
The app runs on an Android device within an Android WebView that hosts all files in the Cordova App. Within that all files will be hosted from the `www` directory. Its absolute path is `file:///android_asset/www/`

**Comment by guybedford** [comment]
So you think we're 100% certain then that meta is just not supported in this environment? I'm wondering then what might be causing that.

To verify can you at least share the values of `Object.keys(System._loader.registry)` and `Object.keys(System.meta)` which provided that exact meta config?

**Comment by screendriver** [comment]
Yes I am sure because if I don't use JSX to write my React component it works. With jspm `0.16` everything works. The only thing you have to change in every project is the `baseURL` to `.` instead of `.` because of the local `file://` url.

```js
console.log('-----')
console.log(System._loader.registry)
console.log(Object.keys(System._loader.registry))
console.log('######')
console.log(Object.keys(System.meta))
```

produces

```
-----
undefined
Uncaught TypeError: Cannot convert undefined or null to object
```

`console.log(Object.keys(System.meta))` alone prints an empty Array.

**Comment by guybedford** [comment]
Apologies it's ._loader.modules. Although how come you have no meta?
Running System.config({ meta: { '... }}) will always show up on
System.meta. So it looks like you really do have no meta!?

**Comment by screendriver** [comment]
> So it looks like you really do have no meta!?

Yes. As I already said before :wink:

**Comment by guybedford** [comment]
@screendriver so to summarize, our shortest replication of the issue is that the following assertion does not hold in your environment:

```javascript
System.config({
  meta: {
    test: { format: 'esm' }
  }
});
assert(System.meta[System.normalizeSync('test')].format == 'esm')
```

Can you please confirm that is the isolated issue here.

**Comment by perrin4869** [comment]
@screendriver I am actually working on a react cordova app right now, and using jspm, no problems at all thus far. I build my scripts with the following:

```js
gulp.task('scripts-mobile', ['lint'], () => {
  const builder = new Builder();

  // mangle minifies variable names to save space
  return builder.buildStatic('mobile', 'mobile/www/index.js', {
    sourceMaps: false,
    minify: true,
    mangle: true,
  })
  .catch(err => gutil.log(err));
});
```

A slightly redacted `jspm.config.js`:

```js
SystemJS.config({
  paths: {
    "npm:": "jspm_packages/npm/",
    "github:": "jspm_packages/github/",
    "web/": "js/web/",
    "mobile/": "js/mobile/",
    "admin/": "js/admin/"
  },
  browserConfig: {
    "baseURL": "/client"
  },
  devConfig: {
    "map": {
      "plugin-babel": "npm:systemjs-plugin-babel@0.0.12",
      "babel-plugin-transform-react-jsx": "npm:babel-plugin-transform-react-jsx@6.8.0",
      "babel-plugin-transform-class-properties": "npm:babel-plugin-transform-class-properties@6.11.5"
    },

   ...

  },
  transpiler: "plugin-babel",
  packages: {
    "web": {
      "main": "main.js",
      "format": "esm",
      "map": {
        "./config.js": {
          "~production": "./config.dev.js"
        }
      }
    },
    "mobile": {
      "main": "main.js",
      "format": "esm"
    },
    "admin": {
      "main": "main.js",
      "format": "esm"
    }
  },
  meta: {
    "*.jsx": {
      "babelOptions": {
        "plugins": [
          "babel-plugin-transform-react-jsx",
          "babel-plugin-transform-class-properties"
        ]
      }
    },
    "*.json": {
      "loader": "json"
    }
  }
});
```

Hope it helps, tell me if you need more help!

**Comment by screendriver** [comment]
@guybedford I modified my `index.html` to following

```html
<!DOCTYPE html>
<html>
    <head>
        <meta name="format-detection" content="telephone=no">
        <meta name="msapplication-tap-highlight" content="no">
        <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width">
        <link rel="stylesheet" type="text/css" href="css/index.css">
        <script type="text/javascript" src="jspm_packages/system.js"></script>
        <!-- <script type="text/javascript" src="jspm.config.js"></script> -->
        <title>Hello World</title>
    </head>
    <body>
        <div id="main"></div>
        <script type="text/javascript" src="cordova.js"></script>
        <script type="text/javascript">
        System.config({
          meta: {
            test: { format: 'esm' }
          }
        });
        console.log(System.meta[System.normalizeSync('test')].format == 'esm')
        </script>
    </body>
</html>
```

The output is `true`. So this seems to work. But not when I include the `jspm.config.js`. You can **easily** reproduce everything with my [sample](https://github.com/screendriver/ignored-babeloptions) project.

@perrin4869 thank you for your help but I don't use bundling at the moment. I simply created a plain new project, did a simple `jspm init` and point all URL's to the `www` directory. There was nothing more that I did.
