### ISSUE TITLE
Getting JSDOM to work with jspm run

### ISSUE THREAD

**Issue by xiankai** [jspm/jspm-cli#2019]
I am trying to run jsdom inside my mocha test in JSPM - but am only able to get it to work after 2 workarounds. 

I am running a simple `import { jsdom } from 'jsdom'` to trigger these errors.

1. It seems that the following override in `package.json` of jsdom is ignored
    ```
        "browser": {
            "canvas": false
        }
    ```

   This seems similar to #1981. The error is:
    ```
    err  (SystemJS) ENOENT: no such file or directory, open '/Users/kj/jspm-test/canvas'
      Error: ENOENT: no such file or directory, open '/Users/kj/jspm-test/canvas'
          at Error (native)
      Error loading /Users/kj/jspm-test/canvas as "canvas" from /Users/kj/jspm-test/jspm_packages/npm/jsdom@9.4.1/lib/jsdom/utils.js
    ```

    I managed to get around it by doing `jspm install npm:jsdom -o override.json` where `override.json` is:
    ```
    {
    	"map": {
    	 	"canvas": "@empty",
    	}
    }
```

2. This time, it seems that jspm doesn't follow the node behavior when requiring a folder - to check if an `index.js` exists, then require that instead. I had the following error:
    ```
    err  (SystemJS) ENOENT: no such file or directory, open '/Users/kj/jspm-test/jspm_packages/npm/jsdom@9.4.1/lib/jsdom/living.js'
      Error: ENOENT: no such file or directory, open '/Users/kj/jspm-test/jspm_packages/npm/jsdom@9.4.1/lib/jsdom/living.js'
          at Error (native)
      Error loading /Users/kj/jspm-test/jspm_packages/npm/jsdom@9.4.1/lib/jsdom/living.js as "./jsdom/living" from /Users/kj/jspm-test/jspm_packages/npm/jsdom@9.4.1/lib/jsdom.js
    ```

    I had to replace all instances of the `living` folder with `living/index.js` instead. To get this to work would require me to fork the jsdom repository.

Is there any better way to work around these?

**Comment by guybedford** [comment]
Which version of jspm are you running here? Have you tried 0.17?

**Comment by xiankai** [comment]
@guybedford Sorry, forgot to mention - I'm on 0.17.0-beta.22

**Comment by guybedford** [comment]
@xiankai this is actually working correctly. The reason being that the `browser: { canvas: false }` applies only in the browser.

If you look at the file `jspm_packages/npm/jsdom\@9.4.2.json`, you should see the correctly generated configuration:

```json
{
  "main": "lib/jsdom.js",
  "format": "cjs",
  "meta": {
    "*": {
      "globals": {
        "process": "process"
      }
    },
    "*.json": {
      "format": "json"
    },
    "lib/jsdom/browser/resource-loader.js": {
      "globals": {
        "Buffer": "buffer/global"
      }
    },
    "lib/jsdom/living/blob.js": {
      "globals": {
        "Buffer": "buffer/global"
      }
    },
    "lib/jsdom/living/file-reader.js": {
      "globals": {
        "Buffer": "buffer/global"
      }
    },
    "lib/jsdom/living/xhr-sync-worker.js": {
      "globals": {
        "Buffer": "buffer/global"
      }
    },
    "lib/jsdom/living/xhr-utils.js": {
      "globals": {
        "Buffer": "buffer/global"
      }
    },
    "lib/jsdom/living/xmlhttprequest.js": {
      "globals": {
        "Buffer": "buffer/global"
      }
    },
    "lib/jsdom/utils.js": {
      "globals": {
        "Buffer": "buffer/global"
      }
    }
  },
  "map": {
    "./lib/jsdom/living": "./lib/jsdom/living/index.js",
    "canvas": {
      "browser": "@empty"
    },
    "vm": {
      "browser": "./lib/jsdom/vm-shim.js"
    }
  }
}
```

I made one change to this file, altering `"canvas": {  "browser": "@empty"  },` to `"canvas": "@empty"`, and that seems like it fixes it.

The reason for this is that when you applied the custom map override, it then skipped auto-generating the other map overrides.

The best approach is to edit this generated configuration file manually - that is actually the recommended workflow for altering package configurations (even though it is not documented I know!).

**Comment by xiankai** [comment]
@guybedford Thanks for helping me to troubleshoot this! I did not know that individual configuration was preserved inside the `jspm_packages` folder - I was trying to edit `package.json` manually but it did not change anything.
