### ISSUE TITLE
jspm bundle only respects top level exports 0.17 beta 25

### ISSUE THREAD

**Issue by wolfmanfx** [jspm/jspm-cli#2020]
Hi,

I wasted a bit time during bundling (sfx), as it seems JSPM only respects exports from the toplevel ts file.
I used a app.ts which imports the needed ts files (which are required for the bundling). The ts files have
exports but these are ignored. The top level had none so I had a esmodule with no exports inside. Also looking at the code I think its not that easy to support deep level exports.

Is this expected behavior? Than a documentation clarification would be great.

**Comment by guybedford** [comment]
Yes only the top-level module is exposed.

**Comment by wolfmanfx** [comment]
Ok than a docu upgrade would be cool - becuase I splitted a TS app into several packages.
