### ISSUE TITLE
Contents of package gets copied when different casing is used

### ISSUE THREAD

**Issue by Karolusrex** [jspm/jspm-cli#2021]
When importing a package from two files using different casing, the contents of that package gets copied twice in the bundle.

**Comment by guybedford** [comment]
SystemJS is a case-sensitive loader, because URLs are case sensitive. jspm may be able to help more in this area in future.

**Comment by Karolusrex** [comment]
The behaviour I would like is that incorrectly cased filenames fail to load. Would that be possible?

**Comment by guybedford** [comment]
This behaviour is really up to the web server being used when loading in the browser.

When loading in Node, `fs.readFile` is case insensitive so we are bound to that. Note also that the Node require is case insensitive so we do need to follow this pattern to support Node requires.

**Comment by Karolusrex** [comment]
I see, thanks for the info
