### ISSUE TITLE
Custom configuration

### ISSUE THREAD

**Issue by snarum** [jspm/jspm-cli#2022]
Hi
I'm introducing jspm in an existing project. In the old configuration I used gulp and webpack to bundle and distribute my website. During this process I also replaced the url of my Rest API in a typescript file to match the target environment, before typescript compilation.

Now I'm trying to find a good way of doing the deploy configuration/replacements without introducing gulp again. For instance, can I add my urls to the config.js file and read this runtime? Is this posible? Any other sugestions? 

I'm quite new to web development, but I would assume it is a common scenario for many applications that the client side needs to be configured during deploy. I haven't been able to find much documentation on the topic though.

Any thoughts are appreciated.

**Comment by guybedford** [comment]
Typically you might have a production configuration that is used in
addition to the main jspm configuration. Then the main jspm configuration
should be written in a way that it uses portable paths that can apply to
both the production and non production modes - eg you don't want to
reference full irks but plain names usually in this config.
