### ISSUE TITLE
Issue w/ JSPM/SystemJS: System is not defined

### ISSUE THREAD

**Issue by simonwidjaja** [jspm/jspm-cli#2023]
I have a problem with a bare JSPM setup. I'm developing an extension for an Adobe tool (CEP). It's basically a WebView w/ baked in nodejs that runs in the tool.

I'm already failing to get the basic JSPM setup to work. In the browser everything works just fine. But in the embedded CEP environment I always get the error that

`System is not defined`

Logging System to the console shows that it is available (see screenshot below).

It's obviously a problem with JSPM/SystemJS or the CEP environment. But I can eliminate the latter. Since I successfully worked on another CEP project with an more complex setup w/ JSPM, Aurelia etc. I had NO problems there... But I have to get this basic setup to run asap. So ANY help appreciated!

<img width="1050" alt="screen shot 2016-08-10 at 09 06 21" src="https://cloud.githubusercontent.com/assets/1757398/17545552/ee8a9126-5edd-11e6-8aae-39b1b67a6d5a.png">

**Comment by guybedford** [comment]
I guess this would depend on how you are including SystemJs. Perhaps
carefully log the code that expects system and system itself to see if it
is a problem of execution order.

**Comment by simonwidjaja** [comment]
Thanks for the reply:
This is the index.html

`<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Test</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>

    
    <h1>TEST</h1>
    <button onclick="window.location.reload(true);" style="position: fixed; right: 0;">↺</button>

    <script src="jspm_packages/system.js"></script>
    <script src="config.js"></script>
    <script>
      System.import('bootstrap');
    </script>

  </body>
</html>`

**Comment by guybedford** [comment]
Is `window.System` set to the `SystemJS` loader instance?

**Comment by guybedford** [comment]
Actually I think I know what this is... we had a similar issue with Node Webkit.

Try adding removing the branch at this line in the `system.js` source - https://github.com/systemjs/systemjs/blob/master/lib/global-eval.js#L89, so that it falls back to the eval execution over the `require('vm')` execution.

If you can confirm if that works that would be a great help to integrate a fix here.

**Comment by simonwidjaja** [comment]
Not sure what exactly you mean. I'm pretty new not SystemJS. How can I find out if it is?
I basically setup a new jspm project from scratch and I just added the 3 scripts as shown above (system.js, config.js and System.import('bootstrap'). I'm using Babel...

**Comment by simonwidjaja** [comment]
Ah yes. Now that you mention it.... I'm pretty sure CEP is using Node Webkit somehow... I will try this right now. Thanks for your help!

**Comment by simonwidjaja** [comment]
Thumbs up. After switching the eval process everything works fine. You saved my day (and weekend ;).

**Regarding the fix:**
This check is failing:
`var nwjs = typeof process != 'undefined' && process.versions && process.versions['node-webkit'];
`
In the CEP context the process object looks like this (might help for identifying the node-webkit environment):
<img width="754" alt="screen shot 2016-08-19 at 13 08 05" src="https://cloud.githubusercontent.com/assets/1757398/17808090/4f9079cc-660e-11e6-92b1-8be4b62ab85c.png">

This seems to be a good starting point:
`process.__node_webkit = 1`

**SOLUTION:** So this works in my environment:
`var nwjs = typeof process != 'undefined' && process.versions && (process.versions['node-webkit'] || process.__node_webkit === 1);`

**Comment by guybedford** [comment]
Thanks for the follow-up here.

I've added a feature detection approach here in https://github.com/systemjs/systemjs/commit/a614724543974f2343e739b81b0f472310e9ac77. Let me know if you're able to try that out too.

**Comment by guybedford** [comment]
Released in the latest SystemJS.
