### ISSUE TITLE
Zlib error on package install from npm.

### ISSUE THREAD

**Issue by aindlq** [jspm/jspm-cli#2024]
I'm trying to install new typescript typings with jspm, e.g `jspm install npm:@types/react`,  `jspm install npm:@types/react-dom`.

These packages are very simple and contain some json and .d.ts files. I was able to successfuly install `@types/react`, but jspm fails on `@types/react-dom`:

```
     Updating registry cache...
     Downloading npm:@types/react-dom@0.14.14
ok   Installed npm:@types/react@0.14 (0.14.29)

err  Error: incorrect header check
    at Zlib._handle.onerror (zlib.js:363:17)
```

jspm version:
```
0.17.0-beta.25
Running against local jspm install.
```

I tried both node v4.4.7 and v6.3.1 and getting the same result. I can successfully install this package with npm, so looks like this is something jspm specific.

**Comment by NervosaX** [comment]
@aindlq I had the same error (on a different package), with success upgrading from v5.9.1 to v5.12.0 of node. Maybe try that?

**Comment by guybedford** [comment]
This may have been fixed by the PR at https://github.com/jspm/npm/pull/148. I'm aiming to post a jspm-npm release later today with the fix to try.

Or of you know of a Node bug that this relates to please share too.

**Comment by guybedford** [comment]
This should be fixed in the latest jspm-npm.
