### ISSUE TITLE
Unable to install angular-translate due to version mismatch

### ISSUE THREAD

**Issue by jonkoops** [jspm/jspm-cli#2025]
When installing [angular-translate](https://github.com/angular-translate/angular-translate) the dependency `"angular": ">=1.2.26 <=1.6"` is resolved to `npm:angular@~1.6.0`, which is a non-existent version of Angular.

**What should happen:**
It should match the latest version of Angular that is >=1.2.26 and  <=1.6. Which is currently version 1.5.8.

**What happens:**
It matches a non-existent version of Angular. And shows the following error:

```
err  Installing npm:angular-translate@2.11.1, no version match for npm:angular@~1.6.0
```

**How to reproduce:**
1. Create a new project using JSPM
2. Run `$ jspm install npm:angular`
3. Run `$ jspm install npm:angular-translate`

**Comment by guybedford** [comment]
jspm doesn't support arbitrary version ranges, this is tracked in https://github.com/jspm/jspm-cli/issues/1253.

You can fix this with an override:

```
jspm install npm:angular-translate -o "{dependencies:{ angular: '~1.5.8' }}"
```

Note that the dependencies override does need to include all other dependencies as well, otherwise no other dependencies will be installed.
