### ISSUE TITLE
depCache from map

### ISSUE THREAD

**Issue by caperavensoftware** [jspm/jspm-cli#2031]
I am writing an aurelia application with http2.
I would like to use depCache so that when aurelia-bootstrap is loaded all the aurelia dependencies are downloaded at the same time.

the map in config.js already defines relations so is it possible to define the depCache from the existing map configuration instead of trying to point it to a particular file.

Alternatively it would be great to just take all the dependencies defined in map and consolidate that into one minified bundle file.

**Comment by guybedford** [comment]
You can create dep cache in jspm via `jspm depcache x`
