### ISSUE TITLE
OAuth for JSPM install

### ISSUE THREAD

**Issue by kendavis2** [jspm/jspm-cli#2032]
Due to the GitHub rate limit, I would like to be able to use a client id and secret when running JSPM install since the GitHub organization feature allow OAuth, but not personal access tokens. 

Attaching a personal access token to my CI process can be an issue since CI servers are not tied to developer accounts.

Thanks,
Kenneth

**Comment by guybedford** [comment]
It would be interesting to look into supporting this certainly. This should be tracked at the https://github.com/jspm/github project.

**Comment by kendavis2** [comment]
Thank you for the response. I have an open issue with GitHub to see if there is a way around it on their side. I will update this issue if something is determined to work. Should I just post this same question on the [https://github.com/jspm/github](https://github.com/jspm/github) project?
