### ISSUE TITLE
Incremental builds don't work with bundle --watch --inject

### ISSUE THREAD

**Issue by antimatter15** [jspm/jspm-cli#2033]
When running `jspm bundle --watch --inject`, it seems like only the first change is built incrementally— the subsequent changes seem to spawn entirely new Builder instances. 

It seems that `--inject` flag updates jspm.config.js whenever a build is completed, and so the next time an update is fired, it notices that the configuration file has changed and then creates a new builder (trashing the cache in the process). 

    if (changeWasConfigFile) {
        config.loader = new JspmSystemConfig(config.pjson.configFile);
        builder = new Builder();
        return;
      }

I'm using `0.17.0-beta` and I have `watchman` installed.

**Comment by guybedford** [comment]
Thanks, ok we need to treat injection as an exception here.

**Comment by guybedford** [comment]
Fixed in https://github.com/jspm/jspm-cli/commit/db137a6e69cb8f4c3caa9c59799e5502849d4d61.

**Comment by guybedford** [comment]
Released in 0.17.0-beta.26.
