### ISSUE TITLE
Feature Request: clientBaseUrl config in package.json

### ISSUE THREAD

**Issue by RayFoss** [jspm/jspm-cli#2035]
We are extremely close to being able to purge the config.js file and just have jspm generate it. The only thing that is missing is the baseUrl line, which we have to add back in manually. It would be fantastic if package.json had a jspm.directories.clientBaseUrl setting that got added to the generated config.js file.

Thank You

**Comment by guybedford** [comment]
The `config.js` file is the version lock of the application, which should actually be checked in. So ensuring all information can be captured in the package.json is not a priority.
