### ISSUE TITLE
0.16.43 Version

### ISSUE THREAD

**Issue by oscarfuquen** [jspm/jspm-cli#2037]
The new version is throwing me the following error "index.ts:22 Uncaught TypeError: Module npm:angular@1.5.7/angular not declared as a dependency."

I rolled back to 0.16.42 and it worked fine

**Comment by VaidotasSm** [comment]
I have same issue - after bundle-sfx getting same errors with various modules on different apps (angular, lodash...). E.g.:
Uncaught TypeError: Module npm:lodash@4.13.1/lodash.js not declared as a dependency.
Uncaught TypeError: Module github:angular/bower-angular@1.5.7/angular not declared as a dependency.

**Comment by guybedford** [comment]
Any chance of a replication here?

**Comment by guybedford** [comment]
Simple steps to reproduce the issue would be ideal.

**Comment by atrauzzi** [comment]
I may be encountering something similar this morning...

![image](https://cloud.githubusercontent.com/assets/115199/17855839/5bb8eb88-6840-11e6-9364-57a6fc91589e.png)

**Comment by guybedford** [comment]
Fixed in 0.17.0-beta.26 and 0.16.44.

**Comment by atrauzzi** [comment]
@guybedford - Thank you so much.

**Comment by oscarfuquen** [comment]
@guybedford thank you very much for your prompt help. amazing job!!!!
