### ISSUE TITLE
jspm link not applying local overrides

### ISSUE THREAD

**Issue by ccantill** [jspm/jspm-cli#2038]
I cloned unifly-aero/powergrid from github, and ran `jspm link github:unifly-aero/powergrid@master`.
I have a project I'm already using this component on and it was working fine. But if I run `jspm install --link github:unifly-aero/powergrid@master` in that project, it stops working. If I compare the two versions, it seems the local overrides are not applied:

```
diff -r /home/christoph/.jspm/linked/github/unifly-aero/powergrid@master/web/promise.js jspm_packages/github/unifly-aero/powergrid@master/web/promise.js
1c1,3
< define(['es6-promise'], function(es6promise) {
---
> /* */ 
> "format amd";
> define(["@empty"], function(es6promise) {
```

**Comment by guybedford** [comment]
Perhaps try using jspm 0.17 here.
