### ISSUE TITLE
NPM package size.

### ISSUE THREAD

**Issue by Hypercubed** [jspm/jspm-cli#2040]
Currently, jspm v0.17 install is ~28MB (that includes deps).  Wondering why docs, test, and testlibs are not .npmignored.

**Comment by guybedford** [comment]
Thanks, I've added https://github.com/jspm/jspm-cli/commit/2af75631c6ad516bb1b73d41b16c173687b20f5a.

**Comment by guybedford** [comment]
Released in latest... thanks for spotting this.
