### ISSUE TITLE
Permission denied trying to install firebase on mac

### ISSUE THREAD

**Issue by dpix** [jspm/jspm-cli#2041]
Hi, not sure if this belongs here or firebase, or it may just be an issue with permissions on my own machine but...

I am getting this error whenever I run `jspm install`: 

```
warn Error on build
     Error: EACCES: permission denied, open '/Users/dan/.jspm/packages/npm/firebase@3.3.0/app.js'
         at Error (native)

warn Installation changes not saved.
```

running as sudo I don't get the error but I don't want to be installing under my user. I have completely removed the .jspm folder in my home directory and tried to re-install but still no luck. Seems odd that it consistently errors on firebase and nothing else.

I'm using version 0.16.42 of jspm

**Comment by tamird** [comment]
I see this same error with `jspm install npm:@types/history`:
```
jspm install npm:@types/history
     Looking up npm:@types/history
     Updating registry cache...
     Downloading npm:@types/history@2.0.33

warn Error on download for npm:@types/history
     Error: EACCES: permission denied, open '/Users/tamird/.jspm/packages/npm/@types/history@2.0.33/lib/actions.d.ts'
         at Error (native)

err  Error downloading npm:@types/history.

warn Installation changes not saved.
```

**Comment by guybedford** [comment]
I believe this is fixed in the latest version of jspm-npm.

**Comment by BiloLwabona** [comment]
Is this definitely fixed? I'm getting the same issue when installing firebase as follows:

`jspm install npm:firebase`

However, if I don't specify *npm*, it works, because it uses the github repo of firebase.

`jspm install firebase`

Please note that the simple `npm install firebase` also works.

**Comment by guybedford** [comment]
@BiloLwabona this is definitely working fine here. Do make sure you're running the latest jspm-npm version (0.30.0 currently).
