### ISSUE TITLE
Mocha - testing files with dependancies

### ISSUE THREAD

**Issue by linnett** [jspm/jspm-cli#2042]
I've got a couple of issues with unit testing js files. 

First error: If the js file I am testing has no dependancies, it's working fine. However, when there are imports at the top, it does not work and throws an error saying it cannot find the file:
```
Error: Cannot find module 'myModule'
```
Do I somehow need to link the jspm.config file to the process and if so, how?

Second error: When I hard code the dependancy link to the file, I'm getting a syntax error that I wouldn't usually get when testing ES6 files: 
```
constructor(options = {}) {
                      ^
SyntaxError: Unexpected token =
```
Do I need to do something to tell it my dependancies are ES6? 

I am running the following from the command line: `mocha <test filename here> --compilers js:babel-register`. 

The top of my test file looks like this:
```
import 'jsdom-global/register';
import chai from 'chai';
import MyModule from './MyModule';

const expect = chai.expect;

describe('MyModule', function() {
```

I am using `"babel-register": "^6.11.6"`. 
Thanks for any help you can provide.

**Comment by dinoboff** [comment]
It won't work. You need to use the mocha API. Something like:
```
var Mocha = require('mocha');
var jspm = require('jspm');
var loader = new jspm.Loader(); // load package and jspm.config.js

var runner = new Mocha({ ui: 'bdd' });

// set up the global variables
runner.suite.emit('pre-require', global, 'global-mocha-context', runner);

return loader.import('my-packages/tests.js').then(function(tests) {
  return new Promise((resolve, reject) => {
    runner.run((failures) => {
      if (failures)
        reject(failures);
      else
        resolve();
    });
  });
})
.catch(console.error.bind(console));
```

You can find more details on [Guy Belford blog post about it](http://guybedford.com/systemjs-mocha-istanbul).

It works well except for error stack which link to transpiled code instead of the source (it might be a regression and an issue with my setup).
