### ISSUE TITLE
jspm doesn't install package that installs with npm

### ISSUE THREAD

**Issue by robhicks** [jspm/jspm-cli#2044]
I'm trying to install [skatejs-named-slots](https://github.com/skatejs/named-slots). 

It installs fine with npm but when I attempt to install it with jspm (0.17.0-beta.25)  it throws the following error:

```
jspm install npm:skatejs-named-slots
Updating registry cache...
ok   Installed npm:debounce@^1.0.0 (1.0.0)
ok   Installed npm:date-now@1.0.1 (1.0.1)

err  Installing npm:skatejs-named-slots@1.1.0, no version match for github:joscha/custom-event-polyfill@de24bd9
```
I have verified that that commit github:joscha/custom-event-polyfill@de24bd9 does not exist so I am not surprised that the jspm installation fails except for not understanding how npm can/does:
```
npm install skatejs-named-slots
skatejs-named-slots@1.1.0 node_modules/skatejs-named-slots
├── custom-event-polyfill@0.2.2
└── webcomponents.js@0.7.21
```

**Comment by dinoboff** [comment]
AFAIK, jspm doesn't support npm's github dependencies targetting a commit hash.

**Comment by guybedford** [comment]
Yes exactly as @dinoboff mentions, jspm doesn't support commit hashes from github.

**Comment by robhicks** [comment]
Are there any plans to do so?.

**Comment by guybedford** [comment]
Not at the moment, as it would require a rewrite of the endpoint API to support a "pull" over a "push"-based API.
