### ISSUE TITLE
arithmetic bundle documentation?

### ISSUE THREAD

**Issue by pcompassion** [jspm/jspm-cli#2050]
I 'd like to bundle jquery, underscore, etc as a bundle and have other bundles to download this bundle for dependencies.

I believe `  jspm bundle app/**/* - [app/**/*] dependency-bundle.js --inject` is the way to do that but I don't get the syntax.  

Does it mean for all the files under app (`app/**/*) except for all the files under app (`[app/**/*]`) (?? doesn't make sense..), 
create `dependency-bundle.js`?

I'm working with Django and there's no common parental directory such as `app`.  

Typical django directory structure for static files looks like below.

static/app-a/../a.js
static/app-b/../b.js

where `static` is the baseUrl.

How can I create the dependency-bundle.js ?

**Comment by dinoboff** [comment]
Would that work?
```
jspm bundle app-a/**/* + app-b/**/* - [app-a/**/*] - [app-b/**/*] dependency-bundle.js --inject
```

**Comment by pcompassion** [comment]
I guess that would work.  Thank you!

Btw, what does `app-a/**/*` and `[app-a/**/*]` mean? 
Below are my guesses, but not sure if it's correct.

`app-a/**/*` = all the app module which acts as the entry from html under `app-a` directory
`[app-a/**/*]` = all the javascript files (modules) under `app-a` directory

**Comment by dinoboff** [comment]
I think without brackets, it include a module and its dependencies. With brackets, it includes just that module.

**Comment by pcompassion** [comment]
Oh I guess then, 
`app-a/**/*` means all the modules under app-a and all its dependencies
`app-a/**/*` means all the modules under app-a but not including dependencies.

Thank you!
