### ISSUE TITLE
npm package causes ReferenceError

### ISSUE THREAD

**Issue by snarum** [jspm/jspm-cli#2051]
I've ported a Angular2/typescript project from webpack/gulp to jspm and it works like a charm. Almost. I need to have a filesaver library included to be able to save files from the project, so I have added the npm package "browser-filesaver". Adding it works fine, but runtime I get

    ReferenceError: saveAs is not defined

I have checked in the debugger that jspm loads the FileSaver.js file which is a part of the npm package, and saveAs is defined here. My minimalistick project looks like this:

app.component.ts

    import 'zone.js';
    import { Component } from '@angular/core';
    import 'browser-filesaver'
    
    @Component({
        selector: 'my-app',
        template: '{{welcome}} <button type="button" (click)="onClick()">Click Me!</button>'
    })
    export class AppComponent {
        welcome: string = 'Hello from Angular2!'
        onClick()
        {
            console.log("klikking");
            saveAs(null,"hei.txt");
        }
    }

boot.ts

    import 'core-js';
    import 'reflect-metadata';
    import { bootstrap } from '@angular/platform-browser-dynamic';
    import { AppComponent } from './app.component';
 
    bootstrap(AppComponent);

index.html

    <!doctype html>
    <html>
    <head>
    <base href="/testsite/"/>
        <meta charset="utf-8">
    </head>
    <body>
        <my-app></my-app>
        <script src="jspm_packages/system.js"></script>
        <script src="config.js"></script>
        <script>System.import('app/boot')</script>
    </body>
    </html>

Attached is the complete project.

I have tried other npm packages that don't give me this problem, for instance chart.js.

Any comments are appreciated.

[filedownloadtest.zip](https://github.com/jspm/jspm-cli/files/442138/filedownloadtest.zip)

**Comment by guybedford** [comment]
Perhaps try `import fileSaver from 'browser-filesaver'`? It's best not to assume global references will exist.

**Comment by snarum** [comment]
If I do that the FileSaver.js file is not downloaded at all. Probably because there isn't anything called fileSaver in the .js file. The only thing that is there is the saveAs() method.

**Comment by snarum** [comment]
I figured out a solution, but it looks super funky:
If I, in my app.component.ts file type:
    import FileSaver from 'browser-filesaver'
the networking window in chrome does not show any download of file FileSaver.js
But if i write 
    import saveAs from 'browser-filesaver'
the file is downloaded.

To use the saveAs() method I then have to write:
    saveAs.saveAs(myBlob,'filename.txt');

To me it seems like a bug in JSPM that the FileSaver.js file is not downloaded in the first example.

Anyway. It works for me now,

**Comment by dinoboff** [comment]
I tried it with jspm 0.17.0-beta.25
```
jspm install npm:browser-filesaver
```

And those import variation:
```
import FileSaver from 'browser-filesaver';
console.log('default', FileSaver.saveAs);

// import * as BF from 'browser-filesaver';
// console.log('*', BF.saveAs);

// import {saveAs} from 'browser-filesaver';
// console.log('saveAs', saveAs);
```

It works each time.
