### ISSUE TITLE
Consider renaming of `jspm_packages` to `jspm_modules`

### ISSUE THREAD

**Issue by ArmorDarks** [jspm/jspm-cli#2054]
Hello

First of all, thank you for SystemJS and JSPM. I can't say we didn't have few troubles with JSPM, but it solved a lot of issues for us. Our workflow definitely would be worse without it. Keep doing great work :+1: 

Now, back to issue.

It seems that `jspm_packages` has inconsistent with npm modules directory naming.

A lot of people expects it to be named `jspm_modules` and amount of [Google search results](https://www.google.com.ua/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=%22jspm_modules%22&pws=0)  only proving it. Even in this repository issues you will see a lot of `jspm_modules` mentions.

This isn't surprising. People always been looking at JSPM as analog of npm but for non-Node JavaScript, and therefor we can't blame them for expecting of similar behavior and consistent naming.

For sure, we can argue a lot about are those really packages or modules, and is it JSPM got naming wrong, or npm has been wrong at first place. I think, it will lead us to nowhere. npm in some sense already established standard, and might be wiser to follow it, for sake of consistency.

**Comment by guybedford** [comment]
You can configure this yourself via the following in the package.json:

```
{
  "directories": {
    "packages': "jspm_modules"
  }
}
```

or by running `jspm init -p` and following the prompts.

**Comment by ArmorDarks** [comment]
Thanks for reply.

This issues is not about configuration possibilities, but about standardization and incorporation in future versions of JSPM.

**Comment by guybedford** [comment]
Breaking changes like this aren't really easy to make. To make such a breaking change would require a very strong reason and benefit, which I'm not sure I can see here though. For example it's like asking Bower to rename `bower_components` to be called `bower_modules`, not really a possibility at this point unfortunately.

**Comment by ArmorDarks** [comment]
It would be best if we could leave this issue open for public discussion,

JSPM isn't 1.0.0, and 0.17.0 already breaking _a lot_. If we want to change something to better, it would be better time now, than latter.

**Comment by guybedford** [comment]
@ArmorDarks my point specifically is that I don't think there is a justification of the benefit for the cost. I'm not saying it's impossible, but just that we'd need a very good reason. `jspm_packages` was chosen because `node_modules` was Node-specific. When the node_modules resolution algorithm was put together, npm was in its very first stages, and the concept of a fully-encasulated local package environment was still forming. I'd argue node_modules has become node_packages, and that's what jspm_packages represents.
