### ISSUE TITLE
jspm.import times out, cannot load module with require directly

### ISSUE THREAD

**Issue by chadfurman** [jspm/jspm-cli#2057]
When I try to import the following code, the jspm.import times out for longer than 5 seconds.
```
// file at: "../../../app/scripts/components/book.js"
m = require('mithril');

module.exports = {
  controller: function() { /*...*/ },
  view: function(ctrl) {
    return m('.book')
  }
}
```

Setup:
```
jspm.import("../../../app/scripts/components/book.js").then(function(component){ 
  callback();     
})
```

This is used in a test runner.  When I require the component directly, it cannot find mithril because I installed mithril using jspm.  

I also tried using setPackagePath:
```
    jspm.setPackagePath("/home/user/code/project/");
```

and

```
    jspm.setPackagePath("/home/user/code/project/app/jspm_packages");
```

this is my package.json: https://gist.github.com/chadfurman/12942db2c08eceb9c1db27ad76ba6f13

I'm wondering why import is timing out?  What am I doing wrong?

**Comment by oligot** [comment]
Hi,

I don't know if this could help you but I just created a small project to show how to use Mithril with Jspm: https://github.com/oligot/mithril-es6-modules.

I've installed mithril with `jspm install mithril` and I use it with
```js
import m from 'mithril';
```
as can be seen [here](https://github.com/oligot/mithril-es6-modules/blob/9726a1dca2c73609064eba496503869b57cd8b5f/app.js#L1)

**Comment by chadfurman** [comment]
Thank you.  I actually have no trouble using Mithril in the browser with jspm.  It's when I go to run my front-end tests that use mithril-query and require me to load in the components.

The components require mithril, which is serviced by JSPM / System.js -- ultimately, requiring the component into a variable fails because the component cannot find mithril.  Loading the component with jspm.load causes the test to time out.

**Comment by guybedford** [comment]
@chadfurman you may just need to add an error handler to your promise here.
