### ISSUE TITLE
Struggling to import a library that needs access to a global

### ISSUE THREAD

**Issue by polyclick** [jspm/jspm-cli#2058]
Ok, I've been trying for hours to get this thing to work, but I can't figure out how to do it. I'm currently back on 0.16.45. I made a short detour to 0.17-beta to test if I can get this thing working, but that version results in even more errors :p.

So, back to 0.16.45, I'm trying to include https://github.com/janpantel/angular-sails into my project:

`jspm install github:janpantel/angular-sails`

But it needs: https://github.com/balderdashy/sails.io.js, so I input:

`jspm install github:balderdashy/sails.io.js`

Then I try to import them like this:

```
import 'balderdashy/sails.io.js'
import 'janpantel/angular-sails'
```

But I get an error:

`system.js:4 Uncaught (in promise) Error: (SystemJS) io is not defined(…)`

(Since both are libraries that you normally include with a <script> tag, polluting the global scope, I don't need to import their contents into an import variable (i think, unsure here))

This error comes from the angular-sails library. It needs access to a global variable `io` so that it can pass it into its own self-executing function. But for some reason it can't seem to find this. So I thought: ok, this is normal in a modular approach, I probably need to expose the `io` object from `sails.io.js` as a global, that `angular-sails` can find it in the global scope.

I tried everything: changing the `map`, adding a `shim` configuration, setting the format to global, tried using the `meta` function, tried to do some `overrides`. Nothing worked.

This is an issue I've been struggling with a LOT. But most of the times I seem to be able to figure it out with some fooling around with configuration settings. But not this time. Does anybody have a clue what I need to do to expose the `io` variable from `sails.io.js` in the global namespace?

Thanks!

**Comment by guybedford** [comment]
Try a shim like `jspm install github:janpatel/angular-sails -o "{shim:{'index':{deps:['sails.io.js']}}}"`
