### ISSUE TITLE
Errors when importing npm:stardust

### ISSUE THREAD

**Issue by denchen** [jspm/jspm-cli#2060]
I'm using `jspm@0.17.0-beta.28` with React, and I've installed [`stardust@0.38.1`](https://github.com/TechnologyAdvice/stardust) (Semantic UI) via jspm. I've added `import { Button } from 'stardust';` in my `main.js` as a test, and I'm getting "`root.Date is undefined`" errors in Firefox (and a similar error in Chrome). I'm using `react@15.3.0`. 

    Error: (SystemJS) root.Date is undefined
	now@http://localhost.corp.yahoo.com:8080/jspm_packages/npm/lodash@4.15.0/now.js:20:3
	setData@http://localhost.corp.yahoo.com:8080/jspm_packages/npm/lodash@4.15.0/_setData.js:27:17
	createWrap@http://localhost.corp.yahoo.com:8080/jspm_packages/npm/lodash@4.15.0/_createWrap.js:104:26
	ary@http://localhost.corp.yahoo.com:8080/jspm_packages/npm/lodash@4.15.0/ary.js:26:10
	castFixed@http://localhost.corp.yahoo.com:8080/jspm_packages/npm/lodash@4.15.0/fp/_baseConvert.js:286:37
	wrap/</<@http://localhost.corp.yahoo.com:8080/jspm_packages/npm/lodash@4.15.0/fp/_baseConvert.js:459:31
	arrayEach@http://localhost.corp.yahoo.com:8080/jspm_packages/npm/lodash@4.15.0/_arrayEach.js:15:9
	wrap/<@http://localhost.corp.yahoo.com:8080/jspm_packages/npm/lodash@4.15.0/fp/_baseConvert.js:452:7
	arrayEach@http://localhost.corp.yahoo.com:8080/jspm_packages/npm/lodash@4.15.0/_arrayEach.js:15:9
	wrap@http://localhost.corp.yahoo.com:8080/jspm_packages/npm/lodash@4.15.0/fp/_baseConvert.js:451:5
	baseConvert@http://localhost.corp.yahoo.com:8080/jspm_packages/npm/lodash@4.15.0/fp/_baseConvert.js:486:12
	convert@http://localhost.corp.yahoo.com:8080/jspm_packages/npm/lodash@4.15.0/fp/convert.js:15:10
	@http://localhost.corp.yahoo.com:8080/jspm_packages/npm/lodash@4.15.0/fp/startsWith.js:2:12
	@http://localhost.corp.yahoo.com:8080/jspm_packages/npm/lodash@4.15.0/fp/startsWith.js:1:31
	@http://localhost.corp.yahoo.com:8080/jspm_packages/npm/lodash@4.15.0/fp/startsWith.js:1:2
	@http://localhost.corp.yahoo.com:8080/jspm_packages/npm/stardust@0.38.1/dist/lib/META.js:8:20
	@http://localhost.corp.yahoo.com:8080/jspm_packages/npm/stardust@0.38.1/dist/lib/META.js:1:31
	@http://localhost.corp.yahoo.com:8080/jspm_packages/npm/stardust@0.38.1/dist/lib/META.js:1:2
	@http://localhost.corp.yahoo.com:8080/jspm_packages/npm/stardust@0.38.1/dist/lib/index.js:145:14
	@http://localhost.corp.yahoo.com:8080/jspm_packages/npm/stardust@0.38.1/dist/lib/index.js:1:31
	@http://localhost.corp.yahoo.com:8080/jspm_packages/npm/stardust@0.38.1/dist/lib/index.js:1:2
	@http://localhost.corp.yahoo.com:8080/jspm_packages/npm/stardust@0.38.1/dist/elements/Button/Button.js:19:12
	@http://localhost.corp.yahoo.com:8080/jspm_packages/npm/stardust@0.38.1/dist/elements/Button/Button.js:1:31
	@http://localhost.corp.yahoo.com:8080/jspm_packages/npm/stardust@0.38.1/dist/elements/Button/Button.js:1:2
	@http://localhost.corp.yahoo.com:8080/jspm_packages/npm/stardust@0.38.1/dist/elements/index.js:7:15
	@http://localhost.corp.yahoo.com:8080/jspm_packages/npm/stardust@0.38.1/dist/elements/index.js:1:31
	@http://localhost.corp.yahoo.com:8080/jspm_packages/npm/stardust@0.38.1/dist/elements/index.js:1:2
	@http://localhost.corp.yahoo.com:8080/jspm_packages/npm/stardust@0.38.1/dist/addons/Confirm/Confirm.js:13:17
	@http://localhost.corp.yahoo.com:8080/jspm_packages/npm/stardust@0.38.1/dist/addons/Confirm/Confirm.js:1:31
	@http://localhost.corp.yahoo.com:8080/jspm_packages/npm/stardust@0.38.1/dist/addons/Confirm/Confirm.js:1:2
	@http://localhost.corp.yahoo.com:8080/jspm_packages/npm/stardust@0.38.1/dist/addons/index.js:7:16
	@http://localhost.corp.yahoo.com:8080/jspm_packages/npm/stardust@0.38.1/dist/addons/index.js:1:31
	@http://localhost.corp.yahoo.com:8080/jspm_packages/npm/stardust@0.38.1/dist/addons/index.js:1:2
	@http://localhost.corp.yahoo.com:8080/jspm_packages/npm/stardust@0.38.1/dist/index.js:7:15
	@http://localhost.corp.yahoo.com:8080/jspm_packages/npm/stardust@0.38.1/dist/index.js:1:31
	@http://localhost.corp.yahoo.com:8080/jspm_packages/npm/stardust@0.38.1/dist/index.js:1:2
	
	Evaluating http://localhost.corp.yahoo.com:8080/jspm_packages/npm/lodash@4.15.0/fp/startsWith.js
	Evaluating http://localhost.corp.yahoo.com:8080/jspm_packages/npm/stardust@0.38.1/dist/lib/META.js
	Evaluating http://localhost.corp.yahoo.com:8080/jspm_packages/npm/stardust@0.38.1/dist/lib/index.js
	Evaluating http://localhost.corp.yahoo.com:8080/jspm_packages/npm/stardust@0.38.1/dist/elements/Button/Button.js
	Evaluating http://localhost.corp.yahoo.com:8080/jspm_packages/npm/stardust@0.38.1/dist/elements/index.js
	Evaluating http://localhost.corp.yahoo.com:8080/jspm_packages/npm/stardust@0.38.1/dist/addons/Confirm/Confirm.js
	Evaluating http://localhost.corp.yahoo.com:8080/jspm_packages/npm/stardust@0.38.1/dist/addons/index.js
	Evaluating http://localhost.corp.yahoo.com:8080/jspm_packages/npm/stardust@0.38.1/dist/index.js
	Error loading http://localhost.corp.yahoo.com:8080/web/main.js

I originally [opened an issue against Stardust](https://github.com/TechnologyAdvice/stardust/issues/458#issuecomment-244197371), but they closed it as they don't think it's specifically related to their package. So now I'm checking with you guys to see if there's something I may possibly have misconfigured somewhere (very likely as I'm still new to both React and jspm), or there's an actual bug.

**Comment by marthinus-engelbrecht** [comment]
From what I can see in the _root.js code is that it seems to try to establish the global environment of your application whether it's node or whether it's in the browser and then assigns that to the root variable in now.js. What is strange is regardless of whether you are in the browser or on node `root.Date`(aka the offending code) should be defined.  Can you open up your application in the browser and then type self.Date and then window.Date?

**Comment by denchen** [comment]
This is what I get in Chrome:

    > window.Date;
    <- Date() { [native code] }
    > self.Date;
    <- Date() { [native code] }   

Could it somehow be something in my configuration or how my app is set up? (I will be honest though, I'm not the original owner to the application I'm working on, and I haven't touched a lot of the configuration, so I haven't ever delved into how everything is set up, jspm/npm/Grunt/Node/React-wise.)

**Comment by marthinus-engelbrecht** [comment]
I don't think this is a SystemJS issue, SystemJS is just reporting on it. The only thing I can think is that something is overriding the `self` global. To confirm,  can you put a `console.log('self date: ' + self.Date, 'root date: '  + root.Date)` below [this](https://github.com/lodash/lodash/blob/4.15.0-npm/_root.js#L7) code in your lodash module?

**Comment by guybedford** [comment]
I just tried `jspm install npm:startdust@0.38.1` and importing that in Firefox seems to work fine for me. I also tried `jspm install npm:lodash` and importing `lodash/now` which is what seems to be giving the issue and that also ran ok.

**Comment by denchen** [comment]
@marthinus-engelbrecht This is what I get in the console (Firefox) with that code:

    self date: function Date() {
      [native code]
    } root date: function Date() {
      [native code]
    }

Also, I created a repo that I'm hopeful can reproduce the problem for you guys:
https://github.com/denchen/jspm-errors

It's taken from my original repo, where I tried to remove as much fluff as possible. The **caveat** is, there's still probably a ton in there that's not relevant, but I didn't know what else could be safely removed. As I've noted above, I'm not the original creator of the repo I'm working on; I'm just taking it over, and there's still a bunch of stuff I don't quite understand about the entire setup. In fact, if you see something obviously incorrect with respect to the jspm part of the setup, do let me know!

That repo, if you just do `npm install`, `jspm install`, and then `grunt serve:dev`, you should be able to see the console errors that I see.

**Comment by guybedford** [comment]
Unfortunately I have to insist on minimal replications these days.. Just don't have the time to clone and run large projects, or take the risk of dependencies with viruses (a very real threat too).

**Comment by guybedford** [comment]
Please do let me know if you manage to isolate this issue further at all.
