### ISSUE TITLE
Make 0.17 the Master and push to NPM

### ISSUE THREAD

**Issue by AckerApple** [jspm/jspm-cli#2061]
Awfully bold of a suggest from an outsider: Please make 0.17 the github master and update npm

Moving to 0.17 solved so many of my jspm package linking issues when including jspm projects into other jspm projects, follow?

Thank you kindly for your great work! Jspm has completely changed my world for the better.

Feel free to close this issue at any time.

**Comment by Martin-Andersen** [comment]
@AckerApple Are you using 0.17 in a production workflow? I really want to jump on the 0.17 wagon.

**Comment by bmayen** [comment]
0.17 betas are already published to NPM.

**Comment by AckerApple** [comment]
@bmayen, please educate me on 0.17 on NPM... It appears to be 0.16

I suppose their is a branch command or a completely different package? I searched around before reply to you and 0.16 is what is installed from: https://www.npmjs.com/package/jspm

@Martin-Andersen, I am using 0.17 to bundle in dev and then build to compile for production. And works remarkably fantastic. INFACT! I'm so thrilled to report I've stopped using [jspm-watch](https://www.npmjs.com/package/jspm-watch) and started using the 0.17 --watch argument to watch for file changes!

JSPM 0.17 really set my ship straight. Hella happy (slight item: my package.json size is huge with 0.17 mark-up but the trade of for how it-just-works is sooo so so so so so so worth it)

**Comment by bmayen** [comment]
Oh, you're right! I've been on 0.17 for so long, I forgot we're pulling it from github still :P

**Comment by AckerApple** [comment]
Seeing your dog icon was worth the chime in.

0.17 for President in '16 !!!!

**Comment by dinoboff** [comment]
0.17.0-beta versions have being on npm for a while
```
> npm view jspm@^0.17.0-beta.0 version
jspm@0.17.0-beta.2 '0.17.0-beta.2'
jspm@0.17.0-beta.3 '0.17.0-beta.3'
jspm@0.17.0-beta.4 '0.17.0-beta.4'
jspm@0.17.0-beta.5 '0.17.0-beta.5'
jspm@0.17.0-beta.6 '0.17.0-beta.6'
jspm@0.17.0-beta.7 '0.17.0-beta.7'
jspm@0.17.0-beta.8 '0.17.0-beta.8'
jspm@0.17.0-beta.9 '0.17.0-beta.9'
jspm@0.17.0-beta.10 '0.17.0-beta.10'
jspm@0.17.0-beta.11 '0.17.0-beta.11'
jspm@0.17.0-beta.12 '0.17.0-beta.12'
jspm@0.17.0-beta.13 '0.17.0-beta.13'
jspm@0.17.0-beta.14 '0.17.0-beta.14'
jspm@0.17.0-beta.15 '0.17.0-beta.15'
jspm@0.17.0-beta.16 '0.17.0-beta.16'
jspm@0.17.0-beta.17 '0.17.0-beta.17'
jspm@0.17.0-beta.18 '0.17.0-beta.18'
jspm@0.17.0-beta.19 '0.17.0-beta.19'
jspm@0.17.0-beta.20 '0.17.0-beta.20'
jspm@0.17.0-beta.21 '0.17.0-beta.21'
jspm@0.17.0-beta.22 '0.17.0-beta.22'
jspm@0.17.0-beta.23 '0.17.0-beta.23'
jspm@0.17.0-beta.24 '0.17.0-beta.24'
jspm@0.17.0-beta.25 '0.17.0-beta.25'
jspm@0.17.0-beta.26 '0.17.0-beta.26'
jspm@0.17.0-beta.27 '0.17.0-beta.27'
jspm@0.17.0-beta.28 '0.17.0-beta.28'
```

You can install the latest with:
```
npm install jspm@beta
```

**Comment by dinoboff** [comment]
ps: I think @guybedford if waiting for better docs to push 0.17 as the latest/default one.

**Comment by AckerApple** [comment]
Thanks for being so informative. Your info is very helpful. Closing issue

**Comment by guybedford** [comment]
Yes exactly updating docs etc here is the issue. Unfortunately at the current rate of things, it seems like jspm 1.0 will be released before jspm 0.17! I blame the maintainers.

**Comment by AckerApple** [comment]
I was going to recommend going to 1.0 as jspm really seems ready for public consumption.

Guy, is 1.0 a branch or just what 0.17 will become?

**Comment by guybedford** [comment]
1.0 is just an idea... it may still be a while yet unfortunately.
