### ISSUE TITLE
Install/update a module and have it resolve its dependencies using its config.js

### ISSUE THREAD

**Issue by ghost** [jspm/jspm-cli#2062]
Hi 

I'm using 'jspm version 0.16.45'

I've been looking at the documentation and playing with `jspm install somepackage` and `jspm update somepackage` and it seems to always try to resolve the dependencies of the package to the highest possible semver version.  If I understand [this](https://github.com/jspm/jspm-cli/blob/master/docs/installing-packages.md#resolution-algorithm) paragraph correctly it's designed that way. 

Unfortunately, in our case, this is not desired. We are trying to keep our build pipelines as predictable as possible and we are planning to make a conscious effort every 2 weeks to update each package's dependencies. This allows us to be more controlled and isolate changes that have broken a build. 

Is there a way I can tell `jspm install somepackage` and `jspm update somepackage` look at the locked version in the config.js? 

I know I can just lock the versions in the package.json but then we loose the ability to run `jspm update` on the packages when we desire to consciously update to the latest semver.  I've tried the '--lock' flag but I don't think I fully understand its purpose. It seems to just update the semver in the package.json.

**Comment by guybedford** [comment]
@marthinus-engelbrecht this can be done via `jspm install/update somepackage --lock` which should update `somepackage` while keeping all other dependencies locked.

**Comment by marthinus-engelbrecht** [comment]
Thanks for the reply. I will try it again as soon as I get a chance. I was most probably just doing something wrong.

**Comment by marthinus-engelbrecht** [comment]
@guybedford I can confirm `jspm install/update somepackage --lock` just does nothing for my scenario. I'm sure I'm misunderstanding something. I've created a quick demonstration of my problem. You can do the below to recreate it:

1. `git clone https://github.com/marthinus-engelbrecht/package-a.git`
2. `cd package-a`
3. `npm install`
4. `jspm install`
5. `jspm update github:marthinus-engelbrecht/package-b --lock`

You will see that even though there is a version 1.0.3 for `package-b`, and the semver in the `package.json` allows an update, it won't update. Nothing happens.

If you `jspm update github:marthinus-engelbrecht/package-b` it will update `package-b` to 1.0.3 and `package-c` to 1.0.2, which is undesired.  I want `package-c` remain at the same version.

Ultimately, I would like to just update `package-b` to its latest version according to the semver in [package.json](https://github.com/marthinus-engelbrecht/package-a/blob/master/package.json#L16) of `package-a`. But keep all the dependents of `package-b` to what is specified in its [config.js](https://github.com/marthinus-engelbrecht/package-b/blob/master/config.js#L20)

**Comment by guybedford** [comment]
Perhaps try using `jspm install github:marthinus-engelbrecht/package-b --lock` here rather?

If so, this may be a bug in the update function that it is still locking the provided argument.

**Comment by marthinus-engelbrecht** [comment]
Tried `jspm install github:marthinus-engelbrecht/package-b --lock`. It just changes the semver in the package.json to the short-hand, but doesn't install anything. See the below git status and git diff.

```
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   package.json

no changes added to commit (use "git add" and/or "git commit -a")
```

```
diff --git a/package.json b/package.json
index 22ffe05..b98c5c9 100644
--- a/package.json


+++ b/package.json
@@ -13,7 +13,7 @@
   },
   "jspm": {
     "dependencies": {
-      "marthinus-engelbrecht/package-b": "github:marthinus-engelbrecht/package-b@^1.0.1",
+      "marthinus-engelbrecht/package-b": "github:marthinus-engelbrecht/package-b",
       "marthinus-engelbrecht/package-c": "github:marthinus-engelbrecht/package-c@^1.0.1"
     },
     "devDependencies": {
```

**Comment by marthinus-engelbrecht** [comment]
Also tried updating to `0.17.0-beta.28` and it behaves the same.

**Comment by guybedford** [comment]
Sure thanks for the update. A better `--lock` workflow would be good here as it should do what you've described.

**Comment by aluanhaddad** [comment]
This is definitely something I would like to see better support for. Perhaps there just needs to be more documentation around `--lock`. That said, jspm handles version conflicts better than any other package manager for JavaScript. The pain of dealing with `peerDependencies` using npm is just ridiculous.
