### ISSUE TITLE
[0.17-beta] jspm unbundle - Error in fetching modules

### ISSUE THREAD

**Issue by sahiljain112** [jspm/jspm-cli#2065]
I'm trying to work with jspm v0.17. Before bundling my files are being fetched from their appropriate paths. Things are pretty smooth even after bundling. But after I unbundle using `jspm unbundle` and go back to dev mode, my files are not being fetched correctly.

For eg: If a file is being fetched from /jspm_packages/npm/xyz.json then after bundling I'm getting a 404 error because the file is being fetched from /npm:xyz.json.

Why does this happen and what's the solution?

**Comment by guybedford** [comment]
It sounds like the paths config for:

```javascript
System.config({
  paths: {
    'npm:*': 'jspm_packages/npm/*'
  }
});
```

isn't present. Make sure this is in your `jspm.config.js` file and is being included in the browser properly so that you can see it is present at `System.paths` before running the import statement.
