### ISSUE TITLE
Setting a breakpoint for app.jsx!transpiled in chrome?

### ISSUE THREAD

**Issue by pcompassion** [jspm/jspm-cli#2067]
I asked the same question in stackoverflow, if it's not appropriate to ask this question, please let me know

I can run Facebook's sample code fine, just can't set a breakpoint in chrome. 
I'm not bundling here (maybe I could with the new `-wid` if I have to).

Here's relevant settings

I'm using jspm@beta ( "jspm": "^0.17.0-beta.28")

```

  transpiler: "plugin-babel",
  babelOptions: {
   "optional": [
    "runtime",
    "optimisation.modules.system"
   ]

 "jsx": "github:floatdrop/plugin-jsx@1.2.1",

  devConfig: {
   "map": {
    "babel-runtime": "npm:babel-runtime@5.8.38",
    "core-js": "npm:core-js@1.2.7",                                                                                                                                                    "plugin-babel": "npm:systemjs-plugin-babel@0.0.13"
   },
   "packages": {
    "npm:babel-runtime@5.8.38": {                                                                                                                                                       "map": {}
    }
   }
  },
```

and I'm loading my app.js with System.import("app.js!jsx");

I can see app.jsx!transpiled in chrome but can't set a breakpoint there.

**edit**
I then tried http://jspm.io/0.17-beta-guide/installing-the-jsx-babel-plugin.html  

with `<script>` loading, chrome shows the app.js gets downloaded, but it doesn't seem to get executed. 

`System.import('app.js')` works fine.
So I guess I need to use System.import with jsx?

**Comment by aluanhaddad** [comment]
I think the issue here is an incorrect url mapping because `app.js!jsx` is probably not going to map to 
`app.jsx!transpiled`.

I'm not sure what your exact package setup is, but why not use something like
```JavaScript
SystemJS.config({
  "packages": {
    "my-app": {
      "meta": {
        "*.js": { 
          "loader": "jsx" 
        }
      }
    }
  }
});
```
This is more maintainable than using explicit plugin syntax.
