### ISSUE TITLE
Color enforcement

### ISSUE THREAD

**Issue by ArmorDarks** [jspm/jspm-cli#2068]
We've encountered an issue during spawning processes with JSPM 0.17-beta. For example, if try to use [grunt-shell](https://github.com/sindresorhus/grunt-shell) JSPM output ends up completely mono-coloric:

![conemu_2016-09-08_14-46-37](https://cloud.githubusercontent.com/assets/4460311/18348276/1861db42-75d3-11e6-8f09-f1fa3863df86.png)

After reading https://github.com/sindresorhus/grunt-shell/issues/21 and [this topic](http://stackoverflow.com/questions/9135579/node-js-spawn-with-colors), if I'm not mistaken, it seems that the only way to bypass this issue is to enforce color with `--color` flag.

As far as I know, JSPM doesn't support `--color` flag. At least, I didn't find it in docs. But, strangly enough it works:

![sublime_text_2016-09-08_14-47-25](https://cloud.githubusercontent.com/assets/4460311/18348301/3aaeedca-75d3-11e6-9351-6491851ca24f.png)

But for some reason it thinks that `--color` isn't a flag, but output directory: 

![conemu_2016-09-08_14-48-24](https://cloud.githubusercontent.com/assets/4460311/18348326/5dd89fee-75d3-11e6-8d88-b1b37fd56792.png)

I then tried to specify output file explicitly, but JSPM simply concatenating both path into single wrong path, resulting in error:

![sublime_text_2016-09-08_14-50-21](https://cloud.githubusercontent.com/assets/4460311/18348377/b8272d26-75d3-11e6-87ef-7ec1c08976f4.png)

`'jspm build "source/scripts/main.js" "test.js"'`, without `--color` works as expected, but, once again, no color in piped through `grunt-shell` output:

![sublime_text_2016-09-08_14-55-17](https://cloud.githubusercontent.com/assets/4460311/18348498/4e935564-75d4-11e6-9255-a910d6226d45.png)

I'm quite confused. Am I missing something, or JSPM indeed mistakenly takes flag for output path? Is there a support of `--color` in JSPM?

**Comment by dinoboff** [comment]
A "--color" flag would be nice but you could use child_process package directly and set stdio to "inherit". E.g.:
```
const ps = require('child_process');

ps.execSync('jspm inspect', {stdio: 'inherit'});
```

**Comment by ArmorDarks** [comment]
Thanks for reply!

Hm, I'm not sure, but it seems to be impossible to control that parameter via [grunt-shell](https://github.com/sindresorhus/grunt-shell).
