### ISSUE TITLE
"Node tls module not supported in browsers."

### ISSUE THREAD

**Issue by dandv** [jspm/jspm-cli#2072]
Just ran into this issue while trying to [use the influx package](https://github.com/node-influx/node-influx/issues/173), which depends on request.

Another user had [the same problem](http://stackoverflow.com/questions/32138320/node-tls-module-not-supported-in-browsers): https://github.com/request/request/issues/1748.

**Comment by guybedford** [comment]
Try using jspm 0.17 here rather, it has better support for environment branching.
