### ISSUE TITLE
How to import CJS code from NPM that uses ES2015 features?

### ISSUE THREAD

**Issue by Rush** [jspm/jspm-cli#2073]
Node6 added 99% of ES2015 features but not the modules. How can I force a cjs module to be transpiled with babel?

**Comment by dinoboff** [comment]
I think you need to define a loader:
```
meta: {
  "*.js":{
    format: "cjs",
    loader: "babel"
  }
},
```

**Comment by Rush** [comment]
Can I define it in package.json?

**Comment by dinoboff** [comment]
Yes, and it you can use the command line
```
jspm install npm:some-package -o '{
  meta: {
    "*.js":{
      format: "cjs",
      loader: "babel"
    }
  }
}'
```

It will had it to package.json, in the `jspm.overrides` field and your jspm config file.

**Comment by dinoboff** [comment]
Try:
```
jspm install npm:some-package -o '{
  meta: {
    "*.js":{
      format: "cjs",
      loader: "plugin-babel",
      babelOptions: {
        modularRuntime: false
      }
    }
  }
}'
```

**Comment by Rush** [comment]
Ok, I'm trying but I'm still seeing `let` statements in the installed code. Am I doing something wrong?
```
jspm install npm:xcase -o '{                                                                                                               ✭ ✱ ◼
  meta: {
    "*.js":{
      format: "cjs",
      loader: "plugin-babel",
      babelOptions: {
        modularRuntime: false
      }
    }
  }
}'
```

**Comment by Rush** [comment]
Ok scratch that. It seems to be working as it's happening at runtime. Thank you @dinoboff

**Comment by Rush** [comment]
Actually I stand corrected, it doesn't work after all. My initial try was bogus.
