### ISSUE TITLE
Ignore Option with jspm API

### ISSUE THREAD

**Issue by mcwillso** [jspm/jspm-cli#2074]
Running into #1817 and need a way to configure the ignore property from the api.
```
jspm.install(true, { lock: true, ignore: ['spec', 'src'] });
```
Doesn't seem to be working.

**Comment by guybedford** [comment]
Try `jspm.install('package', { override: { ignore: ['spec', 'src'] } }`.

The override should be specified for the exact package being installed that this should be ignored for though.

**Comment by mcwillso** [comment]
Thanks @guybedford! After I did that I noticed my jspm overrides config in my package.json now had ignore attributes. So I have decided to edit the package.json to specify my ignores on a per package basis.
