### ISSUE TITLE
jsm bundler command transpiling css as typescript file

### ISSUE THREAD

**Issue by irus1980** [jspm/jspm-cli#2075]
jspm version is 0.16.30

when I run the following I am getting css  related issues (css file is treated as ts/js file)). 

command: **jspm bundle dist/**/* + dist/**/*.html!text + dist/**/*.css!css - angular**

The bundle tree looks like following

dist/a/a.css
dist/a/a.css!github:system.js/plugin-css@0.1.20.js
dist/a/a.html
dist/a/a.html!github:system.js/plugin-text@0.0.4.js
dist/a/a.js
dist/a/index.js
dist/a/a-service.js
dist/index.js

I am getting bundle failure with following errors (it looks like css file is treated as ts/js file)
dis/a/a.css:line:col: Semi-colon expected
dis/a/a.css:line:col: Unexpected token error

**Comment by guybedford** [comment]
`dist/*` is including CSS files. Perhaps try `dist/*.js` or similar rather.

**Comment by irus1980** [comment]
Thanks. This solution works.
