### ISSUE TITLE
unable to load horizon.io

### ISSUE THREAD

**Issue by zwhitchcox** [jspm/jspm-cli#2081]
upon installation, jspm is unable to load horizon.io...see https://github.com/rethinkdb/horizon/issues/832

**Comment by guybedford** [comment]
Did you try using jspm 0.17? It has better support for loading from npm.

**Comment by zwhitchcox** [comment]
No, but I will try that out...thanks for the tip!

**Comment by guybedford** [comment]
Sure, just let me know if you're still having issues with it.

**Comment by zwhitchcox** [comment]
Sorry, should have closed this :-0
