### ISSUE TITLE
undescriptive error

### ISSUE THREAD

**Issue by zwhitchcox** [jspm/jspm-cli#2082]
I love jspm...great project, it's just you get these undescriptive errors, i.e.:

```
system.js:4 Uncaught (in promise) Error: (SystemJS) Identifier 'process' has already been declared(…)t @ system.src.js:122p @ system.src.js:692(anonymous function) @ system.src.js:629g @ system.src.js:774b @ system.src.js:969f @ system.src.js:628m @ system.src.js:674(anonymous function) @ system.src.js:490
```

I mean, how am I supposed to debug this? Look through every instance of `process` used in the project? I mean, as I said, jspm is great, but the moment you *do* encounter an error, you pretty much have to abandon the project, because they're no way to debug it.

**Comment by guybedford** [comment]
Click the '...' To expand the error.

**Comment by zwhitchcox** [comment]
Thank you!
