### ISSUE TITLE
Rollup not including html / css with jspm and angular2

### ISSUE THREAD

**Issue by born2net** [jspm/jspm-cli#2084]
I am trying to roll everything up using angular 2 project via:

```
jspm build src/App.js " + paths.dist + "/" + paths.targetJS + ' --format global --skip-source-maps
```

and getting the following errors:
![capture](https://cloud.githubusercontent.com/assets/5090936/18638690/f45df5ca-7e45-11e6-8f0f-ee14bef1c427.PNG)

I am wondering how do I get rollup to embed all my resources?

Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/ng2Boilerplate
Regards,

Sean

**Comment by born2net** [comment]
I should add my components are configured via __moduleName

```
@Component({
    selector: 'RatesTable',
    moduleId: __moduleName,
    changeDetection: ChangeDetectionStrategy.OnPush,
    styles: [`
        .rateInput {
            width: 40px; 
            color: #0f0f0f;
        }
        .btn span.fa {    			
            opacity: 0;				
        }
        .btn.active span.fa {				
            opacity: 1;				
        }
    `],
    templateUrl: 'RatesTable.html'
})
```

**Comment by guybedford** [comment]
What is the unexpanded error with the `(...)`, it seems like you would need to debug that.

**Comment by born2net** [comment]
it is just the error of it trying to get to the html template:

```
index.min.js:1 Error: Uncaught (in promise): Failed to load /RatesTable.html
    at resolvePromise (https://secure.digitalsignage.com/public/index.min.js:1:23755)
    at resolvePromise (https://secure.digitalsignage.com/public/index.min.js:1:23321)
    at https://secure.digitalsignage.com/public/index.min.js:1:24493
    at ZoneDelegate.invokeTask (https://secure.digitalsignage.com/public/index.min.js:1:32103)
    at Zone.runTask (https://secure.digitalsignage.com/public/index.min.js:1:28035)
    at drainMicroTaskQueue (https://secure.digitalsignage.com/public/index.min.js:1:22525)
    at XMLHttpRequest.ZoneTask.invoke (https://secure.digitalsignage.com/public/index.min.js:2:1538)
```

I honestly dont mind using bundle or build, but in both systems I can't seem to be able to get the jspm to inline the css  /  htmls files

regards

Sean

**Comment by born2net** [comment]
as a workaround I now copy all CSS / HTML to the server, but not ideal

**Comment by guybedford** [comment]
Because Angular dynamically loads those files, you would need to manually include them in the bundle (`bundle angular + templates/*/html` sort of thing) and loading them won't work with static builds either.

**Comment by born2net** [comment]
so it's not possible to bundle all inline?
regards

**Comment by guybedford** [comment]
Bundle but not build because build will stop dynamic loading working.

**Comment by born2net** [comment]
ok so build it is! 
so any recommendations on to what to try and get ```build``` to inject it all?
regards

**Comment by born2net** [comment]
recommended via gitter to try:
https://github.com/jamespamplin/plugin-ng-template
so will have a look
