### ISSUE TITLE
"SyntaxError: Unexpected token" on minification

### ISSUE THREAD

**Issue by refaelos** [jspm/jspm-cli#2086]
Hey,

When trying to minify my code I'm getting `err  Error: SyntaxError: Unexpected token punc «}», expected punc «:» (line: 96821, col: 70, pos: 4195840)`

I want to find where this happens. All I see is the line and col but I don't know what file is failing?

Any ideas?

**Comment by Flashwit** [comment]
Hey, not sure if you've tried, but you could install uglifyjs yourself through npm and run it as a separate step. Ideally that should get you more direct debug info.

**Comment by refaelos** [comment]
@Flashwit thanks. I figured it out.

I just searched all files for a '|' on col 70. It wasn't pretty ;)
