### ISSUE TITLE
JSPM v0.17.0-beta.28: "No resolution found at all for condition" error.

### ISSUE THREAD

**Issue by m-a-r-c-e-l-i-n-o** [jspm/jspm-cli#2088]
Before I take [this route](https://github.com/systemjs/builder/issues/339#issuecomment-145503823), and in light of [this open issue](https://github.com/systemjs/builder/issues/311), I just wanted to check in and verify if static builds still can not handle conditional loading. Following the [example here](http://jspm.io/0.17-beta-guide/conditional-substitution.html), almost to the tee, I get the following error when doing  a static build:
`Error: TypeError: No exact resolution found at all for condition bootstrap/#{bootstrap/lang.js|default}/text.js`

I can assert the mapping is correct and build options are: 
```
{ 
  minify: false,
  mangle: false,
  sourceMaps: true,
  lowResSourceMaps: false,
  node: true,
  production: false 
}
```

**EDIT:** Tried the ["conditions" route](https://github.com/systemjs/builder/issues/339#issuecomment-145503823) (placed it in the build options) and still getting the error, tried the logical `conditions: { 'lang|default': 'en' }` and `conditions: { 'lang.js|default': 'en' }`, and the illogical `conditions: { 'lang': 'en' }`:

Am I missing something here?

**SECOND EDIT:** Got it working using the ["conditions" route](https://github.com/systemjs/builder/issues/339#issuecomment-145503823), seems like the issue is that the conditions don't automatically resolve when attempting to match. Tree has`'bootstrap/lang.js|default'`, while conditions remain at `'lang.js|default': 'en'`, so setting the condition to the resolved path `'bootstrap/lang.js|default'` does it. But looking into this further, it seems like quite a bit [has changed in this department](https://github.com/systemjs/builder/commit/3337e1efd4c50e3aaf1c6b9e5c5c9ba497454440). I'll wait for a new release of JSPM with system builder 0.15.31 before investigating further.

**Comment by guybedford** [comment]
This does sound like exactly that naming issue problem of needing to provide the full `bootstrap/lang.js`. Do you think this is something incorrect in the beta guide, or does that make sense?

Please do try with the coming release and let me know if you see any other issues at all here. The latest conditional changes shouldn't affect this.

**Comment by guybedford** [comment]
Do let me know if you have a further update here at all.

**Comment by m-a-r-c-e-l-i-n-o** [comment]
@guybedford Sorry about that, I was waiting for the new release to give you more feedback, in case there was other concerns. The part that tripped me up was that I interpreted the lack of support for static-build-conditional-substitution as not being able to resolve paths at all. So in my case where I had `import Lang from './#{lang.js}/text.js'`, I didn't expect that to be resolved to `import Lang from './#{bootstrap/lang.js}/text.js'`, so providing the conditions as just simply `{ 'lang.js|default': 'en' }` seemed logical to me (as I thought that would match ` './#{lang.js}/text.js'`).

Now realizing that this is the issue at hand, I do think that issuing conditions as just `{ 'lang.js': 'en' }`, would be more ideal (at least in my case). What are the implications of that?

**Comment by guybedford** [comment]
@m-a-r-c-e-l-i-n-o `bootstrap/lang.js` is the module name of the conditional, so `'bootstrap/lang.js': 'en'` should work here without the `|default` part. If you wanted `lang.js` to work, then that should be possible by adding `map: { 'lang.js': 'bootstrap/lang.js' }` if you haven't got that already. Let me know if that clarifies and matches up with what you're seeing.

**Comment by m-a-r-c-e-l-i-n-o** [comment]
@guybedford So yeah, my concern is with the second part of your message in that despite adding `map: { 'lang.js': 'path/to/lang.js' }` to my config, I still have to do `--conditions "{ 'path/to/lang.js' : 'en'}"` as it will not accept just `--conditions "{ 'lang.js' : 'en'}"`. But if I alias the path (which is what I am currently doing to ease the burden), that alias will be resolved. So I can have `"some-alias/": "path/to/"` in my config and the following will work: `--conditions "{ 'some-alias/lang.js' : 'en'}"`. At any rate, it could very well be a configuration issue on my end, it's not a big deal, and the project with the issue in question is open sourced. I'll just send you a link to it when it's further along and this becomes a higher priority. Thank you for all the help so far!
