### ISSUE TITLE
jspm 0.17 hot reloading

### ISSUE THREAD

**Issue by pcompassion** [jspm/jspm-cli#2089]
In order to use hot reloading, development bundling is a prerequisite?
Or do I need to just  bundle it once?

**Comment by dandv** [comment]
I don't think bundling is necessary? I've followed the steps in [the guide](http://jspm.io/0.17-beta-guide/hot-reloading.html) and hot reloading worked, more or less:

- I often have to make dummy changes for chokidar-socket-emitter to pick up actual changes, e.g. to strings in my source code
- even when it does pick up a change, e.g. `File  index.js  emitted: add`, the browser doesn't pick it up
- in Chrome DevTools -> Sources -> `index.js` isn't updated after hot code reloading
- when I hard reload `http://localhost` an old version of the script runs. No idea where it is cached. I did run `jspm depcache index.js`, but running it again didn't solve the problem. Making some change does cause the actual script to be executed.

I use nginx-1.10.1 stable and I'm very new to jspm, so I'm probably doing something wrong.

**Comment by frankwallis** [comment]
@dandv I had a similar issue to this and I resolved it by turning off all caching on the web server [commit](https://github.com/frankwallis/plugin-typescript/commit/bf2624ee8eefa3f7f57d4f057e0d30094a447ab3), so there is something not quite right (with the HTTP headers maybe?), but I was never able to track it down. Probably this would be better raised on the systemjs-hot-reloader repo.

**Comment by dandv** [comment]
@frankwallis: in the meantime I switched to Webpack 2. Its development server works flawlessly. Curiously, the setup was way simpler than I had read around. Looks like Webpack cleaned up its act.
