### ISSUE TITLE
System.import vs script tag

### ISSUE THREAD

**Issue by refaelos** [jspm/jspm-cli#2090]
Hey,

I want to be able to work with System.import in development and have a script tag to load the main js file on production. For that, I need to have 2 different code snippets in my index.html for the different environments.

Any idea how it can be achieved? (I'm sure someone already solved this issue before...)

**Comment by jp7677** [comment]
I'm doing something like this using gulp-html-replace (https://www.npmjs.com/package/gulp-html-replace), see e.g. https://github.com/jp7677/hellocoreclr/blob/master/ui/src/index.html and https://github.com/jp7677/hellocoreclr/blob/master/ui/build/bundle/html.js as an inspiration.
