### ISSUE TITLE
install from github fork doesn't run scripts in package.json

### ISSUE THREAD

**Issue by pcompassion** [jspm/jspm-cli#2092]
I'm trying to use https://github.com/intljusticemission/react-big-calendar in my project

I forked it (since I intent to modify it) and installed via `jspm install github:pcompassion/react-big-calendar`

I can `jspm install -dev github:pcompassion/react-big-calendar` fine.

But it's lacking `lib` directory, I think jspm is not running "scripts" in package.json  (Is it supposed to do?)

       "scripts": {
         "clean": "rimraf lib",
         "clean:examples": "rimraf examples/static",
         "less": "lessc --autoprefix=\"ie >= 10, last 2 versions\" src/less/styles.less ./lib/css/react-big-calendar.css",
         "assets": "cpy src/less/* lib/less",
         "build": "npm run clean && babel src --out-dir lib && npm run assets && npm run less",
         "build:examples": "npm run clean:examples && webpack --config webpack/examples.config.es6.js",
         "build:visual-test": "webpack --config webpack/visual-test.es6.js",
         "examples": "npm run clean:examples && webpack-dev-server --inline --hot --config webpack/examples.config.es6.js",
         "lint": "eslint src --ext .jsx --ext .js",
         "storybook": "start-storybook -p 9002",
         "test": "npm run lint",
         "tdd": "karma start",
         "release": "release"
       },

So I should go to the folder and mannualy do `npm install` ? (I'm doing it and it's taking very long whereas `jspm install npm:react-big-calendar` didn't  take much time)

Since it's my fork, I can modify the package.json in order for jspm to better install the package if there's a way to do it.

By the way, `jspm install npm:react-big-calendar` generates `lib` folder fine. 

* Edit

So `npm install && npm run build` did create the lib folder. 
But the dependent libraries (such as lodash) are installed under `github/pcompassion/react-big-calendar@0.13.3/node_modules` and systemjs fails to load it.  
I'm jspm installing lodash/warning/and whatever dependency I'm missing.

**Comment by guybedford** [comment]
Package.json scripts are not run by jspm, because jspm takes that stance that that is a security risk.
