### ISSUE TITLE
SFX bundle not executing dependency

### ISSUE THREAD

**Issue by andufratu** [jspm/jspm-cli#2093]
I have a project where I'm trying to build a SFX bundle but for whatever reason a few dynamic dependencies I have defined do not get executed. If, on the contrary, generate a regular bundle and load that everything seems to be working ok. Any ideas as to what the problem might be? What is the exact difference between the two bundle types? I can provide extra information if needed.

**Comment by guybedford** [comment]
If your code contains a dynamic `System.import` load then SFX bundling will not work because that dynamic import will not be locatable, unless you manually include SystemJS and provide the modules in the environment that the SFX bundle runs in.
