### ISSUE TITLE
Is mapping HTTP request between 2 different domains possible ?

### ISSUE THREAD

**Issue by highflyerDL** [jspm/jspm-cli#2094]
Suppose this silly situation where our web client fetches the project from its server "mainserver.app.com". And it has app.js that requires app2.js. 
Instead of the domain "mainserver.app.com", we wanna fetch the same project from "api.app.com". 
Also, the project from "api.app.com" is hashed.
This is possible using the `map` configuration of JSPM:
```javascript
{
  "../app.js":"api.app.com/app-hash.js"
}
```
The problem comes as the "api.app.com/app-hash.js" requires "./app2.js" (which is now hashed) and this does not work : 
```javascript
{
  "../app2.js":"api.app.com/app2-hash.js"
}
``` 
 neither this 
```javascript
{
  "api.app.com/app2.js":"api.app.com/app2-hash.js"
}
```
Any idea is appreciated.

**Comment by guybedford** [comment]
You can use package configuration here, and the fact that package configuration will chain with global map configuration with something like:

```javascript
System.config({
  map: {
    'app': '//api.app.com/app-hash.js',
    'app2': '//api.app.com/app2-hash.js'
  },
  packages: {
    '//api.app.com': {
      map: {
        './app2.js': 'app2' // any require to //api.app.com/app2.js will route to app2 -> app2-hash.js now
      }
    },
    '//site.com': {
      map: {
        './app.js': 'app'
      }
    }
  }
});
```
