### ISSUE TITLE
Install module from GitHub branch?

### ISSUE THREAD

**Issue by dandv** [jspm/jspm-cli#2095]
Use case: testing a WIP branch of a fork.

**Comment by guybedford** [comment]
Yes this is supported.

**Comment by dandv** [comment]
Good to know. I wasn't able to find it in the documentation though.

**Comment by lmj0011** [comment]
@guybedford 
Could more info be provided on how to correctly do this?

related: https://github.com/jspm/jspm-cli/issues/102#issue-40705866

**Comment by lmj0011** [comment]
nvm, I think the info is here:

https://github.com/jspm/jspm-cli/blob/master/docs/registries.md#creating-a-private-jspm-registry

**Comment by lmj0011** [comment]
after doing this: https://github.com/jspm/jspm-cli/blob/master/docs/registries.md#private-github

How would the syntax look for installing the module from the private repo?
