### ISSUE TITLE
Facing issues with bundling and building using jspm 0.17.0-beta.28

### ISSUE THREAD

**Issue by mistyharsh** [jspm/jspm-cli#2096]
I am trying to create a bundle using

``` javascript
jspm bundle src/commons/js/main.js bundle.js
```

It generates bundle successfully. However when I set `production: true` in my `jspm.browser.js` file and include the bundle in my html page as a script then I get the following error:

```
Uncaught (in promise) Error: (SystemJS) Plugin http://localhost:8080/plugin-babel.js cannot load itself, make sure it is excluded from any wildcard meta configuration via a custom loader
```

I was not able to find any documentation around this topic other than http://jspm.io/0.17-beta-guide/bundling.html.

Further, I was trying to create a build with Rollup Optimization:

``` javascript
jspm build src/commons/js/main.js bundle.js
```

I keep getting following error while it attempts to tree shake and create bundle:

```
err  Error: Could not load src/commons/js/main.js: Cannot read property 'metadata' of undefined
       at C:\learn\cyclejs\node_modules\rollup\dist\rollup.js:7320:10
```

My `main.js` is simple file with just one import. However, if I skip rollup optimization, then it works perfectly fine:

```
jspm build src/commons/js/main.js bundle.js --skip-rollup
```

Not sure if this is really jspm/system.js issue.

**Comment by guybedford** [comment]
Yes the Babel plugin is not included in the production configuration - when setting production: true, you need to make sure that all modules are loaded from already-compiled bundles. Check the network tab to see what is being missed here.
