### ISSUE TITLE
Hot-reloader was not disabled for JSPM production build, causing the hot-reloader still working in production

### ISSUE THREAD

**Issue by Simon-Li** [jspm/jspm-cli#2097]
JSPM is an important part of my daily JS dev. workflow. It works greatly for my work except that the duration of refreshing my app takes a long time to load into the browser (in dev/debugging phase). To mitigate this headache instead of trying Webpack, I decided to try this lib.

The lib setup and run up exactly as the readme states, the outcome is awesome as well, so the speed of dev/debugging is really a snap. But, after execute "jspm bundle-sfx", and release the bundle into the production, the hot-reloader are still working, which is not as expected as stated by the wiki:
"At the top of your es6 code:"
"import 'systemjs-hot-reloader/default-listener.js"
"Maps to empty module on production builds, so no needs for any if statements."

The JSPM bundle CLI used is:

❯ jspm bundle-sfx ./jslib/zy_wf_op/zy_workflow_op ./builds/zy_workflow_op_build.js --minify; 
Building the single-file sfx bundle for ./jslib/zy_wf_op/zy_workflow_op...
ok Built into builds/zy_workflow_op_build.js with source maps, minified, mangled.

Any hints to resolve?

Thanks!

**Comment by guybedford** [comment]
This should be taken up with the hot reloader project. Also perhaps try following the steps in the jspm beta guide for jspm 0.17.
