### ISSUE TITLE
Error on translate during jspm bundling with  system text plugin

### ISSUE THREAD

**Issue by abidmix** [jspm/jspm-cli#2098]
I am  having an issue when I try to bundle using jspm. I have created an ambient module declaration like this
```
declare module "*.html" { 
var __html__: string; 
export default __html__; 
} 
```
And in my imports

var DLATemplate = require('/Template/activity/ActivityDla.html')

```
@Component({
selector: 'activities-dla',
template: DLATemplate,
})
```
This builds fine and works fine unbundled, but I am having issues when trying to create a self executing bundle
On bundling I get this error "Error on translate for file"  Template/activity/ActivityDla.html

![image](https://cloud.githubusercontent.com/assets/12702893/18855308/ada39d3a-841f-11e6-84c6-0a832cc73311.png)

I also have this line in my system.config

meta: { "*.html": { loader: 'text' } }

Am not sure why I am getting this error since I am not trying to read a folder here. I am running angular 2.0.0

**Comment by guybedford** [comment]
This sounds like an issue specifically with configuring the TypeScript plugin in builds, and not something with the text plugin?
