### ISSUE TITLE
ES6 Module - Changes export name to 'Test'

### ISSUE THREAD

**Issue by peteringram0** [jspm/jspm-cli#2099]
When importing a ES6 module and setting to ES6, JSPM re-rights the export name to Test. As a result Test cant be found.

````
"overrides": {
      "NAME": {
        "format": "es6"
      }
    }
````

**Comment by guybedford** [comment]
I'm not sure I follow, can you clarify what you mean here?

**Comment by peteringram0** [comment]
So im adding the following https://github.com/kysonic/xhr which is an ES6 module. However when looking at it within jspm_packages at the bottom of the file it says export default Test. Why is this being changed by JSPM?

**Comment by guybedford** [comment]
Are you running `jspm install github:kysonic/xhr` and then importing `System.import('kysonic/xhr/Xhr.js')` then? jspm wouldn't be changing any exports here.

**Comment by peteringram0** [comment]
im importing via ES6 import syntax within my app. Thanks for the help

**Comment by guybedford** [comment]
I would really need more help with a replication to assist.

**Comment by guybedford** [comment]
Make sure you are using `import Xhr from 'kysonic/xhr/Xhr.js'` and not `import * as Xhr` as well here.
