### ISSUE TITLE
CORS error when including stripe

### ISSUE THREAD

**Issue by atrauzzi** [jspm/jspm-cli#2100]
I'm trying to include stripe as per the advice in #984.  Everything seems to be correctly attempting to resolve, but when it goes out to hit the server, I get a CORS error.

![image](https://cloud.githubusercontent.com/assets/115199/18929130/ca538c64-8588-11e6-9364-65f2989dbdbd.png)

Any chance this can be resolved, or does it pretty much require them to set a CORS policy for that script?

**Comment by OrKoN** [comment]
@atrauzzi  in https://github.com/jspm/jspm-cli/issues/984 stripe library was served via the author's proxy server: https://proxy.zoltu.io/stripe/checkout.js and not directly via the Stripe's servers.

Therefore, I would say that in the browser it's gonna work only with a proxy server.

**Comment by guybedford** [comment]
You can load with CSP support via meta configuration:

```javascript
System.config({
  meta: {
    'https://js.stripe.com/v2/': { scriptLoad: true }
  }
});
```

**Comment by atrauzzi** [comment]
Damn, you think of everything!
