### ISSUE TITLE
API Link method not working

### ISSUE THREAD

**Issue by zyzo** [jspm/jspm-cli#2101]
It seems to me that the `ui.confirm` promise is not resolved, though this line of code is never reached:

https://github.com/jspm/jspm-cli/blob/0.17/lib/link.js#L170

reproducible with any jspm project

**Comment by guybedford** [comment]
I've added a potential fix in https://github.com/jspm/jspm-cli/commit/2e7b00216a82edd88c67f2abe061ff5124ac48ca. Please let me know if that works for you here.

**Comment by guybedford** [comment]
Released in 0.17.0-beta.29. Just let me know if this is still giving problems there.

**Comment by zyzo** [comment]
Updated to beta.29 and it worked magically !
