### ISSUE TITLE
(0.17, related to beta.29 release) new version of jspm-npm breaks npm compatibility for many packages.

### ISSUE THREAD

**Issue by joeldenning** [jspm/jspm-cli#2102]
The newly released versions of jspm-npm (0.29.5 and 0.29.6) break npm compatibility for npm packages that use the [`files`](https://docs.npmjs.com/files/package.json#files) property inside of their package.json. It appears that https://github.com/jspm/npm/commit/1dd23bd72775c490eb7af9d6115f19f00193629d is the commit at fault, specifically [this line in that commit](https://github.com/jspm/npm/commit/1dd23bd72775c490eb7af9d6115f19f00193629d#diff-d59e8acbcb92cd0bf52fbd9565335fe9R500). The reason why it breaks things is that it does not put in a`./` into the `map` when one is needed.

Two packages that no longer work with the jspm-npm@^0.29.5 are npm:sockjs-client and npm:asap. See screenshots below for the errors that occur:
![screen shot 2016-09-30 at 2 27 25 pm](https://cloud.githubusercontent.com/assets/5524384/19005859/0e0ce8c8-871a-11e6-8a29-cf88cc3c1675.png)
![screen shot 2016-09-30 at 2 28 04 pm](https://cloud.githubusercontent.com/assets/5524384/19005882/217143d2-871a-11e6-86e0-ead5aa7bdc0a.png)

The reason is that the asap@2.0.4.json file inside of the jspm_packages needs to look like this:
![screen shot 2016-09-30 at 2 43 34 pm](https://cloud.githubusercontent.com/assets/5524384/19006355/4ce7dace-871c-11e6-8a0f-8549238d4862.png)

but with jspm-npm@^0.29.5 it actually looks like this:
![screen shot 2016-09-30 at 2 32 30 pm](https://cloud.githubusercontent.com/assets/5524384/19005998/c0482732-871a-11e6-808d-051f3f74184a.png)

Note that this seems to coincide with the release of jspm@0.17.0-beta.29, but that reverting to jspm@0.17.0-beta.28 does not fix the problem since beta.28 has a caret dependency `"jspm-npm": "^0.29.4"` which picks up the bad version of jspm-npm. The current workaround we've found is to `npm install --save-dev --save-exact jspm@0.17.0-beta.28 jspm-npm@0.29.4`, making our project have a dependency on the working version of jspm-npm so that the caret does not cause the broken version of jspm-npm to be installed.

**Comment by guybedford** [comment]
Thanks so much, released in jspm-npm-0.29.7.
