### ISSUE TITLE
An import path cannot end with a ".ts" extension. (TS 2.0.3)

### ISSUE THREAD

**Issue by jlost** [jspm/jspm-cli#2103]
Generating a new project with jspm init and specifying typescript as my transpiler, the convention for picking up typescript files is as follows:
```
packages: {
    "pets-gui": {
      "main": "main.js",
      "meta": {
        "*.ts": {
          "loader": "plugin-typescript"
        }
      }
    }
  }
```

My understanding is that this means everything with the .ts extension in the import is run through the typescript transpiler plugin. 

However, Typescript 2.0.3 (called externally for intellisense) will report this as an error: `An import path cannot end with a ".ts" extension. Consider importing './app.routing' instead`, for instance. Of course, if I do that, the .ts files aren't transpiled by systemjs, and it just reports 404's as it tries to load "./app.routing" which doesn't exist.

Is there a work-around so I don't have to choose between SystemJS and my intellisense?

Apologies if this is the wrong place to raise this issue.

```
0.17.0-beta.28
Running against local jspm install.
```

**Comment by guybedford** [comment]
It would probably be best raising this with the plugin-typescript project.
