### ISSUE TITLE
[0.17.0-beta.29] command line interface build error if (package.json baseURL) != root path

### ISSUE THREAD

**Issue by shaoahs** [jspm/jspm-cli#2104]
my project
pixi is https://github.com/pixijs/pixi.js
if use 0.17.0-beta.28 is ok!
# 

> package.json

{
  "jspm": {
    "name": "app",
    "main": "app.js",
    "directories": {
      "baseURL": "web/"
    },
    "configFiles": {
      "jspm": "web/config/jspm.config.js"
    },
    "devDependencies": {
      "plugin-babel": "npm:systemjs-plugin-babel@^0.0.15"
    }
  },
  "devDependencies": {
    "jspm": "^0.17.0-beta.29"
  }
}
# 

> jspm.config

SystemJS.config({
  paths: {
    "npm:": "jspm_packages/npm/",
    "depend:": "dependence/",
    "z05/": "src/app/z05/"
  },
  browserConfig: {
    "baseURL": "."
  },
  devConfig: {
    "map": {
      "plugin-babel": "npm:systemjs-plugin-babel@0.0.15"
    }
  },
  transpiler: "plugin-babel",
  map:{
      "pixi": "depend:pixi/pixi.min.4.0.3.js"
  },
  packages: {
    "z05": {
      "main": "app.js",
      "meta": {
        "_.js": {
          "loader": "plugin-babel"
        }
      }
    }
  }
});
SystemJS.config({
  packageConfigPaths: [
    "npm:@_/_.json",
    "npm:_.json"
  ],
  map: {},
  packages: {}
});
# 

> jspm.build.json
> {
>   "meta": {
>     "pixi": {
>       "build": false
>     }
>   }
> }
# source code in src/app/z05/

> main.js
> import 'z05/vendor';
> console.log('start app');
> console.log(PIXI);
# 

> vendor.js
> import 'pixi';
# 

build debug

> jspm bundle src/app/z05/main --config jspm.build.json
> is ok!
# 

build release

> jspm build src/app/z05/main --config jspm.build.json --format amd
> err  Error: Unable to calculate canonical name to bundle file:///home/dott/html/javascript/test/z05/z05/main.js. Ensure that this module sits within the baseURL or a wildcard path config.
>     at getCanonicalNamePlain (/home/dott/html/javascript/test/z05/node_modules/systemjs-builder/lib/utils.js:227:13)
>     at getCanonicalName (/home/dott/html/javascript/test/z05/node_modules/systemjs-builder/lib/utils.js:150:19)
>     at /home/dott/html/javascript/test/z05/node_modules/systemjs-builder/lib/rollup.js:289:25
>     at Array.map (native)
>     at /home/dott/html/javascript/test/z05/node_modules/systemjs-builder/lib/rollup.js:288:49

**Comment by guybedford** [comment]
You need to ensure that the `/home/dott/html/javascript/test/z05/z05/main.js` path is contained within one of these paths:

```
paths: {
"npm:": "jspm_packages/npm/",
"depend:": "dependence/",
"z05/": "src/app/z05/"
},
```

or the baseURL path of `/home/dott/html/javascript/test/web`.

You may want to just alter the baseURL to be `/home/dott/html/javascript/test/`.

**Comment by shaoahs** [comment]
I try some time
if my project root path is 'test01'
config file no change
then package.json   
```
"directories": {
    "baseURL": "web/"
}
```
then jspm-cli in project path test01 
type
`jspm bundle command is ok!`
type 
`jspm build command is error!`

but change jspm-cli path in test01/web
type
`jspm bundle command is ok!`
type 
`jspm build command is ok!`

**Comment by shaoahs** [comment]
I use this project config is ok!
package.json
```
    "directories": {
      "baseURL": "./"
    },
    "configFiles": {
      "jspm": "web/config/jspm.config.js"
    },
```
jspm.config.js

```
  paths: {
    "npm:": "jspm_packages/npm/",
    "depend:": "web/dependence/",
    "z06/": "web/src/app/z06/"
  },
```
```
jspm bundle is ok!
jspm build is ok!
```

then change
package.json
```
    "directories": {
      "baseURL": "web"
    },
    "configFiles": {
      "jspm": "web/config/jspm.config.js"
    },
```
jspm.config.js

```
  paths: {
    "npm:": "jspm_packages/npm/",
    "depend:": "dependence/",
    "z06/": "src/app/z06/"
  },
```
```
jspm bundle is ok!
jspm build is error!
```

**Comment by guybedford** [comment]
Yes the baseURL needs to be lower than `web`.

**Comment by shaoahs** [comment]
okay ! thanks !
current use `jspm bundle --inject ` command has little problem

my project has  test web server (use grunt-browser-sync)
config is
```
    browserSync: {
      dev:{
        bsFiles: {
          src : ['web/!*.html', 'web/src/app/!**!/!*.js', 'web/test/!**!/!*.js']
        },
        options: {
          watchTask: false,
          server: {
            baseDir: "web"
          }
        }
      }
    }
```
my project tree is
```
├── node_modules
└── web
    ├── config
    │    └── jspm.config.js
    ├── dependence
    │   ├── dynamics
    │   ├── howler
    │   ├── loader
    │   ├── mustache
    │   ├── pixi
    │   ├── pouchdb
    │   ├── socket.io
    │   └── yaml
    ├── jspm_packages
    │   └── npm
    │       └── systemjs-plugin-babel@0.0.16
    └── src
        └── app
            └── z06
```
jspm.config.js
```
SystemJS.config({
  browserConfig: {
    "baseURL": ".",
    "paths": {
      "npm:": "jspm_packages/npm/",
      "depend:": "dependence/",
      "z06/": "src/app/z06/"
    }
  },
  nodeConfig: {
    "paths": {
      "npm:": "web/jspm_packages/npm/",
      "depend:": "web/dependence/",
      "z06/": "web/src/app/z06/"
    }
  },
  devConfig: {
    "map": {
      "plugin-babel": "npm:systemjs-plugin-babel@0.0.16"
    }
  },
  transpiler: false,
  map: {
    "pixi": "depend:pixi/pixi.min.4.0.3.js"
  },
  packages: {
    "z06": {
      "main": "z06.js",
      "format": "amd",
      "meta": {
        "*.js": {
          "loader": "plugin-babel"
        }
      }
    }
  }
});

SystemJS.config({
  packageConfigPaths: [
    "npm:@*/*.json",
    "npm:*.json"
  ],
  map: {},
  packages: {}
});

```
----------
use 
`jspm bundle web/src/app/z06/main.js web/debug/build.js --config jspm.build.json`
is ok!
----------
use 
`jspm build web/src/app/z06/main.js web/release/build.js --format amd --config jspm.build.json 
`
is ok!
----------
use 
`jspm bundle web/src/app/z06/main.js web/debug/build.js --config jspm.build.json --inject`
if use browser has error !
```
  browserConfig: {
    "baseURL": ".",
    "paths": {
      "npm:": "jspm_packages/npm/",
      "depend:": "dependence/",
      "z06/": "src/app/z06/"
    },
    "bundles": {
      "web/debug/build.js": [
        "z06/main.js",
        "z06/vendor.js"
      ]
    }
  }
```
then change 
```
  browserConfig: {
    "baseURL": ".",
    "paths": {
      "npm:": "jspm_packages/npm/",
      "depend:": "dependence/",
      "z06/": "src/app/z06/"
    },
    "bundles": {
      "debug/build.js": [
        "z06/main.js",
        "z06/vendor.js"
      ]
    }
  }
```
is ok!

**Comment by shaoahs** [comment]
how to use baseURL ? 
0.17.0-beta.29
only set baseURL: "./" 
if use other name jspm build command has error 
0.17.0-beta.28
baseURL can type sub path of project

**Comment by shaoahs** [comment]
0.17.0-beta.31
is ok
