### ISSUE TITLE
CI use of jspm fails when asked for github credentials

### ISSUE THREAD

**Issue by philkunz** [jspm/jspm-cli#2105]
Hi,

Jspm is awesome!

I'm wrapping the jspm api to enable jspm within some broad scope build tools. ON my local machine everything works fine. However in CI (where there are no github credentials in place) it fails due to github credentials... why is that? Is there any way to prevent that?

See build log: https://gitlab.com/pushrocks/smartjspm/builds/4695567

**Comment by guybedford** [comment]
Thanks for the nice feedback. See https://github.com/jspm/jspm-cli/blob/master/docs/registries.md#auto-configuring-registries for more info here.

**Comment by philkunz** [comment]
Thank you, I somehow didn't see that! Have a nice day and enjoy the beer ;) (supporterhq.com)
