### ISSUE TITLE
[0.17.0-beta.29] JSPM doesn't resolve a fork

### ISSUE THREAD

**Issue by matthew-dean** [jspm/jspm-cli#2107]
I've forked a project to `matthew-dean/[forked_project]` in Github.

However, when I do:
```
jspm install github:matthew-dean/[forked_project]
```
JSPM will install the source (original) project, and not my forked version. Isn't it just resolving the Github URL from the package name on the command line?

**Comment by matthew-dean** [comment]
I'm also getting a resolution error if:
1. I installed one version of a repo.
2. I try to rollback to another version, _and_
3. The previous version was under a different user name.

That is, even though I explicitly provide the old user name for the repo, JSPM can't seem to resolve it if the newer version is in a new name. Not sure if this was because it was previously installed or not, but clearing global caches didn't seem to do anything.

**Comment by guybedford** [comment]
jspm will install the stable version tag, not master by default.

You may just want to use `jspm install github:matthew-dean/[forked_project]@master` here.

**Comment by matthew-dean** [comment]
@guybedford Ah okay, thanks.
