### ISSUE TITLE
jspm bundle arithmetic can't exclude a package without existing file

### ISSUE THREAD

**Issue by dasch88** [jspm/jspm-cli#2108]
I have some script file resources in my web site that are dynamically generated, and served from a web service (endpoint mapped to "api-metadata"). I am trying to bundle my core application using:

`jspm bundle app - api-metadata bundle.js`

...but it is choking on an error message saying that the file does not exist (because it is an api endpoint url). Just to make sure I'm sane, I tried bundling one of my references that does not have anything crazy like that, and exclude one of its dependencies, and it worked just fine. Is there any way to do what I need?

**Comment by guybedford** [comment]
Try `jspm bundle app bundle.js --externals api-metadata` in jspm 0.17.

**Comment by dasch88** [comment]
This looks like exactly what I want. I was using 0.16.x, so I upgraded to 0.17 to give it a try. After quite a few headaches, I was able to get everything upgraded, and now bundling is working great! Thank you!
