### ISSUE TITLE
static bundle and System.import

### ISSUE THREAD

**Issue by devmondo** [jspm/jspm-cli#2109]
hi, 
i have the following dynamic import 

`System.import('my-app/modules/module-a')`

i included SystemJS manually and i bundled this module but i still get 

`http://localhost:9090/my-app/modules/module-a.js 404 (Not Found)`

**Comment by guybedford** [comment]
You need to make sure that the bundle modules defined contains an entry for `http://localhost:9090/my-app/modules/module-a.js`. This can be checked by looking at `Object.keys(System.defined)` to see if it is there.

**Comment by devmondo** [comment]
@guybedford 
thanks for feed back, i did check and the `System.defined` is empty Object!

the command i do using `jspm 0.17 latest` is 
`jspm build my-app/index + my-app/module-a build.js --format umd`

which build fine with the following log
```
 Creating the single-file build for my-app/index.js + my-app/modules/module-a...

       my-app/index.js
       my-app/modules/module-a.js

ok   Built into build.js with source maps, unminified as umd.
```

my files are simple
`index.js`
```
System.import(`my-app/modules/module-a.js`).then((r) => {console.log(r);})
```

`module-a.js`
```
export function hello() {
    return `hello`
}
```
i include the scripts as below
```
<body>
    <script src="./jspm_packages/system.js"></script>
    <script src="./build.js"></script>
</body>
````

**Comment by guybedford** [comment]
You need to use `jspm bundle` not `jspm build` for `System.import` support.

**Comment by devmondo** [comment]
@guybedford , thanks for the update,

i understand what you mean, but the performance of `jspm build` is way more fast than `jspm bundle`, in my case it is 50% faster.

the more deps you add to jspm bundle` the slower it gets to parse, plus with `jspm build` you dont have to have config file.

**Comment by guybedford** [comment]
Certainly use jspm build then, but note that you need to include the built file with a script tag and can't use System.import then (or if you do, it is loading the build itself as a module).

**Comment by devmondo** [comment]
@guybedford thanks again,

but i am confused of what you say here `(or if you do, it is loading the build itself as a module).` , i already load the build as script tag and load system.js before it for making dynamic import works.

**Comment by guybedford** [comment]
Builds do not expose their internal modules. Anything run through build can be considered private and no longer available in the public registry, just as if you did a browserify or rollup build.
