### ISSUE TITLE
jspm run with typescript neither __dirname nor __modulename is defined

### ISSUE THREAD

**Issue by jonaskello** [jspm/jspm-cli#2116]
I'm trying to make a simple express server with 0.17.0-beta.29. I did a jspm init with all defaults, choosing typescript as transpiler. I want to serve from the current dir so I tried __dirname first but it was undefined. Then I read that __modulename should work for ES6 modules but it is also undefined. I think maybe plugin-typescript is outputting System.register format modules. Is there some way to get the current directory under these conditions?

**Comment by guybedford** [comment]
The binding you're looking for here is probably `__moduleName`.

**Comment by jonaskello** [comment]
You are absolutely correct! I somehow just assumed lowercase, probably because of __dirname being lowercase. It it now working perfectly, thanks!
