### ISSUE TITLE
jspm update removing overrides instead of updating them

### ISSUE THREAD

**Issue by pocesar** [jspm/jspm-cli#2118]
when using `jspm update` in `jspm@beta` all the meticulously created overrides for non-compliant modules gets lost, and I need to recreate them all every time. 

```
     Removing unused package.json override npm:angular-google-maps@2.3.4
     Removing unused package.json override npm:jquery@3.1.0
     Removing unused package.json override npm:lodash@4.15.0
```

if there's an override for angular-google-maps@2.3.1 it should at least keep it, so I can manually "up" the version

**Comment by pocesar** [comment]
only in this case it worked:

```
     The following existing package versions were altered by install deduping:

       lodash 4.15.0 -> 4.16.4
       jquery 3.1.0 -> 3.1.1
```

**Comment by guybedford** [comment]
The overrides should only be removed for major version updates, and remain otherwise.

Can you share a minimal replication here? `jspm install lodash@4.15.0 -o "{custom:'override'}" && jspm install lodash` seems to retain the override fine for me.

**Comment by pocesar** [comment]
yes, it seems to be working, I must have done something that wiped the overrides... sorry!
