### ISSUE TITLE
staticBuild not working on Windows 10

### ISSUE THREAD

**Issue by jerryorta-dev** [jspm/jspm-cli#2123]
The build code uses the JSPM API, though ultimately the issues appears to be in systemjs-builder. I have seen this issue addressed in the repos for SystemJS, systemjs-builder, but since I'm using JSPM I decided to log the issue here. Let me know if this issue needs to be reference in another repo.

Despite the many places this issue is addressed, I'm having trouble finding a solution.

[This issue](https://github.com/UIUXEngineering/angular2-jspm-typescript-seed/issues/7) as reference and that project as an architecture that is an example of the issue.

To reproduce in that project, run `npm run prod`.

**Dependencies**
jspm@0.17.0-beta.29
systemjs-builder@0.15.32
Node.js @ 6.4.0
Windows 10
Dell Inspiron 15, series 3000

``` js

    if (isWin) {
      return normalize(path);
    }
    // return normalize(path).replace(/\\/g, '/');
    return normalize(path);
  }

  let projectRootAppSrc: string = fixPathForPC(PROJECT_ROOT_APP_SRC);
  let jspmConfig: string = JSPM_CONFIG;
  let BootstrapModule: string = BOOTSTRAP_MODULE;
  let unminifiedJsProdDest: string = UNMINIFIED_JS_PROD_DEST;


  let Builder = jspm.Builder;
  let builder = new Builder(projectRootAppSrc, jspmConfig);

  // https://github.com/systemjs/builder
  builder.buildStatic(BootstrapModule, unminifiedJsProdDest, outputOptions).then(function() {
      gulp.src(UNMINIFIED_JS_PROD_DEST)
      /**
       * mangle:true ( default ) breaks the angular2 app.
       */
        .pipe(plugins.uglify({mangle:false}))
        .pipe(plugins.rename(JS_PROD_APP_BUNDLE_MIN))
        .pipe(gulp.dest(JS_PROD_DEST_ROOT))
        .on('finish', done);
    });

```

The variables resolve on Windows 10.0 to:

``` js

    projectRootAppSrc =  C:\Users\jerry\OneDrive\Documents\GitHub\angular2-workspace\angular2-jspm-typescript-seed\src\browser\
    jspmConfig =  C:\Users\jerry\OneDrive\Documents\GitHub\angular2-workspace\angular2-jspm-typescript-seed\src\browser\jspm.config
    BootstrapModule =  C:\Users\jerry\OneDrive\Documents\GitHub\angular2-workspace\angular2-jspm-typescript-seed\src\browser\app\main.ts
    unminifiedJsProdDest =  dist\browser\js\app.js
```

**Question**
Do I need to convert any of the above path's separators to "/"? I expiremented  various scenarios, but no luck.

**Comment by jerryorta-dev** [comment]
[This architectures's issue](https://github.com/mgechev/angular-seed/issues/1469) just closed by upgrading to node 6.8.0... let me try that on my project and I will report results.

**Comment by jerryorta-dev** [comment]
This is still broken with node 6.8.0

**Comment by aluanhaddad** [comment]
It builds just fine for me. 
Windows 10 pro x64
node v6.6.0
jspm@0.17.0-beta.29
custom hardware

The file created by `npm run prod` is certainly not empty but fails to load. 
There are a bunch of other issues in general.
There is a format detection issue which causes the built app to fail to load. 
If I build using the jspm-cli, it doesn't have this issue.

There is a tsconfig.json file that is not being used by plugin-typescript which is itself oddly configured. 
jspm.config.js looks like it was upgraded from a jspm 0.16.x project, but not fully, the typescript version used by npm's devDependencies is different than the one used by plugin-typescript. 
Configuration complexity, including all the different settings passed to the builder, is very high.

Can you provide a slimmed down example?

**Comment by jerryorta-dev** [comment]
Sorry, the isWin is a result of troubleshooting. 

As for notes on the above:
- jspm is initted with beta.29
- fresh jspm init, not a migration. I don't use the migration feature. So if something looks as if it's in the wrong place ( devDependencies ), then this is another issue with jspm installing modules.
- tsconfig.json not being used by plugin-typescript is correct. It's used by the environment. The app is decoupled from the environment, hence the use of jspm. The environment is written in 
Typescript. But I still don't want the app to rely on the environment for transpiling config for enterprise developemnt reasons.

Here are more notes on architecture if people are wondering: [WHY_JSPM](https://github.com/UIUXEngineering/angular2-jspm-typescript-seed/blob/master/docs/WHY_JSPM.md)

It's a good exercise to create a simple project. I'll do that for troubleshooting and comment results.

**Comment by jerryorta-dev** [comment]
Thanks @aluanhaddad, great exercise.

jspm buildStatic is not working on Mac or PC now with beta.29.
systemjs buildStatic IS working on both PC and Mac with beta.29.

As an experiment, I created a task invoking the jspm build API, and another task 
using the systemjs-builder API that jspm installs as a peer dependency. The API tasks are identical except which API I'm invoking.

Minimized repo here: [https://github.com/UIUXEngineering/jspm-test](https://github.com/UIUXEngineering/jspm-test)

I did a clean jspm init with the specs in the Readme of the repo.

the commands to run and build:

###Run dev
```bash

$npm run dev
```

###Build with systemjs

```bash

$npm run build.systemjs
```

###Buils with jspm

```bash

$npm run build.jspm
```

Once running in dev or built ( dist ): you should see a page like this:

[![ScreenShot](https://github.com/UIUXEngineering/jspm-test/blob/master/page_rendered_screenshot.png)]

The jspm buildStatic API task looks like this:

```js
...
var jspm = require('jspm');
...

gulp.task('build.jspm.js', function(done) {

  var OUTPUT_OPTIONS = {
    // amd, cjs or es6
    // format: 'es6',
    // baseURL: '/',
    sourceMaps: true,
    config: {
      sourceRoot: path.join('src', 'browser')
    }
  };

  var builder = new jspm.Builder(
    path.join('src', 'browser') + path.sep,
    path.join('src', 'browser', 'jspm.config.js')
  );

  // https://github.com/systemjs/builder
  builder.buildStatic(
    'app/main.ts', // Must be forward slash 
    path.join('dist', 'browser', 'js', 'app.js'),
    OUTPUT_OPTIONS
  ).then(function() {
    createMinJs(done);
  });
});
```

The systemJs staticBuilder task looks like this:

```js

gulp.task('build.systemjs.js', function(done) {

  var OUTPUT_OPTIONS = {
    // amd, cjs or es6
    // format: 'es6',
    // baseURL: '/',
    sourceMaps: true,
    config: {
      sourceRoot: path.join('src', 'browser')
    }
  };
  var SystemJSBuilder = require('systemjs-builder');
  var builder = new SystemJSBuilder(
    path.join('src', 'browser') + path.sep,
    path.join('src', 'browser', 'jspm.config.js')
  );

  // https://github.com/systemjs/builder
  builder.buildStatic(
    'app/main.ts', // Must be forward slash
    path.join('dist', 'browser', 'js', 'app.js'),
    OUTPUT_OPTIONS
  ).then(function() {
    createMinJs(done);
  });
});
```

**Comment by aluanhaddad** [comment]
@jerryorta-dev first of all I agree with all the points in your Why JSPM rational. Obviously I'm a huge fan of the project and I use it for many of the same reasons.

With respect to decoupling from the environment, there's nothing wrong with having another tsconfig.json file in the app directory. It is extremely helpful for IDEs. It makes your configuration more modular. It's important to understand the distinction between an IDE that analyzes your project and the compilation step itself. That's why TypeScript is separated into tsserver and tsc. It also allows things to remain in sync across the project much more easily. 
I'm also not entirely sure what you mean by environment since most of it seems to be a bunch of build tasks and configuration but the actual data is just served come a static JSON file. What I mean is you could use any backend that you like. Taking this a bit further, I would say that one of the really nice advantages of JSPM is how little _manual_ configuration you need to actually maintain.

I see that I was incorrect about the project being upgraded from an older version. The reason it seemed that way that had to do with certain Babel settings and aliases that are non longer generated by default.

One thing to note is that when buidling is that you can just bundle the name of the package ('app').

I am less familiar with the new Conditional Loading features in JSPM but you will likely need multiple outputs from your build to make this worthwhile.

Don't use the systemjs-builder API with JSPM use the JSPM api. The pre-configured Builder that you get from JSPM is the way to go. Of course you can use it, and I have in the past, but there's no need as jspm handles that for you.

**Comment by jerryorta-dev** [comment]
Thank you for the feedback @aluanhaddad.

> there's nothing wrong with having another tsconfig.json file in the app directory.

I'll look into this. It's a good idea.

What I mean by "environment" is that everything in the src/browser directory is self-contained as much as possible. I'm entertaining the idea of creating a package.json for the src/browser directory to further decouple the app. What this really means is that all build dependencies come from the jspm_packages directory and not from node_modules. So the build transpilers are coming from sytemjs ts and babel plugins located from jspm_packages.

**Comment by aluanhaddad** [comment]
I think adding a separate `package.json` would be a great idea.
