### ISSUE TITLE
Cyclic dependency projects: Ignoring dependencies during install

### ISSUE THREAD

**Issue by abhipanda** [jspm/jspm-cli#2125]
Hello Everyone,

Is it possible to ignore some package.json dependency while installing through JSPM install ? This is required for cases where there are sub modules of projects have cyclic dependencies.

E.g.

A depends on C
B depends on C

C depends on A, B

Now if I install B, it installs A, B and C as well

Thanks
Abhi

**Comment by guybedford** [comment]
You can use overrides to change dependencies, but anything listed as a dependency will be installed otherwise, regardless of whether it is a cyclic dependency graph.
