### ISSUE TITLE
'Bundling' an individual package without dependencies

### ISSUE THREAD

**Issue by jamiewinder** [jspm/jspm-cli#2126]
I'm not sure if I'm understanding how the bundler works. I'm using it to both bundle some external libraries together, and also to move individual packages out of `jspm_packages` on deployment. Basically, I have some bundle commands that looks like:

```
jspm bundle react + react-dom bundles/react.js
```

And others that look like:

```
jspm bundle [my-package] bundles/my-package.js
```

I thought the latter would mean I'd now be able to rely on the bundle for when 'my-package' is imported, but System still seems to be looking for the `jspm_packages/my-package/my-package@x.x.x.json` file? Presumably it's something to do with the `[]` part of the expression, but I need to do this to avoid other packages it may import being bundled too.

I thought `[]` meant 'this, and only this package'? Should I be doing something else?

**Comment by aluanhaddad** [comment]
I think you need to add the inject flag when bundling the external library.

**Comment by jamiewinder** [comment]
Sorry, yes I am doing that. The js file url is added to the bundles section, but the json file url is not. The result is that the json file is read from jspm_packages when it is imported, followed by the bundle file. I can add the json to the bundle too, but I'm not sure why I have to if that seems to be the real entry point for the package as far as jspm is concerned.

**Comment by guybedford** [comment]
@jamiewinder in jspm 0.17, package configuration is itself treated as a module that needs to be bundled. So what would really be needed is `jspm bundle [my-package] + [npm:my-package@x.y.z.json] bundles/my-package.js`. Workflows around package configuration bundling are still a little brittle and part of the instability of jspm 0.17.

**Comment by GongT** [comment]
+1

need bundle my project files without any dependency

and bundle some dependency without my project files (already can be done with jspm bundle a + b +c ... )
