### ISSUE TITLE
Why is the "Production Workflows" wiki "oipoipoio"?

### ISSUE THREAD

**Issue by kdex** [jspm/jspm-cli#2128]
Recently, I noticted that in the wiki, the [Production Workflows](https://github.com/jspm/jspm-cli/wiki/Production-Workflows) page [was "sad"](https://github.com/jspm/jspm-cli/issues/1705).

According to its [history](https://github.com/jspm/jspm-cli/wiki/Production-Workflows/_history), three days ago, @geoffrey-gaurav re-created the page with a content of "oipoipoio". His account seems like a bot to me.

In order to prevent future vandalism, please edit the GitHub project settings and make the wiki available to contributors only, or, in case you don't need it, disable it.

**Comment by guybedford** [comment]
Thanks, removed.
