### ISSUE TITLE
0.17 Beta - Promise polyfill

### ISSUE THREAD

**Issue by peteringram0** [jspm/jspm-cli#2129]
Hey, 

Has the ES6 promise polyfill been removed in 0.17? If so maybe this should be mentioned somewhere in the docs. 

Thanks

**Comment by aluanhaddad** [comment]
Do you mean the loader polyfill that is conditionally, included by `system.js`? It is still there in the latest SystemJS release.

**Comment by peteringram0** [comment]
No, on the older version a promise pollyfill was added on build.

**Comment by aluanhaddad** [comment]
Are you transpiling with Babel, TypeScript or Traceur? There were changes in how the Babel runtime was included I believe and this may be related.

**Comment by peteringram0** [comment]
Its running though plugin-babel

thanks for the help

**Comment by guybedford** [comment]
plugin-babel does make breaking changes with each new release, it is advisable to include a promise polyfill manually though.
