### ISSUE TITLE
Unable to install from jspm registry

### ISSUE THREAD

**Issue by knut-soltvedt** [jspm/jspm-cli#2131]
Hi ! 

I'm just discovering jspm and I'm struggling with a problem I don't understand : I'm not able to install from the jspm registry, while github and npm ones work properly.
Here's the output of, say, `jspm install angular` : 
```bash
err  Repo jspm:angular not found. Perhaps try jspm install npm:angular.
```
Now, here are the details : 
```bash
$ jspm -v
0.16.46
Running against local jspm install.
```
```bash
$ jspm registry export jspm
jspm config registries.jspm.remote https://registry.jspm.io
jspm config registries.jspm.repo https://github.com/jspm/registry.git
jspm config registries.jspm.handler jspm-registry
```
Is there something wrong with my registry config ?

Thanks !

**Comment by knut-soltvedt** [comment]
No response in more than 3 days :cry: 

Maybe I should mention that the `angular` package is referenced in the `repository.json` of the JSPM registry repo (see https://github.com/jspm/registry/blob/master/registry.json#L32) :
```
"angular": "github:angular/bower-angular",
```
And that trying to install it directly from github via : 
```
jspm install github:angular/bower-angular
```
works properly. 

So I'm not sure I face a simple "package does not exists" PEBKAC error as my previous message could have let you think.

Moreover, it seems I'm not the only one given the recent issue #2133.

**Comment by guybedford** [comment]
This is odd, I'm not sure what would be going on here. Perhaps try running `jspm cc` to completely clear the local caches.

It may also be worth ensuring you can clone the registry manually via `git clone https://github.com/jspm/registry.git`.

**Comment by knut-soltvedt** [comment]
Thanks for your reply !

So I first tried to clear the caches, without any result. I was still able to clone the registry repository, so I tried to setup a local registry as mentioned in the documentation (http://jspm.io/docs/registries.html#creating-a-private-jspm-registry) : 
```bash
$ jspm registry export jspm
jspm config registries.jspm.remote https://registry.jspm.io
jspm config registries.jspm.repo /tmp/registry/.git
jspm config registries.jspm.handler jspm-registry
```
... and I cleared the caches again, in case of. Unfortunately, it's not working either.

I'm kind of running out of ideas, so here's my `~/.jspm/` dir tree : 
```
$ tree ~/.jspm
.
├── config
├── github-cache
├── jspm-cache
└── npm-cache
```
And the content of my `~/.jspm/config` file : 
```
{
  "defaultTranspiler": "babel",
  "defaultRegistry": "jspm",
  "strictSSL": true,
  "registries": {
    "github": {
      "remote": "https://github.jspm.io",
      "auth": [my_secret_token],
      "maxRepoSize": 0,
      "handler": "jspm-github"
    },
    "npm": {
      "handler": "jspm-npm",
      "remote": "https://npm.jspm.io"
    },
    "jspm": {
      "remote": "https://registry.jspm.io",
      "repo": "/tmp/registry/.git",
      "handler": "jspm-registry"
    }
  }
}
```
Moreover, I've installed jspm from npm version `3.10.8` on an ArchLinux system.

Eventually can give me a pointer to the snippet that do the registry lookup so that I can try to understand what's going on ?

Thanks again :)

**Comment by guybedford** [comment]
This is very strange. It must be some kind of system incompatibilty but it would be very interesting to find out the cause.

The code that does this is `jspm-registry-endpoint` - https://github.com/jspm/registry-endpoint/blob/master/registry.js#L54. Which basically clones the registry project (https://github.com/jspm/registry-endpoint/blob/master/registry.js#L144) into the path at `~/.jspm/registry-cache` so that the regsistry JSON file should be available at `~/.jspm/registry-cache/registry.json`.

Perhaps check if that file is there ok. Apart from that all it is doing is loading that JSON file and returning the redirect response.

**Comment by knut-soltvedt** [comment]
Alright, so simply copying the `registry.json` file into the `~/.jspm/jspm_cache/` directory quick fixes the problem - I'm able to install package from the registry.

But I think I got it.

Here https://github.com/jspm/registry-endpoint/blob/master/registry.js#L203 you assume you'll find `Not a git repo` in the error string from the `git remote show origin -n` exec() call at line 175, in the case the repo has not been already created. However, here is the error I have : 
```
Error: Command failed: git remote show origin -n
     fatal: Ni ceci ni aucun de ses répertoires parents n'est un dépôt git : .git
```
... French locale set up. If I replace the string to be catched with it's translation, the problem is solved.

**Comment by knut-soltvedt** [comment]
Btw, I'll try to prepare a patch for this when I got time ;)

**Comment by knut-soltvedt** [comment]
Here's a simple bugfix : https://github.com/jspm/registry-endpoint/pull/16

**Comment by knut-soltvedt** [comment]
Since the bugfix has been merged, I close the issue. 

Jspm is a cool project, it really helps ; thanks for this !
