### ISSUE TITLE
[0.17.0-beta.29] npm compatibility issue - packages that use module.parent (e.g. uniqid)

### ISSUE THREAD

**Issue by joeldenning** [jspm/jspm-cli#2134]
Any npm packages that use [`module.parent`](https://nodejs.org/api/modules.html#modules_module_parent) are not compatible with jspm. An example npm package that does this is uniqid@>4 ([exact usage here](https://github.com/bayorigin/uniqid/blob/master/index.js#L33)). Since uniqid is a downstream dependency of MeoMix/jspm-loader-css (the best maintained fork of css modules for jspm), using CSS modules with jspm requires doing a custom resolve `jspm resolve --only npm:uniqid@1.0.0`, since 1.0.0 doesn't use module.parent.

Is module.parent something that jspm should try to support? My guess is that it would not really be possible, since dependencies are instantiated before dependents are. Even if support is possible, though, I'm going to look into pull requesting uniqid so that it doesn't use module.parent.

**Comment by guybedford** [comment]
See also https://github.com/systemjs/systemjs/issues/1470. In theory it would be possible to support this as the parent module does exist at the time its call to require is sent, and it could be an argument added to provide this.

But we do have to draw a line on the CJS support - there's always going to be features we haven't included as it is a detailed API. I'm not sure Webpack even supports this feature. (although it does seem to support children and loaded as far as I can tell)

**Comment by joeldenning** [comment]
Thanks for the quick response -- I agree that there has to be a line drawn somewhere on cjs support, and so for my immediate problem I think it's probably easier just to pull request uniqid (see https://github.com/bayorigin/uniqid/pull/9).

For my own curiosity, though, I'm curious how module.parent is even possible in systemjs. Here's my understanding of what happens during a build/bundle; I'd be interested to hear what I'm missing or where I'm wrong:

```js
// parent module
console.log("Parent module being instantiated");
require("child-module");
exports.foo = 'bar';
```

```js
// child module
console.log("Child module being instantiated");
console.log("module.parent.foo = ", module.parent.foo);
```

1. jspm starts bundling "parent-module".
2. "parent-module" is read in as a string from the file system.
3. systemjs detects that parent-module has a `require('child-module')`
4. child-module is loaded
5. child-module is instantiated, the exported values are put into a Module object
6. parent module is instantiated. During instantiation, the Module object for child-module is given to parent module synchronously when `require("child-module")` is called.

If 5 happens before 6, then how could module.parent exist during 5?

**Comment by joeldenning** [comment]
Also, for reference, it appears that webpack doesn't support module.parent either. See https://github.com/webpack/webpack/issues/1569

**Comment by guybedford** [comment]
@joeldenning remember that the CommonJS require is executing - parent module executes, hits the require('child-module') step, then executes child module. See also https://nodejs.org/api/modules.html#modules_cycles.

**Comment by joeldenning** [comment]
I see, that makes sense now. Thanks for the explanation.

I'll close this issue since it seems like support for module.parent crosses the line of what systemjs CJS support should be.
