### ISSUE TITLE
bundle-sfx changes number (z-index) in CSS style

### ISSUE THREAD

**Issue by letmaik** [jspm/jspm-cli#2135]
I know this sounds weird, but, when I use `bundle-sfx` (in dev mode everything works) then the output has `z-index:23` whereas the original has `z-index: 2000`. It's a mystery to me. I tried putting the CSS rule in different files but always the same replacement.

jspm version: 0.16.46
plugin-css: 0.1.31
clean-css: 3.4.20

**Comment by aluanhaddad** [comment]
I haven't investigated much, but I think this is the likely cause http://cssnano.co/optimisations/zindex
See https://github.com/systemjs/plugin-css

**Comment by letmaik** [comment]
Interesting, looks like that's what's happening. @guybedford Is there a way to disable that? I can't see any way to provide options to cssnano within plugin-css.

**Comment by guybedford** [comment]
Added safe optimizations only in https://github.com/systemjs/plugin-css/commit/19bcaeb686b71809f728d8f222b64b42669a7784 for the next release.

**Comment by guybedford** [comment]
This has been released in the latest version of plugin-css.

**Comment by letmaik** [comment]
Works, thanks! :)
