### ISSUE TITLE
any way to use key authentication when fetching from github?

### ISSUE THREAD

**Issue by pocesar** [jspm/jspm-cli#2136]
I'm on windows and I use PuTTY authentication agent (pageant), and I use it for my github pushes. is there any way to use pageant instead of providing an access token? I'm saying this because every time I 'npm update' JSPM, the access token auth breaks.

**Comment by guybedford** [comment]
There isn't currently alternative authentication support. There was some churn in the GitHub authentication recently. Please do let me know if you have issues like this as that is a bug.
