### ISSUE TITLE
Need a way to clear depcache

### ISSUE THREAD

**Issue by togakangaroo** [jspm/jspm-cli#2140]
So consider this workflow
- During development you enable http/2 and in order to load things rapidly run a file watcher that regenerates the jspm config depcache.
- Since depcache is in the same config.js as everything else it must be committed - but that's not a big deal and could almost be considered a good thing
- When deploying you would like to check out your code and bundle your scripts before deploying since http2 is not guaranteed (in our case in fact the webserver does not support it)
- After running `jspm bundle` you now have the bundle js file (I generally just overwrite my SPA entry point). However, note that that `config.js` _still contains the depcache_. 

In my tests this has resulted in all those queries still getting triggered even though there's a bundle of everything available. What is needed therefore is a way of clearing out the depcache key. Unfortunately though, since config.js is not a json file, naive json-parsing techniques won't work.

Therefore some sort of `clear-depcache` command would really help

**Comment by guybedford** [comment]
Sure a `jspm undepcache` or something similar is welcome. Let me know if you're interested in working on this.
