### ISSUE TITLE
global override for packages

### ISSUE THREAD

**Issue by Mosho1** [jspm/jspm-cli#2141]
I'd like to use a copy of a library (such as react) from cdnjs. To do that, I removed it in `config.js` from every library that uses it and only have it in `paths` pointing to the cdn. This works very well but every time I install a package I have to either edit `overrides` in `package.json` for that specific package, or go to `config.js` again and remove the newly added references to the copy of the library (that I want to get from cdnjs) that was installed when I installed the new library that has it as a dependency on `npm`. 

Is there a way to automate this with jspm?

**Comment by guybedford** [comment]
Rather than removing the map entry, try just setting the CDN path in the map config rather:

```javascript
System.config({
  map: {
    react: 'https://cdnjs.com/...'
  }
});
```

That will then at least leave it in place and respect that resolution. There are still annoying edge cases here though.
