### ISSUE TITLE
After upgrading from 0.16.33 -> 0.16.47, Babel starts throwing errors

### ISSUE THREAD

**Issue by onlywei** [jspm/jspm-cli#2143]
I'm confused what Babel version my SystemJS builder is running now. I just did a JSPM upgrade to 0.16.47, and it seems like I now have `babel-generator` version 6.18.0, even though I have `babel-core` 5.8.25 still defined in my `package.json`. I'm now getting errors when I try to run a build:

```
[18:37:33] ReferenceError: public/jspm_packages/github/select2/select2@3.5.4/select2.js: unknown node of type undefined with constructor "Object"
    at Generator.print (/Users/wei/development/urbancompass/src/js/node_modules/babel-generator/lib/printer.js:279:13)
```

I suspect this may be because of the new Babel version? Did I automatically get upgraded somehow to Babel 6 when I upgraded JSPM to the new patch version?

With the new versions of SystemJS and SystemJS Builder that were installed with JSPM 0.16.47, am I supposed to upgrade to Babel 6 everywhere? Right now, the version of Babel in my `jspm_packages` dir is still 5.8.25. How would I even update that? I thought that only 0.17.x beta supports Babel 6+.

**Comment by zbyte64** [comment]
I've been using `babel-core` 5.8.35 and it seems to work with jspm 0.16.47. I know that the subminor updates in `babel-core` do fix various issues with SystemJS. Try updating your babel requirements to `5.8.35` and see what happens.

**Comment by onlywei** [comment]
@zbyte64 thanks, I just tried that but it did not work.

It still looks like systemjs-builder is using babel-generator 6+, while the in-browser systemjs loader is using Babel 5.x.

**Comment by aluanhaddad** [comment]
Make sure you are building either from the command line via
```bash
> jspm bundle app
```
or programmatically via
```js
const Builder = require('jspm').Builder;
const builder = new Builder();
```

**Comment by onlywei** [comment]
@aluanhaddad I am doing the latter.

**Comment by aluanhaddad** [comment]
Sorry, I should have asked earlier, but what is your intent. Do you wish to use babel 5.8.35 or Babel 6? Also, can you share a minimal repro?

**Comment by guybedford** [comment]
This may be an issue with the structure of node_modules. SystemJS builder will use Babel 6 internally, and that will then be run alongside Babel 5 transforms as well. If the node_modules isn't quite right it may lead to conflicts like this. On a fresh install though I believe the standard Babel 5 workflow with jspm 0.16 is working fine though? A replication would help to look into it further.

**Comment by onlywei** [comment]
I solved my error, but I am still unsure which version of Babel that SystemJS builder is using. The problem with my installation is that I am using a fork of the package `ui-select2`, which was not installed correctly with JSPM using the override shim:

```-o "{'shim': {'src/select2': { 'format': 'global', 'deps': ['select2'] } } }"```

After that was done, I no longer have any errors.
