### ISSUE TITLE
trying to use typescript 2

### ISSUE THREAD

**Issue by rafakwolf** [jspm/jspm-cli#2145]
Installing typescript 2 ...  **jspm install npm:typescript** ,  getting this message:

**warn typescript@2.0.6 is unsupported for this version of jspm. Use jspm dl-loader --latest to update.**

Then exec **jspm dl-loader --latest** ... and so the typescript is downgraded to 1.6.2 ... 

It is possible to use typescript 2 with jspm ?

Thanks!

**Comment by guybedford** [comment]
Which version of jspm are you running here? Note that jspm 0.17 beta with plugin-typescript is the recommended approach.

**Comment by aluanhaddad** [comment]
@guybedford this happens with jspm@0.16.47 and may be due to https://github.com/jspm/jspm-cli/blob/master/lib/core.js#L48.

@rafakwolf I believe this warning can be safely ignored but you should update to beta 0.17.

**Comment by rafakwolf** [comment]
@guybedford if instead of loading the files .TS ... I load the .js compiled files, should work too, right?

**Comment by rafakwolf** [comment]
@aluanhaddad  using the beta version... the same behavior happends, when i run  **jspm dl-loader --latest** the old version is restored. 

Thanks!

**Comment by rubyboy** [comment]
+1 (Having the same issue on jspm 0.16.47)
Would prefer to stick to v16 until v17 is out of beta, if possible.
Thanks!

**Comment by aluanhaddad** [comment]
Give this a shot, 
```bash
> jspm install --dev ts -o "{ dependencies: { typescript: 'npm:typescript@2.0.7' } }"
```
You don't need to run `jspm dl-loader --latest`.

**Comment by aluanhaddad** [comment]
I have opened #2162 to update the install process to download typescript@^2.0.7.

**Comment by rafakwolf** [comment]
@aluanhaddad this fix will be available in the next beta release?
thanks!

**Comment by aluanhaddad** [comment]
The Beta release already supports typescript 2.0 and above. I've been using it with typescript 2.1 for several months. This is just for those using the existing workflow without plugin-typescript. If you are using plugin-typescript you can already use any version would like.

I do not know if and when this will go in. I'm not a core contributor, and this is @guybedford's decision.

Honestly it may not even be worth doing given that even in 0.16.x plugin-typescript offers the best workflow. Furthermore you can already obtain this by simply installing the package manually. It just doesn't work with the `dl- loader latest` command.
