### ISSUE TITLE
Error messages in code are very non-descript

### ISSUE THREAD

**Issue by chadfurman** [jspm/jspm-cli#2147]
I'm sure this has a solution -- perhaps I'm using sourcemaps wrong -- however, every error I get is referencing the same line of code in system.src.js:

```
system.src.js:122 Uncaught (in promise) Error: (SystemJS) payload is not defined(…)
t @ system.src.js:122
p @ system.src.js:692
(anonymous function) @ system.src.js:629
g @ system.src.js:774
b @ system.src.js:969
f @ system.src.js:628
m @ system.src.js:674
(anonymous function) @ system.src.js:490
```

~~Certainly looks like a byproduct of minification.  I do have a gulp task wrapping my code.  System.js loads in my minified app.js -- is that what the problem is?~~

~~Do I use non-minified code with system.js?~~

Update: I removed my minification task from gulp and verified the file being included isn't minified -- I'm still getting the exact same error.

**Comment by OrKoN** [comment]
@chadfurman click on three three dots (payload is not defined (..)) to expand the stack trace.

**Comment by chadfurman** [comment]
@OrKoN I posted the expanded stacktrace.  As you can see, not helpful.
