### ISSUE TITLE
question [0.17.0-beta.31] jspm build command chance error ! how to report this 

### ISSUE THREAD

**Issue by shaoahs** [jspm/jspm-cli#2150]
jspm bundle is normal !
jspm build has chance !
my source code like this
```
import * as a from 'a';
import * as b from 'b';
import * as c from 'c';
```
use old beta version is nothing happened
use 0.17.0-beta.31 found error message
`too much recursion   system.js%20line%204%20%3E%20eval:3:15281`
then change to
```
import * as b from 'b';
import * as c from 'c';
import * as a from 'a';
```
jspm build is normal !
how to check this code style has problem ?
use jscs check is no error !
use jshint check is no error !

**Comment by guybedford** [comment]
Is the issue here shown during bundling or when running the bundle in the
browser? Will this replicate for any 'a' 'b' and 'c'?

**Comment by shaoahs** [comment]
in the browser !
happen to know 'game.js' of project.
my project 'import' keyword dependence is no rules.
how to check import dependence has problem ?

/* dependence A, B, C, D */  this rule in jspm 0.17.31 has 'too much recursion ' message
'too much recursion 'message  is in 'function init()'. runtime error !

/* dependence A, D, C, B */ this rule in jspm 0.17.31 is normal !
is happened in 'mithril' framework. it is 'config:ctrl.config' attribute of component 
```
//-------------------------------------------------------------------
// in old jspm beta version (in the browser  is normal !)
// in jspm 0.17.31beta version (in the browser  is happen  too much recursion!)
//-----------
import m from 'mithril';
import * as nuts from 'nuts';          /* dependence A */
import * as scene from 'slotTest/scene';         /* dependence B */
import * as entity from 'slotTest/entity';         /* dependence C */
import * as loading from 'slotTest/loading/base';    /* dependence D */

//------------------------------------------------------------------------
// then change this 
// in jspm 0.17.31beta version (in the browser  is normal !)
//-----------
import m from 'mithril';
import * as nuts from 'nuts';                 /* dependence A */
import * as entity from 'slotTest/entity';   /* dependence C */
import * as loading from 'slotTest/loading/base';   /* dependence D */
import * as scene from 'slotTest/scene';          /* dependence B */



/**
 * mithril component
 */
var component = {
  controller:(args) => {
    let conf = args.config;
    let setGame = args.setGame;
    let game = null;
    function init(element, isInit/*, context*/) {
      if (isInit || game) {
        return;
      }
      conf.event = scene.init();
      conf.canvas = element;
      game = nuts.game.run(conf);
      setGame(game);

      scene.setObject({
        game:game,
        entity:entity
      });
      entity.setObject({
        game:game,
        loading:loading
      });
    }

    return {
      config:init
    };
  },

  view: (ctrl) => {
    return m('canvas.game', { config:ctrl.config });
  }
};

export default component;

```

**Comment by shaoahs** [comment]
try  use
`jspm build --format amd --minify --skip-rollup`
then everything is ok!
try use
` jspm build --format amd --minify`
then care  about  import dependence

so maybe is  rollup ?

**Comment by guybedford** [comment]
@shaoahs so the line with "too much recursion" is shown when running that build in the browser? If so can you perhaps share the output build file with and without rollup, or a reduced version of it for me to have a look?

**Comment by shaoahs** [comment]
yes ! click UI button then happened !
project information
https://github.com/shaoahs/slotTest/blob/master/readme.md

project source code download
https://github.com/shaoahs/slotTest/archive/master.zip
