### ISSUE TITLE
When using --development, JSPM can't find the file

### ISSUE THREAD

**Issue by matthew-dean** [jspm/jspm-cli#2151]
I'm using `jspm build src/scripts/main.js public/dist/js/application.js`. It works find unless I append `--development`, in which case I get this:
```
Creating the single-file build for src/scripts/main.js public/dist/js/application.js...

err  Error on fetch for app/main.js public/dist/js/application.js at file:///Username/example/public/src/scripts/main.js public/dist/js/application.js
  Error: ENOENT: no such file or directory, open '/Username/public/src/scripts/main.js public/dist/js/application.js'
```
It looks like it tries to concat `/Username/public/src/scripts/main.js public/dist/js/application.js` as one file (with a space in the middle). I've tried putting different quotes around it, but it doesn't fix it. Help?

I'm on jspm@0.17.0-beta.31 and had the same issue with beta 29.

**Comment by guybedford** [comment]
Try using `--dev` instead of `--development`.
