### ISSUE TITLE
ETIMEDOUT error with jspm install, no retry

### ISSUE THREAD

**Issue by mayerwin** [jspm/jspm-cli#2154]
I have the following fairly straightforward `package.json` file from [this template project](https://github.com/ServiceStackApps/ReactDesktopApps):
https://github.com/ServiceStackApps/ReactDesktopApps/blob/master/src/DefaultApp/DefaultApp/package.json

When running `jspm install`, it will succeed in "Looking up" and having "Installed" a bunch of modules, and fail after about 30s-40s with the following kind of error (without actually spending time on waiting or retrying a given module, it immediately throws this error):

> warn Error on lookup for npm:arr-flatten
>      Error: connect ETIMEDOUT 151.101.8.162:443
>          at Object.exports._errnoException (util.js:907:11)
>          at exports._exceptionWithHostPort (util.js:930:20)
>          at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14)

Or:

> ok   Installed npm:evp_bytestokey@^1.0.0 (1.0.0)
> ok   Installed npm:browserify-aes@^1.0.4 (1.0.6)
> ok   Installed npm:parse-asn1@^5.0.0 (5.0.0)
> ok   Installed npm:bn.js@^4.1.0 (4.11.6)
> ok   Installed npm:miller-rabin@^4.0.0 (4.0.0)
> ok   Installed npm:buffer-xor@^1.0.2 (1.0.3)
> ok   Installed npm:des.js@^1.0.0 (1.0.0)
> ok   Installed npm:minimalistic-assert@^1.0.0 (1.0.0)
> ok   Installed npm:asn1.js@^4.0.0 (4.8.1)
>      Looking up npm:ripemd160
>      Looking up npm:sha.js
> ok   Installed npm:randombytes@^2.0.0 (2.0.3)
> ok   Installed npm:create-hash@^1.1.0 (1.1.2)
> ok   Installed npm:ripemd160@^1.0.0 (1.0.1)
> ok   Installed npm:cipher-base@^1.0.1 (1.0.3)
> ok   Installed npm:brorand@^1.0.1 (1.0.6)
> 
> warn Error on lookup for npm:string_decoder
>      Error: connect ETIMEDOUT 151.101.8.162:443
>          at Object.exports._errnoException (util.js:907:11)
>          at exports._exceptionWithHostPort (util.js:930:20)
>          at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14)
> 
> err  Error looking up npm:string_decoder.
> 
> warn Installation changes not saved.
> 

Then if I relaunch `jspm install` many times it will eventually run once without error (having installed everything), though it can fail again afterwards. In a first run it may successfully have "Installed" arr-flatten", and then in the following run it may "Error on lookup for npm:arr-flatten". The error can affect any module. I can provide full output if necessary (quit long).

I tried disabling my firewall on my Asus N56U router with the Padavan firmware (I have fibre Gigabit Internet and no connection stability issues), rebooting the router, running `npm set maxsockets 50` (**does it actually help jspm?**), but the only thing that works consistently is using my metered 3G connection instead of my router connected to fibre (both are accessed over Wifi)... No other software I am using is that sensitive to the underlying network topology/hardware (and I am using a very common router), so something is amiss.

**Comment by kbherbert** [comment]
I appear to be receiving the same error which just started this afternoon with no change to my configuration...CI build started failing with:

 fatal: unable to access 'https://github.com/jspm/registry.git/

**Comment by OrKoN** [comment]
@kbherbert I also see errors like this sometimes... it looks like a network error to me. Actually, there are many issues with npm which mention the same IP address/error: https://github.com/npm/npm/issues/13804 https://github.com/npm/npm/issues/13366 So it is probably not a JSPM-specific issue...

**Comment by mayerwin** [comment]
It is for sure a JSPM issue as there should be a way to automatically retry the specific package on failure, instead of stopping the whole thing. This would be enough to solve the problem. There can be plenty of good or wrong reasons why the network is bad, what matters is that these conditions are unfortunately common and JSPM (and NPM) should be designed to work even over crappy connections (if necessary with a config flag to increase the number of retries).

**Comment by kbherbert** [comment]
Thanks for the detail @OrKoN. I was able to work around this for the time being by setting "sslVerify" to "false" in my git config. But what is strange is that it started occurring out of nowhere yesterday on an otherwise stable build. I am behind a corporate firewall and perhaps some settings changed there, but not sure

**Comment by OrKoN** [comment]
@mayerwin I think JSPM does 3 attempts to retry by default. There is a config for that: https://github.com/jspm/jspm-cli/blob/0.17/lib/registry.js#L97 ( ~/.jspm/config)

**Comment by OrKoN** [comment]
@mayerwin I am not sure if it is due to the bad network or due to the bad npm registry servers ;-)

**Comment by mayerwin** [comment]
@OrKoN Thanks for the suggestion, I tried running `jspm config maxRetries 1000` and then `jspm install` but it fails very quickly as before (definitely no 1000 retries). Is it the right way to change this setting?

Here is the `AppData\Local\.jspm\config` file:

```
{
  "defaultTranspiler": "babel",
  "defaultRegistry": "jspm",
  "strictSSL": true,
  "registries": {
    "github": {
      "handler": "jspm-github",
      "remote": "https://github.jspm.io"
    },
    "npm": {
      "handler": "jspm-npm",
      "remote": "https://npm.jspm.io"
    },
    "jspm": {
      "handler": "jspm-registry",
      "remote": "https://registry.jspm.io"
    }
  },
  "maxRetries": 1000
}
```

**Comment by mayerwin** [comment]
It is definitely not because of bad npm registry servers as switching to my 3G connection just works without hiccups. The ISP (MyRepublic) is definitely doing something it shouldn't, but the solution is still to assume this kind of things happen and support a way around.

**Comment by OrKoN** [comment]
@mayerwin I think the only way to find out is to debug what is going on. The relevant parts of the code probably are https://github.com/jspm/jspm-cli/blob/5963d0e7929d5d277f670af64f03ed75743ecc9d/lib/registry.js#L156 and probably https://github.com/jspm/npm/blob/master/lib/npm.js#L242

**Comment by mayerwin** [comment]
Thanks for the references. There you go. I changed https://github.com/jspm/npm/blob/master/lib/npm.js#L242 to the following:
`        if (err.code == 'ENOTFOUND' && err.toString().indexOf('getaddrinfo') != -1 || err.code == 'ECONNRESET' || err.code == 'ETIMEDOUT') {
`
as ETIMEDOUT wasn't a retryable error, and it worked (i.e. retried) kinda flawlessly: 

![image](https://cloud.githubusercontent.com/assets/2272127/20032450/13093922-a3c5-11e6-85ff-7fe12a61971f.png)

I just submitted a PR: https://github.com/jspm/npm/pull/156. If you confirm this is the right way to go, I'll be happy to submit a similar PR to npm (I saw people struggling with the same issue).

**Comment by OrKoN** [comment]
Interesting, I think it's the way to go but only @guybedford can say for sure. Btw, I have noticed that newest node versions also throw a ESOCKETTIMEDOUT error in situations where previously it was a ETIMEDOUT error. Maybe it is worth adding ESOCKETTIMEDOUT to the PR.

**Comment by mayerwin** [comment]
OK, I have added ESOCKETTIMEDOUT to the PR to be future proof as this should also be retryable.
