### ISSUE TITLE
Using rollup but packages bigger than webpack? (Perhaps configuration issue)

### ISSUE THREAD

**Issue by babakness** [jspm/jspm-cli#2155]
Using 0.17@beta. I have tried redux with it but did give blissfuljs a go. I install as follows

jspm install npm:blissfuljs

I bundle using

jspm bundle main.js

I also tried this way

jspm build main.js bundle.js

This increased the bundle size by ~20kb. Compared to the same app bundled with webpack@beta, the jspm version increased by over 10kb more.

With the jspm build method I get a notice about optimization but not with the jspm bundle method; both are roughly the same size.

Not sure if I'm bundling / building correctly with jspm. Any advise appreciated, thanks.

**Comment by OrKoN** [comment]
@babakness the docs say that only the build command does optimizations using Rollup (http://jspm.io/0.17-beta-guide/static-builds-with-rollup-optimization.html) If you could share a sample app (w/ webpack && w/ jspm) I really would like to play with it and compare!

The difference by 10kb may be explained by the fact that JSPM embeds a reduced version of SystemJS in the bundle (but I am not sure about this).
