### ISSUE TITLE
jspm install fails in bizarre way if $HOME/.jspm is a symlink

### ISSUE THREAD

**Issue by myitcv** [jspm/jspm-cli#2158]
Would appreciate any help on the following issue.

On our CI server, we're seeing the following error:

```
$ jspm install
...

err  Repo jspm:jquery not found. Perhaps try jspm install npm:jquery.
```

Running through what I believe to be exactly the same steps, in a docker container from the same image, but by hand: no issue.

Can anyone give me a rough idea of how best to go about debugging what's going on here?

Thanks

**Comment by OrKoN** [comment]
There is a similar issue here: https://github.com/jspm/jspm-cli/issues/2157 with another package though.

**Comment by myitcv** [comment]
@OrKoN - thanks. I'm wondering whether there's actually some sort Github issue here. From my local box, I'm not seeing the error above as I said, but I'm seeing a lot of traffic being dropped, failed connections etc to Github.

**Comment by OrKoN** [comment]
@myitcv there is a similar issue for the network problems as well https://github.com/jspm/jspm-cli/issues/2154 What is the git version that you have on your CI server?

**Comment by myitcv** [comment]
@OrKoN `git version 2.1.4` in our CI containers.

**Comment by myitcv** [comment]
Now I'm fairly consistently unable to complete a `jspm install -f` on my machine (not the CI machine as reported earlier). Errors of the sort:

```
...
ok   Installed d3 as npm:d3@3 (3.5.17)
ok   Installed moment as npm:moment@2.13.0 (2.13.0)
ok   Installed npm:lodash@^3.10.0 (3.10.1)
ok   Installed github:components/jqueryui (1.11.4)
ok   Installed myitcv/Wijmo-Enterprise as github:myitcv/Wijmo-Enterprise@v9.40.20161.0 (v9.40.20161.0)
ok   Installed npm:core-js@^1.0.0 (1.2.7)

warn Error on download for github:jspm/nodelibs-process
     Error: connect ECONNREFUSED 192.30.253.116:443
         at Object.exports._errnoException (util.js:1026:11)
         at exports._exceptionWithHostPort (util.js:1049:20)
         at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)

err  Error downloading github:jspm/nodelibs-process.

warn Installation changes not saved.
```

I have completed a `jspm registry config github`, so I don't think this can be a rate-limiting issue (unless something on the Github side has changed?)

**Comment by myitcv** [comment]
Setting `NODE_DEBUG=request` allows me to get a lot of useful information, but still not been able to track down why I'm getting the two errors I reported above:

1. the `ECONNREFUSED` errors on my local machine
2. the `Repo jspm:jquery not found.` errors on our CI box

**Comment by myitcv** [comment]
I'm willing to bet the errors on my machine relating to point 1 (`ECONNREFUSED` for random, different packages each time I run `jspm install`) could well be Github/network issues.

@guybedford - any thoughts on the error we see every time from point 2, i.e. `Repo jspm:jquery not found`?

**Comment by myitcv** [comment]
I think I've tracked down the cause of the issue on our CI server (I'm now also fully convinced the issues on my local machine are Github/network-route-to-Github related)

It appears to have been something related to `$HOME/.jspm` being a symlink in our CI setup. Slightly tweaking that in our build setup, then `rsync`-ing directories, and we're back up and running.

Don't have a full repro yet... will try and rectify that and post here. This also appears to have been a change in behaviour because this definitely worked before (where I'm yet to define what "before" means; could still be something subtly changed in our setup)

For the record

```
$ jspm --version
0.16.47
Running against local jspm install.
```

**Comment by myitcv** [comment]
I should add that it appears my local issues are not necessarily connected to network issues. 

I had understood the following to be equivalent:

```bash
# 1
jspm cache-clear
jspm install

# 2
jspm install -f
```

However whilst the first succeeds, the second reliably fails every time with various `ECONNREFUSED` errors as reported above.

**Comment by togakangaroo** [comment]
This honestly sounds similar to an issue I had about a year and a half ago. Turned out that github was rate-limiting requests. There is some way (I forget how) to give jspm your github credentials. The rate limit for non-anonymous requests is much higher.

**Comment by myitcv** [comment]
@togakangaroo thanks for the cross reference. All of my requests are done with credentials. 

Using `NODE_DEBUG=request` I've started to compare the requests that are made via `jspm cache-clear && jspm install` vs `jspm install -f`; there are many more differences than I would have imagined given the two are documented as being equivalent.

**Comment by guybedford** [comment]
The 0.4.3 version of `jspm-registry` on npm should resolve this now. But please post back if you are still seeing this with that version.

**Comment by myitcv** [comment]
Thanks @guybedford
