### ISSUE TITLE
babel-plugin-transform-class-properties on jspm 0.16

### ISSUE THREAD

**Issue by Ashoat** [jspm/jspm-cli#2159]
I'm trying to get [babel-plugin-transform-class-properties](https://babeljs.io/docs/plugins/transform-class-properties/) working on jspm 0.16.

I ran:
```
jspm install --dev npm:babel-plugin-transform-class-properties
```

Added the following to my config.js:
```
babelOptions: {
  "optional": [
    "runtime",
    "optimisation.modules.system"
  ]
},
meta: {
  "*.js": {
    "babelOptions": {
      "plugins": [
        "babel-plugin-transform-class-properties"
      ]
    }
  }
},
```

And I have the following in my .babelrc:
```
{
  "presets": ["latest", "react"],
  "plugins": ["transform-class-properties"],
}
```

However, when I load my website in my browser, I get:
```
system.src.js:122 Uncaught (in promise) Error: (SystemJS) http://localhost/~ashoat/squadcal/js/typeahead/typeahead-action-option.react.js: Unexpected token (26:18)(…)
```

Following is the line in question, contained within a class definition:
```
static homeText = "Home";
```

**Comment by aluanhaddad** [comment]
Which version of babel are you using? Also, which babel plugin of are you using, systemjs-plugin-babel or 16.0's default?

**Comment by guybedford** [comment]
This sort of workflow should work with jspm 0.17 I think.
