### ISSUE TITLE
usage in node - packages with browser field in package.json

### ISSUE THREAD

**Issue by Mosho1** [jspm/jspm-cli#2161]
I'm trying to install a package (`request`) which has a dependency on `form-data`, which has `browser: ./lib/browser` in its `package.json`. I would like to use this in `node`, what's the correct way to do this when installing?

**Comment by guybedford** [comment]
jspm 0.16 will always following the `browser` option. If you want the code to run in NodeJS through jspm, you must use jspm 0.17 which has the ability to automatically conditionally load the different Node v browser paths.
