### ISSUE TITLE
Struggles upgrading from jspm 0.16 to jspm 0.17 with Flow

### ISSUE THREAD

**Issue by Ashoat** [jspm/jspm-cli#2166]
Hi,

In response to a suggestion that jspm 0.17 could possibly support Babel plugins, I went ahead and upgraded to the beta. I have a project using React, JSX, and Flow type-checking, and I'm using async/await syntax.

In jspm 0.16 I was using babel-preset-react (for React, JSX, and Flow) and babel-preset-latest (for the async/await syntax). I `jspm install`'d both, and specified both in my .babelrc file.

I unfortunately can't seem to get all of these things working with jspm 0.17. My current issue is that I can't seem to get Babel to strip Flow type annotations. In-browser, I get a syntax error here:

```
import type { SquadInfo } from './squad-info';
            ^
```

This is [Flow syntax](https://flowtype.org/docs/syntax.html#importing-and-exporting-types) that should be stripped. The Babel React preset includes `babel-plugin-transform-flow-strip-types`, but I'm not able to get it working, even if I specify that plugin explicitly in the "plugins" array in both `package_config["meta"]["*.js"]["babelOptions"]` in jspm.config.js and in .babelrc. I've tried the 0.16 -> 0.17 upgrade path, as well as a clean 0.17 install; the problem occurs in both.

Some feedback (take as you will): I'm honestly fairly confused about how jspm interfaces with Babel, even after reading documentation. Does `package_config["meta"]["*.js"]["babelOptions"]` contain the same sort of configuration that .babelrc does? Is .babelrc even looked at when using jspm? The documentation mentions installing a JSX Babel module instead of a preset; are presets not supported? (The Babel documentation suggests using presets.) 

(Don't feel compelled to answer all these questions; there's just the sort of questions that come into my mind when trying to debug my problems, but I'm unfortunately I'm having trouble finding answers for them online. And of course, my sincere apologies if I'm missed some documentation on these subjects.)

And lastly - thanks so much for maintaining and supporting such a wonderful tool.

**Comment by Ashoat** [comment]
I investigated further and learned that in jspm 0.17, the Babel runtime transpilation is handled by systemjs-plugin-babel. I added some log lines in that code, and realized that my config was not being passed in. In my jspm.config.js I had defined the babelOptions object from within a specific module, and I don't think my entrypoint called `System.import` in the correct way to trigger the `babelOptions`. I've got the babelOptions config being passed in now, by reverting to a simple configuration:

```
SystemJS.config({
  paths: {
    "npm:": "jspm_packages/npm/"
  },
  browserConfig: {
    "baseURL": "js2"
  },
  devConfig: {
    "map": {
      "plugin-babel": "npm:systemjs-plugin-babel@0.0.17"
    }
  },
  transpiler: "plugin-babel",
  meta: {
    "*.js": {
      "babelOptions": {
        "presets": [
          "babel-preset-latest",
          "babel-preset-react"
        ]
      }
    }
  }
});
```

(Excluding the .json SystemJS call for brevity.)

Curiously, I now get an "require is not defined" error on the first line on my program, which is:
```
import 'babel-polyfill';
```
(Transpiled to `require("babel-polyfill")`)

This seems to be happening after the transpilation stage, so at least it seems that transpilation is now succeeding. Note that this new issue occurs both on bundles created via `jspm build` as well as the raw `System.import` approach.

**Comment by NervosaX** [comment]
```javascript
  meta: {
    "*.js": {
      "babelOptions": {
        "optional": [
          "runtime"
        ],
        "stage1": true,
        "plugins": [
          "babel-plugin-syntax-flow",
          "babel-plugin-tcomb",
          "babel-plugin-transform-flow-strip-types",
          "babel-plugin-transform-decorators-legacy",
          "babel-plugin-transform-react-jsx"
        ]
      }
    }
  },
```

Here are the plugins I have installed for using flowtypes (and adds tcomb to boot). May help you.
