### ISSUE TITLE
Source maps files broken because of not having full path

### ISSUE THREAD

**Issue by jithin1987** [jspm/jspm-cli#2167]
All the source map files in `build.js.map` for my app is missing file system path, all are flattened out.
Eg: I have this in my source map `"sources":[ "ViewStore.js"` which should have been `"sources":[ "src/stores/ViewStore.js"`

I am on jspm 0.17.0-beta.32

**Comment by guybedford** [comment]
If you're using Babel as your transpiler I think this was fixed in https://github.com/systemjs/plugin-babel/commit/cbd8f6706f21ecc0f6e52a147dc0a64daff2f038. Release to follow soon.

**Comment by eliagrady** [comment]
Adding this line on my end (Windows machine) resulted in sourcemap paths like this:
./src/objects/file:/C:/dev/modules/DFP/src/objects/user.js

**Comment by ArmorDarks** [comment]
@eliagrady  Probably it's related to https://github.com/jspm/jspm-cli/issues/2361
