### ISSUE TITLE
`jspm install` always `touch`es `package.json`

### ISSUE THREAD

**Issue by tamird** [jspm/jspm-cli#2170]
...even when no changes to package.json are made.

This is pretty annoying when used with a Makefile-based build system because `package.json` constantly has its mtime bumped.

@guybedford

**Comment by guybedford** [comment]
In jspm 0.17 this shouldn't be the case unless there are explicit changes to the package.json file.

**Comment by tamird** [comment]
Is there a timeline for the promotion of 0.17 out of "beta"? Alternatively, is it possible to backport this fix to 0.16?
