### ISSUE TITLE
jspm install is not reproducible, peer dependencies change 

### ISSUE THREAD

**Issue by mikz** [jspm/jspm-cli#2171]
# steps to reproduce

```sh
git clone https://gist.github.com/158ac114be12ab44e63ba5344277eec7.git
cd 158ac114be12ab44e63ba5344277eec7
npm install
jspm install
git diff
```

If you don't see the change immediately. Try running `jspm install` several times.

The change is following: 

```diff
diff --git a/jspm.config.js b/jspm.config.js
index d1c7693..08820a6 100644
--- a/jspm.config.js
+++ b/jspm.config.js
@@ -401,7 +401,7 @@ SystemJS.config({
     "path": "npm:jspm-nodelibs-path@0.2.0",
     "plugin-babel": "npm:systemjs-plugin-babel@0.0.17",
     "pluralize": "npm:pluralize@1.2.1",
-    "process": "npm:jspm-nodelibs-process@0.2.0",
+    "process": "github:jspm/nodelibs-process@0.2.0-alpha",
     "select2": "github:select2/select2@4.0.1",
     "virtual-dom": "npm:virtual-dom@2.1.1",
     "vm": "npm:jspm-nodelibs-vm@0.2.0"
diff --git a/package.json b/package.json
index 41258de..58df905 100644
--- a/package.json
+++ b/package.json
@@ -54,7 +54,7 @@
       "moment": "npm:moment@^2.10.3",
       "path": "npm:jspm-nodelibs-path@^0.2.0",
       "pluralize": "npm:pluralize@^1.1.2",
-      "process": "npm:jspm-nodelibs-process@^0.2.0",
+      "process": "github:jspm/nodelibs-process@^0.2.0-alpha",
       "virtual-dom": "npm:virtual-dom@^2.1.1",
       "vm": "npm:jspm-nodelibs-vm@^0.2.0"
     },
```

It flickers back and forth even on the same machine.

**Comment by guybedford** [comment]
You need to make sure you are running `jspm-nodelibs-util@0.2.1` and `jspm-nodelibs-path@0.2.1` as these had incorrect dependencies on `github:jspm/nodelibs-process`.

**Comment by mikz** [comment]
@guybedford thanks. Looks like that is working. 

But still, a rouge dependency can cause a flaky build. Imo the dependency resolution should be deterministic.

**Comment by adelespinasse** [comment]
I've been having this trouble too... I updated jspm-nodelibs-util and jspm-nodelibs-path with:
```
jspm update util
jspm update path
```
so they're now both on 0.2.1 (in my `jspm.config.js`; I didn't edit `package.json`).

After that, `jspm install` still seemed to randomly change its mind about whether to install `npm:jspm-nodelibs-http@0.2.0` or `github:jspm-nodelibs-http@0.2.0-alpha`. When I ran `jspm run` once, it updated the registry cache (see #2139) and went back to `npm:jspm-nodelibs-http@0.2.0`, and now it seems to be staying with that (#2139 has been quiet too), but my colleague, using the same `package.json` and `jspm.config.js`, is still having trouble.

It seems to sometimes modify both `package.json` and `jspm.config.js` and sometimes only the latter. I haven't figured out the pattern.

**Comment by mikz** [comment]
I'd like to say that this was pretty hard issue and no reproducible build system should be compromised by dependencies into changing the tree.

**Comment by jithin1987** [comment]
I noticed this too, but went away after doing `jspm install` twice. My guess is it's a bug with upgrade path from github to npm for nodellibs* packages. However after the double `jspm install` I haven't  noticed this issue.

**Comment by mikz** [comment]
For us it would just flicker on every machine. With those dependencies it would just change on almost every install depending on the internet connection. That is IMO unacceptable for a stable dependency management. CI started failed with all dependencies locked.

**Comment by esbie** [comment]
We're seeing the same flicker by running `jspm install` on the same machine multiple times.
