### ISSUE TITLE
JSPM Build Error when minifying in ESM format

### ISSUE THREAD

**Issue by leepowellcouk** [jspm/jspm-cli#2174]
When attempting to run a jspm build and output as a ES6 module format I get an error at the uglify stage. So this:

    jspm build app/index.js dist/app.js --minify --skip-source-maps --format esm

Returns 
   
    err  Error: SyntaxError: Unexpected token: keyword (default) (line: 9403, col: 7, pos: 312642)
    Error
        at new JS_Parse_Error (eval at <anonymous> (/Users/leepowell/Sites/app/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1545:18)
    ...

However, when run without the `---minify` flag it compiles successfully.

The app at this stage is VERY simple with only one or two ES6 modules being loaded in.

**Comment by guybedford** [comment]
Can you share the unminified output here?

**Comment by leepowellcouk** [comment]
Looks like it's the sfx-esm builder template?
[https://gist.github.com/leepowellcouk/f78ba8e38a016f9f941c26ba755ee4d3](https://gist.github.com/leepowellcouk/f78ba8e38a016f9f941c26ba755ee4d3)

**Comment by guybedford** [comment]
Ah right. Yeah the issue here is that UglifyJS doesn't support ES module syntax at all.  So you'd want to output UMD or something else rather to enable minification.

To support ES6 minification we can upgrade to using Babili. There's an issue tracking this in https://github.com/systemjs/builder/issues/726, and if anyone is interested in working on this please let me know.

**Comment by aluanhaddad** [comment]
I think a lot of folks will run into this issue. I wonder if we should emit an error indicating that the options are currently incompatible. We would need to remove it when https://github.com/systemjs/builder/issues/726 is resolved.

Something like
```bash
jspm build app --minify --format esm

err  Error: Option --minify is incompatible with option --format esm, consider specifying a 
different format or skipping minification
```
