### ISSUE TITLE
Changes in my jspm.config.js keep getting clobbered

### ISSUE THREAD

**Issue by atrauzzi** [jspm/jspm-cli#2175]
Seems like every time I do a `jspm install`, my `jspm.config.js` gets rewritten and all the TypeScript-specific changes I put in are overwritten.

**Comment by guybedford** [comment]
Can you share the config file here?

**Comment by atrauzzi** [comment]
Actually -- before I do that..  I have noticed that sometimes I've run JSPM with incorrect arguments and been prompted as if I was doing an initial setup.  I usually ctrl-c out of those situations, but is it possible the file gets touched at that point?

**Comment by guybedford** [comment]
@atrauzzi I'm not sure, maybe. I'd be interested to know too what incorrect args would prompt like this.

**Comment by atrauzzi** [comment]
Hmm, let me watch for this to happen again.  I'll reopen if it comes up, I really think it might have just been something like that.
