### ISSUE TITLE
jspm bundle is not working with new versions of systemjs

### ISSUE THREAD

**Issue by AScripnic** [jspm/jspm-cli#2177]
Hello,
I was using SystemJS version 0.18.17 and it was working just fine with bundled javascript created by `jspm bundle index bundle.min.js --minify --inject` command. 

But I was getting error: `'Object doesn't support property or method 'config'` in Internet Explorer. I've updated to SystemJS 0.19.x versions and all of them fails when it's looking for a file, outside of the bundled one.

I've looked in config, and the file it's looking outside of the bundle is mapped there too.

While running `Object.keys(System.defined)`  my file is present in the list, but it's on the last position right after my bundled file.

**Comment by guybedford** [comment]
@AScripnic if it is in the last position, that means it's not in the bundle. You can check by reading the `System.register("...")` and `System.registerDynamic("...")` statements in the bundle itself to see if it definitely contains that missing module from the bundle.

**Comment by AScripnic** [comment]
@guybedford Thank you for your response.

I can't find it in `System.register("...")` or `System.registerDynamic("...")`, but I'm importing it the same way I'm importing other modules:

```javascript
import 'auth0/auth0/build/auth0';
```

and in my config it's like:

```javascript
{
...
"auth0/auth0": "github:auth0/auth0.js@7.0.0",
...
}
```

and the file `/build/auth0` is located in `auth0/auth0.js@7.0.0`, in not bundled version it works just fine and with 0.18.x versions too

The only way it's declared in my bundle is like: 
```javascript
define("github:auth0/auth0.js@7.0.0/build/auth0.js", [], c)
```

**Comment by guybedford** [comment]
The `define` means its in the bundle fine then. If you add a log statement, is the `define` call definitely running within the main synchronous execution of the bundle? Apart from that it's just verifying that the name matches up with the name in `System.bundles`. Are you seeing a network request to `auth0/auth0.js@7.0.0/build/auth0.js`?

**Comment by AScripnic** [comment]
Yes, it tries to make a separate call to this file.

I put some console.logs in my bundled file:
```javascript
! function(a, b, c) {
  console.log('before define');
  "undefined" != typeof module && module.exports ? module.exports = c() : "function" == typeof define && define.amd ? console.log('define moment') || define("github:auth0/auth0.js@7.0.0/build/auth0.js", [], c) : b[a] = c()
}
```

The first `console.log('before define')` is shown, but second ` console.log('define moment') ` is not. Could this be the reason?

**Comment by guybedford** [comment]
@AScripnic yes that could be the reason. I guess you can check the values of `"undefined" != typeof module && module.exports` and `"function" == typeof define && define.amd` in this environment to see why?

**Comment by AScripnic** [comment]
@guybedford I have logged all of this values in this order:
```javascript
      !function (a, b, c) {
        console.log('before define');
        console.log("undefined" != typeof module && module.exports);
        console.log("function" == typeof define && define.amd);

        "undefined" != typeof module && module.exports ? module.exports = c() : "function" == typeof define && define.amd ? console.log('define moment') || define("github:auth0/auth0.js@7.0.0/build/auth0.js", [], c) : b[a] = c()
      }
```

and the console looks like this:
![image](https://cloud.githubusercontent.com/assets/11028782/20485896/4b20c314-b006-11e6-84dc-088d55fcf131.png)

**Comment by guybedford** [comment]
It sounds like you need to ensure `module.exports` is not defined in the browser.

**Comment by AScripnic** [comment]
Could you please suggest a way to do it? 

I'm importing it this way, and it's the only one that is not loaded the correct way.
```javascript
import 'angular-cookies';
import 'auth0/angular-storage/dist/angular-storage';
import 'auth0/angular-jwt/dist/angular-jwt';
import 'auth0/auth0-angular';
import 'auth0/auth0/build/auth0';
```

**Comment by guybedford** [comment]
What browser environment are you using? If it's just a normal browser, then try `<script>window.module = undefined</script>`. Not sure what is setting the global module to be breaking this stuff in the first place though.

**Comment by AScripnic** [comment]
@guybedford I'm using Chrome version 54.0.2840.98, but it fails on FF 50.0 and Safari 10.0 as well.

I have updated my index.html this way, but it still shows that module.exports exists.
I have edited manually the bundle and edited `module = undefined` right before that module is defined and it worked just fine.

**Comment by ivignan** [comment]
hello @guybedford @AScripnic have you been able to figure out resolution for this issue? I am experiencing the same problem

**Comment by AScripnic** [comment]
@guybedford Is there a way to make `module` to be undefined by default as I'm doing `jspm bundle` quite often.

**Comment by guybedford** [comment]
What is the value of `window.module` then in the first place? It would be interesting to know why it is set, and what is setting it, as SystemJS itself wouldn't do this.

**Comment by AScripnic** [comment]
When writing `window.module` in browser console it's equal to `undefined`
