### ISSUE TITLE
 Anonymous System.register calls can only be made by modules loaded by SystemJS.import

### ISSUE THREAD

**Issue by atrauzzi** [jspm/jspm-cli#2178]
Getting a weird one:

```
Error: (SystemJS) Invalid System.register call. Anonymous System.register calls can only be made by modules loaded by SystemJS.import and not via script tags.
    @http://[MYFILE].ts!transpiled:1:30
    @http://[MYFILE].ts!transpiled:1:2
    
    Evaluating http://[MYFILE].ts
    Error loading http://[MYFILE].ts as "MYFILE.ts" from http://[ANOTHERFILE].tsx
```

I'm using TypeScript for things, error only seems to happen in Firefox and Edge.

**Comment by guybedford** [comment]
Can you share the contents of `http://[MYFILE].ts` here?

**Comment by atrauzzi** [comment]
Unfortunately it's in a part of our app that is more proprietary than not.

We were able to prevent the bug from happening by disabling firebug on the machine.  Sorry, this is another weird one, but maybe that piece of information can help?

**Comment by guybedford** [comment]
@atrauzzi sounds like https://github.com/systemjs/systemjs/issues/878 then.

**Comment by atrauzzi** [comment]
Awesome, glad it's already in-hand.  Thanks you :)
