### ISSUE TITLE
jspm - set up ts linting

### ISSUE THREAD

**Issue by troymclure1** [jspm/jspm-cli#2181]
Hi There,

This is not really an issue as such but rather a question. I was not sure if I should ask it here or not? I'm wanting to set-up linting, do I use JSPM for this? If so, where are the docs located for this?

Troy

**Comment by aluanhaddad** [comment]
Great question. Since linting is done at the language level and is dialect/version specific integration should happen as part of source transpilation. Also I don't believe there's a hook for it in the spec. Given these considerations I think it would have to be implemented at the transpiler plugin level.
It would be nice to have eslint, tslint integration among others.

**Comment by troymclure1** [comment]
ah ok. I was interested to know what other people are using for this, what do you use @aluanhaddad ?

**Comment by aluanhaddad** [comment]
I run my linters in my IDE continuously while coding. I've also used a gulp watch task at times. I also run linters explicitly before committing, publishing, etc, depending on the project.
You can use the new `jspm run` command for this too. 

I've pretty much removed gulp and npm entirely from my toolchain. I pretty much just use npm to install jspm for client-side code projects.

I use VS Code as my main IDE and it has a lot of very configurable watch and run hooks.

**Comment by troymclure1** [comment]
oh right. Would you mind sharing the linting set-up with me? Or if you know if a good resource that I can get this from ?

**Comment by aluanhaddad** [comment]
Sure I'll post something but it's really just a matter of having a lint configuration file, and the linters installed. What IDE do you use? That will help me post relevant information.

**Comment by seanrkerr** [comment]
@aluanhaddad thank you, that would be awesome. I'm using webstorm ide.

**Comment by troymclure1** [comment]
I'm using the same as u vs code.

**Comment by aluanhaddad** [comment]
Sorry I've been extremely busy I'll try to post something soon.
