### ISSUE TITLE
JSPM bundle Angular 2 'sourceType: module' error

### ISSUE THREAD

**Issue by SeanSobey** [jspm/jspm-cli#2184]
I am trying to create a JSPM (version 0.16.48) bundle using Angular 2 version 2.2.1.

Using this command:

`jspm bundle @angular/common + @angular/compiler + @angular/core + @angular/forms + @angular/http + @angular/platform-browser + @angular/platform-browser-dynamic + @angular/router + @angular/upgrade`

Results in this error:

`err  SyntaxError: jspm_packages/npm/@angular/core@2.2.1/src/facade/lang.js: 'import' and 'export' may appear only with 'sourceType: module' (23:0)`

**Comment by SeanSobey** [comment]
Turns out Angular2 supports UMD/AMD modules, so JSPM can be set to work like so:

`"overrides": {
  "npm:@angular/common@2.2.1": {
    "format": "amd"
  },
  "npm:@angular/compiler@2.2.1": {
    "format": "amd"
  },
  "npm:@angular/core@2.2.1": {
    "format": "amd"
  },
  "npm:@angular/forms@2.2.1": {
    "format": "amd"
  },
  "npm:@angular/http@2.2.1": {
    "format": "amd"
  },
  "npm:@angular/platform-browser@2.2.1": {
    "format": "amd"
  },
  "npm:@angular/platform-browser-dynamic@2.2.1": {
    "format": "amd"
  },
  "npm:@angular/upgrade@2.2.1": {
    "format": "amd"
  },`

**Comment by aluanhaddad** [comment]
What you want is probably `"format": "esm"`. That will enable you to take advantage of RollUp optimizations.
