### ISSUE TITLE
How to run @angular/compiler-cli with jspm?

### ISSUE THREAD

**Issue by petersalomonsen** [jspm/jspm-cli#2186]
I'm trying to create an AOT compiled build for angular2 using JSPM. This works without problems using npm (by executing node_modules/.bin/ngc).

With JSPM I'm trying to run the aot compiler like this (since the ngc executable is not available):

`jspm run @angular/compiler-cli`

I get the following error:

```
err  (SystemJS) Cannot read property 'readFile' of undefined
        TypeError: Cannot read property 'readFile' of undefined
            at new Tsc (jspm_packages/npm/@angular/tsc-wrapped@0.3.0/src/tsc.                                               js:38:53)

```
Anything I'm doing wrong, or is this not possible at the moment? I've set up the same dependencies in JSPM as for NPM.

**Comment by aluanhaddad** [comment]
Please see https://github.com/frankwallis/plugin-typescript/issues/158

**Comment by petersalomonsen** [comment]
Thanks!
