### ISSUE TITLE
Error after bundling (but no error in dev mode)

### ISSUE THREAD

**Issue by staxmanade** [jspm/jspm-cli#2190]
I'm using a rather large dependency codebase that used to work when bundling, but after a recent upgrade of jspm it is now causing this error. (bear with me - long explanation)

It originally worked with `-beta.16` and after upgrading, the error started showing up but only when I bundle (not when in local/dev mode)

```diff
-    "jspm": "^0.17.0-beta.16"
+    "jspm": "^0.17.0-beta.32"
```

## Setup

First the working version. (These are being executed in a PowerShell prompt on windows - but most of the commands should translate to other shells)

```
mkdir jspmtest
cd .\jspmtest\
npm init
npm install --save-dev jspm@beta
jspm init
```

open editor and add the following file

`index.html`
```
<script src="./jspm_packages/system.js"></script>
<script src="./jspm.config.js"></script>

<script>
    System.import('jspmtest').then(function(){
        console.log("app loaded")
    }, function(err) {
        console.error(err);
    })
</script>
```

then in `src/jspmtest.js` add:
```
console.log("HI");
```

Run the app locally to make sure `HI` is printed to the console.

now: install `npm:winjs`

```
jspm install npm:winjs
```

Modify the `src/jspmtest.js`

```
console.log("HI");
import WinJS from 'winjs';
console.log(WinJS);
```

Run the app - notice how `HI` is printed, as well as an object with lots of stuff on it (`WinJS` library)

So this shows that it works without bundling.

# How to get the error:

Now let's bundle.

```
jspm bundle jspmtset --inject
```

Reload in the browser and I get the following error:

```
(index):8 Error: (SystemJS) require is not defined
	ReferenceError: require is not defined
	    at eval (http://localhost:3030/build.js:25748:31)
	    at load (http://localhost:3030/build.js:110:40)
	    at eval (http://localhost:3030/build.js:97:44)
```

# Other thoughts/digging

So it seems that the bundle process is renaming the `require` variable as originally defined in this source: https://github.com/winjs/winjs/blob/master/src/js/amd.js#L3 to `var $__require;` but in another file that expects the `require` function to be defined in it's scope (and called `require`) here: https://github.com/winjs/winjs/blob/master/src/js/base.js#L25 is not being renamed to `$__require`.

I also am afraid that `require(...` may be used elsewhere but due to the size of the WinJS codebase it's tough to tell how to go about fixing this.

Any thoughts?

Thanks,

**Comment by guybedford** [comment]
Thanks, this sounds like a bug in the upgraded CJS transformer of SystemJS builder. //cc @jrauschenbusch @asapach.

**Comment by asapach** [comment]
Interesting, they are implementing their own micro AMD loader and re-declaring `require` and `define`. It's detected as CJS and `require` is renamed to `$__require` everywhere except this one particular spot:
```js
  _WinJS.Namespace.define("WinJS.Utilities", {
    _require: require,
    _define: define
  });
```
(Somewhere at the very end of [base.js](https://unpkg.com/winjs@4.4.0/js/base.js))
@jrauschenbusch, maybe some weird scope issue?

@staxmanade, you can try overriding it as AMD to work around this.

**Comment by asapach** [comment]
@guybedford, this appears to be fixed in [babel-plugin-transform-cjs-system-wrapper@v0.3.0](https://github.com/systemjs/babel-plugin-transform-cjs-system-wrapper/releases/tag/v0.3.0). Need to bump the version in systemjs-builder.

**Comment by staxmanade** [comment]
@asapach I do have a work-around (hack) for now. It's not fun, but works... Each time I jspm install or unbundle or anything jspm-ey I have to re-run my hack script :(

```
sed -i '' -e 's/_require: require,/_require: typeof \$__require === "undefined" \? require : \$__require,/g' jspm_packages/npm/winjs-self-built@4.4.2/js/base.js
```

Replacing:

```diff
-_require: require,
+_require: typeof $__require === "undefined" ? require : $__require,
```

**Comment by jrauschenbusch** [comment]
@guybedford @asapach Yes, this issue was fixed in https://github.com/systemjs/babel-plugin-transform-cjs-system-wrapper/releases/tag/v0.3.0. The release is ready to be integrated in systemjs-builder. I just have forgotten to update the binary in the repo. But this should not be a show stopper. It is available in npm.

Note: The new release has removed the dependency to babel-plugin-transform-cjs-system-require since it's obsolete.
