### ISSUE TITLE
Importing commonJS module fails

### ISSUE THREAD

**Issue by josiahhaswell** [jspm/jspm-cli#2191]
I'm trying to import [mxGraph](https://github.com/jgraph/mxgraph-js), but every import results in either an empty object, or an undefined variable.

**Steps to Reproduce**
-  Install mxGraph: `jspm install mxgraph=github:jgraph/mxgraph-js`
-  Import mxGraph symbol: `import {mxGraph} from 'mxgraph'`

**Expected result:**
`mxGraph` is defined and a constructor

**Actual result**

`mxGraph`` is an empty object (`Object{}`)

**Version**
0.16.48

**Comment by aluanhaddad** [comment]
It does not export anything, it is actually a global, but the package json points to a main file. You can install it with
`jspm install mxgraph=github:jgraph/mxgraph-js -o "{ format: 'global', exports: 'myGraph' }"`

Just to comment, that package adds hundreds of things to `window`, which is just terrible.
