### ISSUE TITLE
build files separately

### ISSUE THREAD

**Issue by pavel06081991** [jspm/jspm-cli#2195]
For example I have the next files structure:
```
src/
	main.js
	someModule1/
		someModule1.js
		someModule1.css
		someModule1.png
	someModule2/
		someModule2.js
		someModule2.css
		someModule2.png
```

Is it possible to build src files to get separate files instead of one bundle file? To get the next files structure:

```
dist/
	main.js
	someModule1/
		someModule1.js
		someModule1.css
		someModule1.png
	someModule2/
		someModule2.js
		someModule2.css
		someModule2.png
```

I want all my files to be loaded separately as if I do not use build but I also want my files to be processed? For example postCSS files to become minified css files; javascript files(es6) to become minified es5 files. In other words I'd like to use
http 2.0 and load all my files separately and want all my files to be processed before downloading them in browser.

And thank you for your project. I hate webpack though it is popular. I think and hope jspm and systemjs will be the future of web development.

**Comment by joeldenning** [comment]
@pavel06081991 I do not think that you can do what you're looking for with a jspm command, but you should be able to do it with systemjs/builder. If you call [trace("src/main.js")](https://github.com/systemjs/builder/blob/master/docs/api.md#buildertraceexpression) and then [bundle(tree)](https://github.com/systemjs/builder/blob/master/docs/api.md#builderbundletree-outfile-options), you then could write out each module in the resulting bundle to a resulting file.

Let me know if that doesn't work for you -- this is something I've seen done in the past but could be misremembering how it was pulled off.
