### ISSUE TITLE
jspm link relative path on a Windows environment

### ISSUE THREAD

**Issue by Rubenisme** [jspm/jspm-cli#2198]
[link.zip](https://github.com/jspm/jspm-cli/files/652242/link.zip)

On Windows, the link command fails. For the package.json because it's being linked with a relative path.
After linking it will fail on parsing this linked package.json and generate an empty .json file in the jspm_packages folder.
We solved this by removing the path.relative on line 136. We don't know what impact this change has on non-Windows systems.

**Comment by aluanhaddad** [comment]
@Rubenisme Thanks for raising this issue. Would mind creating a pull request with your changes?

**Comment by AlbertWillemsen-Centric** [comment]
Haven't tested the impact on non-windows systems yet.
Maybe there is a difference between the relative symlink behaviour.

**Comment by aluanhaddad** [comment]
@AlbertWillemsen-Centric Indeed, it must be tested first. I am currently running on a Windows machine but I will fire up a VM and test this later.

**Comment by guybedford** [comment]
Thanks, the fix looks good to me!

**Comment by AlbertWillemsen-Centric** [comment]
This breaks again, not backported to jspm ~0.16.49.
As i cannot use System 0.20 as of yet,
