### ISSUE TITLE
JSPM .17 Custom Conditional Loading

### ISSUE THREAD

**Issue by peteringram0** [jspm/jspm-cli#2199]
Hey,

Is there any way to create custom variables to load in different modules other then the --production and -dev flags? I am creating an app with three different providers and want to bundle different modules based on the build. 

Thanks,

**Comment by joeldenning** [comment]
Have you tried out [conditional substitution](http://jspm.io/0.17-beta-guide/conditional-substitution.html)? It uses the `#{}` syntax inside of the import string to conditionally load a different file based on any arbitrary logic.

**Comment by aluanhaddad** [comment]
Yeah conditional substitution is awesome. FYI if you are using TypeScript you can still make the conditional substitution typecheck by using the new `rootDirs` feature in TypeScript 2.0 which would look like this in the example linked by @joeldenning 
```ts
{
  "compilerOptions": {
    "rootDirs": [
      "src/en",     
      "src/de",
      "src/es",
      "src/zh",
      "src/#{lang}"
    ]
  }
}
```
