### ISSUE TITLE
jspm error downloading loader files

### ISSUE THREAD

**Issue by markti** [jspm/jspm-cli#2203]
I think I may have corrupted my jspm installation. I was getting timeouts on lookups and downloads so it advised me to increase the timeout duration. So I did and then CTRL-C the install. Now when running install I am getting errors locating "GitHub:floatdrop/plugin-jsx". 

![image](https://cloud.githubusercontent.com/assets/3155241/21431856/03e59f8a-c837-11e6-8f29-e3bfd20e8593.png)

I made these commands to update the timeout durations. I'm pretty sure updating the GitHub timeout to NaN is a bad idea.

![image](https://cloud.githubusercontent.com/assets/3155241/21431892/26a4aa48-c837-11e6-93f9-19b882f73f37.png)

I'm frustrated, I don't know how to clean up the installation.

**Comment by aluanhaddad** [comment]
On Windows, you can find the configuration in `%userprofile%/AppData/Local/.jspm/config`.

**Comment by poonam212** [comment]
i cannot initialize the jspm  when i user jspm it shows can1t download loader files error. tell me how can i fix this??
