### ISSUE TITLE
bundle-sfx failed but exit with code 0

### ISSUE THREAD

**Issue by GongT** [jspm/jspm-cli#2205]
I'm running bundle command during a build process, but I forget to upload jspm.js to my git repo, so this file is missing.    
but jspm show an error then exit normally.

```
[root@localhost package]# jspm bundle-sfx dist/global.js dist/bundle.js --format global

err  No project configuration file not found. Looking for: /data/web/package/jspm.js
[root@localhost package]# echo $?
0
```

package.json:
```
{
  // ....
  "jspm": {
    "configFile": "jspm.js",
    // ....
  }
}
```

**Comment by guybedford** [comment]
This sounds like a bug in just not returning the error code as the exit code. A PR is welcome to fix this.
