### ISSUE TITLE
Precompile es6/typescript and use AMD

### ISSUE THREAD

**Issue by solo474** [jspm/jspm-cli#2208]
Hi I'm now to JSPM and systemjs I'm building a PWA application. I want to asyncronously load all my app components but I  don't want to transpile anything in the browser. I want to pretranspile them. Is there any way to do that in JSPM.  Or is there any concupet of code spliting like wbepack 2 providing ?

**Comment by aluanhaddad** [comment]
Greetings.

If you are using jspm 0.17.0-beta, which you can install with `npm install jspm@beta --save-dev`, you can use development bundling. This enables a bundling based development workflow where files are transpiled, cached, and watched before hitting the browser.

Assuming your local package is called app, you can run `jspm bundle app -wid` to get started.

You can read more about this in the 0.17 beta guide at http://jspm.io/0.17-beta-guide/development-bundling.html

With respect to code splitting, what scenario do you have in mind?

**Comment by sagar12861** [comment]
Hi @aluanhaddad Thaks for replay.
I need to split the code for creating Progressive Web App ( PWA ). I want to lazily load all js and css.
react components and angular components and router modules should load lazy. And transpilation stage should not be in browser.

**Comment by aluanhaddad** [comment]
If you use `jspm bundle app -wid` transpilation will occur in a NodeJS process, not in the browser. The same transpiler pipeline is used regardless of wether you are bundling for transpiling in browser for development, transpiling to an auto-updating bundle for development, or bundling for production. I thought your question pertained to a development workflow. When you ship your app it is customary to pre-transpile it, but during development you are free to do as you wish. This will not affect the structure of your application as deployed.
