### ISSUE TITLE
'Uncaught ReferenceError: require is not defined' with npm modules

### ISSUE THREAD

**Issue by jackfranklin** [jspm/jspm-cli#221]
Hey,

Really enjoying using jspm and loading in modules from GitHub is working really nicely with ES6 too :)

However, using jspm  **V0.8.2** I am unable to successfully import any code from an npm module. I've tried it with jQuery and Lodash so far.

index.html file looks like this:

``` html
<!DOCTYPE html>
<html>
  <head>
    <script src="jspm_packages/system.js"></script>
    <script src="config.js"></script>
    <script>
      System.import('./app').catch(console.error.bind(console));
    </script>
  </head>
  <body>
  </body>
</html>
```

And `app.js` like so:

``` js
import _ from 'npm:lodash';

console.log(_);
```

`config.js` is:

``` js
System.config({
  "paths": {
    "*": "*.js",
    "github:*": "jspm_packages/github/*.js",
    "npm:*": "jspm_packages/npm/*.js"
  }
});

System.config({
  "map": {
    "github:components/jquery": "github:components/jquery@^2.1.1",
    "npm:jquery": "npm:jquery@^2.1.1",
    "npm:lodash": "npm:lodash@^2.4.1",
    "npm:jquery@2.1.1": {},
    "npm:lodash@2.4.1": {}
  }
});

System.config({
  "versions": {
    "github:components/jquery": "2.1.1",
    "github:jspm/nodelibs": "0.0.5",
    "npm:jquery": "2.1.1",
    "npm:lodash": "2.4.1"
  }
});
```

Within `lib/` I have traceur, es6-module-loader, system.js **V0.9.3** and everything is loaded fine. When I then run a server and go to localhost:3000, I get the following error in the console:

```
Uncaught ReferenceError: require is not defined lodash.src.js:2461
Error evaluating http://localhost:3000/jspm_packages/npm/lodash@2.4.1/dist/lodash.js es6-module-loader.src.js:1141
```

I feel like I am missing something really obvious here - but I did also run this by @oliverjash who couldn't spot anything immediately obvious.

Thanks,

Jack.

**Comment by VirenPatil21** [comment]
@guybedford when publishing angular2 project is it necessary to include node_module folder, because i'm getting same error "Uncaught ReferenceError: require is not defined".
