### ISSUE TITLE
In build mode, umd modules having external react fail, but works in dev

### ISSUE THREAD

**Issue by jide** [jspm/jspm-cli#2210]
Hello,

I have a project set up using JSPM 1.7. It imports several custom modules that have been built using webpack with external react as umd : 
```js
module.exports = {
  ...
  output: {
    ...
    libraryTarget: 'umd',
    library: 'react-video',
    umdNamedDefine: 'react-video'
  },
  ...
  externals: {
    react: 'umd react',
    'react-dom': 'umd react-dom'
  }
};
```

jspm.config.js looks like this : 

```js
SystemJS.config({
  packageConfigPaths: [
    'npm:@*/*.json',
    'npm:*.json',
    'github:*/*.json'
  ],
  map: {
    ...
    'react': 'npm:react@15.4.1',
    'react-dom': 'npm:react-dom@15.4.1',
    'react-video': 'github:Synchronized-TV/react-video@master',
    ...
  },
  ...
```

When running in dev (I use jspm-server), the modules are correctly exported and react is resolved.

When using the `build` command though, it does not work. Without any change to jspm.config.js, I get this error on build : 
```
Error: Multiple anonymous defines.
```

I edited jspm.config.js, and after that builds succeeds (but in dev this does not work) : 

```js
SystemJS.config({
  ...
  packages: {
    'github:Synchronized-TV/react-video@master': {
      'format': 'global'
    },
    ...
```
But when running the code, the react module required inside the webpack module is not found : 
```
TypeError: Cannot read property 'PureComponent' of undefined
```

I tweaked jspm.config.js again like this : 
```js
SystemJS.config({
  ...
  packages: {
    'github:Synchronized-TV/react-video@master': {
      'format': 'global',
      map: {
        'react': 'npm:react@15.4.1',
        'react-dom': 'npm:react-dom@15.4.1'
      }
    },
    ...
```
...but I get the same error : 

<img width="612" alt="capture d ecran 2017-01-11 a 18 37 57" src="https://cloud.githubusercontent.com/assets/333073/21859506/21e6ff00-d82d-11e6-8a8e-822241933e08.png">

Which is where react is passed to the webpack module : 

<img width="219" alt="capture d ecran 2017-01-11 a 18 40 13" src="https://cloud.githubusercontent.com/assets/333073/21859580/6e6689a4-d82d-11e6-839a-e83f4d62f86a.png">

Is there something I did wrong ?

**Comment by guybedford** [comment]
This may be related to https://github.com/facebook/react/issues/8392. Perhaps try that latest version of React and see if that fixes things?

**Comment by jide** [comment]
Hmmmm unfortunately it did not work... For my own use case I decided to go back to pure webpack, with some tweaking to be able to remote load the module.
