### ISSUE TITLE
 (SystemJS) define is not a function.

### ISSUE THREAD

**Issue by sergueyarellano** [jspm/jspm-cli#2212]
Hi, having fun with jspm and systemJS. Thanks a lot!

I have found a module that looks like:

```javascript
// module1.js
define( myPath + 'some/path', 
['dep'], function(dep) {
  // ...
} )
```
`myPath = 'src/'` it is loaded before, globally.

```javascript
// module2.js
import './module1'
```

It returns  **Error: (SystemJS) define is not a function**

In the other hand, when rewriting module1:
```javascript
// module1.js
define( 'some/path', 
['dep'], function(dep) {
  console.log(myPath) // -> src/
  // ...
} )
```
module1 loads perfect.

The problem is that I can't rewrite module1 (for now) (It's used in other project with requireJS). Is there a workaround here?

Thanks!

**Comment by guybedford** [comment]
This case will not be detected by SystemJS as an AMD module.

Try adding meta configuration to SystemJS to inform it that this is an AMD module:

```javascript
System.config({
  meta: {
    'path/to/module1.js': { format: 'amd' }
  }
});
```

**Comment by sergueyarellano** [comment]
Thanks a lot, that worked!
