### ISSUE TITLE
process/process.js is Global Dependency

### ISSUE THREAD

**Issue by DaSchTour** [jspm/jspm-cli#2213]
It looks like JSPM 0.17 somehow messes build SfxBundles. From somewhere some jspm-nodelibs where added. But I can't tell why they were added, I didn't do it. So my peerDependencies include these.
```
"assert": "npm:jspm-nodelibs-assert@^0.2.0",
"process": "npm:jspm-nodelibs-process@^0.2.0",
"url": "npm:jspm-nodelibs-url@^0.2.0"
```

When trying to create a SFX i get the following error
`TypeError: Global SFX bundle dependency "process/process.js" must be configured to an environment global via the globalDeps option.`

By using grunt-jspm I somehow omitted this error. But the bundle contained a global dependency to "process/process.js". The curios thing about this is, that the global dependency I defined wasn't recognized. I have "jquery": "$" as global dependency but it was also bundled into.

The strange thing is, that I have another bundle with nearly the same dependency and it doesn't have assert, process and url as peers. And they also are not added on `jspm update` while the other bundle adds them after every `jspm update`.

Oh, and maybe this is important. Loading with SystemJS and so on works fine, only bundling doesn't work.

**Comment by guybedford** [comment]
Is there anyway you can share an example workflow here that reproduces this problem?

**Comment by DaSchTour** [comment]
jspm-nodelibs are deprecated since 0.10? So why is my JSPM trying to use this old deprecated packages?

**Comment by guybedford** [comment]
These are not deprecated, and are the current versions of the nodelibs packages.

**Comment by DaSchTour** [comment]
But I still don't get why the hell this packages are installed. I don't need them, I don't want them and I don't see any of my dependencies requiring them. They are just added to break bundling 😡

**Comment by DaSchTour** [comment]
Well. Back to 0.16 and removing text plugin everything works fine. Looks like 0.17 tries to do things it shouldn't or doesn't do them correctly and transparent to the user.

**Comment by DaSchTour** [comment]
Okay, well after some month of development without any productive deployment I'm on another project with exactly the same problem. The project setup is very big, so I need some advice to create an example workflow without adding all the stuff that doesn't belong to this problem. My main questions are as mentioned above.

# Where is process/process.js defined as a global global dependency that will never ever be bundled?
# Under which circumstances is this package added?
# My generated config reveals, that `process` is needed by `timers-browserify` which is needed by `jspm-nodelibs-timers` which is included as module called `timers` which is not included by any of the modules I load.
# So what triggers dependency of `timers`? Removing all the `jspm-nodelibs` from my package.json doesn't do anything, they are all added again, but I don't now why and don't see any dependency to them.
# How can I inspect dependency to `jspm-nodelibs`?
# Why is adding an override for `timers-browserify` and setting `process` to `@empty` like for lodash doesn't have any effect?

**Comment by DaSchTour** [comment]
May it be, that this isn't interpreted correctly by JSPM?
```
"npm:reflect-metadata@0.1.10": {
        "jspmNodeConversion": false,
        "map": {
          "crypto": {
            "node": "@node/crypto",
            "default": "@empty"
          }
        }
      }
```

And so `crypto` is added although not intended to?
