### ISSUE TITLE
need support @latest version of package

### ISSUE THREAD

**Issue by GongT** [jspm/jspm-cli#2214]
I have a auto build system, which auto create new package version and put in my private npm registry

is there any way to use latest package version instead of a specified one.

or any command to *upgrade* one package to latest version.

**Comment by aluanhaddad** [comment]
`jspm install registry:package@latest` works for npm packages. It should be sufficient to simply run that command but I am not particularly familiar with private npm registries.

**Comment by GongT** [comment]
not work for me :(

>[root@localhost mAccount]# jspm i npm:XXXXXXXXXXXXXXXXXXXX@latest
>     Looking up npm:XXXXXXXXXXXXXXXXXXXX
>
>err  No version match found for npm:XXXXXXXXXXXXXXXXXXXX@latest
>
>warn Installation changes not saved.

>[root@localhost mAccount]# npm show XXXXXXXXXXXXXXXXXXXX dist-tags
{ latest: '2.1.0-1' }

>[root@localhost mAccount]# jspm -v
0.17.0-beta.32
Running against global jspm install.
