### ISSUE TITLE
jspm link ../

### ISSUE THREAD

**Issue by alexisvincent** [jspm/jspm-cli#2216]
@guybedford When writing libraries that are going to be installed by JSPM, we often might have a file tree something like this:

```
|- package.json
|- lib
|    |- index.js
|
|- test
     |- package.json
     |- index.js
     |- index.html
```

Now, from inside `test` I want to be able to `jspm link ..`, but this puts `jspm` into a recursive loop where it eternally processes dependencies. 

Any chance you can detect this symlink and stop processing deps?

**Comment by alexisvincent** [comment]
Or do you perhaps have a different solution

**Comment by guybedford** [comment]
@alexisvincent `jspm link ../` definitely works for me. Do you have a replication of the looping install behaviour?

**Comment by alexisvincent** [comment]
Sure, 

```
git clone https://github.com/alexisvincent/systemjs-tools
cd test/public
jspm link ../../
```

**Comment by guybedford** [comment]
@alexisvincent did you try a blank project example first here to ensure it's not something specific to your project? It helps if you make some effort to reduce the replication first for issue reporting.

**Comment by alexisvincent** [comment]
I'm positive its not specific to my project since I have the same behavior everywhere. But I can make a clean repo for you. 

As far as I can see, the issue occurs when test is not part of the npm ignore.

**Comment by guybedford** [comment]
@alexisvincent perhaps you just need to make the `test/jspm_packages` gitignored? Or make sure its linking as an esm / non-npm package? Remember that npm packages when installed have all their files processed for commonjs dependencies which may be the recursive part?

**Comment by alexisvincent** [comment]
Reproducible case here: https://github.com/alexisvincent/tests/tree/master/jspm/linking
