### ISSUE TITLE
No PLATFORM.Loader error (bundling an aurelia app)

### ISSUE THREAD

**Issue by Baudin999** [jspm/jspm-cli#2218]
HI,

I am trying to deploy an application written with jspm and aurelia. After bundling my application I get the following error when running the application:

```No PLATFORM.Loader is defined and there is neither a System API (ES6) or a Require API (AMD) globally available to load your app.```

I've also asked this question on [StackOverflow](http://stackoverflow.com/q/41815624/1654375).

The example application where I reproduce the problem is: [jspm-bundling-test](https://github.com/Baudin999/)

> You can run the dev environment by running ```npm run setup:dev``` and ```npm run dev```

> You can run the production setup by running: ```npm run setup:prod``` and starting the server. Easiest way of starting the server would be running ```node ./src/server/server.js``` and navigating to ```http://localhost:2345```  

I don't know if this is the right place to ask this question/report this issue; so I hope I'm not offending anyone. If there is anything I can do to help solve the issue I'd be happy to help.

**Comment by Baudin999** [comment]
I've found out that the error is because I import the aurelia-bootstrapper. As soon as I add: ```import * as bootstrapper from 'aurelia-bootstrapper'```; I get the error

**Comment by davismj** [comment]
@guybedford can be closed i think

**Comment by Baudin999** [comment]
Yes, can be closed. I don't know if this is still an issue, but I changed my project.
