### ISSUE TITLE
[0.17.0-beta.33] plugin-text@0.0.9 has problem

### ISSUE THREAD

**Issue by fernandogmar** [jspm/jspm-cli#2220]
Hi there,

after:
`jspm install text`

I have just tryed to do:
`import footer from './footer.html!text';`

And I got an error on the console of the browser:
`common.js:83 Uncaught (in promise) Error: n.concat is not a function(…)`

**Comment by guybedford** [comment]
This bug was just fixed today, try updating the the beta.44 release.

**Comment by fernandogmar** [comment]
Thanks Guy,

I was doing that just in case and it worked! 

Congrats! awesome work. I take my hat off ;)
