### ISSUE TITLE
Not able import the jspm.config.js anymore

### ISSUE THREAD

**Issue by Karolusrex** [jspm/jspm-cli#2222]
Befor beta 35, I could import jspm.config.js from Node, but now I get an error that SystemJS is not defined. The purpose of this is to have a script that can read the settings in the systemjs config to execute some action on build/setup. 

I tried defining SystemJS as global but it seems like the api for accessing the config has changed, System.config({}) doesn't return the config nor is there any way to get it since the config is hidden behind a Symbol.

I hope I made my issue clear. I'd like to access the settings set from jspm.config.js but since last update that doesn't work in the same way anymore. Appreciate some help!

**Comment by Karolusrex** [comment]
I discovered the SystemJS.getConfig(), but that doesn't return the config that was passed. Maybe a bug on SystemJS?

**Comment by guybedford** [comment]
@Karolusrex yes the globals are no longer defined in NodeJS. Also `System.getConfig` returns the normalized configuration, not the original configuration provided.

If you're looking to get the config value from a file, an easy way is to write your own `System` global that can simply return the `config` call object.
