### ISSUE TITLE
jspm can't get loader files

### ISSUE THREAD

**Issue by arcticranger** [jspm/jspm-cli#2224]
i am on an EC2 linux box with jspm@0.16.51 installed.  Tried this with jspm@0.16.15 but got the same results.  i am running as root.

[root@ip-172-31-41-152 client]# jspm -v
0.16.51
Running against global jspm install.
[root@ip-172-31-41-152 client]# jspm init
warn Running jspm globally, it is advisable to locally install jspm via npm install jspm --save-dev.
ok   Verified package.json at package.json
     Verified config file at config.js

warn babel@5.8.3 is unsupported for this version of jspm. Use jspm dl-loader --latest to update.
warn babel-runtime@5.8.3 is unsupported for this version of jspm. Use jspm dl-loader --latest to update.
warn core-js@0.9.18 is unsupported for this version of jspm. Use jspm dl-loader --latest to update.
     Looking up loader files...
warn Error on download for github:systemjs/systemjs
     Bad response code 404
err

err  Error downloading loader files.

**Comment by cleardot** [comment]
update, now getting 404s on individual packages, seems random, maybe this is a clue to loader files problem?

err  Error downloading github:aurelia/http-client

**Comment by guybedford** [comment]
It sounds like the GitHub configuration isn't working here. Perhaps try `jspm registry config github` to update the credentials?

**Comment by arcticranger** [comment]
yes i was using a token without the proper public repo setting, fixed that and good to go, thx,

**Comment by poonam212** [comment]
I am installing jspm for my project i had successfully installed jspm but when i try to  initialize jspm then it gives me error to download loader files here is the screenshot 
![error](https://user-images.githubusercontent.com/37362386/40405281-9defd224-5e79-11e8-9ef1-9b946d4f7d99.PNG)
