### ISSUE TITLE
Missing system-polyfills.js

### ISSUE THREAD

**Issue by peteringram0** [jspm/jspm-cli#2227]
There used to be a system-polyfills.js within the jspm_packages dir however there is no longer. How to get this file back please?

**Comment by guybedford** [comment]
This was only available in jspm 0.16, and should still be available in jspm 0.16 installs.

jspm 0.17 no longer provides this file as it only contains a Promise polypill which is no longer necessary.

**Comment by peteringram0** [comment]
I seem to still need it in my project for tests:

````javascript
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  ReferenceError: Can't find variable: Promise
  at /src/jspm_packages/system.src.js:216
````

**Comment by guybedford** [comment]
Which version of jspm are you using here?

**Comment by peteringram0** [comment]
On one laptop it works fine running version: 0.17.0-beta.29 <0.18.0

On the second laptop it missing that file and cant run promises running version: 0.17.0-beta.35

Thanks

**Comment by guybedford** [comment]
Yeah the polyfills file isn't provided by jspm 0.17, only jspm 0.16. Include a custom promise polyfill in the page if you need it (`jspm install npm:es6-promise` for example).

**Comment by peteringram0** [comment]
I already have this in my project, has the way you load in some modules changed in the later versions? 

Im importing it like so 

````javascript
import 'es6-promise/auto';
````

**Comment by peteringram0** [comment]
Im guessing PhantomJS loads in system.src.js first before it runs my app and the promise is needed at this point. Does anyone know how to add this in? Thanks

**Comment by nelisbijl** [comment]
Removing the polyfill was a bad idea !!

You need a polyfill to be able to load system.js in some browsers (eg IE11)
You can not load this with system.js (as it can not yet be loaded)

installing the needed polyfill with jspm is also a bad idea as you need to specify the version specific path in your script tag.
You did not have that problem when the polyfill was located in jspm_packages.

Having to add a node_modules folder in your webroot just to hold your polyfills is a very bad idea.

Please reconsider the removal of the polyfills

**Comment by peteringram0** [comment]
+1 i agree with @nelisbijl . Still having problems on the latest beta version of JSPM and Phantom due to this. It should be easy to get this working not hard.

**Comment by amenadiel** [comment]
I'm including Bluebird.js since forever, because is faster than native ES6 promises, so no matter what browser are you using, and its support for promises, bluebird is still better.

Just include

```html
        <script src="https://cdn.jsdelivr.net/bluebird/3.4.3/bluebird.min.js"></script>
```
before loading `system.js`

**Comment by peteringram0** [comment]
@amenadiel Have you managed to get this working with testing? Im using this package https://github.com/Workiva/karma-jspm

Thanks

**Comment by amenadiel** [comment]
I'm using the same and no, I haven't been able to make it work with SystemJS 20+. With the polyfills gone (they were present in SystemJS 0.19+) Phantom cannot load system.src.js.

In automated testing, particularly in karma-jspm, Phantom errors because it doesn't support promises (at its current version, 2.1) and there's no way to inject a custom promise polyfill before system.src.js is called (because of karma-jspm logic), which leads to SystemJS global not being declared, with leads to fail the tests.

**Comment by amenadiel** [comment]
@guybedford would you tell us what polyfills did system.polyfills.js had? I've tried to figure it out from the file as it was in SystemJS 0.19+, but I don't know exactly what's the purpose of each part.

I want to build a karma plugin to load PhantomJS polyfills like Object.assign and Function.prototype.bind, now I know I also need a promise polyfill (I guess lie.js or when.js are the smallest ones around), but I need to know if there are other polyfills I should consider to allow PhantomJS to run with SystemJS 0.20+

**Comment by ValeryIvanov** [comment]
I am also trying to upgrade to 0.17 and using karma-jspm with phantomjs and same error occures.

**Comment by ValeryIvanov** [comment]
@guybedford Could you please comment on how to proceed with this issue?

**Comment by guybedford** [comment]
system-polyfills.js can be replaced with any promises polyfill. Ideally just https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.5.0/bluebird.core.min.js.

**Comment by amenadiel** [comment]
@dwilson6 I just saw it. You rock.

**Comment by amenadiel** [comment]
@ValeryIvanov @peteringram0 the PR was merged and released. `karma-jspm` has a new config option `beforeFiles` that allows to load any polyfills you need before loading `system.js`.
