### ISSUE TITLE
Unable to import github repository package

### ISSUE THREAD

**Issue by atrauzzi** [jspm/jspm-cli#2228]
I'm using the typescript plugin and have a package that's hosted on github, pointed to in `package.json` as follows:

```
"company/builder": "github:company/builder@master",
```

The `package.json` in the project has universal modules available and pointed to as follows:

```
  "main": "./lib/index.js",
  "types": "./lib/index.d.ts",
```

Although the typescript itself is also available in the `src/` directory.

I'm having difficulties referencing this package from my JSPM project either implicitly through a regular package import (`import {Something} from "company/builder";`), or directly by pathing all the way to the `.tsx` files.

When I do the regular import, dumping the value I wanted to bring in comes back as `undefined`.  If I try to do the direct pathing, JSPM ends up trying to import a `.tsx.js` file.

I've done everything I need to ensure the package abides by NPM package conventions, but something still seems to be getting in the way.

**Comment by atrauzzi** [comment]
Also tried everything that might make sense in the `overrides` section in `package.json`:

```
    "overrides": {
      "github:company/builder@master": {
        "registry": "npm",
        "main": "index.js",
        "directories": {
          "lib": "lib"
        },
        "format": "esm"
      },
```

**Comment by guybedford** [comment]
Let me know if this is fixed in the latest patch version, otherwise if you can share an exact (and reduced) replication that would help a lot.
