### ISSUE TITLE
Equivalent of `npm ls` for JSPM-cli ?

### ISSUE THREAD

**Issue by GBarthos** [jspm/jspm-cli#2231]
Hi !

I was wondering if JSPM-cli expose a way to do the equivalent of `npm ls name[@version]`.  
The  goal is to show a list of all the versions installed for a package, and a list of every places in the dependency tree where the package is used, for every version.  

I often found that when I want to do `jspm resolve --only registry:name@version`, I don't actually know every places each version of a package is used.  

The only thing I found was which dependency it affected afterwards.

**Comment by guybedford** [comment]
There is `jspm inspect` and `jspm inspect registry:name` which are designed to help here.

**Comment by GBarthos** [comment]
Thanks for your quick response @guybedford !

Right but when I `jspm inspect registry:name` on the forks shown by `jspm inspect --forks`, then there are 2 problems:

1- some package returns a warning: `Package npm:js-tokens not found.` (for example)
2- other package shows only one fork:

```
Installed versions of npm:core-js

            core-js 2.4.1 (^2.4.1)
```
(here in this case a got this fork: `npm:core-js 1.2.7 2.4.1`)  

In any case, I can not know if a given package is just a dependency of another one, and if so which one.

I agree that `jspm inspect` provide some useful information, but I was wondering if it would be possible to indicate from which package a given package is a dependency, ala `npm ls`

**Comment by guybedford** [comment]
@GBarthos the `not found` message for `jspm inspect registry:name` is actually a bug - the output here is supposed to show which parents the package is installed by.

I've marked this as a bug, and I'm sure the fix should be relatively straight forward actually.
