### ISSUE TITLE
JSPM 0.17.0 not matching SystemJS version with its notes

### ISSUE THREAD

**Issue by JulianIsrael** [jspm/jspm-cli#2233]
jspm 0.17.0-beta.32 notes says that it is using "SystemJS 0.19.41", but actually all the jspm from version 0.17.0-X are now using "SystemJS v0.20.4 Dev"

![image](https://cloud.githubusercontent.com/assets/4955274/22491176/12b11310-e7f8-11e6-8afd-edcd1799b665.png)

**Comment by guybedford** [comment]
The version of SystemJS is exactly locked to the version of jspm.

Try running `jspm dl-loader` to check if this isn't working for you.

**Comment by JulianIsrael** [comment]
yes you are right, its good. it turns that package.json "^jspm 0.17.0-beta.32" will ignore the beta.32 and install the latest.

**Comment by JulianIsrael** [comment]
this issue can be closed, it is working as expected.
