### ISSUE TITLE
jspm 0.16 and 0.17

### ISSUE THREAD

**Issue by lipedeitos** [jspm/jspm-cli#2234]
Hi, i'm having two problems here, i was using **jspm 0.17@beta**** and my bundling action with react, was perfect, all react proptypes warnings are showing, until i tried do "jspm install npm:ag-grid-react"... 
If fails everytime _"FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory"_, already try to "-o ignore" nothing seems to help.

If i try to move to **jspm 0.16** "jspm install npm:ag-grid-react" works perfectly... but bundling makes the proptypes warnings not to show anymore.

I guess those are known issues but i really tried a lot of stuffs and nothing seems to work with me...
(Sorry about my english)
Cheers!

**Comment by guybedford** [comment]
The jspm node conversion process seems to be hanging on some kind of Traceur parsing recursion. I'm not sure how that might be happening.

You can try something like the following in 0.17 to disable this conversion:

```
jspm install npm:ag-grid-react -o jspmNodeConversion=false peerDependencies[ag-grid-react]=^7.2.0
```

**Comment by lipedeitos** [comment]
Hi @guybedford, sorry for taking too long to reply this...
Using `jspm install npm:ag-grid -o jspmNodeConversion=false` **WORK**

So thats one problem solved, but now i got another one...
I made a lot of packages of my components, im my grid component package.json i'v got:
```
"dependencies": {
    "ag-grid": "^8.1.1",
    "ag-grid-enterprise": "^8.1.1",
    "ag-grid-react": "^8.1.0",
    "classnames": "^2.2.5",
    "keycode": "^2.1.8",
    "lodash": "^4.17.4",
    "react": "^15.4.2",
    "shortid": "^2.2.8"
  }
```
So in my development environment i need to use a link to my components for test purposes... 
Using `jspm link MyGrid` it gives me the same error "FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory".

I'll try to use the same `-o  jspmNodeConversion=false`, if it works i'll reply again.
Cheers.

**Comment by lipedeitos** [comment]
`jspm link MyGrid -o jspmNodeConversion=false` Didn't work, same error unfortunately. Any other sugestion?
