### ISSUE TITLE
sourcemaps off by one due to `/* */` added at top of file

### ISSUE THREAD

**Issue by AdamWillden** [jspm/jspm-cli#2235]
Comment added to file on download is throwing off sourcemaps

File downloaded by NPM
```js
define(["require", "exports", "tslib", "aurelia-dependency-injection", "./tag-snapshot-manager"], function (require, exports, tslib_1, aurelia_dependency_injection_1, tag_snapshot_manager_1) {
    "use strict";
```

File downloaded by JSPM
```js
/* */ 
define(["require", "exports", "tslib", "aurelia-dependency-injection", "./tag-snapshot-manager"], function (require, exports, tslib_1, aurelia_dependency_injection_1, tag_snapshot_manager_1) {
    "use strict";
```

Why is this comment added and how can I stop it?

**Comment by AdamWillden** [comment]
FWIW

```
jspm -v
0.16.52
Running against local jspm install.
```

**Comment by AdamWillden** [comment]
Found this but not made sense of it yet: https://github.com/jspm/jspm-cli/blob/5963d0e7929d5d277f670af64f03ed75743ecc9d/lib/build.js#L548

**Comment by AdamWillden** [comment]
I can see for SystemJS 0.20 that the wrap does not cause a new line:
https://github.com/systemjs/systemjs/blob/96f9ec1edf9507491b981044f68d30672f199fb8/src/evaluate.js#L32

I'm yet to locate the same line for SystemJS 0.19.

**Comment by AdamWillden** [comment]
Can we not do away with the offending new line so `source = '\/* *\/ \n' + source;` becomes `source = '\/* *\/' + source;` ?

**Comment by AdamWillden** [comment]
I see that change was made 3 years ago. I don't understand how this hasn't been an issue previously and why it's only an issue for my own packages not third party packages.

**Comment by guybedford** [comment]
Can you share the example steps to reproduce here?

**Comment by AdamWillden** [comment]
@guybedford what exactly is it that you want to see reproduced here? I guess you want an app where a plugin which has sourcemaps is consumed and therefore cannot be debugged? I'll try n get that to you but I'm likely to PM you with a link on gitter than share publicly.

**Comment by guybedford** [comment]
@AdamWillden the code you pointed out is not actually run on download, so I just mean what you did to see `/* */` at the top of a file?

**Comment by AdamWillden** [comment]
Ah okay, I don't do anything different, it's just a `jspm install` of any package AFAIK.

1. Download: https://github.com/aurelia/skeleton-navigation/
2. Extract the `skeleton-esnext` project folder
3. `npm install` `jspm install -y`
4. navigate to `\jspm_packages\npm\aurelia-animator-css@1.0.1` folder
5. open `aurelia-animator-css.js`
6. `/* */` is at top of file

optional extra

7. `npm install aurelia-animator-css`
8. navigate to `node_modules\aurelia-animator-css\dist\amd` folder
9. open `aurelia-animator-css.js`
10. `/* */` is not present at top of file

**Comment by AdamWillden** [comment]
This may still be valid but I'm closing anyway. You'd think someone else would have come across this.

**Comment by guybedford** [comment]
@AdamWillden and that the problem might stick around :)

Will keep open in case someone might care enough to investigate further.
