### ISSUE TITLE
Problems with 0.17 Beta 38 and AMD files

### ISSUE THREAD

**Issue by nevf** [jspm/jspm-cli#2237]
I am having several problems with jspm 0.17 beta 38 and AMD files. First when I use es6 import the object returned from the amd file is missing it's properties. ex.

```
// AMD module
    return { floatingWidget: floatingWidget,
             tip: tip,
             noty: noty
           }
````

es6 module
````
import { tip, noty, floatingWidget } from 'floating_widget';
````
```tip``` et.all. are undefined. This worked perfectly up until I updated from jspm 0.17 beta 32.

When I bundle the app and try and run using the bundle I am getting:
```build.min.js:27 Uncaught ReferenceError: define is not defined```

If I run with an unminified build I get the same error. 

I checked the code in the build from the earlier jspm beta that worked and it is
````
}(typeof define === 'function' && define.amd ? define : function(deps, factory) {
````
has been changed to:
````
})('function' === 'function' && true ? define : function (deps, factory) {
````
ie. ```define.amd``` is now ```true```

Also the earlier build wrapped this file in 
````(function() {
var define = System.amdDefine;
;
````
and this is missing from the latest build.

I've tried reinstalling all node modules and jspm from scratch and it made no difference.

Next I wrote a tiny new app in a new folder with all new ```node_modules``` and ```jspm``` and when I run it and import the following file:
````
define( [], function(){

    function bar( msg  ){
        console.log( 'In bar() msg:', msg )
    }

    return { bar: bar }
})
````
I get
````
Uncaught (in promise) Error: define is not a function
  Evaluating http://localhost:8080/src/bar.js
````
the app also imports an es6 module which works fine.

I've tried everything I can think off to isolate the issue and find a solution to no avail.

**Comment by subhaze** [comment]
I'm not sure if this is your issue, but, in beta 33+ it was bumped to SystemJS 0.20 which no longer supports named imports from non-ES Modules and if I'm reading the first part correctly you're using named imports on an AMD file.

Now you'll have to do something like: `import fw from 'floating_widget ';`

https://github.com/systemjs/systemjs/releases/tag/0.20.0
https://github.com/jspm/jspm-cli/releases/tag/0.17.0-beta.33

**Comment by nevf** [comment]
@subhaze Thanks that should explain the named imports problem. I've been working through all of my own amd files and converting them to es6 to resolve this issue.

>AMD define no longer set by default when using scriptLoad, requires manually setting window.define = System.amdDefine for scriptLoad support of AMD.

This could explain my other issue of ```define``` being undefined. However this only occurs in jspm build's in my main app and was only with one specific amd file which I've now converted to es6. 

I'll try it with my small sample test app.
