### ISSUE TITLE
loading plugin-typescript fails in latest release

### ISSUE THREAD

**Issue by nelisbijl** [jspm/jspm-cli#2239]
Not sure whether to place it here, in systemjs/systemjs or frankwallis/plugin-typescript

It is related to systemjs 0.20.x used in the latest version

systemjs calls the setters function of the plugin with a [ModuleNamespace]
However, it looks like it needed the [ModuleNamespace].default to set the proper value.
I can not figure out how it is supposed to work and whether systemjs or the plugin needs adjustments. Or whether I am doing things wrong.

**Comment by guybedford** [comment]
I'd advise following this up with the typescript project itself.

**Comment by nelisbijl** [comment]
I'd advice anyone to refrain from jspm. It's buggy, beta and won't be production ready in 2 or 3 years

**Comment by unional** [comment]
Probably related to https://github.com/Microsoft/TypeScript/issues/8687

**Comment by guybedford** [comment]
@nelisbijl 2.2 years thank you very much.
