### ISSUE TITLE
Hot Reloading documentation missing a step

### ISSUE THREAD

**Issue by jhoch** [jspm/jspm-cli#2243]
Hello,

I read about hot module replacement being added in JSPM 0.17 and was quite excited to try it.  I started by following along with the instructions here: http://jspm.io/0.17-beta-guide/hot-reloading.html.  It took me a while to get it working due to two issues:

1. `systemjs-hot-reloader` is not compatible with `jspm`, versions `0.17.0-beta33` and higher (issue: https://github.com/capaj/systemjs-hot-reloader/issues/126).
2. The instructions do not specify that `jspm.browser.js` must be included in `test.html`.  This seems obvious in hindsight, but it tripped me up.

Regarding (2), I would go ahead and make a PR on the docs, but I'm not sure the proper structure.  At the time in the instructions when it said "Next edit the `jspm.browser.js` file to include `trace: true`", I did not have a `jspm.browser.js` file.  In other words, after following the initial instructions (here: http://jspm.io/0.17-beta-guide/creating-a-project.html), I only had a `jspm.config.js` and not a `jspm.browser.js`, which is why the hot reloading instructions tripped me up.  It seems possible that the documentaiton mistake is actually in "Creating a Project," not in "Hot Reloading" - perhaps `jspm init` should create a `jspm.browser.js`?

After following http://jspm.io/0.17-beta-guide/creating-a-project.html and http://jspm.io/0.17-beta-guide/hot-reloading.html, I had the following:

`jspm.config.js`:
```
SystemJS.config({
  trace: true,
  paths: {
    "npm:": "jspm_packages/npm/",
    "github:": "jspm_packages/github/",
    "jspm-react-component/": "src/"
  },
  browserConfig: {
    "baseURL": "/"
  },
  devConfig: {
    "map": {
      "plugin-babel": "npm:systemjs-plugin-babel@0.0.20",
      "systemjs-hot-reloader": "github:capaj/systemjs-hot-reloader@0.6.0"
    },
    "packages": {
[...]
```
`test.html`:
```
<!doctype html>
<meta charset="utf-8">
<script src="jspm_packages/system.js"></script>
<script src="jspm.config.js"></script>
<body>
  <div id="container"></div>
  <script>
    SystemJS.import('test.js');
  </script>
</body>
```

and I got it working by changing to the following:

`jspm.browser.js`:
```
SystemJS.config({
  baseURL: "/",
  trace: true,
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*",
    "jspm-react-component/": "src/"
  }
});
```
`jspm.config.js`:
```
SystemJS.config({
  nodeConfig: {
    paths: {
      "npm:": "jspm_packages/npm/",
      "github:": "jspm_packages/github/",
      "jspm-react-component/": "src/"
    }
  },
  devConfig: {
    "map": {
      "plugin-babel": "npm:systemjs-plugin-babel@0.0.21",
      "systemjs-hot-reloader": "github:capaj/systemjs-hot-reloader@0.6.0"
    },
    "packages": {
[...]
```
`test.html`:
```
<!doctype html>
<meta charset="utf-8">
<script src="jspm_packages/system.js"></script>
<script src="jspm.browser.js"></script>
<script src="jspm.config.js"></script>
<body>
  <div id="container"></div>
  <script>
    SystemJS.import('test.js');
  </script>
</body>
```

PS: Interestingly, I had to include a glob-like `*` in my configured paths in `system.browser.js`, but not in `system.config.js`.  For example, `"npm:*": "jspm_packages/npm/*"` vs `"npm:": "jspm_packages/npm/"`.

**Comment by alexisvincent** [comment]
@jhoch This is being tracked here -> https://github.com/alexisvincent/systemjs-hmr/issues/18. Thanks for the issue
