### ISSUE TITLE
Question:  Dev Dependencies .17.0 beta

### ISSUE THREAD

**Issue by jrwpatterson** [jspm/jspm-cli#2245]
I'm running beta 39 I was under the understanding that 0.17 would be the equivalent of npm so I could install gulp etc from jspm for the faster install time to speed up server builds. 

Was I mistaken or have I done something wrong?

**Comment by guybedford** [comment]
0.17 has better support for npm but it is still not comprehensive. Best to
use npm still in these cases.

**Comment by jrwpatterson** [comment]
Ok thats disappointing, will there ever be a day I will be able to gulp from jspm?
