### ISSUE TITLE
Latest JSPM giving errors when trying to load module

### ISSUE THREAD

**Issue by atrauzzi** [jspm/jspm-cli#2247]
If I use an older version ~27 of JSPM, I have no issues loading files.  However if I use the latest, I get this error.

![image](https://cloud.githubusercontent.com/assets/115199/22944599/cfa0e9c8-f2b6-11e6-98fd-4af959f5f581.png)

(I know that I'm not supposed to use extensions when loading modules and that's definitely one of the refactors I'll be tackling in this project.  Although I'd like to get JSPM upgraded first if possible.)

**Comment by amenadiel** [comment]
I don't believe that using extensions is a bad practice. Eventually, it will become the only way to load files.
Not using extensions when loading a package is a whole different story, tho.

**Comment by guybedford** [comment]
@atrauzzi which plugin are you using here?

**Comment by atrauzzi** [comment]
@guybedford Using the TypeScript one.

**Comment by guybedford** [comment]
@atrauzzi thanks, and just to check as well, did you definitely upgrade to the latest version of the plugin?

**Comment by atrauzzi** [comment]
Quick update, I did upgrade yesterday and things didn't work right away.  It seems like I had to blow away my `jspm.config.js` file and reinitialize, following the JSPM init prompts.

Part of me kind of wishes some of this configuration went into `package.json` and just got generated.  I seem to have a lot of issues with `jspm.config.json`.
