### ISSUE TITLE
JSPM 0.16.x UglifyJS dependency causing faulty bundles

### ISSUE THREAD

**Issue by Smolations** [jspm/jspm-cli#2255]
Yesterday, our main bundle (using JSPM 0.16.30) for our angular app starting reporting the following error when attempting to load a bundled module:

![screen shot 2017-03-01 at 11 25 30 am](https://cloud.githubusercontent.com/assets/952681/23474835/63659d40-fe72-11e6-96a5-c9a9ea3fe5b6.png)

No front-end code changes occurred recently that would affect the loading, so we starting inspecting our dependencies and sub-dependencies while reverting to a previous build (via a production tarball) so that our staging instance was functional. What we discovered was that the working build was installing `uglify-js@2.7.5` as a JSPM dependency, while the failing build was installing `uglify-js@2.8.3` as a JSPM dependency. We verified that the uglify versions were the issue by using a shrinkwrap file to override our JSPM sub-dependency for that lib, specifying each of the two versions. However, we do not currently have a shrinkwrap file under version control and do not currently wish to add one, so we will probably need to add some custom deploy commands to use the working uglify-js version.

For reference, here is what the start of the bundles were for each of the two uglify-js versions we were comparing:

**2.7.5 (working):** `"bundle";!function(){var define=System.amdDefine;define("views/home/eg-forgot-password.js",`
**2.8.3 (failing):** `"bundle";!function(){(0,System.amdDefine)("views/home/eg-forgot-password.js"`

Looking at the uglify-js project, it appears that a recent issue was posted that may have addressed whatever problem is causing the bundling issue, but upon using the new version (2.8.4), the problem persisted. I do not know how to articulate to that project what needs to happen to fix the issue because I do not know how JSPM is currently using uglify-js to create the bundles (perhaps minification?). Here is a link to the most recent fix, which also references recent issues that were (supposedly) addressed:

https://github.com/mishoo/UglifyJS2/commit/7aa69117e1a38e4aeead13100ac952ca99dbb07f

I am not sure what the best solution is, but i did notice that many JSPM deps are locked down to a specific version, while the uglify-js dep is not (it's at `^2.6.1`). perhaps locking that down to a working version (2.7.5) would be desirable?

**Comment by guybedford** [comment]
Thanks for reporting this. I've posted a jspm 0.16 release out that locks the UglifyJs version for now.

**Comment by Smolations** [comment]
Thank you!

**Comment by Smolations** [comment]
@guybedford Will this change also be applied to the systemjs-builder project? I have recently removed jspm from my gulp builds in favor of the builder as it decreased memory consumption when building a handful of bundles. It would be helpful to make sure the version is locked down for that project as well.
