### ISSUE TITLE
Electron caching JS unless jspm is run with -wid

### ISSUE THREAD

**Issue by charandas** [jspm/jspm-cli#2256]
I am using `0.17.0-beta.40`.

I have an angular app that relies on a handful of jquery plugins. I am able develop on the fly in Chrome (when not creating bundles), but not the same in Electron.

**Comment by charandas** [comment]
Figured, it was some kind of cache plaguing me. The `meta` configuration in Beta 0.17 (previously `shim`) works well.

I am still not sure why Electron caches the stuff and only busts cache when `jspm` is run in background with `-wid`. Gaining insight into that would allow me to close this issue. To be clear, I am not running with bundle.js in the browser. I am loading the JSPM config, systemjs et al.

I did move to github:components/jquery from npm:jquery, but they both look alike AFAIK.

**Comment by aluanhaddad** [comment]
If you run `jspm bundle -wid`, the `-i`, aka `--inject`, flag causes the bundle configuration to be stored in **jspm.config.js** so that you do not have to change your **index.html** by adding an additional script tag. The bundle will be loaded regardless of whether or not the watcher is actually running.

You can run `jspm unbundle` to clear any bundle configuration.

**Comment by charandas** [comment]
Thanks @aluanhaddad. That makes total sense now. Electron wasn't caching, it was just loading the bundle; on one hand I really like testing with the final artifact in development; but it's quite slow nonetheless.

I am gonna try this once again: https://github.com/virtkick/node-serve-jspm

**Comment by charandas** [comment]
Or this one: https://github.com/alexisvincent/systemjs-tools

**Comment by aluanhaddad** [comment]
Personally, for unbundled builds, I still like using `npm:lite-server` for development.
I use a **bs-config.js** file that looks like

```javascript
module.exports = {
  server: {
    baseDir: '',
    port: 3000,
    proxy: {
      target: 'localhost:3000',
      proxyRes: [function (proxyRes) {
        if (proxyRes.req.path.match(/jspm_packages/)) {
          proxyRes.headers['cache-control'] = 'max-age=604800, public';
        }
      }]
    }
  },
  files: [
    '**/*.{html,ts,tsx,js,jsx,css}'
  ],
  watchOptions: {
    injectChanges: true,
    files: [
      '**/*.{html,ts,tsx,js,jsx,css}'
    ],
    ignored: [
      'jspm_packages',
      'node_modules'
    ]
  },
  injectChanges: true
};
```
