### ISSUE TITLE
angular 2 doesn't work when installed with jspm 0.17

### ISSUE THREAD

**Issue by dima-gusyatiner** [jspm/jspm-cli#2257]
Hi guys!
I'm trying to incorporate angular 2 with jspm 0.17, but i'm stuck with this issue for a while now.

When **installing via node**, and importing it via maps configuration, it works:
**[github.com/dima-gusyatiner/system-0.20-angular-2](https://github.com/dima-gusyatiner/system-0.20-angular-2)**

But when **installing via jspm**, it doesn't work anymore.
It complains it can't make the es named import ( `TypeError: core_1.Component is not a function`, http://stackoverflow.com/questions/42564743/issues-with-es6-import-systemjs-0-20-9-typescript-angular-2-jspm-0-17-0-b )
**[github.com/dima-gusyatiner/system-0.20-jspm-0.17-angular-2](https://github.com/dima-gusyatiner/system-0.20-jspm-0.17-angular-2)**

----

On the same note, I'd like to ask about the preferred approach.
I think application bundles should still be created with JSPM. Hot module replacement is also a vital feature.
But unfortunately, IDE lacks code intel (no autocomplete) if using only JSPM. So the packages have to be installed with node first.
A good discussion can be found here: [github.com/systemjs/systemjs/issues/767](https://github.com/systemjs/systemjs/issues/767).
I think I've seen somewhere a beta feature of system / jspm, to automatically resolve packages from node.
I can't seem to find it again. Anyway, what approach is better?
1. install node packages with jspm (two copied), upon npm install or before build
2. use [jampekka/system-npmlocator](https://github.com/jampekka/system-npmlocator) to resolve them on demand, when serving in browser, bundeling, and hot replacing
3. use [alexisvincent/systemjs-config-builder](https://github.com/alexisvincent/systemjs-config-builder) to generate them into system config, upon install or before build

**Comment by guybedford** [comment]
For the latest SystemJS version it is necessary to add the `esModule: true` metadata configuration:

```javascript
System.config({
  meta: {
    'path/to/angular-build.js': { esModule: true }
  }
});
```

This is also needed for each of the angular UMD builds unfortunately.

**Comment by gionkunz** [comment]
@guybedford this does not seem to work when running `jspm build`. Any idea?

**Comment by guybedford** [comment]
Yes, this is a known bug at https://github.com/systemjs/builder/issues/775. Hopefully we can get this fixed soon.

**Comment by guybedford** [comment]
And thanks for the ping @gionkunz, it's an important one.

**Comment by guybedford** [comment]
https://github.com/systemjs/builder/issues/775 is resolved now, and I think this has been fixed on the Angular side too.
