### ISSUE TITLE
Keep `package.json` and `jspm.config.js` clean

### ISSUE THREAD

**Issue by ArmorDarks** [jspm/jspm-cli#2260]
Hello

Thanks once again for JSPM!

We faced few issues with how JSPM treats `package.json` and `jspm.config.js`, and wonder is it possible to make this cleaner.

Consider this. We have empty, clean `package.json` and `jspm.config.js`

Let's install simple dependency

```shell
jspm install npm:system-coffee --save-dev
```

What we expect to see in `package.json`:

```js
  "jspm": {
    "name": "kotsu",
    "main": "main.js",
    "dependencies": {},
    "devDependencies": {
      "systemjs-plugin-json": "npm:system-coffee@^0.1.2",
    }
  },
```

and in `jspm.config.js`:

```js
SystemJS.config({
  baseURL: "assets/scripts",
  paths: {
    "npm:": "jspm_packages/npm/"
  },
  devConfig: {
    "map": {
      "system-coffee": "npm:system-coffee@0.1.2",
    }
  },
  packages: {
    "kotsu": {
      "main": "main.js",
      "format": "esm"
    }
  }
});

SystemJS.config({
  ...
});
```

Unfortunately, after installation we will see instead:

```js
  "jspm": {
    "name": "kotsu",
    "main": "main.js",
    "dependencies": {},
    "devDependencies": {
      "fs": "npm:jspm-nodelibs-fs@^0.2.0",
      "module": "npm:jspm-nodelibs-module@^0.2.0",
      "path": "npm:jspm-nodelibs-path@^0.2.0",
      "plugin-babel": "npm:systemjs-plugin-babel@^0.0.21",
      "process": "npm:jspm-nodelibs-process@^0.2.0",
      "system-coffee": "npm:system-coffee@^0.1.2"
      "vm": "npm:jspm-nodelibs-vm@^0.2.0"
    }
  },
```

and

```js
SystemJS.config({
  baseURL: "assets/scripts",
  paths: {
    "npm:": "jspm_packages/npm/"
  },
  devConfig: {
    "map": {
      "system-coffee": "npm:system-coffee@0.1.2",
      "fs": "npm:jspm-nodelibs-fs@0.2.0",
      "vm": "npm:jspm-nodelibs-vm@0.2.0",
      "process": "npm:jspm-nodelibs-process@0.2.0",
      "path": "npm:jspm-nodelibs-path@0.2.1",
      "module": "npm:jspm-nodelibs-module@0.2.0"
    }
  },
  packages: {
    "kotsu": {
      "main": "main.js",
      "format": "esm"
    }
  }
});

SystemJS.config({
  ...
});
```

If we will try to install React and other libs, things will become even messier:

```shell
jspm install react redux react-dom
```

This will dump into our `package.json` this glorious part

```js
  "jspm": {
    "name": "kotsu",
    "main": "main.js",
    "dependencies": {
      "react-dom": "npm:react-dom@^15.4.2",
      "redux": "npm:redux@^3.6.0"
    },
    "devDependencies": {
      "module": "npm:jspm-nodelibs-module@^0.2.0",
      "plugin-babel": "npm:systemjs-plugin-babel@^0.0.21",
      "system-coffee": "npm:system-coffee@^0.1.2",
      "systemjs-plugin-json": "npm:systemjs-plugin-json@^0.3.0"
    },
    "peerDependencies": {
      "assert": "npm:jspm-nodelibs-assert@^0.2.0",
      "buffer": "npm:jspm-nodelibs-buffer@^0.2.0",
      "child_process": "npm:jspm-nodelibs-child_process@^0.2.0",
      "constants": "npm:jspm-nodelibs-constants@^0.2.0",
      "crypto": "npm:jspm-nodelibs-crypto@^0.2.0",
      "domain": "npm:jspm-nodelibs-domain@^0.2.0",
      "events": "npm:jspm-nodelibs-events@^0.2.0",
      "fs": "npm:jspm-nodelibs-fs@^0.2.0",
      "http": "npm:jspm-nodelibs-http@^0.2.0",
      "https": "npm:jspm-nodelibs-https@^0.2.0",
      "os": "npm:jspm-nodelibs-os@^0.2.0",
      "path": "npm:jspm-nodelibs-path@^0.2.0",
      "process": "npm:jspm-nodelibs-process@^0.2.0",
      "react": "npm:react@^15.4.2",
      "stream": "npm:jspm-nodelibs-stream@^0.2.0",
      "string_decoder": "npm:jspm-nodelibs-string_decoder@^0.2.0",
      "url": "npm:jspm-nodelibs-url@^0.2.0",
      "util": "npm:jspm-nodelibs-util@^0.2.0",
      "vm": "npm:jspm-nodelibs-vm@^0.2.0",
      "zlib": "npm:jspm-nodelibs-zlib@^0.2.0"
    },
```

Notice, that `react` even no longer listed as direct dependency of our package.

Well, someone can tell that this shouldn't matter, but, unfortunately, those invasions into `package.json` by JSPM makes maintenance very hard, since you no longer can just look into `package.json` and clearly understand on what packages relies your package, because you see not what you've installed and saved as dependencies, but all their siblings.

It becomes even harder when JSPM starts to mess with `peerDependencies` and move direct dependencies to `peerDependencies` while you didn't ask for it. I saw repositories in which it absolutely impossible to understand dependencies, because JSPM dumped half of dependencies in `peerDependencies` and messed them with dependencies of main dependencies to the form of unreadable mess.

I understand that there were reasons for making it this way. But I wonder, can we figure out way to keep our `package.json` and first part of `jspm.config.js` cleaner, so that JSPM won't pollute them with mappings and dependencies lists unless we explicitly decided to add those in configs, otherwise keep those mappings in `jspm_packages` internally.

**Comment by ArmorDarks** [comment]
@guybedford Any plans for this? Maybe we can help somehow in designing system, how it should work?

Just another showcase of the issue.

```shell
jspm install npm:babel-plugin-preval --dev
```

Results in following `package.json` changes:

![smartgit_2017-07-20_23-38-00](https://user-images.githubusercontent.com/4460311/28437764-80021054-6da4-11e7-8ff1-172b53b9d828.png)

Enforced changes in `overrides` are at least somehow justified, but I'd say that they should be stored in internal JSPM mappings, and `package.json` should be used only for cases when user want intentionally to override something.

But it is completely unclear why JSPM dumps all those dependencies into `package.json`, since it already saves own mapping in `jspm.config.js`. Once again, `package.json` should be reserved only for explicit user's input, dependencies of dependencies should not write themself there. In our case, it should add only our explicitly defined dependency: `babel-plugin-preval`.

Situation with `jspm.config.js` isn't great either.

![smartgit_2017-07-20_23-40-59](https://user-images.githubusercontent.com/4460311/28437939-18633940-6da5-11e7-8d98-2ec06ce853c5.png)

We can see that JSPM intentionally writes all dependencies mappings into `devConfig` of first `SystemJS.config`. And, they are quite huge...

This also looks strange, since main portion of config should be reserved only for explicit user's input. In our case, we asked to install `babel-plugin-preval`, thus `babel-plugin-preval` is the only mapping which should appear in that section. All other mappings of `babel-plugin-preval` dependencies would be better to store in second `SystemJS.config`, which should be treated as JSPM internal mapping and better to be moved into `jspm_packages`.

First `SystemJS.config` should be reserved only for intentional users mappings additions or overrides.

**Comment by guybedford** [comment]
Yes this isn't ideal, but it is the way jspm is currently architectured. I'm working on some improvements for exactly these problems in jspm 2 though.

**Comment by aluanhaddad** [comment]
For what it's worth, I've  found that using the option to split configuration between a browser, dev, and primary configuration file makes diffs easier to deal with.

**Comment by ericnewton76** [comment]
Yes this would be great, where the package.json isnt messed with as much as it is now.  

@guybedford you mention its the current architecture, would it not be a relatively simple redirection of what is the equivalent of the locked-down-package-versions, (ie, equivalent to npm's package-lock.json file) into a similar jspm-package-lock.json, and the package.json jspm gets just the entries added via `jspm install`?  Seems like it would be relatively low-cost
