### ISSUE TITLE
Introduce `--save` flag

### ISSUE THREAD

**Issue by ArmorDarks** [jspm/jspm-cli#2261]
This issue is tightly coupled to https://github.com/jspm/jspm-cli/issues/2260 and useless without it.

As a side effect of https://github.com/jspm/jspm-cli/issues/2260, moving all not user-declared mapping into internals will also resolve issue with senseless `--save` flag during `jspm install`.

Node-like behavior with `npm install` not saving any dependencies is very useful during development, since sometimes you want to install and test something, but actually _not_ to add it to dependencies.

This is something impossible right now, and because of  that we're forced always to stage `package.json` and `jspm.config.js` before installing anything with JSPM, and then revert it back. This makes testing libraries quite painful, especially considering how intensively some libraries with many dependencies can pollute configs.

Current behavior is understandable, because SystemJS needs to store mapping somewhere. But if they will be moved into internal files, inside `jspm_package`, it will be possible to install and use package with `jspm install`, or install _and_ add to package dependencies with `jspm install --save`, thus making everyone happy.

In result, it will make usage of JSPM CLI straightforward and cognitively easier to understand, especially for beginners.

**Comment by aluanhaddad** [comment]
While I appreciate the spirit of this suggestion, especially as it relates to ease of use for newcomers, I have deep reservations regarding a change to this behavior as the current behavior offers many benefits. The auto saving nature of the jspm install command improves reliability and prevents common development errors that are rampant in npm based projects.

In one of my day jobs, I work on such a project, which uses npm and Webpack, and _without fail_ people simply forget to run `npm install` when switching from develop to master and back to develop when creating and testing a hotfix (for context this project use Atlassian gitflow and deploys around 3 times a week). I update packages very frequently and there are often different versions of critical components in these branches (e.g. typescript@2.1.6 vs 2.2.1) where the differences substantial.

Perhaps I misunderstand your suggestion, but by requiring that the changes to jspm.config.js and package.json be synchronized and checked into source control, the scenario I described above will result in jspm failing to load the app due to a version mismatch. In my view this is a strong advantage.

**Comment by ArmorDarks** [comment]
Hi!

Thanks for your input!

Yes, you a right, this problem occurs, and it has something to do with how NPM resolves dependencies.

However, the NPM way with `--save` is more obvious, because it is explicit. You sure what you're doing by specifying or no specifying that flag, you clearly understand consequences. If you didn't ask npm to explicitly save your input, it won't do this.

On contrary to this, JSPM makes assumptions about intentions of user, and this not only results in limited possibilities (as mentioned, you can't install lib without saving it), but also to sudden, unexpected side effects. You've made `jspm install` of library with many dependencies in project, without git? In some scenarios you will have to spend a lot of time to reverse all changes manually. `jspm uninstall` is great, but it's not always helpful, especially when JSPM reformats your `package.json` and `jspm.config.js` when you didn't ask for it.

As a side note I clearly understand that those assumptions made not because of design, but because so far JSPM relies on mapping in SystemJS config file, it can't work without it. So, `jspm install` without saving those mapping right now is useless, that's why we don't have `--save` flag. But I guess we should strive to make system better with less side effects. In fact, that aspect more touched in #2260.

> In one of my day jobs, I work on such a project, which uses npm and Webpack, and without fail people simply forget to run npm install when switching from develop to master and back to develop when creating and testing a hotfix

That's reminder about interesting case, you're right. I think described issue is more related to how organized usage of tool, but not to how that tool works, though, I agree that tool shouldn't make it a nightmare.

Introducing of `--save` indeed makes whole behavior less strict, since it introduces cases, when you can install something without mentioning it in `package.json`, and then import it. SystemJS will resolve path based on hidden in `jspm_packages` config, and indeed, everything will work even after switching the branch.

However, that's whole point about installing something without saving it, same way as it done in npm. It doesn't track version of dependency.

If you will `--save` it, JSPM will have legitimate source of dependencies, and will compare resolution to `package.json` dependencies and user's `jspm.config.js` overrides. Most likely after switching branch they won't match (paths due to different versions will be different), and imports in app will return error. So, it's still safe.

> Perhaps I misunderstand your suggestion, but by requiring that the changes to jspm.config.js and package.json be synchronized and checked into source control

Hm, I didn't understand that part. What do you mean by saying `synchronized and checked into source control`?

My point, in short:

* With `--save` flag JSPM should behave same way as it does now, and similarly to NPM: install required dependencies and save them to `package.json`, add mappings to `jspm.config.js`
* Without `--save` flag JSPM should install required dependencies and save resolutions to _internal_ SystemJS config, which can be stored in `jspm_packages`, without touching `package.json` or users `jspm.config.js`

Ideally, if #2260 would be implemented, user's `jspm.config.js` shouldn't be touched at all and always used internal SystemJS config, stored in `jspm_packages`, unless user explicitly asks for it.

> the scenario I described above will result in jspm failing to load the app due to a version mismatch. In my view this is a strong advantage.

As I've described above, with `--save` behavior will remain same. You can introduce issues only by not doing `--save` and switching branches, but you're doing `--save`-less installation on purpose, same as in case of NPM, so it's expected behavior.

**Comment by ArmorDarks** [comment]
I think this issue is not relevant anymore, since npm 5+ moved to other semantics of `npm install`, and no longer uses `--save` flag. Instead, any install now will save it to `package.json` and lockfile. In other words, JSPM and NPM `install` now pretty much similar.

I'm still quite unhappy about mess that JSPM does with `package.json` and config-file, but there is a #2260 issue for it already.

**Comment by guybedford** [comment]
The pains of being ahead of the curve :)

jspm 2.0 will be aligning a lot more with node ways too.

**Comment by ArmorDarks** [comment]
> jspm 2.0 will be aligning a lot more with node ways too.

eager to see that! :)
