### ISSUE TITLE
`production` variable and building for production

### ISSUE THREAD

**Issue by ArmorDarks** [jspm/jspm-cli#2263]
Hello

In JSPM beta.21 there was a `production` variable, which were imported like that:

```js
import { production } from '@system-env'
```

In JSPM beta.41 it no longer works and always returns `undefined`. Was it deprecated? I can't find anything about it in logs.

I've also tried to add `--production` to `jspm build --minify`, and add `production: true` to `jspm.config.js`, but still it returns undefined.

Particularly in our case, we want to inject specific middleware only when we are _not_ in production environment, like that:

```js
// ... middleware imports ...

import { production } from '@system-env'

let middleware = [thunk, routerMiddleware(browserHistory)]

if (!production) {
  middleware = [...middleware, immutableStateInvariant(), logger({ collapsed: true })]
}
```

However, since `production` variable always ends up `undefined`, that check is always passed and Browser tries to execute `immutableStateInvariant` which ends up undefined.

Well, though, it's strange why `immutableStateInvariant` ends up undefined in production... I guess it is because it uses `NODE_ENV` check somewhere internally and gets stripped during production shipping. But it isn't related to this issue, I guess.

**Comment by guybedford** [comment]
Is `production` undefined specifically when running `jspm build` and then executing the built file in node?

**Comment by ArmorDarks** [comment]
> Is production undefined specifically when running jspm build and then executing the built file in node?

Not exactly. We make `jspm build` and then loading built file in the browser, not node. Yes, it ends up `undefined`.

**Comment by guybedford** [comment]
Tracking at https://github.com/systemjs/builder/issues/799.
