### ISSUE TITLE
Wrong module format for `redux-thunk`

### ISSUE THREAD

**Issue by ArmorDarks** [jspm/jspm-cli#2264]
Hello

We faced issue with this small library: [redux-thunk](https://github.com/gaearon/redux-thunk)

It works perfectly in development, when not used `jspm build` and deps loaded directly by SystemJS.

However, when we try to `jspm build` our app, JSPM for some reason defines (I guess) as a format of `redux-thunk` the CommonJS, despite lib itself exports result with `export default`.

Well, it isn't great issue, however it resulted in quite curios situation. As seen in `redux-thunk` readme, when lib required via non ES6 way, it should be called as `thunk.default` — with `default` method, not just `thunk`, while for ES6-supporting environments it should be just `thunk`.

Because of that, this code works flawlessly during development, but throws error that `thunk is not a function` after `jspm build`:

```js
import { createStore, applyMiddleware } from 'redux'
import thunk from 'redux-thunk'

import reducers from './reducers/index'

export default createStore(
  reducers,
  applyMiddleware(thunk) // for `jspm build` it should be `thunk.default`
)
```

I tried to redefine format manually in `package.json` with

```js
      "npm:redux-thunk@2.2.0": {
        "format": "esm"
      }
```

but it didn't make a difference. So, maybe issue related to something other.

Strangely enough, it worked in JSPM beta.21, but doesn't work in JSPM beta.41.

The issue itself workaroundable, of course, but still quite unclear why it happens.

Thanks

**Comment by aluanhaddad** [comment]
Try
```js
"npm:redux-thunk@2.2.0": {
  "esModule": true
}
```

**Comment by ArmorDarks** [comment]
@aluanhaddad 

Thanks. Unfortunately, it didn't fix the issue :(

**Comment by funn** [comment]
Got the same problem, using dirty workaround.

**Comment by aluanhaddad** [comment]
I tried the following override successfully in 0.17.41
```bash
$ jspm i npm:redux-thunk -o ./override.json
```
If the above doesn't work clear any existing override for npm:redux-thunk by specifying the -f flag
```bash
$ jspm i npm:redux-thunk -fo ./override.json

```
**overerride.json**
```json
{
  "main": "es/index.j"
}
```
This worked for in browser transpilation with plugin-babel, bundling, and builds.
Let me know if that resolves the issue and we can create an override in the registry to handle this in the future.

**Comment by aluanhaddad** [comment]
Tested this with 0.16.53 and found that the a backwards compatible override needs to specify the module format
```json
{
  "format": "esm",
  "main": "es/index.js"
}
```
