### ISSUE TITLE
Uncaught ReferenceError: System is not defined in built output

### ISSUE THREAD

**Issue by atrauzzi** [jspm/jspm-cli#2265]
I'm using this command to build:
```
jspm build src/App/OrganizationSelect/main.tsx --minify organizationselect.js"
```

Unfortunately it looks like the output still includes a call to `System.register`, and I'm not sure why or how to get around this such that my script can just run.  This build has been working for a while now without ever encountering this issue, so I suspect something has changed in JSPM to cause my builds to break...

**Comment by atrauzzi** [comment]
When I don't minify, it's fairly clear to me that all I'm getting is a UMD module of the first file.  But none of its dependencies are being included.  So it's basically like as if I've only built that one file and nothing else.

**Comment by aluanhaddad** [comment]
This is a react app? Can you share a repro?

**Comment by atrauzzi** [comment]
Not easily.  I may have stumbled on a solution yesterday and lost it, and now I can't recall what the fix was.

I was messing around with this part of `jspm.config.js`:

```
    packages: {
        "src": {
            "defaultExtension": "tsx",
            "modules": {
                "*.tsx": {
                    "loader": "typescript"
                }
            }
        },
```

Could almost swear I had it outputting the whole graph without any calls to `System`.  Unfortunately I can't find the ticket that had the reccomendation, so I can't be certain if the structue above is correct.  I really wish the documentation would be finalized for this project.

**Comment by atrauzzi** [comment]
Alright, further update.  I was able to get things building by switching the `"modules"` key above to `"meta"`.

Encountering another issue now however with the `react-redux` pacakge exporting with the following quirk:

```
// Works unbuilt, fails built:
const thunkMiddleware = thunk.default;
// Works built, fails unbuilt:
//const thunkMiddleware = thunk.default.default;
```

@aluanhaddad or @guybedford  -- Think you can help?

**Comment by guybedford** [comment]
@atrauzzi this may be related to https://github.com/systemjs/builder/issues/775.

**Comment by adelespinasse** [comment]
Thanks for this solution to "System is not defined". It's definitely a matter of having the meta/.../loader configured. I have no idea what these configuration options really mean, but in converting from Babel to Typescript (in a project that is still mostly .js files), I had to add the loader option for *.js extensions fix this error.

The thing with thunk.default vs thunk.default.default seems like this, which Guy said should hopefully be fixed soon: systemjs/babel-plugin-transform-cjs-system-wrapper#12

**Comment by guybedford** [comment]
https://github.com/systemjs/builder/issues/775 is resolved pending the next release.
