### ISSUE TITLE
Preserve fork resolve/Save to overrides

### ISSUE THREAD

**Issue by DaSchTour** [jspm/jspm-cli#2267]
In my current project we sadly have hit two libraries that only use absolute versions which leads to a lot of works and a exploding bundle size. So I tried to clean this up be using overrides and the resolve function. What I found doesn't help at all.
Overrides for versions are deleted from the package.json son that's not the solution. Using resolve only is a one time fix as the next jspm update reverts to previous state.

So I would love to suggest a solution that maybe combines both. A save option for resolve function that adds this resolve as an override to the package.json so I can transfer this option savely from one developer to the next and don't have to fear that somebody will throw it all away with a jspm update.

**Comment by amenadiel** [comment]
If you override the module's config file

For example `jspm_packages \module1\module1.json", definition json file will make  jspm generate the corresponding ovettidwe, with overrides yhay perdure every jspm or lib operapinon.

**Comment by DaSchTour** [comment]
@amenadiel but modifiying something in jspm_packages will be only for my local system. I need a solution that will be preserved through out different developers.

**Comment by guybedford** [comment]
The custom jspm.config.js resolutions are supposed to be persisted through version updates, but there may be edge cases to this version resolution code. If you can point out the exact process by which the jspm.config.js resolutions are being lost, I can see if I can look into it as a bug. That is the recommended approach though here.
