### ISSUE TITLE
Is transpiler needed after bundling?

### ISSUE THREAD

**Issue by amenadiel** [jspm/jspm-cli#2268]
I've set `plugin-babel` as my default transpiler in `jspm.config.js`.

I've got a package written entirely in ES6 syntax. When I bundle and inject to `jspm.browser.js` I see the bundle doesn't have `import` nor `export` statements anymore. However, I can see that loading the bundle still causes `systemjs-babel-browser.js` to be loaded.

Perhaps there should be a way to tell the transpiler that files having "bundle" at the top don't need to be transpiled.

**Comment by amenadiel** [comment]
@guybedford I found the cause and it might be considered a bug.

One of my modules had the form

```js
"format esm"

const someVar = {
	   ...
	};
export default someVar;
```

Bundling this module along others resulted in a bundled file that started with

```js
"bundle";"format esm";System.register(...
```

And that **format esm** was the one causing `systemjs-babel-browser.js` to be loaded and transpile the bundle (which was pretty slow) which didin't need transpiling at all.

I can't find the old docs but I believe having "format something" at the beggining of a module hinted systemjs on its type. I guess that format hinting is not desirable anymore.

**Comment by aluanhaddad** [comment]
Have you installed `plugin-babel` as `devDependency`?

**Comment by amenadiel** [comment]
Nope, I have it as a peer dep.

**Comment by aluanhaddad** [comment]
The format pragma is added to certain files on installation of certain packages by jspm@0.16.x. `meta` configuration handles this in 0.17.x.

 I'm glad you discovered the cause of the issue.

I take it that the pragma was in code that was part of your app, not from a dependency.

**Comment by amenadiel** [comment]
Yes, it came from a module of my own. There was a certain point during development in which I resorted to that pragma to force the bundle to treat it as ES6.

**Comment by aluanhaddad** [comment]
Thanks, I wanted make sure I understood the use case.

**Comment by amenadiel** [comment]
Ok, I'm closing this issue since that pragma was my own addition and not the product of a jspm operation,
