### ISSUE TITLE
jspm bundle has wrong path in source map file

### ISSUE THREAD

**Issue by jithin1987** [jspm/jspm-cli#2269]
Source map file generated for development via `jspm bundle src/main.js -wid` generates wrong source maps. For files in my app inside `src/` does not have path. Say if one js file is at `src/components/Header.js` in `build.js.map` it's just `Header.js`. They are missing path.

However source maps generated via `jspm build` has correct file path in source map.

**Comment by jithin1987** [comment]
Adding `--source-map-contents` makes my source maps work again. What exactly does it do, documentation is sparse ?

**Comment by aluanhaddad** [comment]
@jithin1987 Thanks for bringing this up. You can read about the flag at https://github.com/systemjs/builder/blob/28cefe0e32706b7cc6b615d73cebfcf3fc8fd4b6/README.md#sourcemap-options
That said, it really should be documented in here as well and likely have some info printed about it on the command line. 
It is not obvious what it does simply from reading its name.

**Comment by jithin1987** [comment]
Using `--source-map-contents` unblocks me, but I guess ultimately issue of incorrect path in source maps in bundle mode needs to be addressed.

**Comment by aluanhaddad** [comment]
@jithin1987 that's true. Definitely need to discover the root cause. I will leave this issue open to track it.

**Comment by ArmorDarks** [comment]
Hm, my paths look even worse. Like so:

```
"../../../source/scripts/utils/file:/J:/Work/Someapp/github/source/scripts/utils/someUtil.js"
```
