### ISSUE TITLE
Can't import react from generated typescript files

### ISSUE THREAD

**Issue by pocesar** [jspm/jspm-cli#2272]
the file below was generated by Typescript. the `console.log` below is showing `l {Symbol(): Object}`, but when checking the `react/react.js` file, it isn't an es6 module, but a commonjs module. 

Therefore it's showing the error "Object prototype may only be an Object or null: undefined" because there's no `React.Component` in the React import

tried setting the meta esModule to false, but didn't work

Using JSPM@beta, and systemjs loader 0.20.10, using 0.20.11 is even worse and bring more problems in other files

```js
System.register(["react", "react-router-dom"], function (exports_1, context_1) {
    'use strict';
    var __extends = (this && this.__extends) || (function () {
        var extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
        return function (d, b) {
            extendStatics(d, b);
            function __() { this.constructor = d; }
            d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
        };
    })();
    var __assign = (this && this.__assign) || Object.assign || function(t) {
        for (var s, i = 1, n = arguments.length; i < n; i++) {
            s = arguments[i];
            for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
                t[p] = s[p];
        }
        return t;
    };
    var __moduleName = context_1 && context_1.id;
    function SubmenuItem(props) {
        return (React.createElement(react_router_dom_1.NavLink, __assign({}, props, { activeClassName: "active", className: "content-submenu-item" })));
    }
    exports_1("SubmenuItem", SubmenuItem);
    var React, react_router_dom_1, Submenu;
    return {
        setters: [
            function (React_1) {
                React = React_1;
            },
            function (react_router_dom_1_1) {
                react_router_dom_1 = react_router_dom_1_1;
            }
        ],
        execute: function () {
            console.log(React);
            Submenu = (function (_super) {
                __extends(Submenu, _super);
                function Submenu() {
                    return _super !== null && _super.apply(this, arguments) || this;
                }
                Submenu.prototype.render = function () {
                    return (React.createElement("div", { className: "content-submenu" }, this.props.children));
                };
                return Submenu;
            }(React.Component));
            exports_1("Submenu", Submenu);
        }
    };
});
//# sourceMappingURL=submenu.js.map
```

the original import inside .tsx files looks like

```ts
import * as React from 'react'
```

React has no default exports if imported as `import React from 'React'`

**Comment by aluanhaddad** [comment]
> React has no default exports if imported as import React from 'React'
Can you clarify what you mean?
If you write 
```ts
import React from 'react';
console.log(React);
```
do you get `undefined`?
If it is _not_ undefined, then the solution is simply to fix your `tsconfig.json`
**tsconfig.json**
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true
  }
}
```

**Comment by arackaf** [comment]
For me allowSyntheticDefaultImports only fixed the compile time errors.  For it to work at runtime I also added

`"module": "es2015",`

to compilerOptions in tsconfig.json.

**Comment by aluanhaddad** [comment]
@arackaf Sorry for the late followup.

I am glad you were able to resolve the issue.

Interestingly, changing the module target in _tsconfig.json_ should not affect this unless you had `"module": "none"` specified. That said, there were some changes around this behavior in TypeScript since 2.1, but everything should work fine in the latest stable release.
