### ISSUE TITLE
jspm only attempts to use latest peer dependency

### ISSUE THREAD

**Issue by vsviridov** [jspm/jspm-cli#2274]
I'm installing the `react-redux` package. In its peer dependencies react is listed as such
```
"react": "^0.14.0 || ^15.0.0-0 || ^16.0.0-0",
```
React 16 is currently in beta, and all packages for it are in `16.0.0-alpha1` format so they do not match the `^16.0.0-0` specifier. I have latest React 15 installed. According to the peer dependency specification it should happily pick it up and use it, however i get this message
```
err  Installing npm:react-redux@5.0.3, no version match for npm:react@^16.0.0
```
I have to manually add the override.

It should look at all available versions that match, not just the latest.

**Comment by aluanhaddad** [comment]
@vsviridov Thanks raising this issue. I was able to reproduce the behavior immediately and consistently. I will try to look into it this weekend.

**Comment by vsviridov** [comment]
The other odd consequence of that was this: I add the override to `package.json` file. I run `jspm install` or `jspm update`. It updates all the dependencies, but the override section is now gone from `package.json`. I have to manually re-add it each time I want to do an update.

**Comment by aluanhaddad** [comment]
Which version of jspm are you using?

**Comment by vsviridov** [comment]
```
0.17.0-beta.41
Running against local jspm install.
```

**Comment by aluanhaddad** [comment]
Don't add the overrides manually to the `package.json`. In jspm 0.17, a lot of information is stored in the dep@x.y.z.json files that live in the jspm_packages directory.

Instead add it like

```bash
$ jspm i react-redux -o "{ peerDependencies: { react: '15.0.0' } }"
```

**Comment by vsviridov** [comment]
Ah, i see. I think the command line style was broken, i had to add it via an override file. I was getting JSON syntax errors when I was usint it inline, even though it was correct. (I'm also on fish shell, dunno if that does some weird escaping).

**Comment by aluanhaddad** [comment]
It may well be your shell. The syntax I posted works for Windows Powershell and cmd and should also work in terminal, but using a JSON file is actually a better practice as writing relatively complex overrides inline quickly becomes unwieldy.
