### ISSUE TITLE
can't use package override on 0.17 (being ignored), jspm trying to load wrong path

### ISSUE THREAD

**Issue by pocesar** [jspm/jspm-cli#2275]
```js
SystemJS.config({
  paths: {
    "npm:": "jspm_packages/npm/",
    "github:": "jspm_packages/github/",
    "dist/": "dist/",
    "lib/": "lib/",
    "cim-typings/": "node_modules/cim-typings/",
    "cim-shared-ui/": "node_modules/cim-shared-ui/*",
  },
  browserConfig: {
    "baseURL": "/"
  },
  packages: {
    "dist": {
      "format": "register"
    },
    "cim-typings": {
      "format": "cjs",
      "main": "index.js"
    },
    "cim-shared-ui": {
      "format": "register"
    },
    "lib": {
      "format": "register"
    }
  },
})
```

tried without trailing slash, with wildcards, everything. jspm is trying to load `localhost:3000/cim-shared-ui/helpers` instead of `localhost:3000/node_modules/cim-shared-ui/helpers.js`

calling like this code:

```ts
import { date } from 'cim-shared-ui/helpers'
```

weird is that the `cim-typings` work

![image](https://cloud.githubusercontent.com/assets/461084/24862557/7381e3b6-1dd3-11e7-9966-8b395e08d626.png)

**Comment by pocesar** [comment]
since I'm in a hurry, had to write an URL overwrite on the server, tried everything and couldn't make it work

**Comment by guybedford** [comment]
On first glance, it looks like `"cim-shared-ui/": "node_modules/cim-shared-ui/*",` should be `"cim-shared-ui/": "node_modules/cim-shared-ui/",`?

**Comment by pocesar** [comment]
tried every combination @guybedford, couldn't get it to work. maybe because I don't have an `index.js` file or a `"main"` inside package.json? do I always need to have one?

**Comment by guybedford** [comment]
Can you perhaps share a simple replication then?

**Comment by pocesar** [comment]
i'm using npm link, is that a problem? the issue is that `cim-typings` is also a npm link... does jspm expect the "main" field on package.json to always be set?

**Comment by pocesar** [comment]
after many days struggling with this problem, it seems that only this notation with anonymous register modules are failing:

```es6
// g:/www/components/list.tsx 
import { requestJson } from 'cim-shared-ui/helpers'
// it's being compiled from TS as:
System.register(["react", "react-redux", "cim-shared-ui/title", "react-router-dom", "cim-typings", "cim-shared-ui/submenu", "cim-shared-ui/helpers", "bluebird", "./staticmap", "classnames", "./status", "lodash"], function (exports_1, context_1) {
/** ... */
})
```

```js
// g:/cim-shared-ui/helpers.js
System.register(["bluebird", "cim-typings", "capture-stack-trace", "moment", "lodash"], function (exports_1, context_1) {
    function requestJson(url, body, method, token) {
      /** ... */
    }
    exports_1("requestJson", requestJson);
    var bluebird_1, cim_typings_1, captureStackTrace, moment_1, lodash_1, RequestError;
    return {
        setters: [
            function (bluebird_1_1) {
                bluebird_1 = bluebird_1_1;
            },
            function (cim_typings_1_1) {
                cim_typings_1 = cim_typings_1_1;
            },
            function (captureStackTrace_1) {
                captureStackTrace = captureStackTrace_1;
            },
            function (moment_1_1) {
                moment_1 = moment_1_1;
            },
            function (lodash_1_1) {
                lodash_1 = lodash_1_1;
            }
        ],
        execute: function () {
        }
    };
});
```

```js
// g:/www/index.tsx
import 'cim-shared-ui' 
// this one works, I added a g:/cim-shared-typings/index.js that has:
System.register(["./header", "./helpers", "./logged", "./login", "./modal", "./radiobox", "./search", "./submenu", "./title", "./filter"], function (exports_1, context_1) {
    "use strict";
    var __moduleName = context_1 && context_1.id;
    return {
        setters: [
            function (_1) {
            },
            function (_2) {
            },
            function (_3) {
            },
            function (_4) {
            },
            function (_5) {
            },
            function (_6) {
            },
            function (_7) {
            },
            function (_8) {
            },
            function (_9) {
            },
            function (_10) {
            }
        ],
        execute: function () {
        }
    };
});
```

when doing `import 'cim-shared-ui'`, it loads the `node_modules/cim-shared-ui/*.js` correctly

**Comment by pocesar** [comment]
the output from typescript is inconsistent @guybedford the way it generates using outDir (that I'm using for creating a vendor bundle) is inconsistent with outFile.

instead of `cim-shared-ui/helpers`, it's outputting `../../cim-shared-ui/helpers` and SystemJs isn't being able to find the package, since I'm defining it as above. is there a workaround that I could use while the TS team doesn't fix this inconsistency?

**Comment by aluanhaddad** [comment]
If you are using `tsc --outFile dist/app.js` then TypeScript is generating the named register bundle, not jspm. This is consistent with your package configuration.

**Comment by pocesar** [comment]
@aluanhaddad it isn't, it doesn't happen with another linked dependency

**Comment by aluanhaddad** [comment]
This looks like a bug in TypeScript they have added the `[needs investigation]` label to your issue. I do recommend using JSPM to generate your bundles as it allows for greater flexibility, but that is a separate issue.
