### ISSUE TITLE
Is there an api for getting the dependency tree?

### ISSUE THREAD

**Issue by togakangaroo** [jspm/jspm-cli#2279]
I'm interested in walking my dependency tree and generating a bunch of `<link rel="preload">` statements from these. Is there an api by which I can get the full list of urls from jspm? I'm aware of `depcache` but [it has been buggy for me](https://github.com/jspm/jspm-cli/issues/2146) and upon discussion with some people in gitter, that functionality is apparently not a priority.

**Comment by guybedford** [comment]
SystemJS builder can be used to extract dependency trees through its trace records. This is available at the `builder.trace('module')` method. The code to work with traces for depCache is at https://github.com/systemjs/builder/blob/master/lib/builder.js#L832, which may help constructing your own solution.

Note that in jspm 0.17, depCache does just use preload now so should be much more stable.
