### ISSUE TITLE
bundle-sfx init-app dist/bundle.js fails silently

### ISSUE THREAD

**Issue by ardi-n** [jspm/jspm-cli#2282]
Hello,

I use v0.16.53. It's installed on a Vagrant instance. I use Babel transpiler. When I run the simple command mentioned in the title and my code contains some error like a semicolon before a dot this command fails silently. 

It's really weird because some time ago when I had jspm installed on my host machine it outputted all errors before exiting. 

I dug into the source code and found that when I change rejected promise handling at https://github.com/jspm/jspm-cli/blob/0.16.53/cli.js#L494
to
```
.catch(function(e) {
  console.log(e);
  process.exit(1);
})
```
then I get all errors thrown.
I followed into lib/ui.js to find that errors should be outputted on exit: https://github.com/jspm/jspm-cli/blob/0.16.53/lib/ui.js#L35
I did `console.log(apiResolver)` and it turns out `apiResolver` is an instance of EventEmitter. 

Is it correct it's actually defined for the cli? 
I think this prevents buffered messages from being logged. 
What can be wrong here?

**Comment by guybedford** [comment]
The API resolver is enabled if you require from the `api.js` file. Perhaps there's something in your app that is using this?
