### ISSUE TITLE
Error on download for github:systemjs/systemjs when running `jspm init`

### ISSUE THREAD

**Issue by dmitriz** [jspm/jspm-cli#2284]
```sh
$ jspm init
Would you like jspm to prefix the jspm package.json properties under jspm? [yes]:
Enter server baseURL (public folder path) [./]:
Enter jspm packages folder [./jspm_packages]:
Enter config file path [./config.js]:
Configuration file config.js doesn't exist, create it? [yes]:
Enter client baseURL (public folder URL) [/]:
Do you wish to use a transpiler? [yes]:
Which ES6 transpiler would you like to use, Babel, TypeScript or Traceur? [babel]:
ok   Verified package.json at package.json
     Verified config file at config.js
     Looking up loader files...

warn Error on download for github:systemjs/systemjs
     Unauthorized response for GitHub API.
     Use jspm registry config github to reconfigure the credentials, or update them in your ~/.netrc file.

err  

err  Error downloading loader files.

err  
```

**Comment by SerkanSipahi** [comment]
@dmitriz As the error already says "Unauthorized response for GitHub API." You can solve it by 'reconfigure the credentials, or update them in your ~/.netrc file'

**Comment by dmitriz** [comment]
@SerkanSipahi 
You are right, sorry :)
But is there any reason to require my Github credentials here?

Also in some directories it seems to insist on having it local:
```sh
jspm
-bash: ./node_modules/.bin/jspm: No such file or directory
```
where I really want to run the global one...

**Comment by aluanhaddad** [comment]
@dmitriz 
> But is there any reason to require my Github credentials here?

This is necessary because jspm can install many packages directly from GitHub. These include dependencies of jspm itself, as well as common packages such as bootstrap.




> Also in some directories it seems to insist on having it local:
> where I really want to run the global one...

Interesting, while you should always use a locally installed version, it is not required. Which version are you using?

**Comment by SerkanSipahi** [comment]
> This is necessary because jspm can install many packages directly from GitHub. These include dependencies of jspm itself, as well as common packages such as bootstrap.

... @dmitriz and they (github) can block your request while install directly from GitHub "MANY" packages !

**Comment by dmitriz** [comment]
@aluanhaddad 

>>But is there any reason to require my Github credentials here?

>This is necessary because jspm can install many packages directly from GitHub. These include dependencies of jspm itself, as well as common packages such as bootstrap.

It feels a bit strange that installation of open source packages requires 
permission of a private company that can be potentially taken away any time.
You don't need permission to clone Github repos or install from `npm`.
Any reason none of these free channels cannot be used? 

>>Also in some directories it seems to insist on having it local:
where I really want to run the global one...

>Interesting, while you should always use a locally installed version, it is not required. Which version are you using?

So I did update the version and that error was gone, there was this strange message though
and the installation looked massive:

```sh
warning Unmet peer dependency "react@16.0.0-alpha.6".
```

Is React-alpha really a peer dependency?

**Comment by SerkanSipahi** [comment]
> It feels a bit strange that installation of open source packages requires
permission of a private company that can be potentially taken away any time.

Github requires (Github credentials, token, etc) that ! As i told: `and they (github) can block your requests while installing "MANY" packages if you not set your "Github credentials"!`

> So I did update the version and that error was gone, there was this strange message though
and the installation looked massive:

Sometimes you get an warning ! Please rerun `jspm install`
