### ISSUE TITLE
Question: jspm registries not being found within CI?

### ISSUE THREAD

**Issue by buddyp450** [jspm/jspm-cli#2286]
Thought I'd ask here as well... as standard practice, should I have a bamboo task that adds the jspm registry or should the jspm invocation properly pull from my local machine's .jspm/config registry from the local appdata?

http://stackoverflow.com/questions/43725545/how-to-enable-custom-bitbucket-jspm-registry-entry-inside-a-bamboo-task

**Comment by SerkanSipahi** [comment]
@buddyp450 
1.) what is a bamboo task? 
2.) you can use this command for setting up for own registries:
```bash
jspm registry <command>          Manage registries
  registry config <name>         Configure an existing registry
  registry create <name> <pkg>   Create a new custom registry instance
```
see:
```bash
jspm --help
```
