### ISSUE TITLE
Add a verbosity flag

### ISSUE THREAD

**Issue by JoakimSoderberg** [jspm/jspm-cli#2288]
As quoted from: https://github.com/jspm/jspm-cli/issues/1827 by 
> On the other hand, jspm doesn't have any sort of verbosity/debug option and it makes jspm impossible to debug. I can't know what credentials of stuff jspm is using.

I completely concur. I was trying to setup credentials according to:

https://github.com/jspm/jspm-cli/blob/master/docs/registries.md#auto-configuring-registries

I set the `JSPM_GITHUB_AUTH_TOKEN` and ran `jspm install` things work. But I have no idea if the token is actually used or not. There is no idication what authentication method is used.

Also it would be nice with a way to test the Github credentials, without installing something. So maybe a command for that?

**Comment by adelespinasse** [comment]
jspm does have a verbosity option (`--log`; see #1082), but it defaults to the most verbose mode. I agree that an even more verbose mode could be useful (in my case for tracing a bug in `jspm build`).

**Comment by ericnewton76** [comment]
I would like jspm to visually progress through the process of tracing through each file and tracing through dependencies.  This would help with when things go wrong because of package upgrade causing an old transient dependency to get removed but is actually still used.
