### ISSUE TITLE
jspm adding .js extension to a jsx file

### ISSUE THREAD

**Issue by jithin1987** [jspm/jspm-cli#2289]
When trying to set entry point a `jsx` file jspm is silently adding a `.js` file extension.

```
Jithins-MacBook-Pro:alertzen-ui-web jithin$ jspm bundle src/client/report.jsx -wid --source-map-contents
     Building the bundle tree for src/client/report.jsx...

err  Error on fetch for alertzen/client/report.jsx.js at file:///Users/jithin/dev/src/client/report.jsx.js
  Error: ENOENT: no such file or directory, open '/Users/jithin/dev/src/client/report.jsx.js'
    at Error (native)

```

Should the entry point be always a `.js` file ?

**Comment by aluanhaddad** [comment]
An entry point can have any extension. If you have `defaultJSExtensions` enabled,  you may disable it at the package level using `defaultExtension: false`. Generally an entry point is specified using a package config's `main` property. At which point you can simply import from the package name itself.

**Comment by jithin1987** [comment]
@aluanhaddad Thanks for clarification. That works.
