### ISSUE TITLE
Question: how to use multiple config  ?

### ISSUE THREAD

**Issue by shaoahs** [jspm/jspm-cli#2294]
current use this style , is this okay?
use automation (use grunt) to change package.js content

mode 1: display console log 
```
  "jspm": {
    "name": "com-slot-test-log"
```
mode 2: remove console log
```
  "jspm": {
    "name": "com-slot-test"
```

jspm.config.js has multiple packages name
```
  packages: {
    "com-slot-test-log": {
      "main": "src/slot/test/main.js",
      "format": "es6",
      "meta": {
        "*.js": {
          "loader": "plugin-babel",
          "babelOptions": {
            "plugins": [
              "babel-plugin-transform-minify-booleans",
              "babel-plugin-transform-merge-sibling-variables"
            ]
          }
        }
      }
    },
    "com-slot-test": {
      "main": "src/slot/test/main.js",
      "format": "es6",
      "meta": {
        "*.js": {
          "loader": "plugin-babel",
          "babelOptions": {
            "plugins": [
              "babel-plugin-transform-remove-debugger",
              "babel-plugin-transform-remove-console",
              "babel-plugin-transform-minify-booleans",
              "babel-plugin-transform-merge-sibling-variables"
            ]
          }
        }
      }
    }
  }
```

**Comment by aluanhaddad** [comment]
> current use this style , is this okay?
> use automation (use grunt) to change package.js content

Do you mean _package.json_? It is fine to programmatically change package.json but there are risks as a large number of tools write this file; npm, jspm, cordova, etc.; and even more read it.

It is absolutely fine to have multiple packages in your `jspm.config.js` (or `config.js`) file. It is very useful. Even on small projects I will usually have something like
```js
packages: {
  app: {
    main: "main.js"
  },
  test: {
    main: "all.js"
  }
}
```
If you simply need to switch between package entry points, you can create an alias under map config such as
```js
packages: {
  app: {
    main: "main.js"
  },
  test: {
    main: "all.js"
  },
  map: {
    "entry-point": "test",
    ...
  }
}
```

**Comment by shaoahs** [comment]
yes ! thanks !
