### ISSUE TITLE
defaultJSExtensions seems to conflict with some plugins

### ISSUE THREAD

**Issue by danwellman** [jspm/jspm-cli#2296]
JSPM sets defaultJSExtensions to true when it creates the config.js file. This causes all files that are loaded to have a `.js` extension appended to the filenames of all files loaded by SystemJS.

I see that in some configurations you can set `defaultExtension: false` in the `meta` config, but this does not work with some other plugins, such as the https://github.com/dougludlow/plugin-sass plugin. Even using `defaultExtension: false` does not help, and scss files are tried to be loaded as `.scss.js`

Is this an issue with JSPM, or an issue with the individual plugin not supporting `defaultExtension` ?

**Comment by aluanhaddad** [comment]
This is fully supported. What I would recommend is setting `defaultJSExtensions: false` at top level, and then specifying a `defaultExtension` property for individual `packages` as needed (generally unnecessary for third-party packages installed via `jspm install x`
Here is an example
```js
SystemJS.config({
  defaultExtension: false,
  transpiler: "babel",
  packages: {
    app: {
      defaultExtension: "js", // optional
      main: "main.js"
    },
    meta: {
      "*.scss": {
        loader: "sass"
      },
      "*.sass" : {
        loader: "sass"
      }
    }
  }
});
```

**Comment by danwellman** [comment]
As soon as I change `defaultJSExtensions` to `false`, I then get this error:

>GET http://localhost:57761/jspm_packages/npm/babel-core@5.8.38/ 403 (Forbidden)

I've added the exact config that you've shown above, but the config.js file also contains a whole bunch of additional stuff that JSPM added after running `jspm init` and installing the sass plugin. I don't have any other JSPM plugins, or any libraries installed.

The sass plugin also doesn't seem to work, it can load the .scss file (after I added a mime-type for it to IIS), but it can't seem to parse it and I see:

> Uncaught (in promise) Error: (SystemJS) Unexpected token {

But I guess that's an issue for the sass plugin repo.

**Comment by aluanhaddad** [comment]
It is trying to import the directory instead of the correspondingly named .js file.

**Comment by danwellman** [comment]
Great, I added .js to the path for that file in the `map` configuration, and it started working.

What do you think about adding a question to the init app that asks if you want to enable `defaultJSExtensions` and adds the extension to the configuration for you if you choose no? The `map` configuration is entirely auto-generated at this point (along with almost the rest of the config.js file), and it's kinda weird and confusing to have to go and edit generated code to get things working.

But thanks for the help, much appreciated 👍

**Comment by danwellman** [comment]
Actually, as I am trying to get the sass-plugin working, I'm having to go through and add a .js extension to many paths in the `map` configuration. It's not entirely useful to have to do this manually ;)

**Comment by aluanhaddad** [comment]
Yeah, with jspm@beta this is not an issue so I would be hesitant to add a feature for this. I would suggest you move to the latest beta if possible. It is quite stable and offers new features like development bundling and `jspm run` which can be used to execute modules under node but with proper `System.register` semantics (especially useful for running unit tests).

I realize you may not be able to do that and I will look into an alternative solution.

**Comment by danwellman** [comment]
Using the beta is fine, it's working as expected. Any idea when it will become release?
