### ISSUE TITLE
Suggestion: add an issue_template

### ISSUE THREAD

**Issue by aluanhaddad** [jspm/jspm-cli#2297]
Perhaps it would be a good idea to create an issue template to assist in troubleshooting.

I was thinking of something very simple such as the following.
```markdown
<!-- Please fill in this template if applicable -->
**JSPM Version:** ($ jspm --version) ex: 0.X.XX or 0.X.0-beta.xx

**Transpiler:** babel/traceur/typescript/I do not use a transpiler
```

**Comment by guybedford** [comment]
@aluanhaddad would you be interested in putting this together? I've added you to the admin team so please feel free to go ahead.

**Comment by aluanhaddad** [comment]
Yes I absolutely would. Sorry for taking so long to respond I've been extremely busy.
