### ISSUE TITLE
jspm 0.17 beta 41 bundle error "Cannot find module 'process'"

### ISSUE THREAD

**Issue by far-blue** [jspm/jspm-cli#2299]
I've tried using jspm 0.17 beta 41 by doing a clean npm install then a jsbp init with all the defaults. I created 2 js files within a javascript/app/ folder where a 'main.js' ES6 module loads a 'mod1.js'. There are no other packages involved. full dev mode with babel in the browser works fine but 'bundle' fails.

I'm using this command:
> jspm bundle javascript/app/main.js javascript/dist/main.js 

I get the following error (absolute paths replaced with ...):

>      Building the bundle tree for javascript/app/main.js...
>
> err  Error on translate for javascript/app/main.js at file:///.../javascript/app/main.js
>  (SystemJS) Cannot find module 'process'
>  Error: Cannot find module 'process'
>      at Function.Module._resolveFilename (module.js:338:15)
>      at Function.Module._load (module.js:280:25)
>      at Module.require (module.js:364:17)
>      at require (module.js:380:17)
>      at n ([object Object]:1:577)
>      at d ([object Object]:1:888)
>      at d ([object Object]:1:934)
>       at d ([object Object]:1:934)
>       at d ([object Object]:1:934)
>       at d ([object Object]:1:934)
>       at d ([object Object]:1:934)
>       at d ([object Object]:1:934)
>       at d ([object Object]:1:934)
>       at d ([object Object]:1:934)
>       at d ([object Object]:1:934)
>       at d ([object Object]:1:934)
>   Evaluating /.../jspm_packages/npm/systemjs-plugin-babel@0.0.21/plugin-babel.js
>   Error loading /.../jspm_packages/npm/systemjs-plugin-babel@0.0.21/plugin-babel.js
>   Unable to load transpiler to transpile /.../javascript/app/main.js

**Comment by subhaze** [comment]
It appears that the systemjs-plugin-babel wasn't installed? I just started a small project based on the two files and using all the defaults for `jspm init` and things worked fine, bundled up with no errors with the command you used above.

Potentially a network error occurred when the init was running where systemjs-plugin-babel wasn't installed successfully? I've ran into that before, a drop in my connection while installing, so not all deps were installed.
