### ISSUE TITLE
jspm.browser.js in 0.17 beta what's that?

### ISSUE THREAD

**Issue by ajimix** [jspm/jspm-cli#2301]
In the documentation of jspm 0.17 in some pages [like this one](http://jspm.io/0.17-beta-guide/bundling.html) there is a mention of jspm.browser.js file but that file doesn't appear anywhere else.

Is that file the same as jspm.config.js and the guide is wrong? Or is it a different file?

If that's the case, where can I find the documentation for that file?

Thanks

**Comment by subhaze** [comment]
more info on it here https://github.com/jspm/jspm-cli/issues/1499

**Comment by ajimix** [comment]
Ok, thanks. It's a bit hard as there is not much documentation about it but thanks :)
