### ISSUE TITLE
beta 41 package.json "meta" config seems not supporting "scriptLoad": true for external source

### ISSUE THREAD

**Issue by Tundon** [jspm/jspm-cli#2304]
Hi everyone,

I came across this problem when trying to solve the CORS issue when loading from external source. (see issue from systemjs https://github.com/systemjs/systemjs/issues/225)

The idea is that when I write a library that depends on external source, I don't want the users of my library to worry about that external source. So what I am trying to do, is to add a meta config in my package.json file, as following:
```
  "jspm": {
    "name": "library",
    "main": "library.js",
    "directories": {
      "lib": "src"
    },
    "devDependencies": {
      "plugin-babel": "npm:systemjs-plugin-babel@^0.0.21"
    },
    "map": {
      "wx-login/main.js": "https://res.wx.qq.com/connect/zh_CN/htmledition/js/wxLogin.js"
    },
    "meta": {
      "wx-login/main.js": {
        "scriptLoad": true,
        "format": "global",
        "exports": "WxLogin"
      }
    }
  }
```
That `wx-login/main.js` is an external my library depends on. 

And in the client app project, when install the library (I did `jspm link` for sample project), it seems that meta config is picked up, the `library@1.0.0.json` file under `jspm_packages/local` is:
```
{
  "main": "library.js",
  "map": {
    "wx-login/main.js": "https://res.wx.qq.com/connect/zh_CN/htmledition/js/wxLogin.js"
  },
  "meta": {
    "wx-login/main.js": {
      "scriptLoad": true,
      "format": "global",
      "exports": "WxLogin"
    }
  }
}
```
However, when running the app project in the browser, it complains:
```
Fetch API cannot load https://res.wx.qq.com/connect/zh_CN/htmledition/js/wxLogin.js. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
common.js:85 Uncaught (in promise) Error: Failed to fetch
  Instantiating https://res.wx.qq.com/connect/zh_CN/htmledition/js/wxLogin.js
  Loading http://localhost:8080/jspm_packages/local/library@1.0.0/library.js
  Loading http://localhost:8080/src/app.js
  Loading app
```
I also tested the library project on its own, by adding the config in `jspm.config.js`:
```
  ...
  map: {
    "wx-login/main.js": "https://res.wx.qq.com/connect/zh_CN/htmledition/js/wxLogin.js"
  },
  meta: {
    "wx-login/main.js": {
      "scriptLoad": true,
      "format": "global",
      "exports": "WxLogin"
    }
  }
```
This seems working fine.

So I don't know if it is the way I'm configuring the library project is wrong, or when loading library, that config wasn't picked up.

P.S, attached is the zip file containing two projects `library` and `app` for reference. After `npm i` and `jspm i`, you will nee to `jspm link ../library` under `app` root.

[sample-issue.zip](https://github.com/jspm/jspm-cli/files/1050061/sample-issue.zip)

**Comment by guybedford** [comment]
The meta there only applies to `library/wx-login/main.js`. Having an installable package set the meta on another URL isn't possible unfortunately, it may be best just to instruct adding the meta manually.

**Comment by Tundon** [comment]
Got it. I'll close this issue, since doing it manually seems the best choice now.
