### ISSUE TITLE
JSPM Install: Mapping files are intermittantly not created 

### ISSUE THREAD

**Issue by CxRes** [jspm/jspm-cli#2308]
When running JSPM install, I intermittently find that the file that contains mapping to the module's main, that is, of the form `library@version.js` is not created alongside the `library@version` folder. 

I don't know how to recreate the bug, it's a lottery. Even though, I can manually recreate the file, this is a severe problem if someone else has to run `jspm install` and finds that the build fails.

JSPM 0.16.53
NPM 5.0.3
Node 8.1.0
OS Windows 10 x64 (1607 build)

**Comment by SerkanSipahi** [comment]
@CxRes which library you want to install with JSPM? maybe the lib does not contain the main file in there package.json. In this case you should use your own lib configuration with e.g `jspm install bootstrap -o "{ main: 'js/bootstrap' }"`

**Comment by CxRes** [comment]
@SerkanSipahi This is not library specific. I know this because I have been successfully been using the same deps for about a year (I had a problem like that with one lib which did override till it was fixed). What is happening is that when I run `jspm install` at random one or two files of the form are not created. Its strange!!!!

**Comment by SerkanSipahi** [comment]
@CxRes yep, its strange! have you ever tried jspm v0.17.0-beta.42?

**Comment by CxRes** [comment]
@SerkanSipahi I am sticking to 0.16 for now. I have migration planned but unfortunately other things take priority!

**Comment by SerkanSipahi** [comment]
@CxRes i remember, at work, we have a similar/something like that, but not the same problem with jspm! In our build process we run `jspm install` 2 times. Maybe this can help, i mean it reduce the randomality!

**Comment by CxRes** [comment]
@SerkanSipahi That is exactly what I had done last evening :-)
