### ISSUE TITLE
How to NOT install devDependencies? jspm update --nodev?

### ISSUE THREAD

**Issue by mreiche** [jspm/jspm-cli#2309]
In reference to https://github.com/jspm/jspm-cli/issues/1053

I have the following ``package.json``

```{
  "jspm": {
    "directories": {
      "packages": "3rdParty/jspm_packages"
    },
    "configFile": "3rdParty/jspm_packages/config.js",
    "dependencies": {
      "froala-editor": "npm:froala-editor@^2.5",
      "jquery": "npm:jquery@^3.2.1"
    },
    "devDependencies": {
      "babel": "npm:babel-core@^5.8.24",
      "babel-runtime": "npm:babel-runtime@^5.8.24",
      "core-js": "npm:core-js@^1.1.4",
      "aurelia-animator-css": "npm:aurelia-animator-css@^1.0.1",
     }
}
```

Im using JSPM for frontend and backend development. I dont need the devDepencies for running in frontend mode but when I run ``jspm update``, JSPM installes ALL dependencies, including ``--dev``

```
web1@dev2:/var/www/web$ rm -r 3rdParty/jspm_packages/
web1@dev2:/var/www/web$ jspm update

warn Running jspm globally, it is advisable to locally install jspm via npm install jspm --save-dev.
     Looking up npm:aurelia-animator-css
     Looking up npm:babel-core
     Looking up npm:babel-runtime
     Looking up npm:core-js
     Looking up npm:froala-editor
     Looking up npm:jquery
```

**Comment by SerkanSipahi** [comment]
@matoilic do you have any concerns when devDependencies are installing on frontend?

**Comment by mreiche** [comment]
Please take a look on package.json
```
 "dependencies": {
      "froala-editor": "npm:froala-editor@^2.5",
      "jquery": "npm:jquery@^2"
    },
    "devDependencies": {
      "aurelia-animator-css": "npm:aurelia-animator-css@^1.0.1",
      "aurelia-binding": "npm:aurelia-binding@^1.2.1",
      "aurelia-bootstrapper": "npm:aurelia-bootstrapper@^1.0.0-rc.1.0.0",
      "aurelia-breeze": "npm:aurelia-breeze@^2.2.0",
      "aurelia-cookies": "npm:aurelia-cookies@^1.0.0",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@^1.0.0",
      "aurelia-event-aggregator": "npm:aurelia-event-aggregator@^1.0.0-rc.1.0.0",
      "aurelia-fetch-client": "npm:aurelia-fetch-client@^1.0.0-rc.1.0.0",
      "aurelia-framework": "npm:aurelia-framework@^1.1.1",
      "aurelia-history": "npm:aurelia-history@^1.0.0",
      "aurelia-history-browser": "npm:aurelia-history-browser@^1.0.0",
      "aurelia-i18n": "npm:aurelia-i18n@^1.3.2",
      "aurelia-loader": "npm:aurelia-loader@^1.0.0",
      "aurelia-loader-default": "npm:aurelia-loader-default@^1.0.0",
      "aurelia-logging-console": "npm:aurelia-logging-console@^1.0.0",
      "aurelia-materialize-bridge": "npm:aurelia-materialize-bridge@^0.25.0",
      "aurelia-pal-browser": "npm:aurelia-pal-browser@^1.2.0",
      "aurelia-path": "npm:aurelia-path@^1.1.1",
      "aurelia-polyfills": "npm:aurelia-polyfills@^1.0.0-rc.1.0.0",
      "aurelia-router": "npm:aurelia-router@^1.0.2",
      "aurelia-templating": "npm:aurelia-templating@^1.3.0",
      "aurelia-templating-binding": "npm:aurelia-templating-binding@^1.0.0",
      "aurelia-templating-resources": "npm:aurelia-templating-resources@^1.2.0",
      "aurelia-templating-router": "npm:aurelia-templating-router@^1.0.0",
      "aurelia-validation": "npm:aurelia-validation@^1.0.0",
      "babel": "npm:babel-core@^5.8.24",
      "babel-runtime": "npm:babel-runtime@^5.8.24",
      "breeze": "npm:breeze-client@^1.6.3",
      "core-js": "npm:core-js@^1.1.4",
      "fetch": "github:github/fetch@^2.0.2",
      "i18next-xhr-backend": "npm:i18next-xhr-backend@^0.6.0",
      "materialize-css": "npm:materialize-css@^0.98.1",
      "moment": "npm:moment@^2.18.1",
      "text": "github:systemjs/plugin-text@^0.0.9",
      "url-parse": "npm:url-parse@^1.1.8"
    }
```

Im bundling everything with "Aurelia" and "Material" into two separated optimized bundles. jQuery and Froala are just frontend components the application loads on demand.

The jspm_packages (including devDependencies) directory is about ~70 MiB. This is larger than the whole application.

For comparison: 
Composer vendor: ~27 MiB
The Application itself: ~31 Mib
bower_components: ~4,6 MiB

**Comment by SerkanSipahi** [comment]
>Composer vendor

its php! Does not matter in frontend

>The jspm_packages (including devDependencies) directory is about ~70 MiB. This is larger than the whole application.

jspm_packages its just a directory and as long as it is not used in frontend it will never part of your frontend bundle. So you do not need to worry

>I'm planning to replace Bower by JSPM for frontend development.

with bower you cant build a optimized bundle.

**Comment by mreiche** [comment]
> jspm_packages its just a directory and as long as it is not used in frontend (devDependencies) it will never part of your frontend bundle. So you do not need to worry

The point is, the application installes packages worth twice the size of the whole productive application for NOTHING. Wasting storage and network capacity. This is not an issue for single installations but becomes a topic when updating many nodes. Nothing to say about the error-proness for each node when one ore more CDN's are not responding fast enough.

> with bower you cant build a optimized bundle.

Thats why im planning to replace it.

> its php! Does not matter in frontend

In difference to JSPM, composer supports ``composer update --no-dev``, which only installes the productive versions of any library, excluding tests and examples.

**Comment by mreiche** [comment]
I see that JSPM 0.17 differs between ``jspm.config.js`` and ``jspm.dev.js``. Where can I found documentation for that?

**Comment by mreiche** [comment]
I fixed that by regenerating my "package.json" by a custom command.
``php cli.php jspm:update --dev`` generates a new package.json including all ``devDependencies`` of JSPM and NPM. Without, I generates a *clean* package.json which includes only ``dependencies``.

**Comment by aluanhaddad** [comment]
It sounds like you installed one of the Aurelia packages as a dev dependency witch cause its dependency to intern be installed as dev dependencies. As noted, it doesn't matter that much but when I install Aurelia packages they default to standard dependencies on 0.16.x and peer dependencies on 0.17.0-beta

**Comment by mreiche** [comment]
Sorry, but it DOES matter. I install Aurelia as DEV dependency, because the whole Aurelia frameworks is only required in DEV environments where I use Browser-Sync.

Before releasing to PROD, Aurelia and ALL that static stuff is going to be bundled into several large optimized bundles. The PROD environment DOES NOT require dev dependencies to be installed anymore, because everything of interest is already included in the bundles.

Therefore I do not need to install DEV dependencies in PROD environment. It makes absolutely no sense to me to have devDependencies to be defined without the possibility to exclude these when updating JSPM.

**Comment by dhilgarth** [comment]
This is *not* a non-issue.

I am trying to install an old version of  @progress/kendo-angular-dateinputs, namely v2.0.0

For whatever reason, jspm is trying to pull in all dev dependencies in *their latest versions*! And this fails.
