### ISSUE TITLE
How to update SystemJS?

### ISSUE THREAD

**Issue by mreiche** [jspm/jspm-cli#2310]
JSPM installes SystemJS 0.19.41 on setup.

``less jspm_packages/system.js``

```
/*
 * SystemJS v0.19.41
 */
!function(){function e(){!function(e){f
```

But I require SystemJS 0.2, which supports cache busting (https://github.com/systemjs/systemjs/issues/172)

But I have absolutely no idea how to update SystemJS within JSPM without copying the files to the target location manually.

I tried the following:
* ``jspm update systemjs``: Unfortunately this doesn't do it
* Purged ``jspm_packages`` and made a complete reinstall

Questions:
* How does JSPM installes SystemJS?
* Is there an undocument self-update command? ``jspm help``
* How to update SystemJS withing JSPM?

**Comment by SerkanSipahi** [comment]
@mreiche firstly, this issue is false located. This is a jspm repo and not systemjs.

For your question see: https://github.com/systemjs/systemjs/releases/tag/0.20.0 under 
>To upgrade, first run SystemJS 0.19 with System.config({ warnings: true }) and fix all the deprecation
warnings first before running SystemJS 0.20.

**Comment by mreiche** [comment]
IMHO, this question is exactly on the right place. SystemJS is the CORE component of JSPM. I edited my initial question to make clear, what I'm willing to do.

**Comment by SerkanSipahi** [comment]
@mreiche which jspm version do you use?

**Comment by mreiche** [comment]
``jspm -v``

```
0.16.53
Running against global jspm install.
```

Do you think, that updating JSPM helps out?

**Comment by SerkanSipahi** [comment]
>How does JSPM installes SystemJS?

It comes/installed with `jspm init` command.

>Is there an undocument self-update command

no

>How to update SystemJS withing JSPM?

jspm v0.16.x serve sysetmjs 0.19x.
So if you upgrade to the latest 0.17.0-beta.x you will get systemjs v0.20.x

**Comment by mreiche** [comment]
> So if you upgrade to the latest jspm v0.17.0-beta.x you will get systemjs v0.20.x

Do you think it's stable enough for use in development environments?

**Comment by SerkanSipahi** [comment]
@mreiche sure, its stable enough! We've been using (in a large project with over 200 components) it for more than a year.

**Comment by mreiche** [comment]
I remember there were some issues with Aurelia, but they seem to be outdated now.
Im trying the upgraded and getting back to close this issue when done.

**Comment by mreiche** [comment]
I updated to jspm@beta

**Comment by SerkanSipahi** [comment]
@mreiche :)

**Comment by mreiche** [comment]
Not for me, I got bundling and installation errors now and I don't know who and where to address that.

**Comment by SerkanSipahi** [comment]
>To upgrade, first run SystemJS 0.19 with System.config({ warnings: true }) and fix all the deprecation
warnings first before running SystemJS 0.20.

are you follow -> https://github.com/systemjs/systemjs/releases/tag/0.20.0 ?

**Comment by mreiche** [comment]
Yes. My problems are not related to SystemJS.

**Comment by SerkanSipahi** [comment]
show your problems, please

**Comment by mreiche** [comment]
Unable to install aurelia-materialize-bridge https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/issues/438
Unable to bundle aurelia-plugins-cookies https://github.com/aurelia-plugins/aurelia-plugins-cookies/issues/5

**Comment by SerkanSipahi** [comment]
you are right. it does not work. npm: also not work because its not located there according jspm.

try this, works well:
`
jspm install github:aurelia-ui-toolkits/aurelia-materialize-bridge
jspm install github:aurelia-plugins/aurelia-plugins-cookies
`
