### ISSUE TITLE
After updating to beta.42 the new loader won't work

### ISSUE THREAD

**Issue by pocesar** [jspm/jspm-cli#2311]
Updated JSPM to beta.42, but it installed systemJS loader 0.20.14, and now it won't load lodash anymore. it's choking with the error:

![image](https://user-images.githubusercontent.com/461084/27239019-9f423792-52a5-11e7-9472-cf855a3752e1.png)

the code wasn't changed, it just stopped working after the update. had to manually downgrade to 0.20.10, is the latest version that is working for me. If I use 0.20.11 to 0.20.13, I can't import `redux-thunk` (gives me `{ default: ... }` when importing it), and 0.20.14 gives the error above.

**Comment by SerkanSipahi** [comment]
@pocesar `Error: Promise.resolve is not a function` which browser/env do you use? it seems like your browser/env does not support Promise!

**Comment by pocesar** [comment]
doesn't matter, Chrome, Firefox, all give the same error (all the latest btw)

**Comment by SerkanSipahi** [comment]
@pocesar this does not make sense! as I said `Error: Promise.resolve is not a function`. Please share your code as repo, thnx.

**Comment by pocesar** [comment]
it was a lingering `import 'any-promise/register/bluebird'` in legacy code, all good now 👍

**Comment by SerkanSipahi** [comment]
@pocesar nice :)
