### ISSUE TITLE
(SystemJS) Cannot set property 'open' of undefined

### ISSUE THREAD

**Issue by danwellman** [jspm/jspm-cli#2312]
I was using the .41 beta version of JSPM up until today when I did a fresh install of jspm@beta, this has given me version .42.

I have a very simple app which uses jQuery, a jQuery plugin, and a mixture of ES2015, AMD, and CJS modules.

I can view the app in a browser using the jspm-server tool, and the page runs and SystemJS is able to load my modules and everything it needs to, and the app works as expected.

When I try to produce either a bundle or a build using JSPM however, I see errors like this:

> jspm bundle systemjs-project.js bundle.js
     Building the bundle tree for systemjs-project.js...

> err  Error on translate for systemjs-project.js at file:///C:/Users/Dan/systemjs-project/systemjs-project.js
  (SystemJS) Cannot set property 'open' of undefined
  TypeError: Cannot set property 'open' of undefined
      at C:/Users/Dan/systemjs-project/jspm_packages/npm/systemjs-plugin-babel@0.0.23/systemjs-babel-node.js:30442:24
      at a (C:/Users/Dan/systemjs-project/jspm_packages/npm/systemjs-plugin-babel@0.0.23/systemjs-babel-node.js:1:2434)
      at C:/Users/Dan/systemjs-project/jspm_packages/npm/systemjs-plugin-babel@0.0.23/systemjs-babel-node.js:1:1872
      at C:/Users/Dan/systemjs-project/jspm_packages/npm/systemjs-plugin-babel@0.0.23/systemjs-babel-node.js:30611:16
      at a (C:/Users/Dan/systemjs-project/jspm_packages/npm/systemjs-plugin-babel@0.0.23/systemjs-babel-node.js:1:2434)
      at C:/Users/Dan/systemjs-project/jspm_packages/npm/systemjs-plugin-babel@0.0.23/systemjs-babel-node.js:1:1872
      at C:/Users/Dan/systemjs-project/jspm_packages/npm/systemjs-plugin-babel@0.0.23/systemjs-babel-node.js:30709:25
      at a (C:/Users/Dan/systemjs-project/jspm_packages/npm/systemjs-plugin-babel@0.0.23/systemjs-babel-node.js:1:2434)
      at C:/Users/Dan/systemjs-project/jspm_packages/npm/systemjs-plugin-babel@0.0.23/systemjs-babel-node.js:1:1872
      at C:/Users/Dan/systemjs-project/jspm_packages/npm/systemjs-plugin-babel@0.0.23/systemjs-babel-node.js:33551:45
      at a (C:/Users/Dan/systemjs-project/jspm_packages/npm/systemjs-plugin-babel@0.0.23/systemjs-babel-node.js:1:2434)
      at C:/Users/Dan/systemjs-project/jspm_packages/npm/systemjs-plugin-babel@0.0.23/systemjs-babel-node.js:1:1872
      at C:/Users/Dan/systemjs-project/jspm_packages/npm/systemjs-plugin-babel@0.0.23/systemjs-babel-node.js:35294:15
      at a (C:/Users/Dan/systemjs-project/jspm_packages/npm/systemjs-plugin-babel@0.0.23/systemjs-babel-node.js:1:2434)
      at C:/Users/Dan/systemjs-project/jspm_packages/npm/systemjs-plugin-babel@0.0.23/systemjs-babel-node.js:1:1872
      at C:/Users/Dan/systemjs-project/jspm_packages/npm/systemjs-plugin-babel@0.0.23/systemjs-babel-node.js:42755:24
  Evaluating C:/Users/Dan/systemjs-project/jspm_packages/npm/systemjs-plugin-babel@0.0.23/plugin-babel.js
  Error loading C:/Users/Dan/systemjs-project/jspm_packages/npm/systemjs-plugin-babel@0.0.23/plugin-babel.js
  Unable to load transpiler to transpile C:/Users/Dan/systemjs-project/systemjs-project.js

I've tried downgrading back to JSPM beta.41 and running the init command to generate a fresh config, but that does not help either. I notice that plugin-babel has moved from 0.0.21 to 0.0.23 also over the last few days (since I installed beta4.1 like a week or so ago) - I wonder if this is the cause of the issue, as it is plugin-babel that seems to be having the issue?

**Comment by SerkanSipahi** [comment]
@danwellman can you share your project as repo for investigations?

**Comment by danwellman** [comment]
Sure, it's here: https://github.com/danwellman/systemjs-test

Thanks @SerkanSipahi

**Comment by danwellman** [comment]
Any update on this? Is my configuration wrong, or is it a bug?

**Comment by SerkanSipahi** [comment]
sorry i was so busy. I will give feedback :)

**Comment by danwellman** [comment]
Ok great, @SerkanSipahi, thanks. So, it sounds like a configuration issue rather than a bug?
