### ISSUE TITLE
jspm installs corrupt packages from cache subsequent to a corrupt download 

### ISSUE THREAD

**Issue by CxRes** [jspm/jspm-cli#2314]
Say, a JSPM downloaded package is corrupt. This package gets cached. It not only installs the corrupted package on the present install instance but all subsequent installs.

Expected behaviour, imho should be that jspm first checks the hash for the cached package, assuming an internet connection is available, only then proceed to install the package from cache (hash checking should be default as errors are bound to occur while downloading every now and then). Certainly, this hash information is available for npm packages at least (such as with package `npm:assert` which originally led me to discover this problem).

Using JSPM 0.16.53
Windows 10 x64 (1607 build)

**Comment by guybedford** [comment]
FWIW this is the behaviour in jspm 2.0.
