### ISSUE TITLE
Watch multiple bundles

### ISSUE THREAD

**Issue by ArmorDarks** [jspm/jspm-cli#2317]
Hi

Is there any way to watch multiple bundles on JSPM 0.17 with

```shell
jspm build from.js bundle.js -wid
```

command?

To be more specific, image you have two completely standalone filesets, which used on different pages:

```
scriptsDirectory
|-bundle-1-index.js
|  |- a1.js
|  |- b1.js
|
|
|-bundle-2-index.js
|  |- a2.js
|  |- b2.js
| 
..
```

`bundle-1-index.js` built into `bundle-1.js` file, and `bundle-2-index.js` built into `bundle-2.js` files repsectively.

This can be easily achieved for bundling itself, by running two commands in row:

```shell
jspm build bundle-1-index.js bundle-1.js && jspm bundle-2-index.js bundle-2.js
```

Though, even this doesn't seem to be entirely correct to me, but, anyways, at least it's possible.

But I wonder, is it possible somehow to run watch for both bundles?

**Comment by ArmorDarks** [comment]
I think that would be possible if we could specify for each package where it have to go in single command.

For instance:

```
jspm build bundle-1-index.js = bundle-1.js, bundle-2-index.js = bundle-2.js -wid
```

Unfortunately, this seems to be complication which solves only issue with watching, since usually you would never need something like that just for building\bundling, because it is easier to call JSPM or builder directly with needed settings for each package. But for watch it won't work that way =\

**Comment by aluanhaddad** [comment]
I definitely think support for this would be really valuable. Currently, setting up multiple watch tasks with injected bundle configs causes concurrency errors so it's not possible to use something like `npm:concurrently` to handle it.

I've found myself wanting this functionality multiple times in the last week.
