### ISSUE TITLE
JSPM does not downgrade dependencies

### ISSUE THREAD

**Issue by CxRes** [jspm/jspm-cli#2321]
If I downgrade a package, its dependencies must be downgraded as well!!!! Right now the dependencies of upgraded packages linger around and are not downgraded.

**Comment by aluanhaddad** [comment]
Are you saying that the downgraded packages still depend on newer versions of their dependencies? If so, that's expected if those dependencies are within the allowed semver range of the downgraded dependency.

**Comment by CxRes** [comment]
I don't have an example immediately (been working on things other than code), but afaik lingering sub-deps were outside the semver ranges (in the package.json of downgraded dependencies).

**Comment by aluanhaddad** [comment]
@CxRes thanks for the info.

Just to clarify, do you mean that they are still present on disk or that they are present in `package.json`/`jspm.config.js` or both.

Also, what version of JSPM are you running?

**Comment by CxRes** [comment]
Well, against your advice to me elsewhere I am still on 0.16.53 (cuz I have working demo which I am reluctant to touch).
The subdeps are present on disk (`jspm_packages/`) as well as not removed from `config.js` when they use exact version numbers ie no `~` or `^`.
