### ISSUE TITLE
standard typescript setup doesn't check types

### ISSUE THREAD

**Issue by m0ru** [jspm/jspm-cli#2323]
Just set up a fresh project using jspm 0.17.0-beta.42, picking typescript as compiler in the quick init (to check whether the problems are with the pre-existing setup of a larger project i'm migrating to typescript)

```javascript
function foo(x : string) { console.log(x); }
foo(1);
```
compiles when bundled with `./node_modules/.bin/jspm bundle src/app.ts --inject`

* [package.json](https://gist.github.com/m0ru/de75c9cc97d31ba6cb49f46ced7e8d9b)
* [jspm.config.js](https://gist.github.com/m0ru/19b58993ffd5a19e82fa5899234bb677)
* generated [build.js](https://gist.github.com/m0ru/e64bc9c396238cc6c1fcf4c49446ff8f)

Dunno where in the tool-chain this fails, as i'm not too familiar with jspm's internals ^^"

**Comment by m0ru** [comment]
I assume my current workaround will be something [along these lines](https://stackoverflow.com/questions/34614743/how-to-prepare-release-version-with-systemjs-and-gulp) (i.e. doing a first compilation stage using `ts` and then bundling and minifying via `jspm`)

**Comment by guybedford** [comment]
@m0ru perhaps you'll find a project like https://github.com/fabiandev/jspm-tsc-update useful here?

**Comment by aluanhaddad** [comment]
@m0ru I recommend typechecking via a separate process while still letting JSPM process your source code directly.

Something that works fairly well from the command line is installing the concurrently package for NodeJS (there may be better options but I am not up on them) 
```bash
$ npm install --global concurrently
```
and running
```bash
$ concurrently "jspm bundle app -wid" "tsc --noemit -w -p tsconfig.json"
```
