### ISSUE TITLE
how to debug slowness in bundle?

### ISSUE THREAD

**Issue by pocesar** [jspm/jspm-cli#2324]
I'm doing a simple bundle and it's taking 6 minutes to complete, is there anyway to trace down what is making it so slow? I suspect it's a wasm file that is 1,8MB (and I'm running bundle with --minify)

**Comment by aluanhaddad** [comment]
You can use the builder programmatically from Node and debug it that way.

I suggest removing or excluding dependencies from the bundle.
You might use
```
jspm bundle wasmfile --minify
```

You can also specifically create a bundle that contains the wasm file.

**Comment by aluanhaddad** [comment]
Something I've been doing lately during development is building three bundles like
```bash
$ jspm bundle -id plugin-typescript plugin-babel plugin-sass build.transpilers.js

$ jspm bundle -id app/** - [app/**] build.dependencies.js

$ jspm bundle -wid app/** build.app.js
```
The last bundle is watched (`-w`) and rebuilds are extremely fast (under 1 second). I am running Windows 10 x64 with the experimental Watchman for windows binary and my rig is quite fast overall but only supports SATA II (3Gb/s) so my SSD bottle-necked and it would likely be even faster.
