### ISSUE TITLE
jspm install should look for locally linked modules first

### ISSUE THREAD

**Issue by CxRes** [jspm/jspm-cli#2325]
Currently running `jspm install` causes jspm to search for the repo online even though I have it locally linked for the purpose of development. Perhaps there may be merit in this (though I fail to see one), but it is certainly inconsistent with npm.

This becomes even more problematic if I did have the repo online and then it would install the online version instead of the local linked version.

**Comment by guybedford** [comment]
I'm working on getting the offline workflows going properly for jspm 2 now, so it will happen, just will take a little time.

**Comment by CxRes** [comment]
Should I consider this an **official** jspm 2 announcement???????????????????????????:stuck_out_tongue_winking_eye:
