### ISSUE TITLE
missing items in package.json "dependencies" after many jspm commands

### ISSUE THREAD

**Issue by GongT** [jspm/jspm-cli#2330]
**JSPM Version:** `0.17.0-beta.42`
**Transpiler Plugin(s):** I do not use a transpiler
**Details:**

I found my package.json always wrong after many many commands like install or bundle or ...     
Fastest steps to produce: I test this in a *new* node:alpine docker container
* `npm -g install jspm@beta`
* `mkdir /data` place a `package.json` in it:        
    ```json
    {
         "name": "test",
        "version": "1.0.0",
        "private": true,
        "description": "test jspm package",
        "main": "index.js",
        "license": "WTFPL",
        "jspm": {}
    }
   ```
* `jspm install -y react`
* `cat package.json` ➡️ `"react": "npm:react@^15.6.1"` in dependencies
* `jspm install -y react-dom`
* `cat package.json` ➡️ `"react-dom": "npm:react-dom@^15.6.1"` in dependencies, but `react` disappear
* `jspm uninstall -y react-dom`
* `cat package.json` ➡️ dependencies is `{}`
* `jspm install -y react`
* `cat package.json` ➡️ dependencies is still  `{}` 😱 

This is the simplest case I found, I always got some wrong package.json after many operation.    
now I have only 1 way to fix this: clear `"jspm":` in package.json and install all dependencies again.

I also use a script to parse `package.json`, then create a bundle only my code. (by command like `jspm build index.js - depA -depB`)     
but this wont work because some dependencies installed is missing in `package.json`

**Comment by ArmorDarks** [comment]
This issue is most likely related to #2260 and the way how JSPM deals with dependencies.
