### ISSUE TITLE
fatal error installing package from npm

### ISSUE THREAD

**Issue by selfagency** [jspm/jspm-cli#2331]
**JSPM Version:** 0.17.0-beta.42

**Transpiler Plugin(s):** babel / traceur / typescript / I do not use a transpiler
babel

**Details:**
i get a fatal error attempting to install the [package](https://github.com/metafizzy/flickity/blob/master/package.json) `npm:flickity` due to the heap being 'out of memory.' i have 32GB of ram.

```
$ jspm install npm:flickity                                                                                                                                                                                 1s 52ms
     Updating registry cache...
     Downloading npm:flickity@2.0.9
ok   Installed npm:fizzy-ui-utils@^2.0.0 (2.0.5)
ok   Installed npm:ev-emitter@^1.0.2 (1.1.1)
ok   Installed npm:unidragger@^2.2.3 (2.2.3)
ok   Installed npm:desandro-matches-selector@^2.0.0 (2.0.2)
ok   Installed npm:get-size@^2.0.0 (2.0.2)
ok   Installed npm:tap-listener@^2.0.0 (2.0.0)
ok   Installed peer assert to npm:jspm-nodelibs-assert@^0.2.0 (0.2.1)
ok   Installed npm:unipointer@^2.2.0 (2.2.0)

<--- Last few GCs --->

[2129:0x103801e00]    29874 ms: Mark-sweep 1272.1 (1324.8) -> 1268.2 (1331.8) MB, 2895.4 / 0.0 ms  allocation failure GC in old space requested
[2129:0x103801e00]    32925 ms: Mark-sweep 1268.2 (1331.8) -> 1268.2 (1295.8) MB, 3051.1 / 0.0 ms  last resort
[2129:0x103801e00]    35896 ms: Mark-sweep 1268.2 (1295.8) -> 1268.1 (1295.8) MB, 2971.0 / 0.0 ms  last resort


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x1259a2c1ba79 <JS Object>
    1: DoJoin(aka DoJoin) [native array.js:~96] [pc=0x1c894ffcee53](this=0x1259a2c02241 <undefined>,p=0x27b670d2e4e9 <JS Array[2800293]>,q=2800293,E=0x1259a2c022c1 <true>,A=0x9a71c8932e9 <String[1]\: \n>,z=0x1259a2c022f1 <false>)
    3: Join(aka Join) [native array.js:1] [bytecode=0x9a71c8ca109 offset=86](this=0x1259a2c02241 <undefined>,p=0x27b670d2e4e9 <JS Array[2800293]>,q=2800293,A=0x9a71c89...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 5: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 6: v8::internal::Runtime_StringBuilderJoin(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
 7: 0x1c894f6040bd
 8: 0x1c894ffcee53
fish: 'jspm install npm:flickity' terminated by signal SIGABRT (Abort)
```

**Comment by guybedford** [comment]
Usually this is caused by jspm trying to process too many files in the package. Try installing with some ignore paths provided:

```
jspm install npm:flickity -o ignore=sandbox,test
```

**Comment by selfagency** [comment]
thanks. that worked with a change in syntax:

`jspm install npm:flickity -o "{ignore: ['sandbox','test']}"`

**Comment by aluanhaddad** [comment]
This seems like something that should be checked into jspm/registry as an override.

@selfagency would you be up for creating a pull request?

**Comment by selfagency** [comment]
Sure, I have a bunch of those for different packages actually.

--
Daniel Sieradski
The Self Agency LLC
daniel@self.agency
http://self.agency
o: +1 844.275.6111
m: +1 347.585.0350

On July 22, 2017 at 11:03:23 AM, Aluan Haddad (notifications@github.com) wrote:

This seems like something that should be checked into jspm/registry as an override.

@selfagency would you be up for creating a pull request?

**Comment by selfagency** [comment]
I added another override. Does anyone actually maintain that actively? Because it looks like there are issues and PRs going back quite a while that have gone unaddressed.

**Comment by aluanhaddad** [comment]
@selfagency yes, it is actively maintained. If you look at the PRs and remove the `is:open` filter, you will see that there has been more far more activity than inactivity.

However, as you correctly point out, several open PRs have unaddressed feedback or simply lack a clear path forward.

For example, https://github.com/jspm/registry/pull/938 is over a year old. I was tempted to make the requested changes myself, but perhaps it should simply be closed.
