### ISSUE TITLE
jspm.io down

### ISSUE THREAD

**Issue by donaldev** [jspm/jspm-cli#2332]
**JSPM Version:** 0.16.53

**Transpiler Plugin(s):** babel 

**Details:**
Apologies if this is the wrong place to log this.

The jspm.io site seems to be down and I just wanted to make you aware of it in case you weren't already.
I have tried it on Chrome (+incognito) and IE and the site loads but it is a blank webpage.

Thanks

**Comment by guybedford** [comment]
Thanks, it should be back up now.
