### ISSUE TITLE
Option to disable Watchmen

### ISSUE THREAD

**Issue by ArmorDarks** [jspm/jspm-cli#2334]
**JSPM Version:** `0.17.0-beta-42`

**Transpiler Plugin(s):** babel

**Details:**

We have a bit curious issue with Watchmen.

We do not use Watchmen, but every time we start JSPM with `-wid` option, it launches in watch mode and says:

```
Watchman:  Watchman was not found in PATH.  See https://facebook.github.io/watchman/docs/install.html for installation instructions
Waiting...
```

It seems that it waits for Watchmen for some time. It can be about few minutes, sometimes longer, and watch does not work during that waiting.

Finally, after some time following message appears:

```
     Watching . for changes with Node native watcher...
```

After that watching finally starts to work.

I can't tell is that intentional behavior or a bug. It seems like it would be handy to have ability to disable watchmen waiting altogether for developers, which prefers built-in watcher and quicker start.

**Comment by guybedford** [comment]
This is actually just the delay caused by the node native watcher having to traverse the full tree, rather than the watchman check itself. This slowness is the reason watchman is provided as an alternative.

**Comment by ArmorDarks** [comment]
Ah, I see. It was not clear what actually happened behind the curtains.

I guess, there is no way to make it faster, by ignoring some paths or something?

**Comment by guybedford** [comment]
There isn't currently a feature like this. See https://github.com/jspm/jspm-cli/issues/1999 for past discussion.

**Comment by ArmorDarks** [comment]
I see, thanks. I guess this issue should closed then?
