### ISSUE TITLE
Issue with `babel-plugin-preval`

### ISSUE THREAD

**Issue by ArmorDarks** [jspm/jspm-cli#2335]
**JSPM Version:** `0.17.0-beta-42`

**Transpiler Plugin:** babel

**Details:**

Worth saying at first that I'm not sure is that issue related to [`babel-plugin-preval`](https://github.com/kentcdodds/babel-plugin-preval) or JSPM/SystemJS.

I've installed `babel-plugin-preval`:

```shell
jspm install npm:babel-plugin-preval --dev
```

Added it as babel plugin as `babel-plugin-preval` instruction says:

```json
  packages: {
    "kotsu": {
      "main": "main.js",
      "format": "esm",
      "meta": {
        "*.js": {
          "loader": "plugin-babel",
          "babelOptions": {
            "plugins": [
              "preval"
            ]
          }
        }
      }
    }
  },
```

and tried to build `main.js`:

```js
console.log('hey!')
```

Unfortunately, it resulted in following error:

```
err  Error on translate for kotsu/main.js at file:///J:/Work/Kotsu/github/source/scripts/main.js
  (SystemJS) ENOENT: no such file or directory, open 'J:\Work\Kotsu\github\preval'
  Error: ENOENT: no such file or directory, open 'J:\Work\Kotsu\github\preval'
  Error loading J:/Work/Kotsu/github/preval
```

Well, it seems that JSPM does not resolve properly babel plugin name. I can assume it is because of lack of mapping, so I've added one:

```diff
...
  devConfig: {
    "map": {
      "babel-plugin-preval": "npm:babel-plugin-preval@1.4.2",
+     "preval": "npm:babel-plugin-preval@1.4.2",
    },
...
```

Though fixed, I'm not sure that it's okay...

Alternatively, I could use full plugin name, it seems to work too:

```json
  packages: {
    "kotsu": {
      "main": "main.js",
      "format": "esm",
      "meta": {
        "*.js": {
          "loader": "plugin-babel",
          "babelOptions": {
            "plugins": [
              "babel-plugin-preval"
            ]
          }
        }
      }
    }
  },
```

However, no matter how I do it, it results in another error:

```
err  Error on translate for kotsu/main.js at file:///J:/Work/Kotsu/github/source/scripts/main.js              
  (SystemJS) ENOENT: no such file or directory, open 'J:\Work\Kotsu\github\babel-register'                    
  Error: ENOENT: no such file or directory, open 'J:\Work\Kotsu\github\babel-register'                        
  Error loading J:/Work/Kotsu/github/babel-register as "babel-register" from J:/Work/Kotsu/github/jspm_package
s/npm/babel-plugin-preval@1.4.2/dist/index.js                                                                 
```

Well, it can find `babel-register`, despite docs of preval says that it will use `babel-core` or `babel-register`, and `babel-core` seems to be mapped:

```json
    "packages": {
      ...
      "npm:babel-plugin-preval@1.4.2": {
        "map": {
          "require-from-string": "npm:require-from-string@1.2.1",
          "babylon": "npm:babylon@6.17.4",
          "babel-core": "npm:babel-core@6.25.0"
        }
      },
...
```

I don't know once again is it JSPM or preval issue. It seems to be working for people, but JSPM for some reason fails.

It is fixable by directly installing `babel-register`, though:

```shell
jspm install npm:babel-register --dev
```

Unfortunately it will still result in error, this one:

```
err  Error on translate for kotsu/main.js at file:///J:/Work/Kotsu/github/source/scripts/main.js
  (SystemJS) ENOENT: no such file or directory, open 'J:\Work\Kotsu\github\${path.node.source.value}'
  Error: ENOENT: no such file or directory, open 'J:\Work\Kotsu\github\${path.node.source.value}'
  Error loading J:/Work/Kotsu/github/${path.node.source.value} as "${path.node.source.value}" from J:/Work/Kotsu/github/jspm_packages/npm/babel-plugin-preval@1.4.2/dist/index.js
```

It seems to be comming from [this line](https://github.com/kentcdodds/babel-plugin-preval/blob/master/src/index.js#L84) and related to that templating string which isn't resolved in JSPM.

Once again, I'm confused why it does work in other environments, but doesn't in JSPM.

Would be thankful for any help.

**Comment by guybedford** [comment]
Try following the plugin-babel instructions for configuring plugins rather - https://github.com/systemjs/plugin-babel#custom-presets-and-transforms.

**Comment by ArmorDarks** [comment]
Thanks for reply!

I do follow this guide, everything with accordance to it. Unfortunately, last error seems to be not related to configuration, and issue with `pravel` specified as plugin instead `babel-plugin-preval` not working is just questionable, since it does not work only with JSPM out of box (though, workaraundable), that's why I highlighted it.

**Comment by aluanhaddad** [comment]
With regard to the name of the plugin, installing using an alias is probably the most maintainable work around.

**Comment by ArmorDarks** [comment]
@aluanhaddad  Yeap, that thing is workaraundable, though, it still a bit of mystery to me why babel plugins aliasing works in other environments out of box, but not in JSPM.

Unfortunately, the problem with name isn't real issue, while mentioned last error `(SystemJS) ENOENT: no such file or directory, open 'J:\Work\Kotsu\github\${path.node.source.value}'` is.

@guybedford Can you at least point me, is it SystemJS issue, or `preval` one? From such behavior it is hard to tell.

**Comment by aluanhaddad** [comment]
> though, it still a bit of mystery to me why babel plugins aliasing works in other environments out of box, but not in JSPM.

I agree that it should behave in the standard way. I've been thinking about putting a PR together that fixes this and I don't think it would be too difficult, but the PR would be against the plugin not JSPM.

**Comment by ArmorDarks** [comment]
@ahmedshuhel 

> I agree that it should behave in the standard way. I've been thinking about putting a PR together that fixes this and I don't think it would be too difficult, but the PR would be against the plugin not JSPM.

I see, thanks.

Though, unfortunately, it isn't that important as the fact that prevel doesn't work at all because of template literal in path `${path.node.source.value}`, and I can't figure out should JSPM handle it or not, is it JSPM\SystemJS issue, or prevel's.

**Comment by ArmorDarks** [comment]
For backtracking posted issue in prevel repository too: https://github.com/kentcdodds/babel-plugin-preval/issues/37

**Comment by guybedford** [comment]
Yes unfortunately jspm doesn't offer the ability to handle dynamic resolution. This would be fixed in jspm 2 though.

**Comment by ArmorDarks** [comment]
@guybedford  Ah, great! Thanks for feedback!

**Comment by ArmorDarks** [comment]
@guybedford Still hoped to get it working with JSPM 0.17, so digged a bit.

I've checked `path.node.source.value`, which most likely the source of the issue ([source](https://github.com/kentcdodds/babel-plugin-preval/blob/de16d3802e644e33c1df98d4f7d364b6bda61bb5/src/index.js#L87))

As turned out, the value of `path.node` does not contain `source`, so `path.node.source.value` ends up undefined.

```js
Node {
  type: 'Program',
  start: 0,
  end: 20,
  loc:
   SourceLocation {
     start: Position { line: 1, column: 0 },
     end: Position { line: 2, column: 0 } },
  sourceType: 'module',
  body:
   [ Node {
       type: 'ExpressionStatement',
       start: 0,
       end: 19,
       loc: [Object],
       expression: [Object] } ],
  directives: [] }
```

Is it what you meant under lack of the ability to handle dynamic resolution? That JSPM does not expose source path to babel plugins?
