### ISSUE TITLE
Extracting shared dependencies

### ISSUE THREAD

**Issue by donaldev** [jspm/jspm-cli#2342]
Currently having trouble coming up with a way to extract common dependencies between two or more JavaScript files.
I know that this is very easily done using the '&' operator in SystemJs but I was wondering if there was a way to do it with jspm? - apologies if this is fully supported I just couldn't find it in the documentation.

An example of what I'd be looking to do would be the following : 
` jspm bundle  app/widgets/*.js  & app/pages/*.js app/dist/sharedJS.js --inject`

-sharedJS.js would now have the common JS between the widgets and the pages .

Thank you

**Comment by guybedford** [comment]
Yes that should work. Perhaps try quoting the bundle argument in the command line?

**Comment by donaldev** [comment]
I tried what you were suggesting in a few different ways - still no joy.

Copied from cmd : 

```
C:\PRD_DEV_WORKSPACE\FO\portal-infrastructure\webcontent\js\fdp>jspm bundle src/widgets/**/*.js & src/pages/**/*.js dist/shared.js
     Building the bundle tree for src/widgets/**/*.js...

       npm:jquery@3.2.1.js
       npm:jquery@3.2.1/dist/jquery.js
       npm:lodash@4.17.4.js
       npm:lodash@4.17.4/lodash.js
       src/widgets/com/fineos/refapp/Es6Widget.js

ok   Built into build.js with source maps, unminified.
'src' is not recognized as an internal or external command,
operable program or batch file.

C:\PRD_DEV_WORKSPACE\FO\portal-infrastructure\webcontent\js\fdp>jspm bundle 'src/widgets/**/*.js & src/pages/**/*.js' dist/shared.js
     Building the bundle tree for 'src/widgets/**/*.js...


ok   Built into build.js with source maps, unminified.
'src' is not recognized as an internal or external command,
operable program or batch file.

C:\PRD_DEV_WORKSPACE\FO\portal-infrastructure\webcontent\js\fdp>jspm bundle 'src/widgets/**/*.js' & 'src/pages/**/*.js' dist/shared.js
     Building the bundle tree for 'src/widgets/**/*.js'...


ok   Built into build.js with source maps, unminified.
''src' is not recognized as an internal or external command,
operable program or batch file.

C:\PRD_DEV_WORKSPACE\FO\portal-infrastructure\webcontent\js\fdp>jspm bundle "src/widgets/**/*.js" & "src/pages/**/*.js" dist/shared.js
     Building the bundle tree for src/widgets/**/*.js...

       npm:jquery@3.2.1.js
       npm:jquery@3.2.1/dist/jquery.js
       npm:lodash@4.17.4.js
       npm:lodash@4.17.4/lodash.js
       src/widgets/com/fineos/refapp/Es6Widget.js

ok   Built into build.js with source maps, unminified.
The system cannot find the path specified.
```

**Comment by guybedford** [comment]
`jspm bundle 'src/widgets/**/*.js & src/pages/**/*.js' dist/shared.js` seems like the right track here. Perhaps try with double quotes instead of single quotes or a backslash before the `&` sign? Alternatively perhaps try `^&` in windows as well.

**Comment by donaldev** [comment]
FIXED : 
Needed the double quotes

`jspm bundle "src/widgets/**/*.js ^& src/pages/**/*.js" dist/shared.js`

This is what worked in the end, thank you very much.
