### ISSUE TITLE
Importing "child" module of a package 

### ISSUE THREAD

**Issue by DavidKDeutsch** [jspm/jspm-cli#2343]
**JSPM Version:** 0.16.53

**Transpiler Plugin(s):** I do not use a transpiler

**Details:**
I am brand spanking new to JSPM, SystemJS, and most of the module ecosystem, so apologies if this has nothing to do with JSPM. That being said...

I am attempting to use the @angular/upgrade package to migrate a current TypeScript AngularJS app (which until now has not used any modules at all, just globals) to Angular. I currently transpile the TypeScript myself and have set the module kind to "system". I am not yet doing any bundling with JSPM, nor does SystemJS "know" about any of my code (i.e. it does not know what I plan to load at build time). I have used `JSPM install` to install various packages, such as:

```
@angular/common
@angular/compiler
@angular/upgrade
etc...
```

It all works fine, except for when I try to import `@angular/upgrade/static` (i.e. `System.register(["core-js/client/shim", .. "@angular/upgrade/static"`..), as it tries to retrieve '/jspm_packages/npm/@angular/upgrade@4.3.1/static.js', which does not exist (although a _directory_ named 'static' does). I have temporarily solved the problem by adding the following to my packageConfigPaths: '@angular/upgrade/*/package.json', which seems to allow SystemJS to look into '/jspm_packages/npm/@angular/upgrade@4.3.1/static/package.json' and do its magic (which is pretty cool, BTW).

My question is, is this the right approach, or am I missing something? I never try to import the "parent" module `@angular/upgrade`, which I suspect has something to do with it.

FWIW, here is the JSPM section of my packages.config:

 ```
"jspm": {
    "directories": {
      "baseURL": "jspm",
      "packages": "jspm_packages"
    },
    "configFile": "jspm.config.js",
    "dependencies": {
      "@angular/common": "npm:@angular/common@^4.3.1",
      "@angular/compiler": "npm:@angular/compiler@^4.3.1",
      "@angular/core": "npm:@angular/core@^4.3.1",
      "@angular/platform-browser": "npm:@angular/platform-browser@^4.3.1",
      "@angular/platform-browser-dynamic": "npm:@angular/platform-browser-dynamic@^4.3.1",
      "@angular/upgrade": "npm:@angular/upgrade@^4.3.1",
      "ajv": "npm:ajv@^5.2.2",
      "core-js": "npm:core-js@^2.4.1",
      "rxjs": "npm:rxjs@^5.4.2",
      "systemjs": "npm:systemjs@^0.20.15",
      "zone.js": "npm:zone.js@^0.8.14"
    },
    "devDependencies": {}
  }
```
And here are the relevant sections of the `jspm.config` that JSPM generated:

```
System.config({
  baseURL: "/",
  defaultJSExtensions: true,
  transpiler: false,
  paths: {
    "github:*": "../jspm_packages/github/*",
    "npm:*": "../jspm_packages/npm/*"
  },

  map: {
    "@angular/common": "npm:@angular/common@4.3.1",
    "@angular/compiler": "npm:@angular/compiler@4.3.1",
    "@angular/core": "npm:@angular/core@4.3.1",
    "@angular/platform-browser": "npm:@angular/platform-browser@4.3.1",
    "@angular/platform-browser-dynamic": "npm:@angular/platform-browser-dynamic@4.3.1",
    "@angular/upgrade": "npm:@angular/upgrade@4.3.1",

 "npm:@angular/common@4.3.1": {
      "@angular/core": "npm:@angular/core@4.3.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "tslib": "npm:tslib@1.7.1"
    },
    "npm:@angular/compiler@4.3.1": {
      "@angular/core": "npm:@angular/core@4.3.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "tslib": "npm:tslib@1.7.1"
    },
    "npm:@angular/core@4.3.1": {
      "process": "github:jspm/nodelibs-process@0.1.2",
      "rxjs": "npm:rxjs@5.4.2",
      "tslib": "npm:tslib@1.7.1",
      "zone.js": "npm:zone.js@0.8.14"
    },
    "npm:@angular/platform-browser-dynamic@4.3.1": {
      "@angular/common": "npm:@angular/common@4.3.1",
      "@angular/compiler": "npm:@angular/compiler@4.3.1",
      "@angular/core": "npm:@angular/core@4.3.1",
      "@angular/platform-browser": "npm:@angular/platform-browser@4.3.1",
      "tslib": "npm:tslib@1.7.1"
    },
    "npm:@angular/platform-browser@4.3.1": {
      "@angular/common": "npm:@angular/common@4.3.1",
      "@angular/core": "npm:@angular/core@4.3.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "tslib": "npm:tslib@1.7.1"
    },
    "npm:@angular/upgrade@4.3.1": {
      "@angular/compiler": "npm:@angular/compiler@4.3.1",
      "@angular/core": "npm:@angular/core@4.3.1",
      "@angular/platform-browser": "npm:@angular/platform-browser@4.3.1",
      "@angular/platform-browser-dynamic": "npm:@angular/platform-browser-dynamic@4.3.1",
      "tslib": "npm:tslib@1.7.1"
    }
}
```

I see that the config and package.json do not list `@angular/upgrade/static` as it's own "entity," which I figure must be related. Any help would be appreciated; my fix works fine, but I just get the feeling that I am not doing it the correct way.

**Comment by DavidKDeutsch** [comment]
p.s. - interestingly enough, my "fix" did not work when giving `jspm bundle` a shot; it was again looking for `static.js`. Instead I had to add an explicit entry in the `map` section to `npm:@angular/upgrade@4.3.1/bundles/upgrade-static.umd`.

**Comment by guybedford** [comment]
When jspm installs a package, it doesn't currently support reading nested `package.json` files and having their resolution rules apply. So it sounds like that is the root cause here.

Your fix of adding a custom packageConfigPaths is a good one, a shame it didn't apply to the bundle step.

It may be best to fix this via an override that inlines your custom map:

```
jspm install npm:@angular/upgrade@4.3.1 -o "{map:{'./static':'./bundles/upgrade-static.umd'}}"
```

**Comment by guybedford** [comment]
If that works for you, it would be nice to add to the registry for others to use as well.
