### ISSUE TITLE
Node Conversion and large emscripten JS (sql.js)

### ISSUE THREAD

**Issue by WorldMaker** [jspm/jspm-cli#2345]
**JSPM Version:** 0.16.3

**Transpiler Plugin(s):** typescript

**Details:**

Trying to `jspm install npm:sql.js` fails during node conversion (JS heap out of memory in the middle of traceur). This is likely related to the `js/sql.js` file in the repository is 9MBs in size and presumably a giant thing for traceur to tackle. While I can override and set `jspmNodeConversion` to false (and even shrink the files list to just the most necesary `js/sql.js`), I can't load it at runtime because it is a common JS library that needs some minimal node conversion. Should I pass this over to `jspm/registry` and keep looking for the right combination of overrides and maps/shims or is there some way to get traceur performance down or another option beyond traceur for node conversion?

(Aside: It sounds like JSPM 0.17 has a different approach to this? I'm hesitant to use a tool self-described as "beta" in a project such as this, how is 0.17 progressing and how close to out-of-beta?)

**Comment by guybedford** [comment]
Yeah that's exactly the issue. Unfortunately there's no other way to apply the conversion here.

A shim approach may well work best here, treating it as a global with global deps, so that it is all handled by the runtime, and doesn't need to go through traceur.
