### ISSUE TITLE
Angular 2 - Can we have multiple static html files inside src folder ? i.e other than index.html 

### ISSUE THREAD

**Issue by ManasaSM** [jspm/jspm-cli#2349]
Hi,

I want to have multiple static html pages in my src folder. when i add one static html file and browse i get an white label error.

**Comment by aluanhaddad** [comment]
Can you be more specific? Did you set `<base href="/">`?

**Comment by ManasaSM** [comment]
i added one more file called safe.html in src folder and on APP_INITILIAZER of app.module i call one service if my service is success i will have to navigae to /safe.html..but i cannot do it , it gives me while lable error.

**Comment by aluanhaddad** [comment]
Can you share a repro? That is not much to go on as I cannot see how your routes are structured.

**Comment by ManasaSM** [comment]
Ignore this..

Can you please help me with another issue.

i am using APP_INITILAIZER in my app.module..but it goes into infinite loop..

**Comment by aluanhaddad** [comment]
@ManasaSM `APP_INITIALIZER` is an Angular provider injection token. I don't see how a token would cause an infinite loop but there is no context here to examine. I would need to see the code for `app.module` and the code for the whatever implementation you _providing_.

**Comment by ManasaSM** [comment]
import { BrowserModule } from '@angular/platform-browser';
import { Router, ActivatedRoute } from '@angular/router';
import { NgModule, Injectable, APP_INITIALIZER, Injector } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { ConfigModule, ConfigLoader, ConfigStaticLoader } from 'ng2-config';
import { AccordionModule } from "ng2-accordion";
import { RouterModule } from '@angular/router';

import { AppConfigService } from 'app/services/app-config.service'
import { ExcelService } from './services/ExcelService';

import * as alasql from 'alasql';

import { Http, Response } from '@angular/http';
import { LoginService } from 'app/services/login.service';

import { CommonModuleModule } from './modules/common-module/common-module.module';

import { DashboardModule } from './modules/dashboard/dashboard.module';
import { SearchModule } from './modules/search/search.module';
import { QuotesModule } from './modules/quotes/quotes.module';
import { UsersModule } from './modules/users/users.module';
import { ExceptionsModule } from './modules/exceptions/exceptions.module';
import { InstrumentsModule } from './modules/instruments/instruments.module';
import { AppRoutingModule } from './app-routing-module';
import {PreloginModule} from './modules/prelogin/prelogin.module';
import {SafeModule} from './modules/safe/safe.module'





import { NavigationComponent } from './modules/app-layout/header/navigation/navigation.component';

import { HeaderComponent } from './modules/app-layout/header/header.component';
import { FooterComponent } from './modules/app-layout/footer/footer.component';
import { AppComponent } from './app.component';
import { AllstoreComponent } from 'app/modules/common-module/allstore/allstore.component';
import { AllstoreqpidComponent } from 'app/modules/common-module/allstoreqpid/allstoreqpid.component';
import {PreloginComponent} from 'app/modules/prelogin/prelogin.component';
import {SafeComponent} from 'app/modules/safe/safe.component';



@Injectable()
export class ConfigService {

  public message: string;
private _config: any;


  constructor(private http: Http, private route: ActivatedRoute,
          private router: Router) {
  }

  load(): Promise<boolean> {

    return new Promise<boolean>((resolve) => {
      setTimeout(() => {
//        this.message = "Hello World";
//        console.log('hello world');
//        resolve(true);
//        window.location.href = 'https://www.google.co.in';
          return this.http.get('http://localhost:8080/prelogin')
          .map( (response: Response) => response.json())
          .toPromise()
          .then(data => {
              this._config = data;
              console.log(data);
              window.localStorage['jwttimeout']=data["jwttimeout"];
              window.localStorage['safeurl']=data["safeurl"];
           
              this.router.navigate(['/Prelogin']);
            
              return data;
           })
          
      }, 1000);
    });

  }


}



export function initConfiguration( configService: ConfigService ): Function {

    return () => configService.load();


}

export function configFactory() {


    return new ConfigStaticLoader( 'assets/json-resources/config.json' ); // PATH || API ENDPOINT
}

@NgModule( {
    declarations: [

        NavigationComponent,
        HeaderComponent,
        FooterComponent,
        //BreadcrumbComponent,
        AppComponent,
        AllstoreComponent,
        AllstoreqpidComponent,
     



    ],
    imports: [
        ConfigModule.forRoot( {
            provide: ConfigLoader,
            useFactory: ( configFactory )
        } ),
     
        BrowserModule,
        FormsModule,
        HttpModule,
        AccordionModule,
        // Ng2BreadcrumbModule.forRoot(),

        DashboardModule,
        SearchModule,
        QuotesModule,
        UsersModule,
        ExceptionsModule,
        InstrumentsModule,
        AppRoutingModule,
        PreloginModule,
        SafeModule


    ],
    providers: [
        ConfigService,
        {
            provide: APP_INITIALIZER,
            useFactory: initConfiguration,
            deps: [ConfigService],
            multi: true
        },
        AppConfigService,
        //BreadcrumbService,
        ExcelService, LoginService
    ],
    bootstrap: [AppComponent]
} )
export class AppModule {    
   
}

**Comment by ManasaSM** [comment]
how to access component's html file from spring boot using @RequestMapping?

ex: Say i have a component named Test

i am not able to access it like http://localhost:8080/Test

i can only access index.html ..and further i can access Test component .

@aluanhaddad

**Comment by aluanhaddad** [comment]
I'm sorry I don't know anything about server-side routing using Java and Spring.

Basically you need to configure a rewrite rule that maps a subset of wildcard URL patterns back to your application root.

Then you need to configure the angular router to use push state.

**Comment by aluanhaddad** [comment]
My advice would be to get it working independently of your Spring server, using localhost via something like `lite-server`.

Once you have that working with push state, you can focus your attention on configuring your server to work with single page application push state something for which there is undoubtedly lots of Springs specific documentation.

**Comment by hemminger8** [comment]
I know you said to ignore the first question, but the first question is what I need help with. Can anyone answer if it is possible to have multiple static html files inside src folder?

**Comment by davidrensh** [comment]
Works for me. 
Steps: 1. add static files under assets/static/**.html
Steps: 2. angular-cli.json modify: 

{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "project": {
    "name": "CA5S"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico",
        "**"
      ],
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",

**Comment by aluanhaddad** [comment]
@davidrensh I edited your comment just to format the JSON 
```md
```json
code
```
I appreciate your input but I don't know that the Angular CLI is necessarily relevant here. The Angular CLI wraps Webpack but I don't if and how that static asset configuration is passed to Webpack.

**Comment by bresleveloper** [comment]
1. ng-build with your index.html set properly with its components. (or conditional app-components)
2. rename and copy the rendered to (for example) /src/search.html
3. in angular.json (angular-cli.json for pre v5) find "assets":

```
"assets": [
"src/favicon.ico",
"src/search.html",
"src/assets"
],
```
browse localhost:4200/search.html
enjoy :)

[source](http://bresleveloper.blogspot.com/2018/07/angular-add-more-html-pages.html)

**Comment by siripuramjagadishraj1** [comment]
As a workaround you can have any no of static html files in **assets** folder, 
where u keep images..
