### ISSUE TITLE
Gulp bundling files in a loop

### ISSUE THREAD

**Issue by donaldev** [jspm/jspm-cli#2350]
*JSPM Version:** 0.16.53

**Transpiler Plugin(s):** Babel

**Details:**
I apologize in advance if this is a Gulp issue / my own issue.

I am using gulp to automate my jspm bundling and I am attempting to do it dynamically.

The following set up works well : 
```
var run = require('gulp-run');
var gulp = require('gulp');

//bundle all JS files into one
gulp.task('bundle-single', function () {
 				run('jspm bundle [src/**/*.js] dist/app.js --inject').exec()				
});
```

As expected - all files are bundled into app.js and the config.js is updated accordingly.

The issue I'm having is when I am trying to make a single bundle for each and every JS file in my src folder.
The following example is my attempt at bundling each file inside the "pages" folder : 
```
var path = require('path');
var gulp = require('gulp');
var file = require('gulp-file');
var foreach = require('gulp-foreach');
var file = require('gulp-file');
var run = require('gulp-run');

//single file for every module
gulp.task('bundle-pages', function () {

	//bundle all pages files
	return gulp.src('src/pages/**/*.js')
	.pipe(
			foreach(function(stream,file){
				
				
				
				var filename = path.basename(file.path);
				
				run('jspm bundle [src/pages/com/fineos/refapp/'+filename+'] dist/'+filename+' --inject').exec()
				
				return stream;
			})
	
		)
	});
```
which gives the following output in cmd : 

```
C:\PRD_DEV_WORKSPACE\FO\portal-infrastructure\webcontent\js\fdp>gulp bundle-pages
[13:02:07] Using gulpfile C:\PRD_DEV_WORKSPACE\FO\portal-infrastructure\webcontent\js\fdp\gulpfile.js
[13:02:07] Starting 'bundle-pages'...
[13:02:07] Finished 'bundle-pages' after 61 ms
$ jspm bundle [src/pages/com/fineos/refapp/TestEs6Page2.js] dist/TestEs6Page2.js --inject
     Building the bundle tree for [src/pages/com/fineos/refapp/TestEs6Page2.js]...

       src/pages/com/fineos/refapp/TestEs6Page2.js

ok   dist/TestEs6Page2.js added to config bundles.
ok   Built into dist\TestEs6Page2.js with source maps, unminified.
$ jspm bundle [src/pages/com/fineos/refapp/TestEs6Page.js] dist/TestEs6Page.js --inject
     Building the bundle tree for [src/pages/com/fineos/refapp/TestEs6Page.js]...

       src/pages/com/fineos/refapp/TestEs6Page.js

ok   dist/TestEs6Page.js added to config bundles.
ok   Built into dist\TestEs6Page.js with source maps, unminified.
```
Everything looks fine,right? Well the issue is that even though the bundled files are generated, the config.js bundles configuration only processes the last bundle to the config - in this case it's TestEs6Page.js as seen below : 

```
System.config({
  baseURL: "/fineos-refapp/js/fdp/",
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "optional": [
      "optimisation.modules.system"
    ]
  },
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },
  bundles: {
    "dist/TestEs6Page.js": [
      "src/pages/com/fineos/refapp/TestEs6Page.js"
    ]
  },

```

I understand that gulp works in parallel, however I'd just like to know  - if the files are all being bundled,  why isn't the config.js isn't getting updated correctly? And is there a way to rectify this?

If anybody has any advice on what to do to get this to work it would be greatly appreciated.

**Comment by donaldev** [comment]
FIXED/RESOLVED : 

Ok so after some investigation it was all because of the fact that gulp works in parallel.
It was my understanding that if it was in a for loop it should surely execute it in sequence,  which it does(and that's why the files do actually get bundled), but each of the iterations take a different thread, and all of these threads then try to access the config.js file at once which causes issues.

Here is my workaround in case anybody has similar issues : 
```
//single file for every module
gulp.task('gather-pages', function (callback) {

	//bundle all pages files
	return gulp.src('src/pages/**/*.js')
	.pipe(
			foreach(function(stream,file){
				
				var filename = path.basename(file.path);
				
				filenames.push(filename);//pushes file names into stacK
				
				return stream
				
			})
		)
	});

 executevar = true;
	gulp.task('bundle-pages', ['gather-pages'],			
		function execute() {

			while (filenames.length > 0 && executevar === true) {
				var str=""; //TODO: what is this?
				executevar = false;
				var f = filenames.pop();
				
				run('jspm bundle [src/pages/com/fineos/refapp/'+f+'] dist/'+f+' --inject').exec(str, function(){
					//multiple threads are trying to access config.js so it needs to be ran in order/sequence
					executevar = true;
					execute();
				});			
			}
	
		}
	);
```

**Comment by ArmorDarks** [comment]
I is slightly unclear why would you bundle each file individually?

**Comment by donaldev** [comment]
I believe this link may help explain - https://medium.com/@asyncmax/the-right-way-to-bundle-your-assets-for-faster-sites-over-http-2-437c37efe3ff

With HTTP/1, we can confidently say that bundling everything into one file improves performance.
However with the introduction of HTTP/2, it is said that using multiple files with moderate concatenation may be better for performance. With my bundling , I have a gulp task called bundle-single(for one single file), bundle-groups(for bundling into several "categorical" files), and finally the bundling done above which does a file for each module.

**Comment by ArmorDarks** [comment]
If you aren't using Hot Reloading, maybe just use built-in `--watch` (or better `-wid` in your case)?

**Comment by donaldev** [comment]
I'm not sure what relevance that has.
I have my own gulp task to watch, this is to do with browser loading performance.

**Comment by ArmorDarks** [comment]
This is straightforward relevant. This can be done much easier by using Gulp for all other thing, but letting watching JS files JSPM.

**Comment by ArmorDarks** [comment]
Ah, I see.
