### ISSUE TITLE
Steps for updating React application from jspm "@0.16.53" to "@beta"

### ISSUE THREAD

**Issue by vcernomschi** [jspm/jspm-cli#2352]
I am just wondering if there are any additional steps to migrate application from jspm "@0.16.53" to "@beta". 

I am using the latest version of React v15.6.1 and encountered with the following errors:
1 - defaultExtension (checked with { defaultExtension: 'js', }, but it looks like it doesn't apply the systemjs package configuration)
2 - jsx support (I've tried to do https://jspm.io/0.17-beta-guide/installing-the-jsx-babel-plugin.html, , but it looks like it doesn't apply the systemjs package configuration)

**Comment by aluanhaddad** [comment]
Greetings.

I just ran through the example in the guide and did not run into any issues with the following configuration

```js
SystemJS.config({
  transpiler: "plugin-babel",
  packages: {
    "app": {
      "main": "main.js",
      "format": "esm",
      "defaultExtension": "js",
      "meta": {
        "*.js": {
          "loader": "plugin-babel",
          "babelOptions": {
            "plugins": [
              "babel-plugin-transform-react-jsx"
            ]
          }
        }
      }
    }
  },
  // ...
});
```
would you be able to clarify the specific issue you are experiencing?
