### ISSUE TITLE
New dev-release with newest SystemJS?

### ISSUE THREAD

**Issue by fMads** [jspm/jspm-cli#2354]
When can we expect a new release of the 0.17 branch with the newest SystemJS release?
SystemJS 0.20.15 fixed a circular linking race condition, that's a big issue here.
We can of course run `jspm dl-loader --latest` but it will be much easier for us (and over CI) to just install JSPM without any more stuff to do

**Comment by aluanhaddad** [comment]
@guybedford what would you advise here? Should a new release be drafted with each iteration of SystemJS?

**Comment by guybedford** [comment]
@aluanhaddad yes, exactly what is needed is the package.json version bump, testing and then to publish the release.

Sorry I've been meaning to get to this but am currently in the midst of jspm 2 dev work.

**Comment by aluanhaddad** [comment]
I created #2356 to update to the latest version of the loader (0.20.17).

**Comment by guybedford** [comment]
This is out in 0.17.0-beta.43 now.
