### ISSUE TITLE
Defining "defaultExtension" based on current file extension

### ISSUE THREAD

**Issue by zoff** [jspm/jspm-cli#2357]
**JSPM Version:** 0.17.0-beta.32
**Transpiler Plugin(s):** babel
**Details:**
Hi all, I have an hybrid application I'm porting to typescript, file js and ts must be *by design* in the same directories (bad decision, I know).
It is a HUGE application so this operation will take a lot of time so, while doing the porting, I would like to abstract from file extension in import declaratio.
I tried, hoping for a "lucky strike", something like this:
```
SystemJS.config({
   [...],
    packages: {
        "src": {
            "meta": {
                "*.js": {
                    "defaultExtension": "js"
                },
                "*.ts": {
                    "loader": "ts",
                    "defaultExtension": "ts"
                }
            }
        }
    },
   [...],
})
```
but it isn't working.
Is there a way to tell JSPM to add .js extension for imports in .js files and .ts extension for imports in .ts files?

Thanks

PS: I'm stuck to 0.17.0-beta.32 for some kind of incompatibility on greater versions, yes I need to debug it further.

**Comment by aluanhaddad** [comment]
No, unfortunately, I believe this is not possible because the file is being matched by the extension that is being defaulted. 

Fortunately, there is a very simple workaround.

TypeScript allows a relative module specifier to end in `.js`.
So you can write the following in both `.ts` and `.js` files.
```ts
// my-module.ts
import writtenInTS from './written-in-typescript';
import writtenInJS from './written-in-javascript.js';
```
