### ISSUE TITLE
Change name of System

### ISSUE THREAD

**Issue by donaldev** [jspm/jspm-cli#2359]
Hi all,

With the current project I am working on, I have many different projects which all have JSPM bundling for ES6 modules set up. With that, they all have their own config.js file.

Sometimes in certain projects we pull in JS from other projects e.g. in project A I want to load some of project B's modules.

If I do a simple System.import, it will look for project A's config.js for the bundle depenencies/paths.

To get around this I was planning on renaming the System object in each of the different config.js files and therefore be able to load the modules freely.

E.g. in project A config.js would be
```
A_System.config({
//blah
})
```

 in project B config.js would be
```
B_System.config({
//blah
});
```

Then if I want to call some module from project B(within project A)...

```
B_System.import(module).then(function(){
//blah
})
```

Is something like this possible?
Something like initialising System object in the beginning of config.js

var A_System = new System();

Thank you in advance!

**Comment by aluanhaddad** [comment]
You can use `new SystemJS.constructor()`.
You may want to consider using jspm link 
```bash
~/source/a
$ jspm link ../b
```

**Comment by donaldev** [comment]
Thank you for getting back to me  :)

I will have a look at the docs to get my head around jspm link and see which suits better.
