### ISSUE TITLE
JSPM install meddles with nodeConfig/paths

### ISSUE THREAD

**Issue by ZoolWay** [jspm/jspm-cli#2362]
**JSPM Version:** 0.17.0-beta.44

**Transpiler Plugin(s):** I do not use a transpiler together with JSPM

**Details:**
My `jspm.config.js` has a section `nodeConfig` with `paths`:
```
  nodeConfig: {
    "paths": {
      "github:": "./wwwroot/dev/jspm_packages/github/",
      "npm:": "./wwwroot/dev/jspm_packages/npm/",
    },
  },
```

Every time I run `jspm install`, the paths are changed to:
```
  nodeConfig: {
    "paths": {
      "github:": "jspm_packages/github/",
      "npm:": "jspm_packages/npm/",
    },
```

But that breaks my bundling which requires the path I configured by myself.

Why is JSPM doing this and how can I stop this?

**Comment by aluanhaddad** [comment]
When you run `jspm init` you can configure these paths. You can also rerun the command at any time to update them or to see the currently configured values.

**Comment by ZoolWay** [comment]
The problem is not that I want to update them, the problem is that just running `jspm install` changes them without asking me.

**Comment by amenadiel** [comment]
I can't replicate your issue. The only thing that happened when running `jspm install` was that `nodeConfig` paths were normalized as:

```js
nodeConfig: {
        "paths": {
            "github:": "wwwroot/dev/jspm_packages/github/",
            "npm:": "wwwroot/dev/jspm_packages/npm/"
        }
    },
```
