### ISSUE TITLE
Follow operating system cache location standards

### ISSUE THREAD

**Issue by Siilwyn** [jspm/jspm-cli#2363]
It would be great if this module followed the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html). Instead of placing the cache directory in the home directory it should be placed in the OS specific appropriate directory. Getting the correct directory is easy with a module like [env-paths](https://github.com/sindresorhus/env-paths). This, among other things, allows a user to specify a directory in which they want all applications to look for their user configurable setting files and keep their home directory clean.

**Comment by aluanhaddad** [comment]
if you're talking about the global jspm cache, it is placed in the correct OS directory at least on Windows.

What operating system and version are you running?

**Comment by Siilwyn** [comment]
Hi @aluanhaddad thank you for replying, yes I mean the global cache & I'm using Ubuntu.

I dug into the code a bit and it seems to just place in the home directory [when `process.env.LOCALAPPDATA` is not defined](https://github.com/jspm/jspm-cli/blob/master/lib/config.js#L16) and writing it from [here](https://github.com/jspm/jspm-cli/blob/5963d0e7929d5d277f670af64f03ed75743ecc9d/lib/global-config.js#L32-L47).

**Comment by aluanhaddad** [comment]
Thanks for the clarification and the example code.

This sounds like a good idea (personally I would not want this directory cluttering my home directory). Then again, I am primarily a Windows user so I am OK with an OS being opinionated about this sort of thing.

I did some searching but I can't seem to find any indication about the extent to which XDG is accepted or considered canonical.

Perhaps more Linux users could weigh in on this.

**Comment by Siilwyn** [comment]
As far as I know XDG is the only standard on this subject and is used by major Linux distro's as Debian, Arch and Fedora.
The `env-paths` package is downloaded around 3000 times. This [long standing issue on Atom](https://github.com/atom/atom/issues/8281) contains a lot of replies with people wanting it to follow the standards for various reasons also says a lot.

**Comment by aluanhaddad** [comment]
@Siilwyn thank you. That is exactly the kind of context I was looking for.

**Comment by Siilwyn** [comment]
Oof @guybedford what happened?

**Comment by guybedford** [comment]
@Siilwyn jspm 2.0 has been released, which follows these standards.

**Comment by Siilwyn** [comment]
Alright awesome! :tada: Since it didn't get closed/resolved by a commit I was confused. Much appreciated!
