### ISSUE TITLE
Loding cjs module in an es6 package

### ISSUE THREAD

**Issue by jithin1987** [jspm/jspm-cli#2366]
**JSPM Version:** `0.17.0-beta.44`

**Transpiler Plugin(s):** babel
**Details:**

I have the following config in `jspm.config.js`
```
SystemJS.config({
  paths: {
    "npm:": "jspm_packages/npm/",
    "github:": "jspm_packages/github/",
    "build/": "src/"
  },
  packages: {
    "build": {
      "main": "./src/client/main.js",
      "meta": {
        "build/client/utils/my-module.js": {
          "format": "cjs"
        },
        "*.js": {
          "loader": "plugin-babel",
          "babelOptions": {
            "plugins": [
              "babel-plugin-transform-react-jsx",
              "babel-plugin-transform-object-rest-spread"
            ]
          }
        }
      }
    }
  }
});
```

However using `module.js` in an es6 file like `import MyModule from 'build/client/utils/my-module.js';` results in following error ```system.js:4 Uncaught (in promise) Error: module is not defined```

Is this a supported usage ?

**Comment by guybedford** [comment]
Can you perhaps share a repo that replicates this for me to try?

**Comment by jithin1987** [comment]
@guybedford 
Repo https://github.com/jithin1987/jspm-es6-cjs

This is what I am trying to do - import an 'cjs' module in a 'es6' file https://github.com/jithin1987/jspm-es6-cjs/blob/master/src/app.js#L2

**Comment by guybedford** [comment]
Try changing this line - https://github.com/jithin1987/jspm-es6-cjs/blob/master/jspm.config.js#L25 to `"cjs.js"`?

**Comment by amenadiel** [comment]
If you set your packages config as

```js
    packages: {
        "app": {
            "main": "app.js",
            "format": "esm",
            "meta": {
                "cjs.js": {
                    "format": "cjs"
                }
            }
        }
    }
```

it will work. First, because inside the package called "app" , `cjs.js` should be referenced without the `app/` prefix. Second, because avoiding to set `plugin-babel` as the loader for everything, you avoid trying to make `babel-plugin` to do yor runtime transpilation from CJS to ES6. That's `System.js` job,  not `plugin-babel`'s.

By the way, you are installing Babel^5 packages. They aren't used anymore as of version v0.17-beta.

Your `package.json` should just be

```json
{
  "jspm": {
    "name": "app",
    "main": "app.js",
    "devDependencies": {
      "plugin-babel": "npm:systemjs-plugin-babel@^0.0.25"
    }
  },
  "devDependencies": {
    "jspm": "0.17.0-beta.45"
  }
}
```
