### ISSUE TITLE
no such file or directory: github:systemjs/plugin-json@0.1.2/json

### ISSUE THREAD

**Issue by Mobiletainment** [jspm/jspm-cli#2369]
**JSPM Version:** 0.16.53

**Transpiler Plugin(s):** I do not use a transpiler

**Details:**
I'm having a project with a 3rd party library which has a dependency on systemjs-json:

```
System.config({
    ...
    map: {
        "ag-grid": "npm:ag-grid@12.0.2",
        "npm:ag-grid@12.0.2": {
            "path": "github:jspm/nodelibs-path@0.1.0",
            "process": "github:jspm/nodelibs-process@0.1.2",
            "systemjs-json": "github:systemjs/plugin-json@0.1.2"
        },
    ...
```

I see that the systemjs-json dependency was properly installed in **`jspm_packages/github/systemjs/plugin-json@0.1.2`**.

While the app runs perfectly fine in dev environment, I experience the following issue when creating the production build via **bundle-sfx**. The error output is like following:
**`jspm bundle-sfx app/app.js dist/app.bundle.js --minify --skip-source-maps`**

- `err  (SystemJS) ENOENT: no such file or directory, open 'C:\test\jspm_packages\github\systemjs\plugin-json@0.1.2\json'`
- `Error: ENOENT: no such file or directory, open 'C:\test\jspm_packages\github\systemjs\plugin-json@0.1.2\json'`
- `Error loading C:/test/jspm_packages/github/systemjs/plugin-json@0.1.2/json as "github:systemjs/plugin-json@0.1.2/json" from C:/test/jspm_packages/github/systemjs/plugin-json@0.1.2.js`

I tried installing the loader explicitly and went through different meta configurations, like:
```
      meta: {
          '*.json': { loader: 'systemjs-json' },
```

Nevertheless, I'm not able to generate a successful bundle.

Has anyone experienced a similar problem? Any input is highly appreciated.
Thanks!

**Comment by aluanhaddad** [comment]
Do you have defaultJSExtensions disabled?

**Comment by Mobiletainment** [comment]
Yes I have (I‘m loading Javascript foremost)

**Comment by Mobiletainment** [comment]
I got it running. I'm not sure what eventually fixed it, but what I ended up with was re-installing the text plugin using the old 0.0.4 version (the new one did actually cause errors) and creating an explicit packages entry for the app in config.js:

```
packages: {
    "app": {
      "main": "app/app",
      "defaultExtension": "js",
      "meta": {
        "*.css": {
          "loader": "css"
        },
        "*.less": {
          "loader": "less"
        },
        "*.html": {
          "loader": "text"
        }
      }
    }
  },
```
I'm closing this issue since it was a misconfiguration on my side rather.
Thank you very much.
