### ISSUE TITLE
transpile ES module as SystemJS.transpiler set to false

### ISSUE THREAD

**Issue by caperavensoftware** [jspm/jspm-cli#2370]
**JSPM Version:** `$ jspm --version`
jspm@0.16.53

**Transpiler Plugin(s):** babel / traceur / typescript / I do not use a transpiler
none

**Details:**
Trying to get my code to using ES6 modules (import, export) to work with JSPM.
I don't want transpilation to happen so transpiler is set to false

```
System.config({
    baseURL: "./",
    meta: {
      "app/src/**/*.js": {
        format: "esm"
      }
    },
    defaultJSExtensions: true,
    transpiler: false,
    paths: {
      "*": "app/src/*",
      "npm:*": "jspm_packages/npm/*",
      "github:*": "jspm_packages/github/*"
    },
    map: { ... }
});
```

I get this error when trying to load a ES6 module file

```
Error: (SystemJS) Unable to dynamically transpile ES module as SystemJS.transpiler set to false.
	TypeError: Unable to dynamically transpile ES module as SystemJS.transpiler set to false.
	    at <anonymous>
	Error loading http://127.0.0.1:8080/app/src/main.js
```

What am I doing wrong here?

**Comment by aluanhaddad** [comment]
You need a transpiler to transpile your ES modules.
If you wish to _only_ transpile import and export statements, you can configure your transpiler accordingly.
For example, with plugin-typescript, the configuration would be
```js
SystemJS.config({
  transpiler: "plugin-typescript",
  typescriptOptions: {
    "target": "esnext",
    "module": "system"
  },
  meta: {
    "*.ts": {
      "loader": "plugin-typescript"
    }
  }
});
```

**Comment by caperavensoftware** [comment]
I don't understand why we need transpilers because import / export  is now supported in the browser. Are there any plans to update jspm to not use transpilers for ES6 modules?

**Comment by guybedford** [comment]
@caperavensoftware yes, jspm 2 development based on this target is currently underway.

**Comment by caperavensoftware** [comment]
Excellent news, ty very much for all your effort, much much appreciated.

**Comment by aluanhaddad** [comment]
Sorry, I was not considering the obvious.
