### ISSUE TITLE
0.17 Beta stability / estimated non-beta release date

### ISSUE THREAD

**Issue by DavidKDeutsch** [jspm/jspm-cli#2372]
How safe is it to use 0.17 right now, given that it is still technically a "beta"? In #1794 you mentioned it was complete with the exception of documentation, but that was 1 year and a half ago, so I'm not sure what the current state is. Also, do you have a rough guess as to when the beta label will be dropped?

Thanks

**Comment by ArmorDarks** [comment]
A bit of fresher information can be find here, but not much: https://github.com/systemjs/systemjs/issues/767#issuecomment-335090114

What I can say, it is okey to use in most projects. We didn't encounter any critical bugs during normal usage, but some functionality still might be missed or unfinished. Though, most part of typical frontend projects will never need it anyway.

**Comment by amenadiel** [comment]
Been using 0.17 in production for over a year with no problems at all. I'd say it's more stable, robust, flexible and faster tan v 0.16 in every front.

**Comment by guybedford** [comment]
jspm 0.17 beta is now end of life, with 2.0 to be released tomorrow.

It's been hard closing all these old issues actually, seeing all the struggles. @amenadiel one good comment in a sea of bad means a huge amount. I hope you like 2.0.
