### ISSUE TITLE
bundle misfiring

### ISSUE THREAD

**Issue by selfagency** [jspm/jspm-cli#2373]
**JSPM Version:** 
0.17.0-beta.45

**Transpiler Plugin(s):**
babel

**Details:**
i'm having a strange issue where my bundle fails to execute randomly – it fires just fine on some page loads and doesn't fire at all on others. this happens across browsers.

`<script src="/public/scripts/nylon.js?v=2.19.46" crossorigin="anonymous" async></script>`
[here's the bundle](https://nylon.com/public/scripts/nylon.js?v=2.19.46)

any ideas why this is happening and how to prevent it?

**Comment by guybedford** [comment]
If I run this bundle, I consistently get:

```
JQMIGRATE: Migrate is installed, version 3.0.1  nylon.js:1:55434
TypeError: window.googletag is undefined[Learn More]  nylon.js:1:262320
```

It would help to get the unminified version for debugging. Also if you can clarify exactly what is misfiring that would help.

**Comment by selfagency** [comment]
it seems there was an external script from a third party source that was causing it hang. thanks anyhow.
