### ISSUE TITLE
Terminal Window Closes During `jspm install`

### ISSUE THREAD

**Issue by TomFoyster** [jspm/jspm-cli#2374]
**JSPM Version:** 
0.16.53

**Transpiler Plugin(s):** 
I do not use a transpiler

**Details:**
Very strange issue where the terminal window closes halfway through a `jspm install`. 

Running on Windows 7. I'm at a loss because there are no errors reported back at all - or at least none that I'm aware of. Looking in the _jspm_packages_ dir I can see that modules from NPM have been installed, but nothing from Github. I never see any of the "OK" responses before the window closes itself. 

I really don't know where to start in debugging the issue?

**Comment by guybedford** [comment]
Which terminal are you using here? Do you still get the issue if you try another terminal like the Git terminal?

**Comment by TomFoyster** [comment]
Hi Guy, 

We've tried in the standard Windows 7 Command Prompt as well as Powershell, and we get the same behaviour. We have other machines here with a similar setup and on the same network running things perfectly fine

**Comment by guybedford** [comment]
@TomFoyster if you keep an eye on the system memory, is this perhaps just a case of an out-of-memory error?

**Comment by aluanhaddad** [comment]
I'm wondering if this could be related to group policy. Also, have you tried running the command is administrator?
