### ISSUE TITLE
can't install babel-jest / promise rejected with a non-error

### ISSUE THREAD

**Issue by pocesar** [jspm/jspm-cli#2375]
**JSPM Version:** `0.17.0-beta.45`

**Transpiler Plugin(s):** babel / traceur / typescript / I do not use a transpiler

**Details:**

```
jspm install npm:babel-jest

warn Running jspm globally, it is advisable to locally install jspm via npm install jspm --save-dev.
     Updating registry cache...
(node:12612) Warning: a promise was rejected with a non-error: [object String]
(node:12612) Warning: a promise was rejected with a non-error: [object String]
(node:12612) Warning: a promise was rejected with a non-error: [object String]
(node:12612) Warning: a promise was rejected with a non-error: [object String]

err  Installing npm:babel-jest@21.2.0, no version match for npm:babel-core@^7.0.0

warn Installation changes not saved.
``` 

two things: the wrong Promise rejection using a string (and not a `new Error()`), and it seems jspm is having a hard time understanding `babel-core@7.0.0-beta.3` as part of `^7.0.0`

**Comment by guybedford** [comment]
@pocesar yeah this isn't ideal. In jspm 2 the `--edge` flag will apply to sub-dependencies, but for now you can fix this via an override - `jspm install npm:babel-jest -o "{ peerDependencies: {  "babel-core": "^7.0.0-alpha" }}`
