### ISSUE TITLE
Can't install react-appinsights

### ISSUE THREAD

**Issue by Mosho1** [jspm/jspm-cli#2376]
**JSPM Version:** 0.16.53

**Transpiler Plugin(s):** I do not use a transpiler

**Details:** When trying to install `react-appinsights` the installation exits after getting the following error:

```
warn Error on download for github:jspm/nodelibs-tls
     Bad response code 404

err  Error downloading github:jspm/nodelibs-tls.
```

**Comment by guybedford** [comment]
Have you tried re-entering your github credentials? Which version of jspm-github is installed in jspm? There was a PR at https://github.com/jspm/github/pull/119 and https://github.com/jspm/github/pull/120 that may possibly be interfering here.

**Comment by Mosho1** [comment]
Yes, I did re-enter my github credentials. I had a different response before the 404 saying I should enter github credentials which I did, and they were successfully tested by jspm. `jspm-github@0.13.18` is installed.

**Comment by Mosho1** [comment]
I've successfully installed the package using npm from github, followed by the jspm failed installation:

![image](https://user-images.githubusercontent.com/5153007/31695033-e99d9c2e-b375-11e7-9525-2a873d831921.png)

**Comment by aluanhaddad** [comment]
I cannot reproduce this.
I tried with a fresh installation of `0.16.53` and ran
```shell
$ jspm install npm:react-appinsights
```
Can you share some additional info?

**Comment by Mosho1** [comment]
Investigated and it's my bad, I didn't check public_repo when creating the access token.
