### ISSUE TITLE
install linked package, that refers to another linked package

### ISSUE THREAD

**Issue by PFight** [jspm/jspm-cli#2383]
**JSPM Version:** 0.16.53

**Details:**
I have two 3 packages: core, core-ext, app. I want to develop core and core-ext locally using npm link and jspm link. Package core has no dependencies. Package core-ext depends on core:

    // core-ext package.json
    dependencies:  {
        core: "^0.0.1"
    }

I perform jspm link of core:

    ~/work/core> jspm link npm:core@0.0.1

Link of core-ext:

     ~/work/core-ext> jspm link npm:core-ext@0.0.1

Then in app I want to install core-ext:

     ~/work/app> jspm install npm:core-ext --link
      err  Repo npm:core not found!

Expected, that `jspm install --link` will also try to look for dependent packages as linked, but jspm doesnt. So, using `jspm link` is not possible, when you need install linked package, that refers to another linked package.

**Comment by aluanhaddad** [comment]
The syntax is is not correct. JSPM and NPM don't use the same link commands. 
You can link the directory with
`$ jspm link ../core`

**Comment by PFight** [comment]
Em, but mentioned by me syntax do work (if do not refer to another linked package). Anyway, I will try your variant later.
