### ISSUE TITLE
please support "self-executing bundle"

### ISSUE THREAD

**Issue by nimo23** [jspm/jspm-cli#2388]
**JSPM Version:** 0.17.0-beta.47

**Transpiler Plugin(s):** babel

**Details:**

I cannot find something like 

`jspm bundle-sfx app/main.js app.js`

within https://jspm.io/0.17-beta-guide/bundling.html.

Please provide **"self-executing bundle"** with a optional flag "--sfx": 

For example:

`jspm bundle test.js app-bundle.js --minify  --sfx`

**Comment by zenorbi** [comment]
You can find this under https://jspm.io/0.17-beta-guide/static-builds-with-rollup-optimization.html using the ‘build’ command.
