### ISSUE TITLE
Webpack or JSPM as package manager (Question)

### ISSUE THREAD

**Issue by nimo23** [jspm/jspm-cli#2390]
Question:

With webpack, I can do `"npm install --save lodash"` and use `import _ from 'lodash';` from within my client script. So webpack uses **npm** as its **package manager.** I do not really understand why jspm is a better choice. 

**Please explain, why inventing "jspm_packages" instead of using "node_modules".** Both can be used as a package manager for web. Or?

**Comment by ArmorDarks** [comment]
@guybedford said that JSPM 2 will be just an addition on top of the NPM. And that sounds like a right direction.

**Comment by nimo23** [comment]
cool. I am glad to hear about this. Are there any release plans?
