### ISSUE TITLE
Webstorm (design time) issues and workaround(?)

### ISSUE THREAD

**Issue by Gitii** [jspm/jspm-cli#2391]
**JSPM Version:** `$ jspm --version`
0.16.53
**Transpiler Plugin(s):** babel / traceur / typescript / I do not use a transpiler
typescript
**Details:**
Webstorm 2017.3.1 does not find the installed modules ("Cannot find the module ...") when importing them using "import ... from ...".

I think, the underlying real issue is that typescript does not handle the `jspm` way of storing modules.
Nevertheless actually loading (at **run time**) the code **works fine** (thank you `plugin-typescript`)

But at  **design time**, context and syntax help is **broken** - that's quite annoying.

I think, I found a work around for that issue.
First of all I want to **share** that **workaround** - and **check, if** that is **actually** an issue and not **my faulty setup** that's causing these problems at design time :) 

# Basic idea
I wrote a powershell script, which parses the `package.json` and writes module mappings (`compilerOptions.paths`) into a separate file `tsconfig.paths.json`. 

## At design time
The main `tsconfig.json` is loaded (which loads `tsconfig.paths.json`) and the typescript service now "finds" all modules that I installed using jspm -> webstorm is now happy and works just like expected!
## At runtime
systemjs is configured to load another tsconfig file (`tsconfig.systemjs.json`) which loads the "main" tsconfig **and** resets the `compilerOptions.paths`-property - which is not needed and in fact breaks the build process otherwise.

So, final question:
Are my design time issues with webstorm caused by a mistake on my side?
Or is that an actually issue that I circumvented by my script?

**Comment by ChrisLane** [comment]
I'm currently having the same issue. It'd be great to have WebStorm recognise my installed jspm packages! Not sure why you've posted this here rather than the Idea forums though.
