### ISSUE TITLE
Watcher watching config files breaks development bundling flow

### ISSUE THREAD

**Issue by sergei-maertens** [jspm/jspm-cli#2393]
In the process of upgrading to React 16 I was also bumping the jspm version (beta 22) because of issues with the updated Enzyme version (some context, not very relevant).

A colleague noticed that our bundle flow (`jspm bundle router.js -wid`) was slowed down and no longer doing incremental builds for the changed file, and I managed to trace it back to this change: https://github.com/jspm/jspm-cli/commit/a1bdee88e903e5f19f161bd9b1ab77e929e22b44

We've set up quite a complex flow that integrates with Django, and as such, the config files and jspm_packages files are in `$ROOT/static/js/` and `$ROOT/staticfiles/jspm_packages/`. For all that JSPM is aware, the root for jspm is `$ROOT/staticfiles`, and that is wat was being watched. (relevant docs: https://jspm.io/0.17-beta-guide/development-bundling.html)

Since beta.23, the configfiles are also included, and spawn a new builder if changes in them are detected. Now Watchman is no longer watching `staticfiles`, but the entire `$ROOT`. However - what's being watched doesn't matter too much, but it seems that because of the `-i` (inject) option, there is always a write to the config file, for every source file change, which causes a full new bundle/builder to be started, and the whole hot-module-replacement approach breaks down. Which makes a difference of waiting 1 second vs. 30 seconds for changes to propagate and being able to refresh the browser. On a slower laptop (from my colleague), this appears to sit around the minute-mark even.

I'm currently patching out the line that adds the `configFiles` to the array of files to be watched, which fixes the issue for now, and we don't need that feature (even though it could be useful).

I think this may also be related to #2242 .

Currently I don't have any particular question or proposition, if/when I have more time I'd like to dive deeper into it, but at least here I can keep track of the issue, and it might be useful if other people run into this.

**Comment by guybedford** [comment]
It should be possible to temporarily disable the configuration watcher reaction when saving the config file in jspm itself. Perhaps some kind of messaging between the config save code and the watcher could manage this, or even a shared variable binding.

If you're still interested in looking into this further, I'd be happy to review a PR along those lines.

**Comment by sergei-maertens** [comment]
I'd love to, but unfortunately I can't free up any time for it. Frontend development for our project has been transfered to a different company and jspm is no longer part of the stack... :(

**Comment by guybedford** [comment]
No problem at all, it was just if it can unblock you.
