### ISSUE TITLE
issue reverting jspm back to 0.16.53 (last stable build)

### ISSUE THREAD

**Issue by lj1000** [jspm/jspm-cli#2398]
I recently tried latest beta version of jspm "0.17.0-beta.47" in a local version of a project that i pull from a git repository. Didnt have much success so deleted the project and did a fresh git clone to set everything back.

so the project is backed to using jspm@0.16.53 and usually works fine but since trying this beta version and reverting back every time i run 'jspm install' it tries to add the following line to our config.js file

"systemjs-json": "github:systemjs/plugin-json@0.1.2"

where as before this didnt happen. its also crashing when i run the tests on my local machine with the error

' Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:9877jspm_packages/npm/es6-iterator@2.0.3.json Error loading http://localhost:9877jspm_packages/npm/es6-iterator@2.0.3.json!http://localhost:9877jspm_packages/github/systemjs/plugin-json@0.1.2.js as "../es6-iterator@2.0.3.json!systemjs-json" from http://localhost:9877jspm_packages/npm/es6-iterator@2.0.3/array.js'

like i say this didnt do this before i tried the beta version. i got a collegue to git clone the project onto his machine and everything works fine so its acting as if trying out the beta version has left some global setting on my machine that i cant remove.

any suggestions what could be happening?

**Comment by aluanhaddad** [comment]
Did you install beta globally?

**Comment by lj1000** [comment]
hi aluanhaddad not sure i follow your last comment?

**Comment by ericnewton76** [comment]
@lj1000 did you ever figure this out?

**Comment by lj1000** [comment]
Nope. Eventually moved over to using webpack in our project. There was just too many issues with jspm.
