### ISSUE TITLE
paths property in package.json updates paths only in 'jspm.node.js'

### ISSUE THREAD

**Issue by CxRes** [jspm/jspm-cli#2404]
**JSPM Version:** 0.17.0-beta.47

**Transpiler Plugin(s):** babel 

**Details:** `jspm init`  updates paths only in *jspm.node.js*. Either this should update it in both *jspm.node.js* and *jspm.browser.js* or paths must always be prefixed by `nodeConfig` and `browserConfig`

Also setting `browserConfig.paths`  in *package.json* does not update *jspm.browser.js*.

**Comment by aluanhaddad** [comment]
I see, it's a little confusing at times. I take it you're trying to reconfigure an existing project. Make sure that you use the custom option. This should let you respecify all of the paths explicitly. If you pick the default console workflow, it doesn't offer options for configuring these specific files. If you use the custom workflow it does not for those options and further you can choose to recombine your configs for example.

It's possible I've misunderstood you here and that you're filing a bud to state that it should implicitly update the separated path configuration.

**Comment by CxRes** [comment]
@aluanhaddad Yes, I am trying to migrate and it is EXTREMELY FRUSTRATING. It seems like someone with a fairly complex setup and limited knowledge of JSPM needs a project dev like you at hand to ensure the migration can occur.

I did use the custom options, but I do not recall seeing an option for paths. From what I understood in 0.17 you want to modify settings in *package.json* and have it configure the jspm config files for you (I am not sure about this though - maybe it is my design aesthetic that user configuration should be modified from one place only). So I added the extra `paths` and `packageConfigPaths` I had specified in 0.16 *config.js* and ran `jspm init` on it. However all the paths landed in *jspm.node.js* and `jspm bundle` then cannot find the paths (I fixed this by hand). IMHO the behaviour to not update both set of paths (if it is by design) is inconsistent.

Amongst the problems I am having this was a minor annoyance and one where the inconsistency was easy to spot. Frankly, in the absence of documentation, I am either required to read the source and play computer in my head or I am shooting in the dark. This is just one of many things that I am not able to get to work.  (Especially so if anything is node related)! That is after about a day spent on this already.

No wonder I am so upset!

**Comment by aluanhaddad** [comment]
I am most sorry that you are upset. As @guybedford mentioned in the issue you linked this is only well-supported for 0.17. If you use that the prompts will guide you through all the necessary reconfiguration and allow you to enter paths for each section if you desire to differentiate them. There is no need to manually adjust the package.json file.

Again I do apologize for the lack and/or disorganization of the documentation.

For my part, I use 0.17 for all of my front end projects, and have been meaning to address a number of these issues but have been very occupied with other matters of late.

Nevertheless, I appreciate you or frank and direct feedback.

**Comment by CxRes** [comment]
I have a feeling we may be talking about different things with `paths` here...

I am specifically referring to adding custom paths (over and above things like paths to src for node and browser etc.) to the `paths` property. That I could not do in the prompts. I just ran the custom prompts again... Have I missed something?

**Comment by CxRes** [comment]
Also, a word regarding the other bug since you have read that issue as well. The fix there is really simple but again the `Loader.load()` api is undocumented. I know which line is causing the problem but since I do not know the API I cannot tell the loader to load not only `*.json` (which is done using an override to module loading) but also `*.json!json` (ie normal module loading). Again, a little of guidance would have meant a PR and not an issue!

**Comment by aluanhaddad** [comment]
Regarding your point about custom locations for node and the browser, could you not use `map` or `packages` configuration on startup, obviously just as a workaround?

**Comment by aluanhaddad** [comment]
A fair amount of this is tied in with SystemJS and the version of the loader that ships by default with the different branches. You can use master with the latest SystemJS which does support more articulated environment configuration.

**Comment by CxRes** [comment]
I know I am taking so much of your time and I am sorry for that... 

I am not using `map` or `packages`. I actually did try `map` but that would not copy over properties when I ran `jspm init`, so then I used `paths`. Maybe its easier if I were to just ask you what config to use for my specific circumstance:

My project is laid out like this:
```
jspm_packages/
scripts/
src/
|- components/ (contains about 25 components)
|- api/
|- app/
```

Instead of doing `import src/component/<name>/index.js`, I want to do `import src/component`. For one part of this I set up `packageConfigPath: "[... , src/components/*/package.json]"` where I setup packages config `{"main":"index.js"}`. The other was to map `"components/": "src/components/"`.

Ideally, I would like to avoid 'src/' in all my browser paths but without changing my `baseURL` and keeping location of config files & *jspm_packages/* at the root of my repo. This way I can use `jspm run scripts/foo.js` where `foo.js` can refer to other files within the scripts folder (or anywhere else in the project for that matter).

Thanks in advance!!!!!!
