### ISSUE TITLE
Jspm 0.17 does not handle ` || ` semver range syntax

### ISSUE THREAD

**Issue by zenorbi** [jspm/jspm-cli#2406]
**JSPM Version:** 0.17.0-beta.48

**Transpiler Plugin(s):** I do not use a transpiler

**Details:**
JSPM's semver module does not seem to handle ` || ` semver syntax.

**Steps to reproduce:**
- have jspm@0.17.0-beta.48 installed
- `jspm init` just to create a random project
- `jspm install npm:aurelia-templating-binding@1.4.2`

jspm will report `err  Installing npm:aurelia-templating-binding@1.4.2, no version match for npm:aurelia-binding@^1.3.0 || ^2.0.0`

`npm show aurelia-templating-binding@1.4.2 dependencies` shows:
```
{ 'aurelia-binding': '^1.3.0 || ^2.0.0',
  'aurelia-logging': '^1.0.0',
  'aurelia-templating': '^1.3.0' }
```
`npm show aurelia-binding versions` shows that several version would match this semver range:
```
...
  '1.3.0',
  '1.4.0',
  '1.5.0',
  '1.6.0',
  '1.7.0',
  '1.7.1',
  '2.0.0',
  '2.1.0' ]
```

**Comment by alienriver49** [comment]
I just ran into this as well, same repository: aurelia-templating-binding. I'm using JSPM 0.16.53

**Comment by zenorbi** [comment]
@guybedford I've looked around for a good package for semver parsing and intersecting. At a first glance, jspm could use the `semver` package for version selecting and `semver-set` for intersecting semver version ranges when merging `peerDependencies`.

**Comment by guybedford** [comment]
The project I have been using for semver parsing in newer work is http://npmjs.org/package/sver. Perhaps that resolves the underlying issue here? If so we could look at upgrading to this library.
