### ISSUE TITLE
Issues with AWS Amplify imports

### ISSUE THREAD

**Issue by ArmorDarks** [jspm/jspm-cli#2410]
**JSPM Version:** `0.17.0-beta.48`

**Transpiler Plugin(s):** babel

**Details:**

Doesn't work with [AWS Amplify](https://github.com/aws-amplify/amplify-js) out of the box.

It builds bundle succesfully, but chokes during run in browser with error

```
Uncaught TypeError: require is not a function
```

Issues comes from the line `var AWS = require('../lib/core');` within build by AWS Amplify package.

Seems like for some reason package is not recognized as CommonJS one. I've tried to provide format override, but it didn't affect the result at all:

```json
      "npm:aws-amplify@1.0.4": {
        "format": "cjs"
      },
```

Gets same error about undefined `require`

From that point, I quite have no idea what else can be done.

**Comment by guybedford** [comment]
When specifying the format, make sure to include the path to the main `npm:aws-amplify@1.0.4/index.js` or similar perhaps.

**Comment by ArmorDarks** [comment]
I've tried to use path from `aws-amplify` `package.json` `main` property

```js
      "npm:aws-amplify@1.0.4/lib/index.js": {
        "format": "cjs"
      },
```

but JSPM simply removes those lines from `package.json` on `jspm install` and issue still persists.

In `.dependencies.json` can be seen that `aws-amplify` relies on some dependencies:

```js
  "npm:aws-amplify@1.0.4": {
    "deps": {
      "@aws-amplify/analytics": "npm:@aws-amplify/analytics@^1.0.3",
      "@aws-amplify/api": "npm:@aws-amplify/api@^1.0.4",
      "@aws-amplify/auth": "npm:@aws-amplify/auth@^1.0.4",
      "@aws-amplify/cache": "npm:@aws-amplify/cache@^1.0.3",
      "@aws-amplify/core": "npm:@aws-amplify/core@^1.0.3",
      "@aws-amplify/interactions": "npm:@aws-amplify/interactions@^1.0.3",
      "@aws-amplify/pubsub": "npm:@aws-amplify/pubsub@^1.0.3",
      "@aws-amplify/storage": "npm:@aws-amplify/storage@^1.0.3"
    },
    "peerDeps": {}
  },
```

maybe it's cause of that? Though I've tried to specify in overrides `cjs` format for each of the dependencies, but that resulted in same error.
