### ISSUE TITLE
Trailing CR bug reintroduced in 0.17.0-beta.48 npm release

### ISSUE THREAD

**Issue by fdintino** [jspm/jspm-cli#2413]
**JSPM Version:** 0.17.0-beta.48

**Transpiler Plugin(s):** N/A

**Details:**

The issue that first occurred in the beta.46 release (see #2377) has resurfaced in the beta.48 release. Specifically, carriage return characters appear to have snuck into the js files, causing errors like the following on unix environments:

```
$ ./node_modules/.bin/jspm 
env: node\r: No such file or directory
```

In the interim I'm working around this by installing the release from github rather than npm, i.e. `npm install --save jspm/jspm-cli#0.17.0-beta.48`, but since jspm 0.17 beta 48 will not run on os x or linux as it is currently packaged on npm, I imagine it would affect most users of jspm.

**Comment by guybedford** [comment]
Thanks so much for posting, this is an annoying result of Windows publishing.

I've posted a beta.49 on Mac now which should resolve this.
