### ISSUE TITLE
jspm install -> Javascript heap out of memory

### ISSUE THREAD

**Issue by xania** [jspm/jspm-cli#2416]
**JSPM Version:** `2.0.0-beta.1`
**NodeJS Version:** `8.* ` and `10.* `
**NPM Version:** `6.4.1 ` and `10.* `

**Transpiler Plugin(s):**  I do not use a transpiler

**Details:**
<details>   
<summary> $ jspm install, Fails everytime on two different machines with this horrible error message</summary>

> . Finalizing https://registry.npmjs.org/typescript/-/typescript-3.1.2.tgz#sha512-gOoGJWbNnFAfP9FlrSV63LYD5DJqYJHG5ky1kOXS<--- Last few GCs --->
> 
> [2044:000001B8279FBF80]    80155 ms: Mark-sweep 1267.7 (1409.9) -> 1267.7 (1374.9) MB, 1976.4 / 0.0 ms  (average mu = 0.195, current mu = 0.000) last resort GC in old space requested
> [2044:000001B8279FBF80]    82244 ms: Mark-sweep 1267.7 (1374.9) -> 1267.7 (1370.9) MB, 2089.6 / 0.0 ms  (average mu = 0.104, current mu = 0.000) last resort GC in old space requested
> 
> etc....

</details>

----
After some digging I was able to pinpoint this to the typescript dependency in my package.json. Without typescript the `jspm install` command completed succesfully. I also tried v2.9.2 of typescript but that didnt help either.

<details>
<summary>package.json</summary>

```json
{
  "name": "sample",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "repository": "https://github.com/xania/XaniaApp",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "npx live-server --ignore=**/*.ts,**/*.map",
    "pkgmap": "npx jspm map ./src/test.js -o packagemap.json"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@jspm/node-builtins": "^1.0.0",
    "colors": "^1.3.2",
    "es-module-shims": "~0.1.15",
    "http-server": "~0.11.1",
    "live-server": "^1.2.0",
    "lodash": "^4.17.11",
    "rollup": "~0.66.5",
    "rxjs": "^6.3.3",
    "systemjs": "^2.0.2"
  },
  "jspm": {},
  "devDependencies": {
    "jspm": "git+ssh://git@github.com/jspm/jspm2-cli.git#2.0",
    "rollup-plugin-jspm": "git+ssh://git@github.com/jspm/rollup-plugin-jspm.git",
    "typescript": "^3.1.1"
  }
}
```

</details>

------
Is there anybody able to make sense of this? Is this is actually a jspm issue? is it a node.js instead? or is it the fact that jspm is using some unstable parts of node.js?

**Comment by guybedford** [comment]
Thanks for reporting. I’ll look into this as soon as I can.

**Comment by guybedford** [comment]
Moved to the jspm 2.0 repo.
