### ISSUE TITLE
import <url> will be replaced with "/npm:@jspm/node-builtins@1/@empty.js"

### ISSUE THREAD

**Issue by mantou132** [jspm/jspm-cli#2417]
**JSPM Version:** https://dev.jspm.io/

**Transpiler Plugin(s):** I do not use a transpiler

**Details:**
source code: https://github.com/mantou132/mt-music-player/blob/master/fe/lib/component.js#L1
jspm: https://dev.jspm.io/npm:mt-music-player@0.0.2/fe/lib/component.js

I don't quite clear if this question should be written here, if it is wrong, sorry.

**Comment by guybedford** [comment]
Thanks, yes full URLs are not currently supported. We should support them though. I've created an issue to track this at https://github.com/jspm/project/issues/43.

Rather try using a plain `'lit-html' import, including the declaration of the dependency in the package.json as you would normally with npm.

The other issue you will likely hit next is the lack of named exports support, but with some luck that will be coming soon here :)
