### ISSUE TITLE
jspm-artifactory-github issue

### ISSUE THREAD

**Issue by subbiah28062** [jspm/jspm-cli#2421]
**JSPM Version:** `$ jspm --0.17-beta`

We trigger our build in jenkins which cant access any public url. It can only access npm.company.com && github.company.com && artifactory.

Artifacrtory as cached github repositories as such  https://www.jfrog.com/confluence/display/RTF/VCS+Repositories

Is there a way we can configure github to access package from artifactory github.

Tried using jspm-artifactory-github like so:

1)
	jspm config registries.github.handler jspm-artifactory-github
	jspm config registries.github.remote https://artifacts.company.com/api/vcs/downloadTag/github.com/
2)
	jspm config registries.github.remote git@github.pie.apple.com:jspm/registry
	jspm config registries.github.maxRepoSize 0
	jspm config registries.github.handler jspm-artifactory-github
	jspm config registries.github.hostname https://artifacts.company.com/api/vcs/downloadTag/github.com
3)
	jspm config registries.github.handler jspm-artifactory-github
	jspm config registries.github.remote https://artifacts.company.com/

But neither of them worked. It ends up in timedout.

**Comment by guybedford** [comment]
If this is effectively like GitHub enterprise, I believe there is a configuration option for this in `jspm config github`?
