### ISSUE TITLE
JSPM not load Angular Library: EPERM: operation not permitted, open

### ISSUE THREAD

**Issue by DrGonzo84** [jspm/jspm-cli#2424]
**JSPM Version:** `0.16.53`

**Transpiler Plugin(s):** typescript 

**Details:**
I had an erron when i try to install "@angular/core" dependency. Same errors are throw with other @angular library. 

My command is: 
**jspm install @angular/core=npm:@angular/core** (I could also test=*** and angular-core=***)

My error is:
**Error: EPERM: operation not permitted, open 'C:\Users\dr\AppData\Local\.jspm\packages\npm\@angular\..." (etc etc)**

I don't know why this error occured. However:

1. Someone can help me? Please
2. It's possibile **disable cache** and download library directly in my local project folder?

Thank you

**Comment by guybedford** [comment]
Did you manage to make progress here? Closing for now with the 2.0 launch, but please reopen if this is still causing you issues.
