### ISSUE TITLE
Question: Bundling for production and CDN

### ISSUE THREAD

**Issue by scottc-netflix** [jspm/jspm-cli#2427]
@guybedford 

Basically I'm using SystemJS v0.19.46 and since it seems jspm doesn't yet support bundling for production for newer SystemJS I'm trying to find workarounds. I built a small node proxy that will cache the modules served by jspm, but I'm wondering if there's a way for me to generate these locally if jspm were to be unreachable and I needed to install a newer version of some package?

Alternately, is there any approach I could take, even if it requires some work, that would allow be to bundle dependencies. I may be able to help if I knew what is involved.

Really great work on SystemJS BTW! I'm able to do some really cool stuff like develop locally without having to `npm install`, and true dynamic loading of modules or features in my app that can share dependencies. Just trying to figure out how I can gain some more confidence to use in production.

**Comment by guybedford** [comment]
See jspm 2.0 for CDN bundling approaches. The release will be available at jspm.org tomorrow.

**Comment by guybedford** [comment]
To answer your questions a little more thoroughly:

> since it seems jspm doesn't yet support bundling for production for newer SystemJS I'm trying to find workarounds

jspm 2.0 supports native bundling for the latest SystemJS builds. Including the abililty to create maps against the SystemJS CDN URLs (although this is a somewhat undocumented workflow, so just ask me for help when you take a look at jspm 2.0).

> Alternately, is there any approach I could take, even if it requires some work, that would allow be to bundle dependencies. I may be able to help if I knew what is involved.

It would help a lot if you could clarify so I can understand the specific bundling scenarios you are after.

> Really great work on SystemJS BTW! I'm able to do some really cool stuff like develop locally without having to npm install, and true dynamic loading of modules or features in my app that can share dependencies. Just trying to figure out how I can gain some more confidence to use in production.

Thank you, it's been a lot of work. I hope the jspm 2.0 workflows demonstrate how to move to production better, and I'm happy to answer questions further.
