### ISSUE TITLE
jspm2 getting version 

### ISSUE THREAD

**Issue by javadbat** [jspm/jspm-cli#2455]
problem is simple `jspm -v` not work on jspm2 and say:

> err  Command or file -v does not exist.

**Comment by guybedford** [comment]
Since you asked so nicely :)

**Comment by guybedford** [comment]
Implemented in https://github.com/jspm/jspm-cli/commit/f341de10917cbebc49442b5489a86538081e7052

**Comment by guybedford** [comment]
Released in 2.0.0-beta.3.
