### ISSUE TITLE
import map don`t work properly for react 

### ISSUE THREAD

**Issue by javadbat** [jspm/jspm-cli#2456]
I try to create a sample react project with jspm2 and I install react with  `jspm i react ` command and then create a source map using `jspm map -o importmap.json` command and initiate as explained in
https://stackoverflow.com/questions/56007180/how-to-create-import-map-with-jspm2
the react downloaded successfully when I import it but i get following error in chrome:

> Uncaught (in promise) TypeError: Failed to resolve module specifier "object-assign/index.dew.js". Relative references must start with either "/", "./", or "../".

what should i do?

**Comment by guybedford** [comment]
@javadbat did you enable the Experimental Web Platform Features in Chrome?

**Comment by javadbat** [comment]
yes i do 
i create a github repo:
https://github.com/javadbat/systemjs2-boilerplate

**Comment by javadbat** [comment]
you can run it with npm run serve

**Comment by guybedford** [comment]
It seems like the problem here is that your import map is not being created with the `--flat-scope` option, which is necessary for Chrome support, as it doesn't yet support import maps scopes.

**Comment by javadbat** [comment]
thank you it work perfectly now
