### ISSUE TITLE
package.json jspm{} property dont work as explained in doc

### ISSUE THREAD

**Issue by javadbat** [jspm/jspm-cli#2457]
I try to use npm and jspm together and I follow https://jspm.org/docs/integrations#npm and add jspm{} to `module.json` but jspm still install the package on the npm dependency list.
you can try it in following branch of the repo :
https://github.com/javadbat/systemjs2-boilerplate/tree/jspm_package_list_issue
and run ` jspm i react`

**Comment by guybedford** [comment]
Thanks, yes if installing with npm then jspm this workflow doesn't work out (you'd need to install a jspm dependency first rather). I've updated the docs to make this always work out regardless of order.
