### ISSUE TITLE
Error with simple material-ui example

### ISSUE THREAD

**Issue by TobyEalden** [jspm/jspm-cli#2466]
```
$ jspm
2.0.0-beta.2
Running against local jspm install.
```
I get an error when attempting a basic material-ui integration:

```
index.dew.js:2 Uncaught (in promise) Error: Error converting CommonJS file is-plain-object/index.js, please post a jspm bug with this message.
ReferenceError: Unknown option: .format. Check out https://babeljs.io/docs/en/babel-core/#options for more information about options.
```

I made minor changes to the example in the guide, including using babel to transform JSX:
```
import React from "react";
import ReactDOM from "react-dom";
import clone from "lodash/clone.js";
import Button from "@material-ui/core/Button/index.js";

console.log(clone({ a: "b" }));

import("@babel/core").then(({ default: babel }) => {
  console.log(babel.transform("test").code);
});

const Hello = () => {
  return (
    <Button variant="contained" color="primary">HELLO WORLD</Button>
  );
};

ReactDOM.render(
  <Hello />,
  document.getElementById("root")
);
```

package.json:
```
{
  "name": "app",
  "dependencies": {
    "@babel/cli": "^7.4.4",
    "@babel/core": "^7.4.4",
    "@babel/plugin-syntax-dynamic-import": "^7.2.0",
    "@babel/preset-env": "^7.4.4",
    "@babel/preset-react": "^7.0.0",
    "@material-ui/core": "^3.9.3",
    "lodash": "^4.17.11",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
  },
  "devDependencies": {
    "@jspm/core": "^1.0.4",
    "es-module-shims": "~0.2.7",
    "jss": "^9.8.7",
    "systemjs": "^3.1.6"
  },
  "jspm": {},
  "scripts": {
    "compile": "babel src -d lib",
    "compile-watch": "babel src -d lib --watch"
  },
  "type": "module"
}
```

**Comment by guybedford** [comment]
Thanks for reporting this case, will do my best to track it down for you. Material UI should definitely work - it's tested as a sandbox example too.

If I try `jspm intall is-plain-object` on a fresh install, I can definitely see it works correctly when imported via `test.js` containing `import x from 'is-plain-object'; console.log(x)`.

If you try the same on a fresh project after clearing the cache (`jspm cc`) do you still get the error?

If so, what OS are you running?

**Comment by TobyEalden** [comment]
A fresh project using just `is-plain-object` as you describe does indeed work for me too.

I'll look into it further - just wondered if I was missing something obvious.

I'm running MacOS Mojave 10.14.4

**Comment by guybedford** [comment]
Ahh so the message might be wrong!

I will try your full replication then when I have a moment.

Another thing that might help too is seeing the full error stack since apparently we can't trust the message.

**Comment by TobyEalden** [comment]
A stripped down version of the sandbox example is working for me now, so I'm guessing it's some problem with the configuration in the other project.

```
import React from 'react';
import ReactDOM from 'react-dom';
import Button from '@material-ui/core/Button/index.js';

ReactDOM.render(
  React.createElement(Button.default, {
    variant: "contained",
    color: "primary"
  }, "HELLO WORLD"),
  document.getElementById('container')
);
```

I'll close this and re-open if necessary.

**Comment by guybedford** [comment]
I think this might have been due to the Babel conversion on install loading local configurations in the Babel conversion process. `babelrc: false` isn't enough to disable that, I've added all the opt outs I can now which fixed another similar install consistency issue in https://github.com/jspm/jspm-cli/commit/365674f76f8be49acb45fa05f0cfa17895d4cbaf.
