### ISSUE TITLE
jspm section in package.json

### ISSUE THREAD

**Issue by jbanety** [jspm/jspm-cli#2467]
Hi @guybedford,
I created several jspm packages that are used as dependencies for my main application.
With jspm 0.17 there was a jspm section in the package.json file.
With 2.0, when I install the jspm packages, the dependencies in the jspm section are not installed with.
Do I have to put these dependencies at the root of the package.json file? But I do not want them to be installed with `yarn install` because this packages are only for the front.

Thanks.

**Comment by guybedford** [comment]
jspm 2.0 still supports the `"jspm"` section in the package.json, where dependencies will be installed from and added to there.

Usually I do this via `echo '{ "jspm": { "dependencies": {} } }' > package.json` and then jspm install will always use that.

If there's a way you're doing this that isn't working or is behaving unexpectedly perhaps it's a bug or usability issue I haven't seen.

**Comment by jbanety** [comment]
When I install a package with dependencies in jspm section, these dependencies are not installed.

**Comment by guybedford** [comment]
Ahh, right, the `jspm` field is not being respected in dependencies. Yes, that is a bug!

**Comment by jbanety** [comment]
Can you explain where I have to investigate. If I can, I'll create a PR.

**Comment by guybedford** [comment]
The raw to structured package.json processing happens here - https://github.com/jspm/jspm-cli/blob/master/src/install/package.ts#L422.

It could be worth seeing if a preprocessing phase could copy down the jspm properties (noting that any of devDependencies, peerDependencies, etc should override all of them to be empty, that is dependencies are overridden as a group).

There may be some edge case complexities if this function is used in other scenarios / or in override handling, but we might be lucky with these.

**Comment by jbanety** [comment]
Hi @guybedford,
I think I fixed this issue in the @jspm/jspm-resolve package where the jspm section was not processed in the `processPjsonConfig` method.

**Comment by jbanety** [comment]
An other issue is the overrides in dependencies. They aren't considered. I have to add overrides section in the package.json of the final module.

**Comment by guybedford** [comment]
Do you mean the package.json "overrides"?

There's a central overrides file in jspm at https://github.com/jspm/jspm-cli/blob/master/src/overrides.ts where we can include common overrides that would be correct and useful to all users.

The other option is to directly support overrides being added on install from dependencies, and the machinery is mostly in place to support this quite easily.

I was always hesitant to implement this though for fear of conflicts opting instead for the central registry, but we could still reconsider this.

Overrides in dependencies applied on install, would effectively be propagating into the base-level package.json "overrides". It's like peer dependencies, where conflicts just need to be resolved when this happens, but other than that it's a fairly straightforward integration.

The risk as always is that installing a dependency can potentially break your other dependencies, and this is still the thing we need to weigh up against the benefits.

**Comment by jbanety** [comment]
Yes, it could be dangerous to apply overrides from dependencies.
Maybe we could print the packages with overrides to the user ?

**Comment by guybedford** [comment]
Would your overrides be suitable for inclusion in https://github.com/jspm/jspm-cli/blob/master/src/overrides.ts? This now replaces the previous jspm/registry.

I must admit I was kind of hoping we wouldn't need overrides all that often, and that they would just be a stop-gap more than anything.

**Comment by jbanety** [comment]
My overrides are just to use the correct ES module file in a package with overriding the `main` property.

**Comment by guybedford** [comment]
Do you mind sharing which package? What is the consequence of not using the override?

**Comment by jbanety** [comment]
My app is based on micro-service architecture.
I have built a scoped package named `ui` to  share ui components which depends on `vanilla-notify`.
The `main` property of `vanilla-notify` is set to a non-ES compatible file, so I override the `main`prop in the `package.json`.
Then, I have a `frontend` package wich depends on `ui`.
So when I run `jspm install` in `frontend`, I first wanted to have the `ui` overrides to pull up in the `frontend` but you're right in other case it can break other dependencies.

**Comment by guybedford** [comment]
So jspm should convert the CommonJS vanilla-notify into an ES module on install, making it effectively ES compatible. Is there a reason you can't rely on that process?

**Comment by jbanety** [comment]
I have this error :
```
err (jspm) Error: 'VanillaNotify' is not exported by jspm_packages/npm/vanilla-notify@0.1.20/vanilla-notify.js
``` 
with my code `import {VanillaNotify} from "vanilla-notify";`.
This is because I'm using the `VanillaNotify` class exported by `src/vanilla-notify.js`.
So you're right it is not a ES compatibility problem.

**Comment by jbanety** [comment]
But I always prefer to use vendor ES module file rather than the converted version.

**Comment by guybedford** [comment]
Does #2476 fix this because vanilla-notify is your own package, where you've added a "jspm" property just for jspm?

**Comment by jbanety** [comment]
Nop. This is for the main issue : https://github.com/jspm/jspm-cli/issues/2467#issuecomment-492703205

**Comment by guybedford** [comment]
Ahh right thanks.

So with these problems it's worth always putting in your mind first how we work this out under `node --experimental-modules`. Because the goal is to have one ecosystem not to split it.

And these problems are exactly what `node --experimental-modules` is grappling with right now (https://twitter.com/robpalmer2/status/1130367435020935170, https://twitter.com/MylesBorins/status/1128846502468751361).

There was a proposal to support named exports for CommonJS through a package.json declaration, which would be nice as it would be supported in overrides, but then could also be PR'd to the main repo and supported natively and in Node.js.

This is `namedExports` in jspm and I would still like to push for standardization on that, but we will see.

Otherwise, overriding the main can cause issues because say another dependency uses that version then they won't match up properly as discussed in Myles' thread.

I know ES modules have been pushed on their treeshaking benefits - is that the main reason you'd prefer to use the ES module version?

**Comment by irustm** [comment]
@jbanety 
I think you just need to use transpiler

**Comment by jbanety** [comment]
No need tout use a transpiler since i'm using native es6 in latest browser.

**Comment by irustm** [comment]
I'm about:
not working in latest browsers
```js
import { something } from 'es-module-package';
```
work:
```js
import something from 'es-module-package';
```

**Comment by jbanety** [comment]
And I'm using https://github.com/guybedford/es-module-shims for newer modules specifications.
