### ISSUE TITLE
ReferenceError: require is not defined

### ISSUE THREAD

**Issue by fusionstrings** [jspm/jspm-cli#2471]
I am getting following error while trying to follow following guide https://jspm.org/docs/integrations#rollup
```sh
➜  jspm-test jspm run build
ReferenceError: require is not defined
    at file:///Users/fusionstrings/jspm-test/jspm_packages/npm/rollup@1.12.1/bin/rollup:6:10
    at ModuleJob.run (internal/modules/esm/module_job.js:95:12)
```
Here is repository for reproduction https://github.com/fusionstrings/jspm-beta-issue-require-not-found
Below is compter configuration-

MacOS Mojave 10.14.4
```
➜  jspm-beta-issue-require-not-found git:(master) node -v
v10.15.0
➜  jspm-beta-issue-require-not-found git:(master) npm -v
6.4.1
➜  jspm-beta-issue-require-not-found git:(master) jspm -v
2.0.0-beta.3
Running against global jspm install.
➜  jspm-beta-issue-require-not-found git:(master) 
```

**Comment by guybedford** [comment]
I tried this and got the same error.

Then I ran `jspm cc && jspm install` and it worked for me.

After that I was getting some odd build errors, which turned out to be this bug - https://github.com/jspm/jspm-cli/commit/365674f76f8be49acb45fa05f0cfa17895d4cbaf.

Will post a patch release soon.

**Comment by guybedford** [comment]
Released in 2.0.0-beta.4.

**Comment by fusionstrings** [comment]
Thanks a lot 🤗

**Comment by guybedford** [comment]
Thanks for reporting issues, they only get fixed when they are reported!
