### ISSUE TITLE
The reason behind caching only the resolved versions

### ISSUE THREAD

**Issue by mancasg** [jspm/jspm-cli#2485]
Hello,

I'm interested in the reason the registry-manager caches the resolved package version [here](https://github.com/jspm/jspm-cli/blame/master/src/install/registry-manager.ts#L378) immediately after caching the entire range of versions [here](https://github.com/jspm/jspm-cli/blame/master/src/install/registry-manager.ts#L316). I see it as a bug, but maybe there's more to it.

The reason I ask is because I tracked an issue of failing installs up to the block in registry-manager.ts:378. Here I'm talking about a module with about 3000 dependencies with multiple versions of the same package. What happened was that the first package version was cached, leading to packages of different versions following it to fail with:

`err (jspm) No resolution found for npm:supports-color@^6.1.0.`

For our deployment I simply removed the async block in registry-manager.ts:378.

Looking forward to hearing from you.

**Comment by guybedford** [comment]
This is definitely a bug. So the cache behaves a bit weirdly but for good reason - basically there are two types of lookups - (1) a generic lookup of all versions for a given package name, and (2) a lookup of just a specific version range of a package name. These are separated because there may be bandwidth optimizations that can be made for (2). But both (1) and (2) will still take as an argument the full version cache for all versions, and return the updated cached object in both cases. Effectively they just work to different ranges (`*` v `^1` for example).

Rather I think what we might be seeing here is a cache access bug. The cache code can be prone to race condition and subtle timing issues. The tests in https://github.com/jspm/jspm-cli/blob/master/test/cache.js are designed to try and ensure we don't have these issues, but if you have 3000 dependencies with some repeat access on a particular package name, that sounds like the sort of thing that might discover a cache bug to me.

Can you share your test case for me to try debugging this further? Also out of interest, did you find the failures were sporadic or entirely repeatable everytime?

Help tracking this one down would be amazing - I'll put the time in to fix it here, as these sorts of issues are very important to catch.

**Comment by mancasg** [comment]
Hello again,

To replicate this I've installed some (pseudo)random modules. jspm gives the following output for some consecutive runs:
<details><summary>expand console output</summary>
<pre>
[root@georgem module-531]# npm install es6-plato eslint pacote mocha mochawesome snyk retire jsdoc esm gulp nyc karma jspm rollup rxdb undertaker

+ mocha@6.2.0
+ retire@2.0.3
+ pacote@9.5.4
+ snyk@1.195.1
+ jsdoc@3.6.3
+ esm@3.2.25
+ gulp@4.0.2
+ eslint@6.1.0
+ mochawesome@4.0.1
+ undertaker@1.2.1
+ karma@4.2.0
+ nyc@14.1.1
+ rollup@1.17.0
+ jspm@2.0.0-beta.6
+ es6-plato@1.1.6
+ rxdb@8.2.1
added 1743 packages from 1604 contributors and audited 212363 packages in 92.468s
found 2738 vulnerabilities (682 low, 2056 high)
  run `npm audit fix` to fix them, or `npm audit` for details
[root@georgem module-531]# rm -rf jspm* /root/.cache/jspm/
npx jsp[root@georgem module-531]# npx jspm install
warn (jspm) Deprecation warning for npm:kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
warn (jspm) Deprecation warning for npm:left-pad@1.3.0: use String.prototype.padStart()
err (jspm) No resolution found for npm:ms@2.0.0.
     Installing npm:debug@3.1.0.
     Installing npm:http-proxy-agent@2.1.0.
     Installing npm:make-fetch-happen@5.0.0.
     Installing npm:pacote@9.5.4.
     jspm process terminated.
[root@georgem module-531]# rm -rf jspm* /root/.cache/jspm/
[root@georgem module-531]# npx jspm install
warn (jspm) Deprecation warning for npm:kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
warn (jspm) Deprecation warning for npm:left-pad@1.3.0: use String.prototype.padStart()
err (jspm) No resolution found for npm:punycode@^1.4.1.
     Installing npm:tough-cookie@2.4.3.
     Installing npm:request@2.88.0.
     Installing npm:retire@2.0.3.
     jspm process terminated.
[root@georgem module-531]# rm -rf jspm* /root/.cache/jspm/
[root@georgem module-531]# npx jspm install
warn (jspm) Deprecation warning for npm:kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
/root/dev/jspm-race-issue/module-531/node_modules/proper-lockfile/index.js:186
    compromised = compromised || function (err) { throw err; };
                                                  ^

Error: Unable to update lock within the stale threshold
    at options.fs.utimes (/root/dev/jspm-race-issue/module-531/node_modules/proper-lockfile/index.js:108:66)
    at Object.utimes (/root/dev/jspm-race-issue/module-531/node_modules/proper-lockfile/lib/syncFs.js:17:9)
    at Timeout.lock.updateTimeout.setTimeout (/root/dev/jspm-race-issue/module-531/node_modules/proper-lockfile/index.js:99:20)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at unrefdHandle (timers.js:520:7)
    at Timer.processTimers (timers.js:222:12)
[root@georgem module-531]# events.js:174
      throw er; // Unhandled 'error' event
      ^

Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at process.target.send (internal/child_process.js:636:16)
    at callback (/root/dev/jspm-race-issue/module-531/node_modules/worker-farm/lib/child/index.js:32:17)
Emitted 'error' event at:
    at process.nextTick (internal/child_process.js:640:35)
    at process._tickCallback (internal/process/next_tick.js:61:11)
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at process.target.send (internal/child_process.js:636:16)
    at callback (/root/dev/jspm-race-issue/module-531/node_modules/worker-farm/lib/child/index.js:32:17)
Emitted 'error' event at:
    at process.nextTick (internal/child_process.js:640:35)
    at process._tickCallback (internal/process/next_tick.js:61:11)
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at process.target.send (internal/child_process.js:636:16)
    at callback (/root/dev/jspm-race-issue/module-531/node_modules/worker-farm/lib/child/index.js:32:17)
Emitted 'error' event at:
    at process.nextTick (internal/child_process.js:640:35)
    at process._tickCallback (internal/process/next_tick.js:61:11)
^C
[root@georgem module-531]# rm -rf jspm* /root/.cache/jspm/
[root@georgem module-531]# npx jspm install
warn (jspm) Deprecation warning for npm:kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
warn (jspm) Deprecation warning for npm:left-pad@1.3.0: use String.prototype.padStart()
err (jspm) No resolution found for npm:ms@2.0.0.
     Installing npm:debug@3.1.0.
     Installing npm:http-proxy-agent@2.1.0.
     Installing npm:make-fetch-happen@5.0.0.
     Installing npm:pacote@9.5.4.
   . Finalizing https://registry.npmjs.org/rxjs/-/rxjs-6.5.2.tgz#sha512-HUb7j3kvb7p7eCUHE3FqjoDsC1xfZQ4AHFWfTKSpZ+sAhhz5X1WX0ZuUqWbzB2QhSLp3DoLUG+hMdEDKqWo2Zg==
</pre>
</details>
As you can see, jspm errs every time (but to err is human...).


As for your second question, for our particular project the install failed every time, as it also does for the test scenario provided above.

**Comment by guybedford** [comment]
Yup, I can replicate that!

Thanks for the test case, will investigate further.
