### ISSUE TITLE
jspm link workflow polishing, resolution to be lockfile-specific

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#2489]
This is a tracking issue for the feature that:

```
jspm link ../path
```

should not reflect in the package.json (since the nature of linking is going against the package.json intent for instead following a local intent). Rather it should only represent the link in the lockfile.

In addition `jspm unlink` should properly revert to the previous package.json intent.

**Comment by fusionstrings** [comment]
I think jspm link should not be necessary if somehow monorepo can be detected the way `workspaces` key in package.json is used in yarn.
Please please please

**Comment by guybedford** [comment]
@fusionstrings it could certainly be possible to support the `workspaces` package.json field just like Yarn, but I would want to do it in a way that would effectively be built out of these primitives anyway... because these also open up other opportunities for monorepos, like a monorepo model where the base-package is still a publishable package, with GitHub submodules for the linkage (my ideal monorepo pattern for jspm itself).

So my focus for now continues to be getting the `jspm link` primitive right, then we can easily add the `"workspaces"` sugar in future for sure.

**Comment by fusionstrings** [comment]
Certainly I trust your vision more than anything. I do remember numerous discussions with you on what exactly is JSPM 2 when essentially it strips down the features from jspm0.16 and 0.17. 

And you have been right all along.

I would eagerly wait for this feature to be shipped.
