### ISSUE TITLE
GitHub packages support

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#2497]
It would be worthwhile to support GitHub packages at this point as its own registry.

Either `ghp:` or `gpr:` I forget which is the preferred abbreviation for it at the moment.

It's relatively straightforward to put this together, it's simply a matter that I don't personally have any good reason to need to do this yet.

If anyone is specifically interested in this feature please say so.

**Comment by fusionstrings** [comment]
I would like to have it. Not for me specifically but for community. If you may guide me how, I would like to land a PR.

**Comment by guybedford** [comment]
@fusionstrings a contribution here would be absolutely amazing, and it is certainly something I'd be very grateful if you could work on.

The model to follow would likely be the existing npm / GitHub registries - https://github.com/jspm/npm/blob/master/npm.js / https://github.com/jspm/github/blob/master/github.js.

The registry calls are done by returning an object, which provides an expected class constructor and class methods signatures.

It may also help to see the other side where these calls are made, which is all in the registry manager file at https://github.com/jspm/jspm-cli/blob/master/src/install/registry-manager.ts#L308.

If it would help you to work on this after ensuring the registry API is fully documented I'd be happy to try flesh that out with you too.

**Comment by fusionstrings** [comment]
Thanks a lot for guidance. I am gonna start with it and will ask questions if I will have any. :)
