### ISSUE TITLE
Error: Cannot find module (2.0.0-beta.7)

### ISSUE THREAD

**Issue by stz184** [jspm/jspm-cli#2516]
I am trying to install and use http-server with npmjs following the official guide:

```
jspm install http-server --dev
jspm_packages/.bin/http-server
```
The last command leads to the following error:

> file:///usr/lib/node_modules/jspm/node_modules/@jspm/resolve/loader.mjs:34
>     throw new Error(`Unable to load ${resolved}, as it does not have a valid module format file extension.`);
>           ^
> 
> Error: Unable to load /home/stz184/.cache/jspm/packages/86b948f523affdf85e9e06d1b2bbf1fe48f25cd90426be10fb240401917e0dc0/bin/http-server, as it does not have a valid module format file extension.
>     at resolve (file:///usr/lib/node_modules/jspm/node_modules/@jspm/resolve/loader.mjs:34:11)
>     at async Loader.resolve (internal/modules/esm/loader.js:97:29)
>     at async Loader.getModuleJob (internal/modules/esm/loader.js:243:17)
>     at async Loader.import (internal/modules/esm/loader.js:178:17)

I am getting the same result issuing ``jspm bin http-server``

I am using node v13.14.0 on Ubuntu machine.

**Comment by guybedford** [comment]
Hi @stz184 - thanks for trying this out. Since jspm 2 was released over a year ago and there was zero user interest I am no longer maintaining it, and am rewriting everything for jspm 3. I'd suggest following on Twitter for updates in the coming month or two.
