### ISSUE TITLE
PageSpeed Insights Optimization

### ISSUE THREAD

**Issue by djindjic** [jspm/jspm-cli#267]
I'm testing my jspm sample in production. JSPM mode is **remote** with **depCache** enabled. I have made test domain http://jspm-sample.tk and start google pagespeed test and get [**this results**](https://developers.google.com/speed/pagespeed/insights/?url=jspm-sample.tk).

So there is a few suggestions and I'm not sure is it something that I could setup by my side or some cdn server side config is needed.

1.
These three files are flagged as render-blocking javascript:
- http://jspm-sample.tk/jspm_packages/system.js
- http://jspm-sample.tk/jspm_packages/es6-module-loader.js
- http://jspm-sample.tk/config.js

2.
- https://github.jspm.io/angular-ui/ui-router@0.2.10/release/angular-ui-router.js
- https://github.jspm.io/driftyco/ionic-bower@1.0.0-beta.13/css/ionic.css
- https://github.jspm.io/driftyco/ionic-bower@1.0.0-beta.13/js/ionic-angular.js
- https://github.jspm.io/driftyco/ionic-bower@1.0.0-beta.13/js/ionic.js

above files are configured in registry [here](https://github.com/jspm/registry/blob/master/package-overrides/github/driftyco/ionic-bower%401.0.0-beta.13.json) and [here](https://github.com/jspm/registry/blob/master/package-overrides/github/angular-ui/ui-router%400.2.12.json) by me, and what should I to do to get it minified in production? I could reference to bower minified files but I've understood [here](https://github.com/jspm/jspm-cli#2-creating-a-dependency-cache) that jspm cdn could minify it automatically?

3.
http headers of these four files are configured as **cache-control:max-age=10, public** but not **max-age=604800** (or maybe all files should be max-age=315360000 instead of 604800 as CDN is setup now?)
- https://github.jspm.io/driftyco/ionic-bower@1.0.0-beta.13.js
- https://github.jspm.io/driftyco/ionic-bower@1.0.0-beta.13/css/ionic.css
- https://github.jspm.io/driftyco/ionic-bower@1.0.0-beta.13/js/ionic-angular.js
- https://github.jspm.io/driftyco/ionic-bower@1.0.0-beta.13/js/ionic.js

**Comment by pmadruga** [comment]
Moving the files to the end of <body> didn't fix the trick. Do you have any other ideas @guybedford ? Thanks in advance.
