### ISSUE TITLE
Package management for Meteor-agnostic packages in Meteor, using jspm.

### ISSUE THREAD

**Issue by trusktr** [jspm/jspm-cli#275]
Hi @guybedford There's some discussion at https://github.com/raix/Meteor-community-discussions/issues/1 on preventing from having to create wrapper packages for meteor-agnostic libraries. Nothing technical yet, just ideas. Meteor is so nice, but since it uses it's own package management system, every meteor-agnostic package has to be wrapped in a Meteor package then shipped on atmospherejs.com. I'm still learning about Meteor myself, so I'm not ready to try to propose a working solution, but I have a feeling jspm might be the tool to use for this. I just wanted to open this issue to have an official place for discussion if needed.

**Comment by guybedford** [comment]
Closing for now as there is nothing active happening here, but a Meteor endpoint would be very interesting to explore at some point in future (@crisptrutski).
