### ISSUE TITLE
Documentation Improvements

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#323]
Need a comprehensive documentation on the website or wiki. Then the README should be simplified to just a quick start / overview.

* Include info on how to publish including what package.json properties to set for publishing, whether to publish ES6 directly, whether to publish to npm or GitHub.
* `jspm run`
* ~~`baseURL` and how to set it for client and server.~~
* jspm API / nodeJS usage documentation.
* ~~Dev documentation for how to clone and modify jspm and related projects.~~ (https://github.com/jspm/jspm-cli/issues/461)

Generally we should aim to ensure the full API surface area is documented usefully.

**Comment by guybedford** [comment]
Look at centralising information on jspm in one place.

**Comment by guybedford** [comment]
Document common catches:

* Dependencies not downloading
* `directories.lib` not applying
* `files` removals
* Treating a github repo as an npm repo.

We need to build up "package configuration scenarios / faqs".

**Comment by guybedford** [comment]
Document the version constraint solver algorithm concepts.

**Comment by guybedford** [comment]
We also need to update and check the es6 demo repo again.

**Comment by trusktr** [comment]
With my project, now that I've got the initial workflows done, I'm going to finish the functionality of the current components, then generate docs using inline comments somehow, and write them as I go.

**Comment by guybedford** [comment]
Better document custom endpoints, including third-party endpoint listing. this can be linked to as the "Endpoint API" info, instead of the technical info.

**Comment by guybedford** [comment]
All of these have been covered now in Wiki guides.
