### ISSUE TITLE
Sometimes npm:package doesn't work the first time, but works the second time.

### ISSUE THREAD

**Issue by trusktr** [jspm/jspm-cli#333]
I'm on commit 730b64c28cedfe6051de98a815eab383915fbc43.

I was testing out `"format": "es6"` as per #321. After having updated my `army-knife` package from 0.0.2 to 0.0.4 on npmjs.org (I unpublished 0.0.3 to discover I can't put it back), I tried running `jspm install army-knife=npm:army-knife@^0.0.2`, but it wouldn't work unless I ran it twice in a row:

![](http://i.imgur.com/lIabEHL.png)

**Comment by trusktr** [comment]
@guybedford My package.json is symlinked to jspm.json because my project has a package.json one level up in the filesystem, so I wanted to use jspm.json for jspm so as not to have two package.jsons.

For example,

```
project/
|
├ package.json
└ public/
  ├ package.json -> jspm.json
  └ jspm.json

**Comment by guybedford** [comment]
Yes jspm generates the `.jspm.json` file for installed packages once. It is used only for packages contained in `jspm_packages`. I'm not sure I follow why it exists in your public folder or needs to, but symlinking it is a bad idea as it is used for looking up dependency ranges on installs.

If you want to have a package.json for browser and server use, this is what the `jspm` prefix in the package.json allows - you can have server dependencies for npm at the base and jspm dependencies on top that override in jspm.

**Comment by guybedford** [comment]
@trusktr if you can share something that I can reproduce here let me know.

**Comment by trusktr** [comment]
SUre. I believe you should be able to just clone [my repo](https://g.trusktr.io/trusktr/portfolio), go into the public folder, then run one of the above commands repeatedly.

**Comment by guybedford** [comment]
I just ran this 4 times and it worked fine. Was there a specific error reported, or did this just time out?

**Comment by trusktr** [comment]
There was no errors, and no timeouts, all commands finished quickly, 4 outputs. Seems odd right? Maybe it was a bug with the cache system? i'm unable to reproduce it anymore.

**Comment by guybedford** [comment]
Ok. If you didn't get an `install complete` message this sounds like a duplicate of https://github.com/jspm/jspm-cli/issues/346.
