### ISSUE TITLE
jspm not installing the latest versions of packages.

### ISSUE THREAD

**Issue by trusktr** [jspm/jspm-cli#334]
On commit 730b64c28cedfe6051de98a815eab383915fbc43.

I've got, f.e. `^0.0.5` of npm:infamous in my package.json and infamous is 0.0.7 on npmjs.org, but `jspm install` installs 0.0.5. I've also got `^0.0.4` of npm:army-knife in package.json but jspm is installing both 0.0.2 and 0.0.4. This might be related to #333.

**Comment by trusktr** [comment]
@guybedford I thought `^0.0.2` means use the latest `0.0.x`?  So if `0.0.4` is the latest, wouldn't `^0.0.2` cause `0.0.4` to be used?

**Comment by trusktr** [comment]
It seems that `npm install --save` saves version using `^`. Would you recommend I replace them all with `~`?

**Comment by trusktr** [comment]
jspm also uses the `^` by default. It seems like you recommend I use `~` but npm and jspm are both using `^` by default?

**Comment by guybedford** [comment]
`^` is the thing to do. The solution here is to post `0.1.0` as the first version of everything you publish and never to `0.0.x` versions.

**Comment by trusktr** [comment]
I see what you mean. Why is that? What happens with 0.0.x?

**Comment by guybedford** [comment]
It's the rules of semver compatibility, see https://github.com/npm/node-semver#caret-ranges-123-025-004.

**Comment by trusktr** [comment]
Ah, thanks. That was what I was missing. Some other articles were confusing.

*/#!/*JoePea
