### ISSUE TITLE
jspm register registry function

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#336]
`jspm register jquery github:components/jquery`

Sends a PR to the jspm registry with a new / modified entry.

**Comment by trusktr** [comment]
This will indeed be great. bower has it's own thing like this, so definitely this will help make things easier. Nonetheless, I do believe there will be cases where people will want to override the registry overrides.

+1 for jspm.overrides in package.json.

**Comment by trusktr** [comment]
Just wanted to note: bower allows devs to add a package to the bower registry without needing a PR (or maybe PRs are automatically merged). It's first come, first serve.

**Comment by trusktr** [comment]
Would `jspm register override` and `jspm register name` replace an item if it already exists?

**Comment by guybedford** [comment]
Perhaps we can consider having additions being sent through an API that ensure they are always merged instantly so we get the same behaviour as Bower and npm.

But a PR would always be needed for overrides or adjustments of existing entries.

**Comment by trusktr** [comment]
Yeah, that'd be nice. Bower has a thing where a package can only be modified by the owner of the git repo, and to do so requires providing an API key.
