### ISSUE TITLE
jspm install error on v0.10

### ISSUE THREAD

**Issue by trentgrover-wf** [jspm/jspm-cli#343]
I get this on jspm install with jspm v0.10.0
```
err  Error looking up npm:URIjs
    SyntaxError: Unexpected end of input
```
If I revert to jspm v0.9.0, the error disappears.

**Comment by guybedford** [comment]
For now, I've removed the authentication deprecation when changing jspm versions (https://github.com/jspm/npm/commit/e203ec26483019311150e276331d3a23714c4f01). Let me know if you notice any other issues like this.
