### ISSUE TITLE
apply lib, files and ignore before endpoint build

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#345]

**Comment by guybedford** [comment]
Will allow link to support files and ignore, making it quicker.

**Comment by andreasgrimm** [comment]
with regards to jspm linking speed, is this one still scoped to be in the v0.16 release?

**Comment by guybedford** [comment]
No, this is not currently being prioritised.

**Comment by guybedford** [comment]
This is covered by jspm 0.17 now.

**Comment by joeldenning** [comment]
When is 0.17 planned for release? This issue has caused me a lot of waiting time for linking. To illustrate, here's an example of the type of bash I've been writing as a workaround :D
```bash
npm run build && rm -rf ~/joel-cache && mkdir ~/joel-cache && mv node_modules ~/joel-cache && npm install --production && 
jspm link npm:engagements-menu@latest -y && cd ../end-user-forms-ui && jspm install npm:engagements-menu@latest --link && 
cd ../engagements-menu && rm -r node_modules && mv ~/joel-cache/node_modules .
```

**Comment by guybedford** [comment]
The goal is to get an alpha out this month, for a stable release next month, but we will have to see how things work out.
