### ISSUE TITLE
Bundled ES6 doesn't load correctly unless traceur-runtime explicitly loaded

### ISSUE THREAD

**Issue by theefer** [jspm/jspm-cli#350]
I tried the new feature of letting SystemJS determine when to load traceur-runtime.

That doesn't seem to work when `jspm bundling` an ES6 source. I can see traceur-runtime being loaded right after the bundle, however I get the following error on the console:

```
Uncaught TypeError: Error loading "js/main" at https://my-server/assets/js/main.js
Error loading "build" at https://my-server/assets/build.js
Cannot read property 'build' of undefined
```

where `build.js` depends on `$traceurRuntime`.

Is it come issue with the execution order perhaps?

**Comment by theefer** [comment]
Note that explicitly loading traceur-runtime.js before system.js fixes the issue.

**Comment by guybedford** [comment]
Thanks - I've included a fix in https://github.com/systemjs/systemjs/commit/86be859eaaef2989c7e6f7e595114dd0805bb4fb, and posted out a patch release.

If you just do `jspm dl-loader` it will update the loader files.

**Comment by theefer** [comment]
Great that fixed it thanks!

:+1:
