### ISSUE TITLE
Bundled angular dependency no longer loads

### ISSUE THREAD

**Issue by theefer** [jspm/jspm-cli#351]
When bundling a simple module that depends on angular 1.3.5 with jspm 0.10.3, the resulting bundle no longer loads correctly. The same setup works fine with jspm 0.9.0.

Given the following module:

``` javascript
// js/test.js
import angular from 'angular';
console.log(angular);
```

Running `jspm bundle js/test --inject` and trying to import the bundled module with:

``` html
<script>
System.import("js/test").catch(function(error) {
  setTimeout(function(){ throw error; });
});
</script>
```

fails with the following error:

```
Uncaught ReferenceError: Error loading "js/test" at https://the-server/assets/js/test.js
Jf is not defined
```

In the `build.js`, I can see the error line:

``` javascript
    this["Jf"] = Jf;
```

where Jf is a variable that is not bound in that scope (it is bound in an inner scope above).

There seems to be something going wrong in the detection of globals, as lots of internal variables are getting exported (and failing), whereas previously only the `angular` global was being exported.

**Comment by guybedford** [comment]
Thanks, this has been fixed in SystemJS Builder 0.5.2 (https://github.com/systemjs/builder/commit/4b42d6dd628f5ad331d45ea4090db6e2af16354f).

**Comment by theefer** [comment]
Excellent, that was the last remaining issue for us to upgrade to jspm 0.10, works nicely now, thanks a lot!

**Comment by guybedford** [comment]
Nice, that is great to hear these upgrades haven't been too painful. Appreciated for catching these critical points so quickly, has helped a lot.
