### ISSUE TITLE
override conflicts with npm/browserify usage?

### ISSUE THREAD

**Issue by trusktr** [jspm/jspm-cli#352]
I've come up on a issue. I've been using my npm packages with jspm, so in my package source files I can have something like

```js
import Surface from 'famous/core/Surface'
```

This works with jspm because in the override I specify 

```
"directories": { "lib": "src" }
```

so it puts the source files at the root of the package folder, and `famous/core/Surface` works. Now I'm testing my libraries to make sure they are consumable, so first I'm trying with browserify. I install infamous by doing

```
npm install infamous --save
```

which results in a simple package.json like

```json
{
  "dependencies": {
    "infamous": "^0.0.10"
  }
}
```

then in a the project's `src/app.js` I have

```
var Molecule = require('infamous/dist/Molecule') //  you might foresee the problem here
console.log(new Molecule)
```

Now I use browserify to make a bundle by doing

```
browserify src/app.js -o public/app.js
```

which results in the error

```
Error: Cannot find module 'famous/core/Modifier' from '/Users/josephpea/test/infamous-with-browserify/node_modules/infamous/dist'
```

and this is because the string `"famous/core/Modifier"` refers to a file that doesn't exist. I can temporarily work around it by manually changing the import statements in the source of infamous after installing it.

Any recommendation on how can we handle this? I like using `"famous/core/Modifier"`. I could settle with just changing all the statements to the form `"famous/src/core/Modifier"`, but it doesn't look as nice. Is there another way you might know of that wouldn't require changing the import statements?

**Comment by trusktr** [comment]
Ok, I found the solution. I don't like having to do it, but it works: I added the [famousify](https://github.com/FamousTools/famousify) transform to my package's devDependencies as well as

```json
  "browserify": {
    "transform": [
      "famousify"
    ]
  },
```

to the package.json. This automatically handles the `src` issue in the requires for browserify. It's kind of bad IMHO to make projects have to depend on transforms, so I opened an issue for it at https://github.com/substack/node-browserify/issues/1050.

**Comment by guybedford** [comment]
That does seem like the best solution for now. Support of browserify transforms in jspm is tracked at https://github.com/jspm/npm/issues/10.

Also, did we consider using famous from npm for jspm? If other projects rely on famous, the npm registry may be a better option.

**Comment by trusktr** [comment]
@guybedford I think famous from npm is best, but in my case I'm using a custom branch from my for on github that isn't published on npm, and giving it registry:"npm".
