### ISSUE TITLE
error with minified bundle

### ISSUE THREAD

**Issue by djindjic** [jspm/jspm-cli#353]
Could you guys @guybedford and @EisenbergEffect take a look to this issue:

In project with [aurelia di](https://github.com/aurelia/dependency-injection) I have found some strange error after bundling my code with --minify argument. Without bundling or bundle to "not-minified" file everything works correctly. Here is my sample repo to show this behavior:
https://github.com/djindjic/jspm-bundle

jspm command which I use is:
```bash
jspm bundle app/app bundle-3.js --inject --minify
```

Console error:
![image](https://cloud.githubusercontent.com/assets/1564068/5607595/97712d66-9461-11e4-8fe4-ddbc52fc9355.png)

Also, if I comment [this line](https://github.com/djindjic/jspm-bundle/blob/master/lib/app.js#L4), there is no errors but this is functionality which I need. :)

**Comment by guybedford** [comment]
Which line is the issue happening on that is saying `Cannot redefine property: name`? I guess it would help to know what object it is trying to define `name` onto.

**Comment by djindjic** [comment]
Have I understood your question right, line in dependency injection code base?
I dont know how to get this line because without minify there is no error thrown but minified throws this exception shown at print screen above.

**Comment by djindjic** [comment]
I think there is not this informations. I have publish this on gh pages where you can see this console error:

http://djindjic.github.io/jspm-bundle/

**Comment by guybedford** [comment]
That error shows up as being in https://github.com/aurelia/dependency-injection/blob/master/src/util.js#L2.

This seems like a minification bug in that code in aurelia.

**Comment by djindjic** [comment]
Yes its probably aurelia minify bug, but can you tell me how did you get this line from dev tools? I know its so essential,  but I dont know to find it

**Comment by guybedford** [comment]
I just clicked the error line - http://djindjic.github.io/jspm-bundle/bundle-4.js:1:3749. That goes into the minified source. Clicking the brackets unpacks the source (source maps don't show for direct execution bugs unfortunately). Then I just back-tracked to see the System.register module name the code was in.
