### ISSUE TITLE
6to5 vs Traceur as default

### ISSUE THREAD

**Issue by geelen** [jspm/jspm-cli#354]
With the discussion in https://github.com/systemjs/systemjs/issues/232 and what seems to be some success in https://github.com/ModuleLoader/es6-module-loader/issues/278, I'm wondering how the choice of 6to5 or Traceur fits into plans for JSPM. Would you see 6to5 becoming the default, or will it require the user makes an explicit choice between them on `jspm init`?

**Comment by matthewp** [comment]
Instead of SystemJS loading @traceur it could load @es6compiler or something like that. The choice can be made with a simple map. `System.map["@es6compiler"] = "@6to5"; `

**Comment by guybedford** [comment]
Yes jspm would wrap this with an option on init.

We're still a little way away as I need to restructure the loader files etc around this switch. Working on it!

**Comment by hemanth** [comment]
Came here to post the same! Waiting to see `6to5` as default. :+1:

**Comment by fusionstrings** [comment]
:+1:

**Comment by capaj** [comment]
@geelen just out of curiosity what are the advantages to having 6to5 instead of traceur? Is it lighter/faster? Has more readable output?

**Comment by Alxandr** [comment]
@capaj It has a lot more readable output at least. And it does not require a runtime.

**Comment by aeosynth** [comment]
@Alxandr it requires a browser polyfill, which is basically a runtime.

http://6to5.org/docs/usage/polyfill/

> 6to5 includes a polyfill that includes a custom regenerator runtime and core.js.

**Comment by Alxandr** [comment]
I've never used said polyfill. Though, I have't used all features of 6to5 either...

**Comment by fusionstrings** [comment]
- 6to5 has highest coverage- http://kangax.github.io/compat-table/es6/
- Pollyfills as name suggest will go away once the browser/s start supporting particular feature. 
- Generates more readable output.
- Only closest transpiler is Traceur.

I don't think these points are insignificant.

**Comment by capaj** [comment]
@fusionstrings thanks.

**Comment by tinkertrain** [comment]
What @fusionstrings said.

**Comment by photusenigma** [comment]
+1 what @fusionstrings said.

**Comment by interactionist** [comment]
+1 @fusionstrings

**Comment by hipertracker** [comment]
+ 6to5 can also transpile  React JSX files

**Comment by interactionist** [comment]
Does jspm already reflect the systemjs@12.0 aka 6to5 support?

**Comment by twhitbeck** [comment]
@interactionist I don't think it does, yet. I just did an `npm update -g` to get the latest jspm, and a `jspm init`, and it downloaded SystemJS v0.11.3

**Comment by interactionist** [comment]
Yes. I just did the same :)

**Comment by auser** [comment]
Has the new release dropped yet?

**Comment by hipertracker** [comment]
[package.json](https://github.com/jspm/jspm-cli/blob/master/package.json) is still pointing to old Traceur :( I hope jspm will work with new, 2x faster  6to5 [v3.0](http://6to5.org/blog/2015/01/27/2to3/)

**Comment by sebmck** [comment]
@hipertracker 2x faster than previous 6to5 versions, not 2x faster than Traceur.

**Comment by SekibOmazic** [comment]
+1!

**Comment by guybedford** [comment]
This is in and working, just doing final testing and working on other bugs, then the release should follow soon.

**Comment by matthewp** [comment]
Why should 6to5 be the default?

**Comment by guybedford** [comment]
I've retained Traceur as the default through-out with 6to5 as an opt-in through the `jspm init -p` prompts or doing `jspm dl-loader --6to5`.

**Comment by hipertracker** [comment]
`jspm dl-loader --6to5` created only jspm_modules folder with files. It does not create package.json. And `jspm init -p` does not ask for 6to5. The same with `jspm init -p --edge`. So how to use it?

**Comment by guybedford** [comment]
@hipertracker ensure you're using jspm@0.11.0, try checking with `jspm -v`.

**Comment by interactionist** [comment]
@hipertracker ```npm install -fg jspm@0.11.0``` maybe you need to sudo

**Comment by hipertracker** [comment]
My system was messed with ios and two other node version installed with nvm. Now it works. Tnx

**Comment by interactionist** [comment]
```
     Using loader versions:
       es6-module-loader@0.12.0
       systemjs@0.12.1
       6to5@3.1.1
ok   ES6 transpiler set to 6to5.
```

awesome work @guybedford

**Comment by hipertracker** [comment]
Is it possible to pass additional parameters to 6to5 transpiler in jspm? E.g. experiment and background (https://6to5.org/docs/usage/options/

**Comment by guybedford** [comment]
@hipertracker yes you can set these via `to5Options` in the configuration file.

**Comment by tinkertrain** [comment]
Fantastic work, thanks @guybedford !

**Comment by SekibOmazic** [comment]
Is it possible to set `mangle` option from command line? Something like this:

```Shell
jspm bundle-sfx lib/app --minify --mangle=false
```

**Comment by guybedford** [comment]
@SekibOmazic there's a PR waiting for that here - https://github.com/jspm/jspm-cli/pull/450.

**Comment by martinmicunda** [comment]
@guybedford The `6to5-polyfill.js` is not loaded trough `system.js` is that correct behaviour?  At the moment I have to add this library to my `index.html` manually.

**Comment by guybedford** [comment]
@martinmicunda yes the polyfill isn't added automatically. This is tracking at https://github.com/systemjs/builder/issues/55.

**Comment by douglasduteil** [comment]
Hi @guybedford 
I think no parser/transpiler must be default in jspm/SystemJS. So If you're running in a full ES5 project or in a "ES6-ready" browser you don't have to worry about it.
Then traceur/6to5 can directly come from your current `node_modules` and SystemJs can access to it with the options : 

```js
System.config({
  transpiler: {
    name: '6to5',
    options: { experimental: true },
    path: 'node_modules/6to5/browser.js'
  }
})
```

**Comment by mrspeaker** [comment]
Is 6to5 support working (or have I just bodged something)? I run a clean `jspm init`, choosing 6to5 as the transpiler. It downloads the correct 6to5 files, but when I go to import an ES6 script (`System.import("lib/main")`) it tries to load `/jspm_packages/traceur.js` and because Traceur is not there, it 404s and doesn't load anything.

If I do `jspm dl-loader` it says the loader versions are:

       es6-module-loader@0.13.0
       systemjs@0.13.1
       6to5@3.3.12

**Comment by douglasduteil** [comment]
@mrspeaker Did you set  your  `System.transpiler` to `6to5` following the [Getting Started](https://github.com/systemjs/systemjs/tree/bb21404700c510ddf22a659f39f33ccbc436f433#getting-started) ?

**Comment by mrspeaker** [comment]
Thanks @douglasduteil - sorry, I totally missed that one. Works like a charm.
