### ISSUE TITLE
"registry":"npm" prevents directories.lib from working.

### ISSUE THREAD

**Issue by trusktr** [jspm/jspm-cli#355]
If I run this

```
jspm install -y infamous=npm:infamous@^0.0.10 -o '{ registry: "npm", "directories": { "lib": "src" } }'
```

then the directories property isn't being applied. If I run

jspm install -y infamous=npm:infamous@^0.0.10 -o '{ "directories": { "lib": "src" } }'

without the registry property, then the directories property works. I know it's obvious that we're installing an npm package due to the `npm:` prefix at the beginning, but I think it should still work even if the redundant registry property is there, to make things more frictionless.

**Comment by guybedford** [comment]
The `directories` property doesn't apply when using the `npm` registry because of the fact that publishing to npm doesn't support it. This is because we need to support requires working the same way between the two.

**Comment by trusktr** [comment]
@guybedford  I just wanted to do `import <module> from 'infamous/<module>'` instead of `import <module> from 'infamous/src/<module>'` everything single time. How would I do this with an npm package, while keeping everything in the `src` folder for organization?

**Comment by guybedford** [comment]
This is an npm problem, not something jspm should worry about. It seems sensible that `npm` could support `directories.lib` or something similar, but it doesn't. I'd suggest asking about this as a feature of npm if you're interested but there's nothing I can do this side.

**Comment by trusktr** [comment]
@guybedford Well, in NPM turns out this is quote easy with the scripts.postinstall property of package.json. I can move everything out of src with the postinstall scripts, but currently I'm using it to compile everything to CJS outside of src so browserify and webpack can work with it.

What about support jspm.scripts.postinstall? f.e.

```js
{
  "name": "example",
  "version": "1.2.3",
  "jspm": {
    "scripts": {
      "postinstall": "mv src/* ./"
    }
  }
}
```

**Comment by trusktr** [comment]
Just for reference, this is why I'd like to keep actual code in the `src` folder:

![screen shot 2015-01-08 at 2 23 09 pm](https://cloud.githubusercontent.com/assets/297678/5672083/36961964-9742-11e4-8d8f-892c141aceda.png)

There's lots of bookkeeping and build files in the root.

**Comment by theefer** [comment]
@guybedford I think I observed this behaviour with theseus (which has `{jspm: {directories.lib: "src"}}` in its `package.json`):

`jspm install theseus=github:argo-rest/theseus` correctly applies `directories.lib` (I only get the contents of the `src` dir).

`jspm install theseus=npm:theseus` doesn't seem to apply `directories.lib` (I get the whole package, not just `src`).

If I understand correctly, this is the expected behaviour?

It's slightly annoying that switching endpoint breaks the remapping, and that `directories.lib` can't be used by npm, but I assume there's a good reason for it?

**Comment by guybedford** [comment]
@theefer we need to match npm behaviour for npm packages, otherwise this will lead to unexpected results.

But we do have https://github.com/jspm/npm/issues/35 which is to support `directories.lib` if it is specifically `jspm.directories.lib` in the package.json.

**Comment by theefer** [comment]
Looks like https://github.com/jspm/npm/issues/35 would solve my issue!
