### ISSUE TITLE
Save overrides in package.json, jspm.overrides

### ISSUE THREAD

**Issue by trusktr** [jspm/jspm-cli#356]
In making [infamous](https://www.npmjs.com/package/infamous) consumable for all types of workflows (browserify, webpack, jspm, etc) I've really come to realize that being able to quickly persist overrides somewhere locally inside a project would be very nice. Ideally, the best things to happen would be for all devs to put a jspm property in their package.json. The second best things would be for overrides to exist in the jspm registry. Even if those two cases are 100% satisfied for all JavaScript packages known to mankind, there will still be cases where people want to make custom overrides to tweak the behavior of a package. Sure, it's possible to make a custom registry, and this is great for organizations. But for an individual who just wants to start using jspm and have a working setup in less than an hour, a custom registry is too much friction.

To make things as frictionless as possible, I really believe that being able to save overrides in jspm.overrides of a project's package.json (or somewhere just as easy) would make things the most frictionless.

It might look something like this:

```js
{
  "jspm": {
    "directories": {
      "packages": "party/jspm"
    },
    "configFile": "jspm_config.js",
    "dependencies": {
      "infamous": "npm:infamous@^0.0.10"
    },
    "overrides": {
      "infamous": {
        "directories": {
          "lib": "src"
        }
      }
    }
  }
}
```

I see the need for this. Maybe it doesn't belong in package.json, but it I think it definitely belongs somewhere local to a package, somewhere, somehow.

Related issues: https://github.com/jspm/jspm-cli/issues/136, https://github.com/jspm/jspm-cli/issues/149, https://github.com/jspm/jspm-cli/issues/164, https://github.com/jspm/jspm-cli/issues/174, https://github.com/jspm/jspm-cli/issues/288, https://github.com/jspm/jspm-cli/issues/336

**Comment by guybedford** [comment]
Yes this might make things a lot simpler.

Also, you could test the overrides until everything works, and then jspm could automatically send them:

```javascript
jspm register-overrides
```

Could read the package.json `overrides` property and post the overrides out as a PR.

This could certainly replace the `-o` workflow.

Would be interested to hear what others think.

**Comment by trusktr** [comment]
Yeah, that'd be cool, because then it'd be easy to test a branch from github containing the override (a mini registry if you will) then just `jspm register-overrides` when ready.

Then question is, would anyone be able to override anyone else's overrides?

**Comment by guybedford** [comment]
Yes overrides just combine and the PR is the composed changes.

**Comment by trusktr** [comment]
PR: https://github.com/jspm/jspm-cli/pull/370
