### ISSUE TITLE
Error loading "css" at http://localhost:3000/css.js

### ISSUE THREAD

**Issue by trusktr** [jspm/jspm-cli#357]
I'm trying

```
jspm install -y famous=npm:famous -o '{ "directories": { "lib": "src" }, "dependencies": { "css": "jspm:css@^0.1.0" }, "shim": { "*/*": { "deps": ["../core/famous.css!"] } } }'
```

from scratch with no jspm_packages, config.js, or package.json. When I run in browser, I'm getting the error

```
GET http://localhost:3000/css.js 404 (Not Found)
Potentially unhandled rejection [5] Error loading "npm:famous@11.18.0/core/famous.css!css" at <unknown>
Error loading "npm:famous@11.18.0/core/famous.css!css" from "app" at http://localhost:3000/app.js
Error loading "css" at http://localhost:3000/css.js
Not Found: http://localhost:3000/css.js (WARNING: non-Error used)
```

Note, in the error is shows `npm:famous@11.18.0/core/famous.css!css` but in my code I have `var style = require('famous/core/famous.css!')`. My code is probably redundant since loading famous modules should load the CSS based on the above override, but the expected behavior here (assuming I get past this error) would be that it doesn't load the style again, and just gives me the cached result.

**Comment by guybedford** [comment]
This type of override isn't going to work unfortunately.

That is, `css` is being altered to be a non-npm dependency of an npm package, which isn't something that is supported for npm overrides.

How does this same code work directly through npm? It would be interesting to look at how we can provide css compatibility with browserify and webpack approaches published to npm, and it may involve some manual work in jspm-npm as opposed to being done at the override level.

**Comment by trusktr** [comment]
> That is, css is being altered to be a non-npm dependency of an npm package, which isn't something that is supported for npm overrides.

It actually worked. Seems like jspm:css what installed anyway. I don't see why this should not be allowed. Having flexibility is nice. I'd agree for it not being default behavior, but if it is forced like in this example, then why not? Ultimately the files will simply exist in the file system, and loaded in the browser.

**Comment by trusktr** [comment]
Using `jspm:css` in that override indeed does install github:systemjs/plugin-css. config.js even contains `"css": "github:systemjs/plugin-css@0.1.0"`, but I get that above error.

**Comment by trusktr** [comment]
I change famous to github, like this

```
jspm install -y famous=github:Famous/famous -o '{ "directories": { "lib": "src" }, "dependencies": { "css": "^0.1.0" }, "shim": { "*/*": { "deps": ["../core/famous.css!"] } } }'
```

but I'm still getting the same exact error. It seems like the error isn't depending on whether the target package is npm or github.

**Comment by trusktr** [comment]
Closing, to start an issue specifically for the error.

**Comment by trusktr** [comment]
Hmm, I'm not sure I made the new issue. Testing right now to make a replicable example.
