### ISSUE TITLE
Rename directories.baseURL to directories.public?

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#361]

**Comment by theefer** [comment]
Any particular arguments for the rename?

In my experience, baseURL is fairly descriptive. In our main setup, we have baseURL set in the package.json for commands like bundle or install to point to the relative directory that contains the files (`public`), and overridden in the main HTML file (`/assets`) to point to the paths where those assets are exposed by the web server. `directories.public` would probably work for the first use, but seems odd for the second imo.

By the way, is this the expected setup, with having to override the baseURL manually in the HTML prior to any System.import? It always felt a bit hacky... Is there any other way?

**Comment by guybedford** [comment]
Good points, I suppose baseURL does make the most sense then.

Yes the manually set `System.baseURL` override is currently the best we have. We could the client value set in `config.js` and always override it at the jspm server level too from the package.json.

It's the duality of config.js being for both client and server, where baseURL is different between them. We could consider a `config-server-only.js` as well potentially.

**Comment by theefer** [comment]
Am I right in thinking the package.json baseURL never gets written to the config.js? Or does it depend on the "mode"?

**Comment by guybedford** [comment]
Yes the package.json baseURL is only used to setup the server loader baseURL, and never written to config.js

So you can set a baseURL in config.js and that is client-only.

**Comment by theefer** [comment]
> Yes the package.json baseURL is only used to setup the server loader baseURL

I'm not sure what you mean by that? I was under the impression that the package.json baseURL only affected jspm operations (e.g. install, bundle), but wasn't communicated in any way (well, not in config.js at least) to system.js when loading modules from a web server endpoint. For that, I'd always have to set the baseURL in my HTML file.

Am I misunderstanding something?

It seems to me that there's a use for setting both independently (even if in some cases, it may be the same value).

I also don't tend to edit the config.js by hand as I'm not sure what gets persisted or auto-generated, so I tend to consider it a purely generated file.

Wouldn't it make sense to have both in the package.json?

`jspm.directories.public` would be what we currently use `directories.baseURL` for, i.e. the local path to the "public" directory that contains the files.

`jspm.baseURL` (not necessarily under `directories` as it's not a local directory) would be what we currently have to hardcode in the HTML, and you're suggesting injecting manually in the config.js.

I'm probably missing something, as I've always been slightly confused around these.

**Comment by guybedford** [comment]
When doing `jspm run app/main` we set the baseURL to the value in the package.json on the server. If there was a baseURL in the `config.js` file that would be overridden by the above. So I guess that is the best way to do it? Alternatively yes you can set in HTML too.

I don't know though, `directories.public` could be nice as it makes more sense on the server. Then we don't actually need `baseURL` set in the client as everything could be set automatically relative to the public folder by jspm?

Yes the workflow isn't as neat as it should be yet. Let me know what you think of this idea to remove baseURL being applied entirely in the next breaking release, and make public the base instead.

**Comment by trusktr** [comment]
> We could consider a `config-server-only.js`

### Idea

Webpack and bower use their own names in their files' file names, to avoid ambiguity and confusion.

For example, bower has `bower.json`,  and webpack has `webpack.config.js`. jspm's default `config.js` is ambiguous. Consider having `jspm.conf.js` the default (or similar), and if specified via command line, there could also be web and server configs, `jspm.servconf.js` and `jspm.webconf.js` (or similar).

Browserify doesn't seem to have it's own files (out of the box), but it does have the `browserify` field just like jspm has the `jspm` field in package.json.

I'm using

```
    "configFile": "jspm_config.js",
```

in my package.json to avoid the default ambiguity.

It might be nice to be able to have a separate jspm.json and be able to use that instead of the `jspm` of package.json.

**Comment by trusktr** [comment]
Another thing to note is that webpack uses javascript-based configuration, whereas jspm is using json-based config. It might be nice to be able to use code-based config, where one of the exports of the module could be an override, or perhaps the export can be an object where one of the properties is an override, and that would work in place of package.json `jspm` field. It could then be possible to programmatically change things in the override based on environment, plugins, etc.

**Comment by theefer** [comment]
> When doing jspm run app/main we set the baseURL to the value in the package.json on the server.

Sorry but I think I'm missing something here -- what do you mean by *on the server* in this context? I thought `jspm run app/main` loads the `app/main.js` file into a local Node process via SystemJS.

**Comment by guybedford** [comment]
Yes exactly, `jspm run` uses SystemJS in Node, setting the `baseURL` from the package.json overriding any value in config.js.

**Comment by guybedford** [comment]
@theefer thanks - ok baseURL it remains.
