### ISSUE TITLE
Falling back to getting main file by checking bower.json

### ISSUE THREAD

**Issue by reggi** [jspm/jspm-cli#362]
Not sure how this sounds. I just installed [paulirish/infinite-scroll](https://github.com/paulirish/infinite-scroll) (`jspm install github:paulirish/infinite-scroll`) and I got an error.  The [`package.json`](https://github.com/paulirish/infinite-scroll/blob/master/package.json) file is lacking `main`. Aptly enough because it's not a real NPM module. However [`bower.json`](https://github.com/paulirish/infinite-scroll/blob/master/bower.json#L9) has it.

So I get this error:

>  Potentially unhandled rejection [3] Error loading "github:paulirish/infinite-scroll@2.1.0" at http://localhost:8080/jspm_packages/github/paulirish/infinite-scroll@2.1.0.js
Error loading "github:paulirish/infinite-scroll@2.1.0" from "lib/main" at http://localhost:8080/lib/main.js
Not Found: http://localhost:8080/jspm_packages/github/paulirish/infinite-scroll@2.1.0.js (WARNING: non-Error used)

Would it be possible to check `bower.json` for `main` as a backup? The only thing is that bower main can be an [array](https://github.com/adamcoulombe/jquery.customSelect/blob/master/component.json#L4)  and they used to be called `component.json` as in the case of `adamcoulombe/jquery.customSelect`.

**Comment by guybedford** [comment]
Yes we could consider this - created the issue at the github endpoint page.
