### ISSUE TITLE
Installed github repo missing files

### ISSUE THREAD

**Issue by reggi** [jspm/jspm-cli#365]
I'm installing masonry `jspm install github:desandro/masonry` and I'm only downloading directories for some reason. Thoughts?

```
   └─┬ github/
     └─┬ desandro/
       ├── masonry@3.2.2.js
       └─┬ masonry@3.2.2/
         ├── masonry.js
         ├── dist/
         ├─┬ examples/
         │ ├── browserify/
         │ └── js/
         └── test/
```

**Comment by guybedford** [comment]
This is because the `package.json` `files` property only lists `masonry.js`. Do you need other files here?

**Comment by reggi** [comment]
This is an odd case, `masonry.js` has dependancies.

But in the `dist` is a version that is `pkgd` and it contains a build without any dependancies. So what's happening is when I install using `github` I can't use the `masonry.js` file and I can't access the `dist` which is confusing. 

So I need to install with `npm` which is is giving me the error https://github.com/jspm/jspm-cli/issues/363

Pretty frustrating when I can just `npm install` even just `git clone` the repo instead and have what I need.

**Comment by guybedford** [comment]
You can override this behaviour with:

```
  jspm install github:desandro/masonry -o "{ files: null }"
```

The reason we download the files is because the github bundle comes with them regardless. The file list allows us to exclude other files when processing the repo, which can save compilation time considerably.

Point taken this can be counter-intuitive though. Perhaps we can consider some variations.

**Comment by reggi** [comment]
Alas I've gotten the dep! Thanks a bunch!

**Comment by guybedford** [comment]
I've created an issue for this at https://github.com/jspm/github/issues/23.
