### ISSUE TITLE
Scaffold html on init.

### ISSUE THREAD

**Issue by hemanth** [jspm/jspm-cli#366]
Scaffolding a boilerplate makes sense?

Could be something as simple as:

```html
<!doctype html>
  <script src="jspm_packages/system.js"></script>
  <script src="config.js"></script>
  <script>
    System.import(' ');
  </script>
```

P.S: I might be missing something here, but didn't notice an option in the cli to scaffold a html.

**Comment by guybedford** [comment]
Scaffolding is not something jspm is designed to support.

**Comment by hemanth** [comment]
:+1:
