### ISSUE TITLE
Idea: support jspm.scripts.postinstall in package.json.

### ISSUE THREAD

**Issue by trusktr** [jspm/jspm-cli#367]
```js
{
  "name": "example",
  "version": "1.2.3",
  "jspm": {
    "scripts": {
      "postinstall": "mv src/* ./"
    }
  }
}
```

**Comment by trusktr** [comment]
Initial support for jspm.scripts.postinstall: https://github.com/jspm/jspm-cli/pull/372

**Comment by guybedford** [comment]
See https://github.com/jspm/npm/issues/36.

**Comment by guybedford** [comment]
@trusktr continuing the discussion from https://github.com/jspm/npm/issues/36#issuecomment-69484857:

> The answer is simple: for packages that don't follow npm or github specs, and need special handling. It can't be any clearer than that

Do you mean in the above like your use case of copying src to the base level? This is already handled by `directories.lib` though.

You mentioned the install example `leaflet=github:RickMohr/Leaflet@better-inertial-scrolling`. Does this not currently work in jspm? If so I'll happily look into it.

**Comment by trusktr** [comment]
Well with the new directories.lib for all endpoints (right?) then yeah my lib isn't an example that requires a script.

With `leaflet` installed from the github endpoint, you can make it work if you write one super long shim. I mean like... really long. I think you might see what I mean when you try it...

**Comment by guybedford** [comment]
Sure, is that an argument for better wildcard shim support?

**Comment by trusktr** [comment]
No, not at all, the shim for leaflet would need to be specific for each of the many files.

**Comment by guybedford** [comment]
Wildcard with replacement?

**Comment by trusktr** [comment]
Not sure what you mean, but look at the leaflet `src` folder. https://github.com/Leaflet/Leaflet/tree/master/src

Do you know what order anything in there loads? Should you even have to worry about that if you can just run a postinstall script to build it?

**Comment by guybedford** [comment]
Ok right, since they've written non-explicit modules you need to load a build. That is, install a published build in the first place.

**Comment by trusktr** [comment]
How? `jspm install leaflet=http://leaflet-cdn.s3.amazonaws.com/build/leaflet-0.7.3.zip`?

**Comment by trusktr** [comment]
That's not a branch though. I'm specifically installing a branch from github of someone's fork of leaflet, not published anywhere.

**Comment by trusktr** [comment]
There's no published build for it. SUre, I could make one, but that's a ton of unnecessary work compared to simply just building it with npm.

**Comment by trusktr** [comment]
> install a published build in the first place

That's asking for a lot, IMHO, more work than needed. It's easy to just have a repo branch, it's already there.

**Comment by guybedford** [comment]
@trusktr this is exactly the workflow we do for npm, it's not asking a lot - it is best practise to publish code in a consumable way.

In your specific case, yes you have extra work to make a custom leaflet build to work with jspm. Just like many repos need custom Bower repos to contain just the distributables. This is a problem now because not enough people tailor their builds for jspm yet.

**Comment by trusktr** [comment]
Fixed in (I think) https://github.com/jspm/jspm-cli/pull/2121
