### ISSUE TITLE
Issue fetching user/module from npm

### ISSUE THREAD

**Issue by hemanth** [jspm/jspm-cli#368]
```
$ jspm install npm:github/fetch

     Looking up npm:github/fetch

err  Error looking up npm:github/fetch
     Error: getaddrinfo ENOTFOUND

warn Installation changes not saved.
```

But, `jspm install github:github/fetch` works, as well `npm install github/fetch`

**Comment by guybedford** [comment]
Yes, rather use `jspm install github:github/fetch -o { registry: 'npm' }` to install a GitHub repo as if it were an npm package.

**Comment by hemanth** [comment]
@guybedford So, that's like saying `$npm install github/fetch` ?

**Comment by guybedford** [comment]
@hemanth actually that repo is not an npm repo, it's a bower repo, so you can just do `jspm install github:github/fetch`.

**Comment by hemanth** [comment]
That made me wonder, the [readme](https://github.com/github/fetch/blob/master/README.md#installation) says we can do an `npm install github/fetch`

**Comment by guybedford** [comment]
Yes npm can install from GitHub, but jspm installs from GitHub differently.

**Comment by hemanth** [comment]
:+1: Thanks.

/me makes a note of `jspm install github:github/fetch -o "{ registry: 'npm' }"`
