### ISSUE TITLE
Not functioning in node v0.11.13

### ISSUE THREAD

**Issue by dillonkrug** [jspm/jspm-cli#369]
This isn't necessarily a bug with jspm, It's mostly a note for others who may be experiencing the same problem.

When running jspm init I see

```
     Looking up github:ModuleLoader/es6-module-loader
     Looking up github:systemjs/systemjs
     Looking up github:jmcriffey/bower-traceur
```

but nothing after that — the packages aren't actually downloaded.

It gets as far as the call
```
exec('git ls-remote ' + remoteString + repo + '.git refs/tags/* refs/heads/*'`
```
in jspm-github/github.js (line 236) but the callback never gets called.  I suspect it may have something to do with the child process not keeping the original process alive, like an `unref()`'d [timer](http://nodejs.org/api/timers.html#timers_ref), but that's pure speculation.  It may just be a bug in this version of node.

**Comment by guybedford** [comment]
Can you confirm it is working in Node 0.10 for you?

**Comment by cdetrio** [comment]
I had the same problem with node v0.11.13 (worked around by using `<script src="https://jspm.io/system@0.9.js"></script>` in index.html, instead of `src="jspm_packages/system.js"`).

`jspm init` does work correctly with node v0.10.35.

**Comment by dillonkrug** [comment]
@guybedford 
it functions perfectly in v0.10.22

**Comment by grey93** [comment]
Works in `0.11.14`, `0.11.12`, `0.10.35` on my system (jspm -v `0.10.3`, Ubuntu 14..04), so maybe its specific to `0.11.13`

**Comment by dillonkrug** [comment]
It might be worth mentioning I'm on OS X 10.10 (Yosemite)

I just tested with v0.11.14 and it works fine.  Are there know issues with child-process in v0.11.13?

**Comment by frozzare** [comment]
Same problem for me in Yosemite with node v0.11.13 both v0.11.12 and v0.11.14 works.

**Comment by guybedford** [comment]
I've just tested Node 0.11.13 and it is working fine for me on Yosemite.

Can you confirm you had `git` installed?

**Comment by frozzare** [comment]
@guybedford Yes I have `git` installed.

**Comment by guybedford** [comment]
Thanks @frozzare for the quick response. Which version of git are you running?

Because I can't replicate, any help tracking this down would be really appreciated. Specifically:

* Can we confirm this is the `exec('git ls-remote')` line in jspm github (https://github.com/jspm/github/blob/master/github.js#L285).
* Does it help updating git on the machine?
* Does using `spawn` over `exec` help, or setting process options like increasing the timeout?

**Comment by frozzare** [comment]
@guybedford haven't have time to dig deeper into this but my git version is 2.2.1

**Comment by cfenzo** [comment]
I experienced a similar issue on ubuntu 10.04.4 LTS with Node 0.11.13 and git 1.7.0.4
Upgrading node to to 0.11.14 fixed the problem for me.

**Comment by guybedford** [comment]
This does seem like ultimately a Node issue. Closing for now, but if there's anything else to do here please let me know.
