### ISSUE TITLE
Recursive file entries on Windows

### ISSUE THREAD

**Issue by jdknezek** [jspm/jspm-cli#373]
I discovered this trying to use the JSX loader plugin for SystemJS on Windows. `npm:react-tools`'s `package.json` has the following files list:

```
  "files": [
    "main.js",
    "bin/jsx",
    "src/",
    "vendor/fbtransform/"
  ],
```

When installing via `npm`, `src/` and `vendor/fbtransform/` include all subdirectories and files recursively, whereas installing with `jspm` includes all subdirectories, but none of the files. I suspect this might be a globbing/path separator issue as it appears to work fine on Ubuntu.

**Comment by guybedford** [comment]
Thanks - yes, this is a bug.

**Comment by u9520107** [comment]
So, when I install react on windows. All the files under React/lib are missing should be caused by this bug as well?

**Comment by guybedford** [comment]
The react files entry looks like:

```
  "files": [
    "README.md",
    "addons.js",
    "react.js",
    "dist/",
    "lib/"
  ]
```

If there were folders in the `lib` folder, it seems they would be removed by this bug, yes.

**Comment by guybedford** [comment]
This should be working now.

**Comment by u9520107** [comment]
@guybedford Did you mean this is fixed in the next release? Current release version seems to remain the same (0.10.6) and the issue persists in my windows machine.

**Comment by guybedford** [comment]
@u9520107 did you do `jspm install -f` to clear any local cache?

**Comment by u9520107** [comment]
@guybedford Ok... the files are indeed installed alright..  But a different issue appeared: #443
