### ISSUE TITLE
feature request: command aliases

### ISSUE THREAD

**Issue by grey93** [jspm/jspm-cli#374]
__c__ -> config
__i__ -> install
__remove__ -> uninstall
__r__ -> uninstall
__s__ -> search

from npm

**Comment by guybedford** [comment]
I'm not sure... it would be interesting to hear what others think about this. @crisptrutski any thoughts?

**Comment by grey93** [comment]
I made the request for consistency, on npm i use aliases only, bower also supports i for install, p for prune and s for search

**Comment by guybedford** [comment]
Sure, that makes sense. PRs welcome.
