### ISSUE TITLE
quick install

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#376]
Sometimes the user doesn't want the entire install tree to be checked all the way down, we just want to run the tree as far as necessary, without verifying all integrity.

It would be good to have an install option for this `--quick`, with only first-depth dependency verification.

When linking a project with a lot of dependencies, this is critical to having a quick dev workflow (link would be --quick by default).

@Bubblyworld

**Comment by Anachron** [comment]
I think it would be better to use `--depth`, as [npm does it the same way](https://github.com/npm/npm/issues/4052#issuecomment-32133862)

**Comment by guybedford** [comment]
Nice, thanks for mentioning.

**Comment by guybedford** [comment]
Implemented in https://github.com/jspm/jspm-cli/commit/a7ce163a7a63ddfced3849e3f8f059c88e94f2d1.
