### ISSUE TITLE
Idea: code-based configuration.

### ISSUE THREAD

**Issue by trusktr** [jspm/jspm-cli#377]
Webpack uses javascript-based configuration, which is really nice. Jspm is uses json-based config (the `jspm` field of package.json, for example). It would be nice to be able to use code-based config, where one of the exports of the module could be an override, or perhaps the export can be an object where one of the properties is `override`, and that would work in place of package.json's `jspm` field. It could then be possible to programmatically change things in the override based on the current environment, etc, etc, things that are dynamic.

The json-based config should still work, and if provided, the javascript-based config takes precedence, or something like that. :D

**Comment by trusktr** [comment]
Webpack, is lovable because it is dynamically configurable, while jspm is lovable because it uses the actual SystemJS and ES6 specs. Jspm lets you manage packages and develop with those packages in an environment that is closer than any other tool/workflow to the soon-to-be ES6 environments of the future, *without even having to compile anything, just direct loading of package (!!)*.

Webpack and browserify seem to focus on compiling to ES5, not actually running ES6, so when ES6 comes out, will browserify and webpack evaporate into thin air? Jspm will be the most ready for ES6 when ES6 Module becomes reality, while browserify and webpack in their current states will simply be javascript minifiers/bundlers because compilation to CJS and ES5 will no longer be required.

So with that in mind, if jspm adopts a dynamic code-based configuration, it will be even further in the game than everything else, in my humble opinion. :D

**Comment by guybedford** [comment]
Can you carefully describe a single scenario where code-based configuration offers an advantage?

**Comment by trusktr** [comment]
One great scenario is having different configurations for different environments, for example, in dev, QA1, Staging, Production, and Windows vs Linux vx Mac OS X.

Here's a sample webpack.config.js file. We can see that module.exports is more dynamic than an json file:

```js
var _ = require('underscore');
var webpack = require('webpack');
var config = require('./gulp/config');
var routes = require('./gulp/utils/routes');

var entryKeys = _.pluck(routes, 'name');
var entryValues = _.map(routes, function(route) {
  return ['./src', route.entries.js].join('/');
});

module.exports = {
  entry: _.object(entryKeys, entryValues),
  output: {
    path: '/dist',
    filename: config.prefix + '[name].bundle.js'
  },
  plugins: [
    new webpack.ProvidePlugin({
      jQuery: 'jquery',
      $: 'jquery'
    }),
    new webpack.ProvidePlugin({
      _: 'underscore'
    })
  ],
  module: {
    loaders: [
      {
        test: /\.hbs$/,
        loader: 'handlebars-loader'
      }
    ]
  },
  resolve: {
    alias: {
      'marionette'        : 'backbone.marionette',
      'urijs'             : 'URIjs'
    },
    fallback: './src/utils/hbs-helpers',
    modulesDirectories: ['node_modules', 'src']
  }
};
```

JSON is for communication, code is better for configuration, IMHO. :)

**Comment by trusktr** [comment]
Another example with (possibly future) jspm:

```js
var os = require('os-detector')

module.exports = {
    scripts: {
        postinstall: os.windows? "move src.\\* .\\": "mv src/* ./"
    }
}
```

portability

(I might not be 100% on the windows `move` syntax, but you get the idea)

**Comment by trusktr** [comment]
I would think the sane default would be to not run scripts by default, and give jspm users the freedom to decide what to do, as in https://github.com/jspm/npm/issues/36#issuecomment-69289504.

**Comment by guybedford** [comment]
Changing what code means dynamically is a hinderance to having everyone refer to the same universal code, which is the primary purpose of package.json properties and overrides.

Note that `config.js` IS a code-based config for the loader.

**Comment by trusktr** [comment]
@guybedford Interesting that you brought that up.

After having started to look into systemjs, I see that browserify+npm and webpack+npm workflows are more similar to a systemjs+npm workflow than a jspm workflow. `config.js` is the code-based config for the systemjs, not jspm. When running `jspm install` the `config.js` gets overwritten, and due to that, I have been .gitignoring config.js and letting jspm handle it. Check out the following `config.js` just example:

```js
var foo = {};
foo.blah = function() {
    return false;
}

System.config({
  "paths": {
    "*": "*.js",
    "app/*": "lib/*.js",
    "blah": "foo/bar/*.js",
    "github:*": "jspm_packages/github/*.js"
  }
});

var hello = "hello";

System.config({
  "map": {
    "famous": foo.blah? "blah:just/for/example": "github:trusktr/famous@jspm",
    "infamous": "github:infamous/infamous@master",
    "github:infamous/infamous@master": {
      "army-knife": "github:trusktr/army-knife@0.0.4",
      "famous": "github:trusktr/famous@jspm",
      "jss": "github:jsstyles/jss@0.10.0"
    },
    "github:trusktr/famous@jspm": {
      "css": "github:systemjs/plugin-css@0.1.0"
    }
  }
});

console.log(hello)
```

As soon as I run `jspm install` it now looks like this:

```js
System.config({
  "paths": {
    "*": "*.js",
    "app/*": "lib/*.js",
    "blah": "foo/bar/*.js",
    "github:*": "jspm_packages/github/*.js"
  }
});

System.config({
  "map": {
    "famous": "github:trusktr/famous@jspm",
    "infamous": "github:infamous/infamous@master",
    "github:infamous/infamous@master": {
      "army-knife": "github:trusktr/army-knife@0.0.4",
      "famous": "github:trusktr/famous@jspm",
      "jss": "github:jsstyles/jss@0.10.0"
    },
    "github:trusktr/famous@jspm": {
      "css": "github:systemjs/plugin-css@0.1.0"
    }
  }
});
```

All the custom code is gone. Plus, that's running in the browser, independently of jspm's functions, only affecting systemjs, outside the core part of the jspm workflow (the core part is overrides). It's not controlling what jspm does, just what systemjs does. webpack code-config gets handled server-side, and directly controls webpack. transforms directly control browserify on the server-side.

Plus, jspm could take advantage of systemjs server-side to let a config be written in ES6 too, and that would be highly promotive for ES6 (the doc examples can be written in ES6!):

```js
// jspm.pkg.js

import os from 'os-detector'

export {
  directories: {
    lib: "src"
  }
}
```

Jspm core manages packages and wires them into a systemjs loader environment. `config.js` is a result of that wire up and is outside of the jspm-specific workflow. The `jspm` package.json field and overrides found in other places are the actual jspm-specific configuration.

I know your first intention was to make the `jspm` property simply replace root-level things from package.json, but I think it can do both that and configure other things about jspm's behavior (for example, the [overrides array](https://github.com/jspm/jspm-cli/pull/370) would be jspm-specific). The docs can make it clear what each property/subproperty does, and it'd be all good.

**Comment by guybedford** [comment]
Note that `config.js` should always be checked in. It forms the version lock of the application and as such is the only way to reliably replicate the `jspm_packages` folder. When you install something new, `config.js` is modified because new versions are being resolved and locked into your application.

Yes - currently `config.js` doesn't support arbitrary code structure, but it does allow custom properties to be added to it. We can certainly look into allowing more dynamic custom structures to the configuration file.

**The reason we need JSON-based configuration and a shared override registry for jspm package installs (and also why I'm not keen on allowing overrides in package.json) is because of the idea of installations being universal - users need to all refer to the same code exactly for package portability to work.**

**Comment by trusktr** [comment]
I'm not sure I fully understand, but sure, the registry can be json and universal. But by not letting someone provide their own override (a.k.a configuration) to replace the registry override (code-based or not), jspm is limiting someone, who knows what the result of their override will be, from attaining a known desired result.

Knives are great for cooking. It gives people the option of cutting food. People can also cut themselves if they are careless.

**Comment by trusktr** [comment]
@guybedford Regarding locking down versions by tracking `config.js` in git, well can't I just removed the `^` and `~` symbols from my package.json? To me that's the same thing. Is there another reason to track `config.js`?

**Comment by guybedford** [comment]
@trusktr `jspm install` will modify `config.js` resolutions within the ranges of `package.json`. When doing fork resolution, `package.json` is the constraint, `config.js` is the solution, `jspm install` is the operation.

**Comment by trusktr** [comment]
Ok, so basically it works fine remaking config.js every time. A new solution each time. I guess I just don't see what intrinsic advantage I'll have by saving the file.

**Comment by guybedford** [comment]
You can certainly do what you want, but it is advisable. It's the same advantage as npm shrinkwrap.

**Comment by trusktr** [comment]
I see what you mean now. Thanks for that keyword!

**Comment by cjkoski** [comment]
Hi Guy,

Just wanted to pipe in here really quick.  I have a case where I would like to be able to programmatically modify config.js.  We have two types of deployment:

1.  Main production deployment:

http://www.app.com/

2.  Sandbox development deployments:

http://www.app.com/user/sandbox_name/

These require different config.js base URLs because the path to load PHP and JS modules is different (unfortunately).

IE)
/Vendor/Lib
vs.
./Vendor/Lib

So in my deployment script I will be overwriting baseURL depending on deployment type manually.  No big deal, but food for though :)
