### ISSUE TITLE
Idea: jspm name in file names, and ability to have override in separate file.

### ISSUE THREAD

**Issue by trusktr** [jspm/jspm-cli#378]
Based on the comment at https://github.com/jspm/jspm-cli/issues/361#issuecomment-69263992.

Instead of `jspm` in package.json, it could optionally be in a separate file like `jspm.pkg.json`, and with the idea in #377, it could be `jspm.pkg.js`. Either/or could be used.

jspm would still read things from package.json first, then apply `jspm.pkg.{json,js}`. And if `jspm` exists in package.json, then the outside files take precedence (or perhaps they override it).

The reason for #377 and this one are to have clear separation of concerns and organization, reducing ambiguity, and with #377 more dynamic control of configs (like webpack offers with it's configs).

To make the systemjs config.js file distinct from `jspm.pkg.{json,js}`, they could perhaps be `jspm.conf.js`, `jspm.webconf.js`, and `jspm.servconf.js`. Or, since SystemJS is the key player here, and to indicate it as such, another possibility would be to name them `system.conf.js`, `system.webconf.js`, and `system.servconf.js`.

with the `jspm.*conf.js` scheme, you'd distinguish between the package config and runtime config by `pkg` vs `conf`, but with the `system.*conf.js` scheme, the difference is even more clear.

**Comment by guybedford** [comment]
@trusktr I would advise that when suggesting features, the primary concern to be explained in the request is:

> What is the workflow issue in the current system today that the feature addresses

Arguments like _browserify does it_ or _webpack does it_ are not strong enough on their own.

I'm closing this for now, but if you have an argument for further justification please do post it here.

**Comment by trusktr** [comment]
I'm bet you've seen multiple scenarios in these github issues where a simple locally persisted override or a postinstall script would have prevented a blocker. For example, had we had locally persisted overrides or postinstall scripts, I would've had the jspm workflow published the same day as the browserify and webpack workflows. It took me more than a week to publish the jspm workflow.

I'm persistent, I believe in where jspm is going, but others will gladly throw jspm aside for something that works in a day versus a week,

and simple local overrides or post install scripts would have done the job perfectly.

I'm not saying it's your ideal solution, and i'm also not saying you should drop your other plans for these features. What I am saying is to just add these features to allow people to work around scenarios that you or I can't forsee, then in the meantime work on the feature you want like a nice workflow for publishing overrides, etc.

I'm not the only one getting stuck with scenarios easily solvable by local overrides and postinstall scripts. Having those features means having freedom to choose, and when you release the override publish workflow, then that can be another option to choose from, and you can promote that as the best option in the documentation, but nonetheless give us options.

**Comment by guybedford** [comment]
@trusktr yes I understand the override process is frustrating. As I said though, focusing the discussion on better guided workflows for this is the way I want to approach it - automating registry forking etc.

**Comment by trusktr** [comment]
Can you describe how you envision this new workflow?
