### ISSUE TITLE
Shim doesn't work (without wildcards).

### ISSUE THREAD

**Issue by trusktr** [jspm/jspm-cli#382]
My fork of famous has a shim for loading css, but it doesn't seem to work. package.json: https://github.com/trusktr/famous/blob/jspm/package.json

to replicate:

```
git clone https://g.trusktr.io/trusktr/infamous-jspm-workflow.git
cd infamous-jspm-workflow
git checkout c83e04ca12f08f5e664655df58d5c9e17ebf21ed
cd public
jspm install -y
npm install -g serve
serve
```

then in Dev Tools you'll see no CSS ever gets loaded, despite the fact that infamous has loaded famous modules in order to create the animation (which doesn't look proper due to the lack of CSS).

You'll also see an error, but no idea what it means with respect to my stuff since it doesn't mention files or line numbers:

```
Assertion failed: is loading on fail
```

So close!! Once this works I I'll be able to post the jspm workflow to my the infamous README!! :D I also want to make a post here: http://es6rocks.com/

**Comment by guybedford** [comment]
This seems like it is because only a single `*` wildcard is supported in shim.

**Comment by guybedford** [comment]
No it didn't. I'm not sure what it could be then. I'll test this out when I can. Any other tips appreciated.

**Comment by trusktr** [comment]
For sure. I'm going to compare my working site against the workflow example and see what I find.

**Comment by trusktr** [comment]
For sure. I'm going to compare my working site against the workflow example and see what I find.

**Comment by guybedford** [comment]
@trustkr, as mentioned I think you just need to test the wildcard configuration more carefully. If there is a bug, see if you can work out cases that work (`format: 'global', shim: { "some/path": { "deps": "..." } }`) against cases that don't, slowly bringing in the wildcard testing from there. Also note that `shim` only applies to globals as well.

**Comment by trusktr** [comment]
K, I'm trying it without a wildcard

```js
  "jspm": {
    "registry":"jspm",
    "directories": {
      "lib": "src"
    },
    "dependencies": {
      "css": "^0.1.0"
    },
    "shim": {
      "core/Surface.js": {
        "deps": ["./famous.css!"]
      }
    }
  }
```

and that's still not working. I looking at the top of `jspm_packages/github/trusktr/famous@jspm/core/Surface.js` and there's no `deps` line.

**Comment by trusktr** [comment]
Suggestion: keep issues open until they're confirmed to be resolved.

**Comment by trusktr** [comment]
Note: the format of famous is amd, so jspm is putting `"format amd";` at the top. Is this causing the shims to be ignored?

**Comment by trusktr** [comment]
My goodness! I found the solution so that I can finally post the jspm workflow.

```js
"registry":"jspm"
```

in my project's package.json, and now I can load the famous.css file at least in my project, but not automatically using famous' override, but at least now things work. 

It doesn't seems practical that it is automatically set for npm endpoint packages, but not for other endpoints. This has been such a headache, going in circles trying to get things working.

I put a note in the registry wiki suggesting to just always put the registry property in package.json.

My project isn't meant to be installed by anyone. I don't see a reason why (other than if I don't it doesn't work) I should need to put that property in my project. It should just work. It's not intuitive IMHO.

Can you provide a good example where you actually don't want the registry property?

**Comment by guybedford** [comment]
@trusktr the follow up to that is to close issues when they're sorted.
