### ISSUE TITLE
Better command line help.

### ISSUE THREAD

**Issue by trusktr** [jspm/jspm-cli#384]
This would be nice to clean up: https://github.com/jspm/jspm-cli/blob/c5125f13a88bcd0055b7029af00c8a5c3eb2c63d/cli.js#L49-L100

It's not very manageable.

And it can be further improved by adding help for specific commands, e.g. `jspm help install` to show further details on using `jspm install`.

Some potential tools to use:
* https://www.npmjs.com/package/command-router
* https://www.npmjs.com/package/commander

[contributions welcome]?

**Comment by guybedford** [comment]
It's nice to have an overview of all the commands. What about it isn't manageable? Individual helps feel like they get lost in all the commands, but yes that is probably where things go eventually.

**Comment by douglasduteil** [comment]
:+1:  for commander

**Comment by trusktr** [comment]
What I mean by manageable is that it's tedious and time consuming to manually format all those strings. The tools out there handle it nicely and precisely already.

**Comment by guybedford** [comment]
I haven't found this to be a bottleneck personally, so am not sure I understand the motivations.

**Comment by trusktr** [comment]
I see it as less likely for someone to want to contribute to. You might like writing documents wrapped in strings, but lots of people don't. Who likes writing HTML in strings? That's why we invented template handlers.
