### ISSUE TITLE
Repeatable builds with format overridden

### ISSUE THREAD

**Issue by hitsthings** [jspm/jspm-cli#385]
I'm a bit confused about how overriding formats works.

I have added `phaser` as a dependency from NPM. If I just run `jspm install npm:phaser`, the phaser output is made to work in a Node environment, which means it pulls in Node deps like `process` and `Buffer`.

So I tried running `jspm install npm:phaser -o { \"format\": \"global\", \"registry\": \"npm\" }` which seems to do the right thing. However, `package.json` has no mention of the format difference. It still has

```
...
"jspm": {
  "directories": {
    "baseURL": "public"
  },
  "dependencies": {
    "phaser": "npm:phaser@^2.2.2"
  }
}
...
```

The only place I see mention of the format override is in the phaser source itself.

Doesn't this mean if I don't save my JSPM dependencies, I will have a broken install on any other machine that tries to dev on my project? Those machines will install phaser incorrectly as a Node module if they just `jspm install`.

Am I doing something wrong or is this a known limitation of JSPM?

Thanks for helping a newb figure out his way around JSPM!

**Comment by guybedford** [comment]
Yes, overrides make your system different to the jspm standard. The goal is to try and get users referring to the same code to enable modularity. That is, you should [check your override into the jspm registry](https://github.com/jspm/registry/#packagejson-overrides) or send a PR to the original repo.

There is a lot of discussion around making override workflows easier though too.

**Comment by guybedford** [comment]
Thanks for posting, these workflows will improve certainly - we're currently exploring options for this in https://github.com/jspm/jspm-cli/issues/336.
