### ISSUE TITLE
Managing packages from outside the public folder, but serving the public folder.

### ISSUE THREAD

**Issue by trusktr** [jspm/jspm-cli#386]
I've updated the infamous-jspm workflow, so now package.json is outside the `public` folder in the project's root, and looks like this:

```js
{
  "jspm": {
    "directories": {
      "packages": "public/jspm_packages"
    },
    "configFile": "public/config.js",
    "dependencies": {
      "famous": "github:trusktr/famous@jspm",
      "infamous": "github:infamous/infamous@master"
    }
  }
}
```

then I do `jspm install` in the project root, and it creates `public/config.js` and `public/jspm_packages`. Then I `serve public`. But the problem is the `public/config.js` contains `public/jspm_package` in it, when it actually need to contain just `jspm_package`:

```js
System.config({
  "paths": {
    "*": "*.js",
    "app/*": "lib/*.js",
    "github:*": "public/jspm_packages/github/*.js" // right here, this won't work, we *are* in the public folder.
  }
});

System.config({
  "map": {
    "famous": "github:trusktr/famous@jspm",
    "infamous": "github:infamous/infamous@master",
    "github:infamous/infamous@master": {
      "army-knife": "github:trusktr/army-knife@0.0.4",
      "famous": "github:trusktr/famous@jspm",
      "jss": "github:jsstyles/jss@0.10.1"
    },
    "github:trusktr/famous@jspm": {
      "css": "github:systemjs/plugin-css@0.1.0"
    }
  }
});
```

How can we make this work?

**Comment by trusktr** [comment]
It seems like all the doc examples assume that jspm will be managing packages inside the very folder that will be served to the web, but not everyone will do that. Is there already some config option to manage this?

**Comment by trusktr** [comment]
I added some console.log statements at https://github.com/jspm/jspm-cli/blob/b016e14fabe7a0376b33598d03029794864baa28/lib/build.js#L160, and noticed those aren't getting fired. Should `matchWithWildcard` be getting called?

**Comment by trusktr** [comment]
Ah, I found the problem. I forgot that this was causing the CSS problem. The `'deps ...'` string isn't being inserted into the famous source files, so they aren't loading the CSS files.

I don't remember why this is happening.

**Comment by guybedford** [comment]
You need to set `directories.baseURL` to `public`.

**Comment by trusktr** [comment]
@guybedford I tried that but that still results in the same exact output to public/config.js.

**Comment by guybedford** [comment]
@trusktr did you run `jspm init` to reset the config after changing the `directories.public`?

**Comment by trusktr** [comment]
I deleted all files except package.json and then `jspm install -y`.

**Comment by guybedford** [comment]
@trusktr perhaps check again. If you have a package.json looking like:

```json
{
  "jspm": {
    "directories": {
      "baseURL": "public",
      "packages": "public/jspm_packages"
    },
    "configFile": "public/config.js"
  }
}
```

And then run `jspm install ...`.

The `public/config.js` file will contain references to `jspm_packages/*` as expected.

**Comment by trusktr** [comment]
`baseURL` wasn't mentioned at https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm so I had no idea it went inside `directories`, I just had it directly in `jspm`. I only just discovered baseURL. Doc as you go! It will help new users. I'm going to try out [documentjs](http://documentjs.com) for documenting infamous as I go. Document everything. The lack of docs is probably causing unnecessary "support" issues here.

Thanks for putting up with all of mine. :)

**Comment by trusktr** [comment]
Ok, so baseURL fixed one problem, but made a new one:

I'm running `jspm bundle-sfx src/app public/app.js` and now it's not looking in `src` for `app.js`, it's looking in `public/src`.

**Comment by trusktr** [comment]
The idea is that with browserify and webpack source code can be hidden by not serving the the `src` folder, and only the compiled code goes to the served public folder. I was trying to do the same with jspm.

**Comment by trusktr** [comment]
What would you recommend for production? build a bundle, then delete all but the bundle?

**Comment by guybedford** [comment]
Thanks, I've added some notes in the getting started guide. Exact structure is not really prescribed too heavily at all.

**Comment by trusktr** [comment]
Where's it at? Got a link?

**Comment by guybedford** [comment]
The getting started guide link is at the top of the jspm website 'guides' first section which is simply to the section of the wiki of this repo. https://github.com/jspm/jspm-cli/wiki/Getting-Started

**Comment by trusktr** [comment]
I added details on `baseURL` to https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm. 

I still can't seem to do what I really want to do, and `jspm setmode dev/production` isn't quite helpful.

I'd like all of my development to happen in `src` and during development I serve the src folder as the root of the server. Then, for production, I'd like to compile everything into the `public` folder and serve that folder at the root of the serve instead.

package.json is outside of those folders, and I'm running `jspm` outside of both of those folders. Can you check out what I've got at [here](https://g.trusktr.io/trusktr/infamous-jspm-workflow/tree/5644a9b1869a8b9f9fdeaac9feff111bf6e0a49b)?

The idea would be that you clone the repo (checkout that commit), `jspm install -y`, then serve the `src` folder, which works. I'd like for that to be my "dev" mode.

Then I'd like to `jspm setmode production`, `jspm build something something`, then `serve public` for production and the code in `src` is not exposed by the server.

Can something like this already be done with jspm? I'm starting to think maybe I just need to start using gulp or something on top of `jspm` to make this happen.
