### ISSUE TITLE
Idea: keep the user-defined order/structure of package.json or config.js.

### ISSUE THREAD

**Issue by trusktr** [jspm/jspm-cli#387]
`jspm install` for example will reorder everything in package.json and change indentation levels. Ideally the user format and ordering should be kept.

**Comment by trusktr** [comment]
For example, the following package.json

```js
{
  "jspm": {
    "directories": {
      "lib": "src",
      "baseURL": "public",
      "packages": "public/jspm_packages"
    },
    "dependencies": {
      "famous": "github:trusktr/famous@jspm",
      "infamous": "github:infamous/infamous@master"
    }
  }
}
```

is getting converted to

```js
{
  "jspm": {
    "directories": {
      "baseURL": "public",
      "lib": "src"
    },
    "dependencies": {
      "famous": "github:trusktr/famous@jspm",
      "infamous": "github:infamous/infamous@master"
    }
  }
}
```

**Comment by guybedford** [comment]
We use a standard form for the package.json. The default `configFile` path is the baseURl folder, that is why it is removed, because it matches the default.

**Comment by trusktr** [comment]
I noticed that pattern, I just think you should still keep it. It's unexpected when git says there's changes to a file I didn't change and wouldn't expect to change. It's just completely unexpected. Never happened to me before except with jspm.

**Comment by guybedford** [comment]
Sure, I see what you mean. This would involve using state above and beyond the defaults to work out if a user wants to explicitly maintain a default value in the package.json.

**Comment by trusktr** [comment]
Want to leave this one open to eventually get to?

**Comment by guybedford** [comment]
It's covering quite a few points:

* Maintaining indentiation of package.json
* Maintaining non-standard formatting of properties like `src/.../src`
* Maintaining the property order
* Not hiding default properties

Of the above, I think I'd only consider the last one as a potential feature.

**Comment by trusktr** [comment]
I'd say the second and last most important. Basically maintain all the data at the very least, even if you don't like the data.

**Comment by guybedford** [comment]
https://github.com/jspm/jspm-cli/issues/428
