### ISSUE TITLE
idea: directories.lib for local runtime.

### ISSUE THREAD

**Issue by trusktr** [jspm/jspm-cli#388]
If directories.lib is `js`, and in the baseURL there is `js/foo.js`, then in the HTML would it make sense to be able to do

```html
        <script type="module">
            System.import('foo');
        </script>
```

without the `js` in the path to load the foo.js?

**Comment by guybedford** [comment]
@trusktr I think you're misunderstanding `baseURL`. `baseURL` simply means "base code folder for SystemJS". That is when I do `System.import('app')`, it's the folder it goes to.

**Comment by trusktr** [comment]
@guybedford I believe I understand `baseURL`. I'm just saying that since `directories.lib` is (unexpectedly) relative to `baseURL`, then it would make sense to be able to do `System.import('app')` where `app.js` is located at `baseURL/directories.lib/app.js` instead of having to so `System.import('directories.lib/app')`

**Comment by trusktr** [comment]
Does that make sense what I meant?

**Comment by guybedford** [comment]
`directories.lib` in the package.json is written is relative to the package.json itself, not the baseURL.

`System.import('any/name')` expects the baseURL served on the client to match the path of the baseURL set in the package.json on the server.

`System.import('app/main')` sets the path to `directories.lib` relative to the baseURL.

**Comment by trusktr** [comment]
> directories.lib in the package.json is written is relative to the package.json itself, not the baseURL.

When I set baseURL to `public` and directories.lib to `src` then run `jspm build src/app` from the package.json location, jspm errors out saying it can't find `public/src/app.js`. Seems relative to baseURL from that error.

**Comment by guybedford** [comment]
`directories.lib` corresponds to the name of the application of `app` itself - `jspm bundle app/main`.

**Comment by trusktr** [comment]
Perhaps it's just not clear enough in the docs, I've been just using an `app.js` file. I don't understand how what you just mentioned relates to `jspm build src/app` prepending the baseURL and looking in `baseURL/src` for app.js instead of just `src`.
