### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#389]
Still getting reports of some install issues, specifically `Error downloading loader files Error looking up github:systemjs/systemjs`.

Would be good to see if there are proxy / other concerns here we need to look into still.

**Comment by mrlagmer** [comment]
Hey,

Not behind a proxy. My box is ubuntu 14.04LTS. Running as root. I just did a yum install NPM. Then NPM install jspm -g

Then when I run jspm init the below is what I get. 

Output:

ok   The app/* path has been set to lib/*.js.
     To alter this path, set the directories.lib in the package.json or run jspm init -p to set the code folder.

ok   Verified package.json at package.json
     Verified config file at config.js
     Downloading loader files to jspm_packages
     Looking up github:ModuleLoader/es6-module-loader
     Looking up github:systemjs/systemjs
     Looking up github:jmcriffey/bower-traceur

err  Error downloading loader files 
     Error looking up github:systemjs/systemjs
/bin/sh: 1: git: not found

**Comment by guybedford** [comment]
@mriagmer you need to make sure you have `git` installed on your machine (http://git-scm.com/downloads). I will leave this issue up to make a note that this should be included in the Getting Started guide.

**Comment by guybedford** [comment]
Ok moved to https://github.com/jspm/jspm-cli/issues/391.
