### ISSUE TITLE
Shim not working with a single wildcard *.

### ISSUE THREAD

**Issue by trusktr** [jspm/jspm-cli#390]
I'm using

```
    "shim": {
      "*": {
        "deps": ["core/famous.css!"] // relative to the package directories.lib?
      }
    }
```

for my fork of famous, but no luck. However, it worked for a single file when I did

```
    "shim": {
      "core/Surface": {
        "deps": ["./famous.css!"]
      }
    }
```

It seems like not even a single wildcard works. Or am I doing it wrong?

**Comment by trusktr** [comment]
If I change it to

```
    "shim": {
      "*": {
        "deps": ["src/core/famous.css!"]
      }
    }
```

then code flow passes through the `compileDir` function, but still nothing in the final files.

**Comment by guybedford** [comment]
Yes the wildcard match is not deep, it only works at the current path level.

**Comment by trusktr** [comment]
I'm guessing (but havn't tried) that the best I can do then is

```
./core/*
./surfaces/*
./modifiers/*
```

until I've written one for each directory, and that could unexpectedly change, making it hard to manage. wildcard upgrade to the wishlist. But perhaps not reinvent the wheel and use a widely accepted wildcard lib on npmjs?

**Comment by guybedford** [comment]
@trusktr better wildcard globbing is certainly something we can consider.
