### ISSUE TITLE
error while installing over npm, but same lib works over github release

### ISSUE THREAD

**Issue by djindjic** [jspm/jspm-cli#394]
I have made an small js lib and deploy it to github releases and npm (same version).
`jspm install github:djindjic/forwardablejs` works very well but when I try to install it from npm I've got this error:
```bash
jspm install npm:forwardablejs
     Looking up npm:forwardablejs
     Updating registry cache...
     Downloading npm:forwardablejs@0.1.25

err  Error building package npm:forwardablejs
     TypeError: Object.keys called on non-object

warn Installation changes not saved.
```

only one place where I call Object.keys is in [karma.conf.js](https://github.com/djindjic/forwardablejs/blob/f1491d61042ad9d7a797df1e6f7982d057c5e80c/karma.conf.js#L93) but it doesn't related to jspm and I have proper [package.json configuration](https://github.com/djindjic/forwardablejs/blob/f1491d61042ad9d7a797df1e6f7982d057c5e80c/package.json#L5) for main file.

**Comment by guybedford** [comment]
Thanks, this is a bug - I've added a fix at https://github.com/jspm/jspm-cli/commit/826a7bbf1e1fcd2825d2cd30a2c4763c5baf4b8e, with a release to follow tomorrow.
