### ISSUE TITLE
Guided override prompts

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#395]
`jspm install bootstrap -o`

could start a prompt process for the overrides:

```
(provide an empty value to skip overriding that property)
Set the main: 
Set the module format [es6/cjs/amd/global]:
Would you like to set shim configuration [y/n]?
...
```

**Comment by Hendrixer** [comment]
:+1:  This would be awesome, I have been burned by the sparse docs on how overrides work and what they are. Look at the registry to figure out how to get it going. Maybe I'll do this.

**Comment by guybedford** [comment]
Initial attempted implementation at https://github.com/jspm/jspm-cli/pull/602.

**Comment by guybedford** [comment]
Still not 100% sure about this though. Ideally we should delegate a certain level of responsibility here to the registry implementations.

**Comment by guybedford** [comment]
This would get easier via transitive overrides allowing in-progress prompts for packages based on best-suggestions rather than a massive "wizard" concept which will be too far away from the users' needs. Tracking in transitive overrides at https://github.com/jspm/jspm-cli/issues/854.
