### ISSUE TITLE
Error in bundle with --minify and --skip-source-maps

### ISSUE THREAD

**Issue by victorwpbastos** [jspm/jspm-cli#400]
When I try to generate a bundle with `--minify` and `--skip-source-maps` it returns:

![image](https://cloud.githubusercontent.com/assets/1017515/5723114/9d37372c-9b28-11e4-9d40-d5e90084b068.png)

**Comment by guybedford** [comment]
@victorwpbastos thanks - the fix is already in, I just need to make a new release of SystemJS builder with a fix. Working on it!

**Comment by victorwpbastos** [comment]
Glad to hear that. I'm in love with SystemJS and JSPM. Congratulations for the good work!

**Comment by guybedford** [comment]
Thanks! Closing for now, aiming to get the release out soon.
