### ISSUE TITLE
Switch back to using unminified System, ESML for debugging

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#401]
Let's leave out the `*.src.js` files for these and expect a separate production step.

**Comment by trusktr** [comment]
Could source maps work here?

**Comment by trusktr** [comment]
nvm, deleted.

**Comment by guybedford** [comment]
I'm still not sure about this - I don't think we really do need to ever debug SystemJS source, so I don't see what the real issue is.

**Comment by trusktr** [comment]
Well it could be convenient if someone is using jspm specifically, and happens to find a bug with systemjs, es6-module-loader, or traceur. They wouldn't have to go out of their way to test those separately.

**Comment by guybedford** [comment]
Because bundle provides minification, having the minified loader files is useful I believe.
