### ISSUE TITLE
Uninstalling a single package removes all installed package files from jspm_packages

### ISSUE THREAD

**Issue by raphaelvalerio** [jspm/jspm-cli#402]
I am new to JSPM and have been toying around with it in a sample project, and in the process have discovered unusual behavior when trying to uninstall packages. When i type `jspm uninstall jquery` (or any installed package) JSPM removes the files for ALL of my installed packages from the jspm_packages folder (except jspm itself), including dependency packages. However, it leaves the references to them in packages.json and config.js intact. This requires me to run `jspm install` after uninstalling any package for jspm to fetch the files for all the packages that weren't uninstalled.

As an example, let's suppose I've installed `jquery`, `npm:lodash-node`, `prism`, and `underscore`. If I then run `jspm uninstall jquery` to remove jquery, this is what ends up in my terminal:

```bash
$ jspm uninstall jquery
     Clearing configuration for github:components/jquery@2.1.3
     Removing package files for npm\lodash-node@2.4.1
     Removing package files for npm\process@0.10.0
     Removing package files for npm\underscore@1.7.0
     Removing package files for github\components\jquery@2.1.3
     Removing package files for github\LeaVerou\prism@gh-pages
     Removing package files for github\jspm\nodelibs-process@0.1.0

ok   Uninstall complete.
```

As you can see, jspm removed the package files for ALL my installed packages, including the dependency package `process`. However, it doesn't remove these packages from my `package.json`:

```json
  "jspm": {
    "directories": {
      "baseURL": "app",
      "lib": "app/scripts"
    },
    "configFile": "app/scripts/config.js",
    "dependencies": {
      "lodash-node": "npm:lodash-node@^2.4.1",
      "prism": "gh-pages",
      "underscore": "^1.7.0"
    }
  }
```

If I run `jspm install` again I get this:

```bash
$ jspm install
     Looking up npm:lodash-node
     Updating registry cache...
     Looking up npm:underscore
ok   Installed underscore as npm:underscore@^1.7.0 (1.7.0)
     Looking up github:LeaVerou/prism
     Looking up github:jspm/nodelibs-process
ok   Installed prism as github:LeaVerou/prism@gh-pages (gh-pages)
ok   Installed github:jspm/nodelibs-process@^0.1.0 (0.1.0)
     Looking up npm:process
ok   Installed npm:process@^0.10.0 (0.10.0)
ok   Installed lodash-node as npm:lodash-node@^2.4.1 (2.4.1)
ok   Install tree has no forks.

ok   Install complete.
```

It fetches all the files again for the packages I didn't uninstall, as you would expect. I must run `jspm install` after uninstalling any package or my app breaks as, obviously, the package files for my installed packages are gone.

Am I missing something here? Am I improperly running `jspm uninstall` in some way? It seems like jspm should not be removing all my installed package files if I signify an individual package to uninstall.

**Comment by guybedford** [comment]
@raphaelvalerio thank you so much - this seems like a Windows-specific bug, I'll look into it as soon as I can.

**Comment by raphaelvalerio** [comment]
@guybedford I should have mentioned my system in the original post -- you indeed guessed rightly about Windows. I'm on Win 8.1 64-bit. Also, I use msysgit (Git for Windows) as my terminal shell (though in this instance I don't think the shell has any bearing on the issue).

Let me know if I can be of any help!

**Comment by capaj** [comment]
@raphaelvalerio thanks for creating this issue, I had the same behaviour on Win10 64-bit, but hadn't had yet time to put it in writing.

**Comment by guybedford** [comment]
This should be working now.

**Comment by coderpr** [comment]
great your code is work.........
