### ISSUE TITLE
Wildcard bundling

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#404]
eg `jspm bundle lib/* - lib/core`

**Comment by ahmedshuhel** [comment]
When I requested you said `no`. Now @EisenbergEffect did the same and you created this issue. You better be good to me :wink:

**Comment by ahmedshuhel** [comment]
@guybedford I am interested in participating on this.

**Comment by guybedford** [comment]
@ahmedshuhel sure, this is quite intricate as the wildcards are at a module name level. I can describe the process potentially, but it won't be easy to pick up on.

**Comment by EisenbergEffect** [comment]
It would be awesome to have this same functionality available for the `depCache` generation too...

**Comment by guybedford** [comment]
Ok this is now in the master branches across the projects. Merged in https://github.com/jspm/jspm-cli/commit/58ccb1ab22a9b1827abf34793bfc79923bc4193c.

Arithmetic now supports union and single module additions / removals as well (see https://github.com/systemjs/builder/issues/113, https://github.com/systemjs/builder/issues/111).

I've also added expressions for depCache as well as suggested in https://github.com/jspm/jspm-cli/commit/0eb955969812becbd330fb0758f6f6a8ecf3b3aa.

**Comment by EisenbergEffect** [comment]
Woohooo! Thanks to everyone who worked on this! :fireworks: This is a big deal for us.

**Comment by martingust** [comment]
Awesome!!!!

**Comment by kuraga** [comment]
Yeeeeeeeessssss!!!!!!

**Comment by kristianmandrup** [comment]
Awesome guys :)

**Comment by OrKoN** [comment]
That's great! :+1: :+1:  Gonna test it asap. Thanks a lot @guybedford, @ahmedshuhel and others !
