### ISSUE TITLE
Working on a Jade plugin - questions

### ISSUE THREAD

**Issue by johnsoftek** [jspm/jspm-cli#405]
I am working on a Jade plugin for jspm. I have a working version but I have two problems to overcome.

Firstly, as I understand it, the plugin js file name must match the target file extension. So if I want to say:

````javascript
fn = require('templates/login.jade!');
html = fn();
```
then the plugin file must be called 'jade.js'. But the plugin also calls require('jade'), so there is a naming conflict. To get it working, I named my plugin file jadex.js and used .jadex! as the template file extension. Is there a way to overcome this problem by jspm configuration?

The second problem involves the require('jade') statement. Jade's package.json has
```
"main": "lib"
```
so require('jade') should fetch jade@1.9.0/lib/index.js. To overcome the problem, I manually updated the file jspm-packages/jade@1.9.0.js from
```
module.exports = require("npm:jade@1.9.0/jade");
```
to
```
module.exports = require("npm:jade@1.9.0/lib/index");
```

I think jspm should take notice of the "main" item in jade's package.json.

**Comment by guybedford** [comment]
Nice to see you're working on this. There's nothing wrong with a name clash, as each package is allowed its own local names.

You can set the name in the require with - `require('templates/login.jade!jadex')`.

The plugin name would typically be configured in the dependencies of a package:

```javascript
{
  "dependencies": {
    "jade": "0.1.0"
  }
}
```

Inside the plugin itself, it can load `jade` with a different meaning, and I believe that should work out ok.

It's best not to embed the canonical name require.

Good point about the `main` thing, I've created an issue at https://github.com/jspm/npm/issues/40 to track this.

**Comment by johnsoftek** [comment]
@guybedford I really don't like ```require('templates/login.jade!jadex')```.

The developer will install plugin-jade. It seems inelegant to include loader instructions in code, for each file, that .jade files are loaded by jadex.js. I would prefer to call the main file jade-loader.js and somewhere configure the systemjs loader to load jade! extensions using jade-loader.js.

Ideally, it should be possible to use ```require('templates/login.jade')```, without the exclamation. I started the jade plugin because I am planning to convert a project using Browserify to jspm. Browserify handles .jade extensions rather than .jade! by simple configuration. So does Webpack. I mean, it's obvious that a plugin is needed for other than the default .js file extension.

**Comment by guybedford** [comment]
@johnsoftek `'templates/login.jade!jadex'` is not encouraged. As I say, workflow is to install to the correct name:

```
  jspm install jade=github:johnsoftek/jadex
```

Then:

```javascript
require('templates/login.jade!');
```

Yes, a feature to automatically use a plugin by extension is planned for support in the next SystemJS version.

**Comment by johnsoftek** [comment]
@guybedford. Thanks for the clarification re name spacing. I am almost there now.

I renamed jadex.js to jade.js and use so:
```javascript
require('templates/login.jade!');
```

It works great when installing plugin-jade into another project. config.js includes:
```javascript
    "jade": "github:johnsoftek/plugin-jade@master",
    "github:johnsoftek/plugin-jade@master": {
      "jade": "npm:jade@1.9.0"
    },
```

Just one little problem. When running tests on the plugin by itself, I get an error:

> Error loading "test.jade!npm:jade@1.9.0"

The generated config.js includes:
```javascript
  "map": {
    "jade": "npm:jade@1.9.0",
```
Any ideas on how I can achieve the same disambiguation of "jade" in development?

**Comment by guybedford** [comment]
Within the plugin itself, I would suggest altering that `map` value to be the local path:

```javascript
"map": {
  "jade": "."
}
```

**Comment by johnsoftek** [comment]
@guybedford For plugin-jade, I import the Jade compiler. Package.json has:

```javascript
    "dependencies": {
      "jade": "github:johnsoftek/plugin-jade@^0.5.0",
      "jade-compiler": "npm:jade@^1.11.0"
    },
```

I also need to import the Jade runtime. Previously, I used System.normalize('jade-compiler', module.id) to locate the Jade path and append '/lib/runtime.js' for the import. System.normalize now returns jspm/packages/jade@1.11.0.js rather than a directory. Is there a tidy way to generate the path jspm/packages/jade@1.11.0/lib/runtime.js i.e. '/lib/runtime.js' relative to jade-compiler root?
