### ISSUE TITLE
Cordova/Phonegap file:// and css plugin

### ISSUE THREAD

**Issue by lewisl9029** [jspm/jspm-cli#406]
Hi,

I'm using the css plugin to `import './app.css!';` in my Cordova/Ionic app.
This works fine in the browser when testing, but when I build a bundle and then do an Android build, I run into the following errors: 

```
GET file:///app.css net::ERR_FILE_NOT_FOUND
GET file:///jspm_packages/github/driftyco/ionic-bower@1.0.0-beta.14/css/ionic.css net::ERR_FILE_NOT_FOUND
```

I'm also using the text plugin to import html templates and that seems to work fine under Cordova.

Any idea what could be the issue?

One way to easily reproduce this is to build a bundle of a trivial app with a css import, and then open it in Chrome with the --disable-web-security flag to get around its file:// restrictions.

**Comment by guybedford** [comment]
Are you setting your baseURL? Perhaps check what value it is set to, and set it manually perhaps.

**Comment by lewisl9029** [comment]
Thanks so much for the ridiculously quick response! =)

It started working as soon as I *stopped* manually setting the baseURL by removing this line:
``
System.baseURL='/';
``

Now it's having trouble loading the ionicons icon fonts, but that's to be expected since there isn't a plugin for .ttf/.woff/etc yet. I planned on switching to SVGs anyways. =)

I'll close this issue now.

**Comment by guybedford** [comment]
Great, glad to hear it's working.
