### ISSUE TITLE
config.js: Problem with package name path to lib directory and bundling

### ISSUE THREAD

**Issue by MajorBreakfast** [jspm/jspm-cli#408]
First: Sorry for the issue title :)

For a `package.json` with...
``` JavaScript
// package.json
{
  "name": "my-package"
}
```
... jspm automatically creates a paths entry in `config.js`
```JavaScript
// config.js
System.config({
  "paths": {
    "*": "*.js",
    "my-package/*": "lib/*.js", // <- here
    "github:*": "packages/github/*.js",
    "npm:*": "packages/npm/*.js"
  }
});

System.config({
  "map": {
    ...
```

Now I create a bundle with `jspm bundle lib/main` and add it in `index.html`. This bundle includes `lib/main` and all its dependencies.

``` HTML
<script src="packages/traceur-runtime.js"></script>
<script src="packages/system.js"></script>
<script src="config.js"></script>
<script src="build.js"></script>

<script>
  System.import('my-package/main')
    .catch(function(error) { console.error(error.stack || error) })
</script>
```

I did this. However, then I discovered that the bundle, although it was loaded, didn't work as expected: The browser loads the bundle AND all individual files. Something went wrong!

Solution: I need to use `jspm bundle my-package/main` instead of `jspm bundle lib/main`. That way the bundle holds the modules with their names beginning with "my-package" instead of "lib".

So, why am I posting this as an issue? It's, I think, a documentation problem. It took me two hours until I figured out what was happening. Here's what I propose:
- Document it at: https://github.com/jspm/jspm-cli/wiki/Production-Workflows
- Add a warning to the `bundle` command if a listed module starts with the lib directory (as defined in `package.json`, default: `"lib"`), but really the package-name should be used. I think users that are aware of this problem don't ever want to bundle something the other way.

**Comment by guybedford** [comment]
Thanks, this sounds sensible and an easy catch for others.

Note that in the next version of SystemJS, this won't be an issue anymore as the name would normalize to `lib/main` for both, so that's good.

PRs / contributions welcome.

**Comment by MajorBreakfast** [comment]
@guybedford Based on what information can the upcoming SystemJS version normalize "my-package/main" to "lib/main"? Doesn't it have to apply the paths definitions in the reverse direction for that?

**Comment by guybedford** [comment]
@MajorBreakfast see https://github.com/ModuleLoader/es6-module-loader/pull/219.

**Comment by guybedford** [comment]
@MajorBreakfast basically, module names are becoming URLs.

**Comment by guybedford** [comment]
I've clarified the package name in the getting started guide, as well as including a note on this catch at the end - https://github.com/jspm/jspm-cli/wiki/Getting-Started. Hopefully that should cover this.

**Comment by MajorBreakfast** [comment]
I think so. Thx!
