### ISSUE TITLE
Improved build API

### ISSUE THREAD

**Issue by theefer** [jspm/jspm-cli#412]
When using jspm, I've found it quite refreshing not having to fiddle around with extra layers of build tools to compile my JS, minify it, etc. (disclaimer: that's in spite of me being the author of yet another build build tool called [Plumber](https://github.com/plumberjs/plumber)).

However, I believe sometimes we'll want to apply further transforms as part of the build. The ones I have in mind include [ng-annotate](https://github.com/olov/ng-annotate) and asset hashing.

I believe all the transforms I'm interested in could be done post-bundling (without minification), so I'd end up with:

`jspm bundle | ng-annotate | uglify2 | asset-hash`

That's all fine and doable today, except the fact that `jspm bundle` writes the built filename to the `config.js`, but if we do further operations *including changing the filename* (asset hash), then we need to update the `config.js` again. This could be hacked in as a post-transforms hook, but I'm interested in doing this "properly". I'm also really keen not to bloat jspm with all possible transforms people may want to apply.

Any thoughts on how this could work?

Note that I'm not thinking of any build tool in particular (Grunt, Gulp, Plumber, Gobble, etc).

In its simplest form, could be use the jspm API to get the bundle and its sourcemap out programmatically (i.e. not writing it to the filesystem and not updating config.js), apply our transforms, and then use the API again to record the filename of whatever we did in the config.js?

**Comment by guybedford** [comment]
Would it help to run the custom `bundle` API here? There are two APIs we have for this:

```javascript
require('jspm').bundle(expression, fileName, options);
```

But often one doesn't actually want that, and it is easier to run a lower-level bundling process:

```javascript
var builder = require('systemjs-builder');
builder.loadConfig('./config.js').then(function() {
  builder.config({ baseURL: 'file:' + path.resolve('./public') });
  builder.build('modulename', 'outfile.js');
});
```

etc.

Perhaps it is just about better-documenting the above.

The other side of this is improving the above API so that the builder is a class-based builder:

```javascript
var jspmBuilder = new require('systemjs-builder')({ configFile: './config.js', baseURL: './public' });
// (then even have require('jspm').builder() be a shortcut to the above)

jspmBuilder.trace
jspmBuilder.bundle
// ...etc...
```

But the above still requires the user to manually run `trace` to inject build configuration. Perhaps jspm could extend the builder and provide this convenience too.

Thoughts welcome!

**Comment by theefer** [comment]
Thanks for the pointers, I'll have a play with the suggestions above and see how far I can get.

Even merely hashing (essentially just renaming the bundle) would be a nice one, as we tend to use that as cache busting strategy.

**Comment by guybedford** [comment]
I do think opening up the SystemJS builder API as a class instance may well be the best way to go here.

**Comment by theefer** [comment]
Are you saying you'd then subclass the default builder and override methods representing the steps you want to alter?

**Comment by guybedford** [comment]
No, rather to provide a granular builder API, bound to a jspm project, in an easy way for build tools to easily wrap and consume.

**Comment by theefer** [comment]
Alright, yes that makes sense. Maybe worth trying to dev real uses to inform what is needed from the API.

**Comment by guybedford** [comment]
Any ideas welcome, will start with the low-level functions matching what we have in builder now, but can expand to higher-level helpers too.

**Comment by guybedford** [comment]
The other thing is the build API should expose the `config.load` and `config.save` functions for doing custom configuration modifications.

**Comment by guybedford** [comment]
We're tracking the build interface here in https://github.com/systemjs/builder/issues/44.

**Comment by guybedford** [comment]
Thanks to the work by @crisptrutski I've been able to include a `jspm.newBuilder()` API method in https://github.com/jspm/jspm-cli/blob/master/api.js#L161.

This returns a jspm-configured instance of the SystemJS builder class, which supports in-memory compilation.

This allows workflows such as:

```javascript
  var builder = require('jspm').newBuilder();
  builder.build('module').then(function(output) {
    // do stuff with output.source, output.sourceMap
  });
```

Ideally we should move the handling of bundle arithmetic expressions into SystemJS builder itself as well to continue to support this.

I think the above solves this issue though? Let me know if it sounds about on the right track.

For now I'm not documenting the API, as I want to see if it works out first before committing to semver on it.

**Comment by guybedford** [comment]
Changed the name to `require('jspm').createBuilder()` and allowing optional build configuration as an argument in https://github.com/jspm/jspm-cli/commit/1a579fb750f4005216479aba96062c9ba37004c8.

Will document this release so some stability can be considered.

**Comment by theefer** [comment]
Great, that does sound really useful as a way to programmatically run a build and use the result in-memory for further steps.

When using this API, I assume no bundle gets registered in the `config.js`? Would you envision there being another API allowing recording `module name -> build path` mappings to the `config.js`?

e.g.

``` js
  var builder = require('jspm').newBuilder();
  builder.build('module').then(function(output) {
    // rough pseudo code
    var hash = md5(output.source);
    fs.writeFile('dist/module.' + hash + '.js', output.source);
    var bundledModules = ...; // ?
    builder.config.addBundle('dist/module.' + hash + '.js', bundledModules);
  });
```

**Comment by theefer** [comment]
Do you know if anyone is already calling jspm from Grunt/Gulp/whatnot? Curious if there is any precedent.

**Comment by guybedford** [comment]
@theefer we don't provide any methods to alter configuration currently.

output does contain a `modules` array object on it for doing this population though, that can be directly used to construct the production config as you've shown.

I'm not sure if there's anything in the Gulp space actually. May be worth asking in the Gitter room.

**Comment by theefer** [comment]
OK thanks, will take a look at 0.15!

**Comment by OliverJAsh** [comment]
We have a requirement to cache bust our assets. This involves getting the hash of a file’s contents, updating the filename to contain this hash, and then creating an "asset hash map" to map the canonical filename to the unique, hashed filename—thus cache busting the request by enforcing a unique filename with each change.

In the case of a jspm bundle, we would want to update the path of the bundle in the injected SystemJS configuration:

``` js
{
    "bundles": {
        // "bundles/app": [
        "bundles/0cdbc20e6f8f565a6ad7f67136a19756/app": [
            "x", "y", "z"
        ]
    }
}
```

To achieve this, we need to hook into the jspm bundle to change the path of the output file—on disk *and* in the SystemJS config, like in @theefer’s [pseudo-code](https://github.com/jspm/jspm-cli/issues/412#issuecomment-84659850).

``` js
var API = require('jspm');
API.bundle('app', 'bundles/app', { inject: true }).then(function (output) {
    console.log(output);
    // => undefined
});
```

`API.bundle` doesn't give us the flexibility to do this. The bundle is already written to disk and injected in the SystemJS config. We need to hook into the bundle after the bundle output has been generated, but before the filename is written anywhere.

**Comment by OliverJAsh** [comment]
I'm currently working around this by double bundling:

``` js
var API = require('jspm');
var builder = API.Builder();
var crypto = require('crypto');

var bundlesDir = 'static/src/bundles';
var moduleExpressions = [
    'core',
    'es6/bootstraps/app - core',
    'bootstraps/app - core',
    'bootstraps/commercial - core',
    'bootstraps/sudoku - core',
    'bootstraps/image-content - core',
    'bootstraps/facia - core',
    'bootstraps/football - core',
    'bootstraps/preferences - core',
    'bootstraps/membership - core',
    'bootstraps/ophan - core',
    'bootstraps/admin - core',
    'bootstraps/video-player - core',
    'bootstraps/video-embed - core',
    'bootstraps/dev - core',
    'bootstraps/creatives - core'
];

var getHash = function (moduleExpression) {
    return builder.build(moduleExpression, 'foo.js')
        .then(function (output) {
            return crypto.createHash('md5')
                .update(output.source)
                .digest('hex');
        });
};

var bundle = function (moduleExpression, hash) {
    var moduleId = moduleExpression.replace(/ - .*?$/, '');
    return API.bundle(moduleExpression, bundlesDir + '/' + hash + '/' + moduleId + '.js', { inject: true });
};

// TODO: Promise.all
moduleExpressions.map(function (moduleExpression) {
    return getHash(moduleExpression)
        .then(function (hash) {
            return bundle(moduleExpression, hash);
        })
        .catch(function (error) {
            console.error(error);
        });
});
```

**Comment by theefer** [comment]
It sounds like ideally to avoid double bundling, the builder API would need to expose lower-level primitives such as:
* Generate bundle source and sourceMap in-memory and return them as a Promise
* Inject a bundle into the config.js file (passing the list of modules and bundle path as argument)

Is there an issue with having to know the filename for the bundle generation though?

**Comment by guybedford** [comment]
The way to do this would be by calling the builder directly with:

```javascript
var builder = new require('jspm').Builder();
builder.build('moduleA + moduleB', null, { sourceMaps: true }).then(function(output) {
  // output.source, output.sourceMap, output.modules
});
```

`output.modules` is the direct value to set in the bundles configuration.

Note the plan is to adjust the above to no longer need the `null` argument as well, which is a builder issue currently.

**Comment by OliverJAsh** [comment]
@guybedford How do you suggest writing the bundle’s hashed file to disk, and updating the SystemJS config with the bundle’s hashed file path?

**Comment by guybedford** [comment]
A configuration primitive through the API could certainly be useful. Then the `output.source` and `output.sourceMap` above should allow for hash generation into a custom path.

The alternative would be to offer this high-level API - `jspm.bundle('name', { hashed: true }` or `jspm bundle app --hashed` to automatically name the bundle file with the hash. This makes a lot of sense as well.

**Comment by guybedford** [comment]
The issue with automating the hashing is knowing when to remove the old version. @OliverJAsh or would it be ok to just run `jspm unbundle` each time?

I'm still trying to think of the best way to define custom configuration primitives.

Let me know your thoughts on which route may work best.

**Comment by OliverJAsh** [comment]
@guybedford This could be offered as a higher-level API, but I think it would be useful to improve the API's flexibility so this can be achieved manually at a low level.

``` js
// rough pseudo code
moduleId = x
remove old bundle from SystemJS config
jspm bundle moduleId
hashedFileName = hash bundle output
save bundle to disk at hashedFileName
add bundle to SystemJS config with hashedFileName
```

Perhaps something like:

``` js
jspm.bundle('moduleId')
.then(function (bundle) {
  var hash = md5(bundle.contents);
  var hashedFileName = hash + '/' + bundle.fileName
  return { fileName: hashedFileName, contents: file.contents, modules: bundle.modules };
})
.then(jspm.saveBundle)
```

Removing the old bundle from the config could be achieved by manually maintaining a map of `moduleId => bundleFileName`, and before each bundle, removing the old bundle config by looking up the file name in the map. To do this we would just need simple primitives for updating the SystemJS bundle config.

**Comment by theefer** [comment]
So if I understand @guybedford, the problem is the loss of idempotency of the bundling operation. Previously, a new bundle just replaced a previous one, whereas if the bundle id is dynamic, there is no way to identify the bundle to replace (or remove).

I guess one solution would be to introduce an additional level of indirection (see: *every problem can be solved with...*), and have `bundle -> bundle.12345 -> [ modules... ]` instead of just `bundle.12345 -> [ modules... ]`, so you'd be able to lookup the previous intermediate bundle that the virtual `bundle` resolves to and remove it before replacing it.

I'm not sure I like this idea though, it seems fiddly and complicated.

Alternatively, as @guybedford suggests, we could just assume anyone doing this level of fiddling would be expected to unbundle (remove all previous bundles) prior to re-bundling...

> Removing the old bundle from the config could be achieved by manually maintaining a map of moduleId => bundleFileName, and before each bundle, removing the old bundle config by looking up the file name in the map. To do this we would just need simple primitives for updating the SystemJS bundle config.

By this, do you mean that a single module could not be present in multiple bundles at once? That doesn't seem to be a wanted limitation though?

**Comment by OliverJAsh** [comment]
Correction: I meant a map of `moduleExpression => bundleFileName`.

**Comment by theefer** [comment]
Ah, yeah then I guess it's similar to what I wrote. And as long as the necessary primitives are exposed by the builder API, this map could be part of people's custom build scripts rather than jspm?

**Comment by OliverJAsh** [comment]
That was my thinking. I don't think this is something jspm should have to
worry about—the primitives I suggested are low level enough.

**Comment by guybedford** [comment]
Ok, let's stick with the config primatives then.

So this can be done something like:

```javascript
```

**Comment by guybedford** [comment]
Updated the code example above ^

**Comment by guybedford** [comment]
The alternative to to the config API is just to have bundles as a separate config script, which may make some sense from a caching perspective.

**Comment by OliverJAsh** [comment]
@guybedford That's a nice idea. It would mean we don't cache bust the main SystemJS config file with every new bundle.

**Comment by OliverJAsh** [comment]
Here's what I ended up with:

``` js
/*eslint-env node*/
var jspm = require('jspm');
var builder = new jspm.Builder();
var crypto = require('crypto');
var fs = require('fs');
var path = require('path');
var mkdirp = require('mkdirp');

// TODO: Read from package.json
var jspmBaseUrl = 'static/src';
var bundlesDir = 'bundles';
var bundleConfigs = [
    ['core', 'core.js'],
    ['es6/bootstraps/app - core', 'es6/bootstraps/app.js'],
    ['bootstraps/app - core', 'bootstraps/app.js'],
    ['bootstraps/commercial - core', 'bootstraps/commercial.js'],
    ['bootstraps/sudoku - core', 'bootstraps/sudoku.js'],
    ['bootstraps/image-content - core', 'bootstraps/image-content.js'],
    ['bootstraps/facia - core', 'bootstraps/facia.js'],
    ['bootstraps/football - core', 'bootstraps/football.js'],
    ['bootstraps/preferences - core', 'bootstraps/preferences.js'],
    ['bootstraps/membership - core', 'bootstraps/membership.js'],
    ['bootstraps/ophan - core', 'bootstraps/ophan.js'],
    ['bootstraps/admin - core', 'bootstraps/admin.js'],
    ['bootstraps/video-player - core', 'bootstraps/video-player.js'],
    ['bootstraps/video-embed - core', 'bootstraps/video-embed.js'],
    ['bootstraps/dev - core', 'bootstraps/dev.js'],
    ['bootstraps/creatives - core', 'bootstraps/creatives.js']
];

var getHash = function (outputSource) {
    return crypto.createHash('md5')
        .update(outputSource)
        .digest('hex');
};

Promise.all(bundleConfigs.map(function (bundleConfig) {
    var moduleExpression = bundleConfig[0];
    var outFile = bundleConfig[1];
    return builder.build(moduleExpression, null, { sourceMaps: true })
        .then(function (output) {
            var hash = getHash(output.source);
            var relativeFileName = path.join(bundlesDir, hash, outFile);
            var fileName = path.join(jspmBaseUrl, relativeFileName);

            mkdirp.sync(path.dirname(fileName));
            console.log('writing to %s', fileName);
            fs.writeFileSync(fileName, output.source);
            console.log('writing to %s', fileName + '.map');
            fs.writeFileSync(fileName + '.map', output.sourceMap);

            return { relativeFileName: relativeFileName, modules: output.modules };
        });
}))
    .then(function (bundles) {
        var bundlesConfig = bundles.reduce(function (accumulator, bundle) {
            accumulator[bundle.relativeFileName.replace('.js', '')] = bundle.modules;
            return accumulator;
        }, {});
        var configFilePath = path.join(jspmBaseUrl, 'systemjs-bundle-config.js');
        var configFileData = 'System.bundles = ' + JSON.stringify(bundlesConfig, null, '\t');
        fs.writeFileSync(configFilePath, configFileData);
    })
    .catch(function (error) {
        console.error(error);
    });
```

/cc @theefer

**Comment by laurentgoudet** [comment]
Is it me or does the builder output a different content at every build (order of the modules varies in the bundle), making the usefulness of hash limited?

**Comment by guybedford** [comment]
@laurentgoudet see https://github.com/systemjs/builder/issues/284.

**Comment by laurentgoudet** [comment]
Awesome already fixed! I just have to wait for the next release then :)

**Comment by klausbayrhammer** [comment]
@guybedford the proposed `jspm.updateConfig` api sounds very useful. Did you make any progress on that? Is there a way we could support you?

**Comment by guybedford** [comment]
@klausbayrhammer that API hasn't been developed no. Feel free to create a new issue to track a config API.
