### ISSUE TITLE
liftoff 2x / v8flags 2x released

### ISSUE THREAD

**Issue by tkellen** [jspm/jspm-cli#414]
Heya, this is just a friendly note to let you know that a new version of Liftoff and some of the dependencies commonly used in conjunction with it have been released. This release adds better support for situations where your user's configuration files are written using features behind a v8 flag (e.g. `--harmony`). Windows users and `io.js` users should see less issues if you upgrade!

Some helpful links:
https://github.com/tkellen/node-liftoff/blob/master/UPGRADING.md#100---200
https://github.com/tkellen/node-v8flags/blob/master/README.md#example
https://github.com/tkellen/node-hacker/blob/master/bin/hacker.js#L10-L14

Thanks!

**Comment by guybedford** [comment]
@tkellen sure, thanks for the update. Will check this out for the next release of jspm.

**Comment by guybedford** [comment]
Marked as contributions welcome.

**Contribution steps**:

* Update the liftoff dependency in the package.json (https://github.com/jspm/jspm-cli/blob/master/package.json#L13)
* Check the liftoff execution code in https://github.com/jspm/jspm-cli/blob/master/jspm.js for any changes that would apply from the UPGRADING guide linked above.
* Ensure the jspmConfigPath is being set correctly in https://github.com/jspm/jspm-cli/blob/master/lib/config.js#L66.

**Testing**:

* jspm global should be used by default, and if a local install in node_modules is provided, `jspm -v` should use this version and report that it is using the local version. This behaviour is described at the bottom of the section of the Getting Started guide in https://github.com/jspm/jspm-cli/wiki/Getting-Started#2-create-a-project.
* If in a subfolder of a jspm project, `jspm init` should still be able to pick up the package.json and config.js file (`cd jspm_packages/github && jspm init` should give two Ok's).

PRs welcome on this.

**Comment by guybedford** [comment]
Closed by https://github.com/jspm/jspm-cli/pull/487.
