### ISSUE TITLE
Possible documentation bug when app lives in a subdirectory

### ISSUE THREAD

**Issue by atuttle** [jspm/jspm-cli#418]
Apologies if this has come up before. I'm a complete ES6/SystemJS/JSPM noob. Tried searching but didn't see anything.

I'm seeing what I think to be a bug in either the code or the documentation. I think my problems stem from the fact that I'm attempting to start my app from a faux subdirectory. (e.g. `/admin/index.php/foo/bar/` where obviously the `/foo/bar` portion of the URL is just routing information and not actual folders)

I have the following directory structure:

```
/admin/index.php
/admin/assets/jspm/
/admin/assets/jspm_packages/
```

Given my `admin/package.json`:

```js
{
  //...
  "jspm": {
    "name": "foo",
    "directories": {
      "baseURL": ".",
      "lib": "assets/jspm",
      "packages": "assets/jspm_packages"
    },
    "dependencies": {
    }
  }
}
```

And `admin/config.js`:

```js
System.config({
  "paths": {
    "*": "*.js",
    "foo/*": "assets/jspm/*.js",
    "npm:*": "assets/jspm_packages/npm/*.js",
    "github:*": "assets/jspm_packages/github/*.js"
  }
});

System.config({
  "map": {
  }
});
```

I've found that I need to reset my `System.baseURL` on the page where the app is loaded. If excluded, SystemJS attempts to load the modules from `/admin/index.php/foo/bar/assets/jspm/app.js` rather than `/admin/assets/jspm/app.js`. However, if I add `System.baseURL = '/admin';` after including `config.js` and before importing my app, then all works as expected.

I believe this is because the `baseURL` property is pulling double duty: It's used by the jspm installer to locate the right folder on the filesystem to install to, and also by `System.import` to load modules; and those will not always be the same. In my case, `"baseURL":"."` is even removed by `jspm install ...` because it is the current directory.

I think it's possible that an additional property is needed to separate these concerns in this use-case, or the documentation should be updated to reflect the requirements... if I'm even doing it right. Am I? :)

---

[Relevant](https://github.com/jspm/jspm-cli/wiki/Application-Package-Configuration)

>Set `directories.baseURL` to be the root folder for `System.import`, relative to the package.json itself

**Comment by guybedford** [comment]
@atuttle yes this is a documentation bug - the `baseURL` does need to be set in the browser specifically in the config.js or in the page HTML itself.

**Comment by atuttle** [comment]
At first it seems like there is an implied parallel between package.json's directories.baseURL and (something) in config.js, but the more that I think about it, that may not be the case. Might I suggest renaming one or the other (or both), since they may not always be the same? Perhaps InstallBaseURL/CLIBaseURL and ImportBaseURL?

**Comment by guybedford** [comment]
They refer to the same folder, but they can be different between client and server.

**Comment by guybedford** [comment]
I think just informing that the baseURL refers to the concept of the path, not the actual path is the key thing. Then making sure the documentation clearly explains the difference.

**Comment by atuttle** [comment]
Seems reasonable.

**Comment by guybedford** [comment]
Automatic baseURL handling was added in 11.4 with https://github.com/jspm/jspm-cli/commit/20416a00a021461300cc628c40a09519b730c85e.
