### ISSUE TITLE
jspm not preserving module alias from package.json to config.js

### ISSUE THREAD

**Issue by johnsoftek** [jspm/jspm-cli#419]
When I have a dependency with an alias in package.json:
```javascript
  "jspm": {
    "dependencies": {
      "jade-compiler": "github:jadejs/jade@1.9.1"
    }
  }
```
and I run ```jspm install jade=github:johnsoftek/plugin-jade@1.2.3```, jspm creates this entry in config.js:
```javascript
    "jade": "github:johnsoftek/plugin-jade@1.2.3",
    "github:johnsoftek/plugin-jade@1.2.3": {
      "jade": "github:jadejs/jade@1.9.1"
    }
```
rather than:
```javascript
    "jade": "github:johnsoftek/plugin-jade@1.2.3",
    "github:johnsoftek/plugin-jade@1.2.3": {
      "jade-compiler": "github:jadejs/jade@1.9.1"
    }
```
The jade-compiler alias is not preserved, so when I ```require('jade-compiler')```, it fails.

I'm guessing that adding a jade-compiler entry to the jspm registry would likely solve the problem. But I think this is a bug that makes it difficult to test a plugin or module before requesting a registry update.

**Comment by guybedford** [comment]
I don't see anything in the package.json https://github.com/johnsoftek/plugin-jade/blob/1.9.0/package.json?

**Comment by johnsoftek** [comment]
It's not in master - it's in branch github-jade, tag "github" (not the best tag - maybe confusing)

If you actually want to install plugin-jade to test this version, ```jspm install jade=github:johnsoftek/plugin-jade@github```.

**Comment by guybedford** [comment]
Ok, it seems to be the right dependency still - https://github.com/johnsoftek/plugin-jade/blob/github/package.json#L32.

**Comment by johnsoftek** [comment]
https://github.com/johnsoftek/plugin-jade/blob/github-jade/package.json

**Comment by guybedford** [comment]
They you should be trying `jspm install jade=github:johnsoftek/plugin-jade@giub-jade`.

**Comment by johnsoftek** [comment]
Okay. But that is not the problem. Tag or branch should not matter. It works with tag too.

**Comment by guybedford** [comment]
The tag version doesn't have any dependencies, just the branch version.

**Comment by johnsoftek** [comment]
Okay. I spoke to soon. I just tried using the branch as you suggested and it worked fine.

**Comment by guybedford** [comment]
Sure, no problem.
