### ISSUE TITLE
Error downloading XXXX - response to large

### ISSUE THREAD

**Issue by BuildingJarl** [jspm/jspm-cli#420]
When trying to download the following package: github:mrdoob/three.js i get an error saying that the response is to large. Weird thing is that it worked last week.

![image](https://cloud.githubusercontent.com/assets/5493114/5818558/57bfedf2-a0ae-11e4-995e-513fd554d30c.png)

**Comment by guybedford** [comment]
You can increase your max repo size with `jspm config endpoints.github.maxRepoSize 1000`. Where the number is the size in MB.

**Comment by BuildingJarl** [comment]
thanks for the quick reply, ill give it a try.
