### ISSUE TITLE
jspm install npm:socket.io-client fails

### ISSUE THREAD

**Issue by benmonro** [jspm/jspm-cli#422]
after running that command i get the following error:

```

err  Error processing package config for npm:engine.io-client
     npm dependency format https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz not currently supported by jspm. Post an issue if required.
```

**Comment by guybedford** [comment]
@benmonro thanks for letting me know. The issue here is that the package depends on a tarball, which is not currently supported in jspm.

I've created an issue at https://github.com/jspm/jspm-cli/issues/424 for how we might support something like this. Sorry I don't have an easy solution for now.

**Comment by guybedford** [comment]
Closing to track at https://github.com/jspm/npm/issues/44.
