### ISSUE TITLE
Custom archive registry

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#424]
An endpoint to support loading from tarball / zip URLs:

```
  jspm install archive:github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz
```

Where the assumption is that the protocol is https first, followed by http, with redirect following provided https -> https, falling back to http if not.

Does that make sense?

**Comment by subesokun** [comment]
For me this feature would make definitely sense in case it's allowed to install from local archives as well:
```
jspm install archive:/some/path/pkg-v1.0.0.tar.gz
```
I still have no solution ready to allow installing a complex package tree offline (e.g. by preparing a big package bundle and ship it as whole). But this archive endpoint would help at least to install all top-level dependencies.

**Comment by guybedford** [comment]
Getting the addressing right is the hard part with this. Perhaps:

```
  jspm install http:github.com/file.zip
  jspm install local:c:\some\file.tar.gz
```

?

**Comment by subesokun** [comment]
That would be also ok for me. In case we don't have any space between `local:` and the file path the console auto completion won't work. In that case we can maybe also fall back to some OS agnostic filepath scheme? E.g.
```
jspm install archive:file://some/path/pkg-v1.0.0.tar.gz
```
But not sure if that is more confusing than helping.

**Comment by guybedford** [comment]
```
  jspm install file:/some/path/pkg-v1.0.0.tar.gz
  jspm install http:github.com/file.zip
```

?

**Comment by subesokun** [comment]
yes that would make sense too me :) Just wondering if we should also support installing from folders in case the packages aren't packed e.g. developer just cloned some public repo but didn't create yet an archive out of it.

**Comment by guybedford** [comment]
Yes it could support that as well for the file case, but not http. We could also potentially support installing a single js file too.

**Comment by guybedford** [comment]
What is the version assumption for these endpoints? That's the biggest blocker for me here, and why I prefer to think of endpoints as "managed registries" with versioning included.

**Comment by guybedford** [comment]
It is still a necessary feature - perhaps we can enable non-versioned endpoints in jspm.

**Comment by bfil** [comment]
+1 npm supports it, bower supports it, jspm should too :)

**Comment by guybedford** [comment]
Duplicate of https://github.com/jspm/npm/issues/55.

**Comment by guybedford** [comment]
Looking to rather handle this via the new linking workflow at https://github.com/jspm/jspm-cli/issues/622.
