### ISSUE TITLE
Improve documentation regarding plugins

### ISSUE THREAD

**Issue by ThomasBurleson** [jspm/jspm-cli#426]
The documentation for installing and use the SystemJS plugins is confusing. Newcomers must realize that the plugins must be added as `extras` to their local jspm installs:

```
jspm install css
jspm install json
```
It is also unclear as to how to use the plugin itself; does the developer use:

*  the `System.import( assets/css/avatars.css!' )`.
*  or `import 'assets/css/avatars.css!'`

So documentation clarity would be very helpful;especially when these are very amazing plugins.

**Comment by guybedford** [comment]
Certainly - contributions welcome.

**Comment by speigg** [comment]
> the plugins must be added as `extras`

Hmmm... @ThomasBurleson The way you styled the word `extras` here implied to me that "extras" is a keyword / special concept in jspm/SystemJS... just pointing this out so it doesn't confuse anyone else (like me, a "newcomer" :smile:)

> the `System.import( assets/css/avatars.css!' )`.
> or `import 'assets/css/avatars.css!'`

Aren't these doing exactly the same thing? (except maybe System.import is asynchronous, but other than that?)

**Comment by guybedford** [comment]
Thanks, I've documented plugins including these points at https://github.com/jspm/jspm-cli/wiki/Plugins.

**Comment by ThomasBurleson** [comment]
@guybedford - :+1:  I really like the Plugins docs. 
@speigg  - exactly they essentially do the same thing (which is why I wanted documentation to say that to reduce confusion). The notable difference is that `System.import()` has some nice power with:

 ```js
System.import( <file> ).then(function( fileContent){ ... });
````
