### ISSUE TITLE
Cannot install package including export { Promise }

### ISSUE THREAD

**Issue by theefer** [jspm/jspm-cli#427]
When trying to install a file that contains:

``` javascript
export { Promise };
```
[any-promise-es6.js](https://github.com/argo-rest/any-promise-es6/blob/master/src/any-promise-es6.js)

jspm errors with:

```
$ jspm install npm:any-promise-es6
     Looking up npm:any-promise-es6
     Updating registry cache...
     Downloading npm:any-promise-es6@0.1.0

err  Error building package npm:any-promise-es6
     TypeError: Object.keys called on non-object

warn Installation changes not saved.
```

The export statement seems to compile file in the Traceur demo.

Is this a jspm bug?

**Comment by guybedford** [comment]
@theefer are you running the latest jspm? I can confirm this is working for me on master.

**Comment by theefer** [comment]
Oh, I guess I wasn't (I've got a mix of local and global jspms, and my global one may have been on 0.10.4 for a while yesterday). Great!
