### ISSUE TITLE
Directory names of dependencies

### ISSUE THREAD

**Issue by olanod** [jspm/jspm-cli#429]
Is it possible to change the names of the directories of the installed dependencies? I'd like the directory not to have the @X.X.X suffix.  
I'm using jspm to install polymer components(apart from my other js dependencies) which depend on each other, so if I include one component with an HTML import it will try to include others with a relative path but because of the semver suffix it wont find the other components.

**Comment by guybedford** [comment]
@olanod jspm is multi-version from the core. Bower is the best tool for installing web components that rely on that HTML import pattern you describe.
