### ISSUE TITLE
Exception when importing global remotestorage.js after bundling

### ISSUE THREAD

**Issue by lewisl9029** [jspm/jspm-cli#435]
I'm importing the [remotestorage.js](https://github.com/remotestorage/remotestorage.js) library as a global from the /release/0.11.0/remotestorage.js file in their repo.

Everything works fine when I dev with separate files without bundling, but when I build a bundle and run it, I end up getting the following error: 

```
Potentially unhandled rejection [2] ReferenceError: Error loading "app" at file:///L:/Develop/toc/prod/www/app.js
global is not defined
    at file:///L:/Develop/toc/prod/www/app.js:19092:50
    at file:///L:/Develop/toc/prod/www/app.js:25669:6
    at c (file:///L:/Develop/toc/prod/www/jspm_packages/system.js:1:4771)
    at d (file:///L:/Develop/toc/prod/www/jspm_packages/system.js:1:4387)
    at file:///L:/Develop/toc/prod/www/jspm_packages/system.js:1:4856
    at file:///L:/Develop/toc/prod/www/app.js:25952:20
    at c (file:///L:/Develop/toc/prod/www/jspm_packages/system.js:1:4771)
    at s (file:///L:/Develop/toc/prod/www/jspm_packages/system.js:1:3462)
    at Object.$__global.upgradeSystemLoader.e.instantiate.Promise.all.then.execute (file:///L:/Develop/toc/prod/www/jspm_packages/system.js:1:6882)
    at o (file:///L:/Develop/toc/prod/www/jspm_packages/es6-module-loader.js:7:17751)
```

The problem seems to have something to do with the wrapper they're using for their individual internal modules: 
```
(function (global) {
//module content here
})(typeof(window) !== 'undefined' ? window : global); //exception occurs here
```

Any idea why this would work when serving as separate files but throw an exception when bundled?

**Comment by guybedford** [comment]
@lewisl9029 if you have a test case or steps to reproduce that would help a lot here.

It seems like you just need to get the override for this repo right first though.

Have you tried loading the AMD version?

**Comment by lewisl9029** [comment]
I made a fresh repo here to demonstrate the issue: https://github.com/lewisl9029/jspm-test

If you open /index.html in chrome (with the --disable-web-security flag), you should see no errors in the console.
If you open /build/index.html in chrome, you should see the "global is not defined" error above.

The exact steps I took to build the test project:
1. Make the custom app.js, initialize.js, index.html, override.json files
2. `jspm init` with all default options
3. `jspm install github:remotestorage/remotestorage.js -o override.json`
4. `jspm bundle app build/app.js`
5. copy index.html, config.js from root, and traceur.js, system.js, es6-module-loader.js from jspm_packages folder to /build

Here's what override.json looks like:

```js
{
  "registry": "jspm",
  "main": "release/0.11.0/remotestorage",
  "format": "global",
  "dependencies": {}
}
```

I'm still not too familiar with the override process so this could very likely be where the problem is.

Please let me know if you see anything that doesn't look right or could be done better. =)

**Comment by guybedford** [comment]
Ok the issue is here - https://github.com/remotestorage/remotestorage.js/blob/master/release/0.11.0/remotestorage.js#L5306.

The variable declaration is resulting in the window variable being redefined when the source is wrapped in a closure.

I've added a fix to SystemJS builder here - https://github.com/systemjs/builder/commit/20121f7abe56e86b9fc3cf9ca36f0b6e1d762b58 that will resolve this issue. Perhaps see if you can merge that into your project, the release will be coming in the next few days.

**Comment by lewisl9029** [comment]
Thanks for the super quick fix, as always. =)

Bundling isn't really a necessity yet in this very early stage project I'm working on, so I'll wait for the release. Looking forward to trying out the new version though!
