### ISSUE TITLE
"Bold versions are linked" always comes up when a package is installed

### ISSUE THREAD

**Issue by speigg** [jspm/jspm-cli#437]
I have one package that is linked, but the message "Bold versions are linked" comes up whenever I run "jspm install something", for example, `jspm install image`, which is confusing, because the package "image" is not linked, yet it is displayed as bold:

```
$ jspm install image
     Updating registry cache...
     Looking up github:systemjs/plugin-image
ok   Up to date - **image** as github:systemjs/plugin-image@master (master)
     
Bold versions are linked. To unlink use jspm install --unlink [name].
ok   Install tree has no forks.

ok   Install complete.
```

**Comment by guybedford** [comment]
Thanks, fixed in https://github.com/jspm/jspm-cli/commit/0cf5511bad87f5e7e6c97539556f326f1618554e.
