### ISSUE TITLE
Exclude AMD dependencies when bundling

### ISSUE THREAD

**Issue by piuccio** [jspm/jspm-cli#440]
Hi, I'm trying to use jspm to bundle files.
I have some AMD files, but one of them is generated by the server and added to the page like this

```
   <script>
      System.amdDefine('fromServer', function () {
         return {} // an object generated server side
      });
   </script>
```

When I bundle, I get an error even if I try to exclude that module.

I've created a project where you can more easily have a look.
https://github.com/piuccio/jspm-bundle

Is there an issue in jspm-cli when ignoring modules? Is there anything that I can do from the config file?

Cheers

**Comment by guybedford** [comment]
Yes bundling will try to load all dependencies, even when excluding. 

I would suggest adding a configuration for bundling only (removing it for production) to make the excluded dependency loadable:

```javascript
if (!production)
System.config({
  map: {
    'fromServer': '@empty'
  }
});
```

**Comment by guybedford** [comment]
Let me know how you get on, closing for now.
