### ISSUE TITLE
require path in windows

### ISSUE THREAD

**Issue by u9520107** [jspm/jspm-cli#443]
Currenlty with fresh install of jspm, I could not get react to be bundled up.
The issue appears to be with the path in react@x.x.x/react.js:
In the github repo it looks like this:
```
module.exports = require('./lib/React');
```
But in the jspm_packages folder it got turned into this:
```
module.exports = require('./lib\React');
```
The backlash should be a bug?

**Comment by guybedford** [comment]
Thanks - I've added a fix in https://github.com/jspm/npm/commit/5981f834ec3d76616981f443e147a86305bf712c, let me know if that works for you.

**Comment by u9520107** [comment]
I went into the my global node_modules.. found jspm, and modified the npm.js in the jspm's node_modules. And then I deleted jspm_packages from my project and installed everything again. Also tried install -f react. But still the path is wrong. 
I added a fs.appendFileSync call after the line you modified hoping to see the modified result, but that line didn't seem to be executed at all...
Maybe I modified the wrong copy of npm.js

**Comment by u9520107** [comment]
It appears that the bundler would try to find the files in the wrong place. The error would say that it couldn't open ...\jspm_package\npm\react@0.12.2\DOMPropertyOperations.js
Where the actual path should be: ...\jspm_packages\npm\react@0.12.2\lib\DOMPropertyOperations.js
I am guessing that it's not handling the files thats included via "files":["lib/", "dist/"...] defined in react's package.json. 
Tested with windows using jspm-cli 0.11.0.

**Comment by guybedford** [comment]
If I do the following on a fresh install in windows, it works fine for me:

```
  jspm install react
  jspm bundle react
```

What other steps would I need to to do reproduce this?

**Comment by u9520107** [comment]
@guybedford It works when I do that too... but not in my project folder.
Weird.. I'll fiddle around a bit to see I can dig up more stuff.

**Comment by guybedford** [comment]
@u9520107 ok sure, thanks - just let me know if you notice any other issues, clear reporting helps so much.
