### ISSUE TITLE
Add some more documentation about bundle-sfx

### ISSUE THREAD

**Issue by SekibOmazic** [jspm/jspm-cli#445]
Hi,

it would be really nice to have some more documentation about bundle-sfx option, especially when using --minify flag. I have an issue in my own project using jspm and AngularJS (https://github.com/SekibOmazic/angular-es6-jspm/issues/2) and better documentation would be helpful.

Btw, great work on jspm, Systemjs and es6-module-loader.

**Comment by guybedford** [comment]
I'm not sure what documentation specifically you would like here?

This could be a bug with the mangling somehow, perhaps https://github.com/systemjs/builder/pull/57 will help.

**Comment by SekibOmazic** [comment]
@guybedford Well I didn't look at the source code so I didn't realize it depends on uglify-js. And that library has an issue when applying on angular code (mangle option has to be set to false). 
But the mentioned PR seems to address exactly that. 

Actually no need to change the documentation for this. A quick look at the source code was enough. Please close this issue.
