### ISSUE TITLE
`jspm link` takes longer than it probably should

### ISSUE THREAD

**Issue by speigg** [jspm/jspm-cli#451]
Takes on averages about ~~4-5 seconds~~ (actually it's more like 10-15 seconds). I would expect this to be much faster...?
I tried using the `files` option in the package.json, but that didn't seem to make a difference.

**Comment by speigg** [comment]
It looks like linking copies the package into `~/.jspm/linked`. Wouldn't it be better to link directly to the original folder?

**Comment by speigg** [comment]
I added the following to my package.json:
```
  "directories": {
    "dist": "dist"
  },
```
This speeds up `jspm link endoint:package@version` a fraction of a second, but it's broken... the `~/.jspm/linked/endpoint/package@version` directory is now empty.

**Comment by trusktr** [comment]
Try 

```
  "directories": {
    "dist": "dist"
  }
```

Does that help? Also, I think this: #455

**Comment by trusktr** [comment]
Try 

```
  "directories": {
    "lib": "dist"
  }
```

Does that help? Also, I think this: #455

**Comment by speigg** [comment]
Nope... still empty :(

**Comment by speigg** [comment]
So... it is processing literally the entire dependency chain (this is why linking is taking 15 seconds for me). Everything in `node_modules` and `bower_modules` is processed, and I don't know how to tell `jspm link` to ignore everything except the `dist` directory.

**Comment by guybedford** [comment]
@speigg yes using a `directories.dist` or `directories.lib` is exactly the way to avoid processing everything. Link should follow files and ignore as well, and this is being tracked at https://github.com/jspm/jspm-cli/issues/345.

Linking is definitely working with `directories.dist` and `directories.lib` - I've just tested it again now. It wasn't working for a while though - perhaps make sure that the global version of jspm is completely up-to-date when doing the linking?

**Comment by guybedford** [comment]
Closing as I believe this is working as expected. We can continue to track the `files` and `ignore` support at #345.

**Comment by speigg** [comment]
@guybedford I haven't had the chance to check this until now, but I've udated to the latest jspm and I'm still seeing the same behavior. Using directories.dist or directories.lib (doesn't matter which one) results in an empty `~/.jspm/linked/endpoint/package@version` directory

**Comment by speigg** [comment]
@guybedford Okay, I figured out my problem. I was using `files` in combination with `directories.lib`. I think `files` was being evaluated in the scope of `directories.lib`. I'm not sure if that is a bug, or if that is the expected behavior. Anyway, removing `files` and just relying on `directories.lib` worked for me.

**Comment by guybedford** [comment]
@speigg thanks that really helps to clarify this case - I'm sure we can do something to optimize this.
