### ISSUE TITLE
Bad response code 406

### ISSUE THREAD

**Issue by trusktr** [jspm/jspm-cli#452]
I'm getting

```
err  Error downloading github:MikeMcl/big.js
     Bad response code 406
```

This is after setting up github credentials, but I don't know if that's the cause because before that I was only getting the github rate limit errors.

**Comment by trusktr** [comment]
Oh, yeah, seems like it's credential related. What permission does jspm need?

**Comment by trusktr** [comment]
Added public_repo

**Comment by guybedford** [comment]
Thanks, I've created an issue for a better message on this at https://github.com/jspm/github/issues/33.
