### ISSUE TITLE
Syntax error: Unterminated quoted string

### ISSUE THREAD

**Issue by bekite** [jspm/jspm-cli#453]
Password credentials are not escaped properly.

Steps to reproduce error:
1. ```jspm endpoint config github```
2. Enter a password containing a single quotation mark
3. ```jspm i```

Should show error: ```Syntax error: Unterminated quoted string```

Using an access token instead of the password worked just fine.

**Comment by guybedford** [comment]
This is working ok for me - are you definitely running the latest version of jspm?

**Comment by bekite** [comment]
The installed version of jspm is 0.10.6
I forgot to mention that the os is Ubuntu 14.04.

**Comment by guybedford** [comment]
Thanks, I've fixed this, should get the fix with jspm@0.11.
