### ISSUE TITLE
err  Unable to load endpoint css@jspm

### ISSUE THREAD

**Issue by trusktr** [jspm/jspm-cli#454]
I wasn't getting this before. I've been away for a while. I'm running

```
jspm install -y leaflet=github:RickMohr/Leaflet@better-inertial-scrolling -o '{ "registry": "npm", "main":"dist/leaflet", "dependencies": { "css": "jspm:css@^0.1.0" }, "shim": { "dist/leaflet": { "deps": ["./leaflet.css!"], "exports": "L" } } }'
```

**Comment by trusktr** [comment]
Duh, registry:jspm

**Comment by trusktr** [comment]
Problem solved:

https://www.npmjs.com/package/system-css
https://www.npmjs.com/package/system-image
https://www.npmjs.com/package/system-text
https://www.npmjs.com/package/system-json (@justinbmeyer)

**Comment by guybedford** [comment]
I'd be interested to know why you need the `registry: "npm"` property in that override at all?

The reason this happens is that when you have `registry: "npm"`, jspm treats the `dependencies` object exactly like it would get treated on npm - `jspm:css` no longer holds any meaning in this context as npm doesn't understand it.

Creating new repos for the plugins on npm is not a fix but a workaround, and has created a new maintenance problem for yourself.

**Comment by trusktr** [comment]
> I'd be interested to know why you need the registry: "npm" property in that override at all?

No idea. Because I've had problems in the past when not having a registry property set, so I thought I'd just set it? This is foggy to me. IMHO, the property should be done away with, and let packages come from anywhere, `github:`, `npm:`, or the jspm registry if only a version is specified, with packages being treated as equally as possible regardless of endpoint, abolishing segregation.

**Comment by guybedford** [comment]
@trusktr `registry: npm` means that the package is a published and working npm package following the npm rules. Which means npm-style dependencies. This is a documentation issue I know. Focusing on stability first.

**Comment by trusktr** [comment]
Since the `jspm` section of package.json is specific to jspm, I think allowing non-npm deps there wouldn't be a bad thing, since those deps are being handled by jspm, not npm.

**Comment by guybedford** [comment]
It is allowed - but only if you don't have `registry: npm`. jspm is a registry of registries. Once you've set the registry you abide by the rules of that registry.

**Comment by trusktr** [comment]
> jspm is a registry of registries. Once you've set the registry you abide by the rules of that registry.

Excellent words, put these words in the docs.

So I can publish a package to npm without registry:npm, and jspm will fetch none npm deps from the jspm field of package.json?

**Comment by guybedford** [comment]
Sure, will work on that.

By default something on npm is assumed to have `registry: npm`. If you don't want the npm deps you have to have a `jspm.dependencies = {}`.

**Comment by trusktr** [comment]
So if `registry: npm` is set in an npm package, and `jspm.dependencies = {foo:'github:foo/bar@baz'}` is set, then it'll get the dep from `github:`?

**Comment by guybedford** [comment]
No, because npm does not support this style of dependencies.

**Comment by trusktr** [comment]
Ok, you can change the deps, but they still have to be npm-style deps.

Why not let the jspm field contain jspm-style deps, regardless of the registry property, and let the registry property affect only dependencies with a version number be affected by the registry value. Some examples:

```js
{
  "registry": "npm",
  "dependencies": {
    "army-knife":"^0.2.1",
    "infamous": "0.0.34"
  },
  "jspm": {
    "dependencies": {

      // from npm, since registry is set to npm.
      "army-knife":"^0.2.1",

      // from github, jspm-style, ignore the registry value, and allowed only in the jspm field.
      "infamous": "github:infamous/infamous@0.0.34"
    },
  }
}
```

and here we change the registry value to jspm:

```js
{
  "registry": "jspm",
  "dependencies": {
    "army-knife":"^0.2.1",
    "infamous": "0.0.34"
  },
  "jspm": {
    "dependencies": {

      // Uses the jspm registry, since registry is set to jspm.
      "army-knife":"^0.2.1",

      // from github, jspm-style, ignore the registry value, and allowed only in the jspm field.
      "infamous": "github:infamous/infamous@0.0.34"
    }
  }
}
```

With no registry property set, then jspm can assume registry:npm if the package comes from npm, or registry:jspm if it is gotten via the jspm registry.

This might make the dep-style more consistent in the world of jspm, so people just think of one style, and the registry value only affects deps defined with no specific endpoint.

I thin in most cases that'd lead to intuition just working out. And plus, if a package isn't found in the expected registry, then it can check the other.

Ultimately it'd be very nice for users not to worry about where the code comes from, as long as it comes. The user can adjust their project based on what code arrives (e.g. a package might have one format in a registry, and another format from the other place, but who cares, we can adapt, and package management just works).

**Comment by trusktr** [comment]
I might know how dep resolution works as well as you, but I'm only merely suggesting how things would be much more easy for the jspm user. The internals, the end user shouldn't care about that.

**Comment by trusktr** [comment]
It is confusing to have to worry about to different package syntaxes. One single style would prevent confusion among end users.

**Comment by guybedford** [comment]
@trusktr the jspm property is nothing more than an override of the base-level package.json from the perspective of jspm. The rules are designed to be simple.

**Comment by trusktr** [comment]
Jspm is the first package manager I've tried where dependencies must be specified in one format or another, depending on some other thing in the environment (e.g. the registry property). That might not be initially simple or expected. Perhaps docs will clear this up, but it's not obvious up front.
