### ISSUE TITLE
Idea for jspm link and live changes without having to use versions.

### ISSUE THREAD

**Issue by trusktr** [jspm/jspm-cli#455]
I can't seem to get the hang of jspm "link". I've done `jspm link npm:infamous@0.0.33` from in the local repo folder (which is a few commits ahead of the actual 0.0.33 commit that is published on npmjs), but whenever I install npm:infamous@0.0.33 it seems to be installing either the one from npm, or the actual 0.0.33 local commit. I'm not seeing my latest changes being installed in the project. So, to actually test my changes, I'm publishing new patch version just to test them (which obviously I totally shouldn't do, but it's still in 0.0.x, so it's ok for now).

The idea with npm link and bower link is that I can make changes in the linked package locally, and those changes are available instantly in other local packages.

I noticed that jspm link takes the local package in it current state and transforms it into it's would-be final state, and puts it in ~/.jspm/linked.

Idea: To better match the behavior of npm link and bower link, maybe you can allow us to do `jspm link npm:infamous` without needing the version number. Without the version number, an actual symlink is made in ~/.jspm/linked to the local package folder. When someone installs that package in a local project, then jspm just gets the source from the linked spot, processes it like it would had it come from github or npm, then places the result into the project's jspm_packages.

That would mirror the familiar npm link functionality.

If a version *is* provided, then that can work like it does now. If a user installs that matching version in the project, then the package is gotten from ~/.jspm/linked, but if there's no matching version, then it can fall back to the linked-without-version behavior.

How about that?

**Comment by speigg** [comment]
You have to use `jspm install --link npm:infamous@0.0.33` in the other package

**Comment by trusktr** [comment]
Oh @#$%, I missed the `--link` arg.

I'd say mirror the `npm link` usage patterns. It will be intuitive since `npm` is the original and diffinitive javascript package manager.

**Comment by trusktr** [comment]
Seems like `jspm install --link -y` isn't working. Just `jspm install -y` automatically using linked packages would be great!

**Comment by guybedford** [comment]
Yes it seems there is a bug in jspm link, looking into it at https://github.com/jspm/jspm-cli/issues/451#issuecomment-72329927.
