### ISSUE TITLE
“Which ES6 parser would you like to use”

### ISSUE THREAD

**Issue by rauschma** [jspm/jspm-cli#458]
Is “parser” really the right word here? How about “transpiler”?

**Comment by rauschma** [comment]
Context: `jspm init`.

    Which ES6 parser would you like to use, Traceur or 6to5?

**Comment by guybedford** [comment]
This is a configuration option at `System.parser` (https://github.com/systemjs/systemjs#browser-use). Transpiler would make more sense in this question context I suppose. Do you think it is the wrong term though? I guess I favour the less typing!

**Comment by guybedford** [comment]
@rauschma having to do a major release of the loader now - do you think I should change this to `System.transpiler` (https://github.com/ModuleLoader/es6-module-loader#getting-started)?

**Comment by guybedford** [comment]
I've changed the wording in the message. If you think the API should be `transpiler`, would value feedback.

**Comment by johnsoftek** [comment]
+1 for transpiler

6to5 refers "6to5 and other ES6 transpilers". traceur calls itself a compiler. Neither mentions "parser".

I prefer transpiler to compiler.

**Comment by guybedford** [comment]
Ok, point taken. I've posted https://github.com/ModuleLoader/es6-module-loader/pull/298.

**Comment by guybedford** [comment]
API change has been completed in https://github.com/jspm/jspm-cli/commit/288e9e03c73c3144b2c14f793b069d40ae992259.

**Comment by rauschma** [comment]
I agree with what @johnsoftek said. If you use Traceur and 6to5 (only) to parse, I’d write “parser”, if you use them to transpile, I’d write “transpiler”.
