### ISSUE TITLE
“Name for project”

### ISSUE THREAD

**Issue by rauschma** [jspm/jspm-cli#459]
During `jspm init` you are asked the following question: “Enter a name for the project”.

* This is an alternate name for the “project code folder”, right? Shouldn’t it be described differently, then?
* Don’t most people use the default (= same name for “name for the project” and “project code folder”)? If so, I’d keep it as an option, but would not ask for the project name during `jspm init`.

Am I making sense?

**Comment by guybedford** [comment]
@rauschma thanks for asking - it's these sorts of initial usability questions that are great to polish.

It's the package.json **name** property, which is assumed to be the name in the registry and is then created as an alias to the `lib` folder (the default folder for the question "Enter the project code folder").

That is `import('app/main')` then loads from `lib/main`. The idea is that we're writing the tests and everything to load it by the same name it will be installed into, but I know it's not nearly as clear as it should be, this mainly being a documentation issue?

**Comment by guybedford** [comment]
I've worded this better in https://github.com/jspm/jspm-cli/commit/32f8d18e76d5e6e0255a6c3ca6fe4198b0af9fac, and also documented at https://github.com/jspm/jspm-cli/wiki/Getting-Started#2-create-a-project.
