### ISSUE TITLE
package is installed with different name than I specified.

### ISSUE THREAD

**Issue by trusktr** [jspm/jspm-cli#465]
When I install `github:trusktr/famous@jspm`, it puts famous-polyfills at `jspm_packages/github/Famous/polyfills@0.3.0`, missing the `famous-` prefix.

Here's famous' [package.json](https://github.com/Famous/famous/blob/master/package.json) and famous-polyfills' [package.json](https://github.com/Famous/polyfills/blob/master/package.json).

Why is this happening? Shouldn't it be `jspm_packages/github/Famous/famous-polyfills@0.3.0`

**Comment by trusktr** [comment]
I can make it work by modifying the directory name, and changing the references to it in config.js and the generated module entry point. I can also just use `npm:famous-polyfills` and that works.

**Comment by guybedford** [comment]
GitHub repos are named by their repo names on GitHub.

**Comment by trusktr** [comment]
@guybedford Okay, but jspm.dependencies contains

```js
      "famous-polyfills": "github:Famous/polyfills@master"
```

so intuition would lead me to believe that `require('famous-polyfills')` in my code will work, which isn't the case. It'd be super nice if it worked that way.

**Comment by trusktr** [comment]
I think I mis-stated the problem. I know all the github packages get installed with their actual repo names, but the loader is looking for a folder called `famous-polyfills` for some reason, that's why renaming the folder was a temporary fix.

**Comment by trusktr** [comment]
So what's happening is this: shims aren't working with famous, so I'm manually inserting `"deps famous-polyfills"` into the top of each source file (what you recommend instead of that) so that `famous-polyfills` gets loaded, and the loader is looking for `jspm_packages/github/Famous/famous-polyfills`. When I instead use npm:famous-polyfills, it works out just fine.

**Comment by trusktr** [comment]
Hmmm, well I can't reproduce the problem that I thought I saw, but, as mentioned in some other issue, the modules can't be loaded because they use require calls with .js as in `require('foo.js')` so the loader can't find foo.js.js, 404. (pain point)

**Comment by guybedford** [comment]
Note as mentioned on #177, that installing from npm will handle removing `.js` in module names.

**Comment by trusktr** [comment]
Yeah, I remember that, but the fact that it doesn't work with non-npm endpoints is a pain point and unexpected. I mean, when is `foo.js` not actually `foo.js`? No one -- *no one* -- names their files `foo.js.js`. That's an error.
