### ISSUE TITLE
jspm init copies npm dependencies as jspm dependency in package.json

### ISSUE THREAD

**Issue by Jarreddebeer** [jspm/jspm-cli#466]
Sorry if this exists in another issue..

I had an existing package.json with the following:

 ...
"dependencies": {
     "http-proxy": "^1.3.0"
 },
...

I ran jspm init with the following:

Would you like jspm to prefix the jspm package.json properties under jspm? [yes]: yes
Configuration file config.js doesn't exist, create it? [yes]: yes

the resulting package.json resulted in:

...
"jspm": {
     "dependencies": {
       "http-proxy": "jspm:http-proxy@^1.3.0"
     }
}

then later down the line jspm install resulted in:

err  Repo jspm:http-proxy not found!

---
I don't think this is a pressing issue at all though

**Comment by guybedford** [comment]
Thanks so much for reporting, this should be fixed in https://github.com/jspm/jspm-cli/commit/a9e310a945cd5a5301e2e0ba8a3313ef90f74b25.

**Comment by guybedford** [comment]
Patch released in 0.11.3.

**Comment by Jarreddebeer** [comment]
Awesome :-)
