### ISSUE TITLE
windows error with react...

### ISSUE THREAD

**Issue by chrismcv** [jspm/jspm-cli#468]
Hi, 
Fairly new to this, and trying some stuff out on windows.

`jspm install react`

```
$ cat public/jspm_packages/npm/react\@0.12.2/react.js
/* */
module.exports = require("./lib\React");
```
The `\` seems to being put in, and this is causing errors.

```
Uncaught TypeError: Module ./libReact not declared as a dependency.
es6-module-loader.js:7 Potentially unhandled rejection [2] Error loading "npm:react@0.12.2" at http://localhost:2929/jspm_packages/npm/react@0.12.2.js
Error evaluating http://localhost:2929/jspm_packages/npm/react@0.12.2.js
Uncaught Error evaluating http://localhost:2929/jspm_packages/npm/react@0.12.2/react.js
Uncaught TypeError: Module ./libReact not declared as a dependency. (WARNING: non-Error used)
```

If I change the `\` to a `/` then all is fine.  Is this something that jspm is doing?

Thanks, 
Chris

**Comment by guybedford** [comment]
Hi, yes this was a bug that was resolved recently - can ensure you're running the latest version of jspm (0.11.3)? Use `jspm -v` to see the version.

**Comment by chrismcv** [comment]
Thanks for the quick response, that's it sorted.  My bad.  Sorry for wasting your time.

**Comment by guybedford** [comment]
Sure, glad to hear it's working ok.
