### ISSUE TITLE
directories.lib gets removed if set to current directory

### ISSUE THREAD

**Issue by stefanr** [jspm/jspm-cli#469]
The option for directories.lib gets removed if set to current directory with the following stages:
```json
"directories": {
  "lib": "./"
},
```
$ jspm install ...
```json
"directories": {
  "lib": ""
},
```
$ jspm install ...
```json
"directories": {
},
```

The problem may be due to something like:
```js
if (directories.lib)
```
instead of
```js
if (directories.lib !== undefined)
```

**Comment by guybedford** [comment]
Thanks, fixed in 5a08c648ce89f859dbecc25745bf0132b7b0fa96.
