### ISSUE TITLE
Local linked projects and gulp copy

### ISSUE THREAD

**Issue by volak** [jspm/jspm-cli#470]
In reference to #82 - I am using a local library (kendo) which I linked into jspm.  It created the symlink fine, but I get an EISDIR error from gulp when copying jspm_packages into my build directory.

The error seems to be related to https://github.com/wearefractal/vinyl-fs/issues/39

Depending on what you think, I guess this should either be a known issue in docs or hopefully there is some sort of work around =/

**Comment by guybedford** [comment]
Thanks for reporting, yes this would be good to document for gulp workflows until that is fixed.

**Comment by guybedford** [comment]
Closing as there's nothing to do here in jspm for now.

**Comment by andreasgrimm** [comment]
@volak In addition to serving the build artifacts I simply static-serve `jspm_packages` from the original location even in production.
