### ISSUE TITLE
Cannot configure for my directory structure

### ISSUE THREAD

**Issue by Serhioromano** [jspm/jspm-cli#472]
I am sure I simply cannot understand something. Please help.

I have directory structure.

![2015-02-03_23-49-39](https://cloud.githubusercontent.com/assets/650741/6023459/ea5c3a74-abff-11e4-908c-bdd70243b1f1.png)

The idea behind this structure is that I have folder `build` which is site root. So my `config.js`, `index.html` packages and transcoded ES6 files are there in `modules` folder.

But my `src` folder is outside the site root. This way I keep my `build` folder clean. I do not need to clean it before deploy. Here is my jsmp configuration.

```json
"jspm": {
    "directories": {
      "baseURL": "modules",
      "packages": "build/assets/jspm"
    },
    "configFile": "build/config.js",
    "dependencies": {
      "aurelia-bootstrapper": "^0.9.3",
      "bootstrap": "^3.3.2"
    }
}
```

The problem is that after package install or update in my `config.js` I have this

```js
System.config({
  "paths": {
    "*": "*.js",
    "aurelia-app/*": "lib/*.js",
    "github:*": "../build/assets/jspm/github/*.js",
    "npm:*": "../build/assets/jspm/npm/*.js"
  }
});
```

When for correct functioning I have to have 

```js
System.config({
  "paths": {
    "*": "*.js",
    "aurelia-app/*": "lib/*.js",
    "github:*": "assets/jspm/github/*.js",
    "npm:*": "assets/jspm/npm/*.js"
  }
});
``
 
If in `package.json` I change `"packages": "build/assets/jspm"` to `"packages": "assets/jspm"` then I get it right,  but packages are installed into wrong location.

How can I configure?

**Comment by guybedford** [comment]
Try setting your `directories.baseURL` to `build`, and your `directories.lib` to `build/modules`. Then the `aurelia-app` path jspm creates for you will go to your modules path so you can do `import "aurelia-app/app"` etc.

**Comment by Serhioromano** [comment]
> Try setting your directories.baseURL to build

This is what I did. And I override this in ``index.html` by `System.baseUrl = 'modules'`. This works fine now.

> and your directories.lib to build/modules

Then it will look in `modules/build/`
