### ISSUE TITLE
Ignore/warn on deprecated packages from npm dependencies

### ISSUE THREAD

**Issue by jamespamplin** [jspm/jspm-cli#473]
I've found that jspm can install a deprecated package from npm.

```
jspm install angular=npm:angular
```
This will install an incorrectly packaged angular v1.3.36 which is marked as deprecated in npm. Correct version is 1.3.11, see https://www.npmjs.com/package/angular

`jspm install` should resolve the latest semver package that isn't deprecated.

If a dependency is locked to a deprecated version in `package.json`, a warning should probably show during the install process.

Thanks!

**Comment by jamespamplin** [comment]
`jspm inspect npm:angular` also incorrectly resolves to 1.3.36

**Comment by guybedford** [comment]
Thanks, I've fixed this in https://github.com/jspm/npm/commit/34826197d0df03b9c30a6d022a9f97eb6a91bc34.

Unfortunately it requires a manual clear of the npm lookup cache though (`rm -r ~/.jspm/npm-cache`), will think about better upgrade paths for this.

**Comment by jamespamplin** [comment]
Great, thanks!
