### ISSUE TITLE
Multiple CDN paths

### ISSUE THREAD

**Issue by jhoguet** [jspm/jspm-cli#474]
In short, is it possible to load modules from different paths? 

The use case is: 

- app-a depends on mod-1@1.0.0.js and a.js
- app-b depends on mod-1@1.0.0.js and b.js
- app-a and app-b are independent web apps, but they use the same CDN
- users use both app-a and app-b in their workflows (they think they are just one app)
- ideally, the path to mod-1@1.0.0.js would be something like http://cdn/third-party/mod-1@1.0.0.js while the path to the app specific javascript would live within their own folders, something like http://cdn/app-a/0.4.2/a.js and http://cdn/app-b/0.2.6/b.js so that we can get the cache hit for the common code. 

I noticed that we can set the baseUrl `System.baseURL = '/';` but this would be universal. 

I am seeing code related to CDN https://github.com/jspm/jspm-cli/search?utf8=%E2%9C%93&q=isCDN but it isn't jumping out to me where this is configured, and if it even package specific. 

thanks in advance

**Comment by guybedford** [comment]
@jhoguet yes this is what map configuration is designed for. Perhaps try something like:

```javascript
System.config({
  paths: {
    'cdn/*': 'http://cdn.com/*.js'
  },
  map: {
    "app-a": "cdn/app-a/0.4.2",
    "app-b": "cdn/app-b/0.4.2",
    "mod-1": "cdn/third-party/mod-1@1.0.0"
  }
});
```

Then you can do `System.import('app-a/main')` with imports internally all as expected.

**Comment by jhoguet** [comment]
that makes sense now - thank you
