### ISSUE TITLE
jspm install from npm with jspm registry package referenced

### ISSUE THREAD

**Issue by djindjic** [jspm/jspm-cli#476]
I'm trying to install my own jspm lib from npm but this lib has reference to other lib which is added into jspm registry. jspm install tries to download it from npm without looking into jspm/registry configuration:
```bash
aleksandar@hpprog:~/projects/testjspm$ jspm install npm:metabolicjs
     Looking up npm:metabolicjs
     Updating registry cache...
     Looking up npm:aurelia-dependency-injection
     Looking up npm:forwardablejs

err  Repo aurelia-dependency-injection not found!

warn Installation changes not saved.
```

As it is shown in log, jspm is  looking up to `npm:aurelia-dependency-injection` insted of just `aurelia-dependency-injection`

My package.json is configured like [this](https://github.com/djindjic/metabolicjs/blob/master/package.json#L9), and dependency injection config is [here](https://github.com/jspm/registry/blob/master/registry.json#L41).

**Comment by guybedford** [comment]
Try adding `registry: jspm` to your package.json.

**Comment by djindjic** [comment]
I have it here:
https://github.com/djindjic/metabolicjs/blob/master/package.json#L2

**Comment by djindjic** [comment]
my local jspm version is 0.11.3

**Comment by guybedford** [comment]
Ah right, I believe I fixed this today in https://github.com/jspm/jspm-cli/commit/68b3018e5c5d7cfbed62fd1b6a4992e2ff563279.

**Comment by djindjic** [comment]
Can I test it without cloning repo? I mean, could I install it as beta from npm?

**Comment by djindjic** [comment]
It's ok, I will install it from github releases until new version, thanks!

**Comment by guybedford** [comment]
Let me know if you have any more issues with this, but should be resolved now.

**Comment by djindjic** [comment]
works!
