### ISSUE TITLE
jspm hangs

### ISSUE THREAD

**Issue by calvinmetcalf** [jspm/jspm-cli#477]
was reported as crypto-browserify/publicEncrypt#5 suspect it's a more general problem as for me it stalls somewhere else [log](https://gist.github.com/calvinmetcalf/68bbf97b64b6ff1bddc1) is there a way to set the log level to be more verbose?

**Comment by guybedford** [comment]
Thanks for posting it on! This is an as-yet-undiagnosed io.js bug, either happening in request or child process, https://github.com/jspm/jspm-cli/issues/410.

**Comment by guybedford** [comment]
Closing a a duplicate.
