### ISSUE TITLE
transpiler choice in package.json

### ISSUE THREAD

**Issue by u9520107** [jspm/jspm-cli#479]
Sometimes I find it easier to clean up bundling configurations simply by deleting the config.js file and restart from jspm install and bundle. But currently package.json doesn't hold the information needed to retain the transpiler choice right? It is possible to bake the transpiler choice into package.json itself?

**Comment by guybedford** [comment]
There are other options this applies to as well.

Instead perhaps use `jspm clean` and `jspm unbundle` to clear your config?

**Comment by u9520107** [comment]
It's alright then. I'll reconsider my build process. I was only doing the bundling during development because of network performance issues anyway.
