### ISSUE TITLE
What is the best way to <link/> styles from jspm packages?

### ISSUE THREAD

**Issue by sublimeye** [jspm/jspm-cli#480]
What is the best workflow, for linking styles (css/sass) to html from jspm packages?
For example, you can get bootstrap package which contains:
/js/components
/css (less|sass)

So when /css files goes to /jspm_packages how would you use those styles with other client-side styles?
Could you show an example of directories structure?

**Comment by guybedford** [comment]
Apologies for the delay here - this fell off my radar.

You can use the CSS plugin to load CSS files. The suggestion in jspm is to go with modular CSS - have CSS and JS files together, and not in separate base folders.
