### ISSUE TITLE
Installing angular-strap doesn't create "export" file

### ISSUE THREAD

**Issue by smajl** [jspm/jspm-cli#483]
After `jspm install angular-strap` and this line in my code `import 'angular-strap'` I realised that the `jspm_packages/github/mgcrea/angular-strap@2.1.6.js` file is missing (does not get created in the process).

So now have to bypass it with:
```javascript
import 'github:mgcrea/angular-strap@2.1.6/dist/angular-strap'
import 'github:mgcrea/angular-strap@2.1.6/dist/angular-strap.tpl'
```
Is that problem with jspm, angular-strap package definition or something on my side?

**Comment by guybedford** [comment]
Moved to https://github.com/jspm/registry/issues/160.
