### ISSUE TITLE
'jspm bundle foo - bar' injects foo although '--inject' was'nt used.

### ISSUE THREAD

**Issue by andreasgrimm** [jspm/jspm-cli#484]
Is it on purpose that when creating a bundle with arithmetic the bundle always gets injected into `config.js` even when not using the `--inject` switch?

**Comment by guybedford** [comment]
This shouldn't be the case - perhaps you have bundle config from a previous bundle present? Use `jspm unbundle` to remove the config.

**Comment by andreasgrimm** [comment]
no. I'm always doing an 'jspm unbundle' before a `jspm bundle` (all my gulp bundle tasks depend on the unbundle task)

**Comment by guybedford** [comment]
I'm definitely not able to replicate the issue this side. Are you running the latest jspm?

**Comment by andreasgrimm** [comment]
(oops, I did an edit instead of a new post)

yes, using jspm 0.11.5

**Comment by andreasgrimm** [comment]
ok, not I got it. My fault. It's a typo, I accidentally did a `jspm bundle foo -bar`, missing a blank between the `-` and the `bar`.

Watching the logs should have made it clear that bar wasn't actually subtracted.

**Comment by guybedford** [comment]
Right, yeah that is a possible catch. Glad it's working.
