### ISSUE TITLE
How to prevent function names from being mangled on minify?

### ISSUE THREAD

**Issue by lewisl9029** [jspm/jspm-cli#485]
Right now, with or without the --no-mangle option, function declarations seem to have their names stripped when minified.

I've updated my demo project to demonstrate the issue: https://github.com/lewisl9029/jspm-test

The function declaration in /views/home/home.js line 4:
```js
//function name gets mangled even with --no-mangle flag
let homeController = function HomeController() {

};
```
turns into this when bundled with --no-mangle:
```js
homeController=function(){}
```

I'm not quite sure if this is an issue with UglifyJS, traceur/6to5 (tried on both) or jspm itself.

Any help with this would be appreciated.

**Comment by johnsoftek** [comment]
Your example uses a function expression.

I know it's not equivalent but, as a work around, you can use the function declaration form:
```javascript
function HomeController() {

};
```

**Comment by guybedford** [comment]
If you can work out what option into uglify is needed here, we can certainly add that in with the mangle option.

**Comment by guybedford** [comment]
I had a quick look at the docs, but couldn't tell which option this would be offhand.

**Comment by lewisl9029** [comment]
I did look into this a bit a while ago and it looks like the --lift-vars option (ast_lift_variables in the API) is what causes this behavior. Mangling alone actually only renames the function and doesn't remove the function name.

**Comment by guybedford** [comment]
Thanks for following up. That option is only in UglifyJS 1 I believe though?

**Comment by lewisl9029** [comment]
Hmm... looks like you're right, I didn't realize I was looking at the v1 repo. But apparently they haven't removed the option from the CLI yet since --lift-vars does seem to work.

For v2, I've found that `-c unused=false` or passing `unused: false` into the compressor options has the same effect.

**Comment by guybedford** [comment]
Thanks. Unfortunately that's not really an option we can use as it's removing a lot of functionality. We may just have to work around this rather.

**Comment by jhoguet** [comment]
+1

**Comment by jhoguet** [comment]
I can try and work on this tomorrow if someone can point me in the right direction. 

I tried logging at https://github.com/jspm/jspm-cli/blob/b2b0b997dd0d124a88b07f48b7b0a545d88d77c4/lib/build.js#L580 which didn't work, which makes sense since I can't find the connection from https://github.com/jspm/jspm-cli/blob/621b11490a2acd3ba5878a3413fdb860435d51ef/lib/bundle.js#L170 but build.js is the only thing using uglify, so clearly I am missing something. 

please point me in the right direction :)

**Comment by guybedford** [comment]
@jhoguet this would be welcome - the relevant code is at https://github.com/systemjs/builder/blob/master/lib/output.js#L77.

**Comment by jhoguet** [comment]
looks like the issue I was seeing (--no-mangle wasn't working) is fixed in https://github.com/systemjs/builder/commit/3a70b671c85dad94e3b76140f64ea5ca5d4913eb

**Comment by guybedford** [comment]
I'm not sure there's an easy fix in Uglify for the original issue, so closing as a "can't fix". Any further suggestions please do post back here.
