### ISSUE TITLE
Map does not work in package.json

### ISSUE THREAD

**Issue by johnsoftek** [jspm/jspm-cli#486]
I can refer to a file within a module in config.sys. So I can refer to jade-runtime as:
```javascript
  "map": {
    "jade-compiler": "npm:jade@1.9.1",
    "jade-runtime": "npm:jade@1.9.1/lib/runtime"
  }
```
For plugin-jade, I want to generate this mapping from package.json. I have tried:
```javascript
"jspm": {
    "dependencies": {
      "jade-compiler": "npm:jade@1.9.1"
    },
    "map": {
      "jade-runtime": "npm:jade@1.9.1/lib/runtime"
    }
}
```
but the "map" object is ignored.

I have implemented a work around in code but I would prefer to use the package.json approach.

**Comment by guybedford** [comment]
Rather use - 

```json
{
  "map": {
    "jade-runtime": "./lib/runtime"
  }
}
```

Note that that map will only apply within the repo that is being installed.

If you want to be able to refer to `jade-runtime` from elsewhere, this was what I was trying to describe in https://github.com/johnsoftek/plugin-jade/issues/1#issuecomment-70675336.

**Comment by guybedford** [comment]
Closing as map is working as expected, but let me know if you need more clarification on contextual normalizing for getting an absolute runtime path for inclusion in the template requires.

**Comment by johnsoftek** [comment]
I disagree.

map is not working at all in package.json. plugin-jade is a plugin, so there is no config.sys to work with.

Also, your suggestion does not refer to the runtime within the npm:jade module. It refers to lib within the plugin.

**Comment by guybedford** [comment]
map config is documented at https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm#map. It behaves the same as the `browser` property in Browserify.

Perhaps post an issue for the problem you're having, and I'll run through the suggestion more clearly.

**Comment by johnsoftek** [comment]
I disagree that map works as expected. It works in config.sys. It does not work in package.json - the map entry in package.json is not copied to config.sys. Can you say that it is supposed to do so?

My first post in this issue shows that I can use map in config.sys and it does do what I want. But a plugin does not have a config.sys file. The config.sys file is created by the developer who installs the plugin.

So can I use map in package.json within the plugin so the entry will be added to the developer's config.sys when the plugin is installed.

**Comment by guybedford** [comment]
Yes - installable packages are not able to add global names to the application they are installing into.

**Comment by johnsoftek** [comment]
My first post in this issue shows that I can use map in config.sys and it does do what I want. But a plugin does not have a config.sys file. The config.sys file is created by the developer who installs the plugin.

So can I use map in package.json within the plugin so the entry will be added to the developer's config.sys when the plugin is installed? My attempt to do so failed as jspm install did not copy the map entry from package.json to config.sys.

**Comment by johnsoftek** [comment]
Okay.
