### ISSUE TITLE
config.js system.js mapping update

### ISSUE THREAD

**Issue by djindjic** [jspm/jspm-cli#488]
It sounds known for me, I have looked into closed issues but cant find. Scenario:

- jspm install affect config.js and generate map secfion for packages confogured in package.json
- I have jspm_packages in gitignore
- there is also travis build config calling jspm install
- config.js is not in git ignore
- (for example) I want to change my already instaled package endpoint, so just replace "github/user:" to "npm:" in package.json
- my config.js is still point to github version and jspm install use this as default and download github version in travis build

My first idea was to ask does it make sense to create mapping in saparate file updated with every jspm install, and add it to gitignore, but I think @guybedford told me that this is systemjs issue and it is not planed for now. But, my second idea is about to overwrite mapping on every jspm install. I'm not sure is it usual to costimize default jspm mapping (not in my case), but in this case it could be some separate sections in config.js?

**Comment by guybedford** [comment]
@djindjic can you clarify why you're wanting to change a package's canonical name to something else? You're changing `github/user:x` into `npm:x`? I'm not sure I understand the use case.

**Comment by djindjic** [comment]
I have changed my own package endpoint which is not in registy. For example it was case in https://github.com/jspm/jspm-cli/issues/476 when I fixed github/djindjic:metabolicjs to npm:metaboolicjs in my current project.

I wanted to do this few times before with just removing some canonical packagees from project and needed to manualy remove map sectionbefore run jspm install again. Its not a big issue but just have this as logical problem when try to use it in my dev workflow

**Comment by guybedford** [comment]
It's advisable to know where you are publishing something during development and to match that name exactly - this is why linking etc is all designed around this name. It does have to be a manual process of changing your package location otherwise yes.

**Comment by djindjic** [comment]
Sorry, just discussing.. but if I want to remove some package, why not just remove it from package.json and run jspm install? Maybe I'm wrong but I think this is default behavior for gem install and npm install. Othervice, if user just change package.json and run jspm install there could be a conflict between package.json and config.js because config.js has one more package configured which is removed.

**Comment by guybedford** [comment]
@djindjic it's a good suggestion, created https://github.com/jspm/jspm-cli/issues/489.

**Comment by djindjic** [comment]
it's my pleasure :-)
