### ISSUE TITLE
baseURL and lib cannot both be "." in package.json

### ISSUE THREAD

**Issue by hgl** [jspm/jspm-cli#491]
Setting both to `"."` and run `jspm init`,`lib` will be changed to `""`, and `app/*` will point to `/*.js` in `config.js`. Running `jspm init` again, `app/*` will point to `lib/*.js` in `config.js` and `lib` stays as `""`.

Just to make sure I'm not doing something wrong, can they be set to the same folder?

**Comment by guybedford** [comment]
Make sure you're running jspm@0.12.

**Comment by hgl** [comment]
Great, works like a charm in 0.12. Thanks.
