### ISSUE TITLE
How to bundle 6to5-polyfill and 6to5-runtime?

### ISSUE THREAD

**Issue by hgl** [jspm/jspm-cli#492]
Directly importing them via, say, `import "./jspm_packages/6to5-polyfill";` doesn't seem to work, the bundled js complains `[Error] Module jspm_packages/6to5-polyfill not present.`

**Comment by guybedford** [comment]
I'd suggest just including them with a <script> tag before the bundle. Support for these is being tracked in the builder here - https://github.com/systemjs/builder/issues/46.

**Comment by hgl** [comment]
Thank you. I will do that for the moment, Allowing bundle sfx to bundle them automatically would be awesome.
