### ISSUE TITLE
install option to prioritise prereleases

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#494]
`jspm install --pre`?

**Comment by subesokun** [comment]
Would this mean that `pkg@1.1.0-build.x` matches `pkg@^1.0.0-build.1` in case the `--pre` flag is set? If so, +1 :)

**Comment by Alxandr** [comment]
As I wrote in chat, (for which this issue was created), it would mean that doing `jspm install pkg` would prefer `pkg@1.1.0-build` over `pkg@1.0.0` as it has a higher version number.

**Comment by Alxandr** [comment]
Also, imho, the `--pre` flag should be implicit if you are updating a package that's installed that is a pre-release.

**Comment by Alxandr** [comment]
It should also be recursive. So if you do `jspm install pkg --pre` and `pkg` has a dependency on `pkg2`, it should install `pkg2` with the `--pre` flag.

**Comment by subesokun** [comment]
What I wanted to say is that by default `pkg@1.1.0-build.x` is not part of the `pkg@^1.0.0-build.1` semver range even though it has a higher version number. So not sure how we can influence this behavior via a `--pre` flag as this behavior is implemented fix into the node-semver library.

**Comment by matthewp** [comment]
:+1:

**Comment by crisptrutski** [comment]
Closed by #753 and #754
