### ISSUE TITLE
distinguish npm & jspm uses

### ISSUE THREAD

**Issue by u9520107** [jspm/jspm-cli#495]
Suppose i have a small package that's written in es6 syntax with folder structure like this
```
./module
  -> dist/   //folder of 6to5 transpiled version for node use
  -> source/   es6 source code
  -> package.json
```
To make node uses simple, I listed 6to5-runtime as a dependency, and transpile with "selfContianed" optional transformer, so that the runtime maybe included when needed.

I explicitly maintain jspm dependencies under "jspm" prefix because the module uses fs and path from the node libs. 
Currently I ran into a couple of issues:
*  When I install npm:6to5-runtime, there is a require in the [helper.js] file that differs from the npm install in node_modules.
```
node_modules/6to5-runtime/helper.js:
#3 var _core = require("6to5-runtime/core-js")
jspm_packages/.../6to5-runtime@.../helper.js
#4 var _core = require("./index/core-js"); // "./index" actually doesn't exist
```
*  I actually wish to server out src code in jspm uses. So in under the "jspm" prefix I set main="source/index". This works ok. But there are case where I want to do:
```
require('module/dist/submodule')
```
In both node/browser context using the same code. Is it possible to map "dist/**" to "source/**" under the system module loader context?

Or is it easier of the repo is organized differently like this:
```
./module
  -> /dist
    -> package.json    //for npm publish only
  -> /source
  ->package.json //for jspm use
```
Then install via github instead of npm when used with jspm?

**Comment by u9520107** [comment]
Hmm.. actually I could ship everything with es6 module syntax and let 6to5's regiester check on node modules too. So I guess I can work around these issues.

But still, npm:6to5-runtime seems to yield unusable package.

**Comment by guybedford** [comment]
@u9520107 it seems like you want your package available to Node users on npm? In this case you should build your workflow around 6to5's publishing workflow and use jspm only as a loading environment.

**Comment by u9520107** [comment]
@guybedford I tried to publish my module by transpiling it with self-contained optional transformer and include 6to5-runtime as a dependency. But that seems to fail in SystemJs as the installation of 6to5-runtime ends up with wrong paths.

**Comment by guybedford** [comment]
Ok right, I see what you mean. I'm looking into that issue.

**Comment by guybedford** [comment]
Ok I've posted a fix in https://github.com/jspm/npm/commit/58aa6bb034092beaf1e90099365ae27102b9ec35. Thanks for this.

**Comment by u9520107** [comment]
@guybedford great! thanks.
