### ISSUE TITLE
jspm (0.12.0) install adds directory.lib into package.json

### ISSUE THREAD

**Issue by djindjic** [jspm/jspm-cli#497]
[Here](https://github.com/djindjic/forwardablejs) is my simple js lib which have strange behavior after 0.12.0 update. There is only format: "es6" configuration in jspm section. If I clone this repo and run jspm install, direcories.lib = "lib" section appears in package.json. In this case it breaks my jspm config. I have found workaround, but it could be a bug.

**Comment by guybedford** [comment]
@djindjic yes this was the breaking change in jspm@0.12. You have to manually set `directories.lib` to `.` if you don't want this.

**Comment by guybedford** [comment]
See https://github.com/jspm/jspm-cli/releases/tag/0.12.0.

**Comment by djindjic** [comment]
ah right, haven't checked this

**Comment by guybedford** [comment]
I've been thinking about this and instead I'm changing the `directories.lib` value to `.` and posting a jspm@0.13. This will cause less issues in the upgrade path and is a more sensible default anyway.

**Comment by djindjic** [comment]
I have just tried it, directories.lib does not creates now? This is now "." in jspm core if directories.lib is not provided in package.json? btw it works for me now, without any fix.

Just one more opinion. I found as the most flexible build process without jspm setmode (cant find setmode in docs, is it depricated?). I have "development optimized" repository hooked to travis and if I trigger travis to build it and deploy (ex. npm), all builded files will be deployed, but I don't want to commit and push it back to github. It looks clear for me and I didn't expect that build process could change any NOT-git-ignored file. But in previous situation, modified package.json will be different on npm and source control.

**Comment by guybedford** [comment]
@djindjic yes see https://github.com/jspm/jspm-cli/releases/tag/0.13.1. Basically `directories.lib` is no longer used during development now, but only as a production install indicator.

`jspm setmode production` was deprecated a while back, `jspm setmode remote` is the feature here, but I'm not heavily pushing that yes as it is more of a future feature.

What do you mean the build process could change your not git ignored file? How does your package.json look on npm?

**Comment by djindjic** [comment]
My package.json should be the same on npm and source control, and it is. I just point to that I didn't expect that jspm install could change package.json. Again, I'm looking to gem install and npm install, and I think that gemfile or package.json cannot be modified while installing already configured packages.

>What do you mean the build process could change your not git ignored file? 
I mean that jspm should only have responsibility to create or modify files in jspm_packages (usualy in .gitinore) because sometimes (in case of travis build) I (or we) don't want to push this changes back to source control .

**Comment by guybedford** [comment]
@djindjic thanks, yes you are right again, and thanks for letting me know. I've pushed out 0.13.2 which will not alter package.json directories at all.
