### ISSUE TITLE
can't use es6 jspm dependenies without bundiling

### ISSUE THREAD

**Issue by helios1138** [jspm/jspm-cli#498]
I have a custom jspm package written in ES6 as a git dependency for another jspm ES6 package. And when I try to run the server - it doesn't work. No output at all. No errors or anything, even though I can see that all of the files are being loaded.

It works if I create a bundle however.

Is this behavior intentional or am I doing something wrong?

**Comment by guybedford** [comment]
Do you mean it isn't running in Node, but works in the browser?

**Comment by helios1138** [comment]
I'm running it in browser by serving the public directory, like always. It works if I create a create a jspm bundle, but does not work without it.

**Comment by guybedford** [comment]
Interesting. No this isn't intentional.

If you can isolate the issue so I can replicate it, then can look into debugging it if this is an issue.

**Comment by helios1138** [comment]
I've create two repos:
https://github.com/helios1138/jspm_test_main_package (the main package)
https://github.com/helios1138/jspm_test_subdependency (the main package depends on this subdependency)

serve the /src directory in the main package using a web server

you can see that the main.js is having `console.log('main')` statement in it, which is expected to be shown in console

if you will look at the console output after that, you will see that the output is not there, while all the files (including those from dependency package) are loaded and no error is shown

however if you will run `jspm --bundle app/main --inject`, then console will have the expected output

**Comment by helios1138** [comment]
can you confirm that this is an issue in the code I provided?

**Comment by guybedford** [comment]
Yes I've replicated it, but haven't worked out the issue yet - will look into it next week.

**Comment by guybedford** [comment]
@helios1138 I finally worked this out - you need to use `System.import` not `System.load`!
