### ISSUE TITLE
bundle-sfx (using Traceur) errors with: "Uncaught Module @@global-helpers not present."

### ISSUE THREAD

**Issue by andreasgrimm** [jspm/jspm-cli#499]
index.html has included `traceur-runtime.js` and the bundle (which has CSS bundled within. if that makes a difference .. I didn't test yet unfortunately).

everything is latest version. more details later today if needed.

**Comment by guybedford** [comment]
Thanks so much for posting - yes this was a regression. I've posted a fix in SystemJS builder 0.7.4.

**Comment by andreasgrimm** [comment]
thanks!
I just was about to post: "I included `system.js` in addition to `traceur-runtime.js` but that didn't make any difference. I exluded angular-material (by not importing it anywhere) and thus have no CSS in the bundle at all but that didn't make any difference either." ... but trying again with the new version immediately.

**Comment by andreasgrimm** [comment]
now I'm getting `Uncaught TypeError: undefined is not a function` at:

```javascript
System.register('app.css!github:systemjs/plugin-css@0.1.3', [], false, function() {});
(function(c){var d=document,a='appendChild',i='styleSheet',s=d.createElement('style');s.type='text/css';d.getElementsByTagName('head')[0][a](s);s[i]?s[i].cssText=c:s[a](d.createTextNode(c));})
(" __ all the CSS ___")
(function() {   // <--    Chrome shows squiggles here
  var loader = System;
...
```

**Comment by guybedford** [comment]
Sorry about these issues. Try updating the CSS plugin to 0.1.4, and let me know if you're still getting the issue. If so a replication case would be great.

**Comment by andreasgrimm** [comment]
oops, forgot to check if there's a new CSS plugin version as well.
but still same error with CSS plugin 0.1.4.
I'll let you know as soon as the replication case is available.

**Comment by andreasgrimm** [comment]
in this project: https://github.com/ng-next/ng-next-example after `npm install`, running gulp task `build-standalone-html`, then `npm start` and browsing to `localhost:3000` should reveal the error in the console.
I omitted minification for now.

**Comment by guybedford** [comment]
Thanks so much @andreasgrimm I've fixed this in css@0.1.5.

**Comment by guybedford** [comment]
The app is looking great btw!

**Comment by andreasgrimm** [comment]
thanks a ton, everything seems to work just fine now.
you're simply awesome .. as always :)

thanks. yes, the app is still rough around the edges. I'm planning to make it "public" at some point in the future at ng-next.com.

**Comment by guybedford** [comment]
Thanks, the help is invaluable to catch these things. Do let me know if you have further questions at all and keep me posted on the project.
