### ISSUE TITLE
sub-dependencies not installed

### ISSUE THREAD

**Issue by wilsonpage** [jspm/jspm-cli#501]
I have the following [package.json](https://github.com/wilsonpage/gaia-header/blob/master/package.json) at a `github:` endpoint.

`jspm install wilsonpage/gaia-header` fails to pull in the two sub-dependencies `font-fit` and `gaia-component`. Am I missing something?

**Comment by guybedford** [comment]
@wilsonpage by default it's installing from the 0.3.4 tag. Use `jspm install wilsonpage/gaia-header@master` to install the latest changes there.

**Comment by wilsonpage** [comment]
@guybedford ledge! :smile:
