### ISSUE TITLE
Completely separate dev and prod folders is causing issues

### ISSUE THREAD

**Issue by joezimjs** [jspm/jspm-cli#509]
I'm having an issue with getting my builds to work. In my project folder I have this structure:

```
dev/
  app/ (server application)
  dev/ (development source files)
    public/ (browser application)
      scripts/ (this is where all my js goes)
        vendor/ (jspm packages)
        config.js
        main.js, etc.
      index.html
  prod/ (compile and move all the dev/ files into here)
    public/
      scripts/
        bundle.js
      index.html
```

My `package.json` file has this for the jspm config:

```json
"jspm": {
  "directories": {
    "baseURL": "dev\\public\\scripts",
    "lib": "dev\\public\\scripts",
    "packages": "dev\\public\\scripts\\vendor"
  },
  "dependencies": {
    ...
  }
}
```

My `config.js` file has this starting config:

```js
System.config({
  "baseURL": "/scripts/",
  "transpiler": "6to5",
  "paths": {
    "*": "*.js",
    "github:*": "vendor/github/*.js",
    "npm:*": "vendor/npm/*.js"
  }
});
```
And this is the bundling command I use: `jspm bundle-sfx main prod/public/scripts/build.js`

The issue then ends up being that the entire file system path gets prepended to my module names, e.g. my `main` module's name ends up being something like "file:C:/path/to/project/dev/public/scripts/main". Then when I try to run the code in the browser I get a message telling me that it can't find "main". Is there anything I can do about this?

**Comment by joezimjs** [comment]
After more testing. This only happens when I use 6to5 and doesn't seem to be an issue with the folder structure.

**Comment by guybedford** [comment]
Thanks - yes this was a regression in SystemJS builder. 0.8.2 has been posted. If you do `npm install -fg jspm` that should resolve the issue.
