### ISSUE TITLE
Traceur mobile chrome and safari support fix

### ISSUE THREAD

**Issue by jimthedev** [jspm/jspm-cli#512]
It would be great if we could upgrade to Traceur 0.0.84. There was [a bug](https://github.com/google/traceur-compiler/issues/1647) which broke rendering in Chrome mobile, Safari mobile and Safari desktop. In the mean time you can use the dl-loader --edge flag to fix the issue.

**Comment by guybedford** [comment]
We're waiting on 0.0.84 because it breaks source maps support. See https://github.com/systemjs/builder/issues/62#issuecomment-74079552 for a summary of some of these issues.

**Comment by guybedford** [comment]
Actually we can just bump the browser loader in this special case. Included in https://github.com/jspm/jspm-cli/commit/ab4107d8abf1cb7c4eeb268506a3d830cc886b20, patch to follow.

**Comment by jimthedev** [comment]
Thanks Guy. Closing this since it seems to have fixed the problem.
