### ISSUE TITLE
transient timeouts with `git ls-remote` on Windows

### ISSUE THREAD

**Issue by bennage** [jspm/jspm-cli#513]
When running `jspm install` with a package.json such as the one used in [Aurelia's skeleton](https://github.com/aurelia/skeleton-navigation) I am seeing transient timeouts on Windows. I've run the install dozens of times, and it seems to have a timeout about 70% of the time. Though on occasion, it will work several times in a row. (I am deleting my `jspm_modules` folder in between tests.)

I was able to determine that the problem is occuring in the `jspm-github` module when it invokes `git ls-remote`. I have been able to "fix" this problem by implemeting some retry logic in `lookup` function. (At least, I haven't hit a failure yet on the 2nd retry.

I'm wondering if there is some resource contention that's occuring because of parallel execution?

I've experienced this problem on multiple Windows machines, but everything works fine on OSX.
I've also tested on Ubuntu and I did not have the problem there.

Git versions used:
- Windows: 1.9.5.github.0
- Windows: 1.8.4.msysgit.0
- Ubuntu 14: 1.9.1

**Comment by bennage** [comment]
Here is my hack:
https://github.com/bennage/jspm-github/commit/2e18fbdc777f1e69fa9e0bb3a15bad1d865148bf

**Comment by guybedford** [comment]
@bennage thanks for this. Which version of NodeJS are you using here?

There's an issue tracking retry functionality at https://github.com/jspm/jspm-cli/issues/185, and the way we were planning to implement this was in jspm core calling the lookup function again on error as opposed to in the endpoint itself, so this same functionality can apply to download etc as well.

We can do that certainly, although it would be nice to be able to work out the underlying cause - whether it is a git issue in windows with multiple execution, or a Node process issue.

**Comment by bennage** [comment]
I was using various releases of Node, all 0.10.3x though. I can get a list of specific releases later this evening. I know that the version on Azure was 0.10.32.

**Comment by bennage** [comment]
My other Windows machine is 0.10.35.

**Comment by guybedford** [comment]
I've added the workaround to reduce the probability of this in https://github.com/jspm/jspm-cli/commit/67eef1685984a3ed23bd211b62e004762f6c3367.

I've created https://github.com/jspm/github/issues/36 to track the underlying issue, and we can continue to track that there.

Thanks for reporting.
