### ISSUE TITLE
bundled angular app doesn't work with babel (6to5)

### ISSUE THREAD

**Issue by djindjic** [jspm/jspm-cli#515]
I have pushed [sample project](https://github.com/djindjic/test-samples/tree/f2becba302819e88b1bad4f419ea54022165c525) to show my problem after trying to build angularjs app with transpiler="6to5" instead of "traceur".
[Here](https://github.com/djindjic/test-samples/blob/f2becba302819e88b1bad4f419ea54022165c525/bundle.js#L10003) is my experimental `console.log('app works');` but it seems like it is never executed.

Everything is fine if I use traceur (bundled or not) or babel without bundling.

**Comment by guybedford** [comment]
Have you updated to latest jspm with `npm install -fg jspm`?

**Comment by djindjic** [comment]
Yes, but withput -f, what does mean "f"?

**Comment by djindjic** [comment]
...have tried it now with -fg and have same issue

**Comment by guybedford** [comment]
@djindjic you need to ensure you update SystemJS builder to version 0.8.2 in jspm. That's why I say `npm install -fg jspm` (and if you're running locally `npm install -f jspm`) because that will ensure that the dependency is at its latest version. Perhaps `npm update` is a better bet too?

**Comment by djindjic** [comment]
sorry for delay, it's fine now with only one line difference https://github.com/djindjic/test-samples/commit/f6bc08ef9034424083b1055069679b2d048b8f57

It seems like this issue was found accidentally because I still have similar issue, but in other real app. need to explore it more.

thanks

**Comment by djindjic** [comment]
I found this issue is my original problem.
https://github.com/jspm/jspm-cli/issues/523
