### ISSUE TITLE
OS X/io.js: jspm install sometimes hangs

### ISSUE THREAD

**Issue by wesleycho** [jspm/jspm-cli#517]
When running `jspm install`, it seems sometimes it hangs when downloading packages (i.e. `Downloading npm:ieee754@1.1.4` - no more terminal output occurs, and the process has to be killed) - I have only seen this happen for packages on npm, and it seems that when I kill the process and restart it, it continues on to the next required package.

This appears to be some sort of race condition where it finishes downloading, but doesn't properly move onto the next download/install task.

**Comment by guybedford** [comment]
Yes there is an unknown bug in io.js - this is being tracked at https://github.com/jspm/jspm-cli/issues/410.

**Comment by wesleycho** [comment]
Ah apologies, did not see that - closing as duplicate.
