### ISSUE TITLE
"Uncaught Module foo:bar@0.1.0 not present." with 6to5 bundle-sfx on custom endpoint.

### ISSUE THREAD

**Issue by Dani723** [jspm/jspm-cli#519]
Hi,

I'm getting a error in the browser when using the 6to5 bundler on a custom endpoint.

We have a
- custom npm endpoint: 'foo'.
- module 'foo:bar, published in version 0.1.0.

`jspm install bar=foo:bar`
works as expected, also there is no problem using this module in the dev workflow.

But when creating a bundle the following error is thrown in the browser:
`Uncaught Module foo:bar@0.1.0 not present.`

The bundle.js contains the following line:
`System.register("foo:bar@0.1", ["foo:bar@0.1.0/foo"], function (_export) {`

but it should be
`System.register("foo:bar@0.1.0", ["foo:bar@0.1.0/foo"], function (_export) {`

I tracked down the error to the following file:
`node_modules/jspm/node_modules/systemjs-builder/compilers/es6.js`

Adding the following option to the 6to5 compiler solves the problem for me.
`options.keepModuleIdExtensions = true;`

It seems it's only happening to the modules on our custom endpoint, so I'm not sure if this is related to jspm or systemjs.

**Comment by guybedford** [comment]
Thanks so much for reporting this - I've added that line in and will post a release today or tomorrow.
