### ISSUE TITLE
Package main not found

### ISSUE THREAD

**Issue by bargosc** [jspm/jspm-cli#520]
When I try to `jspm install github:FontFaceKit/open-sans -o '{main: "./open-sans.css"}'` I get
```
warn No main entry point detected for github:FontFaceKit/open-sans@1.2.1.
     Try adding an override, or set the package.json "main": false if this is the intention.
(...)
ok   Install complete.
```
... and `github/FontFaceKit/open-sans@1.2.1.js` doesn't get created so
```javascript
import 'open-sans';
```
makes a 404 request. Is this an expected behavior and `main` field has to be a `*.js` file or I'm missing something?

**Comment by guybedford** [comment]
Try setting the main as a CSS plugin load: `main: "./open-sans.css!", dependencies: {css: '^0.1.5'}"`.

**Comment by bargosc** [comment]
It works. Thanks

**Comment by chovy** [comment]
Where do I put this? `main: "./open-sans.css!", dependencies: {css: '^0.1.5'}".`

**Comment by bgoscinski** [comment]
You don't have to put it anywhere. This package override is already available in [jspm registry](https://github.com/jspm/registry) so all you have to do is:

```sh
jspm install open-sans-fontface
```

and somewhere in your app:

```js
import 'open-sans-fontface';
```
