### ISSUE TITLE
Can I specify root folder to install

### ISSUE THREAD

**Issue by robianmcd** [jspm/jspm-cli#521]
I setup a sample repo here: https://github.com/robianmcd/jspm-package-test to try and learn jspm. It has a couple ES6 modules in the `src` folder. I'd like consumers to be able to import the modules with something like:

```JavaScript
import mod1 from 'jspm-package-test/mod1';
import mod2 from 'jspm-package-test/mod2';
```

However if I install jspm-package-test with `jspm install github:robianmcd/jspm-package-test` then I need to import the modules with `import mod1 from 'jspm-package-test/src/mod1';`

Is there some way to remove the need to specify the `src` folder?

I noticed that if I change the mapping in config.js to something like `"jspm-package-test": "github:robianmcd/jspm-package-test@0.0.7/src"` this works but I'm not sure how to generate a mapping like this from the CLI and I would rather fix the issue from the package itself so consumers don't have to worry about it.

Thanks!

**Comment by subesokun** [comment]
In the Wiki there is a brief summary of what you've to take care when creating packages, see https://github.com/jspm/jspm-cli/wiki/Publishing-Packages#writing-a-library-or-application-for-usage-just-with-jspm

I'd recommend renaming your `src` folder to `lib` and then setting the `directories.lib` property in your `package.json` to this `lib` folder (`lib` is the recommended folder name by jspm). Also you should set a main file e.g. `main.js` (which is located at `lib/main.js`) to export some default module if wished.

An example can be found here, https://github.com/jspm/demo-es6

**Comment by robianmcd** [comment]
@subesokun  Thanks. `directories.lib` is exactly what I was looking for.

Didn't know about that demo-es6 project either. That will definately help me get started.
