### ISSUE TITLE
js files with filename contains more then one dot cause problem in 6to5 bundling

### ISSUE THREAD

**Issue by djindjic** [jspm/jspm-cli#523]
If I have some file named as: myController.module.js it will make an error after bundling with 6to5 transpiler. Error is angular related (print screened bellow), but I'm pretty sure that problem is somewhere in build process because everything is okay with traceur. If file is named like myControllerModule.js, everything work fine with both transpilers. [Here](https://github.com/djindjic/test-samples/commit/372105c838198d68d899882f5636cc6e5faade00) is my commit which renames file to "dotted" and adds broken bundle.js.

![image](https://cloud.githubusercontent.com/assets/1564068/6239916/33a91832-b709-11e4-870f-a35892a57e16.png)

**Comment by guybedford** [comment]
This can happen if you don't declare all of your dependencies on eachother. It is effectively a race condition where if the execution times work out, the module will be defined, but if they don't it isn't. Ensure that everything that defines itself as an Angular module properly loads angular and its dependent modules as dependencies in the module system as well.

**Comment by guybedford** [comment]
Actually this was fixed in https://github.com/systemjs/builder/commit/16ae35a65a3d6fd8798cdedd76c3d7b3aec7ba6d.

**Comment by djindjic** [comment]
I think that everything is properly defined. It's two files example where [main.js](https://github.com/djindjic/test-samples/blob/372105c838198d68d899882f5636cc6e5faade00/main.js) imports [myController.module.js](https://github.com/djindjic/test-samples/blob/372105c838198d68d899882f5636cc6e5faade00/myController.module.js). I will test it with new release, but just want know, I'm not sure, did you say that this is not related to transpiler itself?

**Comment by guybedford** [comment]
This should be fixed now in 0.14.

**Comment by djindjic** [comment]
tested. works!
