### ISSUE TITLE
Non-verbose mode

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#528]
How about:

```
  jspm install --quiet
```

or something like that for log-levels?

**Comment by jackfranklin** [comment]
@guybedford happy to take a stab at this :+1: Would quiet mute all messages?

**Comment by guybedford** [comment]
@jackfranklin yes, please do! I'm not that familiar with log-levels actually, are there any good examples out there for how to approach the use cases?

**Comment by jackfranklin** [comment]
@guybedford did some reading into this and found various StackOverflow posts including [this one](http://stackoverflow.com/questions/7839565/logging-levels-logback-rule-of-thumb-to-assign-log-levels).

I quite like this set of logs:

- Error: critical logical errors on application, like a database connection timeout. Things that call for a bug-fix in near future
- Warn: not-breaking issues, but stuff to pay attention for. Like a requested page not found
- Info: used in functions/methods first line, to show a procedure that has been called or a step gone ok, like a insert query done
- log: logic information, like a result of an if statement
- debug: variable contents relevant to be watched permanently

Where Error, Warn and Info are shown by default. You could then allow a `--log` CLI argument which could be set to `error`, `warn` and so on. When set, jspm would only log anything for that log level and up (so `--log warn` shows warnings and errors). Then, `--log debug` effectively becomes verbose mode, and `--log error` becomes non-verbose.

Does something like that sound vaguely sensible?

**Comment by guybedford** [comment]
Sorry for the delay on this, have just been thinking about it and this proposal sounds ideal.

Just let me know if you have further implementation questions at all.

**Comment by dvc94ch** [comment]
Is a solution this complicated really needed?

I'm thinking of checking for the debug flag and if it's there don't throw a new error and let the old one bubble up.
Or do you think it would be better solved by adding a `debug` function to ui and then add a filter to ui.log?
one could then ui.log('debug', error) before throwing a new one

**Comment by dvc94ch** [comment]
If taking the second route, what would be the default log level? Everything except debug?

**Comment by sergei-maertens** [comment]
another go at it might be using the -v, -vv, -vvv and -vvvv verbosity flags. That's how ssh does it if I'm not mistaken.

Anyway, big +1 from me for being able to surpress anything but errors!

**Comment by watilde** [comment]
Has this issue already resplved..?

**Comment by jackfranklin** [comment]
@watilde, with PR #1082 it was, yes. The next release of jspm will support a `--log` option :tada:

**Comment by watilde** [comment]
@jackfranklin Thanks for your response! Sounds great :tada:

**Comment by guybedford** [comment]
Released in 0.16.3.
