### ISSUE TITLE
jspm install on Mac OS X Mavericks erroneously looks for bower.json

### ISSUE THREAD

**Issue by nickeddy** [jspm/jspm-cli#531]
Hi all,

After trying to install the systemjs text plugin (`jspm install text`), jspm looks for bower.json:
```
$ jspm install text
     Updating registry cache...
     Looking up github:systemjs/plugin-text
     Downloading github:systemjs/plugin-text@0.0.2
 
warn Error on build , retrying (1).
     Error: ENOENT, open '/Users/colinsf/.jspm/packages/github/systemjs/plugin-text@0.0.2/bower.json'
 
warn Error on build , retrying (2).
     Error: ENOENT, open '/Users/colinsf/.jspm/packages/github/systemjs/plugin-text@0.0.2/bower.json'
 
warn Error on build , retrying (3).
     Error: ENOENT, open '/Users/colinsf/.jspm/packages/github/systemjs/plugin-text@0.0.2/bower.json'
 
err  Error building package github:systemjs/plugin-text
     Reached maximum number of retries.
 
warn Installation changes not saved.
```

When trying to use `jspm install text -o package.json` or `jspm install text -p "{ main: 'text' }"` the same error occurs. plugin-text, plugin-css both fail installing, and neither of these have a bower.json or reference to bower.json ANYWHERE in the package.

I've tried forking from systemjs/plugin-text to change it to jspm package.json spec, but it still looks for bower.json which is telling me it's an issue with jspm-cli.

**Comment by capaj** [comment]
@nickeddy have the same issue with darsain/sly: 
```
 jspm install github:darsain/sly
     Looking up github:darsain/sly
     Updating registry cache...
     Downloading github:darsain/sly@1.3.0

warn Error on build , retrying (1).
     Error: ENOENT, open '/Users/telly/.jspm/packages/github/darsain/sly@1.3.0/bower.json'

warn Error on build , retrying (2).
     Error: ENOENT, open '/Users/telly/.jspm/packages/github/darsain/sly@1.3.0/bower.json'

warn Error on build , retrying (3).
     Error: ENOENT, open '/Users/telly/.jspm/packages/github/darsain/sly@1.3.0/bower.json'

err  Error building package github:darsain/sly
     Reached maximum number of retries.

warn Installation changes not saved.
```

I have solved it by adding the bower.json and creating a new release here: https://github.com/capaj/sly
But I think JSPM should not require bower.json to exist at all. Especially if there is package.json

**Comment by guybedford** [comment]
Thanks for letting me know - added bower main detection a little too hastily. Have pushed the fix.
