### ISSUE TITLE
Package self-referencing

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#532]
```json
{
  "map": {
     "name": "."
  }
}
```

Currently supports loading base-level paths, but apparently is not resolving subfolders correctly. We should make sure this works.

**Comment by guybedford** [comment]
We should also make sure this works:

```json
"map": {
  "./test": "another"
}
```

for internal aliases.

**Comment by speigg** [comment]
So what is the difference in the syntax and semantics between an internal map and a non-internal map?

**Comment by guybedford** [comment]
Moved to https://github.com/systemjs/systemjs/issues/410, for support in the new SystemJS config.
