### ISSUE TITLE
Cache-Control es6-module-loader.js and system.js

### ISSUE THREAD

**Issue by djindjic** [jspm/jspm-cli#534]
I'm playing with setting up max-age for all my assets and found that it could be problem with es6-module-loader.js and system.js when we update those files. Does it make sense to have an version suffix in their file names? Example: `es6-module-loader.0.14.0.js` and `system.0.14.1.js`?

**Comment by guybedford** [comment]
There is a plan to allow this in the next version of SystemJS. Working on it! In the mean time this has been discussed quite a bit at https://github.com/systemjs/systemjs/issues/172.

**Comment by djindjic** [comment]
hey thanks, I am subscribed on this issue now.
