### ISSUE TITLE
Dependencies from global formatted libraries

### ISSUE THREAD

**Issue by chrisronline** [jspm/jspm-cli#536]
Hi there,

I'm having a hard time getting something fairly basic to work and hoping for a nudge in the direction. The issue is similar to [another issue](https://github.com/jspm/registry/issues/40) but the information listed on the ticket don't seem to help me.

I pushed a [test repo](https://github.com/chrisronline/jspm-stuck) up as a discussion point and will outline my issues referencing the lines of code in there. I want to load the main JS file from [materializecss](https://github.com/Dogfalo/materialize) and with my current code, I get an error: ```Uncaught ReferenceError: jQuery is not defined```

1. After going through the basic jspm setup, I tried installing with this command:
```jspm install github:dogfalo/materialize -o "{ main: 'js/bin/materialize.js', shim: { 'js/bin/materialize.js': ['jquery'] } }"``` However, running this command (or just ```jspm install github:dogfalo/materialize```) doesn't seem to describe any hard dependency on ```jquery``` in either ```package.json``` or ```config.js```
2. I tried manually [defining a shim](https://github.com/chrisronline/jspm-stuck/blob/master/config.js#L7) to describe the hard dependency
3. If I try to define information within ```package.json```, any ```jspm install``` command removes the changes for whatever reason (tried what is described [here](https://github.com/jspm/jspm-cli/issues/175))

I'd absolutely love any pointers or tips on how to solve this seemingly simple problem.

Thanks

**Comment by guybedford** [comment]
Moved to https://github.com/jspm/registry/issues/224.
