### ISSUE TITLE
Full path written to config.js on every install

### ISSUE THREAD

**Issue by Hendrixer** [jspm/jspm-cli#541]
On every install, the full path to my projects `jspm_packages` directory is written and I have to go in and replace it with the relative one, for example

``` javascript
System.config({
  "baseURL": "/",
  "transpiler": "babel",
  "paths": {
    "*": "*.js",
    "github:*": "Users/myUserName/Dev/myProject/jspm_packages/github/*.js",
    "npm:*": "Users/myUserName/Dev/myProject/jspm_packages/npm/*.js"
  }
});
```

I'm sure there is something I'm missing or maybe how I set up the `cli`. I'm using a local version of jspm and not a global one.

**Comment by guybedford** [comment]
Can you share your package.json settings? You want to ensure you're setting the `baseURL` correctly there.

**Comment by Hendrixer** [comment]
Yup, here is its
```javascript
{
  "jspm": {
    "directories": {
      "baseURL": "/",
      "lib": "/dist/lib",
      "packages": "jspm_packages"
    },
    "configFile": "config.js",
    "dependencies": {
      "angular": "github:angular/bower-angular@^1.3.13",
      "angular-material": "github:angular/bower-material@^0.8.0",
      "css": "github:systemjs/plugin-css@^0.1.6",
      "lodash": "npm:lodash@^3.3.0",
      "lumx": "github:lumapps/lumx@^0.3.12",
      "ngComponent": "github:maseh87/ngComponent@master",
      "text": "github:systemjs/plugin-text@^0.0.2",
      "ui-router": "npm:angular-ui-router@^0.2.13"
    }
  },
```

**Comment by guybedford** [comment]
Right, yes baseURL and lib are both paths relative to the package.json on the server only. Effectively `baseURL` means `path to the public directory` here. Perhaps that is confusing though.

**Comment by Hendrixer** [comment]
Yea, that tripped me up a bit, makes sense now though.

**Comment by Hendrixer** [comment]
Placing the full path in `baseURL` fixed it for me. It's not relative to the `package.json`. I don't think this is the default behavior.

**Comment by guybedford** [comment]
Sure, I've added a warning for this in https://github.com/jspm/jspm-cli/commit/066c08de2240047a02106a763011490a6c2635eb.
