### ISSUE TITLE
Famous override pulled different on travis

### ISSUE THREAD

**Issue by djindjic** [jspm/jspm-cli#542]
I have strange behavior with new added famous override pointing to famous-global.js. In my local everything works fine, but when I push it to travis to build and deploy with a very simple [travis script](https://github.com/djindjic/test-samples/blob/97a9bc2ef78ef1f501f06d6d13c33f2560931781/.travis.yml), [famous@0.3.5.js configuration](http://test-samples.divshot.io/jspm_packages/github/Famous/famous@0.3.5.js) is pulled different then currently valid [override](https://github.com/jspm/registry/blob/master/package-overrides/github/Famous/famous%400.3.5.json#L6) define. It needs to be as it is in my local development project:

```js
module.exports = require("github:Famous/famous@0.3.5/famous-global");
```

insted of ([famous@0.3.5.js configuration](http://test-samples.divshot.io/jspm_packages/github/Famous/famous@0.3.5.js) again):

```js
module.exports = require("github:Famous/famous@0.3.5/famous");
```

I have made this repo from scratch without any old jspm_package reference, and also have checked jspm version to be latest 0.14.0. Same jspm version is in my travis build [log](https://travis-ci.org/djindjic/test-samples/builds/51975082#L98).

P.S.
Looks like some caching problem, but I have tried it on shippable CI and have same problem.

**Comment by guybedford** [comment]
I'm not sure how this could be a jspm issue - as you say it sounds like your CI system is somehow caching the previous version of the override when cloning that repo from GitHub?

**Comment by djindjic** [comment]
It looks like caching problem at travis, but I have tried it on shippable and it is strange to have same  problem on totally different CI servers.

I was waiting two days for this issue because we have modified famous override yesterday, and travis build works now because it pulls latest override, and there is no problem with jspm-github (I can see 0.10.8 in build log and it is ok). In my local, after running npm install -fg jspm, I also have jspm-github@0.10.8 but still have an error:
>warn No main entry point detected for github:Famous/famous@0.3.5.
     Try adding an override, or set the package.json "main": false if this is the intention.

I'm not sure is it all related to the same issue, but I'm pretty sure I have all jspm and jspm's references updated.

**Comment by guybedford** [comment]
Yes that's a separate issue - make sure you're running jspm-npm 0.20.2 with the fix. A fresh jspm install should use that version by default as it is in the semver range, but an existing install may need to be updated.

**Comment by djindjic** [comment]
Thanks for quick replay.
It may be some (my local or not) relation problem with nvm, node 0.12.0 or ubuntu 14.04 to jspm. Here is my console log where I have uninstalled jspm, jspm-github and jspm-npm (I haven't had jspm-npm) and install jspm again:

```bash
$ npm uninstall -g jspm
unbuild jspm@0.14.0
$ npm uninstall -g jspm-github
unbuild jspm-github@0.10.8
$ npm uninstall -g jspm-npm
npm WARN uninstall not installed in /home/aleksandar/.nvm/versions/node/v0.12.0/lib/node_modules: "jspm-npm"
$ jspm
-bash: /home/aleksandar/.nvm/versions/node/v0.12.0/bin/jspm: No such file or directory
$ npm install -fg jspm
npm WARN using --force I sure hope you know what you are doing.
/home/aleksandar/.nvm/versions/node/v0.12.0/bin/jspm -> /home/aleksandar/.nvm/versions/node/v0.12.0/lib/node_modules/jspm/jspm.js
jspm@0.14.0 /home/aleksandar/.nvm/versions/node/v0.12.0/lib/node_modules/jspm
├── jspm-registry@0.3.3
├── rimraf@2.2.8
├── graceful-fs@3.0.5
├── semver@4.3.1
├── mkdirp@0.5.0 (minimist@0.0.8)
├── glob@4.3.5 (inherits@2.0.1, once@1.3.1, inflight@1.0.4)
├── minimatch@2.0.1 (brace-expansion@1.1.0)
├── liftoff@2.0.2 (findup-sync@0.2.1, extend@2.0.0, flagged-respawn@0.3.1, minimist@1.1.0, resolve@1.1.5)
├── rsvp@3.0.17
├── jspm-npm@0.20.2 (resolve@1.1.5, tar@1.0.3, rmdir@1.0.4)
├── uglify-js@2.4.16 (uglify-to-browserify@1.0.2, async@0.2.10, optimist@0.3.7, source-map@0.1.34)
├── jspm-github@0.10.8 (which@1.0.9, tar@1.0.3, decompress-zip@0.1.0)
├── request@2.53.0 (caseless@0.9.0, json-stringify-safe@5.0.0, forever-agent@0.5.2, aws-sign2@0.5.0, stringstream@0.0.4, oauth-sign@0.6.0, tunnel-agent@0.4.0, isstream@0.1.1, node-uuid@1.4.2, qs@2.3.3, form-data@0.2.0, combined-stream@0.0.7, mime-types@2.0.9, bl@0.9.4, http-signature@0.10.1, tough-cookie@0.12.1, hawk@2.3.1)
├── ember-cli-ncp@1.0.2 (rimraf@1.0.9, read-dir-files@0.0.2, mocha@1.21.5)
├── traceur@0.0.82 (commander@2.6.0, semver@2.3.2, source-map-support@0.2.9)
├── systemjs-builder@0.9.1 (source-map@0.2.0, babel-core@4.5.5)
└── systemjs@0.14.1 (es6-module-loader@0.14.0)
$ jspm install famous
     Updating registry cache...
     Looking up github:Famous/famous

warn No main entry point detected for github:Famous/famous@0.3.5.
     Try adding an override, or set the package.json "main": false if this is the intention.

```

**Comment by guybedford** [comment]
Use `jspm install famous -f` to clear the cache.

**Comment by djindjic** [comment]
That's it! thanks!  :+1:
