### ISSUE TITLE
semver problem

### ISSUE THREAD

**Issue by MajorBreakfast** [jspm/jspm-cli#544]
![service-app_ _bash_ _80x24_and_package_json_ _service-app](https://cloud.githubusercontent.com/assets/340142/6361404/3731c142-bc82-11e4-89da-3a5f39951b71.png)

I left out the hat, so it should take the exact version I specified.
jspm 0.14.0

**Comment by guybedford** [comment]
I believe tested this out when it was posted and was able to replicate it.

But now it seems to be working fine?

**Comment by guybedford** [comment]
Perhaps the `0.3.0` was a branch and not a tag?

**Comment by guybedford** [comment]
Btw thanks, these kinds of bugs are really great to catch.

**Comment by MajorBreakfast** [comment]
I just tested it again and now it works as expected. I'm still on jspm@0.14.0 so that's strange. Nevertheless, I'm happy now (I switched to famous@0.3.5 after https://github.com/jspm/registry/pull/228/files anyway), so this is resolved.
