### ISSUE TITLE
Feature Request: Support for hot replacement

### ISSUE THREAD

**Issue by danielfalk** [jspm/jspm-cli#548]
Doing hot module replacement, especially in libraries like react, means that developers can see their changes almost immediately without a browser refresh and all the data-loading that may entail.

It would be awesome to be able to do this in jspm as well, but the author of react hot loader doesn't think this is possible:
https://news.ycombinator.com/item?id=8984539

**Comment by guybedford** [comment]
Hot module replacement is possible in SystemJS but is not a high priority right now.

The way to do this is basically through the `System.delete` method along with some graph analysis which allows you to delete modules from the registry, and then they can be reloaded.

It will certainly be an option in future.

**Comment by guybedford** [comment]
Closing as this is a future feature but not currently in planning.

**Comment by swirlycheetah** [comment]
@guybedford can I pick your brains about what'd be required to get this working? I'm interested in implementing it to speed up my workflow when developing with jspm & SystemJS and if I can develop a plugin for others to use that'd be awesome.

I've got a really simple implementation up & running but it only works with the initial module imported and I'm unsure how to dig into the modules that module uses to delete and re-import them. Would be great if you could give a bit more insight to what'd be required.

**Comment by guybedford** [comment]
@swirlycheetah @geelen has been working on this problem recently with http://npmjs.com/package/jspm-server. Perhaps check it out and link up with him on this work.
