### ISSUE TITLE
Problem installing package with private npm registry.

### ISSUE THREAD

**Issue by jessegavin** [jspm/jspm-cli#549]
I read through a [previous issue related to private npm](https://github.com/jspm/jspm-cli/issues/135), but I am having a different one.

We have a private npm registry which mirrors the public registry (and allows us to serve some private, proprietary npm packages).

I used the endpoint config tool to configure jspm from .npmrc appears to work successfully

    GAVINJ:jspm-test gavinj$ jspm endpoint config npm
    npmrc found, would you like to use these settings? [yes]:
    npm registry [http://registry.npm.ourcompanyname.net/]:
    Would you like to test these credentials? [yes]:
    ok   npm authentication is working successfully.
    ok   Endpoint npm configured successfully.

Installing our package 'michelangelo' (which is not in the public npm registry) works just fine

    GAVINJ:jspm-test gavinj$ npm install michelangelo
    highstock-release@2.0.4 node_modules/highstock-release
    jquery@2.1.3 node_modules/jquery
    d3@3.5.5 node_modules/d3
    lodash@3.3.1 node_modules/lodash
    michelangelo@2.0.1641 node_modules/michelangelo

Attempting to install the same npm package via jspm does not work.

    GAVINJ:jspm-test gavinj$ jspm install michelangelo=npm:michelangelo
         Looking up npm:michelangelo

    err  Repo michelangelo not found!

    warn Installation changes not saved.

Attempting to install lodash via jspm works perfectly

    GAVINJ:jspm-test gavinj$ jspm install lodash=npm:lodash
         Looking up npm:lodash
         Updating registry cache...
         Looking up github:jspm/nodelibs-process
         Looking up npm:process
    ok   Up to date - lodash as npm:lodash@^3.3.1 (3.3.1)
    ok   Install tree has no forks.
    
    ok   Install complete.

Here's what my jspm config file looks like

    {
      "registry": "jspm",
      "endpoints": {
        "github": {
          "timeouts": {
            "lookups": 60
          },
          "handler": "jspm-github",
          "remote": "https://github.jspm.io"
        },
        "npm": {
          "timeouts": {
            "lookups": 60
          },
          "registry": "http://registry.npm.ourcompanyname.net/",
          "remote": "https://npm.jspm.io",
          "auth": "PRIVATE_HERE_BUT_SAME_AS_NPMRC_FILE",
          "handler": "jspm-npm"
        },
        "jspm": {
          "timeouts": {
            "lookups": 60
          },
          "handler": "jspm-registry",
          "remote": "https://registry.jspm.io"
        }
      }
    }

Any idea why I am unable to install the npm pacakge via jspm?  Or, any advice on how I could track down the problem?

Thanks. I am super excited about using JSPM and introducing it to other developers where I work. Just need to get over this hurdle.

**Comment by chmontgomery** [comment]
:+1:

**Comment by guybedford** [comment]
Thanks so much for posting, I haven't been able to personally test this unfortunately as I don't have a private npm registry to test against, so have been relying on users' PRs.

If you're able to look into debug this somewhat that would be amazing. Let me know if that is a possibility. The code running here is https://github.com/jspm/npm/blob/master/npm.js#L244. Perhaps log the URL that is being request and compare to doing a curl?

**Comment by guybedford** [comment]
@jessegavin did you manage to make any further progress on this at all? I'd be very interested to hear.

**Comment by jessegavin** [comment]
Thanks for the reply, I will look into this further today and let you know what I find.

**Comment by jessegavin** [comment]
@guybedford Debugging the line you specified totally helped. I found the issue! 

The private registry url cannot end with a `/`. 

Thanks so much for pointing me in the right direction!

**Comment by guybedford** [comment]
Excellent, glad you worked it out!
