### ISSUE TITLE
b_ package is filtered in config.js

### ISSUE THREAD

**Issue by floatdrop** [jspm/jspm-cli#550]
Hi. I'm trying to install [b_](https://github.com/azproduction/b_) module from npm and use alias `b_` for it:

```
> jspm install b_=npm:b_

     Looking up npm:b_
     Updating registry cache...
ok   Up to date - b_ as npm:b_@^1.3.0 (1.3.0)
```

But in `config.js` map section `b_` key is filtered by this code - https://github.com/jspm/jspm-cli/blob/master/lib/config/loader.js#L250

How this logic can be fixed to allow install this package?

**Comment by guybedford** [comment]
Yes this is a bug - I guess we need escaping in the configuration mechanism!

**Comment by guybedford** [comment]
I guess the easy fix is just to use a slightly more obscure convention. Ending in `__$`?

**Comment by floatdrop** [comment]
Sended a PR for this. Until then workaround is to alias those packages with names, that does not contains `_` on end:

`jspm install b=npm:b_`
