### ISSUE TITLE
Can I use ES6 syntax in commonjs modules?

### ISSUE THREAD

**Issue by johnsoftek** [jspm/jspm-cli#552]
I converted the client side of an app from browserify to jspm. It works really well. I also reworked it to use Reactjs so I use the jsx plugin and ```require('./mymodule.jsx!')``` and ```require('npmmodule')``` to load third-party npm modules

I would like to start using ES6 syntax such as arrow functions in my app files. I tried a few options using babel but get "require not defined " error. Do I need to use a plugin to transpile the ES6 features? Or invoke a different module loader?

**Comment by matthewp** [comment]
Use import instead of require.

```js
import mymodule from './mymodule.jsx!';
```

**Comment by johnsoftek** [comment]
@matthewp Thanks for your help. I tried your suggestion. In file tst.jsx,
```javascript
console.log('tst.js')

module.exports = function () {
  var x = [1,2].map(a => a + 1)
  console.log('tst func', x)
}
```

In calling module,
```javascript
import tst from './tst.jsx!'

tst()
```
I get: ```Uncaught SyntaxError: Unexpected token =>```

**Comment by matthewp** [comment]
Instead of module.exports use:

```js
export default function() {

};
```

**Comment by johnsoftek** [comment]
@matthewp Thanks! That works.

My calling module had other require calls. I had to replace those also with import statements. And I had to replace ```module.exports``` with ```export default```.

So, to sum up, to use ES6 features, a module must also use ES6 module syntax. Also any module calling that module also needs to use ES6 module syntax.

The arrow function worked with just system.js and config.js in index.html. Would you know when I would need to use Babel or Traceur?

**Comment by johnsoftek** [comment]
@matthewp Scratch that last question. Babel is used automatically when ES6 syntax is detected by systemjs.

**Comment by HackPoint** [comment]
@johnsoftek > Babel is used automatically when ES6 syntax is detected by systemjs. What does that mean? Can you show an example of how to use it?

**Comment by johnsoftek** [comment]
If systemjs sees an import statement in a file, it uses Babel to transpile es6 syntax.
