### ISSUE TITLE
Importing name of linked package

### ISSUE THREAD

**Issue by hgl** [jspm/jspm-cli#553]
If I link a package via `jspm install --link github:my/repo@dev`, I have to use `import "my/repo"` to import it. Is there anyway to use `import "repo"` directly?

Also is there a way to remove a linked package? `jspm uninstall my/repo` doesn't seem to work.

**Comment by guybedford** [comment]
Yes you can alias the package - `jspm install --link repo=github:my/repo@dev`.

To unlink use `jspm install --unlink github:my/repo@dev`. Then you can uninstall.

It should be possible to uninstall a linked package directly - I've made an issue at https://github.com/jspm/jspm-cli/issues/557 for this.

**Comment by hgl** [comment]
Thanks for the heads up. Didn't know I could do that.

I was going to add that to the wiki, but then I wonder why not make it more symmetrical with `jspm install`? I mean `jspm install github:my/repo` exposes it as `repo`, why not make `jspm install --link github:my/repo@dev` expose the same. 

Also I believe you have good reasons, but just curious, why the version has to be specified? If some version really must exist, couldn't it defaults to `@dev` for example ?

**Comment by guybedford** [comment]
`jspm install github:my/repo` does expose as `my/repo`.

We could do default version population for link certainly.

**Comment by hgl** [comment]
You are absolutely right. I installed a github repo via jsom install repo directly, and I got the wrong impression. 

Created #560 for the version.
