### ISSUE TITLE
Aliased modules in dependencies

### ISSUE THREAD

**Issue by floatdrop** [jspm/jspm-cli#556]
I have aliased module under `jspm.dependencies`:

```js
{
"name": "A",
"jspm": {
    "dependencies": {
      "b": "npm:b_@^1.3.0",
    }
  }
}
```

I have second module `B`, that requires `A`:

```js
{
"name": "B",
"jspm": {
    "dependencies": {
      "A": "npm:A@0.0.0",
    }
  }
}
```

When I'm trying to install this module with `jspm install npm:A`:

```
     Looking up npm:A
     Updating registry cache...
     Downloading npm:A@0.0.1

err  Endpoint not found.
warn Unable to load endpoint b@npm
err  Error: EINVAL, rename '/Users/floatdrop/.jspm/packages/npm/A@0.0.1/.'
warn Installation changes not saved.
```

Second error is caused by first - `b@npm` is not installed. But first error caused by aliased `b_` module. This what I get from logging options in https://github.com/jspm/jspm-cli/blob/master/lib/endpoint.js#L76:

```
{ exactName: 'b@npm:b_@^1.3.0',
  endpoint: 'b@npm',
  package: 'b_',
  name: 'b@npm:b_',
  version: '^1.3.0',
  exactPackage: 'b_@^1.3.0' }
```

I guess [endpoint](https://github.com/jspm/jspm-cli/blob/master/lib/endpoint.js#L55) is underparsed, so `npm` from config is not picked up.

**Comment by floatdrop** [comment]
It caused by bug in [jspm/npm](https://github.com/jspm/npm). See referenced issue above.

**Comment by floatdrop** [comment]
Turns out, the roots of this bug is in [this repository](https://github.com/jspm/jspm-cli/blob/master/lib/config.js#L45). `derivePackageConfig` function is not aware of aliased modules:

```js
exports.derivePackageConfig = function(pjson, override) {
  // ...
  // then apply the override
  extend(dpjson, dpjson.jspm);
  // ...
  return dpjson;
}
```

This will create invalid dependency in `package.json`.

**Comment by floatdrop** [comment]
It think solution is move aliases to own field under `jspm` in `package.json`.

**Comment by guybedford** [comment]
@floatdrop when publishing to npm, you need to write dependencies in the npm format.

That is - 

```json
{
  "name": "A",
  "dependencies": {
    "b_": "^1.3.0"
  }
}
```

The idea being to stick to npm-style conventions.

If you want to break the conventions (which it looks like you do actually) then use:

```json
{
  "name": "A",
  "jspm": {
    "registry": "jspm",
    "dependencies": {
      "b": "npm:b_@^1.3.0"
    }
  }
}
```

We should do a better job of showing a useful warning here though. The `jspm-npm` conversion should detect jspm-style endpoint names and give a useful message for what to do. I've created https://github.com/jspm/npm/issues/47.

**Comment by floatdrop** [comment]
@guybedford I have almost same `package.json` (except `registry` field - is it necessary?)

Removing alias (after installing jspm from master) fixed error, but still this seems strange. May be aliases is bad practice.

**Comment by guybedford** [comment]
@floatdrop yes, the `"registry": "jspm"` field is absolutely necessary for npm publishing if using an alternate dependency structure to the normal npm dependency format.

**Comment by floatdrop** [comment]
@guybedford for now jspm-cli removing `"registry": "jspm"` from `jspm` section. Is this expected to be so?

**Comment by guybedford** [comment]
@floatdrop it shouldn't be - can you share the install this is happening on?

**Comment by floatdrop** [comment]
@guybedford yep - https://github.com/y-components/y-button/tree/4968c83a6aebdd3799131a64e20c3c79f23498c3 (but you must use jspm from master, because of `b_`).

**Comment by guybedford** [comment]
Ok that's a bug - created https://github.com/jspm/jspm-cli/issues/559.

**Comment by guybedford** [comment]
(not critical though)
