### ISSUE TITLE
Give linked package a default version if one isn't specified.

### ISSUE THREAD

**Issue by hgl** [jspm/jspm-cli#560]
Should be able to do `jspm install --link github:my/repo` without the version.

**Comment by guybedford** [comment]
Just tested this and it is working fine for me.

**Comment by hgl** [comment]
Well, actually I mean using `jspm link github:my/repo` without the version. Is this possible?

**Comment by guybedford** [comment]
Sure, I've added https://github.com/jspm/jspm-cli/commit/5135ebac42eec59e8ccf5e2a1a1d7386b65fba7e.

This will now take the `name`, `version` and `registry` from the package.json if not set.

I've also enabled linking into the `jspm` registry itself, so that we enable workflows like:

```
jspm link custom@dev
jspm install --link custom
```

**Comment by hgl** [comment]
Wow, linking to jspm registry is pretty cool. Thank you for implementing it.

But I'm so not sure about defaulting to package version.

I have a question regarding the version name: sometimes when I install a github repo, I see `@master` in the folder name, does jspm use `master` as a version number in this case? If so, how does it know when the downloaded version is behind the upstream? This `master` name seems to give me a concept of "latest", could the version name defaults to something like that? But maybe my mental model wrong and it's an invalid request.

From a user point of view, I actually don't want to specify a version number, like never. Because what I really want is this:

```
$ cd /source-dir
$ jspm link repo
$ cd /target-dir
$ jspm install --link repo
$ cd /source-dir
$ touch new-file
```
And expect `new-file` to exist in `/source-dir/jspm_packages/repo/new-file`.

When I do `jspm install --unlink repo`, it will just download the latest version from jspm registry.

Really don't want to deal with a version number when linking a folder.

**Comment by hgl** [comment]
Actually, IMHO, the perfect workflow is the one npm uses:

```
$ cd /source-dir
$ jspm link
$ cd /target-dir
$ jspm link package-name
```

But I guess there is some technical issues prevents jspm from adapting this workflow?

**Comment by guybedford** [comment]
Everything has to have a version number in jspm as dependencies are always specified to version ranges. `master` or `dev` are like a GitHub branch reference, and can be used fine. This isn't going to change.

**Comment by hgl** [comment]
(didn't see name is also taken from package.json by default, which is very cool.)

I'm not saying jspm should remove version numbers. I'm just hoping it could hide it from users when they are linking folders.

For example, jspm could use a special version name denoting "this is a linked version", maybe something like `%link` (so they are different from regular `@master` version).

```
$ cd /source-dir
$ jspm link # link as repo%link
$ cd /target-dir
$ jspm install --link repo # link from repo%link
```

It's hard to image people link the source folder to two different versions:

```
$ cd /source-dir
$ jspm link repo@dev1
$ jspm link repo@dev2 # why would people do this?
```

If linking to multiple versions is unlikely, why not use a special name?

**Comment by hgl** [comment]
Just realized this basically has no realize difference defaulting to package version.

I think it's pretty great right now. Sorry for being a whiner. :)

I will close this issue.

**Comment by guybedford** [comment]
Think of the linked version just like a published version but only local. Then linking workflows will make more sense. You can link into the next published version like `project@1.2.4` for the next version and have version ranges work for parent resolution ranges, fully testing out the change.

**Comment by hgl** [comment]
> Think of the linked version just like a published version but only local.

That makes much sense now.

> and have version ranges work for parent resolution ranges, fully testing out the change.

Sounds like it's better than npm. :)

I will try it out asap. Thanks again for your hard work.

**Comment by hgl** [comment]
The current implementation seems to require a registry to be set otherwise it will fail with `err  Package registry endpoint not specified.`

Could jspm infer this from the package name specified? For example, `github:my/repo` should use the github registry, `repo` should use the jspm registry etc.

**Comment by guybedford** [comment]
@hgl thanks for catching that - yes that was an implementation bug.

**Comment by hgl** [comment]
Thank you for fixing it.

I encountered another one.

```js
$ cd /foo
$ jspm link npm:foo
$ cd /bar
$ jspm install --link npm:foo

err  No version match found for npm:foo
```

The same happens for github endpoint.

**Comment by guybedford** [comment]
What's the version in the package.json in this case?

**Comment by hgl** [comment]
Oh, NM. It's my own mistake.

**Comment by hgl** [comment]
I'm using the master branch of jspm (but not master branch of systemjs or esml). And I get the following error:

```js
$ cd /foo
$ jspm link github:my/foo
$ cd /bar
$ jspm install --link github:my/foo

err  No linked versions found for github:my/foo
```

I have tried remove `~/.jspm` and redo these, same result. Using jspm registry is fine, but not github or npm.

Hope it's not because the jspm dependencies are not up-to-date.

**Comment by hgl** [comment]
Published version of jspm doesn't have this issue.

**Comment by guybedford** [comment]
What is the version in the package.json here?

**Comment by hgl** [comment]
Doesn't seem to matter, tried "0.0.0" in package.json and "@dev" in the CLI, both don't work.

**Comment by guybedford** [comment]
Have you got a "name" or "registry" set in the package.json?

**Comment by guybedford** [comment]
Thanks for your help with this - I've added a fix in https://github.com/jspm/jspm-cli/commit/e1c9e0b9959066a9c56247560ced66b6ac9f4a58.

**Comment by hgl** [comment]
Thanks for the help. Removing "registry" does fix the problem. Should the CLI override package.json?

Also while running `link github:my/repo`, it says `Package linked as github:github:my/repo@0.1.0`. But I guess your fix just fixed that?

**Comment by guybedford** [comment]
Yeah exactly it overrides, and yes it was that very fix.

**Comment by hgl** [comment]
Now I can't seem to link without the name: `jspm link` says `err  Package registry endpoint not specified.`

Both `name` and `version` exist in package.json.

`jspm link jspm:name` works.

**Comment by guybedford** [comment]
You will need to set the `registry` property in the package.json if that is what you mean.

**Comment by hgl** [comment]
It's no longer able to infer the registry from the package name? Since the `name` field in package.json is a regular name, I would expect it to use the jspm registry automatically.

**Comment by guybedford** [comment]
The canonical package name consists of three components - registry, name and version. I don't think we should infer the default registry name for linking as `jspm`, as it should really match the publishing workflow ('github').

**Comment by hgl** [comment]
OK. That's reasonable. So if I choose github as the registry, I should use something like "my/repo" as the name?

**Comment by guybedford** [comment]
Exactly, you will also notice that if you set `registry: 'github'` in the package.json other github dependencies no longer need to be written as `github:...`.

**Comment by hgl** [comment]
Great. Thanks for the heads up.
