### ISSUE TITLE
Do not remove "unkown" or "empty" properties within the "jspm" prefix

### ISSUE THREAD

**Issue by stefanr** [jspm/jspm-cli#562]
I would suggest not to remove "unknown" or "empty" properties from the package.json.

All properties should survive `jspm install` and retain their original order (an exception might be the alphabetical order of dependencies). This is an essential part that allows `jspm` to evolve.

*Consider adding new properties in a future release and running `jspm install` using an older version of `jspm` - settings gone.*

**Comment by guybedford** [comment]
Thanks, yes there is actually an issue for this at https://github.com/jspm/jspm-cli/issues/428.

**Comment by guybedford** [comment]
Tracking at #428, contributions with this are very welcome.
