### ISSUE TITLE
Normalize path separator in config.js (Unix vs Windows)

### ISSUE THREAD

**Issue by stefanr** [jspm/jspm-cli#563]
`jspm install` on Unix produces `config.js`

```js
System.config({
  "paths": {
    "*": "*.js",
    "github:*": "jspm_packages/github/*.js",
    "npm:*": "jspm_packages/npm/*.js"
  }
});
```

`jspm install` on Windows produces `config.js`:

```js
System.config({
  "paths": {
    "*": "*.js",
    "github:*": "jspm_packages\\github\\*.js",
    "npm:*": "jspm_packages\\npm\\*.js"
  }
});
```

I would suggest to not use any Windows separators in generated output.

**Comment by guybedford** [comment]
@stefanr thanks for posting - Windows bugs can slip through the cracks. I do believe this was resolved in a much earlier version. Can you confirm which version of jspm you are using here?

**Comment by stefanr** [comment]
Tested this yesterday with version `0.14.0`.

**Comment by guybedford** [comment]
I was able to replicate this if I specified a custom path to `jspmPackages` in the package.json directories, and then got `custom\\path/github/*.js` but haven't been able to get the exact output like you have above there. Also if you look at the code - https://github.com/jspm/jspm-cli/blob/master/lib/config/loader.js#L223 you will see that it is impossible to get any other output?

Perhaps try running `jspm setmode local` explicitly and see if that changes it?

**Comment by stefanr** [comment]
You're right, my mistake, sorry. I was using a relative path like `../../` so the config file actually looked like this:

```js
System.config({
  "paths": {
    "*": "*.js",
    "github:*": "..\\..\\jspm_packages/github/*.js",
    "npm:*": "..\\..\\jspm_packages/npm/*.js"
  }
});
```

The problem is in line [220](https://github.com/jspm/jspm-cli/blob/master/lib/config/loader.js#L220): `path.relative(...)`.

I suggest something like this:

```js
jspmPackages = jspmPackages || path.relative(config.pjson.baseURL, config.pjson.packages);
  if (path.sep === '\\')
    jspmPackages = jspmPackages.replace(/\\/g, '/');
```
