### ISSUE TITLE
Show a useful error message for arithmetic with bundle sfx

### ISSUE THREAD

**Issue by piuccio** [jspm/jspm-cli#564]
```
jspm bundle-sfx one + two build.js
     Building the single-file sfx bundle for one...
ok   Built into + with source maps, unminified, mangled.
```

Generates a file called `+.js` containing only `one`

**Comment by guybedford** [comment]
Yes - bundle-sfx only supports a single entry point because it represents a single execution thread only. If you need multiple modules try writing a main.js that imports them.

**Comment by guybedford** [comment]
We should have a better error message here though.

**Comment by piuccio** [comment]
Well, I have one file that's the single entry point, some other files are loaded independently as 'widgets' by whatever framework you like (angular, backbone, doesn't matter).

I don't want to list an explicit dependency in my files, but still I'd like to package everything in one bundle.

**Comment by guybedford** [comment]
How are you loading the other widget files if they aren't being imported?

**Comment by piuccio** [comment]
Well, in the specific I have this knockout component

```js
ko.components.register('cool-widget', {
    viewModel: { jspm: 'widgets/cool' },
    template: { text: 'widgets/cool.html' }
});
```

Internally when knockout finds the element `<cool-widget></cool-widget>` in the DOM it'll call this code

```js
loadViewModel: function (name, templateConfig, callback) {
    if (typeof templateConfig !== 'object' || !('jspm' in templateConfig)) {
        callback(null);
        return;
    }

    System.import('./' + templateConfig.jspm).then(function (Component) {
        callback(function (params, componentInfo) {
            return new Component(params, componentInfo.element);
        });
    });
}
```

That's not an explicit dependency. You can do the same thing with pretty much any framework.

**Comment by guybedford** [comment]
Right, so if you're calling `System.import` then you're assuming a loader in the page - it is no longer a self-executing bundle, it's just a bundle.

**Comment by piuccio** [comment]
Oh I see, so you're saying that in a `-sfx` bundle I can't call `System.[import | amdRequire]`?

In that case it makes send, I guess I didn't really understand what a self-executing bundle mean.

In my mind a `-sfx` would still include `System` but would automatically do a `System.import` of the main module.

**Comment by guybedford** [comment]
Yes exactly - an SFX bundle contains a micro loader that doesn't have a fetch implementation at all, so it's a System yes but not one that can `System.import`, and it doesn't write a `System` global. SFX bundles will detect if there is a full System loader in the page though and define into that rather necessary though.

**Comment by piuccio** [comment]
Alright. It can be closed unless you want to implement a better error message or add something in the doc to make clear that arithmetic doesn't make sense in this context

**Comment by guybedford** [comment]
Ok for now I've added a better message here in https://github.com/jspm/jspm-cli/commit/07588918540f29941d172c1e8c18121c02ddfebc, there is an issue tracking support for multiple bundle-sfx entry points in https://github.com/systemjs/builder/issues/108, which would most likely be space-separated if we supported this, but I'm not sure if I'm sold on the use case. Further feedback welcome.

**Comment by unional** [comment]
@guybedford  with `systemjs/builder#108` closed with https://github.com/systemjs/builder/commit/2a57d0028bbc4a064369c5d411d1655b2966ab60

Can we do multiple entry points bundle-sfx now?
I want this feature for running tests.

**Comment by unional** [comment]
Essentially I tried to do this:
```js
const jspm = require('jspm');
const run = require('tape-run');
const tapSpec = require('tap-spec');
const streams = require('memory-streams');

const builder = new jspm.Builder();
builder.buildStatic('spec/**/*.spec.ts').then((output) => {
  const reader = new streams.ReadableStream(output.source);
  reader
  .pipe(run())
  .pipe(tapSpec())
  .pipe(process.stdout);

});
```
but the output seems to be wrong.
I did manage to get it working with this:
```js
const gulp = require('gulp');
const jspm = require('gulp-jspm');
const through2 = require('through2');
const run = require('tape-run');
const tapSpec = require('tap-spec');

gulp.src('spec/**/*.spec.ts')
  .pipe(jspm({ selfExecutingBundle: true }))
  .pipe(through2.obj(function(file, enc, callback) {
    this.push(file.contents);
    callback();
  }))
  .pipe(run())
  .pipe(tapSpec())
  .pipe(process.stdout);
```
But that means each test file will be a bundle itself. As the number of test files and source grows, it will become very heavy.

**Comment by unional** [comment]
Found the issue. Likely there is a bug in the `bundleSFX()` with multiple entry. Will file an issue.
