### ISSUE TITLE
Bundle includes traceur-runtime (or Babel) ?

### ISSUE THREAD

**Issue by jackfranklin** [jspm/jspm-cli#576]
Just used the `bundle-sfx` command to generate a self executing version of my app and it worked perfectly, with the single exception that I have to also include the Traceur runtime myself.

I was wondering if you've had any thoughts on detecting if the traceur-runtime (or the Babel runtime, or any others) are required during the bundle phase and then including them in the output file?

**Comment by danharper** [comment]
I imagine this is the same as this issue when using Babel? https://github.com/jspm/jspm-cli/issues/535

**Comment by guybedford** [comment]
Thanks for posting - we're actually working on this feature right now :)

**Comment by jackfranklin** [comment]
@danharper ah yeah I should have spotted that issue.

@guybedford that's awesome, thanks ! Let me know if I can be of use.

**Comment by guybedford** [comment]
The next version of SystemJS builder has this support through the `runtime` build option. So this will be possible with `jspm bundle-sfx main --runtime`.

**Comment by jackfranklin** [comment]
@guybedford that's awesome, thank you!

**Comment by guybedford** [comment]
Note that the released version of this includes the runtime by default, without the need for a `--runtime` CLI argument.
