### ISSUE TITLE
ES6 with NPM I always get "format cjs" and modules don't load properly

### ISSUE THREAD

**Issue by jhoguet** [jspm/jspm-cli#577]
I am trying to use es6 with npm.  

I have the following in my package.json

```js
{
  ...
  "format" : "es6",
  "jspm": {
    "format" : "es6",
    ...
  }
}
```  

I tried format in jspm only but when that didn't work, I added it to the root as well. 

when I install (from our internal npm) I get the following. 
`.../jspm_packages/dtnpm/config-grid-js@0.2.3.js`
```js
module.exports = require("dtnpm:config-grid-js@0.2.3/index");
```
which points to `.../jspm_packages/dtnpm/config-grid-js@0.2.3/index.js`
```js
"format cjs";
import { ConfigGridClient, ConfigGridClientConfig } from './ConfigGridClient';
...
export { ConfigGridClient, ConfigGridClientConfig };
```
I am not expecting "format cjs" and assume jspm put it there.

When I run this, in a local `app.js`

```js
import { Container } from 'aurelia-dependency-injection';
import { ConfigGridClient, ConfigGridClientConfig } from 'config-grid-js';
// ConfigGridClient, ConfigGridClientConfig are undefined
```
stepping into the transpiled version of `app.js` I see `ConfigGridClient = _configGridJs.ConfigGridClient;`

and inspecting `_configGridJs` I can see that `_configGridJs.ConfigGridClient` is `undefined` but `_configGridJs.default.ConfigGridClient` is what I am expecting. 

I am guessing this is related to the fact that "format cjs" was at the top of an ES6 file. 

what am I doing wrong?

**Comment by johnsoftek** [comment]
Commonjs is the default format for npm modules. Try an override:
```javascript
jspm install dtnpm:config-grid-js@0.2.3.js -o '{format: "es6"}'
```

**Comment by guybedford** [comment]
@jhoguet if publishing ES6 to your internal npm repo, you need to specifically add `format: es6` in the package.json of the published library. Otherwise you need to use an override exactly as @johnsoftek has shown. 

I've updated the publishing workflows information with https://github.com/jspm/jspm-cli/wiki/Publishing-Packages#publishing-jspm-style-packages-to-npm for this case.

Let me know if that works out ok for you.

**Comment by jhoguet** [comment]
I am still seeing the same behavior. Here is the package.json of config-grid-js as the consumer sees it after `jspm install dtnpm:config-grid-js`
```js
{
  "name": "config-grid-js",
  "version": "0.2.4",
  "description": "js libraries for interacting with the config grid",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Jon Hoguet",
  "license": "MIT",
  "publishConfig": {
    "registry": "..."
  },
  "jspm": {
    "format" : "es6",
    "registry" : "jspm",
    "main" : "index.js",
    "directories": {
      "lib": ".",
      "packages": "jspm_packages"
    },
    "dependencies": {
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@^0.4.4",
      "aurelia-http-client": "github:aurelia/http-client@^0.5.4"
    }
  }
}
```
and I still see the same symptoms described earlier. 

If I do `jspm install dtnpm:config-grid-js -o '{format: "es6"}'` I also see the same symptoms.

**Comment by guybedford** [comment]
@jhoguet can you share the contents of your `.jspm.json` file in the installed package folder (the processed package.json file)?

This could be a bug, although I'm surprised as I believe we have other users running this workflow.

**Comment by jhoguet** [comment]
.jspm.json
```
{
  "name": "config-grid-js",
  "description": "js libraries for interacting with the config grid",
  "version": "0.2.4",
  "author": {
    "name": "Jon Hoguet"
  },
  "dist": {
    "tarball": ".../config-grid-js/-/config-grid-js-0.2.4.tgz",
    "shasum": "15a0f5194bd813e1aeb1ece5557c558543d72301"
  },
  "license": "MIT",
  "maintainers": [
    {
      "name": "admin",
      "email": "..."
    }
  ],
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "publishConfig": {
    "registry": "..."
  },
  "_from": ".",
  "_npmVersion": "2.1.11",
  "_npmUser": {
    "name": "admin",
    "email": "..."
  },
  "_id": "config-grid-js@0.2.4",
  "jspm": {},
  "registry": "dtnpm",
  "format": "cjs",
  "ignore": [
    "node_modules"
  ],
  "dependencies": {
    "process": "github:jspm/nodelibs-process@^0.1.0",
    "fs": "github:jspm/nodelibs-fs@^0.1.0",
    "util": "github:jspm/nodelibs-util@^0.1.0",
    "path": "github:jspm/nodelibs-path@^0.1.0",
    "systemjs-json": "github:systemjs/plugin-json@^0.1.0",
    "assert": "github:jspm/nodelibs-assert@^0.1.0",
    "buffer": "github:jspm/nodelibs-buffer@^0.1.0",
    "events": "github:jspm/nodelibs-events@^0.1.0",
    "stream": "github:jspm/nodelibs-stream@^0.1.0",
    "string_decoder": "github:jspm/nodelibs-string_decoder@^0.1.0",
    "tty": "github:jspm/nodelibs-tty@^0.1.0",
    "net": "github:jspm/nodelibs-net@^0.1.0",
    "vm": "github:jspm/nodelibs-vm@^0.1.0"
  }
}
```

package.json
```
{
  "name": "config-grid-js",
  "version": "0.2.4",
  "description": "js libraries for interacting with the config grid",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Jon Hoguet",
  "license": "MIT",
  "publishConfig": {
    "registry": "..."
  },
  "jspm": {
    "format" : "es6",
    "registry" : "jspm",
    "main" : "index.js",
    "directories": {
      "lib": ".",
      "packages": "jspm_packages"
    },
    "dependencies": {
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@^0.4.4",
      "aurelia-http-client": "github:aurelia/http-client@^0.5.4"
    }
  }
}
```

**Comment by guybedford** [comment]
@jhoguet note how the `"format": "cjs"` has crept into the `.jspm.json` file. This could be a bug - let me do some testing on this my side.

**Comment by guybedford** [comment]
Still looking into this, but in the mean time I think a way to work around this is to add:

```json
"jspm": {
  "registry": "jspm"
}
```

to the package.json / override.

**Comment by jhoguet** [comment]
that is already there. 

Any way I can help? Can you point me in the right direction to debug this?

**Comment by guybedford** [comment]
@jhoguet specifically you need to add the `registry: "jspm"` within the `"jspm"` object in the package.json itself so it is `pjson.jspm.registry == 'jspm'`. I've been working on making these workflows more intuitive for the next release.

**Comment by jhoguet** [comment]
I believe that is what I have above https://github.com/jspm/jspm-cli/issues/577#issuecomment-78944192 am I missing something?

**Comment by guybedford** [comment]
This is very strange. If you feel like debugging it, the relevant code to look at is https://github.com/jspm/npm/blob/0.20.4/npm.js#L331 where the `cjs` format is set by default, only if another format is not already set.

**Comment by guybedford** [comment]
@jhoguet did you try using an override? Also did you try using `-f` to clear local caches? perhaps `rm -rf ~/.jspm/dtnpm-cache` as well will help.

**Comment by jhoguet** [comment]
No change.... 

```sh
cat jspm_packages/dtnpm/config-grid-js\@0.2.4/package.json | json 'jspm.registry'
```
>jspm

```sh
cat jspm_packages/dtnpm/config-grid-js\@0.2.4/index.js
```

>/* */
>"format cjs";
>import { ConfigGridClient, ConfigGridClientConfig } from './ConfigGridClient';
>...

Which we don't want, but is consistent with 

```sh
cat jspm_packages/dtnpm/config-grid-js\@0.2.4/.jspm.json  | json 'format'
```
> cjs

but worth pointing out registry is not what we're expecting (is it?)

```sh
cat jspm_packages/dtnpm/config-grid-js\@0.2.4/.jspm.json  | json 'registry'
```
>dtnpm

**Comment by guybedford** [comment]
@jhoguet it could be worth ensuring you're running the latest version of jspm-npm here as well?

**Comment by jhoguet** [comment]
it was using the latest (0.14.0). 

is the registry expected to be dtnpm even though we explicitly set it to jspm?

**Comment by guybedford** [comment]
@jhoguet at this point, what would really help the most here to work out the issue would be a test repo or steps to reproduce. I've tried simple replications this side but haven't had any luck yet. Let me know if that might be possible. Thanks for your help tracking this.

**Comment by jhoguet** [comment]
obviously connecting to our internal npm is not possible. 

I instead created a new endpoint to npm thinking that is the only new variable (not default npm)

    jspm endpoint create npm2 jspm-npm

I then installed from npm and npm2, and it worked with es6 properly in both. In other words, I couldn't reproduce. 

given that I can't give you replication procedures, I am going to close this. When I get more time to prove this out more I will dig in deeper and open a new ticket if I am still seeing it. 

Thanks for your help, I certainly have been learning more about JSPM through the process.

**Comment by guybedford** [comment]
@jhoguet thanks for letting me know - please do post back when you have something reproducible.
