### ISSUE TITLE
Check update

### ISSUE THREAD

**Issue by piuccio** [jspm/jspm-cli#579]
Hi, would it be possible to add something like [npm-check-updates](https://github.com/tjunnone/npm-check-updates). It checks if there are new versions available for all your dependencies.

**Comment by guybedford** [comment]
Certainly - we discussed the idea of `jspm update --test` in https://github.com/jspm/jspm-cli/issues/471 to do be able to do a report on what would happen if you ran an update. Could be an option. Unfortunately won't be a high priority in core for a while, so we may need to rely on third-party code to pick this stuff up in the mean time.

**Comment by guybedford** [comment]
Moving this to #471, feedback is welcome there.
