### ISSUE TITLE
Overwriting folder names schema

### ISSUE THREAD

**Issue by hipertracker** [jspm/jspm-cli#582]
I have a very specific environment. Folder names can contain only alphabet letters (a..zA..Z) + underscore character (just like Python modules). On the other side, jspm is using dashes and @ characters for folder names. Is it possible to change it somehow  to more strict schema I have to work with? I know, that I can download any package with another name. But jspm itself is using symlinks @ and - characters. Any hints?

**Comment by guybedford** [comment]
Unfortunately this isn't possible, jspm is tied to this schema.
