### ISSUE TITLE
lib set to `.` on install error

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#583]
From gitter - 

err  Error: EINVAL, rename '/Users/rasmus/.jspm/packages/github/rspi/jspm-test-b@master/.'
         at Error (native)

**Comment by floatdrop** [comment]
@guybedford this is fixed in https://github.com/jspm/jspm-cli/commit/888b9f5e5931273c9101e8f8076b505554710463

**Comment by guybedford** [comment]
Thanks for clarifying.
