### ISSUE TITLE
Can I use jspm instead npm to install dev dependencies from package.json?

### ISSUE THREAD

**Issue by kalopsia** [jspm/jspm-cli#585]
Hello, thanks for the wonderful project, very helpful!

I want to use jspm instead of npm to install dev dependencies from package.json. Is it possible? I just got tired from big amount of different folders. The only reason I use node modules is gulp and gulp plugin. I don't know may be is it possible to install and require gulp-* modules using jspm?

**Comment by guybedford** [comment]
Thanks for posting, I assume you saw https://github.com/jspm/jspm-cli/commit/01b15b07ae6c8e5391bcb1e4402c46109fa4da65 then?

**Comment by kalopsia** [comment]
Oh thank you! No I just close issue, I didn't find any information about it and concluded that I want something "weird"..

I tried to install gulp as follows:
```
jspm init
jspm install npm:gulp
ok installation successful

gulp --help
[11:04:44] Local gulp not found in ~/cloud/projects/test
[11:04:44] Try running: npm install gulp
```
I have very basic JS knowledge. And the reason to install gulp using jspm is to create standalone gulp program.

**Comment by guybedford** [comment]
jspm does not support all npm packages on the server - use npm here rather. See https://github.com/jspm/jspm-cli/wiki/NodeJS-Usage for more info. Server tools still very much need to run through npm.

**Comment by kalopsia** [comment]
I'm sorry for the "newbie" question, but what is:

> ... npm packages on the server
> Server tools ...

I'm Go programmer and npm, node and much of other terms and tools are dark forest to me. Could you clarify, please?  

The first thing I realized is that jspm depends from `npm`, npm from `nodejs`. So to use jspm I need the chain: nodejs -> npm -> jspm. The second one is that jspm can "browserify" modules/packages. As far as I know it means I can get rid of dependencies (including nodejs and npm) and generate one big standalone js file that could contain any modules/packages installed by jspm itself. Am I right?

**Comment by guybedford** [comment]
Yes exactly - npm is what is used to install NodeJS code on the server. jspm is currently best used just for the browser package management itself, allowing for some shared code with the server, but still use npm to install server packages like Gulp etc.

**Comment by kalopsia** [comment]
Got it, thank you for answers.

**Comment by matthewharwood** [comment]
@guybedford 
> Server tools still very much need to run through npm.
why is that?  I mean if i do `jspm install npm:karma --save-dev` why wouldnt it just install it properly through npm?

**Comment by guybedford** [comment]
@matthewharwood see https://github.com/jspm/jspm-cli/wiki/NodeJS-Usage.

**Comment by matthewharwood** [comment]
I see.  Is there a goal to get jspm to support server packages like it is just a tough problem to solve?  Or should we just assume jspm is for client side primary

**Comment by guybedford** [comment]
@matthewharwood yes the goal is to fully support server packages, but it will take a while so don't hold your breath!

**Comment by matthewharwood** [comment]
https://youtu.be/Z9obgyYB1IU

**Comment by marthinus-engelbrecht** [comment]
@matthewharwood Ha ha ha, +1 for the video

**Comment by nmccready** [comment]
This is even more relevant with npm 3. Is there milestone for server side jspm?

https://github.com/npm/npm/issues/8826

**Comment by guybedford** [comment]
This is coming with jspm 0.17, alpha will be mid December.

**Comment by eladh** [comment]
Hi @guybedford 

i was trying to read https://github.com/jspm/jspm-cli/wiki/NodeJS-Usage  as you mentioned in one of your comments and i see Create new page. i saw this issue also in other issues.

10x :-) 
elad.
