### ISSUE TITLE
error normalizing babel-runtime path in windows

### ISSUE THREAD

**Issue by u9520107** [jspm/jspm-cli#586]
Currently I transpile my entire project into cjs, with babel's optional transform "runtime". This somehow simplified the module.default vs. no default issue for me. While my project works find in osx and linux, I ran into this issue on windows.
I get this error msg when I run systemjs-builder's trace on the transpiled code:
```
{ [Error: Error loading "npm:babel-runtime@4.7.3/C:\Users\jack\.jspm\packages\npm\babel-runtime/index" at file:C:/Users/
jack/github/meepworks/jspm_packages/npm/babel-runtime@4.7.3/C:\Users\jack\.jspm\packages\npm\babel-runtime/index.js
Error loading "npm:babel-runtime@4.7.3/C:\Users\jack\.jspm\packages\npm\babel-runtime/index" from "test-server/node/app/
app" at file:C:/Users/jack/github/meepworks/test-server/node/app/app.js
ENOENT: no such file or directory, open 'C:\Users\jack\github\meepworks\jspm_packages\npm\babel-runtime@4.7.3\C:\Users\j
ack\.jspm\packages\npm\babel-runtime\index.js']
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\jack\\github\\meepworks\\jspm_packages\\npm\\babel-runtime@4.7.3\\C:\\Users\\jack\\.jspm\\packages\\
npm\\babel-runtime\\index.js' }
```
It looks like the builder somehow attemps to include a file in the .jspm folder... However, that file doesn't even exist on the file system.

On the client side, es6-module-loader gives this error:
```
Error loading "npm:babel-runtime@4.7.3/C:\Users\jack\.jspm\packages\npm\babel-runtime/index" at http://localhost:15551/jspm_packages/npm/babel-runtime@4.7.3/C:\Users\jack\.jspm\packages\npm\babel-runtime/index.js
Error loading "npm:babel-runtime@4.7.3/C:\Users\jack\.jspm\packages\npm\babel-runtime/index" from "dist/client-app-driver" at http://localhost:15551/dist/client-app-driver.js
Not Found: http://localhost:15551/jspm_packages/npm/babel-runtime@4.7.3/C:\Users\jack\.jspm\packages\npm\babel-runtime/index.js
es6-module-loader.src.js:2563 GET http://localhost:15551/jspm_packages/npm/babel-runtime@4.7.3/C:/Users/jack/.jspm/packages/npm/babel-runtime/index.js 404 (Not Found)
```
In both cases, the module resolves to some path under .jspm folder.

**Comment by guybedford** [comment]
This could be issue - https://github.com/jspm/npm/commit/59cb342820ee41759b712c416ae71531d7e73274. Can you confirm you're running jspm-npm 0.20.3 or greater?

**Comment by u9520107** [comment]
indeed my system had jspm-npm@0.20.2.
I'll try to re-install some packages to see if it's fixed

**Comment by u9520107** [comment]
Updated to jspm-npm@0.20.4
However still seeing the same error.

**Comment by guybedford** [comment]
@u9520107 thanks for letting me know. Even with `jspm install -f`?

**Comment by u9520107** [comment]
@guybedford that seems to fix the issue. Thanks!

**Comment by guybedford** [comment]
Great, thanks for letting me know.
