### ISSUE TITLE
Prevent jspm-cli from accidentally publishing

### ISSUE THREAD

**Issue by interactionist** [jspm/jspm-cli#588]
Hi.
Is there a way to prevent jspm-cli from accidentally publishing code to any registry?
I have a private module and need to make sure nothing leaks.

Thank you for your help.

**Comment by floatdrop** [comment]
@interactionist `jspm-cli` is not publishing anything, `npm` does. You can set [`private`](https://docs.npmjs.com/files/package.json#private) field in `package.json` to prevent accidentally publishing package to `npm`.

**Comment by interactionist** [comment]
@floatdrop +1
I set the private field in the package.json whenever necessary. I just wasn't sure about jspm. 
Many thanks.

**Comment by guybedford** [comment]
Yes exactly, there is no `jspm publish` command as yet, although this is certainly planned. I've noted this feature at https://github.com/jspm/jspm-cli/issues/249.

**Comment by interactionist** [comment]
Hmm … this is annoying, yet another registry you need to be aware of not to accidentally publish too and track that. I especially loved that jspm is (was) bundling-first; and hope it will stay so.

**Comment by guybedford** [comment]
`jspm publish` would publish to npm or GitHub based on the package.json options, it's just a shortcut to `git tag && git push` or `npm publish`.

**Comment by interactionist** [comment]
Okay. But there is nothing to worry as of right now and one is save when you have ```private:true```?

**Comment by guybedford** [comment]
Yes completely.

**Comment by interactionist** [comment]
Okay. Thank you.
