### ISSUE TITLE
using JSPM with NPM shouldn't imply node... or should it?

### ISSUE THREAD

**Issue by jhoguet** [jspm/jspm-cli#592]
This is intended to start a conversation. 

We are seriously considering using JSPM within our enterprise. 

We have available to us both Github Enterprise and NPM (via Artifactory). 

We have decided that we would prefer to pull packages from NPM rather than Github Enterprise because the separation of concerns regarding Version Control and Building / Publishing a package are more clear with NPM. 

For example, using Github Enterprise, a tag might contain built assets but master might not. A consumer might point to master thinking that is the way to get "the latest" only to have that fail because the built assets aren't normally committed. We don't even commit the built assets to the tag so modifications to our process would be necessary for that. 

The problem then is that the NPM endpoint seems pretty opinionated, to the point of it not being recommended unless you are using it for a package that is also for node. Opinionated in that it assumes you're going to need node shims. 

Are we alone in thinking that there should be an npm endpoint that doesn't assume node shims? That as a publisher, you should declare node shims as dependencies, and it not be assumed by the endpoint? 

I am willing to work on such an endpoint, but first I wanted to get feedback... maybe we're overlooking something...

**Comment by guybedford** [comment]
Yes this is a completely valid use case, there is a blurring on npm between Node-style packages and other conventions. I'm working on the upcoming release of jspm at the moment, and am adding support for a `jspmNodeConversion: false` property in the package.json (https://github.com/jspm/npm/commit/2f278895f14ae34a9d6ea6472cfd8821023e3341) to disable all Node-style conversions happening on packages published to npm, to just treat the package normally in jspm like you've described.

Let me know if that sounds like it would solve your use case here.

**Comment by jhoguet** [comment]
sounds like your a step ahead of me - excellent!
