### ISSUE TITLE
jspm dl-loader --edge causes es6-module-loader to look for traceur in the wrong place

### ISSUE THREAD

**Issue by bennlich** [jspm/jspm-cli#597]
Steps to reproduce:
```
jspm init
jspm dl-loader --edge
```
which outputs:
```
Using loader versions:
       es6-module-loader@master
       systemjs@master
       traceur@master
```
which looks good. But then when I try to load a script that imports, say, jquery (after `jspm install jquery`):

![image of error](http://cl.ly/image/112g1O0X0E3t/Screen%20Shot%202015-03-19%20at%202.29.02%20PM.png)

So it looks like it starts looking for traceur in the wrong place?

**Comment by guybedford** [comment]
Yes this is due to a breaking change against jspm in the loader. `dl-loader --edge` doesn't guarantee there won't be breaking changes.

**Comment by guybedford** [comment]
(The fix is to add a new path - `System.config({ paths: { traceur: 'jspm_packages/traceur.js' } })`)

**Comment by bennlich** [comment]
Ah, okay. I tried using `--edge` because I was having trouble importing modules when specifying the full filename including the .js extension. `--edge` didn't seem to fix this though. I keep getting errors like,

    GET http://localhost:8000/js/app.js.js 404 (File not found)

Poking around recent issues, I thought `import './someModule.js'` was now supported though?

**Comment by guybedford** [comment]
@bennlich that change has not been made yet, it will be coming in SystemJS eventually, just working on aligning it with a few other changes which is proving to be tough to synchronise.

**Comment by bennlich** [comment]
Ah, k. Thanks a bunch for the quick replies!

**Comment by guybedford** [comment]
This should be working in the new beta. If not please do let me know.
