### ISSUE TITLE
CommonJS style scripts do not get ES6 transpiling

### ISSUE THREAD

**Issue by zcregan** [jspm/jspm-cli#598]
If you import a JavaScript file containing CommonJS style modules, that file won't have any ES6 transpiling performed on it. I believe this is a valid use case and will actually become very common in the near future as node.js and io.js start implementing ES6 features natively. I don't foresee the node.js/io.js community moving to ES6 module syntax very quickly, but I wouldn't be surprised to see the community start taking advantage of other ES6 features in the very near future (template strings, arrow functions, etc.).

I've put together a small demo including such a script. The problematic script file is `wwwroot/cmjsES6Module.js`. It has CommonJS style modules with an ES6 arrow function. If you run the app with `npm start` and check your browser dev tools, you'll see the error `Uncaught SyntaxError: Unexpected token =>`.

https://github.com/zcregan/jspm-cmjs-es6-demo/tree/master

**Comment by guybedford** [comment]
Yes, this is exactly what we need the Babel plugin for. The default transpiler level is only for ES6 modules specifically.

**Comment by guybedford** [comment]
Just let me know if you need further help with a precompile workflow through Babel here at all.

**Comment by zcregan** [comment]
I updated my example to better illustrate my point.

The `cmjsES6Module.js` file now has a for-of loop. It's an ES6 feature, but Node.js supports it. Because Node supports it, it's likely that developers will start using it in completely node.js compatible npm packages. For-of loops don't work in IE11 though...

So my point was that just because something is 'cjs' doesn't mean that it can't also have 'es6' code in it. Do you not think JSPM should handle npm packages like this transparently? Is there a technical reason you couldn't run 'cjs' files through the es6 transpiler afterwards?

**Comment by guybedford** [comment]
@zcregan I think it may be preferable to do these conversions at the production-level and not the install level. Do you know what Browserify does with these types of ES6 features?
