### ISSUE TITLE
JSPM install command to respect package overrides

### ISSUE THREAD

**Issue by BuildingJarl** [jspm/jspm-cli#599]
Use case:
Say I create a project and install some dependancies through JSPM. Since I need some custom behaviour from these dependancies I have to install them using the -o override command. This all works great, but if I clone my repo on a different computer and run JSPM install the overrides are not respected and the dependancies are installed using the default settings. 
This could lead to errors and takes time to fix, since all the dependancies have to be installed separately using -o -f and the specific override details. 
Is it possible to specify which overrides the JSPM install command should use, if any. Maybe in the package.json file?

Hope this makes sense

**Comment by guybedford** [comment]
Yes there is an issue for this at https://github.com/jspm/jspm-cli/issues/398.

**Comment by guybedford** [comment]
This has been implemented in the current beta.
