### ISSUE TITLE
problem installing knockout

### ISSUE THREAD

**Issue by lookfirst** [jspm/jspm-cli#600]
```
jspm install knockout=github:knockout/knockout
jspm install github:Knockout-Contrib/Knockout-Validation
```

Notice that the K-V install doesn't declare knockout as a dependency in the `config.js`, even though it is there in the `package.json` and the `bower.json` in the K-V github distribution.

**Comment by guybedford** [comment]
I don't see a dependency on Knockout - https://github.com/Knockout-Contrib/Knockout-Validation/blob/2.0.2/package.json.

(note that peerDependencies are not currently supported in jspm)

Certainly submit an override to add this if you're able to.

**Comment by guybedford** [comment]
(Supporting peerDependencies is being tracked at https://github.com/jspm/jspm-cli/issues/490)

**Comment by lookfirst** [comment]
Or better yet, look at the bower.json, where the dependency is declared correctly?

**Comment by guybedford** [comment]
I'm just hesitant to make the browser registry another server that the github endpoint needs to rely on. That's two separate server systems for a single registry which makes no sense. We have to think in terms of backwards compatibility as well.

There is a bower registry already if that is what you want (and yes points of duplication are the next issue there).

Rather let's tackle this from the other direction - having some kind of process to "generate" the override from the metadata, separate to the standard install, that can then read Bower information etc and suggest the override properties.

I've actually been working on an automated override workflow today ("Would you like to enter a main entry point? [y/n]?"-style prompts, programming them making me feel like a kid again :P).

I'll definitely put some thought to this and see if we can come up with something better in the process - "This repo is on GitHub with a bower.json, would you like to auto-generate the override from these properties? [y/n]".

**Comment by carlosagsmendes** [comment]
That seems great. In the meanwhile what's the best way to tackle this? Should I create an entry on the JSPM registry and make Knockout Validation depend on Knockout? https://github.com/jspm/registry/blob/master/package-overrides/github/DataTables/DataTables%401.10.4.json#L14

By the way, why there aren't package overrides for Bower? (only NPM and Github)

**Comment by guybedford** [comment]
@carlosagsmendes I guess the first step here is to see if `jspm install github:knockout/knockout` works and get that override going. I've created https://github.com/jspm/registry/issues/282 and https://github.com/jspm/registry/issues/283 to track this, will look into it when I have some time but right now need it's all release work unfortunately.

**Comment by lookfirst** [comment]
Maybe I don't understand the overall issues here enough, but what I do know is that with no cross repository/endpoint dependency resolution, I'm going to only ever use a single repository, if possible. 

Since github: offers the most flexibility, that is what I'm going to always standardize on. Therefore, I want this tool to always work when I point at a project that is on github. That seems to mean that if there is a bower.json and it has the right information in it, then that is where I would expect the tool to look.

The idea of having the user to answer questions during install seems crazy to me. I would have no idea what to answer with regards to a main entry point. It also complicates hands free installs on CI systems. It isn't user friendly when the tool could easily just do the right thing.

The concept of maintaining overrides seems broken too. I'd rather just get the upstream project fixed if need be. Like what we just did with bootstrap. In the case of this knockout issue, it is a simple tool fix. Overrides should be the last resort, not the first. Otherwise it is always a game of whackamole for infinity.

I fee like jspm is over engineered and isn't following the Unix tool philosophy of focusing on doing one thing well. I really just want a single tool to install my dependencies and write the config.js mappings. I don't want it to bundle and do all this other stuff. That should be left for another tool. 

The multitude of repository support is a neat idea, but in practice as an end user, it is really confusing and difficult. It just takes too much thought and too often ends with a messed up configuration that doesn't do what I need.

I'm willing to help you build this. I'm writing an ebook now and there is a whole chapter on just how messed up the dependency resolution is. I want to remove that chapter so badly. This issue is a prime example of how a user can get lost too easily. Let's make this better!

Jon

**Comment by guybedford** [comment]
> Maybe I don't understand the overall issues here enough, but what I do know is that with no cross repository/endpoint dependency resolution, I'm going to only ever use a single repository, if possible. 

It''s completely possible to have dependencies in other registries: `{ dependencies: { "jquery": "github:components/jquery@^1.2.3", "underscore": "npm:underscore" }`. It's up to the user to keep an eye on duplicated subdependencies.

> Since github: offers the most flexibility, that is what I'm going to always standardize on. Therefore, I want this tool to always work when I point at a project that is on github. That seems to mean that if there is a bower.json and it has the right information in it, then that is where I would expect the tool to look.

If we make the rule that we always do a lookup in the Bower registry for a bower.json, then we are indefinitely dependent on the Bower servers. This is a big step to make, that needs more convincing than that.

> The idea of having the user to answer questions during install seems crazy to me. I would have no idea what to answer with regards to a main entry point. It also complicates hands free installs on CI systems. It isn't user friendly when the tool could easily just do the right thing.

Yes - improving the guess work is an edge we should work on. But it's a hard line to draw - at some point a user just needs to work out what they want jspm to do, and understand jspm, not vice versa. Too much automation can also lead to unpredictable results.

> The concept of maintaining overrides seems broken too. I'd rather just get the upstream project fixed if need be. Like what we just did with bootstrap. In the case of this knockout issue, it is a simple tool fix. Overrides should be the last resort, not the first. Otherwise it is always a game of whackamole for infinity.

You're entirely right - PRs to the package.json of the original repo were always the workflow. Overrides are not meant to exist, but were necessary as a bridging mechanism. I'd like to set up a system to do automated PRs for every override in the registry back to the original repo (created https://github.com/jspm/registry/issues/284).

> I fee like jspm is over engineered and isn't following the Unix tool philosophy of focusing on doing one thing well. I really just want a single tool to install my dependencies and write the config.js mappings. I don't want it to bundle and do all this other stuff. That should be left for another tool. 

I obviously disagree. I'm not sure why you're bringing this up here though, or why it is relevant.

> The multitude of repository support is a neat idea, but in practice as an end user, it is really confusing and difficult. It just takes too much thought and too often ends with a messed up configuration that doesn't do what I need.

It will take thought until package authors support jspm as a first-class environment, growing pains.

> I'm willing to help you build this. I'm writing an ebook now and there is a whole chapter on just how messed up the dependency resolution is. I want to remove that chapter so badly. This issue is a prime example of how a user can get lost too easily. Let's make this better!

Certainly, any help is very welcome, there's only so much I can do. Just try to make it constructive please.

**Comment by carlosagsmendes** [comment]
I did a quick test and here are the issues (the repo is available here: https://bitbucket.org/carlosagsmendes/jspm-knockout/src

1) I installed Knockout and Knockout-Validation using Github

jspm install **knockout**=github:knockout/knockout

jspm install **knockout-validation**=github:Knockout-Contrib/Knockout-Validation

*The references on the config file weren't correct. I had to fix them manually since I couldn't load the files:*

```GET http://localhost:8080/lib/github/knockout/knockout@3.3.0.js 404 (Not Found)
es6-module-loader.src.js:140 Potentially unhandled rejection [3] Error loading "github:knockout/knockout@3.3.0" at http://localhost:8080/lib/github/knockout/knockout@3.3.0.js
Error loading "github:knockout/knockout@3.3.0" from "app/knockout-bootstrapper" at http://localhost:8080/app/knockout-bootstrapper.js
Not Found: http://localhost:8080/lib/github/knockout/knockout@3.3.0.js (WARNING: non-Error used)
es6-module-loader.src.js:2563 GET http://localhost:8080/lib/github/knockout/knockout@3.3.0.js 404 (Not Found)```

2) To get it working I had to change the **config.js** manually. I had to fix the paths:

**Comment by guybedford** [comment]
@carlosagsmendes thanks, moving the discussion about this to https://github.com/jspm/registry/issues/282.

**Comment by carlosagsmendes** [comment]
Thks

**Comment by guybedford** [comment]
`jspm install knockout` should be working now. Let me know if there are any other issues.

**Comment by lookfirst** [comment]
What if I want to make the install from github;?

**Comment by guybedford** [comment]
`jspm install knockout=github:knockout/knockout` is completely equivalent to `jspm install knockout` provided this line remains the same in the registry - https://github.com/jspm/registry/blob/master/registry.json#L178.

**Comment by lookfirst** [comment]
I don't get the point of the registry though... it just seems like you're going to have to whack-a-mole for infinity. Sure, it is great for non-compliant projects that have issues and you need overrides, but for projects that work? I don't get it. I'm really trying to understand here what the preferred way of doing things is.

**Comment by guybedford** [comment]
@lookfirst - it's important to note that the registry is two completely independent things:

1. Short names for install.
2. Overrides.

The short names for install is simply the convenience of using `jspm install knockout` to mean `jspm install knockout=github:knockout/knockout`. That is all it does and nothing more. It's only so you don't have to do lots of typing and remember github user names of what you're installing.

The overrides service is exactly something that the goal is for it not to be used eventually. As you say, the point is for projects to have the config in their package.json files and not use the override service. https://github.com/jspm/registry/issues/284 is the plan to create dynamics to ensure the overrides service can be phased out eventually.

**Comment by lookfirst** [comment]
@guybedford I really appreciate you taking the time to respond. That clarifies things greatly.

How do the cross repo dependencies resolve when using the jspm repo though? For example, if I do this:

`jspm install knockout`

Does that mean that a 3rd party dependency on `github:knockout/knockout` will resolve correctly?

**Comment by guybedford** [comment]
Sure, it helps to know what people get caught on, and thanks for sharing your knowledge in the chat room as well.

Package names are resolved into `registry:name@versionRange`, and sharing these names is how dependencies get shared. Their short-names have no bearing in the resolution process at all apart from being aliases. The only thing to think about is how the package.json dependencies each get mapped into the above form, from other short forms.
