### ISSUE TITLE
Arithmetic support for bundle-sfx?

### ISSUE THREAD

**Issue by hgl** [jspm/jspm-cli#601]
I'm trying to bundle-sfx a couple of polyfills and the main app:

```
$ jspm bundle-sfx polyfill1 + polyfill2 + app/main build.js
```

This doesn't seem to be supported or am I doing it wrong?

**Comment by guybedford** [comment]
Sure, I've added this in https://github.com/jspm/jspm-cli/commit/cb28e421365d859da3294578d051bd8c714b6f66.

**Comment by hgl** [comment]
Thank you for supporting it so quickly. Can't wait to use it. :)
