### ISSUE TITLE
AMD-compatible require not working

### ISSUE THREAD

**Issue by carlosagsmendes** [jspm/jspm-cli#608]
I want to use the AMD require syntax in order to start using JSPM and SystemJS with and existing app.

To do so I'm trying to follow the existing instructions and defining the following variables:

```javascript
<script>
    window.define = System.amdDefine;
    window.require = window.requirejs = System.amdRequire;
</script>
```
But when I try to define and require content:
```javascript
<script>
  define('infrastructure_variable', function() {
        return {
          siteName: 'test',
          siteUrl: 'url'
        }
    });

  require(['infrastructure_variable'], function(iv) {
        console.log(iv);
    });
</script>
```
I get the following error message:
![Error message](http://content.screencast.com/users/carlos.mendes/folders/Jing/media/0a35f87f-bb60-4d7a-8a47-835856a6813c/2015-03-23_1950.png)

**Comment by carlosagsmendes** [comment]
Here's a working example to demonstrate the error:
[AMD Compatible Require Repo](https://carlosagsmendes@bitbucket.org/carlosagsmendes/jspm-amdrequire.git)

**Comment by guybedford** [comment]
Thanks so much for posting, I've fixed this in https://github.com/systemjs/systemjs/commit/57f2b52612278d9be076a6722ba5c2cf9b384f9f, which will be in the next release.

In the mean time you can just use:

```javascript
  window.require = window.requirejs = System.amdRequire.bind(System);
```

**Comment by carlosagsmendes** [comment]
Thank you @guybedford. Now I don't get the error :)

But I get a new one when I try to do an import:

```javascript
import iv from 'infrastructure_variable';
console.log(iv);
```

Error message:

![Babel Error](http://content.screencast.com/users/carlos.mendes/folders/Jing/media/2edf9ee1-a45e-4d7d-8dd4-66b70af37fcc/2015-03-23_2016.png)

I've updated the repo so you can reproduce the problem:
[AMD Compatible Require Repo](https://carlosagsmendes@bitbucket.org/carlosagsmendes/jspm-amdrequire.git)

**Comment by guybedford** [comment]
The global define is interfering with Babel's load. This is actually also fixed in the latest release.

For now I would suggest loading babel manually with a script tag before loading SystemJS.

**Comment by carlosagsmendes** [comment]
Got it. 

Do you have any timeframe about the next release?

**Comment by guybedford** [comment]
Trying not to set release expectations I'll break, but very very soon :)

**Comment by carlosagsmendes** [comment]
Works like a charm. Thanks for the heads-up
