### ISSUE TITLE
Custom overwrites and dependencies

### ISSUE THREAD

**Issue by ebtc** [jspm/jspm-cli#609]
Hi there,

We are currently working on a CRM with Angular 1.3, Loopback & IOJS (node fork) as backend, coding our own things in ES6.

Recently we switched from bower to jspm (one reason was that we needed to manage dependencies manually with bower). So much for the background.

We are now sitting on a number of issues:

1. (I already asked this on gitter - no response) How does one use a dot notated filename in the "main" property when overwriting (e.g. myfile.standalone.js). If I include the full path name it tries to append .js (so .js.js), if I leave.js off it tries to load .standalone ... I also tried to append ! to either option. No luck. 

We are trying to include jQuery-QueryBuilder via a custom overwrite. This plugin has been tricky to include as dependencies always failed (notably extendext and microevent). But there is a standalone with those two included. I cannot get jspm to use that as main entry point because the author called the file xxx.standalone.js. Here is the overwrite:

    {
       "main": "query-builder.standalone.js",
       "registry": "jspm",
       "dependencies": {
        "jquery": "~1.11.0",
        "bootstrap": "^3.1.0",
        "npm:moment": "^2.6.0",
         "npm:microevent-mistic100": "^2.1.0",
         "github:mistic100/jQuery.extendext": "^0.1.1"
        },
       "shim": {
           "dist/query-builder.standalone.js": {
           "deps": [
              "jquery", "bootstrap", "moment"
            ]
        }
      }
    }

2. The dependencies for this plugin get loaded into the package folder and included in the config.js, but it does not load them automatigcally when I import the QueryBuilder. For now I need to set import statements for every dependency.

There may be some other issue involved since we needed to do the same for some CSS files, which would otherwise not load (one was Bootstrap, but there seems to be an known problem with that).

We think that jspm is still the way to go. It offers great features and lets us do things ES6 style, which is awesome. But we are loosing valuable time on small things like this. Which is getting annoying now.

Thanks for your help and great work so far.

**Comment by guybedford** [comment]
The main will accept a `.`, but it needs to find the right main to know how to do this.

If you look at the tagged version of the repo at https://github.com/mistic100/jQuery-QueryBuilder/tree/1.4.2, it has a dist folder, so the main is actually `dist/query-builder.standalone.js`.

Alternatively set a `directories.lib: "dist"` property in the package.json to not need to include the `dist` part.

For the dependencies, you've done the right thing, but just need to include each dependency you want to load with jquery query builder in the same shim with the same alias:

```json
{
  "dependencies": {
    "jquery": "github:components/jquery@~1.11.0",
    "bootstrap": "github:twbs/bootstrap@^3.1.0",
    "moment": "npm:moment@^2.6.0",
    "microevent-mistic100": "npm:microevent-mistic100@^2.1.0",
    "jQuery.extendext": "github:mistic100/jQuery.extendext@^0.1.1"   
  },
  "shim": {
     "dist/query-builder.standalone.js": {
       "deps": [
          "jquery", "bootstrap", "moment", "microevent-mistic100", "jQuery.extendext"
        ]
    }
  }
}
```

For the Bootstrap css issue, that was resolved, and should work fine now if you run `jspm update bootstrap`.

Hope that helps.

**Comment by ebtc** [comment]
Hi there,

Thanks for taking the time to clarify.

I have tried to do this now in two ways (without success):

1. I included this in the overwrite JSON: 
´"main": "dist/query-builder.standalone.js",´

The result is that it still cannot find the proper path:
´Uncaught Error: Unable to load dependency github:mistic100/jQuery-QueryBuilder@1.4.2/dist/query-builder.standalone.´

As you can see, the loader did not append the ".js" to the standalone. 

The same goes for using an ! at the end, like so:
´"main": "dist/query-builder.standalone.js!",´

Results in:
´Potentially unhandled rejection [5] Error loading "github:mistic100/jQuery-QueryBuilder@1.4.2/dist/query-builder.standalone.js!js"´

Am I missing something or is jspm treating any . as a file ending?

The relevant config entries look like this:
    "jQuery-QueryBuilder": "github:mistic100/jQuery-QueryBuilder@1.4.2",

     "github:mistic100/jQuery-QueryBuilder@1.4.2": {
          "bootstrap": "github:twbs/bootstrap@3.3.4",
          "jQuery.extendext": "github:mistic100/jQuery.extendext@0.1.1",
          "jquery": "github:components/jquery@1.11.2",
          "microevent": "npm:microevent-mistic100@2.1.1",
          "moment": "npm:moment@2.9.0"
        },

Thanks.

**Comment by guybedford** [comment]
Strange, this sounds like it could be a bug - I'll look into it.

**Comment by guybedford** [comment]
Oh right - so it's not a CommonJS module but is being detected as one. The error was deceiving because the trailing `.` was actually a full stop - it wasn't about the file extension at all.

Try installing with the `format: "global"` property added to the override, it should work then.

**Comment by ebtc** [comment]
@guybedford thanks, that seems to have done the trick for this package. 

You mentioned that the bootstrap issue was solved. Which bootstrap version would that be, or was that something specific to jspm?

When I add bootstrap through install I get: "bootstrap": "github:twbs/bootstrap@^3.3.4". Then the first three imports for angular's app.js are:

    import 'jquery';
    import 'angular';
    import 'bootstrap';

But that does not seem to load the css files. We have add these lines:

    import 'bootstrap/css/bootstrap.css!';
    import 'bootstrap/css/bootstrap-theme.css!';
    import 'font-awesome/css/font-awesome.css!';

Note that als Fontawesome seem to have this issue. Now, it could still be some setup on our side. But it is very odd, as we did not do anything different from the instructions given in your documentation.

jspm is at 0.14.0

Thanks!

**Comment by ebtc** [comment]
Besides this I have another question that relates to the first question:

Is it (or would it be) possible to include the overwrite instructions in the package.json (maybe as part of the jspm property), so that a jspm install will already use the overwrites?

What would be another way to ensure that one does not have to use the rather long install syntax with overwrites each time an update/install runs? Is that what dependency locks are for?

Thanks for your time.

**Comment by guybedford** [comment]
@ebtc if you can share a test case where the css isn't loading that would help a lot here.

jspm@0.15.0-beta now exactly includes the overrides in the package.json. It is still important for them to be checked into the shared registry though so that dependency sharing works.

**Comment by frankwallis** [comment]
@ebtc in order to automatically load the css files then they need to be shimmed too. Look at the override for angular-material [here](https://github.com/jspm/registry/blob/master/package-overrides/github/angular/bower-material%400.6.0.json). It shims its own css file which means that doing ```require("angular-material")``` will automatically load its css file. 

I think an override probably needs to be added to font-awesome to do the same thing. With bootstrap it is a bit different as people may want to provide their own css file (with theme applied or whatever), this could be achieved by having a separate registry override which delivers just the javascript files?

**Comment by ebtc** [comment]
@frankwallis thanks, that is helpful information

**Comment by ebtc** [comment]
@guybedford how can I control the naming of dependencies? Using the jQueryBuilder example from above: if I `jspm install`it will write the dependencies as follows:

     "github:mistic100/jQuery-QueryBuilder@1.4.2": {
          "bootstrap": "github:twbs/bootstrap@3.3.4",
          "github:mistic100/jQuery.extendext":        
          "github:mistic100/jQuery.extendext@0.1.1",
          "jquery": "github:components/jquery@1.11.2",
          "npm:microevent-mistic100": "npm:microevent-mistic100@2.1.1",
          "npm:moment": "npm:moment@2.9.0"
        },

But, of course, internally the plugin wants to see "microevent" and "moment".

The overwrite in package.json looks as suggested:

    "github:mistic100/jQuery-QueryBuilder@1.4.2": {
        "registry": "jspm",
        "format": "global",
        "main": "dist/query-builder.standalone.js",
        "dependencies": {
          "jquery": "~1.11.0",
          "bootstrap": "^3.1.0",
          "npm:moment": "^2.6.0",
          "npm:microevent-mistic100": "^2.1.0",
          "github:mistic100/jQuery.extendext": "^0.1.1"
        },
        "shim": {
          "dist/query-builder.standalone.js": {
            "deps": [
              "jquery",
              "bootstrap",
              "moment",
              "microevent-mistic100",
              "jQuery.extendext"
            ]
          }
        }

For now I have to manually "fix" the naming to what the example above shows. 

Any ideas?

**Comment by guybedford** [comment]
@ebtc sorry for the delay. The form of the package.json dependencies can be written:

```json
"github:mistic100/jQuery-QueryBuilder@1.4.2": {
    "registry": "jspm",
    "format": "global",
    "main": "dist/query-builder.standalone.js",
    "dependencies": {
      "jquery": "~1.11.0",
      "bootstrap": "^3.1.0",
      "moment": "npm:moment@^2.6.0",
      "microevent-mistic100": "npm:microevent-mistic100@^2.1.0",
      "jQuery.extendext": "github:mistic100/jQuery.extendext@^0.1.1"
    },
    "shim": {
      "dist/query-builder.standalone.js": {
        "deps": [
          "jquery",
          "bootstrap",
          "moment",
          "microevent-mistic100",
          "jQuery.extendext"
        ]
      }
    }
```

Allowing the naming issues to be fixed.

**Comment by ebtc** [comment]
@guybedford thanks. that was it.
