### ISSUE TITLE
Error: EINVAL

### ISSUE THREAD

**Issue by cutandpastey** [jspm/jspm-cli#610]
I'm trying to install https://github.com/guardian/tools-components into a local directory and consistently get:

```
err  Error: EINVAL, rename '~/.jspm/packages/github/guardian/tools-components@1.0.3/.'
```
I'm running:

```
jspm install github:guardian/tools-components
```

I've tried this on different machines and get the same error.

This is reportedly fixed here https://github.com/jspm/jspm-cli/commit/888b9f5e5931273c9101e8f8076b505554710463 and is in master?

Up until the next release is there a known workaround? If not is there a public alpha/beta release which contains this fix?

Thanks.

**Comment by guybedford** [comment]
The jspm 0.15 beta was released yesterday - this should resolve the issue, but please do let me know if not.

**Comment by cutandpastey** [comment]
Excellent, works fine. Thanks so much.
