### ISSUE TITLE
gulp plugin

### ISSUE THREAD

**Issue by olanod** [jspm/jspm-cli#611]
It's something 3rd parties should do but it would be great if you create a gulp plugin exposing the jspm API as a gulp plugin.  
I'm specially interested in the bundling to do something like:

    gulp.src('src/**/*.js')
        .pipe(jspmBundle({}))
        // minify, compress, etc.
        .pipe(gulp.dest('dist'));

**Comment by guybedford** [comment]
Yes this is a common need - I'm not sure if there is anything available yet that does this well. Perhaps ask in the group or Gitter room. If you find something good do post back here.
