### ISSUE TITLE
Avoid non es6 files transpilation

### ISSUE THREAD

**Issue by carlosagsmendes** [jspm/jspm-cli#612]
Is there a way to avoid transpiling legacy files that are not using es6 format?

Thanks in advance

**Comment by guybedford** [comment]
@carlosagsmendes can you clarify what you mean when you say avoiding legacy transpiles?

**Comment by carlosagsmendes** [comment]
Hi @guybedford,

We have a lot of files that aren't written in ES6 so there's no need to transpile them.

I was wondering if there's a way to avoid it but maybe that should be handled during the build process...

Is there any side effect in transpiling them, besides the overhead of the sourcemaps?

Thanks

**Comment by guybedford** [comment]
What do you mean by transpiling the legacy formats? Into ES6? Or System.register?

**Comment by carlosagsmendes** [comment]
My concern is the System.Register since are using RequireJS and we cannot migrate the whole app at the same time.

**Comment by guybedford** [comment]
@carlosagsmendes you can use SystemJS for RequireJS support as described in https://github.com/systemjs/systemjs/wiki/Module-Format-Support#requirejs-support. That will also support bundles created by the r.js optimizer.

That way you can migrate your whole app to run through SystemJS from RequireJS, but your plugins will need to be manually converted and there are edge cases. Then you can handle the build separately.

Alternatively you can run SystemJS and RequireJS together in the page, and create a communication layer between the two registries as well.

There are lots of options here, it really depends on what works best for you.

**Comment by carlosagsmendes** [comment]
Thank you for the guidance!
