### ISSUE TITLE
Support nvm global PATH through liftoff

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#614]
Posted by @subesokun:

> When using nvm every globally installed package gets installed in the folder "~/.nvm/$VERSION/lib/node_modules" depending on the current active node version. When trying to install jspm-git it will be copied under "~/.nvm/$VERSION/lib/node_modules/jspm-git" and jspm will be installed under "~/.nvm/$VERSION/lib/node_modules/jspm"

> Now when jspm ("~/.nvm/$VERSION/lib/node_modules/jspm") tries to require() the jspm-git registry then nodejs will try to find it in the /usr/local/node_modules folder but won't find it of course and jspm fails. Initally I thought this is a bug of nvm but after reading some comments of the nvm developers I'm in doubt about that... See the following comments

It would be interesting to see how Node Liftoff already solves this. Perhaps we just need to set an environment variable in `jspm.js` (liftoff) that passes the global path through to be used for global requires.

It is also potentially a liftoff issue as well, so must have been discussed there.

**Comment by subesokun** [comment]
Thanks for picking it up here! Regarding Liftoff, as far as I understood Liftoff plays nicely together with nvm because you can either create a standalone global cli like jspm or a global cli that depends on a local installed node package (just like gulp or grunt does).

Internally nvm uses [node-resolve](https://github.com/substack/node-resolve) to be more flexible when trying to require a local node package but I think it doesn't cover the use case to require a global node package (like jspm-git). The only way to achieve this seems to be modifying the `NODE_PATH` but the node team opposes such practice.

Further informations can be found here https://github.com/creationix/nvm/pull/97

**Comment by subesokun** [comment]
Lately I'm depending quite much on nvm (locally as well as on build server) so I'm now in a kind of deadlock as my setup requires nvm but I need to use jspm-git as well. Also as far as I understood Travis-CI is using nvm so in case a project is depending on jspm-git it can't be build on Travis.

Any updates on that?

**Comment by guybedford** [comment]
If you're able to chase up a solution here that would be a great help. I'm not sure I fully understand the issue here since if jspm is in `~/.nvm/$VERSION/lib/node_modules/jspm` then the require inside of jspm will search `~/.nvm/$VERSION/lib/node_modules` for `jspm-git` by standard paths rules so it should work fine here.

**Comment by guybedford** [comment]
If you're running a local install of jspm, then you should probably also run a local install of jspm-git. So I think it all works out.

**Comment by subesokun** [comment]
As you said when installing jspm and jspm-git locally it's working as expected but anyways I've debugged the issue a bit.

Interestingly with the latest version of nvm it's now also possible to require the globally installed jspm-git from a globally installed jspm! But I didn't noticed that until now as I've linked jspm globally as I wanted to use the latest head of jspm ( .../lib/node_modules/jspm links to ~/Development/jspm-cli) ... see explanation below

In case jspm is not linked node tries to search jspm-git in the following paths
```
'/home/subesokun/.nvm/versions/node/v0.12.4/lib/node_modules/jspm/lib/node_modules',
'/home/subesokun/.nvm/versions/node/v0.12.4/lib/node_modules/jspm/node_modules',
'/home/subesokun/.nvm/versions/node/v0.12.4/lib/node_modules',
'/home/subesokun/.nvm/versions/node/v0.12.4/node_modules',
'/home/subesokun/.nvm/versions/node/node_modules',
'/home/subesokun/.nvm/versions/node_modules',
'/home/subesokun/.nvm/node_modules',
'/home/subesokun/node_modules',
'/home/node_modules',
'/node_modules'
'/home/subesokun/.node_modules',
'/home/subesokun/.node_libraries',
'/home/subesokun/.nvm/versions/node/v0.12.4/lib/node' 
```

As you can see the path resolver is bubbling up the directory tree starting from the parent folder of the file `jspm/lib/registry.js` which tries to require jspm-git.

Now in case jspm is globally linked it tries to search for jspm-git in the following paths
```

'/home/subesokun/Development/jspm-cli/lib/node_modules',
'/home/subesokun/Development/jspm-cli/node_modules',
'/home/subesokun/Development/node_modules',
'/home/subesokun/node_modules',
'/home/node_modules',
'/node_modules',
'/home/subesokun/.node_modules',
'/home/subesokun/.node_libraries',
'/home/subesokun/.nvm/versions/node/v0.12.4/lib/node'
```

and hence it won't find it :( Also important to notice is that the "NODE_PATH" `~/.nvm/versions/node/v0.12.4/lib/node_modules` is not included in this path list by default.

This leads to following combinations (in case of nvm v0.25.4):
* global jspm + global jspm-git - OK
* global jspm + local jspm-git - ERROR
* local jspm + local jspm-git - OK
* local jspm + global jspm-git - ERROR

The workaround I found for the globally linked jspm issue was to install jspm-git as direct dependency of jspm by calling `npm install jspm-git` within my cloned jspm-cli folder.

I'll do some more tests but I think we can close this issue then.

**Comment by guybedford** [comment]
Yes I think that one needs to either install all local or all global. Perhaps include in the jspm-git docs that if installing jspm locally, jspm-git should also be installed locally. It makes sense to lock both down I think. Closing, but let me know if any further issues come up here.
