### ISSUE TITLE
Should format field of package.json apply to all files?

### ISSUE THREAD

**Issue by hgl** [jspm/jspm-cli#616]
Currently if I specify the `format` field in `package.json` to `es6`, for files not using `import/export`, I still seem to have to specify the format in the systemjs meta config to force it to be transpiled as a module.

I wonder if the `format` field could apply to all files by default and the meta config overrides it file by file?

Also since the spec isn't called es6 anymore, do you think the name should be changed to something like `module`?

**Comment by guybedford** [comment]
Yes the next version of the configuration is planned to support a `modules` object with wildcards instead of separate shim and format.

**Comment by hgl** [comment]
Cool. Since it's planed I will just close this issue.
