### ISSUE TITLE
Extending the ES6 Loader

### ISSUE THREAD

**Issue by spinchristopher** [jspm/jspm-cli#621]
I have extended the es6 loader (specifically the normalize hook), as detailed on the [ModuleLoader wiki](https://github.com/ModuleLoader/es6-module-loader/wiki/Extending-the-ES6-Loader). This works fine when I am transpiling in the browser (I include the script after system, but before config), but when I attempt to build a bundle or a bundle-sfx, I do not know how to make this work. Is this even a feature supported by the jspm bundle command? If so, are there any docs or can you joint me in the right direction; if not, then this would be a feature request. =]

At this point, I have a hackish way to make it work, though it is obviously not a permanent solution. I place the following inside of jspm/jspm.js at the top:
```
require('systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src');

(function() {
	var systemNormalize = System.normalize;
	System.normalize = function(name, parentName, parentAddress) {
		return systemNormalize.call(this, name, parentName, parentAddress);
	}
})();
```

**Comment by guybedford** [comment]
Would it help if the config.js file was allowed to contain these extensions?

**Comment by guybedford** [comment]
The other way to get access to these in the builder is through the API - 

```javascript
var builder = new require('jspm').Builder();
builder.loader.normalize = ...
builder.build('moduleName', 'outfile.js');
```

**Comment by spinchristopher** [comment]
I did see that I can access the hooks when using the API, though (and I suppose I should have mentioned), I am trying to run `jspm bundle-sfx main`. Adding the normalize to the system.config object actually also works in the browser, though when I try to run the build, it errors on the final line inside the new function, where it is trying to call the original System.normalize. The first line of config.json is `var systemNormalize = System.normalize;`, but System.normalize seems to be undefined at this point, so I can't save the reference to it.

Ideally, as I will have lots of projects needing this same modification, I could specify the hooks in a way that would use the same hook for all projects, but specifying them in the config would work too, provided there was a way to reference the original method.

**Comment by guybedford** [comment]
Sure, we could certainly allow the normalize method to be overridden through config.js. Perhaps something like:

```javascript
System.config({
  normalize: function(oldNormalize) { 
    return function(name) {
      return oldNormalize.call(this, name);
    }
  }
});
```

Out of interest here, what custom hook are you adding?

**Comment by spinchristopher** [comment]
That would work, though System automatically applies everything inside that object to this, so you would have to override that, both in the browser and the bundler. Maybe something like `if(typeof config[key] === 'function' && this[key] === 'function') { this[key] = config[key](this[key]); delete this[key]; }`. Additionally, it would have to survive the re-write that is often performed when bundling.

As for the specifics, in es5, we followed a standard of naming the file according to the class name, and usually putting it in a folder with the same name. in Nodejs, we easily manage this by the addition of a few very simple index.js files (actually, in node, you can override the lookup function and have it try several options, in addition to the several it already tries).

At present, this is in a separate file which is included in the html after System but before config.js. Inside config.js, there is an object called 'nested' which contains keys for the folders that need this behaviour (value of true for each). Originally it applied to all, but that broke all the packages...
```
var systemNormalize = System.normalize;
System.normalize = function(name, parentName, parentAddress) {
	if(!this.nested) {
		throw new Error('In order to use `normalize`, you must specify a `nested` object in your config.');
	}
	
	var top = name.substr(0, name.indexOf('/'));
	
	if(top === '.') {
		top = parentName.substr(0, parentName.indexOf('/'));
	}
	
	if(this.nested[top]) {
		name += name.substr(name.lastIndexOf('/'));
	}
	
	return systemNormalize.call(this, name, parentName, parentAddress);
}
```

Also, in case you were curious why nested is an object with true keys, I originally had nested as an array, but when running bundle, it reads and rewrites the file, and that rewrite turned it into an object with numeric keys, which no longer worked with indexOf. Would you like this as a bug report?

**Comment by guybedford** [comment]
In terms of the use case, there is actually an undocumented syntax for these types of requires:

```javascript
System.import('myclass/') // normalizes to myclass/myclass
```

Would that help you here?

**Comment by spinchristopher** [comment]
The undocumented syntax also seem to be untested. =] I can make it work for one level of imports, but if that file tries to import the same way, it seems to ignore the trailing / and look where it would if the / were not there.

**Comment by guybedford** [comment]
Would it be useful?

**Comment by spinchristopher** [comment]
It would be better than having to edit the files directly, though it results in an odd looking syntax (`import Game from 'games/foobar/';`) that may be confusing to those not familiar with it, resulting in "bug fixes" that break things.

**Comment by guybedford** [comment]
Thanks, yes I tend to agree, and that's why I'd like to just remove it entirely.

**Comment by guybedford** [comment]
Let me know if this is still relevant. There might actually be a way to do this by allowing SystemJS builder to be provided with a custom SystemJS build.

If it would still be useful, I'd be happy to consider it.

**Comment by HMUDesign** [comment]
Yes, it is. I also now have a need to extend the system.js to add a custom format. The official way to do this is to replace System.instantiate.

```
(function(System) {
	var systemInstantiate = System.instantiate;
	
	System.instantiate = function(load) {
		if (load.metadata.format === 'glsl-chunk' || !load.metadata.format && load.address.split('.').pop() === 'glsl') {
			load.metadata.format = 'glsl-chunk';
			
			load.metadata.execute = function(require, exports, module) {
				return load.source;
			}
		}
		
		return systemInstantiate.call(this, load);
	}
})(System);
```

**Comment by guybedford** [comment]
Sure, I've created https://github.com/systemjs/builder/issues/147.

The syntax when implemented will be:

```javascript
var builder = new require('jspm').Builder();

builder.reset(MyCustomSystem);

builder.build('some/module').then(done);
```

Closing to track on the builder issue.

**Comment by HMUDesign** [comment]
Is there a way to use this functionality from the command line bundle and bundle-sfx commands?

**Comment by guybedford** [comment]
No, this is advanced build functionality.

**Comment by OrKoN** [comment]
@guybedford So what is the right way to add a custom normalize function to the bundling process? This my attempt. Looks correct to me but does not work.

```
gulp.task('jspm', function() {
  var builder = new jspm.Builder();
  var System = require('systemjs');

  var systemNormalize = System.instantiate;

  System.normalize = function(name, parentName) {
    console.log('normalize ' + name);
    return systemNormalize.call(this, name, parentName);
  }

  builder.reset(System);

  return builder.loadConfig('./app/config.js')
    .then(function() {
      builder.config({
        baseURL: 'app',
        lib: 'app'
      });
      return builder.buildSFX('main', 'dist/app.min.js', { sourceMaps: false, minify: true, mangle: false});
    });
});
```

**Comment by guybedford** [comment]
@OrKoN you need to be using the `_extension` mechanism pattern each of the extensions in SystemJS uses - https://github.com/systemjs/systemjs/blob/master/lib/extension-bundles.js#L20. This will be changing to normal class extension soon.

**Comment by OrKoN** [comment]
Sorry, don't really get how to use that for what I want to do. I like the way to define the normalize method that you suggested here: https://github.com/jspm/jspm-cli/issues/621#issuecomment-86489379  But I guess it's not implemented. Are there better docs on how to user the _extension mechanism?

**Comment by guybedford** [comment]
```javascript
function customExtensionName(System) {
  System._extensions.push(customExtensionName);
  var systemNormalize = System.instantiate;

  System.normalize = function(name, parentName) {
    console.log('normalize ' + name);
    return systemNormalize.call(this, name, parentName);
  }
}
customExtensionName(System);
```

**Comment by guybedford** [comment]
The rest then exactly as you had it.

**Comment by OrKoN** [comment]
Thanks a lot, @guybedford Now it's clear!

**Comment by trusktr** [comment]
@HMUDesign have you made glsl plugin/loader for jspm?

**Comment by OrKoN** [comment]
I have migrated the above code to 0.16.0:

```js
gulp.task('jspm', function() {
  var builder = new jspm.Builder();

  function productionVersions(builder) {
    var systemNormalize = builder.loader.normalize;
    builder.loader.normalize = function(name, parentName, parentAddress) {
      if (name === 'ember') {
        name = 'ember/ember.prod';
      }

      if (name === './env.dev') {
        name = './env.prod';
      }

      return systemNormalize.call(this, name, parentName, parentAddress);
    };
  }

  productionVersions(builder);

  return builder.loadConfig('./system.config.js')
    .then(function() {
      return builder.buildSFX('.tmp/boot', 'dist/app.min.js', { sourceMaps: false, minify: true, mangle: true});
    });
});
```
