### ISSUE TITLE
map property does not work?

### ISSUE THREAD

**Issue by 2fd** [jspm/jspm-cli#623]
when the map property is used, something like:

```bash
    jspm install github:jquery/jquery -o "{map: { sizzle: './src/sizzle/dist/sizzle' } }"
```

this should be reflected in the config.js as:

```javascript

System.config({
  "map": {
    "jquery/jquery": "github:jquery/jquery@2.1.3",
    "github:jquery/jquery@2.1.3": {
      "sizzle": "src/sizzle/dist/sizzle"
    }
  }
})

```

Right?

Currently, this does not work well

**Comment by guybedford** [comment]
No, the map property is only an **internal** map. That is all uses of `require('sizzle')` within the jQuery codebase will be replaced with `require('./src/sizzle/dist/sizzle')` with relative requires correctly normalized.

**Comment by 2fd** [comment]
it is not working equally

![image](https://cloud.githubusercontent.com/assets/208789/6861850/1adc0212-d41c-11e4-83c9-304b929bcd18.png)

**Comment by guybedford** [comment]
So you are using this override:

```
  jspm install github:jquery/jquery -o "{map: { sizzle: './src/sizzle/dist/sizzle' } }"
```

Then what require are you running to get the error?

**Comment by 2fd** [comment]
```javascript
    require('jquery/jquery');
```

or 

```javascript
    require('jquery/jquery/selector');
```

**Comment by guybedford** [comment]
I just had a look at the jQuery override and the issue is that there is a `directories.lib` entry which is set to `src`. As a result the map value needs to be `{map: { sizzle: './sizzle/dist/sizzle' } }` (without `src`) to work.

**Comment by 2fd** [comment]
I get the same error.
and as '/sizzle.js' is the only file that tries to load, makes me think that there solves correctly the map property.

![image](https://cloud.githubusercontent.com/assets/208789/6891034/2737e9e6-d68c-11e4-8d15-977bd3434cef.png)

I can only get it to work by adding the map to system

```js
System.config({
  "map": {
//   [...]
    "github:jquery/jquery@2.1.3": {
      "sizzle": "github:jquery/jquery@2.1.3/sizzle/dist/sizzle"
    }
})

```
but want to solve it by override to add to jspm/registry

**Comment by guybedford** [comment]
Thanks, yes this was an AMD mapping bug - fixed in https://github.com/jspm/jspm-cli/commit/125e0207a32732b6b326d592bdc8bf5a33ecd01b.

**Comment by 2fd** [comment]
:+1:
