### ISSUE TITLE
Issue with "packages.json" configuration

### ISSUE THREAD

**Issue by carlosagsmendes** [jspm/jspm-cli#625]
Hi,

Since I want my packages to be installed into **app/src/lib** I'm using the following **packages.json** configuration: 
```
{
  "jspm": {
    "directories": {
      "packages": "app\\src\\lib"
    },
    "dependencies": {
      "angular": "github:angular/bower-angular@^1.3.15",
      "knockout": "github:knockout/knockout@^3.3.0"
    }
  }
}
```

I've set the **baseUrl** to **/app/src** in my **config.js** file.

I'm using this setup to be able to change the baseURL to **/app/dist** in production. Here's how the config looks like:

```
System.config({
  "baseURL": "/app/src",
  "transpiler": "babel",
  "paths": {
    "*": "*.js",
    "github:*": "lib/github/*.js",
    "base": "infrastructure/base.js"
  }
});
```

My problem is that when I run a `jspm update`, my paths for **github** are automatically changed from `"github:*": "lib/github/*.js"` to `"github:*": "app\\src\\lib/github/*.js"`

I don't understand why is jspm prepending `app\\src\\lib`. Neither how to avoid this.

Here is the config.js file after running a ´jspm update´:
```
System.config({
  "baseURL": "/app/src",
  "transpiler": "babel",
  "paths": {
    "*": "*.js",
    "github:*": "app\\src\\lib/github/*.js",
    "base": "infrastructure/base.js"
  }
});
```

I've created [a repo](https://bitbucket.org/carlosagsmendes/jspm-packages/src/5d8afce65ce555299dca30acfcf4fa3a01c7c495?at=master) to demonstrate my issue.

Thanks in advance

**Comment by guybedford** [comment]
Use a `/` in the directories path - `baseURL: app/src/lib`.

Note that the packages folder is where the github folder is taken to be.

If you want to use the prompts to set these values try using `jspm init -p`.

**Comment by guybedford** [comment]
You probably just want to set:

```json
{
  "directories": {
    "baseURL": "app/src"
  }
}
```

**Comment by carlosagsmendes** [comment]
Thank you @guybedford.

I implemented your suggesting. It was not working by my fault... The problem was that I had my config.js in the app folder and it should be in the app/src folder.

Carlos
