### ISSUE TITLE
github archive as dependency

### ISSUE THREAD

**Issue by u9520107** [jspm/jspm-cli#627]
I tried to install engine.io-client vis jspm, in their dependencies list, there is this entry:
```
"xmlhttprequest": "https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz"
```
Upon hitting this entry, the installation will error out with the message:
```
err  No version match found for github:rase-/node-XMLHttpRequest@a6b6f2
```
Is this kind of behavior supported?

**Comment by guybedford** [comment]
The problem here isn't the support for github archives, but the fact that we don't support commit references.

**Comment by u9520107** [comment]
Ic... 
Currently, if I do engine.io-client=npm:engine.io-client, I see the error.
But if i do engine.io-client=github:Automattic/engine.io-client, then it installs fine.
I presume that it's due to the package.json having a "browser" property that specifies a different source  to the xmlhttprequest package dependency. 
Not sure why the "browser" override is respected when installing from github endpoint, but not when installing from npm endpoint.

**Comment by guybedford** [comment]
It's due to the fact that `jspm install github:rase-/node-XMLHttpRequest@a6b6f2` doesn't work because `a6b6f2` is a commit reference which is not supported.

On GitHub the dependency is not installed at all, because `dependencies` in the package.json on GitHub are not installed unless a registry is explicitly specified.

**Comment by lookfirst** [comment]
@guybedford case for the `@` and thrown an error to indicate that it isn't supported?

**Comment by guybedford** [comment]
@lookfirst good suggestion, I've created https://github.com/jspm/github/issues/41.
