### ISSUE TITLE
Linking into sub-dependencies

### ISSUE THREAD

**Issue by subesokun** [jspm/jspm-cli#629]
Currently it's only possible to link into the direct dependencies of an app but not into the sub-dependencies. As workaround I've helped myself so far via the trick

```javascript
jspm install --link endp:some/pkg@dev
jspm resolve --only endp:some/pkg@dev
```
to ensure that all sub-dependencies are consuming this linked package.

It would be great if this can be covered by the link command itself as this workaround has some ugly side-effects as creating a direct dependency on endp:some/pkg@dev even though this package gets only consumed by the sub packages and also `jspm install --unlink ...` won't work as excepted as it only unlinks the direct dependencies so you'll end up with forks in your config.

As I've no forks so far using the tick with `resolve --only` worked for me but if somebody needs to link into a fork (i.e. into a given version range) that might be problematic. Then a command like `jspm resolve endp:some/pkg@dev 1.2.* ` would be necessary.

**Comment by guybedford** [comment]
@subesokun this is why linking is designed to work into versions. If you link into a version that is semver compatible with the parent dependencies, then that version will be used.

**Comment by subesokun** [comment]
Probably this is an issue caused by the naming convention of my packages but it's quite tricky to link into a package that's getting called `pkg@1.2.3-build.123+sha.xyz` as the version number can change after every update. Also the package.json of `pkg` defines only the version 1.2.3 and running `jspm link` on that package will create a link for version 1.2.3 (what is actually good). But then when I link in this `1.2.3` package it won't replace the pre-release dependencies as theres no exact version match :(

**Comment by guybedford** [comment]
I'm not sure I follow. If you're saying that you have a dependency defined on `pkg@1.2.3-build.123+sha.xyz` then that is the version you should link into. If the dependency is on `pkg@1.2.3` then link installing that version will use that version within subdependencies. The best is to use a range like `~1.2.3`.

**Comment by subesokun** [comment]
Sorry I've to review my use-case again not that I'm asking some nonsense. I'll come back as soon as I've tested my use-case again.

**Comment by subesokun** [comment]
I had now some time to write a [small Gist](https://gist.github.com/subesokun/a634848adf62671b5255) which shows an exemplary linking workflow. I've used in this example Angular as a dependency as this package has the same naming convention as our internal packages. The map configuration looks in its initial state like the following (reduced):
```json
"map": {
  "pkg": "github:dummy/pkg-sub@1.0.0",
  "github:dummy/pkg-sub@1.0.0": {
    "angular": "github:angular/bower-angular@1.4.0-build.3980+sha.4d437ba"
  }
}
```
When using direct linking I'd need to link into the angular package like the following
```bash
jspm link github:angular/bower-angular@1.4.0-build.3980+sha.4d437ba
...
jspm install --link github:angular/bower-angular@1.4.0-build.3980+sha.4d437ba
```
But this is not really practicable in our development environment as the build number is frequently changing and hence it's complicated to link into exact version number.

Instead I'd need to link into a version range but it seems that's currently now working or I'm doing it the wrong way
```bash
# Link into the stable version to make linking easier for developers as they don't 
# have to know the exact build number as it changes often
jspm link github:angular/bower-angular@1.4.0
...
jspm install --link github:angular/bower-angular@~1.4.0
```
As a result I'd expect following map
```json
"map": {
  "pkg": "github:dummy/pkg-sub@1.0.0",
  "github:dummy/pkg-sub@1.0.0": {
    "angular": "github:angular/bower-angular@1.4.0"
  }
}
```
but this is the current result I get when running the example in the Gist
```json
"map": {
  "angular/bower-angular": "github:angular/bower-angular@1.4.0",
  "pkg": "github:dummy/pkg-sub@1.0.0",
  "github:dummy/pkg-sub@1.0.0": {
    "angular": "github:angular/bower-angular@1.4.0-build.3980+sha.4d437ba"
  }
}
```
To go one step further in order to better control what actually gets linked I'd need to define a linking rule like the following
```bash
# Use for all bower-angular@~1.4.0 deps the linked one bower-angular@1.4.1
jspm install --link github:angular/bower-angular@~1.4.0 github:angular/bower-angular@1.4.1
```
because it's not really clear into which version jspm would link when just running `jspm install --link github:angular/bower-angular@~1.4.0`.

Sorry for being difficult regarding the linking stuff :(

**Comment by guybedford** [comment]
So this is the currently recommended way to handle this, please let me know how that sounds for your workflow:

In `github:dummy/pkg-sub@1.0.0` am I right in thinking that you have authorship of this package?

Assuming you do, the dependency range in that package's package.json should be:

```json
{
  "dependencies": {
    "angular": "github:angular/bower-angular@^1.4.0-0"
  }
}
```

The above range will match the most recent stable version of angular followed by the prelease with the highest possible build number.

That means that when the only version available to the lookup is `github:angular/bower-angular@1.4.0-build.3980+sha.4d437ba`, then that will be installed.

But then as soon as you link in `github:angular/bower-angular@1.4.0` that will dominate the resolution and be used instead.

**Comment by subesokun** [comment]
Oh I see, yes these packages are under our control and normally we always use version ranges. Only for the Gist I've bound it to a fixed version to make it reproducible :( I think I understood now better how the link resolution works internally. When using the version range as mentioned by you it's working :) Thanks a lot! Now my map config looks like the following after linking
```json
"map": {
  "angular/bower-angular": "github:angular/bower-angular@1.4.0",
  "pkg": "github:dummy/pkg-sub@1.0.0",
  "github:dummy/pkg-sub@1.0.0": {
    "angular": "github:angular/bower-angular@1.4.0"
  }
}
```
It seems you're planing to work on a new linking workflow, maybe it would be possible to avoid adding this extra line `angular/bower-angular": "github:angular/bower-angular@1.4.0` when linking as it's not really necessary. It doesn't hurt but pollutes a bit the map configuration.
