### ISSUE TITLE
"jspm install" shouldn't modify the package.json by default

### ISSUE THREAD

**Issue by subesokun** [jspm/jspm-cli#631]
Not sure if this is a one time error as we had a greater version jump in jspm but we've some build/sync system that pulls several repos and performs `jspm install`on them. In case there are uncommited changes the sync process rejects pulling that repo and the sync fails.

Now in case you've a package.json generated with a never version of jspm and use an older version of jspm then you'll end up with uncommited local changes which is a bit hard to explain to the others as they expect that sync is not causing any local modifications on files that are under version control.

Would it be possible that `jspm install` avoids modifying the package.json if possible? In our case it would have been better that `jspm install` fails instead of modifying the package.json as this is harder to revert.

**Comment by guybedford** [comment]
Can you explain which package.json changes you're referring to? See also https://github.com/jspm/jspm-cli/issues/428.

**Comment by subesokun** [comment]
Thanks for pointer to issue #428 :) As it covers the same topic I'll close this one and post my comment on the other issue.

**Comment by sochka** [comment]
devDependencies still gets updated with the following:

`
+      "traceur": "github:jmcriffey/bower-traceur@0.0.87",
+      "traceur-runtime": "github:jmcriffey/bower-traceur-runtime@0.0.87"
`

**Comment by guybedford** [comment]
@sochka that is being tracked in https://github.com/jspm/jspm-cli/issues/637.
