### ISSUE TITLE
Use LibGit2 instead of depending on git being installed.

### ISSUE THREAD

**Issue by Zoltu** [jspm/jspm-cli#634]
Currently, jspm requires git to be installed and available in the path to work (correct me if I am wrong).  I recommend removing this external dependency that doesn't come in through NPM and instead leverage libgit2 via something like node-gitteh.  This way, jspm simply needs to depend on node-gitteh rather than the user having installed git and put it in their path.

**Comment by guybedford** [comment]
Thanks, yes this is very much on the roadmap, it's just something that needs to be worked out. I've noted your points on the issue at https://github.com/jspm/github/issues/25.
