### ISSUE TITLE
Cannot import module with dot its name

### ISSUE THREAD

**Issue by mindeavor** [jspm/jspm-cli#638]
I'm trying to use `import m from 'mithril.js'`, but jspm is not translating it. Instead I get the following error:

```
Failed to load resource: the server responded with a status of 404 (Not Found)
es6-module-loader.js:7 Potentially unhandled rejection [3] Error loading "mithril.js" at http://127.0.0.1:8080/mithril.js.js
Error loading "mithril.js" from "test" at http://127.0.0.1:8080/test.js
Not Found: http://127.0.0.1:8080/mithril.js.js (WARNING: non-Error used)
```

Here's how to reproduce:

```bash
$ jspm init # `yes` to all defaults
$ jspm install github:lhorie/mithril.js
$ echo 'import m from 'mithril.js'' > test.js
$ echo '<script src="jspm_packages/system.js"></script><script src="config.js"></script><script>System.import("test");</script>' > index.html
$ npm install -g live-server
$ live-server
```

**Comment by subesokun** [comment]
Did you try already `import m from 'github:lhorie/mithril.js'`? Alternatively you could do also a `jspm install mithril=github:lhorie/mithril.js` and then reference this alias via `import m from 'mithril'`.

Also please be warned that mithril exports the `m` object globally so that you actually just have to do a `import 'mithril'`.

**Comment by guybedford** [comment]
Package names with `.js` are supported fine. It is worth ensuring you have installed `mithril` properly though, try using as @subesokun suggests:

```
  jspm install mithril.js=github:lhorie/mithril.js
```

If you just did `jspm install github:lhorie/mithril.js`, then you need to do:

```javascript
import mithril from 'lhorie/mithril.js';
```

**Comment by mindeavor** [comment]
Thanks, it worked! Is this in the documentation somewhere, or does someone need to add it?

Also, since I did in fact install it using `jspm install github:lhorie/mithril.js`, how would I create the alias accomplished by `jspm install mithril.js=github:lhorie/mithril.js` (without uninstalling/reinstalling) ?

**Comment by frankwallis** [comment]
You can just edit the entries directly in package.json dependencies and config.js map.

**Comment by guybedford** [comment]
Effectively you do need to uninstall and reinstall, or just alter the files yourself. A re-aliasing method could certainly be useful though.

**Comment by mindeavor** [comment]
Thank you. I'm leaving this open until someone gets time to put this in [the docs](https://github.com/jspm/jspm-cli/wiki/Installing-Packages#requiring-packages) (might be me but I'm not sure when).
