### ISSUE TITLE
Can't import alpacajs component

### ISSUE THREAD

**Issue by zmmail** [jspm/jspm-cli#641]
My operations are following:
1.jspm install import gitana/alpaca
2.put "import alpaca from 'gitana/alpaca';" in tables_dynamic.js
3.put these in index.html
    <script src="../../jspm/jspm_packages/es6-module-loader.js"></script>
    <script src="../../jspm/jspm_packages/system.js"></script>
    <script src="../../jspm/config.js"></script>
    <script>
        System.import('html-transparent/dist/js/tables_dynamic');
    </script>

Load index.html, I got the error in Chrome.

Potentially unhandled rejection [2] Error: Error loading "github:gitana/alpaca@1.5.8" at http://localhost:8000/jspm/jspm_packages/github/gitana/alpaca@1.5.8.js
Error loading "github:gitana/alpaca@1.5.8" from "html-transparent/dist/js/tables_dynamic" at http://localhost:8000/html-transparent/dist/js/tables_dynamic.js
Unable to load dependency github:gitana/alpaca@1.5.8/dist/alpaca/bootstrap/alpaca.
    at c (http://localhost:8000/jspm/jspm_packages/system.js:1:5606)
    at http://localhost:8000/jspm/jspm_packages/system.js:1:6021
    at $__global.upgradeSystemLoader.c.execute (http://localhost:8000/jspm/jspm_packages/system.js:1:13947)
    at f (http://localhost:8000/jspm/jspm_packages/system.js:1:5936)
    at l (http://localhost:8000/jspm/jspm_packages/system.js:1:4563)
    at Object.$__global.upgradeSystemLoader.e.instantiate.Promise.all.then.execute (http://localhost:8000/jspm/jspm_packages/system.js:1:8149)
    at o (http://localhost:8000/jspm/jspm_packages/es6-module-loader.js:7:18488)
    at p (http://localhost:8000/jspm/jspm_packages/es6-module-loader.js:7:18860)
    at j (http://localhost:8000/jspm/jspm_packages/es6-module-loader.js:7:16406)
    at k (http://localhost:8000/jspm/jspm_packages/es6-module-loader.js:7:16791)es6-module-loader.src.js:140 (anonymous function)

**Comment by guybedford** [comment]
Unfortunately it's using a named define - so it's not AMD-compatible https://github.com/gitana/alpaca/blob/1.5.8/dist/alpaca/bootstrap/alpaca.js#L17.

I'd suggest looking at how to shim libraries with jspm. Basically you want to do `jspm install github:gitana/alpaca -o "{format: 'global'}"`. You will hit other issues as jQuery etc are expected as dependencies, so use shim dependencies for this. You can read https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm#shim-configuration and use sources like https://github.com/jspm/registry/blob/master/package-overrides/github/twbs/bootstrap%403.3.4.json as an example here.

If you're still having issues, please post an issue directly to the jspm registry at https://github.com/jspm/registry/issues, as this is where we track assistance with these configurations.

**Comment by zmmail** [comment]
Thanks for your details. I'll try it.

**Comment by lookfirst** [comment]
@guybedford Does it make sense to submit a pull request to alpaca to remove the named define? https://github.com/gitana/alpaca/blob/master/config/umd-wrapper.txt

**Comment by guybedford** [comment]
I doubt they'd change their AMD layer at this point. Unfortunately this is a common issue, and part of the fun of figuring out the right override format to use.

**Comment by rhettl** [comment]
This fix is also what I had to do with [twitter/typeahead.js](/twitter/typeahead.js)@0.11.1. 
I looked for a fix for 5 days and finally found this posting. 
Is there a place where this is documented?
