### ISSUE TITLE
../ and ./ in file aliases causes bundled JS to load files separately

### ISSUE THREAD

**Issue by markj-** [jspm/jspm-cli#645]
Hi,

I'm having some difficulties achieving the project structure I desire with both the unbundled and bundled code. When I bundle I'm seeing the shared/module.js file being loaded separately in the browser (even though it is part of bundle.js) which causes an error.

```
markj at Marks-MBP in ~/Playground/jspm-test/application1
$ jspm bundle app/main --inject

Building the bundle tree for app/main...

       ../shared/module
       app/main

ok   build added to config bundles.
ok   Built into build.js with source maps, unminified.
```

The error in the browser:

```
GET http://0.0.0.0:8000/application1/shared/module.js 404 (File not found)
es6-module-loader.src.js:140 Potentially unhandled rejection [3] Error loading "shared/module" at http://0.0.0.0:8000/application1/shared/module.js
Error loading "shared/module" from "app/main" at http://0.0.0.0:8000/application1/app/main.js
File not found: http://0.0.0.0:8000/application1/shared/module.js (WARNING: non-Error used)
```

### Directory structure

* __application1__
  *  __app__
    * main.js
  * __jspm_packages__
  * config.js
  * index.html
  * package.json
* __shared__
  * module.js

### application1/config.js

```javascript
System.config({
  "transpiler": "babel",
  "babelOptions": {
    "optional": [
      "runtime"
    ]
  },
  "paths": {
    "*": "*.js",
    "github:*": "jspm_packages/github/*.js",
    "npm:*": "jspm_packages/npm/*.js"
  }
});

System.config({
  "map": {
    "babel": "npm:babel@4.7.16",
    "babel-runtime": "npm:babel-runtime@4.7.16",
    "sharedModule": "../shared/module",
    "github:jspm/nodelibs-process@0.1.1": {
      "process": "npm:process@0.10.1"
    },
    "npm:babel-runtime@4.7.16": {
      "process": "github:jspm/nodelibs-process@0.1.1"
    }
  }
});
```

### application1/index.html

```
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>

  <script src="jspm_packages/system.js"></script>
  <script src="config.js"></script>
  <script>
    System.import('app/main');
  </script>
</body>
</html>
```

### application1/app/main.js

```javascript
define([
  'sharedModule'
], function() {
  console.log('main module loaded')
});
```

### shared/module.js

```javascript
define(function() {
  console.log('shared module loaded');
});
```

### application1/package.json

```JSON
{
  "jspm": {
    "configFile": "config.js",
    "devDependencies": {
      "babel": "npm:babel@^4.7.16",
      "babel-runtime": "npm:babel-runtime@^4.7.16"
    }
  }
}
```

As a work around, I've noticed that by aliasing 'shared' as '../shared', then loading the shared module using 'shared/module' in main.js this does work. I don't understand why this is the case however. I've also seen this issue happen when aliasing files using ./ although there is little reason to do this.

e.g. "myComponent": "./app/components/my-component"

Thank you!

**Comment by guybedford** [comment]
The issue here is that paths can't dip below the baseURL. Set the baseURL to be lower down to contain all your paths and things should work.

**Comment by markj-** [comment]
Thanks for coming back to me so quickly! I had considered that this might be the issue. I'm porting over a requirejs application which is configured in this way and was hoping to be able to port the config nearly word for word.

If I use bundle-sfx this config does work. I assume this is because of the different module loader that comes bundled with my scripts? Would it be safe for me to rely on this?

The workaround I mentioned does not work if the module that has shared/module as a dependency came from a nested folder, but if I'm using the baseURL incorrectly then this will no doubt be the issue here too. It's no doubt been the cause of the majority of strange behaviour I've seen.

**Comment by markj-** [comment]
I've had further issues even using bundle-sfx, I'll do as you said :) Closing this as it is user error.
