### ISSUE TITLE
Using `node-semver`

### ISSUE THREAD

**Issue by longlho** [jspm/jspm-cli#647]
Hello,

Any reason why you guys don't use `node-semver`? Since this package supports `npm` packages as well it's failing on parsing some version syntax that `node-semver` handles (`1.x`, `1.0 - 2.0`...), but not the local one.

I'm happy to put in the PR for the transition too if you guys agree.

Thanks!

**Comment by guybedford** [comment]
Thanks for posting, sorry for the delay here.

It is a range that only really makes practical sense for peer dependencies though, so when we add peer dependency support to jspm, we should make sure it is possible to install out-of-range and that should resolve this.

Closing, as I've yet to hear a strong argument specifically to support a range like that for non-peerDependency scenarios.
