### ISSUE TITLE
Any ETA for a local: endpoint

### ISSUE THREAD

**Issue by gmosx** [jspm/jspm-cli#649]
I would like split my application into multiple packages. While developing I would like to work on all the packages at the same time, without having to upload my 'library' packages to github/npm all the time? Is there a way to support sym-linking of packages?

**Comment by guybedford** [comment]
I'd suggest looking into the linking workflows here - https://github.com/jspm/jspm-cli/wiki/Linking.

Link doesn't do direct symlinks due to architectural constraints currently, so you ideally want to set up a watcher that relinks packages on changes. This will be changing in future though.

Alternatively you can always set up your own symlinks.

**Comment by gmosx** [comment]
Thanks. Any info about how to manually 'set up my own symlinks'?

On Sun, Apr 5, 2015 at 2:53 PM, Guy Bedford <notifications@github.com>
wrote:

> I'd suggest looking into the linking workflows here -
> https://github.com/jspm/jspm-cli/wiki/Linking.
>
> Link doesn't do direct symlinks due to architectural constraints
> currently, so you ideally want to set up a watcher that relinks packages on
> changes. This will be changing in future though.
>
> Alternatively you can always set up your own symlinks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jspm/jspm-cli/issues/649#issuecomment-89756723>.
>



-- 
http://www.gmosx.com

**Comment by tauren** [comment]
@gmosx I would avoid manually creating symlinks and instead use jspm linking. It is analogous to `npm link`, but a bit more complex because jspm has to process the source, not just link to it.

I just reported some issues that are causing me problems with jspm linking. If you are running into troubles, you might be having the same problem. See #655 and #656.

**Comment by gmosx** [comment]
Still find it amazing that such an obvious feature (e.g. depend on local
packages) is so difficult to implement.
While developing I might make changes to 3-4 packages at the same time,
doesn't feel good having to re-link all the time.
Just a 'file:///..' ref seems like a no-brainer to me.

On Thu, Apr 9, 2015 at 7:27 AM, Tauren Mills <notifications@github.com>
wrote:

> @gmosx <https://github.com/gmosx> I would avoid manually creating
> symlinks and instead use jspm linking. It is analogous to npm link, but a
> bit more complex because jspm has to process the source, not just link to
> it.
>
> I just reported some issues that are causing me problems with jspm
> linking. If you are running into troubles, you might be having the same
> problem. See #655 <https://github.com/jspm/jspm-cli/issues/655> and #656
> <https://github.com/jspm/jspm-cli/issues/656>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jspm/jspm-cli/issues/649#issuecomment-91112399>.
>



-- 
http://www.gmosx.com

**Comment by guybedford** [comment]
@gmosx avoiding the relinking is a big architectural shift that we're actively working on enabling, but it will take a little time unfortunately.

**Comment by gmosx** [comment]
Thanks, will wait then ;-)

On Thu, Apr 9, 2015 at 11:37 AM, Guy Bedford <notifications@github.com>
wrote:

> @gmosx <https://github.com/gmosx> avoiding the relinking is a big
> architectural shift that we're actively working on enabling, but it will
> take a little time unfortunately.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jspm/jspm-cli/issues/649#issuecomment-91150976>.
>



-- 
http://www.gmosx.com

**Comment by NervosaX** [comment]
I've started a little project to try and aid myself in keeping the links up to date. Not sure if it's a good way to do it, but it seems to work. I'm worried about watching too many files on OSX, though, which seems to have a very low limit on watching multiple files.

https://github.com/NervosaX/jspm-linker

Has very very basic functionality.

**Comment by guybedford** [comment]
@NervosaX nice! That could be useful, feel free to add it to the projects wiki at https://github.com/jspm/jspm-cli/wiki/Community-Projects if you want to share further.

**Comment by NervosaX** [comment]
@guybedford I've updated the wiki. Happy for it to be reformatted if it doesn't fit the page for some reason.
