### ISSUE TITLE
Loading a script without a .js extension

### ISSUE THREAD

**Issue by orand** [jspm/jspm-cli#650]
Does jspm have support for loading scripts that don't contain a .js file extension?  I have a dynamically generated script I'd like to do this with.  RequireJS supports this with its [noext plugin](https://github.com/millermedeiros/requirejs-plugins).

**Comment by guybedford** [comment]
You can specify paths that shouldn't add extensions like:

```javascript
System.config({ 
  paths: {
    'app/*': 'app/*'
  }
});
```

And then a `.js` extension won't be added.

**Comment by orand** [comment]
I wasn't expecting it to be that simple.  Thought I'd have to write a plugin.  I just tested and that worked great, thank you!

For others that come across this, you don't have to specify a `*` in the path, you can do exact path matches if desired.
