### ISSUE TITLE
How to customize paths properly in config.js?

### ISSUE THREAD

**Issue by nightire** [jspm/jspm-cli#651]
I've managed to integrate jspm in an existing project like this:

```text
├── package.json
├── gulpfile.js
├── jspm_packages
│   ├── github
│   ├── npm
│   ├── system.js
│   └── (more...)
├── node_modules
│   ├── browser-sync
│   ├── gulp
│   └── (more...)
├── public
│   ├── config.js
│   └── index.html
└── source
    └── (more js/css/...)
```

Couple of things should be clear at first:

1. we use BrowserSync to provide local http server for development, but we don't host app from project root, instead we host if from `public`.
2. in order to reference `config.js`, we set `"baseURL": "public"` in `package.json`.
3. put `jspm_packages` in `public` is not allowed, we have to put it in the project root for many reasons.
4. thus we can't reference any file from `jspm_packages` directly in `index.html`, but luckly BrowserSync can help us to route `"/vendor": "jspm_packages"` so that we can use `src="vendor/system.js"` to reference what we need; we also route `"/source": "source"` as well for other files.
5. since we host the app from `public`, so `"baseURL": "/"` in `config.js` works fine.

So far so good, now the problem:

jspm define `paths` like below:

```json
"paths": {
  "*": "*.js",
  "github:*": "../jspm_packages/github/*.js",
  "npm:*": "../jspm_package/npm/*.js"
}
```

these are resonable when host app from project root, but is doesn't work with our configurations, we have to change it like this:

```json
"paths": {
  "*": "source/*.js",
  "github:*": "vendor/github/*.js",
  "npm:*": "vendor/npm/*.js"
}
```

now, it works like a charm! But wait...

Every time we install/update a package using jspm, for example: `jspm install npm:lodash`, jspm will rewrite the paths to this:

```json
"paths": {
  "*": "source/*.js",
  "github:*": "../jspm_packages/github/*.js",
  "npm:*": "../jspm_packages/npm/*.js"
}
```

we have to change it back manually time after time, that's a terrible thing.

Is there a way to fix the paths configuration or is there a better way to solve our problem like this?

**Comment by guybedford** [comment]
If you want to move the jspm packages folder try setting `directories.packages: '../jspm_packages'`.

**Comment by lookfirst** [comment]
Or do what I do, proxy jspm_packages to /jspm_packages instead of adding the vendor prefix. You don't need that. This is my browserSync proxy config: https://github.com/lookfirst/systemjs-seed/blob/master/gulpfile.js#L43

**Comment by nightire** [comment]
@lookfirst the real problem is not about the folder name, its the relative path that config.js maintained for us. In our case, even we proxy jspm_packages as itself, config.js still change the path to something like: `../jspm_packages/...`, this will break the proxy rule unless browsersync can map `"../jspm_packages": "jspm_packages"` which i'm not sure...I will try it later.

**Comment by nightire** [comment]
@guybedford it didn't work, as we run jspm under the project root, this will create the `jspm_packages` folder one level out of the project root.

**Comment by lookfirst** [comment]
@nightire Look closely at my config, it works great.

**Comment by nightire** [comment]
@lookfirst I've already read your config. try to move your `system.config.js` to your `path.output`, then try to install/update something using jspm, then see what you got. your solution works well **ONLY** when `config.js` and `jspm_packages` at the same level.

**Comment by lookfirst** [comment]
Actually, I previously sent `system.config.js` to the `path.output` from the `path.src`, but moved it to the top level to make things more clear and because I realized I didn't need to move that file around cause I could just proxy it.

**Comment by nightire** [comment]
@lookfirst You're absolutely right, I personally will put `config.js` in the root level for same reasons. In this case, for some historical restrictions, we have to put this under `path.output`, it turns out can't work as we expected so far, sad.

After some discussion and deep thoughts, I decide to convince the team to change the architecture to make things easier. Thanks for all suggestions and helps, I'm going to close this issue for now.

**Comment by lookfirst** [comment]
@nightire Cool... yea... I think the big motivation was that it simplified my gulpfile cause I didn't have to touch that file now. In `production` mode, that file shouldn't even be needed, so it is really only a development issue and in that case, keeping it at the root level really is the simplest all around. =)

**Comment by guybedford** [comment]
@nightire thanks for posting - it sounds like the issue here is that you effectively have a different jspm_packages folder between client and server. Handling this mapping on the server like @lookfirst says does sound preferable to changing configuration.

**Comment by sbaechler** [comment]
I had the same issue and solved it by creating a symlink for the jspm_packages folder so the path matches the path on the server.

Is there a reason why the paths object keeps getting changed on install?
