### ISSUE TITLE
Is all the information in config.js required on the client-side?

### ISSUE THREAD

**Issue by glen-84** [jspm/jspm-cli#652]
I've installed just 3 packages, and my config.js file is already 68 KB (!).

It seems like a lot of this information isn't required on the client-side. For example, this is the info for semantic-ui:

    "npm:semantic-ui@1.11.6": {
      "better-console": "npm:better-console@0.2.4",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "del": "npm:del@1.1.1",
      "extend": "npm:extend@2.0.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "gulp": "npm:gulp@3.8.11",
      "gulp-autoprefixer": "npm:gulp-autoprefixer@2.1.0",
      "gulp-chmod": "npm:gulp-chmod@1.2.0",
      "gulp-clone": "npm:gulp-clone@1.0.0",
      "gulp-concat": "npm:gulp-concat@2.5.2",
      "gulp-concat-css": "npm:gulp-concat-css@2.2.0",
      "gulp-copy": "npm:gulp-copy@0.0.2",
      "gulp-flatten": "npm:gulp-flatten@0.0.4",
      "gulp-header": "npm:gulp-header@1.2.2",
      "gulp-help": "npm:gulp-help@1.3.4",
      "gulp-if": "npm:gulp-if@1.2.5",
      "gulp-less": "npm:gulp-less@3.0.2",
      "gulp-minify-css": "npm:gulp-minify-css@0.5.1",
      "gulp-notify": "npm:gulp-notify@2.2.0",
      "gulp-plumber": "npm:gulp-plumber@0.6.6",
      "gulp-print": "npm:gulp-print@1.1.0",
      "gulp-rename": "npm:gulp-rename@1.2.2",
      "gulp-replace": "npm:gulp-replace@0.5.3",
      "gulp-rtlcss": "npm:gulp-rtlcss@0.1.4",
      "gulp-uglify": "npm:gulp-uglify@1.1.0",
      "gulp-util": "npm:gulp-util@3.0.4",
      "gulp-watch": "npm:gulp-watch@4.2.3",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.1",
      "require-dot-file": "npm:require-dot-file@0.4.0",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0",
      "wrench": "github:derekslife/wrench-js@master"
    },

I'm pretty sure that Gulp stuff is not required on the client-side. If it's required on the server-side, would it be possible to split config.js into two files, config.client.js and config.server.js?

See also: http://stackoverflow.com/questions/28889066/how-to-avoid-adding-the-dependencies-to-config-js-when-installing-jspm-plugins (not my question)

**Comment by guybedford** [comment]
When bundling, you don't need to include the configuration in production.

Methods for building configuration in HTTP/2 scenarios will be developed.

**Comment by poshaughnessy** [comment]
Having just received this advice myself (thanks [Jack Franklin](https://github.com/jackfranklin)!) I wouldn't use JSPM for modules you only want to use on the server-side like Gulp. You can just continue to use NPM directly for that.

I wrote some more here: http://stackoverflow.com/a/29643898/396246

**Comment by glen-84** [comment]
I changed from using NPM to using GitHub for Semantic UI, and my config file went from 68 KB to 6 KB.

SUI uses a bunch of packages for its installer, so all of that information was added to the config file.

Regardless, there is still unnecessary data in this file, and with HTTP/2 coming soon, it would be nice to have a solution for this in the not too distant future.

Do you want to keep this issue open to track that work, or will you open a new issue?

**Comment by guybedford** [comment]
@glen-84 this is mostly about the specifics of Semantic UI - ie what are the benefits of the npm version over the GitHub. If it is worth using the npm version intead, we can potentially look at the necessary override configuration to remove the unnecessary dependency loads.

**Comment by glen-84** [comment]
One difference between the two is that NPM runs a post-install script – how does JSPM handle NPM scripts?

If scripts will be supported at some stage, the dependencies would be required, although obviously still not required in the config.js file.

Is it currently possible to override NPM dependencies?

**Comment by guybedford** [comment]
npm scripts are not currently supported.

Yes overrides work equally well for the npm registry. Overrides always act just as if the properties had been in the original package.json itself.
