### ISSUE TITLE
Linking doesn't seem to honor ignore property

### ISSUE THREAD

**Issue by tauren** [jspm/jspm-cli#656]
When I run `jspm link`, everything is getting copied except for the node_modules folder. I have a git submodule and the entire thing, including its node_modules are being copied. This is causing the link step to take a long time.

I tried to follow the advice that the command spits out when it takes too long, and add an `ignore` property to package.json, but it doesn't seem to be picking it up:

```
  "jspm": {
    "ignore": [
      "decks",
      "docs",
      "config",
      "xls",
      "schemas"
    ]
  }
```

All of those folders are still being copied. Is this a bug, or am I not using the ignore feature correctly? I've tried putting it in the root of the package.json instead of within `jspm` as well.

**Comment by guybedford** [comment]
Yes this is a known issue and is being tracked at https://github.com/jspm/jspm-cli/issues/345.

**Comment by crisptrutski** [comment]
@guybedford worthwhile picking up ignores from `.npmignore` file also, if it exists?

**Comment by guybedford** [comment]
Yes definitely. Also created https://github.com/jspm/npm/issues/56#.

**Comment by guybedford** [comment]
Closing as a duplicate.
