### ISSUE TITLE
filterIgnoreAndFiles is broken

### ISSUE THREAD

**Issue by tauren** [jspm/jspm-cli#657]
Adding a `jspm.ignore` property in `package.json` causes `jspm install` to fail.

```
     Downloading npm:nid-chef-spices@0.0.8
err  TypeError: undefined is not a function
         at /Users/tmil11/stash/nid/chef/node_modules/jspm/lib/build.js:114:28
         at Array.forEach (native)
         at /Users/tmil11/stash/nid/chef/node_modules/jspm/lib/build.js:99:14
         at lib$rsvp$$internal$$tryCatch (/Users/tmil11/stash/nid/chef/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:489:16)
         at lib$rsvp$$internal$$invokeCallback (/Users/tmil11/stash/nid/chef/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:501:17)
         at lib$rsvp$$internal$$publish (/Users/tmil11/stash/nid/chef/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:472:11)
         at lib$rsvp$asap$$flush (/Users/tmil11/stash/nid/chef/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:1290:9)
         at process._tickCallback (node.js:355:11)
```

I added a console.log to line 114 of build.js to see the content of the `ignore` variable:

```
ignore: { '0': 'decks',
  '1': 'docs',
  '2': 'config',
  '3': 'xls',
  '4': 'schemas' }
```

This object doesn't contain the function `some` that it appears it needs to in line 114. It looks like it is expected to be an array, but it is an object with numerical indexes as keys.

```
      if (ignore && ignore.some(function(ignoreFile) {
```

**Comment by guybedford** [comment]
Thanks for posting - this should be a better failure ideally. The `ignore` property should be an array and not an object though. Is it definitely an array in the package.json file itself?

**Comment by tauren** [comment]
Yes, it is an array of strings in package.json. See #656 for an example of what is in my package.json.

**Comment by guybedford** [comment]
@tauren I just tried installing an npm repo with an `jspm.ignore` array set and haven't been able to replicate this at all. Can you perhaps share an example repo directly to help get a replication case?

**Comment by tauren** [comment]
I'll try to find some time to create an example in the next few days. Thanks for working on it!

**Comment by cbas** [comment]
@guybedford I'm seeing this problem with my NPM package: https://github.com/migme/beachball

```
C:\Users\seb\Dev\migme\beachball>jspm link npm:migme

warn It's taking a long time to process the dependencies of npm:migme@0.2.2.
     This package may need an ignore property to indicate test or example folders for jspm to skip.

ok   Package linked as npm:migme@0.2.2
```

`package.json`
```json
{
  "name": "migme",
  "version": "0.2.2",
  "description": "Migme JavaScript SDK.",
  "main": "src/migme.js",
  "scripts": {
    "test": "standard && grunt test"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/migme/beachball.git"
  },
  "keywords": [
    "migme",
    "sdk"
  ],
  "author": "Migme (https://mig.me)",
  "contributors": [
    "Ed Moore <eddie.moore@gmail.com>",
    "Sebastiaan Deckers <seb@ninja.sg>"
  ],
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/migme/beachball/issues"
  },
  "homepage": "https://github.com/migme/beachball",
  "devDependencies": {
    "babel-core": "^4.7.16",
    "babelify": "^5.0.4",
    "chai": "^2.1.2",
    "grunt": "^0.4.5",
    "grunt-babel": "^4.0.0",
    "grunt-contrib-clean": "^0.6.0",
    "grunt-contrib-concat": "^0.5.1",
    "grunt-contrib-uglify": "^0.8.0",
    "grunt-karma": "^0.10.1",
    "isparta": "^2.2.0",
    "karma": "^0.12.31",
    "karma-babel-preprocessor": "^4.0.1",
    "karma-browserify": "^4.0.0",
    "karma-chai": "^0.1.0",
    "karma-chrome-launcher": "^0.1.7",
    "karma-coverage": "git://github.com/douglasduteil/karma-coverage#next",
    "karma-mocha": "^0.1.10",
    "karma-phantomjs-launcher": "^0.1.4",
    "karma-sinon-chai": "^0.3.0",
    "karma-spec-reporter": "0.0.16",
    "load-grunt-tasks": "^3.1.0",
    "mocha": "^2.2.1",
    "standard": "^3.3.2",
    "time-grunt": "^1.1.0",
    "whatwg-fetch": "^0.7.0"
  },
  "standard": {
    "ignore": [
      "dist/**"
    ]
  },
  "dependencies": {
    "localforage": "^1.2.2",
    "uri-template-lite": "^0.1.11"
  },
  "directories": {
    "lib": "src",
    "test": "test"
  },
  "format": "es6",
  "ignore": [
    "node_modules",
    "coverage",
    "test"
  ]
}
```

```
C:\Users\seb\Dev\migme\beachball>jspm --version
0.15.3
Running against global jspm install.

C:\Users\seb\Dev\migme\beachball>node --version
v0.12.2
```

Windows 8.1

**Comment by cbas** [comment]
Ah! Found a solution thanks to @devmondo in the Gitter chatroom. :+1: 
Had to namespace the JSPM properties in my NPM module's `package.json` file. See referenced commit for details.

**Comment by guybedford** [comment]
@cbas your issue here was actually that on npm, `directories.lib` is ignored unless it is inside a `jspm` property.

**Comment by cbas** [comment]
@guybedford Thanks for the reply! Why is it ignored? As a new user I looked in the JSPM docs and didn't see that mentioned. I also looked at the package.json docs and saw that it was a standard property. The way `jspm` namespacing is documented also made it sound like it was 100% the same. Just wanted to share that feedback. (I'd help update the docs if I actually understood how things work. Might do a blog post or tutorial instead.) Very grateful for the work you're doing! :bow:

**Comment by guybedford** [comment]
It's ignored because we need to maintain full backwards-compatibility with the contract npm makes with users. The docs will be revamped as soon as the API is stable (hopefully in the coming couple of months). Help sharing knowledge in the mean time is greatly appreciated.
