### ISSUE TITLE
Default exports not used.

### ISSUE THREAD

**Issue by calebboyd** [jspm/jspm-cli#661]
It seems that the default export isn't passed when the following configuration is used: (jspm-cli 0.15.3)

- `jspm init` -> select babel
- `jspm install npm:bluebird`
- Add `"bluebirdCoroutines"` along with `"runtime"` for babelOptions

Attempting to load a class definition with an `async` instance method will now result in an error as the bluebird export is wrapped with `default` getters/setters where babel does not seem to expect that, it is still attempting to access `.coroutine` which is undefined.

This issue might also not belong in this repo...

**Comment by guybedford** [comment]
Thanks, it was difficult to tell which repo the issue was with, but I've posted https://github.com/babel/babel/issues/1219.

**Comment by guybedford** [comment]
This has been patched in Babel now.
