### ISSUE TITLE
Trying to run zombie headless browser

### ISSUE THREAD

**Issue by justgeek** [jspm/jspm-cli#662]
First of all i wanna that you very much for the awesome library , then i wanna clarify my issue , im trying to run zombie.js headless browser inside my browser ( to scrap some website and inject scripts ) , the headless browser works flawlessly running from cmd , however i tried using jspm to run it from browser , here is what i have did :

1 - install jspm
2 - init jspm
3 - install zombie from npm

as far everything seems ok , and all dependencies are added to config.js file
im using the simple example script .

in index.html :
<!doctype html>
  <script src="jspm_packages/system.js"></script>
  <script src="config.js"></script>
  <script>
    System.import('lib/main');
  </script>

and lib/main.js :
var browser = require("zombie");
b = new browser();
b.visit("http://www.google.com/", function (err, browser) {
  if (err) { console.log('Error:' + err.message); }
  else {
 //Initialize a new jQuery instance with the current window returned by Zombie

  //Get an actual jQuery object so we can search for stuff
  
   console.log(b.window.document.title) 

}
  // ... rest of your code here
});

This is supposed to Log : Google .

but i get errors that cannot load core-js : 
"Potentially unhandled rejection [3] Error loading "core-js/library" at http://169.254.80.80/core-js/library.js
Error loading "core-js/library" from "lib/main" at http://169.254.80.80/lib/main.js
Object Not Found: http://169.254.80.80/core-js/library.js (WARNING: non-Error used)"

http://169.254.80.80 is my local server.
any help is appreciated

**Comment by guybedford** [comment]
I was struggling to work out exactly how you installed zombie.

I tried running `jspm install zombie` but its not in the registry. Could you perhaps clarify the steps a little more carefully?

**Comment by justgeek** [comment]
thanks for quick reply , zombie can be found on npm registry so this should work :
jspm install zombie=npm:zombie 

later can be required :

var browser=require('zombie');

**Comment by guybedford** [comment]
I think you'll find the issue you're posting above is that you are writing ES6 through Babel, which requires core-js to be installed. You can get this to be installed by running `jspm dl-loader`.

Getting Zombie itself to run isn't working for me either though, I'm getting the issue here - https://github.com/jspm/registry/issues/326.

This will take some looking into to fix via an override, but should be possible.

**Comment by justgeek** [comment]
but when i first initiated jspm i picked traceur , also the required files can be found inside jspm/node_modules/jspm/node_modules/core-js , so i thought i might be having wrong registery.

**Comment by guybedford** [comment]
The issue is definitely completely separate to loading Zombie though.

**Comment by justgeek** [comment]
ok but still after excuting jspm dl-loader , still having same error , i still dont get what the problem is , and yes the problem is that zombie is simply not working .

**Comment by guybedford** [comment]
@justgeek are you able to run any code at all through jspm?

**Comment by guybedford** [comment]
Also are you using ES6 and CommonJS together perhaps?

**Comment by justgeek** [comment]
@guybedford actually this is my first to use jspm , and my first trial was zombie , i dont think im using CommonJS , because it was never installed as a standalone module , but maybe any module is instaling it as dependency , is there anyway to check out ?

**Comment by justgeek** [comment]
@guybedford digging inside zombie folders , i have found the "babel-runtime" folder does this relate to  initiating jspm with traceur ?

**Comment by guybedford** [comment]
Which folder did you find it in?

**Comment by justgeek** [comment]
Check this : 
![screenshot](https://cloud.githubusercontent.com/assets/2090555/7087918/41847d70-df90-11e4-9047-a59ec6dd39b6.png)

**Comment by guybedford** [comment]
That looks like you've installed Zombie with npm here. It is actually probably preferable to use Browserify and npm for Zombie here since it's not working in jspm out of the box.

**Comment by justgeek** [comment]
@guybedford unfortunately i have tried browserify before trying jspm , failed with some issues , but i have not tried to solve em , as jspm seemed more promising though it has been less starred on github , but i love the way it works , also believe it or not the produced bundle.js produced by browserify was 4 MBs , how can this be good for production ?! all this was disencouraging to continue using browserify and debug issues , but if you are saying there is no way but using browserify , i guess i will get back to there , are you saying there is no hope to run zombie with jspm ?

**Comment by guybedford** [comment]
Unfortunately support for a library like Zombie won't work in jspm for a little while yet.
