### ISSUE TITLE
jspm dependency of a package is downloaded, but not mapped properly in config.js

### ISSUE THREAD

**Issue by capaj** [jspm/jspm-cli#663]
So in my package I have jspm dependency defined in package.json like this:
https://github.com/capaj/socket.io-rpc-client/blob/master/package.json#L26

Now when I install that package by running `jspm install socket.io-rpc-client`, bluebird is installed in my jspm_packages and I get this in my config.json:
```
"github:capaj/socket.io-rpc-client@0.8.12": {
      "bluebird": "npm:bluebird@2.9.24"
    },
```

But when running it, my
`require('bluebird')` fails.
Is this expected behaviour?
I would expect it to work, when JSPM goes into the trouble of downloading the library, why would it not add a mapping from `"bluebird": "npm:bluebird@2.9.24"` ?

**Comment by guybedford** [comment]
I just ran:

```
  jspm install socket.io-rpc-client
  jspm run socet.io-rpc-client
```

And get the error:

```

err  Error: Error loading "dom-storage" at file:/Users/guybedford/Projects/jspm-cli/sandbox/dom-storage.js
     Error loading "dom-storage" from "github:capaj/socket.io-rpc-client@0.8.12" at file:/Users/guybedford/Projects/jspm-cli/sandbox/jspm_packages/github/capaj/socket.io-rpc-client@0.8.12.js
     ENOENT, open '/Users/guybedford/Projects/jspm-cli/sandbox/dom-storage.js'
         at Error (native)
```

That is, Bluebird is being found fine, but the other dependencies aren't being mapped properly.

Since you're writing the package with npm dependencies, perhaps you want to just set:

```
"dependencies": {
    "socket.io-client": "npm:socket.io-client@^1",
    "bluebird": "npm:bluebird@^2",
    "dom-storage": "npm:dom-storage@^2.0.1"
}
```

**Comment by guybedford** [comment]
Also if you're publishing this to npm, and writing fully in the npm conventions, is there a reason you aren't installing the package from npm?
