### ISSUE TITLE
Support strict-ssl false global configuration option

### ISSUE THREAD

**Issue by admwx7** [jspm/jspm-cli#672]
Currently I'm having an issue with self signed certs blocking fetching external packages, the only solution I can find involves setting the http_proxy environment variable, which isn't an option for me unfortunately.  Looking around I can't find any references to what parameters I can pass to `jspm config` I'm hoping for being able to set strict-ssl=false, since that's the work around I'm having to use for npm, as such `jspm config strict-ssl false` does not work.

What would be ideal is a .jspmrc file that I could include in my repo and set strict-ssl in that file to remove this step for all of the developers on the project, but I can't find any documentation on configuration options to jspm itself.

**Comment by guybedford** [comment]
I agree it could definitely be useful to have a config option to set this up.

It probably makes the most sense entirely as an endpoint configuration option within each endpoint - https://github.com/jspm/github/, https://github.com/jspm/npm, https://github.com/jspm/registry-endpoint.

I'll gladly take PRs along these lines.

**Comment by guybedford** [comment]
Tracking at https://github.com/jspm/jspm-cli/issues/725.
