### ISSUE TITLE
Check ~ edge case

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#674]
See https://github.com/jspm/jspm-cli/blob/master/test/semver.js#L148, I think this test might be wrong.

**Comment by crisptrutski** [comment]
From [node-semver](https://github.com/npm/node-semver#tilde-ranges-123-12-1):
```
~1 := >=1.0.0 <(1+1).0.0 := >=1.0.0 <2.0.0 (Same as 1.x)
```

**Comment by guybedford** [comment]
Ahh right, got it thanks.
