### ISSUE TITLE
error Repo jspm:fs not found

### ISSUE THREAD

**Issue by bastienJS** [jspm/jspm-cli#676]
I try to do in my app_directory

jspm install -y

see here:

![image](https://cloud.githubusercontent.com/assets/5945955/7105731/e0fa89c4-e127-11e4-8906-ee54b90ed626.png)

Why do I get that error?

I did before 'jspm registry config github'

and my username + generated token got accepted no errors so far.

I am on windows 8.1 Pro 64bit.

**Comment by guybedford** [comment]
Ensure you're running jspm 0.15.3 by using `jspm -v`. Then try doing a cache clear before install - `jspm cc`.

**Comment by bastienJS** [comment]
Doing jspm -v I got 0.15.3 and after doing jspm cc I did again: 'jspm isntall -y and get the same error.

**Comment by guybedford** [comment]
I believe we cracked this windows bug in jspm-npm 0.21.2, perhaps check this dependency is up to date within jspm itsel? (`npm install jspm -fg` could be a last resort). If it's still not working, can you share the install you're doing as the bug might have come back, but if you can verify the version of jspm-npm is that first that would help a lot.

**Comment by bastienJS** [comment]
How do I get the version of jspm-npm? Do you mean the version of jspm or npm? I am confused.

**Comment by guybedford** [comment]
When you install jspm, it will tell you the versions of the dependencies in use - ensure that `jspm-npm@0.21.2` is in that list.

**Comment by bastienJS** [comment]
When I run npm install jspm -g

then I get this:

![image](https://cloud.githubusercontent.com/assets/5945955/7105975/22b92d52-e132-11e4-9424-6ef00fdf94fe.png)

I can see => jspm-npm@0.21.1

**Comment by guybedford** [comment]
Ok thanks for confirming, I'll test this out as soon as I can then. Is this just the standard Aurelia skeleton you're installing?

**Comment by bastienJS** [comment]
yes it is this: https://github.com/aurelia/skeleton-navigation

**Comment by guybedford** [comment]
Did you try running `jspm install -f` here to skip cache validation? I've tried this install on both Windows and Mac and it is working completely fine for me.

**Comment by bastienJS** [comment]
This time I did jspm install -f instead of jspm install -y then it seems much more jspm packages are installed =>
![image](https://cloud.githubusercontent.com/assets/5945955/7122168/b62d0dc8-e219-11e4-8e8b-ff53482ed73c.png)


 When I look in the jspm /github folder I see theer now aurelia. When I do gulp watch I get an error that it is not in the app dir. Then I do npm install gulp. Gulp watch again and I get this image =>

![image](https://cloud.githubusercontent.com/assets/5945955/7122191/fe3817fc-e219-11e4-9130-3c92f41add99.png)

Now I dont want anymore if you have not still a last hint I will try to run the aurelia skeleton app on my office notebook also running win 8.1 64bit then we see. If it works there I reformat my private pc ;-)

**Comment by guybedford** [comment]
Are you sure you have the latest version of Aurelia Skeleton? Try updating your clone?

**Comment by guybedford** [comment]
Actually, have you customized the jspm registry at all? Can you share your output of `jspm registry export jspm`?

**Comment by bastienJS** [comment]
![image](https://cloud.githubusercontent.com/assets/5945955/7123011/7898e06c-e21f-11e4-9f3a-d0ca9d2b764a.png)

yes I have latest aurelia skeleton version

**Comment by bastienJS** [comment]
on WHAT windows did you try, windows 8.1 64bit?

**Comment by guybedford** [comment]
Thanks - so can you confirm `jspm install fs` isn't working for you here?

I tried against a Windows 7 VM. I'd be very interested to track this down if we can.

**Comment by bastienJS** [comment]
![image](https://cloud.githubusercontent.com/assets/5945955/7123164/730553dc-e220-11e4-834b-d845caeef76c.png)

**Comment by guybedford** [comment]
Ok try running `jspm cc` and then `jspm install fs` again and see if that helps.

Alternatively you may need to run at a higher access level or check the permissions of the `C:\Users\bastien\.jspm` folder.

**Comment by bastienJS** [comment]
![image](https://cloud.githubusercontent.com/assets/5945955/7123283/71040366-e221-11e4-981c-ff539670d6e1.png)

the CMD is extra opened via administrator, there is nothing higher.

**Comment by guybedford** [comment]
Thanks for bearing with on this. Can you try:

 ```
  cd C:\Users\bastien\.jspm\jspm-cache
  dir
```

And see if that folder exists?

**Comment by bastienJS** [comment]
no prob.

![image](https://cloud.githubusercontent.com/assets/5945955/7123560/3d61f0ca-e223-11e4-88fa-16ad77892cbc.png)

**Comment by guybedford** [comment]
That is completely the wrong contents! Can you tell from the package.json what that is in there? It is supposed to contain a git clone of https://github.com/jspm/registry.

**Comment by bastienJS** [comment]
{
  "name": "iplanmymeettings",
  "version": "0.0.0",
  "dependencies": {},
  "devDependencies": {
    "grunt": "^0.4.1",
    "grunt-autoprefixer": "^0.7.3",
    "grunt-concurrent": "^0.5.0",
    "grunt-contrib-clean": "^0.5.0",
    "grunt-contrib-concat": "^0.4.0",
    "grunt-contrib-connect": "^0.7.1",
    "grunt-contrib-copy": "^0.5.0",
    "grunt-contrib-cssmin": "^0.9.0",
    "grunt-contrib-htmlmin": "^0.3.0",
    "grunt-contrib-imagemin": "^0.7.0",
    "grunt-contrib-jshint": "^0.10.0",
    "grunt-contrib-uglify": "^0.4.0",
    "grunt-contrib-watch": "^0.6.1",
    "grunt-filerev": "^0.2.1",
    "grunt-google-cdn": "^0.4.0",
    "grunt-karma": "^0.9.0",
    "grunt-newer": "^0.7.0",
    "grunt-ngmin": "^0.0.3",
    "grunt-svgmin": "^0.4.0",
    "grunt-usemin": "^2.1.1",
    "grunt-wiredep": "^1.7.0",
    "jshint-stylish": "^0.2.0",
    "karma": "^0.12.23",
    "karma-jasmine": "^0.1.5",
    "karma-phantomjs-launcher": "^0.1.4",
    "load-grunt-tasks": "^0.4.0",
    "time-grunt": "^0.3.1"
  },
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "test": "grunt test"
  }
}

Iplanmymeetings is a project from me...

**Comment by guybedford** [comment]
There seems to be some strange interception going on - try removing the folder and then manually cloning into it with `git clone https://github.com/jspm/registry jspm-cache`.

**Comment by bastienJS** [comment]
I did as you say and cloned it and the package.json content is the same as before.

**Comment by guybedford** [comment]
It sounds like you may have a different git setup then, as it is somehow intercepting your git clone. Are you perhaps running github proxy or enterprise server configuration or something like that?

**Comment by bastienJS** [comment]
no but I had a big problem with my above project last week which I could not solve so I generated a new angular project with gulp instead of grunt etc...

I guess I try tomorrow evening the same stuff on the office notebook. Then I will return here :-) Thanks for your engangement!

**Comment by guybedford** [comment]
Sure, I'd suggest trying to clone another project on github via https and seeing if you get the right thing being cloned. It may be worth trying to update git. It definitely sounds like some sort of git configuration and not jspm though.

**Comment by bastienJS** [comment]
1.) After a fresh win 8.1 pro installation
2.) git + git bash installation
3.) nodejs installation

I did this in a Admin command line window within my aurelia skeleton app folder on C:\Aurelia-skeletona-pp

1.) npm install
2.) npm install -g gulp
3.) npm install -g jspm
4.) jspm install -y

After point 4.) I get this error =>

![image](https://cloud.githubusercontent.com/assets/5945955/7146669/8821e188-e2f5-11e4-8b4a-3e2f5bcb59bf.png)

JSPM is saying git is not installed? ...

What do you think?

**Comment by johnsoftek** [comment]
@bastienJS Did you install Git with the option to make it globally
available?

**Comment by bastienJS** [comment]
I will recheck git repair mode if possible to change that if that option is available, see ya in 3 hours...

**Comment by bastienJS** [comment]
There is nothing like "global option" when installing Git on Windows.

I assume it is automatically installed globally...

see

![image](https://cloud.githubusercontent.com/assets/5945955/7163951/56097eba-e39d-11e4-9d0c-50ed8455e940.png)

**Comment by bastienJS** [comment]
ah... I guess you mean this:

![image](https://cloud.githubusercontent.com/assets/5945955/7164022/b1696374-e39d-11e4-9efa-49c62638402b.png)

**Comment by bastienJS** [comment]
Oh my gush it works, without any error the aurelia skeleton starts fine! Thanks for all your support!

**Comment by bastienJS** [comment]
Whatever the original error was hope I do not face it again :-)

**Comment by guybedford** [comment]
Glad to hear this has finally been sorted out. Will note this for users for future.

**Comment by colinsr** [comment]
I had the same issue ( Git not installed...).  Windows 7.  Reinstalled git with "Use Git from the Windows Command Prompt" and not errors.

Thanks for the help!

**Comment by Turbots** [comment]
I have the same issue ("Git not installed") on an Amazon EC2 instance (Linux image) where Git is already installed.

Git is located at /usr/local/bin/git but JSPM says it cannot find git

What is the command jspm uses to retrieve git repos from the internet? I tried working with aliases by doing "alias git='usr/local/bin/git' but that doesn't work.. 

Here's the relevant part of the build:

Fetching changes from the remote Git repository
 > /usr/local/bin/git config remote.origin.url ssh://git@...

WORKS

But later in the build:

[INFO] Running 'jspm.js install' in /app/jenkins/jobs/jit/workspace/frontend
[ERROR] 
[ERROR] err  Git not installed. You can install git from http://git-scm.com/downloads.
[ERROR] 
[ERROR] err  Unable to load registry github
[INFO] 
[INFO] warn Installation changes not saved.

This happens...

**Comment by johnsoftek** [comment]
Is /usr/local/bin in your path?
`echo $path`

**Comment by Turbots** [comment]
Apparently, I was always adding the git directory to the `$path` environment variable like this
`export path=\usr\local\bin:$path`
but there was never anything in it.

`which git`
printed out a long line of paths where he had looked.

`export $PATH=\usr\local\bin:$PATH
did set my path correctly so I got that figured out.

But I'm still getting the same error from JSPM though

**Comment by johnsoftek** [comment]
Linux paths have forward slashes:
`export PATH=/usr/local/bin:$PATH`

If `which git` does not show `/usr/local/bin/git`, then JSPM will not work.

**Comment by Turbots** [comment]
Yes, I used forward slashes (I typed them wrong in here)

Apparently, on my Jenkins instance (which is on Amazon EC2) I cannot access github.com (I tried pinging it, it seems to be blocked)

I just added the github specific dependencies to my source control (I know, bleh) but it still gives an error.. How can I configure the github repository to not try going to the internet but use my available github dependencies (which are in jspm_packages directory)?

**Comment by johnsoftek** [comment]
Maybe easier to fix the connectivity problem on AWS rather than spend time
on a JSPM workaround..

**Comment by Turbots** [comment]
Yea, unfortunately that's not up to me, I'm just a silly developer :yum: 

Thanks for the help, I know what the root cause is now, I'll figure something out :octocat:

**Comment by Turbots** [comment]
Okay, after long discussions with the administrators of our private Amazon instances (they are linked to the corporate intranet so they're not public instances) he says we should use `http` or `https` to download dependencies (just like Maven does) because they won't allow SSH connections outside of the own virtual network (only SSH over port 22 to 10.0.0.0/8 is allowed) 

Anyone have an idea how I can configure JSPM to pull in the github dependencies over HTTPS? If it already is, then I have no more clue as to what is going wrong :fearful:

**Comment by m4r71n** [comment]
@Turbots `git config --global url."https://".insteadOf git://` works for me
