### ISSUE TITLE
jspm init err  Error locating

### ISSUE THREAD

**Issue by BrettMN** [jspm/jspm-cli#680]
When I try to run `jspm init` I receive the following messages:

```
jspm init
ok   Verified package.json at package.json
     Verified config file at config.js

err  Error locating github:jmcriffey/bower-traceur.
```

Is there a way to enable verbose messages to get more details?

Thanks

**Comment by guybedford** [comment]
Yes this is being tracked at https://github.com/jspm/jspm-cli/issues/528.

**Comment by guybedford** [comment]
@BrettMN closing for now, but did you manage to work out what the underlying issue was? Network issues or authentication / proxy support?

**Comment by BrettMN** [comment]
@guybedford yeah I resolved my issue by deleting the config file.  I wrote about it here  https://www.wipdeveloper.com/2015/04/18/jspm-err-error-locating-github/

**Comment by guybedford** [comment]
@BrettMN thanks for posting. I'm trying to work out how it could have possibly happened, are you sure the broken config had no mention of `registries` or `defaultRegistry`? It is supposed to default populate these properties with the old properties of `endpoints` and `registry` in https://github.com/jspm/jspm-cli/blob/master/lib/global-config.js#L80 and I'm struggling how that could have gone wrong. If you still have the old config somewhere it would be great to see. Really can't offer more than that for now unfortunately.

Thanks for posting your solution online though - really nice to have materials around for people.

**Comment by BrettMN** [comment]
@guybedford it had `registry`, `endpoints`, `defaultRegistry` and `registries`

```
{
  "registry": "github",
  "endpoints": {
    "github": {
      "timeouts": {
        "lookups": 60
      },
      "remote": "https://github.jspm.io",
      "auth": "",
      "maxRepoSize": 0,
      "handler": "jspm-github"
    },
    "npm": {
      "timeouts": {
        "lookups": 60
      },
      "handler": "jspm-npm",
      "remote": "https://npm.jspm.io"
    },
    "jspm": {
      "timeouts": {
        "lookups": 60
      },
      "handler": "jspm-registry",
      "remote": "https://registry.jspm.io"
    }
  },
  "defaultRegistry": "github",
  "registries": {
    "github": {
      "timeouts": {
        "lookups": 60,
        "build": 120
      },
      "remote": "https://github.jspm.io",
      "auth": "",
      "maxRepoSize": 0,
      "handler": "jspm-github"
    },
    "npm": {
      "timeouts": {
        "lookups": 60,
        "build": 120
      },
      "handler": "jspm-npm",
      "remote": "https://npm.jspm.io"
    },
    "jspm": {
      "timeouts": {
        "lookups": 60
      },
      "handler": "jspm-registry",
      "remote": "https://registry.jspm.io"
    }
  }
}
```

With the way it was setup I had to remove `registry`, `endpoints`, and `defaultRegistry` to get install to work.  

```
{
  "registries": {
    "github": {
      "timeouts": {
        "lookups": 60,
        "build": 120
      },
      "remote": "https://github.jspm.io",
      "auth": "",
      "maxRepoSize": 0,
      "handler": "jspm-github"
    },
    "npm": {
      "timeouts": {
        "lookups": 60,
        "build": 120
      },
      "handler": "jspm-npm",
      "remote": "https://npm.jspm.io"
    },
    "jspm": {
      "timeouts": {
        "lookups": 60
      },
      "handler": "jspm-registry",
      "remote": "https://registry.jspm.io"
    }
  }
}
```

Then it would update the config and probably bring it up to date.  

If any of the three were not removed it would fail.

**Comment by guybedford** [comment]
How did the defaultRegistry get set to `github`? That sounds strange, and may be the issue?

**Comment by guybedford** [comment]
I think that's it! Posted https://github.com/jspm/jspm-cli/issues/695.

**Comment by BrettMN** [comment]
I'm not sure, I think I may have mentioned I probably did something wrong at some point.  I know I did the `jspm registry config github` a time or 2 I may have done something wrong at some point

**Comment by guybedford** [comment]
If you had done `jspm config registry github` in an earlier version of jspm, and then when you upgraded that would have become `defaultRegistry: 'github'` only affecting then!
