### ISSUE TITLE
bundle-sfx produce incorect code

### ISSUE THREAD

**Issue by zajca** [jspm/jspm-cli#681]
I'm trying make bundle in my project. In dev everything is just fine but when I create bundle ```jspm bundle-sfx main web/main.js``` code is not working and throws error in [MarkerCluster lib](https://github.com/googlemaps/js-marker-clusterer)

here is produced code: http://pastebin.com/AnKLu2kx

this code show syntax error on line 44 ```Error: Line 44: Unexpected token ;``` source is just fine

**Comment by guybedford** [comment]
Thanks I've added a fix and will push out a patch shortly.
