### ISSUE TITLE
Subtract common

### ISSUE THREAD

**Issue by OliverJAsh** [jspm/jspm-cli#686]
I want to dynamically create a "common" bundle, and then subtract that from all of my bundles.

``` js
// a - (b & c)
var common = 'b & c';
var app = 'a - (' + common + ')';
```

Re. #133

**Comment by guybedford** [comment]
Ok sure, the above should already work without the brackets though (union takes preference in arithmetic I believe)?

**Comment by OliverJAsh** [comment]
When I tested it, subtraction was taking preference, IIRC, i.e.:

```
(a - b) & c
```

**Comment by guybedford** [comment]
Sure, I've created an issue at https://github.com/systemjs/builder/issues/141.

**Comment by guybedford** [comment]
Continuing to track this at the SystemJS builder issue.

**Comment by guybedford** [comment]
Better than brackets might be to allow the subtractions from bundles from eachother. I've created https://github.com/systemjs/builder/issues/150 to track this.

**Comment by OliverJAsh** [comment]
This was actually my use case!

**Comment by devmondo** [comment]
awesome :+1:
