### ISSUE TITLE
The registry is evil

### ISSUE THREAD

**Issue by lookfirst** [jspm/jspm-cli#688]
The registry just gave me 20 minutes of pain. I had added semantic myself:

`jspm install semantic=github:Semantic-Org/Semantic-UI`

I had referenced it like this:

`import ‘semantic/dist/semantic.css!’;`

Things were working fine.

[Then you go and add a registry override 5 hours ago.](https://github.com/jspm/registry/blob/master/package-overrides/github/Semantic-Org/Semantic-UI%401.11.8.json)

Suddenly, my webserver can’t find semantic.css cause now there isn’t a dist folder created.

Since I deploy to Heroku, suddenly a redeployment totally fails.

The registry is evil.

**Comment by douglasduteil** [comment]
Ouch 
@guybedford Are there a way to lock you dependencies graph versions like [`npm shrinkwrap`](https://docs.npmjs.com/cli/shrinkwrap) with jspm ?

**Comment by guybedford** [comment]
Versions are locked by the jspm config file.

This is mostly about ensuring backwards-compatibility conventions for the registry. The current convention has been that a package is considered "not locked down" if when installing that package, a require of the package does not resolve, and fair game for breaking overrides. We either need to be much clearer about this assumption, or alter it.

**Comment by lookfirst** [comment]
It would be nice if there was a configurable option to apply the registry or not. This could be done on a per package basis. I’d like to know when a package is overridden and be able to have control over that for repeatable builds.

**Comment by guybedford** [comment]
I've posted https://github.com/jspm/registry/issues/338 to document more carefully the registry override workflows around backwards-compatibility, creating automated processes to more clearly stick to these rules can make some of this stuff work more smoothly.
