### ISSUE TITLE
how to shim any module with any other module

### ISSUE THREAD

**Issue by jpray** [jspm/jspm-cli#689]
jspm is awesome, but the shim construct has really thrown me for a loop.  I'm working on a project that utilizes jspm and I would like to be able to indicate that module A should be loaded before module B, regardless of whether these modules are from a registry or just a custom module within the project. I'm also confused by whether the shim declaration should be done within package.json or config.js.

After reading everything I could find about shim configuration in jspm here is my best guess:

from package.json
```
...
"jspm": {
  "registry":"jspm",
    "directories": {
      "lib": "src"
    },
    "shim": {
      "backbone.marionette": {
        "deps": ["js/my-marionette-shim"]
      }
    },
...
```

Any guidance would be very much appreciated.  Thanks!

**Comment by guybedford** [comment]
There are two ways to apply shim configuration - directly as configuration for SystemJS or within the package.json of something you are installing.

When installing a package, shim can be specified via the package.json or package.json override - `jspm install x -o "{ shim: { 'file.js': { deps: ['./another-file'] } } }"`

Shim deps are just like writing a custom `require('./another-file')` or `import 'another-file'` within the module itself.

The way to do this same thing via SystemJS configuration is by working out the exact "canonical module name" of that module in the registry and then applying the shim as meta configuration:

```javascript
System.config({
  meta: {
    'exact/name/of/module': {
      deps: ['./relative-module']
    }
  }
});
```

The hard part with the above form is knowing the exact canonical name of the module. This is best worked out at runtime via `System.normalize('my/module').then(console.log.bind(console))`.

Typically for third-party libraries, the override approach and committing the override into the registry is recommended, as it helps other jspm users.

**Comment by jpray** [comment]
Thanks a bunch, that does help me understand things a little better.  I found the module's canonical name and setup the following in config.js

```
System.config({
  "baseURL": "",
  "transpiler": "babel",
  "babelOptions": {
    "optional": [
      "runtime"
    ]
  },
  "paths": {...},
  "meta": {
    'npm:backbone.marionette@2.4.1/lib/core/backbone.marionette': {
      "deps": ['lib/marionette-shim']
    }
  }
});
```

I have been trying to get lib/marionette-shim to work with it written as follows:

```
//https://github.com/jashkenas/backbone/issues/3291
import Backbone from 'backbone';
import $ from 'jquery';

Backbone.$ = $;
```

and I see that the module is being loaded but not executed (just saw your comment on [2ality's post](http://www.2ality.com/2014/09/es6-modules-final.html) that describes that this is what will happen when System.load loads an ES6 module.... so I tried it in cjs format and that didn't seem to change anything.  

In development I've been nesting System.import().then() calls to achieve the desired result, but I want to understand how to make shims work in this case and also so I can use jspm's bundle-sfx command to bundle everything into one file.  Currently when I run jspm bundle-sfx, then I see in the built file that 'lib/marionette-shim' is listed as a dependency `System.register("npm:backbone.marionette@2.4.1/lib/core/backbone.marionette", ["lib/marionette-shim",...], true, function(require, exports, module) {...`  but in stepping through the code it appears that 'lib/marionette-shim' is getting registered but not loaded...

**Comment by guybedford** [comment]
What you're doing should completely in theory work, but isn't because of an issue I've just created in https://github.com/systemjs/systemjs/issues/408.

If that was resolved, this should work completely fine.

One way you should be able to work around the above is to add:

```javascript
  "meta": {
    'npm:backbone.marionette@2.4.1/lib/core/backbone.marionette': {
      "deps": ['lib/marionette-shim'],
      "format": "global" // or try AMD
    }
  }
```

Which will run the module in an execution mode where dependencies don't need to be explicitly `require`ed to execute (the bug above).

Let me know if that helps!

**Comment by jpray** [comment]
Thanks! That's great that #408 will enable shimming of commonjs modules...

Using "global" or "amd" for the format didn't work for the case I was describing because it is a "cjs" module I was shimming  and changing the format declaration was causing errors to be thrown.  

I realized that with 4 supported module formats, there are at least 16 different type combinations when trying to make one module execute before another.  I created a [small project](https://github.com/jpray/jspm-shim-test) to test these combinations to see what works currently.  Here is what my tests show:

```
AMD Shims AMD: SUCCESS
AMD Shims CJS: FAIL
AMD Shims ES6: FAIL
AMD Shims Global: SUCCESS
CJS Shims AMD: SUCCESS
CJS Shims CJS: FAIL
CJS Shims ES6: FAIL
CJS Shims Global: SUCCESS
ES6 Shims AMD: FAIL
ES6 Shims CJS: FAIL
ES6 Shims ES6: FAIL
ES6 Shims Global: FAIL
Global Shims AMD: SUCCESS
Global Shims CJS: FAIL
Global Shims ES6: FAIL
Global Shims Global: SUCCESS
```

Do they results line up with your expectations / tests (given that #48 will be adding some support for cjs modules)?  Also, with #48, will all 4 module types be able to be used as shims for cjs modules?
Are there any combinations that will never be supported for some reason?

Thanks!

**Comment by guybedford** [comment]
Thanks for going through these cases so thoroughly.

To summarize the failures:

```
AMD Shims CJS: FAIL
CJS Shims CJS: FAIL
ES6 Shims CJS: FAIL
Global Shims CJS: FAIL
Solved by systemjs/systemjs#408

AMD Shims ES6: FAIL
CJS Shims ES6: FAIL
ES6 Shims ES6: FAIL
Global Shims ES6: FAIL
Shimming ES6 is not possible in the loader specification.
```

Then for these cases:

```
ES6 Shims AMD: FAIL
ES6 Shims Global: FAIL
```

The reason they are failing is because ES6 always executes after the other formats have executed. That is ES6 modules exhibit _deferred execution_.

You'll find the above modules are executing, but just after the AMD and global modules.

I hadn't thought of it, but interestingly, this case will change in the next specification update, which seems like a good thing.

**Comment by jpray** [comment]
Cool, my questions regarding shims have been thoroughly answered. Thank you.

**Comment by jamiehill** [comment]
Did you guys manage to find the solution to the marionette-shim in the end?  Still trying - without luck - to get it going.

**Comment by jpray** [comment]
Yeah.  I got the shim to work with the following
config.js
```
System.config({
  "meta": {
    "github:marionettejs/backbone.marionette@2.4.1/lib/core/backbone.marionette": {
      "deps": [
        "lib/marionette-shim"
      ],
      "format": "amd"
    }
  }
});
```

lib/marionette-shim.js
```
//why this is needed - https://github.com/jashkenas/backbone/issues/3291
//why this is written in AMD format - https://github.com/jspm/jspm-cli/issues/689
define(['backbone','jquery'],function(Backbone, $){
  Backbone.$ = $;
  return;
})

```

main.js
```
import 'lib/marionette-shim';
...
```

This works.  However, with systemjs/systemjs#408 it seems that doing the shim in CJS format should also work.

**Comment by jamiehill** [comment]
Thanks a million, that got the app running straight away without those aweful nested System.imports in my index!  :+1: 

I'm still having issues with Karma picking things up correctly for some reason though - any ideas?

**Comment by jamiehill** [comment]
Not to worry @jpray have got the tests running now using the shim.  Thanks for your time in helping me getting it working.

**Comment by jamiehill** [comment]
Just a note to anyone stumbling across this issue (specifically shimming Marionette), I've found that `npm:backbone.marionette@2.4.2` fixes this issue, and therefore no shim is now required.
