### ISSUE TITLE
Globally configure default transpiler

### ISSUE THREAD

**Issue by swirlycheetah** [jspm/jspm-cli#691]
I'd prefer it if `jspm init` defaulted to Babel rather than Traceur but I understand that's just my own personal preference.

I was more wondering whether you collect any stats and if so could those be used to to decide which transpiler to default to?

**Comment by lookfirst** [comment]
Yes!

**Comment by clintwood** [comment]
Maybe this could be a user setting in `~/.jspm/config`

**Comment by guybedford** [comment]
Good point - this could be a global configuration option. Then if the user chooses Babel when the default global option is set to Traceur, we can ask if they want to change the global default.

**Comment by crisptrutski** [comment]
@guybedford FYI there's no "Would you like this to be the new default?" step in swirly's patch, but not sure that's necessary. 

Only updates on manual input, not `--prompts` style, which could be confusing.

**Comment by guybedford** [comment]
It's quite nice having the `dl-loader` not being permanent - happy to leave as-is for now.

@swirlycheetah thanks for the PR!

**Comment by swirlycheetah** [comment]
Thanks folks. Yeah it's a pretty basic implementation for now, I'm happy to extend it if required in the future. There may also be some scenarios where the tests could fail if babel is set as the default so if that comes up I'll take a look.
