### ISSUE TITLE
Dealing with pre-compiled templates

### ISSUE THREAD

**Issue by abiee** [jspm/jspm-cli#692]
I want to compile my handlebars templates by myself, so I have this directory structure

    app
    ├── 404.html
    ├── config.js
    ├── images
    ├── index.html
    ├── jspm_packages
    └── scripts
        ├── app.js
        ├── appLayout.js
        ├── main.js
        └── templates
            └── layout.hbs

When I run

    jspm bundle-sfx main dist/scripts/app.js --minify

I got this error message

    ENOENT: no such file or directory, open '/xxx/app/scripts/templates/layout.js'

I know layout.js doesn't exists under that path, because it was compiled and exists in

    /xxx/.tmp/scripts/templates/layout.js

The question is, how can I tell to jspm that this is the path of compiled templates (.tm/scripts)?

**Comment by guybedford** [comment]
You could do this via paths configuration at build time:

```javascript
System.paths['app/scripts/templates/*.js'] = '.tmp/scripts/templates/*.js'
```

Having separate build-time configuration is not currently supported, although we could look at supporting this via a `config.build.js` for example.

Currently you need to manually invoke the jspm build API to do this -

```javascript
var builder = new require('jspm').Builder();
builder.config({
  paths: {
    'app/scripts/templates/*.js': './tmp/scripts/templates/*.js'
  }
});
builder.build('app/main', 'build.js', { sourceMaps: true }).then(function() {
  // done
});
``

**Comment by guybedford** [comment]
Closing, but let me know if you have any further questions.
