### ISSUE TITLE
Wrong interpretation of "directories" in package.json

### ISSUE THREAD

**Issue by smehrbrodt** [jspm/jspm-cli#699]
I tried to install CodeMirror with JSPM: `jspm install github:codemirror/CodeMirror`
This downloads only the "lib/" folder, all other folders are missing. When you remove the [directories property](https://github.com/codemirror/CodeMirror/blob/master/package.json#L8), it works perfectly.

This is not the expected behavior. `npm install codemirror` downloads the whole repository. The `directories` section should not limit the files which are downloaded.

**Comment by guybedford** [comment]
@smehrbrodt if yout install an npm package, then the `directories.lib` is ignored. Perhaps use `jspm install npm:codemirror`?

**Comment by smehrbrodt** [comment]
Thanks, that works.
But why does the jspm interpret the `directories.lib` property that way when installing from github?

**Comment by guybedford** [comment]
Because those are the rules jspm follows when interpreting packages, and it's not breaking prior conventions so we're fine to define this.

**Comment by smehrbrodt** [comment]
Ok, thanks for your help!

**Comment by smehrbrodt** [comment]
I have still a problem. I need to add an override since CodeMirror has a global variable which needs to be exposed. However, once I apply this override and do `jspm install`, the original directory structure is gone and I have only the `lib` folder again. 

What can I do about that?

This is my override:

```json
    "overrides": {
      "npm:codemirror@5.2.0": {
        "registry": "jspm",
        "format": "global",
        "main": "lib/codemirror.js",
        "shim": {
          "lib/codemirror.js": {
            "exports": "CodeMirror"
          }
        }
      }
    }
```

**Comment by guybedford** [comment]
You can override the `directories.lib` value with `{ directories: { lib: '.' } }`.

But yes this behaviour is surprising, which isn't good. It may be worth considering a less surprising approach along the lines of only allowing `directories.lib` to be set via an override or jspm property.

**Comment by guybedford** [comment]
Actually this isn't supposed to happen at all. Posted a bug at https://github.com/jspm/npm/issues/59.

**Comment by guybedford** [comment]
To update here - this behaviour works and is all by design.

Specifically what happened is by adding `registry: 'jspm'` this bypassed the standard npm-interpretation of the package config, and used complete jspm-interpretation, which was the toggle that changed.

The registry property means more than just where to find the dependencies - it also implies that this package itself is written against that registry, with its conventions.

**Comment by smehrbrodt** [comment]
How can I override the `directories.lib` value then?

This doesn't work:

```json
      "npm:codemirror@5.2.0": {
        "registry": "jspm",
        "directories": {
          "lib": "."
        },
        "shim": {
          "lib/codemirror.js": {
            "exports": "CodeMirror"
          }
        }
      },
```

**Comment by guybedford** [comment]
The above is definitely working fine for me (in terms of overriding the directories.lib value).
