### ISSUE TITLE
RFE: Can jspm-cli manage (create/update/delete) paths during install?

### ISSUE THREAD

**Issue by mikol** [jspm/jspm-cli#700]
We have a conflict in our `import` namespace. The conflict arises when a top-level directory in the `import` namespace and an installed module have the same name. For example:

```
import 'css/styles.css!';
```

In this case, the module loader uses the `map` config created by `jspm install css`. For example:

```
  "map": {
    ...
    "css": "github:systemjs/plugin-css@0.1.9",
    ...
  }
```

The module loader therefore attempts to load:

```
.../jspm/packages/github/systemjs/plugin-css@0.1.9/styles.css
```

When we want it to load:

```
.../static/css/styles.css
```

We have considered two workarounds.

In the first workaround, we install the module using `jspm install ld-css=github:systemjs/plugin-css`. And use it with this name (e.g., `import 'css/styles.css!ld-css';`). Pro: jspm manages this package across updates, etc. Con: The loader plugin is named unconventionally so developers must bear that in mind.

In the second workaround, we create an entry in the `paths` config and remove the `map` entry. For example:

```
System.config({
  ...
  "paths": {
    "css": "../jspm/packages/github/systemjs/plugin-css@0.1.9.js",
    ...
    "*": "*.js",
    "github:*": "../jspm/packages/github/*.js",
    "npm:*": "../jspm/packages/npm/*.js"
  }
});
```

Pro: The plugin can be used conventionally. Con: jspm no longer manages this package properly without our intervention.

Because we prefer to preserve the conventional plugin usage, what we’re looking for is a way to tell jspm to manage an install via the `paths` config instead of the `map` config.

That said… If the module loader semantics were similar for both `paths` and `map` (that is, the map name identified a resource file alone and not also the root of a directory hierarchy), that would solve our problem. But  we suspect that these semantics are more or less fixed at this point.

It’s also possible that we’re thinking about this from the wrong perspective. Maybe having modules that overlap with unrelated paths is not a good idea anyway.

**Comment by guybedford** [comment]
The convention for an installed package X is that `import 'X'` will load the main and `import 'X/sub'` will load from inside the package. Also contextual map is necessary to handle separate namespaces for dependencies.

This will get better with the coming configuration changes in jspm and SystemJS:

```javascript
System.config({
  meta: {
  }
});
```

**Comment by mikol** [comment]
This is great. We will work around our collision issues until the coming configuration changes land. Thanks for the quick response.

**Comment by guybedford** [comment]
Great, thanks for bearing with on the workaround. Closing as this will happen naturally as we undergo the architectural shift.
