### ISSUE TITLE
Empty version inserts package name

### ISSUE THREAD

**Issue by admwx7** [jspm/jspm-cli#702]
`jspm install npm:formulajs` fails with `err No version match found for npm:voc@voc` you can trace it back to the package.json in the SheetJS/bessel project on github which has an entry stating `"voc": ""`, when installing via npm this will assume the latest version, however jspm tries to use the name as the version and fails.

**Comment by guybedford** [comment]
Thanks for reporting, this has been fixed in a patch update to jspm-npm.
