### ISSUE TITLE
Prevent from accidental publishing

### ISSUE THREAD

**Issue by interactionist** [jspm/jspm-cli#703]
Was just reading this section:
https://github.com/jspm/jspm-cli/wiki/Publishing-Packages#writing-a-library-or-application-for-usage-just-with-jspm

How can we prevent from accidentally publishing something with ```jspm```.
Does the ```"private":true``` prevent to publish to both ```npm``` and the ```jspm registry```?

Thank you.

**Comment by guybedford** [comment]
There is no `jspm publish`, but when there is we'll likely support this.
