### ISSUE TITLE
npm endpoint doesn't support npm tags

### ISSUE THREAD

**Issue by zcregan** [jspm/jspm-cli#704]
npm install let's you install packages by "npm tags". jspm doesn't appear to offer the same ability.

For example, I publish my npm package `my-library` like so:
`npm publish --tag dev`

Then, in a different npm package I can install `my-library` with:
`npm install my-library@dev`

But with jspm:
`jspm install npm:my-library@dev`
returns:
`err No version match found for npm:my-library@dev`

**Comment by guybedford** [comment]
Thanks, posted https://github.com/jspm/npm/issues/61, will track there.
