### ISSUE TITLE
jspm update should bump up semver base-levels of primaries

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#705]
When running `jspm update x`, the semver range `x` is installed into, should be bumped up so that the new version of x is the base of the range.

**Comment by crisptrutski** [comment]
What's the rationale for this - repeatability? Imagining scenarios where a release rolls out before their private repo cache has updated. Or is your concern something else?

There's a trade-off here - the extra line noise in package file (and the "where's my formatting gone")

**Comment by guybedford** [comment]
This isn't as important for application code actually - it's really specifically for library projects that update dependencies not to release with dependency constraints that allow patches to low that would break them.

**Comment by crisptrutski** [comment]
Interesting. 

My take for libraries is that the etiquette is to provide the widest range that works, to minimise impact on applications. Consider for example the case where dependencies A and B both depend on C, but only B is broken by a breaking change in C. Now imagine that C is a peerDependency.

**Comment by guybedford** [comment]
Not sure I follow the logic. A and B are primary dependencies? Which one are we bumping?

**Comment by crisptrutski** [comment]
`A` (and possibly `B`, doesn't matter) are libraries using jspm, and a `jspm update` is run in `A`, which updates its lower bound on `C`. Now application is blocked from updating `A`.

**Comment by guybedford** [comment]
Which application is blocked from updating A, and why?

**Comment by crisptrutski** [comment]
Ignoring specifics of version number for `A` and `B`, consider their dependencies on some `C`:

`A`: `{C: "^1.4"}`
`B`: `{C: "^1.4.5"}`

Ranges have overlap, application can install both `A` and `B`.

Now, without technical reason `A` updates dependency to `{C: "^1.5.3}` via `jspm update` - ranges no longer have overlap, so application cannot upgrade `A`.

**Comment by guybedford** [comment]
`^1.5.3` certainly overlaps `^1.4.5`.

**Comment by crisptrutski** [comment]
Replace `^` with `~`, spazzed.

**Comment by crisptrutski** [comment]
Or imagine `B`: `{C: "1.4.5"}` (for some technical reason)

**Comment by guybedford** [comment]
Certainly it narrows the consolidation margin, but it's more important to provide ranges that are to our best knowledge non-breaking.

**Comment by guybedford** [comment]
Agreed to make this an option - `jspm update --bump`?

**Comment by crisptrutski** [comment]
+1

**Comment by crisptrutski** [comment]
Dropped for now

**Comment by crisptrutski** [comment]
@guybedford changed your mind? let me know if you want me to pick this up

**Comment by guybedford** [comment]
Happy to leave unlabeled for non priority features, until we reach a point
of usage pressure

**Comment by crisptrutski** [comment]
Ah, cool
