### ISSUE TITLE
jspm upgrade command

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#706]
`jspm update` will always update dependencies within their ranges.

A `jspm upgrade` could be useful to update across major boundaries, perhaps with some kind of rollback facility.

Thoughts?

**Comment by crisptrutski** [comment]
Sounds pretty useful, but some issues spring to mind:

Does it release all the constraints at once? That could actually end in some dependencies getting knock backwards a bit. But releasing them just in time may mean that the command may need to do multiple passes or be run multiple times to converge. Then there's the chestnut of deciding the order to attempt updates in.

None of these are issues if you start with `jspm upgrade X` only though.

**Comment by SandHilt** [comment]
Or add list command like bower;

**Comment by mikeobrien** [comment]
Yes, please! :+1:

**Comment by devmondo** [comment]
:+1:

**Comment by erenard** [comment]
Hey guys, the install command does it.
Exemple :
jspm install aurelia-bootstrapper
---
=> upgraded to the last version

**Comment by mikz** [comment]
Coming from Rails world, the common workflow to bump major versions is to run `bundle outdated` and bump one by one, testing what works in the process. It is hard to imagine, doing automatic bump of all the dependencies, would not break everything. So I'd say https://github.com/jspm/jspm-cli/issues/471 is more important, than this. Just to see what needs to be upgraded.

**Comment by aTable** [comment]
NPM has it's own version called "npm-check-updates"

Developers know not to brute force things so we _probably_ should increment and test package upgrades one by one however...that's like watching paint dry. I'd like to spend less time upgrading packages and more writing code so `jspm upgrade` fits in wonderfully.

There will be times when it backfires for sure but deleting node_modules and reverting the jspm config.js file should be all I can foresee which is  quite manageable.
