### ISSUE TITLE
it seems some npm modules and github module  can not  work together

### ISSUE THREAD

**Issue by pianoboysai** [jspm/jspm-cli#707]
I am not sure  whether it's a bug  and whether should be issued here or systemjs.
for example, I want to use jstree, which depends on jquery
if I install both with npm, it works
jspm install npm:jquery
jspm install npm:jstree

but if one is github module, the other is npm module. it can't work!
jspm install github:jquery/jquery  //or github:components/jquery
jspm install npm:jstree

a testcase is like this.
```
import 'jstree/dist/themes/default/style.min.css!';
import $ from 'jquery'; //set it as npm or github path in "config.js"
import jstree from 'jstree/dist/jstree'; //import a npm module
//import jstree from 'vakata/jstree'; //import a github module

export class TreeBuilder {
constructor() {
$('#testdiv').jstree({'core': {'data': []}}); 
}
}
```

**Comment by douglasduteil** [comment]
Hum... I made you [a plunker demo](http://plnkr.co/a6wMQz) hopping it will help you understanding how to make it work

**Comment by pianoboysai** [comment]
after a research,  I found the problem, the key is in the config.js
"
System.config({
  "map": {
  
    "components/jquery": "github:components/jquery@2.1.3",
    "css": "github:systemjs/plugin-css@0.1.10",
    "jquery": "npm:jquery@2.1.3",
    "jstree": "npm:jstree@3.1.0",
    ....
    "npm:jstree@3.1.0": {
         ....
          "jquery": "npm:jquery@2.1.3",
          ...
        }
    ....
    }
"

when I wrote code like this:
import $ from 'components/jquery';
thought it loaded "github:components/jquery@2.1.3"
but config.js made "jstree" depended on  "jquery": "npm:jquery@2.1.3", the jstree bound "jstree" function to "npm:jquery@2.1.3", not the last one!
in this case, the browser will have 2 jquery module!

there are 2 solutions, both are simple:
1. modify like this:
System.config({
  "map": { 
    "components/jquery": "github:components/jquery@2.1.3",
    
    "npm:jstree@3.1.0": {
        "jquery": "github:components/jquery@2.1.3",
    }
}
and write code like this "import $ from 'components/jquery';"

2.
System.config({
  "map": { 
    "jstree": "npm:jstree@3.1.0",
    
    "npm:jstree@3.1.0": {
        "jquery": "npm:jquery@2.1.3",
    }
}
and write code like this "import $ from 'jquery';"

Thanks everyone

**Comment by lookfirst** [comment]
jspm can't resolve dependencies across repositories. It also doesn't know that 'components/jquery' is the same as 'jquery'. =( This is a pretty big long standing issue. I've found one of the better solutions is to not use npm as the repository, focus on using just github.

**Comment by pianoboysai** [comment]
@lookfirst 
I don't think so, look at my solution above.
of course,  only use npm module or only use github module  are simpler.

**Comment by guybedford** [comment]
Did you manage to work this out?
