### ISSUE TITLE
[v0.15.4] Relative imports are not found in sfx bundles

### ISSUE THREAD

**Issue by OrKoN** [jspm/jspm-cli#708]
I have a module which imports from a module next to it:

```javascript
import parseIRI from './iri';
```

This works w/o sfx bundling but when sfx-bundled it throws an error: Uncaught Module ./iri not present.

Steps to reproduce:

1. git clone https://github.com/OrKoN/jspm-ember-playground.git
2. cd jspm-ember-playground && npm install
3. gulp watch-dist

Worked in 0.15.3 and previosuly.

**Comment by guybedford** [comment]
Thanks, this looks like a Babel bug. I've posted an issue at https://github.com/babel/babel/issues/1342.

**Comment by OrKoN** [comment]
It was fixed in Babel. Thanks @guybedford
