### ISSUE TITLE
jspm install bootstrap does not work.

### ISSUE THREAD

**Issue by Zoltu** [jspm/jspm-cli#709]
JSPM version 0.15.4

1. `npm install jspm`
1. `node node_modules/jspm/jspm.js install --yes`
1. `node node_modules/jspm/jspm.js install bootstrap`
	1. Install fails: `No version match found for github:twbs/bootstrap@bootstrap`
1. `node node_modules/jspm/jspm.js install bootstrap@`
	1. Install succeeds.

I don't know what the @ suffix means, someone in jspm gitter channel recommended it.

**Comment by swirlycheetah** [comment]
I'm seeing similar behaviour on 0.15.4.

**Comment by guybedford** [comment]
Yes this is a bug - apologies this took so long to catch!
