### ISSUE TITLE
Error loading "npm:core-js@0.8.4/library/fn/object/define-property

### ISSUE THREAD

**Issue by stephensauceda** [jspm/jspm-cli#710]
When I load my new jspm project in the browser, I get an error in the console that reads `Potentially unhandled rejection [3] Error loading "npm:core-js@0.8.4/library/fn/object/define-property" at http://localhost:8000/jspm_packages/npm/core-js@0.8.4/library/fn/object/define-property.js`

I checked the path to that file and define-property.js is missing. In the new versions of core-js, the file is present but `jspm install` will only pull in v0.8.4. The project was started with `jspm init` with all default options with the exception of using Babel instead of Traceur.

**Comment by OrKoN** [comment]
I have the same problem.

**Comment by OrKoN** [comment]
I think it's related to the new release of Babel. It's broken with the newest Babel and works if one downgrades to ^5.0.0

**Comment by guybedford** [comment]
Thanks, I've updated in https://github.com/jspm/jspm-cli/commit/e011c2ed7405a57a8f90f37e3dde43aef824c288.

**Comment by kevinmpowell** [comment]
I'm still seeing this issue after updating to jspm 0.15.5

**Comment by guybedford** [comment]
@kevinmpowell you'll need to update Babel via `jspm update --dev` or `jspm dl-loader`.

**Comment by kevinmpowell** [comment]
@guybedford, yep that was my issue. Thanks for responding!
