### ISSUE TITLE
Don't check config.js into version control.

### ISSUE THREAD

**Issue by Zoltu** [jspm/jspm-cli#711]
On https://github.com/jspm/jspm-cli/wiki/Getting-Started it recommends checking config.js into version control.  However, this is a generated file that can be largely derived from package.json.  If someone changes package.json, this file will need to change as well.

I believe there are some options at the top of config.js that are not derived settings.  These should be split out into a separate file so that they may be checked into source control without having to check in all of the mappings (which can be regenerated on `jspm install`).

**Comment by guybedford** [comment]
You do want to check all of config into version control. It's the full representation of your dependency tree.

**Comment by Zoltu** [comment]
In my experience, running `jspm install` regenerates the full file.  Is there something about the contents that are not regeneratable?

**Comment by guybedford** [comment]
Yes - if you come back to the project in a month and new versions of all the dependencies exist, without the same config present `jspm install` will install the new dependencies and not the proven reliable versions you had before.

**Comment by Zoltu** [comment]
Take the scenario when I have a clean repo (no `jspm_packages`), a `package.json` with a jspm dependency on `foo@^1.2.3`, a `config.js` with a dependency of `foo@1.2.3`, and package foo is available as 1.2.4.

Will `jspm install` fetch `1.2.3` or will it fetch `1.2.4`?

My underlying problem here is the redundant information stored in the repository.  Redundant information has a tendency to get out of sync and cause a lot of headache.  Perhaps a better solution is to not store dependency information in package.json?  What value does the dependency information in `package.json` provide if `config.js` exists?

If the answer to the above question is `1.2.3` then it seems that having `^1.2.3` in `package.json` adds no value.  If the answer to the above question is `1.2.4` then it seems that `config.js` adds no value.

Note: It is likely I am just missing a fundamental concept here, I am interested in being enlightened if in that case.

**Comment by guybedford** [comment]
`jspm install` will fetch `foo@1.2.3` as the `--lock` option is implicit for argumentless installs.

The package.json represents the upgrade paths to be tested, while the config file represents the exact current state. They are two very separate things - the intended install and the actual install. The `^1.2.3` in the install tells `jspm update` how it can update the package.

**Comment by lookfirst** [comment]
Remember also that your dependency `foo` in `package.json` might have a dependency on `bar@^1.2.3`. You might want to store that resolved version somewhere too.

**Comment by Zoltu** [comment]
I am sufficiently convinced that `config.js` is necessary.  I am now less sure about the value added by having the dependencies listed in `package.json`.

If I understand correctly, if the user is just doing `jspm install` then the dependency information stored in `package.json` is redundant and adds no value.  It sounds like the intent however is to have it add value when the user runs `jspm update`.  Presumably if the `package.json` dependency begins with a `^` then the latest patch version will be fetched, if it begins with a `~` then the latest minor version will be fetched.  I also assume that `config.js` will be updated at this time.

My question then is why not just put the `~` or `^` into `config.js` and have them be ignored when running `jspm install` and used when running `jspm update`?  If I am not mistaken, this would result in the same behavior as right now, but remove the duplication of dependency information in two different files.

**Comment by lookfirst** [comment]
`package.json` is the dependencies for your project.
`config.js` is the resolved dependencies.

They are two separate things.

**Comment by lookfirst** [comment]
Here is another way to think about it... with npm, you have a `package.json` and a bunch of dependencies listed in there. When you `npm install`, it downloads a bunch of files and puts them into a folder tree called `node_modules`.

Since the web doesn't have a directory structure, you need to specify that structure somewhere. That structure is `config.js`.

**Comment by Zoltu** [comment]
Coming from NPM and NuGet, the situation you have described is exactly why I am confused.  In both cases, there is a single file that defines dependencies (and is checked into version control) and everything else is derived from that file (and left out of version control).  In this case, there are two files that define dependencies (both checked into version control).

Perhaps it would help if someone can explain to me why the dependencies and the resolved dependencies are split into two files?  What benefit do you have from splitting the two?

If my `package.json` says `foo@^1.2.1` and my `config.js` says `foo@1.2.3`, what do I gain from this?  Couldn't config.js just include the `^`?  What information is added by having the `1.2.1` in the package.json?  From what I can tell, it is telling me the version I tried to install, but have likely never actually tested against since when I tried to install 1.2.1 I really got 1.2.3 pulled down into my config.js.  In fact, I would argue (tentatively) that package.json listing 1.2.1 in this case is mis-information because it implies that 1.2.1 would work, when really that is unknown since I may have only ever tested against 1.2.3.

**Comment by lookfirst** [comment]
`config.js` maps to the specific version in the `jspm_packages` folder. Since `config.js` is used in the browser as configuration for SystemJS, there is no way to know what is in the `jspm_packages` folder is a specific version. You need some configuration that resolves `import 'angular'` to `jspm_packages/github/angular/bower-angular@1.3.15.js`. 

You could store this in `package.json`, but sending it to the browser doesn't sound like a great idea as it could contain all sorts of stuff.

Some people suggest making you type `import 'angular@1.3.15'`, but that seems broken. I'd hate to type version numbers into my source files.

Server based solutions do not suffer from this issue because npm doesn't install things with a resolved version number. It just installs `node_modules/gulp`. 

One could argue that the flattened tree of jspm is not a good idea, but I think that might be hard to resolve given that browsers don't (yet) support the concept of isolated dependencies.

**Comment by Zoltu** [comment]
It seems that there are two fundamental concepts at play here.  One is the known-good-version.  This information is stored in `config.js`.  When someone does `jspm install`, `config.js` is read and the exact versions of everything listed are downloaded.

The other concept at play here is what to do when upgrading a package.  Currently, that information is stored in `package.json` in the form of `<identifier>@<upgradepath><version>`.  The version number found here should *not* be used as the "upgrade from" source.  The version here is not what you have been running against so if you tell JSPM you want to do a minor update, it should be a minor update to what you are *actually* using which is in `config.js`.

If the assertion above is correct you could trim `package.json` down to be just `<identifier>@<upgradepath>`.  This is fine and we have removed some useless (and confusing) information.  However, once that is done the logical next step is to realize, "we already have the identifiers for everything listed over in `config.js`, why not just move the upgrade path information into that file?"  To me this seems very reasonable.  The most reasonable way to do this IMO would be to include them next to the version number in the same way (though I don't see a problem with other methodologies).

I believe that the misunderstanding found in this thread stems from either my assertion above about version in `package.json` being irrelevant or from something that prevents upgrade path information from being stored in `config.js` (this seems like a solvable technical problem, not a theoretical problem).

Side note: @lookfirst, you mentioned "flattened tree of jspm".  What do you mean by this?

**Comment by OrKoN** [comment]
I have found a nice article explaining the reasons for having config.js https://blog.engineyard.com/2014/composer-its-all-about-the-lock-file (although it's about composer) + jspm needs config.js for resolving the module names to actual server paths. In my opinion, it's good to keep config.js separately from package.json because one keeps the state of an actual installation and another one describes top-level dependencies of the package. I think the analogy with a bill(config.js) and a menu (package.json) works for this case.

**Comment by lookfirst** [comment]
> Side note: @lookfirst, you mentioned "flattened tree of jspm". What do you mean by this?

When you install something with npm, and that thing has dependencies, they get put into a  node_modules folder within that thing you just installed. This is a recursive operation.

jspm lays everything jspm_packages out flat and appends version numbers to the folder names to avoid conflicts.

**Comment by ericnewton76** [comment]
So now that npm has the package-lock.json, I believe the OP is still correct, that the maps should NOT be part of config.js, but should be either config-lock.js or config-map.js that gets the resolved package numbers, and can be checked in separately from config.js, which holds things like your transpiler, babelOptions for specific packages, etc.

jspm possibly should resolve package versions like npm, into a separate file.  You're mixing configuration with output of dependency resolution, which makes it messy from a source control standpoint.
