### ISSUE TITLE
Installing and working with same library (and dependencies) from different endpoints

### ISSUE THREAD

**Issue by nkoterba** [jspm/jspm-cli#716]
This submission is more a philosophical/best-practice question.

1) I've noticed that some libraries exhibit totally different "installation" behavior when installed via npm vs github.  For an example, see https://github.com/angular/material/issues/2581.

Is this a responsibility of the package maintainer, or should preference always be given to one or another endpoint?

2) I noticed in the current documentation it states that when a library is available in both npm and github, the npm endpoint should be given preference: https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm#npm. However, I've noticed that by default in many cases:
```javascript
jspm install <some-package>
```
often pulls from github even if an npm package exists.  Should the documentation be updated or the code to try npm endpoints first?

3) I've encountered the situation with Angular and Angular modules where if you install a module via github (e.g. `jspm install angular-material`) and it has as a dependency on jspm:github:angular it will install the github version of angular.  However, if I also explicitly include angular in my application but install it via npm (e.g. `jspm install npm:angular`), my application now shows that Angular is being loaded twice (once by the angular module angular-material and by my app itself).  Here is an example of the system.config file:

```javascript
System.config({
  "map": {
    "angular": "npm:angular@1.3.15",  <-- Angular via NPM
    "angular-material": "github:angular/bower-material@0.8.3",
    "babel": "npm:babel-core@5.1.11",
    "babel-runtime": "npm:babel-runtime@5.1.11",
    "core-js": "npm:core-js@0.8.4",
    "github:angular/bower-material@0.8.3": {
      "angular": "github:angular/bower-angular@1.3.15", <-- Angular via github
      "angular-animate": "github:angular/bower-angular-animate@1.3.15",
      "angular-aria": "github:angular/bower-angular-aria@1.3.15",
      "css": "github:systemjs/plugin-css@0.1.10"
    },
```

I know this is an **angular** specific problem in that angular is a *global* library and expects to only be loaded once.  So should the bower-material not load angular and force users to **explicitly** and **manually** load each of its dependencies to ensure no collisions?  Or do I as an end-user need to make sure I'm using the same "mapping" endpoint (e.g. npm or github) whenever a library is referenced as a dependency?

As a follow-up, is there a way to tell jspm that a Package A defined in the `System.config.map` with one "key" name is actually the same as another Package B with a different "key" name, e.g. do aliases exist?

```javascript
// Does jspm support this?
npm:angular@1.3.15 === github:angular/bower-angular@1.3.15
```

**Comment by lookfirst** [comment]
Yup....  I can hear @guybedford groan now... cross repo dependency resolution isn't implemented. And it is a huge problem. I make github my primary source so that I can always fork the repo if I need to and 'fix' it.

**Comment by guybedford** [comment]
These seems to come up quite a bit especially with reference to Angular.

Are the Angular team actively pushing the npm or Bower repo as the main one? Whatever they are pushing we should really be going with.

It's a little worrying if npm is the main one, as the boat has set sail now with all our overrides using the GitHub version.

**Comment by lookfirst** [comment]
Their tutorial mentions bower. https://docs.angularjs.org/tutorial

**Comment by guybedford** [comment]
Interestingly one way of doing this would be by relying specifically on the jspm registry in our angular projects:

```json
{
  "dependencies": {
    "angular": "jspm:angular@^1.2.3"
  }
}
```

Where the above is in reference to the jspm registry. This way we can move the reference over time in the jspm registry, and carry the whole ecosystem with it.

**Comment by lookfirst** [comment]
The real problem here is that it is easily possible to get into a situation of loading the same dependency more than once. Angular is just one example.

**Comment by nkoterba** [comment]
@lookfirst Agreed that Angular is just one example of a situation I think **could** arise in the future with different library providers using different sources for their dependencies that may or may not conflict with the application developer's own use of libraries (though global or singleton libs like Angular, jQuery, etc. are fewer and far between nowadays (thankfully) so specific workarounds are probably possible).

@guybedford I know at least the Angular Material Design team is using or plans to support and/or use jspm so specifying the dependencies as "jspm:xxx" would be a clever way to go.

As for Angular itself, I find the github directories (which all seem to be setup to publish to bower) tend to work better and are more updated than npm equivalents (which Angular/Google has only recently started posting to and exposing proper CommonJS components).  I think this is because a lot of people still rely on bower  to manage their front end development so Google/Angular teams are still publishing to bower and hosting the source via github in projects named "bower-xxx".

I got myself into trouble because after reading the JSPM documents and it suggesting NPM over Github (as well as some other websites saying to use NPM over Github when available), I had Angular installed from both npm and github when using jspm.

The other, probably more Angular-specific, issue I encountered is that some Angular modules seem to want to load Angular while others just expose their module and when Angular is installed from two different endpoints SystemJS doesn't realize they are the same thing and loads it twice.  

Most of my original post was just to address:
- Should I be using NPM or Github versions of libraries when using JSPM?  Or is it really just trial and error until I get one that works correctly.
- Are there any concerns or potential future issues when two identical libraries loaded from different endpoints?

**Comment by guybedford** [comment]
The jspm registry is designed to help alleviate this conflict by providing the default best choice for jspm - `jspm install angular` will give the GitHub bower repo for Angular.

Where something isn't in the jspm registry already, it really is just trial and error to see what works best for jspm. The major concern is - what is the primary publishing environment for the author? I get the feling more and more this will be npm as users move away from Bower and towards npm for dependency management.

In terms of identical libraries from different endpoints, if they are jspm-aware it is for the publisher to be aware they are aligning with the jspm registry choice of using the primary registry for a given package. If they are not jspm-aware, then an override can fix it up instantly. In both cases we're fine.

**Comment by nkoterba** [comment]
@guybedford Thanks for the timely answers!

So the install preference is:
1) Use the jpm registry's choice and assume package maintainers keep the registry properly updated
2) Use trial and error between npm and github to get things working

Agreed that bower seems to be losing ground to npm.

Roger, on using a shim override to specifically define which dependencies a package will use if I know they are identical.

Great work so far on jspm...really enjoying it and the support! 

Am going to close this issue as all my questions have been addressed.

**Comment by lookfirst** [comment]
Sure, the end result after a lot of hacking is that we are fine. The problem is the confusion of when it is a problem. It would be nice if the tooling was able to suggest a warning that hey, you might be installing multiple versions of the same thing across repositories.

**Comment by nfriend** [comment]
Just ran into this situation with d3.  Installing d3 directly pulls from GitHub, while installing d3 indirectly (as a nested dependency of angular-nvd3) installs from npm.  The mismatch was causing the library to load twice (even though they were the same version), and as a result any d3 plugins that were loaded on the first instance of d3 were blown away by the second version.
