### ISSUE TITLE
Bundling babel/polyfill

### ISSUE THREAD

**Issue by nd0ut** [jspm/jspm-cli#717]
Hello! I'm trying to bundle `babel/polyfill` and here the problem that depTree doesn't build properly.
`jspm bundle babel/polyfill`
```bash
     Building the bundle tree for babel/polyfill...
     
       npm:babel-core@5.1.13/polyfill
     
ok   Built into build.js with source maps, unminified.
```
```javascript
"format register";
System.register("npm:babel-core@5.1.13/polyfill", [], false, function(__require, __exports, __module) {
  System.get("@@global-helpers").prepareGlobal(__module.id, []);
  (function() {
    "format global";
    module.exports = require("./lib/babel/polyfill");
  }).call(System.global);
  return System.get("@@global-helpers").retrieveGlobal(__module.id, false);
});

//# sourceMappingURL=build.js.map
```
I think there is something wrong with module format. I go to `jspm_packages/babel-core@5.1.1.13/.jspm.json` and saw that format is global. Why not cjs?

**Comment by guybedford** [comment]
Thanks for posting - I've updated the Babel override to make this work. Try reinstalling with `jspm install babel`, and let me know if you have any further issues at all.

**Comment by nd0ut** [comment]
@guybedford yeah, now it's ok. Thanks.
