### ISSUE TITLE
Distinguish between network errors and other errors in registry API

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#718]
Currently, a non-network error like invalid auth will result in retries.

We should ensure that errors are easy to classify to be able to only run retry functionality for network errors specifically.

Currently we just have one error format - a promise rejection of the API.

Perhaps we can just have a `networkError` property on the error object itself:

```javascript
var e = new Error('No response!');
e.networkError = true;
throw e;
```

**Comment by crisptrutski** [comment]
@guybedford ugly, duplicated code, let me know what you think
