### ISSUE TITLE
Allow package specific registries

### ISSUE THREAD

**Issue by matoilic** [jspm/jspm-cli#719]
When using custom registries (e.g. through jspm-git) it would be useful to store those information within the associated project. Currently every developer who is working on the project needs to create the registry entries manually. Same thing if you switch the workstation.

One possibility would be to allow registries to be defined in package.json under jspm.registries. This would require that the registry loader not only looks in the global config for registries but also in the package config. The package config would have precedence over the global one.

I would make the necessary changes if there is a general interest for such a feature.

**Comment by guybedford** [comment]
Thanks for posting - we're currently looking at supporting this feature via a `jspmrc` or similar at https://github.com/jspm/jspm-cli/issues/190.
