### ISSUE TITLE
ENOENT when bundling package with npm:html-minifier

### ISSUE THREAD

**Issue by marcoms** [jspm/jspm-cli#720]
I am facing troubles trying to install `npm:html-minifier` properly - it seems whenever I try to use it, it fails because it can't find `htmlparser.js` in its `dist/` directory...

Below is a simple test case:

	$>  jspm init
	...
	$>  jspm install npm:html-minifier
	...
	$>  jspm inspect npm:html-minifier
		
		Installed versions of npm:html-minifier
		
		html-minifier 0.7.2 (^0.7.2)

	$>  nano -wO foo.js
	$>  cat foo.js                                                                                                                                                            Wed 29 Apr 20:39:30 BST 2015
	import min from "html-minifier";

	console.log(min);
	$>  jspm bundle-sfx foo bundle.js
		Building the single-file sfx bundle for foo...

	err  Error: Error loading "npm:html-minifier@0.7.2/dist/htmlparser" at file:/home/[REDACTED]/jspmt/jspm_packages/npm/html-minifier@0.7.2/dist/htmlparser.js
		Error loading "npm:html-minifier@0.7.2/dist/htmlparser" from "foo" at file:/home/[REDACTED]/jspmt/foo.js
		ENOENT, open '/home/[REDACTED]/jspmt/jspm_packages/npm/html-minifier@0.7.2/dist/htmlparser.js'
			at Error (native)
	$>  ls jspm_packages/npm/html-minifier@0.7.2/dist/                                                                                                                          Wed 29 Apr 20:34:00 BST 2015
	htmlminifier.js  htmlminifier.min.js

**Comment by guybedford** [comment]
@marcoms this is because the library is a global script on npm, that contains require statements.

Try running `jspm install npm:html-minifier -o "{format: 'global', dependencies: {}}"`

**Comment by guybedford** [comment]
Let me know if you need any further help here at all.
