### ISSUE TITLE
Support Registry packages locally installed

### ISSUE THREAD

**Issue by nkoterba** [jspm/jspm-cli#722]
I'm trying to allow other developers to setup/build/serve our project by just checking out the project and doing:
```javascript
npm install
```

I've got a `postinstall` hook in our package.json that in turn runs `jspm install`.

However, we use several 3rd party packages that are **NOT** hosted on github/npm.  They are private git repos with username/password as well as our internal git server.

I've found the [jspm-git](https://www.npmjs.com/package/jspm-git) registry package.

On their npm page, they say you can install **jspm-git** globally or locally.  Ideally, I'd like to install it *locally* so as not to clutter up the person's global npm libraries if possible.
```javascript
npm install jspm-git --save-dev
```

I could then add things to the `postinstall` hook that creates the necessary registries, e.g.:
```javascript
jspm registry create kendogit jspm-git
jspm registry create internalgit jspm-git
```

However, when I install jspm-git **locally**, I get the following error:
```javascript
$ jspm registry create kendogit jspm-git

err  Registry handler`jspm-git` not installed.
```

If I install `jspm-git` **globally**, everything works.

Is it possible to allow `jspm registry create` to check the local `node_modules` folder for possible registry endpoints/packages?

**Comment by guybedford** [comment]
@nkoterba I believe that for a local install of jspm-git to work, you need to have a local install of jspm as well. If this is not the case, do let me know.

**Comment by nkoterba** [comment]
@guybedford Ok I will check it out and report back...as an aside I do think it's rather commendable that you're responding in the wee hours of the morning...

Appreciate your dedication and commitment to systemjs and jspm...we are betting on it as the future and with web frameworks these days it's always a crap shoot...

So thank you for your dedication and commitment...

**Comment by guybedford** [comment]
@nkoterba you're very welcome, if you need any further help do feel free to ask anytime. I'm in South Africa so it's a different timezone! But yes like to respond quickly (mostly to keep issue queues under control :).
