### ISSUE TITLE
question re ie8

### ISSUE THREAD

**Issue by Ir1sh** [jspm/jspm-cli#723]
I just watched the javascript in 2015 demo on the homepage.  looks great.

At work I need to support ie8 for the moment.  From the video it seems that if we do not write es6 the file does not get compiled.  This is great.  However does using the module loader itself require a compilation step or anything else that would result in it not working on ie8?

**Comment by AutoSponge** [comment]
We're supporting ie8 in production with the appropriate pollyfills:

```
<script src=".../es5-shim.min.js"></script>
<script src=".../es5-sham.min.js"></script>
<script src=".../babel-polyfill.js"></script>
<script src="bundle.js"></script>
```

We were only able to get IE8 to work with a bundle, never with System.import. The good news is, you can write (most) ES6 and it will work in IE8 (just don't use getters and setters).

**Comment by guybedford** [comment]
IE8 is supported so far as transpilers support IE8.
