### ISSUE TITLE
strictSSL option

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#725]
A global-level config option, which is added to endpoint options for each registry constructor. Then each registry implementation usage of `request` should follow it.

**Comment by smastous** [comment]
Hey Guy, I can take a crack at this.  I have it working with some test code, but want to make sure we're on the same page and let you know I'm working on it before submitting a PR.  

Are you thinking something like the following added to the global config?  
```json
"registries": {
    "github": {
      "timeouts": {
        "lookups": 60,
        "build": 120
      },
      "handler": "jspm-github",
      "remote": "https://github.jspm.io",
      "strictSSL": false
    }
   //others
  }
```

**Comment by guybedford** [comment]
@smastous it would be great if you're interested in working on this, thanks for offering!

I was thinking of something like - 

```
"strictSSL": false
"registries": {
    "github": {
      "timeouts": {
        "lookups": 60,
        "build": 120
      },
      "handler": "jspm-github",
      "remote": "https://github.jspm.io",
    }
   //others
  }
```

Where it is a global option that then gets specifically copied into the endpoint options (eg `registryOptions.strictSSL = globalConfig.config.strictSSL || true`).

Just let me know if you have any further questions.

**Comment by smastous** [comment]
Perfect!  That makes sense.  I will get to work and let you know if I run into anything.

**Comment by MaluTom** [comment]
Has this been released?

**Comment by guybedford** [comment]
@MaluTom yes, although it requires manually editing `~/.jspm/config` and setting `strictSSL: false` in the config file. It's not a workflow we want to encourage.

**Comment by MaluTom** [comment]
@guybedford - sorry, where exactly would I find ~/.jspm/config (I'm running a windows environment)

**Comment by smastous** [comment]
There is a .jspm folder in users/<your username>/appdata/local where you can find the global config.

**Comment by MaluTom** [comment]
@smastous I added strictSSL: false to the config file as follows -
```
 "registries": {
    "github": {
      "timeouts": {
        "lookup": 60,
        "build": 120
      },
      "remote": "https://github.jspm.io",
      "auth": "***",
      "maxRepoSize": 0,
      "handler": "jspm-github",
      "strictSSL": false
    },

```

**Comment by guybedford** [comment]
If you want it for everything, add it as a base-level option next to registries.

**Comment by mikehaas763** [comment]
Assuming that this option was created to fix #721 there may be a better and alternative solution as well. NPM has two config options `ca` and `cafile` which take a pem format public cert authority directly or the path to file that contains the cert. I use these options at work in my .npmrc file to help with cert issues with npm. Maybe something similar could be implemented with jspm?

**Comment by smastous** [comment]
Hey Mike, I think custom certificate support can and should be implemented in addition to the strictssl option for those who want to maintain the security when needed.  The request library used in jspm supports certificates.  It's just a matter of wiring it up.  

That said, there are some environments for which even adding cert support doesn't easily solve the problem, so having a nuclear option is still important.  For instance, my company uses a weird proxy setup with multiple self signed certs to do a man in the middle attack on employees.  The certificates are all messed up, so we can't get them to work even when installed locally.

**Comment by lee-tunnicliffe** [comment]
I have been having this problem and editing global-config to add strictSSL: false didn't work for me. 

Editing registry.js and hardcoding strictSSL to false fixes the issue. It's almost as if the global-config.js isn't being read. Has anyone else found this? Suggestions?

**Comment by guybedford** [comment]
@lee-tunnicliffe did you definitely edit `~/.jspm/config` and add a `"strictSSL": false` property? `jspm config strictSSL false` doesn't work properly unfortunately as we handle config options as strings.

**Comment by lee-tunnicliffe** [comment]
@guybedford My company has relaxed the proxy for git now and such I can't reproduce the problem anymore. I was sure I'd done that but can't now double check reliably. Anyway, I'm not having the issue anymore, which is good :). Thanks for your response.

**Comment by sofoklismalakelis** [comment]
@guybedford I've added the intermediate certificate to git, and git works.
However I still get this error when I do this: 

jspm install -y

I can't find a  way to turn off strictSSL

warn Error on locate for github:components/plugin-css, retrying (1).
     Error: self signed certificate in certificate chain
         at Error (native)
         at TLSSocket.<anonymous> (_tls_wrap.js:1022:38)
         at emitNone (events.js:67:13)
         at TLSSocket.emit (events.js:166:7)
         at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._finishInit (_tls_wrap.js:586:8)
         at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ssl.onhandshakedone(_tls_wrap.js:428:38)

**Comment by guybedford** [comment]
@sofoklismalakelis this should just be `jspm config strictSSL false`?

**Comment by sofoklismalakelis** [comment]
I don’t remember what I did.

But this worked: jspm config strictSSL false

Thanks a lot!
