### ISSUE TITLE
Handling of invalid versions

### ISSUE THREAD

**Issue by piuccio** [jspm/jspm-cli#726]
Not sure if you're planning to fix this, but there's an inconsistency in the way versions are handled.

### NPM
```
"dependencies": {
    "jspm": "^0.15.20"
}
```
this throws an error
> `No compatible version found: jspm@'>=0.15.20 <0.16.0'`

### JSPM
```
"dependencies": {
    "es5-shim": "npm:es5-shim@^4.1.50"
}
```
this works fine
> `ok   Up to date - es5-shim as npm:es5-shim@^4.1.50 (4.1.1)`

**Comment by guybedford** [comment]
This is how semver ranges are defined to work as in https://github.com/npm/node-semver#caret-ranges-123-025-004. See also http://semver.npmjs.com/ for experimentation.

**Comment by piuccio** [comment]
Exactly, npm works fine, but in jspm `npm:es5-shim@^4.1.50` should be converted to `>= 4.1.50 <4.2.0`. The installed version is `4.1.1` which is outside of the range.

**Comment by guybedford** [comment]
Are you running an argumentless `jspm install` here?

Because jspm install will always use the existing ranges in config.js to maintain a version lock.

We could look at adding a flag like `jspm install --unlock` to ensure the package.json ranges take preference, although this would be roughly equivalent to `jspm update` anyway.

I see your point though, any suggestions for a way around the confusion welcome.

**Comment by guybedford** [comment]
Perhaps we just need to alter the message here - 

`Installing from config.js version locks...`

Or something at the start or end of the install.

**Comment by guybedford** [comment]
If you wanted to bump a single install, you could alter the package.json and then run `jspm update es5-shim`. Would that cover the use case?

**Comment by piuccio** [comment]
I see. Yes my steps were

```
jspm install --save es5-shim
# update the package.json
jspm install
```

That's how I usually do in npm, I'll have to remember to use `jspm update`

**Comment by guybedford** [comment]
Glad that clarifies. We will look at improving documentation around these workflows in future.
