### ISSUE TITLE
Sparse Checkout of Github Libraries

### ISSUE THREAD

**Issue by nkoterba** [jspm/jspm-cli#727]
So I'm using Google's Material Design icons in my webapp: https://github.com/google/material-design-icons

However, to download the entire library via NPM or github is **~57 MB**.

In our webapp, we only use/require the `svg 24x24 icons`.

With git, it's possible to do a sparse checkout and identify which files to indeed checkout, e.g.:

```javascript
'git init; ' +
'git config core.sparsecheckout true; ' +
'echo "*/svg/production/*_24px.svg" >> .git/info/sparse-checkout; ' +
'git remote add -f origin git://github.com/google/material-design-icons.git; ' +
'git pull origin master'
```

Is there any way using either jspm `overiddes` or other strategy to limit what's "checked out".  Note that the files I need are in various directories so the use of a glob pattern is necessary.  

Does a local override that defines `files` or `directories` support glob patterns?

Thanks in advance!

**Comment by guybedford** [comment]
This is a very interesting proposal - thanks for posting. Unfortunately there isn't a way to do that currently.

In the past we used to maintain shallow cloned repos that we'd copy the package from when installing from GitHub, but this was moved to direct downloading of the tarballs provided by GitHub, as in general this provides the fastest transport.

Note that in this case, you're asking for your package download to be different to the package download for other users, which isn't a good property to design into a package manager.

If you need this to run on CI, it may be worth focusing efforts on pre-populating the cache etc?

**Comment by glen-84** [comment]
:+1:

There's no point in downloading tests, samples, build tasks etc. when you only need the built library for inclusion in your project.

**Comment by nkoterba** [comment]
@guybedford @glen-84 Would a way to "enable" this situation be to use a local override in `package.json` that uses `directories` and `files` to limit what's downloaded?

E.g.
```javascript
"github:hoxton-one/golden-layout@1.0.8": {
        "files": [
          "dist/goldenlayout",
          "src/css/goldenlayout-base.css",
          "src/css/goldenlayout-dark-theme.css"
        ]
      }
```

Based on the documentation, `files` does support glob patterns so perhaps that can be used to "simulate" a sparse github checkout?

https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm#files

So I tried that:
```javascript
      "github:material-design-icons@1.0.1": {
        "files": [
          "*/svg/production/*24px.svg"
        ]
      }
```

but all the files were still downloaded from github so I'm thinking my syntax above was wrong or incorrect (perhaps wildcard + globs are not supported in jspm `files`?).

Since I don't want a ~57 MB dependency that must be downloaded during clean builds and CI we have moved to using Google Font Icons and another library so we have an alternative solution.

I leave it up to @guybedford if he wants to close this issue or leave it open for "future" discussion.

**Comment by glen-84** [comment]
@nkoterba,

As far as I understand it, the `files` option (and other similar options) only apply *after* all files have been downloaded, because the Git repo is not cloned, it is downloaded as a tarball (as mentioned by Guy above).

Therefore, this is not currently possible, but I definitely think that it would be a worthwhile addition.

**Comment by glen-84** [comment]
I guess this depends on https://github.com/jspm/github/issues/6.

**Comment by glen-84** [comment]
@nkoterba,

I tried the example that you gave, but I get:

    error: Sparse checkout leaves no entry on working directory

I think that you have to first clone the repo (see http://stackoverflow.com/a/2467629/221528), which means that you won't be able to only download a specific set of files.

[git archive](http://git-scm.com/docs/git-archive) or using raw.githubusercontent.com may be more efficient.

**Comment by glen-84** [comment]
Sorry, my sparse-checkout file was incorrectly formatted (it included the quotation marks).

I tried again, and it appears to download 18.15 MiB, which is obviously an improvement, but still quite a bit larger than necessary.

**Comment by nkoterba** [comment]
@glen-84 Ah ok...yes I just checked and the sparse checkout does indeed work.

As you mentioned, the checkout is still quite large: 31.6 MB on my machine.

Half the size of the original download, but the actual files I need are < 6 MB.  So where's the additional size coming from?

The culprit is the `index` file (8 MB) and the pack object (19 MB) under `.git`.  These are internal git files used obviously by git.  I agree that `git archive` or other methods may be more efficient.  Ideally, this download should be < 6 MB for the files I need...

**Comment by glen-84** [comment]
@nkoterba See https://github.com/jspm/github/issues/6#issuecomment-101019052.

**Comment by crissdev** [comment]
I believe the solution should come from the _referenced_ project instead of `jspm`. For instance, if `material-design-icons` would be split in various pieces then it would be very convenient to just install only the needed packages. As for `material-design-icons` I think there's already some issue open for that but I'll go one more time to check it out and reference this issue there.

**Comment by glen-84** [comment]
@crissdev I disagree. While this may work in simple scenarios, you can't know what each individual developer may or may not require, and there will be too much administration involved in maintaining multiple separate packages.

**Comment by crissdev** [comment]
@glen-84 Here are some examples that split their main package. This doesn't mean you can't install the full package though.

* [change-case](https://github.com/blakeembrey/change-case) 
* [lodash](https://github.com/lodash/lodash)
* [underscore](https://github.com/jashkenas/underscore)

Administration of separate packages woudn't be a hassle as long as the process is automated - at least that's what the aforementioned projects do.

**Comment by glen-84** [comment]
@crissdev I didn't say that it's not possible, I said that you can't cover all scenarios in this way. What if I just want a single file, like `semantic.css` from [Semantic-UI](https://github.com/Semantic-Org/Semantic-UI/)?

I almost never want tests and examples, does this mean that every single package must now make a separate version available without these folders?

**Comment by crissdev** [comment]
@glen-84 I agree not all scenarios can be covered but at least most of them. Project maintainers should have just enough feedback to split the package in the right pieces :smile:

As for packages published with tests and other stuff...IMHO, that's either because they don't care, don't know or are lazy. I really dislike seeing anything else than what I need in a dependency - Bower, NPM or whatever.

**Comment by glen-84** [comment]
@crissdev, remember that this issue is about Git, not about NPM, so tests may be in the Git repo but not in the NPM package(s).

**Comment by Zoltu** [comment]
With a non-zero amount of work, JSPM could be taught how to fetch individual files from git, rather than cloning the entire repo.  Then one could write an override that did something like glob the dist folder of a git repo.  If I were JSPM maintainer, I would probably put this on the "wish list" though, as it is a lot of work and all it does is make downloads a bit smaller.

**Comment by guybedford** [comment]
Moving this discussion to https://github.com/jspm/github/issues/58.
