### ISSUE TITLE
Add support for <= on a version that doesn't exist

### ISSUE THREAD

**Issue by admwx7** [jspm/jspm-cli#728]
Right now if you run `jspm install gulp-karma` you will get `err  No version match found for npm:karma@~0.13.0`, running through the package.json files on github (from npm) for the dependencies you'll find `"karma": ">=0.10 <=0.13"` as a peer dependency of gulp-karma, version 0.13 does not exist for karma, this shouldn't throw an error though, it should just look for a version number that satisfies the range and is valid.

**Comment by lookfirst** [comment]
Yet another reason to use npm itself to do dep resolution and downloading. Re-inventing npm is a losing battle.

**Comment by admwx7** [comment]
That is my immediate solution to the problem, however I believe this would
be an issue with versioning in general that would need to be resolved.

**Comment by lookfirst** [comment]
Right. My beef is that jspm has invented its own version of npm. It doesn't actually just use npm to do downloads and then munge files from node_modules into jspm_packages. As a result issues like this and others keeps cropping up. Ideally jspm would just use the npm client and server to do all the version resolution, downloading, auth, caching, etc. it would make everything a lot simpler and more stable. It would be easier to support other packaging systems too as the code would be less intermingled. I wrote a quick test of this idea and it was way simpler code.

**Comment by guybedford** [comment]
The argument here is that these types of highly open ranges are only ever seen in peer dependencies.

The way we are tackling this is to allow highly flexible peer dependency conflict resolution. This is being tracked in https://github.com/jspm/jspm-cli/issues/490.

If this still comes up as an issue, after implementing flexible peer dependencies resolution, then I'd be happy to reconsider then.
