### ISSUE TITLE
.config/jspm.json

### ISSUE THREAD

**Issue by shannonmoeller** [jspm/jspm-cli#729]
I could very easily see `jspm` one day becoming as big, if not bigger, than `bower`, `component`, and even `npm`. While I like that jspm makes use of `package.json`, I can see a need in the future for a `jspm.json` config. With that in mind, I'd love to see it provided with the option to put it in a `.config/` dir in the root of a repo.

As more and more tools have become best-practice when authoring npm modules, from `package.json` to `.*rc` to `*file.js`, the root directory of projects has become a very loud place. This dot-noise pushes README content farther and farther down the main page of git repos.

![screenshot 2015-05-01 21 41 51](https://cloud.githubusercontent.com/assets/155164/7439468/e8f2ff9e-f04a-11e4-8c1b-4248379053e9.png)

What if the above could optionally be simplified to the following?

![screenshot 2015-05-01 21 50 12](https://cloud.githubusercontent.com/assets/155164/7439513/179455c2-f04c-11e4-9577-c3b73c2b01c3.png)

This is a simple example and that's already about a 30% vertical space savings. I started the conversation over in the [npm repo](https://github.com/npm/npm/issues/8159), but I'm also submitting issues to the `findup`, `karma`, `travis-ci` and `zuul` repos.

**Comment by shannonmoeller** [comment]
Basically, I'm recommending that the `.config/` directory be added to the list of default locations to check for configuration files for some of the most-used Node.js CLI tools. The idea here is to foster the use of [XDG Base Directory Specification](http://standards.freedesktop.org/basedir-spec/latest/index.html) where `$HOME` is a module's root directory to [declutter](http://unix.stackexchange.com/a/38871) module repos.

So the search would look like this where X is the current directory:

1. If X/file.ext exists, load it. STOP
2. If X/.config/file.ext exists, load it. STOP
3. Change X to parent directory. GO TO 1

Some modules allow the path to be configured in package.json, but that's replacing file noise with config noise and requires additional effort in every project.

**Comment by guybedford** [comment]
It's an interesting idea, and when we look at creating a `.jspmrc` or similar I'd be happy to support this algorithm.

As a side point - do you think it is worth using the `~/.config/jspm` directory instead of `~/.jspm`?

**Comment by guybedford** [comment]
Tracking in https://github.com/jspm/jspm-cli/issues/190, will close this as it's part of that same feature.
