### ISSUE TITLE
Introduce rootURL

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#730]
During builds, in order to do the right CSS normalization, source map normalization, `__filename` normalization for CommonJS and other resources it helps to know what the rootURL is, and currently we don't have anything to track this so have to assume that the baseURL is the rootURL.

We should introduce a `directories.rootURL` in the package.json which is assumed by default to be `baseURL`, unless otherwise specified.

This can then be copied down as a property of SystemJS during builds - `System.rootURL`. It would only be available in build environments and not in browsers. (it's just `new URL(baseURL).origin` in browsers, ie the absolute root of the browser baseURL).

Plugin builders, source maps normalization and formats can then utilize this value during builds.

**Comment by greduan** [comment]
I think this is just the problem I was running into today.

Because my page is being served with Node.js at `localhost:8080/admin` so JSPM stuff is under `localhost:8080/admin/jspm_packages` but when loading plugins JSPM tries `localhost:8080/jspm_packages` so it gives me 404s.

**Comment by guybedford** [comment]
This is effectively another `baseURL` concept and gets confusing quickly. It makes a lot more sense to deprecate baseURL in the long term here, as that is where the spec alignment happens.
