### ISSUE TITLE
Suggestion for bundling configuration to be defined in the package.json

### ISSUE THREAD

**Issue by Aaike** [jspm/jspm-cli#731]
It would be nice if we can predefine how bundles should be created in the package.json, for example:

```javascript
{
  "jspm": {
    "bundles": {
      "bundleA": {
        "options": {minify:true,inject:true}
        "packages": [
          'bootstrap',
          'some-other-module'
        ]
      },
      "path/to/bundleB": {
        "options": {minify:true,inject:true}
        "packages": [
          "prism",
          "showdown"
        ],
      },
      "bundleC": {
        "options": {minify:true,inject:true}
        "packages": [
          "app"
        ]
    }
  }
}
```
As projects get bigger it's often needed to create multiple bundles.

The short module names in the configuration can be resolved from the module mappings in the config.js to get the exact name and versions to use for bundling.

It's also a good idea in general i think to include the configuration for bundling with the package.
This would allow the `jspm bundle` command to be used without arguments.
So the exact same bundles can be easily generated in the future without having to note down which jspm commands to run in which sequence to get the correct bundles.

The bundles would naturally exclude things that are already defined in one of the other bundles. Much like the new arithmetic added recently `jspm bundle bundleA - bundleB - bundleC`

**Comment by lookfirst** [comment]
@Aaike You may want to look at the [systemjs-route-bundler](https://github.com/Swimlane/systemjs-route-bundler), which as its name suggests, bundles based on route definitions. I've found that it is a good way to separate bigger apps.

**Comment by guybedford** [comment]
This isn't something we'd put in the package.json but it has been considered for the builder here - https://github.com/systemjs/builder/pull/134.
