### ISSUE TITLE
Uncaught module 'xxx' not present.  Odd AMD behavior?

### ISSUE THREAD

**Issue by nkoterba** [jspm/jspm-cli#732]
Having issues using 3rd party JS library installed via `jspm-git`.  During `BuildSFX` System.register is not injected into `define` function correct...??

Details:
1) Using latest version of jspm (0.15.5)
2) Believe my dl-loader/babel/systemjs is up-to-date as well:
```javascript
     Using loader versions:
       es6-module-loader@0.16.6
       systemjs@0.16.11
     Looking up npm:babel-core
     Looking up npm:babel-runtime
     Looking up npm:core-js
     Updating registry cache...
ok   Up to date - babel-runtime as npm:babel-runtime@^5.1.13 (5.2.9)
ok   Up to date - babel as npm:babel-core@^5.1.13 (5.2.9)
```
3) I'm using `jspm-git` to install a Kendo UI library (HTML 5 widget library) from an access-controlled git repository hosted by Telerik (company that makes Kendo).
4) I've successfully added the registry for Kendo GIT server using `jspm-git` and downloaded source:
![image](https://cloud.githubusercontent.com/assets/2508944/7458281/0c806902-f248-11e4-8ead-dd62cf460847.png)
5) My development environment allows running code in "development" mode.  In this mode, BrowserSync serves up files in the jspm_packages directory when a 'System.import' or es6 import statement is used.  The Kendo UI library **is available** in this mode, as it's loaded directly from the filesystem: 
![image](https://cloud.githubusercontent.com/assets/2508944/7458333/7340d514-f248-11e4-8f61-b389314d7034.png)
6) When I run my application in production mode, I do **not** include the individual js files...they are all bundled into one JS file and this file is served to the browser via BrowserSync:
```javascript
/**
 * Create JS production bundle.
 */
gulp.task('bundle', 'Create JS production bundle', ['ngconstant'], function (cb) {
	var builder = new Builder();

	builder.loadConfig(snap.paths.systemjsconfig)
		.then(function () {
			builder.buildSFX(snap.paths.app.entry,
				snap.paths.tmp.scripts + 'build.js',
				{
					sourceMaps: true,
					config: {
						sourceRoot: snap.paths.tmp.scripts,
						keepModuleIdExtensions: true
					}
				})
				.then(function () {
					return cb();
				})
				.catch(function (ex) {
					cb(new Error(ex));
				});
		});
});
```
7) The application fails to load with the following displayed in Chrome console:
```javascript
Uncaught Module kendogit:bower-kendo-ui@2015.1.430/js/kendo.all.min not present
```

I tried to troubleshoot/resolve this situation myself but I'm still learning how the SystemJS/jspm/BundleSFX functionality all works.

Here's my current troubleshooting:
1) I confirmed that the Kendo UI Javascript library source **is** being included in my bundled `.js` file.
2) I confirmed that the Kendo UI IIFE is being added to the bundled `.js` file:
```javascript
(function() {
function define(){};  define.amd = {};
System.register("kendogit:bower-kendo-ui@2015.1.430", ["kendogit:bower-kendo-ui@2015.1.430/js/kendo.all.min"], false, function(__require, __exports, __module) {
  return (function(main) {
    return main;
  }).call(this, __require('kendogit:bower-kendo-ui@2015.1.430/js/kendo.all.min'));
});
})();
```

Where things are breaking down is as follows: 
* I use several other JS libraries that use AMD and noticed the source code seems to be modified to *inject* the System.Register statement, e.g.
**Moment.js**
Source:
```javascript
(function (global, factory) {
    typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() :
    typeof define === 'function' && define.amd ? define(factory) :
    global.moment = factory()
}(this, function () { 'use strict';
```
What appears in my bundled `.js` file:
```javascript
(function() {
function define(){};  define.amd = {};
"format amd";
(function(global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() : typeof define === 'function' && define.amd ? System.register("github:moment/moment@2.10.2/moment", [], false, typeof factory == "function" ? factory : function() {
    return factory;
  }) : global.moment = factory();
}(this, function() {
  'use strict';
```

Where `define(factory)` above in the moment.js source, it is replaced by:
```javascript
System.register("github:moment/moment@2.10.2/moment", [], false, typeof factory == "function" ? factory : function() {
    return factory;
  })
```

The same thing is true for HammerJS 1.1:
Source:
```javascript
// AMD export
if(typeof define == 'function' && define.amd) {
    define(function() {
        return Hammer;
    });
```

BundleSFX file:
```javascript
if (typeof define == 'function' && define.amd) {
    System.register("github:hammerjs/hammer.js@1.1.3/hammer", [], false, function() {
      return Hammer;
    });
```

Unfortunately, when I look at the Kendo UI *AMD* code section in the **bundled** js file, it looks like:
```javascript
typeof define == "function" && define.amd ? define : function(_, f) {
  f();
});
```

I could be *way-off* here or missing something else, but it seems like the **define** function in the line above should be 'injected' with something containing System.register('kendogit:bower-kendo-ui@2015.1.430/js/kendo.all.min').

I can provide additional code snippets, etc. to help troubleshoot, but wondering how to get Kendo UI's JS library to work in my application when bundling the JS into one file.

Perhaps I can overcome this issue with:
* Some local JSPM override on the Kendo UI library?

**Comment by guybedford** [comment]
Did you make any progress on this? It sounds like the Kendo UI library wasn't being detected as AMD format? Did you try adding meta to change that?

**Comment by nkoterba** [comment]
@guybedford Still having trouble with this issue.  

Adding this to `package.json`
```javascript
"kendogit:bower-kendo-ui@^2015.1.430": {
        "shim": {
          "kendogit:bower-kendo-ui@^2015.1.430": [
            "jquery",
            "angular"
          ]
        },
        "format": "amd"
      },
```

AND adding this to `config.js`
```javascript
  "meta": {
    "kendogit:bower-kendo-ui@2015.1.430": {
      "format": "amd"
    }
  },
```

Appears to make no difference in my situation.  I do have some insight though...

The file I'm trying to use is effectively defined as this:
```javascript
(function (f, define) {
	define([], f)
})(function () { 
      <<SOURCE CODE HERE>> 
}, typeof define == "function" && define.amd ? define : function (_, f) {
	f()
});
```

The generated javascript when running `bundleSFX` is:
```javascript
(function() {
function define(){};  define.amd = {};
(function(f, define) {  <-- Actual start of library source
  define([], f);
})(function() {
  <<SOURCE CODE HERE>>
}, typeof define == "function" && define.amd ? define : function(_, f) {
  f();
}); <-- Actual end of library source
})();
```

Here's my understanding of this process:
* SystemJS wraps the library source in a IIFE and creates the `define` function and sets `define.amd` to an empty object
* When the IIFE is executed, the library's source checks to see if `define` is a function (**IT IS**) and that define.amd exists (**IT DOES**).  If so, it then passes the library's source and the `define` function to the library's wrapper function which calls the `define` function on an empty array and the library's source.

However, since `define` is defined as an empty function, nothing happens.  My understanding is that SystemJS should somehow replace the `define` function with something...

If I *manually edit* the compiled javascript to look like this, everything works:
```javascript
(function() {
function define(){};  define.amd = {};
(function(f, define) {  <-- Actual start of library source
// REPLACE define([], f); WITH:
System.register("kendogit:bower-kendo-ui@2015.1.430/js/kendo.all.min", [""], false, function() { 
   return f(); 
});
})(function() {
  <<SOURCE CODE HERE>>
}, typeof define == "function" && define.amd ? define : function(_, f) {
  f();
}); <-- Actual end of library source
})();
```

Kendo UI is **supposed** to be an AMD project: http://docs.telerik.com/kendo-ui/using-kendo-with-requirejs

Any insight into this issue?  Does Kendo UI use an *unusual* AMD wrapping scheme?  Is my `meta` and/or `override` not actually working?

**Comment by guybedford** [comment]
@nkoterba you are exactly right - this is a bug. I've created https://github.com/systemjs/builder/issues/167 to track it.

**Comment by nkoterba** [comment]
@guybedford Thanks for making me feel not so crazy!

Without taking a peek inside the SystemJS builder code, I'm not sure how it *replaces* the AMD `define` function with the `System.register` code but it does seem like Kendo's use of an external functional wrapper does cause it to be missed by the "replacement" code.

Appreciate the help!
