### ISSUE TITLE
`jspm install` corrupts config.js `path` entries when using `System.config({ baseUrl })`

### ISSUE THREAD

**Issue by ohjames** [jspm/jspm-cli#733]
I have the following at the top of my `client/config.js`:

```javascript
System.config({
  "baseURL": "jslib",
  "transpiler": "babel",
  "babelOptions": {
    "optional": [
      "runtime"
    ]
  },
  "paths": {
    "*": "*.js",
    "github:*": "jspm_packages/github/*.js",
    "npm:*": "jspm_packages/npm/*.js"
  }
});
```

After `jspm install` it changes to read as such:
```javascript
System.config({
  "baseURL": "jslib",
  "transpiler": "babel",
  "babelOptions": {
    "optional": [
      "runtime"
    ]
  },
  "paths": {
    "*": "*.js",
    "github:*": "jslib/jspm_packages/github/*.js",
    "npm:*": "jslib/jspm_packages/npm/*.js"
  }
});
```

You can see `jslib` has been incorrectly prefixed to the `github` and `npm` fields in my `paths` (this causes the browser to try to load files starting with `jslib/jslib`).

**Comment by guybedford** [comment]
The client baseURL should only be set in the config.js and not in the package.json `directories.baseURL` as well. Make sure that one is empty.

**Comment by ohjames** [comment]
You mean only set in the `package.json` rather than the `config.js` I guess given the baseURL is needed to look up the config in the first place and given that's where `jspm init` puts it.

I see thanks, in my case I have `client/index.html` and `client/config.js` but all of the actual built files are in `client/jslib`. By adding the `jslib` component to `client/config.js` this works fine (except for `jspm install` changing the package). It allows me to separate all of my "built" dependencies into their own tree essentially.

Maybe this workflow isn't supported at the moment or isn't a good idea for some reason.

**Comment by guybedford** [comment]
No I mean only set in the `config.js` and not in the `package.json`. This is the _client baseURL_, while the package.json is the _server baseURL_.

**Comment by guybedford** [comment]
Both `baseURL` paths should point to the same effective server, the one in the file system of the server, and the other as the URL of the browser.

**Comment by ohjames** [comment]
That's exactly as I understood it, it still feels like I need both for this configuration though.

* server baseUrl = `client` = offset to client root directory containing `config.js` and `index.html`
* client baseUrl = `jslib` = offset for browser to use to load packages from (at `jslib`, or `client/jslib` according to the server directory).

If I set only the `config.js` baseUrl... now `jspm` will try to load `config.js` from the root directory but it isn't there, it's in `client`, then it can't even look up my `config.js`.

**Comment by ohjames** [comment]
... and if I put `config.js` in the same path as the `package.json` and only set `baseUrl` in `config.js` then now the client can't access `config.js` as the server serves the client resources from `client` and `config.js` is now in the parent of that directory.

**Comment by guybedford** [comment]
They need to refer to the same folder. I think your server baseURL should be `client/jslib` and your client baseURL can just be `jslib`.

**Comment by ohjames** [comment]
@guybedford Thanks so much for taking the time to help support me on this. Your suggestion works perfectly, I have to move the `config.js` to the build folder which I was hoping to avoid but that doesn't really matter.

Thanks once again.

**Comment by jashatton** [comment]
I have a question related to the baseUrl setting in package.json.  I am using JSPM with a Java project and our project layouts are not like Node or other platforms that serve assets off a filesystem through a web server.  Our web assets are served from an archive (jar) file and loaded through a Java classpath. My question is can we expect that the baseUrl attribute will stay in package.json.  It provides a means for us to place the config.js file where we need it in our setup.  If not do you have a recommendation that is future proof in case the baseUrl may go away for any reason? 

This is an example Java project layout: 
![sample_java_project](https://cloud.githubusercontent.com/assets/121117/9468860/974354fe-4b09-11e5-9367-af9d93e69724.PNG)

Thank you,
Jason

**Comment by guybedford** [comment]
Yes the baseURL will continue to be supported through the package.json directories.baseURL.

**Comment by jashatton** [comment]
Awesome thanks for the reply
