### ISSUE TITLE
self signed certificate in certificate chain error when configuring github enterprise

### ISSUE THREAD

**Issue by bhazen** [jspm/jspm-cli#734]
I'm attempting to set up a registry for our GitHub enterprise instance(replacing mycompany with the appropriate value in all usages):
```
jspm registry create mycompany jspm-github
```

When prompted I entered github.mycompany.net (have also tried without the github.)

When prompted for credentials I entered them and entered yes for testing the credentials and got:
```
err  Error: self signed certificate in certificate chain
         at Error (native)
         at TLSSocket.<anonymous> (_tls_wrap.js:929:36)
         at TLSSocket.emit (events.js:104:17)
         at TLSSocket._finishInit (_tls_wrap.js:460:8)
```

I tried updating my .npmrc to have strict-ssl=false and the cafile to the cert itself, but neither of those seemed to make a difference.

**Comment by OrKoN** [comment]
Does your company's github endpoint has a self-signed certificate? Could you try defining a node variable before running the command:

```
NODE_TLS_REJECT_UNAUTHORIZED="0"; jspm registry create mycompany jspm-github
```

I believe this should disable the node's check for the self-signed certificate.

**Comment by bhazen** [comment]
Thanks @OrKoN!  That did the trick.  In case anyone else running into this comes across this and is also using Powershell I had to slightly modify the command to this to set the variable:
```
$env:NODE_TLS_REJECT_UNAUTHORIZED="0"; jspm registry create mycompany jspm-github
```
