### ISSUE TITLE
Implement the full AMD standard for define

### ISSUE THREAD

**Issue by admwx7** [jspm/jspm-cli#738]
AMD provides the function `define(id?, dependencies?, factory);` I recently came across a library (c3) that uses both optional parameters, this fails in JSPM, however if I edit their code and remove the id optional parameter, it will run through JSPM without issues.

**Comment by guybedford** [comment]
@admwx7 named defines are supported in SystemJS, but will allow that id to write directly to the SystemJS registry.

If you load a library that has multiple named defines in it, then SystemJS won't know which value to take for the entire library. So it's as if you've loaded a bundle - and after that System.import you will need another `System.import(id)` to pull out that ID from the registry. If you load a library that contains a single named define though, SystemJS is clever enough to know to use that named define as the module value.

**Comment by admwx7** [comment]
Updated `define("c3", ["d3"], c3);` to `define("c3", ["d3"], function () { return c3; });` and all is well now. Seems c3 isn't following the standard of their factory inheriting the Function prototype, so when it compiles into `(c3).call` it fails to find the function.

**Comment by guybedford** [comment]
@admwx7 thanks for following up - this is actually a bug! I've posted https://github.com/systemjs/systemjs/issues/446.

**Comment by admwx7** [comment]
Agreed, pretty late yesterday I came across the issue again. It seems that
jspm can handle `define(string, string, function) ` when bundled, but not
runtime. If you remove the id then it doesn't have any issues. I forked the
repo I had this issue with and pushed a pull request to fix the factory not
being a function, but I'm running off a branch on my fork that removed the
id for now. Happy to say I'm now in the final stages of converting the app
I've been working on over to using jspm.

**Comment by guybedford** [comment]
@admwx7 am I right in thinking you were bundling here with `build-sfx`?

**Comment by admwx7** [comment]
Originally no, I am now and have been for the past ~5 days

**Comment by guybedford** [comment]
Thanks for clarifying - I moved the issue to https://github.com/systemjs/builder/issues/168 accordingly. Will aim to get to it soon, but it may end up being pushed along with the next major.
