### ISSUE TITLE
Old .jspm folder not removed when migrating to AppData\Local

### ISSUE THREAD

**Issue by glen-84** [jspm/jspm-cli#740]
Is there any reason not to delete this folder?

**Comment by guybedford** [comment]
For backwards-compatibility.

**Comment by glen-84** [comment]
Ah, like old versions of the CLI referencing this folder? So it's safe for me to delete it if I'm only using the latest version of the CLI?

**Comment by glen-84** [comment]
You didn't answer my question. :disappointed:

**Comment by guybedford** [comment]
Yes it's completely safe to remove.

**Comment by glen-84** [comment]
Thanks. :-)
