### ISSUE TITLE
Add an "unlink" command (?)

### ISSUE THREAD

**Issue by glen-84** [jspm/jspm-cli#741]
I don't see a command to unlink a local folder.

**Comment by guybedford** [comment]
`jspm install --unlink` is what we have currently but the workflow is a little bit awkward still.

**Comment by glen-84** [comment]
But that doesn't remove the files from `AppData\Local\.jspm\linked`, right?

This won't be needed once the [new linking workflow](https://github.com/jspm/jspm-cli/issues/622) is implemented.

**Comment by guybedford** [comment]
We can look into this in future certainly.
