### ISSUE TITLE
JSPM Install should install devDependencies.

### ISSUE THREAD

**Issue by Zoltu** [jspm/jspm-cli#747]
`npm install` installs `dependencies` and `devDependencies`.  JSPM should do the same thing when `jspm install` is executed.  When I first checkout a repository, I do not want to have to execute `jspm install` and `jspm install --dev` just to get my repo into a state that I can start working on it.

**Comment by guybedford** [comment]
Sure, we can look to implement this.

**Comment by telekosmos** [comment]
+1.
At the beginning I thought that was a bug. `--dev`can be kept in the case of ONLY `devDependecies`want to be installed, IMHO.

**Comment by crisptrutski** [comment]
Having `--dev` install *only* `devDependencies` does not seem like a useful behaviour, do you have a motivation for this @telekosmos? Planning to remove the `--dev` flag and make installing both the default behaviour.

**Comment by telekosmos** [comment]
Not a big motivationl, it was just a suggestion to keep back functionality for some.
Well done, thanks!!!
