### ISSUE TITLE
Passing Babel options to bundle-sfx

### ISSUE THREAD

**Issue by hipertracker** [jspm/jspm-cli#748]
How to pass additional parameter to Bable transpiler for bundle-sfx? My index.html contains

```
...
<script>
    System.babelOptions = { stage: 1, blacklist: []};
    System.import('src/startup');
</script>
```

But when I want to use bundle-sfx I have to point to my main js file: `startup.js`
```
jspm bundle-sfx src/startup dist/bundle.js --minify --skip-source-maps
```

so the information about System.babelOptions is gone. How to pass it?

**Comment by guybedford** [comment]
You can add the `babelOptions` in to the `config.js` file.

**Comment by hipertracker** [comment]
Right, tnx.
