### ISSUE TITLE
jspm bundle to AMD/CJS

### ISSUE THREAD

**Issue by OliverJAsh** [jspm/jspm-cli#75]
Is this possible?

**Comment by djindjic** [comment]
@guybedford is it still actual information that we cant bundle es6 code to amd using jspm? I have same issue as @OliverJAsh, want to "export" it as amd to use in an old requirejs app.

**Comment by guybedford** [comment]
@djindjic jspm doesn't provide this functionality but other tools like Babel can do this for you (http://babeljs.io/docs/usage/modules/)

**Comment by djindjic** [comment]
thanks @guybedford. It seems there is no way to use both jspm and babel's features. For example, I really love jspm's format agnostic imports, and workflow with systemjs plugins, but now I am working on angular 1/.x directives library and want to export it as amd module or global object and allow users to include it in their existing apps without package managers while still using jspm install for third party libs in my new library.

**Comment by guybedford** [comment]
There main workflow for this use case currently it to compile ES6 to CJS if
used and publish to npm.

Alternatively if you're happy to build in your dependencies use an SFX
bundle.

You can write SFX bundles that have global adapters that check for the
globals on the window object as well to remove large dependencies this way
too.

**Comment by djindjic** [comment]
SFX bundle sounds like it might help me. Until now I have use it just like this:
```bash
jspm bundle-sfx app/main app.js
```
Are global adapters custom code which I need to write into compiled sfx bundle after jspm-cli command?

**Comment by guybedford** [comment]
Yes, you would basically write:

adapters/jquery.js
export default window.jQuery;

And then add a map:

System.config({
  map: {
    "jquery": "adapters/jquery"
  }
});

**Comment by djindjic** [comment]
once again, WOW + THANKS! looks so logical when somebody show you how :smile:.  that's fine, and by my opinion it is cleaner then npm-CJS in case of browser usage. You made my day because I was totally sure that I will have to use bower and es5 again (and sedatives :pill:) :smiley:
