### ISSUE TITLE
NPM module written in ES6 w/ file extensions in import doesn't work

### ISSUE THREAD

**Issue by hannahhoward** [jspm/jspm-cli#751]
Hello,

   I publish an npm package called [A1AtScript](https://github.com/hannahhoward/a1atscript). A user of my library asked how to use it with JSPM. The library is published in ES6 format and all of the relative import statements include a ".js" extension, per the latest spec for how ES6 modules get loaded -- i.e. relative file imports do not assume a .js extension unless specifically stated. I've done some of the neccesary config: i.e. adding format: 'es6' to the module spec. However, I'm stuck on the fact that that by default config.js includes this:

```javascript
System.config({
  "paths": {
    "npm:*": "jspm_packages/npm/*.js"
  }
});
```

This converts all my relative imports to be .js.js and therefore they don't load. I've jerry rigged importing my own package by changing this config, but I'd like to be able to offer my users a more automatic install. What's the best way to specify the config in my NPM package's package.json so "npm:*": "jspm_packages/npm/*.js" doesn't break my imports?

**Comment by guybedford** [comment]
Thanks for looking into the jspm support. The current version of jspm implements the automatic `.js` extensions as in the previous spec. This is changing in our next breaking release, but for backwards compatibility we have been taking a little while to do this shift (trying to gather up breaking changes together, which can be tricky).

Working on getting the release out as fast as possible here.

For now it could be advisable to load the transpiled CommonJS if you are publishing this as a normal npm package.
