### ISSUE TITLE
jspm api add support for external package managers

### ISSUE THREAD

**Issue by XVincentX** [jspm/jspm-cli#752]
It would be great to plug external loaders (such as bower) using the api and not only with the cli.

**Comment by guybedford** [comment]
This is what the custom registry API is designed to provide.

**Comment by XVincentX** [comment]
Thank you for the prompt reply. Perhaps am I missing something...where should I start to read?

**Comment by guybedford** [comment]
An example to construct a bower registry is at https://github.com/2fd/jspm-bower-endpoint/blob/master/bower.js. I don't suggest this though as we already have the github registry, which does read the main from the bower.json when it can.

**Comment by XVincentX** [comment]
@guybedford I do not get the thing, sorry. You mean that jspm can automatically download out of the box bower packages?

**Comment by XVincentX** [comment]
Oh I understand, you mean that github registry will try to read an eventual _bower.json_ file from the repository and use it to export the library?

**Comment by guybedford** [comment]
Yes exactly - the github registry adapter will check the bower.json if the main entry point is not found from the package.json.

**Comment by XVincentX** [comment]
How about the dependencies? Looks like they do not get followed.

**Comment by guybedford** [comment]
Bower dependencies aren't followed because jspm won't know how to resolve them.

**Comment by codylindley** [comment]
fyi, by using https://www.npmjs.com/package/jspm-bower-endpoint you can use bower names and it will install dependencies.

**Comment by XVincentX** [comment]
@guybedford How does it behaves when main section of bower file contains multiple entries? Looks like actually it is "not working".

**Comment by guybedford** [comment]
@XVincentX yes it will use the first main in that case if it exists. Note that the package.json main takes preference over the bower.json though so it's just a fallback. You can see the code here - https://github.com/jspm/github/blob/master/github.js#L651.

**Comment by XVincentX** [comment]
Got it.
This could be a problem when some bower packages have got a javascript and a css file. Any idea about how to handle that?

**Comment by guybedford** [comment]
You can add the CSS plugin call as a dependency in the shim as well. There are some examples in https://github.com/jspm/registry/tree/master/package-overrides.

**Comment by guybedford** [comment]
@XVincentX a direct example of css loading can be seen at https://github.com/jspm/registry/blob/master/package-overrides/github/lightbox2/lightbox2%402.7.1.json.

**Comment by XVincentX** [comment]
@guybedford This is great. Can I submit a pull request for a package that I am using?

**Comment by guybedford** [comment]
Yes exactly, feel free to do so.
