### ISSUE TITLE
jspm pulls a nodelibs-process dependency from github

### ISSUE THREAD

**Issue by Nehon** [jspm/jspm-cli#755]
Hello, I'm in charge of renewing my company's front end environment and I chose to use jspm for dependencies management.
However we need to use an in-house private registry, sonatype nexus, with a NPM registry plugin to proxy the online registry and register private packages.

Our build agents don't have access to the internet, so we need that every dependencies can be fetched from NPM and our proxy only.

However, when running a jspm install, it pulls a github:nodelibs-process dependency and that's a problem.
I'm not sure why it's needed, but here are my questions : 
1. can I get rid of it? I guess not, but you never know.
2. can I get it from npm instead of github (doesn't seems to be registered as an npm packages on the public registry though)
3. can I somehow publish it to our private npm registry and force jspm to fetch it from there?
4. did I miss a genuine concept of jspm, and I'm going the wrong way?

Thanks

**Comment by guybedford** [comment]
Yes these packages are needed. There are a few approaches to this issue, including:

* Publish the nodelibs packages to npm or your private npm, then create a GitHub registry that acts as an alias to the local npm packages (ie when installing `github:jspm/nodelibs-fs` it maps to `npm:@local/nodelibs-fs` or something like that)
* Create a local GitHub registry that installs these packages from a local server in its implementation (`ie `github:jspm/nodelibs-fs` has its fetch implementation modified to copy from a local server).
* Use a linking workflow to populate the packages before the install - `jspm install --link github:jspm/nodelibs-process@1.2.3`.

Let me know your thoughts.

**Comment by Nehon** [comment]
Hello, thanks for the fast reply.

I'll look into the 3 options and report back.
I'm fairly new to JSPM and I still have a lot of reading to do to completely wrap my head around it. 
I'm not sure what "create a Github registry" really implies. 
I decided to use jspm to get rid of bower and avoid the need of the private bower registry, so I'd like to not have to install another private registry. But from the doc it doesn't seems to be the exact same concept.

From your answer it seems doable from a dev computer, but the issue is more from a continuous delivery process stand point. We're using Atlassian Bamboo to build our application and I'd need to do that on each bamboo agent. And I may not be able to do that for various reasons.

Anyway, I'll continue to dig into it and I'll keep you updated, if you're interested. 
Jspm and system.js are really nice pieces of software so far, thanks a lot for the effort you put into it.

**Comment by guybedford** [comment]
@Nehon if you want to avoid having to write custom registry code I'd advise trying a custom linking workflow here. Read more at https://github.com/jspm/jspm-cli/wiki/Linking.

**Comment by guybedford** [comment]
If you have any further questions here just let me know.
