### ISSUE TITLE
Update has trouble with pointer packages

### ISSUE THREAD

**Issue by crisptrutski** [jspm/jspm-cli#760]
Confused the redirection with having a new version explicitly provided (which is not supported)

**Comment by guybedford** [comment]
Yes we did this by design. Install is for creating new ranges. Update only applies to existing.

**Comment by crisptrutski** [comment]
@guybedford was just describing #766 here, not questioning the decision of update not taking ranges.

**Comment by guybedford** [comment]
@crisptrutski so https://github.com/jspm/jspm-cli/commit/0c52dad6e85b9879ddba5d224047c52e3c1a6482 is the fix, or is this something deeper?

**Comment by crisptrutski** [comment]
That's it
