### ISSUE TITLE
New --edge option does not handle pinned versions

### ISSUE THREAD

**Issue by de-git** [jspm/jspm-cli#765]
I am keen on using #494 and installed jspm from github.

Unfortunately the following command fails:
`npm update --edge`

```
...
err  TypeError: Cannot read property 'join' of undefined
         at matchParsed (C:\Users\ecerd\AppData\Roaming\npm\node_modules\jspm\lib\semver.js:129:59)
         at match (C:\Users\ecerd\AppData\Roaming\npm\node_modules\jspm\lib\semver.js:210:10)
         at getVersionMatch (C:\Users\ecerd\AppData\Roaming\npm\node_modules\jspm\lib\package.js:218:11)
```

The line being:
```
    return range.semver || range.fuzzy || rangeVersion.pre.join('.') === version.pre.join('.');
```

The version in the package.json is pinned (no prefix) and doesn't have a suffix. rangeVersion.pre is undefined.

This is the exact definition:
```
      "ui-router": "github:angular-ui/ui-router@0.2.10",
```

And the parameters:
```
matchUnstable, range: 0.2.10 , version: 0.2.12-pre1
range: { semver: false,
  fuzzy: false,
  version: { major: 0, minor: 2, patch: 10, pre: undefined } } , version: { major: 0, minor: 2, patch: 12, pre: [ 'pre1' ] } , edge:  true
```

(It would also be good if one could select the dependencies that edge version would be resolved for)

**Comment by crisptrutski** [comment]
Thanks for the detailed report, I'll patch this up now. 

RE: `It would also be good if one could select the dependencies that edge version would be resolved for`

Are you asking for something like `jspm update package-one package-two package-three --edge`?

**Comment by crisptrutski** [comment]
Pushed f5d99adc70b3fff50be46d2d281c338ee221ed5a which fixes the bug in the most obvious way, but will also run past @guybedford tomorrow to check this is the behaviour he wants.

**Comment by de-git** [comment]
Great, thank you.

>Are you asking for something like jspm update package-one package-two package-three --edge?

We are using jspm to manage our own as well as third party modules. In our use case we would want to use the latest 'edge' version of our own dependencies, not the third party dependencies. So yes, something where we could select individual packages or perhaps an expression would work. Ideally there was a way that we could group all of our dependencies. But I can't think of a generic criteria apart from the package name and the repository. We could somehow generate a list of our projects. (We are not actually using the command line interface but the API)

**Comment by crisptrutski** [comment]
Sure, keeping the "edge" status of certain packages, via their own range syntax, or setting in some other fashion is something that's come up. Also perhaps limiting `edge` behaviour to primary or explicit dependencies is wise amendment.

**Comment by guybedford** [comment]
@de-git thanks for testing this out! As @crisptrutski mentions, `jspm update package-one package-two package-three --edge` is a good way to handle these types of selective update sets. We're trying to avoid getting into unnecessary syntax until there is further implementation pressure. Will certainly bear the use case in mind.

**Comment by de-git** [comment]
Okay, that seems to work now. Thank you.

So I would run `jspm update` to update all of the dependencies and `jspm update pgk1 pkg2 --edge` to use the latest unstable version.

Now for release builds I would like to only use stable versions and not include the edge version. But if I run `jspm update` or `jspm update pkg1 pkg2` then it won't revert the version back to the latest release. I could remove `config.js` and run `jspm update` again. Do you have any other suggestion?

**Comment by guybedford** [comment]
@de-git interesting point. Perhaps something like the following:

* Package.json set to `^1.0.0`
* jspm install will install 1.0.1, even though there is a 1.0.1-beta
* jspm update --edge will install 1.0.1-beta, but probably should still leave package.json at `^1.0.0` as it is a matching range (_it doesn't currently_)
* We then need some kind of option to "revert ranges" on install and not use the config.js version lock. Perhaps `jspm install --resolve` to indicate that we want to re-resolve the primary dependencies.

It's getting a little bit complex on the logic now, but good to be putting ideas out in these directions.

**Comment by de-git** [comment]
@guybedford yes, that sounds good. I didn't realise until you mentioned that currently it is updating the package.json and I would prefer if it didn't. I liked the idea of package.json being maintained 'manually' while config.js can be updated automatically (we've configured a CI job to move it to the latest version).

**Comment by crisptrutski** [comment]
@de-git there's a simple way to back out of edge - you can run `jspm install pkg1 pkg2`. This will resolve back to the latest stable versions for those dependencies. Installs are "stronger" than updates - they're able to override the version lock, and default to latest.

Around the updating of `package.json` - this was intentionally added. Note that otherwise `config.js` and `package.json` could fall out of sync, and `jspm install` or `jspm update` will not be runnable without the `--edge` option.

Rewriting `package.json` is done conservatively, if there is already a range with is compatible with the resolved edge version, then it will be left alone. The alternate to updating the version range would be to keep a some "resolve this range with --edge" metadata (or a new range literal), and this seems a fraught path to avoid if possible.

One thing to note about the ranges generated, eg `~1.5.2-alpha.1` is that they are "self deprecating", in that without the `--edge` parameter provided again this will match `1.5.3` but not `1.5.3-alpha.1`. This means that once a stable version later than the edge version is released, the range will always resolve to a stable version.

**Comment by crisptrutski** [comment]
Here's where the `package.json` mutation was added, may make things clearer: d50ac1064ed580fe8c2207100ef076dded7d79c0

This stuff is super fresh so open to alternate proposals

**Comment by de-git** [comment]
@crisptrutski thank you for the explanation. I now realise that this would only work for direct dependencies. For indirect / transitive dependencies I wouldn't have control over the versions at the parent level. That seem to be both true for the `jspm update pkg1 pkg2` as well as `jspm install pkg1 pkg2` (please correct me if I am wrong).
e.g. in a dependency hierarchy like pkg1 -> pkg2 -> pkg3, I wouldn't be able to run `jspm update pkg3` within the pkg1.

Although in that situation it could to be an advantage to put the version into the package.json. As pkg2~1.0.1-beta package.json would get updated with say pkg3~1.0.1-beta, which is then seen by pkg1 once it looks for pkg2~1.0.1-beta.

As for the install, it is slightly more complicated as our modules are not in the jspm registry. As I understand it, I would have to go through the package.json to find the full install instruction. But I suppose that is manageable as well.

---

Just to discuss potential alternatives:

I can see your point about `jspm install` vs `jspm update`. But the config.js file would already contain the 'edge' version, something that `jspm install` or `jspm update` could work with.
If we went that way, we would need to find a way to being able to control transitive the edge version of dependencies though.

(I also don't think that adding a metadata to the package.json would be a good idea)

Just in general I understand the meaning of the files as follows:
* package.json: contains user controlled intended version ranges
* config.js: contains actual resolved versions at the time (`jspm install` would install those versions instead of trying to resolve them again).
(I kind of liked the separation as opposed to maven dependencies being expressed in a single file) 

The third party dependencies in our package.json are usually pinned as we want more control over it. It would seem that by updating the package.json with the edge version, and later with the release version (via a separate `jspm install`), all of the versions would effectively be pinned and we wouldn't have much advantage in checking in the config.js anymore.

Perhaps some pros/and cons (some points may be argued either way).
a) do update package.json with edge version (as it is currently the case)
* transitive dependencies could be handled by proxy
* config.js may not need to be checked in anymore

b) don't update package.json with edge version
* package.json continues to express ranges
* package.json stays being more user controlled (i.e. our CI job wouldn't just update it because there is a new 'edge' version available)

**Comment by crisptrutski** [comment]
Certainly `config.js may not need to be checked in anymore` is not a goal here. Maven is very painful when it comes to version ranges, think that `Gemfile.lock`, `npm-shrinkwrap.json` and the other prior art for putting resolved versions into their own file, and the approach has proved itself.

I've put a bit more thought into updating `package.json` during `--edge` installs, and it is something we can avoid by relaxing the behaviour of `jspm update`. Essentially when `config.js` is incompatible with `package.json` for a package being updated, we can just leave it alone and issue a warning.

**Comment by crisptrutski** [comment]
Closing, but happy to continue discussion
