### ISSUE TITLE
Bundling failing on Heroku

### ISSUE THREAD

**Issue by jedrichards** [jspm/jspm-cli#767]
My bundle step is failing on Heroku, with this error,

```
Building the single-file sfx bundle for main...
Error loading "node_modules/react/addons" from "main" at file:/app/public/main.js
  err  Error: Error loading "node_modules/react/addons" at file:/app/public/node_modules/react/addons.js
  at Error (native)
  ENOENT: no such file or directory, open '/app/public/node_modules/react/addons.js'
```

The same bundle step works fine locally, and it works fine in my CI environment too (Codeship). It's odd, because it looks like its looking for `node_modules` in `public/` which is my `baseURL` ...

Any ideas? Any more info I can provide?

Thanks!

**Comment by guybedford** [comment]
@jedrichards `file:/app/public/main.js` already looks wrong here for the main as it should be a full file system URL of the form `file:/User/username/app/public/main.js` for example. Perhaps share your package.json values for baseURL etc?

**Comment by jedrichards** [comment]
The project is actually viewable here: https://github.com/madebycomrades/autokitty-react

In package.json baseURL is just `public`. You can see my bundle command in the `scripts` object of package.json too. Like I mentioned, it all works fine locally, and on Codeship ... just not happy on Heroku, most odd ...

The path to the `main.js` file looked wrong to me too, then I thought that actually it might be a valid full file system URL on Heroku ... i.e., perhaps Heroku apps are deployed in a VM in folder called `/app`.

**Comment by guybedford** [comment]
This might be a windows thing actually - I've added https://github.com/jspm/jspm-cli/commit/bca85a86cf4d4aab458fee583cd2faabe6e23da5 which may help here? Perhaps try running against jspm master and let me know if that works for you?

**Comment by jedrichards** [comment]
I added `"jspm": "jspm/jspm-cli#master",` to my package.json to no avail, still failing with the same error on Heroku. I will investigate further ...

**Comment by jedrichards** [comment]
Arrh its started working with jspm-cli from master branch. I think Heroku was caching things weirdly (I'm trying to make their new "PR Apps" GitHub integration work). Will close this - thanks for your help ...

**Comment by guybedford** [comment]
Excellent, glad to hear that worked!
