### ISSUE TITLE
Error: Repo jspm:npm:codemirror not found!

### ISSUE THREAD

**Issue by smehrbrodt** [jspm/jspm-cli#768]
I get this error when using the latest (0.15.6) JSPM to install my dependencies: `Repo jspm:npm:codemirror not found!`

The weird thing is that it says `jspm:npm:pkg` instead of `npm:pkg`.

This has worked before the update.

My package.json is [here](https://github.com/digitaldeacon/memberhive/blob/master/package.json)

**Comment by guybedford** [comment]
@smehrbrodt it sounds like you've published jspm-style dependencies to npm here? It may be worth double-checking the guidelines in https://github.com/jspm/jspm-cli/wiki/Publishing-Packages. If you can share the scenario, happy to suggest further.
