### ISSUE TITLE
Allow no transpiler option

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#769]
It should be possible to not use a transpiler at all.

**Comment by swirlycheetah** [comment]
Considering I've done some work around transpiler options before I'd be happy to take a look at implementing this.

Any caveats you can think of? Do we just want an option of 'none' within the current transpiler prompt or a new prompt asking users if they'd like to use a transpiler first?

**Comment by guybedford** [comment]
@swirlycheetah thanks we actually already had a contribution in https://github.com/jspm/jspm-cli/pull/792 so this will be in the next release.

**Comment by swirlycheetah** [comment]
Oh brilliant. I'll take another look to see if there's anything else I could pick up.

**Comment by guybedford** [comment]
Sure, thanks!

**Comment by curran** [comment]
Wonderful! So happy to hear this has been implemented. Thank you for addressing this.
