### ISSUE TITLE
Traceur can't find `traceur.js.map`

### ISSUE THREAD

**Issue by ifyio** [jspm/jspm-cli#771]
When I do a jspm install with traceur, I get this error in the console

```
GET http://localhost:63342/jspm-typescript/jspm_packages/github/jmcriffey/bower-traceur@0.0.88/traceur.js.map 404 (Not Found)
```
I have checked the actual folder in `jspm_packages` and the `traceur.js.map` file is indeed not there.

**Comment by guybedford** [comment]
Thanks - posted on the Bower-traceur repo, let's track there.
