### ISSUE TITLE
Build cache

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#772]
When running SystemJS builder, traces are very quick, what takes a long time is the building.

We could store a local build cache in say `jspm_packages/_build_cache` which contains a file for each single-file compilation of each module in a given trace.

Then when running a build, we first check the trace against the build cache and only build the traced modules not already cached.

Depends on the individual load compilation API at https://github.com/systemjs/builder/issues/126.

@crisptrutski do you think this should be in builder rather?

**Comment by crisptrutski** [comment]
Putting into JSPM makes more sense to me, more about IO than building. Either or.

Minification and source map concatenation still form bulk of time, after build, I believe. Haven't benchmarks recently

**Comment by guybedford** [comment]
Initial work here has now been done. Blocked on https://github.com/systemjs/builder/issues/209.

**Comment by guybedford** [comment]
SystemJS builder has a build cache, it just isn't managed through jspm currently.
