### ISSUE TITLE
Handling depcache load order errors

### ISSUE THREAD

**Issue by lewisl9029** [jspm/jspm-cli#774]
I recently switched to a much slower machine than I'm used to, so I looked for some ways to cut down on the reload time for a large jspm project, and found out about the depcache functionality.

However, I ended up getting the following errors:

```
Uncaught ReferenceError: angular is not defined(anonymous function) @ angular-toastr.tpls.js:6(anonymous function) @ angular-toastr.tpls.js:261(anonymous function) @ angular-toastr.tpls.js:466doEval @ system.src.js:2347__eval @ system.src.js:2317a @ system.src.js:339$__global.upgradeSystemLoader.e.instantiate.cjs.n.metadata.format.n.metadata.execute @ system.src.js:1222f @ system.src.js:669l @ system.src.js:528$__global.upgradeSystemLoader.e.instantiate.Promise.all.then.execute @ system.src.js:852o @ es6-module-loader.src.js:1938p @ es6-module-loader.src.js:1986j @ es6-module-loader.src.js:1759k @ es6-module-loader.src.js:1807(anonymous function) @ es6-module-loader.src.js:1628O @ es6-module-loader.src.js:1183K @ es6-module-loader.src.js:11427.y.when @ es6-module-loader.src.js:9307.v.run @ es6-module-loader.src.js:8213.a._drain @ es6-module-loader.src.js:973.a.drain @ es6-module-loader.src.js:62b @ es6-module-loader.src.js:268
es6-module-loader.src.js:140 Potentially unhandled rejection [2] Error loading "npm:angular-toastr@1.3.1/dist/angular-toastr.tpls" at http://localhost:8080/jspm_packages/npm/angular-toastr@1.3.1/dist/angular-toastr.tpls.js
Error evaluating http://localhost:8080/jspm_packages/npm/angular-toastr@1.3.1/dist/angular-toastr.tpls.js
Uncaught ReferenceError: angular is not defined (WARNING: non-Error used)(anonymous function) @ es6-module-loader.src.js:140f @ es6-module-loader.src.js:167i @ es6-module-loader.src.js:189
angular-ui-router.js:18 Uncaught TypeError: Cannot read property 'isDefined' of undefined(anonymous function) @ angular-ui-router.js:18(anonymous function) @ angular-ui-router.js:3223(anonymous function) @ angular-ui-router.js:3224doEval @ system.src.js:2347__eval @ system.src.js:2317a @ system.src.js:339$__global.upgradeSystemLoader.e.instantiate.cjs.n.metadata.format.n.metadata.execute @ system.src.js:1222f @ system.src.js:669l @ system.src.js:528$__global.upgradeSystemLoader.e.instantiate.Promise.all.then.execute @ system.src.js:852o @ es6-module-loader.src.js:1938p @ es6-module-loader.src.js:1986j @ es6-module-loader.src.js:1759k @ es6-module-loader.src.js:1807(anonymous function) @ es6-module-loader.src.js:1628O @ es6-module-loader.src.js:1183K @ es6-module-loader.src.js:11427.y.when @ es6-module-loader.src.js:9307.v.run @ es6-module-loader.src.js:8213.a._drain @ es6-module-loader.src.js:973.a.drain @ es6-module-loader.src.js:62b @ es6-module-loader.src.js:268
es6-module-loader.src.js:140 Potentially unhandled rejection [4] Error loading "github:angular-ui/ui-router@0.2.10/release/angular-ui-router" at http://localhost:8080/jspm_packages/github/angular-ui/ui-router@0.2.10/release/angular-ui-router.js
Error evaluating http://localhost:8080/jspm_packages/github/angular-ui/ui-router@0.2.10/release/angular-ui-router.js
Uncaught TypeError: Cannot read property 'isDefined' of undefined (WARNING: non-Error used)
```

The cause appears to be the modules angular-toastr and angular-ui-router depending on an angular global being available, but because they don't specify angular as a dependency in package.json, depcache ended up loading them before angular.

I repro'd this issue in https://github.com/lewisl9029/jspm-test and tried to add angular as a dependency for both modules in a local override in package.json, but the depcache tree generated doesn't seem to change at all as a result of this (this could be a jspm bug?).

If this isn't the proper way to resolve these kinds of issues, any idea what other workarounds I could try?

**Comment by OrKoN** [comment]
I have the same problem with ember-i18n https://github.com/jamesarosen/ember-i18n I think the project will migrate away from globals but what is the workaround for now? I have tried overriding dependencies for this package but I think depcache only considers actual import statements in files, right?

**Comment by guybedford** [comment]
This is due to the fact that when loading previously, it just happened that most of the time angular had loaded first, but it was by no means guaranteed. Dependencies like angular or ember need to be explicit dependencies of anything that uses them to ensure the right execution order. This is what the global shims are for. 

Eg `jspm install npm:angular-toastr -o "{ "shim": { "dist/angular-toastr.tpls": ["angular"] }, "dependencies": { "angular": "^1.2" } }"`

These shims should really be committed to the jspm registry so other users can also benefit and not hit the same issues.

**Comment by OrKoN** [comment]
@guybedford thanks, it worked. Is it possible to have an injected bundle and depcache at the same time? e.g. I want to have a bundle for app dependencies and depcache for the app itself?

**Comment by guybedford** [comment]
@OrKoN certainly you can do that - depCache supports arithmetic just like bundles so you can subtract the bundle itself from the depcache.

**Comment by lewisl9029** [comment]
@guybedford Thanks for the clarification!
I didn't actually know what shims were used for until now.

I managed to get the depcache working with some local overrides. I'll take some time this weekend to test it a bit more before sending a pull request to the registry.

**Comment by DominicBoettger** [comment]
Okay, this is a lot of work in a project to correct all the deps....

For example angular-resource:
jspm install angular-resource -o '{ "shim": { "angular-resource": { "deps": ["angular"]}}, "dependencies": { "angular": "^1.3" } }'

**Comment by DominicBoettger** [comment]
I tried to add these lines for oczlazyload:

    "github:christopherthielen/ui-router-extras@0.0.13/release/modular/ct-ui-router-extras.core": [
      "github:angular/bower-angular@1.3.15"
    ],
    "github:christopherthielen/ui-router-extras@0.0.13/release/modular/ct-ui-router-extras.future": [
      "github:angular/bower-angular@1.3.15"
    ],
    "github:ocombe/ocLazyLoad@1.0.0-alpha2/dist/ocLazyLoad": [
      "github:angular/bower-angular@1.3.15"
    ]

But it does not work. Did somebody try to inject the angular dependency with this module?

**Comment by DominicBoettger** [comment]
I also added to the files

/* */ 
"format global";
"deps angular";

After that it worked for me, but i am not sure if it will be

**Comment by guybedford** [comment]
@DominicBoettger yes that looks about right in your last comment. The expectation was never for an individual to have to shim multiple libraries like this - this is why the registry persists overrides for all to share. It would be great if you can contribute these overrides to the registry or underlying repos so that others can benefit from your work here.
