### ISSUE TITLE
Invalid gitfile format: .git

### ISSUE THREAD

**Issue by cexbrayat** [jspm/jspm-cli#776]
OSX 10.10
node: v0.12.3 (via nvm)
git: 2.2.0 (via homebrew)

On `jspm init` or `jspm install`, I can't install any package. 

Every package has the same error:
```
warn Error on lookup for github:systemjs/systemjs
     fatal: Invalid gitfile format: .git
```

Am I missing something obvious?

**Comment by guybedford** [comment]
@cexbrayat I'm really not sure what this might be. Perhaps try running `jspm cc` to clear out the cache in case of a corruption of a git repo. You should also ensure your local git install has `git` in the path and is working correctly.

Apart from that perhaps this could be a permissions issue?

Haven't heard of this before, haven't found anything too insightful from Googling yet. Did you make any further progress?

**Comment by cexbrayat** [comment]
Thanks @guybedford for your answer. Sadly I did not found anything useful on the internets too, so I dared to ask here.

No luck after `jspm cc`, no luck after `sudo`, and my local `git` is in path and working correctly, no luck with the OSX `git` instead of the brew git...

Is there a flag I can use to have a more verbose mode and maybe find some clues?

**Comment by cexbrayat** [comment]
Same problem on node 0.10.33
I can install npm package with no problem, but every github package fails with the same error.

Can you tell me what git command is run on lookup, so I can try it directly on the command line?

**Comment by crisptrutski** [comment]
@cexbrayat do you get sensible output from `git ls-remote https://github.com/systemjs/systemjs.git refs/tags/* refs/heads/*` (if using zsh you'll need to escape `*` to `\*`)?

Perhaps post your `~/.jspm/config` file too, wondering if somehow the config for the github registry has been corrupted.

**Comment by cexbrayat** [comment]
@crisptrutski Thanks for your answer.

I do have a sensible output from `git ls-remote`.

My `config` file is : 
```
{
  "defaultTranspiler": "traceur",
  "defaultRegistry": "jspm",
  "registries": {
    "github": {
      "timeouts": {
        "lookup": 60,
        "build": 120
      },
      "remote": "https://github.jspm.io",
      "auth": "XXXXX", //don't know if it is sensible, so removed it
      "maxRepoSize": 0,
      "handler": "jspm-github"
    },
    "npm": {
      "timeouts": {
        "lookup": 60,
        "build": 120
      },
      "handler": "jspm-npm",
      "remote": "https://npm.jspm.io"
    },
    "jspm": {
      "timeouts": {
        "lookup": 60,
        "build": 120
      },
      "handler": "jspm-registry",
      "remote": "https://registry.jspm.io"
    }
  },
  "strictSSL": true
}
```

I've also tried to comment my git config (nothing really special, but you never know...), with a fresh install of jspm, nothing matters, still the same error...

**Comment by guybedford** [comment]
@cexbrayat thanks for your help tracking this down.

Can you try and run the following in the Node repl or in a test file:

```javascript
require('child_process').exec('git ls-remote ' + 'https://github.com/systemjs/systemjs'.replace(/'/g, '\\\'') + '.git refs/tags/* refs/heads/*', function(err, stdout, stderr) { console.log(err); console.log(stdout); });
```

And confirm if it can replicate your issue?

**Comment by cexbrayat** [comment]
I can't reproduce. From Node repl, it's working both in v0.10.33 and v0.12.3

**Comment by guybedford** [comment]
Ok, I'm thinking perhaps the issue is the jspm registry itself then here, specifically https://github.com/jspm/registry-endpoint/blob/master/registry.js#L183 or https://github.com/jspm/registry-endpoint/blob/master/registry.js#L155. Those are the only uses of stateful git we have in the project.

@cexbrayat if you run `jspm cc` and then `jspm init` do you see the text "Creating registry cache"? It would be great to see the output.

**Comment by cexbrayat** [comment]
I don't see this text...

```
Package.json file does not exist, create it? [yes]:
Would you like jspm to prefix the jspm package.json properties under jspm? [yes]:
Enter server baseURL (public folder path) [./]:
Enter jspm packages folder [./jspm_packages]:
Enter config file path [./config.js]:
Configuration file config.js doesn't exist, create it? [yes]:
Enter client baseURL (public folder URL) [/]:
Which ES6 transpiler would you like to use, Traceur or Babel? [traceur]:
ok   Verified package.json at package.json
     Verified config file at config.js
     Looking up loader files...

warn Error on lookup for github:systemjs/systemjs
     fatal: Invalid gitfile format: .git


err  Error downloading loader files.

err  undefined
```

**Comment by crisptrutski** [comment]
Which version are you running by the way? `jspm -v`

Running out of ideas here, may have to start sending you patches to your jspm install and do println style debugging :cactus:

**Comment by cexbrayat** [comment]
I'm running 0.15.6. 

No problem for running my own version, that was what I was beginning to think. I'll give it a  try tomorrow morning, and ping you if I have any progress or if I need help. In the meantime, if you have an idea...

**Comment by guybedford** [comment]
It would be good to explicitly determine via logging that the error is definitely happening on this call - https://github.com/jspm/github/blob/master/github.js#L320 (node_modules/jspm-github/github.js from jspm folder), and if so, logging the exec arguments with `console.log('git ls-remote ' + remoteString.replace(/'/g, '\\\'') + repo + '.git refs/tags/* refs/heads/*', execOpt)` to confirm.

The above is full isolation of the problem if we can get.

**Comment by cexbrayat** [comment]
Here is the result (replaced my token by XXX):

```
git ls-remote https://cexbrayat:XXX@github.com/ModuleLoader/es6-module-loader.git refs/tags/* refs/heads/* { cwd: '/Users/cedric/.jspm/github-cache',
  timeout: NaN,
  killSignal: 'SIGKILL',
  maxBuffer: 2097152 }
git ls-remote https://cexbrayat:XXX@github.com/systemjs/systemjs.git refs/tags/* refs/heads/* { cwd: '/Users/cedric/.jspm/github-cache',
  timeout: NaN,
  killSignal: 'SIGKILL',
  maxBuffer: 2097152 }
{ [Error: Command failed: /bin/sh -c git ls-remote https://cexbrayat:XXX@github.com/ModuleLoader/es6-module-loader.git refs/tags/* refs/heads/*
fatal: Invalid gitfile format: .git
]
  killed: false,
  code: 128,
  signal: null,
  cmd: '/bin/sh -c git ls-remote https://cexbrayat:XXX@github.com/ModuleLoader/es6-module-loader.git refs/tags/* refs/heads/*' }

warn Error on lookup for github:ModuleLoader/es6-module-loader, retrying (1).
     fatal: Invalid gitfile format: .git
```

If I run `git ls-remote` or `/bin/sh -c git ls-remote` in my etrminal or in node repl `require('child_process').exec('git ls-remote ' + 'https://github.com/systemjs/systemjs'.replace(/'/g, '\\\'') + '.git refs/tags/* refs/heads/*', function(err, stdout, stderr) { console.log(err); console.log(stdout); });` it works .

Using the git protocol instead of https does not change anything, the URL generated is valid in my browser, and I updated my git to 2.4.1 from 2.2.0, with no luck...

When I'm trying `jspm install`, it is failing very fast, like it doesn't even try to request.

**Comment by crisptrutski** [comment]
@cexbrayat wondering if perhaps there's an issue with some exotic characters in your password that need escaping in bash. Another thing is to try using those same `execOpts` in your manual test from node.

**Comment by guybedford** [comment]
Yeah I'm wondering if it might be the same thing. @cexbrayat perhaps try generating an access token and see if that helps?

**Comment by cexbrayat** [comment]
I think I've found it: using the execOpts as you suggested, I can reproduce in Node repl \o/. 
If I have `cwd` in my opts, it fails:
```
{ cwd: '/Users/cedric/.jspm/github-cache'}
```

Does it need to have a `.git` directory in there? Because mine hasn't and if I create one in it with `git init`, I don't have this error anymore!

**Comment by cexbrayat** [comment]
I confirm I can reproduce:

- wipe `~/.jspm`
- first `jspm install` -> fails with the error
- do `git init` in `~/.jspm/github-cache`
- retry `jspm install` -> success

**Comment by guybedford** [comment]
Strange! Thanks so much for tracking this doen @cexbrayat. It almost sounds like a git bug though. If you run `git ls-remote` exactly the same manually from within that folder, do you notice the same thing still or just via exec in Node?

**Comment by cexbrayat** [comment]
You're right, the `git ls-remote` crashes too if I run it from a directory that is not a git repo... I have no idea if that's a Git bug or not, does it work for you?
This comment in Git source code let me think that the error is normal but maybe not...
https://github.com/git/git/blob/master/git-parse-remote.sh#L5-L6

I close the issue, if I'm the only one with this problem. Thank you for your help.

**Comment by guybedford** [comment]
It sounds like you might have some kind of corrupted .git folder in your path that gets read by default somehow? Glad to hear it's not our problem for a change :).

**Comment by sundeer** [comment]
@crisptrutski 

    warn Error on lookup for github:systemjs/plugin-css, retrying (1).
    /bin/sh: 1: Syntax error: ")" unexpected

Similar error fixed by using token instead of password. Original password that has since been changed=> wg)8YM9kAXvzbUX#MDrh

**Comment by guybedford** [comment]
@sundeer thanks this was fixed in https://github.com/jspm/jspm-cli/issues/838 in the jspm 0.16 beta release.

**Comment by narratorjay** [comment]
Similar error three years later:
$ git init  // this did nothing to fix it
Reinitialised existing Git repository in /home/jay/anaconda3/CASA0013/.git/
$ git add week8.ipynb
$ git commit -m "trying again"
 1 file changed, 94 insertions(+), 12 deletions(-)
$ git push week8.ipynb
fatal: invalid gitfile format: week8.ipynb
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

found this clue when running
$ git log
...
Author: narratorjay ;
Date:   Wed Nov 28  2018 
commit 22...........................................15   origin/master  origin/HEAD

Fixed with
$ git symbolic-ref refs/remotes/origin/HEAD refs/remotes/origin/master
$ git add week8.ipynb
$ git commit -m "trying again2"
On branch master
Your branch is ahead of "origin/master" by 7 commits.
  (use "git push" to publish your local commits)

... back to working again
