### ISSUE TITLE
ENOENT error

### ISSUE THREAD

**Issue by nateabele** [jspm/jspm-cli#777]
Running `jspm bundle src/<file>` from my project directory yields:

```bash
     Building the bundle tree for src/<file>...

err  Error: Error loading "src/<file>" at file:/[project dir]/src/src/<file>.js
     ENOENT, open '/[project dir]/src/src/pr.js'
         at Error (native)
```

(Note the double `src`).

However, `cd src; jspm bundle <file>` works. (Well, 'works' in the sense that I get far enough to hit a slightly different but equally befuddling error). What am I missing?

**Comment by nateabele** [comment]
Btw, `jspm --version` says:

```bash
0.15.6
Running against global jspm install.
```

**Comment by guybedford** [comment]
Did you set the baseURL to `src` here?

**Comment by guybedford** [comment]
Note that when you bundle, the name you enter is not a file path, but the name of the module to bundle, relative to the baseURL in the loader.

**Comment by nateabele** [comment]
My `config.js` (which is in the top level of the project directory) has `"baseURL": "."`.

**Comment by guybedford** [comment]
There are two `baseURL` settings - one for the client, and one for the server. They should both refer to the same effective folder. The one I'm referring to above is the one in the package.json directories.baseURL value, which if not specified is taken to be the same folder the package.json is in.

It sounds like that must be `src` here surely?

**Comment by nateabele** [comment]
JSPM section of `package.json` looks like this:

```json
  "jspm": {
    "directories": {},
    "dependencies": {
      "marked": "npm:marked@^0.3.3"
    },
    "devDependencies": {
      "babel": "npm:babel-core@^5.1.13",
      "babel-runtime": "npm:babel-runtime@^5.1.13",
      "core-js": "npm:core-js@^0.9.4"
    }
  }
```

Did I `jspm init` with too old a version?

I set `"directories": { "baseURL": "src/" }` in `package.json`, then moved `config.js` to `src/config.js`, but running `bundle` with just the module name still gives the same error with the same broken path.

**Comment by guybedford** [comment]
@nateabele that config seems fine to me actually.

Can you clarify what the value of `<file>` is here in your report above? 

It would really help to see the reduced scenario, with an ES6 file and import and what their paths are to cause this. I think we'll find it has a simple explanation when that is clarified.

**Comment by nateabele** [comment]
Figured it out after lots of tinkering, though I lost track of what actually solved it (sorry). Here's the end result if you're interested: https://github.com/radify/PR.js

**Comment by mwq27** [comment]
Here's what I run, and I get the below error.
```
bash-3.2$ sudo jspm bundle src/js/app devTest.js

warn Running jspm globally, it is advisable to locally install jspm via npm install jspm --save-dev.
     Building the bundle tree for src/js/app...

err  Error: ENOENT, open '/Users/mwoodson/Projects/myApp/src/js/app'
         at Error (native)
```
I don't have the baseURL set in my package.json, but my config.js and package.json are at the same level in the project root.  Here's what my config.js file looks like:  
```
System.config({
  "transpiler": "babel",
  "babelOptions": {
    "experimental": true,
    "blacklist": [],
    "optional": [
      "runtime"
    ]
  },
  "paths": {
    "*": "*.js",
    "app/*": "lib/*.js",
    "github:*": "jspm_packages/github/*.js",
    "npm:*": "jspm_packages/npm/*.js"
  }
});

System.config({
  "depCache": {
    "npm:react@0.13.3/lib/PooledClass": [
      "npm:react@0.13.3/lib/invariant",
      "github:jspm/nodelibs-process@0.1.1"
    ],

...
```

Not sure what to do to get this bundle working.  Any ideas?

**Comment by mwq27** [comment]
Ok, I had jspm installed globally.  WHen I installed jspm to my project instead, it worked.  Not sure why having it installed globally would make a difference, but oh well, im just glad it's working now :)
