### ISSUE TITLE
jspm inject broken?

### ISSUE THREAD

**Issue by edrex** [jspm/jspm-cli#779]
I'm getting the following weird behavior with `jspm@0.15.6`:

```
% mkdir bar && cd bar && jspm init -y
    ...
% jspm inject foo

warn Did you mean jspm install foo@jspm:foo?

err  Update does not support implicit installs.
```

**Comment by edrex** [comment]
`doUpdate` gets set when `args[0] == 'inject'` because.. `case` statement abuse..

**Comment by crisptrutski** [comment]
The blocker here is that `update` has a bug in `0.15.6` (#760), but thanks for catching the extra issue around the `case` drop through. 

Will see about getting out a hotfix to address both issues (did not realise the first bug had been released)

**Comment by crisptrutski** [comment]
@edrex just to update you here, decision from above is for this fix to just roll out in the regular release happening this week. The second bugfix has been added here: bb09a078d14c613338c6e1d59abad34905b91eba
