### ISSUE TITLE
Auto include runtime in normal bundles

### ISSUE THREAD

**Issue by OliverJAsh** [jspm/jspm-cli#781]
Re. https://github.com/systemjs/builder/issues/46, I noticed that the runtime is being bundled in SFX bundles.

Does it make sense to bundle this for normal bundles? Or at least to have an option?

@mattosborn

**Comment by guybedford** [comment]
Yes this has been considered and is being tracked at https://github.com/systemjs/systemjs/issues/431.

In this way, Traceur runtime becomes a dependency of every file compiled via Traceur, which does seem correct though actually.

**Comment by guybedford** [comment]
Closing to make https://github.com/systemjs/systemjs/issues/431 the primary tracker for this.
