### ISSUE TITLE
`jspm install` somehow flattening file structure?

### ISSUE THREAD

**Issue by timbur** [jspm/jspm-cli#787]
If you check out https://github.com/ajaxorg/ace-builds, you'll see multiple `src-*` directories.

When I `jspm install github:ajaxorg/ace-builds`, there are no `src-*` directories, and the files from the `src` directory have somehow ended up in `jspm_packages/github/ajaxorg/ace-builds@1.1.9`.

Is this a problem with the `ace-builds` repo or do I need to configure something with `jspm`?

**Comment by guybedford** [comment]
This is due to the override in https://github.com/jspm/registry/blob/master/package-overrides/github/ajaxorg/ace-builds%401.1.6.json.

We've since changed the practices around this to not usually set directories.lib in overrides for these types of reasons.

Let me know your thoughts.

**Comment by timbur** [comment]
Interesting.  I think this is okay in most cases, but the (somewhat unrelated) problem I'm running into is that SystemJS doesn't seem to be detecting the correct module format for certain `ace` imports - e.g., ext-modelist.js results in the error `define is not a function` - so I was going to just use `src-min-noconflict`.  How do I force the correct format for external packages?

**Comment by timbur** [comment]
Also, the workaround I was about to use just as you (very quickly, thanks :) responded was to just fork the `ace-builds` repo and use that instead, since I had a feeling there was some override or caching happening.

**Comment by guybedford** [comment]
Sure, if you have suggestions for improving the override that are largely backwards compatible that is welcome. In particular setting the `format: 'amd'` and then selectively applying `shim` to globals (which allows specific modules of format global) might work. Fine-grained format options are also coming in the next configuration update.

**Comment by timbur** [comment]
Thanks again!  For anyone else who might come across this issue, see https://github.com/systemjs/systemjs/wiki/Module-Format-Support.  Hopefully that's enough to help me get this working as-is.

**Comment by timbur** [comment]
Well, I seem to be having trouble forcing the format.  The first file I'm importing is `ace/ace`, so in `config.js`, I've tried:
```
System.meta['ace'] = {format: 'amd'};
```
```
System.meta['ace/*'] = {format: 'amd'};
```
```
System.meta['ace/ace'] = {format: 'amd'};
```
```
System.meta['github:ajaxorg/ace-builds@1.1.9'] = {format: 'amd'};
```

What am I doing wrong?

**Comment by guybedford** [comment]
Format needs to be applied at the override level to override the override - `jspm install ace -o "{format: 'amd', shim:{...} }"`

**Comment by timbur** [comment]
Oh wow.  I had no idea that was possible.  Trying it now.

**Comment by timbur** [comment]
Hmmm... so just out of curiosity, is there any way to specify this within the `jspm` section of `package.json` so that `jspm install` will automatically use the override?

**Comment by timbur** [comment]
Okay I see.  I'm guessing it would be possible, as I now see this within the `jspm` section:
```
    "overrides": {
      "github:ajaxorg/ace-builds@1.1.9": {
        "format": "amd"
      }
    }
```
