### ISSUE TITLE
git submodules are ignored

### ISSUE THREAD

**Issue by capaj** [jspm/jspm-cli#794]
I just tried to add a submodule to a repo and install it through JSPM. I found out that submodules are ignored when fetching the contents from github.
Is this desired behaviour or is it just not yet implemented in JSPM?

**Comment by guybedford** [comment]
Yes submodules are not planned to be supported currently.

**Comment by capaj** [comment]
I think jspm doesn't have to support them, but it would be nice to have some utility cli command which could turn submodules into jspm dependencies.
