### ISSUE TITLE
Cannot find module 'rsvp' when installing subdependency with jspm

### ISSUE THREAD

**Issue by helios1138** [jspm/jspm-cli#797]
I have a package that has in its package.json scripts:{install:'jspm install'}
I have second package, that has this first package as a dependency

When I hit npm install on second package, I get "Error: Cannot find module 'rsvp'"

**Comment by guybedford** [comment]
Is jspm a dependency of any of the packages itself? If so that might be the problem.

**Comment by guybedford** [comment]
And an npm problem at that.

**Comment by helios1138** [comment]
It is a dependency of first package, yes. But that's how it should work, isn't it? Gulp works that way, for example (local dependency + gulp command in install script)

**Comment by guybedford** [comment]
So RSVP is a dependency of jspm, which should be present when jspm attempts its install, but it may have been deduped by npm down to a lower level in the package hierarchy.

I can't really tell though. As I say, this seems like more of an npm issue to me./

I'd suggest not using `jspm install` in a package.json script though.

**Comment by helios1138** [comment]
ah yes, my bad. jspm was in "devDependencies"
