### ISSUE TITLE
bug(server): can't resolve file with unescaped character in the url

### ISSUE THREAD

**Issue by douglasduteil** [jspm/jspm-cli#798]
Hi @guybedford 

I was just playing with the remote mode of jspm when I realize that some characters aren't accepted.
Like: **es5-ext** with the `#` in url.

Example : https://github.com/medikoo/es5-ext/blob/v0.10.7/string/%23/contains/index.js

Don't work with
- https://npm.jspm.io/es5-ext@0.10.7/string/#/contains/index.js
- https://npm.jspm.io/es5-ext@0.10.7//string/%23/contains/index.js

Normal ?

**Comment by guybedford** [comment]
@douglasduteil thanks for posting - it should be working now.

**Comment by douglasduteil** [comment]
Great thanks :)
