### ISSUE TITLE
bundle on windows :: err on resolve path

### ISSUE THREAD

**Issue by marcog83** [jspm/jspm-cli#799]
Hi, 
I updated jspm and when I try to bundle, an error occurs.
I'm on window 8 64bit

Investigating a bit i think there is something in lib/bundle.js in function fileURL.
commit 31819e5a14842dc5aec4ebcb7e999a05c5bf067f

terminal shows me this err

err  Error: Error loading "src/totem/js/config-dev" at file:/C:/workspaces/javascript/2015/.../config-dev.js  ENOENT, open '**C:\C:\**workspaces\javascript\2015\...\config-dev.js'        at Error (native)

As you can see there is double root dir. I restored bundle.js before that commit and I can run jspm
Hope it can help. 
Sorry for my english.

**Comment by marcog83** [comment]
I'm Sorry bothering you,
I just would like say that I re-installed everything, and now it works. I think it was sort of mixin from old version and new version.

**Comment by guybedford** [comment]
Sure, thanks for following up.
