### ISSUE TITLE
jspm dl-loader fails with ENOENT

### ISSUE THREAD

**Issue by textgoeshere** [jspm/jspm-cli#800]
```
$ npm list -g jspm
/home/dave/.node_libraries/lib
└── jspm@0.15.6  (git://github.com/jspm/jspm-cli#7f1d6c01fbde8ca366d6653a08dca313cfe258ca)

$ jspm dl-loader
     Looking up loader files...

err  Error downloading loader files.
Potentially unhandled rejection [2] Error: ENOENT, open '$HOME/.jspm/loader-files/systemjs/dist/polyfills.js'
       system.js
       system.src.js
       system.js.map
       system-csp-production.js
       system-csp-production.js.map
       system-csp-production.src.js
```

This happens consistently with `jspm dl-loader` with any combination of its options, and with a fresh `jspm install`.

Apologies if this is an upstream issue.

**Comment by guybedford** [comment]
Make sure you are running the stable release of jspm - the master branch is always unstable and things do change. Alternatively if you track the latest master this will work, but other things will break as master isn't completely stable right now.

**Comment by textgoeshere** [comment]
Gotcha. I just did `npm install jspm/jspm-cli -g` as per https://github.com/jspm/jspm-cli/wiki/Getting-Started - is there a recommended way of installing a stable version?

**Comment by guybedford** [comment]
Oh wow, thanks so much for spotting that. That was a user wiki edit, which has caused users of the getting started guide to install from jspm master!

**Comment by guybedford** [comment]
(`npm install -g jspm` is the stable install)

**Comment by textgoeshere** [comment]
Oh derp of course, thanks!
