### ISSUE TITLE
CLI API for getting module's file dependencies

### ISSUE THREAD

**Issue by hgl** [jspm/jspm-cli#801]
I'm planning to write a CLI API for jspm to get module's file dependencies:

```js
//myModule.js
import "./foo";;
import "./bar/baz";
import "pkg";
```
```
$ jspm file-deps myModule
foo
bar/baz
```

This is very useful for generating prerequisites for make for example.

Are you interested in accepting this into jspm if I send a PR?

And while using `build.trace` to get the tree and ready its keys, I find it also contains package dependencies. Should I walk the tree to filter file dependencies or is there already some hidden API that already offers this list? If I should walk the tree myself, I guess I have to indexOf exclamation mark to get the correct file names for file types like json, jsx, etc?

Should I actually implement the API in builder?

Thanks in advance.

**Comment by guybedford** [comment]
We could offer something like this via `jspm trace module`, but I'm not sure what value this offers as an API? What would use this? We can just as well use the builder trace API through jspm too. Note `builder.trace` can be passed any expression so you can trace `app - x` etc. but you probably want to do your own custom filtering on the tree too.

**Comment by hgl** [comment]
> but I'm not sure what value this offers as an API?

I mean jspm sub-command actually, sorry for the confusion.

And now I think this feature belongs to a separate project, because it traces es 2015 file dependencies, and that's not something only pertains to jspm.

I will close this issue.
