### ISSUE TITLE
ES6 transcompilation under CSP. Possible without manually creating a watch task?

### ISSUE THREAD

**Issue by MeoMix** [jspm/jspm-cli#803]
Hi there!

I was on the Gitter channel last night attempting to get started with JSPM + SystemJS in a Chrome Extension (CSP + Browser) environment.

I ran into a fair few snags and was unsuccessful in my attempt. This led to a few questions:

First off, [this issue](https://github.com/systemjs/systemjs/issues/421#issuecomment-95745108) implies that it's not currently possible to convince JSPM to load CSP automatically. Is this true? Or, is there a setting I've missed where I can indicate that I would like JSPM to pull down and use system-csp.js rather than system-js?

After manually pulling in the CSP file I encountered another issue: https://github.com/systemjs/systemjs/issues/407. This issue seems to imply that it's not possible for ES6 to "just work" when getting started with JSPM under CSP. Is this correct? If so, is there a timeline/issue I may follow for this support? Otherwise, can I have more details on steps I should be taking to manually support ES6 syntax under CSP?

Hopefully these questions don't have blindingly obvious answers. I tried to do a fair amount of digging, but there's a lot to take in! :balloon:

**Comment by guybedford** [comment]
@MeoMix sorry it's not that clear - thanks for sharing the issues you're having. The next version of SystemJS will automatically use script tag loading for AMD, globals and the register format whenever possible.

But it still will be much the same as using the CSP loader as you are doing - that is to load ES6 your best route here is to use a custom gulp task to transpile files individually into the System.register anonymous module format. This should be fairly straightforward for Babel, but unfortunately I don't have any examples to hand. The Traceur workflow here is described in https://github.com/ModuleLoader/es6-module-loader/wiki/Production-Workflows#building-into-separate-files. The key point is that each file is separately converted into a module like `System.register([], ...)` without any string name at the beginning.

Do post back with how it goes, and if you have a good Babel workflow please do share it too.

**Comment by guybedford** [comment]
Just let me know if you need further help here at all.

**Comment by lookfirst** [comment]
https://github.com/lookfirst/gulp-helpers#gulp-helpers-to-the-rescue

gulp-helpers even creates an intelligent watch task for you when you ask it to (`watchTask: true`).
