### ISSUE TITLE
Incorrect wiki content

### ISSUE THREAD

**Issue by tauren** [jspm/jspm-cli#804]
I believe references to `jspm registry` should be `jspm endpoint` in the following wiki page:
https://github.com/jspm/jspm-cli/wiki/Registries

**Comment by guybedford** [comment]
Thanks - it was updated to `jspm registry` in 0.15. See https://github.com/jspm/jspm-cli/issues/589.

**Comment by tauren** [comment]
Too bad wiki can't be versioned along with JSPM versions. This caused troubles for a coworker. We are still using `jspm@0.8.6`.

**Comment by guybedford** [comment]
Yes we've now included all docs in the repo itself to avoid this issue in future. Is there a reason you're holding back on the upgrade path?
