### ISSUE TITLE
Do not skip writing defaults when doing "jspm init"

### ISSUE THREAD

**Issue by AlicanC** [jspm/jspm-cli#805]
If I have observed correctly, `jspm init` does not write configuration if the default options are chosen.

I see two problems here:

- For example, you can not search for "jspm_packages" in the project to find where the path for it is configured. Since it is not written when the default is chosen, it is nowhere to be found. This forces users to consult documentation where it could be done a lot easier by searching the project.

- When any of the defaults are updated in the future, projects will break since their current setup is not written. This makes any change on defaults a breaking change.

**Comment by guybedford** [comment]
You're right about both points - it was very much about not cluttering users' package.jsons and yes the defaults are part of the backwards-compatible api.

In terms of clarifying things for users, we could explicitly write them in on jspm init, but then allow them to be removed and retain their defaults. Perhaps that is a nicer common ground between being explicit and allowing flexibility not to clutter the package.json. Contributions welcome.

**Comment by AlicanC** [comment]
A flexible solution could be:

- (This might already be the case but,) when you run `jspm init` in an already jspm-init'd project, it reads package.json and makes all the default choices what it read from package.json. So if you keep smashing RETURN on a second `jspm init`, nothing changes.

- A new step is added to `jspm init` which asks if the user wants to write defaults. So the user can run `jspm init` multiple times to add or remove defaults.

---

But, do we really need a flexible solution? How much extra clutter are we talking about here? 2 lines, 3 lines? Are there more stuff not being written that I'm not aware of?

Option 1, close and forget this issue:

- We still have the ease of use and backwards compatibility issues.

Option 2, implement a flexible solution:

- We still have the backwards compatibility issue, because there will still be projects without the defaults written.

Option 3, just write the defaults:

- We are cluttering package.jsons, but isn't the 3-line clutter worth it?

**Comment by AlicanC** [comment]
Also, to give an example, NPM writes (some, if not all) defaults and they really help. Here is a package.json after you smash RETURN until `npm init` completes:

```json
{
  "name": "name-of-the-directory",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
```

This file beautifully documentates itself by those defaults. NPM could easily detect a missing `scripts.test` when `npm test` is ran, but that completely useless property still can serve as documentation. It could also be empty just like `description` and `author`, but since it contains an obvious shell command, you even know what you are supposed to put in there.

**Comment by guybedford** [comment]
Certainly, this makes sense. I think initially jspm was attempting not to be invasive for fear of users rejecting it if it "took over" the package.json. But perhaps this isn't such an issue anymore.

**Comment by guybedford** [comment]
jspm 0.17 beta will not erase defaults when explicitly set manually.
