### ISSUE TITLE
running into npm registry authorization errors

### ISSUE THREAD

**Issue by davis** [jspm/jspm-cli#807]
```
~/w/searcher-fe git:backbone-refactor ❯❯❯ jspm registry config npm                                        ⏎ ✱ ◼
Currently using a custom registry. Would you like to reset to npmrc defaults? [no]:yes
npm registry [https://registry.npmjs.org]:
Currently reading credentials from npmrc, configure custom authentication? [no]:yes
Currently using a username and password. Configure token-based authentication? [no]:no
Enter your npm username [daviskim]:daviskim
Enter your npm password:
Would you like to test these credentials? [yes]:yes

warn Provided npm credentials are not authorized.
```

i'm sure i got my npm password right :(

**Comment by davis** [comment]
to get around this, i simply deleted my npmrc - but it looks like it's not property loading from npmrc...

**Comment by marr** [comment]
bump. I also had to mv ~/.npmrc to get init to work.

**Comment by guybedford** [comment]
@marr can you share your npmrc structure that caused the issue?

**Comment by guybedford** [comment]
There have been a number of npm authorization fixes in https://github.com/jspm/npm/issues/78#issuecomment-112842798 and others. It would be great to hear if this is still happening in the latest beta. Closing in the mean time.

**Comment by if-steven** [comment]
I ran into the same problem with 0.16.0-beta.3. Renaming my .npmrc file fixed things.

Here are the contents of the .npmrc (personal info redacted):
```
_auth = <normal looking auth>
prefix = /home/steven/.npm
#_auth = <normal looking auth token>
#init.author.name = <normal looking first and last name>
#init.author.email = <normal looking email>
#email = <normal looking email>
init.author.name = <normal looking first and last name>
init.aurhor.email = <normal looking email>
email = <normal looking email>
```

**Comment by if-steven** [comment]
Just now pasting that, I noticed a typo on the second to last line. The problem with jspm install remains after fixing the typo with `init.author.email`.
