### ISSUE TITLE
jspm 0.16.0-beta breaks paths to packages

### ISSUE THREAD

**Issue by mikz** [jspm/jspm-cli#810]
Because it is a Rails application, I'd like to keep packages and app code in two different subfolders.

I've tried upgrading jspm to beta because of (#809) and found nasty behaviour.

Before upgrade:

```
$  jspm bundle main
     Building the bundle tree for main...

       greeter.js
       main
       npm:babel-runtime@5.4.7/core-js/object/define-property
       npm:babel-runtime@5.4.7/helpers/class-call-check
       npm:babel-runtime@5.4.7/helpers/create-class
       npm:core-js@0.9.14/library/fn/object/define-property
       npm:core-js@0.9.14/library/modules/$
       npm:core-js@0.9.14/library/modules/$.fw

ok   Built into app/assets/javascripts/build.js with source maps, unminified.
```

After upgrade:

```
$ jspm bundle main 
     Building the bundle tree for main...

err  Error: ENOENT, open '/Users/mikz/Developer/3scale/jspm/app/assets/javascripts/main'
         at Error (native)
```

```
$ pwd
/Users/mikz/Developer/3scale/jspm
$ node --version
v0.12.4
```

You can see config.js and package.json in https://github.com/mikz/rails-jspm-es6-example/tree/jspm-beta

**Comment by guybedford** [comment]
@mikz you need to run `jspm init` or something that alters the configuration first to upgrade the config file. Will clarify in the upgrade guide.

**Comment by guybedford** [comment]
I've updated the release notes. Let me know if you're still having issues at all.

**Comment by mikz** [comment]
@guybedford I did that in https://github.com/mikz/rails-jspm-es6-example/commit/aea2dbd66b886c3373d4359f5ac2eec3db907177 but without success.

Still, it tries to access outside of the project folder. Looks like the relative path `../../../` is from the baseURL but it expands it from the current workdir instead.

**Comment by guybedford** [comment]
@mikz the baseURL in https://github.com/mikz/rails-jspm-es6-example/blob/master/package.json#L4 must also be `app/assets` so that the baseURL is the same reference point on both the client and server.

**Comment by mikz** [comment]
@guybedford but in Rails Asset Pipeline the path on filesystem does not reflect the path in the browser. 

Rails combines all files from `app/assets/javascripts/` and `vendor/assets/javascripts/` and other configurable paths and serves them in the browser prefixed with `/assets/`.

But that can easily happen with any other setup where path on the filesystem does not match the path in the browser. For example if I have `public/assets/file.js` and a server serving contents of `public` the path in the browser will be `/assets/file.js` but in the console `public/assets/file.js`.

**Comment by guybedford** [comment]
@mikz you need to run `jspm init` to update the configuration file in the beta. It will upgrade the paths and SystemJS configurations to add the js extensions properly. This is a catch though, will aim to avoid this issue via https://github.com/jspm/jspm-cli/issues/817.

**Comment by mikz** [comment]
@guybedford I did as commit https://github.com/mikz/rails-jspm-es6-example/commit/aea2dbd66b886c3373d4359f5ac2eec3db907177 

Sorry, when I was crafting the example I didn't notice that I pasted wrong error message.
The correct one is


```
   Building the bundle tree for main.js...

err  Error: ENOENT, open '/Users/mikz/vendor/assets/javascripts/jspm_packages/npm/babel-core@5.4.7.js'
         at Error (native)
```

The problem is that the workdir is `/Users/mikz/Developer/3scale/jspm/` but it tries to access packages in  `'/Users/mikz/vendor/assets/javascripts/jspm_packages/`. Looks like it traverses the computed paths https://github.com/mikz/rails-jspm-es6-example/blob/aea2dbd66b886c3373d4359f5ac2eec3db907177/app/assets/javascripts/config.js#L12-L13
from from current directory (`/Users/mikz/Developer/3scale/jspm/../../../`) instead of from baseURL (`/Users/mikz/Developer/3scale/jspm/app/assets/javascripts/../../../`).
Hope it is clear now.

**Comment by guybedford** [comment]
@mikz the relation of your baseURL to your jspm_packages folder must be the same between client and server. That is it is exactly calculating `vendor/assets/javascripts/jspm_packages` relative to `app/assets/javascripts` giving `../../../vendor/assets/javascript/jspm_packages`.

**Comment by mikz** [comment]
@guybedford that kind of prevents it from being used in frameworks where path on filesystem does not match the path in the browser.
I was expecting that the `config.js` is used only on the client and `packages.json` on the server.
Any plans to fix this? Because the only way I see to make it work is to use separate project independent on rails.
That is quite pity, I was hoping to use our tooling, instead of bootstrapping Node project.

**Comment by guybedford** [comment]
@mikz the only thing you need to ensure is that jspm_packages is within the baseURL, and that the structure of baseURL is the same between client and server.

**Comment by mikz** [comment]
@guybedford thats the thing.

On my server the base is `app/assets/javascripts/` (when I'd stick all files to one folder).
But that is server on the client as `/assets/`.

**Comment by guybedford** [comment]
That's fine, but just ensure the structure of both of those folders matches. That is you have:

`app/assets/javascripts/jspm_packages` on the server
`/assets/jspm_packages` on the client

**Comment by mikz** [comment]
@guybedford works awesome, sorry for the misunderstanding. The rails app works https://github.com/mikz/rails-jspm-es6-example/

Will send you link to the blog post how to use ES6 with jspm+babel+rails and get tests (es6 too!) working.
