### ISSUE TITLE
Allow sub-dependencies to be excluded/ignored

### ISSUE THREAD

**Issue by dak** [jspm/jspm-cli#811]
Backbone 1.2.0 no longer requires jQuery; however, [it still attempts to load it](https://github.com/jashkenas/backbone/wiki/Using-Backbone-without-jQuery#without-jquery).
Browserify and Webpack have options to exclude the sub-dependency; however, it appears that JSPM is currently lacking this option.

**Comment by guybedford** [comment]
You can do this via a custom override - `jspm install backbone -o "{map: {jquery: '@empty'}}"`.

**Comment by dak** [comment]
@guybedford Perfect.  Perhaps this could be more obviously documented somewhere (or maybe I just kept missing it)?

**Comment by guybedford** [comment]
Sure, I've added a note at the end of https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm.
