### ISSUE TITLE
Question: Meteor package loader

### ISSUE THREAD

**Issue by dvc94ch** [jspm/jspm-cli#812]
If I understand correctly jspm only handles front-end packages? Would it be suited to load Meteor packages that include both server and client side components?

**Comment by guybedford** [comment]
We could support the Meteor registry with a conversion layer just like we do for npm and allowing `jspm install meteor:x` etc. It's quite a job though, but very much something that should be done.

**Comment by dvc94ch** [comment]
I played around with jspm on a little project, I didn't know it would work for server packages too. So I don't need npm at all to manage packages like gulp etc.?
I'm starting hackreactor remote beta in a few weeks, and this is something I'd really be interested in taking a look at as a graduation project. I'll have to see if I'm up to it dough...

**Comment by guybedford** [comment]
See https://github.com/jspm/jspm-cli/wiki/NodeJS-Usage for the guidelines on server use. Support is not quite there yet for gulp etc, but is improving over time.

Do they allow time for open projects then? It is a tough job and something that's very much about understanding the SystemJS / jspm resolution algorithm and how to map the project into something that can work with that. Note that the conversion process will be changing in about 4 weeks as well, so do ping me if you want to look into this more deeply and we can get it on the new concepts.

It could also be worth reaching out to Meteor as well on this. We've discussed things along these lines before, it's just in need of a contributor.

**Comment by pavlovich** [comment]
Any further progress on jspm <-> meteor ??? Did you end up reaching out to the Meteor Development Group (MDG) on this issue?

**Comment by dvc94ch** [comment]
The isopack format that atmosphere currently uses is being deprecated.
According to MDG roadmap they're reverting to fetching and building
packages from src.

**Comment by pavlovich** [comment]
So, if they are reverting to fetching/building ... is there a possibility of them adopting jspm as the umbrella standard for doing the management of that? Have they selected the solution for that yet?

**Comment by dvc94ch** [comment]
That's MDG politics... Very unlikely at the moment. They have made some
design decisions that make things harder than it should be. I think they
are trying to move in the direction of being more a library then a
framework which would be awesome imo. But we'll have to wait and see...

**Comment by Gaelan** [comment]
@guybedford I'd love to work on this (I've been thinking about this for a while, just found this issue), though I have an amazing talent at starting then dumping side projects. :smile: Don't know how much you know about this, but here is a quick rundown of Meteor's (current) package semantics:

 - A package has a `package.js` (not `json`) file, declaring dependencies (NPM and Meteor) and included files.
 - In package files, variables declared with var are file-scope, variables declared without are package-global
 - The `package.js` file lists which package-global variables should be exported.
 - The exports of a packages's dependencies are available globally within a package.
 - Within a package, load order is based on the order they are added in the `package.js`.
 - There are packages (community and MDG) providing build plugins, many of which we might want to somehow shim:
    - Babel (`ecmascript`)
    - CoffeeScript (`coffeescript`)
    - Spacebars, the template language for Meteor's default UI library Blaze (`spacebars`)
      - Many new Meteor apps these days use React anyway, so this one isn't SUPER important
    - JSX (`jsx`, will probably usually be used from the umbrella `react`)
    - Accessing declared NPM dependencies on the client-side via Browserify (`cosmos:browserify`)
      - We would probably want to shim this one to use JSPM instead
    - Many more, but the above are the more common ones

Meteor's docs on this: http://docs.meteor.com/#/full/writingpackages

**Comment by guybedford** [comment]
@Gaelan yes a `meteor:x` registry installer for jspm is a very suitable project, and @dvc94ch did start some research along these lines here in https://github.com/jspm-meteor/discussion, but there are some difficulties and apparently there are some shifts happening with Meteor packaging that may be worth waiting for. @dvc94ch do you have any links to info about Meteor's packaging plans?
