### ISSUE TITLE
ES6 imports behaving differently in jspm vs. babel-node

### ISSUE THREAD

**Issue by jedrichards** [jspm/jspm-cli#813]
Sorry if this isn't the right place (maybe the Babel repo might be better). But thought I'd try here first.

I'm writing some isomorphic code, designed to run on both the client and server and some ES6 imports aren't working as expected.

Given the following module,

```js
export default {
  foo: 'foo'
};
```

When I interact with it in Node (iojs 2.0.2) using `babel-node` I can import `foo` as a named import directly,

```js
import {foo} from './my-module';
console.log(foo); // "foo"
```

But when I interact with it in the browser via jspm/SystemJS then it doesn't get that named import properly. It does however get the whole default export,

```js
import {foo} from './my-module';
import MyModule from './my-module';
console.log(foo); // undefined
console.log(MyModule); // Object {foo: "foo"}
```

Any idea what's going on here? Is this a jspm thing, or a Babel thing?

I should note that I'm observing this behaviour in a freshly initialised jspm project that otherwise seems to be working aside from the import discrepancy between Node vs browser.

Also it isn't just my own modules, I'm not able to import in this way from some 3rd party libs too. For example, trying to do this with React in the browser also fails in the same way,

```js
import {Component} from 'react';
```

And having checked the React source they're exporting components from the lib in a way that should support the above syntax ...

Thanks for your time! :)

**Comment by jedrichards** [comment]
Additional information: I just ran the exact same files through browserify/babelify using the same version of babel-core and it seems to be working correct, not seeing the same discrepancy.

**Comment by guybedford** [comment]
@jedrichards while it works to import named exports in this way, this is not ES6-compatible code you are writing. Default exports can not be read like named exports, unless you convert the module into CommonJS. Basically this is by design.

/cc @sebmck this an interesting catch we might see more of in future. I'm sure we discussed this case.

**Comment by sebmck** [comment]
@guybedford Oh weird. There seems to be various issues with coercing to `module.exports` when there's 1 default export. Do you think it's worth revisiting it and reverting that behaviour?

**Comment by guybedford** [comment]
@sebmck I think that's very much up to you and what you think will work best for your users, but it could be worth considering making it a flag and not a default. I saw a discussion about it on the TypeScript repo and I believe they decided against it.

**Comment by jedrichards** [comment]
Oh wow, OK. Thanks for the heads up. So is the below the correct approach given the single default export in my example module?

```
import MyModule from './my-module';

const {foo} = MyModule;
```

As for doing `import {Component} from 'react'` I've seen this in a lot of code around the internet. Am I right in thinking its better to err on the side of caution and not do this until such 3rd party code is available in ES6 and their export strategy is unambiguous?

**Comment by guybedford** [comment]
@jedrichards it's completely fine to do named imports, but only against named exports not default exports.

**Comment by guybedford** [comment]
@sebmck I'm sure users will learn to do the right thing here regardless though.

**Comment by jedrichards** [comment]
@guybedford The React ES5 export code looks like this,

```js
var React = {
  Component: ReactComponent,
  ...
};

module.exports = React;
```

I imagine if/when React is published natively in ES6 they'll choose to expose `Component` and friends as named exports.

But is what your saying that, until such time, we should treat the above code as a single default export and import it into our ES6 apps as such?

Is there any way that SystemJS/jspm would interpret ES5 code as having named exports, or will it always assume for a now single default export?

**Comment by guybedford** [comment]
@jedrichards CommonJS is treated differently here and does allow named imports via a compatibility process.
