### ISSUE TITLE
jspm 0.16.0-beta not loading certain nested dependencies?

### ISSUE THREAD

**Issue by lewisl9029** [jspm/jspm-cli#814]
I just gave the new beta a try and ran into some errors complaining about missing dependencies in the console.

It looks like only top level dependencies are being loaded. I updated https://github.com/lewisl9029/jspm-test to demonstrate this issue. All it does is load ionic (using the override in the registry), which is supposed to load angular as a dependency, but when running the site we get an "angular is not defined" error in the console, and in the Chrome Sources tab there's no "jspm_packages/github/angular" folder.

The steps I went through to update the repo was:

1) remove the existing jspm_packages folder and config.js files
2) run jspm init -p and go through the wizard
3) run jspm install

I'm not too sure if this is a SystemJS issue, an issue with my upgrade process or if there's something wrong with the overrides in the registry, so I decided to post this here for now.

**Comment by guybedford** [comment]
Thanks, yes this is a SystemJS bug. I've posted https://github.com/systemjs/systemjs/issues/494 and will aim to create a patch soon.
