### ISSUE TITLE
Running jspm init -p multiple times concats baseURL 

### ISSUE THREAD

**Issue by mikeobrien** [jspm/jspm-cli#815]
I noticed that running `jspm init -p` multiple times concatenates the `baseURL` in the `package.json` file. So for example running it 3 times, with the default options, produces the following where `src/wwwroot` is concatenated to the previous value: 

```js
{
  "name": "SetecAstronomy",
  "version": "0.0.0",
  "jspm": {
    "directories": {
      "baseURL": "src/wwwroot/src/wwwroot/src/wwwroot"
    },
    "devDependencies": {
      "babel": "npm:babel-core@^5.1.13",
      "babel-runtime": "npm:babel-runtime@^5.1.13",
      "core-js": "npm:core-js@^0.9.4"
    }
  }
}
```

Is this the expected behavior or a bug?

Thx!

**Comment by guybedford** [comment]
I'm not able to replicate this at all.

I set my package.json to contain the baseURL `src/wwroot`. Then run `jspm init -p` and select all the default options. There is no concatenation of the baseURL when I do this. Which OS are you running on?

**Comment by mikeobrien** [comment]
I'm on Yosemite & jspm 0.15.7. Ok, good to know, I'll try to dig in when I get a minute.

**Comment by timaschew** [comment]
I'm on Yosemite as well and on jspm 0.15.7, I cannot reproduce it with these steps:

```
mkdir test
cd test
jspm init .
# 1. ENTER
# 2. src/wwwroot ENTER
# ....

jspm init -p
# 1. ENTER
# 2. src/wwwroot ENTER
# ....
```

package.json still looks fine:
```
{
  "jspm": {
    "directories": {
      "baseURL": "src/wwwroot"
```

**Comment by mikeobrien** [comment]
Thx for the feedback. Must be something funky on my end.
