### ISSUE TITLE
Bundle output to stdout

### ISSUE THREAD

**Issue by OliverJAsh** [jspm/jspm-cli#820]
Would this be possible as a flag?

**Comment by OliverJAsh** [comment]
Perhaps it could output a JSON output: a prop for source and a prop for the source map.

**Comment by sergei-maertens** [comment]
+1

**Comment by matthewbauer** [comment]
I haven't tried this yet but:

```jspm bundle bundle.js /dev/stdout```

might work?

**Comment by guybedford** [comment]
Trying this gives me the error - 

```
err  Error: EACCES: permission denied, open '/dev/stdout.map'
    at Error (native)
```

The question with such a stdout feature is just how to handle source maps.

**Comment by subhaze** [comment]
I was looking for this ability today as well. As for source maps, would it be possible to inline them when sending bundle to stdout?
