### ISSUE TITLE
JSPM, Windows and errors while using prompt "-y"

### ISSUE THREAD

**Issue by KingRial** [jspm/jspm-cli#822]
When trying to install new jspm libraries on Windows 8.1, If I use the following command:
```
jspm install D:\WindowsPathYouLike\package.json
```
everything goes fine.

If I try:
```
jspm install D:\WindowsPathYouLike\package.json -y
```
I get the following error:
```
err  Registry D not found.
err  Unable to load registry D
warn Installation changes not saved.
```

JSPM and NodeJS are to the latest stable releases.

I am starting to realise, maybe, I am using improperly JSPM and I cannot use that path as a  paramater to tell him where to find the .json file.

**Comment by KingRial** [comment]
I think I am using improperly JSPM ^^

**Comment by guybedford** [comment]
Yes exactly, this is not an option. jspm will search for the package.json by checking the current directory and then going up through the directories until it finds the package.json. That's all that is supported.
