### ISSUE TITLE
err  Error looking up github:angular/bower-angular

### ISSUE THREAD

**Issue by csrinaldi** [jspm/jspm-cli#826]
I have bugs in packages where it depends on  "github:angular/bower-angular"
By Example: 
  If I want install  jspm install angular-material=github:angular/bower-material@master;
 
  Looking up github:angular/bower-material
  Updating registry cache...
  Looking up github:angular/bower-angular
  Looking up github:angular/bower-angular-animate
  Looking up github:angular/bower-angular-aria
  Looking up github:systemjs/plugin-css

err  Error looking up github:angular/bower-angular

warn Installation changes not saved.

Any suggestions?

**Comment by mikaelborg72** [comment]
We're facing the same issue.  Seems OK via a npm install but not jspm.

**Comment by guybedford** [comment]
Can you clarify which version of jspm you are running, and have you authenticated ok with GitHub?

**Comment by mikaelborg72** [comment]
We were running 0.15.2, but thanks to your nudge I upgraded to 0.15.7 and it now seems to work again.  Thanks!

**Comment by csrinaldi** [comment]
Also upgrade to the version jspm@0.15.7 and the problem is resolved
