### ISSUE TITLE
How to resolve imports on the server when using jspm?

### ISSUE THREAD

**Issue by togakangaroo** [jspm/jspm-cli#827]
If I have es6 modules which don't require a browser environment to run (eg a React application) I should be able to run unit tests for these on the server.

I've figured out how to run mocha with es6 manually, and I've even figured out how to stub out dependencies with [proxyquire](https://github.com/thlorenz/proxyquire) but I can't quite figure out what to do with modules installed via jspm.

Say for example I jspm installed `momentjs`. That's a well-tested library and I don't really want to stub it out, but simply running through node's `require` function isn't going to include it either as node has no idea what to do with

```bash
\Scripts\jspm_packages\github\moment> cat .\moment@2.10.2.js
define(["github:moment/moment@2.10.2/moment"], function(main) {
  return main;
});
```

So what is the intended workflow for unit testing scripts that use modules pulled in via jspm?

It seems like the cli must has some of the path resolving stuff that would be helpful here but I can't quite figure out how that helps this use case

**Comment by guybedford** [comment]
jspm runs in Node via https://github.com/jspm/jspm-cli/wiki/NodeJS-Usage, although not all libraries will support execution in the Node environment.

**Comment by togakangaroo** [comment]
I see...so rather than node's `require` I can use the jspm api to import` command to properly include modules, right? What about stubbing out modules for unit tests? Is there a way to handle this?

**Comment by guybedford** [comment]
Yes - you can intercept requires by setting stubs on SystemJS directly:

`System.set('github:components/jquery@1.2.3', System.newModule({ jquery:
'stub' })`

Alternatively you can do this via map config:

System.config({
  map: {
    jquery: 'jquery-stub'
  }
});

**Comment by togakangaroo** [comment]
@guybedford just getting back to this - I see, but will that do anything when run on the server?

**Comment by guybedford** [comment]
Yes.

**Comment by guybedford** [comment]
Did you manage to make process here? Let me know if you have any further questions.

**Comment by togakangaroo** [comment]
Just an update guy, I managed to get it working on the client but too much pressure to move forward to spend time hacking on it in node. I might come back to it later. Thanks Guy
