### ISSUE TITLE
jspm and npm in the same directory not possible?

### ISSUE THREAD

**Issue by timaschew** [jspm/jspm-cli#828]
is it right that I cannot use jspm and npm in the same directory?
jspm is writing dependencies into the __package.json__ in its own format, which is invalid for npm.
Why jspm is not using its own file, for instance __jspm-modules.json__ ?

**Comment by guybedford** [comment]
package.json is a shared format linked to CommonJS and not owned by npm, in fact npm encourages its extension. jspm will prefix dependencies under the "jspm" package.json property to avoid conflict by default.

**Comment by timaschew** [comment]
but in the jspm-es6 example, after I run `jspm install` my package.json changed to this:

```
{
  "registry": "jspm",
  "main": "lib/main",
  "directories": {
    "lib": "lib"
  },
  "dependencies": {
    "jquery": "github:components/jquery@^2.1.4"
  },
  "devDependencies": {
    "babel": "npm:babel-core@^5.1.13",
    "babel-runtime": "npm:babel-runtime@^5.1.13",
    "core-js": "npm:core-js@^0.9.4"
  }
}
```
and `npm install` is failing now

**Comment by guybedford** [comment]
You should be able to run `jspm init -p` and select yes for the first question (and defaults for the rest) to prefix under "jspm" in the package.json.

**Comment by timaschew** [comment]
okay, so I just cloned the repo and run `jspm install`
the package.json has a `"registry": true` entry and that's the reason why jspm didn't use prefixes.

I also notices that traceur was replaced by babel when I run `jspm install`. Seems that babel become the new standard.
Maybe it's better remove the jspm_packages from this repo and do a `jspm init` instead.
So everyone who will clone this repo will always get the __new__ defaults, I can do a pull request?

**Comment by guybedford** [comment]
This repo uses the convention of not prefixing - it's optional per-project. In this case there is no need for npm in the project, so no need to prefix.

**Comment by timaschew** [comment]
ok

**Comment by timaschew** [comment]
If I choose __no__ at `Would you like jspm to prefix the jspm package.json properties under jspm?`
jspm is asking me all the questions (not just about prefixing)every time when I install something.

**Comment by guybedford** [comment]
It asks all the questions every time, with the defaults set to your last response.

**Comment by timaschew** [comment]
but it doesn't asking anymore if I answer _yes_ to use jspm prefix in pacakge.json

**Comment by guybedford** [comment]
That is very strange and shouldn't happen. What OS are you running, and can you share the full output in this case?
