### ISSUE TITLE
Production Mode and minify dependencies

### ISSUE THREAD

**Issue by csrinaldi** [jspm/jspm-cli#829]
In Production mode I followed the steps in the documentation, and I have some questions:
    1) If I minify the output script, it fails.
    2) It is possible that all the dependencies managed by jspm when they are downloaded at the start of the croissant, are minified and / or minified all in one?

  

   Sorry for the ignoranciam maybe this was discussed

Greetings and thanks .....

**Comment by guybedford** [comment]
Were you able to tell from the minification error message which code was causing the issue? It sounds like this may be an issue between uglifyjs and the transpiled code, that needs to be tracked down.

The suggested method is to always download unminified as it offers the best debugging experience (source maps still don't quite compete with plain sources yet). In such a situation, running a gulp task or server-level minification over all or part of jspm_packages is then the recommended approach for separate files loaded in production.
