### ISSUE TITLE
jspm init is looking into sibling directory for config.js

### ISSUE THREAD

**Issue by timaschew** [jspm/jspm-cli#833]
I create a empty directory, then I run `jspm init`
and this is the result:

```
     Initializing package at ../../
     Use jspm init . to intialize into the current folder.
ok   Verified package.json at ../../package.json
     Verified config file at ../jspm-first/config.js
```

It strange enough that it init is looking to the parent directory, until it find a package.json when I want to init a new project.

But why jspm is looking for the config.js in a different directory? it's not a parent, it's a sibling.

**Comment by yang-wei** [comment]
I don't have such problem in version `0.15.7`.

**Comment by guybedford** [comment]
jspm will search down the folder hierarchy until it finds the first package.json, that is then assumed to be the project package.json. It sounds like in this case you're trying to initialize a project within a project that already has a package.json.

You can use `jspm init .` to make sure it initializes into the current folder without checking for an existing package.json.

**Comment by timaschew** [comment]
> `jspm init .`

that is exactly what I need, thanks!
