### ISSUE TITLE
Cannot find module "npm\cli"

### ISSUE THREAD

**Issue by eliashdezr** [jspm/jspm-cli#834]
Enviroment setup:
  - Windows 8.1 

If I run **jspm -v** from  **AppData\Roaming\npm**, I get this message.
```
0.15.7
Running against local jspm install.
```

But if I try to run the same command outside the **AppData\Roaming\npm** folder, I get this error:
```javascript
module.js:338
    throw err;
          ^
Error: Cannot find module 'C:\Users\eliashdezr\AppData\Roaming\npm\cli'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Liftoff.<anonymous> (C:\Users\eliashdezr\AppData\Roaming\npm\node_modules\jspm\jspm.js:33:5)
    at Liftoff.<anonymous> (C:\Users\eliashdezr\AppData\Roaming\npm\node_modules\jspm\node_modules\liftoff\index.js:196:12)
    at Liftoff.<anonymous> (C:\Users\eliashdezr\AppData\Roaming\npm\node_modules\jspm\node_modules\liftoff\index.js:164:7)
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
```

What I found is that running from **AppData\Roaming\npm**, ```modulePath``` has the following value:
```
modulePath: 'C:\\Users\\eliashdezr\\AppData\\Roaming\\npm\\node_modules\\jspm\\api.js',
```

And when runs outside the npm folder, it has this value:
```
modulePath: 'C:\\Users\\eliashdezr\\AppData\\Roaming\\npm\\jspm',
```

**Comment by guybedford** [comment]
Have you got jspm globally installed in the path here? It sounds like you're running the path too low to detect the local install, and there's no global to fall back on?

**Comment by eliashdezr** [comment]
Yes, npm

**Comment by guybedford** [comment]
Are you sure this folder is in your npm lookup path? ie can you do:

```
node
require('bower')
```

From outside of `AppData\Roaming\npm`?

**Comment by eliashdezr** [comment]
@guybedford 

I found the issue. After debugging in a clean Windows Install (VM) and my Windows Install. I found out that this **ENVIRONMENT VARIABLE** was the issue:
```
NODE_PATH:
%PROGRAMFILES%\nodejs\node_modules;C:\Users\eliashdezr\AppData\Roaming\npm;C:\Users\eliashdezr\AppData\Roaming\npm\node_modules
```
What I couldn't figure out is why was messing only with **jspm**, since running **bower, gulp or yo** outside the **AppData\Roaming\npm**, there were no issues at all.

Thanks for the support!

**Comment by guybedford** [comment]
Thanks for updating - glad to hear you sorted it out.

**Comment by josegranja** [comment]
Sorry I know this issue has been closed but it's happening as well to me. I'm using Windows and I'm adding both path:

C:\...\nodejs 
C:\...\npm

to my path variables. I see that the jspm bin is located in c:\...\npm but it's trying to fetch the cli module from c:\....\npm\cli instead of c:\...\npm\node_modules\cli

jspm is installed globally:

├── .....
├── bower@1.6.5
├── cli@0.11.1
├── jspm@0.16.14
├── ....
