### ISSUE TITLE
Configuration for multiple jspm packages

### ISSUE THREAD

**Issue by timbur** [jspm/jspm-cli#835]
I feel like I must be missing something simple or doing something wrong, because this is surely already considered/implemented.

If I have `some-module` created using jspm and it of course has its own set of dependencies and possibly custom `config.js`, when I install that module into `another-module` using `jspm install some-module=github:timbur/some-module`, shouldn't `another-module` execute `some-module`'s `config.js` as well as import all of its dependencies?  I'm currently running into an issue where `some-module`'s dependencies are missing when using `System.import('some-module')` within `another-module`.  I'm not doing anything out of the ordinary, so I'm really confused as to why this is happening.

**Comment by timaschew** [comment]
>  shouldn't another-module execute some-module's config.js

I don't think so.

> as well as import all of its dependencies?
 
dependencies only working if you using npm as endpoint. If you installing from github and the dependencies defined in the package.json should be loaded from npm you need an override, for instance:

`jspm install github:timbur/some-module -o '{"registry": "npm"}'`

for more information see https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm#package-dependencies

**Comment by timbur** [comment]
In that case, what is the recommended way to solve the following problem:

I'm importing a module that uses the [`ace`](https://github.com/ajaxorg/ace-builds) editor, but the `jspm` registry has an [override](https://github.com/jspm/registry/blob/master/package-overrides/github/ajaxorg/ace-builds%401.1.6.json) that points to the `src` directory, even though I need it to be the `src-min-noconflict` directory, as that seems to be the only one that works for me.  As a simple workaround for this, I've forked the `ace-builds` repo and will use that instead so that jspm will ignore the override, and then within my `config.js` (after using `jspm install ace=github:timbur/ace-builds`), I've set the following so that any references to `ace/*` will retrieve files from within the `src-min-noconflict` directory:
```js
System.config({
  "paths": {
    "github:timbur/ace-builds@1.1.9/*": "jspm_packages/github/timbur/ace-builds@1.1.9/src-min-noconflict/*.js"
  }
});
```

And of course, when I import said module into another module, since that configuration isn't automatically executed, `ace` fails to load.

**Comment by timbur** [comment]
Actually, scratch that last comment.  Let me try something.  I expect I'll have another similar question though.

**Comment by guybedford** [comment]
It sounds like you want to alter `directories.lib` in the override for Ace here? If you think this would be beneficial for others we can consider altering the primary override.

**Comment by timbur** [comment]
Yeah that's what I ended up doing (via `jspm install ace -o "{directories: {lib: 'src-min-noconflict'}}"
`).  It probably would be beneficial to use the `noconflict` version by default, because the `require` and `define` statements throughout `ace`'s code (for themes and extensions) seem to require a significant amount of extra configuration to make them work correctly, which I've been unable to do successfully.

That said, I'm now stuck on automatically setting `ace`'s `basePath` somehow, so that it knows where to look for themes, extensions, etc.  What's the best way to determine the location of some module?  Right now, I'm using `System.locate` as follows, but it of course doesn't work when the accompanying module is installed within another module where `ace` is not within `System.map`.  The asynchronous nature of it also makes it a PITA to load any other modules that depend on `ace`'s `basePath`.
```js
module.exports = function (src) {
  // point ace to the proper directory for its files
  System.locate({name: System.map['ace']}).then(function (aceLocation) {
    aceLocation = aceLocation.replace(window.location.origin, '');
    aceLocation = aceLocation.replace('.js', '');
    ace.config.set('basePath', aceLocation);

    System.import('./src/ui').then(function (ui) {
      ui(src);
    });
  });
}
```
And for some reason, even though `System.trace = true`, `System.loads` is undefined.  But suppose that did work and some module imports the module that uses `ace`, how would we ensure that the top level module sets `System.trace = true` without having to manually set it?

I suspect my problem is actually related to #814.  From what I can tell, I've completely reconfigured everything correctly using only `jspm-cli` (no manual editing of `config.js` or `package.json`) and used package overrides as necessary.  I've also upgraded `jspm` to 0.15.7, and `jspm --version` confirms that.  How do I check which version of SystemJS is being used within some module?

**Comment by timbur** [comment]
I've managed to make it locate `ace` reliably:
```js
module.exports = function (src) {
  var defined = System.defined;
  var aceTest = /\/ace$/;
  var aceName = null;

  for (var key in defined) {
    if (aceTest.test(key)) {
      aceName = key;
      break;
    }
  }

  if (!aceName) {
    throw new Error('Ace not defined?');
  }

  System.locate({name: aceName}).then(function (aceLocation) {
    // point ace to the proper directory for its files
    aceLocation = aceLocation.replace(window.location.origin, '');
    aceLocation = aceLocation.replace('/ace.js', '');
    ace.config.set('basePath', aceLocation);
    
    System.import('web-tedit/src/ui').then(function (ui) {
      ui(src);
    });
  });
}
```

But I'm still running into the issue where SystemJS is looking in the wrong place for dependencies when used within a higher-order module.  I guess I'll try manually updating the `jspm_packages/system.js` file(s) just in case they an old bugged version.  -_-

**Comment by timbur** [comment]
I keep running into all kinds of issues.  -_-  Fix one bug, another pops up unexpectedly.

Manually upgrading the `system.js` files fixed the dependency issue, but now I have to use `System.defaultJSExtensions = true;` and that still doesn't quite work correctly because it is now looking for some files with the extension `.js.js` (even though I've explicitly configured it otherwise), and it is somehow getting stuck in an infinite loop when using `System.import` for `cjs` modules, which definitely did not happen before.  I guess I'll try a significantly older version of SystemJS now.

**Comment by guybedford** [comment]
@timbur the latest SystemJS only works against jspm 0.16 beta.

**Comment by timbur** [comment]
What version(s) should I use that will load dependencies correctly and use the correct file extensions?  And how do I go about ensuring that version is installed correctly?  I tried using the `--edge` flag yesterday but maybe I didn't do it right.

**Comment by timbur** [comment]
It looks like `npm install jspm@beta` does the trick, though I had to run `jspm cache-clear` before running `jspm install` (probably an unrelated issue).  But now, every time I run `jspm install`, I get `Timed out on lookup for npm:babel-core, retrying (1).` for every npm package.  :(

**Comment by timbur** [comment]
What difference between the last stable release and the beta version would cause an infinite loop?  Has something changed with the way modules are `require`d?  I can't seem to track it down because it's happening in multiple places.  The only thing that makes sense is that maybe some internal `loading` flag is no longer being properly set when there is a circular dependency.  Has something changed in this regard?  Because everything loaded fine for me on the last release, but I need this beta release for its ability to deeply load dependencies.

**Comment by timbur** [comment]
I finally tracked down what was causing the infinite loop.  One of the external modules I'm using relies on another module that performs its own checks for `cjs` or `amd` availability - see source [here](https://github.com/creationix/dombuilder/blob/master/dombuilder.js).  My guess is that SystemJS was using the wrong format, probably `amd`, so I've explicitly overridden the format for that module to use `cjs` and it loads fine.  However, this wasn't a problem before, so the root issue must be due to some change to either the `amd` loader or the format detection.
