### ISSUE TITLE
Based on what does jspm add all these dependencies to certain packages?

### ISSUE THREAD

**Issue by timmolendijk** [jspm/jspm-cli#840]
For example, when installing `npm:baconjs`, I ended up with the following dependencies (from `.jspm.json`):

```
  "dependencies": {
    "fs": "github:jspm/nodelibs-fs@^0.1.0",
    "path": "github:jspm/nodelibs-path@^0.1.0",
    "process": "github:jspm/nodelibs-process@^0.1.0",
    "assert": "github:jspm/nodelibs-assert@^0.1.0",
    "buffer": "github:jspm/nodelibs-buffer@^0.1.0"
  }
```

I'm trying to understand what triggers these dependencies, and where they are used but I don't get it. Only `"buffer"` seems to be `require`d inside `Bacon.js` and even that one is not actually used or even referenced anywhere.

All these extra "ghost dependencies" make my app pretty darn heavy though, and as long as I don't understand their purpose it's hard for me to judge whether I will easily be able to "bundle them away" for production releases.

Anyone can shed some light on this thing? Thanks!

**Comment by guybedford** [comment]
If any js file within the npm package (even a test file) contains a require to fs, then it will be a dependency.

Note that when bundling, only the dependencies of the direct files you bundle will be used, so you will probably avoid bundling unnecessary dependencies anyway.

Unnecessary detection can be avoided via setting `files` or `ignore` files or folders.
