### ISSUE TITLE
Default path configuration in `config.js` encourages bad practice

### ISSUE THREAD

**Issue by AlicanC** [jspm/jspm-cli#842]
In https://github.com/systemjs/builder/issues/194, the SystemJS best-practice is explained as:

> - Leave out extensions for packages (import 'jquery' etc)
> - Include extensions for any paths (import './file.js')
> - Subpaths of packages are still a somewhat grey area though (import 'jquery/subpath' or import 'jquery/subpath.js could both be considered viable, depending on the configuration in play)

Sadly, the default JSPM path config is like this:
```javascript
System.config({
  "baseURL": "/",
  "transpiler": "traceur",
  "paths": {
    "*": "*.js",
    "github:*": "jspm_packages/github/*.js",
    "npm:*": "jspm_packages/npm/*.js"
  }
});
```

The `"*": "*.js"` part forces users to leave out extensions which causes incompatibility with SystemJS Builder (it looks like Builder doesn't recognise the path configuration and looks for "./file" instead of "./file.js") and possibly more problems when TypeScript is used.

---

I would love to see it work like this:
- `./file` is just `./file` and not `./file.js`
- `angular` is a module name and translates to whatever `angular` says its entry point is
- `angular/file` is a file in a module and translates to `path/to/angular/file` and not `path/to/angular/file.js`

Automatic extension insertion caused disgusting issues with RequireJS. It would be great not to have it here.

**Comment by guybedford** [comment]
jspm@0.16 beta is the version of jspm with these changes.

**Comment by guybedford** [comment]
(note it is a two-phase transition though, we're keep defaultJSExtensions on pending the full refactoring to the new configuration system)

**Comment by AlicanC** [comment]
That's great news, thanks.
