### ISSUE TITLE
Mocha and jspm dependencies

### ISSUE THREAD

**Issue by yamsellem** [jspm/jspm-cli#843]
By default, Mocha launches its tests with `node_modules` dependencies.
Is there way to use `jspm_packages` dependencies as well?

As an example, I wrote this setup.js file:
```
import { expect } from 'chai';
import $ from 'jquery';
global.expect = expect;
```

Launching `mocha --compilers js:babel/register --require ./test/setup.js` gives the error `Cannot find module 'jquery'` (chai is correctly imported, it was installed with `npm install --save-dev`).

The problem is that `jquery` has been installed with `jspm install jquery` and thus is only available in `jspm_packages`. In the client code, the `import from 'jquery'` works fine. But because mocha look for jquery in `node_modules`, it can't find it.

Is there a way to fix this?
Maybe using `System.config({..})
` somewhere will do the trick?

ps. [issue opened in mocha](https://github.com/mochajs/mocha/issues/1747)

**Comment by curran** [comment]
At some point I got unit tests with Mocha working with JSPM packages by using `System.import()` within the unit test code, instead of ES6 `import` statements (which are interpreted by Babel in your case, not JSPM).

Try replacing your jQuery import with this:

```javascript
System.import('jquery').then(function(m) {
  //tests go here
});
```

Alternative you could try to convert your test code to an ES5 bundle via JSPM first, then run mocha on the bundle (with source maps so you can debug your original code). I have never done this but it should work in theory.

I'm not sure what the best flow is, but it would definitely be useful to be able to write unit tests in ES6 with JSPM somehow.

**Comment by yang-wei** [comment]
```js
System.import('jquery').then(function(m) {
  //tests go here
});
```
@curran If we need to import more than 2 packages, then our code will become awkward right.

 I am also figuring this out. Maybe [node-require-directory](https://github.com/troygoode/node-require-directory) can do some favor?

**Comment by guybedford** [comment]
Yes the System.import style within the tests as above is the preferable way here.

**Comment by yamsellem** [comment]
@guybedford as statued by @yang-wei System.import in the test is not a viable solution if more than 2 packages are involved. 

May you please reconsider this issue and try to bring another solution? 
Thanks

**Comment by guybedford** [comment]
@yamsellem you can use `Promise.all` or chain the promises for multiple imports. Alternatively create a custom wrapper file. We use these sorts of patterns in all the project tests.

**Comment by yamsellem** [comment]
@guybedford the problem is that the import statement belongs to the application code, not to the test.
I used it in a test file only to demonstrate the problem easily.

So, right now, it seems impossible to test a jspm module that uses an external dependency downloaded in jspm_packages with mocha.

**Comment by guybedford** [comment]
@yamsellem this is entirely about code structure. If you have a file that looks like:

test.js
```javascript
System.import('x').then(function() {
  // ... application code
});
```

Then you have two options:

```javascript
// we return the promise so that it can be listened to
exports.bootstrap = function() {
  return System.import('x').then(function() {
    // ... application code
  });
}
```

OR

```javascript
import 'x';

// application code
// this is now a proper module and can be loaded in tests as well
```

**Comment by yamsellem** [comment]
@guybedford I'll take the time to test this and I come back to you.

With require.js I was able to change the dependencies folder for test purpose and I was looking for something as simple ;-).

**Comment by curran** [comment]
@yang-wei I agree that the *ideal* situation would be to have the ability to write the Mocha unit tests in ES6. This means that the test source files should be able to use ES6 `import` statements, and have them resolved through JSPM.

However, it's just not clear to me how this can be done. The two options seem to be:

 * somehow Mocha would need to run the source files using JSPM to resolve imports (similar to `mocha --compilers js:babel/register`, maybe something like `mocha --compilers js:jspm`), or
 * the ES6 tests could be first compiled/bundled to ES5, then run with Mocha (with source map support).

I have not been able to get any workflow going where unit tests are written in ES6.

**Comment by sroucheray** [comment]
I manage to make Mocha testing ES6 module to work with mocha command line.
You can check the setup in a small project here https://github.com/sroucheray/event-class/tree/master/test
There is two files :
* `es6-test-setup.js` is the setup of the tests. It is written in ES6, it must export the variables that will be tested
* `test.js` is the test file itself. It is written in NodeJS ES5 style, but assertions are made on the loaded setup file exports

`test.js` uses JSPM api to load `es6-test-setup.js

**Comment by ScreenDriver** [comment]
Any news about that @yamsellem ? I don't get my unit tests running. Both, my test code and my code to test are written in ES2015.

**Comment by ScreenDriver** [comment]
Finally I created a solution here curran/jspm-mocha-example#2 :tada: :sunglasses:

**Comment by guybedford** [comment]
Nice, I've added the project to https://github.com/jspm/jspm-cli/wiki/Third-Party-Resources.

**Comment by ScreenDriver** [comment]
Thank you. The only thing that driving me nuts is systemjs/systemjs#725
