### ISSUE TITLE
comparison to webpack

### ISSUE THREAD

**Issue by timaschew** [jspm/jspm-cli#844]
Except of these main features which don't exist in webpack (I think):

- github registry suppport
- package.json override interface
- flat dependency hierarchy
- avoid bundle step in dev mode (which seems not to scale with a big code base)

what is the reason to use jspm instead of webpack?

jspm installs the modules into it's own directory.
but this means the code between client and server is not the same (in addition some require paths
might be rewritten) and some tools
which rely on the __node_modules__ need extra configuration or just don't work.

So the __jspm_packages__ folder introduce more complexity for these cases. 

maybe put the answer on a FAQ page

**Comment by lookfirst** [comment]
jspm supports systemjs by writing out a config.js that systemjs can use. systemjs is an implementation of the es6 module loading spec. That is a crucial major difference.

My personal feeling is that following the es6 spec is a better way to future proof your code than to follow any of the historical module loading systems.

**Comment by timaschew** [comment]
yes, but it seems that the beta version supports es6: https://github.com/webpack/webpack/pull/861

**Comment by lookfirst** [comment]
Then why bother with it?

**Comment by lookfirst** [comment]
I should add... you're conflating two issues. jspm is primarily a package manager. 

Regardless of what webpack does, you still need (or at least should use) a package management tool to install dependencies. Because JS doesn't have a really defined way to resolve the `angular` portion of `import from 'angular'` into a specific file on disk, you still need something to do that translation. jspm does that by writing out a `config.js` file.

**Comment by yang-wei** [comment]
My team is building a prototype( PHP + Vue.js ), and this is how we want to write JS:

 1 es6
 2 no watch (watchify etc) during development ( non-js dev refused to do it :sob:  )
 3 testable js ( by writing js the es6 module way, js dev can test happily )

Many tools like webpack, browserify can't solve 2. Jspm fits perfectly =)

**Comment by guybedford** [comment]
In due course this may be nice to have on the website, but should go along with the new website when the project reaches that point. Not a priority for the moment.

**Comment by guybedford** [comment]
Note that since the jspm website is not currently enough on its own to provide information to users, help sharing information about jspm with others in blogs and posts is always very welcome.

**Comment by timaschew** [comment]
We're want to drop component and evaluating webpack and jspm. I just wanted to know if I missed something. 
What I discovered just now: webpack has a really fine-grained plugin system (not just loader plugins) for each life cycle, I didn't find such plugins for jspm or systemjs.
