### ISSUE TITLE
bundle-sfx exclude module/bundle arithmetic

### ISSUE THREAD

**Issue by nordisk** [jspm/jspm-cli#846]
Hi.

I would like to create a self-executing bundle and exclude a common dependency (jQuery in this case) when deploying it. I add jQuery manually through CDN rather than have it bundled with my main code. Any ideas hoot solve this?

Thanks.

**Comment by curran** [comment]
Hello,

Please take a look at [JSPM Shim Configuration](https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm#shim-configuration). This should let you accomplish what you describe, by adding a shim for jQuery.

Also there is [Creating a bundle with arithmetic](https://github.com/jspm/jspm-cli/wiki/Production-Workflows#creating-a-bundle-with-arithmetic), which may also work.

Best,
Curran

**Comment by nordisk** [comment]
@curran Thanks. Seems like shims are the way to go as the bundle arithmetic for subtracting is not working on ```bundle-sfx```.

**Comment by nordisk** [comment]
Okay,the solution was to use ```map```
```
{
   map: {
      "jquery": "@empty"
   }
}

Closing down the issue.

**Comment by nordisk** [comment]
Meh, the map didn't work – it excluded jQuery from the sfx-bundle, but no jQueryis not available inside the bundle :(
I am not sure how I can make the already globally available jQuery accessible in my bundle's scope. Any hints welcome …

**Comment by guybedford** [comment]
This use case is described at https://github.com/systemjs/builder#adapter-modules.

**Comment by nordisk** [comment]
Cheers for that. But do I have to still exclude it from the config map?

```js
System.config({
    "map": {
         …
        "jquery": "github:components/jquery@2.1.3" // Should this be @empty?
      });
```

Assuming I have still to add a shim for ```jquery```pointing to the adapter module definition ```module.exports = window.jQuery;```? Sorry, I am just missing an e2e example.

**Comment by nordisk** [comment]
Setting ```"jquery": "JavaScript/shims/jquery-shim",``` in config.map did the trick.
