### ISSUE TITLE
Infinite spinner on https://jspm.io

### ISSUE THREAD

**Issue by ffffranklin** [jspm/jspm-cli#856]
**Steps to reproduce**
 1. Navigate to https://jspm.io
 1. Observe the loading indicator displays but content never renders

**Actual Result**
See Infinite spinner
![screen shot 2015-06-18 at 4 47 55 pm](https://cloud.githubusercontent.com/assets/1546561/8244794/43abf774-15da-11e5-9ad8-c0a2d59beaa1.png)

**Expected Result**
Should see content
![screen shot 2013-07-25 at 23 38 00](https://cloud.githubusercontent.com/assets/1546561/8244809/7be02110-15da-11e5-90e8-20316aae418f.png)

**Comment by curran** [comment]
It looks like there is an error loading showdown.js:

(index):1 GET https://github.jspm.io/showdownjs/showdown.js net::ERR_CONNECTION_REFUSED
es6-module-loader@0.16.6.src.js:140 Potentially unhandled rejection [3] Error loading "showdown" at https://registry.jspm.io/showdown.js
: https://registry.jspm.io/showdown.js (WARNING: non-Error used)

**Comment by curran** [comment]
Looks like the site is back up and running fine again now.

**Comment by ffffranklin** [comment]
Good call @curran.  Still hanging for me though:
![screen shot 2015-06-18 at 5 26 50 pm](https://cloud.githubusercontent.com/assets/1546561/8245173/64aa3382-15df-11e5-8ee8-042946517e5c.png)

**OS:** OSX 10.10.3
**Browser: Chrome Version 43.0.2357.124** (64-bit)

**Comment by ffffranklin** [comment]
Moved this to the appropriate repo:
jspm/jspm.io#26

Closing
