### ISSUE TITLE
jspm to work with npm with just npm access unless registry specified otherwise

### ISSUE THREAD

**Issue by johnman** [jspm/jspm-cli#858]
Hi,

A feature request really.

Since we already need npm to install jspm can we have the default setup pull dependencies from npm instead of github? If you use jspm without specifying a registry e.g. npm: or you specify github: I understand that it could go to github (npm packages sometimes specify github dependencies themselves so in some cases it can't be avoided).

There are many ways of having your own npm server (sinopia, npm's enterprise server, artifactory etc) but not for github. If you wish to use jspm in someplaces with restricted network access this would make jspm a no go where as if you had npm as the base dependency these dependencies can at least be mirrored internally etc.

That way if github is down for any reason it might not have an impact on your developer workflow (unless you are intentionally pulling down from github which a lot of enterprises do not allow).

**Comment by guybedford** [comment]
Certainly you are free to entirely use npm or a custom git service via something like jspm-git.

GitHub is not a hardcoded default at all. The default setup pulls installs from the "jspm-suggested" option in the jspm registry - https://github.com/jspm/registry/blob/master/registry.json.

If you want to debate the location of a package on GitHub that is in the registry you are welcome to.

Alternatively you are also able to host a fork of the registry that uses npm version for everything instead within your company. This is one of the flexibilities of the registry in allowing a shared naming pool for common libraries.

**Comment by guybedford** [comment]
Just let me know if you have any further questions here.
