### ISSUE TITLE
Files with no import or export do not get passed though babel!

### ISSUE THREAD

**Issue by togakangaroo** [jspm/jspm-cli#859]
Try creating a file `foo.js` which uses es6

     (() => console.log("in an arrow function"))()

then either `import 'foo'` or `System.import('foo')`

you get an error due to the file not being interpreted as es6 and transpiled!

Now try adding any import or any export to the file. It works!

This is especially a hassle when doing tdd as I might create a spec file and code in it for quite a while importing anything before moving things into their own files. As it stands I have to remember to say `export const thisIsDumb = null`

**Comment by AdamBurgess** [comment]
For reference, https://github.com/systemjs/systemjs/blob/master/lib/esm.js#L5-L6 is the regex that discerns whether a file should be transpiled or not.

**Comment by guybedford** [comment]
Yes this is by design. Only ES6 module syntax is transpiled. ES6 modules being different to ES6 scripts.

**Comment by togakangaroo** [comment]
Is that good design though? What about my Tdd use case?




At the very least this should be clearly and boldly documented somewhere, I blew a lot of time on this trying to figure out why transpiling wasn't happening while setting up unit tests. When you are neck deep in karma and getting errors, that systemjs might treat some files differently from others is furthest from your mind.




If it really is desired behavior, I would recommend console logging a warning when you load something via system but choose not to transpile it (and of course providing a global override to toggle off this warning)



—

**Comment by guybedford** [comment]
Good point - it is a catch. I've added notes at https://github.com/jspm/jspm-cli/commit/5ee788fca7b34a7e40052a973851624f92058c86 and https://github.com/systemjs/systemjs/commit/5f777f245f7ffd58047b1681a1ec4edd62db84f2.

The plan is very much to separate the transpilation layer from the module layer, historically the module loader has a direct association of the module format with the language, which will take some time to move away from. It will happen though.
