### ISSUE TITLE
Lookup Error with Angular-Animate and `jspm install`

### ISSUE THREAD

**Issue by ThomasBurleson** [jspm/jspm-cli#862]
```terminal
jspm install angular-animate
```

```console
     Updating registry cache...
     Looking up github:angular/bower-angular-animate

warn Timed out on lookup for github:angular/bower-angular-animate, retrying (1).
warn Timed out on lookup for github:angular/bower-angular-animate, retrying (2).
warn Timed out on lookup for github:angular/bower-angular-animate, retrying (3).
warn Timed out on lookup for github:angular/bower-angular-animate
err  Error looking up github:angular/bower-angular-animate.
warn Installation changes not saved.
```

While `jspm install angular` works fine, this particular command fails... not sure why.

**Comment by guybedford** [comment]
I think GitHub are sporadic issues with this API. Not sure what to do here apart from using a completely different API, but that would involve a big perf loss unfortunately.

**Comment by ThomasBurleson** [comment]
The biggest issue is the fail/error with `jspm install angular-material`; this has dependencies on angular,angular-animate, angular-aria... and fails.
This issue has been occurring consistently with angular-animate for 2 days. Any thoughts ?

**Comment by guybedford** [comment]
This has been working absolutely fine for me, but the jspm server on the west coast has been also getting these lookup errors quite a bit recently unfortunately.

**Comment by ThomasBurleson** [comment]
Any work-arounds that you can recommend ?

**Comment by guybedford** [comment]
Is it really not working at all for you there? Are you able to run:

`git ls-remote https://username:password@github.com/angular/bower-angular-animate.git refs/tags/* refs/heads/*`

on the command line?

**Comment by ThomasBurleson** [comment]
@guybedford - yes that works for me.

**Comment by guybedford** [comment]
That's really strange. Did you enter the same credentials in the above? Perhaps try running `jspm cc` and see if that helps?

Does it really not ever successfully install angular animate at all?

**Comment by ThomasBurleson** [comment]
I upgraded jspm from version 0.15.3 to **0.15.7** and it works now:

*  jspm install angular-animate=github:angular/bower-angular-animate@master
*  jspm install angular-animate
*  jspm install angular-material 

All these work now.
