### ISSUE TITLE
install npm packages under a node_modules folder

### ISSUE THREAD

**Issue by omerts** [jspm/jspm-cli#863]
Hello,

First of all thanks for the great work. Our team are working with it, and we are really liking it. 
Is it possible for packages installed from the npm repo, to be installed under the standard node_modules folder, instead of jspm_packages/npm? 
We have some packages that are looking for that path.

**Comment by guybedford** [comment]
Thanks, I'm glad to hear you're liking the project.

Which specific use case would this be useful for?

**Comment by omerts** [comment]
We are using Karma & Chai for our unit tests, and running the global karma throws the following error (because it is looking for karma in node_modules):
```javascript
Cannot find local Karma!
  Please install karma by `npm install karma --save-dev`.
```

**Comment by guybedford** [comment]
Yes it isn't possible to install Karma via jspm.

**Comment by omerts** [comment]
So maybe if jspm would create a node_modules folder for its npm modules installation path it could work?

**Comment by guybedford** [comment]
It is best to use npm for this rather. jspm does modifications to npm packages so that they can be loaded by SystemJS, which aren't compatible with what Karma expects here.

**Comment by masaeedu** [comment]
This is also useful for TypeScript module resolution.
