### ISSUE TITLE
Add support for global installation | release us from depending on npm

### ISSUE THREAD

**Issue by omerts** [jspm/jspm-cli#864]
Hello,

Is it possible to add support for -g package installations? For us we feel like jspm is close to be the comprehensive solution, but we are still stuck with npm, and one of the reason is global installations.

Thank you,
Omer

**Comment by guybedford** [comment]
A feature like this will be possible in future, but will still take some time unfortunately.

See https://github.com/jspm/jspm-cli/wiki/NodeJS-Usage for more details on the NodeJS restrictions currently which are blocking this.

Closing as this will happen naturally as the architecture moves in these directions.
