### ISSUE TITLE
Browser Package manger vs Universal js package manager

### ISSUE THREAD

**Issue by giltig** [jspm/jspm-cli#870]
Hi,
I would like to know if jspm has a goal in its road map to be a universal single js package manager -
To the server and also to the browser - which means replace all together npm, bower etc.

**Comment by guybedford** [comment]
Yes that is very much the plan. How much of existing npm workflows we can support is yet to be determined. Although there is interesting progress, for example getting express server running through jspm & SystemJS resolution has worked out fine. We're currently limited by the restrictions mentioned in https://github.com/jspm/jspm-cli/wiki/NodeJS-Usage but this will improve in time.
