### ISSUE TITLE
Fails to load babel-core when defaultJSExtensions is false

### ISSUE THREAD

**Issue by silvenon** [jspm/jspm-cli#871]
When I try to load React, I get the following error in the console:

```
GET http://localhost:9000/jspm_packages/npm/babel-core@5.6.4/ 404 (Not Found)
```

This doesn't happen when I load, say, [plur](https://www.npmjs.com/package/plur). So maybe some kind of JSX issue?

jspm config in `package.json`:

```js
  "jspm": {
    "directories": {},
    "dependencies": {
      "react": "npm:react@^0.13.3"
    },
    "devDependencies": {
      "babel": "npm:babel-core@^5.6.4",
      "babel-runtime": "npm:babel-runtime@^5.6.4",
      "core-js": "npm:core-js@^0.9.17"
    }
  }
```

`index.html` file:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
  <script src="jspm_packages/system.js"></script>
  <script src="config.js"></script>
  <script>
    System.import('lib/app.js');
  </script>
</head>
<body>
</body>
</html>
```

System config in `config.js`:

```js
System.config({
  "baseURL": "/",
  "defaultJSExtensions": false,
  "transpiler": "babel",
  "babelOptions": {
    "optional": [
      "runtime"
    ]
  },
  "paths": {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  }
});
```

`lib/app.js` file:

```js
import React from 'react';
```

I tried this on a clean project. I'm using jspm@0.16.0-beta.3.

**Comment by silvenon** [comment]
After further investigating, this is definitely related to `defaultJSExtensions` being set to `false`. It works if I set it to `true`. Any ideas?

**Comment by guybedford** [comment]
Yes `defaultJSExtensions: false` is not supported in jspm@0.16. It will only be removed in jspm@0.17 unfortunately. Rather use package configuration to set `defaultExtension` which then overrides the defaultJSExtensions feature within that package to use custom extensions.

**Comment by silvenon** [comment]
Sorry, I was really reading the docs and release notes, but I got confused.

Thanks for being so helpful.
