### ISSUE TITLE
Add support native to bower

### ISSUE THREAD

**Issue by SandHilt** [jspm/jspm-cli#874]
Or add simply path to add bower search to jspm.

**Comment by curran** [comment]
This seems underspecified. What do you want to happen exactly?

**Comment by SandHilt** [comment]
<p>For example: <a href="https://github.com/twbs/bootstrap-sass">Bootstrap-SASS</a>.</p>
<p>I just got by typing: <pre>jspm install github:twbs/bootstrap</pre></p>
<p>This appear a little bad.</p>
<p>In bower i only type: </p>
<pre>bower install bootstrap-sass --save</pre>

**Comment by cecchi** [comment]
JSPM is relatively agnostic to what registry you install from (GitHub, NPM, or a custom one), so without specifying the registry it will do a lookup in JSPM's own registry, which is currently just a map to GitHub or NPM.

I do agree, however, that a Bower registry would be a great (built-in) addition to JSPM. It looks as though this has already been done in the form of a JSPM plugin: https://www.npmjs.com/package/jspm-bower-endpoint

**Comment by guybedford** [comment]
A PR to add `bootstrap-sass` to the jspm registry file at https://github.com/jspm/registry/blob/master/registry.json is welcome and encouraged.

**Comment by guybedford** [comment]
An alternative here is to support a Bower registry for jspm that is only aliasing. So `jspm install bower:bootstrap-sass` would be the same as writing `jspm install github:twbs/bootstrap-css`. Contributions along these lines would be welcome as a third-party registry, and I'd much prefer it to the custom bower registry as well which is an anti-pattern.
