### ISSUE TITLE
packages need to be within baseURL

### ISSUE THREAD

**Issue by silvenon** [jspm/jspm-cli#875]
[Here](https://github.com/silvenon/jspm-demo)'s a demo. It works in development, but it doesn't seem to work when I run `jspm bundle-sfx lib/app dist/app.js`. Here's the error:

```
err  Error: ENOENT, open '/Users/matija/Code/test/jspm_packages/npm/babel-core@5.6.5.js'
         at Error (native)
	Error loading file:///Users/matija/Code/test/jspm_packages/npm/babel-core@5.6.5.js
	Error loading file:///Users/matija/Code/test/jspm-demo/app/lib/app.jsx
```

However, it works when `jspm_packages` is in the `app` directory too, and if `jspm_packages` is in `app` and `config.js` is in the root. Maybe it has a problem with resolving `../` paths?

**Comment by guybedford** [comment]
Ensure you've configured your paths correctly in jspm.

The baseURL needs to match between client and server, and jspm_packages needs to be within the baseURL.

Also if you've moved jspm_packages from being at the root of the baseURL, then you need to inform jspm where it is relative to the baseURL in the package.json directories.packages property.

**Comment by silvenon** [comment]
Every move I made was using `jspm init -p`, like it's probably recommended? It's true that `jspm_packages` is not inside `baseURL`, but paths configured in `config.js` and `package.json` support that, because `jspm init` lets me put `jspm_packages` wherever I want.

Am I doing something wrong?

**Comment by guybedford** [comment]
Yes it would be worth warning the user when jspm_packages is not contained within the baseURL / handling this case better.

**Comment by antonmoiseev** [comment]
There is a common practice to put packages at the root dir of your project (`bower_components`, `node_modules`, etc.) and all application code to a sub-directory, say `app`. Is it applicable for JSPM? Can I put `jspm_packages` at the root dir of my project and `config.js` to the `app` sub-directory?

Actually I'm not sure whether it makes sense for JSPM. On the one hand `config.js` looks like a "deployable asset", i.e. the app needs it in the runtime. On the other hand, in development environment you can map your web server to get `config.js` from wherever you like (for example from the root dir of your project), but when you are preparing a production version of the app, the bundle doesn't require `config.js`, all information from `config.js` is already applied to the bundle. Is it correct?

**Comment by guybedford** [comment]
@antonmoiseev yes exactly you are correct here on the points. It can also be useful to set up a paths config to the app directory if it is within a deep subfolder:

```javascript
System.config({
  paths: {
    'app/*': 'path/to/app/*.js'
  }
});
```

(or without the `.js` if running the jspm beta release).

**Comment by guybedford** [comment]
Tracking warnings for this at https://github.com/jspm/jspm-cli/issues/925.
