### ISSUE TITLE
How can dl-loader use specific version?

### ISSUE THREAD

**Issue by neothemachine** [jspm/jspm-cli#878]
I'd like to try a newer systemjs version, however it seems there is only `--edge` which loads the current master. Can I somehow specify "use latest tag" or similar?

**Comment by guybedford** [comment]
The version of SystemJS is locked to the version of jspm. The way to user a newer SystemJS version is to upgrade your jspm version as they release together mostly. --edge can be useful when running the latest jspm and a SystemJS update hasn't been released.

**Comment by neothemachine** [comment]
Ok, I already used the latest jspm release (0.15.6) and with --edge it just broke, so I guess --edge is really experimental and the best way is just to wait for newer jspm versions in this case.

**Comment by guybedford** [comment]
I'd suggest using the jspm beta to get the latest loader versions.
