### ISSUE TITLE
Remote URL gets ignored for custom jspm registires?

### ISSUE THREAD

**Issue by subesokun** [jspm/jspm-cli#879]
Not sure why but it seems like the `remote` property gets ignored in case of custom jspm registries. I see this behavior with jspm@0.15.7

```json
{
  "defaultRegistry": "my-jspm",
  "jspm": {
    "handler": "jspm-registry",
    "remote": "https://registry.jspm.io"
  },
  "my-jspm": {
    "timeouts": {
      "lookup": 60,
      "build": 120
    },
    "handler": "jspm-registry",
    "remote": "http://...."
  }
}
```
(btw. this `timeouts` property I don't see in the original `jspm` registry config but it gets always automatically added if I remove it)

If I run then a jspm install command and take a look on the `~/.jspm/my-jspm-cache` repo I see following remote origin:
```
$ git remote show origin
* remote origin
  Fetch URL: https://github.com/jspm/registry.git
  Push  URL: https://github.com/jspm/registry.git
```
but this is not the remote I've defined in my configuration. Doing a `jspm cc` didn't help either.

**Comment by subesokun** [comment]
As info, my `remote` uses `ssh://` as protocol in case that makes any differences....

**Comment by guybedford** [comment]
Thanks. Remote is actually for switching to CDN sources, which is a feature we're not currently pushing. If there is a bug in updating it though, I'm happy to look into it, but I don't think it is critical right now?

**Comment by subesokun** [comment]
My situation is that I'm hosting a fork of the official jspm registry (located at ssh://user@internal/repo.git) which contains experimental package overrides and aliases for packages that are only available in the internal network. Currently projects which are using the alias are failing and also the experimental package overrides doesn't apply hence this issue is critical to me. Is there some other config property than `remote` which I should use instead?

**Comment by guybedford** [comment]
`jspm config registries.jspm.repo ssh://user@internal/repo.git` would be the location of this config.

**Comment by subesokun** [comment]
I see, thanks for the pointer! Just noticed now that this information is also available in the [wiki] (https://github.com/jspm/jspm-cli/wiki/Registries#creating-a-private-jspm-registry).
