### ISSUE TITLE
Cannot install lodash.debounce; TypeError: Arguments to path.resolve must be strings. 

### ISSUE THREAD

**Issue by nordisk** [jspm/jspm-cli#880]
I installed lodash.debounce manually with

```node_modules/.bin/jspm install npm:lodash.debounce```

Now when I want to install my package in another folder with ```node_modules/.bin/jspm install```
I get the following error:

```bash
node_modules/.bin/jspm install
     Looking up npm:lodash.debounce
     Updating registry cache...

err  TypeError: Arguments to path.resolve must be strings
         at Object.posix.resolve (path.js:439:13)
```

My versions is ```"jspm": "0.15.7"```

Not sure why this fails …

**Comment by nordisk** [comment]
Also fails with ```0.16.0-beta.3```

**Comment by nordisk** [comment]
Okay, the problem seems to be that I added a local path in my map config:

```"jquery": "JavaScript/shims/jquery-shim",``` Is there a more elegant way?

**Comment by guybedford** [comment]
Can you clarify the steps to reproduce? I'm unable to get this unfortunately.

I added a custom jquery map in my config file, then ran a fresh `jspm install`, but it worked fine. Should that have done it?

**Comment by nordisk** [comment]
In ```config.js```:

```
System.config({
  "map": {
       "jquery": "JavaScript/shims/jquery-shim" // <== ADDED manually
```


In ```package.json```:

```json
"jspm": {
    "directories": {
      "lib": "./JavaScript"
    },
    "dependencies": {
      "jquery": "github:components/jquery@^2.1.4",
     …
```

**Comment by nordisk** [comment]
The reason I do it is:
I want to keep track of my global available dependencies (here jquery) but exclude them from my sfx-bundle. In this scenario jQuery is added via a separate ```<script>``` before my bundle. But I still keep track of it in my dependencies.

**Comment by guybedford** [comment]
Yes this is not possible - jspm will create custom maps for all dependencies in the package.json and keep control of those regardless of your custom internal settings.
