### ISSUE TITLE
Ignored files in an NPM package still trigger nodelibs to be installed

### ISSUE THREAD

**Issue by blixt** [jspm/jspm-cli#883]
I'm installing an NPM package like this:

```bash
jspm install npm:lameworker -o '{"files":["index.js"]}'
```

[The lameworker package](https://github.com/blixt/js-lameworker) has additional files that contain references to `Buffer` etc. but they're effectively ignored by the `"files"` option. Still, this is the output I get from JSPM:

```bash
$ jspm install npm:lameworker -o '{"files":["index.js"]}'
     Looking up npm:lameworker
     Updating registry cache...
     Downloading npm:lameworker@0.1.1
     Looking up npm:workerproxy
ok   Installed npm:workerproxy@^0.3.3 (0.3.3)
     Looking up github:jspm/nodelibs-buffer
     Looking up github:jspm/nodelibs-process
ok   Installed github:jspm/nodelibs-buffer@^0.1.0 (0.1.0)
     Looking up npm:buffer
ok   Installed github:jspm/nodelibs-process@^0.1.0 (0.1.1)
     Looking up npm:process
ok   Installed npm:process@^0.10.0 (0.10.1)
ok   Installed npm:buffer@^3.0.1 (3.2.2)
     Looking up npm:base64-js
     Looking up npm:ieee754
     Looking up npm:is-array
ok   Installed npm:is-array@^1.0.1 (1.0.1)
ok   Installed npm:ieee754@^1.1.4 (1.1.6)
ok   Installed npm:base64-js@0.0.8 (0.0.8)
ok   Installed lameworker as npm:lameworker@^0.1.1 (0.1.1)
ok   Install tree has no forks.

ok   Install complete.
```

This implies to me that JSPM still scanned [the files in the `dist` directory](https://github.com/blixt/js-lameworker/tree/master/dist) and added all the Node.js compatibility packages, even though they are unnecessary to run [`index.js`](https://github.com/blixt/js-lameworker/blob/master/index.js).

The dependency `workerproxy` has no dependencies on Node.js objects and doesn't cause the installation of all the extraneous packages on its own:

```bash
$ jspm install npm:workerproxy
     Looking up npm:workerproxy
     Updating registry cache...
ok   Installed workerproxy as npm:workerproxy@^0.3.3 (0.3.3)
ok   Install tree has no forks.

ok   Install complete.
```

**Comment by guybedford** [comment]
Thanks, that would be this issue - https://github.com/jspm/jspm-cli/issues/345.
