### ISSUE TITLE
bundling fails when es6 specific features of babel are blacklisted

### ISSUE THREAD

**Issue by awalGarg** [jspm/jspm-cli#884]
I couldn't find this reported previously so I am opening a new issue.

Core issue: Disabling es6 syntax specific flags in babel like adding `"es6.arrowFunctions"` to babel blacklist in config.js, and using arrow functions causes bundling (`bundle-sfx` atleast) to fail, throwing an error "unexpected token" to stderr, aborting the process.

Expected: bundling should be allowed with es6 specific syntax in output as well.

Practical use-cases: I know bundling is intended to be for production where you ideally won't want any es6 specific syntax but there are two cases where this could be very useful:

1. Internal/personal apps where the overhead of runtime bundling is not acceptable. For instance, ES6 generators use es6 specific syntax and they are supported in both firefox and chrome since long for now. Same with `let` and `const`.

2. When development is happening in Firefox: Presently, when using runtime bundling, sourcemaps don't work with the Firefox debugger (because of the way scripts are evaled). The debugger just can't open the script url anymore. OTOH, Firefox has the widest ES6 support right now among all browsers with stuff like default parameters, short object notation and much much more. For projects of sufficient complexity, using the native syntax features can drastically decrease build time. We can watch files for changes and do `bundle-sfx ...` without minify with most of the es6 parts FF supports disabled, which can be a great workflow, IMO.

I hope that makes sense :)
Thanks! <3

**Comment by patrickmichalina** [comment]
Since moving to version 16.beta3 I am getting this error when trying to bundle-sfx:

```err  AssertionError: missing path
         at Module.require (module.js:363:3)
         at require (module.js:384:17)
         at /Users/Patrick/Desktop/jspm-test/node_modules/jspm/node_modules/systemjs-builder/lib/compile.js:157:16
         at Array.forEach (native)
         at wrapSFXOutputs (/Users/Patrick/Desktop/jspm-test/node_modules/jspm/node_modules/systemjs-builder/lib/compile.js:156:26)
         at /Users/Patrick/Desktop/jspm-test/node_modules/jspm/node_modules/systemjs-builder/lib/compile.js:136:14
         at lib$rsvp$$internal$$tryCatch (/Users/Patrick/Desktop/jspm-test/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:489:16)
         at lib$rsvp$$internal$$invokeCallback (/Users/Patrick/Desktop/jspm-test/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:501:17)
         at lib$rsvp$$internal$$publish (/Users/Patrick/Desktop/jspm-test/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:472:11)
         at lib$rsvp$asap$$flush (/Users/Patrick/Desktop/jspm-test/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:1290:9)
         at process._tickCallback (node.js:355:11)```

**Comment by guybedford** [comment]
I completely agree with your rationale. It could be a bug or something else - can you post the exact error and explain the inputs you used?

**Comment by awalGarg** [comment]
Thanks for replying @guybedford

I have set up a gist demonstrating the issue at https://gist.github.com/awalGarg/aecfe13b7188e397bf78

Hope that helps :)

**Comment by guybedford** [comment]
Ok perhaps I don't understand your rationale :)

You're using an arrow function in https://gist.github.com/awalGarg/aecfe13b7188e397bf78#file-index-js-L1. And then disabling the arrow functions feature. Surely that Babel throws an error in that case makes complete sense?

**Comment by awalGarg** [comment]
@guybedford the idea is that babel should skip transpiling arrow functions, like it does normally when blacklisting arrow functions through the command line:

```
awal@bookstro:~/Documents/myApps/jspmBugReport$ babel index.js -o index.es6 -b es6.arrowFunctions
awal@bookstro:~/Documents/myApps/jspmBugReport$ cat index.es6
'use strict';

Object.defineProperty(exports, '__esModule', {
  value: true
});
var foo = () => 'x';
exports.foo = foo;
console.log(foo());
awal@bookstro:~/Documents/myApps/jspmBugReport$ 
```

and systemjs bundler should bundle this code normally. Let me know if I need to be more clear :)

**Comment by guybedford** [comment]
Ok right I see, sorry I missed that initially. Then this is a Babel question not a jspm one, and I'd suggest looking into Babel's support of such a feature.

**Comment by awalGarg** [comment]
Umm, babel already does this. You can try running the command I showed, in your terminal and it will output the above code correctly. But it doesn't work when using babel with systemjs.

**Comment by guybedford** [comment]
@awalGarg right ok I see what you mean. So as part of the transpilation process the source code will be parsed by the build environment. That is you would need Node to support arrow functions here. Perhaps try running the build in iojs then?

We could alter the build to not need to parse the tree in the build environment certainly though too.

**Comment by awalGarg** [comment]
@guybedford exactly. the thing is iojs is also far behind in terms of es6 syntax features in comparison to spidermonkey. So it will be much more flexible to have the latter (alter the build) as an optional flag.

**Comment by guybedford** [comment]
Right, I completely agree but it is tricky to do this as the trace mode of the module loader relies on determining the dependencies by executing the System.register output in the host environment. So it's a complete reshuffle of the module loader tracing algorithm just to get this benefit, which is quite difficult to justify right now unfortunately.
