### ISSUE TITLE
Invalid authentication details.

### ISSUE THREAD

**Issue by trusktr** [jspm/jspm-cli#886]
Why do we need credentials for npm? Is it for people who have private npm? Can you just skip this if you detect it's using the public registry?

```
 ❯ jspm registry config npm                                                                [21:11:27]
npm registry [https://registry.npmjs.org]:
No authentication configured, configure credentials? [no]:
ok   Registry npm configured successfully.

 ❯ jspm install                                                                            [21:06:17]
     Looking up npm:army-knife
     Looking up npm:async
     Looking up npm:infamous
     Looking up npm:james-bond
     Looking up npm:jss
     Looking up npm:jss-nested
     Looking up npm:operative
     Looking up npm:string

warn Error on lookup for npm:jss-nested
     Invalid authentication details. Run jspm registry config npm to reconfigure.

err  Error looking up npm:jss-nested.

warn Installation changes not saved.
```

**Comment by trusktr** [comment]
Oh! I'm on Beta 3 by the way.

**Comment by trusktr** [comment]
So, after entering the correct credentials, it still doesn't work:

```
 ❯ jspm registry config npm                                                                [21:12:37]
npm registry [https://registry.npmjs.org]:
No authentication configured, configure credentials? [no]:yes
Configure token-based authentication? [no]:
Enter your npm username:trusktr
Enter your npm password:
Would you like to test these credentials? [yes]:yes
ok   npm authentication is working successfully.
ok   Registry npm configured successfully.

 ❯ jspm install                                                                            [21:13:23]
     Looking up npm:army-knife
     Looking up npm:async
     Looking up npm:infamous
     Looking up npm:james-bond
     Looking up npm:jss
     Looking up npm:jss-nested
     Looking up npm:operative
     Looking up npm:string

warn Error on lookup for npm:async
     Invalid authentication details. Run jspm registry config npm to reconfigure.

err  Error looking up npm:async.

warn Installation changes not saved.
```

**Comment by trusktr** [comment]
It works in jspm v0.15.7!

**Comment by trusktr** [comment]
I can't write a tool on top of jspm with this limitation in place. This problem blows the previous github rate limit problem out of the water. Some people don't even have npm accounts, then they'll face this issue and turn away, and probably not come back. Please please please make this an optional configuration.

I would love to see jspm get more adoption, and I'm very certain this authentication requirement is going to reduce the adoption rate of jspm.

I have to continue to use Webpack or Browserify in a couple of my projects. As much as I'd love to use Jspm, Jspm can't even be an option while something like this credential requirement is in place. The tools that I'm making need to work without required user configuration (especially credentials) out of the box.

**Comment by mrspeaker** [comment]
I don't now if this is related, but I'm having weird auth errors too after upgrading to beta 3:
```
warn Error on lookup for npm:babel-core
     Invalid authentication details. Run jspm registry config npm to reconfigure.

err  Error looking up npm:babel-core.

warn Error on lookup for npm:babel-runtime
     Invalid authentication details. Run jspm registry config npm to reconfigure.

warn Error on lookup for npm:core-js
     Invalid authentication details. Run jspm registry config npm to reconfigure.
```
I'm not sure it's exactly the same issue that @trusktr is reporting. Even if I authenticate with my npm credentials I get the same messages. Is there some way to work around this, or is there some documentation about it? Thanks!

**Comment by guybedford** [comment]
@mrspeaker @trusktr can you share your npmrc files with tokens removed please? It would help considerably in ensuring this can be supported.

Also @trusktr are you by any chance using symbol characters in your password? This may be an encoding issue.

**Comment by trusktr** [comment]
@guybedford Yeah, I'm using symbols. Here's my `~/.npmrc`:

```
//registry.npmjs.org/:_password=blah
//registry.npmjs.org/:username=trusktr
//registry.npmjs.org/:email=trusktr@gmail.com
//registry.npmjs.org/:always-auth=false
```

Can you please make this behavior not the default behavior? I would really like not to have to do this configuration in order to use JSPM. What's the reason? Is it similar to how the github releases API requires credentials? I would greatly appreciate it so much to not be forced to doing this!

**Comment by guybedford** [comment]
@trusktr thanks so much for updating here - I've just updated the beta release with a fix for this issue.

**Comment by trusktr** [comment]
@guybedford great!

> Can you please make this behavior not the default behavior?

What's your opinion on that request?

**Comment by guybedford** [comment]
@trusktr the idea is that users using private npm and npm enterprise don't have any extra configuration to add and can just start installing. I think we're catching all the issue cases around this workflow now ok.

**Comment by trusktr** [comment]
@guybedford 

> I think we're catching all the issue cases around this workflow now ok.

Not sure what you mean. As a user of a build tool, I simply don't want to log into any service if I don't have to (we don't have to log into npm to use npm, and jspm is a wrapper around that).

**Comment by guybedford** [comment]
@trusktr https://github.com/jspm/npm/issues/83 may help here.

**Comment by trusktr** [comment]
I replied there.
