### ISSUE TITLE
JSPM 0.15.7 has claret dependency of ^0.16.9 on systemjs

### ISSUE THREAD

**Issue by areel** [jspm/jspm-cli#890]
Hi

Using JSPM to handle workflow of producing a web app and an electron app from same codebase.
Trying to resolve an issue where my electron app crashes within systemjs code but my web app deploys without error.

I noticed that there were later releases of both es6moduleloader and systemjs available but I was on 0.16.9. Looking in JSPM dependeny list I see the use of caret.

I changed "^0.16.9" to "latest" and my workflow didn't break (which was great) but what was even better was that my electron app started without error too (another separate dependency was also updated and this was the underlying cause of the electron deploy issue).

So just raising this systemjs dependency definition for review. Appreciate the reasoning behind the claret usage, but it does mean that JSPM users are currently behind the es6ModuleLoader / SystemJS curve.
 
Regards

Aidan

**Comment by guybedford** [comment]
Use the jspm 0.16 beta to get the benefits of the latest SystemJS and Module Loader releases.
