### ISSUE TITLE
Question: Is it possible to update a module with a string value in the browser after the module has been loaded?

### ISSUE THREAD

**Issue by capaj** [jspm/jspm-cli#892]
let's say I have a module `a.js`
Which looks like:
```
module.exports = 1;
```
and I load it with 
```javascript
System.import('a');
```
let's say I have a string at runtime looking like this.
```
'module.exports = 2;'
```
Now what would I put instead of ????
```
System.import('a').then(function(a){
  console.log(a); //should print 1 
  ????//update the module with my string value
  System.import('a').then(function(a){
    console.log(a); //should print 2 
  });
});
```
So is it possible to change the code of the module after it has been loaded?

P.S.: This should have been opened in Systemjs probably, sorry about that, I didn't think it through before posting.

**Comment by guybedford** [comment]
Are you trying to achieve live editing here?

**Comment by capaj** [comment]
@guybedford ideally yes...even if it could work in some limited fashion, I would be super happy.

**Comment by guybedford** [comment]
@capaj have you looked at the work @geelen has been doing on hot-reloading here?

**Comment by capaj** [comment]
@guybedford no, I haven't. Will do ASAP.

**Comment by capaj** [comment]
@guybedford awesome, @geelen did exactly what I needed. This issue is irrelevant.
