### ISSUE TITLE
Two Sites, One Base URL

### ISSUE THREAD

**Issue by mikeobrien** [jspm/jspm-cli#894]
So I have one repo with two sites that both use jspm but there is only one `baseURL` setting:

```json
{
  ...
  "jspm": {
    "directories": {
      "baseURL": "src/wwwroot1"
    },
    ...
  },
  ...
}
```

How would you configure this for two sites?

**Comment by guybedford** [comment]
We need `baseURL` to be a reference point that is shared between client and server in order to handle bundling correctly. So I would suggest two package.json's, or having both sites' assets within the same public folder.

**Comment by mikeobrien** [comment]
Thanks for the suggestions but both those options are less than ideal. :( Idealy, the jspm options could be named, something along these lines:

```json
{
  "jspm": {
    "website1": {
      "directories": {
        "baseURL": "src/wwwroot1"
      }
      ...
    },
    "website2": {
      "directories": {
        "baseURL": "src/wwwroot2"
      }
      ...
    }
  }
}
```

Then you could run `jspm install website1 jquery`. Or if you if you ran `jspm install jquery` it would apply to all.

Any interest in supporting multiple projects? Seems like this scenario would not be that uncommon. And it would be a win to keep everything under one gulpfile.

**Comment by guybedford** [comment]
You can have multiple `package.json`s with one gulpfile - 

```
project
 - package.json - npm
 -- site1
    - package.json - jspm
 -- site2
    - package.json - jspm
 - gulpfile
```

**Comment by mikeobrien** [comment]
Oh sweet. I'll give that a shot, thx!
