### ISSUE TITLE
bable-node interactive behaving differently from being invoked to execute script directly

### ISSUE THREAD

**Issue by silkentrance** [jspm/jspm-cli#895]
Considering the following sources

singleton.es6

```
export default class foo {                               
    static _instance;                                    
                                                         
    static get INSTANCE() {                              
        if (this._instance == null) {                    
            this._instance = new foo();                  
        }                                                
        return this._instance;                           
    }                                                    
}
```

and singleton-use.es6

```
import foo from "./singleton";

console.log(foo.INSTANCE);
```

When running the interactive babel-node console and entering

```
import foo from "./singleton";

foo
```

it will produce an error, stating that foo is undefined, e.g.

```
ReferenceError: foo is not defined
    at [object Object]:3:1
    at _eval (/usr/lib/node_modules/babel/bin/_babel-node:54:13)
    at REPLServer.replEval [as eval] (/usr/lib/node_modules/babel/bin/_babel-node:137:14)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.emit (events.js:95:17)
    at Interface._onLine (readline.js:203:10)
    at Interface._line (readline.js:532:8)
    at Interface._ttyWrite (readline.js:761:14)
    at ReadStream.onkeypress (readline.js:100:10)
    at ReadStream.emit (events.js:98:17)
```

however, when I import `singleton-use` instead, e.g.

```
import "./singleton-use";
```

it will result in the following, more or less as expected, since the module seems to be evaluated twice...

```
{}
{}
```

Am I doing something terribly wrong here or is bable-node behaving entirely different in interactive mode?

Considering that when I `babel-node singleton-use` it will produce the proper result, namely

```
{}
```

**Comment by guybedford** [comment]
I really can't comment on the bahviour of babel-node here as it is a separate project and execution pipeline. It does sound like a strange result to be getting though.

**Comment by silkentrance** [comment]
@guybedford Sorry. Damn it. I am sure that I was on the babel/babel-node project page when I started creating the issue *grin*. No harm done.
