### ISSUE TITLE
Two empty lines at the end of config.js after running `jspm install`

### ISSUE THREAD

**Issue by antonmoiseev** [jspm/jspm-cli#897]
Every time you run `jspm install` (usually after checking out the latest version from a VCS) it adds two empty lines at the end of the `config.js` file. This is tiny minor issue, but still becomes annoying because you need to reset this file each time you make a commit.

**Comment by guybedford** [comment]
Sure thanks, it's great to address - I've added https://github.com/jspm/jspm-cli/commit/7fc0f4fb57bddc80939362626e342fd244374fdd.
