### ISSUE TITLE
jspm builder keeping contents in memory

### ISSUE THREAD

**Issue by jackfranklin** [jspm/jspm-cli#900]
Firstly, please excuse if this is the wrong repo - I think maybe the underlying problem belongs in SystemJS-Builder, but I'm not 100% sure. I'm also not sure if this is an actual; issue or a misunderstanding on my part, so sorry in advance if it is!

What I started hacking around on today was being able to listen to file changes and run the jspm build whenever a file changes. Rather than do this by watching the files and calling a process, I'd rather have one script that I execute that builds the project, watches for changes and then rebuilds.

However, I've come across a problem where somewhere along the chain, the contents of the files get stored in memory (it might be at the transpiler level with Babel), and once it has them in there it never makes it back to disk to reload the new contents. The below code replicates this:

```js
var jspm = require('jspm');
var fs = require('fs');
var builder = new jspm.Builder();

builder.loadConfig('./config.js');

var outputs = [];

fs.writeFileSync('app/foo.js', 'var x = 1');
build().then(function() {
  fs.writeFileSync('app/foo.js', 'console.log');
  build().then(function() {
    console.log('outputs match?', outputs[0].source === outputs[1].source);
  });
});

function build() {
  console.log('----------------');
  console.log(
    'contents of foo.js',
    fs.readFileSync('app/foo.js', {
      encoding: 'utf8'
    })
  );

  return builder.build('app/main.js', 'test.js', {
    minify: false,
    inject: true
  })
  .then(function(output) {
    console.log(output);
    outputs.push(output);
  });
}
```

It imports `app/main.js` as the entry point to the bundle (all this file does is import `foo.js`). I first set the contents of `foo.js` to `var x = 1`, and run the build. I then set the contents of `foo.js` to `console.log`, and rerun the build. I would expect the code outputted to differ, but in reality it's the same, and this line:

```js
console.log('outputs match?', outputs[0].source === outputs[1].source);
```

Logs `true`:

```
~/git/jspm-builder-test > node index.js
----------------
contents of foo.js var x = 1
{ source: 'System.registerDynamic("app/foo.js", [], false, function(__require, __exports, __module) {\n  var _retrieveGlobal = System.get("@@global-helpers").prepareGlobal(__module.id, null, null);\n  (function() {\n    var x = this["x"];\n    var x = 1;\n    this["x"] = x;\n  })();\n  return _retrieveGlobal();\n});\n\nSystem.register(\'app/main.js\', [\'app/foo.js\'], function (_export) {\n  \'use strict\';\n\n  var foo;\n  return {\n    setters: [function (_appFooJs) {\n      foo = _appFooJs[\'default\'];\n    }],\n    execute: function () {\n\n      console.log(\'hello world\');\n      foo();\n    }\n  };\n});\n',
  sourceMap: undefined,
  modules: [ 'app/foo.js', 'app/main.js' ] }
----------------
contents of foo.js console.log
{ source: 'System.registerDynamic("app/foo.js", [], false, function(__require, __exports, __module) {\n  var _retrieveGlobal = System.get("@@global-helpers").prepareGlobal(__module.id, null, null);\n  (function() {\n    var x = this["x"];\n    var x = 1;\n    this["x"] = x;\n  })();\n  return _retrieveGlobal();\n});\n\nSystem.register(\'app/main.js\', [\'app/foo.js\'], function (_export) {\n  \'use strict\';\n\n  var foo;\n  return {\n    setters: [function (_appFooJs) {\n      foo = _appFooJs[\'default\'];\n    }],\n    execute: function () {\n\n      console.log(\'hello world\');\n      foo();\n    }\n  };\n});\n',
  sourceMap: undefined,
  modules: [ 'app/foo.js', 'app/main.js' ] }
outputs match? true
~/git/jspm-builder-test >
```

Be really interested to hear your thoughts - and as always thanks for your help so far :)

**Comment by guybedford** [comment]
Builds are stateful - that is the builder object will cache the file system as it is currently.

This means that for a new build you need to instantiate a new builder instance.

The cache object can be shared between these instances though.

This workflow is very fresh (only landed in the last couple of weeks), so happy to help out and refine it as much as possible. It may be worth driving forward on it as well - two missing features currently are a tracer cache and caching the minified sources for an even bigger perf boost.

**Comment by jackfranklin** [comment]
@guybedford thanks for a quick reply!

> The cache object can be shared between these instances though.

This was the leap I was missing. I'll play around again later.

**Comment by guybedford** [comment]
@jackfranklin the other thing is to run `builder.reset()` to clear the builder state entirely but retain the cache object.

**Comment by jackfranklin** [comment]
Awesome, thank you. Fully aware this is a WIP/beta type API, will keep playing and noting down what I find. If I can help in anyway (maybe putting some docs together, tutorial, etc?) in the future let me know :+1:

**Comment by jackfranklin** [comment]
@guybedford issue now entirely gone thanks to your info above! Hit another problem but I'll open that on SystemJS-Builder :+1:
