### ISSUE TITLE
Best way to manage override

### ISSUE THREAD

**Issue by scoarescoare** [jspm/jspm-cli#901]
I'm trying to use a github repo that has no `main` key in its `package.json` file.

I know that I can submit an override to the registry, or that I can override the module's settings with the `-0` flag. 

I have been able to get past this by using the `packages` key in `System.config`, and from there I can specify the `main` key.

However, when anytime I use `jspm` cli, it resets my changes in the `config.js` file. What is my best option here?

**Comment by scoarescoare** [comment]
Also, when I replace the `main` key when using 
```javascript
System.config({
    packages:
        'foo-module': {main:'my-foo.js'}
    });
```

Systemjs will get a 404 because it now looks for 'my-foo.js.js'. Why is it appending the extra .js? [Shouldn't it work without it?](https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm#main-entry-point)

**Comment by guybedford** [comment]
Yes jspm will reformat the config, but it won't remove properties - your package configuration should still be in-tact fine, just moved to the end of the first config statement.

By default jspm uses the `defaultExtensions: true` option in SystemJS for everything so ".js" will always get added to all requests.

Packages can opt-out of this configuration option via:

```javascript
System.config({
  packages: {
    'foo-module': {
      main: 'my-foo.js',
      defaultExtension: false
    }
  }
});
```

Note this requires the latest SystemJS to be installed via running `jspm dl-loader` first.

**Comment by scoarescoare** [comment]
Ok, great. Thanks!
