### ISSUE TITLE
How to shim a Bootstrap Plugin installed via bower endpoint 

### ISSUE THREAD

**Issue by fspeckmaier** [jspm/jspm-cli#902]
I'm using the jspm / system.js setup with an additonal registered endpoint for bower. I need that endpoint due to the fact that installing Boostrap via npm or github does not provide the necessary less files for Bootstrap (anymore).

However, I want to use some of the Bootstrap Plugins (i.e. collapse). As they are simple jQuery Plugins with no AMD or CommonJS syntax they need jQuery globally. 

Obviously (?!), I cannot use the suggested shim

    {
      "main": "js/jquery.keyboard.js",
      "shim": {
           "js/jquery.keyboard": {
           "deps": ["jquery"]
      }
    },
    "dependencies": {
        "jquery": "*"
        }
    }

due to the fact that I am installing a whole framework with multiple folders and files not just a single plugin (so, as mentioned above, Bootstrap is installed via a bower endpoint for jspm). So how can I define jQuery globally for each of bootstrap plugins?!

To be honest, I am quite confused :/

**Comment by guybedford** [comment]
I think shims support wildcards actually here, exactly for this use case - 

```json
{
  "shim": {
    "js/*": {
      "deps": ["jquery"]
    }
  },
  "dependencies": {
    "jquery": "*"
  }
}
```

Let me know if you need further help here.
