### ISSUE TITLE
Running jspm install does not download a CSP compatible version

### ISSUE THREAD

**Issue by Raydiation** [jspm/jspm-cli#905]
Like described in https://github.com/systemjs/systemjs/blob/master/docs/production-workflows.md#csp-compatible-production

There's also no dist folder.

**Comment by guybedford** [comment]
Try using the latest jspm beta for this. The dist folder is in the SystemJS repo at https://github.com/systemjs/systemjs. Let me know if you need any further help with CSP workflows at all.

**Comment by Raydiation** [comment]
Thanks!
