### ISSUE TITLE
Ways to manually configure JSPM around complex resolution issues?

### ISSUE THREAD

**Issue by andremalkine** [jspm/jspm-cli#907]
I'm trying to use the newer [Famous/engine](https://github.com/famous/engine) in a jspm project. This may be related to known issues with the package and it's reliance on browserify, but I'm wondering if there's a way to configure around it.

The entry point for the package itself is `/index.js`, and it imports sub-modules via require statements like `require('./example');` where "example" is a sub-folder containing another `index.js` file. This pattern is used throughout the package. At the same time, many other internal require's will target `./example` in hopes of importing `./example.js`.

Having installed via jspm, I'm trying to mess with it's config so I can require it without all of the package's internal require's 404'ing because it's looking for `./example.js` instead of `./example/index.js`, but also not breaking when it's the other way around - or breaking resolution of the entry point.

Maybe I'm trying to hack something that shouldn't be hacked or really just need to wait for Famous/engine to grow out of it's browserify dependency...but in the meantime, any thoughts?

**Comment by micky2be** [comment]
+1

**Comment by guybedford** [comment]
@andremalkine this is an npm package, so you should install it from npm. Then jspm will apply all the Node resolution conventions and make them work on install. (`jspm install npm:famous` I assume?).

If you really must install from GitHub, you can enforce the npm conversions process via overriding the registry property which will apply the npm registry conversion operations - `jspm install github:Famous/engine -o "{registry:'npm'}"`. Just let me know if you need more tips here at all.

**Comment by andremalkine** [comment]
Thanks so much! I will let you know how it goes.
