### ISSUE TITLE
loading correct entry point when running from nodejs

### ISSUE THREAD

**Issue by omerts** [jspm/jspm-cli#909]
Hello,

I am trying to run react with server side rendering. My problem is with fetch requests, which use different modules for browser, and nodejs. I am trying to use a package called isomorphic-fetch, which in its config, has an entry point for browsers, and an entry point for nodejs. 
I can see that jspm did a good job splitting the two entry points, and the package.json, inside the isomorphic-fetch looks as follows:
```javascript
{
  "name": "isomorphic-fetch",
  "version": "2.1.0",
  "description": "Isomorphic WHATWG Fetch API, for Node & Browserify",
  "browser": "npm-client.js",
  "main": "server.js",...
```

My problem is that when I run my script with jspm run, it seems to load the browser's entry point, aka npm-client.js, and not server.js.

**Comment by guybedford** [comment]
Yes this is a limitation currently that will be fixed in future. See https://github.com/jspm/jspm-cli/wiki/NodeJS-Usage for more information.
