### ISSUE TITLE
ES6's Array.prototype.find not usable (shim not included from core-js)

### ISSUE THREAD

**Issue by neothemachine** [jspm/jspm-cli#910]
In Chrome my scripts fail because Chrome doesn't support Array.prototype.find yet. However, I thought that this should magically work anyway because jspm uses core-js which in turn [supports it](https://github.com/zloirock/core-js/tree/v0.9.18#ecmascript-6-array). In my jspm devDependencies I have `"core-js": "npm:core-js@^0.9.18"`. Do I have to do anything else to make it work?

**Comment by swirlycheetah** [comment]
You'll need to import the shim in your codebase somewhere for it to work, e.g. `import 'core-js/shim'`.

**Comment by neothemachine** [comment]
I see, but is it then still a devDependency or do I have to move it to the normal dependencies?

**Comment by swirlycheetah** [comment]
Good question, it works for me as a dev dependency (along with babel-runtime) but I'm transpiling via gulp before serving in the browser so not sure if that affects things, see https://github.com/plus-n-boots/plus-n-boots.github.io. Hopefully someone else will be able to highlight the correct workflow.

**Comment by neothemachine** [comment]
Seems to work, I use `jspm bundle` currently and also have babel and babel-runtime as dev dependency. I included the shims with `import 'core-js/es6'`. What's the actual difference between dev and normal dependency? What does it affect?

**Comment by swirlycheetah** [comment]
I'm not what difference the distinction makes to be honest, @guybedford can you shed some light on this please?

**Comment by guybedford** [comment]
This sounds exactly right. If it's code used in your production application then it's a dependency.

**Comment by guybedford** [comment]
(devDependencies are dependencies used only during development).

**Comment by neothemachine** [comment]
Hm, but if I import the es6 shim, then I surely need this in production as well? I understand why babel is a dev dependency, you transpile and build all into a single file, and after that you don't need babel anymore. But the shims are still needed, so shouldn't core-js be always a normal dependency? Maybe I'm confused about something, so please enlighten me :)

**Comment by guybedford** [comment]
Yes exactly, it would be a normal dependency then. I guess core-js should be a normal dependency as well, but it's more of an optional dependency I suppose, so should be added to dependencies as soon as you are actively using it! Definitely worth documenting that somewhere. I'm not sure where.
