### ISSUE TITLE
Bundling shared dependencies is including HTML files

### ISSUE THREAD

**Issue by jackfranklin** [jspm/jspm-cli#911]
We're generating a 3rd party dependencies JS file like so:

```
jspm bundle app/bootstrap - [app/**/*] client/app-vendor.js
```

And including this as a script tag. The problem here is that this ends up including any files we're pulling in via a SystemJS plugin, including our HTML templates, that we include like so:

```
import template from 'path/to/template.html!'
```

This means that changing one of these templates requires an entire regen of the vendor file, whereas it shouldn't, as those files shouldn't get included in the vendor file. How can we avoid including these?

Cheers,

Jack

**Comment by jackfranklin** [comment]
I think I've narrowed down the problem a bit (but a lot of this is stabbing in the dark)

I think the issue is here: https://github.com/systemjs/builder/blob/master/lib/arithmetic.js#L87

When calling that with `app/**/*`, it normalizes it to `app/**/*.js`, hence removing all the HTML files from it.

**Comment by m4r71n** [comment]
```import template from 'path/to/template.html!text'``` 
and 
```jspm bundle app/bootstrap - [app/**/*] - [**/*!text] client/app-vendor.js```
Does work for me on jspm 0.16.0-beta.3

**Comment by jackfranklin** [comment]
@m4r71n ahh that's a great idea. Giving that a try now. Thank you

**Comment by jackfranklin** [comment]
Worked! Thank you! @guybedford would it be any use if I had a crack at editing / adding to the documentation to note this behaviour?

**Comment by guybedford** [comment]
Glad to hear this is sorted and it's a useful feature. Good point - I'm hesitant to document the plugin bundling workflow though as it is somewhat experimental, and we'll have to see if this still works out with the upcoming configuration changes.
