### ISSUE TITLE
Isomorphic imports in sfx-bundles and System.import?

### ISSUE THREAD

**Issue by marcoms** [jspm/jspm-cli#913]
I've been prefixing most of my imports with "/"s to make it explicit that I'm referring to the base directory of the project, however when running `bundle-sfx`, jspm instead looks in my root directory of the filesystem. When importing dynamically using `System.import` there is no issue since it accesses the server root, but I would prefer to have this work in bundles as well.

Is there some way that I can specify the project root directory in config.js to get this desired behaviour?

**Comment by guybedford** [comment]
@marcoms it's advisable not to use absolute URLs for this reason, and use the baseURL-relative form of `app` etc.

**Note that unlike URLs, the two relative forms have different meanings - `./app` is parent-relative, while `app` is baseURL-relative.**

I do hope to better document some of these points soon.

Just let me know if you have any further questions.

**Comment by marcoms** [comment]
But will this same behaviour be applied in natively-supported ES6? Since there won't be a `baseURL` defined, will it automatically use the root dir?

**Comment by guybedford** [comment]
ES6 doesn't define any semantics like this. The loader specification doesn't define baseURL either - this is purely a SystemJS construct to enable bundling.

**Comment by guybedford** [comment]
(the loader spec defines URL normalization and exceptions for packages in a sites table that skip the URL normalization - eg `jquery` being a special reference)
