### ISSUE TITLE
Does link work with overrides?

### ISSUE THREAD

**Issue by myitcv** [jspm/jspm-cli#914]
I'm having a little trouble getting a `link`-ed packaged to work with overrides.

Essentially I've followed the steps documented [here](https://github.com/jspm/jspm-cli/blob/master/docs/linking.md) and [here](http://stackoverflow.com/questions/29148667/jspm-error-when-importing-a-jquery-plugin) for my jQuery plugin package (which happens to be [SpreadJS](http://wijmo.com/products/spreadjs/)):

```
cd my-local-package
jspm link jspm:my/repo@dev
cd my-jspm-app
jspm install --link jspm:my/repo@dev -o "{format: 'global'}"
```

but this format override appears to have no effect. 

Even setting a manual override in `package.json` for `my/repo@dev` does nothing...

Can anyone point me in the right direction?

Thanks

**Comment by myitcv** [comment]
I should add, I see this behaviour with both `0.15.7` and `0.16.0-beta.3`

**Comment by myitcv** [comment]
cc @jackfranklin who has kindly been helping with a few pointers here and there

**Comment by guybedford** [comment]
Yes they should work with overrides. But the linking workflows may not **update** the overrides very well I believe. Perhaps try manually delete the linked folder and re-install the linked package again. Linking workflows have some rough edges unfortunately.

**Comment by myitcv** [comment]
Thanks for getting back to me. 

Just so I'm clear, what directory are you referring to when you say:

> delete the linked folder

**Comment by guybedford** [comment]
I mean clearing it out from jspm_packages. Could also be done via an uninstall too.

**Comment by guybedford** [comment]
Did you have any luck here?
