### ISSUE TITLE
The config.js file generated by jspm init fails to transpile TypeScript in runtime

### ISSUE THREAD

**Issue by daniel-a-melo** [jspm/jspm-cli#915]
Using the `config.js` generated by jspm init does not allow TypeScript transpilation in runtime. 

Steps to reproduce:
1 -  `npm init`
2 - `npm install jspm@beta --save-dev`
3 - `jspm init` and choose TypeScript as transpiler

The generated `config.js` is:

```javascript
System.config({
  "baseURL": "./",
  "defaultJSExtensions": false,
  "transpiler": "typescript",
  "paths": {
    "github:*": "jspm_packages/github/*"
  }
});

System.config({
  "map": {
    "typescript": "github:mhegazy/typescript@v1.5-beta2"
  }
});
```
4 - Try to import TypeScript module without prior transpilation
```javascript
System.import('aModule.ts');
```
It tried to get the URL `http://host/jspm_packages/github/mhegazy/typescript@v1.5-beta2/` instead of the full path for the TypeScript transpiler thus resulting in 404. 

If I change the mapping of `typescript` on config.js to the full transpiler path then all works as expected.

Changed `config.js` 

```javascript
System.config({
  "map": {
    "typescript": "github:mhegazy/typescript@v1.5-beta2/bin/typescript.js"
  }
```

**Comment by Zoltu** [comment]
I suspect this is an issue with `"defaultJSExtensions": false`.  In particular, it really wants to fetch `http://host/jspm_packages/github/mhegazy/typescript@v1.5-beta2.js`, which does exist the above option has told SystemJS not to append `.js` extension by default.

If you update your map to point at the `.js` file by the same name as the directory, you will likely get a little further.  When I tried going down this path though I just ran into another issue.  It is still unclear to me what the path forward is for moving over to `"defaultJSExtensions": false`.

**Comment by guybedford** [comment]
Yes `defaultJSExtensions: false` is not supported in jspm 0.16 at all. This will only come in jspm 0.17.

**Comment by daniel-a-melo** [comment]
@guybedford Should we assume that on-the-fly transpilation of TypeScript won't be supported until jspm 0.17?

**Comment by Zoltu** [comment]
@daniel-a-melo Runtime TypeScript transpilation currently works.  It just takes a bit of fiddling to get it to work correctly.  See https://github.com/systemjs/systemjs/issues/569
