### ISSUE TITLE
Feature / Suggestion Request: SFX exclusion

### ISSUE THREAD

**Issue by LeDominik** [jspm/jspm-cli#917]
I can't get my head around a usecase we encounter over and over: We run JSPM, which is basically our super-productive development mode and use an as-small-as-possible SFX bundle for production. But now every SFX'ed bundle includes React over and over again (makes it unnecessary heavy), which could be easily cached in the browser.

So basically I'd need a SFX that just assumes that any ```import 'react' ``` can be safely ignored... really don't need any module-loaders / etc... in production mode.

**Comment by guybedford** [comment]
Yes SFX exclusions are on the roadmap. In the mean time it is possible to use an adapter module as documented in https://github.com/systemjs/builder#adapter-modules to achieve the same effect via globals.

**Comment by LeDominik** [comment]
Thanks! :+1:
