### ISSUE TITLE
How does the bundle command preprocess environment variables?

### ISSUE THREAD

**Issue by scoarescoare** [jspm/jspm-cli#918]
Looking at some react.js code I can see this:

```javascript
if ("production" !== process.env.NODE_ENV) { // <---------------
      if (format === undefined) {
        throw new Error('invariant requires an error message argument');
      }
    }
```

After I run the `jspm.bundle` command from within my build step, the code from above has been transformed to:

```javascript
if ("production" !== "production") { // <---------------
        if (format === undefined) {
          throw new Error('invariant requires an error message argument');
        }
      }
```

Is jspm actually doing this or is it offloading it to http://github.com/defunctzombie/node-process

**Comment by guybedford** [comment]
This is done in SystemJS builder for CommonJS code to enable production optimizations for Node code.

The last commit in https://github.com/systemjs/builder altered this to only work when minifying through the builder instead of unminified to allow the development workflows to work. Perhaps try installing systemjs builder from master. A release cycle will be following soon though.

**Comment by scoarescoare** [comment]
Perfect, thanks!

FYI the commit that he is referencing is systemjs/builder@63e02a8804ad6ca119bc818f245974d891e28619.

**Comment by tamird** [comment]
@guybedford is it expected that `jspm bundle-sfx app/app build/app.js` would produce "production" builds? I'm seeing this behaviour with systemjs/builder@0.15.22

**Comment by guybedford** [comment]
@tamird yes by default builds and bundles are for production. These defaults are set in SystemJS Builder itself.

**Comment by tamird** [comment]
@guybedford I don't understand. In https://github.com/jspm/jspm-cli/issues/1893#issuecomment-229312794 you said:
> (1) the CommonJS-only process.env.NODE_ENV == production optimization for CommonJS modules that only applies for minfication
In this case I'm not minifying, and yet jspm is applying the `process.env.NODE_ENV == production` optimization (inlining "production").

What am I missing?

**Comment by guybedford** [comment]
@tamird you're right - this used to apply on minification but now is linked to the production flag.

**Comment by tamird** [comment]
Yikes, can we change that?

**Comment by guybedford** [comment]
@tamird why is it a problem? Did you perhaps just want to add a `--dev` flag to your build? Also I would suggest running jspm 0.17 if you can!

**Comment by tamird** [comment]
It's a problem because react doesn't surface useful exceptions in production mode (it instead says something like "run this in debug mode to see what's up"). we want the bundle, but we also want useful debug information.

`--dev` is a 0.17 feature; we're not on 0.17 yet.

**Comment by guybedford** [comment]
@tamird we can add a dev flag to 0.16 quite easily if you're interested. It's at the options in https://github.com/jspm/jspm-cli/blob/0.17/cli.js#L207.

**Comment by tamird** [comment]
I guess you mean https://github.com/jspm/jspm-cli/blob/0.17/cli.js#L411 ?
Are you sure it's so easy? Seems like it would require plumbing from
jspm-cli to builder.

**Comment by guybedford** [comment]
Hehe yes that's the one!

I think it is that easy... that options object gets passed straight through
to the builder I believe.

**Comment by jonathanmarvens** [comment]
@guybedford I'm currently in a situation where I desperately need the __jspm__ bundler to not just inline `process.env.NODE_ENV` to `'production'` but actually reflect the current `process.env.NODE_ENV`. How do I make this happen? I'm using __jspm__ __v0.16.52__.

**Comment by stha** [comment]
+1 We are also using jspm v0.16.48 and need to toggle NODE_ENV for reactjs

**Comment by guybedford** [comment]
@jonathanmarvens @stha did you try disabling minification / running it as a separate process?

**Comment by jonathanmarvens** [comment]
@guybedford Yes, I did. Any way I can completely disable the inlining?

**Comment by guybedford** [comment]
Try running the build with `production: false` or `dev: true` build option.
