### ISSUE TITLE
How to deal with common transitive module dependencies?

### ISSUE THREAD

**Issue by antonmoiseev** [jspm/jspm-cli#919]
With given structure:
```sh
|- page1.js # imports lib.js
|- page2.js # imports lib.js as well
\- lib.js
```
Is there currently a way to prepare two bundles - for page 1 and page 2, with the content of lib.js moved to a separate bundle? I guess it's possible with the bundle arithmetic, but it becomes tedious and error prone as the project grows. I believe similar feature in WebPack is called code splitting. If it's not currently supported, is there an issue to track or something like a design doc or a roadmap?

**Comment by guybedford** [comment]
The commonality operator can be used here:

```
  jspm bundle "page1.js & page2.js common.js"
```

This will create a common.js bundle containing just the shared code between the two trees, which can then be used for subtractions against further bundling operations.

Let me know if that works out ok for you.

**Comment by antonmoiseev** [comment]
Thanks, works fine for me! There is a little typo - double quote should be placed right after page2.js:
```
jspm bundle "page1.js & page2.js" common.js
```
