### ISSUE TITLE
jspm install not resolving versions properly

### ISSUE THREAD

**Issue by togakangaroo** [jspm/jspm-cli#920]
```
> jspm install npm:react-dnd
     Looking up npm:react-dnd
     Updating registry cache...
     Looking up npm:disposables
     Looking up npm:dnd-core
     Looking up npm:invariant
     Looking up npm:lodash
     Looking up npm:react
     Downloading npm:lodash@3.10.0
     Looking up npm:envify
     Looking up github:jspm/nodelibs-process

err  No version match found for npm:react@~0.14.0
```

Huh... 0.14 isn't out yet. And I have latest which is `"react": "npm:react@0.13.3",`.

What's `react-dnd` doing? The version in npm currently is 1.1.3 and looking at [the relevant package.json I see](https://github.com/gaearon/react-dnd/blob/v1.1.3/package.json#L46)

```
  "peerDependencies": {
    "react": ">=0.13.0 <0.15.0"
  },
```

So where on earth does the `0.14.0` come from? In fact, [even looking at react-dnd latest](https://github.com/gaearon/react-dnd/blob/master/package.json#L46) It doesn't have anything that looks out of sorts.

Seems like probably an issue with jspm?

**Comment by guybedford** [comment]
We don't support arbitrary version ranges, so that the `>=0.13.0 <0.15.0` gets rewritten into `~0.14.0`.

You can fix this with an override:

```
  jspm install npm:react-dnd -o "{peerDependencies: { react: '0.13' }}"
```

**Comment by guybedford** [comment]
Just let me know if you have any further questions here at all.
