### ISSUE TITLE
Problem with bundling toastr

### ISSUE THREAD

**Issue by 32graham** [jspm/jspm-cli#921]
I have been successfully bundling lots of packages in our application but, the [toastr](https://github.com/CodeSeven/toastr) package is giving me problems. It works fine until I bundle using

    jspm bundle main --inject

Then the toastr object does not have all the properties that it should. I have [a small repository that demonstrates the problem on GitHub](https://github.com/32graham/jspm-toastr-bundle-problem).

**Comment by guybedford** [comment]
Thanks so much for posting. I've managed to track down the problem and have posted https://github.com/systemjs/builder/issues/228. Will follow the solution there.

**Comment by guybedford** [comment]
This is finally fixed in https://github.com/jspm/jspm-cli/issues/921. Release to follow soon.

**Comment by 32graham** [comment]
Awesome, thanks!
