### ISSUE TITLE
[idea] Automatic shared module splitting.

### ISSUE THREAD

**Issue by trusktr** [jspm/jspm-cli#923]
Webpack has a nice feature where you just specify entry points and when webpack bundles those entry points it can automatically split out shared dependencies and modules. Something like this would be nice for JSPM. Check it out: http://webpack.github.io/docs/code-splitting.html#running-multiple-entry-points

**Comment by trusktr** [comment]
I know that with a single bundle it's not an issue, and there's also bundle arithmetic to do this manually, but I'm working on a project that isn't aware of dependencies/modules ahead of time and will need to compile an unknown number of entry points when used, so it'd be super awesome if JSPM could do the arithmetic automatically.

**Comment by guybedford** [comment]
@trusktr the bundle arithmetic to do this is:

```
jspm bundle entrypointA & entrypointB & entrypointC common.js
jspm bundle entrypointA - common.js build-a.js
jspm bundle entrypointB - common.js build-a.js
jspm bundle entrypointC - common.js build-a.js
```

is this workflow working for you? Or is it unintuitive at all?

**Comment by trusktr** [comment]
The last three make sense, but the first is tricky. Is it combining them? It depends on whether you're speaking in English or in binary.

```slowassapplekeyboard
# it's binary
jspm bundle entrypointA & entrypointB & entrypointC common.js
jspm bundle entrypointA - common.js build-a.js
jspm bundle entrypointB - common.js build-b.js
jspm bundle entrypointC - common.js build-c.js
```

And it's also not clear what shell you're in, so beings will have to guess what to quote. Is it

```zsh
jspm bundle "entrypointA & entrypointB & entrypointC" common.js
jspm bundle "entrypointA - common.js" build-a.js
jspm bundle "entrypointB - common.js" build-b.js
jspm bundle "entrypointC - common.js" build-c.js
```

or

```
jspm bundle entrypointA "&" entrypointB "&" entrypointC common.js
jspm bundle entrypointA - common.js build-a.js
jspm bundle entrypointB - common.js build-b.js
jspm bundle entrypointC - common.js build-c.js
```

?

It's beautiful, but involves guess work. Sticking to a JavaScript API for this might make this faster since the syntax would be in the same tongue we're wanting management for.

**Comment by guybedford** [comment]
Yes I certainly wouldn't recommend sticking this all in the command line - rather set up a build task and run it that way. The JS API can also be used imperatively via `builder.intersectTrees(traceA, traceB)` etc etc.

**Comment by trusktr** [comment]
Ah, that's cool. It's just not documented yet I guess.
