### ISSUE TITLE
Removing optional dependency

### ISSUE THREAD

**Issue by emirotin** [jspm/jspm-cli#924]
I have a project that uses `github:seiyria/bootstrap-slider` library which _optionally_ depends on jQuery.

Here's a piece of my jspm config file (as created by `jspm install`):

```
System.config({
  "map": {
    "seiyria/bootstrap-slider": "github:seiyria/bootstrap-slider@4.10.1",
    "github:seiyria/bootstrap-slider@4.10.1": {
      "jquery": "github:components/jquery@2.1.4"
    },
  }
});
```

The jQuery lib is then downloaded, loaded in dev mode, and included in my resultant file built with sfx option.

I want to remove the dependency, especially from the built file. If I create an empty file called `fake-jquery.js` and change the config
```
    "github:seiyria/bootstrap-slider@4.10.1": {
      "jquery": "fake-jquery"
    },
```
it works just fine in dev mode (with es6 loader).

But on build I get jspm install error (I do fresh install on build):

```
> jspm "install"

     Looking up npm:ractive
     Updating registry cache...
     Looking up github:seiyria/bootstrap-slider
     Looking up github:thomaspark/bootswatch
     Looking up github:less/less.js
     Looking up github:es-shims/es6-shim
ok   Up to date - es6-shim as github:es-shims/es6-shim@^0.32.3 (0.32.3)
ok   Up to date - thomaspark/bootswatch as github:thomaspark/bootswatch@^3.3.5 (3.3.5)
ok   Up to date - less/less.js as github:less/less.js@^2.5.1 (2.5.1)
     Looking up github:jspm/nodelibs-process

err  TypeError: Arguments to path.resolve must be strings
         at Object.posix.resolve (path.js:439:13)
         at Package.getPath (/Users/admin/Work/Protorisk/HedgeIntro/node_modules/jspm/lib/config/package-name.js:82:15)
         at Object.exports.download (/Users/admin/Work/Protorisk/HedgeIntro/node_modules/jspm/lib/package.js:390:25)
         at /Users/admin/Work/Protorisk/HedgeIntro/node_modules/jspm/lib/install.js:314:18
         at lib$rsvp$$internal$$tryCatch (/Users/admin/Work/Protorisk/HedgeIntro/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:489:16)
         at lib$rsvp$$internal$$invokeCallback (/Users/admin/Work/Protorisk/HedgeIntro/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:501:17)
         at /Users/admin/Work/Protorisk/HedgeIntro/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:1095:13
         at lib$rsvp$asap$$flush (/Users/admin/Work/Protorisk/HedgeIntro/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:1290:9)
         at process._tickCallback (node.js:355:11)

warn Installation changes not saved.
```

Any idea what's wrong and how to fix it? I expect jQuery adds significant amount to my JS file's size.

**Comment by guybedford** [comment]
@emirotin you can do this via an override - 

```
  jspm install github:seiyria/bootstrap-slider -o "{map: {jquery:'@empty'}}"
```

**Comment by emirotin** [comment]
Thanks for the response. That added an overrides section to my package.json:

```
"overrides": {
      "github:seiyria/bootstrap-slider@4.10.4": {
        "map": {
          "jquery": "@empty"
        }
      }
    }
```

I'm afraid it has zero effect - I still see jQuery loaded in dev mode, as well as included in the bundle. It seems understandable especially in the first case - System.js doesn't read package.json, right?

I also tried '@empty' in the System config in the slider deps resolution — got the same effect I had for my own stub package - works as expected in dev, but fails on bundle build.

**Comment by guybedford** [comment]
So the override we are fighting with is the one at https://github.com/jspm/registry/blob/master/package-overrides/github/seiyria/bootstrap-slider%404.5.4.json.

That is, we need to override the shim as well:

```
jspm install github:seiyria/bootstrap-slider -o "{map: {jquery:'@empty'},shim:{}}"
```

**Comment by emirotin** [comment]
Oh I didn't realize there's a special repo with packages tweaks. So jspm rewrites modules sources when they're downloaded, now I understand.

Thanks for your help, now my bundle is twice as small :)
