### ISSUE TITLE
Should `config.js` be updated when updating some dependency and the dependency's dependencies already exist within `jspm_packages`?

### ISSUE THREAD

**Issue by timbur** [jspm/jspm-cli#927]
I updated some dependency's dependencies, and then ran `jspm update some-dependency`, and couldn't for the life of me figure out why the dependency's new dependencies weren't getting added to the top package's `config.js`.  I was about ready to give up when I decided to delete the `jspm_packages` directory and then ran `jspm install`, which fixed it and `config.js` is now correct.  Is this the correct behavior or is it a bug?

**Comment by timbur** [comment]
Or could it be because I had `jspm_packages/some-dependency` symlinked?

**Comment by guybedford** [comment]
How did you update the dependency's dependency?

**Comment by timbur** [comment]
I installed a couple of packages into the dependency using `jspm install some-dependency's-dependency=github:timbur/some-dependency's-dependency`.  And then when I ran `jspm update some-dependency` within the top level package, `some-dependency's-dependency` wasn't getting added to the top package's `config.js`.

**Comment by timbur** [comment]
Also, `some-dependency` is located at `~/Node/some-dependency` and then in the top package, I had it symlinked to `~/Node/top-package/jspm_packages/github/timbur/some-dependency` so that any changes made to `some-dependency` could be immediately reflected within the top package, of course.  Not sure how a symlink might affect `jspm`'s configuration algorithm but I can always do a quick test comparing with and without symlinks, if you want.

**Comment by guybedford** [comment]
@timbur yes the issue here is the symlinking process won't read the new dependencies. You'd need to relink and reinstall rather. This dependency-updating linking workflow is under development. If it feels bad that's because it is!

**Comment by timbur** [comment]
Is there a recommended (better) way to do this?  If not, no big deal.

**Comment by guybedford** [comment]
You could try editing the `.jspm.json` file inside the installed package before running the install / update. There's a number of things going on though, so it's difficult to tell if that would be enough.

**Comment by timbur** [comment]
I see.  Thanks for the info!
