### ISSUE TITLE
Typo in Wiki

### ISSUE THREAD

**Issue by pahen** [jspm/jspm-cli#928]
On page:
https://github.com/jspm/jspm-cli/wiki/Registries#travis-ci

The line:

travis encrypt 'JSPM_GITHUB_TOKEN=[JSPM_GITHUB_AUTH_TOKEN]'

should be:

travis encrypt 'JSPM_GITHUB_AUTH_TOKEN=[JSPM_GITHUB_AUTH_TOKEN]'

**Comment by guybedford** [comment]
Sure, thanks.
