### ISSUE TITLE
Error when running output from bundle-sfx

### ISSUE THREAD

**Issue by omerts** [jspm/jspm-cli#929]
Hello,

I ran bundle-sfx, which outputted an app.js file. Trying to load the app.js in the browser throws the following error:
```
Uncaught Node tls module not supported in browsers.
```

**Comment by guybedford** [comment]
You'll need to find which of your dependencies is loading `tls` and map it to `@empty` or add a `build: false` meta.

**Comment by omerts** [comment]
I have a conditional for loading the [broswer-]request package. Looks like the bundle is always trying to load both packages. I only need the bundle for the client side. Is there any way to configure @empty only for bundling?

**Comment by omerts** [comment]
just came across the arithmetic bundling, tried to use 
```
jspm bundle-sfx main - request app.js
```
but it returned an error:
```
SFX Bundles can only use addition and wildcard arithmetic
```

**Comment by guybedford** [comment]
You can configure the loader of the builder before running the build via something like:

```javascript
builder.config({
  map: {
    'x': '@empty'
  }
});
```

**Comment by omerts** [comment]
@guybedford  Thanks for the help, where would I put this config, if I am using jspm, and not directly the systemjs-builder?

**Comment by guybedford** [comment]
It's advisable to run a custom build through jspm like - 

```javascript
var Builder = require('jspm').Builder;

var builder = new Builder();
builder.config
builder.build
// etc
```

**Comment by omerts** [comment]
ok thank you
