### ISSUE TITLE
Automate loader configuration?

### ISSUE THREAD

**Issue by peteruithoven** [jspm/jspm-cli#930]
Currently it requires quite some configuration to setup the default file extension and default loaders per file extension. Could we integrate this into the JSPM cli somehow? 

For example, when installing the typescript loader plugin, I'd like to add the following configuration more easily. 
```
  'packages': {
    'src': {
      'defaultExtension': 'ts',
      'meta': {
        '*.ts': {
          'loader': 'ts'
        }
      }
    }
  }
```

Maybe we can do this when installing plugins? To add specific options this would probably require a separate install method for loader plugins? 
First rough idea: 
```
jspm install-loader css # install css loader plugin.
jspm install-loader css .css # install css loader plugin, add configuration to use css loader for .css files. 
jspm install-loader ts .ts --js-default # install ts loader plugin, add configuration to use ts loader for .ts files, make this the default javascript extention. 
```
In this idea adding configuration to use loader automatically requires extra flags, but maybe it's so normal to do this we can use a flag to explicitly disable this?

One issue with my configuration example is that `src` is project specific, is there a way around this? To apply this to all .ts files in a package, except the files in the jspm_packages folder?

As I'm still inexperienced with JSPM I'm assuming users want to set this configuration for their package only, and not their dependencies, not sure if that's considered "normal".

**Comment by guybedford** [comment]
You're one step ahead of me - this is exactly what is planned.

I was picturing extending the init process to populate a local application package configuration, and then adding an extra init prompt to ask if users would like to install plugins, and then having a pre-configured internal plugin list to suggest from.

Otherwise, users can install plugins via their own manual install means too.

The pre-configured plugin list would be able to do automatic extension-based configs though like your examples.

**Comment by peteruithoven** [comment]
Nice! 
To be honest, I would keep the number of steps in `jspm init` limited, it's something you do over and over when doing small experiments (It can become quite frustrating).

How many steps would this add? Would it be something like the following? 
```
Would you like to install loader plugins? [yes]
Enter plugins to install [css, json]: 
```

I would like to suggest to also add a separate loader install option, so users can do this after their init.

**Comment by peteruithoven** [comment]
Also relevant: https://github.com/jspm/jspm-cli/issues/855

**Comment by guybedford** [comment]
Yes, I would even make the default [no] in the above as well.

**Comment by guybedford** [comment]
Closing to track this under the #855 issue.
