### ISSUE TITLE
Allow defining an target file for depCache

### ISSUE THREAD

**Issue by subesokun** [jspm/jspm-cli#934]
Would it be possible to write out the generated depCache map into a separate file instead of the `config.js`? Like `jspm depcache app/index -o depcache.js`. This depcache file I'd like to exclude from the VCS but not the `config.js`.

**Comment by guybedford** [comment]
For custom features like this, rather use a custom trace implementation - 

```javascript
var Builder = require('jspm').Builder;

var builder = new Builder();
builder.trace('app/index').then(function(trace) {
});
```

Would that work for you here?

**Comment by subesokun** [comment]
Great, yes that will work for me. Thanks :)
