### ISSUE TITLE
Any .babelrc support?

### ISSUE THREAD

**Issue by mmoss** [jspm/jspm-cli#935]
I may be missing something, but I was hoping to aggregate all babel configuration into a **.babelrc** file, as recommended by the [babel maintainers](https://github.com/babel-plugins/babel-plugin-react-constant-elements#via-babelrc-recommended). I previously used duplicate configurations, manually setting `babelOptions` in my **config.js**

**Comment by guybedford** [comment]
Thanks. We could certainly consider populating the config.js babelOptions from the .babelrc in future, but trying to integrate features very sparingly for the current development phase.

**Comment by laurentgoudet** [comment]
Typescript as tsconfig.json as well. Being able to copy these configs on jspm install would definitely be a plus
