### ISSUE TITLE
When packaging JCrop, the CSS reference to the assets are incorrect

### ISSUE THREAD

**Issue by jamesgorrie** [jspm/jspm-cli#937]
When we package JCrop into our `build.js`, the reference to the [JCrop.gif](https://github.com/tapmodo/Jcrop/blob/master/css/jquery.Jcrop.css#L20) isn't respecting the [baseURL](https://github.com/guardian/grid/blob/master/kahuna/public/config.js#L2) set in our [config](https://github.com/guardian/grid/blob/master/kahuna/public/config.js#L2). 

It's reference is `jspm_packages/github/tapmodo/Jcrop@0.9.12/css/Jcrop.gif`.

I'm trying to figure out where the bug is for this, potentially in the [css plugin](https://github.com/systemjs/plugin-css)?

__version: ~0.16.0-beta__.

**Comment by guybedford** [comment]
Have you tried setting the `System.rootURL` value here?

The CSS file is normalized relative to the build baseURL. But it doesn't know the URL that the output page will be based on, so this is where rootURL comes in to know that. Perhaps we should simplify this though to simply "pathPrefix" or something like that.

**Comment by guybedford** [comment]
Created https://github.com/systemjs/plugin-css/issues/52. Will track progress there.
