### ISSUE TITLE
Local jspm dependencies

### ISSUE THREAD

**Issue by laurentgoudet** [jspm/jspm-cli#938]
In a large company, if the dependencies are not versioned per components but shared (e.g. jQuery, angular..), it quickly becomes impossible to upgrade any shared dependency due to the technical (100+ components to update at once) and political boundaries (different teams).

A good approach I see is to define one package.json per component that defines its entry point & dependencies using semver, and makes jspm handle the rest. However having 1 repo git per components is too much friction, and jspm doesn't seem to handle local dependencies like bower does (badly).

No one seems to have built a local jspm registry plugin yet. Is there a better way to handle that problem or should I do it?

**Comment by laurentgoudet** [comment]
Hmm in fact it could probably work with a single package.json and, as a convention, suffix the dependencies names with some sort of semver version when installing & importing the dependencies, i.e. jspm install angular@1.3=angular@1.3 -> "import angular from 'angular@1.3" / "import angular from 'angular@1.4'". Much easier to maintain than having tons of package.json.

There's probably a way to achieve the same using SystemJS maps even though I even figured that out just yet. However it makes it less obvious what exact dependencies a module is using.

**Comment by guybedford** [comment]
One way around the component per repo problem is having component libraries in repos, within each library managed by a team, where the versions can be updated across the whole repo easily anyway.

Local installs will be improving in future, but even amongst teams it doesn't solve the code sharing problem (unless you're using a network drive, does anyone do that?). So how do you manage the shared code otherwise without linking it to a registry? I'd be weary of a custom versioning scheme / map config, would be best to work with jspm here if you can.

**Comment by Munter** [comment]
I just ran into this. For reasons I won't stand behind or argue for we have locally modified and checked in copies of third party libraries. I need to be able to configure that jquery or underscore should authoritatively be handled by these local files.

I've created an example repository with a SystemJS setup that behaves as I expect it to: https://github.com/Munter/jspm-local-dependency-bug/blob/master/app/config.js#L32

However, when I run `jspm install` it throws with
```
$ jspm install
     Looking up npm:babel-core
     Looking up npm:babel-runtime
     Looking up npm:core-js
     Looking up npm:backbone
     Updating registry cache...
ok   Up to date - babel as npm:babel-core@^5.6.4 (5.7.2)

err  TypeError: Arguments to path.resolve must be strings
         at Object.exports.resolve (path.js:313:15)
         at Package.getPath (/home/munter/.nvm/v0.10.29/lib/node_modules/jspm/lib/config/package-name.js:82:15)
         at Object.exports.download (/home/munter/.nvm/v0.10.29/lib/node_modules/jspm/lib/package.js:426:25)
         at Promise.resolve.then.then.resolution.fresh (/home/munter/.nvm/v0.10.29/lib/node_modules/jspm/lib/install.js:313:18)
         at lib$rsvp$$internal$$tryCatch (/home/munter/.nvm/v0.10.29/lib/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:489:16)
         at lib$rsvp$$internal$$invokeCallback (/home/munter/.nvm/v0.10.29/lib/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:501:17)
         at /home/munter/.nvm/v0.10.29/lib/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:1095:13
         at Object.lib$rsvp$asap$$flush [as _onImmediate] (/home/munter/.nvm/v0.10.29/lib/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:1290:9)
         at processImmediate [as _immediateCallback] (timers.js:336:15)

warn Installation changes not saved.
``` 

I tracked it down to https://github.com/jspm/jspm-cli/blob/master/lib/package.js#L383 where it seems my locally handled dependency is now being downloaded, which fails because the local annotation doesn't have a registry.

So I tried to hack it:
```
exports.download = function(pkg, options, installDeps) {
  if (pkg.name.indexOf(':') === -1) {
    // Local package
    return Promise.resolve('local');
  }

  // ...
}
```

The above works-ish. jspm no longer throws when installing, the config is kept as I expect it to. The log is not so informative, but I bet someone who actually knows the code base would know how to fix that.

Would something like this be an approach? If you recognise a dependency to be configured as local, skip it and assume things work

**Comment by guybedford** [comment]
@Munter that's certainly a valid use case, tracking this at https://github.com/jspm/jspm-cli/issues/943.

**Comment by laurentgoudet** [comment]
> it doesn't solve the code sharing problem (unless you're using a network drive, does anyone do that?)

We do have shared libraries of components in dedicated repos, and they work fine with jspm. My specific use case here is more components of a single large web site. Ideally one wants not to run 10 versions of jQuery in parallel on the same page, but by experience having a clean/decoupled migration path from a version to another is essential.

Even with local installs, having to create a package manifest for each component feels like too much overhead (plus probably having copies of jspm_packages everywhere in the tree when running jspm install for a specific package). We were partially doing that with bower, but most devs were skipping the manifest altogether and dumping scripts on the pages. Ideally, creating a new module within an existing project should be limited to creating an ES6 module, itself declaring its dependencies using ES6 imports.

**Comment by guybedford** [comment]
@laurentgoudet just to make sure I'm understanding correctly, would the following model simplified scenario cover the issue you're describing - you want an upgrade path for jQuery in an app that depends on say 50 components, each of which is installed as a separate package in the app and has a dependency on jQuery?

And then locally, you find it unnecessary to be installing all the same dependencies for each component each time you create a new component with some unit tests as its own package?

**Comment by laurentgoudet** [comment]
Yep that would describe it.

We currently have many bower_components folders throughout the tree, one for each "app", and few shared libraries with their own bower_components folders, and keeping them in sync is tricky as files are copied around by bower. Plus people work around bower because they find it "too complex" and we end up with lots of standalone scripts in the tree that makes upgrading - say jQuery - nearly impossible.

We could probably follow the same scheme with jspm, once local installs are supported, i.e. 1 jspm manifest + 1 jspm_packages folder per "app" and per "library", however I'm still wary that people would find it too complex (and not sure how the many jspm_config would be handled).

One approach could be to have a key in the manifest that tells jspm not to install the deps (only update the manifest) as the package is not an entry point per se. The unit tests would then run using the global jspm & System configs, loading each package & its dependencies.

**Comment by guybedford** [comment]
Yeah the linking workflow would be ideal here. Another thing which may simplify this is having `jquery` as a peerDependency (https://github.com/jspm/jspm-cli/issues/490), that feature would provide a bower-style version resolution prompt, where you need to then always ensure you're selecting one version of jQuery to use in the app.

**Comment by laurentgoudet** [comment]
@guybedford I'm willing to give a try at implementing something for this workflow as it would add a lot of value to the JSPM deployment/workflow in my company.

The use case here - which I believe is pretty common - is a large scale non-SPA website for which many JS modules have been developed to add dynamic functionalities to server-side generated pages. The entire site - including all the JS modules - is stored in a single monolithic repo for simplicity of dev & deployment. Unfortunately none of the current package managers (`bower`, `npm`) provides a nice user experience for this use case, and considering `jspm` ability to auto-configure the loader I believe it would add a lot of value.

The goals are to:
- track, through individual `package.json` application manifests, the dependencies (and their version ranges) of each app
- list all the apps in a central manifest and install their dependencies in a single `jspm_packages` folders, while optimizing the number of dependencies by resolving version ranges (and locking the versions in `jspm-config.js`)
- bundle these apps and their dependencies for delivery (using the [SystemJS builder](https://github.com/systemjs/builder)) while optimizing, manually or through an external tool, for cache duration / file size...

The ideal workflow would be:

1. Create a new `myApp` folder for a new app and run `jspm init --local` to initialize a `package.json` manifest with `jspm: true` and an empty `dependencies` map, while skipping all the other steps (i.e., no need to create a `config.js` SystemJS config or to create and download `jspm_packages` as they won't be used anyway).
2. Add dependencies to the local app by running `jspm install <something> --local`: dependencies are added to the manifest (or updated) but nothing gets downloaded (not sure what `inject` is meant to do btw). Loader config is not created or updated.
3. Add the local app to the main configuration manifest by running `jspm install local:./public/modules/myApp`. Ideally the name would be resolved based on `jspm`'s `baseURL` (i.e., `modules/myApp` here if the `baseUrl` is `./public`). `jspm` then takes care of downloading the app dependencies & configuring SystemJS (locking the dependencies version in `config.js`). The local app files themselves are not copied, and the app can be loaded through the usual `System.import('modules/myApp');`.

I've tried my hand at creating a simplistic `local` registry using the [Registry API](https://github.com/jspm/jspm-cli/wiki/Registry-API) but the user experience is quite limited:
- Hundreds of `jspm_packages` folders & `config.js` need to be created if/when using `jspm` in each local application. This is slow & confusing for the devs even though they could be `.gitignore`'d. However, every use of `jspm` in a local app would mean going through the configuration steps (e.g., `Configuration file config.js doesn't exist, create it? [yes]:`...). Manifests could be created manually but this is not ideal (my current solution)
- Through the `local` registry, `jspm install` these apps: a version has to be specified, which is confusing even if `latest` works. The app names have to be manually specified as the `local` registry plugin doesn't have access to the `baseURL` (and reading it from the `package.json` would be hacky), e.g. `jspm install module/myApp=local:./public/module/myApp`.
- The files are duplicated in `jspm_packages` which is error-prone, and `jspm install` needs to be ran every time the app is modified (`jspm link` won't work for us as each dev `rsync` its environment with an AWS instance as the stack is too complex to run locally).

I could finish off and publish the `local` registry, and the registry API may be extended to pass the `baseUrl`. However I feel like the end result won't be ideal either as this `local` workflow is more about skipping steps than trying to copy a remote one.

How would you feel with me sending PR's to implement that workflow? I am probably missing things as the only limitation I am aware of is `jspm` transforming the package manifests on `install`, however I feel that limiting this `local` workflow to `jspm: true` packages would be perfectly reasonable here as the objective is not to publish them.

**Comment by guybedford** [comment]
It sounds like there are quite a few things going on here. To try and summarize some of the things you're looking to be able to do:

* For each individual component's project folder, you want the ability to not install any `jspm_packages` at all in its individual folder? Is there a reason you aren't running per-app unit tests? I thought a `test` folder would have been natural to have along with each one, mandating the need for individual `jspm_packages` to test each component in isolation? If you're not having the `jspm_packages` at all, what is the benefit of each component having its own dependency package.json over a shared package.json? Would you consider the use of a symlinked `jspm_packages` tot he main app here instead perhaps?
* You want to be able to easily install individual components into the main app from local folders. Would the ability to install a folder like `jspm install ../some/folder` be beneficial here?

**Comment by laurentgoudet** [comment]
> For each individual component's project folder, you want the ability to not install any jspm_packages at all in its individual folder?

Essentially yet, we currently have one `bower_components` per app and it feels overkill as a lot of them are duplicated & it takes a long time for `bower` to install them all. It is also harder to manage (e.g., custom script to bootstrap them).

> Is there a reason you aren't running per-app unit tests? 

We are running per-app unit tests but it too does not feel optimal as the `karma.conf.js` configs are duplicated & modified and it becomes hard to extend the setup if needed (e.g., new plugin to enforce code coverage in CI). I'd rather have a single config for all of them, and one way I can think of is to dynamically configure `karma-jspm` (`loadFiles` and `serveFiles`) through `Grunt` or `gulp`

>  If you're not having the jspm_packages at all, what is the benefit of each component having its own dependency package.json over a shared package.json?

The benefit is that apps - like team or people - tend to come and go and it's easier to clean up dead code by `jspm uninstall ../some/folder` than trying to identified which deps are not needed anymore. It is also much easier to incrementally upgrade a specific dep (assuming it's not a `global`).

> Would you consider the use of a symlinked jspm_packages tot he main app here instead perhaps?

Hmm not sure how it would work as `jspm install` in the local app would remove all the deps not defined in the local `package.json`.

> You want to be able to easily install individual components into the main app from local folders. Would the ability to install a folder like jspm install ../some/folder be beneficial here?

Yes definitely. However if the files are copied other instead of pointed to in the loader conf my previous comment still stands: "The files are duplicated in `jspm_packages` which is error-prone, and `jspm install` needs to be ran every time the app is modified (`jspm link` won't work for us as each dev rsync its environment with an AWS instance as the stack is too complex to run locally)."

I feel like I'm maybe over-engineering the solution here and may be better using one global config for all of them, especially considering that dead deps won't incur any overhead in prod thanks to tracing. However that lack of an upgrade path for them still bugs me.

**Comment by guybedford** [comment]
To clarify the symlinking workflow - `jspm_packages` is not unique to each app, and only necessary to install each time if you want to make local modifications etc. We could enable a _symlinking_ mode where jspm_packages would be shared between all apps on the system and symlinked, and uninstall would not remove things from jspm_packages.

Can you explain why exactly `jspm link` won't work for you if you are rsyncing the environments? Is this because symlinks won't rsync in the same way? It sounds like a workflow decision to me that shouldn't have to guide these approaches.
