### ISSUE TITLE
Error "no such file" on "import express from 'express'"

### ISSUE THREAD

**Issue by nvivo** [jspm/jspm-cli#940]
I'm not sure what I'm doing wrong here or if this is not supported yet. I'm trying to use System.js with node and express.

server.js:
```js
var System = require('systemjs');
require('./config');
System.import('app')
  .catch(function(err) {
    console.log(err);
  });
```

app.js: 
```js
import express from 'express';
```

When I run `node server.js`, I get:
```
[Error: ENOENT: no such file or directory, open '/tmp/test/jspm_packages/npm/express@4.13.1/lib/express']
```

Even though the file is at that path.

Here is a script to reproduce:

```
mkdir test
cd test
echo "System.config({baseURL: './'})" > config.js
cat > server.js << EOL
var System = require('systemjs');
require('./config');
System.import('app')
  .catch(function(err) {
    console.log(err);
  });
EOL

echo "import express from 'express';" > app.js

npm install systemjs
jspm install npm:express@4
```

Then just run `node server.js`.

**Comment by omerts** [comment]
See if this helps:
https://github.com/jspm/npm/issues/26

**Comment by nvivo** [comment]
Thanks @omerts. After reading the comments carefully, I got to https://github.com/jspm/jspm-cli/wiki/NodeJS-Usage - what I was missing was this:

> jspm is primarily a browser package manager (...) It is advisable not to use jspm for arbitrary server applications currently

I didn't see that warning before. So, I'll forget using system.js for server side for now.
