### ISSUE TITLE
Site Certificate Expiration

### ISSUE THREAD

**Issue by tadman** [jspm/jspm-cli#942]
The SSL/TLS certificate just expired for http://jspm.io/

Chrome refuses to load the page. Safari is confused.

**Comment by douglasduteil** [comment]
+1

**Comment by guybedford** [comment]
Well that's not ideal.

**Comment by guybedford** [comment]
Thanks, fixed.

**Comment by douglasduteil** [comment]
Good thanks @guybedford +1
