### ISSUE TITLE
NPM Scoped Packages

### ISSUE THREAD

**Issue by WorldMaker** [jspm/jspm-cli#944]
[Cycle.js](http://cycle.js.org) has published its packages using [NPM Scoped Packages](https://docs.npmjs.com/getting-started/scoped-packages) (`@cycle/core` and `@cycle/web` being its main packages). When I try to install these with JSPM it tells me `Repo npm:@cycle/core not found`.

I currently have installed JSPM 0.15.7 and NPM 2.11.3.

**Comment by m4r71n** [comment]
Please see #899

**Comment by guybedford** [comment]
Yes scoped packages are supported in the beta.
