### ISSUE TITLE
bundling fails with template overriden via packages and map

### ISSUE THREAD

**Issue by m4r71n** [jspm/jspm-cli#945]
Hello,
I'm on jspm 0.16.0-beta.3 and systemjs 0.18.4 and I'm trying to override a template imported by another module with a customized own template. I've created a simplified demo repo: 
`git clone https://github.com/m4r71n/systemjs-override.git`
The override does work with systemjs in the browser but on `jspm bundle app/app` I get the following error:
```
jspm bundle app/app
     Building the bundle tree for app/app...

err  Only file URLs of the form file:/// allowed running in Node.
        Error loading override/override.html!file:///c:/download/2015-07-16/systemjs-override/jspm_packages/github/systemjs/plugin-text@0.0.2.js from file:///c:/download/2015-07-16/systemjs-override/app/app.js
        Error loading override/override.html!file:///c:/download/2015-07-16/systemjs-override/jspm_packages/github/systemjs/plugin-text@0.0.2.js
```
After changing the mapping to [this](https://github.com/m4r71n/systemjs-override/compare/bundle) `jspm bundle` does work and also systemjs in the browser dows work.
Should `jspm bundle` also work with the first variant of the mapping?

**Comment by guybedford** [comment]
@m4r71n thanks so much for posting! I've included a SystemJS fix for this in https://github.com/systemjs/systemjs/commit/e3eb0b33e0a4a25446254b34928a4a08fa855b7c.

**Comment by m4r71n** [comment]
@guybedford thank you very much for superfast fixing!
