### ISSUE TITLE
Case issue

### ISSUE THREAD

**Issue by emirotin** [jspm/jspm-cli#946]
I've installed `github:leongersen/noUiSlider`.

It created such file structure:
![](http://monosnap.com/image/Pp8dhv85Vkepus31b0XXetIiAAxKSF.png)

_(I wonder how jspm picks these files, because it's a mix of `distribute` and `src` files, but it appears to be just OK for my needs.)_

Now if we examine the `jspm_packages/github/leongersen/noUiSlider@8.0.2.js` file it says:

```
define(["github:leongersen/noUiSlider@8.0.2/noUiSlider"], function(main) {
  return main;
});
```

The problem is the last part of the path (`noUiSlider`) is mixed case, while the actual file name is `jspm_packages/github/leongersen/noUiSlider@8.0.2/nouislider.js`. It works on OSX (my dev machine) because the FS is case-insensitive, and then fails when I try to reproduce it on Linux server.

The package author seem to do his job right, both `package.json` and `bower.json` there properly define the `main` point as `distribute/nouislider`.

Any particular override to get is resolved now without hard-coding the version part in my code?

**Comment by OrKoN** [comment]
These files seems to be picked from the release zip archive (noUiSlider.8.0.2.zip). Also I have just tried to install this package and I get: 

```
warn Main entry point not found for github:leongersen/noUiSlider@8.0.2.
     Adjust this property in the package.json or with an override, setting "main": false if this is the intention.
```

This noUiSlider.8.0.2.zip contains no package.json. So I wonder how you installed it because it does not seem to work for me using the default install command. 

It can be installed correctly using an override:

```
jspm install github:leongersen/noUiSlider -o '{"main": "nouislider.js"}'
```
I am on jspm@0.15.7

**Comment by emirotin** [comment]
Oh it makes sense now regarding the ZIP. I saw the warning still it installed for me. Thanks for the tip, trying it now

**Comment by emirotin** [comment]
Perfect, it worked. Thanks for the help again!
