### ISSUE TITLE
Lock transpiler version

### ISSUE THREAD

**Issue by OliverJAsh** [jspm/jspm-cli#947]
Is this possible? At the moment it comes down with `jspm dl-loader`. We want the option of upgrading manually. (Developers on the team are getting annoyed that they keep finding changes to the config file.)

**Comment by desbo** [comment]
+1

We'd like to require a specific babel version in `package.json` and update it explicitly. Using `dl-loader` currently overwrites whatever version you have set to `^5.6.4`, so patch updates are automatically installed and written to the config.

**Comment by guybedford** [comment]
Going with a full lock from now on, apologies for the current patch regressions.

https://github.com/jspm/jspm-cli/commit/36abe969b2e0936680bd114f4be251e6b876b6a3

**Comment by guybedford** [comment]
Released in jspm@0.16.0-beta.6.

**Comment by OliverJAsh** [comment]
Thanks for looking into this. This doesn't lock the transpiler, it just locks SystemJS?

**Comment by guybedford** [comment]
Right, yes this was the wrong issue to mark above. In terms of locking the transpiler, the minimum version of the transpiler does need to be enforced by jspm, but then within those bounds, the exact version should be the version the user wants to install and we shouldn't force upgrades unnecessarily.

I'm thinking something along the lines of `jspm dl-loader` to retain whats in the config.js version lock (as long as it is in range) and `jspm dl-loader --latest` to do the full latest upgrade of the transpiler.

**Comment by guybedford** [comment]
Contributions welcome!

**Comment by desbo** [comment]
@guybedford could you take a look at https://github.com/jspm/jspm-cli/pull/1029? It'd solve this problem for us.

**Comment by guybedford** [comment]
@desbo thanks, set as the default behaviour in https://github.com/jspm/jspm-cli/commit/202a1cd9f178a94d7fc30f31a4e61ae93e059376.

**Comment by guybedford** [comment]
Released in 0.16.1.
