### ISSUE TITLE
Jspm install verbose mode?

### ISSUE THREAD

**Issue by togakangaroo** [jspm/jspm-cli#948]
On our build server I'm getting errors from jspm install

     17-Jul-2015 10:41:56	warn Error on lookup for github:components/jquery, retrying (1).
     17-Jul-2015 10:41:56	     fatal: failed to stat '.': No such file or directory

does jspm have a verbose more so that we can get more insight into what is going on? Can it have a verbose mode?

**Comment by guybedford** [comment]
There should be an error stack with the stat error, is there none provided?

**Comment by togakangaroo** [comment]
You mean this?

```
17-Jul-2015 10:41:56	npm ERR! MyProject@0.0.0 jspm:install: `jspm install`
17-Jul-2015 10:41:56	npm ERR! Exit status 1
17-Jul-2015 10:41:56	npm ERR!
17-Jul-2015 10:41:56	npm ERR! Failed at the MyProject@0.0.0 jspm:install script.
17-Jul-2015 10:41:56	npm ERR! This is most likely a problem with the MyProject package,
17-Jul-2015 10:41:56	npm ERR! not with npm itself.
17-Jul-2015 10:41:56	npm ERR! Tell the author that this fails on your system:
17-Jul-2015 10:41:56	npm ERR!     jspm install
17-Jul-2015 10:41:56	npm ERR! You can get their info via:
17-Jul-2015 10:41:56	npm ERR!     npm owner ls MyProject
17-Jul-2015 10:41:56	npm ERR! There is likely additional logging output above.
17-Jul-2015 10:41:56	npm ERR! System Windows_NT 6.2.9200
17-Jul-2015 10:41:56	npm ERR! command "C:\\nodejs\\\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "jspm:install"
17-Jul-2015 10:41:56	npm ERR! cwd E:\Bamboo\xml-data\build-dir\WEB-JOB1\MyProject
17-Jul-2015 10:41:56	npm ERR! node -v v0.10.23
17-Jul-2015 10:41:56	npm ERR! npm -v 1.3.17
17-Jul-2015 10:41:56	npm ERR! code ELIFECYCLE
```

Thats the only thing I see, nothing else relevant

**Comment by guybedford** [comment]
No verbose mode, this is an error bug that it isn't giving the full stack then.

Unfortunately the only thing I can think of then is manually logging all stat calls in `github.js` and `package.js` in jspm. If you find the one, please let me know so we can improve the debugging.

**Comment by togakangaroo** [comment]
`github.js`? i don't see that

**Comment by togakangaroo** [comment]
Looks like the issue was an old version of node `0.10.23`. Updating seems to fix things.
