### ISSUE TITLE
Is there any way to use defaultJSExtensions = false before 0.17.0? When will 0.17 be out?

### ISSUE THREAD

**Issue by hannahhoward** [jspm/jspm-cli#949]
Hi,

  Our current workflow is written entirely with Traceur as the only compilation tool building bundled JS files. We'd like to switch to JSPM but we dutifully added .js to all our imports when Traceur was updated to need .js on imports. Seems like SystemJS is already up to date on the spec, but JSPM doesn't yet allow using the defaultJSExtensions = false feature of SystemJS. I'm just wondering what the timeline is for 0.17.0. Is there an alpha? And easy way to fork and modify JSPM to support .js extension not being default? We'd like to get started converting!

Hannah

p.s. Thanks for all your hard work -- looks like this is the future of package management.

**Comment by guybedford** [comment]
@hannahhoward yes 0.17 is a way away yet unfortunately, but in the mean time you can use package configuration to opt-out of defaultJSExtensions:

```javascript
System.config({
  packages: {
    'js': {
      defaultExtension: false
    }
  }
});
```

Or even `defaultExtension: 'js'` will work as it won't double up extensions with the package defaultExtension option.

Thanks, glad to hear that! Feedback and contributions are always incredibly welcome.

**Comment by guybedford** [comment]
Note by `js` I mean the local application "source folder" in the repo relative to the baseURL.

**Comment by guybedford** [comment]
Just let me know if you have any further questions on this at all.
