### ISSUE TITLE
ie11 & microsoft edge

### ISSUE THREAD

**Issue by u9520107** [jspm/jspm-cli#950]
Got a wierd situation when using ie11 or microsoft Edge.
Probably not jspm's problem tho...
It's a bit complicated:
When dev tools of ie/edge is open, System.import('react-router') will end up with lots of errors. Mainly, saying process object does not have an env property where React checks if the env is in development or in production.
If the dev tools is not open, things run smoothly as predicted.

However, if the dev tools is open, but only loads React and not react-router... then the code that would've ran into issues would run perfectly fine, with env property properly populated in the process object.

On chome, everything is prefectly normal...

I am guess the issue is mainly on react-router's side.. but just to let you know.

Test env:
os: windows 10 build TH 10240
browsers: microsoft Edge, IE11, chrome
react: 0.13.3
react-router: 0.13.3

**Comment by guybedford** [comment]
Thanks, this does sound like a react-router issue. Did you manage to sort out the issue for that ok?

**Comment by u9520107** [comment]
@guybedford No... As long as Edge's dev tools are open, error's would show up.
Most errors are like:
Unable to get property 'NODE_ENV' of undefined or null reference..

which I assume that should point to process object.

**Comment by guybedford** [comment]
@u9520107 if and when you do have time one the thing to check here is if you're able to load the `process` module at all via `jspm install npm:process` and then a `import process from 'process'` checking `process.env` is defined.

**Comment by u9520107** [comment]
if process is the only module i import, then yes, process.env is defined.
Oddly this time i have a very clean install with only process, react@0.13.3,  and react-router@0.13.3.
The error no longer triggers...

However, there's different error:
```
SCRIPT438: Object doesn't support property or method 'inject'
172.16.0.171:8088 (24,3)
SCRIPT5007: Unable to get property 'instanceOf' of undefined or null reference
172.16.0.171:8088 (12,3)
SCRIPT5022: Exception thrown and not caught
172.16.0.171:8088 (10,5)
```

**Comment by guybedford** [comment]
This sounds like it is react-router specific then if process is working fine on its own. If you can determine that react-router is working otherwise fine in Edge, or that there is a specific jspm issue here, please do post back.
