### ISSUE TITLE
Removing duplication automatically

### ISSUE THREAD

**Issue by OliverJAsh** [jspm/jspm-cli#951]
I have three files which I load in the following order:

```
core -> app -> article
```

At the moment I bundle these like so, to remove duplication:

```
core.js = core
app.js = app - core
article.js = article - app - core
```

This means that I have to manually instruct my bundle task which parts of the dependency graph to dedupe. Ideally this would be automatic.

Have you thought about the ideal workflow around this?

**Comment by guybedford** [comment]
What do you mean manually instruct which parts to dedupe? In terms of working out the contents of core?

**Comment by OliverJAsh** [comment]
I know that, when `article` is loaded, many of its transitive dependencies will already be defined with thanks to `core` and `app`. Likewise, when I load `app`, I know many of its transitive dependencies will already be defined thanks to `core`.

To optimise, I have to hardcode the loading order of my files into the bundle task. I'm wondering if there is a better way.

**Comment by guybedford** [comment]
There's no way to guess unfortunately what your loading order is without having browser-level analysis feedback into the server.

One could imagine tooling in future that does such a thing tracing in the browser, and coming up with an optimum loading profile based on statistical analysis of many different page loads and different load order experiments across users.

**Comment by Munter** [comment]
I assetgraph we implemented a "shared bundles" strategy for the bundling transform, which will take all the given entry points into account and create optimal bundles based on shared and unique static requirements per entrypoint https://github.com/assetgraph/assetgraph/blob/master/lib/transforms/bundleRelations.js#L268-L270

**Comment by Munter** [comment]
Since we model the pages themselves we can reason about entry points. But a similar thing could most likely be implemented with the systemjs builder given the js entry points as a simple array

**Comment by guybedford** [comment]
Yes there was some previous work around this at https://github.com/systemjs/builder/issues/51 and https://github.com/systemjs/builder/pull/134. It was thought that this project would be better suited as a wrapper around SystemJS builder and not in core though, and there is an optimization function at https://github.com/Bubblyworld/systemjs-basic-optimize along the lines of that API. It would certainly make a great addon project.
