### ISSUE TITLE
[windows 8] Error when trying to install packages

### ISSUE THREAD

**Issue by Semigradsky** [jspm/jspm-cli#956]
I configuried github access token.

![image](https://cloud.githubusercontent.com/assets/1198848/8849866/b1bd0cda-314b-11e5-9ba9-b2dfdb961d3c.png)

but see the error

![image](https://cloud.githubusercontent.com/assets/1198848/8849869/ba583d88-314b-11e5-839e-2cf71081124a.png)

**Comment by Semigradsky** [comment]
I am trying install `immstruct` from npm:

![image](https://cloud.githubusercontent.com/assets/1198848/8849940/726668d2-314c-11e5-8c54-420e1751b6ab.png)

`jspm/nodelibs-fs` installed, but `systemjs/plugin-json` not

**Comment by kudos** [comment]
Looks like an intermittent Github failure? https://status.github.com/messages

**Comment by Semigradsky** [comment]
It is annoying :fearful:
