### ISSUE TITLE
semver @0.0.x overrides

### ISSUE THREAD

**Issue by speigg** [jspm/jspm-cli#959]
So I am trying to create an override for a package at v0.0.x. According to https://github.com/npm/node-semver#caret-ranges-123-025-004:

> When parsing caret ranges, a missing patch value desugars to the number 0, but will allow flexibility within that value, **even if the major and minor versions are both 0** [emphasis mine].
^1.2.x := >=1.2.0 <2.0.0
^0.0.x := >=0.0.0 <0.1.0
^0.0 := >=0.0.0 <0.1.0

I tried making an override with "github:owner/repo@0.0.x" and "github:owner/repo@0.0", neither of which seemed to work. Am I doing something wrong or is this not supported? It would be nice not to have to create a new override for each 0.0.x version of a package.

**Comment by guybedford** [comment]
Overrides in jspm only apply to exact versions, and then will apply for all versions that are semver compatible with that version. So if you create an override for `0.0.4` it will apply to all `0.0.x` versions where x is greater than 4.

**Comment by guybedford** [comment]
*greater than or equal to 4.

**Comment by speigg** [comment]
That would be great if I saw that behaviour, but I don't... I thought that patch versions in the 0.0.x range are not semver compatible by definition? If that's not the case, I already tried what you suggest and it doesnt seem to work (i.e, an override for 0.0.4 does not take effect with the package at 0.0.5, 0.0.6, 0.0.7, etc. or anything other than 0.0.4).

**Comment by guybedford** [comment]
@speigg right, the behaviour for overrides to apply for later versions was only added in https://github.com/jspm/jspm-cli/commit/f5b2d5b20da65f20d495b5c3401fd0e0cb66f73e, which isn't yet released on the beta track yet.

**Comment by guybedford** [comment]
Released in jspm@0.16.0-beta.6.
