### ISSUE TITLE
[BABEL] Deprecated option metadataUsedHelpers: Not required anymore as this is enabled by default

### ISSUE THREAD

**Issue by helios1138** [jspm/jspm-cli#960]
when trying to use `jspm build-sfx`

**Comment by guybedford** [comment]
Which version of Babel are you running? It's worth ensuring you're running the latest 5 as it was a bug in babel to output this.

**Comment by helios1138** [comment]
global installation, local node_modules all have `babel@5.8.9` installed. jspm_packages contains `babel-core@5.8.9` and `babel-runtime@5.8.9`

**Comment by guybedford** [comment]
Ah right thanks - this would happen only if running jspm 0.15. It is already fixed in the jspm beta.

**Comment by helios1138** [comment]
@guybedford indeed it is, thanks.
