### ISSUE TITLE
Strange behavior for jspm install

### ISSUE THREAD

**Issue by pauldijou** [jspm/jspm-cli#962]
I don't really understand why, but when not prefixing jspm, running `jspm install` will display the init prompts again and reset `package.json` file. This is kind of blocking... I might have done something wrong.

See [that record](https://asciinema.org/a/24039) for more infos. It works just fine if answering `yes` to the question about prefixing with **jspm**.

jspm version is 0.15.7

**Comment by guybedford** [comment]
Try using the jspm@beta version, I believe this is resolved there.

**Comment by pauldijou** [comment]
Works fine with beta 3 indeed. Thanks a lot.
