### ISSUE TITLE
Install Fails for npm:react-forms

### ISSUE THREAD

**Issue by sghall** [jspm/jspm-cli#963]
If you try to install react-forms from npm like so:
jspm install npm:react-forms

<img width="522" alt="screen shot 2015-07-27 at 6 36 35 pm" src="https://cloud.githubusercontent.com/assets/4615775/8921731/b7fe8736-348e-11e5-8324-8ee7c07e7d04.png">

So it says it can't find a suitable version of react-tools.  React-tools is being asked for by reactify in react-forms dependency chain, but there is a version that meets the criteria e.g.  react-tools@0.11.2

The thing is if you just do a straight npm install react-forms it works fine and it installs react-tools@0.11.2.  Any ideas?

**Comment by guybedford** [comment]
So `>= 0.9.0, < 0.12.0` is not actually a valid semver version at all. If you run it through node semver `semver.validRange('>= 0.9.0, < 0.12.0')` returns null.

This is for `npm:reactify@0.13.2`. Perhaps somehow npm is not trying to install this version?

**Comment by sghall** [comment]
npm installs npm:reactify@0.13.2 with the correct react-tools.  Just do "npm install react-forms" locally on your machine.  There's some small difference between jspm parsing and npm parsing versions.  Looks to me like it could simply be the comma in there.  Looking at semver, a comma is not ever a valid character for the version spec.  Could just remove commas (?).

**Comment by guybedford** [comment]
Strange! Ok I've included a fix in https://github.com/jspm/npm/commit/2dcd9f8cb6267df7995136cfd23d9e1b9ebf9096.

**Comment by sghall** [comment]
@guybedford Right on.  Thanks, man.  Appreciate it.
