### ISSUE TITLE
jspm clean to uninstall non-package.json top-level packages

### ISSUE THREAD

**Issue by pauldijou** [jspm/jspm-cli#964]
Not sure if that's an issue or not, but might be worth asking. What is `jspm clean` supposed to do exactly? According to CLI help, it "*Clear unused and orphaned dependencies*". As I understand it, an unused dependency is one which is locally installed but no longer present in my `package.json`. Right or wrong?

Because right now, removing a dependency from `package.json` and running `jspm clean` will not actually delete the locally installed dependency. You will also need to remove it manually from `config.js`. I was thinking that this file was more or less automatically handled by jspm.

So, is that normal to have to remove the dependency from both files in order for `jspm clean` to remove the installed package?

**Comment by guybedford** [comment]
I guess we could extend jspm clean to handle removing items from the package.json manually, sure.

**Comment by guybedford** [comment]
You can just handle this via `jspm uninstall x`. I think that behaviour works well here. If anything we could allow an argumentless `jspm uninstall` to remove anything not matching the right ranges, but I don't think it's too important for now.

**Comment by gabor-farkas** [comment]
I think a feature like this is essential for reliable and repeatable builds.
A jenkins / bamboo server could incrementally build the project (as with java maven). Without this feature we have to delete the jspm_packages folder and to a full ```jspm install``` to make sure that the build produces something that's reproducible later if needed.

**Comment by guybedford** [comment]
This has been since supported in jspm 0.17.
