### ISSUE TITLE
npm, index.js and CSS

### ISSUE THREAD

**Issue by nicklasb** [jspm/jspm-cli#967]
Hi,
I am having this problem, I am trying to use an npm-package (angular-ui-layout), and its index.js file looks like this:
```js
require("./src/ui-layout.css");
require("./src/ui-layout");
module.exports = 'ui.layout';
```
The problem is that SystemJS tries to load `ui-layout.css.js` instead of `ui-layout.css`.

I am not sure if some override is needed from my end or something, however, it would be an unlikely case that anyone would actually call a module *.css.js. 
I would think that it would be pretty safe to assume that a .css-suffix would always denote a .css-file.

**Comment by nicklasb** [comment]
So the solution is actually to import the css, first the css-plugin needs to be installed:
```bash
jspm install css
```
Then, the css is simply included in the code
```es6
import "angular-ui-layout";
import "angular-ui-layout/src/ui-layout.css!";
```

Closing.

**Comment by fyodorvi** [comment]
But how do you solve problem with index.js which continues to require .css and fails with error? Without editing the file, of course.

**Comment by guybedford** [comment]
@fyodorvi you can create submaps in overrides to alter these resolutions (`jspm install x -o "{map: {'./file.css': '@empty'}}"`, where `@empty` can be any other module as well)
