### ISSUE TITLE
Loading transpiled scss->css from a different location

### ISSUE THREAD

**Issue by breandr** [jspm/jspm-cli#968]
Not sure if this belongs here or https://github.com/systemjs/plugin-css/issues.

From `components/user/user.js` I am doing `import './user.css!'`. However, `user.css` is actually `user.scss` and gets transpiled into a build directory which relative to user.js is at `../../../../builds/debug/app/components/user/user.css`. Is there a way to tell jspm/systemjs/plugin-css to search that location for the transpiled css?

Should I just use https://github.com/theefer/plugin-sass? I see it is in alpha.

**Comment by breandr** [comment]
Well Brett, obviously if you want to change the path for which something is loaded you should add a rule to your config.js:

```
"paths": {
    "*.css": "builds/debug/*.css",
}
```

**Comment by Munter** [comment]
You could also do the sass transpilation on the server side with either an [express middleware](https://github.com/Munter/express-compile-sass) or use a [file system wrapper](https://github.com/Munter/fusile). The latter will give you the benefit of being able to access your sass build artifacts with systemjs builder and other tools that consume a file system
