### ISSUE TITLE
Feature Request: Add --no-text-format option to jspm output

### ISSUE THREAD

**Issue by jedd-ahyoung** [jspm/jspm-cli#971]
Not a huge deal, but I think it'd be nice to have a no-text-format output option for the JSPM commands. Copying the output of `jspm inspect` with its bolding and color codes to plaintext can be a bit painful.

Yeah, I'm a whiner, I know. :P

**Comment by guybedford** [comment]
jspm doesn't compose very in terms of piping with other things. Not sure we want to go down this road. Or if we do, we need to probably do a lot more than just an option like this.

For example, can't a UNIX script know that it is being used as a pipe and disable output formatting? Surely that is a standard problem here to have a different mode for piping v displaying to the user?

**Comment by theefer** [comment]
> For example, can't a UNIX script know that it is being used as a pipe and disable output formatting? Surely that is a standard problem here to have a different mode for piping v displaying to the user?

Yes it can, most other tools would disable coloured output when piped to. I forget how to check but should be fairly standard.

**Comment by guybedford** [comment]
A specific json output for outdated dependencies is tracking in https://github.com/jspm/jspm-cli/issues/471.
