### ISSUE TITLE
Help installing escope package

### ISSUE THREAD

**Issue by BuildingJarl** [jspm/jspm-cli#974]
Attempted to install [escope](https://www.npmjs.com/package/escope) 
```
jspm install escope=npm:escope
```

`import escope from 'escope';` doesn't produce any error but if I `consoel.log(escope)` escope is undefined.

**Comment by OrKoN** [comment]
@BuildingJarl The `main` property in package.json of escope is wrong.

**Comment by BuildingJarl** [comment]
@OrKoN what do you mean by wrong? Is it pointing to the wrong file?

**Comment by OrKoN** [comment]
@BuildingJarl yes, it points to lib/index.js and lib does not exist.

**Comment by BuildingJarl** [comment]
@OrKoN Yeah, thats what I though to but it does exist once you download it via jspm.

![screen shot 2015-07-31 at 14 07 05](https://cloud.githubusercontent.com/assets/5493114/9007869/730eb1e4-378d-11e5-81be-3e29a9f0e3ad.png)

**Comment by OrKoN** [comment]
Well, this mysterious lib/index.js does not export anything by default. You can get everything it exports:

```
import * as escope from 'escope';
console.log(escope);
```

But there is no default export meaning the lib does no do `exports = escope;` or `exports = { analyze: ...}`

**Comment by BuildingJarl** [comment]
@OrKoN Cool, I did not know you could do that. 

Thanks your all your help.
