### ISSUE TITLE
npm authentication problems (0.16.0-beta.3)

### ISSUE THREAD

**Issue by Mosho1** [jspm/jspm-cli#975]
I received this message when trying to install:

    Invalid authentication details. Run jspm registry config npm to reconfigure

Then I took the following steps:

1. I reset to `.npmrc` //didn't work
2. I deleted `.npmrc` //didn't work
2. I entered credentials in the jspm registry configuration //didn't work
3. I entered a token in the jspm registry configuration //worked!!

**Comment by nicklasb** [comment]
Try to update npm, that worked for me!
https://github.com/jspm/jspm-cli/issues/972

**Comment by Mosho1** [comment]
Forgot to mention, I did that too.

**Comment by guybedford** [comment]
@Mosho1 can you try adding a `console.log` statement to `jspm/node_modules/jspm-npm/lib/npm.js` just before [line 57](https://github.com/jspm/npm/blob/master/lib/npm.js#L57) with `console.log(this.auth)`? Would really appreciate help to track this down. Also ensure you're running the latest version of jspm-npm (`jspm/node_modules/jspm-npm/package.json` should show version 0.23.4.

**Comment by gunnarlium** [comment]
Have you tried running `npm login`? I had the same problem, and when I did that, a new entry was added to my `.npmrc` file, and `jspm install` works justs fine.

**Comment by Mosho1** [comment]
@guybedford I only now noticed your comment, regrettably the problem is fixed and I can't quite recall the issue or the solution. If it happens again I'll let you know.
