### ISSUE TITLE
Doubt when using jsx pragma on deku application

### ISSUE THREAD

**Issue by thr0w** [jspm/jspm-cli#976]
```javascript
var app = tree(<HelloWorld text="Hello World!" />)
``` 
being transplied to 
```javascript
app = tree(HelloWorld({ text: "Hello World!" }));
``` 
but I wanna 
```javascript
app = tree(dom(HelloWorld,{ text: "Hello World!" }));
```
===
```javascript
<div>{props.text}</div>
``` 
being transpiled to 
```javascript
React.DOM.div(null, props.text);
``` 
but I wanna 
```javascript
dom('div', {}, [props.text])
```
=====

```javascript
babelOptions = {
    "optional": [
      "reactCompat"
    ],
    "jsxPragma": "dom"
  }
}
```
===
Sample application https://github.com/thr0w/deku-sample

**Comment by guybedford** [comment]
This is the way that JSX is designed to transpile. If you're looking for custom transpilation that would require your own custom build process.

**Comment by thr0w** [comment]
Don't worry, I'm just learning jspm and deku simultaneously. I disagree that it is something with Babel because same sample works well with Browserify and Duo.
Thanks!

PS.: If you wanna you can close it, I cann't continue this experiments for some weeks.

**Comment by guybedford** [comment]
What I mean is that the transform is entirely handled by Babel, you can alter the transform options for babel via `System.babelOptions`. jspm has no further control over this process at all.
