### ISSUE TITLE
JSPM can't find traceur function when bundling from gulp.

### ISSUE THREAD

**Issue by dkushner** [jspm/jspm-cli#977]
I'm attempting to build my project from gulp using the programmatic JSPM API. This is the relevant gulp task: 

```javascript
gulp.task('build', function() {                                                                                                                      
  jspm.setPackagePath('.');                                                          
  return Promise.all([                                                               
    jspm.bundleSFX('arborjs/main', './build/index.js', { sourceMaps: true }),        
    jspm.bundleSFX('arborjs/worker', './build/worker.js', { sourceMaps: true })      
  ]);                                                                                
});   
```

During the build process, I encounter the following error:
```
ModuleEvaluationError: $traceurRuntime.hasNativeSymbol is not a function in traceur@0.0.90/src/runtime/polyfills/polyfills.js
```

I've been unable to track down the source of this error so far. I'm using JSPM v0.16.0-beta.3 and SystemJS v0.18.4. Would anyone be able to provide some insights as to where this error is coming from?

**Comment by guybedford** [comment]
It sounds like this may be due to two conflicting versions of Traceur running side-by-side. I'd suggest ensuring that the version of Traceur used by jspm (0.0.90) is the same as the version of Traceur in `jspm/node_modules/systemjs-builder/node_modules/traceur`. Let me know if that helps?

**Comment by dkushner** [comment]
It does appear to have been related to having a superfluous installation of `systemjs` or `systemjs-builder` in the local npm packages. After doing a `node uninstall systemjs systemjs-builder`, the gulp task works exactly as expected. Thanks so much for the prompt help, @guybedford and for such a stellar project!
