### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#979]
Bundling support for TypeScript is currently pending https://github.com/systemjs/builder/issues/262.

**Comment by nomack84** [comment]
@guybedford as you released 0.16 today, in which version you'll include this, 0.17?

**Comment by rofrol** [comment]
@nomack84 

It was released in systemjs-builder-0.13.2. Stable jspm-cli-0.16.11 uses even newer version 0.14.7 of systemjs-builder.

https://github.com/jspm/jspm-cli/blob/0.16.11/package.json

**Comment by guybedford** [comment]
Thanks @rofrol.
