### ISSUE TITLE
Completely remove empty folders as a result of files and ignore

### ISSUE THREAD

**Issue by lookfirst** [jspm/jspm-cli#983]
setup a "files" override and see empty directories get created

**Comment by guybedford** [comment]
@lookfirst I can't replicate this for example `jspm install jquery -o "{files:['dummy']}"`. If you can share a replication please do post back here.

**Comment by lookfirst** [comment]
@guybedford 

install angular-input-modified from github...

https://github.com/betsol/angular-input-modified

look in demo's folder.

**Comment by guybedford** [comment]
Ah right, yes empty directories are not currently removed.

**Comment by lookfirst** [comment]
@guybedford seems like you should re-open the issue then?

**Comment by guybedford** [comment]
Implemented in https://github.com/jspm/jspm-cli/commit/d3b70f4fdd195cfd003fdd4b37997b18e3edff92.

**Comment by guybedford** [comment]
Released in 0.16.3.
