### ISSUE TITLE
Bundling an external hosted dependency fails.

### ISSUE THREAD

**Issue by Zoltu** [jspm/jspm-cli#984]
config.js
```js
System.config({
	"map": {
		"stripe-checkout": "https://proxy.zoltu.io/stripe/checkout.js"
	}
});
```
source/bar.ts
```ts
import stripeCheckout from 'stripe-checkout';
export class Bar {
}
```
source/foo.ts
```ts
import { Bar } from 'bar';
export class Foo {
}
```
Bundle Command:
```cmd
> node_modules/.bin/jspm bundle 'source/**/*' + aurelia-bootstrapper - stripe-checkout
     Building the bundle tree for source/**/* + aurelia-bootstrapper - stripe-checkout...

err  Only file URLs of the form file:/// allowed running in Node.
        Error loading https://proxy.zoltu.io/stripe/checkout.js from file:///c:/Users/Micah/Source/RepoCreator-Client/dist/source/foo.ts
        Error loading https://proxy.zoltu.io/stripe/checkout.js
```

Note: I explicitly put `- stripe-checkout` to try to work around this problem.

**Comment by guybedford** [comment]
It can be worth using a config like - 

```javascript
System.config({
  meta: {
    'https://proxy.zoltu.io/stripe/checkout.js': { build: false }
  }
});
```

Here.

**Comment by Zoltu** [comment]
`build: false` doesn't appear to fully resolve the problem (though it did change the error).
```js
System.config({
  "meta": {
    "https://proxy.zoltu.io/stripe/checkout.js": {
      "format": "global",
      "build": false
    }
  }
});
```

```cmd
$ node_modules/.bin/jspm bundle source/**/* + aurelia-bootstrapper + aurelia-computed
     Building the bundle tree for source/**/* + aurelia-bootstrapper + aurelia-computed...

err  Unable to calculate canonical name to bundle https://proxy.zoltu.io/stripe/checkout.js
```
Same error if I do `- stripe-checkout`.

**Comment by guybedford** [comment]
Right, so you need to set this up as a path instead of a map config - 

```javascript
System.config({
  paths: {
    "stripe-checkout": "https://proxy.zoltu.io/stripe/checkout.js"
  }
});
```

This way it will know to call it `stripe-checkout` in the bundle.

**Comment by Zoltu** [comment]
That seems to have worked.  The final config and bundle command looks like:
```js
System.config({
  "paths": {
    "stripe-checkout": "https://proxy.zoltu.io/stripe/checkout.js"
  },
  "meta": {
    "https://proxy.zoltu.io/stripe/checkout.js": {
      "format": "global",
      "build": false
    }
  },
  "map": {
    "stripe-checkout": "https://proxy.zoltu.io/stripe/checkout.js",
  }
});
```
```cmd
node_modules/.bin/jspm bundle source/**/* + aurelia-bootstrapper + aurelia-computed
```

Is this sort of thing going to be required long-term (close the issue) or is it a temporary workaround (leave the issue open)?

If it working as intended, would it be possible to get some clarity on why it is all required?  I don't fully understand why `- stripe-checkout` didn't work nor why I had to add the `paths` item.

If it is just a bug, I'm fine with the workaround until a fix is available.

**Comment by guybedford** [comment]
Paths configs used to make builds work for proxy paths is a standard workflow and is the way things will always work.

**Comment by guybedford** [comment]
The reason is that bundles use paths as their naming system, which provides the abstraction layer between environments.

**Comment by guybedford** [comment]
Perhaps we can do something better here - posted https://github.com/systemjs/builder/issues/269.

**Comment by Rush** [comment]
Ok, so I am seemingly do the same but then in SFX bundle there is no mention in the URL .. is it a bug? I would at least expect an error.

**Comment by guybedford** [comment]
Yes it would be compatible with that feature, but you'd need to explicitly subtract the module when making the SFX bundle (`jspm bundle-sfx app - http://some/file.js --format amd` for example). Then you would need to load the SFX bundle itself into a modular environment of some sort that will support a URL load as it would effectively look like `define(['http://some/file.js'], function(dep) { ... sfx code ... })`.
