### ISSUE TITLE
Bundle doesn't bundle all dependencies.

### ISSUE THREAD

**Issue by Zoltu** [jspm/jspm-cli#985]
Repro steps:
```cmd
> mkdir test
> cd test
> npm install jspm@beta
> node_modules/.bin/jspm dl-loader --edge
# default to all prompts
> node_modules/.bin/jspm install aurelia-bootstrapper
> node_modules/.bin/jspm bundle aurelia-bootstrapper
```

If you look in `config.js`, you will sse that `aurelia-bootstrapper` depends on several packages, including `aurelia-event-aggregator` and `aurelia-history`.  If you look at the list of things that were bundled though (output of bundle command), you will not find either in the list.  Many of Aurelia's dependencies are bundled... but not all of them.

**Comment by Zoltu** [comment]
If I had to guess, JSPM bundle is not using the dependency graph from the map and instead is looking for import statements (or equivalent) in the source code.  I suspect that Aurelia is doing something fancy to load some of its dependencies, thus making it so JSPM can't find them.  If this is the case, perhaps there could be some way of telling JSPM bundle that I want the dependency tree of some package as defined by `config.js` rather than the discovered tree?

**Comment by Zoltu** [comment]
To make matters worse, you can't bundle indirect dependencies.  In this case, `jspm bundle aurelia-bootstrapper + aurelia-loader-default` will error because it can't find `aurelia-loader-default`.

You can workaround this by doing `+ github:aurelia/loader-default@0.9.0`, but this isn't maintainable because you must include the full version number when bundling a package like this.

**Comment by guybedford** [comment]
This was why Aurelia requested the wildcard bundling feature I believe.

Ideally these would be peer dependencies to bundle together.

**Comment by ahmedshuhel** [comment]
@guybedford bullseye!  
@Zoltu `aurelia router` dynamically decides what to load so we can't have a single predictable dependency graph that jspm can use for bundling every dependency. Aurelia has a [CLI](http://github.com/aurelia/cli) which uses jspm api under the hood and is aimed to ease the bundling process for aurelia application. It will also bundle templates.

**Comment by Zoltu** [comment]
I believe (correct me if I am wrong) that the Aurelia CLI has the same problem.  You have to manually list the dependency tree and you have to hard-code version numbers.  From what I can tell (based on the Readme.md), the only advantage is a config file to make reproducing the bundle a little easier.

**Comment by ahmedshuhel** [comment]
Yes, you have to list the dependencies manually. But we have added a feature(Not released yet) which enables us to avoid hard-coding the version number.
