### ISSUE TITLE
Building from a different directory.

### ISSUE THREAD

**Issue by AlicanC** [jspm/jspm-cli#986]
I have a structure like this:
```
package.json
gulpfile.js
app/
    package.json
    config.js
    main.js
    jspm_packages/
```

I use `require('jspm').Builder` in my gulpfile (which of course runs at the project root) and tries to build `app/main.js` with it.

Sadly, this is what I get:
`Error: Package.json file has not been initialized by jspm before. Run jspm init first.`

How am I supposed to build an app in another directory?

**Comment by ahmedshuhel** [comment]
Try this

```
 var jspm = require('jspm');

  jspm.setPackagePath('../package.json');
  var customCfg = {} // pass all sort of custom configuration like baseURL etc here.
  var builder = new jspm.Builder(customCfg);

```

**Comment by AlicanC** [comment]
Thanks, I could make it work with `setPackagePath()`.

One problem I stumbled upon was the "You can set baseURL once." thing. I removed `baseURL` from `config.js` and it worked properly. This wouldn't be an option if I wasn't using the default path.

**Comment by guybedford** [comment]
Note that jspm will set the baseURL for you automatically as defined in the package.json here - there shouldn't be any reason to manually alter it from that. Feel free to continue discussion here.

**Comment by fragsalat** [comment]
I've got baseURL in my package.json and I got the same problem while bundling with the aurelia-bundler. The aurelia-bundler uses the jspm_bundler and even with setting the packagePath to '../' jspm still complains about missing Package.json. Maybe I did something wrong but with the package.json in place it works.

```
{
  "jspm": {
    "directories": {
      "baseURL": "src"
    },
    .....
```

**Comment by ahmedshuhel** [comment]
@fragsalat If it's a `aurelia-bundler` related issue, please raise it [here](http://github.com/aurelia/bundler/issues) instead.
