### ISSUE TITLE
Reading transitive dependencies

### ISSUE THREAD

**Issue by OliverJAsh** [jspm/jspm-cli#988]
I have found a script that tries to access a transitive dependency:

``` js
require('virtual-dom/node_modules/x-is-array');
```

https://github.com/cyclejs/cycle-dom/blob/d8e57d1068b29c639d035ccf7ab5868df4703fbd/src/virtual-hyperscript.js#L2

Is this invalid use of modules, or should it (somehow) be supported via jspm? Perhaps the most obvious fix is for the package to depend on the module directly, but there could be a good reason for not doing that.

**Comment by lookfirst** [comment]
virtual-dom is listed as a package dependency...

https://github.com/cyclejs/cycle-dom/blob/d8e57d1068b29c639d035ccf7ab5868df4703fbd/package.json#L27

What you'll need to do if you install this project via github is setup an override in the [registry](https://github.com/jspm/registry/tree/master/package-overrides/github) that lists the dependencies for the cyclejs project. Start with the -o argument to jspm install.

**Comment by OliverJAsh** [comment]
The trouble is that jspm cannot find `node_modules/x-is-array`, because jspm is not like npm: it places files in `jspm_packages` instead of `node_modules`, for example.

**Comment by lookfirst** [comment]
Oh dear... I missed that... you're right... sigh... it appears you're going to have to fix cyclejs...

**Comment by lookfirst** [comment]
One other thought... can you just use the dist build instead?

**Comment by guybedford** [comment]
@OliverJAsh if you want to install a project from GitHub as if it is an npm project you can do `jspm install github:cyclejs/cycle-dom -o "{registry: 'npm'}"`, and that will do all the right things.

Note that installing from `npm:` directly is always preferable though.

**Comment by OliverJAsh** [comment]
AFAIK this will still have the same problem: we will fail to load `node_modules/x-is-array`.

**Comment by guybedford** [comment]
Right, ok I've created https://github.com/jspm/npm/issues/86.

**Comment by guybedford** [comment]
Also this is really override territory to fix these sorts of quirks.

`jspm install npm:... -o "{map: { 'virtual-dom/node_modules/x-is-array': 'npm:x-is-array@1.2.3' }}"`

etc
