### ISSUE TITLE
Import jQuery plugins and make them available in different modules

### ISSUE THREAD

**Issue by mvuajua** [jspm/jspm-cli#989]
I'm having trouble shimming and importing several jQuery and bootstrap plugins. What I'm trying to achieve is two things, which seem connected.

One, I'm using the bower version of bootstrap (because that's the one coming with the less files). I've managed to install them with `jspm install bower:bootstrap -o "{ shim: { 'js/*': ['jquery'] } }"`, and importing them works fine with that. However, I cannot catch any events thrown by bootstrap in any of my modules. Example code:

```javascript
import $ from 'jquery';

import 'bootstrap/js/transition';
import 'bootstrap/js/collapse';

$(function() {
    $(document).on('shown.bs.collapse', function(evt) {
        console.log(evt);
    });
});
```

The event is never caught. When adding the same listener directly before the event in question is thrown in the bootstrap code, it works just fine, same as when triggering the event manually directly after setting the listener.

Two, I'm not sure about the correct process of loading jQuery plugins. One of the plugins in question is jQuery equalHeights. The last thing I tried is 
`jspm install equalheights=bower:jquery.equalheights -o "{ shim: { '*' : {deps: ['jquery'], exports: '$'}}, dependencies: {jquery: '*'} , format: 'global', registry: 'bower'}"`
 after reading up on several issues (#40, #171, #175), and I feel I have tried about any possible shim configuration for this. I am able to load the plugin, and it initialises itself. I am also able to use it (as `$(...).equalHeights()`) in my main.js file, where I import it first, along with several other modules I wrote myself. 

I am NOT, however, able to use it in any of those modules, no matter if I import it again there or not (have tried a lot of variations of importing modules in different files in different succession, none of them worked). Example code:

main.js
```javascript
import $ from 'jquery';
import 'equalheights';
import Slider from 'Slider';

$(function() {
    // .equalHeights() is available here and tags with data-equal attributes get initialised
    console.log($.fn);
});
```

Slider.js
```javascript
import $ from 'jquery';
import 'slick-carousel';
import 'equalheights';

// .equalHeights() is NOT available here
```

Slider.js v2
```javascript
import $ from 'equalheights';
import 'slick-carousel';

// .equalHeights() will work here, breaks slick slider though
```

I feel like those two cases are connected somehow (different jQuery instances?), and would appreciate any help on how to get this working (ideally with global plugins only needing to be imported once in the main file and not in every module).

**Comment by guybedford** [comment]
Nice work on making sense of the overrides.

Yes I think this is two versions of jQuery running, and also the reason why it's not generally encouraged to use the separate bower registry as it increases the chances of this happening.

You can alter your override to the following to avoid the duplicates:

```
jspm install bower:bootstrap -o "{ shim: { 'js/*': ['jquery'] } }"
jspm install equalheights=bower:jquery.equalheights -o "{ shim: { '*' : {deps: ['jquery'], exports: '$'}}, dependencies: {jquery: 'github:components/jquery'} , format: 'global'}"
```

**Comment by guybedford** [comment]
(the reason being that `registry: 'bower'` with `dependencies: { jquery: '*' }` is exactly designed to create a dependency on `bower:jquery`.

**Comment by mvuajua** [comment]
Thanks a lot, that cleared a lot of things up!
I've ended up using the shim you posted for equalheights and installed bootstrap-less from github instead of bootstrap from bower.
