### ISSUE TITLE
Missing tag for jspm 0.15.7

### ISSUE THREAD

**Issue by JohannesHoppe** [jspm/jspm-cli#990]
Just a short note:

I think you forget to tag version 0.15.7 in git. There is no release visible on Github. But on NPM v0.15.7 was published 2 months ago.

**Comment by guybedford** [comment]
Thanks, yes, if you know the right commit I'd be happy to tag it.

**Comment by JohannesHoppe** [comment]
I would need to guess.

package.json was not touched for v0.15.7. You might have done some local changes and forget to commit/push?!

**Comment by guybedford** [comment]
Oh wait, now I remember - 0.15.7 is identical to 0.15.6 actually, it was done as a correction when the beta tag was mistakenly set as the latest, and I didn't know at the time how to reassign the `latest` tag in npm without republishing, so it was a dummy publish.

**Comment by JohannesHoppe** [comment]
You might want to add a second tag to that commit, to avoid further confusion! :+1:

**Comment by guybedford** [comment]
You can tag commits twice? Did not know that, thanks have done.
