### ISSUE TITLE
How to exclude es6 polyfills from bundle

### ISSUE THREAD

**Issue by kresli** [jspm/jspm-cli#991]
Everytime I bundle a script, bundle include polyfill for weakMap for example. This take a while when builder finish his job so my question is possible to exclude polyfills from particular bundel and keep it separated?

**Comment by guybedford** [comment]
You can create a common bundle that contains these polyfills, and then subtract that common bundle from all bundle commands.

```
  jspm bundle npm:core-js/weakmap common.js (or whatever)
  jspm bundle app.js - common.js
```

**Comment by guybedford** [comment]
Just let me know if you need any more help to get these exclusions working.

**Comment by kresli** [comment]
That's amazing! So anytime my `app.js` will request `weakmap` SystemJS will get it from `common.js` bundle? Quite smart approach then. Just for clarify, do I need to inject this `common.js` script into `app.js` separately (eg `import "./common"`) or Systemjs knew where to find it for me just by adding `app.js` into my project?

**Comment by guybedford** [comment]
@kresli if you bundle with the `-i` option when making both bundles, they'll both be loaded automatically when needed. Alternatively include a script tag loading common.js on every page after SystemJS.

**Comment by kresli** [comment]
Thank you.
