### ISSUE TITLE
Can't install anything depending on lodash

### ISSUE THREAD

**Issue by jeron-diovis** [jspm/jspm-cli#992]
```
$ jspm i npm:react-hotkeys
     Looking up npm:react-hotkeys
     Updating registry cache...
     Downloading npm:react-hotkeys@0.4.0
     Looking up npm:mousetrap
     Looking up npm:lodash
     Looking up npm:react
     Downloading npm:lodash@3.10.1

warn Error downloading npm:lodash.
ok   Installed npm:mousetrap@^1.5.2 (1.5.3)
     Looking up npm:envify

err  Error downloading npm:lodash.

warn Installation changes not saved.
```

Same for everything depending lodash latest version.
Same for direct `jspm i npm:lodash`, of course.
While `jspm i npm:lodash@3.10.0` is installed normally.
Installing through `github:...` also works. But it's not always acceptable, as files structure can differ for repo and package.
3.10.1 exists in npm. It is installed with npm pretty good. 
What the hell is going on?

**Comment by jeron-diovis** [comment]
Solved it with `jspm i npm:react-hotkeys -o '{"dependencies": { "lodash": "3.10.0", ...copypaste_all_other_dependencies_manually... }}'`
Still want to know what happens.

**Comment by guybedford** [comment]
Perhaps try `jspm cc` if this has to do with an invalid cache. The install is definitely working for me.

**Comment by jeron-diovis** [comment]
Yes, `jspm cc` helped. Thank you.
