### ISSUE TITLE
Environment variable for files cache directory

### ISSUE THREAD

**Issue by juergenzimmermann** [jspm/jspm-cli#995]
In core.js at line 256 the files cache directory is set as:
var loaderFilesCacheDir = path.join(config.HOME, '.jspm', 'loader-files');

It would be nice to have an environment variable like NPM_CONFIG_CACHE (obviously for NPM) to set the cache directory for individual purposes. Maybe JSPM_CACHE_DIR could be a suitable name.

**Comment by guybedford** [comment]
Can you explain why you would want to change this?

**Comment by juergenzimmermann** [comment]
I don't suggest to have a different default value, like e.g. %LOCALAPPDATA%\.jspm for Windows. This one is absolutely fine.

However, I'd prefer to have an additional environment variable to override the default value. Just the same reasons as in NPM, e.g. easier transfer of the whole cache when a new member joins the project team.

**Comment by guybedford** [comment]
Sure, is there any particular reason you'd want this to be an environment variable over a standard configuration option like `jspm config cacheDir /path/to/cache/dir`?

**Comment by juergenzimmermann** [comment]
A standard configuration option is also fine. Is `jspm config cacheDir /path/to/cache/dir` already available? I cannot find any docs for it.

**Comment by guybedford** [comment]
No it's not implemented, just the suggestion here.

The other thing to note is that we don't separate the concept of a cache dir in jspm from the jspm configuration file directory.

That is, it may be worth considering calling this directory `jspmGlobalDir` or something like that.

**Comment by juergenzimmermann** [comment]
`jspmGlobalDir` sounds good to me.

**Comment by guybedford** [comment]
This is `JSPM_GLOBAL_PATH` in the 0.17 beta.

**Comment by amenadiel** [comment]
@guybedford 

I've just discovered  `JSPM_GLOBAL_PATH` and it's very useful.
Turns out the CI provider I use for my company project (Codeship)  caches all content inside `${HOME}/cache`. Therefore, by declaring

```sh
export JSPM_GLOBAL_PATH="${HOME}/cache"
```
in the setup commands, installs everything in `~/cache/.jspm`, and that folder is persisted between builds.

I couldn't find a reference to this in the docs (though I know 0.17-beta isn't fully documented).

**Comment by guybedford** [comment]
@amenadiel nice, it could be worth writing something about this in the CI section at https://github.com/jspm/jspm-cli/blob/master/docs/registries.md.

**Comment by JoshMcCullough** [comment]
To confirm, @guybedford, there is no way in v0.16.47, to set JSPM's cache location for the current terminal session (via command line or environment variable).

E.g. in the case where multiple build agents are running on the same VM, having each agent use its own cache location so as not to run into file locks, etc. when running `jspm i`. Is this possible in this version of JSPM?
