### ISSUE TITLE
Error loading a script with a # in the file path.

### ISSUE THREAD

**Issue by cgoboncan-ebsi** [jspm/jspm-cli#996]
I get a 404 with this message:
```
Unhandled promise rejection Error: XHR error (404 Not Found) loading http://localhost:9000/jspm_packages/npm/es5-ext@0.10.7/string/contains/index.js
	Error loading http://localhost:9000/jspm_packages/npm/es5-ext@0.10.7/string/contains/index.js as "./contains/index" from http://localhost:9000/jspm_packages/npm/es5-ext@0.10.7/string/#/contains.js
```

This file is being required in from d@0.1.1's index.js line 7
```
  , contains      = require('es5-ext/string/#/contains')
```

I have to modify the require statement in es5-ext@0.10.7/string/contains.js from 
```
module.exports = require('./contains/index');
```
to
```
module.exports = require('./#/contains');
```
to get it to load in the browser.

Running jspm 0.16.0-beta.3, windows 7

**Comment by guybedford** [comment]
Thanks I've posted a fix to SystemJS at https://github.com/systemjs/systemjs/issues/621.

**Comment by cgoboncan-ebsi** [comment]
I've upgraded to jspm 0.16.0-beta.7 and i'm still having issues with loading this file.

The browser is looking for `'./#/contains'` at `http://localhost:9000/jspm_packages/npm/es5-ext@0.10.7/string/%23/%23/contains.js` when it should be at `http://localhost:9000/jspm_packages/npm/es5-ext@0.10.7/string/%23/contains.js`.

Does jspm add the 'contains.js' file in the # folder? If so, the the module export should probably be `'./contains/index'` instead of `'./#/contains'`.

**Comment by guybedford** [comment]
@cgoboncan-ebsi which import is giving you this? If I do `System.import('es5-ext')` it is definitely working fine for me here.

**Comment by cgoboncan-ebsi** [comment]
@guybedford I'm not importing this directly. I think it's being imported via d@0.1.1 via EventEmitter@0.3.3.

EventEmitter@0.3.3/index.js line 4
```
var d = require('d')
```

d@0.1.1/index.js line 7
```, contains = require('es5-ext/string/#/contains')
```

es5-ext@0.10.7/string/#/contains.js line 2
```
module.exports = require('./#/contains');
```

est5-ext@0.10.7/string/#/#/contains.js
```
Cannot GET /jspm_packages/npm/es5-ext@0.10.7/string/%23/%23/contains.js
```

Is es5-ext@0.10.7/string/#/contains.js generated by jspm?

**Comment by guybedford** [comment]
@cgoboncan-ebsi in my copy the contents of `string/#/contains.js` are definitely:

```javascript
/* */ 
module.exports = require('./contains/index');
```

Perhaps try `jspm install es5-ext -f` to clear any cache issues and ensure you're running jspm 0.16 beta.

Alternatively this may be a Windows bug if you're running on Windows?

**Comment by cgoboncan-ebsi** [comment]
I'm running jspm 0.16.0-beta.7. Just ran `jspm install npm:es5-ext -f` and now i have the right version of `stirng/#/contains.js`. Thanks for the help!
