### ISSUE TITLE
Installation of Font-Awesome via github fails

### ISSUE THREAD

**Issue by juergenzimmermann** [jspm/jspm-cli#997]
When I do `jspm install fontawesome=github:FontAwesome/Font-Awesome`
then I get this output:
```
     Looking up github:FontAwesome/Font-Awesome
err  Repo github:FontAwesome/Font-Awesome not found!
```
The Git repo is at https://github.com/FortAwesome/Font-Awesome

**Comment by OrKoN** [comment]
@juergenzimmermann Hey, it seems that you have a typo here: FontAwesome/Font-Awesome -> **Fort**Awesome/Font-Awesome. Try installing `jspm install fontawesome=github:FortAwesome/Font-Awesome`

**Comment by juergenzimmermann** [comment]
Thank you, that's it.
