### ISSUE TITLE
Allow bundling of indirect dependencies.

### ISSUE THREAD

**Issue by Zoltu** [jspm/jspm-cli#998]
This is a feature request to work around the symptoms described here: https://github.com/jspm/jspm-cli/issues/985

Currently, if you do `jspm install aurelia-bootstrapper`, JSPM will install `aurelia-bootstrapper` as a direct dependency and several other libraries as indirect dependencies.  When you go to bundle with `jspm bundle aurelia-bootstrapper` not all of the dependencies are picked up because not all of them are statically imported.

Unfortunately, you cannot just do `jspm bundle aurelia-bootstrapper + aurelia-loader-default` because `aurelia-loader-default` is an indirect dependency.  This fetaure request is to make the above work.

Currently, the user can do `jspm bundle aurelia-bootstrapper + github:aurelia/loader-default@0.9.0` but this hard-codes a version into the bundle script (likely leading to bundle failures on `jspm update`) and it requires the user manually locate the mapping in the generated `config.js` file.

The generated `config.js` contains enough information to make this feature work.  In particular, there is a mapping of `aurelia-loader-default` to `github:aurelia/loader-default@0.9.0`, it is just hidden instide the `github:aurelia/bootstrapper@0.14.0` map.  If, during bundling, JSPM were to flatten the map and use the flattened map for bundling lookups then the user would be able to bundle `aurelia-loader-default` without having to directly install it with `jspm install aurelia-loader-default`.

**Comment by guybedford** [comment]
I think the `peerDependencies` feature would provide this feature for you here.

Basically if `aurelia-loader-default` was a peer dependency, that would instead add it to the global namespace so that it would be possible to do `jspm bundle aurelia-bootstrapper + aurelia-loader-default` as you're asking.

We're aiming to being work on this soon - being tracked in https://github.com/jspm/jspm-cli/issues/490. Let me know if that covers this for you.

**Comment by Zoltu** [comment]
I believe this will resolve my issue, as it sounds like the Aurelia team is on-board with moving to peer dependencies.

As a library author, what is the strategy for deciding whether you have a dependency or a peer dependency?

**Comment by guybedford** [comment]
Great. peerDependencies are dependencies that contain _mutability_ or _state_, using plugin patterns.

**Comment by guybedford** [comment]
Let's continue to track at the peerDependencies issue then.
