### ISSUE TITLE
Traceur after 0.0.88 dl-loader update export default function breaks

### ISSUE THREAD

**Issue by origin1tech** [jspm/jspm-cli#999]
Noticed after updating dl-loader that export default for class/function broke in a module.

What's odd is if I set the full path to the module rather than:

    import myModule from 'vendor/module'

if I instead import as the following:

    import myModule from 'jspm_packages/github/vendor/module@master/to/main'

then it imports just fine. 

The issues is the same whether using traceur or babel as the transpiler. 

If anyone has any ideas I'm all ears as this one is a bit tough to replicate may have to dig into this myself so if anyone has any notion please share!!

**Comment by guybedford** [comment]
This looks like it is the same as https://github.com/jspm/jspm-cli/issues/994. Working to get the release out soon.

**Comment by origin1tech** [comment]
thx.
